### ISSUE TITLE
rgdal issues on travis

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#1002]
@rsbivand see https://travis-ci.org/r-spatial/sf/builds/505302909 - any idea? The rgdal version reported by configure (1.4-1) seems to match the code of the 1.4-2 CRAN release.

**Comment by rsbivand** [comment]
Yes, I forgot to touch configure.ac; autoconf, so 1.4-2 reports 1.4-1. Can travis pull from R-Forge, 1.4-3 there should resolve the issue (wrong header order in a file that does nothing >= PROJ 4.9.3 if the failure is in the rgdal install)?

**Comment by edzer** [comment]
Thanks!
