### ISSUE TITLE
st_crop 'geos_op2_geom("intersection", x, y)' error, intelligent bbox improvement?

### ISSUE THREAD

**Issue by SimonDedman** [r-spatial/sf#1006]
Hi all,

st_crop documentation regarding the `y` parameter, and general R use suggests that `st_crop(big_object, small_object)` will create the bounding box from small_object if not given explicitly, but it doesn't, leading to:

> Error in geos_op2_geom("intersection", x, y) : st_crs(x) == st_crs(y) is not TRUE

Further, `st_crop(big_object, bbox(small_object))` also doesn't work, meaning the safest way seems to be to specify each of `xmin xmax ymin ymax` separately in the call. Not the end of the world, but is there any chance this could be improved to convert `y` objects into `bbox `objects into `xmin xmax ymin ymax`?

I'm new to sf & have been hugely impressed with it. I think this issue stuck out for me because it was the first time the package didn't behave as I'd intuitively expect it to!

Cheers

**Comment by edzer** [comment]
The error message says that `big_object` and `small_object` do not have identical CRS. They should. Make sure this is the case (by setting, or transforming) and try again.

**Comment by SimonDedman** [comment]
Interesting... `bbox(small_object)` gives the minmaxes which can then be inputted to `st_crop()` directly for a successful result... but this circumvents the CRS check. Does that therefore mean this approach risks dodging a safety feature in the form of that warning, potentially creating a output that looks like it works but is actually wrong? Or should cropping with minmaxes only work with big_object-crs-compatible minmax values, and fail otherwise?

Thanks

**Comment by edzer** [comment]
You can pass `xmax` etc parameters only when they are _named_, or you pass an object `y` that has a bounding box or _is_ a bounding box. Bounding box objects carry CRS from the object they come from.

**Comment by SimonDedman** [comment]
Gotcha. Sorry if I'm not being clear; what I'm getting at is: if I take the `minmax `parameters from a bounding box object created from an object with a different crs, the crop seems to work. Thus:

1. If circumventing `y` and [bbox ](url)by entering `minmax`'s directly can result in a cropped object which is 'wrong' based on CRS technicalities, then I shouldn't do it. But:

2. If circumventing `y` and `bbox `by entering `minmax`'s directly can NEVER result in a cropped object which is 'wrong' based on CRS technicalities (i.e. it either works properly or it fails), then is there any chance `st_crop` could be modified so that `st_crop(big_object, small_object)` could create the bounding box from `small_object `in cases when `small_object `is not a `bbox `object?

Thanks again

**Comment by edzer** [comment]
The `xmin` etc parameters should of course be in the CRS of `x`. Your 2. should work as you say. If you have problems with one of them, please illustrate with a reproducible example.
