### ISSUE TITLE
Package or Namespace load failes

### ISSUE THREAD

**Issue by danielw2904** [r-spatial/sf#1007]
I get the following error when trying to load ```sf````

```
> library(sf)
Error: package or namespace load failed for ‘sf’:
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found
```

I am on ubuntu 18.04 with R version 

```
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

I've installed the dependencies according to the readme including the PPA.

Thanks!

**Comment by edzer** [comment]
You need to update dplyr to version >= 0.8-0, and then it will work.

**Comment by danielw2904** [comment]
Thanks that worked!

**Comment by YsoSirius** [comment]
Travis CI is giving me the same error for my package, although I am not using dplyr in it, so it is not listed under the Imports/Suggests. Do I have to include them there?

Interestingly, checking the package (with --as-cran) gives me no errors/warnings/notes

**Comment by edzer** [comment]
Where is the `DESCRIPTION`? Maybe you import a package that imports `dplyr`?

**Comment by YsoSirius** [comment]
it's this one: https://github.com/YsoSirius/windfarmGA/blob/master/DESCRIPTION

**Comment by edzer** [comment]
Many import dependencies: quite likely one of them imports dplyr, and that would be enough.

**Comment by YsoSirius** [comment]
I know, I originaly also had `dplyr` in it and I'm trying to remove dependencies now. 

I just didnt know how to avoid the travis error without importing dplyr. I put `dplyr` under Suggests now and thats giving me no error.
