### ISSUE TITLE
Source static installs coming?

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#1008]
Blog by Tomas Kalibera:

https://developer.r-project.org/Blog/public/2019/02/14/staged-install/index.html

**Comment by rsbivand** [comment]
With R-devel and R CMD INSTALL --staged-install:

```
...
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (rgdal)
```
so OK I think.

**Comment by edzer** [comment]
That is a long blog post. Did you try staged installing `sf`?

**Comment by rsbivand** [comment]
Yes, with current master HEAD:

```
...
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
```
so also looks OK. There are extra bits about path setting in packages too (haven't downloaded his package). If Tomas is at useR! and not presenting in the programme, we could ask him to say something short sometime? Monday? (@kalibera)

**Comment by edzer** [comment]
Thanks! Can be closed?
