### ISSUE TITLE
cannot create a crs from an object of class CRS

### ISSUE THREAD

**Issue by MichaelChirico** [r-spatial/sf#1012]
I think this error could be a bit confusing:

```
sf::st_as_sfc('POLYGON((0 0, 0 1, 1 1, 1 0, 0 0))', crs = sp::CRS('+init=epsg:4326'))
```

> Error: cannot create a crs from an object of class CRS
> In addition: Warning messages:
> 1: In is.na(crs) : is.na() applied to non-(list or vector) of type 'S4'
> 2: In is.na(x) : is.na() applied to non-(list or vector) of type 'S4'

Obviously the fix is to just use the input to `CRS` instead, but there are functions that return `CRS` objects, e.g. `OpenStreetMap::osm()`.

Perhaps it's worthwhile to just add a method to do `slot(x, 'projargs')` for `CRS` input?

**Comment by edzer** [comment]
Good idea; makes sense. We still get an `is.na()` warning, but that needs to be addressed in `sp`.
