### ISSUE TITLE
Installation failure on Centos

### ISSUE THREAD

**Issue by BenAbabaei** [r-spatial/sf#1018]
install_github("r-spatial/sf")
Downloading GitHub repo r-spatial/sf@master
from URL https://api.github.com/repos/r-spatial/sf/zipball/master
Installing sf
'/sw/B18a/R/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/gpfs1/scratch/30days/uqbababa/RtmpQeDgXO/devtoolsbdd45da1ca6/r-spatial-sf-f9d0c14'  \
  --library='/gpfs1/homes/uqbababa/.R/library' --install-tests

* installing *source* package ‘sf’ ...
configure: CC: icc -std=gnu99
configure: CXX: icpc -std=gnu++11
checking for gdal-config... /opt/gdal/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.2.0
checking GDAL version >= 2.0.1... yes
checking for gcc... icc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether icc -std=gnu99 accepts -g... yes
checking for icc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... icc -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /opt/gdal/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
checking proj_api.h usability... no
checking proj_api.h presence... no
checking for proj_api.h... no
configure: error: proj_api.h not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/gpfs1/homes/uqbababa/.R/library/sf’
Installation failed: Command failed (1)

**Comment by edzer** [comment]
What did you do to install `PROJ` before installing `sf`?

**Comment by BenAbabaei** [comment]
I am working on a computer cluster on which proj is loaded prior to loading R as a module. I hope this answers your question. 

module load singularity
module load proj
module load gdal
module load R

**Comment by edzer** [comment]
I am not familiar with your cluster architecture, but for _compiling_ sf (which is what you are trying to do) you need to have proj-devel , or something similar, installed / loaded.

**Comment by BenAbabaei** [comment]
I am sure it has been installed on the cluster as I was using the 'sf' package with the previous version of R. Whatever has happened, it must have something to do with the compatibility of 'sf' with R3.5.0.

**Comment by edzer** [comment]
Your configure script breaks on `proj_api.h` not being found. If `sf` could be compiled with the previous version of R, that means that back then `proj_api.h` could be found. Updating R doesn't change anything in whether and where `proj_api.h` can be found; my guess is that you did something (used some configure flag?) earlier to direct `sf` install where it should look for `proj_api.h`, and you didn't do that this time.

**Comment by BenAbabaei** [comment]
Our admin suggested updating INCLUDE_PATH and it worked. No idea what it had to do with 'sf' package!

```
export INCLUDE_PATH=/usr/include/sys/stat.h:/usr/include/sys/signal.h

```
