### ISSUE TITLE
transforming between different WGS84/ITRF/NAD83 realizations

### ISSUE THREAD

**Issue by CCheCastaldo** [r-spatial/sf#1019]
Hi, I was wondering if it was possible to use st_transform to transform coordinates from one realization or epoch of WGS84/ITRF/NAD83 to another? For example, I have some shape files exported from pathfinder office in the year 2000 whose datum is NAD83(CORS96) and I wish to transform it to WGS84 or perhaps a more recent WGS84 realization to overlay on some google map imagery. 

When I transform coordinates from NAD83(CORS96) (epsg:6783) to WGS84 (epsg:4326), the coordinates do not change, which does not seem correct based on the fact that these datums differ by a [couple of meters in the pacific northwest](http://trl.trimble.com/docushare/dsweb/Get/Document-170369/SprtNote_GPSPathfinder_ResolvingNAD83DatumTransformationIssue_0611.pdf). I think the reason the shift is not occurring is that gdal's gdaltransform might have a zero shift transformation between these datums. Based on the documentation for st_transform, I tried using st_transform_proj from the lwgeom package but there was still no shift. Are these types of transformations currently not possible with the sf package/gdal, and if so, do you know of another way to do this in R? 

Thanks for any advice you have. I apologize in advance for any potential stupidity in this post.

Chris

```R
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.7-3

loaded via a namespace (and not attached):
 [1] compiler_3.5.3 magrittr_1.5   class_7.3-15   DBI_1.0.0      tools_3.5.3    units_0.6-2    yaml_2.2.0     Rcpp_1.0.1    
 [9] grid_3.5.3     e1071_1.7-1    classInt_0.3-1


> library(sf)
Linking to GEOS 3.7.1, GDAL 2.4.0, PROJ 5.2.0
# location in degrees of rebar marker at trailhead parking lot in NAD83(CORS96)
> lat <- 46.28654926491890364559
> lon <- -122.2719335437305119285
> rebar_sfc_6783 <- st_sfc(st_point(c(lon, lat)), crs = 6783)
> rebar_sfc_4326 <- rebar_sfc_6783 %>% st_transform(crs = 4326)
# coordinates identical after transformation when there should be a small shift
> print(st_coordinates(rebar_sfc_6783), digits = 20)
                       X                     Y
1 -122.27193354373051193 46.286549264918903646
> print(st_coordinates(rebar_sfc_4326), digits = 20)
                       X                     Y
1 -122.27193354373051193 46.286549264918903646

```

And from the command line using gdaltransform directly shows no shift as well.

```bash
| => gdaltransform -s_srs EPSG:6783 -t_srs EPSG:4326
-122.2719335437305119285, 46.28654926491890364559
-122.271933543731 46.2865492649189 0
```

**Comment by edzer** [comment]
`sf` has no coordinate transformations of its own: `st_transform` uses the GDAL routines for this, `lwgeom::st_transform_proj` uses `PROJ` directly, not going through GDAL (there are a few corner case conversions, like wintri, that only work this way, and not through GDAL). 

AFAIK work in PROJ 6 or 7 is underway for things like time-dependent datum shifts; when things are released and documented they will become available in sf in due course.

**Comment by CCheCastaldo** [comment]
Edzer, thanks for confirming the current limitations with GDAL. Being able to do time-dependent datum shifts would be very useful, especially for repositioning older WGS84 data to account for tectonic plate movements, or transforming GPS data exported from pathfinder office software. It is common for data from POS to accidentally be in the NAD83 realization used by the reference station at the time they were differentially corrected instead of WGS84, and currently there is no easy way to back-transform from NAD83xxxx to WGS84xxxx. I am very much looking forward to having this capability in `sf`.

**Comment by edzer** [comment]
OK; closing here now because this is not an open sf issue. I'll add a note here if I see anything happening in PROJ that can be used through `sf`, or that needs action to get there.
