### ISSUE TITLE
Install issue on RHEL7

### ISSUE THREAD

**Issue by victorhdc** [r-spatial/sf#1022]
The following error occurs when trying to install the sf package in Oracle Linux 7 (based on RHEL7) :
sh: line 1: 31803 Segmentation fault      (core dumped) '/usr/lib64/R/bin/R' --no-save --slave 2>&1 < '/tmp/RtmpPgbsqb/file7a152bf3a26a'
 *** caught segfault ***
address 0x8, cause 'memory not mapped'

The install command was:
install.packages("sf", 
                 type = "source",
                 configure.args = paste0("--with-gdal-config=","/usr/local/bin/gdal-config"),
                 repos = "http://cran.rstudio.com"
                 ,verbose=T
                 ,keep_outputs = T)
We installed GDAL (2.4.1) from source because binaries are not available for versions above 1.14 on RHEL.
Both PROJ (4.8.0-4) and GEOS (3.4.2-2) were installed from epel.

**Comment by edzer** [comment]
Did you check [this](https://github.com/r-spatial/sf#multiple-gdal-geos-andor-proj-versions-on-your-system)?

**Comment by victorhdc** [comment]
Thanks Edzer, I already uninstalled previous versions of gdal.
The error is also different:
undefined symbol: GEOSFrechetDistanceDensify_r is not on my stacktrace

I manually deleted libgeos files from other locations and the error is:
checking GDAL: checking whether PROJ is available fur running:... ./configure: line 3606: 16834 Segmentation fault      (core dumped) ./gdal_proj
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?

Am i missing something?

**Comment by edzer** [comment]
The GEOS error suggests that configure detected GEOS 3.7.0, but that this was not available at link time - again multiple versions and wrong setup; the following GDAL error a broken setup. I'm not familiar with RHEL-based distros. Reboot?

**Comment by victorhdc** [comment]
You were right, tried with a fresh install and this comment: https://github.com/r-spatial/sf/issues/844#issuecomment-464322371

**Comment by kartechbabu** [comment]
In Mac OS environment (Catalina 10.15.4) with Anaconda I got this error when I first tried to install the SF package using "install.packages".

I was able to resolve it by directly installing packages using conda command

`— create a new R environment “r_gis”
environment location: /Users/kbnk/opt/anaconda3/envs/r_gis
conda create -n r_gis --channel conda-forge  python=3.7 gdal=3.0.4 libgdal=3.0.4  r-rgdal=1.4_8  r-gdalutils=2.0.3.2 r-sf udunits2 rstudio
activate r_gis
`
