### ISSUE TITLE
osx installation issue on 10.14.4 

### ISSUE THREAD

**Issue by geoHeil** [r-spatial/sf#1023]
Trying to install on OSX:
`install.packages("sf")`
it fails with:
`configure: error: proj_api.h not found in standard or given locations.`

> NOTE: installing rgdal works fine though, when installed alone. It only fails in the configure step of sf.

full logs are at https://gist.github.com/geoHeil/e684c14a7fe5731738beaa7084b2d3af

R, proj, gdal were all installed via homebrew.
proj6 is installed via brew.

```
➜  include ls /usr/local/include | grep proj
epsg_proj.inc
org_proj4_PJ.h
proj
proj.h
proj_api.h
proj_constants.h
proj_experimental.h
proj_symbol_rename.h
```

**Comment by geoHeil** [comment]
Installing an older version fixed the issue:
For compilers to find osgeo-proj@5 you may need to set:
  export LDFLAGS="-L/usr/local/opt/osgeo-proj@5/lib"
  export CPPFLAGS="-I/usr/local/opt/osgeo-proj@5/include"

For pkg-config to find osgeo-proj@5 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/osgeo-proj@5/lib/pkgconfig"

**Comment by ricardoekm** [comment]
Hi @geoHeil,
I'm facing the same issue, which older version solved the issue?

Was it an older sf version?

Thanks.

**Comment by ricardoekm** [comment]
Solved the issue. For future reference I had to install pkg-config:
brew install pkg-config
