### ISSUE TITLE
st_difference fails for sfc with 0 features

### ISSUE THREAD

**Issue by sericson0** [r-spatial/sf#1024]
I need to take the difference between a sfc (geometry set) and another which is the intersection of two polygons and am getting an error when the intersection does not have any shapes in common. I am not sure if this is a bug or simply my misunderstanding of how best to use the package, but I figured I would point it out. 
As a simple example:
```r
shape1 <-st_sfc(st_polygon(list(rbind(c(0,0), c(1,0), c(3,2), c(2,4), c(1,4), c(0,0)))))
shape2 <- st_sfc(st_polygon()) 
shape3 <- st_sfc(st_polygon())

st_difference(shape1, shape2) 
#works as expected, returning shape1 as shape2 has no elements

shape4 = st_intersection(shape2, shape3) 
#Because no elements in common, shape4 has 0 features
st_difference(shape1, shape4)  
#returns a zero feature geometry when would expect to return shape1 
```
At least to me it seems the output should be the same as when they are polygons and not geometry sets 
```r
shape1 <- st_polygon(list(rbind(c(0,0), c(1,0), c(3,2), c(2,4), c(1,4), c(0,0))))
shape2 <- st_polygon() 
shape3 <- st_polygon()

st_difference(shape1, shape2) 
#works as expected, returning shape1 as shape2 has no elements

shape4 = st_intersection(shape2, shape3) 
st_difference(shape1, shape4)  
#returns shape1 as expected  
```

It seems natural that st_difference(x,y) where y is a geometry set with zero features should return x, or at least it could be nice if there was an option to allow this to be the case

**Comment by edzer** [comment]
thanks, should work now!
