### ISSUE TITLE
Problem with fields

### ISSUE THREAD

**Issue by daviddonaire** [r-spatial/sf#1028]
Hi,

I'm trying to read a GeoJSON file (see below example), but for the description field the st_read function only pick up the first part of the string (i.e. "2019-04-05 08:43:00"). How can I pick up the full string?

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "description": "2019-04-05 08:43:00; 2019-04-05 09:16:00\n",
        "name": "Bike"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            144.972208,
            -37.809801
          ],
          [
            144.97292,
            -37.811334
          ],
          [
            144.965539,
            -37.813587
        ]
      }
    }
  ]
}

**Comment by edzer** [comment]
You forgot a `]` near the end. The following works:
```r
library(sf)
st_read(
'{
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": {
"description": "2019-04-05 08:43:00; 2019-04-05 09:16:00\n",
"name": "Bike"
},
"geometry": {
"type": "LineString",
"coordinates": [
[
144.972208,
-37.809801
],
[
144.97292,
-37.811334
],
[
144.965539,
-37.813587
]
]
}
}
]
}')
```

**Comment by daviddonaire** [comment]
Sorry for the error, but despite this correction st_read still takes only one of the two dates from the description field.

Simple feature collection with 1 feature and 2 fields
geometry type:  LINESTRING
dimension:      XY
bbox:           xmin: 144.9655 ymin: -37.81359 xmax: 144.9729 ymax: -37.8098
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
          description name                       geometry
1 2019-04-05 08:43:00 Bike LINESTRING (144.9722 -37.80...

**Comment by edzer** [comment]
I'm afraid that's internal to GDAL; GDAL lets you read things and list-of-things (like list of integers, list of strings), but not list of dates, AFAICT. See e.g. [here](https://www.gdal.org/classOGRFeature_1_1FieldValue.html#a5b39924e0b43fad413704851908dd195). 

Maybe you can make the JSON such that GDAL reads it in as text rather than `POSIXct`, in which case you'd have to do the text parsing in R.

**Comment by daviddonaire** [comment]
Thank you. I added another feature where the description field was character and then st_read worked well.
