### ISSUE TITLE
st_voronoi resulting object cannot be converted to other sf objects

### ISSUE THREAD

**Issue by SjoerdBraaksma** [r-spatial/sf#1030]
by using st_voronoi(do.call(c, sfc_object))

The resulting object is of class:  "XY"/"GEOMETRYCOLLECTION"/"sfg"

when I try to recreate this class:

`poly1<- st_polygon(list(matrix(c(33951.62, 417105.2, 33951.62, 478764.3, 38535.53, 478764.3, 67755.92, 444999, 
                                 67061.27, 444184.4, 66257.33, 443325.5, 33951.62, 417105.2),
                                   ncol = 2, byrow = T)))`

`poly2<- st_polygon(list(matrix(c(66257.33, 443325.5, 67061.27, 444184.4, 67643.44, 444555.9, 67702.53, 444267.8, 66257.33, 443325.5),
                               ncol = 2, byrow = T)))`

`geom_coll<- st_geometrycollection(poly1, poly2)`

I get the error message

`Error in vapply(x, class, rep("", 3)) : values must be length 3,
 but FUN(X[[1]]) result is length 1`

this is the exact same error message I get when I try to convert the geometry collection to an sfc/multipoint object. 

As I can't recreate the object, here is a picture of it's structure:
[link](https://imgur.com/SpB34vS)

Anyone got any idea what I am doing wrong? help would be very much appreciated!

**Comment by edzer** [comment]
Try
```r
geom_coll<- st_geometrycollection(list(poly1, poly2))
```

**Comment by SjoerdBraaksma** [comment]
This works! Thank you edzer!

How can I best transform this resulting object back to an sf object?

and second question: is there a way for st_voronoi to automatically let each element in the output inherit the id/rownumber of the point it was made from?

**Comment by edzer** [comment]
I think that
```r
pols[unlist(st_intersects(pts, pols))]
```
returns the polygons (`pols`) in the order of the points (`pts`). Here, `pols` is an `sfc` object returned from 
```r
pols = st_collection_extract(st_voronoi(do.call(c, st_geometry(pts))))
```

**Comment by SjoerdBraaksma** [comment]
Awesome, it works! 

Thank you Edzer!
