### ISSUE TITLE
Allow for creating sf objects with missing coordinates...

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/sf#1034]
... right now creating sf objects with missing coordinates is impossible:

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.3.2, PROJ 4.9.3
df = data.frame(X = c(1, NA),
           Y = c(3, NA))
st_as_sf(df, coords = c("X", "Y"))
#> Error in st_as_sf.data.frame(df, coords = c("X", "Y")): missing values in coordinates not allowed
```

<sup>Created on 2019-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment]
That is intentional. Why would you want to do that, and how would you expect it to behave?

**Comment by Nowosad** [comment]
Some **sf** functions support missing coordinates, e.g., it is possible to create a sf object with an empty point. Allowing for creating sf objects with missing coordinates could be useful when only a part of a dataset has coordinates, but you do not want to lose the rest (e.g., because of some other variables).

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.3.2, PROJ 4.9.3
empty_point = st_point()
st_sf(data.frame = 1, geom = st_sfc(empty_point))
#> Simple feature collection with 1 feature and 1 field (with 1 geometry empty)
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
#> epsg (SRID):    NA
#> proj4string:    NA
#>   data.frame        geom
#> 1          1 POINT EMPTY
```

<sup>Created on 2019-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment]
For those cases, you could abuse empty geometries. (I think that strictly their interpretation is "there is no geometry for which...", which is different from missingness which would be "there is a geometry, but we don't know its properties".)

That `st_point()` is represented as a length 2 numeric with `NA` values is somewhat arbitrary, and the only exception. The problem is that the simple feature standard does not describe what the WKB representation of the `POINT EMPTY` is. Even good OGC standards are not perfect.

**Comment by etiennebr** [comment]
I agree that this can be confusing and annoying when `sf`refuses to perform an operation because a geometry is missing. I think we shouldn't be too strict about it when it's not likely to create problems (i.e. internally). 

We sometimes treat `NA` and `empty` interchangeably. (I'm not sure if this is right, but it's convenient). 
``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0

tibble(a = 1:2, WKT = c("POINT(1 2)", NA)) %>% write_csv("pts.csv")
x <- st_read("pts.csv")
#> Reading layer `pts' from data source `/tmp/RtmpwjdF3O/reprex4ff34c21228/pts.csv' using driver `CSV'
#> replacing null geometries with empty geometries
#> Simple feature collection with 2 features and 2 fields (with 1 geometry empty)
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 2 xmax: 1 ymax: 2
#> epsg (SRID):    NA
#> proj4string:    NA
```
Bringing your attention to **`replacing null geometries with empty geometries`**, second line after reading the csv. Is it from GDAL?
``` r
x
#> Simple feature collection with 2 features and 2 fields (with 1 geometry empty)
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 2 xmax: 1 ymax: 2
#> epsg (SRID):    NA
#> proj4string:    NA
#>   a        WKT    geometry
#> 1 1 POINT(1 2) POINT (1 2)
#> 2 2         NA POINT EMPTY
```

Also postgis does keep null geometries represented as null and equivalent to empty geometries.
``` sql
select 'POINT(1 2)'::geometry union select null as geometry;
                  geometry
--------------------------------------------
 0101000000000000000000F03F0000000000000040
 ¤
```

it doesn't even bother to mention it on union (not sure this is desirable, I think I'd warn on `NA`, but not on `empty`.)
``` sql
with 
  a as (select 'POINT(1 2)'::geometry UNION select Null as geometry) 
select st_astext(st_union(geometry)) as wkt from a;
    wkt     
------------
 POINT(1 2)
```

**Comment by edzer** [comment]
The message **replacing null geometries with empty geometries** comes from [here](https://github.com/r-spatial/sf/blob/master/src/gdal_read.cpp#L434), i.e. from sf: OGR (GDAL) allows for `NULL` geometries, but R (sf) doesn't. I also think that the sfa standard doesn't, but I might be wrong.

**Comment by Nowosad** [comment]
> We sometimes treat `NA` and `empty` interchangeably. (I'm not sure if this is right, but it's convenient).

I agree with @etiennebr. It would be convenient if **sf** would allow for working with missing coordinates. Right now, some things are possible and some are not:

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(dplyr)

# create an sf object with one empty geometry -----------------------------
# right_join creates an empty geometry ------------------------------------
sf_obj = st_sf(geom = st_sfc(st_point(x = c(1, 2))))
sf_obj = rbind(sf_obj, sf_obj)
sf_obj$id = c(1, 2)
df_obj = data.frame(id = 1:3, value = 7:9)
sf_obj_new = right_join(sf_obj, df_obj, by = "id")
sf_obj_new
#> Simple feature collection with 3 features and 2 fields (with 1 geometry empty)
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 2 xmax: 1 ymax: 2
#> epsg (SRID):    NA
#> proj4string:    NA
#>   id value        geom
#> 1  1     7 POINT (1 2)
#> 2  2     8 POINT (1 2)
#> 3  3     9 POINT EMPTY

# create a data frame object with one pair of NA coordinates -------------
# empty geometry is represented as NA coordinates -------------------------
sf_obj_new2 = cbind(sf_obj_new, st_coordinates(sf_obj_new))
sf_obj_new2 = st_drop_geometry(sf_obj_new2)
sf_obj_new2
#>   id value  X  Y
#> 1  1     7  1  2
#> 2  2     8  1  2
#> 3  3     9 NA NA

# creation of an sf object when coordinates are NA gives an error ---------
st_as_sf(sf_obj_new2, coords = c("X", "Y"))
#> Error in st_as_sf.data.frame(sf_obj_new2, coords = c("X", "Y")): missing values in coordinates not allowed

# however, there is a possible workaround using GDAL  ---------------------
# (with st_write and st_read) ---------------------------------------------
st_write(sf_obj_new,
         "new_file1.csv",
         layer_options = "GEOMETRY=AS_XY")

sf_obj_new3 = st_read("new_file1.csv",
                      options = c("X_POSSIBLE_NAMES=X",
                                  "Y_POSSIBLE_NAMES=Y"))

sf_obj_new3
#> Simple feature collection with 3 features and 4 fields (with 1 geometry empty)
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 2 xmax: 1 ymax: 2
#> epsg (SRID):    NA
#> proj4string:    NA
#>    X  Y id value    geometry
#> 1  1  2  1     7 POINT (1 2)
#> 2  1  2  2     8 POINT (1 2)
#> 3 NA NA  3     9 POINT EMPTY

# another workaround (with write.csv and st_read) is also suprising--------
# it represents missing values as coordinates of 0,0 ----------------------
write.csv(sf_obj_new2,
          "new_file2.csv")

sf_obj_new4 = st_read("new_file2.csv",
                      options = c("X_POSSIBLE_NAMES=X",
                                  "Y_POSSIBLE_NAMES=Y"))

sf_obj_new4
#> Simple feature collection with 3 features and 5 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 0 ymin: 0 xmax: 1 ymax: 2
#> epsg (SRID):    NA
#> proj4string:    NA
#>   field_1 id value  X  Y    geometry
#> 1       1  1     7  1  2 POINT (1 2)
#> 2       2  2     8  1  2 POINT (1 2)
#> 3       3  3     9 NA NA POINT (0 0)
```

<sup>Created on 2019-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment]
Sounds simple, but simple feature compliant data don't have missing valued coordinates (the WKB `POINT EMPTY` set aside, and even that we have to [work around](https://github.com/r-spatial/sf/blob/master/src/geos.cpp#L160-L174)). Behavior of downstream code (GEOS, GDAL, possibly PROJ) will be undefined or break.

**Comment by Fgazzelloni** [comment]
This is replacing null geometries with empty geometries and transforming coordinates. 

library(geoR)
library(sf)
#> Linking to GEOS 3.11.0, GDAL 3.5.2, PROJ 9.1.0; sf_use_s2() is TRUE

gambia.borders %>%DataExplorer::profile_missing()
#>   feature num_missing pct_missing
#> 1       x         114  0.00821444
#> 2       y         114  0.00821444
# NA in the borders coords 
st_write(gambia.borders,
         "new_file1.csv",
         layer_options = "GEOMETRY=AS_XY")
#> Writing layer `new_file1' to data source `new_file1.csv' using driver `CSV'
#> options:        GEOMETRY=AS_XY
#> Warning in CPL_write_ogr(obj, dsn, layer, driver,
#> as.character(dataset_options), : GDAL Message 1: Geometry type None is not
#> compatible with GEOMETRY=AS_XYZ.
#> Writing 13878 features with 2 fields without geometries.

# replacing null geometries with empty geometries
gambia.borders2 = st_read("new_file1.csv",
                          options = c("X_POSSIBLE_NAMES=X",
                                      "Y_POSSIBLE_NAMES=Y"),
                          crs="+proj=utm +zone=10") 
#> options:        X_POSSIBLE_NAMES=X Y_POSSIBLE_NAMES=Y 
#> Reading layer `new_file1' from data source 
#>   `/private/var/folders/k3/gwjlymxx6mb2p6p_tw4dnvkc0000gn/T/RtmpdwQDg2/reprex-13112d2ed141-dopey-nyala/new_file1.csv' 
#>   using driver `CSV'
#> replacing null geometries with empty geometries
#> Simple feature collection with 13878 features and 2 fields (with 114 geometries empty)
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 303436.2 ymin: 1445166 xmax: 630742.4 ymax: 1527792
#> CRS:           +proj=utm +zone=10


gambia.borders2 %>%
  sf::st_as_sf(coords = c(1,2), 
               crs = "+proj=utm +zone=10") %>%
  # utm tranformation to longlat
  sf::st_transform(crs = "+proj=longlat +datum=WGS84") 
#> Simple feature collection with 13878 features and 2 fields (with 114 geometries empty)
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -124.8149 ymin: 13.06671 xmax: -121.7922 ymax: 13.81974
#> CRS:           +proj=longlat +datum=WGS84
#> First 10 features:
#>           x       y                   geometry
#> 1  458490.8 1521917  POINT (-123.384 13.76633)
#> 2  458805.8 1522102 POINT (-123.3811 13.76801)
#> 3  459107.5 1522289  POINT (-123.3783 13.7697)
#> 4  459542.3 1522498  POINT (-123.3743 13.7716)
#> 5  459690.7 1522575  POINT (-123.3729 13.7723)
#> 6  459914.6 1522692 POINT (-123.3708 13.77336)
#> 7  460308.4 1522873   POINT (-123.3672 13.775)
#> 8  460543.1 1522962  POINT (-123.365 13.77581)
#> 9  460949.7 1523156 POINT (-123.3613 13.77757)
#> 10 461242.9 1523251 POINT (-123.3585 13.77843)
