### ISSUE TITLE
Get library(sf) to link to newest PROJ library

### ISSUE THREAD

**Issue by jf15558** [r-spatial/sf#1038]
I am trying to perform some coordinate reference system conversions using a recently developed coordinate system (Equal Earth). This coordinate system is part of the PROJ 5.2.0 library which I have installed on my system.

However, the R package 'sf' (I have the most recent version installed) continues link to PROJ 4.9.3, which does not contain the new coordinate system, when I use library(sf). Any ideas about how I can get it it link to the newer library?

**Comment by edzer** [comment]
Did you build the package from source? `sessionInfo()`?

**Comment by jf15558** [comment]
My original version was from CRAN. I retried with the source tar.gz, but ran into a load of installation errors which I was unable to resolve. I have noted that the package rgdal is also linking to the older version of proj4 despite my updates. ALso fyi I am using Windows, so brew type solutions won't work for me

**Comment by edzer** [comment]
TBH I don't know how people on Windows do this.

**Comment by rsbivand** [comment]
The package sources in **sf**, **rgdal**, **rgeos** and similar run Makevars.win, which runs tools/winlibs.R, which downloads the current binaries from https://github.com/rwinlib/gdal2/archive for the R version. If you download that zip archive, build your matching set and put it on a download site, point tools/winlib.R at your zip archive, and install from source, you'll get your PROJ, GDAL and GEOS binaries. I think it is a lot of effort.

Can you find a proj4 string that expresses it directly and just use that (I can't see one)? Could you download PROJ for windows from https://proj4.org/install.html and try to install the CRAN **proj4** package (doesn't work with PROJ 6)? Then you'd have to unpack all the coordinates, project, and repack into objects afterwards.
