### ISSUE TITLE
pairwise st_distance() distance is slow for a large number of points

### ISSUE THREAD

**Issue by s-fleck** [r-spatial/sf#1044]
I need to calculate (Eucledian, pairwise) distances between a large number of points, and the performance of `st_distance()` is becoming a problem for me. 
A simple Pythagoras-style distance calculation between the coordinate pairs is about 100 times faster on my machine, however, the distance I end up with is in somewhat useless map units instead of meters.

Is there an efficient way to transform point coordinates from any crs to a regular meters based grid? If so it would be pretty simple to speed up the calculation and I could also work on a pull request if desired.

What i have so far:
```
library(sf)
library(bench)

p1 <- data.frame(x = runif(10000), y = runif(10000))
p2 <- data.frame(x = runif(10000), y = runif(10000))
p1 <- sf::st_as_sf(p1, coords = c("x", "y"))
p2 <- sf::st_as_sf(p2, coords = c("x", "y"))

eucledian_simple <- function(x, y){
  from <- matrix(unlist(x$geometry), ncol = 2, byrow = TRUE)
  to   <- matrix(unlist(rev(x$geometry)), ncol = 2, byrow = TRUE)
  sqrt( (from[, 1] - to[, 1])^2 + (from[, 2] - to[, 2])^2 )
}

bench::mark(
  st_distance = sf::st_distance(p1, p2, by_element = TRUE),
  eucledian_simple = eucledian_simple(p1, p2), 
  check = FALSE
)
```

**Comment by s-fleck** [comment]
Related to #1016

**Comment by edzer** [comment]
I don't think it is related to that issue, because that is about geodetic distances, not Euclidean. I think this is related to the cost of storing individual points in a list, and possibly using the GEOS library for this. It's an edge case, and you show how easy it can be optimized.

**Comment by s-fleck** [comment]
To the R side: There is surely a lot of performance loss from calling the function repeatedly via `mapply()` instead of taking advantage of c-level vectorization. I doubt the list storage per-se is a huge problem (the 100x speed improvement I measured already includes the step of converting from a list to a matrix).

I don't do much GIS so I have no feeling how much of the perfomance loss comes from converting to lat/long to meters. From skimming the blog post linked in #1016 it seems to me that the "cheap ruler" thing is basically just eucledian distance with some math on the lat/long first so that we get nice distances + some optimizations (just implemented in java script). If I understand it correctly it should be pretty easy to port to R.

**Comment by tim-salabim** [comment]
If it's of any help, I've created some cpp functions to calculate euclidean distances [here](https://gist.github.com/tim-salabim/561afd611fea2acdd14b4b6acce1bc8e#file-perppoints-cpp-L1-L64).
They also provide bearing calculations (from true north).

NOTE: These functions currently assume input to be the delta x and delta y of the planar coordiante pairs to be measured, i.e. not the actual coordinates of the points.

**Comment by rhalbersma** [comment]
Would a pull request for lines 168-169 of `geom-measures.R` along the following be welcome?

```
		d = if (by_element) {
                                if (which == "Euclidean") {
                                     sqrt(apply((st_coordinates(x) - st_coordinates(y))^2, 1, sum))
                                } else {
				     mapply(st_distance, x, y, by_element = FALSE, which = which, par = par)
                                }
                }
```

Then we'd at least have a vectorized by-element version for the Euclidean case.
