### ISSUE TITLE
st_transform producing spurious ribbons across region

### ISSUE THREAD

**Issue by webb-e** [r-spatial/sf#1046]
I am trying to use st_transform on PERZONES shapefile available [here ](https://doi.pangaea.de/10.1594/PANGAEA.888600?format=html#download).  In its native projection, it looks like this:

![image](https://user-images.githubusercontent.com/47614215/57590506-4765a300-74fa-11e9-805b-e961bb80ac59.png)

However, when I run the command:
```
tansformedPF<-st_transform(PF,"+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs") 
##This should be the MODIS sinusoidal projection
```
I get:
![image](https://user-images.githubusercontent.com/47614215/57590600-e8ecf480-74fa-11e9-936a-48b666ebfe53.png)
I thought maybe st_transform_proj would fix the problem but it did not.  I also tried to plot the raster in Earth Engine just in case it was a problem with R's plotting and not the raster itself, but EE also shows the bands.  I've used st_transform with the same destination crs with other shapefiles with no problem (although now I'll need to double check).

**Comment by jeffreyhanson** [comment]
Just in case this helps, did you try using `st_wrap_dateline` before using `st_transform`? E.g. `st_wrap_dateline(PF, options = c("WRAPDATELINE=YES")`? You might also need to set the offset value too. E.g. `st_wrap_dateline(PF, options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180")`, though you will need to change the offset value according to the original CRS.

**Comment by webb-e** [comment]
Thanks for the tip.  I had not tried that, but I did just try that with and without the `"DATELINEOFFSET=180"`, but neither solved the problem.    The native crs is  "+proj=stere +lat_0=90 +lat_ts=71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs".

**Comment by jeffreyhanson** [comment]
Ok, I'm sorry, I don't have any other ideas. It might be that you need find the correct date line offset number, but I don't know how to do this given just the source and destination coordinate system. If you're in a rush and need something fast, one solution might be to just try various incremental numbers and see if you can find it through trial and error. Otherwise, hopefully someone with more experience can chime in. Of course, it's also possible that I'm entirely wrong and the fix has nothing to do with `st_wrap_dateline`. If you haven't already, it might be worth trying `lwgeom::st_make_valid` to fix any potential geometry issues in case these are causing the problem.

**Comment by edzer** [comment]
Use `st_wrap_dateline()` when the data is in geographic coordinates:
```r
PF %>% 
  st_transform(4326) %>% 
  st_wrap_dateline() %>% 
  st_transform("+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs") -> 
  s2
```

**Comment by jeffreyhanson** [comment]
Ah - now I understand - thank you @edzer

**Comment by webb-e** [comment]
Yes, thank you @edzer.  That did solve the problem, which seems to have arisen because of the native coordinate system, correct?  Can you explain why re-projecting to 4326 prior to using `st_wrap_dateline() `is necessary?

**Comment by edzer** [comment]
There are no native coordinate systems, but indeed, the CRS in which your data came didn't have this problem. The issue arises if the antimeridian is used to split the Earth for projection, as does sinusoidal and also equidistant rectilinear (used by sf for plotting geographic, longlat coordinates). A `LINESTRING(-179 50, 179 50)` then crosses the entire Earth, passing, say, through `(0 50)`, wheras it was meant to wrap around, and pass through `(180 50)`. `st_wrap_dateline` forces it do so by cutting it in two pieces:
```r
> st_wrap_dateline(st_as_sfc("LINESTRING(-179 50, 179 50)", crs = 4326))[[1]]
MULTILINESTRING ((-179 50, -180 50), (180 50, 179 50))
```
