### ISSUE TITLE
labelLayer

### ISSUE THREAD

**Issue by Bgy1sae** [r-spatial/sf#1048]
Hi,
I'm trying to do some mapping in R using package sf. For some reason the labelLayer function no longer works. Is there a certain version of R this script is associated to and do you know how I could get it working please.

**Comment by rCarto** [comment]
Hello, 
`labelLayer()` is a function from `cartography`, not from `sf`. If loading cartography does not solve your problem you should post on cartography repo (https://github.com/riatelab/cartography/issues)
