### ISSUE TITLE
Graticule in orthographic projection has unexpected horizontal lines

### ISSUE THREAD

**Issue by fzenoni** [r-spatial/sf#1050]
I am drawing the globe in an orthographic projection as defined below:
```r
ortho <- "+proj=ortho +lat_0=-78 +lon_0=166 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs"
```
In the end I do the following plot:
```r
library(rnaturalearth)
world <- ne_countries(scale = 'small', returnclass = 'sf')

ggplot() + 
  # geom_sf(data=circle, fill = 'aliceblue') + # the globe "horizon" - you can ignore
  geom_sf(data=world) + # the visible continents
  coord_sf(crs = ortho) +
  theme(
    panel.grid.major = element_line(
      color = gray(.5), linetype = 'dashed', size = 0.5),
    panel.ontop = TRUE,
    panel.background = element_rect(fill = NA)
  )
```
![image](https://user-images.githubusercontent.com/6040873/57843139-07d6d980-77ce-11e9-907c-934d32bca5f6.png)

(I treat the `world` polygons in a sophisticated way to preserves the surfaces, so your outcome will be different, but it does not matter here.)

Is there a reason for the horizontal grid line? Is it expected?
Such lines do not appear for all views, there are times in which only the classic parallels and meridians are shown.

**Comment by edzer** [comment]
Please make your example reproducible by including the creation of `world` in it. Adding `+ coord_sf(ndiscr=1000)` to the `ggplot()` expression might help.

**Comment by fzenoni** [comment]
My bad, it is now edited. `ndiscr=1000` didn't help, sadly.

**Comment by AWSisco** [comment]
@fzenoni I too had noticed this graticule behavior in plotting some Northern and Southern Hemisphere polar maps, so I am glad to see an issue was already created. Related to your plot above, I assume the "sophisticated method" you referred to is to preserve the polygon edges to the extent of the globe. Would you be willing to share the method by which you did that or point me in the right direction? The issue is fairly evident for South America below:
![south_amer_poly](https://user-images.githubusercontent.com/37667176/58655051-e520e680-82de-11e9-9db2-3318652588c9.png)

**Comment by fzenoni** [comment]
Hi @AWSisco, indeed it is about preserving the polygons extent. Without taking care of it, the effect may be more or less visible, if not catastrophic (e.g. when the whole of Eurasia disappears).
Though certainly not an `sf` bug, a warning coming from the package could possibly help the user.

The method is a bit long to explain. I created a [gist](https://gist.github.com/fzenoni/ef23faf6d1ada5e4a91c9ef23b0ba2c1) for this purpose. In summary, I show how to build the red polygon as follows:
![image](https://user-images.githubusercontent.com/6040873/58693317-c8dd8200-8390-11e9-99d5-71043948f299.png)
and how to use it to clip the continents and keep the visible hemisphere.
![image](https://user-images.githubusercontent.com/6040873/58693364-e7dc1400-8390-11e9-97bb-cd854b8848ff.png)

Do not hesitate to leave a comment over there if you have questions.

**Comment by edzer** [comment]
To be continued here: https://github.com/r-spatial/global/issues/2

**Comment by notpeerreviewed** [comment]
> Hi @AWSisco, indeed it is about preserving the polygons extent. Without taking care of it, the effect may be more or less visible, if not catastrophic (e.g. when the whole of Eurasia disappears).
> Though certainly not an `sf` bug, a warning coming from the package could possibly help the user.
> 
> The method is a bit long to explain. I created a [gist](https://gist.github.com/fzenoni/ef23faf6d1ada5e4a91c9ef23b0ba2c1) for this purpose. In summary, I show how to build the red polygon as follows:
> ![image](https://user-images.githubusercontent.com/6040873/58693317-c8dd8200-8390-11e9-99d5-71043948f299.png)
> and how to use it to clip the continents and keep the visible hemisphere.
> ![image](https://user-images.githubusercontent.com/6040873/58693364-e7dc1400-8390-11e9-97bb-cd854b8848ff.png)
> 
> Do not hesitate to leave a comment over there if you have questions.

Hi @fzenoni 
I copied the code from your gist and replicated it for my project. The only thing I changed was the target lat and long (lat = -40, long = 175). I still get the odd horizontal graticules for some reason. I wonder if this is a southern hemisphere thing?

I'm using sf 0.8-1, lwgeom 0.2-1, and mapview 2.7.0

Jeff
