### ISSUE TITLE
More useful error message when trying to write a sub-raster

### ISSUE THREAD

**Issue by kendonB** [r-spatial/sf#1051]
I ended up here trying to use `st_rasterize`. 

https://github.com/r-spatial/sf/blob/b860ad64ce3f7d1f5fc787048237fb952b226325/R/stars.R#L48

Is there a better error message? Like "Not all \'from\' values are 0. Cannot write a sub-raster."?

happy to PR

**Comment by edzer** [comment]
I admit that this is not a very clear error message, but `from` values not being zero IMO also isn't (they're 1, on the user side)

**Comment by kendonB** [comment]
Does `from = 1` always turn into `from = 0` once it hits that part of the function?

**Comment by edzer** [comment]
Yes: https://github.com/r-spatial/sf/blob/b860ad64ce3f7d1f5fc787048237fb952b226325/R/stars.R#L32

**Comment by kendonB** [comment]
So: `"Not all 'from' values are 1. Cannot write a sub-raster."?` would be acceptable? Should `st_rasterize` also test for this itself or, better yet, convert the from, to, and offset values so that they line up at from=1?

**Comment by edzer** [comment]
Would it help you, if you were the user? I don't know how you got into this situation, and how you got out.
