### ISSUE TITLE
Question: how to find width of a polygon

### ISSUE THREAD

**Issue by Demetrio92** [r-spatial/sf#1053]
I have some input polygons created by another algorithm, and I am trying to clean-up and dissolve them. One of the problems, is that I need to remove "narrow" polygons -- they are not desired for multiple reasons. 
Example image: the polygon in the middle is obviously narrow. 
![image](https://user-images.githubusercontent.com/22682408/58018616-94053b80-7b03-11e9-8bb0-f7656601a3a2.png)

Now, the way I understand the technical definition, is that at each point of the polygon I'd have to define a line with the straight angle, find where it touches the other side, and measure the distance. Potentially, I'd only have to do it for "infliction points". (_Pardon my terminology, I am new to the whole thing_). 

So, what are my options? 

_my workaround for now is to filter by area, but a very long and narrow polygon would easily escape this logic. I could use maximum bbox size and area, but this is a hack, not a solution_

**Comment by edzer** [comment]
Other than hacks (where you also may want to explore `lwgeom::st_minimum_bounding_circle`) `sf` doesn't provide for this, and to my knowledge the libraries it interfaces also don't. Maybe ask on SO?
