### ISSUE TITLE
configure should get R version number from base::version, not by parsing the R startup message.

### ISSUE THREAD

**Issue by BillDunlap** [r-spatial/sf#1054]
sf/configure currently gets the R version number by parsing the R startup message
```
> RBIN="${R_HOME}/bin/R"
> RVER=`"${RBIN}" --version | head -1 | cut -f3 -d" "`
```
This doesn't work with TERR (and perhaps other R variants) because the the version number is not the third field in the first line of the header (and the version number in the 6th field is the TERR version number, not the version of R it is compatible with).  I would prefer sf/configure to look at the version object to get the version number, as in:
```
> RSCRIPT="${R_HOME}/bin/Rscript"
> RVER=`"${RSCRIPT}" -e 'writeLines(paste(sep=".", base::version$major, base::version$minor))'`
```

**Comment by edzer** [comment]
(I updated your comment so that the back-quotes are not interpreted as github rendering commands). Thanks, this should fix it.

**Comment by BillDunlap** [comment]
Thank you, looks good.
