### ISSUE TITLE
Map coercion fails for world map when fill = FALSE

### ISSUE THREAD

**Issue by kuriwaki** [r-spatial/sf#1059]
As the last comment in #194 showed, the coercion still fails when `fill = FALSE` (the default). Should it? 

``` r
library(maps)

# works
sf::st_as_sf(maps::map('world', plot = FALSE, fill = TRUE))
#> Simple feature collection with 253 features and 1 field
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -180 ymin: -85.19218 xmax: 190.2708 ymax: 83.59961
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#> First 10 features:
#>                          geometry             ID
#> 1  MULTIPOLYGON (((74.89131 37...    Afghanistan
#> 2  MULTIPOLYGON (((20.06396 42...        Albania
#> 3  MULTIPOLYGON (((8.576563 36...        Algeria
#> 4  MULTIPOLYGON (((-170.7263 -... American Samoa
#> 5  MULTIPOLYGON (((1.706055 42...        Andorra
#> 6  MULTIPOLYGON (((23.9665 -10...         Angola
#> 7  MULTIPOLYGON (((-63.00122 1...       Anguilla
#> 8  MULTIPOLYGON (((-161.9938 -...     Antarctica
#> 9  MULTIPOLYGON (((-61.71606 1...        Antigua
#> 10 MULTIPOLYGON (((-64.54916 -...      Argentina

# doesn't work with the fill = FALSE
sf::st_as_sf(maps::map('world', plot = FALSE, fill = FALSE))
#> Error in maptools::map2SpatialPolygons(x, IDs = ID0, proj4string = sp::CRS("+init=epsg:4326")): map and IDs differ in length
```

<sup>Created on 2019-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mdsumner** [comment]
I don't think there's any easy fix for this, the data in the maps package is often internally inconsistent and there's no way to restore the relationship between the data and the geometry. It was originally stored as shared boundaries, and was simplified into closed paths, so the IDs and paths are not aligned in the `fill = FALSE` case. 

https://github.com/adeckmyn/maps/issues/6#issuecomment-239622947

**Comment by kuriwaki** [comment]
Thanks for the reference -- I see.  I'm not too familiar with spatial data myself but was looking for a teaching MWE. A simple world map is something that is ubiquitous in intro classes, so if there is a shapefile world map  it might be effective to have one pre-loaded in `inst/shape/` instead of relying on `maps`.

**Comment by rsbivand** [comment]
Maybe **rnaturalearth** or the older **rworldmap**, both from Andy South?
