### ISSUE TITLE
Very slow rendering with geom_sf

### ISSUE THREAD

**Issue by thk686** [r-spatial/sf#1062]
Posting here as it is possibly more of an sf-project issue than ggplot (but let me know and I'll post over there). The following takes a very long time to plot:

```r
nc_state <- st_read(dsn = "ncshape", layer = "nc_state", quiet = T)
railroads <- st_read(dsn = "ncshape", layer = "railroads", quiet = T)
hospitals <- st_read(dsn = "ncshape", layer = "hospitals", quiet = T)
ggplot(nc_state) +
  geom_sf() +
  geom_sf(data = railroads) +
  geom_sf(data = hospitals)
```
Its an example I use in teaching.

**Comment by edzer** [comment]
Did you update to latest versions? @thomasp85 did some recent work optimizing sf stuff in order to speed up `geom_sf`.

**Comment by thk686** [comment]
CRAN or github version? (Just reinstalled from CRAN and am testing.)

THK

**Comment by adrfantini** [comment]
Can you please include your data? `geom_sf` is definitely not as fast as `sf::plot` but it should be ok-ish even for relatively large datasets. However keep in mind that while grid is quite fast, all the rest of the `ggplot` architecture was never meant for speed.

**Comment by thomasp85** [comment]
You’ll need R 3.6 and the devel version of ggplot2 to get fast polygon rendering with `geom_sf()`

The next ggplot2 release is just around the corner

**Comment by thk686** [comment]
Perfect. Thanks. I'll try that.

**Comment by etiennebr** [comment]
@thk686, I'll close the issue, but feel free to reopen it if R 3.6 and devel version of `ggplot2` fail you.
