### ISSUE TITLE
st_write can silently ignore driver specification if update = TRUE and dsn directory is non-empty

### ISSUE THREAD

**Issue by thebat137** [r-spatial/sf#1066]
I discovered that if I am attempting to use st_write to write a shapefile to a directory that previously contained only (non-empty) CSV files, my driver = 'ESRI Shapefile' specification is silently ignored if update = TRUE is specified.  Instead, the attribute table of my shapefile is saved as a CSV and the rest is lost.  It is impossible to override this and indicate that I would like to add an actual shapefile to the directory.  If there is even a single non-CSV file in the directory in advance of trying to save, this problem does not occur.

The only workarounds I've found for this are to either create any non-CSV file in the directory before saving the shapefile (e.g., by creating empty copies of the shapefile files in advance), or to check the directory contents in advance of saving the shapefile and use that to decide whether to set update = TRUE.  (I'm writing a function that should automatically create the shapefile if it does not exist or update it if it does, and I spent an awful lot of time trying to figure out why it was only creating CSVs on the first run through.)  This seems suboptimal...

MWE:
```
library(sf)

dir.create('foobar')

df <- data.frame(a = 'hi', b = 1)
write.csv(x = df, file = file.path('foobar', 'foo.csv'))

fname <- system.file(file.path('shape', 'nc.shp'), package='sf')
nc <- st_read(fname)

st_write(obj = nc, dsn = 'foobar', layer = 'bar', driver = 'ESRI Shapefile', update = TRUE)
```

**Comment by edzer** [comment]
This now generates at least an error message in your case; I'm not sure the GDAL API allows us to do what you're trying. Do you have experience with other software that did what you wanted in this case (e.g. rgdal, or QGIS or so)?

**Comment by etiennebr** [comment]
Thanks, that's an intriguing bug. I don't totally understand the origin of the problems. My understanding is:
  1. Can't write shapefile (or any other format I've tried) when there's a csv. That's very weird! Thanks for reporting what must have been a very long bug to isolate.
  2. Can't update shapefile

For number 1, it works if you use file name. If it suits your need it's a good option.
```r
st_write(obj = nc, dsn = 'foobar/bar.shp')
```

For number 2, did you try  `delete_layer = TRUE`? Unless you want to append, this would work:
```r
st_write(obj = nc, dsn = 'foobar/bar.shp', delete_layer = TRUE)
st_write(obj = head(nc, 20), dsn = 'foobar/bar.shp', delete_layer = TRUE)
```
If you wan't to append, one way would be to do it in R by `st_read`ing the existing layer, merging and then `delete_layer`.

@edzer, I think `ogr` supports what @thebat137 is trying to do. Running this in terminal from `foobar` works:  `ogr2ogr bar.shp ~/sf/inst/gpkg/nc.gpkg`.

**Comment by thebat137** [comment]
@etiennebr, I had problem 2 early on and resolved it with ``delete_layer = TRUE`` as you suggest.  Since it actually gave me a semi-informative error message, I didn't think to report that one, sorry!

Problem 1 _is_ resolved for me if I use ``dsn = 'foobar/bar.shp'`` instead of ``dsn = 'foobar', layer = 'bar'``.  However, ``dsn = 'foobar', layer = 'bar.shp'`` has the same result as ``dsn = 'foobar', layer = 'bar'``.

@edzer, I'm in the process of switching my workflows to ``sf`` from ``sp``/``rgdal``.  I never had this issue with ``writeOGR``, and I can't seem to reproduce it there.

**Comment by edzer** [comment]
Thanks; in that case, @rsbivand (author of rgdal) may have an idea.
