### ISSUE TITLE
Update group_map() to work with dplyr 0.8.1

### ISSUE THREAD

**Issue by mattbk** [r-spatial/sf#1071]
As of https://github.com/tidyverse/dplyr/pull/4251, `group_map()` is now `group_modify()` and some other functions have been added. Would be helpful if `group_modify()` could take sf objects. Follows #969.

More on the new functions: https://coolbutuseless.github.io/2019/03/17/group_map-in-dplyr-0.8.1-still-in-development/

**Comment by edzer** [comment]
PR's welcome, but closing here.
