### ISSUE TITLE
mutating the geometry column strips the projection

### ISSUE THREAD

**Issue by FabianRoger** [r-spatial/sf#1073]
I have data that come in Lat Long (points) which I transform to SF with a projection. When I mutate the geometry column to shift the points the crs is dropped again. I provide a repex below. Am I missing something? And can I just reattach the crs without without worrying?  

repex:

    library(sf)
    data(meuse)
    
    #transform to sf and add crs
    meuse <- 
    meuse %>% 
      st_as_sf(coords = c("x", "y"), crs = "+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

    Simple feature collection with 155 features and 12 fields
    geometry type:  POINT
    dimension:      XY
    bbox:           xmin: 178605 ymin: 329714 xmax: 181390 ymax: 333611
    epsg (SRID):    NA
    proj4string:    +proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
    
    #mutating geometry column to shift the points strips the projection 
    meuse %>% 
      mutate(geometry = geometry + c(0,1000)) 

    Simple feature collection with 155 features and 12 fields
    geometry type:  POINT
    dimension:      XY
    bbox:           xmin: 178605 ymin: 330714 xmax: 181390 ymax: 334611
    epsg (SRID):    NA
    proj4string:    NA

**Comment by edzer** [comment]
you are adding values to your coordinates; that means you are doing a coordinate conversion (projection) which is not in the book of "known" projections, hence the new CRS becomes `NA`, to be understood as "no idea how to describe this in PROJ terms".

**Comment by FabianRoger** [comment]
Fair enough. In my real example I am constructing new coordinates using a known origin, the distance and the direction (i.e. new point 1 km north, new point 2 1km north and 1km east). It seems to work as expected. Is this discouraged?

**Comment by edzer** [comment]
Not at all, but you're moving outside the PROJ realm, into the "this is no longer a known coordinate reference system" realm. Hence the `NA`. Only you know what you've been doing.
