### ISSUE TITLE
Transform fails on empty sf

### ISSUE THREAD

**Issue by krlmlr** [r-spatial/sf#1075]
``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3

st_sf(x = integer(), geom = st_sfc(crs = 3857)) %>%
  sf::st_transform(4326)
#> Error in CPL_transform(x, crs$proj4string): CPL_transform: zero length geometry list
```

<sup>Created on 2019-06-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Related: #228. The origin of the error might be here:

https://github.com/r-spatial/sf/commit/aa45bda2cc77d76ca320e8426cb4f2280d809ffd#diff-f2365be569cb22a0677b4f0c79d12a7bR246

Is there a reason why this corner case isn't supported? I'd expect an empty sf with the new CRS applied.

**Comment by edzer** [comment]
Thanks, @krlmlr , should work now.
