### ISSUE TITLE
Strange behaviour of st_segmentize 

### ISSUE THREAD

**Issue by jamesgrecian** [r-spatial/sf#1078]
When processing spatial data it can be useful to create a bounding box defined by lat and lon coordinates but then projected to cartesian xy.

This square box should become a wedge shape. However, when defined by only four corners the projected box becomes a trapezoid. 

I've tried to use `st_segmentize` to generate additional points between the corners of the box. These form the curves in the wedge when projected. This works when the corner coordinates are defined as a polygon, but not when the extent information is taken from a raster and so `st_segmentize` is working with a geometry.

PS. This is my first attempt at reporting an issue/ question on GitHub so apologies if I've not followed the right procedure.
PPS. For completeness this follows on from a twitter conversation here:
https://twitter.com/JamesGrecian/status/1137018574504153089

``` r
require(sf)
#> Loading required package: sf
#> Warning: package 'sf' was built under R version 3.5.2
#> Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3
require(ggplot2)
#> Loading required package: ggplot2

ext <- raster::extent(-40, 40, -60, -40)
ext <- ext %>% st_bbox(crs = 4326)
ext <- ext %>% sf::st_as_sfc() 
ext <- ext %>% sf::st_segmentize(sf::st_length(ext)/5000)
ext <- ext %>% sf::st_transform(crs = "+proj=laea +lat_0=-50 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs") 
ext %>% ggplot() + geom_sf() + ggtitle("Strange")
```

![](https://i.imgur.com/KOjHTjU.png)

``` r

pol <- sf::st_polygon(list(rbind(c(-40, -60),
                                c( 40, -60),
                                c( 40, -40),
                                c(-40, -40),
                                c(-40, -60))))
pol <- sf::st_segmentize(pol, 1)
pol <- pol %>% sf::st_sfc() 
pol <- pol %>% st_set_crs(4326)
pol <- pol %>% sf::st_transform(crs = "+proj=laea +lat_0=-50 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs")
pol %>% ggplot() + geom_sf() + ggtitle("Not strange")
```

![](https://i.imgur.com/oiVzi60.png)

<sup>Created on 2019-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mdsumner** [comment]
This is due to st_segmentize operating with respect to geographic distance and assuming great circle traversal (I thought this was fixed as it came up very early when graticules were being developed), but you can avoid the problem by  forcing it to work in the coordinate system you are actually using - what follows is effectively the same as your second example because you segmentize with a hardcoded value before setting CRS. 

`st_length` appears to return 0  if the CRS is NA, so we hardcode a sub-degree value

``` r
require(sf)
#> Loading required package: sf
#> Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0
require(ggplot2)
#> Loading required package: ggplot2
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang

ext <- raster::extent(-40, 40, -60, -40)
ext <- ext %>% st_bbox(crs = 4326)
ext <- ext %>% sf::st_as_sfc() 
## remove the crs so we get planar ops, but restore immediate
crs <- st_crs(ext)
ext <- st_set_crs(ext, NA)
ext <- ext %>% sf::st_segmentize(1) %>% st_set_crs(crs)
ext <- ext %>% sf::st_transform(crs = "+proj=laea +lat_0=-50 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs") 
ext %>% ggplot() + geom_sf()
```

![](https://i.imgur.com/DK5feB8.png)

<sup>Created on 2019-06-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Agreed; you need to get your head around the difference of drawing lines in R2 (the usual thing), and drawing lines over S2 (a sphere). Except for the equator and poles, points connecting locations with equal latitude are not shortest distance "lines".

**Comment by jamesgrecian** [comment]
Ok, thanks both. Happy to avoid the problem by stripping out the CRS before using `st_segmentize`, but thought you should be aware of the strange behaviour.

**Comment by edzer** [comment]
I don't consider that behaviour strange.
