### ISSUE TITLE
stplanr

### ISSUE THREAD

**Issue by PoorvaITS** [r-spatial/sf#1079]
Desire lines plot issue:

I tried to generate desire line plot for Bristol_cycle by following the steps from your book, Geo-computation with R and it plotted the map. But when I am trying to use my data by making it read the file in R, I am not able to generate the same for Denmark because the steps which I have followed is generating UK regions only. 

I want to produce a origin-destination desire line map using FromZONEID and ToZONEID of Denmark and can also use latitude-longitude for the same. Can you please suggest the codes and process on how to plot when I have to use a non-UK data and zones.

**Comment by edzer** [comment]
Maybe you want to post this issue at https://github.com/ropensci/stplanr?
