### ISSUE TITLE
Feature request: st_concave_hull

### ISSUE THREAD

**Issue by prosoitos** [r-spatial/sf#1084]
I need to create concave hulls around points and [this QGIS plugin](https://github.com/detlevn/QGIS-ConcaveHull-Plugin) does it perfectly.

But I would love to do this in R.

Apologies if sf already has such a feature and I missed it. I didn't see anything in the manual.

**Comment by prosoitos** [comment]
As a workaround, I guess there is RQGIS.

**Comment by Nowosad** [comment]
@prosoitos there is also https://github.com/joelgombin/concaveman

**Comment by prosoitos** [comment]
Oh thanks. I missed it when I searched. RQGIS3 seems to allow me to use the QGIS plugin just fine. But good to know that an algorithm is already implemented in R.

**Comment by jannes-m** [comment]
Just for clarification: I've just had a quick glance at https://github.com/joelgombin/concaveman. It seems to be a wrapper around JavaScript code. The respective QGIS (`qgis:concavehull`, `qgis:knearestconcavehull`) and GRASS (`v.concave.hull`) tools, I haven't looked it up, but are probably written in C++. Hence, none of these tools are implemented in R, R is only quite good to allow access to such third-party tools.

**Comment by edzer** [comment]
@jannes-m do you also classify GDAL, GEOS and PROJ as third-party tools, as they are C++ libs linked to and not written in R?

**Comment by jannes-m** [comment]
Yes, I would, wouldn't you? I guess one could go further and classify in more detail according to the degree of integration (partial, full) and the used link (system command line, reticulate, Rccp), for example. However, here I just wanted to point out two things:

1. that the mentioned concave hull tools are not written in native R, and therefore ...
2. that it is often worth looking for implementations in other software packages since quite often these are already accessible from within R which in turn avoids reinventing the wheel.

**Comment by edzer** [comment]
I guess so, yes. It's also helpful to know in case problems come up, where to look for solutions.

**Comment by dr-jts** [comment]
There is now a [concave hull in GEOS](http://libgeos.org/doxygen/geos__c_8h.html#aaceadb7351dda799a583edca329931ae).  Perhaps this could be exposed?

**Comment by edzer** [comment]
> There is now a [concave hull in GEOS](http://libgeos.org/doxygen/geos__c_8h.html#aaceadb7351dda799a583edca329931ae). Perhaps this could be exposed?

On which GEOS version does this depend?

**Comment by dr-jts** [comment]
Concave Hull will be in 3.11, which should get released Real Soon Now.

**Comment by rsbivand** [comment]
No luck building head of libgeos on Fedora 36, GCC 12.1.1:

```
  8%] Building CXX object CMakeFiles/geos.dir/src/geom/GeometryFactory.cpp.o
In file included from /usr/include/c++/12/bits/stl_tree.h:63,
                 from /usr/include/c++/12/set:60,
                 from /home/rsb/topics/github/geos/include/geos/geom/Coordinate.h:19,
                 from /home/rsb/topics/github/geos/src/geom/GeometryFactory.cpp:21:
In static member function ‘static _Tp* std::__copy_move<_IsMove, true, std::random_access_iterator_tag>::__copy_m(const _Tp*, const _Tp*, _Tp*) [with _Tp = geos::geom::Coordinate; bool _IsMove = false]’,
    inlined from ‘_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = const geos::geom::Coordinate*; _OI = geos::geom::Coordinate*]’ at /usr/include/c++/12/bits/stl_algobase.h:495:30,
    inlined from ‘_OI std::__copy_move_a1(_II, _II, _OI) [with bool _IsMove = false; _II = const geos::geom::Coordinate*; _OI = geos::geom::Coordinate*]’ at /usr/include/c++/12/bits/stl_algobase.h:522:42,
    inlined from ‘_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = __gnu_cxx::__normal_iterator<const geos::geom::Coordinate*, vector<geos::geom::Coordinate> >; _OI = geos::geom::Coordinate*]’ at /usr/include/c++/12/bits/stl_algobase.h:529:31,
    inlined from ‘_OI std::copy(_II, _II, _OI) [with _II = __gnu_cxx::__normal_iterator<const geos::geom::Coordinate*, vector<geos::geom::Coordinate> >; _OI = geos::geom::Coordinate*]’ at /usr/include/c++/12/bits/stl_algobase.h:620:7,
    inlined from ‘void geos::geom::FixedSizeCoordinateSequence<N>::setPoints(const std::vector<geos::geom::Coordinate>&) [with long unsigned int N = 0]’ at /home/rsb/topics/github/geos/include/geos/geom/FixedSizeCoordinateSequence.h:108:22:
/usr/include/c++/12/bits/stl_algobase.h:431:30: error: argument 1 null where non-null expected [-Werror=nonnull]
  431 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/12/bits/stl_algobase.h:431:30: note: in a call to built-in function ‘void* __builtin_memmove(void*, const void*, long unsigned int)’
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/geos.dir/build.make:818: CMakeFiles/geos.dir/src/geom/GeometryFactory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:345: CMakeFiles/geos.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by rsbivand** [comment]
Looks as though clang version 14.0.0 (Fedora 14.0.0-1.fc36) is OK.

**Comment by dr-jts** [comment]
GEOS now fixed for GCC 12: https://github.com/libgeos/geos/pull/610

**Comment by dr-jts** [comment]
@edzer @rsbivand   Also might want to expose [GEOSConstrainedDelaunayTriangulation](http://libgeos.org/doxygen/geos__c_8h.html#a1849ca38fe31c72787463989b50bbb0d) for triangulating polygonal geometry.

**Comment by rsbivand** [comment]
@dr-jts thanks for the GCC 12 fix, make and ctest clean.
