### ISSUE TITLE
proj.h check fails with PROJ 6.1.0 and `--with-proj-api=no`

### ISSUE THREAD

**Issue by paulmenzel** [r-spatial/sf#1090]
Building sf 0.7-5 with PROJ 6.1.0 installed in `/dev/shm/proj` fails.

```
$ PKG_CONFIG_PATH=/dev/shm/proj/lib/pkgconfig pkg-config --modversion proj
6.1.0
$ PKG_CONFIG_PATH=/dev/shm/proj/lib/pkgconfig LD_LIBRARY_PATH=/dev/shm/proj/lib/:$LIBRARY_PATH ./configure --with-proj-lib=/dev/shm/proj/lib --with-proj-include=/dev/shm/proj/include --with-proj-share=/dev/shm/proj/share/proj --with-proj-data=/dev/shm/proj --with-proj-api=no
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.4.1
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: pkg-config proj exists, will use it
checking proj.h usability... no
checking proj.h presence... no
checking for proj.h... no
configure: error: proj.h not found in standard or given locations.
```

Passing `--with-proj-api=yes` works.

So the part with `AC_CHECK_HEADERS(proj.h,PROJH=yes,PROJH=no)` below in `configure.ac` fails.

https://github.com/r-spatial/sf/blob/ee35c42e9fdcd1f1fe72d347d50bffbbc30f779c/configure.ac#L340-L358

Has this combination been tested in the current configure script?

	$ ls -lR /dev/shm/proj/include/
	/dev/shm/proj/include/:
	total 184
	-rw-r--r-- 1 joey joey 44277 Jun 21 12:37 geodesic.h
	-rw-r--r-- 1 joey joey  2960 Jun 21 12:37 org_proj4_PJ.h
	drwxrwx--- 2 joey joey   220 Jun 21 12:37 proj
	-rw-r--r-- 1 joey joey 42586 Jun 21 12:37 proj.h
	-rw-r--r-- 1 joey joey  8346 Jun 21 12:37 proj_api.h
	-rw-r--r-- 1 joey joey 23206 Jun 21 12:37 proj_constants.h
	-rw-r--r-- 1 joey joey 34185 Jun 21 12:37 proj_experimental.h
	-rw-r--r-- 1 joey joey 19796 Jun 21 12:37 proj_symbol_rename.h

	/dev/shm/proj/include/proj:
	total 296
	-rw-r--r-- 1 joey joey 15312 Jun 21 12:37 common.hpp
	-rw-r--r-- 1 joey joey 74637 Jun 21 12:37 coordinateoperation.hpp
	-rw-r--r-- 1 joey joey 25072 Jun 21 12:37 coordinatesystem.hpp
	-rw-r--r-- 1 joey joey 51546 Jun 21 12:37 crs.hpp
	-rw-r--r-- 1 joey joey 28370 Jun 21 12:37 datum.hpp
	-rw-r--r-- 1 joey joey 38016 Jun 21 12:37 io.hpp
	-rw-r--r-- 1 joey joey 16149 Jun 21 12:37 metadata.hpp
	-rw-r--r-- 1 joey joey 15185 Jun 21 12:37 nn.hpp
	-rw-r--r-- 1 joey joey 24567 Jun 21 12:37 util.hpp

Strangely `proj.h` still mentions something about PROJ 4.

	$ head /dev/shm/proj/include/proj.h
	/******************************************************************************
	 * Project:  PROJ.4
	 * Purpose:  Revised, experimental API for PROJ.4, intended as the foundation
	 *           for added geodetic functionality.
	 *
	 *           The original proj API (defined previously in projects.h) has grown
	 *           organically over the years, but it has also grown somewhat messy.
	 *
	 *           The same has happened with the newer high level API (defined in
	 *           proj_api.h): To support various historical objectives, proj_api.h

**Comment by paulmenzel** [comment]
> Strangely proj.h still mentions something about PROJ 4.

Looks like, `PROJ.4` is the old project name. It was renamed to PROJ. So seems unrelated.

**Comment by lguangyu** [comment]
It is because in 6.1.0+ the proj lib changed the header (I think is for speeding the deprecation of PROJ4 api)

```
/home/li.gua/usr/proj/6.1.1/include/proj_api.h:37:2: error: #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
 #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
  ^~~~~
./configure: line 3869: ./proj_conf_test: No such file or directory
```
It throws this error from the header file, but unfortunately your `configure` think its due to missing header file.

**Comment by lguangyu** [comment]
OK, case solved. It starts in `configure.ac` line 310:
```
PROJ_CONFIG="pkg-config proj"

if `$PROJ_CONFIG --exists` ; then
  AC_MSG_NOTICE([pkg-config proj exists, will use it])
  proj_config_ok=yes
else
  proj_config_ok=no
fi
```
Then line 342-358:
```
if test "${proj_config_ok}" = yes; then
(check proj.h)
...
fi
(below is checking v4 API)
```
If your proj's pkgconfig is not configured with pkg-config nor in standard path, the existence of `proj.h` would **NEVER** have a chance to be checked. Then it tries to use `proj_api.h` but the newer version of proj tries to accelerate the deprecation of v4 API: it forces the user to define a macro before using it, otherwise an manual error:
```
(proj_api.h 
#ifndef ACCEPT_USE_OF_DEPRECATED_PROJ_API_H
#error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
#endif
```
which is not passed to the ac test function. But if you specify force using v4 API, it is obvious that they define that macro. However, the `configure` mistakenly thinks this error is due to missing header.

**Comment by edzer** [comment]
OK, thanks. Close here, or would you like to try to improve `configure.ac`?
