### ISSUE TITLE
as_Spatial with empty polygons

### ISSUE THREAD

**Issue by bastistician** [r-spatial/sf#1093]
**sf** knows about empty polygons, but conversion of a geometry list column with empty polygons to **sp**'s "SpatialPolygons" class is fragile. Is there a way to transfer empty polygons to the "SpatialPolygons" representation? If not, I suggest to catch the error that `as_Spatial()` currently produces for the edge case and instead stop with a more informative error message, for example "cannot create SpatialPolygons with empty polygons". An example follows:

``` r
library("sf")

mysfc <- st_sfc(list(
    st_polygon(list(matrix(c(1,3,2,1,0,0,1,0), 4, 2))),
    st_polygon()  # empty polygon
))

as_Spatial(mysfc)
## Error in sp::Polygons(lapply(seq_along(x), function(i) sp::Polygon(x[[i]], :
##   length(srl) > 0 is not TRUE
traceback()
## 8: stop(simpleError(msg, call = if (p <- sys.parent(1L)) sys.call(p)))
## 7: stopifnot(length(srl) > 0)
## 6: sp::Polygons(lapply(seq_along(x), function(i) sp::Polygon(x[[i]], 
##        i > 1)), "ID")
## 5: FUN(X[[i]], ...)
## 4: lapply(from, function(x) sp::Polygons(lapply(seq_along(x), function(i) sp::Polygon(x[[i]], 
##        i > 1)), "ID"))
## 3: sfc2SpatialPolygons(from, IDs)
## 2: .as_Spatial(from, cast, IDs)
## 1: as_Spatial(mysfc)
```

A bit of context: I was using `rmapshaper::ms_simplify(..., keep_shapes = TRUE)` with an old-fashioned SpatialPolygons object, which internally does SpatialPolygons -> GeoJSON -> simplified GeoJSON (with empty polygons) -> sf -> SpatialPolygons. The dubious error occurred in the last back-transformation step.

**Comment by rsbivand** [comment]
It needs an error, as **sp** classes do not admit empty geometries by design. Think marked point patterns with a missing point ... It doesn't make any sense for spatial analysis, that was what was thought then.
