### ISSUE TITLE
Geometry column automatically renamed

### ISSUE THREAD

**Issue by etiennebr** [r-spatial/sf#1097]
I noticed using multi-column geometries, that `sf` doesn't keep the user supplied name. 
``` r
library(sf)
#> Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0

data.frame(
    a = st_sfc(st_point(c(0, 0))),
    b = st_sfc(st_point(c(1, 0)))
)
#>      geometry  geometry.1
#> 1 POINT (0 0) POINT (1 0)
```
`a` and `b` are renamed to `geometry`(then renamed by `data.frame` to `geometry.1`). This can make it hard to predict which column should be the active geometry column.

``` r
st_as_sf(
    data.frame(
        a = st_sfc(st_point(c(0, 0))),
        b = st_sfc(st_point(c(1, 0)))
    ), 
    sf_column_name = "b"
)
#> Error in st_sf(x, ..., agr = agr, sf_column_name = sf_column_name): sf_column_name %in% all_sfc_names is not TRUE

# need to use the implicit name
st_as_sf(
    data.frame(
        a = st_sfc(st_point(c(0, 0))),
        b = st_sfc(st_point(c(1, 0)))
    ), 
    sf_column_name = "geometry.1"
)
#> Simple feature collection with 1 feature and 0 fields
#> Active geometry column: geometry.1
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 0 xmax: 1 ymax: 0
#> epsg (SRID):    NA
#> proj4string:    NA
#>      geometry  geometry.1
#> 1 POINT (0 0) POINT (1 0)
```

**Comment by etiennebr** [comment]
It's happening in https://github.com/r-spatial/sf/blob/76fb4fe2cc9edf7d06c35724a0b8b32504684c78/R/sfc.R#L223-L227

**Comment by edzer** [comment]
Yes, and at the moment `as.data.frame.sfc` is called by `data.frame`, `deparse(substitue(x))` gives you `x[[i]]`, so the name seems to be lost at that point. Without such a method, I guess creating a `data.frame` errors or gives bogus results. Any reason why you want to use `data.frame()` rather than `tibble`?
```r
tibble(
    a = st_sfc(st_point(c(0, 0))),
    b = st_sfc(st_point(c(1, 0)))
)
# A tibble: 1 x 2
        a       b
  <POINT> <POINT>
1   (0 0)   (1 0)
```

**Comment by etiennebr** [comment]
i thought we settled on supporting `tibble` and `data.frame` :smile:  That's how I stumbled on the problem, trying to create code that would work for both.

**Comment by edzer** [comment]
I'm with you, I just don't know how, and whether this can be done with data.frames.

**Comment by edzer** [comment]
Can this be closed?
