### ISSUE TITLE
st_proj_info() more useful if contained proj-string

### ISSUE THREAD

**Issue by andybeet** [r-spatial/sf#1099]
The function sf::st_proj_info(type="proj) returns a list of projections mapping 3D to 2D.

The list is very similar (if not identical) to the definitions found in proj.org (https://proj.org/operations/projections/index.html). However in proj.org after you click on a projection you see a map of the projection and the "proj-string" identifier. 

Can this proj-string be included in sf::st_proj_info()?

Alternatively can someone explain how to project using the output of st_proj_info()? Otherwise i am not sure i see the value in this function.

I am interested in producing figures of all projections listed in  sf::st_proj_info(type="proj)

**Comment by edzer** [comment]
```r
library(sf)
# Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0
st_crs(paste0("+proj=", as.character(st_proj_info(type="proj")[140, "name"])))
# Coordinate Reference System:
#   No EPSG code
#   proj4string: "+proj=vandg +lon_0=0 +x_0=0 +y_0=0 +R_A +ellps=WGS84 +units=m +no_defs"
```
This doesn't work for all of them, I don't know why.

**Comment by andybeet** [comment]
Thanks. 

The reason "bonne" fails (as an example) is that it is pulling an incorrect crs.
It pulls "+proj=bonne, reason: lat_1 = 0" instead of "+proj=bonne, reason: lat_1 = 10"

I am guessing this is out of the hands of sf developers.

Looks like i am making my own table

**Comment by edzer** [comment]
Indeed; and I think that makes sense for your purpose. Note that this is really a list of projection _families_, each having configurable parameters. For some, the parameters have reasonable defaults (`aea`), for others nonsense defaults as you just found out.

**Comment by andybeet** [comment]
My last comment:

It seem like there are 2 "issues".

1. Nonsensical parameters stored (where, i am unsure) that st_crs() pulls
2. Using parameters listed on PROJ4.org st_transform() returns an error

eg. https://proj.org/operations/projections/gnom.html. Listed crs = "+proj=gnom +lat_0=90 +lon_0=-50" but

st_transform(shapefile,crs="+proj=gnom +lat_0=90 +lon_0=-50")

produces an error.
Thanks for your help

**Comment by edzer** [comment]
1. in proj, not in sf;
2. No it doesn't:
```r
> library(sf)
Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0
> st_crs("+proj=gnom +lat_0=90 +lon_0=-50")
Coordinate Reference System:
  No EPSG code
  proj4string: "+proj=gnom +lat_0=90 +lon_0=-50 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs"
> 
```
but possibly the proj version your sf version links to is out of sync with the one on the web site; I used
```r
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.7.0"        "2.4.0"        "5.2.0"         "true" 
```

**Comment by andybeet** [comment]
I am using a different version.

> sf_extSoftVersion()

          GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.6.1"        "2.2.3"        "4.9.3"         "true"

But the error was with st_transform() not st_crs()
