### ISSUE TITLE
st_difference creates colname 'Id', may cause st_write to fail

### ISSUE THREAD

**Issue by SimonDedman** [r-spatial/sf#1100]
Hi all,

Issue discovered [here](https://gis.stackexchange.com/questions/327725/st-write-fails-for-object-created-with-st-difference-using-r?noredirect=1#comment534131_327725), whereby I read in polygons (originally shapefiles from MarineRegions.org then converted to GPKG) and used st_difference to remove the overlap of smaller regions (Gulf of Mexico, Slope Sea) from the main region (West Atlantic + Bahamas). The original WAtl/Bah file contains a colname 'id', either as downloaded or via GPKG conversion (simple st_write).

My first st_difference created a column named 'id.1', meaning a call to st_write succeeds.
My second st_difference added a single extra column named 'Id', meaning a call to st_write fails.

Having read [this](https://github.com/r-spatial/sf/issues/538) and Spacedman's solution suggestion (simply manually rename the column), I feel this might be somewhat bug territory, insofar as a viable input GPKG file can have one sf function performed on it (st_difference) than saves with another (st_write) successfully, but if two st_differences are called, it fails.

It's not clear where the 'blame' lies, since GPKG column names must be unique and are case insensitive, but R object names don't have to be unique and are case sensitive. In my examples, it turns out the main file (WAtl/Bah) has an 'id' column, as does the first st_difference candidate (GOM, 'id') so st_difference renames GOM's 'id' to 'id.1', helpfully. However since the second st_difference candidate (slopesea) has an upper case variant ('Id') this must not trigger the st_difference rename code, and the Id column passes through untouched, only to kill the st_write attempt.

Possible solutions:
- st_difference to add a check any(duplicated(toupper(names(x)))) and include those in the 'y.1' rename code.
- do the check but then simply warn the user, e.g. "names of column 2 'id' and 42 'Id' are identical other than by case, this will cause st_write to fail for GPKG files"
- st_write to do either of these, probably warning the user if the former.

Thanks in advance for any thoughts.

**Comment by edzer** [comment]
As far as I can see, your issue on SO has been solved by @barryrowlingson . `sf` can read many different formats, I don't see why the behavior of one of them could be an issue for `sf`. When you do see a real issue for `sf`, please bring a short and clear, self-contained example here.

**Comment by SimonDedman** [comment]
It's really a personal decision for you, I'd say.
Within the sf suite, st_difference will allow joining of objects with columns that only differ in their case status. This is fine.
Within the sf suite, the default export option for one's work - st_write - will fail with a lengthy and somewhat cryptic error stream if asked to save an object with columns that only differ in their case status. This is also somewhat fine (notwithstanding st_write could add a clear error message upstream of the GDAL/sqlite3 error).
That both happen within the sf suite lead me to think sf could CHOOSE to intercept this potential sticking point for users, again with the clear admission that it's not an explicit BUG that st_difference, st_write, GDAL or sqlite3 work as they do.
Cheers.
