### ISSUE TITLE
LIBKML not accessible to sf

### ISSUE THREAD

**Issue by emochoa** [r-spatial/sf#1104]
I am using the `st_read` function in `sf` to read a KML file.  As in #499, the result has the appropriate geometry but is missing all of its variables and instead has 'Name' and 'Description' fields.

Following advice in #499, I reinstalled `GDAL` (upgrading to 2.4.2).

From the terminal, I can verify that `LIBKML` is installed:
```
> ogrinfo --formats | grep KML
LIBKML -vector- (rw+v): Keyhole Markup Language (LIBKML)
KML -vector- (rw+v): Keyhole Markup Language (KML)
```

But `sf` does not seem to have access to `LIBKML`, only `KML`:
```
> st_drivers() %>% filter(name == 'KML' | name == 'LIBKML')
   name        long_name              write  copy  is_raster  is_vector  vsi
1  KML Keyhole Markup Language (KML)  TRUE   FALSE   FALSE      TRUE     TRUE
```

I have uninstalled and reinstalled both `GDAL` (using `Homebrew`) and `sf` (using `devtools`), even rebooting in between every step, and still `LIBKML` is not accessible to `sf`.

Here's what I'm running:
OS X 10.12.6
`RStudio`  1.0.153
`R`  3.5.3
`GDAL`  2.4.2
`sf`  0.7-7

If you have any advice, please, I would very much appreciate it.  Thank you for your time and consideration.  Please let me know if you need any additional information.

**Comment by edzer** [comment]
Maybe check here: https://github.com/r-spatial/stars/issues/202#issuecomment-519890669

**Comment by ar-puuk** [comment]
Hi @emochoa, did you find a solution to this? I have the same issue.

The discussion linked in the reply comment flies above my head. I am using:
Windows 11 26100.2605,
R 4.4.2,
RStudio 2024.12.0 Build 467,
sf 1.0-20, GEOS 3.12.2, GDAL 3.9.3, PROJ 9.4.1; sf_use_s2() is TRUE

**Comment by rsbivand** [comment]
@ar-puuk Note that GDAL provides two drivers, `KML` https://gdal.org/en/stable/drivers/vector/kml.html#vector-kml and `LIBKML`https://gdal.org/en/stable/drivers/vector/libkml.html . The latter needs GDAL built with the `libkml` library, which is not included in Windows binary builds IIRC. You may read and write kml files with the simpler (and better aligned with simple features) `KML` driver. If you need `libkml`, you'll have to build GDAL from source against that library yourself, which sounds like more than you are prepared to do.

**Comment by ar-puuk** [comment]
@rsbivand, the reason I am looking to use LIBKML instead of KML driver is because loading a kml file into an `sf` object clumps all the attributes together into a single "Description" column. For now, I have been converting KML to SHP using QGIS and then importing to R as an `sf` object, which has been inefficient for iterative tasks.

As with the first post on this issue, the GDAL I installed using OSGeo4W contains the LIBKML driver (if my understanding is correct).

```{r}
system("ogrinfo --version")
# GDAL 3.9.3, released 2024/10/07
# [1] 0

system("ogrinfo --formats", intern = TRUE) |> grep("KML", x = _, value = TRUE)
# [1] "  LIBKML -vector- (rw+v): Keyhole Markup Language (LIBKML) (*.kml, *.kmz)"
# [2] "  KML -vector- (rw+v): Keyhole Markup Language (KML) (*.kml)"  
```

Is there a way for me to use the Windows installation of GDAL (that includes LIBKML) with sf?

```{r}
sf::sf_extSoftVersion()
#          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
#      "3.12.2"        "3.9.3"        "9.4.1"         "true"         "true"        "9.4.1" 

sf::st_drivers(what = "vector", "KML")
#     name                     long_name write  copy is_raster is_vector  vsi
# KML  KML Keyhole Markup Language (KML)  TRUE FALSE     FALSE      TRUE TRUE
```

**Comment by rsbivand** [comment]
However, `sf` is not, and cannot be, built as a statically linked Windows binary package against GDAL from OSGeo4W. So your use of OSGeo4W is the best you can do. 

Maybe use the OSGEO4W `ogr2ogr` command line program run from the OSGeo4W shell to convert from KML to something `sf` can read. 

R (Rtools) uses UCRT and MXE cross-complied libraries, OSGeo4W uses versioned CRT, they are not compatible.
