### ISSUE TITLE
attach multiple geometries to `sf` ? 

### ISSUE THREAD

**Issue by rgzn** [r-spatial/sf#1106]
I've run into a very similar issue to this stackoverflow question : [compute pointwise distance by group in R with sf dplyr](https://stackoverflow.com/questions/54887209/compute-pointwise-distance-by-group-in-r-with-sf-dplyr)

The issue is if you have multiple `sfc` objects, between which you want to do some sort of geometric operation, like `st_distance`, but you only want to do this between features with matching values in some non-geometric columns. 

The easiest non-spatial, `dplyr` method of doing this style of comparison is to join the tibbles on the shared attributes:
```
left_join(tibble_1, tibble_2) %>% group_by(shared_filed) %>% summarise(function(geometry_1, geometry_2))
```

Because `sf` does not allow for multiple geometry fields in an `sfc` object, this style of operation is not possible. 

What is the `sf` preferred method for doing this computation?

The method in the accepted answer on the so question does not work due to a problem in crs interpretation. 

The alternative method proposed is very slow. 

Sorry if this is a dumb question.

**Comment by edzer** [comment]
`sf` does allow for multiple geometry list columns in an `sf` object, but all `sf` functions operate only on a single one (the _active_ geometry).

Given that the SO issue seems to be solved, what exactly is your new issue here? 

If you are interested in distances between groups of geometries, summarize them, this computes the groupwise union, which then is used in distance evaluation.

**Comment by rgzn** [comment]
Sorry I misunderstood an aspect of `sf`.

There is still this issue in the accepted SO answer:

> hmm, unfortunately this solution doesn't work in my real world application. it complains about x and y not having the same crs, even though st_crs(d_sf) == st_crs(centers_sf) is TRUE. something breaks inside that map2 call i think  - Florian Oswald

But I think that is a separate issue. Closing this.
