### ISSUE TITLE
Question: Why does `st_ll_sample()` remove crs?

### ISSUE THREAD

**Issue by rgzn** [r-spatial/sf#1107]
`st_sample()` sets crs to `NA` when called on `LINESTRING` objects that are in longlat format, but not many other objects.

This is in function `st_ll_sample()`  here:

https://github.com/r-spatial/sf/blob/3fbac2885deac5ba1de5d60f9aebe30bb30bad5b/R/sample.R#L143-L147

And these lines were added in this fix:
https://github.com/r-spatial/sf/commit/14903624da442fd2b8e4c8bef99e85f42e9668f1

It seems that it was to fix some other bug but I don't understand why crs should not be preserved in this case when it is in other cases. It causes some unexpected behavior.

**Comment by edzer** [comment]
Could you please check whether this does what you need?

**Comment by rgzn** [comment]
Thanks!
