### ISSUE TITLE
Package does not load

### ISSUE THREAD

**Issue by fishkey** [r-spatial/sf#1108]
Hello,

I can't get this package to load. I opened R, copy and pasted install.packages("sf") from the git page, it successfully unpacked, and then when I entered library(sf), I received this error:

Error: package or namespace load failed for ‘sf’:
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found
In addition: Warning message:
package ‘sf’ was built under R version 3.5.3 

I then closed R, reopened it, and tried the second method listed on the git page: library(devtools)
install_github("r-spatial/sf"). 
It took about 5 minutes to load everything, and then when I entered library(sf), I received this error message:

Error: package or namespace load failed for ‘sf’:
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found

I'm not really sure why I can't get this package to load. I have done exactly as described. Any ideas?

Thanks for your time,
Matt

**Comment by edzer** [comment]
You'll have to update package dplyr.

**Comment by fishkey** [comment]
Thank you! I'm not sure how you gleaned that from the error, but thanks nonetheless.

**Comment by edzer** [comment]
Did you search the sf issues for `group_map`?

**Comment by heather340** [comment]
Hi! I'm  also getting this error but my dplyr looks to be updated: 

Loading required package: ggplot2
Loading required package: grid
Error: package or namespace load failed for ‘ggsn’:
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found
In addition: Warning message:
package ‘ggsn’ was built under R version 3.5.2 
# and 
> library(tidyverse)
── Attaching packages ───────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.1.0     ✔ purrr   0.2.5
✔ tibble  2.1.3     ✔ dplyr   0.8.3
✔ tidyr   0.8.2     ✔ stringr 1.3.1
✔ readr   1.3.1     ✔ forcats 0.3.0

**Comment by edzer** [comment]
Please show complete information:
- start R without loading any package
- load sf
- show the complete output of R, not sections
- show the complete output of sessionInfo() at that point
