### ISSUE TITLE
[st_distance] Haussdorf distance is same as euclidean. 

### ISSUE THREAD

**Issue by rgzn** [r-spatial/sf#1109]
`st_distance(x,y, which = "Haussdorf")` produces the same result as the default `which = "Euclidean"` in geometries where they should not be equal. 

The Haussdorf distance is "the greatest of all the distances from a point in one set to the closest point in the other set". Therefore for two disjoint polygons of non-zero area in the same plane, the Haussdorf distance should be greater than the euclidean distance. 

Here is a reprex:

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3

nc <- st_read(system.file("shape/nc.shp", package="sf"))
poly1 <- nc[1,]
poly2 <- nc[3,]

ggplot() +
  geom_sf(data = poly1) +
  geom_sf(data = poly2)
```
![](https://i.imgur.com/owe1wR6.png)
``` r

st_distance(poly1, poly2, which = "Euclidean") == 
  st_distance(poly1, poly2, which = "Haussdorf")
#>      [,1]
#> [1,] TRUE
```

<sup>Created on 2019-07-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by edzer** [comment]
Thanks! That was a bit sloppy indeed. You will now get a (hopefully) informative error message.
