### ISSUE TITLE
`st_bind_cols()` misleading warning message

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/sf#1111]
It is possible to bind an sf object and a data.frame by column using the `bind_cols()` function. The downside - it requires **dplyr**. Alternatively, `st_bind_cols()` can be used, but it also gives a warning back suggesting using the `cbind()` function instead. However, `cbind()` did not work in those cases.
@edzer I do not know what is the best action to do in this case - I just want to make you aware of this case.

Related issues: https://github.com/r-spatial/sf/issues/92

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(spData)

crs = st_crs(3857)
d = st_sf(a = 4, 
          geomc = st_sfc(st_multilinestring(list(matrix(1:4, 2)))), 
          crs = crs)

df = data.frame(x = 3)

# works but requires dplyr
dplyr::bind_cols(d, df)
#> Simple feature collection with 1 feature and 2 fields
#> geometry type:  MULTILINESTRING
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 3 xmax: 2 ymax: 4
#> epsg (SRID):    3857
#> proj4string:    +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs
#>   a                        geomc x
#> 1 4 MULTILINESTRING ((1 3, 2 4)) 3

# works but gives a warning
st_bind_cols(d, df)
#> Warning: 'st_bind_cols' is deprecated.
#> Use 'cbind' instead.
#> See help("Deprecated")
#> Simple feature collection with 1 feature and 2 fields
#> geometry type:  MULTILINESTRING
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 3 xmax: 2 ymax: 4
#> epsg (SRID):    3857
#> proj4string:    +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs
#>   a x                        geomc
#> 1 4 3 MULTILINESTRING ((1 3, 2 4))

# works, but not as expected
cbind(d, df)
#>       d      df
#> a     4      3 
#> geomc List,1 3
```

<sup>Created on 2019-07-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Have you read the documentation of `cbind.sf`?

**Comment by Nowosad** [comment]
Yes, I did. I still think the warning message is misleading. 

Right now the message is:
```r
Warning: 'st_bind_cols' is deprecated.
Use 'cbind' instead.
```
It suggests `cbind()` as a solution to this problem (it is not). 
How about changing the message to something like:

```r
Warning: 'st_bind_cols' is deprecated.
Use 'cbind' instead when all arguments to be binded are of class sf.
If you need to cbind a data.frame to an sf, use 'st_sf' or 'bind_cols'.
```

**Comment by edzer** [comment]
That is a good idea. However, `st_sf(df, d)` or `st_sf(d, df)` both don't work, and `bind_cols` would need to be `dplyr::bind_cols`.

**Comment by edzer** [comment]
And then, the idea of deprecating is that functions will eventually be removed.

**Comment by Nowosad** [comment]
Sure, I understand.
I've opened a new PR - https://github.com/r-spatial/sf/pull/1112. It just adds a longer message. I think it could be useful to some users before you decide to remove this function.
