### ISSUE TITLE
Merge and all.x=TRUE

### ISSUE THREAD

**Issue by davidorme** [r-spatial/sf#1114]
I'm trying to merge a dataframe on to an sf object and get an error. It's an odd corner case: when the data.frame is the first argument to the merge and when `all.x=TRUE`. When the sf object is first, and `all.y=TRUE` the behaviour is as expected - unmatched rows in `y` are filled in with empty geometries, just as a merge on two data frames fills in with NA. 

The other way around, the merge fails when it encounters a non-matching row:

```r
> x <- data.frame(name=LETTERS)
> y <- data.frame(name=LETTERS[1:13], letters[14:26])
> y$geometry <- st_sfc(st_point(c(0,0)))
> y <- st_sf(y)
> merge(x, y, all.x=TRUE)
Error in vapply(lst, class, rep(NA_character_, 3)) : 
  values must be length 3,
 but FUN(X[[14]]) result is length 1
```

This occurs in the binary install of 0.7-6 on Mac OS 10.14.5. I haven't tried 0.7-7 - need to fight the Kyngchaos framework and brew installs on my machine to get that to install.

Cheers,
David

**Comment by edzer** [comment]
Nice catch! Should work now. 

Note that this path, `merge.data.frame` is called which is outside `sf`'s hands and so will return a `data.frame`, not an `sf` object; pass it through `st_sf` to set it back to `sf`.

**Comment by davidorme** [comment]
Yes, that makes sense: methods dispatch makes it inevitable, so `merge(sf, data.frame)` is required to avoid losing the class. I'll do it that way around but thanks for the quick fix too.
