### ISSUE TITLE
n_empty attribute of sfc not updating

### ISSUE THREAD

**Issue by davidorme** [r-spatial/sf#1115]
I'm piecing together an `sf` object where geometries come from a couple of sources, so I'm inserting geometries into the geometry field `sfc` object. That makes the `n_empty` attribute of the field reported in the `print.sfc` method inaccurate (and hence also in the output of `print.sf`):

```r
> x <- st_as_sfc(list(st_point(c(0,0)), NULL))
> x
Geometry set for 2 features  (with 1 geometry empty)
geometry type:  POINT
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 0 ymax: 0
epsg (SRID):    NA
proj4string:    NA
POINT (0 0)
POINT EMPTY
> x[2] <- st_point(c(1,1))
> x
Geometry set for 2 features  (with 1 geometry empty)
geometry type:  POINT
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 0 ymax: 0
epsg (SRID):    NA
proj4string:    NA
POINT (0 0)
POINT (1 1)
```
I think the solution is probably to define a `[<-.sfc` method that recalculates `n_empty` - that seems cheaper than always having to calculate `n_empty` when printing?

Thanks,
David

**Comment by davidorme** [comment]
Ha. There already is such a method - must have botched my `grep` on the package source. Thanks for the quick fix!

**Comment by edzer** [comment]
This may be easier:
```r
> library(sf)
Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0
> methods(`[<-`)
 [1] [<-,data.frame-method [<-.data.frame        [<-.Date             
 [4] [<-.factor            [<-.numeric_version   [<-.POSIXct          
 [7] [<-.POSIXlt           [<-.raster*           [<-.sfc*             
[10] [<-.ts*               [<-.unit*            
see '?methods' for accessing help and source code
```
