### ISSUE TITLE
st_nearest_feature not working on Ubuntu 16.04 RStudio Connect server

### ISSUE THREAD

**Issue by chrisjkeeney** [r-spatial/sf#1117]
I am using RStudio Connect to host an API on my Ubuntu 16.04 server.  The RStudio Connect server uses R 3.6.1 compiled by source.  My geos version is 3.7.2

My Api grabs a shape file from [NOAA Shoreline](https://shoreline.noaa.gov/data/datasheets/medres.html) and calculated the distance to coast with a given Lat/Lon.

Below is the code I use for the API. The API works just fine when I run it locally, but not when it's posted onto the server.  I created a different version where I use geosphere's function dist2Line and that works just fine, but is much slower than st_nearest_feature.  What Am I missing here?

`require(plumber)
require(sf)
require(rgdal)
require(tidyverse)

#* Return the distance to coast
#* @param lon is the longitude
#* @param lat is the latitude
#* @post /distance

function(lon,lat){
  coords <- data.frame(Longitude = as.numeric(lon), Latitude = as.numeric(lat)) %>% 
    st_as_sf(coords = c('Longitude','Latitude'))
  shape <- st_read("us_medium_shoreline.shp")
  st_nearest_feature(coords,shape)/1609
}`

**Comment by edzer** [comment]
My guess is that st_nearest_feature assumes Carthesian coordinates, where you have geodetic coordinates, meaning that it doesn't do the right thing (unless you project your data first).
