### ISSUE TITLE
Typo in st_distance() documentation

### ISSUE THREAD

**Issue by jfsmenezes** [r-spatial/sf#1118]
Hi,

In the documentation of st_distance(), Hausdorff distance is written as "Haussdorf". However, Hausdorff must be written correctly or the function outputs an error.
 
As a side note, it was difficult to figure out that the problem was a typo. If you copy and paste the distance name from the documentation in the function, the function gives the error "wrong value for op". It was not clear at first glance that "op" refers to the name of distance. Perhaps it would also be possible to write a more intuitive error message?

Thanks

**Comment by edzer** [comment]
Thanks!
