### ISSUE TITLE
MapboxVectorTiles: alignment of geometry and fields

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/sf#1119]
In this file  `6160.mvt`  (attached)  [obtained from Mapbox](https://docs.mapbox.com/vector-tiles/reference/)  there are mismatched rows of attributes and numbers of geometries. 

The first layer `landuse` has 84 rows of attributes (it's padded?), and only 81 geometries. It seems clear that the last 4 rows are padding, because all fields but `mvt_id` are the empty string. 

This causes error on read. 

```R
library(sf)

read_sf("6160.mvt", layer = "landuse")
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  NULL error in sfc_from_ogr

```

We can check that `OGR_GEOMETRY` (the WKT type name) is not empty. 

```R
read_sf("6160.mvt",  query = "SELECT * FROM landuse WHERE OGR_GEOMETRY != ''")

Simple feature collection with 81 features and 3 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: 1218 ymin: 971 xmax: 4096 ymax: 4096
epsg (SRID):    NA
proj4string:    NA
# A tibble: 81 x 4
   mvt_id class type                                                                     `_ogr_geometry_`
    <dbl> <chr> <chr>                                                                      <MULTIPOLYGON>
 1      0 park  park  (((1841 1807, 1880 1794, 2123 1774, 2140 1739, 2110 1565, 2098 1471, 2100 1444, 21…
 2      0 park  park  (((1705.81 4096, 1928 3974, 1810 3766, 1844 3749, 1826 3681, 1885 3664, 1837 3514,…
 3      0 park  park    (((2232 3823, 2516 3667, 2583 3640, 2542 3514, 2443 3170, 2145 3362, 2232 3823)))
 4      0 park  park  
... 
```

We get the same result by checking that `class` is not empty - it seems the [names of the geometries](https://gdal.org/doxygen/classOGRFeature.html#ae7254201e4d96e8429c2509194740d58) is the thing to match (81 valid rows, then ignore the last 4). 

```R
read_sf("6160.mvt",  query = "SELECT * FROM landuse WHERE class != ''")
Simple feature collection with 81 features and 3 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: 1218 ymin: 971 xmax: 4096 ymax: 4096
epsg (SRID):    NA
proj4string:    NA
# A tibble: 81 x 4
   mvt_id class type                                                                     `_ogr_geometry_`
    <dbl> <chr> <chr>                                                                      <MULTIPOLYGON>
 1      0 park  park  (((1841 1807, 1880 1794, 2123 1774, 2140 1739, 2110 1565, 2098 1471, 2100 1444, 21…
 2      0 park  park  (((1705.81 4096, 1928 3974, 1810 3766, 1844 3749, 1826 3681, 1885 3664, 1837 3514,…
 3      0 park  park    (((2232 3823, 2516 3667, 2583 3640, 2542 3514, 2443 3170, 2145 3362, 2232 3823)))
 4      0 park  park  (((367
...
```

EDIT: missing attachment added, this is the 6160.mvt zipped 

[6160.mvt.zip](https://github.com/r-spatial/sf/files/3483823/6160.mvt.zip)

**Comment by mdsumner** [comment]
Ah, so it's because these tiles are *instances* from a global layer. Sometimes there's no geometry for a given tile, but the index and identity of features does of course not change. 

https://lists.osgeo.org/pipermail/gdal-dev/2019-August/050633.html

I think it means the easiest solution is a format-specific approach, where you detect the situation and flesh out empty geoms - or optionally drop them. From Even's reply I think the only way to tell (beyond some format-expectations) is to iterate the features.

**Comment by edzer** [comment]
I'd like to look into this, but can't find the file you say was attached.

**Comment by mdsumner** [comment]
Doh! Attached now, general access to this is with 

```
http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v7/14/4823/6160.mvt?access_token=<MAPBOX-TOKEN>
```

**Comment by edzer** [comment]
Thanks. Instead of the unhelpful error, should we return an empty geometry in the cases where the OGRGeometry is `NULL`? At least that gives access to the records, and allows for filtering the `sf` object.

**Comment by edzer** [comment]
gives:
```r
> library(sf)
Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0
> x = read_sf("6160.mvt")
Warning message:
In evalq((function (..., call. = TRUE, immediate. = FALSE, noBreaks. = FALSE,  :
  automatically selected the first layer in a data source containing more than one.
> x
Simple feature collection with 85 features and 3 fields (with 4 geometries empty)
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: 1218 ymin: 971 xmax: 4096 ymax: 4096
epsg (SRID):    NA
proj4string:    NA
# A tibble: 85 x 4
   mvt_id class type                                                    geometry
    <dbl> <chr> <chr>                                             <MULTIPOLYGON>
 1      0 park  park  (((1841 1807, 1880 1794, 2123 1774, 2140 1739, 2110 1565,…
 2      0 park  park  (((1705.81 4096, 1928 3974, 1810 3766, 1844 3749, 1826 36…
 3      0 park  park  (((2232 3823, 2516 3667, 2583 3640, 2542 3514, 2443 3170,…
 4      0 park  park  (((3677.725 4096, 3733 4063, 3752 4061, 3900 3973, 3909 3…
 5      0 park  park  (((2087 1643, 2063 1603, 2045 1534, 2065 1467, 2069 1389,…
 6      0 park  park  (((1319 2266, 1340 2251, 1341 2244, 1298 2243, 1273 2197,…
 7      0 park  park  (((1773 2596, 1866 2546, 1834 2440, 1809 2390, 1669 1885,…
 8      0 park  park  (((1974 1759, 2022 1756, 2049 1743, 2068 1716, 2070 1675,…
 9      0 park  park  (((1926 3072, 1996 3056, 1980 2963, 1879 2603, 1847 2626,…
10      0 park  park  (((1365 2671, 1533 2577, 1359 2263, 1340 2287, 1330 2291,…
# … with 75 more rows
```

**Comment by mdsumner** [comment]
I think that's more faithful to the overall data set, especially since there's no ID for features - I see that this is the line that allows the larger feature count for allocation: 

https://github.com/r-spatial/sf/blob/master/src/gdal_read.cpp#L197

and so maybe an `allow_empty_feature` option  at the top would be good - I don't have a strong position, the definition of a feature amongst all this seems confusing - and this fix is enough.

**Comment by edzer** [comment]
Thanks - It seems easiest to handle `allow_empty_feature` at the R level, right now, so I leave it until someone comes up with a strong reason or demand for that.
