### ISSUE TITLE
report proj API ?

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#1124]
I thought of providing a PR, but I don't know Rcpp and guess proj.cpp should not be mixed up with SEXP functions, so I prefer not to send what I have. The idea would be to have a stub function just returning the value of defined(HAVE_PROJ_H) && !defined(ACCEPT_USE_OF_DEPRECATED_PROJ_API_H) as a logical, so that the user can check which API is being used.

**Comment by edzer** [comment]
as part of `sf_extSoftVersion()`?

**Comment by edzer** [comment]
```r
> library(sf)
Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0
> sf_extSoftVersion()
          GEOS           GDAL           PROJ GDAL_with_GEOS     USE_PROJ_H 
       "3.7.0"        "2.4.0"        "5.2.0"         "true"        "false" 
```

**Comment by rsbivand** [comment]
Thanks!

Still stuck, though, as `sf::st_transform()` uses GDAL, which may or may not use `proj.h`, and `lwgeom::st_transform_proj()` in the CRAN **lwgeom** version uses `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H`. I'll put up a reprex tomorrow.

**Comment by edzer** [comment]
Can't you `try()` `sf::st_transform` with a proj string that is only allowed under the proj.h API?

**Comment by rsbivand** [comment]
This is a single point in a GPKG from https://github.com/rsbivand/geomed19-workshop, Geomed19_II.Rmd basis:
[xy_c.zip](https://github.com/r-spatial/sf/files/3491545/xy_c.zip)
```
xy_c <- st_read("xy_c.gpkg")
st_coordinates(xy_c)
# 295460.1 9120358
# without CA7072_003.gsb
st_coordinates(st_transform(xy_c, 31985))
# 295489.3 9120352
xy_c1 <- xy_c
st_crs(xy_c1) <- "+proj=utm +zone=25 +south +ellps=intl +units=m +nadgrids=CA7072_003.gsb"
print(st_coordinates(st_transform(xy_c1, 31985)), digits=9)
# 295486.396 9120350.62
# without CA7072_003.gsb
xy_c2 <- xy_c
st_crs(xy_c2) <- "+proj=utm +zone=25 +south +ellps=intl +units=m +towgs84=-206.05,168.28,-3.82,0,0,0,0"
st_coordinates(st_transform(xy_c2, 31985))
# 295488.6 9120352
```
This is the NTv2 grid file to (maybe) put in share/proj:
[CA7072_003.zip](https://github.com/r-spatial/sf/files/3491552/CA7072_003.zip) obtained from https://www.eye4software.com/hydromagic/documentation/ntv2/.

Note that **lwgeom** is built using `proj_api.h`, but:

```
# +towgs84= from read
> st_coordinates(lwgeom::st_transform_proj(xy_c, 31985))
         X       Y
1 295489.3 9120352
# +nadgrids=
> st_coordinates(lwgeom::st_transform_proj(xy_c1, 31985))
         X       Y
1 295486.4 9120351
# alternative +towgs84= 
> st_coordinates(lwgeom::st_transform_proj(xy_c2, 31985))
         X       Y
1 295488.6 9120352
```

I'm also being puzzled by possible caching of share/proj files, so that it seems that even when I've removed the NTv2 file (so it shouldn't be used), it looks as though some paths still pick it up.
