### ISSUE TITLE
binary predicate with user-defined overlap area threshold?

### ISSUE THREAD

**Issue by kendonB** [r-spatial/sf#1125]
I have a case where I have polygon files that change over time but actual locations of the boundaries shift a bit. So, polygon 4 in 2003 might correspond to polygon 4 in 2008 but because the boundaries don't remain literally identical an `st_join` pulls in neighbouring polygons based on slivers of overlap with the surrounding polygons.

So, it would be good to be able to do something like:
```r
polygon_1 %>% 
  st_join(polygon_2, join = st_overlaps_with_threshold, threshold = 0.1)
```
The above would pull in information for those elements of `polygon_2` that have a sufficiently large overlap with a row of `polygon_1`. The test would be that the ratio of the intersection polygon to the _minimum_ area of the two parent polygons was above 0.1.

To illustrate the problem:

[polygons.zip](https://github.com/r-spatial/sf/files/3490889/polygons.zip)

``` r
library(tidyverse)
library(sf)

polygon_1 = readRDS("polygon_1.rds")
polygon_2 = readRDS("polygon_2.rds")

polygon_1 %>% 
  st_join(polygon_2 %>% select(geometry), left = FALSE, join = st_overlaps) %>%
  ggplot() + 
  geom_sf() + 
  geom_sf(data = polygon_2, fill = "blue", alpha = 0.5, color = "red")
```

![](https://i.imgur.com/2q5uyck.png)

<sup>Created on 2019-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by etiennebr** [comment]
Maybe https://github.com/dgrtwo/fuzzyjoin could help, although I think it doesn't do what you need. From what I understand, I would compute the area of intersection between every pair of polygons (or optimize if it's too large), pick the largest overlap for each polygon, then join attributes on that id.

**Comment by edzer** [comment]
You'll have to write your `st_overlaps_with_threshold` function that does exactly what you want, and behaves like `st_intersects` and all those similar binary predicate functions (essentially: a list of the matching indexes for each feature).

**Comment by dbaston** [comment]
Maybe it's best approached as a documentation issue: how two write a custom predicate?

**Comment by edzer** [comment]
Here you go:
```r
library(tidyverse)
library(sf)

polygon_1 = readRDS("polygon_1.rds")
polygon_2 = readRDS("polygon_2.rds")

st_overlaps_with_threshold = function(x, y, threshold) {
    int = st_intersects(x, y)
    lapply(seq_along(int), function(ix)
        if (length(int[[ix]]))
            int[[ix]][which(st_area(st_intersection(x[ix,], y[int[[ix]],])) > threshold)]
        else
            integer(0)
    )
}   

polygon_1 %>%
  st_join(polygon_2, left = FALSE,
    join = st_overlaps_with_threshold, threshold = units::set_units(1000, m^2)) %>%
  ggplot() + 
  geom_sf() + 
  geom_sf(data = polygon_2, fill = "blue", alpha = 0.5, color = "red")
```
![x](https://user-images.githubusercontent.com/520851/63383399-fdb01280-c39c-11e9-8ac2-9c9cab0ce7a1.png)

Does anyone see a more elegant solution that could go into the docs?
