### ISSUE TITLE
select() and filter() compatibility with st_read()

### ISSUE THREAD

**Issue by pinehowe** [r-spatial/sf#1127]
Hello,

I was wondering if it is possible to make the select() and filter() from dplyr compatible with st_read() so that you could use a pipeline of selecting columns and filtering data that you want directly in st_read, with similar behavior to the query options currently used. 

Example: st_read(dsn="mydata", layer="layer1", select(year:col5), filter(year > 2000))

Or: st_read(dsn="mydata", layer="layer1", options= select(year:col5) %>% filter(year > 2000))

**Comment by Nowosad** [comment]
Hi @pinehowe - it is already possible. See the last example in this section https://geocompr.robinlovelace.net/attr.html#vector-attribute-subsetting.

**Comment by pinehowe** [comment]
> https://geocompr.robinlovelace.net/attr.html#vector-attribute-subsetting



> Hi @pinehowe - it is already possible. See the last example in this section https://geocompr.robinlovelace.net/attr.html#vector-attribute-subsetting.

This might be me being dense, but from my understanding, the current implementation only works once the data is loaded into the R session, but cannot be used instead of query in st_read.

**Comment by edzer** [comment]
There are no plans to make things work the way you'd like. If you _need_ selection during read e.g. because the dataset is too large otherwise, look into the `query` argument of `st_read`.

**Comment by pinehowe** [comment]
> There are no plans to make things work the way you'd like. If you _need_ selection during read e.g. because the dataset is too large otherwise, look into the `query` argument of `st_read`.

@edzer That is totally reasonable, just thought I would ask. Thanks!
