### ISSUE TITLE
st_read does not read the style field of DXF file (OGR feature style info)

### ISSUE THREAD

**Issue by faridcher** [r-spatial/sf#1131]
Hi,

notice the Style field of the first OGRFeature.

```bash
$ ogrinfo b.dxf entities | head -n 25

INFO: Open of `b.dxf'
      using driver `DXF' successful.

Layer name: entities
Geometry: Unknown (any)
Feature Count: 447
Extent: (31.241719, 4.491139) - (126.120570, 87.319495)
Layer SRS WKT:
(unknown)
Layer: String (0.0)
PaperSpace: Integer(Boolean) (0.0)
SubClasses: String (0.0)
Linetype: String (0.0)
EntityHandle: String (0.0)
Text: String (0.0)
OGRFeature(entities):0
  Layer (String) = 3
  SubClasses (String) = AcDbEntity:AcDbLine
  Linetype (String) = DASHDOT
  EntityHandle (String) = FA
  Style = PEN(c:#ffff00,w:0.5g,p:"0.5g 0.2g 0.1g 0.2g")
  LINESTRING Z (90.3454201528005 51.3719795492818 0,102.33059403266 51.9749901946629 0)

OGRFeature(entities):1
  Layer (String) = 3
```

No Style field shows up with `st_read`:
```R
x <- st_read('b.dxf', as_tibble = FALSE, stringsAsFactors = TRUE)
names(x)
Layer PaperSpace SubClasses Linetype EntityHandle Text geometry
```
I am on Debian testing with GDAL 2.4.2 and the dev version of sf compiled manually.
relevant:
https://gdal.org/drivers/vector/dxf.html

[b.zip](https://github.com/r-spatial/sf/files/3512426/b.zip)

thanks

**Comment by edzer** [comment]
style field may be something particular of dxf files, it is not part of the simple feature standard, which `sf`  tries to implement.

**Comment by faridcher** [comment]
Not quite specific to DXF driver but also other drivers like KML, MapInfo, JML and PDF. Please see https://gdal.org/user/ogr_feature_style.html
Does it mean `sf` will never read this field?

**Comment by edzer** [comment]
If there is a good reason to do so, and if someone provides a simple and clean PR for it, I see no reason why not, most style couldn end up as a  attribute variable in an `sf` objects. IMO it also only makes sense if the style (etc) would be interpreted correctly by R's plotting routines.

**Comment by faridcher** [comment]
Because CAD and its related formats (DWG, DXF, etc.) do not support attributes as we have them in a database, people tend to use style information such as line type, line width, etc. as information. I have tons of DXF files that use a linestring style (e.g. linetype, linewidht) to define a boundary type e.g. wall, door, etc. My goal is to map this style information to feature attributes. 
I think right now I am unable to provide a PR for this because my C++ knowledge is limited but will try in future.

thanks

**Comment by faridcher** [comment]
I found a solution. We need to specify the OGR_STYLE field explicitly in the sql query to the dxf file as in:

```r
x <- st_read('b.dxf',query='select *, OGR_STYLE from entities', as_tibble = FALSE, stringsAsFactors = TRUE)
```

works as expected.
