### ISSUE TITLE
r-spatial/sf install fails: proj.h presence, usability "no" (Centos 7.6)

### ISSUE THREAD

**Issue by jbsysadmin** [r-spatial/sf#1134]
Greetings.
Given a Centos 7.6 OS, and the environment settings below, what other conditions are needed to install r-spatial/sf ?

(Note that the "missing" proj.h is in fact at /usr/local/company/dept/proj-6.1.1-x86_64/include)

This fails when running R interactively (with "R" or prepending env to that statement) and also when invoking this way:

/bin/R -e "install.packages('remotes', repos='http://archive.linux.duke.edu/cran')"
/bin/R -e "remotes::install_github('r-spatial/sf', configure.args = '--with-gdal-config=/usr/local/company/dept/gdal-3.0.1-x86_64/bin/gdal-config --with-proj-include=/usr/local/company/dept/proj-6.1.1-x86_64/include/ --with-proj-lib=/usr/local/company/dept/proj-6.1.1-x86_64/lib/')" 

Changing the end of "with-proj-lib" to proj-6.1.1-x86_64/share/proj made no difference.

I need it to work both ways: command-line & last-resort interactive. The goal is an install of monocle3 (https://cole-trapnell-lab.github.io/monocle3/monocle3_docs/#installing-monocle-3), and this is the last dependency. Thank you for any leads.

A selection of the error output is at bottom.

Regards,
-John
export PATH=/usr/local/company/dept/proj-6.1.1-x86_64/bin:/usr/local/company/dept/proj-6.1.1-x86_64/lib:/usr/local/company/dept/proj-6.1.1-x86_64/include:$PATH
export LD_LIBRARY_PATH=/usr/local/company/dept/proj-6.1.1-x86_64/lib:/usr/local/company/dept/proj-6.1.1-x86_64/include:$LD_LIBRARY_PATH

export PATH=/usr/local/company/dept/gdal-3.0.1-x86_64/bin:/usr/local/company/dept/gdal-3.0.1-x86_64/include:/usr/local/company/dept/gdal-3.0.1-x86_64/lib:$PATH
export LD_LIBRARY_PATH=/usr/local/company/dept/gdal-3.0.1-x86_64/include:/usr/local/company/dept/gdal-3.0.1-x86_64/lib:$LD_LIBRARY_PATH

export PKG_CONFIG_PATH="/usr/local/company/dept/proj-6.1.1-x86_64/lib/pkgconfig"

=============================================================
Last section, error output:
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -m64 -std=gnu99 accepts -g... yes
checking for gcc -m64 -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -m64 -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/company/dept/gdal-3.0.1-x86_64/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: pkg-config proj exists, will use it
checking proj.h usability... no
checking proj.h presence... no
checking for proj.h... no
configure: error: proj.h not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/usr/lib64/R/library/sf’
Error: Failed to install 'sf' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp0ZOHeb/file8f6c2c49655/sf_0.8-0.tar.gz’ had non-zero exit status

**Comment by edzer** [comment]
What is the output of
```
pkg-config proj --modversion
```
?

**Comment by jbsysadmin** [comment]
Thank you for reply!
Output is:

6.1.1

-John

**Comment by jbsysadmin** [comment]
Are there any leads?

**Comment by edzer** [comment]
Pleas try with adding the flag `--with-proj-api=yes` to `configure.args`.

**Comment by edzer** [comment]
The Dockerfile modified in https://github.com/r-spatial/sf/commit/bec3611283e6320174b2deae6350a3538420613f runs for me; this is a bug, I still need to figure out why `--with-proj-api=no` (the default) does not work.

**Comment by edzer** [comment]
This line:

https://github.com/r-spatial/sf/blob/master/configure.ac#L351

needs to be replaced by a check that takes the non-standard locations into account.

**Comment by edzer** [comment]
Should work now, irrespective `--with-proj-api` setting.

**Comment by edzer** [comment]
That's a different problem. Do you have libsqlite3-dev installed?

**Comment by jbsysadmin** [comment]
Thanks for reply!

We run Centos 7.6.x. EPEL is enabled.
Is this the same?

-        Package sqlite-devel-3.7.17-8.el7.x86_64 already installed and latest version

**Comment by edzer** [comment]
Yes. I'm out of ideas.

**Comment by jbsysadmin** [comment]
One more question, then.

Should "proj-lib" always refer to /proj-6.1.1-x86_64/share/proj or /proj-6.1.1-x86_64/lib  ?

**Comment by edzer** [comment]
`--with-proj-lib` should point to a `lib` directory.
