### ISSUE TITLE
gdal_utils('rasterize', ...): uninformative error when target exists

### ISSUE THREAD

**Issue by johnbaums** [r-spatial/sf#1136]
When a destination file already exists, `gdal_utils('rasterize', ...)` fails, with a fairly obscure error message returned by CPL_gdalrasterize:

>Error in gdal_utils("rasterize", datasource, "out2.tif", options = c("-tr",  : 
  gdal_utils rasterize: an error occured
In addition: Warning message:
In CPL_gdalrasterize(source, destination, options) :
  GDAL Error 1: hDstDS != NULL but options that imply creating a new dataset have been set.

I was under the impression that gdal_rasterize would overwrite an existing target ("This file will be created (or overwritten if it already exists)", from [here](https://gdal.org/programs/gdal_rasterize.html)). 

Is this unsupported by the C API? If so, I wonder if it's worth clarifying the docs and/or the error message. 

```R
library(sf)
## Linking to GEOS 3.7.2, GDAL 2.4.1, PROJ 5.2.0
demo(nc, ask = FALSE, echo = FALSE)
## Reading layer `nc.gpkg' from data source `/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sf/gpkg/nc.gpkg' using driver `GPKG'
## Simple feature collection with 100 features and 14 fields
## Attribute-geometry relationship: 0 constant, 8 aggregate, 6 identity
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
## epsg (SRID):    4267
## proj4string:    +proj=longlat +datum=NAD27 +no_defs
e = as.character(st_bbox(nc))

gdal_utils('rasterize', datasource, "out.tif", 
          options = c("-tr", ".01", ".01", "-a", "AREA", "-te", e))

gdal_utils('rasterize', datasource, "out.tif", 
          options = c("-tr", ".01", ".01", "-a", "AREA", "-te", e))
## Error in gdal_utils("rasterize", datasource, "out.tif", options = c("-tr",  : 
##   gdal_utils rasterize: an error occured
## In addition: Warning message:
## In CPL_gdalrasterize(source, destination, options) :
##   GDAL Error 1: hDstDS != NULL but options that imply creating a new dataset have been set.
```

**Comment by edzer** [comment]
Thanks! This should solve it. I hope.

**Comment by johnbaums** [comment]
Perfect, thanks. Working nicely
