### ISSUE TITLE
sf version 0.7-7 not available for conda yet?

### ISSUE THREAD

**Issue by KoichiHashikawa** [r-spatial/sf#1137]
Hi,

related to my question in classInt package,an analysis package requires sf v 0.7-7.
it seems that conda install -c conda-forge r-sf is installing v 0.7-6.
Will 0.7-7 be available for conda sometime soon?

thanks!

**Comment by edzer** [comment]
sf 0.7-7 is on CRAN, so you will need to ask the maintainer of the sf-r-anaconda distribution, that's not me/us.
