### ISSUE TITLE
st_difference between polygons generates lines 

### ISSUE THREAD

**Issue by rusca07** [r-spatial/sf#1138]
Hello,
I am trying to perform an st_difference between 2 overlapping polygons, with the aim of obtaining as a result the areas that do not overlap, as shown in the image.
![image](https://user-images.githubusercontent.com/23371750/64094165-72b41c80-cd8d-11e9-8cbe-dcbaed482f5c.png)

I read both shapefiles with st_read and perform:

original.fire<- st_set_precision(st_buffer(st_make_valid(original.fire), dist = 0), 1000000)
and
overlap.pixels<- st_set_precision(st_buffer(st_make_valid(overlap.pixels), dist = 0), 1000000)

I then use st_difference in the following way:
clean.fire<-st_difference(original.fire,st_union(st_combine(overlap.pixels)))

I have a few of these to do, and this works for most of my cases. But for one of the combinations (the one shown), this generates a set of lines:

![image](https://user-images.githubusercontent.com/23371750/64093711-0a187000-cd8c-11e9-920c-8bbd3c2e271e.png)

This prevents me from using this file in subsequent spatial analysis operations (eg st_intersection).

Any suggestion of what could be going wrong? 
Thank you very much in advance for your time.

**Comment by dbaston** [comment]
Can you share the polygonal inputs to `st_difference` that produce lines in the result?

**Comment by rusca07** [comment]
Thanks!

[fire_overlap_2002.zip](https://github.com/r-spatial/sf/files/3572179/fire_overlap_2002.zip)

**Comment by dbaston** [comment]
I'm not seeing the issue; can you let me know what GEOS version you're using, or if there is something about the reproducible example below that's inconsistent with what you're doing?

```
library(sf)
library(lwgeom)

download.file('https://github.com/r-spatial/sf/files/3572179/fire_overlap_2002.zip', 'fire_overlap.zip')

unzip('fire_overlap.zip', junkpaths = TRUE)

overlap.pixels <- st_read('overlap2001-2002.shp')
original.fire <- st_read('sw_gvd_2002_FireScars_MGA51_att.shp')

original.fire <- st_set_precision(st_buffer(st_make_valid(original.fire), dist = 0), 1000000)
overlap.pixels <- st_set_precision(st_buffer(st_make_valid(overlap.pixels), dist = 0), 1000000)

a <- original.fire
b <- st_union(st_combine(overlap.pixels))

clean.fire <- st_difference(a, b)

unique(st_geometry_type(clean.fire))
# [1] POLYGON      MULTIPOLYGON

```

I should mention that my interest here is in seeing what inputs to GEOS cause linestrings to appear in the result. But your problem is probably most easily solved by filtering these lines out of the result.

**Comment by rusca07** [comment]
Thanks very much for your answer!

I am using GEOS 3.6.1.

The code you provided does exactly what I do, and I get the same result, my output polygon has only polygons and multpolygons as geometry types as well (I had already checked that, maybe I should have mentioned it in my original message, my bad. In fact I tried filtering out only polygons from that feature and nothing changed).  I am not sure if you inspected the output polygon in the coordinates I mentioned in my first message, the lines are still there, but they are not being picked up as strings or lines, they are considered part of a multipolygon (when you select them with arcmap, the whole adjacent polygon gets highlighted).

**Comment by dbaston** [comment]
Oh, I see. You don't actually have any lines, only very narrow polygons. Maybe you could filter them out by area:

```
clean.fire %>%
  st_cast('MULTIPOLYGON') %>%
  st_cast('POLYGON', warn=FALSE) %>%
  filter(st_area(.) > units::set_units(1, m^2)) %>%
  group_by(id) %>%
  summarize(geometry = st_combine(geometry))
```
