### ISSUE TITLE
Errors attempting to link sf to GEOS

### ISSUE THREAD

**Issue by samaperrin** [r-spatial/sf#1139]
I am attempting to use the `st_nearest_feature` function in sf, at which point I am told that I need GEOS version 3.6.1. I have tried reinstalling the rgeos package and then GEOS 3.6.3 from source, however when I load sf I still get the following message.

`Linking to GEOS 3.5.1, GDAL 2.2.2, PROJ 4.9.2`

I have tried re-installing sf, to which i get the following error message:

```
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/samp/R/x86_64-pc-linux-gnu-library/3.4/sf/libs/sf.so':
  /home/samp/R/x86_64-pc-linux-gnu-library/3.4/sf/libs/sf.so: undefined symbol: GEOSSTRtree_nearest_generic_r
```
Based on previous errors of this nature I am guessing it has something to do with multiple geos installations? However I have no idea how to fix this.

I am running Ubuntu 16.04 LTS. Apologies for the poor explanation, I'm still not particularly adept with Linux.

**Comment by edzer** [comment]
Remove the packaged GEOS by `apt-get remove libgeos-dev` maybe, then reinstall GEOS, then recompile sf? Look what removing does before you say "yes".

**Comment by samaperrin** [comment]
When I reinstall GEOS using `sudo apt-get install libgeos-dev`, it always seems to reinstall version 3.5.1. Have updated and upgraded the system a few times.

**Comment by edzer** [comment]
I suggested to remove it.

**Comment by dbaston** [comment]
You may find that putting the following line in your `~/.Rprofile` also resolves the issue:

`dyn.load('/usr/local/lib/libgeos_c.so', local=FALSE)`

**Comment by samaperrin** [comment]
Have followed the advice above and am still getting the same result. I initially compiled GEOS 3.6.3. from source, which is now in /usr/local/src/, could be that sf is not correctly linking to it?
