### ISSUE TITLE
GDAL-3.1.0 PROJ-6.0.0 sf build

### ISSUE THREAD

**Issue by chris-english** [r-spatial/sf#1140]
ubuntu-16.04
source build of gdal and proj6
~$ gdal-config --version
3.1.0
~$ pkg-config proj --modversion
6.0.0
gdal-config --ogr-enabled
yes
Following from #1085
~$ export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
~$ R
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

remotes::install_github('r-spatial/sf', configure.args=('--with-gdal-config=/usr/local/bin/gdal-config --with-proj-lib=/usr/local/lib --with-proj-include=/usr/local/include --with-proj-share=/usr/local/share/proj --with-proj-data=/usr/local/share/proj'))
Downloading GitHub repo r-spatial/sf@master
   checking for file ‘/tmp/RtmptE6WrZ/remotes46d026f2932a/r-spatial-sf-8150edb/D✔  checking for file ‘/tmp/RtmptE6WrZ/remotes46d026f2932a/r-spatial-sf-8150edb/DESCRIPTION’
─  preparing ‘sf’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘sf_0.8-0.tar.gz’
   
Installing package into ‘/home/chris/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘sf’ ...
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
configure: gdal-config set to /usr/local/bin/gdal-config
checking gdal-config exists... yes
checking gdal-config executable... yes
checking gdal-config usability... yes
configure: GDAL: 3.1.0
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: pkg-config proj exists, will use it
configure: using proj.h.
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
configure: PROJ_LIB: /usr/local/share/proj
checking for geos-config... /usr/local/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/local/lib -lgeos_c... yes
configure: Package CPP flags:  -I/usr/local/include -DHAVE_PROJ_H -I/usr/local/include -I/usr/local/include
configure: Package LIBS: -L/usr/local/lib  -lproj  -L/usr/local/lib -lgdal -L/usr/local/lib -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/usr/local/include -DHAVE_PROJ_H -I/usr/local/include -I/usr/local/include -I"/home/chris/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/usr/local/include -DHAVE_PROJ_H -I/usr/local/include -I/usr/local/include -I"/home/chris/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -g -O2 -c bbox.cpp -o bbox.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/usr/local/include -DHAVE_PROJ_H -I/usr/local/include -I/usr/local/include -I"/home/chris/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -g -O2 -c gdal.cpp -o gdal.o
In file included from gdal.cpp:1:0:
./gdal.h:3:1: error: ‘OGRSpatialReference’ does not name a type; did you mean ‘DEFINED_OGRSpatialReferenceH’?
 OGRSpatialReference *handle_axis_order(OGRSpatialReference *sr, bool traditional = true);
 ^~~~~~~~~~~~~~~~~~~
 DEFINED_OGRSpatialReferenceH
/usr/local/lib64/R/etc/Makeconf:168: recipe for target 'gdal.o' failed
make: *** [gdal.o] Error 1
ERROR: compilation failed for package ‘sf’
* removing ‘/home/chris/R/x86_64-pc-linux-gnu-library/3.5/sf’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmptE6WrZ/file46d041d73e78/sf_0.8-0.tar.gz’ had non-zero exit status
> 
Puzzling as gdal-config suggests ogr-enabled. Is Rccp stricter than gcc perhaps?

**Comment by edzer** [comment]
Not sure, I have only tried with released versions of GDAL (up to 3.0.1); this seems a GDAL issue indeed. @rouault any idea?

**Comment by rsbivand** [comment]
I think we'd need to know the actual equivalent of the SVN revision number, and whether GDAL was built from a fork or from the unmodified upstream master (at a particular checkpoint. @chris-english please provide as much detail as possible of the provenance of your GDAL, OS, compiler versions, etc.

**Comment by chris-english** [comment]
generated by GNU Autoconf 2.69.  Invocation command line was
  $ ./configure LDFLAGS=-L/usr/local/lib CFLAGS=-I/usr/local/include
## --------- ##
## Platform. ##
## --------- ##

hostname = jacie
uname -m = x86_64
uname -r = 4.4.0-41-generic
uname -s = Linux
uname -v = #61-Ubuntu SMP Tue Sep 27 17:27:48 UTC 2016
Ubuntu-16.04LTS
gcc version 7.1.0 (Ubuntu 7.1.0-10ubuntu1~16.04.york0)

git cloned GDAL two days ago. 
(And now done...)
** installing vignettes
** testing if installed package can be loaded
* DONE (sf)
>
When in doubt, permissions. Awoke and realized I hadn't completely followed Thiago #1085, as above session was a user session, and success was sudo R. Sorry to trouble, and thanks.
