### ISSUE TITLE
st_read() of .gpkg from https source doesn't work for GDAL >2.4

### ISSUE THREAD

**Issue by mikoontz** [r-spatial/sf#1142]
I am unable to use `st_read()` on a .gpkg file from an https source with GDAL >2.4. My colleague reports this on GDAL 2.4.0, and I can reproduce the behavior on GDAL 2.4.2. I can read a .gpkg from an https source fine using GDAL 2.2.3.

Reading the .gpkg that comes with {sf} from disk works:
`st_read(system.file("gpkg/nc.gpkg", package = "sf"))`

Reading that same file when it's been uploaded to (for instance) a public S3 bucket does not work:

`st_read("https://earthlab-mkoontz.s3-us-west-2.amazonaws.com/nc.gpkg")`

The GeoJSONSeq driver is chosen to read the file from the https source, which is the wrong driver. GeoJSONSeq is new for GDAL 2.4 ([https://gdal.org/drivers/vector/geojsonseq.html](https://gdal.org/drivers/vector/geojsonseq.html)), so maybe that is related?

Downloading the file first does seem to allow {sf} to choose the right driver upon calling `st_read()`

```
my_temp_dir <- tempdir()
download.file("https://earthlab-mkoontz.s3-us-west-2.amazonaws.com/nc.gpkg", destfile = file.path(my_temp_dir, "nc.gpkg"))
test_gpkg <- st_read(file.path(my_temp_dir, "nc.gpkg"))

trying URL 'https://earthlab-mkoontz.s3-us-west-2.amazonaws.com/nc.gpkg'
Content type 'binary/octet-stream' length 124928 bytes (122 KB)
==================================================
downloaded 122 KB

Reading layer `nc.gpkg' from data source `/private/var/folders/xl/hy7rwmvx4llff5_00gwbk2vh0000gp/T/RtmprlECGQ/nc.gpkg' using driver `GPKG'
Simple feature collection with 100 features and 14 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs
```
Is this expected behavior?

Session details:

```
sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.7.2"        "2.4.2"        "6.2.0"         "true" 

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.7-7

loaded via a namespace (and not attached):
 [1] compiler_3.6.1     magrittr_1.5       class_7.3-15       DBI_1.0.0         
 [5] tools_3.6.1        units_0.6-4        Rcpp_1.0.2         KernSmooth_2.23-15
 [9] grid_3.6.1         e1071_1.7-2        classInt_0.4-1    
```

**Comment by edzer** [comment]
Yes, I see the same happening when using the command line tool `ogrinfo`:
```
ogrinfo https://earthlab-mkoontz.s3-us-west-2.amazonaws.com/nc.gpkg
```
and I don't see way to constrain the drivers that are being tried.

**Comment by edzer** [comment]
Limiting the drivers used to attempt to open the file doesn't help, but gives
```
> st_read("https://earthlab-mkoontz.s3-us-west-2.amazonaws.com/nc.gpkg", drivers = "GPKG")
options:        GPKG 
Error: Cannot open "https://earthlab-mkoontz.s3-us-west-2.amazonaws.com/nc.gpkg"; The file doesn't seem to exist.
```

**Comment by mikoontz** [comment]
Odd! The file definitely is still there (the `download.file()` approach above still works, and putting the link directly in a web browser prompts a download too).

Does that suggest it's a GDAL >2.4 thing and thus out of your hands?

**Comment by edzer** [comment]
I think so. I see the same issue with GDAL 3.0.1 / PROJ 6.2.0.

**Comment by mikoontz** [comment]
Okay! I hadn't seen it documented anywhere else, so happy that it's noted here for posterity! I can close the issue.
