### ISSUE TITLE
error in update from 0.7 to 0.8

### ISSUE THREAD

**Issue by LY1989eco** [r-spatial/sf#1153]
I used the code below to update the package ( to 0.8)
>library(devtools)
>install_github("r-spatial/sf")
Downloading GitHub repo r-spatial/sf@master
√  checking for file 'C:\Users\LY\AppData\Local\Temp\RtmpiU1O9x\remotes3b7076605c42\r-spatial-sf-8913c0e/DESCRIPTION' ... 
-  preparing 'sf': (1.4s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (690ms)
-  checking for empty or unneeded directories
-  building 'sf_0.8-1.tar.gz'
   Warning: file 'sf/cleanup' did not have execute permissions: corrected
   Warning: file 'sf/configure' did not have execute permissions: corrected
   
* installing *source* package 'sf' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs
rm -f sf.dll RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfg.o signed_area.o stars.o wkb.o
mkdir -p ../inst
"D:/Program Files (x86)/R/R-3.6.1/bin/x64/Rscript.exe" --vanilla "../tools/winlibs.R" 2.2.3
Warning messages:
1: In download.file(sprintf("https://github.com/rwinlib/gdal2/archive/v%s.zip",  :
  downloaded length 21855594 != reported length 44034709
2: In unzip("lib.zip", exdir = "../windows") : 从zip文件中抽取1时出了错
cp -r ../windows/gdal2-2.2.3/share/gdal ../inst/
cp: cannot stat '../windows/gdal2-2.2.3/share/gdal': No such file or directory
make: *** [Makevars.win:28: winlibs] Error 1
ERROR: compilation failed for package 'sf'
* removing 'D:/Program Files (x86)/R/R-3.6.1/library/sf'
Error: Failed to install 'sf' from GitHub:
  (converted from warning) installation of package ‘C:/Users/LY/AppData/Local/Temp/RtmpiU1O9x/file3b70293b4ee2/sf_0.8-1.tar.gz’ had non-zero exit status

I donot know the reason,  and I  am a complete beginner.

**Comment by edzer** [comment]
You're trying to install from source: unless you know what you are doing, please wait a couple of days and then installl the windows binary from on CRAN.

**Comment by LY1989eco** [comment]
Thanks for the advice

**Comment by LY1989eco** [comment]
> You're trying to install from source: unless you know what you are doing, please wait a couple of days and then installl the windows binary from on CRAN.

Thanks for the advice
