### ISSUE TITLE
OBJECTID dropped when reading table from geodatabase, regardless of fid_column_name argument

### ISSUE THREAD

**Issue by mkoohafkan** [r-spatial/sf#1159]
I have tables as well as features stored in an ESRI geodatabase. Sometimes it is helpful to retrieve the OBJECTIDs:

```r
st_read("my.gdb", "my_layer", fid_column_name = "OBJECTID")
##    OBJECTID station                    Shape
## 1         1       4 POINT (1903421 585786.5)
## 2         2       5 POINT (1904153 586100.5)
## 3         3       3   POINT (1902952 586375)
## 4         4       9 POINT (1906156 586474.5)
## 5         5       6 POINT (1904125 586560.2)
## 6         6       8 POINT (1905272 586861.5)
## 7         7      10 POINT (1907421 587151.5)
## 8         8       7 POINT (1904355 587364.3)
## 9         9      11 POINT (1908091 587368.5)
## 10       10       2 POINT (1902367 587555.5)
```

However, if I try to read a table that was exported from a layer (i.e. the table has an OBJECTID field but no geometry) there is no way to retrieve the OBJECTID:
```r
st_read("my.gdb", "my_table", fid_column_name = "OBJECTID")
## Warning message:
## no simple feature geometries present: returning a data.frame or tbl_df 
##    station
## 1        4
## 2        5
## 3        3
## 4        9
## 5        6
## 6        8
## 7       10
## 8        7
## 9       11
## 10       2
## 11       1
## 12      12
```

Any chance we can get the OBJECTID to be returned for tables when the `fid_column_name` argument is specified?

**Comment by edzer** [comment]
Could you provide an example file with which this happens? (off-line if needed)

**Comment by mkoohafkan** [comment]
hmmm, I am not able to reproduce this on my home computer---`st_read` returns the FID of the table I just created. I will look into what's happening on my work computer (where the problem occurred) on Monday. The only difference I know of right now is in the ArcGIS Pro version (2.4.1 at home, 2.4 at work).

**Comment by mkoohafkan** [comment]
This turned out to be user error. Sorry about that!
