### ISSUE TITLE
Stratified and clustered sampling types

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/sf#1161]
@edzer would you be interested in adding stratified and clustered sampling types to **sf**? They exist in **sp**. If so, I can clean my code and add some documentation. The alpha version is at https://github.com/r-spatial/sf/pull/1144. 

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
nc = st_read(system.file("shape/nc.shp", package = "sf"))
#> Reading layer `nc' from data source `/home/jn/R/x86_64-redhat-linux-gnu-library/3.6/sf/shape/nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> epsg (SRID):    4267
#> proj4string:    +proj=longlat +datum=NAD27 +no_defs
nc2 = st_transform(nc, 2163)

# existing
plot(st_sample(nc2, size = 150, type = "random"))
```

![](https://i.imgur.com/SgDz0BJ.png)

``` r
plot(st_sample(nc2, size = 150, type = "regular"))
```

![](https://i.imgur.com/pr2aIsw.png)

``` r

# added
plot(st_sample(nc2, size = 150, type = "clustered", nclusters = 10))
```

![](https://i.imgur.com/FY3y1MF.png)

``` r
plot(st_sample(nc2, size = 150, type = "stratified"))
```

![](https://i.imgur.com/5x2LH1K.png)

<sup>Created on 2019-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Yeah, I'm somewhat torn (unhappy with the `spsample` implementation), but more in favor than against it. A few questions/remarks:
* should the routines warn in case of geographic coordinates?
* should cells always be squared, and automatic?
* the `nclusters = 10` case above doesn't seem to return 10 clusters
* the documentation of `nclusters`, and examples, are missing from the PR
It would be good if there were an example where you'd sample 10 counties randomly, then 10 samples in each county, as of: stratified, guided by counties.

**Comment by Nowosad** [comment]
Hi @edzer - thanks for all your comments. As you can probably see, I've followed the sp implementation... I will take a look at it again in the next few days and try to make some improvements.

**Comment by Nowosad** [comment]
Hi @edzer ,

> should the routines warn in case of geographic coordinates?

Yes, I think it should.

> should cells always be squared, and automatic?

Probably no. We could have two versions: (1) squared and automatic, (2) based on the user-provided polygons.

> the `nclusters = 10` case above doesn't seem to return 10 clusters

I think that some clusters are just overlapping. We can try to use an alternative idea here, e.g., https://hpaulkeeler.com/simulating-a-matern-cluster-point-process/. What do you think about that?

We could also add "random' sampling with minimum distance separation" by @obrl-soil. 

Let me know what you think about all of it.

**Comment by edzer** [comment]
An alternative is to defer sampling methods of this kind to `spatstat` methods, assuming they have them. In case they have them, they might be much better documented there. I think the minimum distance random for instance is available in `spatstat`, as are random methods with known, varying densities (see e.g. [here](https://edzer.github.io/UseR2019/part2.html#spatial-point-processes)). @rubak

**Comment by rubak** [comment]
There are indeed quite a few (well documented) point sampling methods in `spatstat` which could be exposed through `sf::st_sample` if the user has `spatstat` installed. I don't know exactly the best way to expose them, but I would be happy to discuss ideas.

**Comment by Nowosad** [comment]
Simple point sampling can be probably exposed just by adding 
```r
  if (!requireNamespace("spatstat", quietly = TRUE)){
    stop("package spatstat required, please install it first")
  }
```
before the proper code. Bigger issue is a lack of methods to convert **sf** objects into **spatstat** objects:


``` r
library(sf)
library(spatstat)

# points only -------------------------------------------------------------
pp1 = st_collection_extract(st_as_sf(runifpoint(n = 50)), "POINT")

plot(pp1)
```

![](https://i.imgur.com/HOXomUT.png)

``` r


# points in polygon -------------------------------------------------------
window = read_sf(system.file("shape/nc.shp", package = "sf"))

pp2 = st_collection_extract(st_as_sf(runifpoint(n = 50, win = spatstat::as(window, "owin"))), "POINT")
#> Error: 'as' is not an exported object from 'namespace:spatstat'

plot(pp2)
#> Error in plot(pp2): object 'pp2' not found
```
Related to: https://github.com/spatstat/spatstat/issues/104

**Comment by edzer** [comment]
`as` is S4, a big taboo in `spatstat`.

A workaround now is
```r
library(maptools) # contains the sp -> spatstat converters
win = spatstat::as.owin(as(window, "Spatial"))
```
but then something strange happens:
```
> pp2 = st_collection_extract(st_as_sf(runifpoint(n = 50, win = win)), "POINT")
Warning message:
In st_cast.GEOMETRYCOLLECTION(st_polygonize(do.call(c, do.call(st_sfc,  :
  only first part of geometrycollection is retained
```

**Comment by Nowosad** [comment]
The warning is related to the use of `st_as_sf()` on a `ppp` object with polygonal boundary:

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(spatstat)
library(maptools)
#> Loading required package: sp
#> Checking rgeos availability: TRUE
window = read_sf(system.file("shape/nc.shp", package = "sf"))

win = spatstat::as.owin(as(window, "Spatial"))

pp2a = runifpoint(n = 50, win = win)
pp2b = st_as_sf(pp2a)
#> Warning in st_cast.GEOMETRYCOLLECTION(st_polygonize(do.call(c,
#> do.call(st_sfc, : only first part of geometrycollection is retained
pp2c = st_collection_extract(pp2b, "POINT")

plot(pp2c)
```

![](https://i.imgur.com/UDeEyNq.png)

<sup>Created on 2019-11-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Yes, but what is the problem it signals?

**Comment by Nowosad** [comment]
This line:
https://github.com/r-spatial/sf/blob/d2634d1e28605c0c569a4f9bc29f240a763d0031/R/spatstat.R#L16

It:
1. Creates `sfc_LINESTRING of length 2421`
2. Converts it into `sfg` `MULTILINESTRING`
3. Polygonizes it. The result is a `sfg` `GEOMETRYCOLLECTION` with six `sfg` `POLYGON` objects.
4. Casts it into `sfg` `POLYGON` -> only the first polygon from the previous object is retained -> warning `"only first part of geometrycollection is retained"`

**Comment by Nowosad** [comment]
@edzer I do not know if this is the best solution, but this seems to work (you need to replace the line from the previous post and the next two lines).

```r
  pol = st_union(st_collection_extract(st_sfc(st_polygonize(do.call(c, do.call(st_sfc, lst1)))), "POLYGON"))
  label = c("window")
  winwork_sf = st_sf(label = label, geom = pol)
```

**Comment by edzer** [comment]
Thanks; this extracts multiple polygons and combines them into a `MULTIPOLYGON`, so that the first feature remains the observation window.

**Comment by Nowosad** [comment]
Close?

**Comment by mkamenet3** [comment]
Hello! I recognize this thread is a bit old, but I'm looking for a way to do exactly what @Nowosad had proposed here: `plot(st_sample(nc2, size = 150, type = "clustered", nclusters = 10))` 

I wasn't able to quite follow how this resolved in the thread - could you please elaborate?  Thanks in advance!

**Comment by mkamenet3** [comment]
@rubak Thank you for your explanation and example, I appreciate it! :)
