### ISSUE TITLE
Save list of sf objects as individual kml files

### ISSUE THREAD

**Issue by markyxe** [r-spatial/sf#1163]
Hello, I am trying to save a list of sf objects as individual kml files, using this code:

for(i in 1:length(dat_list)){ 
st_write(dat_list[i], driver='kml',dsn=paste0("test/",names(dat_list)[i], ".kml"))
}

But I am getting this error:

Error in UseMethod("st_write") : 
  no applicable method for 'st_write' applied to an object of class "list"

Does anyone know how I can alter my loop to make this work? My workaround is to run i lines of code (where i = the number of list elements) like this:

st_write(dat_list[[1]],driver='kml',dsn=paste0("FolderName/",names(dat_list)[1], ".kml"))

but this can get cumbersome so I'd prefer to loop through the list if sf can be convinced to save list elements using a loop.

Thanks in advance for any help,

Mark

**Comment by edzer** [comment]
study lists: use `dat_list[[i]]` instead of `dat_list[i]` in your loop.

**Comment by markyxe** [comment]
Thank you Edzer!
