### ISSUE TITLE
Save sf object as KML file with lines connecting subsequent points

### ISSUE THREAD

**Issue by markyxe** [r-spatial/sf#1164]
Hello,

I would like to save GPS data currently held in a sf object as a KML file for visualization in Google Earth such that points subsequent in time are connected by a line in Google Earth. When I save the sf object using this code:

st_write(dat_list[[1]],driver='kml',dsn=paste0("FolderName/",names(dat_list)[1], ".kml"))

...I do get a KML object that can be viewed in Google Earth, but points subsequent in time are not joined by a line so it is difficult to visualize which points come first, next, etc.

Are there any options for st_writing KML files that allow this, or another way?

Many thanks,

Mark

**Comment by markyxe** [comment]
Thank you Edzer. I would like to retain time for each of the points, do you know how I could do that?

**Comment by edzer** [comment]
I don't think you can.
