### ISSUE TITLE
ibproj.so.15 missing

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/sf#1165]
Since a few days I'm getting a `libproj.so.15: cannot open shared object file: No such file or directory` when using the latest `sf` from github on Ubuntu 18.04 with the ubuntuGIS-unstable repo enabled. This system is up to date and the packages in the README.md are installed.

I guess it's missing Proj6?

**Comment by edzer** [comment]
I have the same setup, and things run find. What do you see if you do sth like (please use the right path):
```shell
$ ldd ~/R/x86_64-pc-linux-gnu-library/3.6/sf/libs/sf.so  | grep proj
	libproj.so.13 => /usr/lib/x86_64-linux-gnu/libproj.so.13 (0x00007fbeba0f7000)
```
possibly, your machine has two proj versions installed, one packaged, one from source?

**Comment by adrfantini** [comment]
Nevermind, it was my bad. Had to reinstall `lwgeom` first as well.
