### ISSUE TITLE
`group_split` raises error with multiprocessing

### ISSUE THREAD

**Issue by karldw** [r-spatial/sf#1167]
I noticed an issue where the `group_split.sf` method raises an error when multiprocessing. 

``` r

library(sf)

cl <- parallel::makeCluster(2)
demo(nc, ask = FALSE, echo = FALSE)

fn <- function(x) {
  dplyr::mutate(x, NWBIR79= NWBIR79*2)
}

nc_split <- nc %>%
  dplyr::group_by(SID74) %>%
  dplyr::group_split()

# Non-parallel group_split
lapply(nc_split, fn) %>% do.call(rbind, .) %>% print()
#> Simple feature collection with 1 feature and 14 fields
#> ... 

# Parallel group_split (error)
parallel::parLapply(cl, nc_split, fn) %>% do.call(rbind, .) %>% head(1) %>% print()
#> Error in .subset2(x, i): attempt to select less than one element in get1index
```

<sup>Created on 2019-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Other notes:
- This behavior is the same with `parLapply` and `furrr::future_map` with `future::plan("multisession")`
- Forking (`mclapply`) works
- Using `base::split` instead of `dplyr::group_split` works, though the result loses the `sf` class

**Comment by edzer** [comment]
You forgot to export the methods to the cluster nodes, after
```
clusterEvalQ(cl, library(sf))
clusterEvalQ(cl, library(dplyr))
```
things work.

**Comment by karldw** [comment]
Ah, I'm sorry. I'm used to `future` taking care of these exports for me, but as they [document](https://cran.r-project.org/web/packages/future/vignettes/future-4-issues.html), auto-exporting sometimes fails. Thank you!
