### ISSUE TITLE
formula for st_distance with no "distance" argument?

### ISSUE THREAD

**Issue by randomgambit** [r-spatial/sf#1171]
Hello there!

I was using the great `st_distance` between two latitude/longitude points (`crs = 4326`) but I am not sure which formula is used by `sf` when neither Haussdorf nor Frechet are specified.

Is `st_distance(x = new_york_latlon, y = chicago_latlon, by_element = TRUE)` simply the euclidian distance between the two cities?

That is according to https://math.stackexchange.com/questions/29157/how-do-i-convert-the-distance-between-two-lat-long-points-into-feet-meters ?

Thanks!

**Comment by lbusett** [comment]
According to `st_distance()`  [documentation](https://r-spatial.github.io/sf/reference/geos_measures.html) ,  " for geodetic coordinates, great circle distances are computed.... great circle distance calculations use function geod_inverse from PROJ".

The `which` argument can not actually be used, if coordinates are lat/lon.
