### ISSUE TITLE
sf::st_centroid() reverses lat/lon

### ISSUE THREAD

**Issue by jzadra** [r-spatial/sf#1174]
calling sf::st_centroid() reverses the latitude and longitude.  

`st_centroid()` gives the geometry in order lon, lat, which is against convention.  And using `st_coordinates()` on the centroid gives the lat as Y and lon as X. However Lat should be the x axis (east/west), lon should be the y axis (north/south). 

``` r
require(tidyverse)
#> Loading required package: tidyverse
require(tigris)
#> Loading required package: tigris
#> To enable 
#> caching of data, set `options(tigris_use_cache = TRUE)` in your R script or .Rprofile.
#> 
#> Attaching package: 'tigris'
#> The following object is masked from 'package:graphics':
#> 
#>     plot
require(sf)
#> Loading required package: sf
#> Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3

ut <- states(cb = T) %>% 
  st_as_sf() %>% 
  filter(STUSPS == "UT")

(centroid <- st_centroid(ut)) #Gives gemoetry in lon, lat against the convention)

#> Warning in st_centroid.sf(ut): st_centroid assumes attributes are constant
#> over geometries of x
#> Warning in st_centroid.sfc(st_geometry(x), of_largest_polygon =
#> of_largest_polygon): st_centroid does not give correct centroids for
#> longitude/latitude data
#> Simple feature collection with 1 feature and 9 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: -111.6782 ymin: 39.32379 xmax: -111.6782 ymax: 39.32379
#> epsg (SRID):    4269
#> proj4string:    +proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs
#>   STATEFP  STATENS    AFFGEOID GEOID STUSPS NAME LSAD        ALAND
#> 1      49 01455989 0400000US49    49     UT Utah   00 212884846341
#>       AWATER                   geometry
#> 1 7000199770 POINT (-111.6782 39.32379)

st_coordinates(centroid)
#>           X        Y
#> 1 -111.6782 39.32379
```

<sup>Created on 2019-10-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SymbolixAU** [comment]
> However Lat should be the x axis (east/west), lon should be the y axis (north/south)

This statement is incorrect.


https://simple.wikipedia.org/wiki/Longitude

> Longitude says how far east (positive numbers) or west (negative numbers) of the Prime Meridian any place is.

**Comment by jzadra** [comment]
Oh boy that's embarassing.  I can never remember which is which, and I was thrown of by this image, which to me indicates lat = horizontal = x, lon = vertical = y, but I can see now the misinerpretation:

![image](https://user-images.githubusercontent.com/25590353/66847373-81672500-ef30-11e9-9a36-db4a956971f7.png)
