### ISSUE TITLE
High heap usage after st_read

### ISSUE THREAD

**Issue by GreatEmerald** [r-spatial/sf#1175]
I noticed that after I read a large file with `st_read()`, R reports memory usage that is in line with expectations given the dataset size, yet the OS (CentOS 7 in my case) is reporting resident memory size that is three times larger; /proc/[pid]/smaps says it's used by the heap. `gc()` can't clear such a memory overhead, which leads to my machine swapping out much earlier than I expected.

This is independent of the GDAL driver being used (same for a shapefile and geopackage).

Here's a reprex:
```r
# Test memory usage of st_read
library(pryr)
library(sf)

# Make a large geopackage
mydata = matrix(0, 500000, 100)
object_size(mydata) # 400 MiB
mydata = data.frame(mydata, x=runif(100), y=runif(100))
mydata = st_as_sf(mydata, coords = c("x", "y"))
object_size(mydata) # 464 MiB
st_write(mydata, "memorytest.gpkg")
mem_used() # 560 MB
system("ps -o rss `pidof rsession`") # 662 MiB

.rs.restartR() # Or manually restart R

library(pryr)
library(sf)

mem_used() # 43 MiB
mem_change(mydata <- st_read("memorytest.gpkg")) # 514 MiB
mem_used() # 558 MiB
gc(TRUE)
system("ps -o rss `pidof rsession`") # 1605 MiB!

### Test a shapefile
.rs.restartR() # Or manually restart R

library(pryr)
library(sf)

# Make a large shapefile
mydata = matrix(0, 500000, 100)
object_size(mydata) # 400 MiB
mydata = data.frame(mydata, x=runif(100), y=runif(100))
mydata = st_as_sf(mydata, coords = c("x", "y"))
object_size(mydata) # 464 MiB
st_write(mydata, "memorytest.shp")
mem_used() # 560 MB
system("ps -o rss `pidof rsession`") # 747 MiB

.rs.restartR()

library(pryr)
library(sf)

mem_used() # 43 MiB
mem_change(mydata <- st_read("memorytest.shp")) # 514 MiB
mem_used() # 558 MiB
gc(TRUE)
system("ps -o rss `pidof rsession`") # 1621 MiB!
```

**Comment by edzer** [comment]
Maybe worth mentioning that it's an rstudio reprex; the `.rs.restartR()` didn't work for me even in R studio. I get similar results in ubuntu after copying chunks by hand. I may assume you did read [R FAQ 7.42](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-is-R-apparently-not-releasing-memory_003f)?

**Comment by GreatEmerald** [comment]
Yes, the RStudio macro also would result in not cleaning up the environment for me, so I also restarted it manually after each chunk (hence my comment there; and indeed I don't use RStudio that often myself).

Yes, indeed, I know that there may not be much that can be done, but I'd be interested in knowing the cause and any potential workarounds. Memory fragmentation could indeed be one cause, but I'd imagine that for a file that large, `mmap` would be used, thus avoiding that problem.

Right now I'm working around this issue by chunking my vector processing (same can be achieved by chunking reads in the case of GeoPackages, I guess, but I haven't tried that specifically).

**Comment by edzer** [comment]
`st_read` reads a data source into an R object, meaning _into memory_, how could it use `mmap` for that? If you're interested into developing experiments in that direction, you may want to look into the [ALTREP framework](https://www.r-project.org/dsc/2017/slides/dsc2017.pdf).

**Comment by GreatEmerald** [comment]
Not `sf`, I mean that R and/or the OS would use it for large objects, as the R FAQ entry you linked to suggests. I think an `sf` object counts as a (set of) long vector(s), and it should be quite contiguous.

Hm, if I try the same experiment with a plain CSV, I get similar results (and apparently geometry takes a lot of memory!), so I guess we should just expect three times more memory consumption when reading...

```r
### Test a regular CSV

library(pryr)
library(sf)

# Make a large CSV
mydata = matrix(0, 500000, 100)
object_size(mydata) # 400 MiB
mydata = data.frame(mydata, x=runif(100), y=runif(100))
object_size(mydata) # 408 MiB
write.csv(mydata, "memorytest.csv")
mem_used() # 465 MB
system("ps -o rss `pidof rsession`") # 575 MiB

.rs.restartR()

library(pryr)
library(sf)

mem_used() # 60 MiB
mem_change(mydata <- read.csv("memorytest.csv")) # 212 MiB
mem_used() # 272 MiB
gc(TRUE)
system("ps -o rss `pidof rsession`") # 678 MiB!
```

**Comment by mdsumner** [comment]
I suggest to use the `query` argument to read only subsets, there's no lazy sf tbl yet, though I've come close and it partially works.
