### ISSUE TITLE
st_sample runs indefinetelly when size is non-integer value

### ISSUE THREAD

**Issue by dvictori** [r-spatial/sf#1178]
Running st_sample on a polygon and setting the size parameter to a non-integer value will keep R running indefinitely.

I know it does not make much sense to set size to a non-integer value but, if the user forgets to round the number (like I did), the script will keep on running without a warning.

Maybe throw a warning and round the number.

Example:
```
library(sf)

outer = matrix(c(0,0,10,0,10,10,0,10,0,0),ncol=2, byrow=TRUE)

poly <- st_polygon(list(outer))

sample_10 <- st_sample(poly, 10)

plot(poly)
plot(sample_10, add = TRUE, col = 'blue')

# this just keeps on running
sample_float <- st_sample(poly, 100.1)
```

Running R 3.4.4 on Ubuntu, sf v.0.8-0 and tidyverse 1.2.1

**Comment by Robinlovelace** [comment]
Good catch and clear reproducible example. I added a timeout so it would work in reprex. Definitely an issue IMO.

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.2, PROJ 5.2.0
outer = matrix(c(0,0,10,0,10,10,0,10,0,0),ncol=2, byrow=TRUE)
poly <- st_polygon(list(outer))
sample_10 <- st_sample(poly, 10)
plot(poly)
plot(sample_10, add = TRUE, col = 'blue')
```

![](https://i.imgur.com/BfsbD0c.png)

``` r
# this just keeps on running
system.time(sample_float <- st_sample(poly, 100))
#>    user  system elapsed 
#>   0.005   0.001   0.005
system.time(R.utils::withTimeout(expr = {sample_float <- st_sample(poly, 100.1)}, timeout = 3))
#> Registered S3 method overwritten by 'R.oo':
#>   method        from       
#>   throw.default R.methodsS3
#> [2019-10-16 18:26:09] TimeoutException: reached elapsed time limit [cpu=3s,
#> elapsed=3s]
#> Timing stopped at: 3.011 0.045 3.075
```

<sup>Created on 2019-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Thanks; non-integer values for size now generate an error.
