### ISSUE TITLE
Affine transformation of a set around a single point.

### ISSUE THREAD

**Issue by matthewross07** [r-spatial/sf#1181]
This probably more my own lack of understanding, but I am hoping to use `sf` to do something very similar to `maptools::elide` which can shift, rotate, and scale polygons all around a single axis such as is shown here: https://rud.is/b/2014/11/16/moving-the-earth-well-alaska-hawaii-with-r/. 

While in sf, one can similarly make polygons or any simple feature rotate, I only see examples (and can only figure out myself) on how to rotate every feature in a simple feature set like here: https://r-spatial.github.io/sf/articles/sf3.html#affine-transformations

Is there a simple way to do affine transformations so that, for example, the entirety of North Carolina counties would rotate and shrink by 90 degrees? This would keep all counties still touching, just rotate the whole state. 

Thank you for any advice.

**Comment by matthewross07** [comment]
Well, I made a hacky fix that mostly works but is slow and ugly. If there is a more elegant way to do this, I'd love to hear. Thanks for an amazing package. 

This requires USAboundariesData to be installed to work. 

```
library(tidyverse)
library(USAboundariesData)
library(sf)

# From geospatial R tutorial 
rotation = function(a){
  r = a * pi / 180 #degrees to radians
  matrix(c(cos(r), sin(r), -sin(r), cos(r)), nrow = 2, ncol = 2)
} 
ak_cts = us_counties() %>%
  filter(state_name == 'Alaska') %>%
  st_transform(2163) 


sf_elision <- function(st,shift=c(-1900000, -2600000)){
  ak_geo_shift <- st_geometry(st) + 
    shift
  
  
  many_center <- st_centroid(ak_geo_shift)
  
  single_center <- st %>%
    group_by() %>%
    summarize() %>%
    slice(rep(1:n(),each=nrow(st))) %>%
    st_centroid() %>%
    st_geometry() 
  
  shift_centers <- single_center + shift
  
  ak_rote <- (ak_geo_shift-shift_centers)*rotation(-35)*0.4 + shift_centers
  
  
  return(st_set_crs(ak_rote,2163))
}

ak_shrunk_and_spun <- sf_elision(ak_cts)
```

**Comment by edzer** [comment]
I get
```
Error in us_counties() : could not find function "us_counties"
```
but if this solves the problem for you, please close.
