### ISSUE TITLE
Trouble installing on CentOS 7 - undefined symbol: _Z17CPL_gdalrasterizeN4Rcpp6VectorILi16ENS_15PreserveStorageEEES2_S2_b

### ISSUE THREAD

**Issue by MBXBB** [r-spatial/sf#1188]
I'm having a tremendously difficult time getting sf installed into my environment. 

CentOS 7, R 3.6.1.

Attached is the most recent output from an attempted install. Any advice would be much appreciated.

`* installing to library ‘/n/apps/CentOS7/install/r-3.6.1/lib64/R/library’
* installing *source* package ‘sf’ ...
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /n/apps/CentOS7/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.0.3
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /n/apps/CentOS7/install/gdal-2.0.3/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
checking for pj_init_plus in -lproj... yes
checking PROJ: epsg found and readable... yes
checking for geos-config... /bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib64 -lgeos_c... yes
configure: Package CPP flags:   -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include
configure: Package LIBS:  -L/n/apps/CentOS7/install/gdal-2.0.3/lib -lgdal -lproj  -L/n/apps/CentOS7/install/gdal-2.0.3/lib -lgdal -L/usr/lib64 -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c bbox.cpp -o bbox.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c gdal.cpp -o gdal.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c gdal_geom.cpp -o gdal_geom.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c gdal_read.cpp -o gdal_read.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c gdal_utils.cpp -o gdal_utils.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c gdal_write.cpp -o gdal_write.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c geos.cpp -o geos.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c hex.cpp -o hex.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c ops.cpp -o ops.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c polygonize.cpp -o polygonize.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c proj.cpp -o proj.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c proj_info.cpp -o proj_info.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c raster2sf.cpp -o raster2sf.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c sfg.cpp -o sfg.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c signed_area.cpp -o signed_area.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c stars.cpp -o stars.o
g++ -std=gnu++11 -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/include" -DNDEBUG -I/n/apps/CentOS7/install/gdal-2.0.3/include -I/usr/include -I"/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c wkb.cpp -o wkb.o
g++ -std=gnu++11 -shared -L/n/apps/CentOS7/install/r-3.6.1/lib64/R/lib -L/n/apps/CentOS7/lib64 -L/n/apps/CentOS7/lib -L/usr/lib64 -L/usr/lib -o sf.so RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfg.o signed_area.o stars.o wkb.o -L/n/apps/CentOS7/install/gdal-2.0.3/lib -lgdal -lproj -L/n/apps/CentOS7/install/gdal-2.0.3/lib -lgdal -L/usr/lib64 -lgeos_c -L/n/apps/CentOS7/install/r-3.6.1/lib64/R/lib -lR
installing to /n/apps/CentOS7/install/r-3.6.1/lib64/R/library/00LOCK-sf/00new/sf/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
in method for ‘dbWriteTable’ with signature ‘"PostgreSQLConnection","character","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘dbDataType’ with signature ‘"PostgreSQLConnection","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘coerce’ with signature ‘"Spatial","sf"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"Spatial","sfc"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sf","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sfc","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"XY","Spatial"’: no definition for class “Spatial”
** help
*** installing help indices
  converting help for package ‘sf’
    finding HTML links ... done
    Ops                                     html  
    aggregate.sf                            html  
    bind                                    html  
Rd warning: /tmp/sf/man/bind.Rd:19: file link ‘rbind’ in package ‘base’ does not exist and so has been treated as a topic
Rd warning: /tmp/sf/man/bind.Rd:34: file link ‘bind_cols’ in package ‘dplyr’ does not exist and so has been treated as a topic
    coerce-methods                          html  
Rd warning: /tmp/sf/man/coerce-methods.Rd:32: file link ‘sp’ in package ‘sp’ does not exist and so has been treated as a topic
    dbDataType                              html  
    db_drivers                              html  
    extension_map                           html  
    gdal                                    html  
    gdal_utils                              html  
    geos_binary_ops                         html  
    geos_binary_pred                        html  
    geos_combine                            html  
Rd warning: /tmp/sf/man/geos_combine.Rd:33: file link ‘gUnaryUnion’ in package ‘rgeos’ does not exist and so has been treated as a topic
Rd warning: /tmp/sf/man/geos_combine.Rd:33: file link ‘gUnion’ in package ‘rgeos’ does not exist and so has been treated as a topic
    geos_measures                           html  
    geos_query                              html  
    geos_unary                              html  
    internal                                html  
    is_driver_available                     html  
    is_driver_can                           html  
    is_geometry_column                      html  
    merge.sf                                html  
    nc                                      html  
    plot                                    html  
Rd warning: /tmp/sf/man/plot.Rd:75: file link ‘rainbow’ in package ‘grDevices’ does not exist and so has been treated as a topic
    prefix_map                              html  
    rawToHex                                html  
    reexports                               html  
Rd warning: /tmp/sf/man/reexports.Rd:14: file link ‘%>%’ in package ‘magrittr’ does not exist and so has been treated as a topic
    sf-deprecated                           html  
    sf                                      html  
    sf_extSoftVersion                       html  
    sf_project                              html  
    sfc                                     html  
    sgbp                                    html  
    st                                      html  
    st_agr                                  html  
    st_as_binary                            html  
    st_as_grob                              html  
    st_as_sf                                html  
    st_as_sfc                               html  
    st_as_text                              html  
    st_bbox                                 html  
    st_cast                                 html  
Rd warning: /tmp/sf/man/st_cast.Rd:76: file link ‘aggregate’ in package ‘sf’ does not exist and so has been treated as a topic
Rd warning: /tmp/sf/man/st_cast.Rd:76: file link ‘summarise’ in package ‘sf’ does not exist and so has been treated as a topic
    st_cast_sfc_default                     html  
    st_collection_extract                   html  
    st_coordinates                          html  
    st_crop                                 html  
    st_crs                                  html  
    st_drivers                              html  
    st_geometry                             html  
    st_geometry_type                        html  
    st_graticule                            html  
    st_interpolate_aw                       html  
    st_is                                   html  
    st_is_longlat                           html  
    st_jitter                               html  
    st_join                                 html  
Rd warning: /tmp/sf/man/st_join.Rd:31: file link ‘left_join’ in package ‘dplyr’ does not exist and so has been treated as a topic
    st_layers                               html  
    st_line_sample                          html  
    st_make_grid                            html  
    st_nearest_feature                      html  
    st_nearest_points                       html  
    st_normalize                            html  
    st_precision                            html  
    st_read                                 html  
    st_relate                               html  
    st_sample                               html  
    st_transform                            html  
    st_viewport                             html  
    st_write                                html  
    finding level-2 HTML links ... done

    st_zm                                   html  
    stars                                   html  
    summary.sfc                             html  
    tibble                                  html  
    tidyverse                               html  
Rd warning: /tmp/sf/man/tidyverse.Rd:157: file link ‘unnest’ in package ‘tidyr’ does not exist and so has been treated as a topic
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/00LOCK-sf/00new/sf/libs/sf.so':
  /n/apps/CentOS7/install/r-3.6.1/lib64/R/library/00LOCK-sf/00new/sf/libs/sf.so: undefined symbol: _Z17CPL_gdalrasterizeN4Rcpp6VectorILi16ENS_15PreserveStorageEEES2_S2_b
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/n/apps/CentOS7/install/r-3.6.1/lib64/R/library/sf’
`
[sf.txt](https://github.com/r-spatial/sf/files/3821851/sf.txt)

**Comment by edzer** [comment]
Errors like this are usually caused by the presence of more than one installation of PROJ, GEOS and/or GDAL. See https://github.com/r-spatial/sf and search for "Multiple".

**Comment by MBXBB** [comment]
Thanks for the quick response.

I have read, and I believe I understand the issues with having multiple versions of any of those pieces of software. I am at a loss though as I can only find a single version of each on my system.

**Comment by MBXBB** [comment]
I was able to get version 0.6.3 to install in the same environment.

**Comment by edzer** [comment]
Recently?

**Comment by MBXBB** [comment]
Yes. On Friday 11/8.

**Comment by edzer** [comment]
With 0.6-3 installed, after starting R, please post the output you see from
```
system(paste("ldd", system.file("libs/sf.so", package = "sf")))
```

**Comment by MBXBB** [comment]
> system(paste("ldd", system.file("libs/sf.so", package = "sf")))
        linux-vdso.so.1 =>  (0x00007ffe705de000)
        libgdal.so.20 => /n/apps/CentOS7/lib/libgdal.so.20
(0x00007f8ce6ba1000)
        libproj.so.0 => /usr/lib64/libproj.so.0 (0x00007f8ce694e000)
        libgeos_c.so.1 => /usr/lib64/libgeos_c.so.1 (0x00007f8ce6727000)
        libR.so => /n/apps/CentOS7/install/r-3.6.1/lib64/R/lib/libR.so
(0x00007f8ce607d000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f8ce5d74000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00007f8ce5a72000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f8ce585c000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007f8ce5498000)
        libsqlite3.so.0 =>
/n/apps/CentOS7/install/sqlite-3.26.00/lib/libsqlite3.so.0
(0x00007f8ce518f000)
        libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007f8ce4f64000)
        libhdf5.so.10 => /n/apps/CentOS7/lib/libhdf5.so.10
(0x00007f8ce4a78000)
        libgif.so.4 => /usr/lib64/libgif.so.4 (0x00007f8ce486e000)
        libjpeg.so.62 => /usr/lib64/libjpeg.so.62 (0x00007f8ce4619000)
        libtiff.so.5 => /usr/lib64/libtiff.so.5 (0x00007f8ce43a4000)
        libpng15.so.15 => /usr/lib64/libpng15.so.15 (0x00007f8ce4179000)
        libpq.so.5 => /usr/lib64/libpq.so.5 (0x00007f8ce3f4a000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f8ce3d2d000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00007f8ce3b25000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f8ce38c3000)
        libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007f8ce3659000)
        libiconv.so.2 =>
/n/apps/CentOS7/install/libiconv-1.15/lib/libiconv.so.2 (0x00007f8ce3373000)
        libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007f8ce3009000)
        libz.so.1 => /n/apps/CentOS7/lib/libz.so.1 (0x00007f8ce2def000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f8ce2beb000)
        libgeos-3.4.2.so => /usr/lib64/libgeos-3.4.2.so (0x00007f8ce284b000)
        libRblas.so =>
/n/apps/CentOS7/install/r-3.6.1/lib64/R/lib/libRblas.so (0x00007f8ce261d000)
        libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f8ce22fb000)
        libquadmath.so.0 => /usr/lib64/libquadmath.so.0 (0x00007f8ce20bf000)
        libreadline.so.6 => /usr/lib64/libreadline.so.6 (0x00007f8ce1e78000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f8ce1c52000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007f8ce1a42000)
        libicuuc.so.50 => /usr/lib64/libicuuc.so.50 (0x00007f8ce16c8000)
        libicui18n.so.50 => /usr/lib64/libicui18n.so.50 (0x00007f8ce12c9000)
        libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007f8ce10a3000)
        /lib64/ld-linux-x86-64.so.2 (0x000055c136743000)
        libsz.so.2 => /n/apps/CentOS7/lib/libsz.so.2 (0x00007f8ce0e8e000)
        libSM.so.6 => /usr/lib64/libSM.so.6 (0x00007f8ce0c86000)
        libICE.so.6 => /usr/lib64/libICE.so.6 (0x00007f8ce0a6a000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f8ce072b000)
        libjbig.so.2.0 => /usr/lib64/libjbig.so.2.0 (0x00007f8ce051f000)
        libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f8ce02ad000)
        libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f8cdfe4b000)
        libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007f8cdfb63000)
        libcom_err.so.2 => /usr/lib64/libcom_err.so.2 (0x00007f8cdf95f000)
        libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2
(0x00007f8cdf711000)
        libldap_r-2.4.so.2 => /usr/lib64/libldap_r-2.4.so.2
(0x00007f8cdf4b4000)
        libidn.so.11 => /usr/lib64/libidn.so.11 (0x00007f8cdf281000)
        libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007f8cdf056000)
        libssl3.so => /usr/lib64/libssl3.so (0x00007f8cdee04000)
        libsmime3.so => /usr/lib64/libsmime3.so (0x00007f8cdebdd000)
        libnss3.so => /usr/lib64/libnss3.so (0x00007f8cde8af000)
        libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007f8cde680000)
        libplds4.so => /usr/lib64/libplds4.so (0x00007f8cde47c000)
        libplc4.so => /usr/lib64/libplc4.so (0x00007f8cde276000)
        libnspr4.so => /usr/lib64/libnspr4.so (0x00007f8cde038000)
        libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007f8cdde05000)
        liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2 (0x00007f8cddbf5000)
        libldap-2.4.so.2 => /usr/lib64/libldap-2.4.so.2 (0x00007f8cdd9a1000)
        libtinfo.so.5 => /usr/lib64/libtinfo.so.5 (0x00007f8cdd776000)
        libicudata.so.50 => /usr/lib64/libicudata.so.50 (0x00007f8cdc1a2000)
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f8cdbf9c000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f8cdbd74000)
        libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0
(0x00007f8cdbb65000)
        libkeyutils.so.1 => /usr/lib64/libkeyutils.so.1 (0x00007f8cdb961000)
        libresolv.so.2 => /usr/lib64/libresolv.so.2 (0x00007f8cdb747000)
        libsasl2.so.3 => /usr/lib64/libsasl2.so.3 (0x00007f8cdb529000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f8cdb325000)
        libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f8cdb0fd000)
        libcrypt.so.1 => /usr/lib64/libcrypt.so.1 (0x00007f8cdaec6000)
        libfreebl3.so => /usr/lib64/libfreebl3.so (0x00007f8cdacc2000)
>

**Comment by edzer** [comment]
I'm lost. I think I would update GDAL to a more recent 2.x version (>= 2.1.x) and try again.

**Comment by MBXBB** [comment]
I will give that a try as soon as possible.

**Comment by Eli-Berkow** [comment]
@MBXBB please let me know if you have any luck. I have been having the same problem since sf `0.8.0`. I have a working installation of `0.7.7` though. Using R 3.6.0 and Red Hat Enterprise Linux Server release 7.7 (Maipo).

**Comment by MBXBB** [comment]
@edzer @Eli-Berkow 

I was able to successfully install sf-0.8.0 in both R-3.5.2 and R-3.6.1 after updating GDAL from 2.0.3 to 2.1.4.
