### ISSUE TITLE
Git Release

### ISSUE THREAD

**Issue by r-barnes** [r-spatial/sf#1189]
I notice that there's a v0.8-0 of sf available on CRAN, but the Github releases stop at v0.6-3. Is there a way to fill in the other git releases so they match CRAN?

**Comment by edzer** [comment]
I don't see the point of doing that since cran carries the full archive of source releases.

On 8 November 2019 18:37:10 CET, Richard Barnes <notifications@github.com> wrote:
>I notice that there's a v0.8-0 of sf available on CRAN, but the Github
>releases stop at v0.6-3. Is there a way to fill in the other git
>releases so they match CRAN?

-- 
Sent from a phone. Please excuse my brevity.

**Comment by edzer** [comment]
The archive is here: https://cran.r-project.org/src/contrib/Archive/sf/
