### ISSUE TITLE
Passing command line arguments to st_read

### ISSUE THREAD

**Issue by davidorme** [r-spatial/sf#1192]
Is there a way to pass OGR command line options in `st_read`? The specific use case is that I wanted to load a small spatial subset of a large file, which I'd do on the command line using `-spat xmin ymin xmax ymax`. The `query` argument works beautifully for getting a subset by feature attribute, but not spatial queries.

More of a feature request than an issue...

**Comment by edzer** [comment]
Good idea! See https://github.com/r-spatial/sf/blob/master/tests/read.R#L139-L144 for an example.

**Comment by edzer** [comment]
I chose to pass a geometry as WKT, rather than four numbers; I believe the implementation by OGR in the end is identical, in the sense that overlap with bounding box is given; see [here](https://gdal.org/api/ogrlayer_cpp.html#_CPPv4N8OGRLayer16SetSpatialFilterEP11OGRGeometry).

**Comment by davidorme** [comment]
Perfect. Thanks, Edzer.
