### ISSUE TITLE
Request extent argument to plot.sf

### ISSUE THREAD

**Issue by davidorme** [r-spatial/sf#1193]
Again, this functionality may already exists and I've missed it and it is definitely a feature request not an issue.

I often find myself plotting a basemap where I want to change the extents to zoom in or to leave space for overplotting with layers with larger extents.

I can of course use `xlim` and `ylim` for that:

```r
bb <- st_bbox(layer2)
plot(layer1, xlim=bb[c(1,3)], ylim=bb[c(2,4)])
```

It doesn't save a lot of typing but it seems a common enough pattern that being able to use any object with an `st_bbox` method to set the extent directly (superseding `xlim` and `ylim`?) would be a useful feature.

```r
plot(layer1, extent=layer2)
```

Cheers,
David

**Comment by edzer** [comment]
This should work now.

**Comment by davidorme** [comment]
Sorry to resurrect this - it works but is only implemented for `plot.sf` and not when plotting `sfc` objects. I think that should be a pretty straightforward copy of the updates made to the `plot.sf` arguments into `plot_sf`?

**Comment by edzer** [comment]
I haven't tested this, but it might work - please verify.

**Comment by davidorme** [comment]
That works - I've only done a light test with overplotting some polygon `sfc` objects, but it works as expected. Many thanks.
