### ISSUE TITLE
st_as_sfc.pq_geometry

### ISSUE THREAD

**Issue by SymbolixAU** [r-spatial/sf#1195]
If a table is read from a postgis database as a regular data.frame using `RPostgres::dbGetQuery` the geometry column is returned as class `pq_geometry`.

This can be converted to `sfc` by

```r
sf:::st_as_sfc.WKB( df$geom, EWKB = TRUE )
```

Can we have a `sf_as_sfc.pq_geometry` method which does this automatically as part of `sf`?

For example

```r
#' @export
sf_as_sfc.pq_geometry <- function(x, ..., EWKB = FALSE, spatialite = FALSE, pureR = FALSE, crs = NA_crs_) {
  st_as_sfc.WKB(x, ..., EWKB = TRUE, spatiallite = spatialite, pureR = pureR, crs = crs)
}

```

**Comment by dcooley** [comment]
@edzer sorry yes, that makes more sense. I missed setting the `EWKB` argument to `TRUE`.
