### ISSUE TITLE
Pass aggregation function to st_join (analogous to raster::extract)

### ISSUE THREAD

**Issue by ratnanil** [r-spatial/sf#1202]
The function `raster::extract()` accepts an aggregation / summary function in the `fun = ` argument. 

> function to summarize the values (e.g. mean). The function should take a single numeric vector as argument and return a single value (e.g. mean, min or max), and accept a na.rm argument. Thus, standard R functions not including an na.rm argument must be wrapped as in this example: fun=function(x,...)length(x). If y represents points, fun is only used when a buffer is used (and hence multiple values per spatial feature would otherwise be returned).

Would it be possible to include something similar in `st_join()`. I have the following usecase extremely often:

1. join two datasets -> resulting dataset has replications of identical geometries
2. group by (e.g. `group_by(id)`) a unique identifier per geometry
3. summarise to count values or get means (e.g. `summarise(mean_val = mean(value)`)

I've created a small reprex to illustrate what I mean:

``` r

library(sf)
library(ggplot2)
library(dplyr)

set.seed(10)
points <- st_as_sf(data.frame(x = rnorm(10), y = rnorm(10), value = sample(1:10,10)), coords = c("x","y"))

squares <-st_make_grid(points,cellsize = 1) %>%
  st_as_sf() %>%
  mutate(id = LETTERS[row_number()])

ggplot(squares) +
  geom_sf() + 
  geom_sf_label(aes(label = id)) +
  geom_sf(data = points) +
  geom_sf_text(data = points, aes(label = value),inherit.aes = FALSE,nudge_x = 0.05, nudge_y = 0.05)
```

![](https://i.imgur.com/jK3tNBm.png)

``` r




st_join_agg <- function(x, y, join = st_intersects,..., aggfun){
  require(sf)
  require(dplyr)
  require(tibble)
  
  oldcols <- colnames(x)
  
  x <- x %>%
    rowid_to_column()
  
  newcol <- colnames(x)[!colnames(x) %in% oldcols]
  
  x_joined <- st_join(x,y,join,...) %>%
    group_by_(newcol) %>%
    summarise_if(.predicate = is.numeric,.funs = aggfun) %>%
    ungroup() 
  

}

squares_joined <- st_join_agg(squares,points,aggfun = mean)

ggplot(squares_joined) +
  geom_sf() + 
  geom_sf_label(aes(label = paste("Mean:",value))) +
  geom_sf(data = points) +
  geom_sf_text(data = points, aes(label = value),inherit.aes = FALSE,nudge_x = 0.05, nudge_y = 0.05)
```

![](https://i.imgur.com/PyXnjtv.png)

``` r


squares_joined <- st_join_agg(squares,points,aggfun = max)

ggplot(squares_joined) +
  geom_sf() + 
  geom_sf_label(aes(label = paste("Max:",value))) +
  geom_sf(data = points) +
  geom_sf_text(data = points, aes(label = value),inherit.aes = FALSE,nudge_x = 0.05, nudge_y = 0.05)
```

![](https://i.imgur.com/WLLqVGD.png)

<sup>Created on 2019-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
I feel that tidyverse wants you to live by the `group_by` - `summarise` two-step way of doing things, which `sf` supports, as you show. If tidyverse would come with a method doing both in one step, I'd support that, but it doesn't. 

The base R command that does both steps at once is called `aggregate`, and there is an `sf` method for that, where `by` can be a spatial object and the join predicate can be altered; have you looked at that?

If you'd do a polygon-polygon aggregate and want area weighting, look at `st_interpolate_aw` or functions in package `areal`.

**Comment by ratnanil** [comment]
Thanks for your answer. 
Using aggregate saves me an additional step (see below), but what still bothers me slightly about this approach is that I have to know (or create) a unique identifier for `x`s geometries (`id` in this case). 
```
st_join(squares,points) %>% aggregate(list(.$id),max) # sidenote: mean seems to behave very different from max in my minimal example
```
How is `st_join` dependent on the tidyverse way to do things? Wouldn't an additional, optional argument (e.g. `aggFun = `) in `st_join()` be independent of the tidyverse?

**Comment by edzer** [comment]
I meant sth like
```r
> aggregate(points, squares, mean)
Simple feature collection with 9 features and 1 field
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: -1.626673 ymin: -0.9549439 xmax: 1.373327 ymax: 2.045056
epsg (SRID):    NA
proj4string:    NA
  value                       geometry
1  7.50 POLYGON ((-1.626673 -0.9549...
2  3.00 POLYGON ((-0.6266727 -0.954...
3    NA POLYGON ((0.3733273 -0.9549...
4  8.00 POLYGON ((-1.626673 0.04505...
5  4.25 POLYGON ((-0.6266727 0.0450...
6  5.00 POLYGON ((0.3733273 0.04505...
7    NA POLYGON ((-1.626673 1.04505...
8  7.00 POLYGON ((-0.6266727 1.0450...
9    NA POLYGON ((0.3733273 1.04505...
```

**Comment by ratnanil** [comment]
I did not know this! Thank you, this is an amazing feature!
