### ISSUE TITLE
single-point lines created during snapping not detectable 

### ISSUE THREAD

**Issue by faridcher** [r-spatial/sf#1205]
The attached vector layers (e.g. bounds) are drawn with QGIS. My primary purpose is to use `st_polygonize` to find all the polygons enclosed by the boundaries.  With the use of `st_snap` (to snap the geometries to self), it is possible to detect all polygons and `st_polygonize` forms them all. However, in the process `st_snap` seems to produce many duplicate vertices which result in single-point lines after noding and casting. I could identify these single-point lines by eye-balling (e.g. `b` in the following example) but R does not consider their coordinates equal even though they are equal. `st_is_simple` which is supposed to find these single-point lines fails to find them all as well.
a reprex:

```r
library(sf)
xl <- st_read('subdiv.gpkg', 'bounds')
# many duplicate vertices are created next
xls <- st_snap(xl, xl, 0.001)
# this line captures them 
lapply(xls$geom, function(x) duplicated((x)))
# but if we unclass geometries (to get the matrices) duplicates won't be captured!
lapply(xls$geom, function(x) duplicated(unclass(x)))
# e.g. the last two vertices are identical
xls[342,]$geom[[1]]
```

[subdiv.zip](https://github.com/r-spatial/sf/files/3893834/subdiv.zip)

**Comment by edzer** [comment]
This is a data analysis issue, not necessarily an issue with sf. If nobody helps, I will close it here.

**Comment by faridcher** [comment]
thanks. I will try to provide a fine-grained example.

**Comment by faridcher** [comment]
the 2nd and 3rd vertices of the following snapped geometry looked the same but
they are not. R default print method on numeric vectors prints 7 significant
digits i.e. `signif(1234.56789)`. 

```r
xls$geom[[342]]
dput(xls$geom[[342]])
```

@edzer thanks again.
