### ISSUE TITLE
abbreviate_shapefile_names() abbreviates short names when long names are present

### ISSUE THREAD

**Issue by pasipasi123** [r-spatial/sf#1206]
When writing to a shapefile spec with `st_write` column names are limited to 10 characters, so in `sf` `abbreviate_shapefile_names()` is used. There's a bug though. Names shorter than 11 characters are also abbreviated, if there's at least one name longer than 10 characters.

I'm using sf_0.8-1.

``` r
x <- rlang::set_names(c("shortname", "tinyname"))
y <- rlang::set_names(c("shortname", "withsome", "verylongname"))

sf:::abbreviate_shapefile_names(x)
#>   shortname    tinyname 
#> "shortname"  "tinyname"

sf:::abbreviate_shapefile_names(y)
#> Warning in sf:::abbreviate_shapefile_names(y): Field names abbreviated for
#> ESRI Shapefile driver
#>        shortnm        withsom        vrylngn 
#>    "shortname"     "withsome" "verylongname"
```

<sup>Created on 2019-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Thanks! @rsbivand this was, I believe, code taken from rgdal.

**Comment by rsbivand** [comment]
Consider reverting your fix. The problem the over-use of abbreviate addressed was that (IIRC) abbreviating only too-long names could lead to non-uniqueness randomly, see rev 315-318 in 2011. It ended up both with abbreviating over the name vector then testing that this held also for all drivers. The only proper fix is to deprecate the driver. ?abbreviate mentions the non-uniqueness problem.

**Comment by pasipasi123** [comment]
I think uniqueness can easily be checked though.

**Comment by edzer** [comment]
Thanks; now reverted.
