### ISSUE TITLE
configure: error: GDALAllRegister not found in libgdal

### ISSUE THREAD

**Issue by lduvaux** [r-spatial/sf#1209]
Hi, I'm trying to install "sf" for the package "adegenet" on my manjaro laptop (using rstudio) but I keep getting this message:

`configure: error: GDALAllRegister not found in libgdal.`

However, I already have installed the dependencies as suggested:
`pacman -S gdal proj geos`

I've seen on the web that I should rebuild gdal but that does not work (note that under arch/manjaro, there is no dev version of a package, everything should already be in the regular package).

Many thanks for any help.

**Comment by lduvaux** [comment]
Note that my R and rstudio were installed using conda:
```
(base) [ludo@garuda ~]$ which R
/opt/anaconda/bin/R
(base) [ludo@garuda ~]$ which rstudio
/opt/anaconda/bin/rstudio
(base) [ludo@garuda ~]$ 
```

**Comment by edzer** [comment]
anaconda-R is not something that we support; you need to ask its community for help, I'm afraid.

**Comment by lduvaux** [comment]
OK thanks for your quick reply

**Comment by lduvaux** [comment]
I'll try to install "sf" on a regular R/rstudio installation and let you know how it goes.

**Comment by juliohm** [comment]
I am not using Anaconda, and still get the same error on Arch Linux when installing other packages such as `rspatial/terra`.

Any directions to fix the issue? GDAL is installed in the system with `pacman -S gdal`.

**Comment by juliohm** [comment]
The installation command I am using is `remotes::install_github("rspatial/terra")` Can you please confirm that it should work? I don't even have R-studio installed, just a plain R installation (version 4.0.4).

**Comment by edzer** [comment]
Terra has it's own issue, here: https://github.com/rspatial/terra/

**Comment by juliohm** [comment]
I think the issue is not on a specific package `terra` or `sf` but on the GDAL installation under the hood. I am trying to workaround the problem, but it is not easy. Maybe the packages are trying to install a different version of GDAL than the one I already have installed in the system, I don't know.

**Comment by HCharlie** [comment]
is there any update on this issue? I still have the error
ubuntu 20.04
R 4.2.3
gdalinfo --version 3.0.4 and 3.3.2 both are not working.

**Comment by agelosnm** [comment]
It's absolute embarrassing that installation and compatibilities issues are occurring for years now and no any clear documentation exists for linux environments.

**Comment by edzer** [comment]
@agelosnm please take notice of the [CoC](https://github.com/r-spatial/sf/blob/main/CONDUCT.md) of this project. Please consider providing positive contributions, e.g. to improving the README.md linux instructions or to the docker files found [here](https://github.com/r-spatial/sf/tree/main/inst/docker).

**Comment by agelosnm** [comment]
> @agelosnm please take notice of the [CoC](https://github.com/r-spatial/sf/blob/main/CONDUCT.md) of this project. Please consider providing positive contributions, e.g. to improving the README.md linux instructions or to the docker files found [here](https://github.com/r-spatial/sf/tree/main/inst/docker).

The thing here is that it is not clear at all for anyone on how to install this package for years! Searchning around leads you up to answers like "I did this and that and it worked". There is no clear path on how to move. Personally I have installed the latest available versions of GEOS, PROJ & GDAL from source and I would expect "sf" to be installed without any issues as this is also the official way to install those tools.

The existing documentation is quite old as the packages are installing older versions of them.

If I manage to install it I will provide some documentation for reference!

**Comment by edzer** [comment]
> The thing here is that it is not clear at all for anyone on how to install this package for years! 

I strongly disagree with the _anyone_. Most R users use windows or MacOS and install binary packages, in which case there is no problem at all, no need to even think about GEOS/Proj/GDAL; they can do this for released versions from CRAN or for dev versions from r-universe.dev. Many other users follow the instructions on the README, or use binary installs from linux binary packages, e.g. from Posit or r2u. I also get more and more reports on users being successful getting r-sf installed from conda-forge, although this is not supported by us.

**Comment by rsbivand** [comment]
And those experiencing problems often have multiple installs of GEOS, GDAL and/or PROJ: https://github.com/r-spatial/sf#multiple-gdal-geos-andor-proj-versions-on-your-system.
