### ISSUE TITLE
Read in `ndjson.gz`

### ISSUE THREAD

**Issue by josiekre** [r-spatial/sf#1212]
I'm trying to read in newline-delimited GeoJSON records (common output from say MongoDB) that are gzipped, but I can only get the unzipped file to read in. This unzipped works:

```
x <- sf::st_read("/path/to/file.ndjson", drivers = "GeoJSONSeq")
```

This does NOT:

```
x <- sf::st_read(
    gzcon(file("/path/to/file.ndjson.gz", "rb")), drivers = "GeoJSONSeq"
)
```

I tried using `gzfile()` too but no luck. The above `gzcon()` approach is the one that works with `jsonlite::stream_in()`.

Here is a sample `ndjson` file with Feature records:

```
{"type":"Feature","id":1,"geometry":{"type":"Point","coordinates":[-157.855676,21.304547]},"properties":{"place":"city"}}
{"type":"Feature","id":2,"geometry":{"type":"Point","coordinates":[-158.031025,21.685909]},"properties":{"place":"city"}}
```

**Comment by Robinlovelace** [comment]
Do you have an example file to test on? That could help testing in the search for solutions.

**Comment by edzer** [comment]
Have you tried prepending the file path with `/vsigzip/`?

**Comment by josiekre** [comment]
> Do you have an example file to test on? That could help testing in the search for solutions.

The last code bit above (2 lines) can be copied into a new file (name it 'test.ndjson') and then gzip it with:

```
gzip test.ndjson
```

> Have you tried prepending the file path with /vsigzip/?

Just now tried and this does not work out of box. I haven't previously heard of this virtual folder for GDAL so maybe I do not have it setup. 

```
> x <- sf::st_read("/vsigzip/local/path/to/file.ndjson.gz", drivers = "GeoJSONSeq")
options:        GeoJSONSeq 
Error: Cannot open "/vsigzip/local/path/to/file.ndjson.gz"; The file doesn't seem to exist.
```

**Comment by josiekre** [comment]
Upon reading further... absolute paths need another `\`. This works:

```
x <- sf::st_read("/vsigzip//local/absolute/path/to/file.ndjson.gz", drivers = "GeoJSONSeq")
```

Is this something the package could append if a `gz` extension is found without the prepend? I don't know if that makes sense, but it might be useful.

**Comment by edzer** [comment]
No, I think such users should learn about the `/vsixxx/` stuff in GDAL. R shouldn't prevent them from learning that.

**Comment by SymbolixAU** [comment]
Throwing in my 2 cents regarding getting data from MongoDB. This is my usual workflow and it may help.

I've modified `mongolite` in a [clone of the repo](https://github.com/SymbolixAU/mongolite/blob/master/R/mongo.R#L170) to use an `ndjson` argument, which returns a vector of GeoJSON (one element for each line).

Then you can convert the returned geojson to an sf object

```r
sf <- geojsonsf::geojson_sf( geo )
```

**Comment by josiekre** [comment]
I've looked at `geojsonsf`, but it has a GPL-3 license only. This project is generally trying to avoid GPL and stick with MIT or similar. But this is not the place for license discussions. 

Thanks @SymbolixAU. Your example might help others.

**Comment by SymbolixAU** [comment]
@josiekre That's an interesting point, and I've never really put much thought into licensing. I see [here](https://github.com/r-spatial/sf/blob/master/DESCRIPTION#L49) that `sf` uses both GPL and MIT, would it help if I considered something similar for `geojsonsf`?

**Comment by josiekre** [comment]
@SymbolixAU Yes a dual license with MIT would allow us to use it.

**Comment by dcooley** [comment]
digging up an old post - `geojsonsf` now has an MIT licence - https://github.com/SymbolixAU/geojsonsf/blob/master/DESCRIPTION

**Comment by arthurgailes** [comment]
For what it's worth, the original problem can be solved with `geojsonsf`. Warning that this is a large file.

```
library(sf)
library(geojsonsf)
u <- 'https://int.nyt.com/newsgraphics/elections/map-data/2020/national/precincts-with-results.geojson.gz'
f <- gzcon(url(u, 'rb'))
t <- geojson_sf(f)
```
