### ISSUE TITLE
FR: sf_column()

### ISSUE THREAD

**Issue by krlmlr** [r-spatial/sf#1214]
instead of `attr(x, "sf_column")`, internally and for users of the package? A setter would be useful too.

**Comment by edzer** [comment]
I think the user-side function I had in mind for getting this done is
```
st_set_geometry(x, sf_column_name = "sf_column")
```
but that does a bit more than only setting the attribute (validating `x`, returning an `sf` object if `x` is `data.frame`). Do you think that just setting this attribute deserves a function of itself?

**Comment by krlmlr** [comment]
I think a getter and a setter would be great, the latter should err if the column is not an sfc.

**Comment by edzer** [comment]
I vote against this and need broad support before doing this. Normal users should never need this, and those who do know how to use `attr`. I'm in favor of keeping the number of exported functions limited. I also don't like functions with a name longer than the body.

**Comment by etiennebr** [comment]
I also think it would be useful. Not for regular usage, but for e.g. package developers I think it would be useful and add a lilte layer that could be useful if to make changes to sfc columns, or change the way we handle multiple geometry columns, or `data.frame` with an `sfc` column. 

Maybe it could be exported, but not prefixed with `st_` to indicate it's not a function users should need.
