### ISSUE TITLE
[0.8] converting from sp to sf size increases 6x

### ISSUE THREAD

**Issue by spono** [r-spatial/sf#1216]
Hi devs,
is there a technical explanation why converting a huge `SpatialPointDataFrame` file using `st_as_sf`, the initial memory size (appr. 2Gb) increases at least 6x exhausting the available memory (16Gb)?
Is is a matter of different data structure or some kind of memory leak?
thanks in advance

**Comment by etiennebr** [comment]
Thanks for reporting this issue  @spono, would you happen to have a reproducible examples? Conversion from sp usually works, so there seems to be something specific with your data.

**Comment by edzer** [comment]
It's the data structure: every point is stored as a length-2 vector in a list in sf, whereas sp stores all points in a 2-column matrix. A consequence of doing simple features systematically.

**Comment by etiennebr** [comment]
You could try to convert in small batches (by subsetting the sp object), because `st_as_sf` creates a few copies of the coordinates, so it might help stay below the memory limit.

**Comment by spono** [comment]
> 
> 
> You could try to convert in small batches (by subsetting the sp object), because `st_as_sf` creates a few copies of the coordinates, so it might help stay below the memory limit.

yep, that's how I solved. Thanks!

Unfortunately right now I can't provide data because they're still private...but still good to know that the data structure transformation could drive to such behaviour. Thanks @edzer
