### ISSUE TITLE
sf_project() fails at S pole with proj=lcc

### ISSUE THREAD

**Issue by dankelley** [r-spatial/sf#1227]
I noticed that `sf_project()` fails at the south pole, with the LCC projection.  A test code is provided below, along with results on my (osx catalina, R-devel) machine.

This came up for me in coding the oce package to use `sf::sf_project()` (reference https://github.com/dankelley/oce/issues/1629#issuecomment-569106096), but it is not a blocking issue for me, because I can make oce move such points to be a tiny bit north of the pole. Still, I thought I ought to point this out, in case doing so would be of use to the `sf` team.

```R
## Show that sf_project() fails at south pole, with Lambert Conic Conformal projection
library(sf)
from <- "+proj=longlat"
to <- "+proj=lcc +lat_0=30 +lat_1=60"
tol <- 1e-4
try(sf::sf_project(from, to, cbind(0, 90))) # OK
try(sf::sf_project(from, to, cbind(0, -90))) # fails
for (power in seq(-8, -11)) {
    eps <- 10^power
    cat(sprintf("eps=%15.12e\n", eps))
    try(sf::sf_project(from, to, cbind(0, -90 + eps)))
}
```

[sf_bug_report.txt](https://github.com/r-spatial/sf/files/4003245/sf_bug_report.txt)

**Comment by edzer** [comment]
Thanks; this is a property of the underlying library, PROJ; using command line `proj`:
```bash
$ echo "0 -89.99999999" | proj +proj=lcc +lat_0=30 +lat_1=60
0.00	-5879242108888943.00
$ echo "0 -89.999999999" | proj +proj=lcc +lat_0=30 +lat_1=60
*	*
```
as this is not an issue of `sf`, I'm closing here.

**Comment by dankelley** [comment]
Thanks for the very quick response.  I apologize for commenting on a closed issue, and would understand completely if you just ignore this, but I wonder whether I could make a respectful suggestion (after a prelude)...

*1. Prelude*

I tried something closer to my real application, with multiple points
```
sf echo "0 0\n0 -90\n0 1" | proj +proj=lcc +lat_0=30 +lat_1=60
0.00    -4329324.29
*       *
0.00    -4158078.42
```
i.e. it does not fail, but rather reveals problematic points

But I see why `st_transform()` is acting as it does, because its c++ function `CPL_proj_direct()` (at `src/proj.cpp` line 93) calls `proj_trans_array()`, which  https://proj.org/development/reference/functions.html reveals will return an error code if any single point is problematic.

My reading of https://proj.org/development/reference/functions.html gives me to understand that `proj_trans()` deals with a single point at a time. 

*2. Suggestion*

I wonder would other `sf` users be interested in an extra argument to `sf::sf_transform()` to make it call `proj_trans()` for each row of a matrix (sorry, I know I'm not using the right words here) instead of using `proj_trans_array()` on all the matrix rows at once?  That way, people who want to get an error if there is any problematic points can get the error, but some other people (odd people, like me) could get NA values for the problematic points.

*3. Postscript and apology*

Again, please  just ignore this, if I'm being a pest. You may notice that all of my issues and questions have related to this theme of wanting to get NA (or Inf or some recognizable value) for problematic points, because oce users need that kind of thing in their work.  (For example, we often deal with isolated points, such as a position where a ship was in making a measurement, as opposed to polygons.  A set of points where a ship had stopped is called a "transect", and we would not want to lose information about a whole transect, e.g. in mapping data, if some points were on the "other side" of a world view.)

**Comment by dankelley** [comment]
As a way to try to learn more about the proj API, I did a little test (git patch attached).  I do not want to presume that you want to use this, @edzer, so the code is not complete, i.e. I have not added an extra argument to `CPL_proj_direct()` to select between the two schemes, nor have I altered `R/transform.R` and `R/RcppExports.R` to offer the user the choice.

If you think there is any merit in what I am thinking of, I'd be happy to code this up more fully, and to update the documentation, providing the results in a pull request. However, I do not want to presume your interest in the suggestion.  Since you've closed this issue, perhaps I ought to keep my thoughts to myself.

Thanks for your patience (if you have any left!), and best for the new year.

[dek_patch.txt](https://github.com/r-spatial/sf/files/4005345/dek_patch.txt)

**Comment by edzer** [comment]
I can see that makes sense and would welcome a PR in that direction. Does your approach return out-of-range values as R `NA`s?

**Comment by dankelley** [comment]
Yes, it returns as `NA`s.  I'll have a look at it tomorrow (right now I'm revising a paper about the physics of ships hitting whales ... no map projection there at all!).

**Comment by dankelley** [comment]
I've made a PR, but I should note that I was not at all sure how to handle the old proj API, and also that I am perplexed by the different results I get in commandline `proj`. These things are discussed in more depth in my ~800 word commit note.

**Comment by dankelley** [comment]
Oh, sorry, regarding the different to commandline proj, I think it is because I was giving `lat_0` when I meant `lat_1`; things agree if I specify `lat_1` and `lat_2` in the two systems.
```R
> sf_project("+proj=longlat","+proj=lcc +lat_1=30 +lat_2=60", cbind(0,-80),TRUE)
     [,1]      [,2]
[1,]    0 -53554590
> system("echo '0 -80' | proj +proj=lcc +lat_1=30 +lat_2=60")
0.00	-53554589.59
```

**Comment by rsbivand** [comment]
@dankelley : **rgdal** rev 921 now has P6-adapted `project()`, which seems to perform as before, so hopefully this will remain an alternative. https://github.com/dankelley/oce/issues/1604
