### ISSUE TITLE
extract attribute values from origins in st_intersection

### ISSUE THREAD

**Issue by andriatz** [r-spatial/sf#1230]
Hi,
i want to create a column that contains some information about attributes after st_intersection.

    a <- st_point(c(1,1))
    b <- st_point(c(1,2))
    c <- st_point(c(2,1))

    g <- st_sfc(a,b,c)
    
    s <- st_sf(id=c("a","b","c"), g) %>% st_buffer(dist = 1) 
    st_intersection(s) 

    Simple feature collection with 7 features and 3 fields
    geometry type:  GEOMETRY
    dimension:      XY
    bbox:           xmin: 0 ymin: 0 xmax: 3 ymax: 3
    epsg (SRID):    NA
    proj4string:    NA
    id n.overlaps origins                              g
    1    a          1       1 POLYGON ((1.5 0.1339746, 1....
    1.1  a          2    1, 2 POLYGON ((0.1339746 1.5, 0....
    2    b          1       2 POLYGON ((2 2, 2 2, 2 2, 1....
    1.2  a          2    1, 3 POLYGON ((2 1, 1.99863 0.94...
    1.3  a          3 1, 2, 3 GEOMETRYCOLLECTION (LINESTR...
    2.1  b          2    2, 3 POLYGON ((2 2, 1.99863 1.94...
    3    c          1       3 MULTIPOLYGON (((3 1, 2.9986...

the column origins i related to row.names, i'd like to create a column "att" that contains the concatenated values of id, something like this:

    Simple feature collection with 7 features and 4 fields
    geometry type:  GEOMETRY
    dimension:      XY
    bbox:           xmin: 0 ymin: 0 xmax: 3 ymax: 3
    epsg (SRID):    NA
    proj4string:    NA
      id n.overlaps origins                              g   att
    1  a          1       1 POLYGON ((1.5 0.1339746, 1....     a
    2  a          2    1, 2 POLYGON ((0.1339746 1.5, 0....    a,b
    3  b          1       2 POLYGON ((2 2, 2 2, 2 2, 1....     b
    4  a          2    1, 3 POLYGON ((2 1, 1.99863 0.94...   a,c
    5  a          3 1, 2, 3 GEOMETRYCOLLECTION (LINESTR... a,b,c
    6  b          2    2, 3 POLYGON ((2 2, 1.99863 1.94...   b,c
    7  c          1       3 MULTIPOLYGON (((3 1, 2.9986...     c

is it possible from st_intersection or maybe there is an elegant way to manipulate the origins column?

**Comment by edzer** [comment]
```r
i = st_intersection(s)
i$ids = sapply(i$origins, function(x) paste0(as.character(s$id)[x], collapse = ","))
i$ids
# [1] "a"     "a,b"   "b"     "a,c"   "a,b,c" "b,c"   "c"
```

**Comment by andriatz** [comment]
Thank you. Looking better i see that st_intersection generates one geometrycollection and one multypolygon, it seems strange, i replicate the same workflow on mapshaper (using mosaic funciont) and it creates a correct output

    mapshaper -i ./inputLayer.geojson -mosaic calc='output=collect(id).toString()' -o ./output.geojson

**Comment by edzer** [comment]
That is a precision issue:
```r
i = st_intersection(st_set_precision(s, 10000))  # generates POLYGONs
plot(i["n.overlaps"])
```
![x](https://user-images.githubusercontent.com/520851/71664320-e163af80-2d58-11ea-87cf-f2125ffb33ec.png)

What does `mapshaper` give as output?

**Comment by andriatz** [comment]
This is the import of the output.geojson generated by mapshaper 

    Simple feature collection with 7 features and 1 field
    geometry type:  POLYGON
    dimension:      XY
    bbox:           xmin: 0 ymin: 0 xmax: 3 ymax: 3
    epsg (SRID):    4326
    proj4string:    +proj=longlat +datum=WGS84 +no_defs
      output                       geometry
    1    a,c POLYGON ((1.866025 1.5, 1.8...
    2      c POLYGON ((1.5 0.1339746, 1....
    3      a POLYGON ((1.5 0.1339746, 1....
    4    a,b POLYGON ((0.1339746 1.5, 0....
    5      b POLYGON ((1.5 1.866025, 1.4...
    6  a,b,c POLYGON ((1.5 1.866025, 1.5...
    7    b,c POLYGON ((1.866025 1.5, 1.8...

**Comment by edzer** [comment]
Looks similar. Close here?
