### ISSUE TITLE
shapefile full extent on R plotting device

### ISSUE THREAD

**Issue by FelipeCarrillo** [r-spatial/sf#1235]
Hi, I am totally new to sf and currently going through tutorials. One thing that I noticed and can't find it in any of the tutorials is the R device screen plot size. All of my shapefiles render in the middle of the plot device having a lot of white space above and below. Question, is there an argument inside geom_sf() to extend the plot to the entire screen?

**Comment by edzer** [comment]
Hi, `geom_sf()` is part of `ggplot2`, you may want to ask there (after reading those tutorials). For base plots I could be more helpful.

**Comment by FelipeCarrillo** [comment]
Ok, thank you.
