### ISSUE TITLE
gdal.h not found in given locations

### ISSUE THREAD

**Issue by istfer** [r-spatial/sf#1236]
Hi, I'm trying to install and compile sf on a Red Hat Enterprise Linux Server v7.7

We have been experiencing GDAL related problems. First, the version was the issue (we had 1.11.4, sf required >= 2.0.1). Since then we are having hard time finding the right combination of dependencies and versions. 

I would appreciate your help starting with this one.

`locate gdal-config` brings:
```
/usr/bin/gdal-config
/usr/bin/gdal-config-64
```

`/usr/bin/gdal-config --version` gives me this:
```
-bash: /usr/bin/gdal-config: No such file or directory
```

while `/usr/bin/gdal-config-64 --version` returns:
```
3.0.1
```

So I was trying to install with `install.packages('sf', type = "source", configure.args=c('--with-gdal-config=/usr/bin/gdal-config-64'))` which can't find gdal.h:

```
* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -m64 -std=gnu99
configure: CXX: g++ -m64 -std=gnu++11
configure: gdal-config set to /usr/bin/gdal-config-64
checking gdal-config exists... yes
checking gdal-config executable... yes
checking gdal-config usability... yes
configure: GDAL: 3.0.1
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -m64 -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -m64 -std=gnu99 accepts -g... yes
checking for gcc -m64 -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -m64 -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... no
checking gdal.h presence... no
checking for gdal.h... no
configure: error: gdal.h not found in given locations.
ERROR: configuration failed for package ‘sf’
```

I have a `gdal.h` under `/usr/include/gdal/gdal.h`. Is this a matter of specifying the right paths/environment?

**Comment by edzer** [comment]
What does `/usr/bin/gdal-config-64 --cflags` give as output?

**Comment by dothakola** [comment]
Hi,

The actual error while trying to compile sf with gdal-3.0.1 is as follows:

        testing if installed package can be loaded from temporary location
        Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
        unable to load shared object '/usr/lib64/R/library/00LOCK-sf/00new/sf/libs/sf.so':
        /usr/gdal30/lib/libgdal.so.26: undefined symbol: GEOSMakeValid_r
        Error: loading failed
        Execution halted
        ERROR: loading failed
        removing ‘/usr/lib64/R/library/sf’

istfer didn't find the gdal header files as this version of gdal was already removed while trying to compile another version of gdal.

BR
sysadm

**Comment by istfer** [comment]
Is it then related to [the multiple versions](https://github.com/r-spatial/sf#multiple-gdal-geos-andor-proj-versions-on-your-system) issue?

@dothakola could [this](https://github.com/r-spatial/sf/issues/1158) be related?

**Comment by Basha-EDB** [comment]
> /usr/bin/gdal-config-64 --cflags

[buildfarm@docker-desktop builds.edb]$ /usr/libexec/edb-gdal30/bin/gdal-config-64 --cflags
-I/usr/libexec/edb-gdal30/include/gdal
I'm passing 
  LIBGDAL_LDFLAGS="-L%{gdalinstdir}/lib -lgdal"; export LIBGDAL_LDFLAGS
LIBGDAL_CFLAGS="-I%{gdalinstdir}/include/gdal"; export LIBGDAL_CFLAGS
CFLAGS="$CFLAGS -I%{gdalinstdir}/include/gdal"; export CFLAGS

Though I got an error.  Can you help me out with this? I didn't understand why it's not picking its CFLAGS path 

I too faced the same error.
checking gdal.h usability... no
checking gdal.h presence... no
checking for gdal.h... no
configure: error: could not find GDAL headers
