### ISSUE TITLE
Wrong counties added with st_intersection

### ISSUE THREAD

**Issue by ChristophVSteinert** [r-spatial/sf#1239]
Hi,

I have one map with SO2-Pollution and one map with counties of the former GDR that I like to match with 'st_intersection'. That works but in this process some SO2-values are added for counties in Western Germany where originally no SO2-values existed (e.g. Göttingen, Fulda,...). Why does this happen and how could I avoid this problem?

Thanks in advance for your help!

```r
library(tidyverse)
library(sf)
counties <- read_sf('Germany_1989_v.1.0.shp')
so2 <- read_sf('EstGermany_77_final.shp')
ggplot(so2, aes(geometry=geometry, fill=factor(Range) )) + geom_sf()
head(so2)

counties <- st_transform(counties, st_crs(so2)$epsg)

res <- st_intersection(st_buffer(so2,0),
                       st_buffer(counties,0))
```

**Comment by edzer** [comment]
intersection means any intersection: that could be areas overlapping, covering, or even touching. Without having access to your data I can of course say nothing about your problem; if you want to share a reproducible example first try to make it as small as possible.

**Comment by ChristophVSteinert** [comment]
Thanks for your quick reply! How can I share the data? I realized that I cannot upload data in the .shp format....

**Comment by ChristophVSteinert** [comment]
I managed to upload them as xlsx-files. Is this useful?

**Comment by edzer** [comment]
No.

**Comment by ChristophVSteinert** [comment]
Could you at least give a hint how to add sf-data to a reproducible example? The usual way doesn't work with the "geometry-column" and I couldn't find an alternative solution.

**Comment by edzer** [comment]
I'm sorry, but that burden lies on your side. You could browse the sf issues and look for examples where people succeeded to provide a reprex.
