### ISSUE TITLE
Unexpected plotting behavior with knitr/reprex

### ISSUE THREAD

**Issue by rubak** [r-spatial/sf#1241]
I have observed weird plotting behavior when running the following
code with knitr in a reprex using the `reprex` package. Everything
behaves as expected if I run it interactively. Can others reproduce?
**NOTE: This is run with the dev version of `sf` where the master branch can handle conversion to/from `spatstat` objects**

``` r
library(spatstat)
#> Loading required package: spatstat.data
#> Loading required package: nlme
#> Loading required package: rpart
#> 
#> spatstat 1.62-2       (nickname: 'Shape-shifting lizard') 
#> For an introduction to spatstat, type 'beginner'
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
```

The polygon below is centered around (0,0), but it seems the plotting
region is a unit box centered in (0.5,0.5), so (0.1,0.1), is plotted
in the bottom left corner:

``` r
W <- Window(gordon)
W_sf <- st_as_sf(W)
W_sf
#> Simple feature collection with 1 feature and 0 fields
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: -26.40848 ymin: -36.32095 xmax: 26.40848 ymax: 36.32095
#> epsg (SRID):    NA
#> proj4string:    NA
#>                             geom
#> 1 POLYGON ((22.0448 -14.20711...
plot(W_sf, col = 2)
p_sf <- st_point(matrix(c(0.1,0.1),ncol=2))
plot(p_sf, add = TRUE, col = 4)
```

![](https://i.imgur.com/66cofu2.png)

If the bounding box is plotted first and the polygon is
added afterwards everything works as expected and (0.1,0.1) is close to
the center of the polygon.

``` r
plot(st_as_sfc(st_bbox(W_sf)))
plot(W_sf, add = TRUE, col = 2)
plot(p_sf, add = TRUE, col = 4)
```

![](https://i.imgur.com/wgAUObn.png)

**Comment by edzer** [comment]
If you want to add elements after using `plot` on an `sf` object, you need add parameter `reset = FALSE`. This is not the case for `sfc` objects. It is caused by reserving room for the key/legend.

**Comment by rubak** [comment]
Thanks for clarifying this. I must have confused myself at some point because I had the impression when I ran some code that I got different plots using `knitr` and running interactively. This does not seem to be the case. I may have experienced that I plotted a point outside the window which I could still see interactively, but which was cut off in the margins by `knitr`. Anyway, thanks for your help.

**Comment by rubak** [comment]
Sorry to reopen this, but I once again seemed to experience different behaviour interactively and in a reprex. I encountered the problem while writing [this answer on SO](https://stackoverflow.com/a/61731172/3341769).

I **think** I finally understand what is going on and would like to check whether this is expected behaviour:
Setting up data:

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
nc <- st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
n <- 3
poly_dat <- st_sf(poly_id = LETTERS[1:n], geom = nc$geometry[1:n])
line1 <- st_linestring(rbind(c(-81.8,36.5),c(-80.5,36.5)))
line2 <- st_linestring(rbind(c(-81,36.3),c(-80.5,36.3)))
line_dat <- st_sf(linename = c("1", "2"), geometry = st_sfc(line1, line2, crs = st_crs(poly_dat)))
```

This is what I believe is the correct plotting procedure:

``` r
plot(poly_dat, reset = FALSE)
plot(line_dat, add = TRUE, col = 1:2, lty = 2)
legend("topright", legend = paste("Line", 1:2), col = 1:2, lty = 2)
```

![](https://i.imgur.com/HvIk3IQ.png)

Here the missing reset causes the lines not to be plotted (in the right place):

``` r
plot(poly_dat)
plot(line_dat, add = TRUE, col = 1:2, lty = 2)
legend("topright", legend = paste("Line", 1:2), col = 1:2, lty = 2)
```

![](https://i.imgur.com/XxIky0J.png)

However, if one has made a previous plot of a certain kind (with implicit
`reset = FALSE` I assume) the behaviour of the plot command is different (“correct”):

``` r
plot(poly_dat$geom)
```

![](https://i.imgur.com/WKq0Ldh.png)

``` r
plot(poly_dat)
plot(line_dat, add = TRUE, col = 1:2, lty = 2)
legend("topright", legend = paste("Line", 1:2), col = 1:2, lty = 2)
```

![](https://i.imgur.com/emxKPdd.png)

Is it expected that a previous plot has side effects that change behaviour of the
current plot? It really confused me a lot for a long time, since it seemed things were
different when I worked interactively than when I rendered a reprex.

**Comment by edzer** [comment]
It is expected that without `reset = FALSE`, plot commands that follow with `add = TRUE` are misplaced, and that is what you found. 

About the side effect from a previous plot: maybe `plot.sf()` needs to call `plot.new()` at startup (if `add=TRUE` is not given); I asumed that `layout(matrix(1))` had the same effect, but it doesn't.

**Comment by rubak** [comment]
Thanks for the quick reply.

> It is expected that without reset = FALSE, plot commands that follow with add = TRUE are misplaced, and that is what you found.

Yes, this is no surprise (after you told me a about it some months ago ;-)).

> About the side effect from a previous plot: maybe plot.sf() needs to call plot.new() at startup (if add=TRUE is not given); I asumed that layout(matrix(1)) had the same effect, but it doesn't.

OK. This is the part that confused me. I hope you can find a way to change the behaviour.

**Comment by edzer** [comment]
I can no longer reproduce the funny placed lines, and think that `plot.new` is now always called before plotting something without `add = TRUE`. Please reopen if I'm wrong!
