### ISSUE TITLE
st_write with GDAL error

### ISSUE THREAD

**Issue by piiiiman** [r-spatial/sf#1247]
I'm trying to write a shapefile to CSV using:

`st_write(shapefile, "path/XXX.csv", layer_options = "GEOMETRY=AS_XY")`

The format of the shapefile is:

Simple feature collection with 6248811 features and 19 fields (with 1423006 geometries empty)
geometry type:  POINT
dimension:      XY
bbox:           xmin: -81.59492 ymin: 28.54207 xmax: -81.20455 ymax: 28.65672
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs

But it gives me the following errors:

`
Creating field ID failed.
Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Layer creation failed.
In addition: Warning message:
In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 1: Attempt to create field ID, but a field with this name already exists.
`

Any ideas about this problem? Thank you.

**Comment by edzer** [comment]
It would be helpful if you could provide a (small) reproducible example, if needed of-line by email.

**Comment by piiiiman** [comment]
> It would be helpful if you could provide a (small) reproducible example, if needed of-line by email.

Hi Edzer, Thank you for your reply. I just find the problem is because I have two columns with names as 'id' and 'ID'. After I change 'id' to 'new_id', the code works fine. I did not know the 'sf' is case sensitive or not before.

**Comment by piiiiman** [comment]
> It would be helpful if you could provide a (small) reproducible example, if needed of-line by email.

Also, it works fine when I write it to shapefile. It automatically renames one of the 'id' and 'ID'

**Comment by edzer** [comment]
OK, thanks; so this seems a GDAL issue; you may want to follow up there.
