### ISSUE TITLE
Examples for agr in documentation

### ISSUE THREAD

**Issue by MichaelChirico** [r-spatial/sf#1251]
I'm trying to learn how to use `st_as_sf`; it points me to `?st_sf` for understanding its `agr` argument, which is described in `agr` with:

> `agr`, attribute-geometry-relationship, specifies for each non-geometry attribute column how it relates to the geometry, and can have one of following values: `"constant"`, `"aggregate"`, `"identity"`. `"constant"` is used for attributes that are constant throughout the geometry (e.g. land use), `"aggregate"` where the attribute is an aggregate value over the geometry (e.g. population density or population count), `"identity"` when the attributes uniquely identifies the geometry of particular "thing", such as a building ID or a city name. The default value, `NA_agr_`, implies we don't know.

This sounds basically OK, but I still don't know how to _use it_. Do we supply `agr` as a vector? Named list? I've only come across a few examples in a quick search and they all supply only one `agr` value, so the "for each non-geometry... column" part is unexplored.

**Comment by edzer** [comment]
Cool! There's an example in 
```r
demo(nc)
```
