### ISSUE TITLE
troubles with reprojecting a shapefile and writing the result

### ISSUE THREAD

**Issue by ericemc3** [r-spatial/sf#1253]
I am trying to reproject a shapefile (from epsg 4267 to 3857) and save it:
```
nc = st_read(system.file("shape/nc.shp", package="sf"))
st_transform(nc, 3857)
st_write( nc, "c:/apps/R/ncnew.shp",  delete_layer =TRUE ) 

nc = st_read("c:/apps/R/ncnew.shp")
```
wrong result here, the saved shapefile looks identical to the original (checked with Qgis)
_Reading layer `ncnew' from data source `c:\apps\R\ncnew.shp' using driver `ESRI Shapefile'
Simple feature collection with 100 features and 14 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs_

2d attempt, specifying the new crs after st_transform
```
nc = st_read(system.file("shape/nc.shp", package="sf"))
st_transform(nc, 3857)
st_crs(nc)$proj4string = "+init=epsg:3857"
st_write( nc, "c:/apps/R/ncnew.shp", delete_layer =TRUE ) 

nc = st_read("c:/apps/R/ncnew.shp")
```
wrong result here, the saved shapefile has inconsistent definitions, between epsg and coordinates (checked with Qgis)
_Reading layer `ncnew' from data source `c:\apps\R\ncnew.shp' using driver `ESRI Shapefile'
Simple feature collection with 100 features and 14 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
epsg (SRID):    3857
proj4string:    +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs_

The only way i found to get it right (checked with Qgis):
```
nc = st_read(system.file("shape/nc.shp", package="sf"))
st_crs(nc)$proj4string = str_c("+init=epsg:", st_crs(nc)$epsg)
st_transform(nc, 3857)
st_crs(nc)$proj4string = "+init=epsg:3857"
st_write( nc, "c:/apps/R/ncnew.shp", delete_layer =TRUE ) 

nc = st_read("c:/apps/R/ncnew.shp")
```
Reading layer `ncnew' from data source `c:\apps\R\ncnew.shp' using driver `ESRI Shapefile'
Simple feature collection with 100 features and 14 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
epsg (SRID):    3857
proj4string:    +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs

**Comment by tim-salabim** [comment]
R does not update by reference, so you need to save the result of `st_transform` in an object

```r
nc = st_read(system.file("shape/nc.shp", package="sf"))
ncnew = st_transform(nc, 3857)
st_write( ncnew, "c:/apps/R/ncnew.shp",  delete_layer =TRUE ) 
```

should work

**Comment by ericemc3** [comment]
my mistake indeed, thank you.
Actually the new shapefile created does not align well in Qgis (over OpenStreetMap for instance) it displays a strange ESRI54004 reference system
![image](https://user-images.githubusercontent.com/17407796/73259967-344e4c80-41c9-11ea-8b8e-aecd34e8a572.png)

However, the final result is correct if i add this line:
nc <- st_read(system.file("shape/nc.shp", package="sf"))
ncnew <-  st_transform(nc, 3857)
**st_crs(ncnew)$proj4string = "+init=epsg:3857"**
st_write( ncnew, "c:/apps/R/ncnew.shp", delete_layer=TRUE )

**Comment by tim-salabim** [comment]
Don't know about the Qgis issue, but you usually shouldn't need this extra line

**Comment by rsbivand** [comment]
For your platform, please show the versions of GDAL and PROJ, for example with `sf_extSoftVersion()`.

**Comment by ericemc3** [comment]
Hi @rsbivand , here it is
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.6.1"        "2.2.3"        "4.9.3"         "true"        "false" 

newnc.prj=>recognized by Qgis as ESRI:54004
PROJCS["Mercator_2SP",GEOGCS["GCS_unnamed ellipse",DATUM["D_unknown",SPHEROID["Unknown",6378137,0]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Mercator"],PARAMETER["standard_parallel_1",0],PARAMETER["central_meridian",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]

with st_crs(ncnew)$proj4string = "+init=epsg:3857"
newnc.prj=>=>recognized by Qgis as EPSG:3857
PROJCS["WGS_1984_Web_Mercator_Auxiliary_Sphere",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Mercator_Auxiliary_Sphere"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",0.0],PARAMETER["Standard_Parallel_1",0.0],PARAMETER["Auxiliary_Sphere_Type",0.0],UNIT["Meter",1.0]]

**Comment by rsbivand** [comment]
OK, so you are firmly in history (PROJ 7 coming shortly). Maybe QGIS is running a later PROJ?

**Comment by ericemc3** [comment]
well, i have installed sf package in R Studio maybe one week ago, so my history is short... will try and figure out how to update proj4 within R

**Comment by rsbivand** [comment]
No, nothing to do with any of that. R Studio is also completely irrelevant. **sf** is built against three major external libraries - GEOS, GDAL and PROJ. They are also versioned. Your platform is probably Windows or OSX, and you installed **sf** most likely as a binary package from CRAN. That binary package contains statically linked parts of GEOS, GDAL and PROJ from when the binary package was built. However, QGIS also links to GEOS, GDAL and PROJ, and probably links to different versions of that external software, which behave differently (latest QGIS uses PROJ6 and GDAL3, your **sf** uses PROJ4 and GDAL2). If you are installing binary R packages, there is nothing you can do.

**Comment by ericemc3** [comment]
Thank you, this is perfectly clear. I am indeed on Windows. So i'll wait for an upcoming windows binary version of sf linked to PROJ6 and GDAL3. Meanwhile the st_crs(ncnew)$proj4string = "+init=epsg:3857" trick works nicely

**Comment by rsbivand** [comment]
It should never be used, and you should discard it promptly. `+init=` will go away soon, `+datum=` is gone in PROJ6. Saying `st_crs(ncnew)$proj4string = "+init=epsg:3857"` is inserting an unchecked verbatim string into an object, `st_crs(ncnew) = "+init=epsg:3857" ` is (trying to) overwrite the `"crs"` object. This kind of usage is very grief-prone going forward.

**Comment by ericemc3** [comment]
ok, i agree with you for the most part but 

> st_crs(ncnew)$proj4string = "+init=epsg:3857" is inserting an unchecked verbatim string into an object

 looks strange to me... since the $proj4string targets a string inside the object and not the whole crs object

**Comment by rsbivand** [comment]
Precisely - developers may perhaps circumvent internal sanity checks, but users should not:

```
> my_crs <- st_crs("+init=epsg:3857")
> my_crs
Coordinate Reference System:
  EPSG: 3857 
  proj4string: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs"
> my_crs$proj4string <- "+init:epsg:0000"
> my_crs
Coordinate Reference System:
  EPSG: 3857 
  proj4string: "+init:epsg:0000"
> my_crs$epsg <- 1111
> my_crs
Coordinate Reference System:
  EPSG: 1111 
  proj4string: "+init:epsg:0000"
> st_crs("+init:epsg:0000")
proj_create: unrecognized format / unknown name
Error: invalid crs: +init:epsg:0000, reason: generic error of unknown origin
```
