### ISSUE TITLE
Problems installing sf on linuxmint 19.3

### ISSUE THREAD

**Issue by PauGallesClara** [r-spatial/sf#1256]
Hi 
I'm trying to install sf package and I get this error:

ERROR: configuration failed for package ‘systemfonts’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/systemfonts’
Warning in install.packages :
  installation of package ‘systemfonts’ had non-zero exit status
* installing *source* package ‘deldir’ ...
** package ‘deldir’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran -fno-optimize-sibling-calls  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong  -c acchk.f -o acchk.o
/bin/bash: gfortran: no s'ha trobat l'ordre
/usr/lib/R/etc/Makeconf:191: recipe for target 'acchk.o' failed
make: *** [acchk.o] Error 127
ERROR: compilation failed for package ‘deldir’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/deldir’
Warning in install.packages :
  installation of package ‘deldir’ had non-zero exit status
* installing *source* package ‘classInt’ ...
** package ‘classInt’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran -fno-optimize-sibling-calls  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong  -c fish1.f -o fish1.o
/bin/bash: gfortran: no s'ha trobat l'ordre
/usr/lib/R/etc/Makeconf:191: recipe for target 'fish1.o' failed
make: *** [fish1.o] Error 127
ERROR: compilation failed for package ‘classInt’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/classInt’
Warning in install.packages :
  installation of package ‘classInt’ had non-zero exit status
ERROR: dependency ‘systemfonts’ is not available for package ‘gdtools’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/gdtools’
Warning in install.packages :
  installation of package ‘gdtools’ had non-zero exit status
ERROR: dependency ‘deldir’ is not available for package ‘spatstat’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/spatstat’
Warning in install.packages :
  installation of package ‘spatstat’ had non-zero exit status
ERROR: dependency ‘classInt’ is not available for package ‘sf’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status
ERROR: dependency ‘sf’ is not available for package ‘leafem’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/leafem’
Warning in install.packages :
  installation of package ‘leafem’ had non-zero exit status
ERROR: dependency ‘gdtools’ is not available for package ‘svglite’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/svglite’
Warning in install.packages :
  installation of package ‘svglite’ had non-zero exit status
ERROR: dependency ‘sf’ is not available for package ‘lwgeom’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/lwgeom’
Warning in install.packages :
  installation of package ‘lwgeom’ had non-zero exit status
ERROR: dependencies ‘sf’, ‘svglite’ are not available for package ‘leafpop’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/leafpop’
Warning in install.packages :
  installation of package ‘leafpop’ had non-zero exit status
ERROR: dependencies ‘sf’, ‘lwgeom’, ‘classInt’ are not available for package ‘tmaptools’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/tmaptools’
Warning in install.packages :
  installation of package ‘tmaptools’ had non-zero exit status
ERROR: dependencies ‘sf’, ‘classInt’, ‘lwgeom’ are not available for package ‘stars’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/stars’
Warning in install.packages :
  installation of package ‘stars’ had non-zero exit status
ERROR: dependencies ‘leafem’, ‘leafpop’, ‘sf’, ‘svglite’ are not available for package ‘mapview’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/mapview’
Warning in install.packages :
  installation of package ‘mapview’ had non-zero exit status
ERROR: dependencies ‘tmaptools’, ‘sf’, ‘lwgeom’, ‘classInt’ are not available for package ‘tmap’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/tmap’
Warning in install.packages :
  installation of package ‘tmap’ had non-zero exit status

I've read the instructions and performed the next

**Comment by PauGallesClara** [comment]
commands on my terminal from the installing page of sf:
sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update
sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 

After that I have tried to install again having the same error list

**Comment by edzer** [comment]
It seems you're lacking proper compilers on your platform; look for the error mentioning `gfortran`.

**Comment by PauGallesClara** [comment]
ok I'll take a look
Thank you

**Comment by PauGallesClara** [comment]
Hi  @edzer 
It seems that the error on gfortran is here right?

gfortran -fno-optimize-sibling-calls -fpic -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -c acchk.f -o acchk.o
/bin/bash: gfortran: no s'ha trobat l'ordre
/usr/lib/R/etc/Makeconf:191: recipe for target 'acchk.o' failed
make: *** [acchk.o] Error 127

But, I'm new on Linux, and I'm currently using Linux Mint 19.3, and don't know what is expected to be done to solve this "lack of compiler".... so, I would appreciate help or suggestions.

Thank you in advance

**Comment by edzer** [comment]
I don't know. It's not an issue with this R package.

**Comment by rsbivand** [comment]
Try to install **classInt** first. If you have a working `gfortran` (I don't think you have), it will install smoothly. If not, figure out how to install your compilers more completely. Note that the error message following the `gfortran` command is `no s'ha trobat l'ordre - command not found` in Catalan (google translate). R itself and many packages use the Fortran compiler.

**Comment by PauGallesClara** [comment]
Hi 
I have followed your advice
I've looked how to install gfotran and I've done it with this
`apt install gfortran gfortran-doc`
After that I've installed the classInt packatge and it worked
Then I've installed sf like this:
`install.packages("sf" , dependencies = TRUE)` and the result was succesful but with the some errors:
installing to /home/pau/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-spatstat/00new/spatstat/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (spatstat)
ERROR: dependency ‘gdtools’ is not available for package ‘svglite’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/svglite’
Warning in install.packages :
  installation of package ‘svglite’ had non-zero exit status
* installing *source* package ‘tmaptools’ ...
** package ‘tmaptools’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (tmaptools)
* installing *source* package ‘stars’ ...
** package ‘stars’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
in method for ‘coerce’ with signature ‘"stars","Raster"’: no definition for class “Raster”
in method for ‘coerce’ with signature ‘"stars_proxy","Raster"’: no definition for class “Raster”
in method for ‘coerce’ with signature ‘"stars","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"stars","STFDF"’: no definition for class “STFDF”
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (stars)
ERROR: dependency ‘svglite’ is not available for package ‘leafpop’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/leafpop’
Warning in install.packages :
  installation of package ‘leafpop’ had non-zero exit status
* installing *source* package ‘tmap’ ...
** package ‘tmap’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (tmap)
ERROR: dependencies ‘leafpop’, ‘svglite’ are not available for package ‘mapview’
* removing ‘/home/pau/R/x86_64-pc-linux-gnu-library/3.6/mapview’
Warning in install.packages :
  installation of package ‘mapview’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmppbx25K/downloaded_packages’
Now I have to test if it really works
Thank you @edzer and @rsbivand for your time and explanations

**Comment by rsbivand** [comment]
So now you need to figure out what **gdtools** needs, and so on, until everything completes without error.

**Comment by sainadfensi** [comment]
Thank you! I'm having trouble with installing other R packages and find this post is useful for me.
