### ISSUE TITLE
json to sf object

### ISSUE THREAD

**Issue by PauGallesClara** [r-spatial/sf#1259]
Hi I'm trying to parse a json file with the geometry, but I'm not able to transform it to an sf object.
What I want is to get all de direction points of Reus city. You can find it in  ` url: `https://geoportal.reus.cat/apps/giscube-admin/plugins/mapiareus_search/search/?q=prim&e=adreca`  . And this is the json:
` {
        "resultat": {
            "adreca":[
            {
                "id": ...,
                "geom":{}
                "etiqueta": "...",
                "nom_carrer": ...,
            }]
        },
        "estat": "OK"
    }`

And what I've done is what it follows:
`library(jsonlite)`
`library(sf)` 

`adreces` <- fromJSON("https://geoportal.reus.cat/apps/giscube-admin/plugins/mapiareus_search/search/?q=&e=adreca", simplifyVector = TRUE, simplifyDataFrame = TRUE, simplifyMatrix = `TRUE)`
`adreces`

`df_adreca` <- `adreces$resultat$adreca`
`summary(df_adreca)`
`class(df_adreca)`

`df_adreca_sf` <- st_sf(df_adreca)`

And I have this error message:
Error in st_sf(df_adreca) : no simple features geometry column present

But as you can see in the json file. There is an specific field for geometry, that it can also be seen when executing `df_adreca`

How i must solve the error message?

**Comment by edzer** [comment]
Could you please clean up the formatting of your question? I can't understand it like this.
