### ISSUE TITLE
st_within performance comparison between R/sf and QGIS

### ISSUE THREAD

**Issue by ericemc3** [r-spatial/sf#1261]
As a QGIS user scripting some topological processes with Python, i wanted to compare it with a R/sf script on a usual case for me, selecting 20,000 census output areas inside a region (classic "within" test between polygons that, in that case, align perfectly).

I am surprised by the performance lag i am noticing between R and Py/Qgis (nearly 1mn versus 5s). 

Here is a REPREX attempt:
```
sfc = st_sfc(st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,0)))))
plot( hxgrid <- st_as_sf( st_make_grid(sfc, cellsize = .005, square = FALSE) ) )
plot(sfc)
plot( cont <- hxgrid %>% summarise() )
```
i get a grid with 23,435 hexagons (sfc) and the boundary polygon (cont).
Then i select all hexagons within the polygon:
`system.time( t <- hxgrid %>% filter( st_within(x, cont, sparse = FALSE )  ))`
=> 18 seconds for selecting all 23,435 hexagons

for testing within Qgis 3.8:
```
hxgrid %>% write_sf( str_c(tempdir(), "/",'hex.shp') )
cont %>% write_sf( str_c(tempdir(), "/",'conthex.shp') )
```
Then i run in Qgis "Extract by location":
=> 1 second

https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorselection.html#qgisselectbylocation
Are within: Tests whether a geometry is within another. Returns 1 (true) if geometry a is completely inside

<img width="201" alt="qgis_select_within" src="https://user-images.githubusercontent.com/17407796/74109381-2d3d1c00-4b83-11ea-8717-93cf6003be0f.png">

**Comment by edzer** [comment]
Thanks! I'm seeing this:
```r
> system.time( t1 <- hxgrid %>% filter( st_contains(cont, x, sparse = FALSE , prepared = TRUE) ))
   user  system elapsed 
  0.658   0.000   0.658 
> system.time( t0 <- hxgrid %>% filter( st_within(x, cont, sparse = FALSE , prepared = TRUE) ))
   user  system elapsed 
 11.978   0.000  11.982 
> all.equal(t0, t1)
[1] TRUE
```
so maybe that is what QGis does for you, under the hood. Smart.

**Comment by ericemc3** [comment]
Thank you, i will use it! I thought that st_within and st_contain where just logical opposites.

Why st_within can be so slow, is it about prefiltering or not with a spatial index?

**Comment by edzer** [comment]
Yes: prefiltering using a spatial index; both queries build a tree index on the first object and then loop over the prefiltered second. We haven't come up with heuristics for when this should be reversed; if you could point us to the source code lines where QGis does such a thing, that would be most welcome.

**Comment by rsbivand** [comment]
Just for fun, and avoiding the unneeded **dplyr** distractions - which may lead to not seeing that reversed order leads to an  empty set:

```
library(sf)
sfc <- st_sfc(st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,0)))))
hxgrid <- st_as_sf(st_make_grid(sfc, cellsize = .005, square = FALSE))
cont <- st_as_sf(st_union(hxgrid))
library(rgeos)
sfc_sp <- as(sfc, "Spatial")
hxgrid_sp <- as(hxgrid, "Spatial")
cont_sp <- as(cont, "Spatial")
# reverse orderings of  geoms give empty set
system.time(t1 <- hxgrid %>% dplyr::filter(st_contains(cont, x, sparse = FALSE)))
system.time(t1b <- hxgrid[st_contains(cont, hxgrid, sparse = FALSE)[1,],])
# I would prefer:
o <- st_contains(cont, hxgrid, sparse = FALSE)
str(o) # showing  what is actually going on
t1b1 <- hxgrid[o[1,],]
system.time(t1_sp <- hxgrid[gContains(cont_sp, hxgrid_sp, byid=TRUE, returnDense=TRUE)[1,],])
all.equal(st_as_sf(t1_sp), t1, check.attributes=FALSE)
all.equal(t1b, t1, check.attributes=FALSE)
system.time(t0a <- hxgrid %>% dplyr::filter(st_within(x, cont, sparse = FALSE)))
system.time(t0c <- hxgrid[st_within(hxgrid, cont, sparse = FALSE)[1,],])
system.time(t0_sp <- hxgrid[gWithin(hxgrid_sp, cont_sp, byid=TRUE, returnDense=TRUE)[1,],])
all.equal(st_as_sf(t0_sp), t0a, check.attributes=FALSE)
all.equal(t0c, t0a, check.attributes=FALSE)
```
Note also that the timings are very consistent, with `sf::st_within()` and `rgeos::gWithin()` and the contain alternatives running in equivalent times (I had expected **sf** to be faster than **rgeos**).

**Comment by edzer** [comment]
So it's argument order, and not use of the spatial index (tree).

**Comment by ericemc3** [comment]
Actually i'd be curious to understand why the st_contains algorithm is so much more efficient than the st_within one. I don't think this is just about testing bounding boxes. The tough part i guess is about testing polygons that touch (but from the inside, and without overlapping) the boundary. I can understand why this is expensive to test, But what is the magig between st_contains that works so well here

**Comment by rsbivand** [comment]
The case is an edge case anyway, there the tree index will not help because all are contained by definition. Maybe buffer in `cont`:

```
library(sf)
sfc <- st_sfc(st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,0)))))
hxgrid <- st_as_sf(st_make_grid(sfc, cellsize = .005, square = FALSE))
cont <- st_as_sf(st_union(hxgrid))
cont1 <- st_buffer(cont, dist=-0.2)
library(rgeos)
hxgrid_sp <- as(hxgrid, "Spatial")
cont_sp <- as(cont1, "Spatial")
system.time(t1b <- hxgrid[st_contains(cont1, hxgrid, sparse = FALSE)[1,],])
system.time(t1_sp <- hxgrid[gContains(cont_sp, hxgrid_sp, byid=TRUE, returnDense=TRUE)[,1],])
all.equal(st_as_sf(t1_sp), t1b, check.attributes=FALSE)
system.time(t0c <- hxgrid[st_within(hxgrid, cont1, sparse = FALSE)[,1],])
system.time(t0_sp <- hxgrid[gWithin(hxgrid_sp, cont_sp, byid=TRUE, returnDense=TRUE)[1,],])
all.equal(st_as_sf(t0_sp), t0c, check.attributes=FALSE)
```

The index doesn't help when all are included, and the index swapping i the output matrices is oddish. Interesting.

**Comment by dbaston** [comment]
There's no intrinsic complexity difference between contains and within. The performance difference here comes from the conversion of the first argument to a prepared geometry. So although we don't see a benefit from the external index created in `CPL_geos_binop`, we do see a benefit from the prepared geometry internal index created on `cont`.

IMO, the best way to poke at these kinds of things is to serialize the inputs and run, e.g.,

    R --vanilla -d 'valgrind --tool=callgrind' -e "x <- sf::st_within(readRDS('hxgrid.rds'), readRDS('cont.rds'))"

then inspect the results with kcachegrind. Counting coordinate access is a good proxy for operation complexity, and `st_contains(cont, hxgrid)` requires 645 million coordinate accesses, while `st_within(hxgrid, cont)` requires only 16 million.

**Comment by edzer** [comment]
Thanks @dbaston ! We also see it here:
```r
> system.time( t1 <- hxgrid %>% filter( st_contains(cont, x, sparse = FALSE, prepared = FALSE) ))
   user  system elapsed 
 11.633   0.017  11.690 
> system.time( t0 <- hxgrid %>% filter( st_within(x, cont, sparse = FALSE, prepared = FALSE) ))
   user  system elapsed 
 11.528   0.000  11.566 
> system.time( t1 <- hxgrid %>% filter( st_contains(cont, x, sparse = FALSE, prepared = TRUE) ))
   user  system elapsed 
  0.634   0.000   0.634 
> system.time( t0 <- hxgrid %>% filter( st_within(x, cont, sparse = FALSE, prepared = TRUE) ))
   user  system elapsed 
  11.13    0.00   11.13 
```

**Comment by ericemc3** [comment]
That makes sense, thanks! So st_within could be easily optimized if for instance, we could choose which argument to "prepare", not only the first by default. Or maybe a smart optimization depending on the difference of nature (cardinality, feature count or rings count) between both entities to compare
