### ISSUE TITLE
No method to retrieve geometry type of `sfc` object ?

### ISSUE THREAD

**Issue by rgzn** [r-spatial/sf#1264]
Afaik there is no method to retrieve the Geometry Type of a Simple Features Collection. 
the method `st_geometry_type(sfc_object)` is a vectorized function that returns the geometry type of each `sf` object in the geometry column of the `sfc_object`.   

Is there a simple way to retrieve the value of the geometry type for the `sfc` object? 

Here is my current method:
```
> sfc %>% st_geometry %>% class %>% .[1] %>% substring(5)
[1] "POLYGON"
```

**Comment by edzer** [comment]
Maybe we can add an argument to `st_geometry_type`, e.g. `by_geometry=TRUE`, which, when `FALSE`, returns the type of the set?

**Comment by rgzn** [comment]
thanks edzer, I really should start contributing but you are so responsive that i don't have to!
