### ISSUE TITLE
Writing to PostGIS drops geometry column when append=T

### ISSUE THREAD

**Issue by eroubenoff** [r-spatial/sf#1265]
I'm trying to insert shapefiles to a PostGIS database using RPostgreSQL and SF. I have my processed and valid sf dfs (validity confirmed using st_valid). I then run:

```{R}
sf::st_write(points, dsn = con, append = T)
```
No errors appear. Then when I try to retrieve the same file using st_read(con, layer = "points"), I get the following error:

```{R}
Warning message:
In st_read.DBIObject(con, layer = "points") :
  Could not find a simple features geometry column. Will return a data.frame. 
```

This error persists if I use `sf::dbWriteTable(con, "points", points, overwrite = FALSE, append = T, binary = F)` with the binary flag set to either T or F.

I need to have `append = T`.  This operation does not fail when `append = F`.

**Comment by edzer** [comment]
This works for me:
```r
library(sf)
# Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
sf = st_sf(a=1:2, geom = st_sfc(st_point(0:1), st_point(2:3)))
st_write(sf, "PG:dbname=postgis", "sf", update = TRUE)
# Updating layer `sf' to data source `PG:dbname=postgis' using driver `PostgreSQL'
# Writing 2 features with 1 fields and geometry type Point.
st_write(sf, "PG:dbname=postgis", "sf", update = TRUE)
# Updating layer `sf' to data source `PG:dbname=postgis' using driver `PostgreSQL'
# Updating existing layer sf
# Writing 2 features with 1 fields and geometry type Point.
st_read("PG:dbname=postgis", "sf")
# Reading layer `sf' from data source `PG:dbname=postgis' using driver `PostgreSQL'
# Simple feature collection with 4 features and 1 field
# geometry type:  POINT
# dimension:      XY
# bbox:           xmin: 0 ymin: 1 xmax: 2 ymax: 3
# CRS:            NA
```
note that `st_read`, being GDAL based, listens to `update=TRUE`, not `append=TRUE`.

**Comment by eroubenoff** [comment]
Thank you.  This appears to work for me.

**Comment by eroubenoff** [comment]
This worked at first but has since stopped— I can't figure out what changed between the test case and the actual insertion. Running:
```
sf::st_write(places, dsn = con, update = T)
``` 

I'm now getting the error :

```
Error in read_lines_chunked_(ds, locale, na, chunk_size, callback, progress) : 
  Evaluation error: Table points exists in database, and both overwrite and append are FALSE.
```

**Comment by edzer** [comment]
Please point out how your problem differs from the one that worked, by providing a reproducible script.

**Comment by eroubenoff** [comment]
Resolved.  This was a driver issue.
