### ISSUE TITLE
st_intersects vs. st_intersection on st_linestring

### ISSUE THREAD

**Issue by PhilippBuehler** [r-spatial/sf#1267]
The behaviour of `st_intersects` and `st_intersection` does result in different outputs.
The output of `st_intersection` results in a point, but not the whole line. This can only be archieved by using `st_intersects`, as can be seen in the following example.

```
l1 <- st_sfc(lapply(list(matrix(-9:10,, 2),matrix(c(-1:3,-2:2), , 2),
	matrix(c(-5:-2,-2:3), , 2), matrix(3:6, , 2)),st_linestring))

square = st_polygon(list(matrix(c(0,0,10,0,10,10,0,10,0,0),ncol=2, byrow=TRUE)))

plot(square)
plot(l1,add=TRUE)

plot(square)
plot(l1[st_intersects(l1,square,sparse = FALSE)],add=TRUE)

plot(square)
plot(st_intersection(l1,square),add=TRUE)
```

Shouldn't the outputs be the same or at least show a warning that the output of `st_intersection` results in a point ?

**Comment by edzer** [comment]
No: your first expression selects those parts of l1 that have points in common with square, the second yields the geometry that l1 and square have in common.
