### ISSUE TITLE
Unexpected behavior when plotting points

### ISSUE THREAD

**Issue by choisy** [r-spatial/sf#1273]
When I plot the following two points:
```
library(sf)
x <- c(101.6455, 112.0166)
y <- c(8.62447, 23.36242)
xy_sf <- st_as_sf(data.frame(x = x, y = y), coords = c("x", "y"), crs = 4326)
plot(xy_sf, col = "blue")
```
I am surprised to see these axes:
```
axis(1)
axis(2)
```
And I think I would expected to be able to add points like this:
```
points(mean(x), mean(y))
```
which obviously doesn't work because, for some reason, the coordinates seem to have been rescaled between 0 and 1. Which seems to be confirmed by this:
```
points(.5, .5)
```

**Comment by rsbivand** [comment]
@choisy : Please provide output of `sessionInfo()` and `sf_extSoftVersion()`.

@edzer : With PROJ 6.3.0/GDAL 3.0.4, **sf** 0.8-2, I get axis swapping in the output graphic with `plot(xy_sf, col = "blue", axes=TRUE)` but not with `plot(st_geometry(xy_sf), col = "blue", axes=TRUE)`.

**Comment by choisy** [comment]
```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.8-1      raster_3.0-12 sp_1.3-2     

loaded via a namespace (and not attached):
 [1] compiler_3.6.2     magrittr_1.5       class_7.3-15       DBI_1.1.0          tools_3.6.2        units_0.6-5        Rcpp_1.0.3        
 [8] KernSmooth_2.23-16 codetools_0.2-16   grid_3.6.2         e1071_1.7-3        classInt_0.4-2     lattice_0.20-38   
```

**Comment by choisy** [comment]
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.7.2"        "2.4.2"        "5.2.0"        "false"        "false"

**Comment by edzer** [comment]
@choisy you need to set `reset = FALSE` if you want to add anything to a plot of an `sf` object. @roger: looking into it; this is only on branch `SetFromUserInput` it seems.

**Comment by rsbivand** [comment]
@edzer : yes, on `SetFromUserInput`.

**Comment by edzer** [comment]
@roger this should work now. 
@choisy your example is rather counter intuitive and will work as you expected in future sf versions; only when `sf` objects have attributes, the device has to reset because of the legend.

**Comment by choisy** [comment]
Thanks a lot!
Your reaction time is impressive!
I let you close the issue if you want to.
