### ISSUE TITLE
How does sf discover the current PROJ data_dir on load?

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#1277]
With **rgdal** 1.5-5 on 7.0.0RC1, I see:

```
> library(rgdal)
Loading required package: sp
rgdal: version: 1.5-5, (SVN revision 938)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 3.1.0dev-e52a02d452, released 2020/02/21
 Path to GDAL shared files: /usr/local/share/gdal
 GDAL binary built with GEOS: TRUE 
 Loaded PROJ.4 runtime: Rel. 7.0.0, March 1st, 2020, [PJ_VERSION: 700]
 Path to PROJ.4 shared files: /home/rsb/.local/share/proj:/usr/local/share/proj:/usr/local/share/proj
 Linking to sp version: 1.4-0 
> Sys.getenv("PROJ_LIB")
[1] ""
```

```
> getPROJ4libPath()
[1] ""
attr(,"search_path")
[1] "/home/rsb/.local/share/proj:/usr/local/share/proj:/usr/local/share/proj"
```
returns `PROJ_LIB` with the output of `proj_info().searchpath`. **sf** uses `proj_context_set_search_paths()`, but I can't see if it gets too. I think we both need to check what gets set on load for PROJ >= 7 and stop any extension before the user can decide. My first cut on policy: factory-fresh **sf**/**rgdal**: no local cache in search path; policy 1 is to add a per-session cache under tempdir() and advertise it for other packages using PROJ; policy 2 permit local per user cache. Maybe either null or 2 is enough, but the CRAN cannot run checks for any tests or examples needing cached grids (in revdep packages too).

**Comment by edzer** [comment]
I'm trying to understand what you write, and thought about installing rgdal first, but with
```
install.packages("rgdal", repos="http://R-Forge.R-project.org")
```
which tries to install 1.5-5, I get
```
proj_info6.cpp: In function ‘SEXPREC* CRS_compare(SEXP, SEXP, SEXP, SEXP)’:
proj_info6.cpp:306:28: error: ‘PJ_VERSION’ was not declared in this scope
 Rprintf("PJ_VERSION %d\n", PJ_VERSION);
                            ^~~~~~~~~~
```
This is on
```
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.2"        "6.2.1"         "true"         "true" 
```

**Comment by rsbivand** [comment]
I'll look at this later. The problem is that PROJ 7.0.0 creates a directory in user space as soon as **rgdal** or **sf** load (Linux: $HOME/.local/share/proj) and puts cache.db in it. This breaks CRAN rules.

**Comment by rsbivand** [comment]
But it doesn't  always do it ... puzzling.

**Comment by rsbivand** [comment]
See https://lists.osgeo.org/pipermail/proj/2020-February/009405.html.

Your problem is my code see https://r-forge.r-project.org/scm/viewvc.php/pkg/src/proj_info6.cpp?root=rgdal&r1=932&r2=933 and your PROJ version: I use `proj_is_equivalent_to_with_ctx()` which is >= 6.3. I'll add a speculative `proj_is_equivalent_to()` and branch on 6.3 for `proj_is_equivalent_to_with_ctx()`. Will inform when committed and built.

I can install from R-Forge without problems on:

```
> sf::sf_extSoftVersion()
                 GEOS                  GDAL                proj.4 
              "3.8.0" "3.1.0dev-e52a02d452"               "7.0.0" 
       GDAL_with_GEOS            USE_PROJ_H 
               "true"                "true" 
```
Same on desktop with:
```
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.4"        "6.3.1"         "true"         "true" 
```

**Comment by edzer** [comment]
Fixed the compilation problem on r-forge/rgdal

**Comment by rsbivand** [comment]
Moved the pre-6 version to projectit.cpp, and forked on >=6.3 or 6 < 6.3 in rev 940.

**Comment by rsbivand** [comment]
rev 941 removed issue with Windows build (earlier PROJ/GDAL exposed wrong logic).

**Comment by Robinlovelace** [comment]
Heads-up, I'm getting install errors on Ubuntu 18.04 with ubuntugis-unstable repos. As mentioned here https://github.com/r-spatial/sf/pull/1254#issuecomment-598790230 this version contains PROJ 7. I have looked at https://github.com/r-spatial/sf/issues/1298 and https://github.com/r-spatial/sf/issues/1288 . Based on the latter I will try to re-install PROJ again, as per https://github.com/r-spatial/sf/issues/1288#issuecomment-599652305

**Comment by Robinlovelace** [comment]
Specifically, I'm running these lines verbatim as root:

https://github.com/r-spatial/sf/blob/d1ffa442542d4ea2ae1d877ab3312eed6e8a72b1/inst/docker/custom/Dockerfile#L32-L39

**Comment by edzer** [comment]
Where is your dockerfile?

**Comment by Robinlovelace** [comment]
The dockerfiles for geocomputation with R, that I hope can be of use for https://github.com/r-spatial/discuss/issues/35#issuecomment-599107294 , can be found here: https://github.com/Robinlovelace/geocompr/tree/master/docker . But in this case re-installed PROJ onto the main OS (Ubuntu 18.04). After running the lines of code highlighted above (minus the `RUN`) `sf` is still not installing. Happy to provide further details if that would be of use.

**Comment by edzer** [comment]
did you remove proj and libproj-dev before you tried to install from source?

**Comment by Robinlovelace** [comment]
> did you remove proj and libproj-dev before you tried to install from source?

No, will do.

**Comment by Robinlovelace** [comment]
Happy to say that somehow, after uninstalling `libproj-dev`, `proj` and a whole chain of other packages that were somehow auto-uninstalled alongside these, I guess due to ubuntugis-unstable, and then re-installing `libproj-dev` and other dependencies (from the ubuntugis-unstable repo rather than from source this time) the following command worked (but not `install.packages("sf")`):

```r
remotes::install_github("r-spatial/sf")
```

Now I'm running PROJ 7 it seems:

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
```

<sup>Created on 2020-03-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       Ubuntu 18.04.4 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_GB:en                    
#>  collate  en_GB.UTF-8                 
#>  ctype    en_GB.UTF-8                 
#>  tz       Europe/London               
#>  date     2020-03-16                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                             
#>  assertthat    0.2.1      2019-03-21 [2] CRAN (R 3.6.0)                     
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                     
#>  callr         3.4.2      2020-02-12 [1] CRAN (R 3.6.2)                     
#>  class         7.3-15     2019-01-01 [2] standard (@7.3-15)                 
#>  classInt      0.4-3      2019-12-04 [1] Github (r-spatial/classInt@7bc8a82)
#>  cli           2.0.2      2020-02-28 [1] CRAN (R 3.6.2)                     
#>  crayon        1.3.4      2017-09-16 [2] standard (@1.3.4)                  
#>  DBI           1.1.0      2019-12-15 [2] CRAN (R 3.6.2)                     
#>  desc          1.2.0      2018-05-01 [2] standard (@1.2.0)                  
#>  devtools      2.2.2      2020-02-17 [1] CRAN (R 3.6.2)                     
#>  digest        0.6.25     2020-02-23 [1] CRAN (R 3.6.2)                     
#>  e1071         1.7-3      2019-11-26 [2] CRAN (R 3.6.1)                     
#>  ellipsis      0.3.0      2019-09-20 [3] CRAN (R 3.6.1)                     
#>  evaluate      0.14       2019-05-28 [2] CRAN (R 3.6.0)                     
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.2)                     
#>  fs            1.3.2      2020-03-05 [2] CRAN (R 3.6.3)                     
#>  glue          1.3.2      2020-03-12 [2] CRAN (R 3.6.3)                     
#>  highr         0.8        2019-03-20 [3] CRAN (R 3.5.3)                     
#>  htmltools     0.4.0.9003 2020-02-28 [1] Github (rstudio/htmltools@ce76055) 
#>  KernSmooth    2.23-16    2019-10-15 [4] CRAN (R 3.6.1)                     
#>  knitr         1.28       2020-02-06 [1] CRAN (R 3.6.2)                     
#>  magrittr      1.5        2014-11-22 [2] CRAN (R 3.5.2)                     
#>  memoise       1.1.0      2017-04-21 [3] CRAN (R 3.5.0)                     
#>  pkgbuild      1.0.6      2019-10-09 [2] CRAN (R 3.6.1)                     
#>  pkgload       1.0.2      2018-10-29 [3] CRAN (R 3.5.1)                     
#>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 3.6.2)                     
#>  processx      3.4.2      2020-02-09 [2] CRAN (R 3.6.2)                     
#>  ps            1.3.2      2020-02-13 [1] CRAN (R 3.6.3)                     
#>  R6            2.4.1      2019-11-12 [2] CRAN (R 3.6.1)                     
#>  Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                     
#>  remotes       2.1.1      2020-02-15 [1] CRAN (R 3.6.2)                     
#>  rlang         0.4.5.9000 2020-03-16 [1] Github (r-lib/rlang@af34567)       
#>  rmarkdown     2.1.1      2020-02-04 [1] Github (rstudio/rmarkdown@18ba267) 
#>  rprojroot     1.3-2      2018-01-03 [2] CRAN (R 3.5.3)                     
#>  sessioninfo   1.1.1      2018-11-05 [3] CRAN (R 3.5.1)                     
#>  sf          * 0.9-0      2020-03-16 [1] Github (r-spatial/sf@a4de5e5)      
#>  stringi       1.4.6      2020-02-17 [1] CRAN (R 3.6.2)                     
#>  stringr       1.4.0      2019-02-10 [2] standard (@1.4.0)                  
#>  testthat      2.3.2      2020-03-02 [1] CRAN (R 3.6.3)                     
#>  units         0.6-6      2020-03-16 [1] CRAN (R 3.6.3)                     
#>  usethis       1.5.1.9000 2020-03-08 [1] Github (r-lib/usethis@112e071)     
#>  withr         2.1.2      2018-03-15 [2] CRAN (R 3.5.3)                     
#>  xfun          0.12       2020-01-13 [1] CRAN (R 3.6.2)                     
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.2)                     
#> 
#> [1] /home/robin/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Comment by Robinlovelace** [comment]
Should add that I've been playing with the dev version of QGIS and I suspect that messes with some of the dependencies used by `sf`. That has burned me in the past...

**Comment by edzer** [comment]
Returning to the topic of this issue, I now renamed `st_proj_info` into `sf_proj_info`, and added getting and setting the data path as follows:
```r
library(sf)
# Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
sf_proj_info("path")
# [1] "/usr/share/proj"
x = sf_proj_info(path = "/")
x
# [1] TRUE
sf_proj_info("path")
# [1] "/"
```

**Comment by edzer** [comment]
... and on the custom-installed PROJ 7 docker image, running as root:
```r
> library(sf)
Linking to GEOS 3.8.1, GDAL 3.0.4, PROJ 7.0.0
> sf_proj_info("path")
[1] "/root/.local/share/proj:/opt/share/proj"
```
maybe it creates this `$HOME/.local/share/proj` directory only after the first datum grid download? @rsbivand do you have an example for this?

**Comment by rsbivand** [comment]
Out walking now, I see it too in rgdal. More when I get home.

Roger Bivand
Falsensvei 32
5063 Bergen

tir. 17. mar. 2020, 12.57 skrev Edzer Pebesma <notifications@github.com>:

**Comment by Robinlovelace** [comment]
I also saw this:

```
 sf_proj_info("path")
[1] "/root/.local/share/proj:/opt/share/proj"
```

**Comment by rsbivand** [comment]
Right, `proj_context_is_network_enabled()` gives the CDN status. Otherwise, `proj_info().searchpath` gives the search path. The $HOME/.local/share/proj is empty and not created unless the CDN is turned on, but may also  be used to add grids manually (because it is user-writeable). My mistake was to think it was being used by default - it appeared on my platforms because I run `make check` for PROJ.

**Comment by edzer** [comment]
Right, with env variable `PROJ_NETWORK=ON` on PROJ 7 we get
```r
> sf_proj_info("network")
[1] TRUE
```
