### ISSUE TITLE
st_nearest_feature has odd behavior for polygon polygon comparisons which touch/overlap

### ISSUE THREAD

**Issue by kendonB** [r-spatial/sf#1278]
I found a case where st_nearest_feature doesn't pick out itself when comparing two polygons that are the same. See below:

``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
pl = list(rbind(c(0,0), c(1,0), c(1,1), c(0,1), c(0,0)))
pl2 = pl
# Make a polygon adjacent to the other one
pl2[[1]][,1] <- pl2[[1]][,1] + 1
sfc = st_sfc(st_polygon(pl), st_polygon(pl2))
plot(sfc)
```

![](https://i.imgur.com/cDKb6jM.png)

``` r
# 1, 1 rather than 1, 2
st_nearest_feature(sfc, sfc)
#> [1] 1 1
```

<sup>Created on 2020-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I presume this happens here because it picks out the first index when there are ties for the minimum distance - both are zero distance from each other as they share an edge.

I don't think the solution to this is necessarily any code changes, just some documentation describing how the distance metric is calculated in the background. People can convert to centroids before the comparison if they wish.

**Comment by edzer** [comment]
I didn't find this confusing, but if you do, feel free to PR the docs.
