### ISSUE TITLE
Convert sf data to sp for spatial analysis

### ISSUE THREAD

**Issue by pkageliza** [r-spatial/sf#1281]
Dear all

I have my data which I need to convert to sp for spatial analysis from sf. Kindly advice on how to go about it

This is what I have

mrima_sf <- st_as_sf(mrima, coords = c("lon","lat"), crs=4326)
> mrima_sf
Simple feature collection with 13984 features and 2 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: 39.24534 ymin: -4.499777 xmax: 39.27487 ymax: -4.465078
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
# A tibble: 13,984 x 3
    dose source             geometry
   <dbl> <chr>           <POINT [°]>
 1  171. DayB   (39.25961 -4.499777)
 2  180. DayB   (39.25897 -4.499175)
 3  204. DayB   (39.25832 -4.498565)
 4  207. DayB   (39.25767 -4.497953)
 5  219. DayB   (39.25703 -4.497378)
 6  216. DayB   (39.25639 -4.496855)
 7  210. DayB    (39.25573 -4.49641)
 8  222. DayB   (39.25506 -4.496005)
 9  213. DayB   (39.25436 -4.495658)
10  210. DayB    (39.2536 -4.495347)
# ... with 13,974 more rows

**Comment by edzer** [comment]
`as(mrima_sf, "Spatial")`

**Comment by pkageliza** [comment]
Thank you
