### ISSUE TITLE
Suppresing warnings

### ISSUE THREAD

**Issue by fgoerlich** [r-spatial/sf#1282]
Using `st_within()` or `st_touches` with sf layers with geographic coordinates (longitude/latitude) produce a warning of the type:
>although coordinates are longitude/latitude, st_within assumes that they are planar

Is there anyway of suppresing these warnnings? 
Neither `suppressWarnings()` nor `options(warn=-1)` works with this type of messages.

Thanks a lot.

**Comment by edzer** [comment]
It's a message, not a warning: you can use `suppressMessages()`, but I don't recommend doing so.
