### ISSUE TITLE
Overlaying a shapefile on a terrain or hybrid base map

### ISSUE THREAD

**Issue by pkageliza** [r-spatial/sf#1285]
Hi

I have now struggled for a number of hours to overlay a ggplot map on a  base map. I have been able to get the two files separately, but I am unable to overlay the map. Kindly assist

This has worked out
Base_map <- get_map(location=c(39.38, -4.44), maptype = "hybrid", zoom=11)
ggmap(Base_map, extent="panel")

and also this one
Base<- ggplot(Area_3)+ geom_sf(data=Study_area)

**Comment by edzer** [comment]
I think you need to post this issue at the `ggmap` or `ggplot2` repositories: `geom_sf` is part of `ggplot2`.

**Comment by pkageliza** [comment]
Still Stuck. Let me go through it again

**Comment by pkageliza** [comment]
Worked 

ggmap( +
  geom_sf(data = ?_sf, inherit.aes = FALSE)

**Comment by pkageliza** [comment]
ggmap( )+
geom_sf(data = ?_sf, inherit.aes = FALSE)
