### ISSUE TITLE
Is there a way to build alpha shapes (complex) with sf?

### ISSUE THREAD

**Issue by maikol-solis** [r-spatial/sf#1287]
For a given set of points, an alpha shape is a subset of a Delanauy triangulation where each triangle is contained in a ball centered in a set of points with radius `alpha`. There is a package alphahull (https://cran.r-project.org/web/packages/alphahull/index.html) that performs this operation. However, their implementation only retrieve the edges of the frontier and not polygons. 

My question is if is it possible to create something like that with sf?

I have the following example, which I could only able to construct the circles that contained the Delanauy triangles, but I can't create the proper triangles.

```
set.seed(123)
n <- 100
theta1 <- runif(n, 0, 2 * pi)
theta2 <- runif(n, 0, 2 * pi)
theta3 <- runif(n, 0, 2 * pi)
r1 <- runif(n, 1, 1.5)
r2 <- runif(n, 1, 1.5)
r3 <- runif(n, 1, 1.5)

X1c1 <- r1 * cos(theta1)
Yc1 <- r1 * sin(theta1)
X1c2 <- r2 * cos(theta2) + 3
Yc2 <- r2 * sin(theta2) + 3
X1c3 <- r3 * cos(theta3) - 3
Yc3 <- r3 * sin(theta3) + 3

X <- cbind(c(X1c1, X1c2, X1c3), c(Yc1, Yc2, Yc3))

p<- lapply(seq_len(nrow(X)), function(i){
  st_point(c(X[i,1],X[i,2]))
})
  
g1 <- st_geometrycollection(p) 

g2<- g1 %>% st_collection_extract("POINT")

b<-st_buffer(g2,0.4)

v <- st_voronoi(g1) %>% st_collection_extract()

vb<- st_intersection(v,st_union(b))

plot(vb)
```
![plot_zoom](https://user-images.githubusercontent.com/4078489/75841113-8703c100-5d92-11ea-8856-6f908344fe5d.png)

Thanks for the help.

Some additional references about alpha shapes (complexes)

https://en.wikipedia.org/wiki/Alpha_shape
https://doc.cgal.org/latest/Alpha_shapes_2/
https://gudhi.inria.fr/doc/latest/group__alpha__complex.html

**Comment by etiennebr** [comment]
I'm not sure I understand what result you would like (or what `alphahull` doesn't do), but maybe 
```r
v2 <- st_triangulate(g1)
plot(v2, col = "grey90")
plot(g2, add = TRUE, col = 2, pch = 16)
```
![image](https://user-images.githubusercontent.com/393576/75928031-8bd07f80-5e3b-11ea-8231-907b634eb50f.png)

**Comment by maikol-solis** [comment]
Thanks @etiennebr  for your reply. You are right. Maybe I had to be clearer with my question. 

I was thinking more on reconstructing the Delanauy triangles that belong only to the purple sections (see figure below). The other triangles we could  ignore them. 

I did this plot using the function `ashape` from the `alphahull` package (and paint for the purple areas). 

![plot_zoom2](https://user-images.githubusercontent.com/4078489/75998070-dac2f700-5ec5-11ea-8253-2a28beb5cdd0.png)
 
This package recovers the sequence of edges to create the inner and outer borders, but it ignores all the triangles inside.

My question is how, with `sf`, we could recover the triangles inside the alpha shape?

Thanks again for your help.

**Comment by mdsumner** [comment]
I don't believe you can truly get the shapes out of alphahull, it consists of the triangulation and the voronoi diagram, and it summarizes that down using the alpha parameter to a set of edges - so they are disconnected linestrings, with no way to know which triangles define the shape itself.  (I'm disappointed, thought there was more to it). 

Somewhat faster than @etiennebr 's approach is to use generic triangulation and the raw length of the triangle boundary as the filter. Another step would get the exploded boundaries and test for the length of individual sides (as  the example above does, definitely could make that faster). 


``` r
  set.seed(123)
n <- 100
theta1 <- runif(n, 0, 2 * pi)
theta2 <- runif(n, 0, 2 * pi)
theta3 <- runif(n, 0, 2 * pi)
r1 <- runif(n, 1, 1.5)
r2 <- runif(n, 1, 1.5)
r3 <- runif(n, 1, 1.5)

X1c1 <- r1 * cos(theta1)
Yc1 <- r1 * sin(theta1)
X1c2 <- r2 * cos(theta2) + 3
Yc2 <- r2 * sin(theta2) + 3
X1c3 <- r3 * cos(theta3) - 3
Yc3 <- r3 * sin(theta3) + 3

X <- cbind(x = c(X1c1, X1c2, X1c3), y = c(Yc1, Yc2, Yc3))

library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
pts <- st_union(st_as_sf(data.frame(x = X[,1], y = X[,2], id = 1), coords = c("x", "y"))) 
sfx <- st_cast(st_triangulate(pts))
## use a heuristic or arbitrary length value to filter the triangles
lens <- st_length(st_cast(sfx, "LINESTRING"))
val <- quantile(lens, 0.89)
plot(sfx[lens < val])
```

![](https://i.imgur.com/sv9nCPY.png)

<sup>Created on 2020-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
As this is not an issue with `sf`, I'm closing here.

**Comment by user3386170** [comment]
Thanks for all the tips on this page. It is not an issue and as such may have been better suited to a gis.stackexchange post although it could be a feature request.

@etiennebr why do you convert to a tibble? I need to have the final output as a polygon in order to calculate the area. Picking up from the `st_segment` function, here's my version of the code. I added the segment length directly to the polygons and filtered in there. I'm sure there is a more elegant way to run it in fewer lines and write it up as a function. I do not understand the subtlety of why `st_segment` require an `sfc` which prevented me from creating the `sf` that could take on an attribute from the start.

```
# triangulate the points
v2 <- st_triangulate(g1) %>% st_collection_extract()
#I had to run st_union prior to st_triangulate() in my dataset

segments<-map(v2, st_segment)
max_lengths<-map_dbl(segments, ~max(st_length(.x$geometry)))

v2.sf<-st_as_sf(v2)
v2.sf$max_length<-max_lengths


# set your maximal edge length
alpha_max <- mean(max_lengths)*2  #example of how to set max length based on values (this is the suggested value for NatureServe rank calculations)

#create alpha hull around points
v2.alpha.hull<-st_union(v2.sf%>%filter(max_length<alpha_max))
plot(v2.alpha.hull)
```

@mdsumner Unless I'm mistaken, your solution take the sum of the individual triangles (or set of lines) while the alpha hull method is supposed to look for the longest individual segment.
