### ISSUE TITLE
default behaviour of st_distance when supplied with points and polygons

### ISSUE THREAD

**Issue by brfitzpatrick** [r-spatial/sf#1289]
Is the default behaviour of st_distance when supplied with points and polygons to calculate the shortest distance between each point and the edge of each polygon as opposed to the shortest distance between each point and the centroid of each polygon?

**Comment by edzer** [comment]
edge.

**Comment by brfitzpatrick** [comment]
Many thanks. This is what I would expect the default behaviour to be, I just wanted to make sure.
