### ISSUE TITLE
building with -rpath fails due to LDFLAGS not passed to CXX

### ISSUE THREAD

**Issue by zerothi** [r-spatial/sf#1291]
When running like this:

```r
install.packages(...,
configure.vars='LDFLAGS="-L/opt/gnu/9.1.0/proj/6.1.0/lib -L/opt/gnu/9.1.0/geos/3.8.0/lib -L/opt/gnu/9.1.0/sfcgal/1.3.7/lib -L/opt/gnu/9.1.0/gdal/3.0.0/lib -Wl,-rpath=/opt/gnu/9.1.0/proj/6.1.0/lib -Wl,-rpath=/opt/gnu/9.1.0/geos/3.8.0/lib -Wl,-rpath=/opt/gnu/9.1.0/sfcgal/1.3.7/lib -Wl,-rpath=/opt/gnu/9.1.0/gdal/3.0.0/lib"')
```
It will fail since the `configure` script misses to add `LDFLAGS` to `CXX` compilation.

The offending line in `configure` is this:
```bash
${CXX} ${CPPFLAGS} -o gdal_test gdal_test.cpp ${LIBS} 2> errors.txt
```
It should also contain the `LDFLAGS`

**Comment by zerothi** [comment]
Oh sorry, this is multiple places in the configure file...

**Comment by zerothi** [comment]
@edzer did you fix it, or did you just close the issue? :)

**Comment by edzer** [comment]
I closed it because lack of activity. Is it a bug? What is wrong with setting `LD_LIBRARY_PATH` as is done here: https://github.com/r-spatial/sf/blob/b6965168a87dc06749adcc3ea6809d8559a9e18e/inst/docker/custom/Dockerfile#L79
or how do you make sure the dynamic libs are found at runtime?

**Comment by zerothi** [comment]
I would argue this is a bug.
I am forcing the run-time path using `LDFLAGS` (`-Wl,-rpath`) and hence don't need `LD_LIBRARY_PATH`. The problem is that `LDFLAGS` isn't used at all whereas it should.
Additionally I could have used `LIBS` in the configure of the script, but R has a line-length limit which produces spurious errors.

Your configure script adds `LDFLAGS` _some_ places, but not others. This is what I want to get fixed. :)

**Comment by edzer** [comment]
Ah, I see. Well, PR welcome!

**Comment by edzer** [comment]
Please try.

**Comment by zerothi** [comment]
Great! Thanks!
