### ISSUE TITLE
Error Trying to convert a data frame to an sf

### ISSUE THREAD

**Issue by PauGallesClara** [r-spatial/sf#1295]
Hi!! 
I have geocede some addresses from one dataset using the OSM nominatim appi.
Once I have de coordenades in the dataset I want to set de dataframe as an sf object but I have the next error message

`> sample_addresses_sf <- st_as_sf(sample_addresses, c("lon", "lat"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
Error in st_sf(x, ..., agr = agr, sf_column_name = sf_column_name) : 
  no simple features geometry column present`

So, how can the geometry must be points but I don't know how to fix this error.
Here I attached the dataframe I'm talking about
[sample_addresses_geo.txt](https://github.com/r-spatial/sf/files/4323052/sample_addresses_geo.txt)

Thank you in advance

**Comment by rCarto** [comment]
Hello, 
You have to use the `coords` argument explicitly. 
 ```r
sample_addresses <- read.csv("sample_addresses_geo.txt")
x <- st_as_sf(sample_addresses, coords=c("lon", "lat"), crs = 4326)
```
On a side note and giving the PROJ evolution, I think it is preferable to use the epsg code (4326) instead of the proj4string string.

**Comment by PauGallesClara** [comment]
Hi @rCarto 

It worked!!!
I've tried with crs = 4326 and crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
And they both worked. But I will consider your side note of the PROJ evolution.
Thank you very much
Pau
