### ISSUE TITLE
Install sf with proj-epsg support

### ISSUE THREAD

**Issue by collinmines** [r-spatial/sf#1296]
Greetings!

I'd like to install "sf" on a CentOS 7 system. I downloaded "sf_0.8-1.tar.gz" and then run

$ R CMD INSTALL --configure-args="CFLAGS=... --with-proj-include=... --with-proj-lib=..." sf_0.8-1.tar.gz

Now, it is a "yes" to find "proj_api.h". But it gave me the error "checking for PROJ: epsg found and readable ... no". It was further suggested to install "proj-nad" and "proj-epgs" RPMS on systems. My version of PROJ is 6.2.1. I only found the "proj-epsg" rpm package for the legacy PROJ.4. My question is, how can I set up "epsg" for PROJ 6? Are any source files of "epsg" available? Should I register at EPSG.org to download dataset? If I downloaded the dataset, place it in a directory, does "--with-proj-share=" need to point to that directory for the dataset?

Thanks for any hints!

**Comment by edzer** [comment]
Please report full inputs and outputs, your summary is not helpful.
