### ISSUE TITLE
tidyr::expand and tidyr::complete support

### ISSUE THREAD

**Issue by kylebutts** [r-spatial/sf#1297]
When trying to use the complete command, the returning tibble has NA for geometries. It would be nice if sf had capabilities to copy the geometries from the group variable to the newly created rows. It would be useful to be able to have zeros filled in instead of ending up with maps with giant "holes" in it. For example, when summarizing using n=n(), if there are no y features in the x row, then it won't show up as a row unless using `tidyr::complete()` afterwards

After thinking, I think the main issue is whether the group has 1 constant geometry (in the reprex below county), or if you are trying to complete say on a group variable that contains multiple geometries, it might be hard to determine what is the appropriate geometry to copy. Likely the answer is to return an error that says the group doesn't have a constant geometry or something like that?

``` r
# tidyverse::expand
library(tidyverse)
library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0

nc <- st_read(system.file("shape/nc.shp", package="sf"))
#> Reading layer `nc' from data source `/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sf/shape/nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> epsg (SRID):    4267
#> proj4string:    +proj=longlat +datum=NAD27 +no_defs
nc1 <- nc %>% mutate(var= 1, value= runif(100))
nc2 <- nc %>% mutate(var= 2, value= runif(100)) %>% head()
nc <- rbind(nc1, nc2)

nc_expanded <- nc %>% expand(CNTY_ID, var)
nc_completed <- nc %>% complete(CNTY_ID, var, fill= list(value= 0))
nc_completed %>% select(CNTY_ID, var, geometry) %>% .[10:15,]
#> # A tibble: 6 x 3
#>   CNTY_ID   var                                                         geometry
#>     <dbl> <dbl>                                               <MULTIPOLYGON [°]>
#> 1    1832     2 (((-77.21767 36.24098, -77.23461 36.2146, -77.29861 36.21153, -…
#> 2    1833     1 (((-76.74506 36.23392, -76.98069 36.23024, -76.99475 36.23558, …
#> 3    1833     2 (((-76.74506 36.23392, -76.98069 36.23024, -76.99475 36.23558, …
#> 4    1834     1 (((-76.00897 36.3196, -75.95718 36.19377, -75.98134 36.16973, -…
#> 5    1834     2                                                            EMPTY
#> 6    1835     1 (((-76.56251 36.34057, -76.60424 36.31498, -76.64822 36.31532, …
```

<sup>Created on 2020-03-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Happy to consider a PR for this!
