### ISSUE TITLE
` group_map(st_union)` not working (CRS issue ?)

### ISSUE THREAD

**Issue by Bakaniko** [r-spatial/sf#1299]
I want to create centroids of clustered points.
In order to do that I was thinking about using the `group_map` function.
It does not work well with several GEOS like `st_centroid` or `st_make_convex_hull`

It appears I have to use `st_union` before hand but I got this error:

```r
Error in geos_op2_geom("union", x, y) : 
  st_crs(x) == st_crs(y) is not TRUE
```

```r
# create fake points
nc <- st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE) %>%
  st_transform(2264) %>% 
  st_centroid() 

# Create 3 clusters
km <- stats::kmeans(st_coordinates(nc), centers = 3)

# Add cluster value to points
nc <- nc %>% mutate(cluster = km$cluster)

# st_union not working : st_crs(x) == st_crs(y) is not TRUE
nc %>% group_by(cluster) %>% 
  group_map(st_union) 

# Returns EPSG: 2264 for all
nc %>% 
  group_by(cluster) %>% 
  group_map(st_crs)
```

Here is informations about my session:

```r
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252 
[2] LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

other attached packages:
 [1] purrr_0.3.3                
 [2] stplanr_0.4.1              
 [3] attempt_0.3.0              
 [4] scales_1.1.0               
 [5] flextable_0.5.7            
 [6] ggplot2_3.2.1              
 [7] tidyr_1.0.0                
 [8] tibble_2.1.3               
 [9] fs_1.3.1                   
[10] cartography_2.3.0          
[11] sf_0.8-0                   
[12] magrittr_1.5               
[13] dplyr_0.8.4                
[14] readr_1.3.1                
[15] package_under_dev_0.0.0.9000
```

**Comment by edzer** [comment]
I think you want to use `summarize` rather than `group_map` for this:
```r
nc %>% group_by(cluster) %>% summarize(BIR74 = sum(BIR74))
Simple feature collection with 3 features and 2 fields
geometry type:  MULTIPOINT
dimension:      XY
bbox:           xmin: 487860.8 ymin: 119830.2 xmax: 2946788 ymax: 1004425
projected CRS:  NAD83 / North Carolina (ftUS)
# A tibble: 3 x 3
  cluster  BIR74                                                        geometry
*   <int>  <dbl>                                   <MULTIPOINT [US_survey_foot]>
1       1  89350 ((2173440 951343.2), (2188532 642434.5), (2188866 450666.5), (…
2       2 178029 ((1445275 752321.2), (1453901 549109.4), (1503998 973341.3), (…
3       3  62583 ((487860.8 541220.4), (560401.7 615571.8), (579871.7 508519.9)…
```
you can pipe that into `st_centroid()`.

**Comment by Bakaniko** [comment]
Yes, @statnmap helped me in a similar way :

```r
nc %>% 
  group_by(cluster) %>% 
  summarise(geometry = st_union(geometry)) %>% 
  st_centroid()
```
But I still don't understand why I got this error and/or why `group_map` doesn't work in that case.

Anyway thanks for your response.

**Comment by statnmap** [comment]
Indeed, this works:  
```r
nc %>%
  group_by(cluster) %>% 
  group_map(~st_union(.x)) 
```
But not this one:
```r  
  nc %>%
    group_by(cluster) %>% 
    group_map(st_union)
```

**Comment by edzer** [comment]
The documentation of `group_map` explains this: if a function is passed, this function should at least take two arguments, if a fomula is passed with `.x`, you pass the group; if `.y` is used, in addition a one-row tibble with the key is passed as `.y`. This latter form (with `.y`) is the form taken when you pass a function directly. `st_union` doesn't know what to do with that key tibble in `.y`. 

`st_crs` on a non-sf object returns `NA`: maybe it should break with an error instead?

**Comment by Bakaniko** [comment]
I'm not very keen with the formula notation so I was not able to understand the documentation correctly and provided a solution like Sebastien. 

Thanks for this explanation. Let's hope it will also help someone in the future.

**Comment by edzer** [comment]
Another solution is to wrap `st_union` with an anonymous function absorbing `y`:
```r
nc %>% group_by(cluster) %>% 
  group_map(function(x, y) st_union(x)) 
```

**Comment by rsbivand** [comment]
Sorry, base is simply clearer and easier:

```
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
nc1 <- st_centroid(st_transform(nc, 2264))
nc1$cluster <- kmeans(st_coordinates(nc1), centers = 3)$cluster
res <- st_centroid(aggregate(nc1[, 9:14], list(nc1$cluster), sum))
```
(Grouping the id variables is improper, summing the count variables proper).

**Comment by edzer** [comment]
Sorry, but I don't see any point in fighting that fight here.

**Comment by rsbivand** [comment]
I do not do fighting, and resent your suggestion that  such is the intention. I'm just pointing to something obvious, and that the reprex wasn't reproducible (missing `set.seed()`). Do not impute pugilistic intent where none is meant. Your comment is rather a sign of closing down reasoned discussion (muting as put in a well-known video).
