### ISSUE TITLE
How to assign a range of values in a color palette and use it with ggmap

### ISSUE THREAD

**Issue by pkageliza** [r-spatial/sf#1301]
I am trying to assign dose levels and show them on a map. The color_scale_viridis works well. However, I would like to have the distribution in such a way that values 0-60 is blue, 60-120 is green, 120-360 is yellow 360-600 is orange and >600 red. I have tried this using color_scale_manual after assigning the values as below  using library(unikn)

my_color=c("0-60"= "blue", "60-120"="green", "120-360"="yellow", "360-600"="orange", ">600"="red")
but an error occurs
Error: Continuous value supplied to discrete scale
Kindly assist

**Comment by edzer** [comment]
If you want someone to assist, provide a minimal reproducible example. From what you provide here, it looks like a problem with ggmap or unikn, I'd suggest you first continue there.

**Comment by pkageliza** [comment]
ggplot(Mrima, mapping=aes(x=lon,y=lat))+
  geom_point(aes(color=dose),alpha=0.6, size=1)+coord_quickmap()+scale_color_viridis(direction=-1)

Output is this
![Dose_map](https://user-images.githubusercontent.com/55737282/76680703-def4c000-65fb-11ea-9f19-3837e62562f0.png)
