### ISSUE TITLE
st_centroid which could return a point inside the polygon

### ISSUE THREAD

**Issue by ericemc3** [r-spatial/sf#1302]
Is there a way to get a centroid that is for sure inside the polygon (or multipolygon), i am thinking about an option like "inside_polygon = TRUE" ?

=> st_centroid( pg, of_largest_polygon = TRUE, inside_polygon = TRUE ) 

I know i can build a function that would check this with st_within() and fetch if needed a new adjusted centroid via st_point_on_surface(). But it would be easier of course, and probably faster if implemented in st_centroid directly.

Thanks

**Comment by tim-salabim** [comment]
I believe what you are after is `st_point_on_surface`. It is a best approximation of a centroid guaranteed to be inside a (multi)polygon. See [here](https://gis.stackexchange.com/questions/76498/how-is-st-pointonsurface-calculated) for how it is calculated.

**Comment by ericemc3** [comment]
I am looking for a pretty and consistent centroid, so the first computation as the middle of the largest polygon/ring bounding box is my first target. But in some rare cases it falls outside the polygon, hence the need to adjust the centroid position only in those cases. The problem with st-point_on_surface is that it delivers a random location inside the polygon.

This is for building thematic maps with proportional symbols, nicely "centered" on each area.

**Comment by Nowosad** [comment]
@ericemc3 please read the link provided by @tim-salabim. `st_point_on_surface` do not return a random location inside the polygon. See also example below from https://geocompr.robinlovelace.net/geometric-operations.html#centroids:

![](https://geocompr.robinlovelace.net/figures/centr-1.png)

**Comment by ericemc3** [comment]
Thank you both @Nowosad and @tim-salabim, this is very interesting. Of course st_point_on_surface has an implementation, it does not return random points. Maybe it is not so bad. I'd like to know the exact logic behind this function. 

From the link provided by @tim-salabim, i read:

> Thus, ST_PointOnSurface() and ST_Centroid() are usually different points, even on convex polygons.

I just would like to be sure that st_point_on_surface generally returns a location close to the usual bounding-box centroid AND inside the largest polygon if we have to deal with a multipolygon.

**Comment by tim-salabim** [comment]
@ericemc3 how bout you calculate the centroids first and for all the centroids that do not intersect or lie within a polygon you use `st_point_on_polygon` as a fallback?

**Comment by ericemc3** [comment]
@tim-salabim 
i had already found some answers following that idea:
https://stackoverflow.com/questions/52522872/r-sf-package-centroid-within-polygon/55099535#55099535
and
https://stackoverflow.com/questions/44327994/calculate-centroid-within-inside-a-spatialpolygon

But a low-level implemetation in r-sf / st_centroid() could definitely prove faster and more elegant. I wish i'd could propose something, but my skills in R/C++ are not yet so developped...

**Comment by setabnai** [comment]
Sorry this is not elegant, not C++, probably not as fast as it could be ... but it is R and 'works for me'.

```r
# example polygon
x <- sf::st_as_sf(
    data.frame(
        wkt = "POLYGON ((1441727.5096940901130438 6550163.0046194596216083,1150685.2609429201111197 6669225.7427449300885201,975398.4520359700545669 6603079.7771196700632572,866257.6087542800232768 6401334.5819626096636057,836491.9242229099618271 6106985.0349301798269153,972091.1537546999752522 5835786.5758665995672345,1547561.0546945100650191 5782869.8033663900569081,1408654.5268814601004124 5600968.3978968998417258,720736.4843787000281736 5663807.0652409195899963,598366.4479719599476084 6001151.4899297598749399,654590.5187534400029108 6341803.2128998702391982,869564.9070355399744585 6784981.1825891500338912,1451649.4045378800947219 6788288.4808704098686576,1441727.5096940901130438 6550163.0046194596216083))"
    )
    , wkt = "wkt"
)

# find centroids
cx <- list(
    # usual sf::st_centroid()
    cx1 = .st_centroid_within_geo(x, ensure_within = FALSE, of_largest_polygon = FALSE)
    , cx2 = .st_centroid_within_geo(x, ensure_within = FALSE, of_largest_polygon = TRUE)
    # utilising sf::st_point_in_surface() if needed
    , cx3 = .st_centroid_within_geo(x, ensure_within = TRUE, of_largest_polygon = FALSE)
    , cx4 = .st_centroid_within_geo(x, ensure_within = TRUE, of_largest_polygon = TRUE)
)

# visualise
ggplot2::ggplot() +
    ggplot2::geom_sf(data = x) +
    lapply(
        rev(seq_along(cx))
        , function(i) {
            ggplot2::geom_sf(aes(fill = as.character(i)), shape = 21, size = 2*i, data = cx[[i]])
        }
    )

```
... with a nod to 
https://stackoverflow.com/questions/52522872/r-sf-package-centroid-within-polygon
https://stackoverflow.com/questions/44327994/calculate-centroid-within-inside-a-spatialpolygon
Robin Lovelace
... and probably other sources

```r
library("dplyr")
library("sf")
library("data.table")


#' Find largest ring of a multipolygon
#'
#' Assumes dealing with polygons
#'
#' @param x (sf object of polygons)
#'
#' @return (sf object) replaced with centroids
#'
#' @seealso sf:::largest_ring()
#'
.st_largest_ring <- function(x) {
    if (nrow(x) < 1)
        return(x)

    seq(1, nrow(x)) %>%
        lapply(function(i){
            x[i, ] %>%
                sf::st_set_agr("identity") %>%
                sf::st_cast("POLYGON") %>%
                mutate(st_area = sf::st_area(st_geometry(.))) %>%
                top_n(1, st_area) %>%
                select(-st_area)
        }) %>%
        data.table::rbindlist() %>%
        sf::st_as_sf()
}


#' Find a centroid summary of a polygon.
#'
#' reference:
#' https://stackoverflow.com/questions/52522872/r-sf-package-centroid-within-polygon
#' https://stackoverflow.com/questions/44327994/calculate-centroid-within-inside-a-spatialpolygon
#'
#' @param x (sf) spatial polygon
#' @param ensure_within (logical) TRUE to ensure point within polygon.
#' @param of_largest_polygon (logical) TRUE to use largest polygon when
#'   determining centroid.
#'
#' Will return the usual geometric centroid when \code{ensure_within} is FALSE.
#'
#' Otherwise the point returned will be the geometric centroid if it lies within
#' the polygon else a point determined by st_point_on_surface.
#'
#' In all cases an attempt is made to observe \code{of_largest_polygon} (see
#' sf::st_centroid()).
#'
#' \code{of_largest_polygon} used when determining geometric centroid.  An
#' effort to apply this idea to sf::st_point_on_surface() routine.
#'
#' @return (sf) spatial object with centroids within spatial feature.
#'
.st_centroid_within_geo <- function(
    x
    , ensure_within = TRUE
    , of_largest_polygon = FALSE
) {
    cx <- sf::st_centroid(
        sf::st_set_agr(x, "identity")
        , of_largest_polygon = of_largest_polygon
    )

    if (ensure_within) {

        i_within <- sf::st_within(cx, x, sparse = TRUE) %>%
            as.data.frame() %>%
            filter(row.id == col.id) %>%
            pull(row.id)

        i_nwithin <- setdiff(seq(1, nrow(x)), i_within)

        sf::st_geometry(cx[i_nwithin, ]) <- (
            x[i_nwithin, ] %>% {
                if (of_largest_polygon == TRUE)
                    .st_largest_ring(.)
                else
                    .
            } %>%
                sf::st_geometry() %>%
                sf::st_point_on_surface()
        )
    }

    return(cx)
}

**Comment by rsbivand** [comment]
Thanks. A start, but recall that pipes should not be used inside functions. Inside functions, all intermediate objects should be assigned to objects, so that their contents are available to `debug()`. Pipes assign to `.` internally, but you have to debug the pipe operator to be able to verify its contents. That is why pipes may be used in scripts, but not in functions (unless one bravely assumes that the objects always and only contain what is expected, in this case irrespective of GEOS versions).

What is actually needed is the centroid of the interior convex hull of the border point set, the largest area defined within the points making up the border in a planar representation. I did look to see if  there are any implementations, such as in the **alphahull** package. Maybe the centroid of the largest tesselation output (Delauney/Voronoi) within the border points of the largest component POLYGON object, preferably with no interior rings. The interior ring problem is hard because say rural municipalities often surround urban municipalities. I seem to recall that @barryrowlingson touched on this some time ago elsewhere?

**Comment by dr-jts** [comment]
The algorithm GEOS uses is the same as JTS.  The algorithm is described [here](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/algorithm/InteriorPointArea.html):

* Determine a horizontal scan line on which the interior point will be located. To increase the chance of the scan line having non-zero-width intersection with the polygon the scan line Y ordinate is chosen to be near the centre of the polygon's Y extent but distinct from all of vertex Y ordinates.
* Compute the sections of the scan line which lie in the interior of the polygon.
* Choose the widest interior section and take its midpoint as the interior point.

In practice, this is usually better than the centroid for a label point.  

JTS is also shortly to gain a `MaximiumInscribedCircle` algorithm, which provides another candidate for a label point.  (Although experimenting with all of these indicates that no single algorithm always produces a good label location.  It would be an interesting area of research to find a heuristic which chooses the best option out of all of them).

**Comment by ericemc3** [comment]
Thanks, st_point_on_surface looks then like the proper choice
