### ISSUE TITLE
creating a data range for color coding and using it in color_manual_scale

### ISSUE THREAD

**Issue by pkageliza** [r-spatial/sf#1304]
Dear All.

Kindly assist me with the proper code for the following. I have converted the dose to factor and grouped it into 5 levels. I need to assign a color code to each of the level and use is for spatial maaping. Thank you

ggplot(Mrima, mapping=aes(x=lon,y=lat))+
      geom_point(data=Mrima, aes(colour=factor(dose), cut(dose,br=c(0,60,120,360,600,5144)))) +
    scale_color_manual(my_col, values = c("#D01556#", "#DF785B","EFDC60", "#B5D374","#7CCA89"),breaks=waiver(), aesthetics =c("colour","fill"))
    
This is the error I am getting

Error: Insufficient values in manual scale. 1806 needed but only 5 provided.

**Comment by rsbivand** [comment]
This is not an approoriate place to ask. Ask where the main packages used
live, use a different package, such as tmap, or post on R-sig-geo after
subscribing. Understand that you will not get any quick help without a
fully reproducible example, which runs completely without access to your
data.

Roger Bivand
Falsensvei 32
5063 Bergen

man. 16. mar. 2020, 09.18 skrev pkageliza <notifications@github.com>:

**Comment by pkageliza** [comment]
Thank you
