### ISSUE TITLE
library installation error: `units` needed

### ISSUE THREAD

**Issue by NoushinN** [r-spatial/sf#1305]
Hi there,
Here's the error I am getting when installing sf package:

`library(sf)
Error: package or namespace load failed for ‘sf’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘units’`

Any suggestions?

**Comment by NoushinN** [comment]
install.packages("sf")

* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/units’
Warning in install.packages :
  installation of package ‘units’ had non-zero exit status

**Comment by edzer** [comment]
Have you tried installing package `units`?

**Comment by NoushinN** [comment]
Yes, this is the error:
Warning in install.packages :
  installation of package ‘units’ had non-zero exit status

**Comment by NoushinN** [comment]
problem is solved, successfully installed the `units` package but **not** compiled from source! Thank you
