### ISSUE TITLE
sf 0.9 submission to CRAN

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#1310]
See [here](https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt) for revdep checks. I went through all of them, and will resubmit a version that addresses point 2.

1. Warning: replacing previous import â€˜sf::st_make_validâ€™ by â€˜lwgeom::st_make_validâ€™ when loading â€˜bdlâ€™

   st_make_valid is being moved from lwgeom to sf; packages importing
   both will now generate this warning on startup. This will go away
   automatically when I can submit lwgeom after sf, with lwgeom no
   longer exporting this method.

   Packages affected: bdl, EmissV, RGISTools, tmap

2. problems now solved in sf; 
     - st_sample has become a generic, but didn't export a sfg method
	 - st_make_valid strips crs

   Packages affected: cartography, dssd, eSDM, GADMTools, transformr

3. have been informed:
	
* compstatr https://github.com/slu-openGIS/compstatr/issues/19
* eixport: caused by silicate; reported https://github.com/hypertidy/silicate/issues/104
* exactextractr: https://github.com/isciences/exactextractr/issues/24
* geobr: https://github.com/ipeaGIT/geobr/issues/129
* geosample: by email
* geouy: https://github.com/RichDeto/geouy/issues/3
* jpndistrict: https://github.com/uribo/jpndistrict/issues/30
* hereR: https://github.com/munterfinger/hereR/issues/36
* macleish: https://github.com/beanumber/macleish/issues/26
* mapview: https://github.com/r-spatial/mapview/issues/271
* nhdR: https://github.com/jsta/nhdR/issues/62
* fasterize: https://github.com/ecohealthalliance/fasterize/issues/31
* oceanis: https://github.com/insee-psar-at/oceanis-package/issues/2
* raceland: https://github.com/Nowosad/raceland/issues/5
* rFIA: email to stankehu@msu.edu
* RFmerge: https://github.com/hzambran/RFmerge/issues/1
* rmapshaper: https://github.com/ateucher/rmapshaper/issues/103
* sen2r: https://github.com/ranghetti/sen2r/issues/260
* slga: https://github.com/obrl-soil/slga/issues/1
* spsurvey: email to Weber.Marc@epa.gov
* stars: author is me
* tanaka: https://github.com/rCarto/tanaka/issues/1
* tmaptools: https://github.com/mtennekes/tmaptools/issues/20

4. False positives:

* cdcfluview: curl error, happens at random places, also with current CRAN version of sf;
* gtfs2gps: network error
* NLMR: caused by fasterize, reported there
* rasterDT: caused by fasterize, reported there
* reproducible: caused by fasterize, reported there

**Comment by edzer** [comment]
Reverse dependency checks of second submission: https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200321_121257/reverseDependencies/summary.txt

**Comment by edzer** [comment]
(As expected: cartography, dssd, eSDM, GADMTools, transformr are now resolved)

**Comment by rafapereirabr** [comment]
Hi @edzer . Do you have a planed date to submit the new version of `sf` to CRAN?

**Comment by edzer** [comment]
Yes, it is in the submission process, and could appear any time soon now.

**Comment by edzer** [comment]
Third submission: on PROJ 7.0.0 tests would fail; https://github.com/r-spatial/sf/commit/5187565461ba1790e1df58ab87a3ba220db7922f removes the `unload_gdal()` / `load_gdal()` test; potential issue raised here: https://github.com/OSGeo/gdal/issues/2344
