### ISSUE TITLE
configure: error: proj_api.h not found in standard or given locations.

### ISSUE THREAD

**Issue by ahmathlete** [r-spatial/sf#1313]
Hello people ! 
I'm trying to install sf  and mapview pakages in R , still have the same error of:
configure: error: proj_api.h not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/ahmed/R/x86_64-pc-linux-gnu-library/3.6/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status
I have tried any possible solution available on the internet , No process at all !! 
- Linux installed is : 18.04.1-Ubuntu 
- R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
- proj : Rel. 7.0.0, March 1st, 2020 
The full error text : 
> install.packages("sf")
Installing package into ‘/home/ahmed/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/sf_0.8-1.tar.gz'
Content type 'application/x-gzip' length 8469173 bytes (8.1 MB)
==================================================
downloaded 8.1 MB

* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.0.4
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
checking proj_api.h usability... no
checking proj_api.h presence... no
checking for proj_api.h... no
configure: error: proj_api.h not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/ahmed/R/x86_64-pc-linux-gnu-library/3.6/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status

Your help is already appreciated in advance.!!!!

**Comment by edzer** [comment]
Have you searched the issues of this repo, and read the README section on ubuntu?

**Comment by ahmathlete** [comment]
I have searched the issue in this repo and already tried almost all the solution suggested here starting from : 
1. installing libproj-dev and  libgdal-dev
2. print(Sys.setenv(PKG_CONFIG_PATH = "/usr/local/lib/pkgconfig/")) which shows its TRUE 
3. installing the pakage with directiory  provided :
> install.packages("sf",configure.args = "--with-gdal-config=/usr/bin/gdal-config --with-geos-config=/usr/bin/geos-config --with-proj-include=/usr/include/ --with-proj-lib=/usr/lib/ --with-proj_api.h=/usr/include")
Still  not working , and i can find the missing file in my system. 
Although i didnot read README section on ubunntu.

**Comment by ahmathlete** [comment]
Now its working i installed the development version  from https://github.com/r-spatial/sf/blob/master/README.md, using those commands 
>install.packages(devtools)
>library(devtools)
>install_github("r-spatial/sf")
Output: 
Downloading GitHub repo r-spatial/sf@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: Rcpp  (1.0.3 -> 1.0.4) [CRAN]
5: units (0.6-5 -> 0.6-6) [CRAN
Enter one or more numbers, or an empty line to skip updates:

I had to update all installed pakages.  when loading the package in R , output is : 
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0 
and its working perfectly. 
Thanks !
