### ISSUE TITLE
The replacement of 'st_nn' and 'maxdist'

### ISSUE THREAD

**Issue by PeiLi-Sandman** [r-spatial/sf#1315]
I'm planning to do some similar things as the [Spatial Joining](https://gis.stackexchange.com/questions/320841/combining-st-join-with-st-nn-to-include-all-points-within-as-well-as-within-a-g)

Seems the solution for this problem is: `st_join(points, polygons, join = st_nn, k = 1, maxdist = 500)`

However, when I'm trying to implement this code, it gives me two errors of 'st_nn' and 'maxdist'. So I'm wondering is this a version problem? Did these two parameters are replaced?

**Comment by edzer** [comment]
In that question, `st_nn` was used from package `nngeo`. Did you load that package first?

**Comment by rsbivand** [comment]
Is this related to: https://github.com/michaeldorman/nngeo/issues/12 ?

**Comment by PeiLi-Sandman** [comment]
> In that question, `st_nn` was used from package `nngeo`. Did you load that package first?
Thank you, it works now
