### ISSUE TITLE
Spurious warning

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/sf#1319]
I know and understand the first warning, but I think the second one should not be there...

``` r
library(spData)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

nz_c = st_centroid(nz)
#> Warning in st_centroid.sf(nz): st_centroid assumes attributes are constant over
#> geometries of x
#> Warning: st_crs<- : replacing crs does not reproject data; use st_transform for
#> that
```

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
This is caused by `nz` having an old-style `crs` attribute. Doing a
```
st_crs(nz) = st_crs(nz)
```
before the centroid computation solves it.
