### ISSUE TITLE
sf failing on Solaris

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#1321]
See https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/sf-00check.html

@etiennebr could you please modify tests that require RPostgres so that they are not being run on solaris?

**Comment by etiennebr** [comment]
> Package suggested but not available for checking: ‘RPostgres’

@krlmlr, is it something new or `RPostgres` has never been available for solaris?

**Comment by krlmlr** [comment]
Never been.
