### ISSUE TITLE
Unable to find geos_c.h

### ISSUE THREAD

**Issue by jhrcook** [r-spatial/sf#1324]
Hello,

I am trying to install 'sf' on a computing cluster. I had to install GEOS manually, and I think I did it correctly, but I may not have.

When I try to install 'sf' in R, here is the output I get:

```
> install.packages('sf')

Installing package into ‘/home/jc604/R-3.5.1/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/sf_0.9-0.tar.gz'
Content type 'application/x-gzip' length 8474738 bytes (8.1 MB)
==================================================
downloaded 8.1 MB

* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /n/app/gdal/3.0.2/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.0.2
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /n/app/gdal/3.0.2/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.0.2
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 6.0.0
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
checking for geos-config... /home/jc604/mysoftware/geos-bin/usr/local/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.9.0
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... no
checking geos_c.h presence... no
checking for geos_c.h... no
configure: error: geos_c.h not found in given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/jc604/R-3.5.1/library/sf’

The downloaded source packages are in
	‘/tmp/Rtmp5zzSTH/downloaded_packages’
Warning message:
In install.packages("sf") :
  installation of package ‘sf’ had non-zero exit status
```

It looks like it fines my `geos-config` file at `/home/jc604/mysoftware/geos-bin/usr/local/bin/geos-config`, but it cannot locate the `geos_c.h` file at `/home/jc604/mysoftware/geos-bin/usr/local/include/geos_c.h`.

Also, if it provides any insight, running `geos-config --includes` returns `/usr/local/include` which is *not* where the actual include directory is. Do I need to change this, and if so, how?

I've been struggling with this for hours, so I would greatly appreciate any help you could offer.

Thank you,
Josh

**Comment by rsbivand** [comment]
Geos 3.9.0 is not yet released, the latest release is 3.8.1.
https://trac.osgeo.org/geos/ Could you try with a released version?

Roger Bivand
Falsensvei 32
5063 Bergen

fre. 27. mar. 2020, 23.12 skrev Josh Cook <notifications@github.com>:

**Comment by jhrcook** [comment]
Thank you for such a quick reply! I installed version 3.8.1 the same way as I did for 3.9.0 and still got the same error (truncated message shown below):

```
> install.packages("sf")
...
checking for geos-config... /home/jc604/mysoftware/geos-bin/usr/local/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.8.1
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... no
checking geos_c.h presence... no
checking for geos_c.h... no
configure: error: geos_c.h not found in given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/jc604/R-3.5.1/library/sf’

The downloaded source packages are in
	‘/tmp/RtmpJDTrrw/downloaded_packages’
Warning message:
In install.packages("sf") :
  installation of package ‘sf’ had non-zero exit status
```

**Comment by edzer** [comment]
I use a docker file for testing with custom install directories of PROJ, GDAL and GEOS here: https://github.com/r-spatial/sf/blob/master/inst/docker/custom/Dockerfile

**Comment by rsbivand** [comment]
I think that there may be multiple installed GEOS, or anyway geos-config, and the one found by ./configure does not point to the correct include directory. I'd run `geos-config --clibs` and `geos-config --cflags` manually at the command line to see where they point, and `locate geos-config` and `which geos-config`. It isn't anything to do with **sf** or **rgeos** - did you try installing **rgeos** to cross-check?

Also, download and unpack the sf source, and run ./configure stand-alone to try out possible configure arguments. 

Most likely multiple GEOS installs.

Where did 3.9.0 come from? The development version built from the Gitea source may rather report 3.9.0dev. Did you have a reason for trying to install with the current development master/some branch?

I also hope that you know that GEOS and PROJ must be installed before GDAL if installing from source, because GDAL can depend on GEOS and must depend on PROJ.

**Comment by jhrcook** [comment]
> I use a docker file for testing with custom install directories of PROJ, GDAL and GEOS here: https://github.com/r-spatial/sf/blob/master/inst/docker/custom/Dockerfile

Unfortunately, the maintainers of the computing cluster have not installed Docker, so I cannot test with that image.

> I think that there may be multiple installed GEOS, or anyway geos-config, and the one found by ./configure does not point to the correct include directory. I'd run, assuming Linux or similar, `geos-config --clibs` and `geos-config --cflags` manually at the command line to see where they point, and `locate geos-config` and `which geos-config`. It isn't anything to do with **sf** or **rgeos** - did you try installing **rgeos** to cross-check?
> 
> Also, download and unpack the sf source, and run ./configure stand-alone to try out possible configure arguments.
> 
> Most likely multiple GEOS installs.
> 
> Where did 3.9.0 come from? The development version built from the Gitea source may rather report 3.9.0dev. Did you have a reason for trying to install with the current development master/some branch?
> 
> I also hope that you know that GEOS and PROJ must be installed before GDAL if installing from source, because GDAL can depend on GEOS and must depend on PROJ.

I tried the suggestions you gave, but there is only one GEOS installed. I found out the problem was that I needed to set the `-DCMAKE_INSTALL_PREFIX=` when running `cmake` during the installation process. It seems to have fixed the issue with the missing `geos_c.h` file. However, the next check now fails:

```
install.packages("sf")
...
checking for geos-config... /home/jc604/mysoftware/geos-bin/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.8.1
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/home/jc604/mysoftware/geos-bin/lib -lgeos_c... no
checking geos: linking with -L/home/jc604/mysoftware/geos-bin/lib -lgeos_c -lgeos -lm... no
/usr/bin/ld: cannot find -lgeos
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: initGEOS_r not found in libgeos_c.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/jc604/R-3.5.1/library/sf’

The downloaded source packages are in
	‘/tmp/RtmpuAJA8c/downloaded_packages’
Warning message:
In install.packages("sf") :
  installation of package ‘sf’ had non-zero exit status
```

Do you have any idea what causes this?
The following files are in the `/home/jc604/mysoftware/geos-bin/lib` directory:

```
cmake
libgeos_c.so -> libgeos_c.so.1
libgeos_c.so.1 -> libgeos_c.so.1.13.3
libgeos_c.so.1.13.3
libgeos.so.3.8.1
```

Version 3.9.0 is the version that is obtained from downloading the zip of the GH repo. I have instead used the 3.8.1 release.

You are completely correct that this is not a 'sf'-specific problem - the same problems happen when I try to install 'rgeos'. I just don't know where else to get help with this problem from knowledgeable people. I greatly appreciate your help.

**Comment by rsbivand** [comment]
I have only ever used ./configure to install GEOS, and cannot comment on cmake, other than comments on the mailing list perhaps indicating that it is not what users on unixen use. Try the ./configure, make, make check, make install route. If you can see what is wrong with cmake, create an issue or comment on the GEOS list.

**Comment by rsbivand** [comment]
The table on https://trac.osgeo.org/geos/  suggests that most Debian/Alpine/Ubuntu are using automake, and that there may be specific versions of cmake needed.

**Comment by jhrcook** [comment]
I have reinstalled GEOS using `./configure --prefix=/home/jc604/mysoftware/geos-bin` and that has solved most of the issues. I now get all the way through to the last final checks of the installation process and then get the following error:

```
> install.packages("sf")

...

** R
** demo
** inst
** byte-compile and prepare package for lazy loading
in method for ‘dbWriteTable’ with signature ‘"PostgreSQLConnection","character","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘dbDataType’ with signature ‘"PostgreSQLConnection","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘coerce’ with signature ‘"Spatial","sf"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"Spatial","sfc"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sf","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sfc","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"XY","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"crs","CRS"’: no definition for class “CRS”
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/jc604/R-3.5.1/library/00LOCK-sf/00new/sf/libs/sf.so':
  libgeos_c.so.1: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/jc604/R-3.5.1/library/sf’

The downloaded source packages are in
	‘/tmp/RtmpcpN47i/downloaded_packages’
Warning message:
In install.packages("sf") :
  installation of package ‘sf’ had non-zero exit status
```

The same error occurs when I try to install 'rgeos.' The following are the contents of '/home/jc604/mysoftware/geos-bin/lib' (which is the directory that is output from `geos-config --libs`:

```
[~]$ ls /home/jc604/mysoftware/geos-bin/lib
libgeos-3.8.1.so
libgeos.a
libgeos_c.a
libgeos_c.la
libgeos_c.so -> libgeos_c.so.1.13.3
libgeos_c.so.1 -> libgeos_c.so.1.13.3
libgeos_c.so.1.13.3
libgeos.la
libgeos.so -> libgeos-3.8.1.so
```

**Comment by rsbivand** [comment]
The GEOS shared object is not being found at run time. I am admin on my machines, so use admin mechanisms, adding a file to `/etc/ld.so.conf.d/` specifying the non-standard location in which to look; then I run `/usr/sbin/ldconfig` to register the contents of that directory. 

If you do not have admin rights, you will need to work around this, possibly with environment variable `LD_LIBRARY_PATH`, before starting R (check its existing value and add the path to where the so lives to that), or at least before loading **sf**. If you alter the environment variable inside R with `Sys.setenv()`, do add your path to what is already there, do not overwrite that (on unixen `:` separated). 

Note that GDAL is often built against GEOS, so once GEOS is found by say **rgeos**, you may need to rebuild GDAL (some vector drivers use GEOS if available). If you installed GDAL from source before installing GEOS, it will not use GEOS. If that doesn't matter, OK, but some vector drivers work better using GEOS to check topologies.

**Comment by jhrcook** [comment]
Adding it to `LD_LIBRARY_PATH` did the trick! Thank you so much for your patience and help, I greatly appreciate it!

For completeness, here are the reuiqred steps:

```bash
cd ~/mysoftware

# Download the latest release (not development version v3.9.0)
wget https://github.com/libgeos/geos/archive/3.8.1.zip
unzip 3.8.1.zip
cd geos-3.8.1

./autogen.sh

mkdir ~/mysoftware/geos-bin
mkdir obj && cd obj
../configure --prefix=/home/jc604/mysoftware/geos-bin

make

make install
```

And add the following to `~/.bash_profile`:

```bash
# For GEOS
export PATH=$PATH:$HOME/mysoftware/geos-bin/bin
export PATH=$PATH:$HOME/mysoftware/geos-bin/include
export PATH=$PATH:$HOME/mysoftware/geos-bin/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/mysoftware/geos-bin/lib
```
