### ISSUE TITLE
proj_api.h not found in standard or given locations

### ISSUE THREAD

**Issue by MuDestructor** [r-spatial/sf#1329]
Hi,

I have this error when installing sf
configure: error: proj_api.h not found in standard or given locations.

I know where the file is, in which variable could the address pass it?

thanks!

**Comment by rsbivand** [comment]
Unless you need to install **sf** from source, and know how to install all its system requirements, do not do so. If you really need to and are, let me guess, on OSX, read https://github.com/r-spatial/sf/issues/1327 and draw the same conclusions. 

Effectively the only real need would be that you are the maintainer of a package that the recent release of **sf** has broken, and you cannot work on any other platform. Since this does not seem to be the case, simply use the CRAN binaries that are available.

**Comment by MuDestructor** [comment]
I'm just trying to install the package on my Linux machine. Just like I install the rest of the packages.

**Comment by edzer** [comment]
Which linux, which command did you use, which R version, which GDAL/GEOS/PROJ versions, how did you install PROJ, did you follow the instructions on the README of this repo?

**Comment by rsbivand** [comment]
Did you read: https://github.com/r-spatial/sf README -> Install, and issues regarding broken PROJ 7.0.0 proj.pc? How did you install (all of) PROJ, GDAL, GEOS? Which version of **sf** are you trying to install? If you have PROJ 7.0.0, this message could occur with earlier versions of **sf**, but not released 0.9-0. Did you install all of PROJ?

**Comment by MuDestructor** [comment]
Thanks for your responses.

I understand from what they say that there is no simple answer to my question, about how to pass the location of the files.

Linux version:
CentOS Linux release 7.5

The command I use is:
install.packages ("sf")
or
install_github ("r-spatial / sf")

R version:
R version 3.6.3

I have installed everything with CONDA
conda install -c conda-forge proj4 --override-channels
conda install -c conda-forge gdal --override-channels
conda install -c conda-forge libgdal
conda install -c conda-forge r-rgdal

This has worked for me
conda install -c conda-forge r-sf

And since install.packages ("sf") fails I wanted to know what environment variable they would have configured for the installation to work for them. Since then I also wanted to install another package that gave the same problem https://github.com/rspatial/terra but they don't have packages in conda-forge.

I continue investigating what they have written to me.

**Comment by rsbivand** [comment]
Unless you can confirm that the missing file is on your system, all hope is out. `locate proj_api.h` should be in `pkg-config proj --cflags`. If conda does not package correctly, or does not provide all the required files, use your regular distribution packager  or install from source. AFAIK no R spatial developer or maintainer uses conda, so you are on your own there.

**Comment by MuDestructor** [comment]
The package is on my system
miniconda3/envs/esteban_env2/include/proj_api.h
What I don't know is how to tell you where to look for it

Thank you very much for trying to help me.

**Comment by rsbivand** [comment]
What does `pkg-config proj --cflags` say? Probably conda doesn't support other build systems, so you'll need to use configure arguments. For **sf** 

```
  --with-gdal-config=GDAL_CONFIG
                          the location of gdal-config
  --with-data-copy=yes/no local copy of data directories in package, default
                          no
  --with-proj-data=DIR    location of PROJ data directory
  --with-proj-include=DIR location of proj header files
  --with-proj-api=yes/no  use the deprecated proj_api.h even when PROJ 6 is
                          available; default no
  --with-proj-lib=LIB_PATH
                          the location of proj libraries
  --with-proj-share=SHARE_PATH
                          the location of proj metadata files
  --with-geos-config=GEOS_CONFIG
                          the location of geos-config
```
so probably `pkg-config proj --modversion` fails. If you can find `proj.pc`, `export PKG_CONFIG_PATH=` to the directory it lives in may be easier than using configure arguments.

**Comment by MuDestructor** [comment]
Returns nothing
pkg-config proj --cflags

pkg-config proj --modversion
Returns 4.8.0

I have found proj.pc in
miniconda3/envs/esteban_env2/lib/pkgconfig

I will try with the things that you indicate to me, thanks.

**Comment by rsbivand** [comment]
PROJ 4.8.0 was released in 2012, I'm afraid, and isn't viable.

**Comment by MuDestructor** [comment]
Thank you very much for your help. Your comments have made me solve the problem.
I installed
conda install -c conda-forge pkgconfig
And it already works.
Until now
pkg-config proj --modversion
He was giving me back the system version and not the conda version.
