### ISSUE TITLE
Suggestion for filtering on geometry

### ISSUE THREAD

**Issue by msberends** [r-spatial/sf#1338]
For spatial analyses I often require to filter on a specific area with multiple geometries without knowing their names or IDs. 

I find filtering on a geometry very hard and I could not find a suitable solution online. I plot sf with `ggplot()`, but their suggestion is to use `coord_sf(xlim = ..., ylim = ...)`, which only 'hides' part of the data and remains slow for a large region with small geometries (like detailed zip codes).

I came with these solutions to quickly filter on `sfc` variables:
```r
x_min <- function(geometry) {
  sapply(geometry, function(x) min(x[[1]][[1]][, 1]))
}
x_max <- function(geometry) {
  sapply(geometry, function(x) max(x[[1]][[1]][, 1]))
}
y_min <- function(geometry) {
  sapply(geometry, function(x) min(x[[1]][[1]][, 2]))
}
y_max <- function(geometry) {
  sapply(geometry, function(x) max(x[[1]][[1]][, 2]))
}
```

They basically return all minima and maxima of x and y.

So plotting without filter:

```r
# loading required data
library(sf)
nc <- st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)
```

```r
nc %>%
  plot(max.plot = 99)
```
![image](https://user-images.githubusercontent.com/31037261/78422026-b3924d80-765c-11ea-8de8-424cc2829792.png)

And plotting with filter:
```r
nc %>%
  filter(x_max(geometry) < 78,
         y_min(geometry) > 36) %>%
  plot(max.plot = 99)
```
![image](https://user-images.githubusercontent.com/31037261/78422037-c442c380-765c-11ea-8bfc-e803f87427f8.png)

Would this be something to add to the package? Or something that resembles it? This saves me tons of time and energy.

**Comment by edzer** [comment]
You could do sth like "within bounding box" selection, using
```r
bb = st_bbox(nc)
bb["ymin"] = 36
bb["xmax"] = 78
plot(nc[st_as_sfc(bb),,op=st_within])
```
or, `dplyr` style,
```r
nc %>% st_filter(st_as_sfc(bb), .predicate = st_within) %>% plot()
```
This will work for arbitrary geometries, unlike your approach which will not do it for both `POLYGON` and `MULTIPOLYGON` geometries

**Comment by msberends** [comment]
True, but for not so experienced GIS analysts I find that not exactly convenient. 

Couldn’t st_filter() work without having to set the required dimensions in three extra commands?

**Comment by edzer** [comment]
No, sorry.

**Comment by msberends** [comment]
Alright, that's too bad. Thank you for your time.

Should anyone get here via a search machine, you can use this function to use the robust method as provided by @edzer:
```r
filter_sf <- function(.data, xmin = NULL, xmax = NULL, ymin = NULL, ymax = NULL) {
  bb <- sf::st_bbox(.data)
  if (!is.null(xmin)) bb["xmin"] <- xmin
  if (!is.null(xmax)) bb["xmax"] <- xmax
  if (!is.null(ymin)) bb["ymin"] <- ymin
  if (!is.null(ymax)) bb["ymax"] <- ymax
  sf::st_filter(.data, sf::st_as_sfc(bb), .predicate = sf::st_within)
}

# example
nc %>%
  filter_sf(xmax = 78,
            ymin = 36) %>%
  plot()
```
