### ISSUE TITLE
gdal_utils "translate" does not respect compression option

### ISSUE THREAD

**Issue by lbusett** [r-spatial/sf#1339]
Hi, 

   trying to use the "translate" option in `gdal_utils` and setting the compression of the ouput file , I noticed that the "-co COMPRESS=XXX" option is ignored, with a warning: 

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
tempout <- tempfile(fileext = ".tif")
sf::gdal_utils("translate", system.file("tif/L7_ETMs.tif", package="stars"), 
               tempout, options = c("-co", "COMPRESS=LZW"))
#> Warning in CPL_gdaltranslate(source, destination, options, oo): GDAL Message 6:
#> driver GTiff does not support open option COMPRESS
```

I'd guess this is due to this line in gdal_utils: 

https://github.com/r-spatial/sf/blob/39fc9e9a9fb11a0a4273c0b1adb9ca19489bbf9a/R/gdal_utils.R#L76

, where I think "-co" options are "transformed" in "-oo" options. 

If so, this would affect also others utils, such as `gdalwarp`, though I did not test it. 

HTH

<sup>Created on 2020-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
I don't know why I put in that line. 

@Robinlovelace could you please check that this doesn't cause a regression in https://github.com/ITSLeeds/geofabrik/issues/12 , where this all began?
