### ISSUE TITLE
R < 3.5 does not have isFALSE

### ISSUE THREAD

**Issue by gdkrmr** [r-spatial/sf#1342]
you are using the function isFALSE [here](https://github.com/r-spatial/sf/blob/cdf5f58dfa1aacd64179006fcc6c15ff90812146/R/read.R#L379). The function was introduced into R with version 3.5.

This can be fixed by adding the following somewhere:
```r
 if (as.integer(version$major) <= 3 &&
    as.integer(strsplit(version$minor, ".", fixed = TRUE)[[1]][1]) <= 4) {
    isFALSE <- function(x) is.logical(x) && length(x) == 1L && !is.na(x) && !x
}
```
funnily `isTRUE` is defined in earlier versions of R.

**Comment by edzer** [comment]
Oops, yes, thanks - should work now.
