### ISSUE TITLE
install.packages('sf') does not work , I can not install it

### ISSUE THREAD

**Issue by lerods** [r-spatial/sf#1344]
Hi Everyone, 

I am trying to install this package, using:
 install.packages('sf')

But , I have not been able to solve it.
Could you help me please.
Thanks in Advance.

Installing package into ‘C:/Users/Leonardo/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is
  later:
   binary source needs_compilation
sf  0.9-0  0.9-1              TRUE

installing the source package ‘sf’

trying URL 'http://cran.rstudio.com/src/contrib/sf_0.9-1.tar.gz'
Content type 'application/x-gzip' length 8478350 bytes (8.1 MB)
downloaded 8.1 MB

* installing *source* package 'sf' ...
** package 'sf' successfully unpacked and MD5 sums checked
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs

*** arch - i386
rm -f sf.dll RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfg.o signed_area.o stars.o wkb.o zm_range.o
mkdir -p ../inst
"C:/PROGRA~1/R/R-36~1.0/bin/i386/Rscript.exe" --vanilla "../tools/winlibs.R" 2.2.3
Error in download.file(sprintf("https://github.com/rwinlib/gdal2/archive/v%s.zip",  : 
  no fue posible abrir la URL 'https://github.com/rwinlib/gdal2/archive/v2.2.3.zip'
Además: Warning message:
In download.file(sprintf("https://github.com/rwinlib/gdal2/archive/v%s.zip",  :
  fallo en InternetOpenUrl: 'No se pudo establecer una conexión con el servidor'
Ejecución interrumpida
make: *** [Makevars.win:27: winlibs] Error 1
ERROR: compilation failed for package 'sf'
* removing 'C:/Users/Leonardo/Documents/R/win-library/3.6/sf'
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status

**Comment by edzer** [comment]
Consider installing the binary version, instead of the source version, unless you know what you are doing.

**Comment by gregleleu** [comment]
Hi, 
I have a similar issue. Here is the message I get.
>In file included from gdal_write.cpp:5:
In file included from /usr/local/include/ogrsf_frmts.h:35:
In file included from /usr/local/include/ogr_feature.h:35:
In file included from /usr/local/include/ogr_featurestyle.h:33:
In file included from /usr/local/include/cpl_conv.h:36:
In file included from /usr/local/include/cpl_vsi.h:62:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:727:31: error: unknown type name 'uuid_t'; did you mean 'uid_t'?

Oh, and I know what I'm doing...

**Comment by lerods** [comment]
Thanks for your help,

I installed the previuos version (sf 0.9-0) and it worked.

Thanks a lot.
