### ISSUE TITLE
arduino / esp8288 / blynk

### ISSUE THREAD

**Issue by hipatel93** [r-spatial/sf#1346]
I am facing error i include section .. can anybody help me.  I have mention program and error below

#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266_SSL.h>

#define BLYNK_PRINT Serial
#define enA 9
#define in1 4
#define in2 5
#define enB 10
#define in3 6
#define in4 7
int motorSpeedA = 0;
int motorSpeedB = 0;
void setup() {

error

Arduino: 1.8.12 (Windows Store 1.8.33.0) (Windows 10), Board: "Arduino Uno"

In file included from C:\Users\patel\OneDrive\Desktop\sketch_apr08a\sketch_apr08a.ino:3:0:

Multiple libraries were found for "BlynkSimpleEsp8266_SSL.h"
C:\Users\patel\OneDrive\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp8266_SSL.h:15:2: error: #error This code is intended to run on the ESP8266 platform! Please check your Tools->Board setting.

 Used: C:\Users\patel\OneDrive\Documents\Arduino\libraries\Blynk
 Not used: C:\Users\patel\OneDrive\Documents\Arduino\libraries\blynk-library-0.6.1
 #error This code is intended to run on the ESP8266 platform! Please check your Tools->Board setting.

  ^~~~~

C:\Users\patel\OneDrive\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp8266_SSL.h:18:10: fatal error: version.h: No such file or directory

 #include <version.h>

          ^~~~~~~~~~~

compilation terminated.

exit status 1
Error compiling for board Arduino Uno.
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\Arduino-master
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\ESP8266SdFat
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\libraries
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\SoftwareSerial
Invalid library found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools: no headers files (.h) found in C:\Users\patel\OneDrive\Documents\Arduino\libraries\tools

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by edzer** [comment]
What does that have to do with this repository?
