### ISSUE TITLE
Open multiple layers from Geodatabase

### ISSUE THREAD

**Issue by Rkleisley** [r-spatial/sf#1353]
I have a geodatabase with multiple layers I want to pull from using buffers and within.
I open the database but it only pulls the first layer, Not sure what options i need to change within st_read.

```> db <- st_read("C:\\....\\ArcGIS\\Projects\\MyProject1\\MyProject1.gdb", promote_to_multi=T)
Multiple layers are present in data source C:\....\ArcGIS\Projects\MyProject1\MyProject1.gdb, reading layer `Point_A'.
Use `st_layers' to list all layer names and their type in a data source.
Set the `layer' argument in `st_read' to read a particular layer.
Reading layer `Point_A' from data source `C:\....\Projects\MyProject1\MyProject1.gdb' using driver `OpenFileGDB'
Simple feature collection with 1 feature and 2 fields
geometry type:  MULTIPOLYGON
dimension:      XYZ
bbox:           xmin: 4911399 ymin: 3917195 xmax: 4968375 ymax: 3959226
z_range:        zmin: 0 zmax: 0
CRS:            3857
Warning message:
In evalq((function (..., call. = TRUE, immediate. = FALSE, noBreaks. = FALSE,  :
  automatically selected the first layer in a data source containing more than one.
```

Also tried

```
> st_read("C:\\....\\ArcGIS\\Projects\\MyProject1\\MyProject1.gdb", layer = c("NAI", "Events"))
Reading layer `NAI' from data source `C:\....\ArcGIS\Projects\MyProject1\MyProject1.gdb' using driver `OpenFileGDB'
Simple feature collection with 5 features and 3 fields
geometry type:  POINT
dimension:      XYZ
bbox:           xmin: 4929375 ymin: 3934413 xmax: 4950826 ymax: 3947552
z_range:        zmin: 0 zmax: 0
CRS:            3857```

**Comment by edzer** [comment]
Have you read the output `st_read` gave you, and based on that tried `st_layers` on the same file?

**Comment by Rkleisley** [comment]
> Have you read the output `st_read` gave you, and based on that tried `st_layers` on the same file?

I have and which lead me to the second line that I attempted, neither opened both files

**Comment by edzer** [comment]
If you clean up the formatting of your issue I can maybe understand what you mean by "the second line".

**Comment by Rkleisley** [comment]
> If you clean up the formatting of your issue I can maybe understand what you mean by "the second line".

That should help, I'm new to this so I apologize

**Comment by edzer** [comment]
`st_read` reads a single layer, if you want to read multiple layers, call it twice with a different value for the `layer` command.
