### ISSUE TITLE
st_line_sample oversamples when density is over twice linestring length

### ISSUE THREAD

**Issue by mcoghill** [r-spatial/sf#1365]
Here is a reproducable example of what I'm trying to convey:

`line <- st_linestring(matrix(c(0, 0, 10, 0), ncol = 2))`

This will produce a linestring of 10 units in length:

`st_length(line)`

I would expect that when `st_line_sample` is used to sample points along the linestring, if the density of points is larger than the length of the line, only a single point would be produced in the middle of the linestring. Indeed, this occurs when the samplng density is anything less than twice the line length, for example if I produce one point for every 11, 15, and 19 units:

```
st_line_sample(line, density = 1/11)
st_line_sample(line, density = 1/15)
st_line_sample(line, density = 1/19)
```
All of the above lines will produce a single point in the middle of the linestring; however, when using densities larger than twice the linestring length, two points are produced: 1 at the beginning and 1 at the end of the line:

```
st_line_sample(line, density = 1/20)
st_line_sample(line, density = 1/50)
st_line_sample(line, density = 1/100)
```
Is that how it is supposed to behave? It just feels a bit awkward, especially when working with multiple lines of varying length. If I had, say, a 10 m, 20 m, and 60 m line segments, if the density of sampling was 1 sample every 30 m, I would only get one sample along the 20 m line segment and two samples along the 10 m segment and the 60 m segment.

Thanks for all your hard work!

**Comment by edzer** [comment]
Thanks! We now return an empty geometry for the smaller densities.
