### ISSUE TITLE
st_intersects() inconsistent results between sf and sfc

### ISSUE THREAD

**Issue by salbeke** [r-spatial/sf#1366]
I am experiencing a strange behavior that I do not understand, perhaps this is the incorrect place to ask the question, but wanted to put it out there. I have two sf objects that have originated from
```
ex1 # sf object of 1 MULTILINESTRING originating from National Hydrography Dataset

nhd # sf object of 1 LINESTRING that does overlap with sf object ex1, also from NHD

st_intersects(ex1, nhd, sparse = FALSE)  # Returns FALSE

# But if I take the WKT of each feature
ex1WKT<- st_as_sfc("MULTILINESTRING ((-1049672 1898011, -1049622 1897993, -1049557 1897971, -1049547 1897968), (-1049672 1898011, -1049682 1898015, -1049719 1898028, -1049740 1898031, -1049760 1898030, -1049797 1898019, -1049810 1898019, -1049823 1898021, -1049829 1898026))")

wktNHD<- st_as_sfc("LINESTRING (-1049834 1898030, -1049823 1898021, -1049810 1898019, -1049797 1898019, -1049760 1898030, -1049740 1898031, -1049719 1898028, -1049682 1898015, -1049622 1897993, -1049557 1897971, -1049530 1897962, -1049522 1897957, -1049517 1897955)")

st_intersects(ex1WKT, wktNHD, sparse = FALSE)  # Returns TRUE
```
I am not sure why there would be a difference in st_intersects() returning FALSE when sf object, and TRUE when I force to sfc object. Does anyone have a suggestion as to why the behavior is different? It is causing some issues with st_join() for me.

sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363) 

other attached packages:
sf_0.9-1 (other packages omitted for readability) 

Thanks in advance,

**Comment by edzer** [comment]
I see
```
> st_intersects(ex1WKT, wktNHD, sparse = FALSE)  # Returns TRUE
     [,1]
[1,] TRUE
> st_intersects(st_as_sf(ex1WKT), st_as_sf(wktNHD), sparse = FALSE)  # Returns TRUE
     [,1]
[1,] TRUE
```
so I think you need to come with a reproducible example.

**Comment by salbeke** [comment]
Yes, sorry for not giving a full example. The best way I can do that is to provide a GeoPackage with two layers, each having one feature: https://web.petalibrary.arcc.uwyo.edu/wygisc/Albeke_Courses/nhdTest.gpkg

Once you have the nhdTest.gpkg, I run the following code:

```
ex1<- st_read("nhdTest.gpkg", "BHS")
nhd<- st_read("nhdTest.gpkg", "NHD")

st_intersects(ex1, nhd, sparse = FALSE) # Returns FALSE

ex1SFC<- st_sfc(ex1$geom)
nhdSFC<- st_sfc(nhd$geom)

st_intersects(ex1SFC, nhdSFC, sparse = FALSE) # Returns FALSE

ex1WKT<- st_as_sfc(st_as_text(ex1SFC))
nhdWKT<- st_as_sfc(st_as_text(nhdSFC))

st_intersects(ex1WKT, nhdWKT, sparse = FALSE) # Returns TRUE
```
For this example at least, my experience is that st_intersects() is having an unexpected behavior that I am unsure of how to solve. Thank you for looking into this.

**Comment by edzer** [comment]
You expect that the WKT representation is identical to the binary, but it isn't:
```r
> identical(ex1WKT, st_geometry(ex1SFC))
[1] FALSE
```
You can write the WKT with more digits using e.g.
```r
st_as_text(ex1SFC,digits=20)
```
but in general I think you shouldn't count on things being equal after binary -> wkt -> binary conversions.
