### ISSUE TITLE
 Possible bug in reprojection of vector data (Natural Earth coastline to Robinson projection)

### ISSUE THREAD

**Issue by AndrewCunliffe** [r-spatial/sf#1372]
Reprojection of the small scale Natural Earth coastline dataset to a Robinson projection returns an erroneous line feature on the plot. Apologies if this is the wrong place to report, it might be an issue with the projection library?

Medium-scale coastlines reproject okay to a World Robinson projection (EPSG:54030)
coastlines <- ne_coastline(scale = "medium", returnclass = "sf")
ggplot(data = coastlines) + geom_sf(colour = "black") + coord_sf(crs = st_crs(54030)) + theme_bw()

Medium-scale coastlines reproject okay to a World Robinson projection (EPSG:54030)
`coastlines <- ne_coastline(scale = "medium", returnclass = "sf")`
`ggplot(data = coastlines) + geom_sf(colour = "black") + coord_sf(crs = st_crs(54030)) + theme_bw()`
![79444912-bc2b4200-7fd3-11ea-9080-03ebe186531c](https://user-images.githubusercontent.com/25197948/79473812-8e5af300-7ffd-11ea-873b-cca01dc067e3.png)

Small-scale coastlines display okay at the default projection
`coastlines <- ne_coastline(scale = "small", returnclass = "sf")`
`ggplot(data = coastlines) + geom_sf(colour = "black") + theme_bw()`
![79444961-cd744e80-7fd3-11ea-89b7-90550a7e1527](https://user-images.githubusercontent.com/25197948/79473831-92871080-7ffd-11ea-9a79-d7ec75b60774.png)

Small-scale coastlines reprojected to the World Robinson projection (EPSG:54030) include the erroneous line feature at ca. 70 degrees north
`coastlines <- ne_coastline(scale = "small", returnclass = "sf")`
`ggplot(data = coastlines) + geom_sf(colour = "black") + coord_sf(crs = st_crs(54030)) + theme_bw()`
![79444953-c8af9a80-7fd3-11ea-9399-62856dabe2f9](https://user-images.githubusercontent.com/25197948/79473776-80a56d80-7ffd-11ea-9e41-6990d39aa233.png)

[Referral from ggplot2](https://github.com/tidyverse/ggplot2/issues/3949)

**Comment by edzer** [comment]
With newer PROJ, I don't see an EPSG:54030: 
```
> library(sf)
Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
> st_crs(54030)
Coordinate Reference System: NA
Warning message:
In CPL_crs_from_input(x) :
  GDAL Error 1: PROJ: proj_create_from_database: crs not found
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.9-3

loaded via a namespace (and not attached):
 [1] compiler_3.6.3     magrittr_1.5       class_7.3-15       tools_3.6.3       
 [5] DBI_1.1.0          units_0.6-6        Rcpp_1.0.4.6       KernSmooth_2.23-15
 [9] grid_3.6.3         e1071_1.7-3        classInt_0.4-3    
```

**Comment by edzer** [comment]
But there is an `st_crs('ESRI:54030')`.

**Comment by edzer** [comment]
```r
ggplot(data = st_wrap_dateline(coastlines)) + geom_sf(colour = "black") +
   coord_sf(crs = st_crs('ESRI:54030')) + 
   theme_bw()
```

![x](https://user-images.githubusercontent.com/520851/79475680-4beae380-8008-11ea-8257-cdbe9bbefb05.png)
