### ISSUE TITLE
saving and sharing data

### ISSUE THREAD

**Issue by igordot** [r-spatial/sf#1375]
I am just getting started with spatial data, so please excuse a potentially very basic question. It's more of a documentation clarification than an actual problem.

If you are working with regular data frames or matrices, you can save them as regular text files. There are some more specialized formats for very large tables, but standard text files are the standard for most people.

If you save a shapefile, you end up with multiple files in addition to `.shp`. That makes it more difficult to share. The most obvious solution is put them in a zip/tar archive, but that adds an extra step for both writing and reading. However, that seems to be a common practice. An obvious alternative is to just save the `sf` object, but then you are relying on a specific package. `write_sf` supports a few options, but it's not very clear what the tradeoffs are. Is there an optimal solution?

**Comment by tim-salabim** [comment]
Geopackage seems like the best choice to me. File ext is .gpkg. it can be read by all major geospatial platforms. st_read/st_write support it and you can even mix vector and raster data in one file.

**Comment by tim-salabim** [comment]
Closing here due to lack of activity. Feel free to reopen if you think this has not been resolved (it's actually not an issue of this repo anyway...)
