### ISSUE TITLE
undefined symbol: pj_get_ellps_ref

### ISSUE THREAD

**Issue by EmmaVJones** [r-spatial/sf#1378]
When trying to install latest version of sf (0.9-2) on R 3.6.1 I cannot seem to overcome 
...
Error: package or namespace load failed for âsfâ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/R/3.6.1/lib/R/library/00LOCK-sf/00new/sf/libs/sf.so':
  /opt/R/3.6.1/lib/R/library/00LOCK-sf/00new/sf/libs/sf.so: undefined symbol: pj_get_ellps_ref

Full R install log at the bottom of post.

The same error is encountered trying to install rgdal as well as previous versions of sf (0.8-0).

I am running RHEL7 with GDAL 2.2.3, PROJ 4.8.0, and GEOS 3.4.2. GDAL 1.11.4 is installed on system (most recent compiled version on EPEL installed via yum), but R is pointing to GDAL 2.2.3 for installation. 

Thanks,
Emma

> install.packages('sf')
trying URL 'https://mirrors.nics.utk.edu/cran/src/contrib/sf_0.9-2.tar.gz'
Content type 'application/x-gzip' length 8479198 bytes (8.1 MB)
==================================================
downloaded 8.1 MB

* installing *source* package âsfâ ...
** package âsfâ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /usr/local/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.2.3
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 2.2.3
configure: pkg-config proj exists, will use it
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
configure: PROJ: 4.8.0
checking for pj_init_plus in -lproj... yes
Fatal error: glibc detected an invalid stdio handle
./configure: line 4060: 26252 Aborted                 ./proj_conf_test
checking PROJ: epsg found and readable... yes
checking for geos-config... /bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib64 -lgeos_c... yes
configure: Package CPP flags:    -I/usr/local/include -I/usr/include
configure: Package LIBS: -lproj     -L/usr/local/lib -lgdal -L/usr/lib64 -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c bbox.cpp -o bbox.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c gdal.cpp -o gdal.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c gdal_geom.cpp -o gdal_geom.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c gdal_read.cpp -o gdal_read.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c gdal_utils.cpp -o gdal_utils.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c gdal_write.cpp -o gdal_write.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c geos.cpp -o geos.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c hex.cpp -o hex.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c ops.cpp -o ops.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c polygonize.cpp -o polygonize.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c proj.cpp -o proj.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c proj_info.cpp -o proj_info.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c raster2sf.cpp -o raster2sf.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c sfg.cpp -o sfg.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c signed_area.cpp -o signed_area.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c stars.cpp -o stars.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c wkb.cpp -o wkb.o
g++ -std=gnu++11 -I"/opt/R/3.6.1/lib/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I"/opt/R/3.6.1/lib/R/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c zm_range.cpp -o zm_range.o
g++ -std=gnu++11 -shared -L/opt/R/3.6.1/lib/R/lib -L/usr/local/lib -o sf.so RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfg.o signed_area.o stars.o wkb.o zm_range.o -lproj -L/usr/local/lib -lgdal -L/usr/lib64 -lgeos_c -L/opt/R/3.6.1/lib/R/lib -lR
installing to /opt/R/3.6.1/lib/R/library/00LOCK-sf/00new/sf/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
in method for âdbWriteTableâ with signature â"PostgreSQLConnection","character","sf"â: no definition for class âPostgreSQLConnectionâ
PostgreSQLConnectionâ
Spatialâ
Spatialâ
Spatialâ
Spatialâ
Spatialâ
CRSâ

*** installing help indices
  converting help for package âsfâ
    finding HTML links ... done
    Ops                                     html
    aggregate.sf                            html
    bind                                    html
Rd warning: /tmp/RtmpjegcSq/R.INSTALL641559c6bb56/sf/man/bind.Rd:19: file link ârbindâ in package âbaseâ does not exist and so has been treated as a topic
    coerce-methods                          html
Rd warning: /tmp/RtmpjegcSq/R.INSTALL641559c6bb56/sf/man/coerce-methods.Rd:33: file link âspâ in package âspâ does not exist and so has been treated as a topic
    dbDataType                              html
    db_drivers                              html
    extension_map                           html
    gdal                                    html
    gdal_utils                              html
    geos_binary_ops                         html
    geos_binary_pred                        html
    geos_combine                            html
Rd warning: /tmp/RtmpjegcSq/R.INSTALL641559c6bb56/sf/man/geos_combine.Rd:33: file link âgUnaryUnionâ in package ârgeosâ does not exist and so has been treated as a topic
Rd warning: /tmp/RtmpjegcSq/R.INSTALL641559c6bb56/sf/man/geos_combine.Rd:33: file link âgUnionâ in package ârgeosâ does not exist and so has been treated as a topic
    geos_measures                           html
    geos_query                              html
    geos_unary                              html
    internal                                html
    is_driver_available                     html
    is_driver_can                           html
    is_geometry_column                      html
    merge.sf                                html
    nc                                      html
    plot                                    html
Rd warning: /tmp/RtmpjegcSq/R.INSTALL641559c6bb56/sf/man/plot.Rd:159: file link ârainbowâ in package âgrDevicesâ does not exist and so has been treated as a topic
    prefix_map                              html
    rawToHex                                html
    reexports                               html
Rd warning: /tmp/RtmpjegcSq/R.INSTALL641559c6bb56/sf/man/reexports.Rd:14: file link â%>%â in package âmagrittrâ does not exist and so has been treated as a topic
    sf-defunct                              html
    sf                                      html
    sf_extSoftVersion                       html
    sf_project                              html
    sfc                                     html
    sgbp                                    html
    st                                      html
    st_agr                                  html
    st_as_binary                            html
    st_as_grob                              html
    st_as_sf                                html
    st_as_sfc                               html
    st_as_text                              html
    st_bbox                                 html
    st_cast                                 html
Rd warning: /tmp/RtmpjegcSq/R.INSTALL641559c6bb56/sf/man/st_cast.Rd:78: file link âaggregateâ in package âsfâ does not exist and so has been treated as a topic
Rd warning: /tmp/RtmpjegcSq/R.INSTALL641559c6bb56/sf/man/st_cast.Rd:78: file link âsummariseâ in package âsfâ does not exist and so has been treated as a topic
    st_cast_sfc_default                     html
    st_collection_extract                   html
    st_coordinates                          html
    st_crop                                 html
    st_crs                                  html
    st_drivers                              html
    st_geometry                             html
    st_geometry_type                        html
    st_graticule                            html
    st_interpolate_aw                       html
    st_is                                   html
    st_is_longlat                           html
    st_jitter                               html
    st_join                                 html
    st_layers                               html
    st_line_sample                          html
    st_m_range                              html
    st_make_grid                            html
    st_nearest_feature                      html
    st_nearest_points                       html
    st_normalize                            html
    st_precision                            html
    st_read                                 html
    st_relate                               html
    st_sample                               html
    st_shift_longitude                      html
Rd warning: /tmp/RtmpjegcSq/R.INSTALL641559c6bb56/sf/man/st_shift_longitude.Rd:26: file link ârecenterâ in package âspâ does not exist and so has been treated as a topic
    st_transform                            html
    st_viewport                             html
    st_write                                html
    finding level-2 HTML links ... done

    st_z_range                              html
    st_zm                                   html
    stars                                   html
    summary.sfc                             html
    tibble                                  html
    tidyverse                               html
    transform.sf                            html
    valid                                   html
    vctrs                                   html
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for âsfâ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/R/3.6.1/lib/R/library/00LOCK-sf/00new/sf/libs/sf.so':
  /opt/R/3.6.1/lib/R/library/00LOCK-sf/00new/sf/libs/sf.so: undefined symbol: pj_get_ellps_ref
Error: loading failed
Execution halted
ERROR: loading failed
* removing â/opt/R/3.6.1/lib/R/library/sfâ

The downloaded source packages are in
        â/tmp/RtmpYm5LQl/downloaded_packagesâ
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("sf") :
  installation of package âsfâ had non-zero exit status

**Comment by rsbivand** [comment]
You must upgrade PROJ. Grepping for the function in the 4.8.0 source, I see:

```
$ grep pj_get_ellps_ref *.[ch]
cs2cs.c:                    for (le = pj_get_ellps_ref(); le->id ; ++le)
geod.c:                                    for (le=pj_get_ellps_ref(); le->id ; ++le)
pj_ellps.c:struct PJ_ELLPS *pj_get_ellps_ref()
proj.c:                    for (le = pj_get_ellps_ref(); le->id ; ++le)
projects.h:struct PJ_ELLPS *pj_get_ellps_ref( void );
```
so it is not in `proj_api.h`. PROJ 4.8.0 is not usable any more, current PROJ is 7.0.0. It is also possible that you have multiple PROJ installed, you need to handle that too - there should only be one od GDAL, PROJ and GEOS, and GDAL should be built against those unique PROJ and GEOS.

**Comment by edzer** [comment]
I've seen this problem most commonly when there are multiple versions of the system dependencies present on your system.
