### ISSUE TITLE
conflicts with package RcppParallel/roll

### ISSUE THREAD

**Issue by earthcli** [r-spatial/sf#1392]
I am working on a windows x64 platform. The sf package could not be loaded succfully if the RcppParallel is first loaded. While if sf is first loaded, RcppParallel as well as the depended package such as roll would not work. This is related to the tbb.dll the gdal is depended on.

require(RcppParallel)
require(sf)
1: package ‘sf’ was built under R version 3.6.3 
2: In CPL_gdal_init() :
  GDAL Error 1: Can't load requested DLL: G:\OSGeo4W64\bin\gdalplugins\gdal_MG4Lidar.dll
.......

Thers is more than one GDAL driver installed in my computer. Loading with the the order above, the sf package start to search dll for gdal in my system environment not in the sf package.

Would you please check this problem, and give me a suggestion about how to work with these packages together. 
Thanks.

**Comment by edzer** [comment]
Did you install sf as binary or from source? I would try reinstalling it, binary, not from source.

**Comment by earthcli** [comment]
I installed it from Rstudio, binary.

**Comment by edzer** [comment]
> 1: package ‘sf’ was built under R version 3.6.3

did you try R 4.0 with sf and RcppParallel compiled for 4.0?

**Comment by earthcli** [comment]
Sorry, currently I do no want to move to R 4.0, because it will take much time to check all my packages, I have not prepared well to do so.
Maybe I would use a older version of sf temporary. I am also working with osge4w and Qgis, the gdal driver did have brought me much trouble. The new version of sf including  a gdal3.0 driver is great, I am looking forward to try it, Thanks for your efforts.

**Comment by edzer** [comment]
The advice, then, is to install binary.
