### ISSUE TITLE
Issue installing sf on Centos 7 without root access

### ISSUE THREAD

**Issue by JingjingSherryWu** [r-spatial/sf#1397]
Hello,

I used conda to create a virtual environment to install gdal 3.0.4 through conda forge on my local directory. I have made sure that conda forge override the default channel to avoid conflict of versions. proj 7.0.0 is default associated with gdal, but I also tried installing proj 6.1.1 instead, got the same following error. I did modify LD_LIBRARY_PATH to include my local lib. Could you please advise how to solve the problem? Thank you very much!

I did search for possible solutions but without much success.

#obviously I tried to put everything in configure.args...
install_github("r-spatial/sf", configure.args = "--with-proj-lib=/home/jw394/pkgs/lib --with-proj-include=/home/jw394/pkgs/include/proj --with-proj-share=/home/jwDownloading GitHub repo r-spatial/sf@mastere/jw394/pkgs/bin/gdal-config --with-gdal-share=/home/jw394/pkgs/share/gdal")

#Here is the output
✔  checking for file ‘/tmp/Rtmp3QsS4T/remotes940126eecb61/r-spatial-sf-83180aa/DESCRIPTION’ (341ms)
─  preparing ‘sf’:
✔  checking DESCRIPTION meta-information ... OK
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘sf_0.9-3.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'

Installing package into ‘/home/jw394/R-3.6.1/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘sf’ ...
** using staged installation
configure: WARNING: unrecognized options: --with-gdal-share
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
configure: gdal-config set to /home/jw394/pkgs/bin/gdal-config
checking gdal-config exists... yes
checking gdal-config executable... yes
checking gdal-config usability... yes
configure: GDAL: 3.0.1
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... yes
checking GDAL: /home/jw394/pkgs/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... ./gdal_proj: symbol lookup error: /home/jw394/pkgs/lib/libgdal.so.26: undefined symbol: TIFFReadRGBATileExt
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
ERROR: configuration failed for package ‘sf’
* removing ‘/home/jw394/R-3.6.1/library/sf’
Error: Failed to install 'sf' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp3QsS4T/file94011933e34d/sf_0.9-3.tar.gz’ had non-zero exit status

**Comment by edzer** [comment]
Maybe this: https://github.com/r-spatial/sf#multiple-gdal-geos-andor-proj-versions-on-your-system

**Comment by kzxkzx** [comment]
Have you solved the problem of installing sf on Centos7

**Comment by edzer** [comment]
Could you check whether the problem is still there, with sf from GH/master? https://github.com/r-spatial/sf/commit/72ac142a9f0409edc5ebe355ece4cdbc8ae11569 may have helped.

**Comment by JingjingSherryWu** [comment]
Our IT with root access helped me. I could not figure it out myself.
