### ISSUE TITLE
cannot install the package

### ISSUE THREAD

**Issue by Sebastian-Suppa** [r-spatial/sf#1399]
> install.packages("/tmp/RtmprF9R27/downloaded_packages/sf_0.9-3.tar.gz", repos = NULL, type = "source")
Installing package into ‘/home/octavio/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/octavio/R/x86_64-pc-linux-gnu-library/4.0/sf’
Warning in install.packages :
  installation of package ‘/tmp/RtmprF9R27/downloaded_packages/sf_0.9-3.tar.gz’ had non-zero exit stat

**Comment by edzer** [comment]
The error you see indicates that you didn't set up GDAL properly; see the README of this repo for instructions.

**Comment by wolfQK** [comment]
I removed sf_0.7.6 from my system, and I want to update sf (using updatepackages("sf") cannot update it successfully). I tried sf_0.7-2, sf_0.9-2 and sf_0.9-3, they all reported the same errors as below: my R version is 3.6.1, and system is CentOS.6.9
> install.packages("sf")
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/sf_0.9-3.tar.gz'
Content type 'application/x-gzip' length 8483731 bytes (8.1 MB)
==================================================
downloaded 8.1 MB
* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: cc
configure: CXX:
checking for gdal-config... /zfssz2/ST_MCHRI/COHORT/zhongjixing/software/miniconda3/bin//gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.4.2
checking GDAL version >= 2.0.1... yes
checking for gcc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
./configure: line 3474: -I/zf/software/miniconda3/include: No such file or directory
./configure: line 3489: -I/zf/software/miniconda3/include: No such file or directory
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘sf’
* removing ‘/zfssz2/ST_MCHRI/COHORT/zhongjixing/software/miniconda3/lib/R/library/sf’
The downloaded source packages are in
        ‘/tmp/RtmpUeUvQj/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("sf") :
  installation of package ‘sf’ had non-zero exit status

**The directory "/zf/software/miniconda3/include" is acturally exist !**

**Comment by wolfQK** [comment]
I removed sf_0.7.6 from my system, and I want to update sf (using updatepackages("sf") cannot update it successfully). I tried sf_0.7-2, sf_0.9-2 and sf_0.9-3, they all reported the same errors as below: my R version is 3.6.1, and system is CentOS.6.9

install.packages("sf")
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/sf_0.9-3.tar.gz'
Content type 'application/x-gzip' length 8483731 bytes (8.1 MB)
==================================================
downloaded 8.1 MB

installing source package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: cc
configure: CXX:
checking for gdal-config... /zf/software/miniconda3/bin//gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.4.2
checking GDAL version >= 2.0.1... yes
checking for gcc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
./configure: line 3474: -I/zf/software/miniconda3/include: No such file or directory
./configure: line 3489: -I/zf/software/miniconda3/include: No such file or directory
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘sf’
removing ‘/zf/software/miniconda3/lib/R/library/sf’
The downloaded source packages are in
‘/tmp/RtmpUeUvQj/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("sf") :
installation of package ‘sf’ had non-zero exit status
**The directory "/zf/software/miniconda3/include" is acturally exist !**

**Comment by edzer** [comment]
I'm sorry, but can't offer help with conda installs; please get in touch with the R/conda maintainers.
