### ISSUE TITLE
Missing values and XYZ dimension

### ISSUE THREAD

**Issue by lionel-** [r-spatial/sf#1400]
With an XYZ dimension there is an issue when expanding with missing indices:

```r
xyz <- sf::st_linestring(matrix(1:9, ncol = 3))
xyz_sfc <- sf::st_sfc(xyz, xyz)

xyz_sfc[c(NA, 1:2, NA)]
#> Error in CPL_get_z_range(obj, 1) : z error - expecting three columns;

sf::st_sfc(xyz, NA)
#> Error in CPL_get_z_range(obj, 1) : z error - expecting three columns;
```

It works as expected with XY dimension:

```r
xy <- sf::st_linestring(matrix(1:8, ncol = 2))
xy_sfc <- sf::st_sfc(xy, xy)

xy_sfc[c(NA, 1:2, NA)]
#> Geometry set for 4 features  (with 2 geometries empty)
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
#> CRS:            NA
#> LINESTRING EMPTY
#> LINESTRING (1 5, 2 6, 3 7, 4 8)
#> LINESTRING (1 5, 2 6, 3 7, 4 8)
#> LINESTRING EMPTY

sf::st_sfc(xy, NA)
#> Geometry set for 2 features  (with 1 geometry empty)
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 5 xmax: 4 ymax: 8
#> CRS:            NA
#> LINESTRING (1 5, 2 6, 3 7, 4 8)
#> LINESTRING EMPTY
```

`NA` expansion is important for tidyverse support because we have started using a combination of `c()` and `[` in vctrs to support foreign classes that don't implement vctrs methods. When columns are combined with missing chunks (this happens when the data frames are disjoint), we first combine the non-missing chunks with `c()` and then expand the missing ones with `[`.

**Comment by edzer** [comment]
Thanks! Yes, that was sloppy. We now have these fixed. I went into looking at even further edge cases, and don't understand why
```r
(e = st_sfc(st_linestring(matrix(numeric(0), 0, 3), dim = "XYZ")))
# Geometry set for 1 feature  (with 1 geometry empty)
# geometry type:  LINESTRING
# dimension:      XYZ
# bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
# z_range:        zmin: NA zmax: NA
# CRS:            NA
# LINESTRING Z EMPTY
e[c(NA,NA)]
# Geometry set for 2 features  (with 2 geometries empty)
# geometry type:  GEOMETRY
# dimension:      XYZ
# bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
# z_range:        zmin: NA zmax: NA
# CRS:            NA
# GEOMETRYCOLLECTION Z EMPTY
# GEOMETRYCOLLECTION Z EMPTY
st_sf(e)
# Simple feature collection with 1 feature and 0 fields (with 1 geometry empty)
# geometry type:  LINESTRING
# dimension:      XYZ
# bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
# z_range:        zmin: NA zmax: NA
# CRS:            NA
#                    e
# 1 LINESTRING Z EMPTY
st_sf(e[c(NA,NA)])
# Simple feature collection with 2 features and 0 fields (with 2 geometries empty)
# geometry type:  GEOMETRY
# dimension:      XYZ
# bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
# z_range:        zmin: NA zmax: NA
# CRS:            NA
#                 e.c.NA..NA..
# 1 GEOMETRYCOLLECTION Z EMPTY
# 2 GEOMETRYCOLLECTION Z EMPTY
library(dplyr)
bind_rows(st_sf(e), st_sf(e[c(NA,NA)]))
# Error in st_sfc(x, crs = st_crs(to), precision = st_precision(to)) : 
#   found multiple dimensions: XYZ XY
# Calls: bind_rows ... vec_rbind -> vec_restore_dispatch -> vec_restore.sfc -> st_sfc
# Execution halted
```
but I won't have sleepless nights if this doesn't work.

<details>

```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.99.9002 sf_0.9-4         

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       class_7.3-17       crayon_1.3.4       grid_4.0.0        
 [5] R6_2.4.1           lifecycle_0.2.0    DBI_1.1.0          magrittr_1.5      
 [9] e1071_1.7-3        units_0.6-6        pillar_1.4.4       KernSmooth_2.23-17
[13] rlang_0.4.6        ellipsis_0.3.0     vctrs_0.3.0        generics_0.0.2    
[17] tools_4.0.0        glue_1.4.1         purrr_0.3.4        compiler_4.0.0    
[21] pkgconfig_2.0.3    classInt_0.4-3     tidyselect_1.1.0   tibble_3.0.1      

```

</details>

It looks like `bind_rows` and `bind_cols` now no longer return `sf` objects when given `sf` objects, is that correct? If so, is it a documented change, or can we fix this with `vctrs` methods on the `sf` object level?

**Comment by lionel-** [comment]
With dev vctrs this seems to work:

```r
bind_rows(st_sf(x = e), st_sf(y = e[c(NA,NA)]))
#>                    x                        y
#> 1 LINESTRING Z EMPTY GEOMETRYCOLLECTION EMPTY
#> 2   LINESTRING EMPTY GEOMETRYCOLLECTION EMPTY
#> 3   LINESTRING EMPTY GEOMETRYCOLLECTION EMPTY
```

Note that CRAN vctrs still uses the vctrs methods for sfc lists. Dev vctrs no longer uses them, and falls back to `c()` and `[` instead. The sf methods should have stopped working in the last version because we disabled inheritance of coercion methods, but we special-cased them for compatibility. Now I am working on improving the fallbacks to base methods for foreign classes, and I have disabled the special-casing. Once this is all done, I'll follow up with a PR for sf to remove the methods that are no longer needed for tidyverse support.

> It looks like bind_rows and bind_cols now no longer return sf objects when given sf objects, is that correct? If so, is it a documented change, or can we fix this with vctrs methods on the sf object level?

Three ways to fix it:

1. Implement vctrs methods, but for `bind_cols()` this will be problematic because the sf class doesn't support zero-cols data frames. 

2. Implement `dplyr_reconstruct()`. The reconstruct generics in dplyr and tidyr are stopgaps that we have added because data frame genericity is very hard.

3. We're planning to fall back to `base::rbind()` methods. This is tracked in r-lib/vctrs#1117.

I think you'll need (2) in any case, to be safe. I'll look into it next week.

**Comment by edzer** [comment]
@dcooley FIY I also fixed the z and m computation parts similarly to how it's done for X/Y
