### ISSUE TITLE
integration of FlatGeobuf format

### ISSUE THREAD

**Issue by ervanSTRI** [r-spatial/sf#1402]
Is there yet any chance to write/convert sf objects into .fgb format?
Thanks
E

**Comment by edzer** [comment]
Have you tried (after compiling sf to GDAL 3.1)?

**Comment by tim-salabim** [comment]
I have GDAL 3.1.0 on my linux box and it works like a charm. The only thing that is not supported is guessing of the driver from the .fgb fileextension.

**Comment by ervanSTRI** [comment]
No. Sorry. I am still with GDAL 3.0.4. Will upgrade to 3.1.
Thanks for your prompt reply! Best

**Comment by tim-salabim** [comment]
Thanks @edzer !
