### ISSUE TITLE
Line to Curve

### ISSUE THREAD

**Issue by arielfuentes** [r-spatial/sf#1406]
Is it possible to include a function to convert a linestring to a circularstring? Something like the postgis function **ST_LineToCurve**.  [postgis manual] (https://postgis.net/docs/manual-1.4/ST_LineToCurve.html)

This is especially important to do Origin-Destination flows.

**Comment by edzer** [comment]
If something is in PostGIS, the code is usually in their liblwgeom, and that code is again wrapped in package lwgeom. I gave it a quick look and couldn't find it. Any pointers where to find it would be helpful.

**Comment by arielfuentes** [comment]
I have a lack of knowledge, the first time I hear about it. 
But searching I guess it is something like **lwcircstring_from_lwmpoint** which would need a double transformation. [](https://github.com/postgis/postgis/blob/master/liblwgeom/lwcircstring.c)
[](https://www.postgis.net/docs/doxygen/2.4/d8/df2/lwcircstring_8c_a55f0fed94a837d85f3a6d41c1ba255ab.html#a55f0fed94a837d85f3a6d41c1ba255ab)

Also, I'm seeing that gdal have something that could do the transformation **curveFromLineString()** 
[](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrlinestring.cpp)

I hope this helps.

**Comment by edzer** [comment]
Sure, it just needs someone willing to implement it! ;-)
