### ISSUE TITLE
Create multipolygon "footprint" around boundary of multi-part raster?

### ISSUE THREAD

**Issue by markyxe** [r-spatial/sf#1410]
Hello, I'd like to make a multipolygon "footprint" around the boundary of a multi-part raster. I'm not looking to make a bounding box, as that would be much bigger than the extent of the NODATA pixels in the raster. Is there a function in sf (or another package) for this? Many thanks! Mark

**Comment by rgzn** [comment]
`sf` does not handle raster data. These are not comprehensive answers but they will point you in the right direction:

If you would like to stay within the R-Spatial system, this can be done with `stars`. Using `dplyr` verbs with a `stars` object you can select only valid pixels, and then using `st_as_sf` you can convert those pixels to a `sf` polygon.

If you want more general open-source tools, the underlying libraries behind `sf` and `stars` are available using GDAL. You can use GDAL tools to do this, as outlined here:
```
gdalwarp -dstnodata 0 -dstalpha -of GTiff foo1 foo2
gdal_polygonize.py foo2 -b 2 -f "ESRI Shapefile" foo3
```
source: https://gis.stackexchange.com/questions/61512/calculating-image-boundary-footprint-of-satellite-images-using-open-source-too
