### ISSUE TITLE
Error in CPL_geos_op2(op, st_geometry(x), st_geometry(y)) : Evaluation error: std::bad_alloc.

### ISSUE THREAD

**Issue by CobbyNewton** [r-spatial/sf#1411]
Hello,
Let me apologize in advance in case I unknowingly flout the rules here. This is my very first time raising an issue here and I tried to look up help on previously resolved issues but I am not sure they addressed mine. Of course I am beginner when it comes to coding (in R).

I have data set of about 3400 location points with which I am trying to generate data of each point and their neighbors within defined radii (eg, 0.25, 1, and 3 miles). 

The data has the following form:

```r
> head(Pointsdata)
    ID        lon        lat  pop_size
1 ID_1 -10.051100  18.441917  675.3872
2 ID_2   5.394999   4.148627 1472.2674
3 ID_3   1.306370  15.794475  137.6444
4 ID_4   5.910318  -6.438676 1380.2332
5 ID_5   9.355191 -10.118736  513.3624
6 ID_6  -4.804669  -7.762536  212.9331
```

I got help putting together the following code which gives me what I want if run on a small sample of my data (just about 1000 points).

```r
library(sf) 
library(dplyr)
library(ggplot2)
library(stringr) 
library(rgdal) 
library(lwgeom) 
library(sp)
#library (bigmemory)
#library (biganalytics)

#load raw data
Mydata <- read.csv("Pointsdata.csv")

#attach(Mydata)

#Transform and project to required UTM
projdata <- st_as_sf(Mydata,coords = c("lon", "lat"), crs = 4326) %>% st_transform(26913)


bufferR <- c(402.336, 1609.34, 3218.69, 4828.03, 6437.38) # sequence of radii in miles??

#Create data of neighboring wells per buffer

dataout <- do.call("rbind", lapply(1:length(bufferR), function(y) {
    bfr <- projdata %>% st_buffer(bufferR[y]) ## create Buffer
    ## minus the next smaller buffer
    if(y>1) {
      inters <- suppressWarnings(st_difference(bfr, projdata %>% st_buffer(bufferR[y-1])))    
      bfr <- inters[which(inters$ID == inters$ID.1),]
    }

    # get ids that intersect with buffer

    inters <- bfr %>% st_intersects(projdata) 


    do.call("rbind", lapply(which(sapply(inters, length)>0), 
         function(z) data.frame(orig = projdata[z,]$ID, radius = bufferR[y],
                incl = projdata[unlist(inters[z]),]$ID, 
                pop_size_mtchd = projdata[unlist(inters[z]),]$pop_size)))
}))
```
 However, when I run it on all or even just above 1000 sample points, I get this error:

```Error in CPL_geos_op2(op, st_geometry(x), st_geometry(y)) : Evaluation error: std::bad_alloc.```

From my search, it appears this is pointing to a memory issue. But I am not sure as I have a 16GB memory.

```>
 memory.limit()
[1] 16257
```
My session info is :

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lwgeom_0.2-1  rgdal_1.4-8   stringr_1.4.0 ggplot2_3.3.0 dplyr_0.8.5  
[6] raster_3.0-12 sp_1.4-0      sf_0.9-0     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4         pillar_1.4.3       compiler_3.6.3     class_7.3-15      
 [5] tools_3.6.3        lifecycle_0.2.0    tibble_3.0.0       gtable_0.3.0      
 [9] lattice_0.20-38    pkgconfig_2.0.3    rlang_0.4.5        DBI_1.0.0         
[13] cli_2.0.2          e1071_1.7-3        withr_2.1.2        vctrs_0.2.4       
[17] classInt_0.4-2     grid_3.6.3         tidyselect_0.2.5   glue_1.3.2        
[21] R6_2.4.1           fansi_0.4.1        purrr_0.3.3        magrittr_1.5      
[25] scales_1.0.0       codetools_0.2-16   ellipsis_0.3.0     units_0.6-6       
[29] assertthat_0.2.1   colorspace_1.4-1   KernSmooth_2.23-16 stringi_1.4.6     
[33] munsell_0.5.0      crayon_1.3.4    
```
I will appreciate so much I someone can help me resolve this.
Thanks for any support.

**Comment by etiennebr** [comment]
I would replace `st_buffer` with `st_is_within_distance`. It is more accurate and requires less memory. Run `st_is_within_distance` for every radius you have, this will give you `TRUE` and `FALSE`; then you can test combinations without the need for `st_difference` and `st_intersect` (e.g. within 1609.34, but not within 402.336).

Related to #976.

**Comment by edzer** [comment]
Hi @CobbyNewton , I would be happy to look into this, but would need a reproducible example: right now this only runs with data that only you have.

**Comment by CobbyNewton** [comment]
Hello @edzer,  I have below a sample of my data (about 1000 points).
It is an Rdata file.
[Pointsdata_sub.zip](https://github.com/r-spatial/sf/files/4708216/Pointsdata_sub.zip)

Hope this helps. 

@etiennebr , thanks for your suggestion. I would like to explore it as well. What I am not sure of is how to fully implement the test combinations and arrive at the data table the current code gives me.

**Comment by edzer** [comment]
This ran for me without problems, but had a memory footprint of over 8 Gb. Maybe you need to rethink your approach as @etiennebr suggested?
```r
> head(dataout)
     orig  radius    incl pop_size_mtchd
1 2105618 402.336 2105618          406.9
2 2706186 402.336 2706186          115.2
3 2706185 402.336 2706185          107.5
4 2705082 402.336 2705082          106.7
5 2706190 402.336 2706190          104.4
6 2705571 402.336 2705571          103.7
> dim(dataout)
[1] 62318     4
```

**Comment by CobbyNewton** [comment]
@edzer, yes, this is about the size of the data that runs for me too. Once I run from a 1000 and above, the error pops up. Would you want to try with the full data set? I could upload as well.

@etiennebr, are you able to help me out on how to fuse your suggestion with the current code I have and still come up with the dataframe in ```dataout```?

**Comment by edzer** [comment]
I can imagine it does. I think @etiennebr 's suggestion was right, given your terse description of the problem. The code you provide is hard to read, and I don't think you can expect someone here to rewrite it for you.

**Comment by CobbyNewton** [comment]
@edzer, I am sorry if my code is not clear enough, probably a confirmation of my being a novice in this area. I am definitely trying to explore @etiennebr 's suggestion. In the meantime, I thought I should explain a bit more the problem I am trying to solve in case it is helpful in anyway.

What I essentially seek to achieve is the output in ```dataout```.  

Given the structure of my ```Pointsdata``` as attached above, I want to create multi-ring buffers (of 402.336, 1609.34, 3218.69, 4828.03, and 6437.38 meters radius ) around each point. 

The end goal is that for each (original) point with ```ID```s , now named ```orig``` in ```dataout```, I want its neighboring points within the specified ```radius```  listed under ```incl```  in a long format. The caveat is that for the very first (ie. the smallest) radius 402.336, ```incl``` should return neighboring points within in that distance. But for subsequent radii, ```incl``` should return neighboring points within them but not within the smaller radius. Thus for example, for radius 1609.34m, I should get as neighboring points, points within 1609.34m but not within the smaller buffer/radius 402.336m.  

The last column ```pop_size_mtchd``` is the associated attribute ```pop_size``` of  the points with IDs under ```incl```-- ie. the ```pop_size``` of neighboring points ```incl``` for each ```radius```.

**Comment by edzer** [comment]
Buffers are expensive to compute and for your problem you don't need them. What you are looking for is help with your problem, which you got here. This place is however meant for issues with the software package `sf`, which I haven't seen in this case, and that's why I'm closing now.

**Comment by rsbivand** [comment]
Please consider using R-sig-geo as a more suitable channel after
subscribing https://stat.ethz.ch/mailman/listinfo/R-SIG-Geo,  and
confirming subscription. Provide a reprex with built-in data, say using the
house data set in spData.

Roger Bivand
Falsensvei 32
5063 Bergen

man. 1. jun. 2020, 21:48 skrev CobbyNewton <notifications@github.com>:
