### ISSUE TITLE
how to turn off strings as factors in sf -> data.frame conversion for R< 4.0.0

### ISSUE THREAD

**Issue by lorenzwalthert** [r-spatial/sf#1422]
Is there a way to tell {sf} not to convert my strings to factors? I assume this is only a problem for R < 4.0.0

First, just creating an sf object:
``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
pt1 = st_point(c(0,1))
pt2 = st_point(c(1,1))
st_sfc(pt1, pt2)
#> Geometry set for 2 features 
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 0 ymin: 1 xmax: 1 ymax: 1
#> CRS:            NA
#> POINT (0 1)
#> POINT (1 1)
d = data.frame(a = 1:2, string = "a")
d$geom = st_sfc(pt1, pt2)
df = st_as_sf(d)
```

Here's the unexpected
```r
df <- st_drop_geometry(df)
#st_geometry(df) <- NULL # same result
class(d$string)
#> [1] "factor"
```
<sup>Created on 2020-06-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
`data.frame()` has an argument `stringsAsFactors` which you can set to `FALSE`.

**Comment by lorenzwalthert** [comment]
Sorry for wasting your time I made a mistake in my thinking, of course I just have to create it as a string column in the first place, which I did not in my original code because I had `st_sf(..., stringsAsFactors = default.stringsAsFactors()`, so the problem was not the conversion back to a data frame but the creation in the first place.
