### ISSUE TITLE
crs documentation

### ISSUE THREAD

**Issue by dcooley** [r-spatial/sf#1423]
The documentation for `crs` still references EPSG and proj4string

https://github.com/r-spatial/sf/blob/master/R/sf.R#L193

> #' @param crs coordinate reference system: integer with the EPSG code, or character with proj4string

suggested update something like

> #' @param crs coordinate reference system: list with two components, input and wkt

**Comment by edzer** [comment]
Thanks! Your suggestion will not work; it has to be something that can be accepted as input to `st_crs()`.
