### ISSUE TITLE
st_relate works with sf_0.9-2 an dplyr_0.8.5 BUT not with sf_0.9-4 an dplyr_1.0.0

### ISSUE THREAD

**Issue by birdMig** [r-spatial/sf#1424]
Hi, I am assuming this is sf related, but could be dplyr or something else?

Using R 4.0.0, sf_0.9-2 an dplyr_0.8.5 this works:
```
library(sf)
library(dplyr)

demo(nc, ask = FALSE, verbose = FALSE)

st_rook = function(a, b = a) st_relate(a, b, pattern = "F***1****")

nb <- nc %>% mutate(NB_ROOK = st_rook(.))
```

BUT, using R 4.0.0, sf_0.9-4 an dplyr_1.0.0, the same exact code results in the following error:

Error: Problem with `mutate()` input `NB_ROOK`.
x Input `NB_ROOK` must be a vector, not a `sgbp` object.
i Input `NB_ROOK` is `st_rook(.)`.

Any ideas of why and how could this be solved?

Thanks

**Comment by edzer** [comment]
Thanks! This fixes it; with existing `sf` you can also use
```
st_rook = function(a, b = a) unclass(st_relate(a, b, pattern = "F***1****"))
```
to make things work.

**Comment by birdMig** [comment]
Great stuff! Thanks for your v quick reply!
