### ISSUE TITLE
st_write doesn't write srid / geometry type metadata in postgis 'geometry_columns'

### ISSUE THREAD

**Issue by eblondel** [r-spatial/sf#1429]
Dear @edzer ,

I'm trying to use ``st_write`` with a Postgres/postgis database 

```R
require("sp")
data(meuse)
pts <- st_as_sf(meuse, coords = c("x", "y"), crs = 28992)
pts_4326 <- st_transform(pts, crs = 4326) 
st_write(pts_4326, con, layer = "sf_meuse", layer_options = 'OVERWRITE=YES')
```

The data import into the new table ``sf_meuse`` works, but the metadata inserted in ``geometry_columns`` is not accurate for:
* srid: it is set to 0 instead of the srid we have for the sf object
* type: it is set to GEOMETRY (here I'd expect POINT)
FYI, this metadata has then side effect on how data is exposed through geographic servers (eg GeoServer) that rely on these metadata to properly interface postgis datastore.

I've tested this with other datasets in other crs/geometry types, and I get always the same in ``geometry_columns`` (srid=0, type=GEOMETRY)

Is it a limitation of ``st_write``? or GDAL driver?
Any advice to get rid of this issue?

Thanks a lot in advance for your support

_______

Characteristics of the environment 

* PostgreSQL 11.7 (Ubuntu 11.7-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

* POSTGIS="2.5.3 r17699" [EXTENSION] PGSQL="110" GEOS="3.7.1-CAPI-1.11.1 27a5e771" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.3, released 2017/11/20" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" RASTER

* R environment:

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)

*  sf version = 0.9-3

**Comment by edzer** [comment]
What is `con`?

**Comment by eblondel** [comment]
My DBI connection object to Postgres (sorry i missed to say that)

**Comment by eblondel** [comment]
Hum, we still use RPostgreSQL::PostgreSQL() driver . I see you use a different one for your tests, could it be this?

**Comment by edzer** [comment]
Ah, ok, yes please try with RPostgres before I ask @etiennebr to look at this. You may also want to try the GDAL PostGIS driver as an alternative.

**Comment by eblondel** [comment]
Tested with RPostgres::Postgres() driver, I get the same issue.

**Comment by etiennebr** [comment]
Thanks, I'll look into it! My initial thought is that most of the trouble comes from the (old) GDAL and Postgis version on the database.  Could you share your `sf::sf_extSoftVersion()`?

Also, to force the `POINT` type (or any other type than `GEOMETRY`) you need to do it explicitly either by `ALTER` ing your column or creating the table before writing. This is not very convenient, and I hope to better support specific geometry column types when I get to work on it, in a few weeks.

**Comment by eblondel** [comment]
This is the result of ``sf::sf_extSoftVersion() ``:

         GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.8.0"        "3.0.4"        "6.3.1"         "true" 
    USE_PROJ_H 
        "true"

**Comment by eblondel** [comment]
Sorry this is wrong, that's my local environment, i should check further since the DB I operate on is not local. I will give a try on a local database with the above environment and let you know.

**Comment by etiennebr** [comment]
Thanks, it's fine. I wanted to know what version your client was running. You already provided the database info in your original post.

**Comment by eblondel** [comment]
In case it helps, I've tried on local db and it didn't work.

Local environment:
* Postgres version: PostgreSQL 9.6.17, compiled by Visual C++ build 1800, 64-bit
* Postgis: POSTGIS="2.5.3 r17699" [EXTENSION] PGSQL="96" GEOS="3.7.2-CAPI-1.11.0 3.7.2" SFCGAL="1.3.2" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.4, released 2018/03/19" LIBXML="2.7.8" LIBJSON="0.12" LIBPROTOBUF="1.2.1" TOPOLOGY RASTER
* On R sf::sf_extSoftVersion():
     GEOS           GDAL         proj.4 GDAL_with_GEOS  USE_PROJ_H
   "3.8.0"        "3.0.4"             "6.3.1"               "true"        "true"

**Comment by etiennebr** [comment]
If you can run a docker container locally, you could try to run your example with the latest postgis version (it should work). 

Start the container
``` bash
docker run -p 25432:5432 -d -t kartoza/postgis:latest
```
Then connect with R
```R
con <- dbConnect(
	RPostgres::Postgres(),
	host = "localhost",
	port = 25432,
	dbname = "gis",
	user = "docker",
	password = "docker"
)
```
We don't test `sf` against postgis 2.5 anymore, because of all the changes in handling the projections, but maybe we should :thinking:.

**Comment by eblondel** [comment]
@etiennebr I tried using the docker above. I get the same issue. Here is the result of ``geometry_columns`` after inserting test data:


```
  f_table_catalog f_table_schema f_table_name f_geometry_column coord_dimension srid     type
1             gis         public     sf_meuse          geometry               2    0 GEOMETRY
```

**Comment by etiennebr** [comment]
That's expected. You should still see that the srid is `4326` for each geometry.
``` sql
select st_srid(geometry) from sf_meuse limit 1;
--  st_srid
-- ---------
--    4326
```

The reason is that we use a "generic" `GEOMETRY` type which does not enforce the SRID, so unlike `sf`, each geometry could have a different `srid`. In that case, the `geometry_column` view shows an undefined SRID (0). For that reason, you need to check the geometry SRID. 

When you read it back to `sf`, it should still give a `crs`, `EPSG:4326`.
``` r
st_read(con, "sf_meuse") %>% st_crs()
#> Coordinate Reference System:
#>   User input: EPSG:4326
#>   wkt:
#> GEOGCRS["WGS 84",
#>     DATUM["World Geodetic System 1984",
#>         ELLIPSOID["WGS 84",6378137,298.257223563,
#>             LENGTHUNIT["metre",1]]],
#>     PRIMEM["Greenwich",0,
#>         ANGLEUNIT["degree",0.0174532925199433]],
#>     CS[ellipsoidal,2],
#>         AXIS["geodetic latitude (Lat)",north,
#>             ORDER[1],
#>             ANGLEUNIT["degree",0.0174532925199433]],
#>         AXIS["geodetic longitude (Lon)",east,
#>             ORDER[2],
#>             ANGLEUNIT["degree",0.0174532925199433]],
#>     USAGE[
#>         SCOPE["unknown"],
#>         AREA["World"],
#>         BBOX[-90,-180,90,180]],
#>     ID["EPSG",4326]]
```

If you want to do force it, you must alter your geometry column with:
``` sql
alter table sf_meuse alter column geometry type geometry(POINT, 4326);
```
Then
``` sql
table geometry_columns;
-- f_table_catalog | f_table_schema | f_table_name | f_geometry_column | coord_dimension | srid | type  
-- -----------------+----------------+--------------+-------------------+-----------------+------+-------
--  gis             | public         | sf_meuse     | geometry          |               2 | 4326 | POINT
```
Could you confirm it works in `postgis:latest` and then check with your server just to make sure the issue is still there?

**Comment by eblondel** [comment]
Got it, yes the last sql statement works. 

Indeed now I got your point, I thought that this should have been managed through st_write, but in fact as you say we may have different geometry srid within the same table. I was reasoning stating it was unique, with no mixing of srids, because this is what I use to manage from a web perspective (use PostGIS stores in OGC web geographic servers).
Now it's clear why you don't enforce the SRID in ``geometry_columns`` with sf st_write. I can stick with running the above SQL statement. Maybe it would be worth having this as option in ``st_write``?

Thanks for your help!

**Comment by etiennebr** [comment]
> Maybe it would be worth having this as option in st_write?

Absolutely! Do you want to close the issue, or do you still have problems with postgis 2.5?

**Comment by eblondel** [comment]
We can close, thanks a lot!
