### ISSUE TITLE
st_polygon(list(NULL)) gives inscrutable error

### ISSUE THREAD

**Issue by MichaelChirico** [r-spatial/sf#1440]
```
sf::st_polygon(list(NULL))
# Error in vapply(x, ncol, 0L) : values must be length 1,
#  but FUN(X[[1]]) result is length 0
```

This came up as the edge case to some dynamic code so I didn't recognize the issue right away.

Two options:

(1) check `all(vapply(x, is.matrix, NA))` first, & error informatively: element `n` is not a matrix
(2) use `vapply(x, NCOL, 0L)` which will return `0L` for the `NULL` input. Hopefully this errors later down the line more informatively (not yet tested)

Happy to file a PR, but no opinion really on which option is better.

**Comment by edzer** [comment]
`sf::st_polygon` works as documented. `st_polygon(list())` creates the `POLYGON EMPTY`. I don't see a need for more options.

**Comment by MichaelChirico** [comment]
Thanks @edzer, perhaps I should clarify this is a request for better / more informative error handling, rather than a request for change of behavior.

**Comment by edzer** [comment]
Ah, yes, sorry I misread. This should now do that (committed to s2 branch, soon to be merged):
```r
> sf::st_polygon(list(NULL))
Error in FUN(X[[i]], ...) : is.numeric(x) is not TRUE
```
