### ISSUE TITLE
Misleading error message in ./configure when sqlite3 not found.

### ISSUE THREAD

**Issue by barryrowlingson** [r-spatial/sf#1441]
I'm trying to compile from source with GDAL and PROJ and friends scattered around the system in various locations, and configure triggered this error message:

```
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
configure: error: libproj not found in standard or given locations.
ERROR: configuration failed for package 'sf'
```

The error message was wrong - the problem was `sqlite3` not being found - `libproj` was found correctly. Code line in configure is around line 3840 in version sf-0.9-4

I don't know if sqlite3 not being found is a problem with the configure script, most likely its my configuration, but when I took the `-lsqlite3` out of the test in the configure script it went through fine.

Maybe the sqlite3 and proj linking tests should be separate in configure.ac (line 426)?

**Comment by edzer** [comment]
Shall I make this 
```
configure: error: libproj and/or sqlite3 not found in standard or given locations.
```
?

**Comment by barryrowlingson** [comment]
that's the minimal effort on the part of the developer solution, yes :) Adding a separate test for sqlite3 would have narrowed down my search for the solution. I'm no expert with autoconf so I don't appreciate how hard that would be.

my reaction to seeing the error was thinking "oh, where were these standard and given locations that you looked?" and I edited the script to echo the compiler line....

**Comment by barryrowlingson** [comment]
Actually, commenting out `-lsqlite3` resulted in the package building successfully, so I'm not sure what the point of the test for it there is - either its not used in the rest of the package, or that test wasn't looking in the right place if it was used elsewhere...

**Comment by edzer** [comment]
I'm quite sure that you will be able to find a combination of GDAL and PROJ versions where the `-lsqlite3` is needed; feel free to add checks whether `-lsqlite3` is needed at all.

**Comment by rsbivand** [comment]
I don't think `-libsqlite3` is needed - I've removed it (and -ltiff and -lcurl) for **rgdal** without painnful consequences. The first is needed by PROJ 6, and in addition the others for PROJ 7, but in static builds they are included anyway, and in dynamic builds they must have been there as reverse dependencies of PROJ (they are all probable dependencies of GDAL too). I think the original issue (I haven't looked for which) was a misunderstanding, neither **sf** not **rgdal** use SQLite directly. They are all needed for static builds, though, so rgdal/configure.ac does add -lsqlite3 in proj_conf_test2 (and should maybe add tiff & curl). I added Brian Ripley's suggestion to modify proj.pc https://github.com/OSGeo/PROJ/issues/2084#issuecomment-642612602 to pick up the requirements automatically, but that will not work for non-pkg-config settings, or until that patch gets released.

**Comment by ice4prince** [comment]
Dear Contributor,

Grateful that you found the error of not finding sqlite3. However, may I ask how I can link sqlite3 and libproj when sqlite3 and dgal, proj.4 and geos are in separate dir? I was using this in terminal and all these are modules load. 

Thank you very much!
