### ISSUE TITLE
Error in trying to get Census data on a specific city within a county

### ISSUE THREAD

**Issue by spatiallyunaware** [r-spatial/sf#1442]
I'm getting an error message: Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet, : Opening layer failed.

I'm trying to get census data on San Diego County using tidycensus (which I've done successfully), but when I try to get it filtered down to San Diego City I get that error message. This used to work before in past projects so I don't understand what is wrong now.

Here's my code:
#Getting SD County Data
 San_Diego <- get_acs(geography = "tract", 
              year = 2018,
              variables = c(tpop = "B01003_001", tpopr = "B03002_001", 
                            nhwhite = "B03002_003", nhblk = "B03002_004",
                            nhasn = "B03002_006", hisp = "B03002_012", medincome= "B19013_001"), 
              state = "CA",
              county = "San Diego",
              survey = "acs5",
              geometry = TRUE) %>%
              select(-(moe)) %>%
              spread(key = variable, value = estimate) %>%
              mutate(pnhwhite = nhwhite/tpopr, pnhasn = nhasn/tpopr, 
        pnhblk = nhblk/tpopr, phisp = hisp/tpopr, oth = tpopr - (nhwhite+nhblk+nhasn+hisp), 
        poth = oth/tpopr, nonwhite = tpopr-nhwhite, pnonwhite = nonwhite/tpopr) %>%
              select(c(GEOID,tpop, tpopr, medincome, pnhwhite, pnhasn, pnhblk, phisp,
           nhwhite, nhasn, nhblk, hisp, nonwhite, pnonwhite, oth, poth))%>%
  filter(tpop != 0)

pl <- places(state = "CA", cb = TRUE, year=2018)
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet, : Opening layer failed.
#Getting SD City Data, here's where the error occurs ^^
cb <- core_based_statistical_areas(cb = TRUE, year=2018)
SD <- filter(cb, grepl("San Diego", NAME))
SD.city <- filter(pl, NAME == "San Diego")
SD.city.tracts <- ms_clip(target = San_Diego, clip = SD.city, remove_slivers = TRUE)

**Comment by rgzn** [comment]
It's hard to see which function call is returning this error. Are you sure this is from `sf`? It would be much easier to help if you generated this example with [`reprex`](https://reprex.tidyverse.org).

**Comment by edzer** [comment]
I think this is an issue with tidycensus, but as @rgzn said, your example is not reproducible.
