### ISSUE TITLE
st_crs returns different outputs in R version 3.6.1 vs 4.0.2

### ISSUE THREAD

**Issue by NathanWhitmore** [r-spatial/sf#1459]
I recently upgraded R from version 3.6.1. to 4.0.2. When I did -  I noticed that the output of the st_crs function changed from a tidy 2 line output with a EPSG and proj4 string output to a verbose output. 

Under 3.6.1 

    library(sf)
    library(tidyverse)
    library(rnaturalearth)

    world <- ne_countries(scale = "medium", returnclass = "sf")
    greenland <- world %>% filter(name == "Greenland")

    st_crs(greenland)

Returned:

Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +datum=WGS84 +no_defs"

by comparison under 4.0.2 I get:

Coordinate Reference System:
  User input: +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
  wkt:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]

Is this the behavior I should expect?

**Comment by edzer** [comment]
In the same action, you must have updated package `sf` as well; see https://www.r-spatial.org/r/2020/03/17/wkt.html

**Comment by rsbivand** [comment]
Please do read https://www.r-spatial.org/r/2020/03/17/wkt.html. This
transition has been discussed since 2017.

Roger Bivand
Falsensvei 32
5063 Bergen

fre. 31. jul. 2020, 06:49 skrev NathanWhitmore <notifications@github.com>:
