### ISSUE TITLE
sf, rgdal, and terra can't install after upgrading from gdal 3.0.4 to 3.1.2 on Ubuntu 20.04

### ISSUE THREAD

**Issue by GeraldCNelson** [r-spatial/sf#1463]
I have both a mac and a linux box. gdal on the mac is installed through home brew. gdal on the linux box has been installed both with the usual configure, make, make install and with sudo apt-get install gdal-bin. Both completed successfully and sudo apt-get install gdal-bin returns GDAL 3.1.2, released 2020/07/07.

When I attempt to install or upgrade sf, rgdal, or terra I get similar error messages. They come after
`** testing if installed package can be loaded from temporary location`

The messages are
```
free(): invalid size
Aborted (core dumped).
```

**Comment by edzer** [comment]
The most likely cause is that you have more than one installation of GDAL and/or PROJ on your system, one is found during compilation, the other during run time, and that causes the error. See [here](https://github.com/r-spatial/sf#multiple-gdal-geos-andor-proj-versions-on-your-system).

**Comment by GeraldCNelson** [comment]
I am attempting to remove all traces of GDAL (I haven't done anything to PROJ recently) before installing but am not having much luck. Can you point me to a site that explains how to do this? I haven't found anything that works for me.

**Comment by edzer** [comment]
For those who don't know how to do this, the general recommendation is to ***NOT*** do source installs of sf, but use binary installs.

**Comment by GeraldCNelson** [comment]
I'd be happy to stick with binary installs, but the process for that in ubuntu 20.04 is murky at best. At any rate, first I need to get rid of all traces of the previous binary install and there doesn't seem to be any good, recent directions for this.

**Comment by edzer** [comment]
Ah, I missed that this is on linux.

**Comment by GeraldCNelson** [comment]
Should I transfer this discussion to the gdal site? It's probably more relevant there.

**Comment by edzer** [comment]
No, it's an issue with R packages, R and GDAL. I'm closing the issue here, as this is not something we can work around in the `sf` package.

**Comment by GeraldCNelson** [comment]
Before we leave this, can I ask what installs sf.so and where? On linux (Ubuntu 20.04), I have two copies
```
/home/jerry/R/x86_64-pc-linux-gnu-library/3.4/sf/libs/sf.so
/home/jerry/R/x86_64-pc-linux-gnu-library/3.6/sf/libs/sf.so
```
These are the only contents of the directory. One was placed there April 18, the other April 28. 
 When I attempt to install sf from github (or CRAN) the error message is
```
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/jerry/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-sf/00new/sf/libs/sf.so':
  /home/jerry/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-sf/00new/sf/libs/sf.so: undefined symbol: proj_context_is_network_enabled
Error: loading failed
Execution halted
```
Since I haven't had sf installed on this machine, it must be from some other piece of software. If you tell me what that is, perhaps I can un- and reinstall and solve my problems.

**Comment by edzer** [comment]
These are shared libraries, created from compiling the C/C++ code in package `sf`, installed there during `R CMD INSTALL` or similar. The `3.6` indicates the R version used at install time.

**Comment by edzer** [comment]
The error message btw might indicate a double install of PROJ.

**Comment by GeraldCNelson** [comment]
Is there some easy (or even not so easy) way to find out if I have a double install of PROJ and how to correct it?

**Comment by GeraldCNelson** [comment]
Problem solved. It was a double install of proj. I compiled 7.0 from source and then later installed the binary, which is at 6.3.1. When I removed 7 with make uninstall (which worked perfectly) sf installed in RStudio. Thanks for your debugging help!
