### ISSUE TITLE
Mac installation issues

### ISSUE THREAD

**Issue by jacobmiller29** [r-spatial/sf#1464]
Following the mac installation instructions gives the following error: 

Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/lib/R/4.0/site-library/classInt/libs/classInt.so':
  dlopen(/usr/local/lib/R/4.0/site-library/classInt/libs/classInt.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/9/libgfortran.5.dylib
  Referenced from: /usr/local/lib/R/4.0/site-library/classInt/libs/classInt.so
  Reason: image not found

I have tried the following different methods of installing: 
install.packages("sf")
install.packages("sf", configure.args = "--with-proj-lib=/usr/local/lib/") 
library(devtools)
install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")

All yield the same error. 

Versions:
Mac Catalina 10.15.6 
R 4.0.2
proj 7.1.0
gdal 3.1.2
geos 3.8.1_1

**Comment by edzer** [comment]
What happens if you try to (re)install package `classInt`?

**Comment by jacobmiller29** [comment]
Thanks, that fixes it! Though when reinstalling classInt the following warning occurs: 
ld: warning: directory not found for option '-L/usr/local/opt/gcc/lib/gcc/10/gcc/x86_64-apple-darwin19/10.1.0'
installing to /usr/local/lib/R/4.0/site-library/00LOCK-classInt/00new/classInt/libs

**Comment by edzer** [comment]
That seems to be a problem with your local setup.
