### ISSUE TITLE
unable to install sf

### ISSUE THREAD

**Issue by yzut-ydv** [r-spatial/sf#1467]
I don't manage to install sf, although I have tried a couple of methods. Here I attach the report of my last attempt. Does anyone know why it doesn't work?
I am working in Windows 10. 
Thank you!

`> install_github("r-spatial/sf")
Downloading GitHub repo r-spatial/sf@master
√  checking for file 'C:\Users\ulloa-to\AppData\Local\Temp\RtmpaiQLkB\remotes24b06f3d5ba1\r-spatial-sf-f36719c/DESCRIPTION' ...
-  preparing 'sf': (461ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (541ms)
-  checking for empty or unneeded directories
-  building 'sf_0.9-6.tar.gz'
   Warnung: file 'sf/cleanup' did not have execute permissions: corrected
   Warnung: file 'sf/configure' did not have execute permissions: corrected
   
Installing package into ‘C:/Users/ulloa-to/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'sf' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs

*** arch - i386
rm -f sf.dll RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfg.o signed_area.o stars.o wkb.o zm_range.o
mkdir -p ../inst
"C:/PROGRA~1/R/R-35~1.1/bin/i386/Rscript.exe" --vanilla "../tools/winlibs.R" 3.0.4
cp -r ../windows/gdal3-3.0.4/share/gdal ../inst/
cp -r ../windows/gdal3-3.0.4/share/proj ../inst/
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c bbox.cpp -o bbox.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal.cpp -o gdal.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal_geom.cpp -o gdal_geom.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal_read.cpp -o gdal_read.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal_utils.cpp -o gdal_utils.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal_write.cpp -o gdal_write.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c geos.cpp -o geos.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c hex.cpp -o hex.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c ops.cpp -o ops.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c polygonize.cpp -o polygonize.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c proj.cpp -o proj.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c proj_info.cpp -o proj_info.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c raster2sf.cpp -o raster2sf.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c sfg.cpp -o sfg.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c signed_area.cpp -o signed_area.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c stars.cpp -o stars.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c wkb.cpp -o wkb.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c zm_range.cpp -o zm_range.o
C:/RBuildTools/3.5/mingw_32/bin/g++ -shared -s -static-libgcc -o sf.dll tmp.def RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfg.o signed_area.o stars.o wkb.o zm_range.o -L../windows/gdal3-3.0.4/lib-4.9.3/i386 -L../windows/gdal3-3.0.4/lib/i386 -lgdal -lsqlite3 -lspatialite -lproj -lgeos_c -lgeos -ljson-c -lnetcdf -lmariadbclient -lpq -lpgport -lpgcommon -lwebp -lcurl -lssh2 -lssl -lhdf5_hl -lhdf5 -lexpat -lfreexl -lcfitsio -lmfhdf -lhdf -lxdr -lpcre -lopenjp2 -ljasper -lpng -ljpeg -ltiff -lgeotiff -lgif -lxml2 -llzma -lz -lodbc32 -lodbccp32 -liconv -lpsapi -lwldap32 -lsecur32 -lgdi32 -lnormaliz -lcrypto -lcrypt32 -lws2_32 -LC:/PROGRA~1/R/R-35~1.1/bin/i386 -lR
installing to C:/Users/ulloa-to/Documents/R/win-library/3.5/sf/libs/i386

*** arch - x64
rm -f sf.dll RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfg.o signed_area.o stars.o wkb.o zm_range.o
mkdir -p ../inst
"C:/PROGRA~1/R/R-35~1.1/bin/x64/Rscript.exe" --vanilla "../tools/winlibs.R" 3.0.4
cp -r ../windows/gdal3-3.0.4/share/gdal ../inst/
cp -r ../windows/gdal3-3.0.4/share/proj ../inst/
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c bbox.cpp -o bbox.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal.cpp -o gdal.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal_geom.cpp -o gdal_geom.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal_read.cpp -o gdal_read.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal_utils.cpp -o gdal_utils.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c gdal_write.cpp -o gdal_write.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c geos.cpp -o geos.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c hex.cpp -o hex.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c ops.cpp -o ops.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c polygonize.cpp -o polygonize.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c proj.cpp -o proj.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c proj_info.cpp -o proj_info.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c raster2sf.cpp -o raster2sf.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c sfg.cpp -o sfg.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c signed_area.cpp -o signed_area.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c stars.cpp -o stars.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c wkb.cpp -o wkb.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/gdal3-3.0.4/include/gdal-3.0.4 -I../windows/gdal3-3.0.4/include/geos-3.8.0 -I../windows/gdal3-3.0.4/include/proj-6.3.1 -DHAVE_PROJ_H -I"C:/Users/ulloa-to/Documents/R/win-library/3.5/Rcpp/include"        -O2 -Wall  -mtune=generic -c zm_range.cpp -o zm_range.o
C:/RBuildTools/3.5/mingw_64/bin/g++ -shared -s -static-libgcc -o sf.dll tmp.def RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfg.o signed_area.o stars.o wkb.o zm_range.o -L../windows/gdal3-3.0.4/lib-4.9.3/x64 -L../windows/gdal3-3.0.4/lib/x64 -lgdal -lsqlite3 -lspatialite -lproj -lgeos_c -lgeos -ljson-c -lnetcdf -lmariadbclient -lpq -lpgport -lpgcommon -lwebp -lcurl -lssh2 -lssl -lhdf5_hl -lhdf5 -lexpat -lfreexl -lcfitsio -lmfhdf -lhdf -lxdr -lpcre -lopenjp2 -ljasper -lpng -ljpeg -ltiff -lgeotiff -lgif -lxml2 -llzma -lz -lodbc32 -lodbccp32 -liconv -lpsapi -lwldap32 -lsecur32 -lgdi32 -lnormaliz -lcrypto -lcrypt32 -lws2_32 -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR
installing to C:/Users/ulloa-to/Documents/R/win-library/3.5/sf/libs/x64
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
in method for 'dbWriteTable' with signature '"PostgreSQLConnection","character","sf"': no definition for class "PostgreSQLConnection"
in method for 'dbDataType' with signature '"PostgreSQLConnection","sf"': no definition for class "PostgreSQLConnection"
in method for 'coerce' with signature '"Spatial","sf"': no definition for class "Spatial"
in method for 'coerce' with signature '"Spatial","sfc"': no definition for class "Spatial"
in method for 'coerce' with signature '"sf","Spatial"': no definition for class "Spatial"
in method for 'coerce' with signature '"sfc","Spatial"': no definition for class "Spatial"
in method for 'coerce' with signature '"XY","Spatial"': no definition for class "Spatial"
in method for 'coerce' with signature '"crs","CRS"': no definition for class "CRS"
** help
*** installing help indices
  converting help for package 'sf'
    finding HTML links ... fertig
    Ops                                     html  
    aggregate.sf                            html  
    bind                                    html  
    coerce-methods                          html  
    dbDataType                              html  
    db_drivers                              html  
    extension_map                           html  
    gdal                                    html  
    gdal_utils                              html  
    geos_binary_ops                         html  
    geos_binary_pred                        html  
    geos_combine                            html  
    geos_measures                           html  
    geos_query                              html  
    geos_unary                              html  
    internal                                html  
    is_driver_available                     html  
    is_driver_can                           html  
    is_geometry_column                      html  
    merge.sf                                html  
    nc                                      html  
    plot                                    html  
    prefix_map                              html  
    rawToHex                                html  
    reexports                               html  
    s2                                      html  
    sf-defunct                              html  
    sf                                      html  
    sf_extSoftVersion                       html  
    sf_project                              html  
    sfc                                     html  
    sgbp                                    html  
    st                                      html  
    st_agr                                  html  
    st_as_binary                            html  
    st_as_grob                              html  
    st_as_sf                                html  
    st_as_sfc                               html  
    st_as_text                              html  
    st_bbox                                 html  
    st_cast                                 html  
    st_cast_sfc_default                     html  
    st_collection_extract                   html  
    st_coordinates                          html  
    st_crop                                 html  
    st_crs                                  html  
    st_drivers                              html  
    st_geometry                             html  
    st_geometry_type                        html  
    st_graticule                            html  
    st_interpolate_aw                       html  
    st_is                                   html  
    st_is_longlat                           html  
    st_jitter                               html  
    st_join                                 html  
Rd warning: C:/Users/ulloa-to/AppData/Local/Temp/Rtmp8yeyGb/R.INSTALL40fc79d72687/sf/man/st_join.Rd:38: missing file link 'mutate-joins'
    st_layers                               html  
    st_line_sample                          html  
    st_m_range                              html  
    st_make_grid                            html  
    st_nearest_feature                      html  
    st_nearest_points                       html  
    st_normalize                            html  
    st_precision                            html  
    st_read                                 html  
    st_relate                               html  
    st_sample                               html  
    st_shift_longitude                      html  
    st_transform                            html  
    st_viewport                             html  
    st_write                                html  
    finding level-2 HTML links ... done

    st_z_range                              html  
    st_zm                                   html  
    stars                                   html  
    summary.sfc                             html  
    tibble                                  html  
    tidyverse                               html  
    transform.sf                            html  
    valid                                   html  
    vctrs                                   html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'sf':
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: Objekt 'group_split' nicht gefunden
Fehler: Laden fehlgeschlagen
Ausführung angehalten
*** arch - x64
Error: package or namespace load failed for 'sf':
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: Objekt 'group_split' nicht gefunden
Fehler: Laden fehlgeschlagen
Ausführung angehalten
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/ulloa-to/Documents/R/win-library/3.5/sf'
In R CMD INSTALL
Error: Failed to install 'sf' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ulloa-to/AppData/Local/Temp/RtmpaiQLkB/file24b0106256d6/sf_0.9-6.tar.gz’ had non-zero exit status`

**Comment by ateucher** [comment]
Is there a reason you are trying to install it from GitHub? If you don't need the development version, install it from CRAN using `install.packages("sf")`. If you get a prompt asking if you would like to install from source, choose "No".

**Comment by edzer** [comment]
I agree. The error message you see indicates an outdated version of dplyr; reinstall or update that first.
