### ISSUE TITLE
checking for geos_c.h... no configure: error: geos_c.h not found in given locations. ERROR: configuration failed for package 'sf'

### ISSUE THREAD

**Issue by wbharrykyupelyan** [r-spatial/sf#1469]
Dear sf support team,

I run this command on my rstudio IDE Amazon linux 2 EC2 instance:

install.packages("sf", configure.args = "--with-gdal-config=/usr/local/bin/gdal-config --with-geos-config=/usr/local/bin/geos-config --with-proj-include=/usr/local/include --with-proj-lib=/usr/local/lib", configure.vars = "PROJ_LIB=/usr/local/lib/share/proj GDAL_DATA=/usr/local/share/gdal")

and I get the following error: (checking for geos_c.h... no configure: error: geos_c.h not found in given locations.
ERROR: configuration failed for package 'sf')

-----R console dump
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
configure: gdal-config set to /usr/local/bin/gdal-config
checking gdal-config exists... yes
checking gdal-config executable... yes
checking gdal-config usability... yes
configure: GDAL: 3.1.2
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.1.2
checking proj.h usability... yes
checking proj.h presence... yes
checking for proj.h... yes
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
configure: geos-config set to /usr/local/bin/geos-config
checking geos-config exists... yes
checking geos-config executable... yes
checking geos-config usability... yes
configure: GEOS: 3.8.1
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... no
checking geos_c.h presence... no
checking for geos_c.h... no
configure: error: geos_c.h not found in given locations.
ERROR: configuration failed for package 'sf'
* removing '/homedirs/user/R/x86_64-pc-linux-gnu-library/3.6/sf'
Warning in install.packages :
  installation of package 'sf' had non-zero exit status
The downloaded source packages are in
	'/tmp/RtmpIgSnrE/downloaded_packages'

-------------------------------------------------Installation was done the following way----------------------------
I run the following commands to download and install proj, gdal and geos.

sudo mkdir downloads
sudo chown user:group downloads
cd downloads

----download geos 3.8.1---------
wget http://download.osgeo.org/geos/geos-3.8.1.tar.bz2
bunzip2 geos-3.8.1.tar.bz2
tar xvf  geos-3.8.1.tar

---download proj 6.2.0---------
sudo wget https://download.osgeo.org/proj/proj-6.2.0.tar.gz
sudo tar xf proj-6.2.0.tar.gz

----download gdal 3.1.2--------
sudo yum-builddep gdal
sudo wget http://download.osgeo.org/gdal/3.1.2/gdal-3.1.2.tar.gz
sudo tar xf gdal-3.1.2.tar.gz

---install geos 3.8.1-----------
export PREFIX=/usr/local;
cd geos-3.8.1

sudo CPPFLAGS=-I${PREFIX}/include LDFLAGS=-L${PREFIX}/lib ./configure --prefix=${PREFIX};
sudo make
sudo make install
sudo ldconfig
cd ..

----install proj 6.2.0 -----------
cd proj-6.2.0;
sudo CPPFLAGS=-I${PREFIX}/include LDFLAGS=-L${PREFIX}/lib ./configure --prefix=${PREFIX};
sudo make ;
sudo make install;
sudo ldconfig
cd ..

------install gdal 3.1.2-----------
export LD_LIBRARY_PATH=${PREFIX}/lib:${LD_LIBRARY_PATH};
export PATH=${PREFIX}/bin:${PATH};
cd gdal-3.1.2;

sudo CPPFLAGS=-I${PREFIX}/include LDFLAGS=-L${PREFIX}/lib ./configure --prefix=${PREFIX} --with-proj=/usr/local --with-geos=yes;
sudo make ;
sudo make install;
echo /usr/local/lib | sudo tee -a /etc/ld.so.conf.d/local.conf
sudo ldconfig

--set permissions on the directory
sudo chmod -R 755 /usr/local/lib/share

----set environment variables
sudo vim /etc/profile.d/globalvars.sh
export PROJ_LIB=/usr/local/lib/share/proj
export GDAL_DATA=/usr/local/share/gdal
export PREFIX=/usr/local;
export LD_LIBRARY_PATH=${PREFIX}/lib:${LD_LIBRARY_PATH};
export PATH=${PREFIX}/bin:${PATH};

sudo chmod 644 /etc/profile.d/globalvars.sh

--------------------------------------------------end of installation---------------------------------------------

---------------------------------------gdal-config
$ gdal-config --prefix
/usr/local
$ gdal-config --libs
-L/usr/local/lib -lgdal
$ gdal-config --dep-libs
-lcrypto -lfreexl -lgeos_c -lwebp -lsqlite3 -lodbc -lodbcinst -lexpat -lxerces-c -lpthread -lopenjp2 -ljasper -lnetcdf -lhdf5 -L/usr/lib64/hdf -lmfhdf -ldf -logdi -lgif -lCharLS -ljpeg -ltiff -lgta -lpng -lcfitsio -L/usr/local/lib -lproj -lsqlite3 -lz -lpthread -lm -lrt -ldl -lpcre -lcurl -lxml2
$ gdal-config --cflags
-I/usr/local/include
[$ gdal-config --datadir
/usr/local/share/gdal
$ gdal-config --version
3.1.2
$ gdal-config --ogr-enabled
yes
$ gdal-config --gnm-enabled
yes

-----------------------------------------------geos-config--------------------------
$ geos-config --prefix
/usr/local
$ geos-config --version
3.8.1
$ geos-config --libs
-L/usr/local/lib -lgeos-3.8.1
$ geos-config --clibs
-L/usr/local/lib -lgeos_c
$ geos-config --cclibs
-L/usr/local/lib -lgeos
$ geos-config --static-clibs
-L/usr/local/lib -lgeos_c -lgeos -lm
$ geos-config --static-cclibs
-L/usr/local/lib -lgeos -lm
$ geos-config --cflags
-I/usr/local/include
$ geos-config --ldflags
-L/usr/local/lib
$ geos-config --includes
/usr/local/include
$ geos-config --jtsport
1.13.0

---------------------------------------------------
$ c++ --version
c++ (GCC) 7.3.1 20180712 (Red Hat 7.3.1-9)
Which defaults to C++ compiler version 14. sf has a hard requirement for version C++ 11.

----------------------------------------------------
$R_HOME : /opt/R/3.6.1/lib64/R
R version is R3.6.1

------------------------------------------------------

Questions:

1. How can we fix checking for geos_c.h... no configure: error: geos_c.h not found in given locations.
ERROR: configuration failed for package) 'sf' issue, what switches, env vars, etc.. are we missing in our above build and configuration?
2. sf hard requirement is C++ 11 version of the compiler. How do we enable that with the switches, env vars or inline sf call, switches during ./configure call?

Thanks
Harry

**Comment by wbharrykyupelyan** [comment]
I forgot to mention,

$ c++ --version
c++ (GCC) 7.3.1 20180712 (Red Hat 7.3.1-9)
Which defaults to C++ compiler version 14. sf has a hard requirement for version C++ 11.
Thanks
Harry

**Comment by edzer** [comment]
If you would make this available as a docker file, it would be easier to test and try to replicate your problem.

**Comment by wbharrykyupelyan** [comment]
Dear Edzer, we do not use docker, so the direction is to make it work on current EC2 instance.

Can you please help resolve the issue?
Steps on how to reproduce are all in the ticket.
Regards,
Harry

**Comment by edzer** [comment]
No, sorry, someone else from the "support team" has to step in.

**Comment by wbharrykyupelyan** [comment]
I forgot to mention:
$R_HOME :   /opt/R/3.6.1/lib64/R
R version is R3.6.1

Thanks
Harry

**Comment by edzer** [comment]
Have you also tried, _instead of_ installing everything from source, to follow the instructions for fedora, [here](https://github.com/r-spatial/sf#fedora)?

**Comment by wbharrykyupelyan** [comment]
Dear Edzer,

The sf System Requirements are:	
C++11, 
GDAL (>= 2.0.1), 
GEOS (>= 3.4.0), 
PROJ (>= 4.8.0). 
Note C++ 11 is a hard requirement.

1. In our live environment we currently have:
$ yum info proj
Installed Packages
Name        : proj
Arch        : x86_64
Version     : 4.8.0
Release     : 4.el7
Size        : 474 k
Repo        : installed
From repo   : epel
--------------------------------
$ yum info gdal
Installed Packages
Name        : gdal
Arch        : x86_64
Version     : 1.11.4
Release     : 3.el7
Size        : 760 k
Repo        : installed
From repo   : epel

--------------------------------
$ yum info geos
Installed Packages
Name        : geos
Arch        : x86_64
Version     : 3.4.2
Release     : 2.el7
Size        : 1.8 M
Repo        : installed
From repo   : epel

1. What is the best way to upgrade epel gdal 1.11.4 tp version 3.1.2?
2. What are the correct paths and flags to use so C++ 11 compiler is is invoked?

Thanks
Harry

**Comment by wbharrykyupelyan** [comment]
Dear Edzer,

We have epel-release version 7 release 11 installed on our Amazon linux2 ec2 instance.
$ yum info epel-release
Name        : epel-release
Arch        : noarch
Version     : 7
Release     : 11
Size        : 24 k
Repo        : installed
From repo   : amzn2extra-epel
Summary     : Extra Packages for Enterprise Linux repository configuration
URL         : http://download.fedoraproject.org/pub/epel
License     : GPLv2
------------------------------------

Epel 8 which contains newer version of gdal 3.0.x is only available with RHEL 8.
Is there a way to upgrade gdal 1.11.4 to version 3.1.2 on epel 7?

Thanks
Harry

**Comment by rsbivand** [comment]
The only way to install PROJ/GDAL/GEOS to moderately modern versions (PROJ 4.8.0 is from 2012) on your choice of platform is from source. However, you then have to install all of the external dependencies needed for the drivers you require. Basically, **sp**/**rgdal**/**rgeos** will still install on your system with the outdated rpms, but **sf** must have GDAL >= 2 (major API change). From GDAL 2 onward, **sf** and **rgdal** handle API changes by `#ifdef`s in the compiled code and branching in the R code. 

If you cannot make **sf** work on your system by installing all it needs from source, you should seriously consider changing platform, or reconfiguring your workflow to use **sp**/**rgdal**/**rgeos** which do still support PROJ 4.8.0/GDAL 1.11.4/GEOS 3.4.2, although so much has changed since then that much functionality is not supported and many bugs  are not fixed.

**Comment by tedmoorman** [comment]
Hello,

Trying to install sf on R version 3.5.3 with Rprofile configured as follows.

```R
Sys.setenv("LD_LIBRARY_PATH" = "/usr/local/lib:/opt/glpk-4.65/lib:/opt/app/SybaseIQ/IQ-16_1/lib64::/lib:/usr/local/lib64:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-1.el7.x86_64/jre/lib/amd64/server")
Sys.setenv(GDAL_DATA="/usr/share/epsg_csv")
dyn.load("/usr/local/lib/libgeos_c.so")
dyn.load("/usr/local/lib/libgeos-3.8.1.so")
```
The installation is on a server, and I'm trying to install to my local package library directory. Another caveat is that I don't have permissions to install directly from URLs (or CRAN repositories or GitHub). I have to download files to my desktop and then upload them to the server. I receive the following error messages when trying to install:

```R
> install.packages("~/package_files/sf_0.9-7.tar.gz", repos=NULL, type="source", dependencies = TRUE)
Installing package into ‘~/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /usr/local/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.3.2
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 2.3.2
configure: pkg-config proj exists, will use it
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
configure: PROJ: 4.8.0
checking for pj_init_plus in -lproj... yes
checking PROJ: epsg found and readable... yes
checking for geos-config... /usr/local/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.8.1
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... no
checking geos_c.h presence... no
checking for geos_c.h... no
configure: error: geos_c.h not found in given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/8b3sb/R/x86_64-pc-linux-gnu-library/3.5/sf’
Warning in install.packages :
  installation of package ‘/home/8b3sb/package_files/sf_0.9-7.tar.gz’ had non-zero exit status
```R

In doing some searches for related files, I come up with the following:

```R
/usr/lib64/grass-6.4.4/etc/ogr_csv/gcs.csv
/usr/local/share/gdal/gcs.csv
/usr/share/proj/epsg
/usr/share/epsg_csv/gcs.csv
/usr/share/gdal/gcs.csv
/usr/bin/geos-config
/usr/local/bin/geos-config
/usr/include/geos_c.h
/usr/local/include/geos_c.h
/usr/lib64/libgeos_c.so
/usr/lib64/libgeos_c.so.1
/usr/lib64/libgeos_c.so.1.8.2
/usr/local/lib/libgeos_c.so
/usr/local/lib/libgeos_c.so.1
/usr/local/lib/libgeos_c.so.1.13.3
```

Any suggestions are appreciated.

Thanks,
-Ted

**Comment by edzer** [comment]
Looks like you have a mix of GEOS versions on your system; see the README of this repo.
