### ISSUE TITLE
st_interpolate_aw with NAs

### ISSUE THREAD

**Issue by kylebutts** [r-spatial/sf#1473]
I am trying to interpolate data across census tracts over time, but I have `NA`s in my data. It seems like `st_interpolate_aw()` will assign the value `NA` for any polygon that covers a geometry with an `NA`. In the below reprex, you can see that any of the grid that intersects with the `NA` polygon will get a value of NA instead of just excluding that and summing the non-NA portion. Is it possible to have a paramater to the function thats similar to `remove.na`?

``` r

library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
nc = st_read(system.file("shape/nc.shp", package="sf"))
#> Reading layer `nc' from data source `/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/shape/nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> CRS:            4267
g = st_make_grid(nc, n = c(40,20))
#> although coordinates are longitude/latitude, st_relate_pattern assumes that they are planar
nc[36, "BIR74"] <- NA
plot(nc["BIR74"])
```

![](https://i.imgur.com/IR761lx.png)

``` r
int = st_interpolate_aw(nc["BIR74"], g, extensive = FALSE)
#> Warning in st_interpolate_aw.sf(nc["BIR74"], g, extensive = FALSE):
#> st_interpolate_aw assumes attributes are constant over areas of x
#> although coordinates are longitude/latitude, st_intersection assumes that they are planar
plot(int["BIR74"])
```

![](https://i.imgur.com/PvL4P1W.png)

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edzer** [comment]
Is anything wrong with
```
int = st_interpolate_aw(na.omit(nc)["BIR74"], g, extensive = FALSE)
```
?

**Comment by kylebutts** [comment]
Now I feel a bit silly! :-) Thanks for the help

**Comment by edzer** [comment]
No need to - thanks!
