### ISSUE TITLE
CRS WKT2 breaks st_crs.character when PROJ < 6, GDAL < 3

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#1474]
https://github.com/r-spatial/sf/commit/5cade16b233bbde500ec642e1d1a25ddd151478e

not worth a PR, just add the protection to use the extant Proj4 string when PROJ and GDAL are ancient.

**Comment by edzer** [comment]
Thanks!

**Comment by rsbivand** [comment]
@jcheng5 does this resolve the issue, assuming that your **sf** is built using PROJ < 6 and/or GDAL < 3 ?

**Comment by jcheng5** [comment]
That does resolve it, thank you!

```r
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.6.2"        "2.2.3"        "4.9.3"         "true"        "false" 
```

I was/am using the PROJ and GDAL libraries that come with my Linux distro (Ubuntu 18.04).

**Comment by rsbivand** [comment]
Some distros have hung back because of the speed of change in PROJ and GDAL. @rouault has an impressive work and commit rate, supported by others in OSGeo. Getting from relying on Proj4 strings to WKT2 has been necessary. We've been considering configuring R-spatial as an OSGeo community formally, since that is what we do anyway. Probably direct contact between him and the Shiny team about Flatgeobuf is sensible  - @tim-salabim is already in touch. 

However, a formal structure between R and OSGeo could be used to let each other know what is going on. https://github.com/r-spatial/discuss/issues/37 is the discussion started by @basille which probably should see some progress. It would also help everybody if we set up testing frameworks with very old, old stable, stable, unstable PROJ/GDAL combinations, something a working group could propose.

**Comment by Robinlovelace** [comment]
> We've been considering configuring R-spatial as an OSGeo community formally, since that is what we do anyway.

Interesting idea, let me know if there's anything I or others in the r-spatial community can do to help with those efforts.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.

**Comment by basille** [comment]
Thanks @rsbivand to bring me in this discussion, and @Robinlovelace for your interest! While I do think establishing R spatial as an OSGeo community is indeed the way to go, health issues (vertigo) have prevented me to make any progress on this front — and I won't be able to focus on this in the foreseeable future either, as I need to consider limited priorities. I'm hoping for better, but I cannot guarantee anything at the moment.
