### ISSUE TITLE
Potentially unexpected behaviour of st_intersection of polygons

### ISSUE THREAD

**Issue by nevilamos** [r-spatial/sf#1484]
---
title: "Potentially unexpected behaviour of st_intersection of polygons"
---

I Have ecountered what , for me was an unexpected behaviour of st_intersection.
When perfomring intersection of  only polygons, I expected the output would also be only polygons or multipolygons.

ie the output geomtry is the same order as the input geometry where a single input geomtyr type is used, or of the lower order where multiples types are used.

However when the input polygons contain common boundaires the output contains a mix of "POLYGON","LINESTRING" and "GEOMETRYCOLLECTION" containing both the other types.

Perhaps this should be mader clearer in the help? 

```{r}
df<-data.frame("ID"=1:3)
g <- st_geometry(st_sfc(
  st_buffer(st_point(c(1, .5)), .5),
  st_polygon(list(rbind(c(0, 0), c(0, 1), c(1, 1), c(1, 0), c(0, 0)))),
  st_polygon(list(rbind(c(.4, .2), c(.5, 1.5), c(1, 1.2), c(1, .3), c(.4, .2))))
))


inputSF<-st_set_geometry(df, g)
```

```{r}
plot(st_geometry(inputSF),main="Three partially overlapping polygons shared boundary from 1,.3 to 1,1",axes=T)

```
From the interection of these three polygons I expected to get 6 unique non overlapping polygons,  This would be the result in at least some other GIS. However the result is seven rows of three geometry types.
```{r}
intersected_SF<-st_intersection(inputSF)
st_geometry_type(intersected_SF)
```
This can be parailly fixed ( once you are aware of the issue)
using st_collection_extract()
The results are all multipolygons rather than polygons
```{r}
cleaned_SF<-st_collection_extract(intersected_SF,type= "POLYGON")
st_geometry_type(cleaned_SF)
```
If these are simplified using st_cast() most of these are due to slivers forming on the boundary of the circle.
Is there any way to atuomatically clen or avoid these?
```{r}
simplified_SF<-st_cast(cleaned_SF,to="POLYGON")
par(mfrow=c(1,1))
for (i in 1:nrow(simplified_SF)){plot(st_geometry(simplified_SF[i,]),xlim=c(0,1.5),ylim=c(0,1.5),axes=T)}
```

**Comment by edzer** [comment]
```r
intersected_SF<-st_intersection(inputSF)
```
returns the n-ary intersections, where
```r
intersected_SF<-st_intersection(inputSF, inputSF)
```
returns the pairwise interactions. It sounds you are after the latter. Of the latter, there are 9, as they include the self-intersections.

**Comment by nevilamos** [comment]
I do not want the  pairwise intersections, but a "clean" version of the n-ary intersections.
The pairwise operation
```{r}
st_intersection(inputSF, inputSF)
```
correctly returns 9 polygons, **and only polygons**
While the n-ary intersection 

```{r}
st_intersection(inputSF)
```
returns the 6 n-ary excluding self interesections, ie 6 non-overlapping polygons with the orgin attribute indicating which of the n input polyogns they are the intersection of - this i what I want, 
But also returns addtional sliver polygons ( in multipolygons with the "clean" polyogons ( to give a total of 10 polygons of which 4 are the slivers, plus LINESTRINGS. it is this difference behaviour that I was not expecting.

**Comment by edzer** [comment]
Did you come to that expectation because of the documentation, or was it rather what you hoped for? Sometimes, setting a non-zero precision helps in getting rid of slivers in such cases.

**Comment by rsbivand** [comment]
The expectation in GEOS is that all the intersections (points, line segments, polygons) be returned. See for a discussion the introduction of Overlay NG (a re-implementation in GEOS) which has been moved back to return a GEOMETRYCOLLECTION, as previously (https://lists.osgeo.org/pipermail/geos-devel/2020-September/009670.html, https://lists.osgeo.org/pipermail/geos-devel/2020-August/009599.html). The user may choose to accept only the members that meet a given topological dimension constraint. We had to do this in **rgeos**, as the `drop_lower_td=` argument describes: https://rgeos.r-forge.r-project.org/reference/topo-bin-gIntersection.html.

**Comment by nevilamos** [comment]
First of all, thankyou both Edzer and Roger for all your work on r-spatial, and for your responses here.

The reason I gave this issue the title "Potentially unexpected behaviour" was precisely because I was unsure whether it was just a result of my expecations - based mainly on the results of the n-ary union function in esri arcpy ( where one set of overlapping shapes is provided as the input as it is in st_intersection(my_polygons) in SF. For a while I have been trying to find an R function that behaved similary to the esri function, st_interection() with a single SF input does.  

rgeos::gIntersection cannot be used, becuase it requires two inputs, and returns only the pairwise intersections  - so the polygons produced are not  the non- overlapping n-ary ones.

I had a look again at the help for st_intersection() and the example of n-ary intersection of squares therein ( which does only produce polygons)  and it is still not clear to *me* that polygons and linestrings will be produced from polygons with an intersecting boundary.  Surely if all interections were produces points where lines of the polygons cross should also be produced but they are not?  
Also if a polygon is duplicated(pp below) and shifted so that some parts of its boundaires intersect linestrings are produced in some cases (pp2 below) but not others (pp1 below)
```{r}
m = rbind(c(0,0), c(2,0), c(2,2), c(0,2), c(0,0))
p = st_polygon(list(m))
p1 = p+c(1,0)
p2 = p+c(1,2)

pp<-st_sfc(list(p,p))%>%st_set_geometry(data.frame("ID"=1:2),.)
pp1<-st_sfc(list(p,p1))%>%st_set_geometry(data.frame("ID"=1:2),.)
pp2<-st_sfc(list(p,p2))%>%st_set_geometry(data.frame("ID"=1:2),.)

st_intersection(pp)
st_intersection(pp1)
st_intersection(pp2)
```

I think that an argument similar to the drop_lower_td= in rgeos, metioned by Roger would be great in st_intersects  since would allow control over and make explict the possibilitie of what geometriies may be returned.
