### ISSUE TITLE
geometry column name different when using wildcard in query for shp files

### ISSUE THREAD

**Issue by dpprdan** [r-spatial/sf#1485]
When using a `query` on a shp, `st_read()` returns the geometry column as `geometry` when specific columns are queried, but as `_ogr_geometry` when the `*` wildcard is used.

    library(sf)
    #> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

    shp_path <- system.file("shape/nc.shp", package="sf")

    colnames(st_read(shp_path, query = "SELECT NAME FROM \"nc\" WHERE BIR74 > 20000"))
    #> Reading layer `nc' from data source `path\to\sf\shape\nc.shp' using driver `ESRI Shapefile'
    #> Simple feature collection with 2 features and 1 field
    #> geometry type:  POLYGON
    #> dimension:      XY
    #> bbox:           xmin: -81.06555 ymin: 34.82742 xmax: -78.49929 ymax: 35.50912
    #> geographic CRS: NAD27
    #> [1] "NAME"     "geometry"

    colnames(st_read(shp_path, query = "SELECT * FROM \"nc\" WHERE BIR74 > 20000"))
    #> Reading layer `nc' from data source `path\to\sf\shape\nc.shp' using driver `ESRI Shapefile'
    #> Simple feature collection with 2 features and 14 fields
    #> geometry type:  POLYGON
    #> dimension:      XY
    #> bbox:           xmin: -81.06555 ymin: 34.82742 xmax: -78.49929 ymax: 35.50912
    #> geographic CRS: NAD27
    #>  [1] "AREA"           "PERIMETER"      "CNTY_"          "CNTY_ID"       
    #>  [5] "NAME"           "FIPS"           "FIPSNO"         "CRESS_ID"      
    #>  [9] "BIR74"          "SID74"          "NWBIR74"        "BIR79"         
    #> [13] "SID79"          "NWBIR79"        "_ogr_geometry_"

Is this behaviour intended or unavoidable?

With gpkg (and sqlite and possibly everything other than shp), the geometry column has to be explicitly selected, so this seems to be driver-dependent.

<details>
<summary>
gpkg & sqlite examples
</summary>

    gpkg_path <- system.file("gpkg/nc.gpkg", package="sf")
    colnames(st_read(gpkg_path, query = "SELECT NAME FROM \"nc.gpkg\" WHERE BIR74 > 20000"))
    #> Reading layer `nc.gpkg' from data source `path\to\sf\gpkg\nc.gpkg' using driver `GPKG'
    #> Warning: no simple feature geometries present: returning a data.frame or tbl_df
    #> [1] "NAME"

    colnames(st_read(gpkg_path, query = "SELECT NAME, geom FROM \"nc.gpkg\" WHERE BIR74 > 20000"))
    #> Reading layer `nc.gpkg' from data source `path\to\sf\gpkg\nc.gpkg' using driver `GPKG'
    #> Simple feature collection with 2 features and 1 field
    #> geometry type:  MULTIPOLYGON
    #> dimension:      XY
    #> bbox:           xmin: -81.06555 ymin: 34.82742 xmax: -78.49929 ymax: 35.50912
    #> geographic CRS: NAD27
    #> [1] "NAME" "geom"

    colnames(st_read(gpkg_path, query = "SELECT * FROM \"nc.gpkg\" WHERE BIR74 > 20000"))
    #> Reading layer `nc.gpkg' from data source `path\to\sf\gpkg\nc.gpkg' using driver `GPKG'
    #> Simple feature collection with 2 features and 14 fields
    #> geometry type:  MULTIPOLYGON
    #> dimension:      XY
    #> bbox:           xmin: -81.06555 ymin: 34.82742 xmax: -78.49929 ymax: 35.50912
    #> geographic CRS: NAD27
    #>  [1] "AREA"      "PERIMETER" "CNTY_"     "CNTY_ID"   "NAME"      "FIPS"     
    #>  [7] "FIPSNO"    "CRESS_ID"  "BIR74"     "SID74"     "NWBIR74"   "BIR79"    
    #> [13] "SID79"     "NWBIR79"   "geom"

    sqlite_path <- system.file("sqlite/nc.sqlite", package="sf")

    colnames(st_read(sqlite_path, query = "SELECT NAME, GEOMETRY FROM \"nc.sqlite\" WHERE BIR74 > 20000"))
    #> Reading layer `nc.sqlite' from data source `path\to\sf\sqlite\nc.sqlite' using driver `SQLite'
    #> Simple feature collection with 2 features and 1 field
    #> geometry type:  MULTIPOLYGON
    #> dimension:      XY
    #> bbox:           xmin: -81.06555 ymin: 34.82742 xmax: -78.49929 ymax: 35.50912
    #> geographic CRS: NAD27
    #> [1] "name"     "GEOMETRY"

The latter has been discussed in the original issue (\#834) and PR (\#854) regarding the query feature.
</details>

<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> - Session info ---------------------------------------------------------------
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       Windows 10 x64              
    #>  system   x86_64, mingw32             
    #>  ui       RTerm                       
    #>  language en                          
    #>  collate  German_Germany.1252         
    #>  ctype    German_Germany.1252         
    #>  tz       Europe/Berlin               
    #>  date     2020-09-16                  
    #> 
    #> - Packages -------------------------------------------------------------------
    #>  package     * version    date       lib source                             
    #>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.2)                     
    #>  backports     1.1.9      2020-08-24 [1] CRAN (R 4.0.2)                     
    #>  callr         3.4.4      2020-09-07 [1] CRAN (R 4.0.2)                     
    #>  class         7.3-17     2020-04-26 [2] CRAN (R 4.0.2)                     
    #>  classInt      0.4-3      2020-04-07 [1] CRAN (R 4.0.2)                     
    #>  cli           2.0.2      2020-02-28 [1] CRAN (R 4.0.2)                     
    #>  crayon        1.3.4      2017-09-16 [1] CRAN (R 4.0.2)                     
    #>  DBI           1.1.0      2019-12-15 [1] CRAN (R 4.0.2)                     
    #>  desc          1.2.0      2018-05-01 [1] CRAN (R 4.0.2)                     
    #>  devtools      2.3.1      2020-07-21 [1] CRAN (R 4.0.2)                     
    #>  digest        0.6.25     2020-02-23 [1] CRAN (R 4.0.2)                     
    #>  dplyr         1.0.2      2020-08-18 [1] CRAN (R 4.0.2)                     
    #>  e1071         1.7-3      2019-11-26 [1] CRAN (R 4.0.2)                     
    #>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.2)                     
    #>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.2)                     
    #>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.2)                     
    #>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                     
    #>  generics      0.0.2      2018-11-29 [1] CRAN (R 4.0.2)                     
    #>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                     
    #>  highr         0.8        2019-03-20 [1] CRAN (R 4.0.2)                     
    #>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 4.0.2)                     
    #>  KernSmooth    2.23-17    2020-04-26 [2] CRAN (R 4.0.2)                     
    #>  knitr         1.29       2020-06-23 [1] CRAN (R 4.0.2)                     
    #>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.0.2)                     
    #>  magrittr      1.5.0.9000 2020-08-31 [1] Github (tidyverse/magrittr@15f6f07)
    #>  memoise       1.1.0      2017-04-21 [1] CRAN (R 4.0.2)                     
    #>  pillar        1.4.6      2020-07-10 [1] CRAN (R 4.0.2)                     
    #>  pkgbuild      1.1.0      2020-07-13 [1] CRAN (R 4.0.2)                     
    #>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.2)                     
    #>  pkgload       1.1.0      2020-05-29 [1] CRAN (R 4.0.2)                     
    #>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.2)                     
    #>  processx      3.4.4      2020-09-03 [1] CRAN (R 4.0.2)                     
    #>  ps            1.3.4      2020-08-11 [1] CRAN (R 4.0.2)                     
    #>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.2)                     
    #>  R6            2.4.1      2019-11-12 [1] CRAN (R 4.0.2)                     
    #>  Rcpp          1.0.5      2020-07-06 [1] CRAN (R 4.0.2)                     
    #>  remotes       2.2.0      2020-07-21 [1] CRAN (R 4.0.2)                     
    #>  rlang         0.4.7      2020-07-09 [1] CRAN (R 4.0.2)                     
    #>  rmarkdown     2.3        2020-06-18 [1] CRAN (R 4.0.2)                     
    #>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 4.0.2)                     
    #>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.2)                     
    #>  sf          * 0.9-6      2020-09-13 [1] CRAN (R 4.0.2)                     
    #>  stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)                     
    #>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.2)                     
    #>  testthat      2.3.2      2020-03-02 [1] CRAN (R 4.0.2)                     
    #>  tibble        3.0.3      2020-07-10 [1] CRAN (R 4.0.2)                     
    #>  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 4.0.2)                     
    #>  units         0.6-7      2020-06-13 [1] CRAN (R 4.0.2)                     
    #>  usethis       1.6.1      2020-04-29 [1] CRAN (R 4.0.2)                     
    #>  vctrs         0.3.4      2020-08-29 [1] CRAN (R 4.0.2)                     
    #>  withr         2.2.0      2020-04-20 [1] CRAN (R 4.0.2)                     
    #>  xfun          0.17       2020-09-09 [1] CRAN (R 4.0.2)                     
    #>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)                     
    #> 
    #> [1] C:/Users/daniel/Documents/.R/win-library
    #> [2] C:/Program Files/R/R-4.0.2/library

</details>

**Comment by edzer** [comment]
This happens at the GDAL level, [here](https://github.com/r-spatial/sf/blob/master/src/gdal_read.cpp#L75-L83): `sf` returns the name provided by GDAL whenever there is one, and that seems to vary for shapefiles.

**Comment by dpprdan** [comment]
👍 Sounds intended then. Thanks! 😄
