### ISSUE TITLE
Error on st_transform on linux

### ISSUE THREAD

**Issue by lbusett** [r-spatial/sf#1488]
Hi,

  On a Linux machine (Ubuntu 18.04) on which i updated libraries recently, with sf 0.9.5, I am seeing the following behaviour: 

``` r
nc <- system.file("shape/nc.shp", package="sf")
nc <- sf::st_read(nc, quiet = TRUE)
sf::st_transform(nc, 32633)
```

> Error in CPL_transform(x, crs, aoi, pipeline, reverse) : 
>   OGRCreateCoordinateTransformation() returned NULL: PROJ available?
> In addition: Warning messages:
> 1: In CPL_transform(x, crs, aoi, pipeline, reverse) :
>   GDAL Error 1: PROJ: proj_create_operations: SQLite error on SELECT name, description, scope, source_crs_auth_name, source_crs_code, target_crs_auth_name, target_crs_code, area_of_use_auth_name, area_of_use_code, accuracy, step1_auth_name, step1_code, step2_auth_name, step2_code, step3_auth_name, step3_code, operation_version, deprecated FROM concatenated_operation WHERE auth_name = ? AND code = ?: no such column: step1_auth_name
> 2: In CPL_transform(x, crs, aoi, pipeline, reverse) :
>   GDAL Error 6: Cannot find coordinate operations from `EPSG:4267' to `EPSG:32633'

```
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.2"        "6.2.1"         "true"         "true" 
```

This used to work before updating. Note that this works well on a windows machine but with:
```
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.4"        "6.3.1"         "true"         "true" 
```

Also, the error does not always apper. For example, reprojecting to epsg 3035 works well. 

Is this related to GDAL/PROJ versions? Any way to fix it? 

HTH

Lorenzo

Lorenzo

**Comment by edzer** [comment]
You did reinstall `sf` after updating libraries, right?

**Comment by lbusett** [comment]
I did not before, but I did now. So, working now on `sf` 0.9.6 now but seeing the same behaviour, unfortunately.

**Comment by edzer** [comment]
duplicate installations of any of the libraries GDAL, GEOS or PROJ?

**Comment by lbusett** [comment]
I do not think so, but I'll check more thoroughly. Maybe some leftover was left behind in the update.  I'll let you know.

**Comment by lbusett** [comment]
After updating again more properly libraries and reinstallin, now everything is back to "normal" with

> sf::sf_extSoftVersion()
>           GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
>        "3.8.0"        "3.0.4"        "7.0.0"         "true"         "true" 

Closing here. Sorry for bothering you.
