### ISSUE TITLE
Unable to install sf in Mac

### ISSUE THREAD

**Issue by EvelynaS** [r-spatial/sf#1493]
Hello, 
I need to get the version .9 of sf to use stars and mapsapi. I currently have the sf version 8.1. I am using a macOS Catalina, and my R version is 1.1.463

my current sf is linked to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0 and  my rgdal version is 1.48

I tried 
```
install.packages("rgdal", configure.args = c("--with-proj-lib=/usr/local/lib/", "--with-proj-include=/usr/local/include/"))

```
but I get this error

```
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/sf’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/sf’
```
I don't really understand why my gdal cannot be linked .

Thanks

**Comment by edzer** [comment]
This is not an `sf` issue. Please try installing binary, using `install.packages("rgdal", type = "mac.binary")`

**Comment by EvelynaS** [comment]
Thanks for the reply, the same error happen when installing sf

```
install.packages("sf", configure.args = "--with-proj-lib=/usr/local/lib/")
```
Is there a reason why I cannot update the sf version that I already have installed  (version 8.1)
```
sessionInfo()
Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.8-1    rgdal_1.4-8 sp_1.4-1   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4         pillar_1.3.1       compiler_3.5.2     class_7.3-14       prettyunits_1.0.2  remotes_2.2.0     
 [7] tools_3.5.2        pkgbuild_1.0.5     tibble_2.1.3       lattice_0.20-38    pkgconfig_2.0.2    rlang_0.4.5       
[13] Matrix_1.2-15      cli_1.1.0          DBI_1.0.0          rstudioapi_0.9.0   curl_3.3           yaml_2.2.0        
[19] xfun_0.4           e1071_1.7-0        dplyr_0.8.5        knitr_1.25         classInt_0.4-2     grid_3.5.2        
[25] tidyselect_0.2.5   glue_1.3.0         data.table_1.12.8  R6_2.3.0           processx_3.4.1     purrr_0.2.5       
[31] callr_3.3.2        magrittr_1.5       units_0.6-2        codetools_0.2-15   ps_1.3.0           assertthat_0.2.0  
[37] KernSmooth_2.23-15 crayon_1.3.4

```

**Comment by rsbivand** [comment]
On MacOS, only install CRAN binary packages. If you try to install source, it is your responsibility to install all the external dependencies (not R packages) yourself (and to keep them updated). If you installed the **sf** you have from the CRAN MacOS repository, all the functions from external libraries were included in a static build, and cannot be used to update just the R package.

**Comment by EvelynaS** [comment]
> This is not an `sf` issue. Please try installing binary, using `install.packages("rgdal", type = "mac.binary")`
@edzer 
It happens the same when I use 
```
install.packages("sf", configure.args = "--with-proj-lib=/usr/local/lib/")
```

I get
```
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/sf’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/sf’
```
Is there any way to link sf  installation to my gdal file?

**Comment by Nowosad** [comment]
@EvelynaS it seems that you are using out-dated R version. I would suggest you to start by updating your R to the current version.
