### ISSUE TITLE
error when installing in R4.0.2

### ISSUE THREAD

**Issue by ZHIDIHUAYUAN** [r-spatial/sf#1497]
Hi,
When I ran the command `install.packages("sf")`, I got
`试开URL’https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/sf_0.9-6.tar.gz'
Content type 'application/octet-stream' length 4160758 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

* installing *source* package ‘sf’ ...
** 成功将‘sf’程序包解包并MD5和检查
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /usr/local/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.0.1
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 2.0.1
configure: pkg-config proj exists, will use it
checking proj_api.h usability... yes
checking proj_api.h presence... yes
checking for proj_api.h... yes
configure: PROJ: 4.8.0
checking for pj_init_plus in -lproj... yes
checking PROJ: epsg found and readable... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.4.2
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib64 -lgeos_c... yes
configure: Package CPP flags:    -I/usr/local/include -I/usr/include
configure: Package LIBS: -lproj     -L/usr/local/lib -lgdal -L/usr/lib64 -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/home/apps/R/4.0.2/lib64/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I'/home/apps/R/4.0.2/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/home/apps/R/4.0.2/lib64/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I'/home/apps/R/4.0.2/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c bbox.cpp -o bbox.o
g++ -std=gnu++11 -I"/home/apps/R/4.0.2/lib64/R/include" -DNDEBUG -I/usr/local/include -I/usr/include -I'/home/apps/R/4.0.2/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdal.cpp -o gdal.o
In file included from gdal.cpp:1:0:
./gdal.h:3:1: 错误：‘OGRSpatialReference’不是一个类型名
 OGRSpatialReference *handle_axis_order(OGRSpatialReference *sr);
 ^
./gdal.h:4:1: 错误：‘Rcpp’不是一个类型名
 Rcpp::List create_crs(const OGRSpatialReference *ref, bool set_input);
 ^
make: *** [gdal.o] 错误 1
ERROR: compilation failed for package ‘sf’
* removing ‘/amber/users/myzhou/R/x86_64-pc-linux-gnu-library/4.0/sf’

下载的程序包在
	‘/tmp/RtmpDjam85/downloaded_packages’里
Warning message:
In install.packages("sf") : 安装程序包‘sf’时退出狀態的值不是0`

I don't know how to deal with it, please help me!

**Comment by edzer** [comment]
It would help if the error messages were translated, but although the GDAL/GEOS/PROJ versions are the minimum ones specified so should in principle work, it is recommended to install more modern releases of these libraries on your system.

**Comment by ZHIDIHUAYUAN** [comment]
> It would help if the error messages were translated, but although the GDAL/GEOS/PROJ versions are the minimum ones specified so should in principle work, it is recommended to install more modern releases of these libraries on your system.

Thank you very much!
After I updated these libraries, everything is going well now.

**Comment by wuzhigui** [comment]
Well , I have the same error  with you ! 
![image](https://user-images.githubusercontent.com/70992194/114527615-c7fb2400-9c7a-11eb-8fe0-ac958778e2e2.png)
And  there  is my R information 
![image](https://user-images.githubusercontent.com/70992194/114527786-f37e0e80-9c7a-11eb-801a-70ac15219b1c.png)

**Comment by edzer** [comment]
Looks like an Rcpp problem, not a problem with `sf`.
