### ISSUE TITLE
sf::st_join very slow compared to sp::over

### ISSUE THREAD

**Issue by andybeet** [r-spatial/sf#1498]
**Using `sp`**

* data.table with 2.5 million records. Each record has a LAT and LON.
* convert to spatial data frame (sp::coordinates), then transform to a crs (sp::spTransform)
* shapefile (set of polygons) is read in using rgdal::readOGR and also transformed to the same crs
* use sp::over to assign points to polygon.

*This takes < 2 seconds to complete.*

**Using `sf`**

* convert the data.table to sf object (sf::st_as_sf using LAT, LON and crs)
* read in shapefile as sf object (sf::st_read) and convert to same crs (sf::st_set_crs(crs))
* sf::st_join(x,y,join = sf::st_intersects)

*This takes a 1m 20 s to complete*

Wondering why these times are so different. I am trying to shift 100% of my effort to using sf. This makes it difficult

**Comment by edzer** [comment]
The data representation is very different in sf (each point is a classed list element, in sp points are all in an n x 2 matrix), and the code called is dfferent (GEOS for sf, legacy O'Rourke routines for sp). Have you tried whether there's a timing difference in computing `st_intersects(x, y)` and `st_intersects(y, x)`, and adding `prepared=TRUE` or `prepared=FALSE` in both cases?

**Comment by andybeet** [comment]
So i profiled (profvis) the code

|join|prepared|time(s)|
|---|---|---|
|st_intersects(points, poly)| T|148|
|st_intersects(points, poly)| F|118|
|st_intersects(poly, points)| T|31|
|st_intersects( poly,points)| F|95|

So an improvement but still pretty slow
