### ISSUE TITLE
Compilation failed for package 'sf' in R3.6.1 on CentOS8

### ISSUE THREAD

**Issue by NK1119** [r-spatial/sf#1499]
Hi,

I tried installing sf in R3.6.1 with install.packages("sf") on CentOS8, but entounterd errors about "proj.o".
I already installed gdal-3.0, geos-3.7, and proj-6.3.

Can I take your help to install sf?

Thanks

---
> install.packages("sf")
 URL 'https://cran.ism.ac.jp/src/contrib/sf_0.9-6.tar.gz' 
Content type 'application/x-gzip' length 4160758 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

* installing *source* package ‘sf’ ...
**  Successfully decompressed package 'sf' and validated the MD5 package 
** using staged installation
configure: CC: /home/nishitsuji/local/src/miniconda3/envs/monocle/bin/x86_64-conda_cos6-linux-gnu-cc
configure: CXX: /home/nishitsuji/local/src/miniconda3/envs/monocle/bin/x86_64-conda_cos6-linux-gnu-c++
checking for gdal-config... /home/nishitsuji/local/src/miniconda3/envs/monocle/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.3.3
checking GDAL version >= 2.0.1... yes
checking for gcc... /home/nishitsuji/local/src/miniconda3/envs/monocle/bin/x86_64-conda_cos6-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /home/nishitsuji/local/src/miniconda3/envs/monocle/bin/x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
checking for /home/nishitsuji/local/src/miniconda3/envs/monocle/bin/x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /home/nishitsuji/local/src/miniconda3/envs/monocle/bin/x86_64-conda_cos6-linux-gnu-cpp
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /home/nishitsuji/local/src/miniconda3/envs/monocle/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 2.3.3
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 6.3.2
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
/home/nishitsuji/local/src/miniconda3/envs/monocle/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lproj
collect2: error: ld returned 1 exit status
./configure: line 3870: ./proj_conf_test: No such file or directory
checking for geos-config... /home/nishitsuji/local/src/miniconda3/envs/monocle/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.7.1
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/home/nishitsuji/local/src/miniconda3/envs/monocle/lib -lgeos_c... yes
configure: Package CPP flags:   -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include
configure: Package LIBS: -lproj    -L/home/nishitsuji/local/src/miniconda3/envs/monocle/lib -lgdal -L/home/nishitsuji/local/src/miniconda3/envs/monocle/lib -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c bbox.cpp -o bbox.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c gdal.cpp -o gdal.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c gdal_geom.cpp -o gdal_geom.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c gdal_read.cpp -o gdal_read.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c gdal_utils.cpp -o gdal_utils.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c gdal_write.cpp -o gdal_write.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c geos.cpp -o geos.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c hex.cpp -o hex.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c ops.cpp -o ops.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c polygonize.cpp -o polygonize.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/include" -DNDEBUG -DHAVE_PROJ_H -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -I"/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/Rcpp/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -Wl,-rpath-link,/home/nishitsuji/local/src/miniconda3/envs/monocle/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/nishitsuji/local/src/miniconda3/envs/monocle/include -fdebug-prefix-map=/tmp/build/80754af9/r-base_1570124924484/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/nishitsuji/local/src/miniconda3/envs/monocle=/usr/local/src/conda-prefix  -c proj.cpp -o proj.o
proj.cpp: In function 'Rcpp::LogicalVector CPL_set_data_dir(std::__cxx11::string)':
proj.cpp:31:2: error: 'proj_context_set_search_paths' was not declared in this scope
  proj_context_set_search_paths(PJ_DEFAULT_CTX, 1, &cp);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
proj.cpp:31:2: note: suggested alternative: 'proj_context_destroy'
  proj_context_set_search_paths(PJ_DEFAULT_CTX, 1, &cp);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  proj_context_destroy
proj.cpp: In function 'Rcpp::LogicalVector CPL_use_proj4_init_rules(Rcpp::IntegerVector)':
proj.cpp:36:2: error: 'proj_context_use_proj4_init_rules' was not declared in this scope
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, v[0]);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
proj.cpp:36:2: note: suggested alternative: 'CPL_use_proj4_init_rules'
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, v[0]);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CPL_use_proj4_init_rules
proj.cpp: In function 'Rcpp::List CPL_proj_is_valid(std::__cxx11::string)':
proj.cpp:50:2: error: 'proj_context_use_proj4_init_rules' was not declared in this scope
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
proj.cpp:50:2: note: suggested alternative: 'CPL_use_proj4_init_rules'
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CPL_use_proj4_init_rules
proj.cpp: In function 'Rcpp::NumericMatrix CPL_proj_direct(Rcpp::CharacterVector, Rcpp::NumericMatrix, bool, bool, bool)':
proj.cpp:83:2: error: 'proj_context_use_proj4_init_rules' was not declared in this scope
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
proj.cpp:83:2: note: suggested alternative: 'CPL_use_proj4_init_rules'
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CPL_use_proj4_init_rules
proj.cpp:88:7: error: 'proj_normalize_for_visualization' was not declared in this scope
   P = proj_normalize_for_visualization(PJ_DEFAULT_CTX, P);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/etc/Makeconf:175: proj.o] Error 1
ERROR: compilation failed for package ‘sf’
* removing ‘/home/nishitsuji/local/src/miniconda3/envs/monocle/lib/R/library/sf’

installation of package ‘sf’ had non-zero exit status 

--

**Comment by edzer** [comment]
Two observations: (i) you are using conda, so maybe you need to ask help at the conda/R community rather than here, (ii) you are mixing GDAL 2.3.3 and PROJ 6.3.1; with such a new PROJ version it may work better if you would use a GDAL 3.x.x version.

**Comment by NK1119** [comment]
Thank you for your reply.

(i) I use conda to switch environments.
(ii) Unistalling GDAL3 and PROJ6 and installing GEOS 3.7.1, GDAL 2.3.3, and PROJ 6.3.2 could solve this issue.

Thanks

**Comment by rsbivand** [comment]
No, mixing GDAL 2.3.3, and PROJ 6.3.2 is dangerous. Use PROJ < 6 with GDAL < 3, PROJ >= 6 with GDAL >= 3. It may appear to work, but will only lead to more trouble later. Either stay fully in the past, or move to the present, don't mix the two.
