### ISSUE TITLE
Masking Error with Unused SRS_string Argument

### ISSUE THREAD

**Issue by AyrtonB** [r-spatial/sf#1500]
Hi All,

I'm trying to mask a raster with a shapefile and keep encountering an error related to SRS_string being unused, any help/guidance would be much appreciated.

I'm reading in datasets with different CRS', transforming the shapefile to the same CRS as the raster, then trying to mask the raster.

```R
library(sf)
library(raster)

df_zambia <- read_sf('../data/zambia/zambia.shp')
solar <- raster('../data/africa/solar.tif')

df_zambia_4326 <- st_transform(df_zambia, crs=st_crs(solar))

mask(solar, df_zambia_4326)
```

However this is the error that is returned.

```R
Error in sp::CRS(SRS_string = from$wkt): unused argument (SRS_string = from$wkt)
Traceback:

1. mask(solar, df_zambia_4326)
2. mask(solar, df_zambia_4326)
3. .sf2sp(mask)
4. as(from, "Spatial")
5. asMethod(object)
6. sp::addAttrToGeom(as_Spatial(geom, IDs = row.names(from)), data.frame(from), 
 .     match.ID = FALSE)
7. as_Spatial(geom, IDs = row.names(from))
8. .as_Spatial(from, cast, IDs)
9. sfc2SpatialPolygons(from, IDs)
10. sp::SpatialPolygons(l, proj4string = as(st_crs(from), "CRS"))
11. stopifnot(is(proj4string, "CRS"))
12. is(proj4string, "CRS")
13. as(st_crs(from), "CRS")
14. asMethod(object)
15. CRS_from_crs(from)
16. comment(sp::CRS(SRS_string = from$wkt))
```

Before masking they are in the same CRS and don't appear to have any issues

![image](https://user-images.githubusercontent.com/29051639/94684086-74993800-031f-11eb-833b-3b4574c86132.png)

Any help would be much appreicated!

**Comment by edzer** [comment]
If this persists after you update package `sp`, please send the output of `sessionInfo()`.

**Comment by rsbivand** [comment]
Report `sessionInfo()`. **raster** imports **sp** and uses **rgdal**, so if your **sp** and **rgdal** are stale (and if you install **rgdal** from source the versions of PROJ and GDAL), your workflow will be using unaligned packages. So report `sessionInfo()`, say how you installed **sf** and **rgdal**, and report `sf::sf_extSoftVersion()` and `rgdal::rgdal_extSoftVersion()`. Certainly your **sp** is outdated. Do you run `update.packages()` frequently?

**Comment by AyrtonB** [comment]
Thanks for the quick reply! After reinstalling `sp` the error persists but changes slightly

```R
Error in sp::CRS(SRS_string = from$wkt): no arguments in initialization list
Traceback:

1. mask(solar, df_zambia_4326)
2. mask(solar, df_zambia_4326)
3. .sf2sp(mask)
4. as(from, "Spatial")
5. asMethod(object)
6. sp::addAttrToGeom(as_Spatial(geom, IDs = row.names(from)), data.frame(from), 
 .     match.ID = FALSE)
7. as_Spatial(geom, IDs = row.names(from))
8. .as_Spatial(from, cast, IDs)
9. sfc2SpatialPolygons(from, IDs)
10. sp::SpatialPolygons(l, proj4string = as(st_crs(from), "CRS"))
11. stopifnot(is(proj4string, "CRS"))
12. is(proj4string, "CRS")
13. as(st_crs(from), "CRS")
14. asMethod(object)
15. CRS_from_crs(from)
16. comment(sp::CRS(SRS_string = from$wkt))
17. sp::CRS(SRS_string = from$wkt)
18. stop(res[[2]])
```

My session is as follows

```R
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] zeallot_0.1.0 ggplot2_3.1.1 raster_2.8-19 sp_1.4-2      dplyr_0.8.0.1
[6] stars_0.4-1   abind_1.4-5   sf_0.9-6     

loaded via a namespace (and not attached):
 [1] pbdZMQ_0.3-3       tidyselect_0.2.5   repr_0.19.2        purrr_0.3.2       
 [5] lattice_0.20-38    V8_2.3             colorspace_1.4-1   htmltools_0.3.6   
 [9] base64enc_0.1-3    rlang_0.3.4        e1071_1.7-1        pillar_1.3.1      
[13] foreign_0.8-71     glue_1.3.1         httpcode_0.2.0     withr_2.1.2       
[17] DBI_1.0.0          uuid_0.1-2         plyr_1.8.4         geojsonio_0.9.2   
[21] rgeos_0.5-1        munsell_0.5.0      gtable_0.3.0       codetools_0.2-16  
[25] evaluate_0.13      maptools_0.9-5     parallel_3.6.1     curl_3.3          
[29] class_7.3-15       IRdisplay_0.7.0    Rcpp_1.0.1         KernSmooth_2.23-15
[33] scales_1.0.0       classInt_0.4-3     lwgeom_0.1-7       IRkernel_0.8.15   
[37] jsonlite_1.6       digest_0.6.18      grid_3.6.1         rgdal_1.4-4       
[41] jqr_1.1.0          tools_3.6.1        magrittr_1.5       lazyeval_0.2.2    
[45] geojson_0.3.4      tibble_2.1.1       crul_1.0.0         crayon_1.3.4      
[49] pkgconfig_2.0.2    assertthat_0.2.1   R6_2.4.0           units_0.6-2       
[53] compiler_3.6.1  
```

**Comment by AyrtonB** [comment]
I reinstalled the entire environment from scratch a couple of hours ago so was surprised the latest version of `sp` wasn't being used. This may be related to the fact I'm using Conda.

The environment.yml that I'm using is:

```
name: ESDA-Spatial

channels:
    - r
    - conda-forge

dependencies:
    - jupyterlab
    - nbclient
    - r-base
    - r-essentials
    - r-sf
    - r-raster
    - r-spatstat
    - r-geojsonio
    - r-leaflet
    - r-gsubfn
    - r-zeallot
    - r-tmap
    - r-rgdal
    - r-kernsmooth
    - pip
    
    - pip:
        - sphinx-thebe
```

**Comment by rsbivand** [comment]
Obviously, because **sf** and **rgdal** for Windows are installed as binaries from CRAN. Installing from source will also draw in by download for static built GDAL. PROJ and GEOS, so neither **sf** nor **rgdal** will use conda libraries. Your **raster** is very out of date. I suggest abandoning conda as it is certainly a problem, and install all needed packages from CRAN at their latest versions. Seriously consider upgrading R, your version is very old.

**Comment by AyrtonB** [comment]
Thanks for the recommendations will try them out.

The thinking behind using Conda was that for Python at least it is highly useful in resolving package conflicts and within the Python spatial ecosystem manages the necessary versions of GDAL, PROJ etc, it seems this isn't the case for R. Conda does use CRAN for r-packages though, e.g. with [sf ](https://anaconda.org/conda-forge/r-sf) and [rgdal](https://anaconda.org/conda-forge/r-rgdal), so I'm confused as to why it wouldn't be downloading the static builds in the same way.

**Comment by rsbivand** [comment]
CRAN is the system which removes the need for conda. Elsewhere, e.g. Python, package management is chaotic, needing intermediating systems to handle dependencies between binary components. In R, CRAN does this. For the Windows and MacOS platforms, fairly recent GDAL. PROJ and GEOS libraries are used, and static-linked to CRAN binaries. There are issues when users say use QGIS through OSGeo4W, because the versions of the external libraries may not be the same.

**Comment by AyrtonB** [comment]
Thanks for the explanation. I've just retried in a new environment which didn't have QGIS and that's solved my original issue

**Comment by edzer** [comment]
Maybe you can communicate this back to those who told you how to (not) do an R + QGIS conda setup.
