### ISSUE TITLE
Points from st_line_sample are not on the line

### ISSUE THREAD

**Issue by mem48** [r-spatial/sf#1503]
I want to split a linestring into three equal segments, so I used `st_line_sample(l,2)`  to get two points on the line.

When plotted it looks fine

![image](https://user-images.githubusercontent.com/15819577/94955334-4f085c00-04e2-11eb-999f-843643445aa7.png)

But the points are actually very slightly off the line, thus functions like `lwgeom::st_split` don't work.

```
# Make a line
set.seed(123)
x = seq(1:10)
y = x + rnorm(1:10, sd = 0.5)
l <- st_linestring(matrix(c(x,y), ncol = 2))

# Sample points on the line
pt <- st_line_sample(l,2)

# looks ok
plot(l)
plot(pt, add = T)

# but is not on the line
st_intersects(l, pt)
Sparse geometry binary predicate list of length 1, where the predicate was `intersects'
 1: (empty)
> st_distance(l, pt)
             [,1]
[1,] 2.887361e-16
```

Session Info:

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.9-6

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1         rstudioapi_0.11    magrittr_1.5       units_0.6-7        tidyselect_1.1.0  
 [6] R6_2.4.1           rlang_0.4.6        fansi_0.4.1        dplyr_1.0.0        tools_4.0.0       
[11] grid_4.0.0         KernSmooth_2.23-16 cli_2.0.2          e1071_1.7-3        DBI_1.1.0         
[16] ellipsis_0.3.1     class_7.3-16       assertthat_0.2.1   tibble_3.0.1       lifecycle_0.2.0   
[21] crayon_1.3.4       purrr_0.3.4        vctrs_0.3.1        glue_1.4.1         compiler_4.0.0    
[26] pillar_1.4.4       generics_0.0.2     classInt_0.4-3     pkgconfig_2.0.3   
```

**Comment by edzer** [comment]
You may want to look into `st_set_precision`.

**Comment by mem48** [comment]
First I got the error

```
Error in UseMethod("st_precision") : 
  no applicable method for 'st_precision' applied to an object of class "c('XY', 'LINESTRING', 'sfg')"
```

So I added `l <- st_sfc(list(l))` then `st_set_precision(l, 1e6)` using a range of values from very large to very small. But it made no difference.

**Comment by rsbivand** [comment]
Is this related to **rgeos** `gProject()` and `gInterpolate()` for linear reference? The outcomes still do not intersect the line, which suggests that since the line has infinitely small width, nothing will intersect it.

**Comment by mem48** [comment]
Does that mean it is not possible to get points on the line? From a mathematical perspective, their should be infinite points that intersect any line.

**Comment by edzer** [comment]
Welcome to the world of floating point arithmetic.

**Comment by agila5** [comment]
Hi @mem48! I didn't check the issue on `saferactive` (so maybe the following example is useless), but if you want to divide a linestring into n parts, I think you can apply something like this: 

``` r
# packages
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(lwgeom)
#> Linking to liblwgeom 3.0.0beta1 r16016, GEOS 3.8.0, PROJ 6.3.1

# fake data
set.seed(123)
x <- seq(1:10)
y <- x + rnorm(1:10, sd = 0.5)
l <- st_linestring(matrix(c(x,y), ncol = 2))

# plot
plot(l)
```

![](https://i.imgur.com/K0wXL2P.png)

``` r

# Divide l into three parts of "approximately" equal length
l1 <- st_linesubstring(l, 0, 0.33)
l2 <- st_linesubstring(l, 0.33, 0.66)
l3 <- st_linesubstring(l, 0.66, 1)

# plot them
plot(l, col = "white", reset = FALSE)
plot(l1, col = "darkred", reset = FALSE, add = TRUE)
plot(l2, col = "darkblue", reset = FALSE, add = TRUE)
plot(l3, col = "darkgreen", reset = FALSE, add = TRUE)
```

![](https://i.imgur.com/bp4rCZw.png)

``` r

# lengths
st_length(l1); st_length(l2); st_length(l3)
#> [1] 4.424614
#> [1] 4.424614
#> [1] 4.558693
```

<sup>Created on 2020-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I added more details [here](https://github.com/ropensci/stplanr/issues/359), but I think I won't work on that problem for at least a few months.

**Comment by mem48** [comment]
Thanks @agila5  I'd come to a similar conclusion. @edzer unless you have any other suggestions I'll close the issue as this doesn't seem to be fixable.

**Comment by ratnanil** [comment]
> I'll close the issue as this doesn't seem to be fixable.

So setting precision is not a viable solution?

I want to do precisely the same thing (split a line segment by regular points on the line), and using `st_linesubstring` does not seem right.

**Comment by agila5** [comment]
Hi @ratnanil! If you are working with spatial networks, please check [`st_network_blend()`](https://luukvdmeer.github.io/sfnetworks/reference/st_network_blend.html).

**Comment by luukvdmeer** [comment]
In the sfnetworks vignettes I also show the problem described in this issue. Even the intersection of two lines as computed by `st_intersection` may not be evaluated as intersecting those lines themselves when using `st_intersects`. See here: https://luukvdmeer.github.io/sfnetworks/articles/sfn03_join_filter.html#blending-points-into-a-network
