### ISSUE TITLE
st_write cannot write more than 998 columns

### ISSUE THREAD

**Issue by jstrunk001** [r-spatial/sf#1506]
The error isn't terribly informative, but I have determined that 998 columns is ok, and 999 or more is not

> sf::st_write(stands_sf , dsn = paste(dir_fps,"\\SRS_predictions_stands_20201007.gpkg",sep=""), layer = "lidar_inventoryde", driver = "GPKG",overwrite_layer = T)
Writing layer `lidar_inventoryde' to data source `D:\Box\VMARS\Projects\2019 Savannah River\R\Jacob Post-Stratification Evaluation\data\FPS Input\version_3\SRS_predictions_stands_20201007.gpkg' using driver `GPKG'
Writing 5 features with 999 fields and geometry type Polygon.
Failed to create feature 0 in lidar_inventoryde
writing first to temporary file C:\Users\...\AppData\Local\Temp\RtmpWqvxFn\file51fc2c8137e6.gpkg
Writing layer `lidar_inventoryde' to data source `C:\Users\...\AppData\Local\Temp\RtmpWqvxFn\file51fc2c8137e6.gpkg' using driver `GPKG'
Writing 5 features with 999 fields and geometry type Polygon.
Failed to create feature 0 in lidar_inventoryde
Error in st_write.sf(stands_sf, dsn = paste(dir_fps, "\\SRS_predictions_stands_20201007.gpkg",  : 
  failed writing to temporary file C:\Users\...\AppData\Local\Temp\RtmpWqvxFn\file51fc2c8137e6.gpkg
In addition: Warning messages:
1: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 1: failed to prepare SQL: INSERT INTO "lidar_inventoryde" ( "geom", "OBJECTID", "SPATIAL_ID", "STAND_ID", "ACRES", "YEAR_OF_OR", "STAND_AGE", "ID", "OBJECTID_1", "x", "y", "Elev_P95", "Elev_P20", "cover_2", "Profile_area", "HWProportion", "ba_sw_saw_ge9", "ba_sw_saw_ge13", "ba_sw_nonsaw_d5to13", "ba_hw_saw_ge12", "vol_sw_saw_ge9", "vol_sw_saw_ge13", "vol_sw_nonsaw_d5to13", "vol_hw_saw_ge12", "ba_sw_pulp_d5to8", "ba_hw_pulp_d6to11", "vol_sw_pulp_d5to8", "vol_hw_pulp_d6to11", "ba_hs_l_tp", "ba_hw_l_tp", "ba_sw_l_tp", "vol_hs_l_tp", "vol_hw_l_tp", "vol_sw_l_tp", "bbm_hs_l_tp", "bbm_hw_l_tp", "bbm_sw_l_tp", "den_hs_l_tp", "den_hw_l_tp", "den_sw_l_tp", "lor_hs_l_tp", "lor_hw_l_tp", "lor_sw_l_tp", "t40_hs_l_tp", "t40_hw_l_tp", "t40_sw_l_tp", "mht_hs_l_tp", "mht_hw_l_tp", "mht_sw_l_tp", "med_hs_l_tp", "med_hw_l_tp", "med_sw_l_tp", "qmd_hs_l_tp", "qmd_hw_l_tp", "qmd_sw_l_tp", "ba_hs_d_tp", "ba_hw_d_tp", "ba_sw_d_tp", "vol_hs_d_tp", "vol_hw_d_tp", "vol_sw_d_tp", "bbm_hs_d_tp", "bbm_h [... truncated]
2: In CPL_write_ogr(obj, tmp, layer, driver, as.character(dataset_options),  :
 
 Error in st_write.sf(stands_sf, dsn = paste(dir_fps, "\\SRS_predictions_stands_20201007.gpkg",  : 
  failed writing to temporary file C:\Users\...\AppData\Local\Temp\RtmpWqvxFn\file51fc2c8137e6.gpkg

**Comment by edzer** [comment]
Sounds like a limiitation of the GDAL driver and/or SQLITE. What makes you think the issue is with `sf`?

**Comment by jstrunk001** [comment]
I think you may be right. I just encountered the same issue with rgdal and arcgisbindings packages – although arcgisbindings actually told me the bds was limited in the number of columns.

I don’t well understand the interplay between drivers etc. so I figured that sf carried around the drivers for writing to SQLite rather than using rgdal drivers…

Cheers!

[Forest Service Shield]
Jacob Strunk, PhD
Statistician
Forest Service
PNW Research Station, Vegetation Monitoring and Remote Sensing Team (VMaRS)
p: 206-503-0665
jacob.strunk@usda.gov<mailto:jacob.strunk@usda.gov>
3625 93rd Ave SW
Olympia, WA 98512
www.fs.fed.us<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.fs.fed.us%2F&data=02%7C01%7C%7C23b2297a8bc3463bb2d008d727a6bed1%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637021470872207468&sdata=0PL4U2IQtoOxR5z4Bofo9pY1oKiVwMSrulxmJtROk%2Bs%3D&reserved=0>
[USDA Logo]<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fusda.gov%2F&data=02%7C01%7C%7C23b2297a8bc3463bb2d008d727a6bed1%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637021470872217463&sdata=oqnCO30huLZ%2BnxGYpLG8ElpZXhlaUlebnT5g4d2pilM%3D&reserved=0> [Forest Service Twitter] <https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fforestservice&data=02%7C01%7C%7C23b2297a8bc3463bb2d008d727a6bed1%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637021470872227460&sdata=qNfffSQ5nK7oyOSmTnJPHOMYaAQ%2FUL8nXrk6zeGQIIM%3D&reserved=0>  [USDA Facebook] <https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2Fpages%2FUS-Forest-Service%2F1431984283714112&data=02%7C01%7C%7C23b2297a8bc3463bb2d008d727a6bed1%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637021470872227460&sdata=rLirJWbIskQ41ovVc04enJ04NG3luhIlPjFkgaZve6Q%3D&reserved=0>
Caring for the land and serving people

**Comment by edzer** [comment]
That is true, `sf` doesn't use `rgdal`, but the problem is in the underlying software (GDAL, sqlite3). If you would recompile sqlite with a larger maxiumum and then recompile GDAL against that, and then compile sf against that, you could probably write more columns. `sf` doesn't have the means to check all that.

**Comment by rsbivand** [comment]
The default SQLite maximum number of columns is 2000 https://sqlite.org/limits.html. With:

```
library(sf)
m <- matrix(1:2000, nrow=1)
df <- as.data.frame(m)
df$x <- df$y <- 1
sf_obj <- st_as_sf(df, coords=c("x", "y"))
st_write(sf_obj[,1:1998], "df.gpkg") # succeeds
st_write(sf_obj[,1:1999], "df.gpkg") # fails (geometry column and FID?)
```
You'd need to state how you installed **sf** (CRAN binary - platform?, or source), if source how SQLite and GDAL were installed. I think you mean 1998/1999, not 998/999. Show `dim(sf_obj)`.

**Comment by jstrunk001** [comment]
Thanks for sharing. I also saw the defaults for sqlite, but my limit is actually 998 columns (rather than 2000).  Strangely this holds for all 3 of rgdal, sf, and arcgisbindings

Another user had similar issues:
https://gis.stackexchange.com/questions/314500/does-geopackage-impose-a-maximum-number-of-non-geometry-columns-per-feature



[Forest Service Shield]
Jacob Strunk, PhD
Statistician
Forest Service
PNW Research Station, Vegetation Monitoring and Remote Sensing Team (VMaRS)
p: 206-503-0665
jacob.strunk@usda.gov<mailto:jacob.strunk@usda.gov>
3625 93rd Ave SW
Olympia, WA 98512
www.fs.fed.us<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.fs.fed.us%2F&data=02%7C01%7C%7C23b2297a8bc3463bb2d008d727a6bed1%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637021470872207468&sdata=0PL4U2IQtoOxR5z4Bofo9pY1oKiVwMSrulxmJtROk%2Bs%3D&reserved=0>
[USDA Logo]<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fusda.gov%2F&data=02%7C01%7C%7C23b2297a8bc3463bb2d008d727a6bed1%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637021470872217463&sdata=oqnCO30huLZ%2BnxGYpLG8ElpZXhlaUlebnT5g4d2pilM%3D&reserved=0> [Forest Service Twitter] <https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fforestservice&data=02%7C01%7C%7C23b2297a8bc3463bb2d008d727a6bed1%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637021470872227460&sdata=qNfffSQ5nK7oyOSmTnJPHOMYaAQ%2FUL8nXrk6zeGQIIM%3D&reserved=0>  [USDA Facebook] <https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2Fpages%2FUS-Forest-Service%2F1431984283714112&data=02%7C01%7C%7C23b2297a8bc3463bb2d008d727a6bed1%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637021470872227460&sdata=rLirJWbIskQ41ovVc04enJ04NG3luhIlPjFkgaZve6Q%3D&reserved=0>
Caring for the land and serving people

**Comment by rsbivand** [comment]
I did ask you to report on how you installed **sf**. If you state that, maybe it will be clearer why your SQLite, linked to the GPKG driver in GDAL, is using the non-standard 1000 limit rather than 2000. Please reply in github, not by email, which pollutes the github issue with extraneous USDA verbiage and "protected" links.

**Comment by jstrunk001** [comment]
I used install.packages("sf") in R version 4.0.2. I am running R from within RStudio if that has any bearing.

**Comment by rsbivand** [comment]
What is your platform?? Windows, MacOS, what? For Windows and MacOS, CRAN binaries have static linked SQLite that we sort of control, and can check whether the default column limit is changed. If you installed **sf** from source (homebrew, Linux, conda), SQLite is your responsibility. So if Windows CRAN binary, we know where to look, MacOS CRAN binary perhaps we know, otherwise not.

**Comment by jstrunk001** [comment]
This is on 64 bit Windows 10 and is 64 bit R. I am pulling packages from CRAN.

**Comment by rsbivand** [comment]
Thanks, that has narrowed down the problem. I'll do the same test on Windows with the CRAN **sf** binary tomorrow (my time), and folllow up from there. I don't immediately see the limit being changed in https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-sqlite3/PKGBUILD, but if I can replicate the issue, we know who to ask.

**Comment by jstrunk001** [comment]
Awesome! Thanks for checking into this issue!

**Comment by rsbivand** [comment]
@edzer @jeroen : the rwinlib SQLite library appears to limit the number of columns to about 1000, rather than the 2000 default columns. This appears to be a compile-time choice; I cannot immediately see where in the build script this is set, but it may follow from other build flags, perhaps. The use case seems  to be monitoring many species at sample locations. It would be very helpful for this use to revert to the default of 2000 (as on Linux, in my case the standard Fedora SQLite rpm). It does not seem to be the GDAL GPKG driver, which takes 1998 on my system, but 998 on Windows for **sf** (and **rgdal** takes 997, because it imposes a FID I think). The same limits apply to the GDAL SQLite driver.

**Comment by jeroen** [comment]
@rsbivand ok, can you try to send a PR to https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-sqlite3/PKGBUILD to fix it?

**Comment by rsbivand** [comment]
@edzer - do you have access to someone with current Windows development experience? I have no idea how to write or test a PKGBUILD.

**Comment by jeroen** [comment]
You don't need experience, just edit line 29 with the  compile `CFLAGS` to add the `SQLITE_MAX_COLUMN` field.

**Comment by rsbivand** [comment]
I'll try to see what limits are reported by the existing library archive, and go from there. Before changing the PKGBUILD file, I'd like to know that the fix works. Without `SQLITE_MAX_COLUMN` defined, the default should be 2000.

**Comment by rsbivand** [comment]
I  know nothing of SQL, and too little of the build train. Without knowing that the edit actually fixes the problem, I am reluctant to proceed. I do not understand why the limit given in the code (the old version pulled in PKGBUILD) is not used.

**Comment by jeroen** [comment]
OK I can do it, can you provide a minimal example in R that allows me to reproduce the problem, so I can verify that is is fixed?

**Comment by rsbivand** [comment]
Thanks, this is what I've been using. Currently only passes on Windows with `sf_obj[, 1:998]`:

```
library(sf)
m <- matrix(1:2000, nrow=1)
df <- as.data.frame(m)
df$x <- df$y <- 1
sf_obj <- st_as_sf(df, coords=c("x", "y"))
tf <- tempfile(fileext=".gpkg")
st_write(sf_obj[, 1:2000], tf, append=FALSE) # should fail
st_write(sf_obj[, 1:1999], tf, append=FALSE) # should fail
st_write(sf_obj[, 1:1998], tf, append=FALSE) # should succeed for default 2000 max. columns
```

**Comment by jeroen** [comment]
OK I have updated the rwinlib binaries, the problem should be gone for new builds. It may take about a week for CRAN to update binary packages for `sf` and `gdal`.

**Comment by rsbivand** [comment]
@jeroen Thanks, checked on 64-bit and 32.bit Windows, now writes 1998 columns of GPKG, 1997 to SQLite.

**Comment by rsbivand** [comment]
@jstrunk001 Could you please install RTools for your R version and check using your real use case after `install.packages("sf", type = 'source')` ?

**Comment by edzer** [comment]
At least GPKG gives an error message when maxing out column space; unlike here: https://www.verdict.co.uk/excel-coronavirus-test-data/

**Comment by jstrunk001** [comment]
Great! This works for me now! Thank you!

**Comment by jstrunk001** [comment]
> At least GPKG gives an error message when maxing out column space; unlike here: https://www.verdict.co.uk/excel-coronavirus-test-data/

Gosh, and I was thinking of moving all of my analyses to excel too 🤷‍♂️
