### ISSUE TITLE
Wrong result from st_nearest_point

### ISSUE THREAD

**Issue by nfruehADA** [r-spatial/sf#1511]
In the example provided below, the linestring which is returned by st_nearest_point is not actually the shortest connection between the given point and the linestring. 

As can be seen from plot 1, the result is correct if X and Y coordinates are interpreted as just numbers. But if the WGS 84 projection is used to to plot the data with leaflet (the coordinates initially are given in WGS 84), the second plot clearly shows that the connection is no longer the shortest one, since the angle between the linestring and the connection line is not 90 degrees. 

I do not know if this is indeed a bug or if I am missing something regarding the different projections.
```library(sf)
library(leaflet)
library(dplyr)

linestring <- st_linestring(x = matrix(c(8.7250775, 47.6282506, 
                                         8.7247244, 47.6282508, 
                                         8.7236060, 47.6281228), 
                                       nrow = 3, ncol = 2, byrow = TRUE), 
                            dim = "XY")

point <- st_point(x = c(8.724544986, 47.62806733), 
                  dim = "XY")

shortestLine <- st_nearest_points(point, linestring)

# Plot Nbr 1
plot(st_union(linestring, point) %>% st_union(shortestLine), axes = TRUE)

# Plot Nbr 2
leaflet() %>% addTiles() %>% 
  addPolylines(data = st_union(linestring, point, shortestLine) %>% 
                 st_union(shortestLine) %>% 
                 st_sfc() %>% st_set_crs(4326))
```
The plots generated look like this:
![ProblemWithStNearestPoints](https://user-images.githubusercontent.com/69671715/95845432-72d16a80-0d4a-11eb-8269-18d92d241f87.png)

**Comment by tim-salabim** [comment]
Just to be clear, leaflet does not plot in WGS84/longlat but in web-mercator (leaflet internally re-projects the data). So if you want this to be "true" in your leaflet plot, you'd need to do the `st_nearest_points` in web-mercator projection. But then you'd obviously need to re-project back to longlat to be able to plot in leaflet again... It's cumbersome, but that's how leaflet works.

**Comment by luukvdmeer** [comment]
I re-ran the example of the OP taking into consideration the hints of @tim-salabim and can confirm that works. So the issue can be closed I guess.

```r
library(leaflet)
library(dplyr)

linestring <- st_linestring(x = matrix(c(8.7250775, 47.6282506, 
                                         8.7247244, 47.6282508, 
                                         8.7236060, 47.6281228), 
                                       nrow = 3, ncol = 2, byrow = TRUE), 
                            dim = "XY")

point <- st_point(x = c(8.724544986, 47.62806733), 
                  dim = "XY")

linestring = st_sfc(linestring, crs = 4326) %>%
  st_transform(3857)

point = st_sfc(point, crs = 4326) %>%
  st_transform(3857)

shortestLine <- st_nearest_points(point, linestring)

leaflet() %>% addTiles() %>% 
  addPolylines(data = st_transform(linestring, 4326)) %>%
  addPolylines(data = st_transform(shortestLine, 4326))
```

![Rplot](https://user-images.githubusercontent.com/26540305/96455247-3f488180-121d-11eb-9dac-d12328604629.png)

**Comment by nfruehADA** [comment]
Thank you very much for your support! I will try this out myself, but you can already close the issue :)
