### ISSUE TITLE
Provide config options for install on machines with non-standard library locations

### ISSUE THREAD

**Issue by serbinsh** [r-spatial/sf#1513]
Responding to request to submit a PR to address #1471, specifically the request to provide a --with-sqlite3 like config option when running install.packages('sf', xxx).   Presently its not very easy to install when you need to use non-standard locations, such as on an HPC/shared storage system.  

It looks like you can get around this using env variables but it would be easier to provide config options.

**Comment by edzer** [comment]
Yes, such a PR would be welcome.

**Comment by rrobinson-RMS** [comment]
Hi What is the solution to this ? What env variables are you using for sql lite ?
I am have setup the following variable (to the correct file locations not list) for both sqlite3 and Proj7

 LD_LIBRARY_PATH
 LIBRARY_PATH 
 PATH 
 MANPATH 
 C_INCLUDE_PATH 
 CPLUS_INCLUDE_PAT
 INCLUDE 
 PKG_CONFIG_PATH "
 CMAKE_PREFIX_PATH
 
 This is my error
 
 checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... yes
checking GDAL: /mnt/opt/Centos7/hpc/spack/spack_Oct_2020/opt/spack/linux-centos7-broadwell/gcc-7.3.1/gdal-3.2.0-7juusgnasjeppoqamonw253tvgpeaafs/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.2.0
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 7.1.0
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
configure: error: libproj or sqlite3 not found in standard or given locations.
ERROR: configuration failed for package ���sf���
* removing ���/mnt/opt/Centos7/hpc/spack/spack_Oct_2020/opt/spack/linux-centos7-broadwell/gcc-7.3.1/r-4.0.3-tu34p762h7igt6pdf7wlfm4fnaxmxyne/rlib/R/library/sf���

The downloaded source packages are in
        ���/mnt/gpfs/tmp/R/RtmpDek6az/downloaded_packages���
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("sf") :
  installation of package ���sf��� had non-zero exit status
