### ISSUE TITLE
sf object not behaving as a data frame when trying to calculate percentage?

### ISSUE THREAD

**Issue by paragemini** [r-spatial/sf#1517]
Hey - I've asked this question on stackoverflow. and here is the link attached.

https://stackoverflow.com/questions/64445552/sf-object-not-behaving-as-a-data-frame-when-trying-to-calculate-percentage

![image](https://user-images.githubusercontent.com/13204081/96654521-1d282f80-1301-11eb-9e7f-7f8a41243e82.png)

**Comment by paragemini** [comment]
Data inherited from the previous function used names() function instead of colnames().

**Comment by edzer** [comment]
A reprex is missing, also the link to SO seems to no longer exist.
