### ISSUE TITLE
'plot' cuts long factor labels out by default (key.width)

### ISSUE THREAD

**Issue by basille** [r-spatial/sf#1521]
Assuming a simple `sf` object:

```r
library("sf")
x <- st_sf(long_factor = factor(c("Long_label_1", "Long_label_2")), geom = st_sfc(st_point(c(1,1)), st_point(c(2,2))))
```

Plotting it without any argument will cut the labels out as they stay horizontal (factors):

```r
plot(x)
```

![sf-factor](https://user-images.githubusercontent.com/4000337/97713508-50538700-1a96-11eb-9671-3aa126b7a086.png)

A manual workaround is to play with `key.pos` and `key.width` arguments (the former is necessary to set in order to keep the key to the right):

```r
plot(x, key.pos = 4, key.width = lcm(4.2))
```

![sf-keypos](https://user-images.githubusercontent.com/4000337/97713628-7b3ddb00-1a96-11eb-8648-f94d2bd5106d.png)

Would it be possible to have this behavior by default, i.e. plot of a factor adjusting `key.width` to the actual labels?

**Comment by edzer** [comment]
I'm not aware of a function that tells you the size, in cm, of a string in base plot.

**Comment by basille** [comment]
Ah, so that would necessarily be completely ad-hoc, like counting the number of characters and come up with a guesstimate of the width…

Good to know though. The initial reason for this issue is to reuse `plot.sf` for `sftrack` objects (which use a factor grouping) with sane defaults. For now, we have arbitrarily set `key.width` to `lcm(4)` if the key is on the side, but it would have been much better to rely on `sf` defaults (or on an exact approach using base plot). 

Feel free to close the issue if it does not have a clean solution.

**Comment by edzer** [comment]
I'm pretty sure ggplot gets this right.

**Comment by basille** [comment]
Yes indeed, we haven't had this problem with `ggplot2`, and the automatic resizing seems to work just fine.

**Comment by rCarto** [comment]
> I'm not aware of a function that tells you the size, in cm, of a string in base plot.

In `graphics` there is `strwidth()` and `strheight`.

**Comment by basille** [comment]
Thanks @rCarto! @edzer, would this be a solution, something you would consider for `sf`?
(it seems to require a plotting device already on display though)

**Comment by edzer** [comment]
Happy to consider a PR that doesn't make`plot.sf` more confusing than it already is.

**Comment by basille** [comment]
Ha! Fair enough. 
On quick inspection, `strwidth` does not seem too promising, as it only works with an existing display… We may come up with a simple heuristic based on `nchar`, but I cannot see how it can be bulletproof… Maybe a good reason to use `ggplot2` for the task.
