### ISSUE TITLE
Alpha geom_sf not working properly in combination with use of coord_sf

### ISSUE THREAD

**Issue by LaurentSmeets** [r-spatial/sf#1522]
I am not sure whether this bug is `sf` of `ggplot2` related, but I am posting it here. Apologies if this is a feature and not a bug and that I maybe should have uploaded it to StackExchange. Anyways, I consider this unexpected behaviour. I am trying to plot a map with a polygon overlaid over it (everything in the polygon being plotted as normal and everything outside of it with a black shade over it, but not completely cut-out). To do this I create a new larger  polygon and use `st_difference()` to create a new polygon that can be used as a mask. This solution works fine if the mask has just a solid fill, but as soon as I add an alpha level to the `geom_sf()` it does not plot anything. If I do not add   `coord_sf()`, it also works.  This is a small reproducible example of what I try to explain:

```
library(rworldmap)
library(sf)
library(tidyverse)
World_map  <- getMap(resolution = "low")
World_map <- st_as_sf(World_map)


# just create a quick example shapefile to use as a cutout
mid_point <- data.frame(lat = 0, long = 0 ) %>%  
  st_as_sf(coords = c("long", "lat"),  crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") 

circle <- st_buffer(mid_point, dist = 15)
circle_2 <- st_buffer(mid_point, dist = 40) 

masked_area <- st_difference(circle_2, circle)

ggplot() +
  geom_sf(data = World_map) +
  geom_sf(data = circle, fill = NA, col = "red")+ 
  geom_sf(data = masked_area, 
          fill = "green", 
          alpha = .7, 
          col = "black") +
  coord_sf( xlim = c(-20, 20),
            ylim = c(-20, 20), expand = F) 
```
![image](https://user-images.githubusercontent.com/18034318/97813413-f7dfdd80-1c7f-11eb-80b9-3b32fee1e5ee.png)

This does work
```
ggplot() +
  geom_sf(data = World_map) +
  geom_sf(data = circle, fill = NA, col = "red")+ 
  geom_sf(data = masked_area, 
          fill = "green", 
         # alpha = .7, 
          col = "black") +
  coord_sf( xlim = c(-20, 20),
            ylim = c(-20, 20), expand = F) 
```
![image](https://user-images.githubusercontent.com/18034318/97813421-0cbc7100-1c80-11eb-885e-20aa9534104c.png)

This also works
```
ggplot() +
  geom_sf(data = World_map) +
  geom_sf(data = circle, fill = NA, col = "red")+ 
  geom_sf(data = masked_area, 
          fill = "green", 
          alpha = .7, 
          col = "black") #+
  #coord_sf( xlim = c(-20, 20),
  #           ylim = c(-20, 20), expand = F) 
```
![image](https://user-images.githubusercontent.com/18034318/97813428-1ba32380-1c80-11eb-81f9-b4f31c691107.png)

Using `fill = alpha("green", .7)`, also doesnot work.

**Comment by edzer** [comment]
Thanks for the reprex. `geom_sf` and `coord_sf` are both part of `ggplot2` - I have no idea what in `sf` could cause this. @yutannihilation do you have any idea?

**Comment by yutannihilation** [comment]
#254? This is a known bug of Windows' default graphics device. You can try ragg. https://cran.r-project.org/web/packages/ragg/index.html

**Comment by LaurentSmeets** [comment]
> #254? This is a known bug of Windows' default graphics device. You can try ragg. https://cran.r-project.org/web/packages/ragg/index.html

Thanks, using `ragg` did indeed solve my problem.

For people who stumble on this in the future, for now this worked:`
```
library(ragg)

agg_png("file.png", width = 500, height = 500, res = 144)
ggplot() +
  geom_sf(data = World_map) +
  geom_sf(data = circle, fill = NA, col = "red")+ 
  geom_sf(data = masked_area, 
          fill = "green", 
          alpha = .7, 
          col = "black") +
  coord_sf( xlim = c(-20, 20),
            ylim = c(-20, 20), expand = F) 
invisible(dev.off())
```
![image](https://user-images.githubusercontent.com/18034318/97840240-94839900-1cdb-11eb-90b0-b3db84339ecc.png)

**Comment by LaurentSmeets** [comment]
@yutannihilation, Thanks! Your solution helped with the alpha levels, but did create a new issue for me (again, probably not `sf` related though): https://github.com/r-lib/ragg/issues/62
