### ISSUE TITLE
geom_sf 

### ISSUE THREAD

**Issue by phdykd** [r-spatial/sf#1523]
I have df that has long, lat, and geometry of Africa countries. The geometry seems to be sfc multiploygon.
I am not able to graph the Africa map. geom_sf or tmap is not working.
it says geom_sf needs aes....
 
Then, I changed geometry column to st_sf(column geometry),
now it says stat_sf requires the following missing aesthetics: geometry

It basically does not work..

```{r}
st_sf(sf_Atmal$geometry)
ggplot(sf_Atmal)+
  geom_sf(aes(fill=pr))+
  scale_fill_gradient(low='#56B1F7', high='#132B43')
```
Would you please help me out to solve this problem?
Thanks

**Comment by Robinlovelace** [comment]
Do you have a reproducible example? That will greatly help resolve the issue. The example could start with something like the following:

```r
library(sf)
u = "https://link-where-you-uploaded-the-data.geojson"
f = basename(u)
download.file(u, f)
sf_Atmal = st_read(f)
...
```

**Comment by Robinlovelace** [comment]
Here's a reproducible example to show what I mean:

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(ggplot2)
u = "https://github.com/npct/pct-outputs-regional-notR/raw/master/commute/lsoa/isle-of-wight/rnet_full.geojson"
f = basename(u)
download.file(u, f, mode = "wb")
sf_Atmal = st_read(u)
#> Reading layer `rnet_full' from data source `https://github.com/npct/pct-outputs-regional-notR/raw/master/commute/lsoa/isle-of-wight/rnet_full.geojson' using driver `GeoJSON'
#> Simple feature collection with 1311 features and 7 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: -1.54331 ymin: 50.58314 xmax: -1.07968 ymax: 50.80027
#> geographic CRS: WGS 84
plot(sf_Atmal)
```

![](https://i.imgur.com/ALeqxuy.png)

``` r
ggplot(sf_Atmal)+
  geom_sf(aes(fill=bicycle))+
  scale_fill_gradient(low='#56B1F7', high='#132B43')
```

![](https://i.imgur.com/vB6A8g0.png)

<sup>Created on 2020-11-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by phdykd** [comment]
Thanks...
But, I do not have it and I am not familiar wit geojson... 
I did not understand what you are trying. I do not have map or shape, but geometry, long and lat column in the dataset.

But I can send you the rmd

or printscreen...


![image](https://user-images.githubusercontent.com/72084102/97878862-2f38a380-1ced-11eb-91ae-fe44a3ac991c.png)

![image](https://user-images.githubusercontent.com/72084102/97878910-424b7380-1ced-11eb-9d85-2e2b9fb50d9d.png)

**Comment by Robinlovelace** [comment]
Thanks for the quick response @phdykd. Can you create a .zip file with the .Rmd/R file and the data? You should be able to upload the .zip file by clicking on this link when creating a new reply: 

![image](https://user-images.githubusercontent.com/1825120/97879531-024db600-1d18-11eb-9fe3-206c5ff93d44.png)

**Comment by phdykd** [comment]
Ho Robin,
I am attaching it...
DSBA522.Rmd is the one I use... (line 281...) Both Rmd s are related...
[GIT.zip](https://github.com/r-spatial/sf/files/5478201/GIT.zip)

Thanks

**Comment by Robinlovelace** [comment]
Hi @phdykd I have tried to reproduce the issue starting with the .zip file you shared but cannot see how to reproduce the issue. Can you write code that starts with the following lines that generates the error you see?

```r
library(sf)
library(ggplot2)
setwd(tempdir())
u = "https://github.com/r-spatial/sf/files/5478201/GIT.zip"
f = basename(u)
download.file(u, f)
unzip(f)
list.files("GIT/data")
sf_Atmal = st_read("GIT/data/TM_WORLD_BORDERS_SIMPL-0.3.shp")
# plot(sf_Atmal)
ggplot(sf_Atmal)+
  geom_sf(aes(fill=POP2005))+
  scale_fill_gradient(low='#56B1F7', high='#132B43')
```

If not it may be worth asking a question in a different place, e.g. https://stackoverflow.com/, https://gis.stackexchange.com/, https://community.rstudio.com/ or https://stat.ethz.ch/mailman/listinfo/r-sig-geo.
