### ISSUE TITLE
sf and data.table interaction

### ISSUE THREAD

**Issue by andreacaflisch** [r-spatial/sf#1524]
First of all thanks for the awesome package.

I often work with scripts combining data.table and sf. In these situations, `dt` is a data.table where each entry has point coordinates in variables `latitude` and `longitude`. I obtain an sf object by:
`my.sf <- st_as_sf(dt, coords = c("longitude", "latitude")`

In a fairly long script, I encountered some strange behaviour where the geom attribute in `my.sf` would change after some manipulation of `dt` taking place _below_ the code which creates `my.sf`. Unfortunately, I am not in a position to share the script, but the function causing the problem is `setorderv`. This reorders the `dt`, but in doing so it seems to also reorder `my.sf` - except for the geom attribute.

Beyond `setorderv`, the important point (I think) is that the issue takes place after the last reference to `my.sf` in the script. That is, just by working on `dt` (which does not contain a geom attribute, but only the original `latitude` and `longitude` as numeric), the geom attribute in `my.sf` changes. This got me thinking that the issue must have something to do with the way in which `dt` and `my.sf` are stored in memory, particularly since data.table is known to (purposefully) lead to some 'weird' (but often useful) behaviour in its reference semantics (see e.g. https://cran.r-project.org/web/packages/data.table/vignettes/datatable-reference-semantics.html, https://stackoverflow.com/questions/8030452/pass-by-reference-operator-in-the-data-table-package-modifies-another-data). 

Indeed, the issue stopped when I changed the line to obtain the sf object to:
`my.sf <- st_as_sf(copy(dt), coords = c("longitude", "latitude")`.

I did not expect the type of 'inheritance' behaviour from data.table to also apply to a simple feature derived from it - and it seems particularly dangerous since geom, which is not in the original data.table, isn't behaving consistently with the other attributes. I tried to look on stackoverflow but could not find anyone with similar issues. Could this be a bug?

**Comment by edzer** [comment]
If not a bug it sounds pretty fishy. But what makes you believe it is an issue with sf, not data.table?

**Comment by andreacaflisch** [comment]
Data.table is causing the issue, but it seems to be doing it through its usual (if somewhat weird) behaviour of updating by reference. I saw it as an issue with sf because I expected that sf would automatically create a new object in memory when using st_as_sf, that would remain the same irrespective of any changes to the source object.

**Comment by edzer** [comment]
See #1530 : `data.table` is causing the issue.
