### ISSUE TITLE
Why use st_union and st_combine for st_erase?

### ISSUE THREAD

**Issue by josiekre** [r-spatial/sf#1525]
I see code here that uses both `st_union` and `st_combine` for an "st_erase" shortcut:

https://github.com/r-spatial/sf/blob/5caaca7ee62f37ae205cdc2d934f63e86c78de30/R/geom-transformers.R#L704

If I try to use these together removing water from Census blocks, for example below, I get an error. But if I simplify to just `st_union()`, it works:

```
library(dplyr)
library(sf)
library(tigris)

# Setup with a random county in Alabama with a river
fips <- "01001"

# Grab water and blocks
state <- substr(fips, 1, 2)
county <- substr(fips, 3, 5)
water <- tigris::area_water(state, county, class = "sf")
blocks <- tigris::blocks(state, county, class = "sf")

# Erase water from blocks
sf::st_difference(blocks, sf::st_union(sf::st_combine(water)))  # error
sf::st_difference(blocks, sf::st_union(water))  # success
```

The error is a self intersection:
```
> sf::st_difference(blocks, sf::st_union(sf::st_combine(water))) 
although coordinates are longitude/latitude, st_difference assumes that they are planar
Error in CPL_geos_op2(op, x, y) : 
  Evaluation error: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -86.857856999999996 32.439617999999996 at -86.857856999999996 32.439617999999996.
```

In particular, the combination of `st_union` with `st_combine` seems to miss dissolving this boundary (and probably others too), and I cannot figure out why given the documentation suggests "This can for instance be used to resolve internal boundaries after polygons were combined using st_combine." Also I cannot figure out why this boundary makes the `difference` fail either.

![Screen Shot 2020-11-02 at 3 18 10 PM](https://user-images.githubusercontent.com/5776153/97929718-a0dd1580-1d1e-11eb-9e57-a924eed18334.png)

**Comment by josiekre** [comment]
I used git blame to see that this example of `st_erase()` was added to the docstring from this issue: https://github.com/r-spatial/sf/issues/346. In the issue, it is not clear why the combo of `st_union()` and `st_combine()` fixed the problem at hand. It is even more perplexing that the same error resulted in the exact opposite case: the error message went away by using both. My error message is present when I use both.

**Comment by edzer** [comment]
Well, the OP of #346 didn't give the use case that motivated using `st_combine`, so I'm OK with removing that from the example. Would that solve your issue?

**Comment by josiekre** [comment]
You don't need to remove it from the example. I have my own implementation that does so. Thanks though.

I was more interested in whether this was a bug in `st_union`, or if there was something I could learn from it. It is hard to understand what is happening behind `st_combine` and `st_union` given the abstraction and their combined documentation. I thought `st_union` should dissolve the internal boundary shown in the above screenshot. Why didn't it?

**Comment by edzer** [comment]
The union of the result from `st_combine` is invalid, without `st_combine` gives a valid output:
```
> u = sf::st_union(sf::st_combine(water))
although coordinates are longitude/latitude, st_union assumes that they are planar
> st_is_valid(u)
[1] FALSE
> plot(u)
> u = sf::st_union(water)
although coordinates are longitude/latitude, st_union assumes that they are planar
> st_is_valid(u)
[1] TRUE
```
The reason is probably that `st_union` expects a valid input, but doesn't break on an invalid one, just outputs something invalid. It is documented that output of `st_combine` will be invalid (when polygons share boundaries).

**Comment by jldupouey** [comment]
I still do not understand exactly why in general, or in which specific cases, st_union needs to be applied following st_combine in the "st_erase" function:

st_erase = function(x, y) st_difference(x, st_union(st_combine(y))) 

Is it only in case of errors or a specific geometric structure in the y layer? Which errors or specific geometric structures lead to the need for st_union?

Or are there other reasons? Which ones?

**Comment by edzer** [comment]
`st_erase` is not an `sf` function, it is only an example of something that worked under a particular circumstance: it is not exported nor documented, nor claimed to work under any other circumstance. I am thinking about removing it from the documentation.

**Comment by josiekre** [comment]
I think "erasing" a polygon from another one is common. Removing this suggested operation that was nicknamed `st_erase` from the docstring does not help users figure out how to accomplish the erasing error-free. 

@jldupouey I admittedly am having a hard time following your comment. Adding quote marks around your function names in-line and putting your example code into a chunk would be helpful. I did find that for my example removing `st_combine()` worked. The text in the combined docstring for `st_union()` and `st_combine()` is still confusing to me, and I do not have a good grasp on what kind of cases "break" which either.

**Comment by jldupouey** [comment]
Thanks @josiekre. I edited and tried to improve my comment. I hope it is clearer now.

My question is not about removing or not the erase example from the `sf` documentation.

I agree with you that it is unclear why `st_union` should be chained to `st_combine`, and in which cases. I tested this chaining on several layers, but could not find any case where the value returned by `st_union(st_combine(SF1))` was different from that returned by `st_combine(SF1)`. And if such a case exists, it would perhaps imply that some explanations are lacking in the `st_union`/`st_combine` documentation. But all these are speculations.

**Comment by francisbarton** [comment]
I might not have the correct language to exactly explain this, but I just discovered a case where using `sf::st_combine` before calling `sf::st_union` made a big difference to me.

I was using `dplyr::group_by` and `dplyr::summarise` to group an `sf` tibble by a certain variable and then union each group to a single sf object:
```
sf_tibble %>%
  dplyr::group_by(area) %>% 
  dplyr::summarise()
```

However, what I ended up with was _multipolygon_ geometries, which is fine, but it meant that when I plotted my shapes with text labels, I ended up with multiple text labels for each area. I only wanted a single text label.

Then I tried using `st_combine` first, then `st_union`, and this solved my issue. I now only get single text labels for each area. To be explicit:
```
sf_tibble %>%
  dplyr::group_by(area) %>% 
  dplyr::summarise(across(geometry, ~ sf::st_combine(.)), .groups = "keep") %>% 
  dplyr::summarise(across(geometry, ~ sf::st_union(.)), .groups = "drop")
```
[It may be that a plain `dplyr::summarise()` is fine for one of those lines, and I'm not sure how important the `.groups` bits are.]

(Edit:
```
sf_tibble %>%
  dplyr::group_by(area) %>% 
  dplyr::summarise(across(geometry, ~ sf::st_combine(.)), .groups = "keep") %>%
  # dplyr::summarise(across(geometry, ~ sf::st_union(.)), .groups = "drop")
  dplyr::summarise()
```
seems to have the same effect as the code in the previous block.)

I realised that I might need to do this when [I read that](https://datascience.blog.wzb.eu/2021/03/15/simplifying-geospatial-features-in-r-with-sf-and-rmapshaper/) `st_union`
> can be used to join overlapping and adjacent features

My areas were _not_ all comprised of overlapping and adjacent features - some of them were coastal areas with separate islands. So then I realised that I maybe needed to combine the areas first, before unioning.

[also posted as an SE answer [here](https://gis.stackexchange.com/q/379096/104738)]
