### ISSUE TITLE
Possible bug when grouping and unioning polygons where some groups all overlap and others don't

### ISSUE THREAD

**Issue by atrevisan21** [r-spatial/sf#1530]
When trying to use `st_union` by grouping, if there are polygons that do not overlap, they will be coerced to a multipolygon. Likewise if there are groups that all overlap, they will be converted to a polygon. The conflict arises when both are present in a single sf class. This produces a geometry that expects multipolygon or polygon depending on the first grouping but adds polygon or multipolygon geometries in conflict with the geometry type of the class. I'm not sure exactly why this is happening or if this is a bug.
   
    library(sf)
    
    b0 = st_polygon(list(rbind(c(-1,-1), c(1,-1), c(1,1), c(-1,1), c(-1,-1))))
    b1 = b0 - 1
    b2 = b0 + 2.5
    b3 = b0 + 3.0
    b4 = b0 + 5
    b5 = b0 + 2.5
    
    # All polygons overlap
    aa <- st_sfc(b0, b1, b2, b3) %>% st_as_sf()
    # Some polygons overlap some don't
    bb <- st_sfc(b0, b1, b4, b5) %>% st_as_sf()
    
    aa$id <- c(1, 1, 2, 2)
    bb$id <- aa$id
    
    works <- aa %>% group_by(id) %>% summarise(x = st_union(x))
    fails <- bb %>% group_by(id) %>% summarise(x = st_union(x))

This will actually work with data.table's grouping so you can actually see the conflict.

    library(data.table)
    dt <- as.data.table(bb)
    dt[,.(x=st_union(x)), by=id] %>% sf::st_as_sf()
    # Simple feature collection with 2 features and 1 field
    # geometry type:  POLYGON  <--- polygon class
    # dimension:      XY
    # bbox:           xmin: -2 ymin: -2 xmax: 1 ymax: 1
    # CRS:            NA
    # id                              x
    # 1  1 POLYGON ((0 -1, 0 -2, -2 -2...
    #  2  2 MULTIPOLYGON (((1.5 1.5, 3....  <--- mismatch of types

I was able to get it to work by first combining the features by group and then unioning them, because the geometry type was GEOMETRY, so it allowed for mixed geometries.

    bb %>% group_by(id) %>% summarise(x = st_combine(x)) %>% st_union(by_feature=TRUE)

**Comment by edzer** [comment]
You can use `st_cast(fails, "MULTIPOLYGON")` to get rid of the `GEOMETRY`. The `data.table` problem is a problem of package `data.table`, not of `sf`: `data.table`s claim they are `data.frame`, but then they behave differently (as do tibbles, but they are supported by `sf`). I think this has been pointed out to the `data.table` developers, and if they would be interested they could come and help here - as can anyone else interested in solving this problem.
