### ISSUE TITLE
inconsistent behaviour when casting mixed POLYGON/MULTIPOLYGON to POLYGON?

### ISSUE THREAD

**Issue by bosten** [r-spatial/sf#1532]
Can someone explain the reason why casting a mixture of POLYGONs and MULTIPOLYGONs to POLYGON retains the first polygon only? The function 'st_cast' indicates that this is happening by warning 'polygon from first part only'. However, this behavior is not consistent with casting MULTIPOLYGONs to POLYGONs, which keeps all features. Below is simple example code that illustrates my point, using the total area of sf objects as an illustration of how geometries change. 

```
library(sf)
#package �sf� was built under R version 4.0.3Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

# set up four polygons
p1 <- st_polygon(list(rbind(c(1, 1), c(1, 2), c(2, 2), c(2, 1), c(1, 1))))
p2 <- p1 + 2
p3 <- p1 + 4
p4 <- p1 + 6
polygons <- st_sf(st_sfc(list(p1,p2,p3,p4)))
sum(st_area(polygons))
# Area: 4

# set up two multipolygons
pm1 <- st_multipolygon(list(p1,p2))
pm2 <- st_multipolygon(list(p3,p4))
multipolygons <- st_sf(st_sfc(list(pm1, pm2)))
sum(st_area(multipolygons))
# Area: 4

# Cast multipolygons to polygons
polygons_2 <- st_cast(multipolygons, "POLYGON")
sum(st_area(polygons_2))
# Area: 4

# mixed two polygons and one multipolygon
mixed <- st_sf(st_sfc(list(p1, p2, pm2)))
sum(st_area(mixed))
# Area: 4

# Inconsistent: Cast from mixed POLYGON/MULTIPOLGON to POLYGON does not retain all geometries
mixed_cast_to_POLYGON <- st_cast(mixed, "POLYGON")
# This produces the warning: polygon from first part only
# Accordingly, the area is only 3 units
sum(st_area(mixed_cast_to_POLYGON))
# Area: 3

# It would seem more consistent if above cast would retain all four polygons from 'mixed', as in the workaround below that individually casts features to "POLYGON".
mixed_cast_to_POLYGON2 <- NULL
for(i in 1:nrow(mixed)) {
  mixed_cast_to_POLYGON2 <- rbind(mixed_cast_to_POLYGON2, st_cast(mixed[i,], "POLYGON"))
}
sum(st_area(mixed_cast_to_POLYGON2))
# Area: 4

```

**Comment by edzer** [comment]
`st_cast` hasn't been worked out for all possible cases. Have you tried
```
mixed %>% st_cast("MULTIPOLYGON")  %>% st_cast("POLYGON")
```
?

**Comment by bosten** [comment]
Thanks. That is doing the trick.


Bertram Ostendorf
Chair for Spatial Environmental Sciences
The University of Adelaide, AUSTRALIA 5005
Ph: +61 8 8313 7317
e-mail: Bertram.Ostendorf@adelaide.edu.au<mailto:Bertram.Ostendorf@adelaide.edu.au%22%20%5Ct%20%22_blank>
Office: North Tce Campus, Oliphant 305
http://www.adelaide.edu.au/directory/bertram.ostendorf

CRICOS Provider Number 00123M
-----------------------------------------------------------
This email message is intended only for the addressee(s)  and contains information which may be confidential and/or copyright.  If you are not the intended recipient please do not read, save, forward, disclose, or copy the contents of this email.
