### ISSUE TITLE
From sf to rasterLayer object. How?

### ISSUE THREAD

**Issue by RSO9192** [r-spatial/sf#1533]
Hello,
I am trying to also work with rotated grid in R using CORDEX domain EAS-44. Following your discussion, I managed to transform my curvilinear rotated coordinate to CRS WGS 84. 
![Rplot](https://user-images.githubusercontent.com/40058235/98966824-a4815100-2503-11eb-88ac-463de61f3e8f.png)

Now, I would like to make a raster file from the sf object. I have tried the following:

```
sf_df <- as.data.frame(x)
options(digits = 5)

sff_df <- sf_df %>% 
  separate(geometry, ",", into = c("lon", "lat")) %>% 
  mutate_at(vars(2),  funs(gsub("[c(]", "", .))) %>% 
  mutate_at(vars(3),  funs(gsub("[)]", "", .))) %>% 
  mutate_all(as.numeric) %>% 
  arrange(lat)

names(data3) <- c("tas", "lon", "lat")

points2 <- SpatialPoints(sff_df[, c('lon', 'lat')])
pixels2 <- SpatialPixelsDataFrame(points2, as.data.frame(sff_df$`df$prhmax`), tolerance =  0.893041  ) 

plot(pixels2)

raster <- raster(pixels)
crs(raster) <- CRS("+init=epsg:4326")

pal <- colorNumeric(c("blue", "green", "pink", "orange", "red", "black"),
               values(raster),
               na.color = "transparent")

leaflet() %>%
  addProviderTiles(providers$OpenTopoMap) %>%
  addRasterImage(raster, colors = pal, opacity = 0.8) %>% 
  addLegend(
    pal = pal,
    values = values(raster),
    labFormat = labelFormat(digits = 7),
    position = "bottomleft",
    title=" tas") 
```

![Rplot01](https://user-images.githubusercontent.com/40058235/98968370-83b9fb00-2505-11eb-92ae-8ed45d8f4280.png)

I think it is a problem of how sf has stored the data (points rather than polygons?) But I can't figure out how to solve this. Any help would be appreciated. 

My sf object has the following specifications:

Simple feature collection with 33901 features and 1 field
geometry type:  POINT
dimension:      XY
bbox:           xmin: 63.426 ymin: -18.22 xmax: 175.22 ymax: 58.6
geographic CRS: WGS 84
First 10 features:
   df$prhmax               geometry
1     24.462 POINT (77.573 -17.229)
2     24.489  POINT (77.98 -17.171)
3     24.510 POINT (78.386 -17.114)
4     24.520 POINT (78.793 -17.058)
5     24.524 POINT (79.199 -17.002)
6     24.532 POINT (79.605 -16.946)
7     24.562 POINT (80.012 -16.892)
8     24.601 POINT (80.418 -16.837)
9     24.630 POINT (80.824 -16.784)
10    24.655  POINT (81.231 -16.73)

**Comment by edzer** [comment]
Without a reproducible example we can only guess at what your code does. Since you are working with grid data, and curvilinear grids in particular, I would suggest to try using package [stars](https://github.com/r-spatial/stars), and if you then got stuck open an issue there.
