### ISSUE TITLE
Error while loading sf

### ISSUE THREAD

**Issue by F-Chalreo** [r-spatial/sf#1534]
Hello, I receive the following message when I try to load the `sf` package

> library(sf)
Erro: package or namespace load failed for ‘sf’:
 .onLoad falhou em loadNamespace() para 'units', detalhes:
  chamada: udunits_init(file.path(.get_ud_xml_dir(), "udunits2.xml"))
  erro: Error in function udunits_init: Can't open installed, default, unit database
Além disso: Warning message:
package ‘sf’ was built under R version 4.0.3 

Anyone knows how to help?

**Comment by edzer** [comment]
Maybe you need to reinstall package `units`.

**Comment by edzer** [comment]
Closing by lack of response.

**Comment by franz-maikaefer** [comment]
I reinstalled units, without affecting the error message. But following [this advice](https://stackoverflow.com/a/65465515/5591870) (loading udunits2 before sf), it worked.

**Comment by choisy** [comment]
I got the following error while trying to load `sf` on macOS 11.5.2, R 4.1.0:
```
Error: package or namespace load failed for ‘sf’:
 .onLoad failed in loadNamespace() for 'units', details:
  call: udunits_init(path)
  error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'
```
Any idea what's going on? I've tried the suggestions above but doesn't work in my case.

**Comment by choisy** [comment]
Problem solved by re-installing `Rcpp`.

**Comment by andradefisio** [comment]
> Maybe you need to reinstall package `units`.

I have the same problem and re-installing `units` solved it. 
tks

**Comment by Bee-ginner** [comment]
I have the same problem, I already installed the unit package, but when loading the library I get this error

`> library(units)
Error: package or namespace load failed for 'units':
 .onLoad failed in loadNamespace() for 'units', details:
  call: ud_init(path)
  error: el paquete 'Rcpp_precious_remove' no ofrece la función 'Rcpp'
Además: Warning message:
package 'units' was built under R version 4.0.5`

my R version is 4.0.4 (2021-02-15) -- "Lost Library book"

**Comment by edzer** [comment]
reinstall package `Rcpp`? update R?
