### ISSUE TITLE
sf installation problem under Mac OS 11 - Big Sur

### ISSUE THREAD

**Issue by codyevers** [r-spatial/sf#1536]
Upgrading to Mac OS 11 - Big Sur appears to have created an issue in installing and loading 'sf'. The issue seems specific to the 'rgdal' package, which is looking for the library "libpq.5.dylib" which no longer exists in "/usr/lib/". Found another post on the same problem here: https://github.com/R-macos/recipes/issues/14, though no solutions yet. Anyone have thoughts on how to resolve this?

Error reported in R when install sf and/or rgdal:
>  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so':
>   dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so, 6): Library not loaded: /usr/lib/libpq.5.dylib
>   Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so
>   Reason: image not found

**Comment by rsbivand** [comment]
https://twitter.com/opencpu/status/1326902988334657537?s=19

A known issue, and good advice not to upgrade until those who understand
Apple (I do not) confirm that it is safe to do so. Following R-sig-mac is
also advised https://stat.ethz.ch/mailman/listinfo/r-sig-mac.

Roger Bivand
Falsensvei 32
5063 Bergen

fre. 13. nov. 2020, 20:24 skrev codyevers <notifications@github.com>:

**Comment by abuabara** [comment]
These steps worked for me ... 

PART 1: Using Terminal
1) Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

2) Install these ones:
brew install gdal proj geos
brew install pkg-config

2.1) Not sure it's necessary ... but good to have it
export LDFLAGS="-L/usr/local/opt/libpq/lib"
export CPPFLAGS="-I/usr/local/opt/libpq/include"

PART 2: Using R
3) install.packages("rgeos", repos="http://R-Forge.R-project.org", type="source")

4) install.packages("rgdal", repos="http://R-Forge.R-project.org", type="source")

5) library(devtools)

6) install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")

Restart R and tidycensus, rgdal, rgeos, and sf will load properly.

**Comment by codyevers** [comment]
Fantastic @abuabara. I can confirm that this fixed the problem on my end, and I assume will work for anyone else running into this issue after installing Mac OS 11 - Big Sur. Thanks for the quick fix!

**Comment by franzkappa** [comment]
Hi there. I get this when running the last line of code:

```
> install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")
Downloading GitHub repo r-spatial/sf@HEAD
Error: Failed to install 'sf' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
Warning message:
1 components of `...` were not used.

We detected these problematic arguments:
* `configure.args`

Did you misspecify an argument?
```

**Comment by thierrygosselin** [comment]
This is my _brew less_ version... to fix the install of sf on macOS 11.0.1 (Big Sur)

Note: change _-j56_ below in the code to the number of CPU on your machine

**macOS terminal**

[udunits](https://www.unidata.ucar.edu/software/udunits/)

```
cd ~/Downloads
curl -L https://www.unidata.ucar.edu/downloads/udunits/udunits-2.2.26.tar.gz | tar xf -
cd udunits*
./configure && make -j56 && sudo make install
cd ..
sudo rm -R udunits*
```

[sqlite](https://www.sqlite.org)

```
cd ~/Downloads
curl -L https://www.sqlite.org/2020/sqlite-autoconf-3330000.tar.gz | tar xf -
cd sqlite-autoconf*
./configure && make -j56 && sudo make install
cd ..
sudo rm -R sqlite-autoconf*
```

[libtiff](http://libtiff.maptools.org)

```
cd ~/Downloads
curl -L https://download.osgeo.org/libtiff/tiff-4.1.0.tar.gz | tar xf -
cd tiff*
./configure && make -j56 && sudo make install
cd ..
sudo rm -R tiff*
```

[proj](https://proj.org/about.html)

```
cd ~/Downloads
curl -L  http://download.osgeo.org/proj/proj-7.2.0.tar.gz | tar xf -
cd proj*
./configure --libdir=/usr/local/lib && make -j56 && sudo make install
cd ..
sudo rm -R proj*
```

[gdal](https://gdal.org)

```
export LDFLAGS="-L/usr/local/lib"
export CPPFLAGS="-I/usr/local/include"

cd ~/Downloads
curl -L https://github.com/OSGeo/gdal/releases/download/v3.2.0/gdal-3.2.0.tar.gz | tar xf -
cd gdal*
./configure --prefix=/usr/local --libdir=/usr/local/lib --with-proj=/usr/local && make -j56 && sudo make install
cd ..
sudo rm -R gdal*
```

[geos](https://trac.osgeo.org/geos)

```
cd ~/Downloads
git clone https://git.osgeo.org/gitea/geos/geos.git
cd geos*
./autogen.sh
./configure --libdir=/usr/local/lib && make -j56 && sudo make install
cd ..
sudo rm -R geos*
```

**Back in R console**
```
install.packages("rgeos", repos="http://R-Forge.R-project.org", type="source")
install.packages("rgdal", repos="http://R-Forge.R-project.org", type="source")
devtools::install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local")
```

**Comment by jeroen** [comment]
@thierrygosselin you should be really careful using `sudo make install` because there is no way to uninstall hose libs, so they may start conflicting with other things on the system. Also if you build gdal like this, you are missing all of the drivers that are provided by 3rd party dependency libraries.

**Comment by thierrygosselin** [comment]
@jeroen not sure for GDAL, I'm barely using it, I need sf to run [adegenet](http://adegenet.r-forge.r-project.org), and for 99% of the other genomics related packages and software I use, I see only advantages of using `sudo make install`:

- no permission issues
- Installing in `/usr/local/` is in the `PATH` by defaults, that's a plus for novice users
- as for remaining in the system forever, I have stories with homebrew that required erase/install of the main drive. I'm usually advertising to do an erase/install every year or so... With external hard drive and important personal files / preferences synced to the cloud these days, it makes the operation effortless, but that's probably outside the scope of this thread...
- I'm no fan of *homebrew* and *MacPorts*, as you might have guess...
- most importantly, it's not folders protected by [macOS System Integrity Protection](https://support.apple.com/en-ca/HT204899) so there is **no harm done by writing/moving/deleting them**.
- **3rd party dependency libraries**: I have no problem with packages that depends on it, but please make correction if you have a better way to install/compile without homebrew, I'll update my pipeline with it!

Best,
Thierry

**Comment by markegge** [comment]
Thanks @abuabara - ran with a slight simplification. These steps worked for me ...

PART 1: Using Terminal

Using Homebrew, install gdal:

```
brew install pkg-config
brew install gdal proj geos
```


PART 2: Using R

```
devtools::install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")
```

Restart R and sf will load properly.

**Comment by 007sya** [comment]
> Thanks @abuabara - ran with a slight simplification. These steps worked for me ...
> 
> PART 1: Using Terminal
> 
> Using Homebrew, install gdal:
> 
> ```
> brew install pkg-config
> brew install gdal proj geos
> ```
> 
> (Homebrew installs gdal, proj, and geos into a Cellar, and then symlinks these into the /usr/local/lib folder. You can ignore the postgres formula "keg only" warning produced when libpq is installed.)
> 
> PART 2: Using R
> 
> ```
> devtools::install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")
> ```
> 
> Restart R and sf will load properly.

In my case no need for restarting R.

**Comment by jeroen** [comment]
This problem is now fixed on CRAN. You can now install the sf and rgdal packages from CRAN in the regular way on MacOS big sur.

**Comment by Yizhi-Liang** [comment]
I am having problems when installing packages in R
It shows:

> >install.packages("rgeos", repos="http://R-Forge.R-project.org", type="source")
试开URL’http://R-Forge.R-project.org/src/contrib/rgeos_0.5-7.tar.gz'
Content type 'application/x-gzip' length 276293 bytes (269 KB)
==================================================
downloaded 269 KB

>* installing *source* package ‘rgeos’ ...
** using staged installation
configure: CC: clang -mmacosx-version-min=10.13
configure: CXX: clang++ -mmacosx-version-min=10.13 -std=gnu++14
configure: rgeos: 0.5-7
checking for /usr/bin/svnversion... no
cat: inst/SVN_VERSION: No such file or directory
configure: svn revision: 
checking for geos-config... no
no
configure: error: geos-config not found or not executable.
ERROR: configuration failed for package ‘rgeos’
>* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rgeos’
Warning in install.packages :
  installation of package ‘rgeos’ had non-zero exit status

>The downloaded source packages are in
	‘/private/var/folders/78/9n9r7b590z9_vy2trjt6nnhc0000gn/T/RtmpDtHvAI/downloaded_packages’
> install.packages("rgdal", repos="http://R-Forge.R-project.org", type="source")
试开URL’http://R-Forge.R-project.org/src/contrib/rgdal_1.5-25.tar.gz'
Content type 'application/x-gzip' length 4379698 bytes (4.2 MB)
==============
downloaded 1.2 MB

>Warning in install.packages :
  downloaded length 1245184 != reported length 4379698
Warning in install.packages :
  URL 'https://download.r-forge.r-project.org/src/contrib/rgdal_1.5-25.tar.gz': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://R-Forge.R-project.org/src/contrib/rgdal_1.5-25.tar.gz' failed
Warning in install.packages :
  download of package ‘rgdal’ failed
> library(devtools)
载入需要的程辑包：usethis
> install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")
Downloading GitHub repo r-spatial/sf@HEAD
✓  checking for file ‘/private/var/folders/78/9n9r7b590z9_vy2trjt6nnhc0000gn/T/RtmpDtHvAI/remotes4a0181ffb26/r-spatial-sf-7a0ec2c/DESCRIPTION’ ...
─  preparing ‘sf’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts (443ms)
─  checking for empty or unneeded directories
─  building ‘sf_1.0-3.tar.gz’
   
>* installing *source* package ‘sf’ ...
** using staged installation
configure: CC: clang -mmacosx-version-min=10.13
configure: CXX: clang++ -mmacosx-version-min=10.13 -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’
>* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/sf’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/78/9n9r7b590z9_vy2trjt6nnhc0000gn/T//RtmpDtHvAI/file4a049f26abe/sf_1.0-3.tar.gz’ had non-zero exit status

But I am sure that  gdal proj geos have been installed by brew

>Warning: pkg-config 0.29.2_3 is already installed and up-to-date.
To reinstall 0.29.2_3, run:
  brew reinstall pkg-config
Warning: gdal 3.3.1_3 is already installed and up-to-date.
To reinstall 3.3.1_3, run:
  brew reinstall gdal
Warning: proj 8.1.1 is already installed and up-to-date.
To reinstall 8.1.1, run:
  brew reinstall proj
Warning: geos 3.9.1 is already installed and up-to-date.
To reinstall 3.9.1, run:
  brew reinstall geos

So, what should I do next?

**Comment by rsbivand** [comment]
Do not use source packages unless you can handle installation yourself, based on for example https://github.com/r-spatial/sf/#macos. In the **rgeos** case, `geos-config` is not found, so if you must install from R-Forge (why, CRAN has the same source package and a binary for your platform?), you'll need to provide configure argument: `--with-geos-config=GEOS_CONFIG` the location of geos-config. Similarly for the others. But really you should avoid source installs unless you have very good reason.

**Comment by aourednik** [comment]
@abuabara  
Your solution lead me on the right path but it does not work anymore on the arm64 (M1) architecture.
See https://github.com/r-spatial/sf/issues/1848

**Comment by cheuerde** [comment]
> ```
> install_github("r-spatial/sf", configure.args = "--with-proj-lib=/usr/local/lib/")
> ```

For a homebrew installation of proj, use this:

```r
install_github("r-spatial/sf", configure.args = "--with-proj-lib=/opt/homebrew/lib")
```

**Comment by rsbivand** [comment]
No, it always depends  on the architecture, so without stating which architecture, this advice is not accurate, since on M1 rosetta can be brought into play with the wrong path. Always best to use CRAN binaries only, also when installing from source.

**Comment by rominamehh** [comment]
ERROR: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/readxl/libs/readxl.so':
dlopen(/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/readxl/libs/readxl.so, 0x0006): Symbol not found: _iconv
Referenced from: <231DE4EB-276B-39EC-80E7-1467425670C9> /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/readxl/libs/readxl.so
Expected in:     <E727677E-6116-3B73-A86B-E3AB4DFB621A> /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libR.dylib

i got this error and cant upload excel files, how can i fix this? i dont use github to code

**Comment by rsbivand** [comment]
@rominamehh You have hijacked a five year old closed issue for a package that is not `readxl`. Ask the `readxl` maintainer at https://github.com/tidyverse/readxl/issues, not here. Note that R 4.3 will be effectively unsupported from April 11, when R 4.5 is released. Your problem is restricted only to yourself, the package is passing all its tests for R 4.3 (package version 1.4.5) on CRAN. Maybe try to re-install from CRAN - `install.packages("readxl")`.
