### ISSUE TITLE
unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so'

### ISSUE THREAD

**Issue by gustavopap** [r-spatial/sf#1540]
After upgrading my ios to BigSur, I am having problems in the command library(sf).

Error message:
> library(sf)
Erro: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 impossível carregar objeto compartilhado '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so, 6): Library not loaded: /usr/lib/libpq.5.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so
  Reason: image not found

What can I do?

**Comment by edzer** [comment]
See the README.md, and from there the link to https://github.com/r-spatial/sf/issues/1536#issuecomment-727342736

**Comment by gustavopap** [comment]
perfect. thanks a lot
