### ISSUE TITLE
Error in st_as_sfc.SpatialPolygons : package rgeos required

### ISSUE THREAD

**Issue by jrmdel** [r-spatial/sf#1541]
I am trying to follow this great tutorial on how to use sf with ggplot2 : https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html and I'm stuck, sadly, at the beginning.

When I try to execute these lines : 
```r
library(sf)
# Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
library(rnaturalearth)
library(rnaturalearthdata)

w <- ne_countries(scale = "medium", returnclass = "sf")
```
I get the following error in my RStudio console : 
```
Error in st_as_sfc.SpatialPolygons(sp::geometry(x), ...) : 
  package rgeos required for finding out which hole belongs to which exterior ring
```

The thing is, I did indeed download this RGEOS package, along with others (GDAL and PROJ), as suggested in the README here. (I should mention that I run my project on a linux distribution, Lubuntu 19.10)

I have tried this other method which works but, if possible, I'd rather have `ne_countries()` worked : 
```r
w <- ne_coastline(scale = "medium", returnclass = "sf")
ggplot(data = w) + geom_sf()
```

Thank you in advance for your help

**Comment by Nowosad** [comment]
Have you tried:

```
install.packages("rgeos")
```

?

**Comment by jrmdel** [comment]
Well, this solved everything! I feel bad because I thought that importing `libgeos-dev` would be enough and I completely forgot about the possibility of installing packages. Thank you so much !
