### ISSUE TITLE
sfc required as input to lwgeom_make_valid

### ISSUE THREAD

**Issue by bniebuhr** [r-spatial/sf#1547]
Hi,

Frequently I have some issue with the geometry of some of the features in vector files. This frequently cause problems when processing the file, such as when combining features with `sf::st_union()`.

When working with `sf`, I've read somewhere I could do something like:
```r
my vector %>% 
  sf::st_buffer(dist = 0) %>% 
  lwgeom::st_make_valid() %>% 
  sf::st_union()
```

It used to work quite well. However, as I understand in the latest versions of `lwgeom` the function `st_make_valid()` was replaced by `lwgeom_make_valid()`, which requires an `sfc` object as input. In this case, I have to do the following:

```r
my vector %>% 
  sf::st_buffer(dist = 0) %>% 
  as("Spatial") %>% 
  sf::st_as_sfc() %>% 
  lwgeom::lwgeom_make_valid() %>% 
  sf::st_union()
```

Is there an easier way to do use and `sf` object as input for `lwgeom_make_valid()`, without having to transform it into a `Spatial` object (mainly now that `sp` has retired)?
Maybe that would be a question at the `lwgeom` repo, not here.

**Comment by edzer** [comment]
You should now use `sf::st_make_valid()`, which replaces the `lwgeom` function/method.

**Comment by bniebuhr** [comment]
Ok, That's the point now. Thanks!
