### ISSUE TITLE
Problem to cast from multipoint in mixed sfc-objects 

### ISSUE THREAD

**Issue by hemip** [r-spatial/sf#1556]
This week a feature or perhaps a bug in st_cast bite me hard. In a large simulation I needed to cast multipoint objects to single points. It seemed to work, but I noticed some missing points in the final data set and I tracked it down to this behaviour of st_cast.

Start with a simple sfc-object with one point object and one multipoint object. The aim is to produce a data collection consisting only of point objects. In this case 1 + 5 objects.

However, st_cast("POINT") only produces two point objects and a warning. The solution seems to be to first cast all objects to multipoints and then cast these into points. Is this really the desired behaviour of st_cast?

Best regards,
Hans Gardfjell

``` r
library(tidyverse)
library(sf)

a_sfc <- st_sfc(st_point(c(1,8)), st_multipoint(matrix(1:10,, 2)))

st_cast(a_sfc, "POINT")
#> Warning in st_cast.MULTIPOINT(X[[i]], ...): point from first coordinate only
#> Geometry set for 2 features 
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 6 xmax: 1 ymax: 8
#> CRS:            NA
#> POINT (1 8)
#> POINT (1 6)

a_sfc %>% st_cast("MULTIPOINT") %>% st_cast("POINT")
#> Geometry set for 6 features 
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 6 xmax: 5 ymax: 10
#> CRS:            NA
#> First 5 geometries:
#> POINT (1 8)
#> POINT (1 6)
#> POINT (2 7)
#> POINT (3 8)
#> POINT (4 9)
```

**Comment by edzer** [comment]
I think there is a lot of room for improving `st_cast`, so feel free to contribute here. At least you got a warning for the case you didn't want, and yes, right now using `st_cast` in several smaller steps is sometimes the only way to get what you want.
