### ISSUE TITLE
Issue when obtaining bounding box from a set of points

### ISSUE THREAD

**Issue by gilbertocamara** [r-spatial/sf#1558]
Hi, Edzer

I have a set of lat/long points, from which I would like to get the bounding box in sinusoidal projection (used by MODIS). I compared two ways of doing in sf, and the results are different.

The data is as follows
```
long <- c(-55.55527, -55.54954, -55.54988, -55.65931, -55.64833, -55.66738)
lat <- c(-11.51782, -11.52401, -11.53525, -11.76267, -11.76385, -11.78032)
points <- tibble::tibble("longitude" = long, "latitude" = lat)
crs <- "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +R=6371007.181 +units=m +no_defs +type=crs"
```
Option 1 - Create an sf object, transform to sinusoidal and then extract the bbox
```
sf_p <- sf::st_as_sf(points, coords = c("longitude", "latitude"), crs = 4326)
bbox_1 <- sf::st_bbox(sf::st_transform(sf_p, crs = crs))
```
Option 2 - Create an sfc object from points, transform to sinusoidal and then extract the bbox
```
p1 <- sf::st_point(c(min(long), min(lat)))
p2 <- sf::st_point(c(max(long), max(lat)))
p3 <- sf::st_point(c(min(long), max(lat)))
p4 <- sf::st_point(c(max(long), min(lat)))
sfc <- sf::st_sfc(p1, p2, p3, p4, crs = 4326)
bbox_2 <- sf::st_bbox(sf::st_transform(sfc, crs = crs))
```
The sf and sfc objects have the same bounding box in lat/long
```
> sf_p
(....)
bbox:           xmin: -55.66738 ymin: -11.78032 xmax: -55.54954 ymax: -11.51782
> sfc
(...)
bbox:           xmin: -55.66738 ymin: -11.78032 xmax: -55.54954 ymax: -11.51782
```
However, the resulting bounding boxes are different
```
bbox_1
>    xmin     xmax     ymin     ymax 
-6064553 -6058762 -1314169 -1308378 
> bbox_2
    xmin     ymin     xmax     ymax 
-6065288 -1309913 -6046735 -1280725 
```
I am using sf_0.9-6  linking to GEOS 3.8.1, GDAL 3.2.0, PROJ 7.1.1

**Comment by edzer** [comment]
Hi Gilberto! I think that is to be expected, since the sinusoidal transformation is non-linear. In that case, for instance f(max(x)) is not equal to max(f(x)) with f(x) the transformation of points x.

**Comment by gilbertocamara** [comment]
Hi, Edzer!  Thanks for the quick response. What then should be the preferrable option?

**Comment by edzer** [comment]
well, if we want to have the bounding box in the new CRS of the transformed points, the former. If you want to have the bounding box of the transformation of the bounding box of the untransformed points, the latter. Note that the latter may be both smaller or larger than the former, so doesn't really correspond to what I think "we" understand as a bounding box. Note that `bbox` objects have a `st_as_sfc` method, to allow for direct transformation of bbox:
```r
library(sf)
# Linking to GEOS 3.8.1, GDAL 3.1.3, PROJ 7.1.1
long <- c(-55.55527, -55.54954, -55.54988, -55.65931, -55.64833, -55.66738)
lat <- c(-11.51782, -11.52401, -11.53525, -11.76267, -11.76385, -11.78032)
points <- tibble::tibble("longitude" = long, "latitude" = lat)
crs <- "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +R=6371007.181 +units=m +no_defs +type=crs"
sf_p <- sf::st_as_sf(points, coords = c("longitude", "latitude"), crs = 4326)
sf_p %>% st_transform(crs = crs) %>% st_bbox()
#     xmin     ymin     xmax     ymax 
# -6059562 -1309913 -6052110 -1280725 
st_bbox(sf_p) %>%
	st_as_sfc() %>%
	st_transform(crs = crs) %>%
	st_bbox()
#     xmin     ymin     xmax     ymax 
# -6065288 -1309913 -6046735 -1280725 
```

**Comment by gilbertocamara** [comment]
Great! Many thanks!
