### ISSUE TITLE
Converting raw data from database to sf objects

### ISSUE THREAD

**Issue by Camil88** [r-spatial/sf#1563]
I'm looking for best and workable solution when it comes to converting raw data from db to sf object. Why I'm touching this topic is that I think it wasn't described in a book and need some professional guidance on it. 
I need to create POINTs. According to a book, we create sf object from raw data like this:

```
lnd_point = st_point(c(0.1, 51.5)) 
lnd_geom = st_sfc(lnd_point, crs = 4326)
lnd_attrib = data.frame(
  name = 'London',
  temperature = 25,
  date = as.Date('2017-06-21')
)
lnd_sf = st_sf(lnd_attrib, geometry = lnd_geom)
```

Unfortunately, it doesn't apply to columns with data in db. Here is my database table (named 'tableDB'):

![image](https://user-images.githubusercontent.com/57962280/103273445-9dcd7100-49bf-11eb-916c-2b3f4db04583.png)

Like in the example above, I wanted first create POINTs from those 4 last columns (using st_point), then create list of points (using st_sfc) and finally create sf object (using st_sf) but it doesn't work in my case.

Generally speaking, I need to create POINT data type of lonCust/latCust and lonApp/latApp in 2 seperate columns (2 geometry columns placed at the end of data frame). First I want to convert them to POINTs but `st_point` doesn't work for my columns, as I mentioned before. What I found in the book and on the internet is this:

```
newDF <- tableDB %>%
  st_as_sf(coords = c("lonCust","latCust"), crs = 4326)
```
After that, my 'newDF' became 'sf' and 'data.frame' object what is ok but I still need to make 2 geom columns, not one. Don't know how to add second and more geom columns at the end of df. Summing up, I have a few questions:

1. What's the best way to convert raw data from db into spatial objects (e.g. POINTs)?
2. How to add more geom columns to a data frame (like in my example, I need to have 2 geom POINT columns: for ..Cust and ..App)?
3. Is is a good practice to subtract e.g. lat/lon columns from original df and create a new, seperate sf object? If so then how can I pair/assign each spatial point with attribute (like with ZLP or LP in my example above)? 

I'm really interesting in good practices in terms of converting raw data into spatial data - I want to write Shiny app and need to know where to start.

**Comment by edzer** [comment]
1. the way you do it, above, with the `coords = ` argument.
2. by creating a POINT column in a similar way, and then add it, as in `newDF$geom2 = st_geometry(newDF)`
3. don't know; you can switch this off by adding `remove = FALSE`
