### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by spono** [r-spatial/sf#1564]
Dealing with big-but-not-huge datasets, some operations get quite long. Other times they simply freeze but you don't have an idea of it as long as R/Rstudio crashes.
A recent case happened using `st_intersection` and `st_join`, querying a vector land use map with a layer containing less than 2000 point features.

Unfortunately I'm not into the deep understaning of `sf` functioning but, if possibile, I would consider implementing such an enhancement.
(BTW, thanks for the great work!)

**Comment by andrew-lucmaps** [comment]
Yes I would love to see this as well. I often am running intersections that take 45 minutes or more and it would help the work flow enormously if I knew how long I needed to wait. Overall, the sf package has completely changed the way I look at R for spatial analysis and its ability to work within the tidyverse idiom is fantastic. Thank you very much.
