### ISSUE TITLE
End of Support for PROJ <6.0.0

### ISSUE THREAD

**Issue by jlacko** [r-spatial/sf#1565]
First of all, let me thank you for a great package and support you provide to the spatial community.

Secondly, I would like to ask whether there is a plan to raise system requirements of `{sf}` from current PROJ 4.8.0 to a higher version, e.g. 6.0.0 in an upcoming version.

I am currently supporting a mixed environment, which leads to problems when `{sf}` objects are shared between users in `*.rds` format.

The results of `sf::st_crs()` ran on an object in EPSG 4326 on a system with PROJ 4.9.3 read:
```
Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
```
The same function used on the same object, but on a system using PROJ 7.2.0, produces a different result:
```
Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]
```
This has the unfortunate consequence that the `st_crs(x) == st_crs(y) is not TRUE` check is prone to failure.

There are workarounds around this, but given the recent active development on PROJ front the support of versions both old and new is getting difficult - as you are no doubt aware. Knowing that there is a deliverance approaching would be most appreciated.

Thank you again for your time and effort!

**Comment by edzer** [comment]
I see your point. Have you also thought about the problems such a move might create for other users? Which workarounds did you have in mind?

**Comment by jlacko** [comment]
It is obvious that support for oldish versions can not be feasibly killed overnight. PROJ 4.9.3 was for a long time a part of the standard Windows binaries, and there are still many of these around.

I was asking more generally whether there is some roadmap, that would set a future date when 6.0.0 would become the minimal requirement (perhaps end of 2021? - something like that).

The workaround I mentioned involves producing shared R binary objects on the lowest commonly used PROJ version, which in my case is 4.9.3 - these will not throw the `st_crs()` error when loaded on systems with higher PROJ, while the opposite is not true. As more and more users migrate to higher PROJ versions the friction of this workaround increases.

**Comment by rsbivand** [comment]
Another issue is that of reproducing results from earlier work. **sf** is GDAL >= 2, but **rgdal** still permits GDAL < 2 to a certain extent. **rgdal** will not block earlier versions, and I suggest that **sf** should not either (PROJ >= 6 is the same as GDAL >= 3). It is the problem of script authors (and some package maintainers - many packages import from **sf** and/or **rgdal**) to navigate this. A lab with a script collection should be able to decide to require barn-raising compliancy, but the package maintainers of **sf** and **rgdal** and others installing against PROJ (maybe 6-8 packages) are not in a position to make that call.

**Comment by jlacko** [comment]
Thank you for your guidance; if you can live with supporting old versions indefinitely so can I.

**Comment by rsbivand** [comment]
Indefinitely is too strong, but since code to branch on PROJ and GDAL versions is in place, and CentOS clusters are very conservative, we'd create problems by blocking out things that still work. It may make sense to issue warnings at some stage, pointing out that newer PROJ and GDAL have fixed bugs in older versions, and that new functionality will not be available to users staying with older versions. For PROJ, >= 7 offers CDN for transformation grids (https://cdn.proj.org). CRAN Windows and MacOS package binaries keep to a reasonably stable choice of PROJ, GDAL, GEOS versions.

**Comment by jlacko** [comment]
Well, perhaps "in the foreseeable future" would be a better term - but the gist remains that 1) no end of life date for oldish PROJ libraries has been set (yet) and 2) I am happy to follow where you lead.
Thanks again for your guidance, it was much appreciated!
