### ISSUE TITLE
GEOS considering dropping autotools

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#1569]
See https://lists.osgeo.org/pipermail/geos-devel/2021-January/010050.html. How will this affect us? Will it affect CI?

**Comment by edzer** [comment]
Thanks! I don't think it will - building GEOS from source is not part of building sf or rgdal or other R packages, nor of CI where we use binary installs. Cmake is funny, but so is autotools - you need to get used to and if it doesn't work you're pretty easily lost with both systems. There's an (older) example of source install of GEOS with cmake here: https://github.com/r-spatial/sf/blob/master/inst/docker/custom/Dockerfile#L50-L59
