### ISSUE TITLE
Distance between points with same id

### ISSUE THREAD

**Issue by MOGasserIRDA** [r-spatial/sf#1570]
I want to calculate distances only between points sharing the same Id and was wondering how to specify this with sf_distance. A simple group_by in dplyr doesn't seem to do the trick :

```
Distance_Lab_Id <- Datasf %>%
  group_by(Lab_Id) %>%
  mutate(Dist=st_distance(Datasf, by_element = TRUE))
```
Sorry for the amateurism

**Comment by edzer** [comment]
How about calling `st_distance` once for each group?

**Comment by MOGasserIRDA** [comment]
Out of 90 000 points, there  is  about 4000 points which have 2,3 or 4 same id(sample points on the same field). I want to validate that they are not 2 km or more apart (in the same field). This function exists  in GISs
