### ISSUE TITLE
sf installation on google colab throws errors 

### ISSUE THREAD

**Issue by le-kutscher** [r-spatial/sf#1572]
For a project, we want to run geospatial computations in **Google Colab**, using the sf package. 

However, when trying to **install sf via install.packages() it does not work**. The installation does not throw an error, but when calling the library function, 3 errors occurs:  `"Error in library(sf) : there is no package called ‘sf’"` , `installation of package ‘units’ had non-zero exit status`, `installation of package ‘sf’ had non-zero exit status`. 

For other packages (e.g. dplyr), it works just fine. 

I tried the following things:
- install it with a different library path (gets same errors)
- install from command line (Error `'/usr/bin/sudo: /usr/bin/sudo: cannot execute binary file'`)

I created a **reproducible example**, and would really be grateful for any kind of help! 
https://colab.research.google.com/drive/1VCGIZ9vC2LS7pYVE0J4LZywW-JAsdHzQ?usp=sharing

All best, 
Samuel

**Comment by edzer** [comment]
I'm not familiar with that platform. Packages like `dplyr` do not have system dependencies, packages like `units` and `sf` do. Please install these system dependencies (udunits, GDAL, GEOS, PROJ) first, then install the R packages. See the README of this repo for instructions.

**Comment by tapiamcclung** [comment]
@le-kutscher @edzer 
From within an R session inside Colab (https://colab.to/r), this does the trick:
```
system('sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable')
system('sudo apt-get update')
system('sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev')
install.packages('sf')
```
may need to change the calls for your Python session

**Comment by fms-1988** [comment]
It not worked for me. The error is:

`Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘units’


Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/sf/libs/sf.so':
  /usr/lib/libgdal.so.26: undefined symbol: GEOSMakeValid_r
Traceback:

1. library(sf)

2. tryCatch({
 .     attr(package, "LibPath") <- which.lib.loc
 .     ns <- loadNamespace(package, lib.loc)
 .     env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
 . }, error = function(e) {
 .     P <- if (!is.null(cc <- conditionCall(e))) 
 .         paste(" in", deparse(cc)[1L])
 .     else ""
 .     msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
 .         sQuote(package), P, conditionMessage(e))
 .     if (logical.return && !quietly) 
 .         message(paste("Error:", msg), domain = NA)
 .     else stop(msg, call. = FALSE, domain = NA)
 . })

3. tryCatchList(expr, classes, parentenv, handlers)

4. tryCatchOne(expr, names, parentenv, handlers[[1L]])

5. value[[3L]](cond)

6. stop(msg, call. = FALSE, domain = NA)`
