### ISSUE TITLE
Tidyverse function: drop_na

### ISSUE THREAD

**Issue by gregleleu** [r-spatial/sf#1578]
Could you please add `{tidyr}`'s `drop_na` function to the tidyverse function for sf?
I know it's just a wrapper for `filter(is.na(.))` but it's a convenient one :) and also for people who use it all the time it's always a source of error because `drop_na` currently drops the geometry silently.

Thanks!

**Comment by KiranmayiV** [comment]
Hi @gregleleu , 

Could you give reprex?  I did this, the geometry column doesn't seem to drop.

```
> df
Simple feature collection with 3 features and 2 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: 20.1 ymin: -1.2 xmax: 20.2 ymax: -1.1
CRS:            NA
# A tibble: 3 x 3
      x y        geometry
  <dbl> <chr>     <POINT>
1     1 a     (20.1 -1.1)
2     2 NA    (20.2 -1.2)
3    NA b     (20.1 -1.2)
> drop_na(df)
# A tibble: 1 x 3
      x y        geometry
  <dbl> <chr>     <POINT>
1     1 a     (20.1 -1.1)
```

**Comment by edzer** [comment]
It looks like the class is dropped.

**Comment by KiranmayiV** [comment]
> It looks like the class is dropped.

Aaah, ok thanks. I will look into it.

**Comment by KiranmayiV** [comment]
If this seems alright, can put a PR.

``` r
#' @name tidyverse
#' @param … see original function docs
#' @examples
#' library(tidyr)
#' df <- st_as_sf(
#' tibble::tibble(x = c(1, 2, NA,3),
#' y = c(“a”, NA, “b”, “a”),
#' lng = c(20.1, 20.2, 20.1, 20.4),
#' lat = c(-1.1, -1.2, -1.2, -1.4)),
#' coords = c(“lng”, “lat”))
#' drop_na(df, x)
#' drop_na(df)

drop_na.sf <- function(data, ...){
  if (!requireNamespace("tidyr", quietly = TRUE))
    stop("tidyr required: install first?")
  
  class(df) <- setdiff(class(df), "sf")
  sf::st_as_sf(tidyr::drop_na(df))
  
}
```

<sup>Created on 2021-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by KiranmayiV** [comment]
If this looks good for `drop_na.sf`, I can put in a PR to include this in tidyverse.R . Please let me know if you prefer any changes. 

``` r
library(roxygen2)
library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
library(tibble)
library(tidyr)

#' @name tidyverse
#' @param … see original function docs
#' @examples
#' library(tidyr)
#' df <- st_as_sf(
#' tibble::tibble(x = c(1, 2, NA,3),
#' y = c(“a”, NA, “b”, “a”),
#' lng = c(20.1, 20.2, 20.1, 20.4),
#' lat = c(-1.1, -1.2, -1.2, -1.4)),
#' coords = c(“lng”, “lat”))
#' drop_na(df, x)
#' drop_na(df)

t_n <- function(data, ...){
  if (!requireNamespace("tidyr", quietly = TRUE))
    stop("tidyr required: install first?")
  
  class(df) <- setdiff(class(df), "sf")
  sf::st_as_sf(tidyr::drop_na(df, ...))
  
}

df <- sf::st_as_sf(
  tibble::tibble(x = c(1, 2, NA,3), 
                 y = c("a", NA, "b", "a"),
                 lng = c(20.1, 20.2, 20.1, 20.4),
                 lat = c(-1.1, -1.2, -1.2, -1.4)),
  coords = c("lng", "lat"))

t_n(df)
#> Simple feature collection with 2 features and 2 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 20.1 ymin: -1.4 xmax: 20.4 ymax: -1.1
#> CRS:            NA
#> # A tibble: 2 x 3
#>       x y        geometry
#>   <dbl> <chr>     <POINT>
#> 1     1 a     (20.1 -1.1)
#> 2     3 a     (20.4 -1.4)
```

<sup>Created on 2021-01-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks,

**Comment by KiranmayiV** [comment]
Sorry about that, I am new to open source contribution and learning. Yes, happy to include for corner cases - following arrange.sf pattern.

**Comment by ilikegitlab** [comment]
Any progress? Just noticed that drop_na mysteriously caused some things to fail. Took me a while to see it was changing the class of my custom tibble....

**Comment by gregleleu** [comment]
I just tried making a PR (it's a pretty simple change) but I can't get devtools::check to work (it's not finding sqlite3 apparently, and I could find how to set --with_sqlite3_lib)

**Comment by gregleleu** [comment]
Close via https://github.com/r-spatial/sf/pull/1975

**Comment by ilikegitlab** [comment]
thanks! Actually noticed i meant to complain about tidyr::drop_na, not r-spatial. But still nice something got fixed...
