### ISSUE TITLE
More informative error message in case of illegal column type in st_interpolate_aw

### ISSUE THREAD

**Issue by jlacko** [r-spatial/sf#1581]
The function `sf::st_interpolate_aw` fails when supplied with non-numeric data, such as in this reprex:

```
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"))
g <- st_make_grid(nc, n = c(20,10))

st_interpolate_aw(nc[,c(5,9)], # ie. NAME and BIR74
                  g,
                  extensive = FALSE)

although coordinates are longitude/latitude, st_intersection assumes that they are planar
Error in v * x_st$...area_st : non-numeric argument to binary operator
In addition: Warning message:
In st_interpolate_aw.sf(nc[, c(5, 9)], g, extensive = FALSE) :
  st_interpolate_aw assumes attributes are constant or uniform over areas of x
```
The root cause is that a character column - `NAME` in this case - can not be interpolated by area. The failure is to be expected, but the error message feels somewhat cryptic (without understanding the underlying logic).

I suggest a test of `is.numeric()` on columns supplied, and a more informative error message if the condition is not met.

I will be happy to propose a pull request in this matter, if that would be agreeable to the maintainers.

**Comment by edzer** [comment]
Make sense - thanks!
