### ISSUE TITLE
Exporting class "sf" to allow class unions

### ISSUE THREAD

**Issue by VLucet** [r-spatial/sf#1584]
Hello, 
I am writing a package in which I find myself needing to set a union between `data.frame` and `sf` as such:
```r
#' @import sf
setOldClass(c("data.frame", "sf"))
setClassUnion("spatial.data.frame", c("data.frame", "sf"))
```
Yet doing so I get a the following warning when I `devtools::document` or when I build the package:
```r
Warning: class "sf" is defined (with package slot ‘sf’) 
but no metadata object found to revise superClass information---not imported?  
Making a copy in package ‘spaspm’
```
I think this is due to the fact that the class `sf` is not exported by the `sf` package. 

Therefore my question is: would you consider exporting the `sf` class to allow for class unions?

**Comment by edzer** [comment]
`sf` uses the S3 mechanism, which doesn't define classes formally, so there's nothing to export. I think in your package you can
```r
setOldClass("sf")
```
to register it as an official class to be used for S4 purposes.

**Comment by VLucet** [comment]
@edzer thanks for the quick reply. That is what I am doing up there with `setOldClass(c("data.frame", "sf"))` , I am still getting the warning. It is my understanding that "S3 generics are just regular R functions, you can `@export` them like functions" (from https://r-pkgs.org/namespace.html#export-s3)

**Comment by yutannihilation** [comment]
I guess the problem is somehow related to the fact that sf is already declared as a class that doesn't inherits `data.frame`. This probably needs to be `setOldClass(c("sf", "data.frame"))`.

https://github.com/r-spatial/sf/blob/b211f354f6e4f968acebba2c6067c62f0c058993/R/init.R#L19

e.g. tibble declares like this:

https://github.com/tidyverse/tibble/blob/57d5b22a600c68778d959742dbadb48dd5d6dff2/R/class-tbl_df.R#L3

**Comment by tim-salabim** [comment]
[This](https://github.com/r-spatial/mapview/blob/master/R/AAAmapviewClasses.R) is what I do in mapview to register sf

**Comment by VLucet** [comment]
@yutannihilation turns out setting `setOldClass(c("sf", "data.frame"))` generates the following error (related to ihneritance as well?)
```r
 Error in setOldClass(c("sf", "data.frame")) : 
  inconsistent old-style class information for “sf”; the class is defined but 
does not extend “data.frame” and is not valid as the data part 
```
Having the two statement separate (as below) does not solve the issue. 
```r
setOldClass("data.frame")
setOldClass("sf")
```
@tim-salabim I'm guessing you are not running into any issues as you are not setting unions (the warnings only comes up when I try to set the class union). 
Should I just forget about making an union between the two classes and design a workaround?

**Comment by VLucet** [comment]
I've added  the following tag in `init.R` and it it solves the issue. 
```r
#' @exportClass sf
``` 
see https://github.com/VLucet/sf/commit/a92d762311a64e6e5e6d1434d02e36b659b317cd

**Comment by yutannihilation** [comment]
Yes, I meant your code `setOldClass(c("data.frame", "sf"))` is opposite to the inheritance order and should be `setOldClass(c("sf", "data.frame"))`, which seems to conflict with how sf package declares it. But, sorry, this doesn't seem to relate to the original issue, please ignore.

**Comment by edzer** [comment]
Package `sf` either creates objects of class `c("sf", "data.frame")`, or of class `c("sf", "tbl_df", tbl", "data.frame")`. I don't see any point if your package picks one of these, but I'm hesitant in choosing one of the two and adding that to the `sf` package.

**Comment by VLucet** [comment]
I guess I must be a little out of my depth: maybe I do not know how to properly "pick one of these" from `sf` as you say. My apologies.

**Comment by VLucet** [comment]
So my understanding is that I cannot "pick" from the classes `c("sf", "data.frame")` or `c("sf", "tbl_df", tbl", "data.frame")`, because indeed this is S3 and all of this is not formal. The `sf` part of the class definition of these objects is never really defined formally (not a formal `structure()`), because the `sf` class is only ascribed by `st_sf()` (the actual class constructor for `sf` objects) to an object when it is casted to one of the two `sf` objects, see here: 
https://github.com/r-spatial/sf/blob/ada2e82c6e478e39d835ac8321ee7817350ed3f5/R/sf.R#L284-L291

The `sf` parts of these objects never really stands on its own and its constructor doesn't have the same name so it not actually exported when `st_sf()` is exported ; yet I think it is a requirement to allow formal class unions. For me to set a formal class union between the `sf` class and other objects for which the there is a more classic definition (for instance `data.frame` for which the constructor exports the class when it is exported), the actual class `sf` has to be somewhat exported and defined. Just exporting the class like in the PR I provided allows this (all that is missing is a doc entry). I don't think it comes at any cost: you don't have to choose one of the two objects (`c("sf", "data.frame")` or `c("sf", "tbl_df", tbl", "data.frame")`)

Apologies if I'm being mistaken and I know this is super niche, but I think it would be nice to improve compatibility with the S4 system. But maybe there as consequences to that that I can't see.

**Comment by edzer** [comment]
I fail to see why this has to happen here.

**Comment by edzer** [comment]
I too often made changes for which I _thought_ there was no cost, and am only willing to consider this if you can make clear that this comes at a clearly greater cost _for you_ when you would do this in your package.

**Comment by VLucet** [comment]
I apologize for being a source of confusion. I'm going to try again my best to demonstrate all this better.
 
The basic issue is that the `sf` class cannot be imported from the package and therefore no class unions can be set with it. This is, from my limited understanding, because the class is not formally exported. This results in issues for other package who need to handle situations in which we would want to allow an S4 slot to contain either a `data.frame` or a `sf` object, because we would need to set a class union between the two classes, which can't be done.

A similar issue seems to have been reported [here on stackoverflow](https://stackoverflow.com/questions/28871632/how-to-resolve-warning-messages-metadata-object-not-found-spatiallinesnull-cla) for `rgeos`. In a response to this issue, @edzer, you wrote "you may try by compiling a modified version of rgeos that exports this class". I followed your advice and compiled a version of `sf` that exports the `sf` class and it allowed me to set a class union. 

What is the cost of exporting the class? My understanding is that the export is a formality that will allow packages to do more things but of course you have more experience and might anticipate more issues.
