### ISSUE TITLE
sf package will not install R version 4.0.3

### ISSUE THREAD

**Issue by seandres11** [r-spatial/sf#1586]
Hi!

I am having a hard time getting sf to install on my computer (Macbook Pro 2017) with the latest version of Rstudio. 

When I call the command 
install.packages("sf")

I get the following error message: 
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/sf_0.9-7.tgz'
Content type 'application/x-gzip' length 89143896 bytes (85.0 MB)
====
downloaded 8.0 MB

Warning in install.packages :
  downloaded length 8421340 != reported length 89143896
Warning in install.packages :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/sf_0.9-7.tgz': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://cran.rstudio.com/bin/macosx/contrib/4.0/sf_0.9-7.tgz' failed
Warning in install.packages :
  download of package ‘sf’ failed

Normally sf has not caused me issues, however I seem to be having a hard time getting the package to install. 

Let me know if I can provide anything else to help. 

Cheers,
Sam

**Comment by edzer** [comment]
a problem with the CRAN mirror: please try again, or try another mirror.

**Comment by seandres11** [comment]
I have tried changing a few mirrors and still have no luck. 

This package is a dependency for many other packages I am using at the moment and I am unsure how to debug the fail to download.

Let me know if I can provide any other informaiton

**Comment by edzer** [comment]
Seems to be a broader problem, some follow-up here: https://hypatia.math.ethz.ch/pipermail/r-sig-mac/2021-January/013884.html

**Comment by jimhester** [comment]
A workaround is to use https://mac.r-project.org/ as your CRAN mirror, as the issue is really in syncing that mirror with the rest of the mirrors. https://mac.r-project.org/ itself is internally consistent.
