### ISSUE TITLE
st_make_valid returns error

### ISSUE THREAD

**Issue by vronizor** [r-spatial/sf#1589]
I am using official community district maps from New York City. For the 2016 shapefile, it seems that a geometry is not valid. However, I am unable to figure out why or to make it valid. See below my `reprex`.

What are your suggestions?

``` r
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1

#### Load the shapefile from NYC website ####
url_zip = 'https://www1.nyc.gov/assets/planning/download/zip/data-maps/open-data/nycd_16a.zip'

download.file(url = url_zip,
              destfile = 'comm_dstrct_2016.zip')

unzip('comm_dstrct_2016.zip',
      junkpaths = T)

comm_dstrct_16 = st_read('nycd.shp')
#> Reading layer `nycd' from data source `/private/var/folders/y3/cg53v8tx3g538m3751w1_9v80000gn/T/Rtmp5TVnQ6/reprexf5c570aa6ed7/nycd.shp' using driver `ESRI Shapefile'
#> Warning in CPL_read_ogr(dsn, layer, query, as.character(options), quiet, : GDAL
#> Message 1: organizePolygons() received an unexpected geometry. Either a polygon
#> with interior rings, or a polygon with less than 4 points, or a non-Polygon
#> geometry. Return arguments as a collection.
#> Warning in CPL_read_ogr(dsn, layer, query, as.character(options), quiet, :
#> GDAL Message 1: Geometry of polygon of fid 45 cannot be translated to Simple
#> Geometry. All polygons will be contained in a multipolygon.
#> Simple feature collection with 71 features and 3 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: 913175.1 ymin: 120121.9 xmax: 1067383 ymax: 272844.3
#> projected CRS:  NAD83 / New York Long Island (ftUS)

#### Check validity ####

# This works as expected
st_is_valid(comm_dstrct_16)
#>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
#> [16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
#> [31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
#> [46]   NA TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
#> [61] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

# This displays errors
st_is_valid(comm_dstrct_16, reason = T)
#> Error in CPL_geos_is_valid_reason(x): Evaluation error: IllegalArgumentException: Invalid number of points in LinearRing found 3 - must be 0 or >= 4.
comm_dstrct_16_valid = st_make_valid(comm_dstrct_16)
#> Error in CPL_geos_make_valid(x): Evaluation error: IllegalArgumentException: Invalid number of points in LinearRing found 3 - must be 0 or >= 4.
```

<sup>Created on 2021-02-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by edzer** [comment]
You could tell that it contains invalid polygons (rings with less than 4 points), and that they are in record 46. So,
```r
> sapply(st_geometry(comm_dstrct_16)[[46]], function(x) nrow(x[[1]]))
 [1]    3    3    3  748   47    4    5   39    6  569  114 1145  120    5    5
[16]   10 1247 1720  732 1009  127  671   29   99  100  167  104   14   41  202
[31]  193  192  121   89
```
indicates these are in the first three sub-polygons. Removing these, and replacing the geometry with the repaired one
```r
> g = st_geometry(comm_dstrct_16)
> g[[46]][1:3] = NULL
> st_geometry(comm_dstrct_16) = g
```
seems to give a usable object.

**Comment by vronizor** [comment]
Thanks for the answer, @edzer. Two follow-up questions: (1) so what does `st_make_valid` actually fix, and when should I use it? (2) if this issues appears repeatedly, would there be a way to automatize this process?

**Comment by dbaston** [comment]
You might find this interesting, @dr-jts

**Comment by dr-jts** [comment]
Yes, interesting @dbaston .  At a guess I would say that the Shapefile reader is emitting invalid 3-point LinearRings, and MakeValid isn't fixing those. This could be because "traditionally" in JTS/GEOS 3-point rings throw an error when they are created (which is a questionable design decision, but there it is).

One way to fix this would to prevent creating LinearRings in the Shapefile reader, by appending duplicate points as necessary.  They will still be invalid, but MakeValid will likely then be able to handled them.

**Comment by dbaston** [comment]
Ah, I see. The error message makes it look like `MakeValid` is throwing the exception, but it's actually being thrown in the `LinearRing` [constructor](https://github.com/libgeos/geos/blob/4b6ccd37d457db83e1c26d2dc051dfe29f83b0d0/src/geom/LinearRing.cpp#L73) that is called by the GEOS `WKBReader` (sf uses WKB to interchange w/GEOS). Any downside to allowing the invalid rings to be constructed on the GEOS side?

**Comment by dr-jts** [comment]
Not sure.  It might be fine, but it might not.  It is probably a good change to make, though.  

For sure LinearRings should have the first and last points identical, however.  That is relied upon everywhere.  If this is not the case for the input points it should just be forced.

**Comment by dr-jts** [comment]
There is a related JTS [issue](https://github.com/locationtech/jts/issues/558).

**Comment by dr-jts** [comment]
> Any downside to allowing the invalid rings to be constructed on the GEOS side?

I just tested JTS with the check on minimum LinearRing length removed.  All tests run fine, apart from the one that tests this error condition, of course.  But that's likely not very thorough coverage of this condition, since it has been disallowed before.  However, as far as I know it should be fine to remove this restriction.  Worth keeping an eye for subsequent errors to turn up in the wild, however (and then they should be patched).

There is still a restriction on minimum `LineString` length (2).  And the `LinearRing` check that the ring is closed needs to stay.

This seems like a good improvement to make in JTS as well.

**Comment by dbaston** [comment]
> Oddly, the JTS Shapefile reader doesn't complain about this dataset, and reads it all as valid geometries. I wonder if the R-sf reader is doing some sort of transformation on the coordinates which ends up making some of them co-incident?

I can't explain that. sf is using GDAL to read the shapefile. If I read it with shp2pgsql, I also end up three 3-point `LinearRing`s from this feature.
```
  46 |          3 | POLYGON((1003491.51123047 151624.78918457,1003491.51879883 151625.794189453,1003491.51123047 151624.78918457))
  46 |          3 | POLYGON((1003491.22680664 151627.780395508,1003491.48400879 151626.295837402,1003491.22680664 151627.780395508))
  46 |          3 | POLYGON((1003491.22680664 151627.780395508,1003490.93023682 151628.740600586,1003491.22680664 151627.780395508))
```
The first of these is consistent with what I see in the debugger from GDAL:

```
(gdb) p asPolyEx[0].poPolygon->getExteriorRingCurve()->paoPoints[0]
$16 = {x = 1003491.5112304688, y = 151624.78918457031}
(gdb) p asPolyEx[0].poPolygon->getExteriorRingCurve()->paoPoints[1]
$17 = {x = 1003491.5187988281, y = 151625.79418945312}
(gdb) p asPolyEx[0].poPolygon->getExteriorRingCurve()->paoPoints[2]
$18 = {x = 1003491.5112304688, y = 151624.78918457031}
```

I've opened a GEOS ticket for further discussion, to avoid spamming the `sf` folks :)
https://github.com/libgeos/geos/issues/406

No matter what we do in GEOS, GDAL is going to continue to throw an error here. I'm not sure if that has any practical implication for sf. https://github.com/OSGeo/gdal/blob/3a6533029645e5ffc2e76fa70f5dcf429b1443a4/gdal/ogr/ogrgeometryfactory.cpp#L1627

**Comment by edzer** [comment]
Would be great if this would be dealt with upstream!
