### ISSUE TITLE
package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):

### ISSUE THREAD

**Issue by yang-qingxin** [r-spatial/sf#1593]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/71535886/106854961-27770980-66f7-11eb-8d69-cbfcbc12914e.png">

**Comment by edzer** [comment]
You have probably more than one version of the GEOS library installed on your system; make sure there is only one, see the README of this repo.

**Comment by yang-qingxin** [comment]
Thanks for your reply!
