### ISSUE TITLE
Error converting stars object with only one y dimension to sf

### ISSUE THREAD

**Issue by jepol77** [r-spatial/sf#1598]
I am converting rasters to polygons, using st_as_stars, and then st_as_sf. This works fine for most rasters, but I found that when you only have one row in the raster, the stars object will not have an y dimension. This causes the error 
`Error in st_as_sf.stars(s) : no feature geometry column found`

Do you have a workaround for this. See code example here:

`r <- new("RasterLayer", file = new(".RasterFile", name = "", datanotation = "FLT4S", 
                                   byteorder = "little", nodatavalue = -3.4e+38, NAchanged = FALSE, 
                                   nbands = 1L, bandorder = "BIL", offset = 0L, toptobottom = TRUE, 
                                   blockrows = 0L, blockcols = 0L, driver = "", open = FALSE), 
         data = new(".SingleLayerData", values = 194421993:194421994, 
                    offset = 0, gain = 1, inmemory = TRUE, fromdisk = FALSE, 
                    isfactor = FALSE, attributes = list(), haveminmax = TRUE, 
                    min = 194421993L, max = 194421994L, band = 1L, unit = "", 
                    names = "layer"), legend = new(".RasterLegend", type = character(0), 
                                                   values = logical(0), color = logical(0), names = logical(0), 
                                                   colortable = logical(0)), title = character(0), extent = new("Extent", 
                                                                                                                xmin = 499200, xmax = 499400, ymin = 6356300, ymax = 6356400), 
         rotated = FALSE, rotation = new(".Rotation", geotrans = numeric(0), 
                                         transfun = function () 
                                           NULL), ncols = 2L, nrows = 1L, crs = new("CRS", projargs = "+proj=utm +zone=32 +ellps=GRS80 +units=m +no_defs"), 
         history = list(), z = list())`
`s <- st_as_stars(r)`
`sf <- st_as_sf(s)`

**Comment by edzer** [comment]
Thanks - should work now!
