### ISSUE TITLE
write_sf() Ignores delete_layer Argument

### ISSUE THREAD

**Issue by jaredlander** [r-spatial/sf#1599]
When using `write_sf()` I kept getting an error about `overwrite` being used multiple times.

```r
Error in .local(conn, name, value, ...) : 
  formal argument "overwrite" matched by multiple actual arguments
```

So I realized that the `overwrite` argument had been changed to `delete_layer`. But then I checked the source code for `write_sf()` and it appears to ignore what I am setting and forces `delete_layer=TRUE`.

```r
function (..., quiet = TRUE, append = FALSE, delete_layer = TRUE) 
{
    st_write(..., quiet = quiet, append = append, delete_layer = TRUE)
}
```

This occurs at [https://github.com/r-spatial/sf/blob/master/R/read.R#L502](https://github.com/r-spatial/sf/blob/master/R/read.R#L502).

I imagine 

```r
st_write(..., quiet = quiet, append = append, delete_layer = TRUE)
```

should be 

```r
st_write(..., quiet = quiet, append = append, delete_layer = delete_layer)
```

**Comment by edzer** [comment]
I don't see this when I do for instance
```{r}
write_sf(st_sf(a=1, b=st_sfc(st_point(0:1))), 'x.gpkg')
```
Could you give a small reprex, and state your `sessionInfo()`?

**Comment by edzer** [comment]
Ah, thanks! @etiennebr could you take a look at this?

**Comment by etiennebr** [comment]
I'll have a look!

**Comment by etiennebr** [comment]
Indeed, I think we got lost in the defaults!  #1600 should fix the error message and the behavior. Thanks for this clear report @jaredlander! 

Let me know if anything doesn't work as expected.
