### ISSUE TITLE
st_crop omits the Z coordinates

### ISSUE THREAD

**Issue by marcel-ald** [r-spatial/sf#1603]
I'm working with a large dataset of multipoints which include a Z dimension. Due to the size I'm using the st_crop function to select a relevant subset. However, after using st_crop the Z dimension no longer exists. 

The st_crop function uses a rectangular extent, but i would expect that the Z dimension remains untouched. Or is this intended behavior?

<pre class="r"><code># load sf package
library(sf)
#&gt; Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1

# create a spatial data frame with multipoint geometry including Z dimension
df &lt;- data.frame(&quot;ID&quot; = 1, &quot;geom&quot; = st_multipoint(x = cbind(&quot;X&quot; = c(1, 2, 3),
                                                            &quot;Y&quot; = c(4, 5, 6),
                                                            &quot;Z&quot; = c(1, 2, 3)), dim = &quot;XYZ&quot;)
                 %&gt;% st_sfc()) %&gt;% st_sf()
# crop features using an extent
df_crop &lt;- st_crop(df, c(xmin = 0, xmax = 10, ymin = 0, ymax = 10))
#&gt; Warning: attribute variables are assumed to be spatially constant throughout all
#&gt; geometries

# the original object has a Z dimension
st_coordinates(df)
#&gt;      X Y Z L1
#&gt; [1,] 1 4 1  1
#&gt; [2,] 2 5 2  1
#&gt; [3,] 3 6 3  1

# the cropped object is missing a Z dimension
st_coordinates(df_crop)
#&gt;      X Y L1
#&gt; [1,] 1 4  1
#&gt; [2,] 2 5  1
#&gt; [3,] 3 6  1</code></pre>
<p><sup>Created on 2021-02-11 by the <a href="https://reprex.tidyverse.org">reprex package</a> (v1.0.0)</sup></p>

**Comment by edzer** [comment]
You could use
```r
df[st_as_sfc(st_bbox(c(xmin = 0, xmax = 10, ymin = 0, ymax = 10))),]
```
instead; if we'd modify `st_crop` to do this, we'd loose the ability to cut off parts of polygons, as is done in its examples.

**Comment by edzer** [comment]
A reason why `st_intersection` (used by `st_crop`) cannot return `M` or `Z` values may be that it creates new nodes, for which `M` or `Z` values are unknown; unknown `Z` or `M` values are not allowed according to the specs, AFAICT.

**Comment by marcel-ald** [comment]
Thanks for the additional information, i'll use a work-around for my specific use case :-)
