### ISSUE TITLE
st_cast for MULTIPOINT only converts first point

### ISSUE THREAD

**Issue by pvermees** [r-spatial/sf#1604]
Running the example from the CRAN documentation:

```
nc = st_read(system.file("shape/nc.shp", package="sf"))
pt = st_cast(nc$geometry[[4]], "POINT")
```

Returns the following warning:

```
Warning message:
In st_cast.MULTIPOLYGON(nc$geometry[[4]], "POINT") :
  point from first coordinate only
```

How can I extract ALL the points from a MULTIPOLYGON or MULTIPOINT object?

Thanks!

PV

**Comment by edzer** [comment]
```r
nc$geometry[4] %>% st_cast("POLYGON") %>% st_cast("LINESTRING") %>% st_cast("POINT") %>% plot(type='l')
```
Note that I used `[4]`, not `[[4]]`.

**Comment by pvermees** [comment]
Thanks for quick reply! What is the equivalent solution for MULTIPOINT objects? For example:

```
xy <- data.matrix( expand.grid(x=1:20,y=1:10) )
mpts <- st_multipoint(xy,dim="XY")
st_cast(mpts,"POINT")
```
and 

```
mpts %>% st_cast("POLYGON") %>% st_cast("LINESTRING") %>% st_cast("POINT")
```

both give the same warning (`point from first coordinate only`).

**Comment by edzer** [comment]
Do this for `sfc`, not `sfg` objects (see my note above).
