### ISSUE TITLE
Controlling the sig digs of coordinates in exported files from st_write()...

### ISSUE THREAD

**Issue by peter-bastian** [r-spatial/sf#1610]
Is there some way to control the number of sig digs exported to files by the st_write() function, or otherwise change the sig digs of the sf objects' coordinates in pre-processing prior to calling st_write()? For example, I have GeoJSON files with these types of entries for the coordinates:

`"geometry": { "type": "Polygon", "coordinates": [ [ [ -102.21368238410196, 32.027733497763805 ]`

I would like to be able to control the sig digs of the coordinates to get something like this:

`"geometry": { "type": "Polygon", "coordinates": [ [ [ -102.2137, 32.0277 ]`

which matches, for example, the precision of the input dataset. It also helps reduce the size of the output file generated by st_write() if I can cut some of those significant figures.

I have done this before with the sp package, accessing the S3 objects with the slot methods...but not sure how to do it in sf.

**Comment by edzer** [comment]
You can can control the writing of the [GDAL GeoJSON driver](https://gdal.org/drivers/vector/geojson.html) by passing `layer_options="SIGNIFICANT_FIGURES=7"`; this controls all fields, not only coordinates. An alternative is to roundtrip coordinates to WKB and rounding there, as in
```r
library(sf)
# Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
st_sfc(st_point(c(1/3, 2/3))) %>% st_as_binary(precision = 1000) %>% st_as_sfc()
# Geometry set for 1 feature 
# geometry type:  POINT
# dimension:      XY
# bbox:           xmin: 0.333 ymin: 0.667 xmax: 0.333 ymax: 0.667
# CRS:            NA
# POINT (0.333 0.667)
```

**Comment by peter-bastian** [comment]
Perfect! Thank you for the quick reply.
