### ISSUE TITLE
Voronoi of mixed geometries (points and lines)...

### ISSUE THREAD

**Issue by peter-bastian** [r-spatial/sf#1612]
Have you ever considered doing something like this [https://youtu.be/KUQRlQ3mZCY] to voronoi a combination of line and points? 
I have used sf and st_voronoi to tesselate points and lines, but only after I densify the linestrings with st_line_sample, and then after st_voronoi, dissolve the resulting voronoi polygons into one voronoi polygon for the linestring. Overall, this works very well, but gets computationally intense if the sampling interval for the linestring is small(er).

So, I am just asking if doing something like the video above has ever been considered for implementation in sf? I suppose it really needs to be asked of the GEOS developers/maintainers?

**Comment by edzer** [comment]
> I suppose it really needs to be asked of the GEOS developers/maintainers?

Yes, or alternatively in a an R package of its own.

**Comment by peter-bastian** [comment]
Thank you again!
