### ISSUE TITLE
st_nearest_feature(x, y) to return nth nearest feature...

### ISSUE THREAD

**Issue by peter-bastian** [r-spatial/sf#1614]
I have two collections of geometries, x and y. Each of x is also in y, although y has other geometries that are not in x.

I am doing a nearest-feature determination for x, but because each of x is also in y, a standard st_nearest_feature() call returns indexes to x itself. I have tried NULLing all geometries of x in y, but that breaks what I want to do, and no longer works. That's not a solution.

So, as a workaround, I am currently using apply to enumerate over each x against (y minus each x). Needless to say, this seems slow when you have say, 15,000 features to check.

It is clear to me that a direct call to st_nearest_feature(x, y) is very fast. Is it possible to have st_nearest_feature(x, y) return the nth nearest feature? If, for the sake of this discussion, the nearest feature is x itself, and that is the 0th nearest feature, I would like to return the next one in the list. It doesn't appear that the current implementation of st_nearest_feature() can do that.

Any suggestions?

**Comment by edzer** [comment]
Please use this place with _issues_ with this package, not with generic analysis questions.

**Comment by peter-bastian** [comment]
My apologies…is there a way to make this a feature request then?

 

Peter

682.560.0321 (mobile)
