### ISSUE TITLE
Does st_*() operations affect all sfc columns?

### ISSUE THREAD

**Issue by yutannihilation** [r-spatial/sf#1620]
(During investigating https://github.com/tidyverse/ggplot2/issues/4362, we found this behavior)

An `sf` object can have multiple `sfc` columns. Does this mean all of these are the geometries of the `sf`, which then should mean all of them are modified by `st_*()` operations? Or, is this that only the column specified as `sf_column_name` is the geometry and other `sfc` columns are just one of the data columns? (My guess is the latter)

Currently, only the primary geometry column is affected. I want to confirm if this is the intended behavior.

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

pt <- st_point(c(1, 1))

x <- st_sfc(pt, crs = 4326)

d <- st_sf(id = 1, x1 = x, x2 = x, sf_column_name = "x1")

d_transformed <- st_transform(d, crs = 3857)

# transformed
st_crs(d_transformed$x1)$input
#> [1] "EPSG:3857"

# not transformed
st_crs(d_transformed$x2)$input
#> [1] "EPSG:4326"
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by edzer** [comment]
Thanks for bringing this up! Yes, the idea is that although there can be multiple geometry columns, only one is considered the "active" geometry and is being acted upon by `st_*` functions or methods; the others are just carried along or ignored. For plotting systems that are clever enough to maintain their own coordinate reference system (like `ggplot2::geom_sf`), you'd have to transform/convert every geometry column to the CRS used.

**Comment by yutannihilation** [comment]
I got it, thanks for the clear explanation!
