### ISSUE TITLE
cannot download git code, HTTP error 404

### ISSUE THREAD

**Issue by yingfeic** [r-spatial/sf#1623]
Hi, 
I used to install sf successfully before. I'm using Red hat 7, and R/3.6.1. 
And I just found it doesn't work any more. I don't think it's a proxy issue, because they are set up correctly.
Any suggestion?

> remotes::install_github("r-spatial/sf", configure.args = "--with-proj-include=/my/gcc/6.0.0/include --with-proj-lib=/my/gcc/6.0.0/lib/") 

Error: Failed to install 'sf' from GitHub:proj/gcc/6.0.0/lib/")
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`baddstats`) and repo name (`spatstat`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
 
Thanks a lot!

**Comment by edzer** [comment]
Thanks, fixed in https://github.com/r-spatial/sf/commit/7d43d3c80963367b1e0606ee0736b642cee06942

**Comment by yingfeic** [comment]
Hi edzer,
Thanks for fixing that issue. Now I can install sf, but got the following error. Here are all the software that I use (R/3.6.1-gccmkl gcc/6.3.0 geos/gcc/3.7.2 gdal/gcc/2.4.1 proj/gcc/6.0.0 hdf5_18/1.8.1 python/3.6.4-anaconda), I'm guessing it's the proj version that cause the problem? Should I update proj?

proj.cpp:260:57: error: ‘proj_normalize_for_visualization’ was not declared in this scope
   P = proj_normalize_for_visualization(PJ_DEFAULT_CTX, P);
                                                         ^
make: *** [proj.o] Error 1
ERROR: compilation failed for package ‘sf’
* removing ...
* restoring previous ‘...’
Error: Failed to install 'sf' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpdCjRq6/file534560352da/sf_0.9-8.tar.gz’ had non-zero exit status

**Comment by edzer** [comment]
Yes.

**Comment by yingfeic** [comment]
Do you recommend proj 8.0.0 or 7.2.1?
