### ISSUE TITLE
sudo R Linking to GEOS 3.9.0, GDAL 3.3.0dev-2e0ba54423-dirty, PROJ 8.1.0 #1085, #1140

### ISSUE THREAD

**Issue by chris-english** [r-spatial/sf#1624]
ubuntu 20.04
forgot sudo R session for sf install, again. Sigh.
* DONE (sf)

The downloaded source packages are in
	‘/home/chris/r_TMPDIR/Rtmpp3W9sL/downloaded_packages’
> library(sf)
Linking to GEOS 3.9.0, GDAL 3.3.0dev-2e0ba54423-dirty, PROJ 8.1.0

**Comment by hewm2008** [comment]
Also  Do no need the sudo. you can follow these to solve this issue.
1. Suppose  your  gdal  install prefix = /PathA/xxxx/   ;
2. Suppose  your  R Home Path is = /PathB/yyyy/   ;   ( lib/  include/  bin/)
<pre>
cd   /PathB/yyyy/inlude/;
ls  /PathA/xxxx/inlude/gdal*.h   |while read dd ; do ln -s $dd ; done
</pre>

then  R  : 
install.package("sf");  will be  DONE (sf)

**Comment by Ttttt47** [comment]
> Also Do no need the sudo R . you can follow these to solve this issue.
> 
> 1. Suppose  your  gdal  install prefix = /PathA/xxxx/   ;
> 2. Suppose  your  R Home Path is = /PathB/yyyy/   ;   ( lib/  include/  bin/)
> 
> cd   /PathB/yyyy/inlude/;
> ls  /PathA/xxxx/inlude/gdal*.h   |while read dd ; do ln -s $dd ; done
> then R : install.package("sf"); will be DONE (sf)

THANKS! The suggestion work in my case. btw, any idea why this problem would happend? I can't understand.

**Comment by hewm2008** [comment]
Because the environment variable C_INCLUDE_PATH cannot find glab.h. Sodu will put them in the specified directory  to find the  glab.h
