### ISSUE TITLE
Cannot re-install sf after upgrade to Ubuntu 20.04

### ISSUE THREAD

**Issue by Robinlovelace** [r-spatial/sf#1628]
Wanting to err on the side of caution and wait until any teething problems had been sorted, I delayed upgrading Ubuntu on my desktop until now that the 2nd point release ([20.04.2](https://lists.ubuntu.com/archives/ubuntu-announce/2021-February/000264.html)) is out.

Happily R and `sf` worked fine after the installation process, showing:

``` r
packageVersion("sf"); sf::sf_extSoftVersion()
#> [1] '0.9.7'
#>           GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
#>        "3.8.0"        "3.0.4"        "7.0.0"         "true"         "true"
```

<sup>Created on 2021-03-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Sadly I cannot reinstall `sf` or install the dev version. I get this message:

``` r
remotes::install_github("r-spatial/sf")
#> Using github PAT from envvar GITHUB_PAT
#> Downloading GitHub repo r-spatial/sf@HEAD
#> 
#>      checking for file ‘/tmp/RtmpZf6IBY/remotes1b2a749395190/r-spatial-sf-3e85c61/DESCRIPTION’ ...  ✔  checking for file ‘/tmp/RtmpZf6IBY/remotes1b2a749395190/r-spatial-sf-3e85c61/DESCRIPTION’
#>   ─  preparing ‘sf’:
#>    checking DESCRIPTION meta-information ...  ✔  checking DESCRIPTION meta-information
#> ─  cleaning src
#>   ─  running ‘cleanup’
#>   ─  checking for LF line-endings in source and make files and shell scripts
#>   ─  checking for empty or unneeded directories
#>   ─  building ‘sf_0.9-8.tar.gz’
#>      
#> 
#> Installing package into '/home/robin/R/x86_64-pc-linux-gnu-library/4.0'
#> (as 'lib' is unspecified)
#> Error: Failed to install 'sf' from GitHub:
#>   (converted from warning) installation of package '/tmp/RtmpZf6IBY/file1b2a741e74abc/sf_0.9-8.tar.gz' had non-zero exit status
```

<sup>Created on 2021-03-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Looking at the install logs it seems to be related to this:

```
proj.cpp: In function ‘Rcpp::CharacterVector CPL_enable_network(Rcpp::CharacterVector, bool)’:
proj.cpp:196:40: error: ‘proj_context_get_url_endpoint’ was not declared in this scope; did you mean ‘proj_context_set_url_endpoint’?
  196 |   return Rcpp::CharacterVector::create(proj_context_get_url_endpoint(PJ_DEFAULT_CTX));
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                        proj_context_set_url_endpoint
make: *** [/usr/lib/R/etc/Makeconf:181: proj.o] Error 1
ERROR: compilation failed for package ‘sf’
* removing ‘/home/robin/R/x86_64-pc-linux-gnu-library/4.0/sf’
* restoring previous ‘/home/robin/R/x86_64-pc-linux-gnu-library/4.0/sf’
Error: Failed to install 'sf' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpMFi2bp/filed08f2dd0b737/sf_0.9-8.tar.gz’ had non-zero exit status
```

It seems likely that the update process has thrown something out of alignment. I guess that simply updating a system dependency will fix the problem. I will document my findings here in case it's of use to others facing a similar issue and in case anyone knows a quick fix. 

Many thanks for `sf` Edzer, it has served me very well, most recently being the foundation on which the data analysis and processing component of the ActDev project was built, resulting in this web app that has the potential to scale nationally (and perhaps internationally) for evidence-based investment in walking and cycling infrastructure around new housing developments: https://actdev.cyipt.bike/

**Comment by Robinlovelace** [comment]
1st attempt at a fix: reinstall Rcpp first. No joy, still getting:

```
in method for ‘coerce’ with signature ‘"crs","CRS"’: no definition for class “CRS”
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
double free or corruption (out)
Aborted (core dumped)
ERROR: loading failed

```

Seems it fails quite late in the process.

**Comment by edzer** [comment]
Thanks; this should do it (condition on PROJ >= 7.1, not PROJ > 7).

**Comment by Robinlovelace** [comment]
Just tried again and no luck.

<details>

remotes::install_github("r-spatial/sf")
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo r-spatial/sf@HEAD
✔  checking for file ‘/tmp/RtmpJGiS4C/remotes24e0765e64f95/r-spatial-sf-0212fdc/DESCRIPTION’ ...
─  preparing ‘sf’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘sf_0.9-8.tar.gz’
   
Installing package into ‘/home/robin/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘sf’ ...
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.0.4
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.0.4
checking proj.h usability... yes
checking proj.h presence... yes
checking for proj.h... yes
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.8.0
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib/x86_64-linux-gnu -lgeos_c... yes
configure: Package CPP flags:   -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include
configure: Package LIBS:  -L/usr/lib -lgdal -lproj  -L/usr/lib -lgdal -L/usr/lib/x86_64-linux-gnu -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bbox.cpp -o bbox.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c gdal.cpp -o gdal.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c gdal_geom.cpp -o gdal_geom.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c gdal_read.cpp -o gdal_read.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c gdal_utils.cpp -o gdal_utils.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c gdal_write.cpp -o gdal_write.o
Error: Status code 502 returned
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c geos.cpp -o geos.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hex.cpp -o hex.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ops.cpp -o ops.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c polygonize.cpp -o polygonize.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c proj.cpp -o proj.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c proj_info.cpp -o proj_info.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c raster2sf.cpp -o raster2sf.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sfg.cpp -o sfg.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c signed_area.cpp -o signed_area.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c stars.cpp -o stars.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c wkb.cpp -o wkb.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -DHAVE_PROJ_H -I/usr/include/gdal -I/usr/include -I'/home/robin/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-EkOYxp/r-base-4.0.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c zm_range.cpp -o zm_range.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o sf.so RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfg.o signed_area.o stars.o wkb.o zm_range.o -L/usr/lib -lgdal -lproj -L/usr/lib -lgdal -L/usr/lib/x86_64-linux-gnu -lgeos_c -L/usr/lib/R/lib -lR
installing to /home/robin/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-sf/00new/sf/libs
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
in method for ‘dbWriteTable’ with signature ‘"PostgreSQLConnection","character","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘dbDataType’ with signature ‘"PostgreSQLConnection","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘coerce’ with signature ‘"Spatial","sf"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"Spatial","sfc"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sf","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sfc","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"XY","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"crs","CRS"’: no definition for class “CRS”
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
double free or corruption (out)
Aborted (core dumped)
ERROR: loading failed
* removing ‘/home/robin/R/x86_64-pc-linux-gnu-library/4.0/sf’
* restoring previous ‘/home/robin/R/x86_64-pc-linux-gnu-library/4.0/sf’
Error: Failed to install 'sf' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpJGiS4C/file24e0768871de8/sf_0.9-8.tar.gz’ had non-zero exit status
> 

</details>

**Comment by edzer** [comment]
We've seen that more often with problematic GDAL/GEOS/PROJ installations; have you tried reinstalling all three?

**Comment by Robinlovelace** [comment]
> have you tried reinstalling all three?

Not yet. Will give it a try and document the results.

**Comment by Robinlovelace** [comment]
Updating all the UbuntuGIS packages - lots of updates for Focal now as documented below. Well worth adding the ubuntugis-unstable PPA IMO:

```bash
# Check to see what ubuntugis repos you have:
cd /etc/apt
rg ubuntugis
# ubuntugis-unstable disabled on upgrade to 20.04

# instructions from
# https://rtask.thinkr.fr/installation-of-r-4-0-on-ubuntu-20-04-lts-and-tips-for-spatial-packages/
# lots of packages on unstable: 
# https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable?field.series_filter=focal

sudo add-apt-repository 'deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu focal main '
sudo add-apt-repository 'deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu focal main '
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 314DF160
sudo apt update
apt list --upgradable
# gdal-bin/focal 3.2.1+dfsg-1~focal0 amd64 [upgradable from: 3.0.4+dfsg-1build3]
# gdal-data/focal,focal 3.2.1+dfsg-1~focal0 all [upgradable from: 3.0.4+dfsg-1build3]
# libgdal-dev/focal 3.2.1+dfsg-1~focal0 amd64 [upgradable from: 3.0.4+dfsg-1build3]
# libgeos-c1v5/focal 3.9.0-1~focal0 amd64 [upgradable from: 3.8.0-1build1]
# libgeos-dev/focal 3.9.0-1~focal0 amd64 [upgradable from: 3.8.0-1build1]
# libgeotiff-dev/focal 1.6.0-1~focal0 amd64 [upgradable from: 1.5.1-2]
# libgeotiff5/focal 1.6.0-1~focal0 amd64 [upgradable from: 1.5.1-2]
# libopencv-core4.2/focal 4.2.0+dfsg-5+focal1 amd64 [upgradable from: 4.2.0+dfsg-5]
# libopencv-imgcodecs4.2/focal 4.2.0+dfsg-5+focal1 amd64 [upgradable from: 4.2.0+dfsg-5]
# libopencv-imgproc4.2/focal 4.2.0+dfsg-5+focal1 amd64 [upgradable from: 4.2.0+dfsg-5]
# libopencv-videoio4.2/focal 4.2.0+dfsg-5+focal1 amd64 [upgradable from: 4.2.0+dfsg-5]
# libopenthreads21/focal 3.6.5+dfsg1-6~focal1 amd64 [upgradable from: 3.6.4+dfsg1-3build2]
# libproj-dev/focal 7.2.1-1~focal0 amd64 [upgradable from: 7.0.0-1~bionic0]
# libproj19/focal 7.2.1-1~focal0 amd64 [upgradable from: 7.0.0-1~bionic0]
# libsaga-api-7.3.0/focal 7.3.0+dfsg-4~focal1 amd64 [upgradable from: 7.3.0+dfsg-3build5]
# libsaga-gdi-7.3.0/focal 7.3.0+dfsg-4~focal1 amd64 [upgradable from: 7.3.0+dfsg-3build5]
# libspatialite-dev/focal 5.0.0-1~focal1 amd64 [upgradable from: 4.3.0a-6build1]
# libspatialite7/focal 5.0.0-1~focal1 amd64 [upgradable from: 4.3.0a-6build1]
# proj-bin/focal 7.2.1-1~focal0 amd64 [upgradable from: 7.0.0-1~bionic0]
# proj-data/focal,focal 7.2.1-1~focal0 all [upgradable from: 7.0.0-1~bionic0]
# python3-gdal/focal 3.2.1+dfsg-1~focal0 amd64 [upgradable from: 3.0.4+dfsg-1build3]
# r-cran-cellranger/focal,focal 1.1.0-2 all [upgradable from: 1.1.0-2~ubuntu18.04.1~ppa1]
# r-cran-curl/focal 4.3+dfsg-1 amd64 [upgradable from: 4.3-1cran1~ubuntu18.04.1~ppa1]
# r-cran-gtable/focal,focal 0.3.0+dfsg-1 all [upgradable from: 0.3.0-1cran1.1804.1]
# r-cran-highr/focal,focal 0.8+dfsg-1 all [upgradable from: 0.8-1cran1.1804.1]
# r-cran-markdown/focal 1.1+dfsg-1 amd64 [upgradable from: 1.1-1cran1.1804.1]
# r-cran-numderiv/focal,focal 2016.8-1.1-2 all [upgradable from: 2016.8-1.1-1cran1.1804.0]
# r-cran-readxl/focal 1.3.1-2build1 amd64 [upgradable from: 1.3.1-1cran1.1804.0]
# r-cran-xtable/focal,focal 1:1.8-4-1 all [upgradable from: 1:1.8-3-1cran1ubuntu1.1804.0]
# saga-common/focal,focal 7.3.0+dfsg-4~focal1 all [upgradable from: 7.3.0+dfsg-3build5]
# saga/focal 7.3.0+dfsg-4~focal1 amd64 [upgradable from: 7.3.0+dfsg-3build5]

sudo apt upgrade
```

**Comment by Robinlovelace** [comment]
After that

```r
install.packages("sf")
```

worked :+1:

**Comment by Robinlovelace** [comment]
As did

```r
remotes::install_github("r-spatial/sf")
```

**Comment by edzer** [comment]
Great! Déjà vu, right?

**Comment by Robinlovelace** [comment]
Yes but from the README I would expect it to work with the default OSGeo versions: https://github.com/r-spatial/sf#ubuntu

Worth updating that to recommend the ubuntugis-unstable for all Ubuntu versions?

**Comment by Robinlovelace** [comment]
Possibly another reason why being part of OSGeo is a good idea.

**Comment by edzer** [comment]
> Yes but from the README I would expect it to work with the default OSGeo versions: https://github.com/r-spatial/sf#ubuntu

I would first want to see the failure on a clean 20.04.02 machine rather than one upgraded to it.

**Comment by Robinlovelace** [comment]
> I would first want to see the failure on a clean 20.04.02 machine rather than one upgraded to it.

Good point. Confirmation: it works on a clean Ubuntu install. Reproducible example

```bash
docker run --rm -ti ubuntu:20.04
cat /etc/lsb-release 
# 20.04.2
apt-get -y update && apt-get install -y  libudunits2-dev libgdal-dev libgeos-dev roj-dev
apt install r-recommended
R
install.packages("sf")
```

**Comment by edzer** [comment]
Thanks!

**Comment by edzer** [comment]
Thanks!

**Comment by jslingsby** [comment]
I've just upgraded to Ubuntu 20.04 and had the same issue. I found this thread useful, but it didn't solve my problem entirely so I thought I'd post what worked in case that's useful for others. Sadly, it required a full R reinstall. I've included some steps that may not have been relevant, but it's hard to know exactly what did the trick... My theory as to why the issue at the bottom.

As a starting point, I had R 4.1.0 installed before the OS upgrade (from 18.04).

1) [possibly unrelated] I was getting hash sum mismatch errors when running `sudo apt update`, which seems to have been a local mirror problem. I solved this by setting _Software & Updates_ to download from "Main server"

2) I ran `sudoedit /etc/apt/sources.list` and hashed out anything that mentioned "CRAN" (e.g. I still had 3.5 in the list) or "bionic"

3) I removed all things R (you may want to apply your own favourite hack to keep a list of all your packages etc first):

`sudo apt-get purge r-base* r-recommended r-cran-*`

`sudo apt autoremove`

`sudo apt update`

4) Installed R using the instructions for Ubuntu on CRAN

5) Installed the ubuntugis-unstable PPA etc following [r-spatial.github.io/sf/](https://r-spatial.github.io/sf/) 

6) `install.packages("sf")` in R

**My theory:**
I suspect this all has to do with the `snap` system introduced with 20.04. When I upgraded a lot of the snap packages were installed, creating duplicates (e.g. I found that libproj is also used by [gimp](https://www.gimp.org/) etc). Eliminating duplicates may do the trick, but I was wary to delete snaps as they are installed per application (i.e. duplicated), but also didn't want to delete the deb versions, because the snaps are usually behind the official release or dev versions that other software may require (e.g. _sf_). With a clean install, R and _sf_ seem to have worked out where to find the dependencies they want.

Good luck out there!

**Comment by GianRos** [comment]
> Updating all the UbuntuGIS packages - lots of updates for Focal now as documented below. Well worth adding the ubuntugis-unstable PPA IMO:
> 
> ```shell
> # Check to see what ubuntugis repos you have:
> cd /etc/apt
> rg ubuntugis
> # ubuntugis-unstable disabled on upgrade to 20.04
> 
> # instructions from
> # https://rtask.thinkr.fr/installation-of-r-4-0-on-ubuntu-20-04-lts-and-tips-for-spatial-packages/
> # lots of packages on unstable: 
> # https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable?field.series_filter=focal
> 
> sudo add-apt-repository 'deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu focal main '
> sudo add-apt-repository 'deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu focal main '
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 314DF160
> sudo apt update
> apt list --upgradable
> # gdal-bin/focal 3.2.1+dfsg-1~focal0 amd64 [upgradable from: 3.0.4+dfsg-1build3]
> ```

Hi,
late to the party, but this worked for me too.

My problem was with the package 'gdistance', which I could not install. For some reason 'sf' was already installed and kept working after both Ubuntu upgrades (18->20 and 20->22).

Thanks!

Gianluigi
