### ISSUE TITLE
loading "sf" troubles

### ISSUE THREAD

**Issue by magobu** [r-spatial/sf#1630]
I'm getting this error message when trying to install package "sf" on my MacBook Pro Catalina. Any help would be great! I see other people having similar issues with sf.
Gracias in advance!

> install.packages("sf")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/sf_0.9-7.tgz'
Content type 'application/x-gzip' length 89143896 bytes (85.0 MB)
==============
downloaded 24.9 MB

Warning in install.packages :
  downloaded length 26114646 != reported length 89143896
Warning in install.packages :
  URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/sf_0.9-7.tgz': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://cran.rstudio.com/bin/macosx/contrib/4.0/sf_0.9-7.tgz' failed
Warning in install.packages :
  download of package ‘sf’ failed

**Comment by rsbivand** [comment]
Please try a different mirror, clearly cran.rstudio.com is having a
difficult day. Try for example cloud.r-project.org, or another from
https://cran.r-project.org/mirrors.html.

Roger Bivand
Falsensvei 32
5063 Bergen

man. 15. mar. 2021, 22:12 skrev Marta Gomez-Buckley <
***@***.***>:

**Comment by edzer** [comment]
or (for those others with similar problems) try sth like
```r
options(timeout = 1000)
```
