### ISSUE TITLE
sf / tmap on solaris CRAN error

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#1632]
on [CRAN solaris checks](https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/sf-00check.html), we see:
```
--- re-building ‘sf5.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
Quitting from lines 213-215 (sf5.Rmd)
Error: processing vignette 'sf5.Rmd' failed with diagnostics:
invalid 'path' argument
--- failed re-building ‘sf5.Rmd’
```
the corresponding segment in `sf5.Rmd` is:
```r
tmap_mode("view")
tm_shape(nc) + tm_fill("BIR74", palette = sf.colors(5))
```
Any idea what the error indicates?

Is this maybe because I failed to set
```
mapviewOptions(fgb = FALSE)
```
@mtennekes @tim-salabim

**Comment by tim-salabim** [comment]
@edzer I think this is due to `mapview 2.9.0` still being the CRAN release. See https://github.com/r-spatial/mapview/issues/312 for which I think is the problem. 
I will try to find some time to start updating all relevant packages and eventually push mapview to CRAN
