### ISSUE TITLE
R package sf 0.9.8 will not built and install on MacOS

### ISSUE THREAD

**Issue by jrminter** [r-spatial/sf#1633]
It fails with, complaining that gdal-config not found. I would appreciate any suggestions.
* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang -mmacosx-version-min=10.13
configure: CXX: clang++ -mmacosx-version-min=10.13 -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status

**Comment by edzer** [comment]
Wait until the binary package for `sf` 0.9-8 is built, and install that.

**Comment by jrminter** [comment]
Thank you, I will.

**Comment by stefanocoretta** [comment]
If one needs to build from source on macOS Big Sur on an Apple Silicon machine, setting the PATH before installing the package works. Posting here in case somebody has the same issue.

```r
Sys.setenv(
  PATH = paste0(
    "/opt/homebrew/Cellar/proj@7/7.2.1/include:/opt/homebrew/Cellar/proj@7/7.2.1/lib:/opt/homebrew/Cellar/proj@7/7.2.1/bin:",
    Sys.getenv("PATH")
  )
)

install.packages("sf")
```
