### ISSUE TITLE
does +proj=ortho need new arguments to function as in vsn 0.9-7?

### ISSUE THREAD

**Issue by dankelley** [r-spatial/sf#1635]
I'm wondering whether `sf` 0.9-8 with `+proj=ortho` needs new arguments to function as before (in 0.9-7).

The question arises because of a problem I'm working on for the `oce` package, in which `sf` 0.9-8 produces unexpected results (https://github.com/dankelley/oce/issues/1793#issuecomment-803570868) compared with 0.9-7 (https://github.com/dankelley/oce/issues/1793#issuecomment-803578009). Please note that I am not asking anyone to look in the `oce` code ... I'll be doing that.  What I'm wondering is whether there have been other reports of problems with `+proj=ortho`, or whether there is a document I ought to be reading about changes.

**Comment by dankelley** [comment]
I am starting to think that the problem is that `oce` is not doing a proper job in interpreting the `sf` results.  A test of this follows.  I see that the `sf` output agrees quite well from version 0.9-7 to 0.9-8), except at the "edge of the world".

As a way to avoid bothering `sf` developers too much, I plan to close this issue myself tomorrow at 1600h UTC.  I'm not closing it now, because I think `sf` developers might be interested to know that `oce` might be getting a CRAN update soon to work around the new changes to `sf`.


**With 0.9-7**

``` r
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
packageVersion("sf")
#> [1] '0.9.7'
lons <- c(-50, -51, 50, 51)
lats <- rep(0, length(lons))
ll <- cbind(lons, lats)
sf_project("+proj=longlat", "+proj=ortho +lon_0=-40", ll, keep=TRUE, warn=FALSE)
#>          [,1] [,2]
#> [1,] -1107552    0
#> [2,] -1217006    0
#> [3,]  6378137    0
#> [4,]       NA   NA
sf_project("+proj=longlat", "+proj=ortho +lon_0=40", ll, keep=TRUE, warn=FALSE)
#>          [,1] [,2]
#> [1,] -6378137    0
#> [2,]       NA   NA
#> [3,]  1107552    0
#> [4,]  1217006    0
```

<sup>Created on 2021-03-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>



**With 0.9-8**

``` r
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
packageVersion("sf")
#> [1] '0.9.8'
lons <- c(-50, -51, 50, 51)
lats <- rep(0, length(lons))
ll <- cbind(lons, lats)
sf_project("+proj=longlat", "+proj=ortho +lon_0=-40", ll, keep=TRUE, warn=FALSE)
#>          [,1] [,2]
#> [1,] -1107552    0
#> [2,] -1217006    0
#> [3,]  6378137    0
#> [4,]       NA   NA
sf_project("+proj=longlat", "+proj=ortho +lon_0=40", ll, keep=TRUE, warn=FALSE)
#>          [,1] [,2]
#> [1,] -6378137    0
#> [2,]       NA   NA
#> [3,]       NA   NA
#> [4,]       NA   NA
```

<sup>Created on 2021-03-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment]
I've done some further tests, to isolate the issue further from the `oce` package.  You can see the results if you click "Details" below.   

The plots show that `sf` version 0.9-7 gives a recognizable world coastline for `+proj=ortho` but `sf` version 0.9-8 does not.

The coastline comes from the `oce` package, and contains some `NA` values.  I wonder, are `NA` values a problem here?  If not, then it seems to me that the updated `sf` is handling `+proj=ortho` in quite a different way than the older versions did.  This might be an issue with other packages that use `sf::sf_project()`.

<details>

**Good results with sf version 0.9-7**

```r
library("oce") # use this for a world coastline
#> Loading required package: gsw
##> Loading required package: testthat
##> Loading required package: sf
##> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
library("sf")
packageVersion("sf")
#> [1] '0.9.7'
data(coastlineWorld, package="oce")
lonlat <- cbind(coastlineWorld[["longitude"]], coastlineWorld[["latitude"]])
longlatProj <- sf::st_crs("+proj=longlat")
proj <- sf::st_crs("+proj=ortho")
xy <- sf::sf_project(longlatProj, proj, lonlat, keep=TRUE, warn=FALSE)
plot(xy[,1], xy[,2], asp=1, type="l")
grid()
mtext(paste("sf::sf_project() results with sf version", packageVersion("sf")))
```

![](https://i.imgur.com/qXlqQSg.png)

<sup>Created on 2021-03-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


**Odd results with sf version 0.9-8**

```r
library("oce") # use this for a world coastline
#> Loading required package: gsw
##> Loading required package: testthat
##> Loading required package: sf
##> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
library("sf")
packageVersion("sf")
#> [1] '0.9.8'
data(coastlineWorld, package="oce")
lonlat <- cbind(coastlineWorld[["longitude"]], coastlineWorld[["latitude"]])
longlatProj <- sf::st_crs("+proj=longlat")
proj <- sf::st_crs("+proj=ortho")
xy <- sf::sf_project(longlatProj, proj, lonlat, keep=TRUE, warn=FALSE)
plot(xy[,1], xy[,2], asp=1, type="l")
grid()
mtext(paste("sf::sf_project() results with sf version", packageVersion("sf")))
```

![](https://i.imgur.com/nD2JynZ.png)

<sup>Created on 2021-03-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by rsbivand** [comment]
@dankelley Please add sessionInfo() and sf_extSoftVersion() output. Most likely versions of PROJ and/or GDAL also changed, and your OS may also affect which changes in upstream components bite. I can reproduce your problem with **sf** 0.9-8, PROJ 8.0.0, GDAL 3.2.2.

However, `rgdal::project(lonlat, "+proj=ortho")` with the same PROJ and GDAL seems OK, so maybe there were late changes/regressions in this function that tests did not trap.

**Comment by dankelley** [comment]
Thanks, @rsbivand; the requested output is below.  I'd be happy to try other tests.

``` r
sessionInfo()
#> R version 4.0.4 (2021-02-15)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur 10.16
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] knitr_1.31        magrittr_2.0.1    debugme_1.1.0     rlang_0.4.10     
#>  [5] fansi_0.4.2       stringr_1.4.0     styler_1.3.2      highr_0.8        
#>  [9] tools_4.0.4       xfun_0.22         utf8_1.2.1        htmltools_0.5.1.1
#> [13] ellipsis_0.3.1    yaml_2.2.1        digest_0.6.27     tibble_3.1.0     
#> [17] lifecycle_1.0.0   crayon_1.4.1      purrr_0.3.4       vctrs_0.3.6      
#> [21] fs_1.5.0          glue_1.4.2        evaluate_0.14     rmarkdown_2.7    
#> [25] reprex_1.0.0      stringi_1.5.3     compiler_4.0.4    pillar_1.5.1     
#> [29] backports_1.2.1   pkgconfig_2.0.3
sf::sf_extSoftVersion()
#>           GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
#>        "3.9.0"        "3.2.1"        "7.2.1"         "true"         "true"
```

<sup>Created on 2021-03-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by rsbivand** [comment]
Thanks, we should wait for @edzer I think, since `rgdal::project()` is OK with these data, `sf_project()` should be, and changes occurred in the C++ file just before release.

**Comment by edzer** [comment]
Yes, crazy enough this is the problem: https://github.com/r-spatial/sf/commit/63fc501282e7d65ecd87200aee8c04f8260143fe#diff-59a13f86b092e121c1452cc4ddc0a6e42729293d5a906248e8b1314247a5c4e7R311-R313 - no clue how I should understand that, since we're passing a struct, not a pointer to it. Anyway, I reverted it back to how it was.

**Comment by rsbivand** [comment]
I've seen comments that there are multiple levels of abstraction in play in PROJ (and GDAL). Does CI also run valgrind - the patch looks good, but with PROJ I got really stuck on `proj_trans()` in **rgdal** in `project_ng()`.

**Comment by edzer** [comment]
Not on GA, but the reason work on this and to initialize `row` with `{ 0.0, 0.0, 0.0, 0.0}` came from a CRAN check.

**Comment by dankelley** [comment]
I wonder, is there a thought of updating "sf" on CRAN?  I ask because "oce" just got a message from CRAN to fix errors that arise from using "sf" in some examples.  It's easy for me to change those examples, and that's my plan, but I wanted the "sf" folks to know that at least one other CRAN package will need updating to allow for this temporary bug in "sf".

**Comment by edzer** [comment]
I see that for `oce` the error only appears in the special "donttest" repo of BDR: if you had not put it in a donttest block this regression would have been noted during revdep checks by myself, or during those run during submission to CRAN, it would also have been noticed if you had added tests to `sf` when implementing this `keep=TRUE` feature.  Updates of `sf` always cost time from the CRAN team, so in this case I will wait until there is more reason for an update. I also have limited credit with the CRAN team.

**Comment by dankelley** [comment]
Thanks, @edzer, for the note. Your plan makes sense to me.

For context, I have some things in `donttest` to speed testing, as a way to avoid CRAN notes about slowness.

My plan is to replace the tests in my Roxygen blocks with something like
```R
#' if (FALSE) { # Skip this to avoid bug in "sf" version 0.9-8
#'   # This is code using proj=ortho
#'}
```
(still wrapped in `donttest`), so that users will see that things will be fine if they use an older "sf", or a later one.

I apologize for not noticing this earlier.  I've been busy with other things and haven't been following along with the changes to "sf"; I only learned of the problem in a recent `R-CMD-check` output, which was too late to help prior to CRAN submission of "sf".  I'll try to keep more up-to-date with the development version of "sf", in the future.

**Comment by rsbivand** [comment]
You could also use `if (utils::packageVersion("sf") != "0.9.8")` - untried, but then you wouldn't have to reverse the edit, perhaps?
