### ISSUE TITLE
Problem with the library in R.

### ISSUE THREAD

**Issue by gjunior01** [r-spatial/sf#1637]
Erro: package or namespace load failed for ‘sf’:
 .onLoad falhou em loadNamespace() para 'units', detalhes:
  chamada: udunits_init(path)
  erro: no database found!

**Comment by edzer** [comment]
(re)install package units?

**Comment by gjunior01** [comment]
I tried to install units, then it says that the problem in udunits, the only package in cran is unudits2.

**Comment by janupii** [comment]
I'am experiencing the same issue. 
(Re)installed units and unudits2 but did not resolved.

I'm on windows10 and R 4.0.3

**Comment by janupii** [comment]
Here are a info and errors.

> > library(sf)
>  エラー: package or namespace load failed for ‘sf’:
>   .onLoad は loadNamespace()（'units' に対する）の中で失敗しました、詳細は: 
>   call: udunits_init(path) 
>   error: no database found! 
> 

> 
> > sessionInfo()
> R version 4.0.5 (2021-03-31)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19042)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932    LC_MONETARY=Japanese_Japan.932
> [4] LC_NUMERIC=C                   LC_TIME=Japanese_Japan.932    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
>  [1] compiler_4.0.5     magrittr_2.0.1     class_7.3-18       DBI_1.1.1          tools_4.0.5        proxy_0.4-25      
>  [7] Rcpp_1.0.6         tinytex_0.31       KernSmooth_2.23-18 grid_4.0.5         e1071_1.7-6        classInt_0.4-3    
> [13] xfun_0.22         
> >

**Comment by edzer** [comment]
Your problems are with package units, not with sf.
