### ISSUE TITLE
Knowing what units to attribute to the output of st_nearest_feature

### ISSUE THREAD

**Issue by LukeKR84** [r-spatial/sf#1638]
Hi all,
I've just used st_nearest_feature to calculate the distance between a dataset of points and a dataset of polygons. My goal is to find the nearest distance from any given point to the closest polygon. The function works just fine, I receive an output of integers for each point, however, I want to know what these numbers correspond to in terms of units. My projection for both datasets is RGF 2154 or Lambert 93, which is the standard projection for France, which uses metres as its unit of measurement. Logically this should mean that the output of st_nearest_feature will also be in metres, but could somebody please confirm this ?

Kind regards,
Luke

**Comment by edzer** [comment]
No, it returns an index. Here is a reprex that shows, building on the docs example [here](https://r-spatial.github.io/sf/reference/st_nearest_feature.html), how to do this:
```r
library(sf)
# Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
r = sqrt(2)/10
b1 = st_buffer(st_point(c(.1,.1)), r)
b2 = st_buffer(st_point(c(.9,.9)), r)
b3 = st_buffer(st_point(c(.9,.1)), r)
circles = st_sf(st_sfc(b1, b2, b3))
plot(circles, col = NA, border = 2:4)
pts = st_sf(st_sfc(st_point(c(.3,.1)), st_point(c(.6,.2)), st_point(c(.6,.6)), st_point(c(.4,.8))))
plot(pts, add = TRUE, col = 1)
# draw points to nearest circle:
(nearest = st_nearest_feature(pts, circles))
# [1] 1 3 2 2
st_distance(pts, circles[nearest,], by_element = TRUE)
# [1] 0.05857864 0.17481378 0.28284271 0.36849479
```
If you work with a CRS having units `m`, your result will be in `m`.

**Comment by LukeKR84** [comment]
Thank you very much! Very helpful advice.
