### ISSUE TITLE
Binary tree for k-dimensional points for the nearest neighbors of any point

### ISSUE THREAD

**Issue by Leprechault** [r-spatial/sf#1639]
Hi Everyone!!

Is there in the `sf` any function that creates an index into a set of k-dimensional points that can be used to find the nearest neighbors of any point? The idea is create a binary tree, each of whose nodes represents an axis-aligned hyperrectangle. Each node specifies an axis and splits the set of points based on whether their coordinate along that axis is greater than or less than a particular value.

Thanks in advance!

**Comment by edzer** [comment]
No; there are several CRAN packages linking to the ANN library, for instance `FNN` or `RANN`.

**Comment by rsbivand** [comment]
**spdep** has just switched from **RANN** to **dbscan** for this purpose, also for 3D distance bounds.

**Comment by Leprechault** [comment]
Thanks, @edzer and @rsbivand for the tips!!
