### ISSUE TITLE
st_intersection error

### ISSUE THREAD

**Issue by Saadi4469** [r-spatial/sf#1643]
Hello,

Let's say I have two point shapefiles and I wish to extract the points from each of these that lie within a polygon, and then export them as two new point shapefiles. While running the code below, I get an error with the [st_intersection] function. How can I fix this? The sample data can be downloaded from [here](https://app.box.com/s/kizi9f6tn3ce2kpzc6jvs0mu9x38k52o).

```
# Load the study area polygon
Stdy_Area = st_read("~", "Study_Area")

# List the shapefiles
all.shp.files = list.files(path = "~",
                       pattern=".shp", full.names = TRUE)


for(i in all.shp.files){
  file = lapply(i, st_read)
  intersect.1 = st_intersection(x = file, y = Stdy_Area)
  names = substr(i, 1, nchar(all.files)-4)
  writeOGR(intersect.1, dsn = "~", layer = names, driver = "ESRI Shapefile")
```

Error

```
Error in UseMethod("st_intersection") : 
  no applicable method for 'st_intersection' applied to an object of class "list"

```

Thank you,

**Comment by edzer** [comment]
don't use `lapply`. 

This is not an issue with this package, but an issue of not understanding how R works; please look for help somewhere else with problems of that kind.
