### ISSUE TITLE
ld: cannot find -llzma

### ISSUE THREAD

**Issue by chrisdane** [r-spatial/sf#1644]
Hi

Running `install.packages("sf")` yields the error `ld: cannot find -llzma`. However, `liblzma.so` is available, but in a non-standard location. Running
```
install.packages("sf", configure.args="--with-lzma-lib=/dirname/of/path/to/liblzma.so")
```
yields the same error and the warning
```
configure: WARNING: unrecognized options: --with-lzma-lib
```
as for other configure args (`--with-ld-lib`, `--with-gcc-lib`, `--with-sf-lib`, `--with-xz-lib`; since this lib is in the path of the program `xz`, ...).

Also, running `export LD_LIBRARY_PATH=/dirname/of/path/to/liblzma.so:$LD_LIBRARY_PATH` or `export PKG_CONFIG_PATH=/dirname/of/path/to/liblzma.so:$PKG_CONFIG_PATH`  in terminal before running the installation command in R does not help.

I dont have the permission to install anything on the system.

Thanks a lot for any help,
Chris

```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          5.3                         
year           2019                        
month          03                          
day            11                          
svn rev        76217                       
language       R                           
version.string R version 3.5.3 (2019-03-11)
nickname       Great Truth                 
```

**Comment by edzer** [comment]
It looks like that libproj links to liblzma; `sf` assumes you have a working PROJ installation, but apparently you don't. I don't think that is the problem of `sf`, or that `sf` should help you work around _that_. I don't think it is reasonable to expect that `sf` will ever be equipped with command line flags for custom installs for each and every library it links to indirectly.

**Comment by chrisdane** [comment]
Thanks for your answer. It turned out that some other library paths were missing. This worked:
```
install.packages("sf", configure.args="
--with-gdal-config=/sw/rhel6-x64/gdal-2.1.3-gcc48/bin/gdal-config 
--with-proj-include=/sw/rhel6-x64/graphics/proj4-4.9.3-gcc48/include 
--with-proj-lib=/sw/rhel6-x64/graphics/proj4-4.9.3-gcc48/lib 
--with-geos-config=/sw/rhel6-x64/geos-3.6.1-gcc48/bin/geos-config")
```
