### ISSUE TITLE
Can't change the crs with coord_sf()

### ISSUE THREAD

**Issue by vidonne** [r-spatial/sf#1645]
I have an issue while trying to change the projection of natural earth data using the coord_sf() function from ggplot. I'm posting this here because the problem seems to be on the GDAL/PROJ side.

Please see below the reproducible code as well as my attempt to fix it with the solution from [issue 1419](https://github.com/r-spatial/sf/issues/1419)

```
library(rnaturalearth)
library(sf) # On load Linking to GEOS 3.8.1, GDAL 3.1.3, PROJ 7.1.0
library(ggplot2) 

world <- ne_countries(returnclass = "sf")

ggplot(data = world) +
  geom_sf() +
  theme_minimal() +
  coord_sf(crs = 54030)
# Error in CPL_transform(x, crs, aoi, pipeline, reverse, desired_accuracy,  : crs not found: is it missing?
# In addition: Warning message:
# In CPL_crs_from_input(x) : GDAL Error 1: PROJ: proj_create_from_database: crs not found


st_transform(world, 54030)
# Error in CPL_transform(x, crs, aoi, pipeline, reverse, desired_accuracy,  : crs not found: is it missing?
# In addition: Warning message:
# In CPL_crs_from_input(x) : GDAL Error 1: PROJ: proj_create_from_database: crs not found


st_crs(world) <- 54030
# Warning message:
# In CPL_crs_from_input(x) : GDAL Error 1: PROJ: proj_create_from_database: crs not found


st_transform(world, 54030)
# Error in st_transform.sfc(st_geometry(x), crs, ...) : cannot transform sfc object with missing crs


ggplot(data = world) +
  geom_sf() +
  theme_minimal() +
  coord_sf(crs = 54030)
# Error in st_transform.sfc(st_geometry(x), crs, ...) : cannot transform sfc object with missing crs
```
Also find my R session settings:

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 20.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.3       sf_0.9-8            rnaturalearth_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         magrittr_2.0.1     units_0.7-1        munsell_0.5.0     
 [5] tidyselect_1.1.0   colorspace_2.0-0   lattice_0.20-41    R6_2.5.0          
 [9] rlang_0.4.10       fansi_0.4.2        dplyr_1.0.5        tools_4.0.2       
[13] grid_4.0.2         gtable_0.3.0       KernSmooth_2.23-17 utf8_1.2.1        
[17] e1071_1.7-6        DBI_1.1.1          withr_2.4.1        rgeos_0.5-5       
[21] ellipsis_0.3.1     class_7.3-17       assertthat_0.2.1   tibble_3.1.0      
[25] lifecycle_1.0.0    crayon_1.4.1       farver_2.1.0       purrr_0.3.4       
[29] vctrs_0.3.7        glue_1.4.2         sp_1.4-5           proxy_0.4-25      
[33] compiler_4.0.2     pillar_1.6.0       scales_1.1.1       generics_0.1.0    
[37] classInt_0.4-3     pkgconfig_2.0.3 
```
Thanks for your help

**Comment by edzer** [comment]
If you specify a CRS by it's ID, the assumption is that it is a CRS under EPSG authority; in this case it isn't, you may want to try `'ESRI:54030'` instead.

**Comment by vidonne** [comment]
Works like a charm thanks a lot!!!

**Comment by Alwaysikky** [comment]
Hello, I want to use a proj from ESRI too, how can I fix this error? Thanks!!

>a_sp_trans=st_transform(a_sp,"ESRI:102141")
#Error in st_transform.sfc(st_geometry(x), crs, ...) :  cannot transform sfc object with missing crs

**Comment by Alwaysikky** [comment]
Hello, I want to use a proj from ESRI too, but it is a missing CRS, even though I have used st_crs. Would you please offer some clues? Thanks!

> proj=st_crs("ESRI:102141")
> proj
Coordinate Reference System:
  User input: ESRI:102141 
  wkt:
PROJCRS["Hong_Kong_1980_UTM_Zone_49N",
    BASEGEOGCRS["Hong Kong 1980",
        DATUM["Hong Kong 1980",
            ELLIPSOID["International 1924",6378388,297,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4611]],
    CONVERSION["UTM zone 49N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",111,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Not known."],
        AREA["China - Hong Kong - onshore and offshore."],
        BBOX[22.13,113.76,22.58,114.51]],
    ID["ESRI",102141]]

> a_sp_trans=st_transform(a_sp,proj)
#Error in st_transform.sfc(st_geometry(x), crs, ...) : 
  cannot transform sfc object with missing crs

**Comment by edzer** [comment]
`a_sp` does not have it's CRS set, so `st_transform` doesn't know where from to transform (`proj` is the where to).
