### ISSUE TITLE
Equivalent of PostGIS ST_WrapX

### ISSUE THREAD

**Issue by dbaston** [r-spatial/sf#1648]
The PostGIS function [ST_WrapX](https://postgis.net/docs/ST_WrapX.html) allows geometries to be split at an arbitrary meridian and "wrapped" around the globe. I am using it to transform standard administrative boundaries (longitude range: +/- 180) to the spatial extent of the ERA5 reanalysis (longitude range: -0.125 to 359.875). It seems like `st_shift_longitude` works pointwise, so it is not suitable for polygons or lines that cross the meridian of interest. I cobbled together a hackish equivalent of the PostGIS function that probably fails in some edge cases:

```
st_wrap_x <- function(x, wrap, move) {
  allrows <- st_drop_geometry(x)
  allrows$`.row_number` = seq_len(nrow(allrows))

  result_type <- as.character(st_geometry_type(x, by_geometry = FALSE))

  box <- as.list(st_bbox(x))

  left <- st_crop(x, xmin = box$xmin, xmax = wrap, ymin = box$ymin, ymax = box$ymax) %>%
    dplyr::full_join(allrows) %>%
    dplyr::arrange(.row_number)
  right <- st_crop(x, xmin = wrap, xmax = box$xmax, ymin = box$ymin, ymax = box$ymax) %>%
    dplyr::full_join(allrows) %>%
    dplyr::arrange(.row_number)
  st_geometry(left) <- st_geometry(left) + c(move, 0)
  st_crs(left) <- st_crs(x)

  left %>%
    st_union(st_geometry(right)) %>%
    st_cast(result_type) %>%
    dplyr::select(-.row_number)
}
```
This allows the transformation I need via `st_wrap_x(regions, -0.125, 360)`.

But I'm wondering:
- is there no built-in way to do this in sf?
- if no, would a binding to the `lwgeom` function that does this be desirable?

**Comment by edzer** [comment]
Functionality of this kind, if it helps the user, is very welcome. OTOH, my gut feeling says that after `sf_use_s2(TRUE)` things should also work out. But you probably want to run `exactextractr` for the polygons on the ERA5 data?

**Comment by dbaston** [comment]
Yes, I need to extract ERA5 data for the polygons.

Would the best approach be to add the function to `lwgeom`? Then, if the functionality ever migrates to GEOS, it could be added to `sf` ? I feel like the process became a little confused when `st_make_valid` moved from `lwgeom` to `sf` and I'd like to do any work in a way that avoids hassle later on.
