### ISSUE TITLE
st_intersects returns different results locally and remote

### ISSUE THREAD

**Issue by AlexandraKapp** [r-spatial/sf#1651]
I'm not sure if this is the right place to ask - but maybe you have a hint where to look?

When I run the exact same code with the exact same data once locally in R and once on a remote server, I get different results for `st_intersects`. Some points that should intersect with lines, are correctly returned locally while they are not returned as intersecting remotely. 
In both cases `sf` Version ‘0.9.8’ is used.
I guess this has to be some kind of environment issue?

Its hard to give a reproducable example here, but here are the screenshots of the two runs:

<img width="447" alt="Bildschirmfoto 2021-04-18 um 16 16 42" src="https://user-images.githubusercontent.com/18367515/115148813-99f25700-a061-11eb-97fc-e6d5d7023ea9.png">

<img width="378" alt="Bildschirmfoto 2021-04-18 um 16 16 59" src="https://user-images.githubusercontent.com/18367515/115148812-96f76680-a061-11eb-9e67-445597f0f92f.png">

**Comment by edzer** [comment]
> I guess this has to be some kind of environment issue?

It could be, but little sensible can be said without a reprex. You may want to look into differences between output for `sessionInfo()`, and for `sf_extSoftVersion()`.

**Comment by AlexandraKapp** [comment]
Thanks for the quick reply!
I updated GDAL on the remote server, but its still the same issue. 

As I am using OSM data, I tried a different approach for debugging:
- query the osm data with `osmdata`
- use `osmextract` (what I did originially, which led to the error)

The problem only occured with `osmextract`. So apparently this must happen when reading the data with `osmextract` (maybe some inaccuracy in the coordinates?). I still dont understand, why this is different within in the different environments, but setting the `st_precision=1` then solved it. :)

Anyways, here is the example, in case thats helpful for someone.

``` r
library(sf)

# use osmdata: works as expected
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
point1 <- opq_osm_id(type = "node", id = "3847367624") %>% 
  opq_string () %>%
  osmdata_sf ()
point1 <- point1$osm_points %>% 
  st_transform(3035)

line1 <- opq_osm_id(type = "way", id = "381539717") %>% 
  opq_string () %>%
  osmdata_sf ()
line1 <- line1$osm_lines %>% 
  st_transform(3035)

st_intersects(line1, point1, sparse = F)
#>      [,1]
#> [1,] TRUE

# produces error
library(osmextract)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright.
#> Check the package website, https://docs.ropensci.org/osmextract/, for more details.
line2 <- oe_get(
  "Regierungsbezirk Stuttgart",
  stringsAsFactors = F,
  query = "SELECT * FROM 'lines' WHERE osm_id = '381539717'")
#> The input place was matched with: Regierungsbezirk Stuttgart
#> File downloaded!
#> Start with the vectortranslate operations on the input file!
#> 0...10...20...30...40...50...60...70...80...90...100 - done.
#> Finished the vectortranslate operations on the input file!
#> Reading layer `lines' from data source `/private/var/folders/7p/3qdn4bj91bs8lk0vk9r76lt80000gn/T/Rtmp5R7Wqx/geofabrik_stuttgart-regbez-latest.gpkg' using driver `GPKG'
#> Simple feature collection with 1 feature and 9 fields
#> Geometry type: LINESTRING
#> Dimension:     XY
#> Bounding box:  xmin: 9.175039 ymin: 48.78115 xmax: 9.175436 ymax: 48.78171
#> Geodetic CRS:  WGS 84

point2 <- oe_get(
  "Regierungsbezirk Stuttgart",
  stringsAsFactors = F,
  layer = 'points',
  query = "SELECT * FROM 'points' WHERE osm_id = '3847367624'"
)
#> The input place was matched with: Regierungsbezirk Stuttgart
#> The chosen file was already detected in the download directory. Skip downloading.
#> Adding a new layer to the .gpkg file
#> Start with the vectortranslate operations on the input file!
#> 0...10...20...30...40...50...60...70...80...90...100 - done.
#> Finished the vectortranslate operations on the input file!
#> Reading layer `points' from data source `/private/var/folders/7p/3qdn4bj91bs8lk0vk9r76lt80000gn/T/Rtmp5R7Wqx/geofabrik_stuttgart-regbez-latest.gpkg' using driver `GPKG'
#> Simple feature collection with 1 feature and 10 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 9.175039 ymin: 48.78171 xmax: 9.175039 ymax: 48.78171
#> Geodetic CRS:  WGS 84

line2 <- st_transform(line2, 3035)
point2 <- st_transform(point2, 3035)
st_intersects(line2, point2, sparse = F)
#>      [,1]
#> [1,] TRUE # This is FALSE on the remote server!

st_precision(line2) <- 1
st_precision(point2) <- 1
st_intersects(line2, point2, sparse = F)
#>      [,1]
#> [1,] TRUE # now works locally and remotely as expected
```

<sup>Created on 2021-04-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
