### ISSUE TITLE
Nit: Vignette 6 formatted incorrectly.

### ISSUE THREAD

**Issue by zmeers** [r-spatial/sf#1652]
Hello,

Just a heads up that vignette 6 in `sf` is formatted incorrectly, so the title doesn't show up on the drop down menu of the `pkgdown` site.
<img width="867" alt="Screen Shot 2021-04-19 at 12 15 05 pm" src="https://user-images.githubusercontent.com/26280637/115172598-ee9cdd00-a108-11eb-9727-bcb197ebe7ed.png">

If you want a PR, I can take a look at it later today, but it should be an easy fix.

Zoe

**Comment by edzer** [comment]
Thanks!
