### ISSUE TITLE
keep or pass polygon ID's with st_interpolate_aw?

### ISSUE THREAD

**Issue by DHLocke** [r-spatial/sf#1657]
First off sf is a fantastic package and I'm very grateful for all of the excellent work supporting the package and its development.

Sometimes polygons don't overlap, and it would be helpful if sf::st_interpolate_aw would pass or take on polygon identifiers columns as arguments to facilitate tabular joins (like dplyr::left_join or base::merge) rather than rely on row order for joining the results back to one of the inputs.

Thank you for your consideration.

**Comment by edzer** [comment]
A small reprex would be helpful!

**Comment by DHLocke** [comment]
library(sf)
set.seed(1)
nc_half = st_read(system.file("shape/nc.shp", package="sf")) %>% 
  dplyr::sample_frac(1/2)

plot(nc_half)

g = st_make_grid(nc_half, n = c(20,10))
a1 = st_interpolate_aw(nc_half["BIR74"], g, extensive = FALSE)

plot(a1)


a2 = st_interpolate_aw(nc_half["BIR74"], g, extensive = TRUE)

# how can values from a1 or a2 be joined back to g?

**Comment by edzer** [comment]
This puts the ID of `g` as row names in `a1` and `a2`, but also adds an option `keep_NA = TRUE` that will return the whole geometry of `g` with `NA` values in place.

**Comment by leahbevis** [comment]
Hi, i have the exact same question about maintaining IDs, and I see edzer closed the issue with a comment "This puts the ID of g as row names..." but I don't see the code that he is referring to. Edzer, where is the code that does this? (I am probably missing something obvious about the formatting here; I literally just joined github to see the answer to this question.)

**Comment by leahbevis** [comment]
Never mind, I figured out that you were referring to adding the capability keep_NA = TRUE. This is very helpful!
