### ISSUE TITLE
PROJ threads seen from GDAL

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#1659]
I'm unsure whether **sf** or **rgdal** need to be concerned about https://lists.osgeo.org/pipermail/gdal-dev/2021-April/054007.html, because R is single-threaded, and we (now, mostly) use the PROJ default context. However, this is a placeholder in case we need to follow `pyproj` and use `proj_context_set_autoclose_database()`, say on `unload()`.

**Comment by edzer** [comment]
Thanks; closing because currently not an issue.
