### ISSUE TITLE
query argument in st_read() truncates to 64 characters when within a function

### ISSUE THREAD

**Issue by imarkonis** [r-spatial/sf#1661]
Hello, here is an example:

con <- dbConnect(Postgres(), dbname = db_name,       
                 user = rstudioapi::askForPassword("Database user"),      
                 password = rstudioapi::askForPassword("Database password"))

query <- paste0("SELECT * FROM hs_basins.basins_all_regions_4_11 WHERE pfaf_id IN 
('225', '2251', '22519', '225190', '2251904', '22519043', '225190431', '2251904311', '22519043112', '225190431120'))

aa <- function(x) {
  st_read(con, query = x)
}

If x length is above 64, then it truncates to 64.
The same code works if st_read is executed normally.

**Comment by edzer** [comment]
Please fix the formatting of this issue - there is no matching `"` afaics, and a reprex would be helpful. @etiennebr is this something you could look into?

**Comment by etiennebr** [comment]
Reaching the query limit is not uncommon. I don't remember the exact maximal length of a query for `Rpostgres`, but it's longer than 64 character. Without a [reprex](https://reprex.tidyverse.org/articles/articles/learn-reprex.html) or an output it will be difficult to resolve. Might be useful: https://github.com/r-dbi/odbc/issues/202, https://stackoverflow.com/q/46165852.
