### ISSUE TITLE
SQL dialects assumes Spatialite available, errors if only plain SQLite

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#1663]
See https://github.com/r-spatial/sf/issues/1653#issuecomment-830578335 which is a strong regression, imposing an untested assumption that the GDAL SQLite driver includes Spatialite.

**Comment by rsbivand** [comment]
On `master` I'm seeing:
```
> # if you select the SQLite dialect, then you can use several spatial
> # functions when building the query:
> nc_sqlite = st_read(
+   system.file("shape/nc.shp", package="sf"),
+   query = "
+     SELECT GEOMETRY, ST_Area(ST_Transform(GEOMETRY, 32119)) AS AREA_m2
+     FROM nc
+     WHERE ST_Intersects(
+       ST_Transform(GEOMETRY, 32119),
+       GeomFromText('POINT (573193 199429)', 32119)
+     )
+   ",
+   dialect = "SQLite"
+ )
Warning in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  GDAL Error 1: In ExecuteSQL(): sqlite3_prepare_v2(
    SELECT GEOMETRY, ST_Area(ST_Transform(GEOMETRY, 32119)) AS AREA_m2
    FROM nc
    WHERE ST_Intersects(
      ST_Transform(GEOMETRY, 32119),
      GeomFromText('POINT (573193 199429)', 32119)
    )
  ):
  no such function: ST_Transform
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Query execution failed, cannot open layer.
Calls: st_read -> st_read.character -> CPL_read_ogr
Execution halted
```
which is the `dialects` addition I expect. Is this known? Is the dialect presupposing that spatialite is available (with me it is not, I really dislike the circular dependencies it induces). Should the `"SQLite"` dialect differentiate between pure SQLite3 and Spatialite? Re-installing GDAL (always without Spatialite) to make sure ... this is not GDAL, it is an unspoken assumption that SQLite is Spatialite. In my setting with a plain SQLite file:

```
$ ogrinfo vv.sqlite --debug on
SQLITE: Spatialite not available. Implementing a few functions
SQLITE: OGR style SQLite DB found !
GDAL: GDALOpen(vv.sqlite, this=0x1d487a0) succeeds as SQLite.
INFO: Open of `vv.sqlite'
      using driver `SQLite' successful.
OGR: GetLayerCount() = 1

SQLITE: Spatialite not available. Implementing a few functions
1: vv (Multi Polygon)
OGR: Unloading VirtualOGR module
GDAL: GDALClose(vv.sqlite, this=0x1d487a0)
GDAL: In GDALDestroy - unloading GDAL shared library.
OGR: Unloading VirtualOGR module
```

**Comment by rsbivand** [comment]
So there shoud be code in ogrinfo somewhere to test whether SQLite is Spatialite. Maybe rather in ogr/ogrfrmts/sqlite ? This also feels like the odd `sqlite3_prepare_v2()` issue that we've seen in some GPKG issues, maybe? How to check the SQLite driver from code to see whether it is Spatialite or not?

**Comment by edzer** [comment]
@agila5

**Comment by edzer** [comment]
I reverted this PR - thanks for discovering!

**Comment by rsbivand** [comment]
A shame really, but it doesn't look obvious how to test the driver for the assumption that Spatialite is present. If it did, maybe there would be a (kludgy) way forward.

**Comment by agila5** [comment]
Hi @rsbivand and @edzer, and thanks for the additional testings. Unfortunately, I have minimal knowledge of GDAL and SQLite drivers, so I didn't think about this problem. 

If you are still interested in including the `dialect` argument in `st_read`, I can try (sometimes next week) to add an if clause somewhere in the code to test that the SQLite driver includes Spatialite (and skip the test and the example if not)

**Comment by rsbivand** [comment]
This might be handled expensively by catching the error (`try()` or `tryCatch()`) and issuing a warning() instead, if it isn't possible to ask the GDAL SQLite driver if it knows Spatialite before running the operation. Maybe also asking on the GDAL list might provide insight into whether one can ask whether the SQLite driver is Spatialite capable.
