### ISSUE TITLE
st_read causing crash when single feature is too large

### ISSUE THREAD

**Issue by mafw** [r-spatial/sf#1665]
When I try and load a `.geojson` file that has features that exceed the limit set by the `OGR_GEOJSON_MAX_OBJ_SIZE` option for the "GEOJSON" driver used by GDAL I get a repeated error message that causes my R session to freeze so that I need to force quit it. I am guessing that a new error message is produced for every feature that's too large and this causes problems if there are many large features. The error message says: 

`In CPL_read_ogr(dsn, layer, query, as.character(options),  ... : GDAL Error 1: GeoJSON object too complex, please see the OGR_GEOJSON_MAX_OBJ_SIZE environment option`

Now I am not sure how to exactly solve this issue but it would be very convenient if it's possible to avoid this endlessly repeated error message that causes my session to crash. Maybe the read operation could exit as soon as this problem is encountered. Note that my issue is not primarily with GDAL not loading files with features that exceed 200MB, but with how `st_read` produces the error message. 

On a related note, it would also be nice if one could specify these "configuration options" for the "GEOJSON" drivers right in the call to `st_read`, as is possible for the "open options" via the `options` argument. Right now I am setting the environment variable to increase the size limit for the `OGR_GEOJSON_MAX_OBJ_SIZE` option. Being able to do this through `st_read` would move the "fix" closer to the code execution and thus make it clearer. Alternatively, would it be possible for `sf` to use another driver for large files? `geojsonsf::geojson_sf `  handles large files pretty well, for example. 

I am using `sf_0.9-8, GDAL 3.0.4` Below is some info from my session. I experience the same issue on my Mac Mini and Windows 10 machines.
```
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS
```
Example code:
```
# This produces the error message
sf::st_read("PATH_TO_LARGE_GEOJSON_FILE")
```

**Comment by rsbivand** [comment]
Were you using RStudio (it makes a difference)? Did you set the environment variable `OGR_GEOJSON_MAX_OBJ_SIZE` to a larger value as suggested by https://gdal.org/drivers/vector/geojson.html#vector-geojson. If you are trying to read a file generated by Statkart, be aware that very often they include multiple geometry levels. Check `st_layers()` first, set the environment variable to a large value, and try again.

**Comment by mafw** [comment]
Yes, I am using Rstudio. Sorry for not including that. 

As I mention, the problem is with loading the file: I can circumvent that issue by setting the environment variable as you suggest. My issue is that if I try to read the file or check the layers (using `st_layers()`), my session freezes. This makes it cumbersome to deal with `.geojson` files that contain large files using the `sf` package through Rstudio.  Of course one could argue that I should know my files (and the default configuration options for GDAL) better and adjust my environment variables accordingly. 

I realize now that this issue might really be about how Rstudio handles recurring error messages. Reading the large file in a terminal R session produces the same warnings, but I am able to stop the process without the session freezing. I'll therefore close this issue.
