### ISSUE TITLE
Installation issues under Fedora

### ISSUE THREAD

**Issue by courtiol** [r-spatial/sf#1670]
_NOTES:_ 
- this is probably related to #1268, #1471 and other similar issues
- there is a solution at the end of this message

_PROBLEM_:
**The current instructions for how to install sf under Fedora do not seem to work**, at least with Fedora 34 (I did not test other versions).

Contrary to other issues related to this problem, I have a standard fresh install of Fedora with nothing else installed than R and RStudio.

You wrote: 
> sudo dnf install gdal-devel proj-devel proj-epsg proj-nad geos-devel sqlite-devel udunits2-devel

But doing that gives me the following error message from dnf:
```
No match for argument: proj-epsg
No match for argument: proj-nad
```

When dropping those two, other packages do install:
```bash
[alex@fedora ~]$ sudo dnf install gdal-devel proj-devel geos-devel sqlite-devel udunits2-devel
Last metadata expiration check: 0:08:19 ago on Tue 04 May 2021 12:28:05 PM CEST.
Package gdal-devel-3.2.2-1.fc34.x86_64 is already installed.
Package proj-devel-7.2.1-2.fc34.x86_64 is already installed.
Package geos-devel-3.9.0-3.fc34.x86_64 is already installed.
Package sqlite-devel-3.34.1-2.fc34.x86_64 is already installed.
Package udunits2-devel-2.2.28-2.fc34.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

That does not seem sufficient to install from sources:

```r
> install.packages("sf")
Installing package into ‘/home/alex/R/x86_64-redhat-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/sf_0.9-8.tar.gz'
Content type 'application/x-gzip' length 4213253 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -m64
configure: CXX: g++ -m64 -std=gnu++11
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.2.2
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -m64
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -m64 accepts -g... yes
checking for gcc -m64 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -m64 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.2.2
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 7.2.0
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
configure: error: libproj or sqlite3 not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/alex/R/x86_64-redhat-linux-gnu-library/4.0/sf’

The downloaded source packages are in
	‘/tmp/RtmpKcLkx6/downloaded_packages’
Warning message:
In install.packages("sf") :
  installation of package ‘sf’ had non-zero exit status
```

The message is confusing since libproj & sqlite3 seem to be installed, as shown in the dnf output above.

_SOLUTION:_
Following other issues, I checked where the libproj files are:

```bash
[alex@fedora ~]$ sudo ldconfig -p | grep libproj
[sudo] password for alex: 
	libproj.so.19 (libc6,x86-64) => /lib64/libproj.so.19
	libproj.so (libc6,x86-64) => /lib64/libproj.so
```

I then tried:
```r
remotes::install_github('r-spatial/sf', configure.args= '--with-proj-lib=/lib64')
```

**which did work!**

_PROPOSAL:_
I could PR a revised README, but perhaps you will prefer to revise the configure file.
Personally, I have zero experience with configure files...

What shall we do?

Thanks a lot, Alex

**Comment by rsbivand** [comment]
This looks more like a packaging problem in the `rpm`, as `proj.pc` should be installed. Can you try to see whether it is installed, and if so, does `pkg-config proj --libs` give the right output? Is the `PKG_CONFIG_PATH=` environment variable set, and set so that it sees where `proj.pc` is installed? I'd guess that either there isn't a `proj.pc` file, or that it isn't placed on the expected path (or that `pkg-config` isn't installed).

**Comment by courtiol** [comment]
Thanks for investigating @rsbivand.

> whether [proj.pc] is installed

How can I check?

> does pkg-config proj --libs give the right output? 

This is what I get:
``` bash
[alex@fedora ~]$ pkg-config proj --libs
-lproj 
```
>  Is the PKG_CONFIG_PATH= environment variable set

In env no:
```
[alex@fedora ~]$ env | grep PKG
[alex@fedora ~]$ 
```
> (or that pkg-config isn't installed)

It is: 
```bash
[alex@fedora ~]$ pkg-config --version
1.7.3
```

> So is /usr/lib64/pkgconfig on PKG_CONFIG_PATH=?

Not as shown above.

What step should have created this PATH automatically?
The dnf call to install proj-devel?

**Comment by rsbivand** [comment]
To debug this, you would need to download the source package tarball, unpack it, and run `./configure` in the root package directory. I would have expected your output to say where to find `-lproj`, so `-L/usr/lib64 -lproj`, but maybe `/usr/lib64` is assumed to be searched anyway. It looks from line 392 ff in `sf/configure.ac ` that `${PROJ_CONFIG} --libs --static` is expected to provide -L unless proj.so is in a directory already on the path. In my case for PROJ installed from source, I get `-L/usr/local/lib -lproj -lsqlite3 -ltiff -lcurl -lstdc++`.

**Comment by courtiol** [comment]
Many thanks, I am trying... 
... but I cannot promise to be very helpful since I admit to understand the previous message only very partially :-/

I did understand that I have to tinker with `configure.ac`, so I added some "echo" statements  and after some frustration, I discovered that for my change to take effects, I needed to install and run autoconf on the modified file so to recreate `configure`.

What I could learn from that is that the following test in `configure.ac` passes successfully:
``` bash
if test "${proj_config_ok}" = yes; 
```

after this test I have queried the variables in this region of the script and I get:
``` bash
PROJ CONFIG: pkg-config proj
PROJ LIB PATH: -lproj /usr/lib64/libsqlite3.so /usr/lib64/libtiff.so /usr/lib64/libcurl.so -lstdc++ 
PROJ INPKG LIBS: 
```
so PROJ INPKG LIBS is empty.

The command `${PROJ_CONFIG} --libs --static` returns:
```
lproj /usr/lib64/libsqlite3.so /usr/lib64/libtiff.so /usr/lib64/libcurl.so -lstdc++ 
```

I don't know if that helps and I don't know what is a packager, how to test `proj.pc` (nor what it is), but I am happy to try whatever you want me to if you explain a little what shall I do :-)

**Comment by jolars** [comment]
```r
remotes::install_github('r-spatial/sf', configure.args= '--with-proj-lib=/lib64')
```

solved it for me too, although I did need to install `geos-devel` as well, which was not listed among the required fedora packages in the README.

**Comment by rsbivand** [comment]
Thanks! The packager is the person, who writes the specification file and is responsible for publishing new versions. I'm assuming that there is a missing `-` before `lproj`, and I'm puzzled by the direct paths to the shared objects, but maybe the packager needs to do that. There is indeed no `-L/usr/lib64` there.

**Comment by courtiol** [comment]
I think I have identified where to file an issue: https://src.fedoraproject.org/rpms/proj/
@rsbivand, would you mind doing that since you will surely better phrase the problem than I can?
Thanks

**Comment by rsbivand** [comment]
Bug filed as https://bugzilla.redhat.com/show_bug.cgi?id=1958191

**Comment by neteler** [comment]
> Bug filed as https://bugzilla.redhat.com/show_bug.cgi?id=1958191

FWIW: on Fedora 33 no issues (PROJ 6.3.2). Apparently a new issue with PROJ 7. I do not have F34 yet but will try to find out what's going on (see the bug report above).
