### ISSUE TITLE
writing geojson to file with fields containing multiple values per geometry

### ISSUE THREAD

**Issue by HughSt** [r-spatial/sf#1671]
Hi,

I have a geojson where 1 field contains an array of values per geometry. This is valid GeoJSON and reads into R fine using `st_read`. However, when I write the same object back to file using `st_write` I receive the following warning indicating that field has been dropped.

```
Warning message:
In clean_columns(as.data.frame(obj), factorsAsCharacter) :
  Dropping column(s) data2 of class(es) list
```

Am I missing an argument that I should be setting when reading/writing the GeoJSON? Or is this currently not possible? Reproducible code below.

Thanks, Hugh

```
s <- st_read('{"type": "FeatureCollection","features": [{"type": "Feature","properties": {"data": 1, "data2": [2,3,4]},"geometry": {"type": "Point","coordinates": [6.148577928543091,46.25852477357608]}}]}')

# data2 field contains list of values
s$data2

# When this object is written to file, it drops data2 with a warning
st_write(s, "test_sf.geojson")

# No issue if fields are only single values per geometry
st_write(s['data'], "test_sf_data_only.geojson")
```

**Comment by edzer** [comment]
This is currently not possible.
