### ISSUE TITLE
Conversion from wkt fails with newline

### ISSUE THREAD

**Issue by dbaston** [r-spatial/sf#1674]
I would have expected this to work:

```
mp <- st_as_sfc('MULTIPOLYGON (((0 0, 2 0, 2 2, 0 2, 0 0)),
               ((2 2, 4 2, 4 4, 2 4, 2 2)))')
```

but I get:

```
OGR: Corrupt data
Error in CPL_sfc_from_wkt(x) : OGR error
In addition: Warning message:
Unexpected token :  (GDAL error 1) 
```

If the newline is removed it is parsed successfully.

**Comment by edzer** [comment]
You could use `st_as_sfc(wk::as_wkt(r))` with `r` the offending string. Or are you suggesting `sf` should do this (i.e., replace newlines with space)?

**Comment by dbaston** [comment]
It would be nice if it "just worked." `sf` could strip the newlines, or use GEOS instead (which should tolerate this). But maybe you're using GDAL to get curved geometry support?

**Comment by edzer** [comment]
> But maybe you're using GDAL to get curved geometry support?

Yes. Patch GDAL?

**Comment by dbaston** [comment]
Done.
