### ISSUE TITLE
Basic plot overlay

### ISSUE THREAD

**Issue by ahb108** [r-spatial/sf#1681]
I have come across some behaviour I don't understand with regard to basic plotting of sf LINESTRING on top of 

POLYGON which may or may not be a bug. For example ([example.rda.zip](https://github.com/r-spatial/sf/files/6545323/example.rda.zip)):

library(sf)
load("example.rda")
## Works as I anticipated
plot(midline, col="blue")
plot(front, col=NA, add=TRUE)
## Does not work as I anticipated (midline not visible)
plot(front, col=NA)
plot(midline, col="blue", add=TRUE)

> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.2.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:

[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.9-8

loaded via a namespace (and not attached):
 [1] compiler_4.1.0     magrittr_2.0.1     class_7.3-19       tools_4.1.0        DBI_1.1.1         
 [6] units_0.7-1        proxy_0.4-25       Rcpp_1.0.6         KernSmooth_2.23-20 grid_4.1.0        
[11] e1071_1.7-7        classInt_0.4-3

**Comment by kadyb** [comment]
Probably you should  use this:

```r
plot(front, col=NA, reset=FALSE)
plot(midline, col="blue", add=TRUE)
```

Check the documentation for more information: `?plot.sf`
