### ISSUE TITLE
Join error due to column renaming and `sf_column` attribute

### ISSUE THREAD

**Issue by treysp** [r-spatial/sf#1682]
Hello,

Thank you so much for all your work on `sf`! 

I'm encountering a join error between an sf data frame and a non-sf data frame due to my renaming of the sf data frame's columns. This may be expected (and desired) behavior.

Possibly relevant details:
- sf data frame being read from file geodatabase, so geometry column is named `SHAPE` upon read
- I am renaming the sf data frame columns with `tolower(names())`
- The error is fixed by `st_geometry() <-`
- Related issues: #1415, #1431 

Data is from [this USGS link](https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHD/National/HighResolution/GDB/NHD_H_National_GDB.zip). Note that it's a 26GB file.

Reprex:

``` r
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
library(dplyr, warn.conflicts = FALSE)
#> Warning: package 'dplyr' was built under R version 4.0.4

# read data
water <- st_read("d:/data/hydrography/NHD_H_National_GDB.gdb", "NHDPoint") # geometry data
#> Reading layer `NHDPoint' from data source `D:\data\hydrography\NHD_H_National_GDB.gdb' using driver `OpenFileGDB'
#> Simple feature collection with 491483 features and 9 fields
#> Geometry type: POINT
#> Dimension:     XYZ
#> Bounding box:  xmin: -167.3785 ymin: 0 xmax: 145.7912 ymax: 70.68186
#> z_range:       zmin: 0 zmax: 0
#> Geodetic CRS:  NAD83

feature_defs <- st_read("d:/data/hydrography/NHD_H_National_GDB.gdb", "NHDFCODE") # tabular data
#> Reading layer `NHDFCODE' from data source `D:\data\hydrography\NHD_H_National_GDB.gdb' using driver `OpenFileGDB'
#> Warning: no simple feature geometries present: returning a data.frame or tbl_df

# original capitalized column names works
attr(water, "sf_column") %in% names(water) # TRUE
#> [1] TRUE

water_join <- left_join(water, feature_defs, by = "FCODE")

# lowercase column names throws error due to capitalized `sf_column` attribute
names(feature_defs) <- tolower(names(feature_defs))
names(water) <- tolower(names(water))

attr(water, "sf_column")
#> [1] "SHAPE"
attr(water, "sf_column") %in% names(water) # FALSE
#> [1] FALSE

water_join <- left_join(water, feature_defs, by = "fcode")
#> Error in sf_join(NextMethod(), attr(x, "sf_column"), suffix[1]): sf_column %in% names(g) is not TRUE

# works if geometry column name explicitly set
st_geometry(water) <- "shape"

water_join <- left_join(water, feature_defs, by = "fcode")
```

<sup>Created on 2021-05-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by edzer** [comment]
Yes, `names<-` is not a generic so sf can't protect anyone destroying the sf object's consistency with it. Don't use it, or use it on a data.frame and convert that back into an sf object.

**Comment by treysp** [comment]
Thanks for clarifying. 

It looks like dplyr has equivalent functionality with the generic [`rename_with`](https://dplyr.tidyverse.org/reference/rename.html), but if this issue has never been raised before it likely isn't worth implementing an sf method.

**Comment by edzer** [comment]
But you can use `rename` to rename columns, there's an `sf` method for that.

**Comment by treysp** [comment]
Got it - thanks for the quick reply and all your work on sf.

**Comment by jslatane** [comment]
In case this helps anyone, you can use batch lowercase names while also changing the `sf_column` attribute by using `rename_with`. Just supply `tolower` as the function argument. Using the example from above:

```r
feature_defs <- dplyr::rename_with(feature_defs, tolower)
water <- dplyr::rename_with(water, tolower)
```
