### ISSUE TITLE
Extension of GDAL ExportToWkt binding to allow the export of an srs specified format other than WKT2

### ISSUE THREAD

**Issue by jacpete** [r-spatial/sf#1690]
**Disclaimer:** This is a feature request to assist development on the [yonghah/esri2sf](https://github.com/yonghah/esri2sf) repository [\#27](https://github.com/yonghah/esri2sf/issues/27), but it could be useful for a variety of applications.

**Problem:**  In order to work with the [ESRI Map Service Query API](https://developers.arcgis.com/rest/services-reference/enterprise/query-map-service-layer-.htm) and specify the `outSR` (output spatial reference) argument we have to either have the WKTid of a CRS or a formatted [spatial reference JSON object](https://developers.arcgis.com/documentation/common-data-types/geometry-objects.htm) that contains a WKT representation of the CRS. However, because we are dealing with an ESRI product here, WKT format is the `wkt_esri` representation not the `wkt2` format that the {sf} package is using.

https://github.com/r-spatial/sf/blob/405ca1ca4ebdbd5672948aea88251e5d12004740/src/gdal.cpp#L115-L128

So the hope here is that {sf} would consider extending the above C++ code to allow the `FORMAT` argument of GDALs exportToWkt function to be specified by a higher level R function (it looks like adding options here has already been discussed by the comment on line 115). Alternatively, if access to the GDAL utility [gdalsrsinfo](https://gdal.org/programs/gdalsrsinfo.html) could be made accessible through the sf::gdal_utils() function I believe it would present a similar solution.

I am happy to do what I can to help create a pull request for this but I would like to know which of the above proposed solutions (or any alternatives) would be most acceptable to the {sf} maintainers. I don't currently have an C++ experience, but I am armed with a couple books, an internet full of resources, and about 3 year old itch to find the time somewhere to learn.

**Comment by edzer** [comment]
This gives me
```r
library(sf)
# Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
cat(st_crs(4326)$WKT1_ESRI, "\n")
# GEOGCS["GCS_WGS_1984",
#     DATUM["D_WGS_1984",
#         SPHEROID["WGS_1984",6378137.0,298.257223563]],
#     PRIMEM["Greenwich",0.0],
#     UNIT["Degree",0.0174532925199433]] 
```

**Comment by jacpete** [comment]
Wow that was quick and pretty simple. I threw together a couple visual tests to check it out and thought I would post them here too.

```
#remotes::install_github("r-spatial/sf")
library(sf) 
# Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
library(rvest)

getWKT <- function(wktID, esri = FALSE) {
  if (esri) {
    url <- paste0("https://epsg.io/", wktID, ".esriwkt")
    wkt <- readLines(con = url, warn = FALSE)
  } else {
    url <- paste0("https://epsg.io/", wktID, ".wkt")
    html <- rvest::read_html(url)
    wkt <- rvest::html_text(rvest::html_element(html, "p"))
  }
  wkt
}
WKTunPretty <- function(wkt) {
  gsub("\\n[[:blank:]]*", "", wkt)  
}

#How does it compare to the ESRI WKT pulled from epsg.io as a check?
st_crs(4326)$WKT1_ESRI %>% WKTunPretty()
# [1] "GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]"
getWKT(4326, esri = TRUE)
# [1] "GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137,298.257223563]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.017453292519943295]]"
```

They aren't exactly the same due to some rounding differences, but not a big deal. Next I did a check to verify that GDAL could transform different inputs into the ESRI WKT. I didn't expect this to be an issue at all but it was a sanity check for myself.

```
#Don't expect this to be an issue in anyway but I figured I would check different inputs to st_crs (inputs pulled from epsg.io)
c(
  "OGC WKT" = st_crs('GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]')$WKT1_ESRI %>% WKTunPretty(),
  "ESRI WKT" = st_crs('GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]')$WKT1_ESRI %>% WKTunPretty(),
  "PROJ.4" = st_crs("+proj=longlat +datum=WGS84 +no_defs")$WKT1_ESRI %>% WKTunPretty(),
  "WKTid" = st_crs(4326)$WKT1_ESRI %>% WKTunPretty()
)

# OGC WKT 
# "GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]" 
# ESRI WKT 
# "GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]" 
# PROJ.4 
# "GEOGCS[\"GCS_unknown\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]" 
# WKTid 
# "GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]"
```

I believe that's all the functionality I was looking for. Thank you for being so quick and responsive @edzer.
