### ISSUE TITLE
Win "r-release" binaries still at 0.9-8

### ISSUE THREAD

**Issue by Alternikaner** [r-spatial/sf#1698]
Not sure if it is intentional, or if there's a (CRAN-side?) delay in compiling binaries for Windows, but only the r-devel branch seems to be pointing to the new 1.0-0 binaries for this platform.

As an aside, thank you for the fantastic work on sf in general and the s2 enhancements in particular.

**Comment by edzer** [comment]
Thanks! Yes, there's always something like a week delay in the binary package creation process.
