### ISSUE TITLE
Extract specific segments of st_buffer() result

### ISSUE THREAD

**Issue by kevinwolz** [r-spatial/sf#1707]
Hello, I'm trying to utilize `st_buffer()` in a specific way that I imagine might be a common use, but I cannot figure out an easy way to do this with `st_buffer()` or another `sf` function. 

Take this linestring, p:
```
coords <- matrix(c(0,0,0,1,1,1,1,2,3,2,3,1), ncol = 2, byrow = TRUE)
p <- st_linestring(x = coords)

ggplot() +
  geom_sf(data = p, color = "black")
```
![image](https://user-images.githubusercontent.com/11711566/123452006-9ddfaf80-d5a3-11eb-8561-856215bfa347.png)

I can create a one-sided polygon buffer using `st_buffer()` like this:
```
p1 <- st_buffer(x = p, dist = -0.5, singleSide  = TRUE)

ggplot() +
  geom_sf(data = p1, color = "green", fill = "white") +
  geom_sf(data = p, color = "black")
```
![image](https://user-images.githubusercontent.com/11711566/123453116-c2885700-d5a4-11eb-955a-3bc292ee0a28.png)

However, I don't want the full polygon. I just want the edge(s) of the polygon that comprise the new line that is **parallel** to the original line (i.e. not the portion underneath the original line and not the two segments that go from 0,0 to 0,0.5 and from 2.5,1 to 3,1). **How do I extract just this portion after making the buffer?**

Currently, in the absence of a more elegant solution, here's what I am doing:
```
p1.segments <- stdh_cast_substring(x = p1, to = "LINESTRING")
removal.buffer <- st_buffer(x = p, dist = 1e-3, singleSide  = TRUE)
p1.desired <- p1.segments[!st_intersects(p1.segments, removal.buffer, sparse = FALSE), ] 

ggplot() +
  geom_sf(data = p1.desired, color = "red") +
  geom_sf(data = p, color = "black")
```
![image](https://user-images.githubusercontent.com/11711566/123453389-1a26c280-d5a5-11eb-8416-ea37b5ccef29.png)

This approach has the desired effect, BUT (1) relies on the non-sf function `stdh_cast_substring()` which I got from [HERE](https://rpubs.com/dieghernan/Cast-line-subsegments-R) (and is pasted below for easy reference), and (2) is potentially sensitive to less simplistic cases than what I present here. Any suggestions on how to do this using package functions and/or more elegantly would be greatly appreciated!

```
stdh_cast_substring <- function(x, to = "MULTILINESTRING") {
  ggg <- sf::st_geometry(x)

  if (!unique(sf::st_geometry_type(ggg)) %in% c("POLYGON", "LINESTRING")) {
    stop("Input should be  LINESTRING or POLYGON")
  }
  for (k in 1:length(sf::st_geometry(ggg))) {
    sub <- ggg[k]
    geom <- lapply(
      1:(length(sf::st_coordinates(sub)[, 1]) - 1),
      function(i)
        rbind(
          as.numeric(sf::st_coordinates(sub)[i, 1:2]),
          as.numeric(sf::st_coordinates(sub)[i + 1, 1:2])
        )
    ) %>%
      sf::st_multilinestring() %>%
      sf::st_sfc()

    if (k == 1) {
      endgeom <- geom
    }
    else {
      endgeom <- rbind(endgeom, geom)
    }
  }
  endgeom <- endgeom %>% sf::st_sfc(crs = sf::st_crs(x))
  if (class(x)[1] == "sf") {
    endgeom <- sf::st_set_geometry(x, endgeom)
  }

  if (to == "LINESTRING") {
    endgeom <- endgeom %>% sf::st_cast("LINESTRING")
  }
  return(endgeom)
}

```

**Comment by edzer** [comment]
I think this would fit better on stackoverflow or the like, as this is not an issue with this package.
