### ISSUE TITLE
sf doesn't compile agains most recent version of proj

### ISSUE THREAD

**Issue by mhoban** [r-spatial/sf#1711]
It looks the most recent version of proj (which is what you get when you install it via various package managers) has gotten rid of `proj_api.h` (replaced with `proj.h`), which causes sf installation to fail. 

I was able to remedy this by symlinking `proj.h` to `proj_api.h`, but this seems like something that'll come up for others so I'm posting it here.

**Comment by rsbivand** [comment]
Please note that proj_api.h is defunct in PROJ 8, and required a deprecated
flag set in 7 and 6. To continue to use the library, you must change and
update  compiled code for proj.h.

Roger Bivand
Falsensvei 32
5063 Bergen

ons. 30. jun. 2021, 05:13 skrev mhoban ***@***.***>:

**Comment by rsbivand** [comment]
And no, you must substantiate your assertion that sf fails to install using
recent PROJ. It has been checked with 8.1.0RC1, and succeeds without any
problems.

Roger Bivand
Falsensvei 32
5063 Bergen

ons. 30. jun. 2021, 05:13 skrev mhoban ***@***.***>:

**Comment by mhoban** [comment]
Well, I take it back. It didn't work the last time I tried it, but I did it over again on a clean system and it worked just fine.
