### ISSUE TITLE
cannot join g.vcf files using glnexus

### ISSUE THREAD

**Issue by kostasgalexiou** [r-spatial/sf#1714]
Hi,

When I try to merge gvcf files generated with deepvariant, using glnexus, I get the following error:

`[W::bgzf_read_block] EOF marker is absent. The input is probably truncated
Error: BCF read error`

Below is the command that I am using:

`./glnexus_cli \`
`--config DeepVariantWGS \`
`SQU1.sort.pcr_rem.RG.kept.g.vcf.gz SQU3.sort.pcr_rem.RG.kept.g.vcf.gz |  \`
`bcftools view - | \`
`bgzip -c > SQU13.vcf.gz`

My gvcf files look normal and the log file for gvcf generation did not give any errors.

Any help will be appreciated.

Thanks

**Comment by edzer** [comment]
as far as I can tell there is no R involved here.
