### ISSUE TITLE
sf st_linestring

### ISSUE THREAD

**Issue by m4rkus84** [r-spatial/sf#1722]
I have noticed that the function to convert points to lines (st_linestring()) does not maintain the original CRS. 
Even the command st_transform(line, crs=4326)  does not work for me after the conversion

**Comment by edzer** [comment]
`sfg` objects, like those obtained by `st_linestring()`, don't have a CRS. `sfc` objects have. Maybe use `st_sfc()` on the linestring?

**Comment by m4rkus84** [comment]
Thank you, I'm trying your suggestion but it produces this message:
Geometry set for 1 feature 
geometry type:  LINESTRING
dimension:      XY
bbox:           xmin: 755822.7 ymin: 5023348 xmax: 761853 ymax: 5027875
projected CRS:  WGS 84 / UTM zone 32N
LINESTRING (761853 5025099, 761795.6 5025163, 7...

And If I export the object like a shapefile I get this message:
Writing 1 features with 0 fields and geometry type Line String.

Maybe the way is correct but that '0 fields' does not sounds good

**Comment by edzer** [comment]
Well, your linestring doesn't have any attributes. Is that a problem?

**Comment by m4rkus84** [comment]
No it isn't. I have double checked and it seems to work, thank you
