### ISSUE TITLE
How to truly calculate a spherical voronoi diagram using sf?

### ISSUE THREAD

**Issue by arthurwelle** [r-spatial/sf#1723]
I want to make a world map with a voronoi tessellation using the spherical nature of the world (not a projection of it), with R/sf.

As I understand ("[Goodbye flat Earth, welcome S2 spherical geometry](https://r-spatial.org/r/2020/06/17/s2.html)") the `sf ` package is now fully based on the `s2` package and should perform as I needed. But I don't think that I am getting the results as expected. A reproducible example:

```
library(tidyverse)
library(sf)
library(rnaturalearth)
library(tidygeocoder)

# just to be sure
sf::sf_use_s2(TRUE)

# download map 
world_map <- rnaturalearth::ne_countries(
                scale = 'small', 
                type = 'map_units',
                returnclass = 'sf')

# addresses that you want to find lat long and to become centroids of the voronoi tessellation 
addresses <- tribble(
~addr,
"Juneau, Alaska" ,
"Saint Petersburg, Russia" ,
"Melbourne, Australia" 
)

# retrive lat long using tidygeocoder
points <- addresses %>% 
          tidygeocoder::geocode(addr, method = 'osm')

# Transform lat long in a single geometry point and join with sf-base of the world
points <- points %>% 
          dplyr::rowwise() %>% 
          dplyr::mutate(point = list(sf::st_point(c(long, lat)))) %>% 
          sf::st_as_sf() %>% 
          sf::st_set_crs(4326)

# voronoi tessellation
voronoi <- sf::st_voronoi(sf::st_union( points ) ) %>% 
     sf::st_as_sf() %>% 
     sf::st_set_crs(4326)

# plot
ggplot2::ggplot() +
    geom_sf(data = world_map,
            mapping = aes(geometry = geometry), 
            fill = "gray95") +
    geom_sf(data = points,
            mapping = aes(geometry = point),
            colour = "red") +
    geom_sf(data = voronoi,
            mapping = aes(geometry = x),
            colour = "red",
            alpha = 0.5)  
```

![image](https://user-images.githubusercontent.com/6665804/125209000-54ae8180-e26c-11eb-9e0e-cb67a1380bf8.png)

The whole Antarctica should be closer to Melbourne than to the other two points. What am I missing here? How to calculate a voronoi on a sphere using sf`? 

PS: I put [the same question](https://stackoverflow.com/questions/68324079/how-to-truly-calculate-a-spherical-voronoi-diagram-using-sf) on stackoverflow two days ago without (so far) successfully solve it. But I learned that GEOS doesn't automatically do computations that account for spherical geometry, and it was suggested to use Reticulate +[ SciPy](https://py-sphere-voronoi.readthedocs.io/en/latest/voronoi_utility.html) (should I go on this route?).

**Comment by edzer** [comment]
`s2` does not provide Voronoi computations. If you had set the CRS before calling `st_voronoi`, `sf` would have given you the corresponding warning.

**Comment by edzer** [comment]
`s2` does not provide Voronoi computations. If you had set the CRS before calling `st_voronoi`, `sf` would have given you the corresponding warning.

**Comment by arthurwelle** [comment]
Thanks for the answwer @edzer. `sf ` is now fully based on the `s2`, but to the limits of `s2` (of course). Well, Reticulate it is!
