### ISSUE TITLE
Incorrect (?) output st_crop and st_intersection with S2

### ISSUE THREAD

**Issue by Buitenwerf** [r-spatial/sf#1725]
Hello, 

I'm trying to `st_crop()` and/or `st_intersection()` some polygons (WGS 84) with a simple bounding box, but get unexpected output when the bounding box contains negative longitude coordinates. The problem does not occur when the polygons do not have a crs. 

Am I not understanding how these functions work, or is something strange going on? Here an example for `st_crop()`:

``` 
library(sf)

pol = st_as_sfc(st_bbox(c(xmin = 0, ymin = 0, xmax = 180, ymax = 1), crs = st_crs(4326)))  

box_1 = c(xmin = 0, ymin = 0, xmax = 170, ymax = 1)  
st_bbox(st_crop(pol, box_1))
```
so far so good
```
box_2 = c(xmin = -10, ymin = 0, xmax = 170, ymax = 1)
st_bbox(st_crop(pol, box_2))
```
I fail to see why the result here is different from the first `st_crop()`

Many thanks!

**Comment by Buitenwerf** [comment]
I just discovered things work as expected with `sf_use_s2(FALSE)` so I will do that for now. 

Thanks again

**Comment by edzer** [comment]
Since `sf` 1.0-0, for ellipsoidal coordinates (as in your case) `sf` uses spherical geometry, meaning that great circles between points are used, rather than straight lines in a _Cartesian_ space of longitude and latitude. If you define a line by two points on exactly opposite sides of the sphere, the great circle line between them is completely undefined.

**Comment by Buitenwerf** [comment]
Thanks, this makes sense. I am still struggling to understand how best to create the equivalent of a bounding box to crop/intersect in s2 world, where the "bounding box" spans more than half the globe, but it seems this is likely my lack of understanding.

**Comment by edzer** [comment]
`st_segmentize` it along the parallels, i.e. either with `s2` off, or with CRS set to NA or projected to +proj=eqc.

**Comment by Buitenwerf** [comment]
Ah, excellent! This should work, thanks a lot!
