### ISSUE TITLE
library(sf) failed due to missing function of the Rcpp package

### ISSUE THREAD

**Issue by Suspicis** [r-spatial/sf#1727]
The following error code occurs:

> library(sf)
Error: Failed to load package or namespace for 'sf'.
 .onLoad in loadNamespace() for 'units' failed, details:
  Call: udunits_init(path)
  Error: The function 'Rcpp_precious_remove' is not provided by package 'Rcpp'.

**Comment by edzer** [comment]
You may have to reinstall packages `Rcpp`, `units`, and maybe then `sf` also.

**Comment by Suspicis** [comment]
Thanks for your quick reply. Reinstalling `Rcpp` solved the problem!

**Comment by FCArguibel** [comment]
Thanks for your quick reply.

Reinstalling `Rcpp`, `units` y `sf` has solved the problem.
