### ISSUE TITLE
Package does not load

### ISSUE THREAD

**Issue by FCArguibel** [r-spatial/sf#1728]
Hello everyone,
I'm trying to load the package on my computer. Here are the characteristics of my computer.

```
platform x86_64-w64-mingw32          
arch x86_64                      
os mingw32                     
system x86_64, mingw32
version.string R version 4.1.0 (2021-05-18)
```

However, I install correctly the "sf" package but then when I want to load the library I get the following error:
```
Error: package or namespace load failed for 'sf':
 .onLoad failed in loadNamespace() for 'sf', details:
  call: CPL_set_data_dir(prj)
  error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'.

```
Does anyone know how I can fix it? I would appreciate help as I am lost.

**Comment by edzer** [comment]
How about checking recently closed issues first?

**Comment by FCArguibel** [comment]
Hi @edzer, thanks for the prompt reply.

I checked the recently closed issues, but I'm fairly new to this and didn't understand much. I have uninstalled Rstudio and reinstalled but it still doesn't work.

Could you please help me?

**Comment by edzer** [comment]
Look here: https://github.com/r-spatial/sf/issues/1727
