### ISSUE TITLE
Failure to compile v1.0-1 on macOS causing build error

### ISSUE THREAD

**Issue by nicholascarey** [r-spatial/sf#1733]
Hi 

A lack of a binary version of `v1.0-1` and then failure to compile it on macOS is causing a build error on my R package. The log can be seen  [here](https://github.com/januarharianto/respR/runs/3131777252?check_suite_focus=true)

For a manual install I can choose "no"  on the `Do you want to install from sources the packages which need compilation? (Yes/no/cancel)` prompt, in which case the `v1.0-0` binary installs fine, but I've failed to find any option to set this as a default in, for instance, my package DESCRIPTION so that automatic builds or users do not encounter this problem. 

`sf` is not a direct dependency, but is of several of my dependencies. I have tried adding `sf` as a specific dependency with the version `sf (== 1.0-0)` but this failed to work. 

Perhaps I am missing a dependency that will allow `v1.0-1` to be compiled ? 

I'm not sure how to resolve this. Any advice would be welcome. 

I realise this is probably related to this issue - #1703 - and `gdal` but the discussion there is far beyond my understanding. 

By the way, `v1.0-1` fails to compile on both my own development machine (an M1 Mac) and an Intel Mac, both on Big Sur. 

Thanks

**Comment by rsbivand** [comment]
This is the same result as CRAN checks: https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/sf-00install.html and https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/sf-00install.html. It is related to the deficiencies in generating the `proj.pc` file when building PROJ. If you can dig into how your process builds PROJ, it may be that an extra argument can be added to encourage it to yield a `proj.pc` that works. It may also be necessary to ensure that `libsqlite3` etc. are visible to the **sf** `configure` step.

**Comment by edzer** [comment]
@rsbivand: it's related to this error message:
```
./configure: line 3769: Darwin: command not found
```
which results from an error in (my) configure.ac, and configure; now fixed in 1.0-2 (not yet on CRAN).

**Comment by rsbivand** [comment]
OK, good that you tracked it down. I'll try to confirm, but that sounds sensible. So installing source from github should work.

**Comment by nicholascarey** [comment]
Ok, great. Thanks. In other words sit tight and it will be resolved when this version is available? 

Any idea of a rough timeline of when that might be?  I'm planning my own submission of this to CRAN soon and hoping this won't hold it up. 

If i understand [this (at very bottom)](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html) correctly, I cannot have Github dependency remotes on submission to CRAN.

**Comment by edzer** [comment]
Pretty soon I hope, waiting for a report from @appelmar on whether my fix will work (there's no win-builder analogy for OSX)

**Comment by nicholascarey** [comment]
Ok, thanks a lot.

**Comment by edzer** [comment]
1.0-2 is now on CRAN, OSX binaries typically follow after a few days...

**Comment by nicholascarey** [comment]
Binary installed now on both M1 and Intel Macs, and no build errors in the package. 
Thanks!  🥳

**Comment by edzer** [comment]
Thanks for reporting!
