### ISSUE TITLE
Can't load sf package

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [r-spatial/sf#1743]
Hi I can't load sf on windows x64. I am able to install it from windows binaries (somehow compilation doesn't work), but when I load sf it gives me an only error: R session aborted , R encountered fatal error, the session was terminated, start new session. I use R 4.1 x64 and Rstudio daily from today. I tried  to install older sf versions like 1.0.0 and 1.0.1 but it was the same.

**Comment by edzer** [comment]
Have you tried using a released Rstudio version instead of "daily"?

**Comment by Andrzej-Andrzej** [comment]
I just have installed normal version of RStudio 1.4.1717 and later I tried 1.4.1725 (preview) and both didn't work. I got the same error. Other packages like tidyverse load correctly.

**Comment by rsbivand** [comment]
What happens in regular Rgui? What else is being loaded/attached? Output of `sessionInfo()` before `library(sf)`? Verbatim error message in Rgui or in the Windows console/terminal?

**Comment by Andrzej-Andrzej** [comment]
In Rgui 4.1 x64 when I try to load sf it hangs for a moment a closes a few seconds afterwards. I tried to unload all other packages and load only sf but the problem persists.

**Comment by rsbivand** [comment]
Are debris from your failed attempt to install from source present? How many libraries are being used? What does `.libPaths()` say? Is a damaged **sf** in a library being searched before the library containing the installed CRAN binary?

**Comment by Andrzej-Andrzej** [comment]
Where should I look for these debris ? 
.libPaths() says: C:/Program Files/R/R-4.1.0/library

**Comment by edzer** [comment]
Have you tried reinstalling `sf`? If that didn't work, reinstalling `Rcpp`?

**Comment by Andrzej-Andrzej** [comment]
Thank you very much indeed, I reinstalled Rcpp and now it works. Thanks again.

**Comment by rsbivand** [comment]
Typically, `.libPaths()` should contain (at least) two character strings, the system library (the one you report) second, and the user-writable library with packages you installed yourself first (often in the user's `Documents/R/win-library/<R-version>` directory).
