### ISSUE TITLE
Constrain st_distance somehow by a constraining polygon?

### ISSUE THREAD

**Issue by BajczA475** [r-spatial/sf#1744]
I have a polygon of a lake, sample points within the lake (blue), and then a public boat launch on the edge of a lake (red). 
![lake data](https://user-images.githubusercontent.com/15620636/127689303-3ad38053-0fd4-4d14-bcf4-e40618cef855.png)

st_distance() will calculate the straight-line distance between all the sample points and the boat launch just fine, but these calculations assume it's ok to cross land, which wouldn't be how a boat moves, and that's what we're interested in. Is there a way to create a "wrapper" of st_distance() that can take a constraining polygon (the lake edge) and force the distance lines calculated by st_distance() to break into two or more segments as necessary that can then "bend" around intervening land? I assume this would be relatively complicated (without converting the data to raster data perhaps!), but I'm not sure, so I thought I'd ask!

**Comment by edzer** [comment]
Wrong place to ask - this is not an issue with package `sf`. Maybe stackoverflow, or r-sig-geo?
