### ISSUE TITLE
Can't install sf dev version

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [r-spatial/sf#1747]
Hi, I have tried to install sf dev version (and it returns: sf had no zero exit status). I use R 4.1 x64 and Rstudio released version for windows 10.
I checked RTools according to this: [https://cran.rstudio.com/bin/windows/Rtools/](url) and I compiled this: `install.packages("jsonlite", type = "source")` as guided in  tutorial without any problems so I assume that with my RTools everything is OK. 
Compiltaions stops somewhere here: 
"./windows/gdal3-3.2.1/lib/i386/libcfitsio.a(getcolj.c.obj):(.text+0x1f3a): undefined reference to `__divmoddi4'
../windows/gdal3-3.2.1/lib/i386/libcfitsio.a(getcolj.c.obj):(.text+0x68d4): more undefined references to `__divmoddi4' follow
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'sf'

Please advise, thank you

**Comment by edzer** [comment]
Maybe @jeroen has an idea?

**Comment by jeroen** [comment]
Can you show the full output log? There is a problem with your R configuration. I suspect you are using rtools 3.x to compile instead of rtools4.

**Comment by Andrzej-Andrzej** [comment]
I use Rtools 4.0 v2 - so the newest. Some of the dev version packages compile properly and some don't. I checked on other 2 laptops and problem persists.

**Comment by jeroen** [comment]
> Can you show the full output log?

**Comment by Andrzej-Andrzej** [comment]
I will try as output in the console looks very long

**Comment by Andrzej-Andrzej** [comment]
What should I do to prepare full install log, as copying from console is difficult.

**Comment by rsbivand** [comment]
`install.packages("sf", type="source")`

No problem here for R 4.1.0, but latest Rtools40 from CRAN identifies in Windows Settings -> Apps & Features as Rtools 4.0 (4.0.1.0) - I reinstalled yesterday to check.

To copy from the console: in RGui, Edit -> Select all, then Edit -> Copy; paste into for example Notepad and save as a text file to upload here.

**Comment by Andrzej-Andrzej** [comment]
This output is so huge that I can't scroll back to the beginning (to the command prompt in console up there) in order to copy it as a whole. How do I do it ? Is it some kind of limit in R console that limits a display's output ?

**Comment by rsbivand** [comment]
Use Select all in the File menu in Rgui. Of course all consoles limit the # lines. Try rather R CMD check of the tarball to generate a 00install.out file. The problem is with your installations, so unreproducible elsewhere, which is why (at least parts of) the console output must be provided. If this is too hard, use only Windows binary versions, from CRAN or try https://r-spatial.r-universe.dev/ui#builds for the newest development version.

**Comment by Andrzej-Andrzej** [comment]
Thank you for all your help, can you explain why `R CMD check sf_1.0-2.tar.gz` not working ? I opened cmd in windows 10 as administrator and received an error: 'R' is not recognized as an internal or external command, operable program or batch file. How do I should zip the 00install.out ?

**Comment by rsbivand** [comment]
Well, you probably need to either put where `R.exe` lives in your `PATH` variable, or give a complete path: `"C:/Program Files/R/R-4.1.0/bin/x64/R.exe" CMD check sf_1.0-2.tar.gz`

**Comment by Andrzej-Andrzej** [comment]
1. So is it beyond R capabilities to to provide full console  output ?
I have found this, but this is an old post: [https://stackoverflow.com/questions/9206932/capture-output-of-install-packages](url)
2. When I run code from previous post in Windows Command Prompt nothing is happening and 00install.out file wasn't created. 
3. I am grateful for directing me to: [https://r-spatial.r-universe.dev/ui#builds](url) as zip file installed correctly and I did not know about this link before. But I still would like to learn about getting full install log output.

**Comment by rsbivand** [comment]
1. Rgui -> Edit -> GUI preferences ... sets 250000 characters or 8000 lines as the console default, which the user can modify. In Rgui, the following generates `sf.out`: `install.packages("sf", repos="https://cloud.r-project.org", type="source", keep_output=TRUE)` .
2.  Try `"C:/Program Files/R/R-4.1.0/bin/x64/R.exe"` first to see that R is there.
3. See 1., best with `keep_output=TRUE`, which avoids changing console defaults.

**Comment by rsbivand** [comment]
Because of the way **remotes** works, `keep_outputs=` does not work with install functions in that package: https://github.com/r-lib/remotes/issues/588#issuecomment-783517600
