### ISSUE TITLE
Avoid use of GDAL in st_dimension

### ISSUE THREAD

**Issue by dbaston** [r-spatial/sf#1752]
`st_dimension(x)` copies its input into an OGR geometry type. In a test of 100,000 point-in-polygon intersections, this takes ~25% of the runtime:

![image](https://user-images.githubusercontent.com/6318931/128503071-36c8cf7d-ce8a-4dce-b1a6-34b1e9cc8c0e.png)

It seems like the topological dimension could be more easily determined from `class(x)`.

**Comment by edzer** [comment]
The problem is what to do with `GEOMETRYCOLLECTION`?
