### ISSUE TITLE
Compatibility with arrow storage formats

### ISSUE THREAD

**Issue by wlandau** [r-spatial/sf#1756]
I have heard reports of folks having trouble saving `sf` objects using the feather and parquet formats from the `arrow` package. I do not personally work with spatial data, but @jaredlander could fill you in. 

A lot has happened since #10, including list column support for both feather and parquet. https://github.com/ropensci/targets/discussions/599 is also relevant, but I feel this thread is appropriate for discussion because a solution in `sf` and `arrow` could help far more R users than just users of `targets`.

**Comment by jaredlander** [comment]
I'll try to create a reproducible example, but have had great failure trying this.

But question, does `write_sf()` support writing to parquet or do I have to do this using the `{arrow}` package? (Using `{arrow}` is how I've been failing.)

**Comment by edzer** [comment]
write_sf won't do that, as it writes through gdal, and there's no driver for arrow or parquet afaict. Have you tried writing with pkg arrow after removing the sf class, e.g. using as.data.frame or as_tibble on the sf object?

On August 13, 2021 4:56:16 AM GMT+02:00, Jared Lander ***@***.***> wrote:
>I'll try to create a reproducible example, but have had great failure trying this.
>
>But question, does `write_sf()` support writing to parquet or do I have to do this using the `{arrow}` package? (Using `{arrow}` is how I've been failing.)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/r-spatial/sf/issues/1756#issuecomment-898144635
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by edzer** [comment]
Have you checked https://github.com/r-spatial/sf/pull/2036 and the `use_stream` argument in `st_read()`? Doesn't `sf` support (write) support go (geo)parquet once GDAL supports this?

**Comment by mlhollestelle** [comment]
Thanks for the quick response. This looks good.
