### ISSUE TITLE
st_as_text autodetect (or guess) precision, or documentation updates

### ISSUE THREAD

**Issue by mkoohafkan** [r-spatial/sf#1764]
The documentation for `st_as_text()` make only a brief mention of output precision in the description of `...` arguments:

<html>
<body>

... | modifiers; in particular digits can be passed to control the number of digits used
-- | --

</body>
</html>

In addition, the use of `st_precision()` and `st_set_precision()` is a wild goose chase in this use case because 
1) the `precision` setting is usually an attribute of the `sf data.frame` object rather than the geometry itself, and 
2) even if you manually set the precision of the individual `sfc` objects it will *still* be ignored by `st_as_text()`.

It would be helpful if either

1) `st_as_text()` can guess the precision of the `sfc` object, rather than defaulting to one decimal place
2) `st_as_text()` is verbose about the default precision when `digits` is not specified
3) call out the `digits` argument for `st_as_text()` more prominently, and mention in the documentation for `st_precision()` that setting precision in this way will not affect the WKT representation of the object.

**Comment by edzer** [comment]
```r
> st_as_text(st_point(c(1/3,2/3)))
[1] "POINT (0.3333333 0.6666667)"
> st_as_text(st_point(c(1/3,2/3)), digits = 3)
[1] "POINT (0.333 0.667)"
> print(st_point(c(1/3,2/3)), digits = 3)
POINT (0.333 0.667)
> c(1/3,2/3)
[1] 0.3333333 0.6666667
```
this is only about textual representation (printing), not about any rounding to some grid that takes place before computations. For rounding, precision has to be set. `st_as_text()` will never be guessing anything, and doesn't default to one decimal place. Default for printing is identical to the defaults of R. 

It looks like you are confusing printing and rounding to grid; I'm closing this, please reopen if anything remains unclear.
