### ISSUE TITLE
undefined reference error during install

### ISSUE THREAD

**Issue by HantaoShu** [r-spatial/sf#1769]
I try to install sf following the tutorial on Ubuntu 16.04 and R 4.1.
After install  libudunits2-dev libgdal-dev libgeos-dev libproj-dev by using apt, I try to install sf by using install.package('sf') in R 4.1 and get following error
......
/home/shuhantao/anaconda2/envs/R4/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib/libgdal.so: undefined reference to `curl_easy_cleanup@CURL_GNUTLS_3'
/home/shuhantao/anaconda2/envs/R4/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib/x86_64-linux-gnu/libcurl.so: undefined reference to `ldap_first_message@OPENLDAP_2.4_2'
/home/shuhantao/anaconda2/envs/R4/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib/x86_64-linux-gnu/libodbc.so: undefined reference to `lt_dlclose'
/home/shuhantao/anaconda2/envs/R4/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib/libgdal.so: undefined reference to `sqlite3_result_double' 
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘sf’

Is there any advice?

**Comment by edzer** [comment]
I'm sorry, conda is not a platform we are supporting; please ask help there.

**Comment by HantaoShu** [comment]
So this error is caused by conda?  Thanks, and I have closed this issue.
