### ISSUE TITLE
st_make_grid makes grid that does not intersect with all points

### ISSUE THREAD

**Issue by mem48** [r-spatial/sf#1777]
I've had an intermittent bug appear in code that use to work (documented here https://github.com/ropensci/stplanr/issues/466)

The problem is occurring because

```
sf::st_intersects(p, sf::st_make_grid(p, what = "polygons"))
```
returns empty values. Where `p` is a set of points.

I can reproduce the problem with a simple example:

```
library(sf)
# Make some random lat/lng in Yorkshire
p <- data.frame(id = 1:1e5,
                lat = runif(1e5, 53, 54), 
                lng = runif(1e5, -2.7, -0.2))
p <- st_as_sf(p, coords = c("lng","lat"), crs = 4326)

# Make a grid around those points
grid <- st_make_grid(p, what = "polygons")

# Check those points intersect the grid
inter <- st_intersects(p, grid)

summary(lengths(inter)) # Should always be > 0 but isn't
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
# 0       1       1       1       1       1
```

If I plot the points that don't intersect with the grid they are always on the outside edge

![image](https://user-images.githubusercontent.com/15819577/131754859-fe76165b-98ef-4c59-a0ba-bd01286dcd24.png)

The bounding boxes of the grid and the points are identical, so why don't the points intersect with any of the polygons in the grid?

**Comment by edzer** [comment]
Looks like more fall-out of using spherical geometry; setting `sf_use_s2(FALSE)` prior to `st_intersect()` should do. The reason might be that the horizontal "straight lines" you see as polygon boundaries you think of them as lines with constant latitude; with spherical geometry they are however great circle arcs, which don't follow constant latitude (except on the equator).

**Comment by mem48** [comment]
I wondered if it was related to `s2`. I've checked and the problem doesn't seem to occur with projected CRS. Is there a long-term fix where the grid is larger and so does include all the points?

**Comment by edzer** [comment]
This is not a bug, it is a feature (of spherical geometry).

**Comment by mem48** [comment]
Granted, but I think most users will expect a grid produced from a group of points to intersect with all those points, not just some of them.
