### ISSUE TITLE
Weighted centroids

### ISSUE THREAD

**Issue by williamlai2** [r-spatial/sf#1784]
Would it be good to have some sort of weighted centroid function? Ideally where you could group by another column? Something like the `UID ` field in [mean coordinates in QGIS](https://docs.qgis.org/3.16/en/docs/user_manual/processing_algs/qgis/vectoranalysis.html?highlight=mean%20coordinates#mean-coordinate-s).

`spatialEco::wt.centroid()` sort of does this, but doesn't allow you to group by a unique id. I have put this in to an sf version, but it doesn't group, which I was hoping to do. The use case I am thinking of is for population weighted centroids of one geographical area, weighted by the population of a smaller geographical area.

```
library(sf)

weighted_centroid <- function(x, weight){
  if (!inherits(x, "sf")) 
    stop(deparse(substitute(x)), " must be a 'sf' object")
  
  p <- x[[weight]]
  Xw <- sum(st_coordinates(x)[, 1] * p)
  Yw <- sum(st_coordinates(x)[, 2] * p)
  wX <- Xw/sum(p)
  wY <- Yw/sum(p)
  df <- data.frame(wX = wX, wY = wY)
  xy <- st_as_sf(df, coords = c("wX", "wY"))
  return(xy)
  
}

# test using the example from https://www.rdocumentation.org/packages/spatialEco/versions/1.3-7/topics/wt.centroid
meuse_sf <- st_as_sf(meuse)
weighted_centroid(meuse_sf, 'zinc')
spatialEco::wt.centroid(meuse, 'zinc')
```

**Comment by juansebastianl** [comment]
I think this a cool idea, but I think it would be confusing given the current behavior `st_centroid` which produces the centroid of each row. This is more akin to a summary function, like the ideal syntax would be something like 

     df %>% 
        group_by(gid) %>% 
             st_summarize(..., type = "weighted_centroid", weights = weight_column) %>% 
        ungroup()

But that's clearly a bigger kind of function because sf currently doesn't have `st_summarize` and is already extremely slow with normal `st_summarize`

**Comment by ryanzomorrodi** [comment]
For future people, I made a package called [centr](https://ryanzomorrodi.github.io/centr/) (Not on CRAN quite yet, but maybe soon). That does exactly this. It even supports lon lat geometries using a spherical representation of earth (like s2) and its quite a lot faster than using [`tidyr::uncount` to generate one point for each person](https://stackoverflow.com/a/69809208/25690756). 

``` r
library(centr)
library(tidycensus)
library(tidyverse)
library(sf)

NC_tracts <- get_decennial("tract", state = "NC", "P1_001N", year = 2020, geometry = TRUE) %>%
  filter(!st_is_empty(.)) %>%
  mutate(COUNTY = str_sub(GEOID, 1, 5)) 

NC_counties <- st_read(system.file("shape/nc.shp", package="sf")) 
```

``` r
mean_center(NC_tracts, group = "COUNTY", weight = "value")

plot(st_geometry(NC_counties))
plot(st_geometry(NC_counties_pwc), col = "red", add = TRUE)
```

![](https://i.imgur.com/50wV6Ui.png)
