### ISSUE TITLE
sf giving slightly wrong locations on map.

### ISSUE THREAD

**Issue by monkeytronics** [r-spatial/sf#1785]
I'm seeing an issue where the locations coming out of geom_sf are consistently wrong. I've double checked the lat, long numbers. Let me share what I'm seeing. 

Check:
device_map$long
[1] 174.7835 174.7835 174.7835 174.7835 174.7835 174.7835 174.7835
> device_map$lat
[1] -41.34071 -41.34071 -41.34071 -41.34071 -41.34071 -41.34071 -41.34071

Code:

long_min <- min(device_map$long) - 0.25
long_max <- max(device_map$long) + 0.25
lat_min  <- min(device_map$lat) - 0.25
lat_max  <- max(device_map$lat) + 0.25

world <- ne_countries(scale = "large", returnclass = "sf")
class(world)

ggplot(world) +
    geom_sf() +

    # manually assign colours based on 'connected'
    geom_point(data = filter(device_map, connected == TRUE), aes(x = long, y = lat),
             size = 2, colour="green3") +

    geom_point(data = filter(device_map, connected != TRUE), aes(x = long, y = lat),
           size = 2, colour="red3") +

    scale_shape_manual(values = c(20, 4), breaks = waiver(), na.value = NA) +

    coord_sf(xlim = c(long_min, long_max), ylim = c(lat_min, lat_max), expand = TRUE) +

   # theme() +

    labs(
      title = paste("Deployment in", city),
      subtitle = report_months,
      caption = waiver(),
      tag = waiver()
    )

Output:
The output is in the sea! But the lat, long is actually an address. I see the same thing all over the country! Any help?

![image](https://user-images.githubusercontent.com/8485854/132140865-7565150a-9336-441d-9de9-dc4125921f24.png)

**Comment by markolipka** [comment]
`ne_countries(scale = "large")` might be too coarse to correctly image the rugged coastline at this location.

I wasn't able to test it with the highres version of `ne_countries()` (scale = "large") but the problem can be illustrated with the two coarser scales "small" and "medium":

<img width="473" alt="image" src="https://user-images.githubusercontent.com/9739839/132143241-d7c39fe0-0505-4b98-9418-c15398fac062.png">

**Comment by monkeytronics** [comment]
I see. I was originally using medium, and switched to large. Large is slightly better, but still very rough indeed, against the actual map you overlaid above. Any hints how to increase the res?

**Comment by markolipka** [comment]
If you need to have the coastline only, find high resolution Geodata for the regions you want to map. If other background maps are ok as well, you could use map services like OSM, Stamen or Google Satellite images instead.
