### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Hongjinwu** [r-spatial/sf#1786]
I am trying to install sf in an environment of Centos7+R4.0.2 via command "install.packages("sf", type = "source", configure.args = "--with-gdal-config=/home/wuhj/software/gdal-3.3.1/apps/gdal-config --with-proj-lib=/home/wuhj/software/proj-6.0.0/build/lib")". But failed with the following error:

>install.packages("sf", type = "source", configure.args = "--with-gdal-config=/home/wuhj/software/gdal-3.3.1/apps/gdal-config --with-proj-lib=/home/wuhj/software/proj-6.0.0/build/lib")
试开URL’https://mirrors.tongji.edu.cn/CRAN/src/contrib/sf_1.0-2.tar.gz'
Content type 'application/octet-stream' length 3645982 bytes (3.5 MB)
==================================================
downloaded 3.5 MB

* installing *source* package ‘sf’ ...
** 成功将‘sf’程序包解包并MD5和检查
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
configure: gdal-config set to /home/wuhj/software/gdal-3.3.1/apps/gdal-config
checking gdal-config exists... yes
checking gdal-config executable... yes
checking gdal-config usability... yes
configure: GDAL: 3.3.1
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
/home/wuhj/software/gdal-3.3.1/libgdal.la: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
/home/wuhj/software/gdal-3.3.1/libgdal.la: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/wuhj/software/R-4.0.2/library/sf’

bty: there two versions of gdal are installed in my operate system(2.3.1 and 3.3.1). 
Can you help me. Thanks!

**Comment by edzer** [comment]
the [README](https://github.com/r-spatial/sf#multiple-gdal-geos-andor-proj-versions-on-your-system) explains this will not work. This is not the right place to ask questions about how to clean up your system.
