### ISSUE TITLE
Use `message()` instead of `cat()` in `sf::sf_use_s2()`

### ISSUE THREAD

**Issue by eliocamp** [r-spatial/sf#1788]
I've noticed that `sf::sf_use_s2()` will print a `Spherical geometry (s2) switched on/off` message when the setting is changed. However, this message is printed using cat in this line:

https://github.com/r-spatial/sf/blob/7a0ec2c3a9a3820f647aca885cf6dfb9011c6903/R/s2.R#L19
 
I suggest to use `message()` here, since it's easier for the user to suppress. In my case, I put `sf::sf_use_s2(FALSE)` on an rmarkdown chunk with `message = FALSE` and `warning = FALSE`, but I still got `## Spherical geometry (s2) switched off` printed on the final PDF.

**Comment by edzer** [comment]
Yes, please read & use #1782 for this discussion.
