### ISSUE TITLE
st_as_grob.sfc_*POLYGON() doesn't handle empty polygons correctly

### ISSUE THREAD

**Issue by yutannihilation** [r-spatial/sf#1789]
(Originally reported here: https://github.com/tidyverse/ggplot2/issues/4607)

`gpar()` parameters aren't skipped for the empty geometries. I think I can eventually create a pull request for this, but it takes some time.

``` r
library(ggplot2)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

m <- rbind(c(0, 0), c(1, 0), c(0, 1), c(0, 0))

p1 <- st_polygon()
p2 <- st_polygon(list(m))

d <- st_sf(fill = c("red", "yellow"), geometry = st_sfc(p1, p2))
d
#> Simple feature collection with 2 features and 1 field (with 1 geometry empty)
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 0 ymin: 0 xmax: 1 ymax: 1
#> CRS:           NA
#>     fill                       geometry
#> 1    red                  POLYGON EMPTY
#> 2 yellow POLYGON ((0 0, 1 0, 0 1, 0 0))

ggplot(d) +
  geom_sf(aes(fill = fill)) +
  scale_fill_identity() +
  coord_sf(xlim = c(0, 2), ylim = c(0, 2)) +
  ggtitle("The triangle should be yellow")
```

![](https://i.imgur.com/HY78l5o.png)

<sup>Created on 2021-09-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is because the empty element is removed by `unlist()` here. I don't confirm it yet, but probably we need to fix other `st_as_grob()` as well (I confirmed at least `LINESTRING` has the same problem).

https://github.com/r-spatial/sf/blob/ee88455c79adbbccdb0015d7e7d3dcb803d92c32/R/grid.R#L179-L185

**Comment by edzer** [comment]
Thanks, I can look into that.

**Comment by edzer** [comment]
Pls have a look whether you see any dangers in doing it this way - I'm open to any other solution.

**Comment by yutannihilation** [comment]
Thanks! It seems `fill`, which users are most likely to face this problem with, is now handled correctly. But, I think the code needs to consider other parameters (e.g. `col`, `lwd`) in `gpar()`. Also, there are other parameters than `gpar()` (e.g. `rules`, `arrow`).

For `gpar()`, probably we can tweak `expand_gp()` and use it.

https://github.com/r-spatial/sf/blob/ee88455c79adbbccdb0015d7e7d3dcb803d92c32/R/grid.R#L246-L252

**Comment by edzer** [comment]
Not sure - my reasoning was that `gp` either is constant for all (in which case `length(gp$fill)` is 1) or has all fields the same length, also those that are constant. I now use the `[` method for `gpar` to make it match the actually drawn (non-empty) structures. Do you have an example that shows the proposed solution doesn't work?

**Comment by yutannihilation** [comment]
Ah, sorry. I was a bit confused. You are right. I was playing with some failing examples with the dev version of sf of the main branch, in the assumption that the commit is included there...

**Comment by yutannihilation** [comment]
It seems `gp` itself can have varying lengths of parameters. In the case of ggplot2, I think your assumption is correct, so I'm not sure if this needs to be considered.

``` r
grid::gpar(col = c("red", "blue", "green"), lwd = 1:2, fill = "fill")
#> $col
#> [1] "red"   "blue"  "green"
#> 
#> $lwd
#> [1] 1 2
#> 
#> $fill
#> [1] "fill"
```

<sup>Created on 2021-09-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edzer** [comment]
Thanks! Indeed, but subsetting it will recycle:
```r
> gp = grid::gpar(col = c("red", "blue", "green"), lwd = 1:2, fill = "fill")
> gp[2:3]
$col
[1] "blue"  "green"

$lwd
[1] 2 1

$fill
[1] "fill" "fill"
```

**Comment by yutannihilation** [comment]
Yes, but, in this case, `length(gp$fill) != length(x)`.

**Comment by edzer** [comment]
good catch; then the criterion should be `length(gp$fill) == 1 || length(gp$fill) == length(x)`, right? (and hope that nobody tries to plot 10 million points following a `POINT EMPTY`...)

**Comment by yutannihilation** [comment]
It looks good to me! Further, maybe the `if` statement can be simplified to just

``` r
if (any(is_e <- st_is_empty(x))) {
```

because `length(gp$fill) == 1 || length(gp$fill) == length(x)` should cover most of the cases, and even when `length(gp$fill)` doesn't match either, `gp` can be recycled to `length(x)` (I guess this is what will happen in `grid::*Grob()` anyway if we don't recycle it by ourselves).

> hope that nobody tries to plot 10 million points following a `POINT EMPTY`...

Yeah, agreed...

**Comment by yutannihilation** [comment]
Thank you for fixing!
