### ISSUE TITLE
st_write() error: Write error for writing to shapefile

### ISSUE THREAD

**Issue by erstearns** [r-spatial/sf#1792]
I have been unable to succesfully write an sf object to a shapefile using code I have been using for over a year since updating R to latest version (4.1.1) and am not sure what the issue is - I have updated all sf & related geo packages. A shapefile is written, however it is empty. The error message just indicates a 'Write error' with some warnings about the length of field names:

`st_write(obj = data_sf, dsn = paste0(data_dir, "/prepared_data/data_sf.shp"))`

Error message returned:

``Writing layer `data_sf' to data source 
  `/Users/.../prepared_data/data_sf.shp' using driver `ESRI Shapefile'
Writing 3220 features with 24 fields and geometry type Multi Polygon.
Unknown field name `cnty_hsptl_bds_t': updating a layer with improper field name(s)?``

``Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Write error``

``In addition: Warning messages:
1: In abbreviate_shapefile_names(obj) :
  Field names abbreviated for ESRI Shapefile driver
2: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Message 6: Normalized/laundered field name: 'cnty_hsptl_bds_t' to 'cnty_hsptl'
3: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Message 6: Normalized/laundered field name: 'cnty_hsptl_bds_n' to 'cnty_hsp_1'``

<details>
  <summary>Session info</summary>
  ─ Session info ─────────────────────────────────────────
 setting  value   
                    
 version  R version 4.1.1 (2021-08-10)

 os       macOS Big Sur 11.5.2        

 system   x86_64, darwin17.0      
    
 ui       RStudio                     

 language (EN)           
             
 collate  en_US.UTF-8       
          
 ctype    en_US.UTF-8         
        
 tz       America/Los_Angeles         

 date     2021-09-13                  

─ Packages ───────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.1.0)
 backports     1.2.1   2020-12-09 [1] CRAN (R 4.1.0)
 broom         0.7.9   2021-07-27 [1] CRAN (R 4.1.0)
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.1.0)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.1.0)
 cellranger    1.1.0   2016-07-27 [1] CRAN (R 4.1.0)
 class         7.3-19  2021-05-03 [1] CRAN (R 4.1.1)
 classInt      0.4-3   2020-04-07 [1] CRAN (R 4.1.0)
 cli           3.0.1   2021-07-17 [1] CRAN (R 4.1.0)
 colorspace    2.0-2   2021-06-24 [1] CRAN (R 4.1.0)
 crayon        1.4.1   2021-02-08 [1] CRAN (R 4.1.0)
 DBI           1.1.1   2021-01-15 [1] CRAN (R 4.1.0)
 dbplyr        2.1.1   2021-04-06 [1] CRAN (R 4.1.0)
 desc          1.3.0   2021-03-05 [1] CRAN (R 4.1.0)
 devtools    * 2.4.2   2021-06-07 [1] CRAN (R 4.1.0)
 digest        0.6.27  2020-10-24 [1] CRAN (R 4.1.0)
 dplyr       * 1.0.7   2021-06-18 [1] CRAN (R 4.1.0)
 e1071         1.7-8   2021-07-28 [1] CRAN (R 4.1.0)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)
 evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.0)
 fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.0)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
 forcats     * 0.5.1   2021-01-27 [1] CRAN (R 4.1.0)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.1.0)
 generics      0.1.0   2020-10-31 [1] CRAN (R 4.1.0)
 ggplot2     * 3.3.5   2021-06-25 [1] CRAN (R 4.1.0)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.1.0)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 4.1.0)
 haven         2.4.3   2021-08-04 [1] CRAN (R 4.1.0)
 hms           1.1.0   2021-05-17 [1] CRAN (R 4.1.0)
 htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.1)
 httr          1.4.2   2020-07-20 [1] CRAN (R 4.1.0)
 jsonlite      1.7.2   2020-12-09 [1] CRAN (R 4.1.0)
 KernSmooth    2.23-20 2021-05-03 [1] CRAN (R 4.1.1)
 knitr         1.33    2021-04-24 [1] CRAN (R 4.1.0)
 lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.1.0)
 lubridate     1.7.10  2021-02-26 [1] CRAN (R 4.1.0)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.1.0)
 modelr        0.1.8   2020-05-19 [1] CRAN (R 4.1.0)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 4.1.0)
 pacman        0.5.1   2019-03-11 [1] CRAN (R 4.1.0)
 pillar        1.6.2   2021-07-29 [1] CRAN (R 4.1.0)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.1.0)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
 pkgload       1.2.2   2021-09-11 [1] CRAN (R 4.1.1)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.1.0)
 processx      3.5.2   2021-04-30 [1] CRAN (R 4.1.0)
 proxy         0.4-26  2021-06-07 [1] CRAN (R 4.1.0)
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.1.0)
 purrr       * 0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.0)
 Rcpp          1.0.7   2021-07-07 [1] CRAN (R 4.1.0)
 readr       * 2.0.1   2021-08-10 [1] CRAN (R 4.1.0)
 readxl        1.3.1   2019-03-13 [1] CRAN (R 4.1.0)
 remotes       2.4.0   2021-06-02 [1] CRAN (R 4.1.0)
 reprex        2.0.1   2021-08-05 [1] CRAN (R 4.1.0)
 rlang         0.4.11  2021-04-30 [1] CRAN (R 4.1.0)
 rmarkdown     2.10    2021-08-06 [1] CRAN (R 4.1.0)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.1.0)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)
 rvest         1.0.1   2021-07-26 [1] CRAN (R 4.1.0)
 scales        1.1.1   2020-05-11 [1] CRAN (R 4.1.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.0)
 sf          * 1.0-2   2021-07-26 [1] CRAN (R 4.1.0)
 stringi       1.7.4   2021-08-25 [1] CRAN (R 4.1.1)
 stringr     * 1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
 testthat      3.0.4   2021-07-01 [1] CRAN (R 4.1.0)
 tibble      * 3.1.4   2021-08-25 [1] CRAN (R 4.1.1)
 tidyr       * 1.1.3   2021-03-03 [1] CRAN (R 4.1.0)
 tidyselect    1.1.1   2021-04-30 [1] CRAN (R 4.1.0)
 tidyverse   * 1.3.1   2021-04-15 [1] CRAN (R 4.1.0)
 tzdb          0.1.2   2021-07-20 [1] CRAN (R 4.1.0)
 units         0.7-2   2021-06-08 [1] CRAN (R 4.1.0)
 usethis     * 2.0.1   2021-02-10 [1] CRAN (R 4.1.0)
 utf8          1.2.2   2021-07-24 [1] CRAN (R 4.1.0)
 vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.0)
 withr         2.4.2   2021-04-18 [1] CRAN (R 4.1.0)
 xfun          0.25    2021-08-06 [1] CRAN (R 4.1.0)
 xml2          1.3.2   2020-04-23 [1] CRAN (R 4.1.0)
 yaml          2.2.1   2020-02-01 [1] CRAN (R 4.1.0)

</details>

Thank you in advance for help resolving this issue!

**Comment by edzer** [comment]
Shapefiles have an inbuilt limitation of field names having maximally 10 characters. See https://gdal.org/drivers/vector/shapefile.html for more details.

**Comment by erstearns** [comment]
@edzer  -- thank you for the quick reply! I am aware of that limitation, however in the past and according to that documentation, field names with 10+ characters are simply truncated, it has never caused a write error for me in the past.

**Comment by edzer** [comment]
Ah, you are right:
```r
library(sf)
# Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
st_sf(very_long_field_name=1, geom = st_sfc(st_point(0:1)))
# Simple feature collection with 1 feature and 1 field
# Geometry type: POINT
# Dimension:     XY
# Bounding box:  xmin: 0 ymin: 1 xmax: 0 ymax: 1
# CRS:           NA
#   very_long_field_name        geom
# 1                    1 POINT (0 1)
st_sf(very_long_field_name=1, geom = st_sfc(st_point(0:1))) |>
  st_write("x.shp")
# Writing layer `x' to data source `x.shp' using driver `ESRI Shapefile'
# Writing 1 features with 1 fields and geometry type Point.
# Warning message:
# In abbreviate_shapefile_names(obj) :
#   Field names abbreviated for ESRI Shapefile driver
read_sf("x.shp")
# Simple feature collection with 1 feature and 1 field
# Geometry type: POINT
# Dimension:     XY
# Bounding box:  xmin: 0 ymin: 1 xmax: 0 ymax: 1
# CRS:           NA
# # A tibble: 1 × 2
#   vry_l__ geometry
#     <dbl>  <POINT>
# 1       1    (0 1)
```
Could you provide a complete reprex?

**Comment by rsbivand** [comment]
Are the field names no longer unique after truncation?

Roger Bivand
Falsensvei 32
5063 Bergen

man. 13. sep. 2021, 18:35 skrev Edzer Pebesma ***@***.***>:

**Comment by erstearns** [comment]
@rsbivand -- that was exactly the issue. I renamed the offending field names and voila! A shapefile was successfully written. Thank you, @edzer & @rsbivand !
