### ISSUE TITLE
parallel, weird things happen

### ISSUE THREAD

**Issue by luigidolcetti** [r-spatial/sf#1795]
Hi,
something weird happens when I use an sf data frame in a cluster. Please consider the following:

#'
#' @export
extractPixelStatistics<-function(fn_polygons,
                                 fn_raster,
                                 fn_function,
                                 verbose=T,
                                 cl=NA,
                                 ...){

  prgrsbr<-verbose
  if (!any(is.na(cl))){
    parallel::clusterExport(cl=cl,
                            varlist = c('fn_raster',
                                        'fn_polygons',
                                        'fn_function',
                                        'prgrsbr'),
                            envir = environment())
  }

  if (!any(is.na(cl))){

    value_x<-parallel::parLapply(unique(fn_polygons$uid),function(x){

      sub_raster<-fn_raster[[x]]
      sub_condensedPolygon<-fn_polygons[fn_polygons$uid==x,]
      value<-exactextractr::exact_extract(x = sub_raster,
                                          y = sub_condensedPolygon,
                                          fun = fn_function,
                                          progress = prgrsbr,
                                          force_df = T)

      colnames(value)<-names(sub_raster)
      value<-dplyr::bind_cols(pIDs=sub_condensedPolygon[,'pIDs',drop=T],value)

    },cl = cl)

  } else {

    value_x<-lapply(unique(fn_polygons$uid),function(x){

      sub_raster<-fn_raster[[x]]
      sub_condensedPolygon<-fn_polygons[fn_polygons$uid==x,]
      value<-exactextractr::exact_extract(x = sub_raster,
                                          y = sub_condensedPolygon,
                                          fun = fn_function,
                                          progress = prgrsbr,
                                          force_df = T)

      colnames(value)<-names(sub_raster)
      value<-dplyr::bind_cols(pIDs=sub_condensedPolygon[,'pIDs',drop=T],value)

    })

  }

  value_x<-do.call(rbind.data.frame,value_x)
  return(value_x)

}

Essentialy, the non-parallelised version (cl=NA) works as expected, while when using a cluster produced with parallel::makecluster() I obtain the following error:

Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: attr(obj, "sf_column") does not point to a geometry column.
Did you rename it, without setting st_geometry(obj) <- "newname"? (I did not as far as I can understand...)

Now, if I retrieve from the loop fn_polygons the sf data frame appears normal and the methods (like show, plot) behaves as expected, if I pull out fn_polygons[fn_polygons$uid==x,] the sf data frame is corrupted (this happens only in the cluster) and it seems that the geometry column name changed... while this is actually not true (at least on the surface).

Any clue of what's happening...?

Thank you in advance for your help,
Luigi

**Comment by edzer** [comment]
Please properly format your code and the github issue. Maybe you forgot to load `sf` on the cluster nodes?

**Comment by luigidolcetti** [comment]
Brilliant! Thank you!
