### ISSUE TITLE
Saving photos to a kml/kmz using st_write()

### ISSUE THREAD

**Issue by aloboa** [r-spatial/sf#1800]
I currently use `st_write()` to save an sf object (a dataframe with lonlat coordinates converted to sf with `st_as_sf(mydf) `) to a kml,
then I interactively include the photos in GE using Properties/Add local image for each point and finally save as kmz.
I would like to do this automatically by just  including a field with the path and name of the photo for each
point in the dataframe, then` st_write(st_as_sf(mydf,...),...).`
Is this possible? If not, could this feature be considered as a new addition?

**Comment by edzer** [comment]
#1721 describes how you can write photos to binary fields in a GPKG, which you could try, but I'd be surprised if it would work for kml, as that would probably need some information that the binary field is a photo. So, if this can't be done with the KML GDAL driver, then it can't be done with sf. I am reluctant to add driver-specific code to sf, in particular if it would bypass GDAL.

**Comment by aloboa** [comment]
By comparing the kml that is directly written by st_write() at the moment to the one within the kmz resulting from GE after including the photos, it seems that the only difference are groups such as:
`<description><![CDATA[<img style="max-width:500px;" src="files/DSC_0007.JPG">]]></description>`
But I understand the reluctance to do anything beyond GDAL. 
On the other hand, this tool would be immensely  useful for field photography in disciplines such as geology, in which GE is the only de facto tediousness alternative to visualize the terrain.

**Comment by edzer** [comment]
You could write an R package that does this: take a KML file and a list of images + IDs and merge the two into a new KML file with the images inlined.

**Comment by rsbivand** [comment]
Can `ogr2ogr` convert a GPKG to KML/Z without losing images? If so one could add the images to an sf object, export to a temporary GPKG, and use `ogr2ogr` to complete. A reprex might elucidate ...

**Comment by edzer** [comment]
The GPKG doesn't know that the blob is an image.

**Comment by aloboa** [comment]
I've put a toy example with one single point for one single photo:
https://www.dropbox.com/s/t2saom38b7yiu5y/example.zip?dl=0
I reproduce the readme.txt file:

- examaple.csv: file with coordinates and picture names
- example_log.R: script to create example.kml
- example.kml: kml created by example_log.R from example.csv
- example.kmz: kmz of example.kml created with GE
- At this point, use GE to add DSC_0007.JPG to point 1a in example.kml (Properties/Add local image)
- examplewithphoto.kml: kml saved once photo has been added
- examplewithphoto.kmz: kmz saved with GE

Comparing the doc.kml within example.kmz to the doc.kml within examplewithphoto.kmz suggests that the relevant difference
is
```
			<description><![CDATA[<img style="max-width:500px;" src="files/DSC_0007.JPG">]]></description>
			<styleUrl>#default</styleUrl>


```
doc.kml within example.kmz:

```
		<Placemark>
			<name>1a</name>
			<ExtendedData>
				<SchemaData schemaUrl="#rod">
					<SimpleData name="Parada">1</SimpleData>
					<SimpleData name="Ruta">Pista de Rodalquilar a los Albaricoques por las Minas de Rodalquilar en las Lazaras</SimpleData>
					<SimpleData name="UTMX">585014</SimpleData>
					<SimpleData name="UTMY">4079052</SimpleData>
					<SimpleData name="MaterialsArribas_1">Naranja (11) – Domos riolíticos; Violeta (12) – Ignimbrita de las Lazaras</SimpleData>
					<SimpleData name="Foto">DSC_0007.JPG</SimpleData>
				</SchemaData>
			</ExtendedData>
			<Point>
				<coordinates>-2.04636775100265,36.8535612671517,0</coordinates>
			</Point>
		</Placemark>

```
doc.kml within examplewithphoto.kmz

```
		<Placemark>
			<name>1a</name>
			<description><![CDATA[<img style="max-width:500px;" src="files/DSC_0007.JPG">]]></description>
			<styleUrl>#default</styleUrl>
			<ExtendedData>
				<SchemaData schemaUrl="#rod">
					<SimpleData name="Parada">1</SimpleData>
					<SimpleData name="Ruta">Pista de Rodalquilar a los Albaricoques por las Minas de Rodalquilar en las Lazaras</SimpleData>
					<SimpleData name="UTMX">585014</SimpleData>
					<SimpleData name="UTMY">4079052</SimpleData>
					<SimpleData name="MaterialsArribas_1">Naranja (11) – Domos riolíticos; Violeta (12) – Ignimbrita de las Lazaras</SimpleData>
					<SimpleData name="Foto">DSC_0007.JPG</SimpleData>
				</SchemaData>
			</ExtendedData>
			<Point>
				<coordinates>-2.04636775100265,36.8535612671517,0</coordinates>
			</Point>
		</Placemark>

```

This is all I can do in the hope that someone with the necessary skills finds creating these kmz files including photos directly from a csv in R an interesting task.
