### ISSUE TITLE
`digits` argument of st_as_text produces different results depending on implementation used

### ISSUE THREAD

**Issue by MilesMcBain** [r-spatial/sf#1805]
Reprex:

``` r
point <- sf::st_point(c(1.123456, 2.123456))
Sys.setenv("LWGEOM_WKT"="false")
sf::st_as_text(point, digits = 6)
#> [1] "POINT (1.12346 2.12346)"
Sys.setenv("LWGEOM_WKT"="true")
sf::st_as_text(point, digits = 6)
#> Warning: package 'sf' was built under R version 4.1.1
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1
#> [1] "POINT(1.123456 2.123456)"
```

<sup>Created on 2021-09-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The `digits` arg of `format` refers to total digits. I think you probably want to use `formatC` here instead:

https://github.com/r-spatial/sf/blob/master/R/wkt.R#L20

The `digits` arg of `formatC` has the same meaning as in `{lwgeom}`.

**Comment by edzer** [comment]
using `formatC` there gives me
```r
point <- sf::st_point(c(1.123456, 2.123456))
Sys.setenv("LWGEOM_WKT"="false")
sf::st_as_text(point, digits = 6)
# [1] "POINT (1.12346 2.12346)"
```

**Comment by MilesMcBain** [comment]
Ah sorry, it seems you also need the `format` arg:

```r
> format(1.123456, digits = 6)
[1] "1.12346"
> formatC(1.123456, digits = 6)
[1] "1.12346"
> formatC(1.123456, format = "f", digits = 6)
[1] "1.123456"
```

**Comment by edzer** [comment]
Yes. Changing it in the place you suggests however causes lots of problems elsewhere, so please provide a well tested PR if this is important for you or others - this is of too low priority for me to spend time on.
