### ISSUE TITLE
Which attributes does st_intersection retain?

### ISSUE THREAD

**Issue by paluchs** [r-spatial/sf#1806]
When using st_intersection to create individual polygons from overlapping polygons, it is unclear which attributes of which "parent" are retained. (Maybe I missed something?)

I feel like there are two possible behaviors:
- Either the st_intersection returns multiple polygons where two polygons intersect, retaining the attributes of the original geometries.
- Or there is the possibility much like in a summarise when using group_by to define a summarising function (such as e.g. sum, min, max) to define the new attributes.

**Comment by edzer** [comment]
first:
```r
library(sf)
# Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
p1 = st_sf(a = 1, geom = st_sfc(st_point(c(0,0)))) |> st_buffer(1)
p2 = st_sf(b = 2, geom = st_sfc(st_point(c(0,1)))) |> st_buffer(1)
st_intersection(p1, p2)
# Simple feature collection with 1 feature and 2 fields
# Geometry type: POLYGON
# Dimension:     XY
# Bounding box:  xmin: -0.8660254 ymin: 0 xmax: 0.8660254 ymax: 1
# CRS:           NA
#   a b                           geom
# 1 1 2 POLYGON ((0.8386706 0.45536...
# Warning message:
# attribute variables are assumed to be spatially constant throughout all geometries 
```

**Comment by edzer** [comment]
> Or there is the possibility much like in a summarise when using group_by to define a summarising function (such as e.g. sum, min, max) to define the new attributes.

You can use `summarise`, or `aggregate`, to compute intersections but these will need to be unioned to get valid geometries for each of the group.
