### ISSUE TITLE
Bug Report (Maybe): Problem reading Shapefile via st_read

### ISSUE THREAD

**Issue by jingjunL** [r-spatial/sf#1808]
Hello sf developers:

I think this might be a bug in the SF `st_read` function but I am not sure. Basically, my colleague and I are co-working an R script on OneDrive. Most part of the code is written by me, and the script works fine on my laptop (which is a Windows 10 pc). My colleague is reviewing the code on MacBook, but she got the following mistake when running the below command:
`proximus_CellDivisionShape <- st_read("ProximusData/cell_locations_20200120_20200220.shp")`

The warning message she has is:
> BrusselsSSDivision <- st_read("BelgiumStatisticalSector/sh_statbel_statistical_sectors_20180101.shp") Error: Cannot open "/Users/evyrombaut/Vrije Universiteit Brussel/AV EV Lab (BUTO MOBI) - R - AV - SRP/JingjunOwnRPractice/BelgiumStatisticalSector/sh_statbel_statistical_sectors_20180101.shp"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.

However, when I try to run the same line of the code, I did it successfully by having the print out as:
```
`Reading layer `sh_statbel_statistical_sectors_20180101' from data source 
  `C:\Users\jingli\Vrije Universiteit Brussel\AV EV Lab (BUTO MOBI) - R - AV - SRP\JingjunOwnRPractice\BelgiumStatisticalSector\sh_statbel_statistical_sectors_20180101.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 19793 features and 29 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 21995.51 ymin: 21162.16 xmax: 295167.1 ymax: 244027.2
Projected CRS: Belge 1972 / Belgian Lambert 72`
```

This is super weird as **the line of code which she got stuck is not the first line that uses `st_read( )` in our script.** Before this we also tried to read one shapefile using the formula and it works quite well on her MacBook actually.

BTW, my colleague just installed a new version of R a week ago, and this problem was there either before or after her installation, so it is very likely that this is not a problem related to R version.

I am wondering if you know the potential reasons for this? And how should we tackle this? Thanks very much for your help in advance :)

**Comment by jingjunL** [comment]
And for your information, you can download the shapefile which encountered this problem on this link:
https://statbel.fgov.be/sites/default/files/files/opendata/Statistische%20sectoren/sh_statbel_statistical_sectors_20180101.shp.zip

**Comment by edzer** [comment]
No problems reading that file here. Might be some GDAL - OneDrive interaction? Can `ogrinfo` open the file?

**Comment by jingjunL** [comment]
> No problems reading that file here. Might be some GDAL - OneDrive interaction? Can `ogrinfo` open the file?

Thanks for your reply Edzer, my colleague will have a try. I am not an expert in GDAL, but if it's the issue of OneDrive interaction, this script should not work on my laptop either (if I am correct?), but it works well on myside (all shapefile can be read). But for my colleague, all shapefile except this one can also be read
