### ISSUE TITLE
CDN grid st_transform() problems with Windows and macOS

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#1815]
See the thread starting https://stat.ethz.ch/pipermail/r-sig-geo/2021-October/028796.html, originally: https://stackoverflow.com/questions/69507752/how-to-apply-a-grid-transformation-in-sf-with-proj7

Uploaded an R file

[cdn_211010_sf_rgdal.R.zip](https://github.com/r-spatial/sf/files/7324693/cdn_211010_sf_rgdal.R.zip)

```
# at the very beginning of the R session, define the user-writable
# directory
td <- tempfile()
dir.create(td)
Sys.setenv("PROJ_USER_WRITABLE_DIRECTORY"=td)   
library(rgdal)
rgdal_extSoftVersion()
# check the PROJ search paths and check that the user-writable directory
# is empty and that the CDN is not enabled
(pths <- get_proj_search_paths())
list.files(pths[1])
is_proj_CDN_enabled()
# define the objects and check that the search paths are still OK
library(sf)
get_proj_search_paths()
pt_27572 <- data.frame(X=55824.4970,Y=2394454.2120)
pt_2154 <- data.frame(X=107242.8310,Y=6832277.1820)
ptSf_27572 <- st_as_sf(pt_27572, coords = c("X", "Y"), crs=27572)
ptSf_2154 <- st_as_sf(pt_2154, coords = c("X", "Y"), crs=2154)
# enable the CDN and that the user-writable directory is still empty
enable_proj_CDN()
is_proj_CDN_enabled()
list.files(pths[1])
# list candidate coordinate operations
(o <- list_coordOps("EPSG:27572", "EPSG:2154"))
# transform using the first returned coordinate operation pipeline
ptSf_2154_grid <- st_as_sf(spTransform(as(ptSf_27572, "Spatial"),
  CRS("EPSG:2154"), coordOp=o[1, "definition"]))
# print the coordinate operation used
get_last_coordOp()
# check that the user-writable directory is populated
list.files(pths[1])
# check distance to defined point in target crs
st_distance(ptSf_2154_grid, ptSf_2154)
```
three Rout files from running this script on Linux, win10 and macOS

[cdn_211010_sf_rgdal_Rout.zip](https://github.com/r-spatial/sf/files/7324701/cdn_211010_sf_rgdal_Rout.zip)

and a CSV file from running variants. It turned out that setting the pipeline was essential also on Linux, for unknown reasons, but that setting the pipeline didn't work for sf because st_transform was only looking at the bundled PROJ metadata directory.

[cdn_211010_table.csv](https://github.com/r-spatial/sf/files/7324709/cdn_211010_table.csv)

**Comment by rsbivand** [comment]
Extracted example:

```
library(sf)
(sp <- sf_proj_search_paths())
sf_proj_network()
pt_27572 <- data.frame(X=55824.4970,Y=2394454.2120)
pt_2154 <- data.frame(X=107242.8310,Y=6832277.1820)
ptSf_27572 <- st_as_sf(pt_27572, coords = c("X", "Y"), crs = 27572)
ptSf_2154 <- st_as_sf(pt_2154, coords = c("X", "Y"), crs = 2154)
sf_proj_network(TRUE)
(p = sf_proj_pipelines("EPSG:27572", "EPSG:2154"))
ptSf_2154_grid <- st_transform(ptSf_27572, crs=2154)
st_distance(ptSf_2154_grid, ptSf_2154) 
(ptSf_pi = st_transform(ptSf_27572, "EPSG:2154", pipeline = p[1,]$definition))
st_distance(ptSf_pi, ptSf_2154)
```
Yes, this works on Linuxen, but still has the problem of the least accurate pipeline being chosen in `st_transform()` when no pipeline is given. This problem (for these crs) is the same for `rgdal::spTransform()`. Without setting a temporary user-writable directory, when CDN is OFF, any grids in the default user-writable directory should be used, but do not seem to be accessed:

```
library(RSQLite)
db <- dbConnect(SQLite(), dbname=file.path(sp[1], "cache.db"))
dbListTables(db)
dbReadTable(db, "chunks")
dbDisconnect(db)
```

Maybe `fr_ign_ntf_r93.tif`  is used rather than `fr_ign_gr3df97a.tif` because it is smaller, less download?

I've also established that the 74m distance is omitting any datum transform, but:

```
ptSf_2154_via_CRS84 <- st_transform(st_transform(ptSf_27572, crs="OGC:CRS84"), crs=2154)
st_distance(ptSf_2154_via_CRS84, ptSf_2154)
# Units: [m]
#          [,1]
# [1,] 3.777444
```
where 27572 -> CRS84 is a 3-coefficient Helmert transformation. So `st_transform()` via GDAL seems to fall back to using the deprecated WGS84 hub when grids are not working on win10 and macOS.

**Comment by florisvdh** [comment]
In Linux I get the same results as you (sf 1.0.3, linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1) with just one grid downloaded and available (and yes, auto-download worked!):

```r
> dbReadTable(db, "chunks")
  id                                      url offset data_id data_size
1  1 https://cdn.proj.org/fr_ign_gr3df97a.tif      0       1     16384
```

It might be the grid naming mismatch that causes the ballpark transformation to be used - indeed it is (running below code after running your script):

```r
> (ptSf_pi = st_transform(ptSf_27572, "EPSG:2154", pipeline = p[3,]$definition))
Simple feature collection with 1 feature and 0 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 107316.6 ymin: 6832280 xmax: 107316.6 ymax: 6832280
Projected CRS: RGF93 / Lambert-93
                  geometry
1 POINT (107316.6 6832280)
> st_distance(ptSf_pi, ptSf_2154)
Units: [m]
        [,1]
[1,] 73.7975
> ptSf_pi
Simple feature collection with 1 feature and 0 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 107316.6 ymin: 6832280 xmax: 107316.6 ymax: 6832280
Projected CRS: RGF93 / Lambert-93
                  geometry
1 POINT (107316.6 6832280)
```

This may be a bug in PROJ 7.2.1, since with its `cs2cs` tool one gets the same ballpark transformation:

```bash
$ echo 55824.4970 2394454.2120 | cs2cs EPSG:27572 EPSG:2154
107316.59	6832279.59 0.00
```

Moreover PROJ does not complain about a missing grid either, for the first pipeline, so it should have used the first pipeline it seems:

```bash
$ projinfo -s EPSG:27572 -t EPSG:2154 --summary
Candidate operations found: 3
unknown id, Inverse of Lambert zone II + NTF (Paris) to NTF (1) + Inverse of RGF93 to NTF (2) + Lambert-93, 1 m, France - onshore - mainland and Corsica.
unknown id, Inverse of Lambert zone II + NTF (Paris) to NTF (1) + NTF to RGF93 (1) + Lambert-93, 1 m, France - onshore - mainland and Corsica., at least one grid missing
unknown id, Inverse of Lambert zone II + Inverse of Transformation from RGF93 to NTF (Paris) altered to use prime meridian of RGF93 + Ballpark geographic offset from NTF (Paris) altered to use prime meridian of RGF93 to RGF93 + Lambert-93, unknown accuracy, World, has ballpark transformation
```

While writing a [tutorial](https://inbo.github.io/tutorials/tutorials/spatial_transform_crs_2/), it was observed that default `st_transform()` will trigger location dependent choice of pipeline, i.e. choosing a ballpark transformation for coordinates that fall outside the CRS's area of usage (geographic bounding box), and choosing the more accurate pipeline only for coordinates that fall within. (This makes sense but I think it is not documented to that detail in https://keen-swartz-3146c4.netlify.app/sf.html#pipelines.) However I checked the coordinates of the currently investigated point and such thing doesn't seem to be the case here - so excluding this as a possible cause.

Ideally this is re-tested with latest PROJ and if it's still there, seems like a bug to be solved at PROJ?

**Comment by rsbivand** [comment]
No, I have:

```
> sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
 "3.10.0beta3"        "3.3.2"        "8.1.1"         "true"         "true" 
          PROJ 
       "8.1.1" 
```
And pipeline listing is with strict containment FALSE, so various odd things are going on.

**Comment by rouault** [comment]
> No `cache.db` is created in the default location, where is it?

https://proj.org/usage/network.html?highlight=network#caching + https://proj.org/resource_files.html#user-writable-directory might help

> Is this: https://gdal.org/api/ogr_srs_api.html#_CPPv420OSRGetPROJAuxDbPathsv relevant?

probably not. This is about storing extra CRS and coordinate operations in auxiliary databases. Not about grid caching

**Comment by rouault** [comment]
> However, **sf** uses OSR not PROJ for transformation (apart from direct projinfo-style pipeline lookup)

PROJ networking must be enabled through the PROJ_NETWORK=ON environment variable (and not GDAL config option) to be enabled in OSR usage.

**Comment by rsbivand** [comment]
**sf** uses PROJ to enable the network: 
https://github.com/r-spatial/sf/blob/ea94efe83cf2ef575bf6e9d59e04a07301d06b28/src/proj.cpp#L193-L207
The equivalent **rgdal** code is in https://r-forge.r-project.org/scm/viewvc.php/pkg/src/proj_network7.cpp?view=markup&root=rgdal, and returns the output of `proj_context_set_enable_network(PJ_DEFAULT_CTX, TRUE);`.

**Comment by rsbivand** [comment]
A simple check function for the `+pm-grid` https://github.com/OSGeo/PROJ/pull/2884 bug in `PROJ`for **sf**:
```
sf_check_pm_grid_bug = function(x, to_crs) {
    p = sf_proj_pipelines(st_crs(x)$wkt, to_crs)
    res = rep(FALSE, nrow(p))
    pv = package_version(sf:::CPL_proj_version())
    if (pv >= "7.2.1" && pv <= "8.1.1") {
        res = grepl("\\+pm=", p$definition) & !grepl("greenwich", p$definition) & grepl("grid", p$definition)
    }
    res
}
```
In the context of the example at https://github.com/r-spatial/sf/issues/1815#issuecomment-940776012:

```
p = sf_proj_pipelines("EPSG:27572", "EPSG:2154")
o = sf_check_pm_grid_bug(ptSf_27572, "EPSG:2154")
p$accuracy[!o]
```
shows the residual accuracy from found pipelines, suggesting use of a manual hub avoiding the bug.

For **rgdal**:
```
rgdal_check_pm_grid_bug <- function(x, to_crs) {
    p <- list_coordOps(wkt(x), to_crs)
    res <- rep(FALSE, nrow(p))
    pv <- attr(getPROJ4VersionInfo(), "short")
    if (pv >= 721 && pv <= 811) {
        res <- grepl("\\+pm=", p$definition) & !grepl("greenwich", p$definition) & grepl("grid", p$definition)
    }
    res
}
```

**Comment by edzer** [comment]
> So the current MXE PROJ build is missing something as suspected.

PROJ, or libcurl?

As of the `sf` issue, I guess that `sf_proj_network(TRUE)` should then always call `Sys.setenv("PROJ_NETWORK"="ON")` to inform GDAL, right?
