### ISSUE TITLE
Shiny student project?

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#1820]
This just appeared on the PROJ list: https://github.com/jjimenezshaw/crs-explorer; maybe a student contribution to **sf** as a shiny app? **sf** ships with `proj.db`, so all the information is there, and **mapview** is already suggested @tim-salabim .

**Comment by rsbivand** [comment]
Something similar is in **crsuggest** @walkerke https://github.com/walkerke/crsuggest.

**Comment by sebdalgarno** [comment]
sorry for the delay. Here's what I propose based on info above:  

- a very lightweight Shiny app (using Shiny, sf and mapview libraries) that allows the user to retrieve crs from coordinates by clicking on an interactive map
- this uses the proj.db file in sf
- the app is called from a single function (e.g. `crs_explore()`) 
- Shiny is added to DESCRIPTION suggests. 
- The crs_explore() function checks if Shiny is installed already and if not, will prompt the user to install prior to launching the app

optionally, the `crs_explorer()` could include argument(s) that are passed to the Shiny app, e.g. coordinates or sf object to preload onto the map.

I will also look closely at `crsuggest` for inspiration on how to display/suggest potential crs options to the user

I can get started on a Shiny app in a separate personal repository for your initial feedback and comments. 
Let me know how that sounds.

**Comment by rsbivand** [comment]
Yes, using the `proj.db` shipping with **sf** for CRAN binary installs, or the system `proj.db` for other systems makes more sense than **crsuggest**, which ships a copy of the EPSG database as an MDB (Access) file. `proj.db` is an SQLite DB, so can also be accessed by **RSQLite**.
