### ISSUE TITLE
Is there a way to delete a layer using sf? 

### ISSUE THREAD

**Issue by damianooldoni** [r-spatial/sf#1828]
This is a **question** popping up during a coding club organised within our organisation. While we were learning how to write layers in a geopacakge, somebody asked the interesting question: _"is there a way to delete a layer?"_ 

There are no issues in this repo about this. I tried to make a search on internet and I found this: https://stackoverflow.com/questions/59722900/delete-layer-from-geopackage

However, this looks more like a workaround, specific to geopackages (`gpkg`). Are there plans to write a generic function like `st_delete_layer()` or `st_delete()`?

Thanks in advance.

**Comment by edzer** [comment]
merged in master.
