### ISSUE TITLE
GDAL 3.4.0rc1 has epoch support

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#1830]
See: https://github.com/rouault/gdal/blob/coordinate_epoch_v2/gdal/doc/source/user/coordinate_epoch.rst and https://gdal.org/development/rfc/rfc81_coordinate_epoch.html for details. I'm inclined to let **rgdal** stay without support, but **sf** will need support and tests, where tests for Australia may be the place to go first.

**Comment by edzer** [comment]
some support in `sf::sf_project()`
