### ISSUE TITLE
Support for extracting a component CRS from a compound CRS

### ISSUE THREAD

**Issue by mbedward** [r-spatial/sf#1831]
I am working with LiDAR point cloud data that uses a compound CRS (projected horizontal CRS plus vertical CRS) and need a way to extract just the horizontal component. The only way that I could work out so far has been to write a function that parses the WKT for a compound CRS. It is described [in this StackOverflow question](https://stackoverflow.com/a/69763185/40246) along with an example of a compound CRS that I am working with. The function seems to work but it's clunky and will probably fail for some instances. 

I gather that the PROJ library includes functions to extract components from compound CRSs. Would it be possible to expose these via the `sf` package?

**Comment by edzer** [comment]
Not sure this belongs to `sf`, or a more dedicated package. What you could try is avoid parsing WKT by using the PROJJSON represenation, e.g. (bulding on the SO example) by
```r
x = st_as_text(compound_crs, projjson=TRUE)
jsonlite::fromJSON(x)
```

**Comment by mbedward** [comment]
Thanks @edzer. Using JSON makes the function a lot simpler but I'm stuck on the last step: creating a `crs` object from the parsed data for the horizontal component (bummer comment in the function below). I suspect the component needs to return to a JSON representation first (?) Any hints would be much appreciated!

```
get_horizontal_crs2 <- function(x) {
  xcrs <- sf::st_crs(x)
  if (is.na(xcrs)) stop("No CRS defined")
  
  x <- sf::st_as_text(xcrs, projjson = TRUE)
  x <- jsonlite::fromJSON(x)
  
  if ("type" %in% names(x)) {
    if (tolower(x$type) == "compoundcrs") {
      # Extract the horizontal component. We pattern match on 'vertical'
      # then get the other component to allow for projected or geographic
      # coordinates.
      is_vert <- grepl("vertical", x$components$type, ignore.case=TRUE)
      
      ### Bummer - this returns NA ###
      horiz_comp <- x$components[!is_vert, ]
      st_crs( horiz_comp )

    } else {
      # Not a compound CRS so just return the input
      xcrs
    }
    
  } else {
    stop("Expected element `type` in JSON representation of CRS")
  }
}

```

**Comment by edzer** [comment]
Well, currently `sf` doesn't do this: it considers CRS in their WKT representation but doesn't help you take that apart and or reshuffle it. Maybe that would be something for a dedicated package.
