### ISSUE TITLE
'sf' and 's2' have 'non-zero exit status'

### ISSUE THREAD

**Issue by Namita-Joshi** [r-spatial/sf#1832]
Hello! Hope you are well.

I am having an issue with installing the SF and s2 packages onto R studio. I am running it on an Ubuntu pc. I am not sure whether this is the correct forum to get help from and I apologise if it's not. This is the error message I get when installing the two packages. I would really appreciate any advice.

> install.packages('sf')
Installing package into ‘/home/namita/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
also installing the dependency ‘s2’

trying URL 'https://cloud.r-project.org/src/contrib/s2_1.0.7.tar.gz'
Content type 'application/x-gzip' length 2235408 bytes (2.1 MB)
==================================================
downloaded 2.1 MB

trying URL 'https://cloud.r-project.org/src/contrib/sf_1.0-3.tar.gz'
Content type 'application/x-gzip' length 3524145 bytes (3.4 MB)
==================================================
downloaded 3.4 MB

ERROR: failed to lock directory ‘/home/namita/R/x86_64-pc-linux-gnu-library/4.0’ for modifying
Try removing ‘/home/namita/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-s2’
Warning in install.packages :
  installation of package ‘s2’ had non-zero exit status
ERROR: dependency ‘s2’ is not available for package ‘sf’
* removing ‘/home/namita/R/x86_64-pc-linux-gnu-library/4.0/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpjrKGc0/downloaded_packages’

> install.packages('s2')
Installing package into ‘/home/namita/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/s2_1.0.7.tar.gz'
Content type 'application/x-gzip' length 2235408 bytes (2.1 MB)
==================================================
downloaded 2.1 MB

ERROR: failed to lock directory ‘/home/namita/R/x86_64-pc-linux-gnu-library/4.0’ for modifying
Try removing ‘/home/namita/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-s2’
Warning in install.packages :
  installation of package ‘s2’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpjrKGc0/downloaded_packages’

Thank you so much!

**Comment by Namita-Joshi** [comment]
I also tried installing it using the tar.gz after downloading the file, but still get the same error

**Comment by rsbivand** [comment]
The error message is very clear:

> ERROR: failed to lock directory ‘/home/namita/R/x86_64-pc-linux-gnu-library/4.0’ for modifying
Try removing ‘/home/namita/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-s2’

Did you do that? Then install **s2** first, and only if that succeeds, proceed to **sf**. Please also read carefully: https://github.com/r-spatial/sf/#linux
