### ISSUE TITLE
sf_intersection - LinearRing with 3 points

### ISSUE THREAD

**Issue by thejibin** [r-spatial/sf#1841]
I used a POLYGON sf object of to intersect POINT sf object using st_intersection (data is available in zip folder to reproduce the error: https://drive.google.com/file/d/1rUU-OT9TMsN2ypKtT3JNQ38g9TQQBL6E/view?usp=sharing) and it gave me an error as former contained LinearRing with 3 points (it must be either 0 or >=4 to form a polygon). I tried to do an intersection with ArcGIS Pro to verify if something was wrong and there was no problem. Further, when I tried to look further into the geometry of POLYGON sf object, it was found that 30 out of 332 LINESTRING had 3 points instead of 0 or >=4. 
```r
library(sf)
## Read the POLYGON and POINT files
huc2_04_sf<-st_read("./huc2_04_sf.shp")
few_points_sf<-st_read("./few_points_selected.shp")

## Intersection 
points_in_huc_sf<-st_intersection(few_points_sf,huc2_04_sf)

## Find the unclosed LINESTRING in polygon causing issue
counter=0
for(ii in 1:332){
  coords<-data.frame(huc2_04_sf$geometry[[1]][i])
  if(as.numeric(nrow(coords))<=3){
    cat(sprintf("LINESTRING number-\"%1.0f\" points in LINESTRING -\"%1.0f\"\n", ii, as.numeric(nrow(coords))))
    print(huc2_04_sf$geometry[[1]][i])
    counter=counter+1
  }
}
cat(counter)
```
How to make the intersect work in this case? Is there a way to remove LINESTRING with 3 points or override this issue (as in ArcGIS Pro)?

**Comment by edzer** [comment]
ArcGIS Pro is not the measure of all things. Try
```r
points_in_huc_sf<-st_intersection(few_points_sf,st_make_valid(huc2_04_sf))
```

**Comment by thejibin** [comment]
I am completely new to R. May be I am doing something wrong. 

Already tried st_make_valid before posting the issue here. But, it did not work earlier and now. Is it due version of sf package? I was using sf - 0.9.8. I tried to update it in R and it did not update to 1.0-4 (as mentioned in https://r-spatial.github.io/sf/).

**Comment by edzer** [comment]
Does it now work? (There might be a change in the underlying GEOS versions related to this.)

**Comment by thejibin** [comment]
I had R-3.6.0 installed in my machine. I removed sf and installed it again, but I could get v0.9.8 (which is did not match the version in https://r-spatial.github.io/sf/). This did not help me to make st_make_valid work. So I updated R from 3.6.0 to 4.1.2. It allowed me to install sf-v1.0.3 and st_make_valid worked well. Thanks!
