### ISSUE TITLE
Implement expand operation (st_expand())

### ISSUE THREAD

**Issue by jolars** [r-spatial/sf#1842]
It would be great to have an implementation of `st_expand()` in line with the definition at <https://postgis.net/docs/ST_Expand.html>.

**Comment by edzer** [comment]
package stars has an unexported function `stars:::bb_shrink` that shrinks a bounding box with a factor; giving it a negative factor will expand it. Something like this could be used as a starting point.

**Comment by wiesehahn** [comment]
it's not implemented in sf, is it?

**Comment by edzer** [comment]
No.
