### ISSUE TITLE
geometry column vs. geom column with st_read()

### ISSUE THREAD

**Issue by wiesehahn** [r-spatial/sf#1847]
st_read() seems to name the geometry column differently based on the file type. 
It is `geom` for geopackage and `geometry` for shapefile. 

This is weird and problematic when merging data. 

```
nc_shp = st_read(system.file("shape/nc.shp", package="sf"))
nc_gpkg = st_read(system.file("gpkg/nc.gpkg", package = "sf"))
```

**Comment by edzer** [comment]
> st_read() seems to name the geometry column differently based on the file type.

Not exactly, it fetches the name through [GDAL](https://gdal.org/doxygen/classOGRGeomFieldDefn.html#afee61d406460dd46eeaa48a77f477991) if there is one, and sets it to "geometry" if there is not one (like for shapefiles). Databases like PostGIS might have different names, I think for GPKG "geom" is the normal (maybe fixed) name, but there is no reason geometry columns should have a certain name. If they would, we couldn't deal with multiple geometry columns (which we can).
