### ISSUE TITLE
sf 1.0.4 looks for libgeos-3.8.0, libproj15 and libgdal26.

### ISSUE THREAD

**Issue by kuang-da** [r-spatial/sf#1851]
Hi, I noticed that the latest `sf` (1.0.4) looks for `libgeos-3.8.0`, `libproj15`, and `libgdal26`. Since those are relatively old packages, it caues denpendency issue for other R packages (such as sp, rgeos, and GADMTools). I wonder whether there is any way to bypass this?

I created a [docker environment](https://github.com/kuang-da/sf-dependency-issue/tree/main) as the minimal example to reproduce the error I had.

Thank you very much!

**Comment by rsbivand** [comment]
Please state in plain text what your context is: OS version, R version and how you installed PROJ, GEOS and GDAL. All of these are your chooice, and most likely your container (containers are often just as confusing without plain text specs) is very specific to your case. Much more basic information is required. And of course CRAN tests and CI tests recorded on the README page for this repo show no such problems in general.

**Comment by kuang-da** [comment]
Thank you for the quick reply and sure I would love to fill in more information. The readme file of `sf` looks good so probably I will be able to get this run by tuning my Dockerfile.

My [Dockerfile](https://github.com/kuang-da/sf-dependency-issue/blob/main/dockerfile) is basically `rocker/verse` with the ubuntu installation instructions in the readme of `sf`.

- OS Version: Ubuntu 20.04.3 LTS x86_6
- R Version: 4.1.2
- How I installed PROJ, GEOS, and GDAL:

```
RUN apt-get update
RUN apt-get -y install libudunits2-dev
RUN apt -y install software-properties-common dirmngr apt-transport-https lsb-release ca-certificates
RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable
RUN apt-get update
RUN apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
```

Any suggestion would be highly appreciated.

**Comment by rsbivand** [comment]
You haven't reported the actual versions of GDAL or PROJ. I can see GEOS 3.9.1, PROJ 7.2.1, GDAL 3.3.2 on https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable. As mentioned, I do  not use Ubuntu or Debian, so have no idea how their packaging and distribution policies are supposed to work. You also didn't mention what the dependency issues for other packages were - of course updating external software that  several R packages depend on requires manual  reinstallation of  all those packages.

**Comment by edzer** [comment]
See https://github.com/r-spatial/sf#ubuntu for the general recommendation how to get recent version of system requirements.

**Comment by kuang-da** [comment]
Hi, thank you for the discussion. I think the main issue I had is that I was trying to install GEOS, PROJ, GDAL from `ubuntugis-unstable PPA`  because in the readme it says as follows.

> However, to get more up-to-date versions of dependencies such as GDAL, we recommend adding the ubuntugis-unstable PPA 

But it turns out `sf` is not compatible with GEOS, PROJ, GDAL in ubuntugis-unstable PPA yet.

Tracing down @edzer's example in [the other thread](https://github.com/r-spatial/spatialreg/issues/22#issuecomment-966435301), I found the [installation script](https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_geospatial.sh) for `rocker/geospatial`, and that is a very good example. Thank you very much.

------

The take-away is for Ubuntu 20.04, please install GEOS, PROJ, GDAL by 

```
apt-get -y update && apt-get install -y  libudunits2-dev libgdal-dev libgeos-dev libproj-dev
```

DO NOT install from `ubuntugis-unstable PPA`.

**Comment by edzer** [comment]
Please provide a dockerfile that demonstrates your claim that

>  sf is not compatible with GEOS, PROJ, GDAL in ubuntugis-unstable PPA yet.

**Comment by kuang-da** [comment]
Sure I would love to! The Dockerfile is as follows

```
FROM rocker/verse:4.1.2

RUN apt-get update
RUN apt -y install software-properties-common dirmngr apt-transport-https lsb-release ca-certificates
RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable
RUN apt-get update
RUN apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
RUN R -e "install.packages('sf')"
```

Then I used the following docker-compose.yml

```
version: "3.9"
services: 
  gadm:
    build: .
    image: gadm
    ports: 
      - "8787:8787"
    environment: 
      - ROOT=TRUE
      - PASSWORD=gadm
      - DISABLE_AUTH=true
    volumes: 
      - .:/home/rstudio
```

Then in the console, I encountered

```
> library(sf)
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/sf/libs/sf.so':
  libproj.so.15: cannot open shared object file: No such file or directory
```

If I try to find `libproj` in the filesystem, I got

```
rstudio@420e77a7d84e:~$ sudo find / -name "libproj*"
/usr/lib/x86_64-linux-gnu/libproj.so.19
/usr/lib/x86_64-linux-gnu/libproj.so.19.2.1
/usr/lib/x86_64-linux-gnu/libproj.la
/usr/lib/x86_64-linux-gnu/libproj.a
/usr/lib/x86_64-linux-gnu/libproj.so
/usr/share/doc/libproj19
/usr/share/doc/libproj-dev
/var/lib/dpkg/info/libproj19:amd64.list
/var/lib/dpkg/info/libproj19:amd64.symbols
/var/lib/dpkg/info/libproj-dev:amd64.md5sums
/var/lib/dpkg/info/libproj-dev:amd64.list
/var/lib/dpkg/info/libproj19:amd64.md5sums
/var/lib/dpkg/info/libproj19:amd64.triggers
/var/lib/dpkg/info/libproj19:amd64.shlibs
```

**Comment by edzer** [comment]
If I understand this docker image maze correctly, you are building images on Debian. The instructions for using the PPA are listed for Ubuntu.

**Comment by kuang-da** [comment]
hmm... I am pretty sure this is a Ubuntu image
<img width="448" alt="image" src="https://user-images.githubusercontent.com/18092300/142917299-a87f41da-5828-4a45-8eb3-4d5d39b40c10.png">

**Comment by kuang-da** [comment]
I wonder which part of the Dockerfile looks confusing and suboptimal? I thought I basically follow the critical steps in the [Dockerfile](https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/geospatial_4.1.2.Dockerfile) of geospatial. Thank you!

**Comment by edzer** [comment]
In your docker image, `sf` and dependencies get installed as _binary_ package from rstudio's binary linux package management system; this is a demonstration that this is (obviously) not robust against variations in system requirement libraries, such as proj/gdal/geos/udunits. To robustly provide binary packages, they should have used static linking just like CRAN does for windows and macos binary packages.

If you replace the last line of your dockerfile with
```r
RUN R -e "install.packages('sf', type = 'source', repos = 'https://cran.r-project.org/')"
```
it will install `sf` and its dependencies from source; then you'll get
```r
> library(sf)
Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1
```

**Comment by kuang-da** [comment]
I confirm it works like a charm followed by your suggestions. Thank you very much.

---

> `sf` and dependencies get installed as binary package from rstudio's binary linux package management system

I am not familiar with this topic so it is in fact not obvious to me. But thanks for your explanation. Now I have a better understanding of dependency management. 

Appreciate your and @rsbivand's time.

**Comment by rsbivand** [comment]
Is this another case of this docker image being affected by dragging in RStudio where it is not needed? The trick last time was to tell it to run bash: `docker run -e PASSWORD=xxyy -p 8787:8787 --rm -ti rocker/geospatial /bin/bash`.

**Comment by edzer** [comment]
@rsbivand that is what I did; the problem is that this image ("rocker/verse:x.y.z") sets linux package installation to binary, and repository to `https://packagemanager.rstudio.com/all/__linux__/focal/latest` or so.

@kuang-da maybe you want to come back to your earlier statement that

> sf is not compatible with GEOS, PROJ, GDAL in ubuntugis-unstable PPA yet.

**Comment by kuang-da** [comment]
Sure. I did take that back and replaced it with a piece of notes based on our discussion. Maybe it would help others as well.
