### ISSUE TITLE
Preserve class structure

### ISSUE THREAD

**Issue by famuvie** [r-spatial/sf#1852]
Dear all,
I've noticed that `sf` methods systematically replace `sf` at the top of the class list at each operation.
I'm not sure whether this is intended or not, but it breaks workflows that seem natural to me.
Specifically, I am developing a package which implements a class built on top of `sf` objects. But any manipulation breaks the class structure, re-placing `sf` at the top.
Here is a MRE:

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1

obj <- st_sf(a = 3, geometry = st_sfc(st_point(1:2)))
(class(obj) <- c("my-class", class(obj)))
#> [1] "my-class"   "sf"         "data.frame"

obj$a <- 4
class(obj)
#> [1] "sf"         "my-class"   "data.frame"
```

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I don't think this behaviour is desirable. I should be able to benefit from the methods for the more general classes in the hierarchy without having to reset my class each time, right?

Best wishes.

**Comment by edzer** [comment]
Good point! This fix addresses it for this particular case (`$<-` calling `[[<-.sf`) but there are MANY more instances where this happens!

**Comment by famuvie** [comment]
Thanks! I was afraid I was missing something obvious.
Yes, I've reported the simplest case I could think of. But it happens with all _tidyverse_ verbs.
ƒacu.-

**Comment by edzer** [comment]
(@henningte: relevant for `sftime`!)

@famuvie I'm trying to dig up why we did it this way, and didn't simply rely on a bare `NextMethod()` call. I believe that the answer was that `NextMethod()` does not guarantee to preserve any attributes. That means, even if `sf` methods would preserve the subclass it was called with (as in this "fix"), attributes that you added to the object to make it distinct from an `sf` object will not be preserved. Simply copying them wouldn't work, as some attributes may need to be subsetted too, for instance.  See here: https://stat.ethz.ch/pipermail/r-devel/2016-June/072819.html the comment from an R core member.

For instance, doing this for `select` for an `c("sftime", "sf", "data.frame")` object (an `sf` object which has an attribute pointing to the time column) will return an invalid object if the time column is not selected; `sf` is helpless here.

This would mean you'd have to write the wrappers yourself. Please prove me wrong, it would be great if this could be solved in `sf`!

**Comment by tim-salabim** [comment]
Just had a quick try with this new behaviour for mapview. Unless I am doing something wrong in method definition in mapview, I think this change could be quite problematic...

``` r
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1

obj <- st_sf(a = 3, geometry = st_sfc(st_point(1:2)))
(class(obj) <- c("my-class", class(obj)))
#> [1] "my-class"   "sf"         "data.frame"

obj$a <- 4
class(obj)
#> [1] "my-class"   "sf"         "data.frame"

mapview::mapview(obj)
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'mapView' for signature '"my-class"'
```

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edzer** [comment]
That is S4 vs. S3 inheritance difference, and solved with `setOldClass("my-class", "sf"))`, which @famuvie 's package should do.

**Comment by henningte** [comment]
Isn't this what the vctrs package tries to solve - allowing to apply methods for a specific class on instances of a subclass to this class, so that the class and other attributes get restored? So a similar function to `vctrs_restore()` may be a solution? See also: https://adv-r.hadley.nz/s3.html#s3-subclassing

**Comment by tim-salabim** [comment]
Thanks for the explanation. @Athanasiamo this is also relevant for `ggseg` I assume

**Comment by edzer** [comment]
IIRC, the problem of using `vctrs` for `sf` objects is that `sf` breaks the rule that `length(x["a"]) == length("a")` ("sticky geometry").

**Comment by edzer** [comment]
The way forward (without breaking a lot of existing code) might be to introduce an alternative to `sf` classes that does not have sticky geometry, and that could have a `vctrs` implementation. But what would the advantage of such a class be over `data.frame` or `tibble` with a geometry column? Geometry list columns already have a `vctrs` implementation (see file `tidyverse-vctrs.R`).

**Comment by famuvie** [comment]
>  ... This would mean you'd have to write the wrappers yourself. Please prove me wrong, it would be great if this could be solved in `sf`!

Ok. I understand the issue. I don't see any way out, other than handling the classes within my package.

By the way, I'm using S3 classes as well, so, I don't need to `setOldClass()` if I understand correctly.

Thanks for your insights.
ƒacu.-

**Comment by edzer** [comment]
> By the way, I'm using S3 classes as well, so, I don't need to setOldClass() if I understand correctly.

you don't have to, but there is no cost to it, and the benefit is that things might work where S4 inheritence is used, like `mapview`.
