### ISSUE TITLE
ERROR with st_cast.POINTS() and st_cast.GEOMETRY()

### ISSUE THREAD

**Issue by fipoucat** [r-spatial/sf#1856]
I am getting the below error linked with the above sf functions:

Error in st_cast.POINT(x[[1]], to, ...) : 
  cannot create MULTILINESTRING from POINT
In addition: Warning message:
In st_cast.GEOMETRYCOLLECTION(X[[i]], ...) :
  only first part of geometrycollection is retained

Any hint on the cause and fix?

thanks

**Comment by rsbivand** [comment]
Reproducible example, please! Maybe based on `?st_multipoint`:
```
library(sf)
outer = matrix(c(0,0,10,0,10,10,0,10,0,0),ncol=2, byrow=TRUE)
hole1 = matrix(c(1,1,1,2,2,2,2,1,1,1),ncol=2, byrow=TRUE)
hole2 = matrix(c(5,5,5,6,6,6,6,5,5,5),ncol=2, byrow=TRUE)
pts = list(outer, hole1, hole2)
(ml1 = st_multilinestring(pts))
st_cast(ml1, "POINT")
st_cast(ml1, "MULTIPOINT")
st_cast(st_cast(ml1, "MULTIPOINT"), "POINT")
```
Is your MULTILINESTRING valid?

**Comment by fipoucat** [comment]
I'll check more closely because it is not direct use of mentioned
functions. I get the error when using a ggplot2 function geom_sf().
If not solved maybe will send the error to ggplot2.

Thank you

**Comment by fipoucat** [comment]
disabling s2 solved my problem.

**Comment by dominicroye** [comment]
I had the same error today for the first time. It's somewhat strange and it can be solved as stated by @fipoucat when I set s2 FALSE. I had only points generated with st_as_sf().

**Comment by fabeit** [comment]
Same problem here, everything was working before I updated to the latest version.

**Comment by apal90** [comment]
I am sorry, how does on turn off `s2`? And this issue is still not solved in the latest version of `sf`.

**Comment by edzer** [comment]
> I am sorry, how does on turn off s2?

`sf_use_s2(FALSE)`
