### ISSUE TITLE
Transforming GEOMETRYCOLLECTION to POINT

### ISSUE THREAD

**Issue by CianGraham** [r-spatial/sf#1857]
Hello everyone,

I am new to sf. Now I have some points that is `GEOMETRYCOLLECTION` like below:
`Geometry set for 1 feature  (with 1 geometry empty)`
`Geometry type: GEOMETRYCOLLECTION`
`Dimension:     XY`
`Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA`
`Projected CRS: Belge 1972 / Belgian Lambert 72`
`GEOMETRYCOLLECTION EMPTY`

However, I would like to transform this to `POINT`, something like below:
`Geometry set for 1 feature  (with 1 geometry empty)`
`Geometry type: POINT`
`Dimension:     XY`
`Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA`
`Projected CRS: Belge 1972 / Belgian Lambert 72`
`POINT EMPTY`

I am wondering which function I should use to achieve this? I have tried `st_cast` but I got the following error message:
`Error in seq_len(nrow(m)) : `
`  argument must be coercible to non-negative integer`
`In addition: Warning messages:`
`1: In structure(as.matrix(y), class = c(class(y)[1], to, "sfg")) :`
`  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.`
`  Consider 'structure(list(), *)' instead.`
`2: In seq_len(nrow(m)) : first element used of 'length.out' argument`

Thanks in advance :)

**Comment by rsbivand** [comment]
Please provide a fully reproducible example; without such an example any response would be guesswork.

**Comment by edzer** [comment]
You may want to look into `st_collection_extract()`

**Comment by SpatLyu** [comment]
Thanks,Save my life!!!
