### ISSUE TITLE
sf install cannot find libpng

### ISSUE THREAD

**Issue by birendave** [r-spatial/sf#1858]
Hello, I am having some difficulties installing sf on an HPC system, where I do not have root permissions.

I have confirmed that GDAL, GEOS, PROJ and LIBPNG are installed system-wide.

In R, I am executing the following to install sf:

`install.packages("sf", lib = "/home/bdave/R/x86_64-pc-linux-gnu-library/4.1", configure.args = "--with-gdal-config=/hpf/tools/centos6/gdal/2.4.0/bin/gdal-config --with-geos-config=/hpf/tools/centos6/geos/3.4.2/bin/geos-config --with-proj-lib=/hpf/tools/centos6/proj/5.2.0/bin/ --with-proj-include=/hpf/tools/centos6/proj/5.2.0/include/")`

I am getting the following output:

* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -std=gnu99
configure: CXX: g++ -std=gnu++11
configure: gdal-config set to /hpf/tools/centos6/gdal/2.4.0/bin/gdal-config
checking gdal-config exists... yes
checking gdal-config executable... yes
checking gdal-config usability... yes
configure: GDAL: 2.4.0
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
/bin/ld: warning: libpng12.so.0, needed by /hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so, not found (try using -rpath or -rpath-link)
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_create_write_struct@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_color_type@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_rowbytes@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_write_end@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_tRNS@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_interlace_type@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_compression_level@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_IHDR@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_tRNS@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_read_image@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_cHRM@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_write_image@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_read_end@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_write_info@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_compression_strategy@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_access_version_number@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_gAMA@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_error_ptr@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_write_fn@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_iCCP@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_channels@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_text@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_sig_cmp@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_packing@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_iCCP@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_create_info_struct@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_cHRM@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_io_ptr@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_read_rows@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_error_fn@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_bit_depth@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_destroy_write_struct@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_gAMA@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_PLTE@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_destroy_read_struct@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_create_read_struct@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_read_fn@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_write_rows@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_sRGB@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_error@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_PLTE@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_image_height@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_rows@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_read_png@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_image_width@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_text@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_IHDR@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_sRGB@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_read_info@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_valid@PNG12_0'
collect2: error: ld returned 1 exit status
/bin/ld: warning: libpng12.so.0, needed by /hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so, not found (try using -rpath or -rpath-link)
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_create_write_struct@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_color_type@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_rowbytes@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_write_end@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_tRNS@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_interlace_type@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_compression_level@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_IHDR@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_tRNS@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_read_image@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_cHRM@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_write_image@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_read_end@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_write_info@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_compression_strategy@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_access_version_number@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_gAMA@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_error_ptr@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_write_fn@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_iCCP@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_channels@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_text@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_sig_cmp@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_packing@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_iCCP@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_create_info_struct@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_cHRM@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_io_ptr@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_read_rows@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_error_fn@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_bit_depth@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_destroy_write_struct@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_gAMA@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_PLTE@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_destroy_read_struct@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_create_read_struct@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_read_fn@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_write_rows@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_sRGB@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_error@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_PLTE@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_image_height@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_rows@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_read_png@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_image_width@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_text@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_set_IHDR@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_sRGB@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_read_info@PNG12_0'
/hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so: undefined reference to `png_get_valid@PNG12_0'
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘sf’
* removing ‘/home/bdave/R/x86_64-pc-linux-gnu-library/4.1/sf’

The downloaded source packages are in
        ‘/localhd/tmp/RtmpBy952H/downloaded_packages’
Warning message:
In install.packages("sf", lib = "/home/bdave/R/x86_64-pc-linux-gnu-library/4.1",  :
  installation of package ‘sf’ had non-zero exit status

`libpng12.so.0` is apparently not found, however it is available on the HPC at the following path: `/hpf/tools/centos6/libpng/1.2.59/lib/libpng12.so.0`.

Is there a way to specify the path to `libpng12.so.0` during sf installation?

Thank you very much,

Biren

**Comment by edzer** [comment]
> Is there a way to specify the path to libpng12.so.0 during sf installation?

No. You may succeed by manipulating `LD_LIBRARY_PATH`, but R does that too, so that might collide or fail. I would say, if GDAL got installed _properly_ on your system, your system should find the libraries GDAL depends on when linking to it. I wouldn't consider your case as having "GDAL installed system-wide". Yes, it has been put somewhere, but doesn't work.

**Comment by edzer** [comment]
On my system, GDAL links to 120 other libraries, so if you solve this for libpng, then ...

**Comment by birendave** [comment]
Thank you for the prompt reply, Edzer.

I'm able to run:
`[bdave@qlogin22 ~]$ gdal-config --version`
`2.4.0`

Is there a way to check which libraries GDAL is linking to?

**Comment by edzer** [comment]
```
ldd /hpf/tools/centos6/gdal/2.4.0/lib/libgdal.so
```

**Comment by birendave** [comment]
Thank you again, it does appear that libpng is not linked to GDAL

libpng12.so.0 => not found

**Comment by edzer** [comment]
When you have GDAL reinstalled, make sure to pick a more recent version!

**Comment by birendave** [comment]
yes will do! thank you
