### ISSUE TITLE
st_intersection does not provide non-overlap points

### ISSUE THREAD

**Issue by jstrunk001** [r-spatial/sf#1859]
There doesn't seem to be a way to return observations with NA values when vectors do not intersect. For example in the code below any "pts" that do not fall within "plys" are dropped. Am I missing the syntax to retain those values with NAs ?

```
pts_ply = st_intersection(pts,plys)
```
I would have guessed something like

```
pts_ply = st_intersection(pts,plys , na.rm=F)
```

Thanks !

**Comment by edzer** [comment]
No. You may want to try `st_disjoint()` to find which points do not intersect, or `st_difference` to find those points.

**Comment by jstrunk001** [comment]
> No. You may want to try `st_disjoint()` to find which points do not intersect, or `st_difference` to find those points.

Ok, thank you!

**Comment by markolipka** [comment]
Does st_join(pts, plys, left = TRUE) what you want?

**Comment by jstrunk001** [comment]
> Does st_join(pts, plys, left = TRUE) what you want?

Yes! that is exactly what I was looking for - thank you!
