### ISSUE TITLE
A geometric error

### ISSUE THREAD

**Issue by Ysuerte** [r-spatial/sf#1865]
Good evening everyone.
I disturb you because an R script gives me an error that I cannot resolve.
The error in question is Error in CPL_nary_intersection (x): GEOS exception. Unfortunately, all the solutions I found on this forum did not solve the problem (maybe I applied them incorrectly). What should can I write here to enable people to give me help? Thank you all

**Comment by Ysuerte** [comment]
Thanks. 
Forgive my ignorance! What can I post?
The script that generates the error?

**Comment by edzer** [comment]
Here; make sure that it is reproducible by someone else.

**Comment by Ysuerte** [comment]
I thank you for your patience. the script uses a Gdb in which the problem occurs only in one of the feature classes. Could it be useful to post the script and feature class (put in the repository)?

**Comment by Ysuerte** [comment]
This is the script. I hope it's not too long to check. Besides the script what can I provide?

library("sp")
library("rgdal")
library("stringr")
library("plyr")
library("dplyr")
library("sf")
library("s2")
library("GISTools")
library("rgeos")

studiogdb <-"N:\\Cartografia Catastale 2018\\DB_CATASTO_GL\\CATASTO_2018.gdb"
subset(ogrDrivers(), grepl("GDB", name))
fc_list <- ogrListLayers(studiogdb)
layer<-sort(print(fc_list))

tipo_file=c("_FAB","_PART", "_FID", "_FOG", "_ACQ", "_STRA")
layer<-c("TP_FAB", "TP_PART", "TP_FID", "TP_FOG", "TP_ACQ", "TP_STRA",
         "CA_FAB","CA_PART", "CA_FID", "CA_FOG", "CA_ACQ", "CA_STRA",
         "NU_FAB","NU_PART", "NU_FID", "NU_FOG", "NU_ACQ", "NU_STRA")

for(i in 1:length(tipo_file)){
  layer_da_girare<-layer[substring(layer, 3)==tipo_file[i]]
    
  for(j in 1:length(layer_da_girare)){
    st_make_valid(catasto<-st_read(dsn=studiogdb,layer=layer_da_girare[j], stringsAsFactors = FALSE)) 
    as.vector(catasto$Nomefile)
        
    if (tipo_file[i]=="_FAB") { sf=st_sf(catasto)
                                           st_transform(sf, crs=st_crs(32632))
                                           fabbricati_sovrapposti <- st_intersection((sf[which(lengths(st_overlaps(sf)) > 0),]), dec=",")
                                           sf_use_s2(FALSE)
                                           fabbricati_sovrapposti$area <- st_area(fabbricati_sovrapposti)
                                           fabbricati_sovrapposti1=cbind(E,fabbricati_sovrapposti)
                                           st_precision(sf)=0.01
                                           if (g<1) {FABBRICATI_SOVRAPPOSTI=fabbricati_sovrapposti1;rm(fabbricati_sovrapposti,fabbricati_sovrapposti1)} else {print("E' il primo")}
                                           if (g>0) {FABBRICATI_SOVRAPPOSTI=rbind.fill(FABBRICATI_SOVRAPPOSTI,fabbricati_sovrapposti1); rm(fabbricati_sovrapposti,fabbricati_sovrapposti1)} else {g=1}                                        
                                              
        } else  {print ("Nessuna sovrapposizione")}
    } }

**Comment by kadyb** [comment]
@Ysuerte, these materials are very helpful to prepare the reproducible example:
1. https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example
2. https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-create-one/5219

I think you should remove unnecessary packages, add a minimal dataset in an attachment, and reduce lines of code. Then the chances of solving the problem will increase. You can also check other resolved issues as examples which include reproducible examples.

**Comment by Ysuerte** [comment]
Good morning. I was able to solve this problem by using the st_make_valid command
in the right syntax (I found in these pages the example that looked like my file). Thanks to you for the support.
