### ISSUE TITLE
Unclear error messages for standalone .shp files and SHAPE_RESTORE_SHX

### ISSUE THREAD

**Issue by 18kimn** [r-spatial/sf#1866]
## Describe the bug
I often have to work with standalone `.shp` files for reasons beyond my control. I understand I lose quite a bit of information when the files that should go along with it are not provided, but I'm still interested in importing the data and working with what I have. I'm not sure how to do so using the standard `read_sf`/`st_read` functions and the provided error messages seem counterintuitive.

When running the below example, `sf` (or rather GDAL) throws an error because it can't find a `.shx` file. This is expected and good, and the message suggesting to set `SHAPE_RESTORE_SHX` from GDAL is also helpful. However, when I pass ` options="SHAPE_RESTORE_SHX='YES'"` and other variants of that option, `read_sf`/`CPL_read_ogr`/GDAL tells me that the option is not supported, while still telling me to specify it:

```r
Error: Cannot open "[...]/nc.shp"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
In addition: Warning messages:
1: In CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  GDAL Message 6: driver ESRI Shapefile does not support open option SHAPE_RESTORE_SHX
2: In CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  GDAL Error 4: Unable to open [...]/nc.shx or [...]/nc.SHX. Set SHAPE_RESTORE_SHX config option to YES to restore or create it.
```

This is confusing, I'm not sure if I should be specifying it or the option is unsupported, or if there is a syntax error with the `option=` field on my end. `SHAPE_RESTORE_SHX` also seems to be [relatively new](https://gdal.org/drivers/vector/shapefile.html#advanced-topics) so maybe the issue comes from that, but my version of GDAL is up-to-date as the output of `sf_extSoftVersion` below shows. The current documentation has a nice note about `options`, and the discussion in #1157 that the docs point to in that note is informative, but I still can't get this syntax to work.

## Suggested fix

- best-case scenario: automatically recreate `.shx` files by specifying the `SHAPE_RESTORE_SHX` option under the hood, and throw a warning that this happened
- also best-case: fixing any possible `sf` inconsistencies that lead to this paradoxical error
- second-best-case scenario: addition to the docs for how to correctly specify options like `SHAPE_RESTORE_SHX` . If the option cannot be specified, addition to the docs for alternative strategies to recreate `.shx` files
- More specific error messages. The provided `sf` error just says the source is corrupt or not supported, which is partially true, but this information and the advice to check `st_drivers` can be more helpful. Some strategies here could be:
    - `st_drivers` could report a column for the conditions that lead to a driver being used -- for example, I'd like to see that `.shp` files will be associated with the ESRI shapefile driver, and that `.json` files will be associated with GeoJSON/TopoJSON/etc. 
    - Related information could be shown in the error message, showing which drivers were tried or should have worked (e.g. if a `JSON` file was supplied, to report the JSON-related drivers that were tried but did not succeed)
    - If possible, to check which of "source is corrupt" and "source is not supported" it is, and report only the case that threw the error  

These error message changes might require lower-level interaction than what `sf` currently does. My guess is that `gdal` picks the driver and not `sf` directly, so `sf` might not be able to report how `gdal` picked it exactly or what "should" have worked but in fact did not. So I'd definitely be happy with just more documentation.

## To reproduce

```r
library(sf)
# move the file into a directory where no other shapefile components are present
dir.create("test")
file.copy(system.file("shape/nc.shp", package="sf"), "test/nc.shp")
read_sf("test/nc.shp")
read_sf("test/nc.shp", options="SHAPE_RESTORE_SHX='YES'")        
read_sf("test/nc.shp", options="SHAPE_RESTORE_SHX=true")        
```

<details>

`sf_extSoftVersion()`:

```
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.9.0"        "3.2.1"        "7.2.1"         "true"         "true" 
          PROJ 
       "7.2.1" 
```

`sessionInfo()`:

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_1.0-2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7         rstudioapi_0.13    magrittr_2.0.1    
 [4] units_0.7-2        tidyselect_1.1.1   R6_2.5.1          
 [7] rlang_0.4.12       fansi_0.5.0        dplyr_1.0.7       
[10] tools_4.1.2        grid_4.1.2         KernSmooth_2.23-20
[13] utf8_1.2.2         e1071_1.7-9        DBI_1.1.1         
[16] ellipsis_0.3.2     class_7.3-19       assertthat_0.2.1  
[19] tibble_3.1.6       lifecycle_1.0.1    crayon_1.4.2      
[22] purrr_0.3.4        vctrs_0.3.8        glue_1.5.1        
[25] proxy_0.4-26       compiler_4.1.2     pillar_1.6.4      
[28] generics_0.1.1     classInt_0.4-3     jsonlite_1.7.2    
[31] pkgconfig_2.0.3   
```
</details>

**Comment by 18kimn** [comment]
Another anomaly is that 
```
SHAPE_RESTORE_SHX=YES ogrinfo -al nc.shp
```

Seems to work as expected. Perhaps the problem is with `sf`?

**Comment by edzer** [comment]
You don't give a reproducible example, so we can only guess. Have you tried
```r
Sys.setenv(SHAPE_RESTORE_SHX='YES')
read_sf("test/nc.shp")
```
You're assuming that passing it through `options` works, but that's not always the case.

**Comment by 18kimn** [comment]
Sorry, I tried to include an example reproducing the error and message at the bottom of the post. Is the example not reproducible / what would qualify it as a reproducible example?

And thank you, that works perfectly! I don't know why I didn't think of that after seeing the environment variable worked for `ogrinfo`. Please feel free to close this issue --
