### ISSUE TITLE
SF and SQL with several queries

### ISSUE THREAD

**Issue by latot** [r-spatial/sf#1880]
Hi hi, I notice sf have SQL support, and is great, here the question:

1) lets read data with a sql query

2) do something with the data

Question, in step 2, where will be executed the new queries, in the db or in R?

Thx.

**Comment by mdsumner** [comment]
in R

**Comment by edzer** [comment]
If you have a spatial database, you can do a spatial query in step 1, but this has nothing to do with what this package does.

**Comment by latot** [comment]
maybe, I think SF is a great lib, and would be useful if we can choose, run the functions over R, or over SQL.

**Comment by edzer** [comment]
> in R

@mdsumner have you read the last paragraph [here](https://gdal.org/user/ogr_sql_dialect.html#non-ogr-sql)? 

> All OGR drivers for database systems: MySQL, PostgreSQL / PostGIS, Oracle Spatial, SQLite / Spatialite RDBMS, ODBC RDBMS, ESRI Personal GeoDatabase, and MSSQLSpatial - Microsoft SQL Server Spatial Database, override the GDALDataset::ExecuteSQL() function with dedicated implementation and, by default, pass the SQL statements directly to the underlying RDBMS. 

@latot this concerns the use of the `query` argument to `st_read()`.

**Comment by mdsumner** [comment]
yes, {lazysf} allows some more - but not tested much against real databases, there's some key differences between real ones and the way gdal provides a virtual db for non-databases - there's a small sql engine in gdal for any format, but the query is passed directly to a real db
