### ISSUE TITLE
Using st_intersection

### ISSUE THREAD

**Issue by Ysuerte** [r-spatial/sf#1883]
Good evening everyone.
I have a problem due to my lack of knowledge of R and for this reason I ask everyone for useful advice.
I am using the st_intersection command on a single polygonal shape file to investigate the possible intersections between the polygons.

The geometry structure of the result is
 
MULTIPOLYGON            POLYGON     GEOMETRYCOLLECTION              POINT  LINESTRING    MULTILINESTRING            (Other) 
        7869                         6267                     3245                                   35           28                       22                              2 
       
This result is a problem also because it is not exportable. 
My question is:
it would be possible to obtain a result so that are there only polygons? 
1)Multipolygons should be divided into as many records as there are polygons created by the st_intersecion (every polygon generated= 1 record). 
2)The geometrycollection unfortunately I don't know what it corresponds to and I don't know what relationship there is with polygons. 3)Eliminate point, linestring, multilinestring and others because they are non-useful objects created by st_intersection.
Thank you for your patience and the opportunity to learn from everyone's expertise.

**Comment by kadyb** [comment]
You didn't include reprex, so here are just general tips.

> 3)Eliminate point, linestring, multilinestring and others because they are non-useful objects created by st_intersection.

Suppose `x` is a sfc object. Using [st_is()](https://r-spatial.github.io/sf/reference/st_is.html) you can check if the geometry is of a given type and you get a logic vector (it can be change to index).

```r
# select only "POLYGON" and "MULTIPOLYGON" types
logical_vec = st_is(x, c("POLYGON", "MULTIPOLYGON"))
idx = which(logical_vec) # return index instead of logical value
x_selected = x[idx]
```

> 1)Multipolygons should be divided into as many records as there are polygons created by the st_intersecion (every polygon generated= 1 record).

You can use [st_cast()](https://r-spatial.github.io/sf/reference/st_cast.html) for this.

```r
# cast "MULTIPOLYGON" to "POLYGON"
st_cast(multipolygon, "POLYGON")
x_cast = st_cast(x[st_is(x, "MULTIPOLYGON")], "POLYGON")
```

> 2)The geometrycollection unfortunately I don't know what it corresponds to and I don't know what relationship there is with polygons.

The extraction of specific geometries from the collection is possible by [st_collection_extract()](https://r-spatial.github.io/sf/reference/st_collection_extract.html).

```r
# st_geometrycollection() example
pt = st_point(c(1, 0))
ls = st_linestring(matrix(c(4, 3, 0, 0), ncol = 2))
poly1 = st_polygon(list(matrix(c(5.5, 7, 7, 6, 5.5, 0, 0, -0.5, -0.5, 0), ncol = 2)))
poly2 = st_polygon(list(matrix(c(6.6, 8, 8, 7, 6.6, 1, 1, 1.5, 1.5, 1), ncol = 2)))
multipoly = st_multipolygon(list(poly1, poly2))
i = st_geometrycollection(list(pt, ls, poly1, poly2))
polygons = st_collection_extract(i, "POLYGON")
```

There are books for spatial data science: [Geocomputation with R](https://geocompr.robinlovelace.net/) and [Spatial Data Science with applications in R](https://www.r-spatial.org/book). There are [tutorials](https://r-spatial.github.io/sf/articles/) for `{sf}`.

**Comment by Ysuerte** [comment]
I have tried several times to post a reprex but it was never considered sufficient. Could you help me post a right one because I've never been able to even though I have read all the specifications that have been indicated to me on what a reprex should contain. Thanks a lot

**Comment by kadyb** [comment]
Reprex should look like this, but notice that `i` only contains polygons and linestrings. You have to adapt this to your case. 

```r
library("sf")

poly1 = matrix(c(0, 0, 1, 0, 1, 1, 0, 1, 0, 0), ncol = 2, byrow = TRUE)
poly1 = st_polygon(list(poly1))
poly2 = matrix(c(1, 0, 2, 0, 2, 1, 1, 1, 1, 0), ncol = 2, byrow = TRUE)
poly2 = st_polygon(list(poly2))
buffer = st_buffer(st_point(c(1, 1)), dist = 0.5)
sfc = st_sfc(poly1, poly2, buffer)
# plot(sfc)

i = st_intersection(sfc)
```

**Comment by Ysuerte** [comment]
tipo_file=c("_FOG","_ACQ","_STRA","_FAB","_PART","_FID")
for(i in 1:length(tipo_file)){
  layer_da_girare<-layer[substring(layer, 3)==tipo_file[i]]
    
  
  for(j in 1:length(layer_da_girare)){
    st_make_valid(catasto<-st_read(dsn=studiogdb,layer=layer_da_girare[j], stringsAsFactors = FALSE))
    as.vector(catasto$Nomefile)

str(catasto)
Classes ‘sf’ and 'data.frame':	4295 obs. of  16 variables:
 $ Codice_comune: chr  "B080" "B080" "B080" "B080" ...
 $ Sez          : chr  "_" "_" "_" "_" ...
 $ Fg           : chr  "0001" "0002" "0003" "0004" ...
 $ Mappale      : chr  "B080_000100" "B080_000200" "B080_000300" "B080_000400" ...
 $ Denom        : chr  " " " " " " " " ...
 $ Allegato     : chr  "0" "0" "0" "0" ...
 $ Svi          : chr  "0" "0" "0" "0" ...
 $ Nomefile     : chr  "B080_000100" "B080_000200" "B080_000300" "B080_000400" ...
 $ Ext          : chr  " " " " " " " " ...
 $ Htxt         : num  12 12 12 12 12 12 12 12 12 12 ...
 $ Rtxt         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Xtxt         : num  13.5 13.5 13.6 13.6 13.6 ...
 $ Ytxt         : num  37.6 37.6 37.6 37.6 37.6 ...
 $ geom_Length  : num  0.0611 0.0627 0.0294 0.0363 0.0379 ...
 $ geom_Area    : num  8.84e-05 9.52e-05 3.06e-05 3.10e-05 4.61e-05 ...
 $ geom         :sfc_MULTIPOLYGON of length 4295; first list element: List of 1
  ..$ :List of 1
  .. ..$ : num [1:488, 1:2] 8.77 8.77 8.77 8.77 8.77 ...
  ..- attr(*, "class")= chr  "XY" "MULTIPOLYGON" "sfg"
 - attr(*, "sf_column")= chr "geom"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA ...
  ..- attr(*, "names")= chr  "Codice_comune" "Sez" "Fg" "Mappale" 

                                sf=st_sf(catasto)
                               st_transform(sf, crs=st_crs(32632))
                                sf_use_s2(FALSE)
                                st_set_precision(sf,0.001)

                       fogli_sovrapposti <- st_intersection (st_make_valid (sf))

str(fogli_sovrapposti)
Classes ‘sf’ and 'data.frame':	17462 obs. of  18 variables:
 $ Codice_comune: chr  "B080" "B080" "B080" "B080" ...
 $ Sez          : chr  "_" "_" "_" "_" ...
 $ Fg           : chr  "0001" "0001" "0002" "0001" ...
 $ Mappale      : chr  "B080_000100" "B080_000100" "B080_000200" "B080_000100" ...
 $ Denom        : chr  " " " " " " " " ...
 $ Allegato     : chr  "0" "0" "0" "0" ...
 $ Svi          : chr  "0" "0" "0" "0" ...
 $ Nomefile     : chr  "B080_000100" "B080_000100" "B080_000200" "B080_000100" ...
 $ Ext          : chr  " " " " " " " " ...
 $ Htxt         : num  12 12 12 12 12 12 12 12 12 12 ...
 $ Rtxt         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Xtxt         : num  13.5 13.5 13.5 13.5 13.6 ...
 $ Ytxt         : num  37.6 37.6 37.6 37.6 37.6 ...
 $ geom_Length  : num  0.0611 0.0611 0.0627 0.0611 0.0294 ...
 $ geom_Area    : num  8.84e-05 8.84e-05 9.52e-05 8.84e-05 3.06e-05 ...
 $ n.overlaps   : int  1 2 1 2 1 2 1 2 3 2 ...
 $ origins      :List of 17462
  ..$ : int 1
  ..$ : int  1 2
  ..$ : int 2
  ..$ : int  1 3
  ..$ : int 3
  ..$ : int  3 4
  ..$ : int 4
  ..$ : int  4 5
  ..$ : int  3 4 5
  ..$ : int  3 5
  ..$ : int 5
  ..$ : int  4 6
  ..$ : int  4 5 6
  ..$ : int  5 6
  ..$ : int 6
  ..$ : int  2 7
  ..$ : int 7
  ..$ : int  7 8
  ..$ : int  2 8
  ..$ : int  3 8
  ..$ : int 8
  ..$ : int  8 9
  ..$ : int 9
  ..$ : int  8 10
  ..$ : int  9 10
  ..$ : int  8 9 10
  ..$ : int 10
  ..$ : int  8 11
  ..$ : int  10 11
  ..$ : int  8 10 11
  ..$ : int  4 11
  ..$ : int  6 11
  ..$ : int 11
  ..$ : int  7 12
  ..$ : int 12
  ..$ : int  12 13
  ..$ : int  9 13
  ..$ : int  7 13
  ..$ : int  10 13
  ..$ : int 13
  ..$ : int  13 14
  ..$ : int  10 13 14
  ..$ : int  10 14
  ..$ : int  11 14
  ..$ : int 14
  ..$ : int  14 15
  ..$ : int  11 15
  ..$ : int 15
  ..$ : int  12 16
  ..$ : int  13 14 16
  ..$ : int  14 16
  ..$ : int  13 16
  ..$ : int 16
  ..$ : int  16 17
  ..$ : int  15 17
  ..$ : int  14 17
  ..$ : int 17
  ..$ : int  16 18
  ..$ : int  17 18
  ..$ : int 18
  ..$ : int  16 19
  ..$ : int 19
  ..$ : int  19 20
  ..$ : int 20
  ..$ : int  19 21
  ..$ : int  20 21
  ..$ : int  18 21
  ..$ : int 21
  ..$ : int  20 22
  ..$ : int 22
  ..$ : int  21 23
  ..$ : int  20 23
  ..$ : int  20 21 23
  ..$ : int 23
  ..$ : int  22 24
  ..$ : int 24
  ..$ : int  24 25
  ..$ : int  22 24 25
  ..$ : int  22 25
  ..$ : int  20 25
  ..$ : int  23 25
  ..$ : int  20 23 25
  ..$ : int 25
  ..$ : int  25 26
  ..$ : int  24 26
  ..$ : int  24 25 26
  ..$ : int 26
  ..$ : int  25 27
  ..$ : int  23 27
  ..$ : int 27
  ..$ : int  26 28
  ..$ : int  25 28
  ..$ : int  27 28
  ..$ : int 28
  ..$ : int  24 29
  ..$ : int  26 29
  ..$ : int 29
  ..$ : int  29 30
  ..$ : int  26 30
  .. [list output truncated]
 $ geom         :sfc_GEOMETRY of length 17462; first list element: List of 1
  ..$ : num [1:635, 1:2] 8.77 8.77 8.77 8.77 8.77 ...
  ..- attr(*, "class")= chr  "XY" "POLYGON" "sfg"
 - attr(*, "sf_column")= chr "geom"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA ...
  ..- attr(*, "names")= chr  "Codice_comune" "Sez" "Fg" "Mappale" ...

**Comment by Ysuerte** [comment]
Obviously I am unable to publish a reprex
