### ISSUE TITLE
Source installation on macOS fails due to configure issues (libproj, sqlite3)

### ISSUE THREAD

**Issue by pat-s** [r-spatial/sf#1894]
As already noted by the action taken in https://github.com/r-spatial/sf/commit/cc698f22f7fce70288b6efcaaef7f387cc204434 there is an issue when installing `sf` (and others, e.g. `terra`) from source on macOS currently (also backed by CI builds).

```
configure: using proj.h.
configure: PROJ: 8.2.1
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
configure: error: libproj or sqlite3 not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
```

Even when defining `PKG_CONFIG_PATH` to point to the sources explicitly, the installation fails.
I've also tried patching `Makevars` without success.

As there was no issue yet covering this, I thought it might be helpful.

**Comment by pat-s** [comment]
The following works

```r
install.packages("sf", type = "source", configure.args = c("--with-sqlite3-lib=/opt/homebrew/opt/sqlite/lib", "--with-proj-lib=/opt/homebrew/opt/proj/lib"))
```

I couldn't quite figure out how to use env vars to define these paths, i.e. the following does not work

```r
Sys.setenv(PROJ_LIBS = "/opt/homebrew/opt/proj/lib")
Sys.setenv(SQLITE3_LIBS = "/opt/homebrew/opt/sqlite/lib")

install.packages("sf", type = "source")
```

In general it is unclear to me what causes this error both for `sf` and `terra` now as the location of these libraries did not change on macOS recently.

**Comment by rsbivand** [comment]
Which architecture? How are the two architectures distinguished when intel is rosetta?

**Comment by pat-s** [comment]
AFACIS it's architecture-agnostic as I am running `arm` locally but the GHA builds are using `x86`.

Paths for both architectures are different of course but until recently `pkg-config` just did the job and given that it appears on both, I think the problem is somewhere else.

**Comment by pat-s** [comment]
AFAICS the issue solved itself; my CI builds which install `sf` from source are green again.

FWIW I personally see source installs and the discovery of such issues as a feature - not as an issue.
It's better to let CI find it (early) than letting users go crazy about it without being able to find a reference for their problem :)

**Comment by pat-s** [comment]
Ups - I was too quick.

Local source installations still error and it seems it was only caught on CI because there was no binary available yet after the last release.

Seems like `remote::install_github()` now makes use of macOS binaries on GHA. Interesting.

**Comment by rsbivand** [comment]
CI from source (apart from the package being checked) for packages other than the one actually being checked seems to be rather CO2-generative. Careful local checking is more parsimonious, isn't it? Maybe it doesn't matter, but heavy CI will put some mm on early sea level increases, won't it? CI for my packages (spdep, spatialreg) only installs binary upstream packages on Windows and macOS, `remotes::install_deps(dependencies = TRUE, type="binary")`, and Linux uses rspm (so only source installing those for which no binary is in the repo).

**Comment by stefanocoretta** [comment]
Are there updates on why this occurs on macOS with Apple Silicon and homebrew?

**Comment by rsbivand** [comment]
Why do you need to install from source? The arm binary for 1.0-7 is available for download, use that. Do you need the development version of sf, or of external software libraries? Nothing else could account for a source install; if just for fun, it doesn't justify an issue.

**Comment by edzer** [comment]
Or consider donating a couple of Silicon/homebrew machines to the r-spatial team! ;-)

**Comment by rsbivand** [comment]
Or, better, to contribute solutions both for homebrew GDAL, PROJ and GEOS binaries, and for building their development versions. Long-term commitment to supporting homebrew users is always welcome.

**Comment by stefanocoretta** [comment]
I am not sure why it builds from source, but it does. In fact, the behaviour relating to installation is very erratic.

Sometimes it works, sometimes it doesn't. Sometimes it gets fixed by applying one or more of the many solutions suggested here on elsewhere. I've been using the package for a few years and had to install it in several occasions and always had issues with installation, on different systems and configurations.

This, in my opinion, qualifies as something that deserves an issue on GH.

**Comment by edzer** [comment]
homebrew is a moving target, is not used for building CRAN binaries, and is a platform neither Roger nor I can troubleshoot with or for. I'd be happy if someone took care of making this stable, but don't see that happening. Leaves me wondering Roger's question:

> Why do you need to install from source?

**Comment by stefanocoretta** [comment]
`renv` was installing it from source, although now in a new repository it installed the binary. I will investigate and report back if anything comes up. But my question remains: when building from source, what causes the problem with linking of proj and sqlite?

I reckon you don't have an answer because you don't have access to brew + silicon, but hopefully somebody can shed light on this (again, I will try to investigate myself).

**Comment by pat-s** [comment]
> Why do you need to install from source? The arm binary for 1.0-7 is available for download, use that. Do you need the development version of sf, or of external software libraries? Nothing else could account for a source install; if just for fun, it doesn't justify an issue.

There are people which favor source installations for different reasons. 
One example is that during the time of a new CRAN release, it takes some time for the binary to be available. If one wants to install the package during these days or just has an automated workflow somewhere, this fails because of this.
I think everybody here agrees that it's not a blocking issue because of a working binary but it's an issue in some cases. This is probably also the reason why its dangling around and nobody wants to tackle it as input/reward is quite low.

I don't think that users are to blame for doing so (and the wording sounds a bit like this tbh) and that a more positive wording could be used.
If there's an issue, this should be professionally addressed and mentioned just like any other issue without any sentiment.
Suggestion: pin this issue in the repo and update the current status in the OP.

> Or consider donating a couple of Silicon/homebrew machines to the r-spatial team! ;-)

Currently a mac Mini costs 799$ in its minimal configuration. Because of the lack of mac arm64 runners in the CI/CD (and cloud) world, one currently needs to use self-hosted runners on such architectures for proper testing. I am not involved into R-consortium or other initiatives too much but I'd consider such testing frameworks a valid use case. Why not get one of these and provide testing access for maintainers in `r-spatial` and other similar established R FOSS orgs?

> Or, better, to contribute solutions both for homebrew GDAL, PROJ and GEOS binaries, and for building their development versions.

This would be great but is like many levels above the average level of contributers or people who just want to have a working source installation of an R package :)

> homebrew is a moving target, is not used for building CRAN binaries, and is a platform neither Roger nor I can troubleshoot with or for. I'd be happy if someone took care of making this stable, but don't see that happening

I would not blame homebrew directly as nothing has changed AFAICS from the point when it worked last. I think it's more likely an issue of `pkg-config` or one of PROJ/GDAL. But in the end it does not matter (and maybe it's in fact an homebrew issue) as this is not a blame game - it should just be addressed or at least communicated in an objective, non-judgemental way :) 

---

That being sad, I also don't currently know where the issue is and have spend like 1-2 hours i the past digging a bit deeper - without success.
Sometimes such linking issues revole itself if underlying deps get updated - sometimes not.

**Comment by edzer** [comment]
Thanks, Patrick for sharing your thoughts. I am not blaming anyone; my targets are CRAN platforms, and source code users who know how to handle source code on their platform.

The MacOS section of the [README](https://github.com/r-spatial/sf#macos) now starts with "MacOS users are strongly encouraged to install the sf binary packages from CRAN, unless they are familiar with compilers, linking, C++ source code, and homebrew."  

I am inclined to remove the remaining part of the section with homebrew instructions, since it seems outdated, doesn't receive updates, and seems to not work. Maybe we could replace it with a section on how to build binaries the way the CRAN MacOS binaries are built, and only mention homebrew as an option that may or may not work, without giving (outdated) instructions that may as well not work.

**Comment by pat-s** [comment]
> Thanks, Patrick for sharing your thoughts. I am not blaming anyone; my targets are CRAN platforms, and source code users who know how to handle source code on their platform.

Thanks, I guess "blame" is a too strong wording here, not sure which word would be a better match WRT to software issues :)
My point was just to emphasize that the issue might not necessarily be caused from the most visible player (i.e. `homebrew`) as a lot is happening behind the scences.
`homebrew` itself is just the package manager, it does not directly/necessarily control what and how the installed libraries do their linking (even though it can of course be used to make (wrong) adaptions and ensure a smooth runtime for users in the best case).

> The MacOS section of the [README](https://github.com/r-spatial/sf#macos) now starts with "MacOS users are strongly encouraged to install the sf binary packages from CRAN, unless they are familiar with compilers, linking, C++ source code, and homebrew."

Sounds fair enough! 

> I am inclined to remove the remaining part of the section with homebrew instructions, since it seems outdated, doesn't receive updates, and seems to not work. Maybe we could replace it with a section on how to build binaries the way the CRAN MacOS binaries are built, and only mention homebrew as an option that may or may not work, without giving (outdated) instructions that may as well not work.

FWIW the general spatial toolstack on macOS was quite solid for me in the last 1-2 years, even when switching to arm lately. Since roughly this time GDAL/PROJ/GEOS are maintained in `homebrew-core` as opposed to `ogeo4mac` (which mainly relied on 1-2 people with write access which sometimes just disappeared). 

I am too far away from the underlying linking with packages like {sf} or {terra} and which role `pkg-config` plays in here. Also I don't have too much involvement right now with all the spatial libs and tools, hence I cannot substantially help to solve this on the code side. But I think reporting and discussing might also be somewhat helpful.

**Comment by pat-s** [comment]
So I've spent a few hours debugging and found something.

AFAICS it comes down to the `LIBS` var in `configure`. Down below you see some results.
When removing `-ljpeg` from `LIBS`, `configure` succeeds.

It looks to me that both proj and sqlite linkers are fine by default and the error message is actually a false positive. I come to this conclusion because in scenario (2), the proj linker is the same as in the default and the sqlite linker is not even used.

```sh
# (1) current default
LIBS="-L/opt/homebrew/Cellar/sqlite/3.38.3/lib -L/opt/homebrew/Cellar/proj/9.0.0_1/lib -lproj
  -L/opt/homebrew/Cellar/libtiff/4.3.0/lib -lc++ -lm -ldl -lsqlite3 -lz -ltiff -ljpeg -lz -lcurl 
  -lldap -lz    -L/opt/homebrew/Cellar/gdal/3.4.2_3/lib -lgdal"
# (2) when using `--with-proj-lib=/opt/homebrew/opt/proj/lib`
LIBS="-L/opt/homebrew/Cellar/proj/9.0.0_1/lib  -lproj   -L/opt/homebrew/Cellar/gdal/3.4.2_3/lib -lgdal"
# (3) without -ljpeg (working)
LIBS="-L/opt/homebrew/Cellar/sqlite/3.38.3/lib -L/opt/homebrew/Cellar/proj/9.0.0_1/lib -lproj
  -L/opt/homebrew/Cellar/libtiff/4.3.0/lib -lc++ -lm -ldl -lsqlite3 -lz -ltiff -ljpeg -lz -lcurl 
  -lldap -lz    -L/opt/homebrew/Cellar/gdal/3.4.2_3/lib -lgdal"
```

Instead of removing `-ljpeg`, one can also add `-L/opt/homebrew/opt/jpeg/lib` to `LIBS`.

Now the final check in https://github.com/r-spatial/sf/blob/main/configure#L3868 is actually making use of `PROJ_LIB_PATH` (as `$LIBS` is defined by it in https://github.com/r-spatial/sf/blob/main/configure#L3780), which is also missing `-L/opt/homebrew/opt/jpeg/lib` by default.

To have a user-level solution here, adding `-L/opt/homebrew/opt/jpeg/lib` to CPPFLAGS in `~/.R/Makevars` works.

```
CPPFLAGS += -L/opt/homebrew/opt/jpeg/lib
```

So to conclude, I don't know which library is actually responsible for the missing linker and where this fix would need to be included - but I am happy to have found an acceptable user level solution.

FWIW, using `proj@7` would also work without modifications, i.e.

```sh
brew unlink proj
brew install proj@7
brew link proj@7
```

**Comment by luispuerto** [comment]
I just set on `.Renviron` file this, so packages are able to find homebrew library first and my problems are solved in general. 

```
PATH="/opt/homebrew/bin:/usr/local/opt/llvm/bin:${PATH}"
```

**Comment by pat-s** [comment]
@luispuerto it's about lib and `.so` files here during the configure step, not about executables. How does your solution help here specifically?

**Comment by luispuerto** [comment]
I was trying to reinstall sf, rgal and terra from source and it gave me error all the time that it wasn't able to find those libraries from homebrew… so instead of point to them on the `install.package` command, I set homebrew first on R path.

Now I have zero complaints while building.

**Comment by pat-s** [comment]
Adding `/opt/homebrew/bin` to $PATH would only add the respective executables, linkers are not affected and other "configure"-related directories. Adding it to the beginning of $PATH means your shell will always look there first but executables. This should do no harm in general (I also have in my $PATH) but is unrelated to this issue (I think).

Still a good advice, thanks for mentioning it!

**Comment by openpencil** [comment]
> The following works
> 
> ```r
> install.packages("sf", type = "source", configure.args = c("--with-sqlite3-lib=/opt/homebrew/opt/sqlite/lib", "--with-proj-lib=/opt/homebrew/opt/proj/lib"))
> ```

Confirming that this works. 

* I had to follow this post https://stackoverflow.com/questions/68263165/installing-r-on-osx-big-sur-edit-and-apple-m1-for-use-with-rcpp-and-openmp/68275558#68275558 

* Then install `brew install udunits` (which came up in an error message during `sf` install)

* Lastly install sf using the command line above in R. The key is pointing `sf` to homebrew's version of sqllite and proj.

**Comment by pat-s** [comment]
Adding to my previous https://github.com/r-spatial/sf/issues/1894#issuecomment-1120383916, I now set `-Qunused-arguments` in addition, so the full definition becomes

```
CPPFLAGS += -L/usr/local/opt/jpeg/lib -Qunused-arguments
```

Doing so suppresses the warning about unused arguments when compiling as passing an `-L` flag in `CPFFLAGS` is usually not expected and the warning might cause an R CMD check failure. Works "good enough" as a workaround.
