### ISSUE TITLE
More Rows than Origin after st_join? How should I tackle this?

### ISSUE THREAD

**Issue by jingjunL** [r-spatial/sf#1901]
**Describe the bug**
I don't know if this is a bug or something. What I tried to do is read a CSV file with geometry information, then, I read a shapefile about the municipality and try to know which municipality does each CSV row belongs to. The code I have is as below:
`library(dplyr)`
`library(sf)`
`library(sfheaders)`
`library(tmap)`
`library(readr)`
`tmap_mode("view")`
`#Read output trip`
`outputTrip <- read_delim("example.csv")`
`#Read BRU shapefile`
`BrusselsMunicipality <- st_read("BrusselsShapefile/UrbAdm_MUNICIPALITY.shp", crs = 31370)`
`#Check if the trip origin is within Brussels`
`outputTrip_origin <- sf_point(outputTrip, x = "start_x", y = "start_y")`
`outputTrip_origin <- st_set_crs(outputTrip_origin, 31370)`
`#----------------------------------------------------------------(10000 rows after this)`
`#st join the table`
`outputTrip_origin <- st_join(outputTrip_origin, select(BrusselsMunicipality, NAME_FRE))`
`#----------------------------------------------------------------(10001 rows after this)`

Basically, if I run this code, the final output `outputTrip_origin` will have 10001 rows. I guess the problem is because that point is at the boundary of two polygons, and when it is processed by sf, sf thinks it belongs to both polygons, so it produce an additional row for this point. However, this is not what I would like to have, I want to have 10000 rows so that I can do `cbind` with `output_trip` after this step. Nevertheless, I don't know which point causes this problem because there are indeed multiple duplicated points in my dataset. I am wondering how should I tackle this? Thanks!

**To Reproduce**
[example.csv](https://github.com/r-spatial/sf/files/8008134/example.csv)

Github cannot upload shapefile, you can download it from here:
https://drive.google.com/drive/folders/1DlugHNpST9RQXvtyVPPjmEPLMFfuqwg_?usp=sharing

**Comment by edzer** [comment]
Duplicate points will not be the problem, but the single point that is on a polygon boundary. You can find that point with
```r
> which(lengths(st_intersects(outputTrip_origin, BrusselsMunicipality)) > 1)
[1] 1779
```

**Comment by jingjunL** [comment]
> Duplicate points will not be the problem, but the single point that is on a polygon boundary. You can find that point with
> 
> ```r
> > which(lengths(st_intersects(outputTrip_origin, BrusselsMunicipality)) > 1)
> [1] 1779
> ```

Hi @edzer, thanks very much! That's very helpful.

Just a small suggestion, maybe we should add at least a warning when such of situation happen as it changes the original data, but as a user who is not aware of such situation, he will not know some additional points are added there. What do you think?

**Comment by edzer** [comment]
> What do you think?

For your case understandable, but not generalizable: one-to-many or many-to-many links are very common. Even for the case where the first argument is `POINT` geometries, there is no guarantee that there are no overlapping polygons in the second argument, which leads to one-to-many links for points not on polygon boundaries.
