### ISSUE TITLE
After using st_shift_longitude, gridlines disappear

### ISSUE THREAD

**Issue by kdgorospe** [r-spatial/sf#1907]
# Plotting before st_shift_longitude

> no_shift <- ne_countries(scale = "medium", returnclass = "sf", type = "countries", country = "United States of America")
> ggplot(data = no_shift) + geom_sf()
![no_shift](https://user-images.githubusercontent.com/2940025/155752227-1b7fe31c-1af8-41e6-986b-44a286f75840.png)

# Plotting after st_shift_longitude

> shift <- st_shift_longitude(no_shift)
> ggplot(data = shift) + geom_sf() 
![shift](https://user-images.githubusercontent.com/2940025/155752204-1e7d9703-1550-4b7e-939b-557d3590e33d.png)

**If reporting a change from previous versions**

Please read https://cran.r-project.org/web/packages/sf/news/news.html first.

**Additional context**

<details>
Paste the output of your `sessionInfo()` and `sf::sf_extSoftVersion()`
</details>

**Comment by edzer** [comment]
Fixed in https://github.com/r-spatial/sf/commit/b3eb4f17ce8bfc45bb454851047eed7b14a61e94
