### ISSUE TITLE
Extreme delays in plot times for UK admin data specific to macos

### ISSUE THREAD

**Issue by kidwellj** [r-spatial/sf#1909]
When I load in any of the shapefile datasets from [Census data explorer](https://borders.ukdataservice.ac.uk/) plots are brutally slow. I suspect this is an issue specific to MacOS (but not just a1 chip machines). I'm running MacOS 11.6, R-4.1.2-arm64 and RStudio 2021.09.1+372. I've replicated this problem using R command line and in RStudio. Plots take more than 30 minutes, potentially several hours across any of the configurations I've tried, whereas someone with a Windows laptop can run them in seconds.

**To Reproduce**
```
require(sf)
download.file("https://borders.ukdataservice.ac.uk/ukborders/easy_download/prebuilt/shape/infuse_dist_lyr_2011.zip", destfile = "data/gis/infuse_dist_lyr_2011.zip")
unzip("infuse_dist_lyr_2011.zip", exdir = "data/gis")
local_authorities <- st_read("data/gis/infuse_dist_lyr_2011.shp")
plot(local_authorities)
```

This seems to be related to the complexity of shapes:

```
require(sf)
local_authorities <- st_read("data/gis/infuse_dist_lyr_2011.shp")
benchmark("row1" = {
          plot(local_authorities[1,])}, 
benchmark("row2" = {
          plot(local_authorities[2,])}, 
benchmark("row3" = {
          plot(local_authorities[3,])}, 
benchmark("row4" = {
          plot(local_authorities[4,])}, 
replications = 1, columns = c("test", "replications", "elapsed", "relative", "user.self", "sys.self"))
```

Results are the following:

```
  test replications elapsed relative user.self sys.self
1 row1            1   0.134        1     0.121    0.006
1 row2            1 964.725        1   961.112    2.294
1 row3            1   0.358        1     0.333    0.015
1 row4            1   0.136        1     0.124    0.008
1 row5            1   0.578        1     0.557    0.012
1 row6            1   0.245        1     0.237    0.004
1 row7            1   8.603        1      8.55    0.041
1 row8            1   0.776        1     0.757    0.011
1 row9            1   0.471        1      0.45     0.01
1 row10            1   0.174        1     0.167    0.003
1 row11            1  83.648        1     83.26    0.246
```

Inspecting individual shapes in this shapefile seems to indicate that the struggle here relates to the number of parts within each individual MULTIPOLYGON. So row 2 has more than a thousand parts, others with similar levels of complexity also lag greatly, e.g. Shetland, row 244 with 549 parts and row 387, with 521 parts.

I've included some more specific performance metrics on [stackexchange here](https://gis.stackexchange.com/questions/424897/why-is-sf-struggling-to-run-plots-quickly-on-uk-datasets)

<details>

> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Big Sur 11.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] fansi_0.5.0      assertthat_0.2.1 utf8_1.2.2       crayon_1.4.2     dplyr_1.0.7      R6_2.5.1        
 [7] DBI_1.1.2        lifecycle_1.0.1  magrittr_2.0.1   scales_1.1.1     pillar_1.6.4     rlang_0.4.12    
[13] vctrs_0.3.8      generics_0.1.1   ellipsis_0.3.2   forcats_0.5.1    tools_4.1.2      glue_1.5.1      
[19] munsell_0.5.0    purrr_0.3.4      compiler_4.1.2   colorspace_2.0-2 pkgconfig_2.0.3  tidyselect_1.1.1
[25] tibble_3.1.6

sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
       "3.9.1"        "3.2.3"        "7.2.1"         "true"         "true"        "7.2.1" 
</details>

**Comment by edzer** [comment]
On an average laptop running Ubuntu:
```r
> system.time(plot(local_authorities))
   user  system elapsed 
 20.423   0.555  24.788 
```
does that make this an `sf` issue?

**Comment by kidwellj** [comment]
Hmmm. Maybe R?

**Comment by edzer** [comment]
Yes, or the graphics device on macos? Does it also take so long to write the same plot to a png or pdf?

**Comment by ateucher** [comment]
The default graphics device on macOS is [known to be slow](https://github.com/rstudio/rstudio/issues/3866). I will sometimes switch to `x11()` for interactive plotting of sf objects as I iterate (though it's not as nice looking). As suggested in that thread you can switch your graphics device in RStudio to use `AGG` (requires the `ragg` package to be installed).

Using the `AGG` device I get:

```
> system.time(plot(local_authorities))
   user  system elapsed 
122.059   4.464 127.085 
```

Slower than @edzer on Ubuntu but much faster than what you report. I tried using the default device and ended up just manually killing it after about 5 minutes.

**Comment by kidwellj** [comment]
That is the ticket. Wow, thanks @ateucher completely resolved the issue on my side, and really glad to know about this easy fix.

```
> benchmark("local_authorities" = {plot(local_authorities)}, replications = 1, columns = c("test", "replications", "elapsed", "relative", "user.self", "sys.self"))
               test replications elapsed relative user.self sys.self
1 local_authorities            1   9.017        1     8.073    0.437
> 
```
