### ISSUE TITLE
Problem installing sf 1.0-6 from binary on Mac OSX 12 (Monterey)

### ISSUE THREAD

**Issue by aneal01** [r-spatial/sf#1910]
Hi,

I'm having trouble installing sf 1.0-6 from binary using RStudio. When it asks if I want to install from source, I respond "no", and it downloads an older version of sf (v0.8-1). I am undoubtedly missing something very obvious here, but would appreciate any help that people could provide.   

Here is a copy of the output that I get when I try to install sf:

> install.packages("sf")

  There is a binary version available but the source version is later:
   binary source needs_compilation
sf  0.8-1  1.0-6              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) no
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/sf_0.8-1.tgz'
Content type 'application/x-gzip' length 53770407 bytes (51.3 MB)
==================================================
downloaded 51.3 MB

The downloaded binary packages are in
	/var/folders/yf/2f0_wnss5k12pj2bkv9p2t1xsr9r1b/T//RtmpSuBlbr/downloaded_packages

I'm using RStudio 2022.02.0 Build 443, and session info is as follows:

> sessionInfo()

R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X  12.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.2 tools_3.5.2

**Comment by edzer** [comment]
> R version 3.5.2 (2018-12-20)

Update your R version to the released version, 4.1.2.

**Comment by rsbivand** [comment]
Please try a different CRAN mirror, but note that the offered binary is the last published for R 3.5, which is not supported any more. Binary packages are available for 4.1 and 4.0; 4.2 will be released shortly. If that doesn't work, download the tgz file from https://cran.r-project.org/package=sf for your architecture, but again will not work for R 3.5.

**Comment by aneal01** [comment]
Thanks for that - I updated to R v4.1.2 and it worked.
