### ISSUE TITLE
Slivers after intersecting

### ISSUE THREAD

**Issue by ecrjak** [r-spatial/sf#1913]
I am currently trying to transfer from sp to sf but am encountering some issues with intersections, namely that often (not always) polygon borders of excluded polygons end up in the final product of st_intersections. I did not encounter such issues with the sp equivalent and was wondering what I'm missing here. This is a minimum example of the issue and I'm attaching the shape file folder as well:
[German_Empire_1871_Stat_v.1.0.zip](https://github.com/r-spatial/sf/files/8184194/German_Empire_1871_Stat_v.1.0.zip)

```
map.path <- paste0(datapath2, "/../GIS/german_empire_statistical_units_1871-1931/", 
                    "German Empire Statistical Units/German_Empire_1871_Stat_v.1.0.shp")


map.tocut <- read_sf(map.path)
map.cutter <- st_union(st_make_valid(map.tocut[map.tocut$LAND != "20000",]))

map.tocut <- map.tocut[map.tocut$LAND %in% c("19000","20000"),]
map.tocut <- st_intersection(map.tocut, map.cutter)

table(map.tocut$LAND)
plot(st_geometry(map.tocut[map.tocut$LAND == "20000",]))


map.tocut <- readOGR(map.path)
map.cutter <- gUnaryUnion(clgeo_Clean(map.tocut[map.tocut$LAND != "20000",]))

map.tocut <- map.tocut[map.tocut$LAND %in% c("19000","20000"),]

temp <- map.tocut@data
row.names(temp) <- sapply(slot(map.tocut, "polygons"), function(x) slot(x, "ID"))
map.tocut <- gIntersection(map.tocut, map.cutter, drop_lower_td = TRUE, byid = TRUE)
map.tocut <- spChFIDs(map.tocut, str_sub(sapply(slot(map.tocut, "polygons"), function(x) slot(x, "ID")), 1, -3))
temp <- temp[row.names(temp) %in% row.names(map.tocut),]
map.tocut <- SpatialPolygonsDataFrame(map.tocut, data=temp)

table(map.tocut$LAND)
plot(map.tocut[map.tocut$LAND == "20000",])
```

The plot from sf is as shown below. The "table" command shows 58 for value 19000 and 13 for 20000. For sp it's only 58 for value 19000 and the plot is empty as it should.
![Rplot](https://user-images.githubusercontent.com/100914509/156725664-5b192e39-75c2-4fc8-96ea-eaa30c0dc686.png)

Thanks a lot in advance for your help!

**Comment by rsbivand** [comment]
Provide `sf_extSoftVersion()` and `rgeos_extSoftVersion()`, with `sessionInfo()` output. GEOS is used by **sf** and **rgeos**, and has well-studied MakeValid functions, in general to be preferred to cleangeo. In fact, `st_buffer(map.tocut, dist=0)` on the input is sufficient. My guess is that at least `drop_lower_td = TRUE` is what is playing in here. Confirmed (I think) by (LAND is integer):

```
map.tocut <- read_sf(map.path)
map.tocut <- st_buffer(map.tocut, dist=0)
x <- map.tocut[map.tocut$LAND != 20000,]
map.cutter <- st_union(x)
map.tocut <- map.tocut[map.tocut$LAND %in% c(19000, 20000),]
map.tocut <- st_intersection(map.tocut, map.cutter)
map.tocut
table(st_dimension(map.tocut))
table(map.tocut[st_dimension(map.tocut) == 2,]$LAND)
plot(st_geometry(map.tocut[st_dimension(map.tocut) == 2,]))
```

**Comment by ecrjak** [comment]
Thanks a lot, this was very useful. Below is the output you requested. The issue persists also when using `st_buffer(map.tocut, dist=0)` as you recommended but I can now see that the redundant pieces all have dimension equal to 1. 

This suggests that I could just apply `map.tocut <- map.tocut[as.numeric(st_dimension(map.tocut)) > 1,]' to get the desired result. This is maybe not the most elegant version but do you see any issues with this approach?

sf_extSoftVersion()
```
   GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
      "3.9.1"        "3.2.1"        "7.2.1"         "true"                       "true"        "7.2.1" 
```

rgeos_extSoftVersion()
```
   GEOS OverlayNG        sp 
  "3.9.1"    "TRUE"   "1.4-6" 
```

sessionInfo()
```
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.4.0  sf_1.0-6       rgdal_1.5-28   cleangeo_0.2-4 maptools_1.1-2 rgeos_0.5-9    sp_1.4-6      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8         plyr_1.8.6         compiler_4.1.2     pillar_1.7.0       Rmisc_1.5          class_7.3-19      
 [7] tools_4.1.2        lifecycle_1.0.1    tibble_3.1.6       lattice_0.20-45    pkgconfig_2.0.3    rlang_1.0.1       
[13] DBI_1.1.2          cli_3.2.0          e1071_1.7-9        dplyr_1.0.8        generics_0.1.2     vctrs_0.3.8       
[19] classInt_0.4-3     grid_4.1.2         tidyselect_1.1.2   glue_1.6.2         R6_2.5.1           fansi_1.0.2       
[25] foreign_0.8-81     purrr_0.3.4        magrittr_2.0.2     ellipsis_0.3.2     units_0.8-0        KernSmooth_2.23-20
[31] utf8_1.2.2         proxy_0.4-26       stringi_1.7.6      lwgeom_0.2-8       crayon_1.5.0 
```

**Comment by rsbivand** [comment]
The argument you used to gIntersection() trimmed objects that were not polygons; sp objects cannot contain geometries of differing dimensions. However, sfc objects can be collections of geometries of different dimensions, so st_intersection can give the output you got. So using dt_dimension to choose just polygons makes sense for your purposes.

**Comment by tim-salabim** [comment]
There's also `st_collection_extract(x, "POLYGON")`

**Comment by ecrjak** [comment]
Thanks a lot to both of you. In the meantime, I encountered another, related issue when incorporating a second map, which is supposed to be identical in most parts apart from few polygon changes. Again, the output of `sf` produces slivers while `sp` does not. These are now actually polygons, so the previous solutions doesn't work anymore. I am attaching the additional shapefile here: **[German_Empire_1922_v.1.0.zip](https://github.com/r-spatial/sf/files/8196727/German_Empire_1922_v.1.0.zip)**

```
library(cleangeo)
library(rgdal)
library(sf)
library(sp)
library(stringr)


map.path <- paste0(datapath2, "/../GIS/german_empire_statistical_units_1871-1931/", 
                    "German Empire Statistical Units/German_Empire_1871_Stat_v.1.0.shp")
map.path2 <- paste0(datapath2, "/../GIS/german_empire_1871-1945/", 
                    "German Empire 1871-1945/German_Empire_1922_v.1.0.shp")


map.tocut <- read_sf(map.path)
map.cutter <- read_sf(map.path2)
map.cutter <- st_union(st_buffer(map.cutter[map.cutter$LAND != "20000",], dist=0))

map.tocut <- map.tocut[map.tocut$LAND %in% c("19000","20000"),]
map.tocut <- st_intersection(map.tocut, map.cutter)
map.tocut <- map.tocut[as.numeric(st_dimension(map.tocut)) > 1,]

table(map.tocut$LAND)
plot(st_geometry(map.tocut[map.tocut$LAND == "20000",]))



map.tocut <- readOGR(map.path)
map.cutter <- readOGR(map.path2)
map.cutter <- clgeo_Clean(gUnaryUnion(clgeo_Clean(map.cutter[map.cutter$LAND != "20000",])))

map.tocut <- map.tocut[map.tocut$LAND %in% c("19000","20000"),]

temp <- map.tocut@data
row.names(temp) <- sapply(slot(map.tocut, "polygons"), function(x) slot(x, "ID"))

map.tocut <- spTransform(map.tocut, proj4string(map.cutter))
map.tocut <- gIntersection(map.tocut, map.cutter, drop_lower_td = TRUE, byid = TRUE)
map.tocut <- spChFIDs(map.tocut, str_sub(sapply(slot(map.tocut, "polygons"), function(x) slot(x, "ID")), 1, -3))
temp <- temp[row.names(temp) %in% row.names(map.tocut),]
map.tocut <- SpatialPolygonsDataFrame(map.tocut, data=temp)

table(map.tocut$LAND)
plot(map.tocut[map.tocut$LAND == "20000",])
```

**Comment by edzer** [comment]
`rgeos` (sp) use a precision (scale) value of `1e8`, `sf` doesn't do that. Have you tried setting the same precision as rgeos? (`st_set_precision`) ?

**Comment by rsbivand** [comment]
Or check areas and subset:

```
> st_area(map.tocut)[which(st_area(map.tocut) < units::set_units(1, "m^2"))]
Units: [m^2]
[1] 1.322106e-05 4.821128e-06 0.000000e+00 7.501803e-07 0.000000e+00
[6] 0.000000e+00 0.000000e+00 1.381245e-05
```

**Comment by edzer** [comment]
>  I was wondering if this is something that may be improved in the future

We try to make progress, but somehow I have the feeling that problems like these will never entirely disappear.
