### ISSUE TITLE
st_write: add gpx as an automatically recognised format

### ISSUE THREAD

**Issue by pgiraudoux** [r-spatial/sf#1917]
Using st_write, gpx is not recognised automatically yet. See https://github.com/r-spatial/sf/blob/ddc79d0e9b7f7500a6d6020964b180cd4064bc83/R/read.R#L670-L695
However, with the argument driver = "GPX" explicit, the file is written correctly.
May I suggest to add it among the automatically recognised format since this file format is quite popular among people using GPS?
Best,
Patrick

**Comment by edzer** [comment]
Thanks!

**Comment by pgiraudoux** [comment]
Will feel better in mountain bike and trekking now.. 😂😂. Thanks to you Edzer... sf is really excellent...
