### ISSUE TITLE
Feature request.  Could you add support for gdaladdo (add overviews) to gdal_utils() ?

### ISSUE THREAD

**Issue by ethanplunkett** [r-spatial/sf#1921]
You now support all the gdal utilities that I use except for gdaladdo.  It would be great to not need  another installed gdal  just for that one utility. 

https://gdal.org/programs/gdaladdo.html

Thanks for the awesome package!

**Comment by edzer** [comment]
Yes, nice one. However, it doesn't fit in the function profile of `gdal_utils()`, it needs specifications of bands and layers, so is a new thing really, in terms of API.

**Comment by edzer** [comment]
There you go!

**Comment by ethanplunkett** [comment]
Wow.  That was quick. Thank you!
