### ISSUE TITLE
 Documentation typo in st_nearest_feature

### ISSUE THREAD

**Issue by barryrowlingson** [r-spatial/sf#1922]
Backslash missing: `code{x}` should be `\code{x}`:

https://github.com/r-spatial/sf/blob/5dde39c8261dc6b202e6cde9d41ad3bf0f46aa3a/R/nearest.R#L73

I wondered what "codex" was...

       y: object of class ‘sfg’, ‘sfc’ or ‘sf’; if missing, features in
          codex will be compared to all remaining features in ‘x’.

**Comment by edzer** [comment]
Thanks, Barry!
