### ISSUE TITLE
GEOJSON export creates geometries non-conform to d3-geo requirements 

### ISSUE THREAD

**Issue by aourednik** [r-spatial/sf#1923]
**Describe the bug**

When exporting with `st_write(geodata,geojson)`, the GEOJSON geometries are not valid in the context of a d3-geo framework. See example of [rendering problem](https://github.com/aourednik/historical-basemaps/issues/18).

**To Reproduce**

```r
require(sf)
require(magrittr)
geodata <- st_read("path/to/geodata.gpkg") # multipolygons with holes
geodata <- geodata %>% st_transform(crs=4326, check=T)
st_write(geodata,"path/to/new/geodata.geojson")
```

The resulting geojson can have a [rendering problem](https://github.com/aourednik/historical-basemaps/issues/18) with d3-geo.

**Additional context**

The problem can be solved by repairing faulty geometries with the javascript algorithm below (`normalizeWindingOrder` and `normalizePolygon`). Could this repair routine be ported to R and integrated directly into `st_write()`when exporting to geojson ?

System call from R : 

```r
geojson <- "path/to/new/geodata.geojson"
system(paste("/opt/homebrew/bin/node repair_geometries.js --file",geojson))
```

Content of repair_geometries.js : 

```javascript
// yarn add d3
// yarn add d3-geo

let d3 = {};
runapp();

async function runapp(){
  const fs = require('fs');
  d3 = await Promise.all([
    import("d3"),
    import("d3-geo")
  ]).then(d => Object.assign({}, ...d));
  let currentMapFile = process.argv[3];
  let data = fs.readFileSync(currentMapFile);
  data = JSON.parse(data);
  console.log(data);
  data.features = data.features.map(dat => normalizeWindingOrder(dat));
  fs.writeFileSync( currentMapFile, JSON.stringify(data));
}

function normalizeWindingOrder(geo) {
  switch (geo.type) {
    case "FeatureCollection":
      geo.features.forEach(normalizeWindingOrder);
      return geo;
    case "Feature":
      normalizeWindingOrder(geo.geometry);
      return geo;
    case "GeometryCollection":
      normalizeWindingOrder(geo.geometries);
      return geo;
    case "MultiPolygon":
      geo.coordinates.forEach(normalizePolygon);
      return geo;
    case "Polygon":
      normalizePolygon(geo.coordinates);
      return geo;
  }
  return geo;

  function normalizePolygon(coordinates) {
    coordinates.forEach((ring) =>
      ring.forEach((p) => {
        if (Math.abs(p[1]) > 90) p[1] = 90 * Math.sign(p[1]);
      })
    );
    coordinates.forEach(
      (ring, i) =>
        (d3.geoArea({ type: "Polygon", coordinates: [ring] }) >= 2 * Math.PI) ^
          !!i && ring.reverse()
    );
  }
}
```

<details>
sessionInfo()

R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.3

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_1.0-7

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3       rstudioapi_0.13    magrittr_2.0.2     units_0.8-0        tidyselect_1.1.2  
 [6] R6_2.5.1           rlang_1.0.2        fansi_1.0.2        dplyr_1.0.8        tools_4.1.2       
[11] grid_4.1.2         KernSmooth_2.23-20 utf8_1.2.2         cli_3.2.0          e1071_1.7-9       
[16] DBI_1.1.2          ellipsis_0.3.2     class_7.3-20       tibble_3.1.6       lifecycle_1.0.1   
[21] crayon_1.5.0       purrr_0.3.4        vctrs_0.3.8        glue_1.6.2         proxy_0.4-26      
[26] compiler_4.1.2     pillar_1.7.0       generics_0.1.2     classInt_0.4-3     pkgconfig_2.0.3   

sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
       "3.9.1"        "3.2.3"        "7.2.1"         "true"         "true"        "7.2.1" 
</details>

**Comment by edzer** [comment]
> `geodata <- st_read("path/to/geodata.gpkg") # multipolygons with holes`

That is now what we mean when we say "minimal reproducible example". 

`st_read` has an argument `check_ring_dir` that can be set to repair polygons with "wrong" ring directions (whatever that means, esp. with geodetic coordinates), otherwise there is an `st_make_valid()` that does all kind of things, for geodetic coordinates also depending on whether `sf_use_s2()` is TRUE or FALSE.
