### ISSUE TITLE
st_write() drops times for tracks

### ISSUE THREAD

**Issue by millermc38** [r-spatial/sf#1924]
**Describe the bug**
st_write() does not write out the times when using KML as the driver

**To Reproduce**
Please see this stack post I unsuccessfully put a bounty on: 
https://stackoverflow.com/questions/71533176/can-r-convert-gpx-files-to-kml-files

Session Information:

R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.1.3 tools_4.1.3 

          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
       "3.9.1"        "3.2.1"        "7.2.1"         "true"         "true"        "7.2.1"

**Comment by edzer** [comment]
If `vectortranslate` or `ogr2ogr` cannot do it, I don't see why or how `sf` would be able to do it, or why this would be a bug in `sf`.

**Comment by millermc38** [comment]
I don't have a great understanding of the ecosystem that supports `sf`, so I thought this would be the right place, but I see now that `sf` relies on a lot of other tools. This would be a gdalUtils bug/feature request then? We can close this out here...

**Comment by edzer** [comment]
I don't think gdalUtils can do much more than `sf::gdal_utils()`. @agila5 is clearly deeper into this, but my feeling is that your tracks data model doesn't map well onto the GDAL/OGR simple feature model.

**Comment by agila5** [comment]
Hi @millermc38! As I already said on SO, I have a very limited experience with GPX/KML files, so I cannot add much more that what I've already written there. I also don't understand what is the expected output in this case (but please ignore the following if that doesn't make any sense). 

I think that the structure of the GPX data you shared can be summarised as follows: there is 1 track composed by one segment which is also composed by 3 (ordered) points. Each point has a different time/elevation field. How can you map those 3 values to a unique time/elevation for the corresponding MULTILINESTRING object?

**Comment by agila5** [comment]
Hi @millermc38! I read some docs online that explain the key features of GPX and KML data, but still I have no idea how to solve your problem. You may want to check the [GPX](https://gdal.org/drivers/vector/gpx.html) and [KML](https://gdal.org/drivers/vector/libkml.html) drivers webpage on GDAL website and see if there is any option that may help during the conversion of (I didn't find any). I just copy here one note from KML webpage: 

> Libkml from Google provides reading services for any valid KML file. However, please be advised that some KML facilities do not map into the Simple Features specification OGR uses as its internal structure. Therefore, a best effort will be made by the driver to understand the content of a KML file read by libkml into ogr, but your mileage may vary. Please try a few KML files as samples to get a sense of what is understood. In particular, nesting of feature sets more than one deep will be flattened to support ogr’s internal format.

**Comment by millermc38** [comment]
I'm coming the the same conclusion. Thanks to both of you for your thoughts! I'll close this out now.
