### ISSUE TITLE
Simple move operation, coordinate direction

### ISSUE THREAD

**Issue by gaberunte** [r-spatial/sf#1929]
I apologize if I have missed this on an existing thread, but I am hoping for a very simple operation that takes a "sfc_POINT" object and allows me to move it X meters in Y coordinate direction while retaining the "sfc_POINT" class. Thank you in advance!

**Comment by edzer** [comment]
```r
library(sf)
# Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE
pts = st_sfc(st_point(c(0,0)), st_point(c(2,3)))
x = 10 # metres
pts + c(0, x)
# Geometry set for 2 features 
# Geometry type: POINT
# Dimension:     XY
# Bounding box:  xmin: 0 ymin: 10 xmax: 2 ymax: 13
# CRS:           NA
# POINT (0 10)
# POINT (2 13)
```

**Comment by gaberunte** [comment]
Thank you for the rapid reply!
The rest, I assume, will just be some reasonably basic trigonometry.

**Comment by edzer** [comment]
What do you mean by "the rest"?

**Comment by gaberunte** [comment]
The easiest possible function I could imagine would accept a sfc_point object, a direction in degrees and a distance in meters. The output, ideally, would be a new sfc_point object. 

But I think this can be computed with something like:
pts + c(Distance*sin(Heading), Distance*cos(Heading))

Where Distance is divided by meters/degree and Heading is the corrected compass direction of the move. There are issues such as the changing meters/degree with latitude and the heading needing correction since North is zero rather than the x-axis being zero.

**Comment by edzer** [comment]
Ah, I see. Yes, that could work.
