### ISSUE TITLE
accessing shapefiles within s3 buckets

### ISSUE THREAD

**Issue by coverton-usgs** [r-spatial/sf#1935]
I can't load my aws stored files.

Is there a format or expression that is required to use st_read within Rstudio in an EC2 when accessing an s3 bucket?  Something like the 
`read.csv(text = rawToChar(aws.s3::get_object(s3_object, s3_bucket)` required for text files?

**Comment by edzer** [comment]
You may want to look into prefixing your datasource name with `/vsis3/` , see [here](https://gdal.org/user/virtual_file_systems.html).
