### ISSUE TITLE
Assigning the overlap between polygons to the nearest polygon does not really remove the overlap

### ISSUE THREAD

**Issue by fgoerlich** [r-spatial/sf#1936]
Taking the example from this [stackexchange question](https://gis.stackexchange.com/questions/358797/splitting-overlap-between-polygons-and-assign-to-nearest-polygon-using-r) and his `st_no_overlap` function:

```
st_no_overlap <- function(polygons) {

  centroids <- st_centroid(polygons)

  # Voronoi tesselation
  voronoi <-
    centroids %>%
    st_geometry() %>%
    st_union() %>%
    st_voronoi() %>%
    st_collection_extract()

  # Put them back in their original order
  voronoi <- voronoi[unlist(st_intersects(centroids, voronoi))]

  # Keep the attributes
  result <- centroids

  # Intersect voronoi zones with polygons
  st_geometry(result) <-
    mapply(function(x, y) st_intersection(x, y),
           st_geometry(polygons),
           voronoi,
           SIMPLIFY = FALSE) %>%
    st_sfc(crs = st_crs(polygons))

  result
}
```
I run his example,
```
pol <- st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,1), c(0,0))))
b   <- st_sfc(pol, pol + c(.8, .2), pol + c(.2, .8))
cl = sf.colors(3, categorical = TRUE)

plot(st_no_overlap(st_sf(geometry = b)), col = cl)
```
and get the same nice picture without overlaping.

![image](https://user-images.githubusercontent.com/6486324/165585894-35995943-a10a-4281-8665-000b86d56673.png)

but this is only in the picture. If I check for overlapping with `st_overlaps`, I get that the polygons indeed overlap!

```
st_overlaps(st_no_overlap(st_sf(geometry = b)))
Sparse geometry binary predicate list of length 3, where the predicate was `overlaps'
 1: 2, 3
 2: 1
 3: 1
```
The same happens with the `st_buffer_without_overlap` function mentioned in [#824](https://github.com/r-spatial/sf/issues/824#issuecomment-414805992), so I am not sure if this has to do with the geometrical operations done in the functions (voronoi, intersections,...) o with the slivers mentioned in #547.

Is there a general way to prevent this behaviour or at least to solve it? Thanks!

**Comment by edzer** [comment]
A consequence of not setting a precision:
```r
> st_overlaps(st_set_precision(st_no_overlap(st_sf(geometry = b)),1e8))
Sparse geometry binary predicate list of length 3, where the predicate
was `overlaps'
 1: (empty)
 2: (empty)
 3: (empty)
```
