### ISSUE TITLE
lazy loading failed for package 'sf'

### ISSUE THREAD

**Issue by pawan1198** [r-spatial/sf#1937]
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/pawan/R/x86_64-pc-linux-gnu-library/4.1/units/libs/units.so':
  libudunits2.so.0: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘sf’
* removing ‘/home/pawan/R/x86_64-pc-linux-gnu-library/4.1/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpqk1VHG/downloaded_packages’

**Comment by edzer** [comment]
You may have to reinstall package `units`

**Comment by pawan1198** [comment]
Thanks a lot

**Comment by johnsCheng** [comment]
Just btw, 
I have the same installation error said "lazy loading failed"
```
make: Nothing to be done for 'all'. 
installing to /zhanglab/home/jinghui/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-sf/00new/sf/libs 
** R ** demo ** inst ** byte-compile and prepare package for lazy loading *** 
Error in `/software/R4/R-4.0.3/build_dir_share/lib64/R/bin/exec/R': free(): invalid pointer: 0x0000000003f2a688 
*** ======= Backtrace: =========
```
blablabla,
then shows core dumped without any specific file or package dependency.
Once I saw this answer above, I know that could be the case.
I update my gcc few days ago, And I choose skipping to update packages when I tried to install a new one ( just thought it could be less conflicts)
So, I select the packages like 

> units
here to update before installing the 

> sf from source code or github , and it worked!
