### ISSUE TITLE
st_write changes column names

### ISSUE THREAD

**Issue by Saadi4469** [r-spatial/sf#1940]
Hello, I am writing an `sf object` to a `shapefile` using `st_write`. The output is fine, it's just that the shapefile now has `different` column `names` than the original. It basically shortens the column name, for example, `low_depth_002_year00` is changed to `l__002_`. 

How can I write a shapefile in such a way that the original column names are retained?

**Comment by edzer** [comment]
See https://gdal.org/drivers/vector/shapefile.html: 

> Attribute names can only be up to 10 characters long.

If you need longer names, use GeoPackage.
