### ISSUE TITLE
Evaluation error: Found 13 features with invalid spherical geometry.  Loop 37 is not valid: Edge 0 has duplicate vertex with edge 8

### ISSUE THREAD

**Issue by jiepingy** [r-spatial/sf#1943]
Hi, I am using the flicker API to get the photo, and I faced some problems with the code in R. Here is my code and the error. Thanks, if anyone could help, I will appreciate it a lot.

<img width="578" alt="截屏2022-05-13 00 44 48" src="https://user-images.githubusercontent.com/101899593/168126745-adc5e59a-706e-46ce-a2d7-ba98e972f763.png">
<img width="574" alt="截屏2022-05-13 00 44 58" src="https://user-images.githubusercontent.com/101899593/168127024-fdfed339-a080-49f8-b5ca-a44049f66383.png">

If you need any datasets from me, please feel free to ask.

**Comment by kadyb** [comment]
Try to turn off the spherical geometry engine as workaround: `sf_use_s2(FALSE)`; or transform the coordinate system to plannar: `st_transform()`.

**Comment by edzer** [comment]
Could you specify "would not work"? I downloaded the map you point to, which obviously is not valid on S2, but `st_make_valid()` makes it valid without issue.
