### ISSUE TITLE
geos::geos_minimum_rotated_rectangle equivalent

### ISSUE THREAD

**Issue by scoddou** [r-spatial/sf#1953]
**Describe the bug**
Was wondering if `sf` will ever have an equivalent to `geos::geos_minimum_rotated_rectangle`, but in the process found the results from `geos` were not *always* as expected

**To Reproduce**

```R
library(sf)
library(geos)
library(ggplot2)

# function to calc min rotated bbox
minimum.rotated.bbox = function (x) {
  
  # calc convex hull, centroid and associated edge points
  hull = st_convex_hull(st_union(x))
  hull.centroid = st_centroid(hull)
  coords = st_coordinates(hull)
  
  # generate the edge vectors between convex hull coords
  x1 = head(coords[,1],-1); x2 = tail(coords[,1],-1)
  y1 = head(coords[,2],-1); y2 = tail(coords[,2],-1) 
  dx = x2 - x1; dy = y2 - y1
  
  # function to calculate bbox aligned to each convex hull edge
  oriented.bbox = function(hull,hull.centroid,dx,dy){
    
    bbox.area = st_area(st_as_sfc(st_bbox(hull)))
    
    # to delete
    holder = st_sf(area=rep(NA,length(dx)),geometry=rep(st_sfc(st_geometrycollection()),length(dx)))
    
      for (i in 1:length(dx)) {
        
          # calc direction vector for each side of convex hull
          magnitude = sqrt(dx[i]**2 + dy[i]**2)
          ux = dx[i] / magnitude; uy = dy[i] / magnitude
          
          # re-orient hull to current side being analyzed, generate bbox 
          hull.bbox = st_as_sfc(st_bbox((hull - hull.centroid) * matrix(c(ux,uy,-uy,ux),2,2) + hull.centroid))[[1]]
          hull.bbox.area = st_area(hull.bbox)
          
          # uncomment
          #if (hull.bbox.area<bbox.area) {bbox.area=hull.bbox.area; bbox = hull.bbox; uxf=ux ; uyf=uy}
          
          # to delete 
          holder$area[i]=hull.bbox.area
          holder$geometry[i]=(hull.bbox - hull.centroid) * matrix(c(ux,-uy,uy,ux),2,2) + hull.centroid
          
      }
      # uncomment
      #(bbox - hull.centroid) * matrix(c(uxf,-uyf,uyf,uxf),2,2) + hull.centroid
      
      # to delete
      holder
  }
  oriented.bbox(hull,hull.centroid,dx,dy)
}

#initialize points and hull
points = st_multipoint(matrix(rnorm(100, mean=10, sd=5),ncol=2))
hull = st_convex_hull(points)

#function test
bbox = minimum.rotated.bbox(points)

#geos test
geos.bbox = st_as_sfc(geos_minimum_rotated_rectangle(st_sfc(points)))[[1]]
geos.area = st_area(geos.bbox)

#output
bbox
writeLines(paste0("\n\n\n GEOS output area: ",geos.area))
#ggplot(st_sfc(list(points,hull,bbox))) + geom_sf(fill=NA)
ggplot(st_sfc(list(points,hull,bbox$geometry[bbox$area==min(bbox$area)][[1]]))) + geom_sf(fill=NA) 
ggplot(st_sfc(list(points,hull,geos.bbox))) + geom_sf(fill=NA)
```
```R
Simple feature collection with 8 features and 1 field
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -5.541727 ymin: -4.908192 xmax: 26.41156 ymax: 28.19019
CRS:           NA
      area                       geometry
1 540.7856 POLYGON ((26.41156 7.126129...
2 436.4733 POLYGON ((22.05467 3.507135...
3 498.6377 POLYGON ((21.17651 -0.77293...
4 526.6993 POLYGON ((20.30409 -2.72817...
5 435.6293 POLYGON ((4.791 -1.635778, ...
6 455.1381 POLYGON ((-3.891192 19.4175...
7 459.7069 POLYGON ((-0.08799392 23.99...
8 433.7233 POLYGON ((15.68688 26.59675...



 GEOS output area: 459.706879291801
```

:triangular_flag_on_post:***Notice `geos::geos_minimum_rotated_rectangle` area is not the minimum area according the the custom function***

`minimum.rotated.bbox` output:
![image](https://user-images.githubusercontent.com/97531714/171974572-6727759a-efd9-47c3-8551-dd21f84756de.png)

`geos::geos_minimum_rotated_rectangle` output:
![image](https://user-images.githubusercontent.com/97531714/171974577-475da9e7-eb81-4427-891a-44bb6b09a2c1.png)

**Additional context**
Curious if my implementation of @shapely's `minimum_rotated_rectangle` is correct, and if `sf` will provide `geos::geos_minimum_rotated_rectangle` as `sf::st_minimum_rotated_rectangle` or otherwise in the future

Also, I apologize if this post is not formatted to the standard...this is only my second post on github :smile: 

<details>
sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] geos_0.1.3      ggplot2_3.3.5   lwgeom_0.2-8    sfheaders_0.4.0 sf_1.0-7       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3       compiler_4.1.1     pillar_1.7.0       libgeos_3.10.0-1   class_7.3-19       tools_4.1.1        odbc_1.3.3        
 [8] digest_0.6.29      bit_4.0.4          gtable_0.3.0       evaluate_0.15      lifecycle_1.0.1    tibble_3.1.6       pkgconfig_2.0.3   
[15] rlang_1.0.2        DBI_1.1.2          cli_3.2.0          yaml_2.3.5         xfun_0.30          fastmap_1.1.0      e1071_1.7-9       
[22] withr_2.5.0        dplyr_1.0.8        knitr_1.37         generics_0.1.2     vctrs_0.3.8        hms_1.1.1          tidyselect_1.1.2  
[29] classInt_0.4-3     bit64_4.0.5        grid_4.1.1         glue_1.6.2         R6_2.5.1           fansi_1.0.2        rmarkdown_2.13    
[36] farver_2.1.0       purrr_0.3.4        blob_1.2.2         magrittr_2.0.2     scales_1.1.1       ellipsis_0.3.2     htmltools_0.5.2   
[43] units_0.8-0        assertthat_0.2.1   colorspace_2.0-3   KernSmooth_2.23-20 utf8_1.2.2         proxy_0.4-26       wk_0.6.0          
[50] munsell_0.5.0      crayon_1.5.0 

sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
       "3.9.1"        "3.2.1"        "7.2.1"         "true"         "true"        "7.2.1" 
</details>

**Comment by edzer** [comment]
Your post is formatted well, but doesn't address an issue with `sf` (except, indirectly, a feature request). R package geos also doesn't implement the function you address, but the [GEOS library](https://github.com/libgeos/geos) does. Maybe post it in one of these two places?

**Comment by rsbivand** [comment]
**rgeos** exposes `gMinumumRotatedRectangle()`:
```
library(rgeos)
set.seed(1) # the example should set the seed
m <- matrix(rnorm(100, mean=10, sd=5),ncol=2)
pts_sp <- SpatialPoints(m)
mrr <- gMinumumRotatedRectangle(pts_sp)
plot(mrr)
points(pts_sp)
```
so **sf** could too. There have been recent bug-fixes, so a recent `GEOS` should be preferred. `shapely` also uses `GEOS`, so differences are likely to be from different `GEOS` versions with incrementally improved heuristics. My `GEOS` 3.10.2, 3.10.3 released yesterda but not yet tried; has fixes for suboptimal heuristics in this operation based on JTS.

**Comment by scoddou** [comment]
My apologies @edzer, I was ultimately wondering if the same functionality could be exposed in `sf`. But before considering exposing it, I just wanted to point out I was getting different answers from `geos::geos_minimum_rotated_rectangle` compared to my custom function...

@rsbivand, thank you for the follow-up (and tip on seeding). I am indeed getting the same results from `rgeos` and `geos` on `set.seed(1)`, with both returning the incorrect rectangle compared to my custom function that was based on `shapely`. I am not sure how to update my `GEOS` linking, but to your point, that might be the problem.

Let me know if you would like for me to close here. It sounds like even if `sf` exposed this function, I personally might still run into the same issue due to my `GEOS` linking. But still interested to see it added as a new feature!

**Comment by edzer** [comment]
```r
set.seed(1) # the example should set the seed
m <- matrix(rnorm(100, mean=10, sd=5),ncol=2)
library(sf)
# Linking to GEOS 3.10.2, GDAL 3.4.3, PROJ 8.2.0; sf_use_s2() is TRUE
setNames(as.data.frame(m), c("x", "y")) |> st_as_sf(coords = c("x", "y")) |> st_geometry() -> pts
st_combine(pts) |> st_minimum_rotated_rectangle() |> plot()
plot(pts, add = TRUE)
```
![x](https://user-images.githubusercontent.com/520851/175032397-caa42590-b2e7-4451-b646-c2e316324ce0.png)

**Comment by scoddou** [comment]
Much appreciated!
