### ISSUE TITLE
st_is_valid returns NA instead of FALSE for closed 2 coordinates polygons

### ISSUE THREAD

**Issue by Jean-Romain** [r-spatial/sf#1954]
`st_is_valid` returns `NA` instead of `FALSE` for 2 nodes closed polygons which may lead to troubleshooting in subsequent test. 

```r
library(sf)
M = matrix(c(0, 0, 0, 0), 2, 2)
P = st_polygon(list(M))
P = st_sfc(P)
st_is_valid(P)
#> NA
```

Related: it is possible to build an invalid non closing 2 nodes polygon without error while it is not possible with 3 or more nodes. But, if not closed, `st_is valid()` returns `FALSE` properly.

```r
M = matrix(c(0, 0, 2, 1), 2, 2)
P = st_polygon(list(M))
P = st_sfc(P)
st_is_valid(P)
#> FALSE

M = matrix(c(0, 0, 1, 1, 2, 2), 3, 2)
P = st_polygon(list(M))
#> Erreur dans MtrxSet(x, dim, type = "POLYGON", needClosed = TRUE) : 
#>  polygons not (all) closed
```

**Comment by edzer** [comment]
Regarding your first point, the `NA` is there to catch error polygons, you can get the error raised by
```
> st_is_valid(P, NA_on_exception=FALSE)
Error in CPL_geos_is_valid(x, as.logical(NA_on_exception)) : 
  Evaluation error: IllegalArgumentException: Invalid number of points in LinearRing found 2 - must be 0 or >= 4.
```

**Comment by Jean-Romain** [comment]
I understand that you are aware of that and it is not a bug but a feature. With that in mind the documentation is actually clear on the topic.

On my side I was expecting `st_is_valid` to answer `TRUE`/`FALSE` in all cases and never `NA` otherwise we always need additional specific code to handle `NA`s when analyzing the output of `st_is_valid`.  If it returns FALSE it already means there is an error and that the polygon must be checked. Anyway it is documented and known so it is on my side to handle the `NA` cases.

**Comment by edzer** [comment]
The word `valid` has a restricted meaning: invalid polygons can be made valid. Your `P` is valid nor invalid: its wrong; `st_make_vald()` will not be able to make it valid.

**Comment by Jean-Romain** [comment]
But a two node polygons should always return NA right. There is no way to make it valid right?

**Comment by edzer** [comment]
> But a two node polygons should always return NA right? There is no way to make it valid right?

right; I'd agree that it is not very helpful behavior that `st_polygon` doesn't error on it, but I don't think `st_polygon()` is used much in real work.

**Comment by Jean-Romain** [comment]
Maybe but in this case `st_is_valid` should return `NA` not `FALSE` in

```r
M = matrix(c(0, 0, 2, 1), 2, 2)
P = st_polygon(list(M))
P = st_sfc(P)
st_is_valid(P)
```

I'm using `st_polygon` or `st_linestring` very often to build shapes compatible with R geospatial ecosystem and I think I'm doing real work :wink:. I found these edge cases when computing concave hulls of point sets that includes limits case with 4 aligned points. The problem was silently ignored until it generated troubles later. But this is now handled in my code.

**Comment by Jean-Romain** [comment]
Ok I made some mess somewhere when writing this report...
