### ISSUE TITLE
Error when loading sf package 

### ISSUE THREAD

**Issue by glenncampagna** [r-spatial/sf#1960]
install.packages("sf")
library(sf)

library(dplyr)
library(sf)
library(ggplot2)
library(ggspatial)

Error: "Error: package or namespace load failed for ‘sf’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘classInt’"

**Comment by Nowosad** [comment]
Have you tried to install the `classInt` package?

**Comment by glenncampagna** [comment]
that worked, thank you
