### ISSUE TITLE
st_cast fails when casting empty GEOMETRYCOLLECTION geometries to MULTIPOLYGON

### ISSUE THREAD

**Issue by botanize** [r-spatial/sf#1961]
**Describe the bug**
It seems like st_cast should be able to cast empty geometries of any type to MULTIPOLYGON, but instead I get this:

```r
st_cast(st_sfc(st_geometrycollection(), st_multipolygon()), 'MULTIPOLYGON')
>Error in x[[1]] : subscript out of bounds
```

What does work is casting an empty polygon to multipolygon:

```r
st_cast(st_sfc(st_polygon(), st_multipolygon()), 'MULTIPOLYGON')
```

It looks like the problem is that [the code is asking for the first element of the geometry collection](https://github.com/r-spatial/sf/blob/4f550e55c497789ddccd31599050344ea32882d8/R/cast_sfg.R#L199), but the list is empty.

See issues #1767 and  #1094.

**Comment by edzer** [comment]
Thanks, should work now!
