### ISSUE TITLE
st_bbox() inconsistent with edited sf object coordinates

### ISSUE THREAD

**Issue by jmw86069** [r-spatial/sf#1965]
**Describe the bug**
I am transitioning from `sp` to `sf`, please excuse the noob question. :)
`st_bbox()` appears inconsistent/incorrect on `sf` when internal `st_geometry()` has been modified.

**To Reproduce**
I am using affine transformations (addition, multiplication, as you described), to move a polygon. I notice it updates the bbox for the polygon, but not for the `sf` object when it is an entry in that object.
Create a simple two-polygon `sf` object to reproduce:
```R
p1 <- st_polygon(list(cbind(
   x=c(3, 4, 3, 2, 3),
   y=c(3, 2, 1, 2, 3))))
p1p2 <- sf::st_sf(
   geometry=sf::st_sfc(list(p1, p1)),
   row.names=letters[1:2])
data.frame(p1p2)
#>                         geometry
#> a POLYGON ((3 3, 4 2, 3 1, 2 ...
#> b POLYGON ((3 13, 4 12, 3 11,...
```
Move one polygon to the right via `st_geometry()`:
```R
# move one polygon to the right
st_geometry(p1p2[2,]) <- st_geometry(p1p2[2,]) + c(0, 10)

# st_bbox() is not updated
st_bbox(p1p2)
#> xmin ymin xmax ymax 
#>   2    1    4    3

# st_bbox() on the sequence of rows shows the updated range
st_bbox(p1p2[1:2, ])
#> xmin ymin xmax ymax 
#>   2    1    4   13
```

1. Is there a method to update the bbox?
2. Is there a better way to adjust coordinates in an `sf` object?
```R
attr(p1p2[["geometry"]], "bbox")
#> xmin ymin xmax ymax
#>    2    1    4    3
attr(p1p2[1:2,][["geometry"]], "bbox")
#> xmin ymin xmax ymax
#>    2    1    4   13

# this?? :)
attr(p1p2[["geometry"]], "bbox") <- attr(p1p2[1:2,][["geometry"]], "bbox")
```

Thank you for the hard work on creating this package, and thank you for the help!

<details>

**sessionInfo()**:
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] sf_1.0-5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8         magrittr_2.0.2     units_0.7-2        tidyselect_1.1.1   R6_2.5.1           rlang_1.0.0        fansi_1.0.2        dplyr_1.0.7        tools_3.6.1        grid_3.6.1         KernSmooth_2.23-15 utf8_1.2.2
[13] cli_3.1.1          e1071_1.7-4        DBI_1.1.2          ellipsis_0.3.2     class_7.3-15       tibble_3.1.6       lifecycle_1.0.1    crayon_1.5.1       purrr_0.3.4        vctrs_0.3.8        glue_1.6.1         compiler_3.6.1
[25] pillar_1.7.0       generics_0.1.1     classInt_0.4-3     pkgconfig_2.0.3

**sf::sf_extSoftVersion()**:
```
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ
       "3.7.2"        "2.4.2"        "5.2.0"        "false"        "false"        "5.2.0"
```

</details>

**Comment by edzer** [comment]
Thanks! That should work now.

**Comment by edzer** [comment]
> Is there a method to update the bbox?

`st_sfc()` now has an parameter `compute_bbox` that, when set to TRUE, recomputes the bounding box. You shouldn't have to use that, though.

**Comment by jmw86069** [comment]
Confirmed! Thanks so much!

```R
st_bbox(p1p2[1:2, ])
#> xmin ymin xmax ymax
#>    2    1    4   13
```

A bit of a learning curve transitioning to `sf` which is understandable. I like it a lot so far, most things being in a `data.frame`.

My use of `sf` is mostly for geometry-related functions. It seems that most workflows are intended for maps that have "fixed" coordinates. Moving polygons around, possibly rotating and rescaling them, does not seem as common in a map context. It seems straightforward to do, hopefully goes smoothly from here out. Definitely nice to have some `rgeos` and `maptools` functions already included in `sf`. :)

Thank you!
