### ISSUE TITLE
R crash when reading a postgresql table or query

### ISSUE THREAD

**Issue by SIGDREALOCCITANIE** [r-spatial/sf#1967]
Hi,

I am looking to query a postgresql/postgis database to feed a tmap component. To simplify the development, I first launch my connection on a local database, to call a multipolygon layer in the "Public" schema.

Each time I launch the query R crashes without giving me any reason. The only message is "R encoutered a fatal error".

I don't know how to solve this problem, especially since my code was working some time ago with a version prior to R.

My code :

```r
library(sf)
library(RPostgreSQL)

pg = dbDriver("PostgreSQL")
conn = dbConnect(pg, user="******", password="*****",
                 host="localhost", port=5432, dbname="bd_dpch_dev", )
query <- paste('SELECT * FROM dept_adm_r76ext;')
limdep <- read_sf(conn,query=query,quiet=TRUE)
data(limdep)
```

The crash occurs on read_sf

I try also a syntax stolen on some example :

```r 
library(sf)
library(RPostgreSQL)
try(conn <- dbConnect(PostgreSQL(), dbname = "bd_dpch_dev",user="****", password="*****"))
if (exists("conn") && !inherits(conn, "try-error")) {
  x = st_read(conn, "dept", query = "select * from dept_adm_r76ext limit 3;")
  x = st_read(conn, table = "dept_adm_r76ext")
  print(st_crs(x)) # SRID resolved by the database, not by GDAL!
  dbDisconnect(conn)
 }
}
```
... With sadly the same problem

What can i change to make it work again ? I a newbie on R but a few months ago, my code worked correctly, I certainly makes a mistake...
Thanks a lot for your help

My env :
- R 4.2.1 windows 10
- sf 1.0.7
- postgresql 13.7 / postgis 3.2.1

Jerome Caba

**Comment by markolipka** [comment]
Probably related:

Connection to my PostGIS DB via

'''
con <- "PG:host=*** dbname=alkis user=user password=***

st_read(con, layer = "ax_flurstueck")
'''

- Worked with R 4.0.2 under windows 10

- Still Works with R 4.2.1 under macOS

- But fails with R 4.2.1 under windows 10

Error: Cannot open "PG:host=*** ..."; Check connection parameters.

**Comment by SIGDREALOCCITANIE** [comment]
Thanks a lot Markolipka, i downgraded to my old version (4.0.5) and it works too. I'll wait a little for a new upgrade

**Comment by edzer** [comment]
@etiennebr any idea?

**Comment by etiennebr** [comment]
Would you be able to share the `traceback()` of the error? I don't have access to a Windows machine right now, so it's hard to tell, but I'd be happy to look into it if you could provide a bit more details on the error.

Could you also try the following queries:
```r
read_sf(conn, query = "select 1")
```

```r
read_sf(conn, query = "select 'POINT(1 1)'::geography")
```

**Comment by geo-jd** [comment]
I had the same problem. It would seem that `dbDriver()` has been depreciated since 2017 [DBI 0.6 (2017-03-08)] . See https://dbi.r-dbi.org/news/ 

Using `pg =  RPostgres::Postgres()` should solve the problem (it did for me). There is also a thread on StackOverflow dealing with a simialr problem offering the same solution [(https://stackoverflow.com/questions/44401454/r-postgres-connection-to-remote-survey-error-in-rs-dbi-driver)]

Possibly interesting tidbit:
dbplyr actually gives a warning about outdated code when using DBI's `dbDriver()` function.

**Comment by etiennebr** [comment]
Ah interesting, thanks for sharing! I suggest opening an issue on the DBI side so they can add a deprecation warning to `dbDriver()`.
