### ISSUE TITLE
Support for circularstring and other rarer WKT formats

### ISSUE THREAD

**Issue by swooping-magpie** [r-spatial/sf#1974]
Hey guys,
Love the work,
Just wanted to confirm that we don't handle intersection and area for circularstring and other rarer WKT formats within the sf library natively (as in we need to linearise first). This might be because GEOS itself doesn't handle it? Do you know whether GEOS is looking to eventually support that feature or whether there exists other open source geometry libraries out there that do? Does the SF team plan to support operations like intersection and area natively for circular string

**Comment by edzer** [comment]
Yes, no, no.

**Comment by swooping-magpie** [comment]
Brilliant thanks
