### ISSUE TITLE
cannot install sf package ; Macbook  Big Sur 11.4

### ISSUE THREAD

**Issue by pubpolicy** [r-spatial/sf#1979]
I was trying all day installing sf package to work on some maps but it is not working 
I deleted and re-installed R and RStudio ( installed the right R and R studio versions)

any help will be very much appreciated : 

error message:

Warning in install.packages :
  downloaded length 42811451 != reported length 96526155
Warning in install.packages :
  URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/sf_1.0-8.tgz': Timeout of 60 seconds was reached
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/sf_1.0-8.tgz' failed
Warning in install.packages :
  download of package ‘sf’ failed

**Comment by kadyb** [comment]
> Timeout of 60 seconds was reached

There is a problem with the Internet connection or servers. Try to set up before downloading:

```r
options(timeout = 600)
```
