### ISSUE TITLE
Broken buffer around closed linestring

### ISSUE THREAD

**Issue by zoeschindler** [r-spatial/sf#1986]
**Describe the bug**
When creating a buffer around linestrings, sometimes the buffer is intersecting the lines to be buffered. This did not occur for all, but some of the linestrings I tested.

**To Reproduce**
```
# set coordinates
ch_crd <- structure(
  c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3.50850510439515, 3.34156954142671, 
    2.87898194958676, 2.72374630132234, 2.2922345396554, 2.29312419890067, 
    2.32261681738335, 2.49720251348322, 3.19886481773371, 3.50850510439515, 
    1.62424111363924, 1.64507013529592, 1.71055495856562, 1.8867890234822, 
    2.38801074041958, 2.91005134572971, 3.22939872710867, 3.25684154033292, 
    2.97375702861173, 1.62424111363924), dim = c(10L, 3L), dimnames = list(
      NULL, c("id", "x", "y"))) 

# add appropriate offet
ch_crd[,"x"] <- ch_crd[,"x"] + 413700
ch_crd[,"y"] <- ch_crd[,"y"] + 5316500

# create line & buffer
ch_lin = st_linestring(ch_crd[, 2:3])
ch_lin = st_sfc(ch_lin, crs = "epsg:25832")
ch_buff = st_buffer(ch_lin, 2)

# plot line & buffer
plot(ch_buff, col = "lightblue")
plot(ch_lin, add = T)
```
![grafik](https://user-images.githubusercontent.com/59600387/184899166-d9415b02-cdd9-488f-a1e3-252ecdbcc2d9.png)

**Additional context**
I already opened another issue for the `terra` package, in which I originally encountered the issue: https://github.com/rspatial/terra/issues/765. When using a smaller buffer, e.g. 1m, this problem does not occur. I don't think it's because the points are close to each other, since multiplying both the coordinates and the buffer by 100 does not help, although it reduces the number of decimal points.

<details>

**sessionInfo()**

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8    LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                    LC_TIME=German_Germany.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_1.0-8

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9         rstudioapi_0.13    magrittr_2.0.3     units_0.8-0        tidyselect_1.1.2   R6_2.5.1           rlang_1.0.4        fansi_1.0.3        dplyr_1.0.9        tools_4.2.1        grid_4.2.1         KernSmooth_2.23-20 utf8_1.2.2        
[14] cli_3.3.0          e1071_1.7-11       DBI_1.1.3          class_7.3-20       assertthat_0.2.1   tibble_3.1.8       lifecycle_1.0.1    purrr_0.3.4        vctrs_0.4.1        glue_1.6.2         proxy_0.4-27       compiler_4.2.1     pillar_1.8.0      
[27] generics_0.1.3     classInt_0.4-7     pkgconfig_2.0.3

**sf::sf_extSoftVersion()**

          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
       "3.9.1"        "3.4.3"        "7.2.1"         "true"         "true"        "7.2.1"

</details>

**Comment by edzer** [comment]
Looks like a problem in GEOS, the library `terra` and `sf` use for this kind of problems. If you use
```r
ch_lin = st_polygon(list(ch_crd[, 2:3]))
```
then things look fine. Is there a reason you need a `LINESTRING`?

**Comment by edzer** [comment]
> Because when I provide terra with a positive buffer, it fills the hole in the middle. With a negative buffer, e.g. -2m, it throws an error instead of returning an empty polygon if there is no hole.

@rhijmans
