### ISSUE TITLE
Unable to suppress messages.  

### ISSUE THREAD

**Issue by rccline** [r-spatial/sf#1988]
*I*Describe the bug**
I am unable to suppress messages from st_read when knitting.  Someone suggested adding quiet=TRUE.  I did not find quiet in the documentation.  Adding it made no difference and caused no errors.  

I cannot stop Rmarkdown from printing messages in my chunk that uses the function st_read()
I have set message=FALSE in every chunk.  I still get messages from st_read()
I have parsed the code down to st_read().  Still with only loading libraries and st_read()  I get messages.
And I restart so I am starting clean and still, I get messages.
My first code chunk:
```{r include=FALSE,  message=FALSE, warning=FALSE}
knitr::opts_chunk$set( warning=FALSE, message = FALSE,
  comment = "#>", echo = FALSE, fig.width = 6)
```
My code chunk with st_read() begins with message=FALSE
{r  echo=FALSE, message=FALSE, warning=FALSE} 
> Reading layer `tg3' from data source `E:\path\tg3.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 359 features and 18 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 596002.2 ymin: 295900.1 xmax: 528011.5 ymax: 230955.1
#> Projected CRS: NAD83 / Nebraska (ftUS)

```{r  echo=FALSE, message=FALSE, warning=FALSE}
tg <- st_read(here("shapefiles/tg3.shp"))
```

**Additional context**
loaded via a namespace (and not attached):
 [1] prettyunits_1.1.1 ps_1.7.1          rprojroot_2.0.3   withr_2.5.0       crayon_1.5.1      digest_0.6.29     R6_2.5.1         
 [8] evaluate_0.16     rlang_1.0.4       cli_3.3.0         curl_4.3.2        rstudioapi_0.13   callr_3.7.1       rmarkdown_2.15   
[15] tools_4.2.0       processx_3.7.0    xfun_0.32         yaml_2.3.5        fastmap_1.1.0     compiler_4.2.0    pkgbuild_1.3.1   
[22] htmltools_0.5.3   knitr_1.39       

 sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
       "3.9.1"        "3.4.3"        "7.2.1"         "true"         "true"        "7.2.1"          > library(styler)
Warning message:
package ‘styler’ was built under R version 4.2.1 
> reprex:::reprex_addin()
ℹ Rendering reprex...
Error in parse(text = x, keep.source = TRUE) : 
  <text>:8:26: unexpected symbol
7:  sf::sf_extSoftVersion()
8:           GEOS           GDAL
                            ^

**Comment by rsbivand** [comment]
http://r-spatial.github.io/sf/reference/st_read.html has by default quiet=FALSE, perhaps try quiet=TRUE? Using args(st_read) or ?st_read would have been effective self-help.

**Comment by rccline** [comment]
The first line of my  posting reported that _quiet=TRUE_ did not work.  Niccola Rennie on r4ds suggested _results='hide'_   That worked!  Thank you Niccola.

**Comment by rccline** [comment]
Niccola Rennie on r4ds suggested the solution to suppressing messages when message=FALSE or quiet=TRUE does not work.  The solution     **_results='hide'_**

**Comment by rsbivand** [comment]
Reproducible example, knitr 1.39:

```
setwd(tempdir())
Rmd <- tempfile(fileext=".Rmd")
con <- file(Rmd)
open(con, open="wt")
writeLines("---", con)
writeLines("title: Reprex", con)
writeLines("output: html_notebook", con)
writeLines("---", con)
writeLines("\n", con)
writeLines("```{r}", con)
writeLines('f <- system.file("gpkg/nc.gpkg", package="sf")', con)
writeLines('nc <- sf::st_read(f)', con)
writeLines("```\n", con)
writeLines("```{r}", con)
writeLines('nc <- sf::st_read(f, quiet=TRUE)', con)
writeLines("```\n", con)
close(con)
knitr::knit(Rmd)
file.show(file.path(Rmd))
```
![image](https://user-images.githubusercontent.com/10198404/186978116-0ffc2a83-3b5a-47c1-9f3f-6895b29bf39a.png)

```
file.show(sub("\\.Rmd", ".md", file.path(Rmd)))
```
![image](https://user-images.githubusercontent.com/10198404/186978233-2220e597-9ff4-4c9a-be1f-f689a059d474.png)


No sign of the `quiet=` argument failing to suppress output. This isn't a warning or a message, it is output. And the argument is in the documentation.
