### ISSUE TITLE
Implement st_precision<- as an S3 generic

### ISSUE THREAD

**Issue by agila5** [r-spatial/sf#1989]
Dear sf developers, I'm writing this issue to propose implementing `st_precision<-`

https://github.com/r-spatial/sf/blob/7169d84d771da5c70508e8f83b497a803d724d5f/R/sfc.R#L451-L456

as an S3 generic following the same pattern as in `st_crs<-` or `st_agr<-`. If you want, I can propose a PR. 

It's really not a big deal, but this (super tiny) "problem" came up here: https://github.com/luukvdmeer/sfnetworks/issues/209#issuecomment-1220819949

**Comment by edzer** [comment]
No objections, but as `st_precision<-` calls `st_set_precision`, doesn't that dispatch on any other class? Or do you need a form that does something else?

**Comment by agila5** [comment]
Oops, yes, you're right. Then, I guess the only problem was implementing the ad-hoc method, not the actual use of `st_precision<-`. Are you still interested in a PR? Otherwise, feel free to close!
