### ISSUE TITLE
Where can I see the math behind `sf::st_centroid()`?

### ISSUE THREAD

**Issue by rtheodoro** [r-spatial/sf#1990]
Hi, guys!

I have been using the function `sf::st_centroidst()` in my academic paper and my advisor asked me where can I see the math behind it.

I did check the description at CRAN, but I did not find it.

**Comment by rsbivand** [comment]
Are your position data (coordinates) projected or not? If you are using recent sf, look for details in references to s2geometry http://s2geometry.io/ in the s2 package if your geometries are not projected, and references to GEOS if projected http://libgeos.org/. In both cases the code is the expression of the maths, where multipolygons are a special case. For projected coordinates, the axes share planar units of measurement. For non-projected coordinates on the sphere/ellipsoid, curves between points are most often curves.

**Comment by rtheodoro** [comment]
Yes, I have been using to calculate the distance between some Brazilian cities.

I will check this two sites. Thanks!
