### ISSUE TITLE
Why I can't install the "SF" package in R 4.2.1?

### ISSUE THREAD

**Issue by PritomBhowmikAkash** [r-spatial/sf#1992]
When I run this command install.packages("sf")
the console shows-

  download from 'https://cran.rstudio.com/bin/windows/contrib/4.2/sf_1.0-8.zip' failed
Warning in install.packages :
  download of package ‘sf’ failed

**Comment by rsbivand** [comment]
Try a different CRAN mirror for download?

**Comment by PritomBhowmikAkash** [comment]
> I am a newbie in the R programming language. Would you please provide me with a different CRAN mirror for download?

**Comment by PritomBhowmikAkash** [comment]
Thank you, Sir. I got solution from a similar issue posted on GitHub previously. It was due to the loss of my internet connection.
