### ISSUE TITLE
CRS mismatch even though they are same in ArcGIS Pro

### ISSUE THREAD

**Issue by Saadi4469** [r-spatial/sf#2000]
Hello and good day,

Can you please propose a workaround to fixing the `CRS` of the `sf` object to have it match with the `CRS` information stored in the `LAS` file? As I don't want to change the CRS of the `point cloud` file.

For further reference, please look at this [question](https://gis.stackexchange.com/questions/439712/r-lidr-clip-roi-error).

Thank you

**Comment by rsbivand** [comment]
From the question not recorded here, the LAS is 3D, but the clipping object 2D as was already pointed out, with the resolution `st_crs(FL_20180602_B1_e1586n0472) = st_crs(clip_sf)` or equivalently the reverse if you can justify adding:
```
    VERTCRS["NAVD88 height",
        VDATUM["North American Vertical Datum 1988"],
        CS[vertical,1],
            AXIS["gravity-related height (H)",up,
                LENGTHUNIT["metre",1]],
        ID["EPSG",5703]]
```
to the 2D CRS.

**Comment by Saadi4469** [comment]
@rsbivand so it won't work if I do `st_crs(clip_sf) = st_crs(FL_20180602_B1_e1586n0472)`?

**Comment by rsbivand** [comment]
Perhaps try and see, but you are assuming that the vertical crs is correct.

**Comment by Saadi4469** [comment]
Yes the coordinates are correct for the shapefile and the LAS file, as ArcGIS Pro does not give a CRS mismatch error. So I tried what I stated in the above comment and this is the error I get:

```
Warning message:
st_crs<- : replacing crs does not reproject data; use st_transform for that 
```

**Comment by rsbivand** [comment]
It is not an error but a warning as it says. Many users mistake assigning a new crs definition as carrying out a transformation, wich it is not, hence the warning.
