### ISSUE TITLE
Add ability to remove layer via GDALDataset::DeleteLayer(layer_index)

### ISSUE THREAD

**Issue by dblodgett-usgs** [r-spatial/sf#2007]
per @rouault here: https://gist.github.com/dblodgett-usgs/61425b5cb58bd570a47e7ed054a8d7b5 is this something that could be added somehow? 

I've got a number of use cases where being able to cleanly remove a layer from a gpkg would be helpful. Maybe if we could call st_write with a NULL object?

e.g. `sf::st_write(NULL, "foo.gpkg", "bar", delete_layer = TRUE)` would remove the `bar` layer from `foo.gpkg` and not actually write anything to it?

**Comment by edzer** [comment]
Did you try `st_delete`?

**Comment by dblodgett-usgs** [comment]
RTFM... sorry.
