### ISSUE TITLE
When projecting to Berghaus Star, all spatial units become empty

### ISSUE THREAD

**Issue by coconn41** [r-spatial/sf#2014]
The Berghaus Star projection is not within the standard EPSG codes identified by `sf`. Technically, it has the EPSG of ESRI 102299, which is not recognized. When copying the WKT2 given here: https://epsg.io/102299 and creating a projection in string format, `st_transform()` accepts the string projection in the `crs` argument. No errors are given. However, when plotting the resulting transformed data, all spatial units are read as empty.

See the reprex below:
``` r
library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.2, PROJ 8.2.1; sf_use_s2() is TRUE
library(spData)
library(tmap)

data('world')

proj='PROJCRS["Berghaus_Star_AAG",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["Berghaus_Star_AAG",
        METHOD["Berghaus_Star"],
        PARAMETER["False_Easting",0,
            LENGTHUNIT["metre",1]],
        PARAMETER["False_Northing",0,
            LENGTHUNIT["metre",1]],
        PARAMETER["Central_Meridian",-52,
            ANGLEUNIT["Degree",0.0174532925199433]],
        PARAMETER["Latitude_Of_Origin",90,
            ANGLEUNIT["Degree",0.0174532925199433]],
        PARAMETER["XY_Plane_Rotation",36,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Not known."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["ESRI",102299]]'

Berghaus_Star = world %>%
  st_transform(., crs = proj)

tm_shape(Berghaus_Star)+
  tm_borders()
#> Error: The shape Berghaus_Star only contains empty units.
```

<sup>Created on 2022-10-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rsbivand** [comment]
Yes, it is recognized:
```
> library(sf)
Linking to GEOS 3.11.0, GDAL 3.5.2, PROJ 9.1.0; sf_use_s2() is TRUE
> st_crs("ESRI:102299")
Coordinate Reference System:
  User input: ESRI:102299 
  wkt:
PROJCRS["Berghaus_Star_AAG",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["Berghaus_Star_AAG",
        METHOD["Berghaus_Star"],
        PARAMETER["False_Easting",0,
            LENGTHUNIT["metre",1]],
        PARAMETER["False_Northing",0,
            LENGTHUNIT["metre",1]],
        PARAMETER["Central_Meridian",-52,
            ANGLEUNIT["Degree",0.0174532925199433]],
        PARAMETER["Latitude_Of_Origin",90,
            ANGLEUNIT["Degree",0.0174532925199433]],
        PARAMETER["XY_Plane_Rotation",36,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Not known."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["ESRI",102299]]
```
The problem (if any) is:
```
> system("projinfo ESRI:102299 -o PROJ")
PROJ.4 string:
Error when exporting to PROJ string: Unsupported conversion method: Berghaus_Star
> sf_proj_pipelines(st_crs(world), "ESRI:102299")$definition
[1] "+"
> system("projinfo -s EPSG:4326 -t ESRI:102299 -o PROJ")
Candidate operations found: 1
-------------------------------------
Operation No. 1:

unknown id, axis order change (2D) + Berghaus_Star_AAG, 0 m, World

PROJ string:
Error when exporting to PROJ string: Unsupported conversion method: Berghaus_Star
```
So PROJ does not currently generate a forward projection pipeline. There seem to be no such issues on https://github.com/OSGeo/PROJ/issues. You cannot always replicate ArcGIS behaviour in FOSS for obvious reasons. Consider raising an issue with PROJ, but note that PROJ will most likely respond that the target is rather pointless. Rather save the projected output from ArcGIS to GPKG and read into R from that.

**Comment by coconn41** [comment]
Ahh I see. I will raise an issue there for good measure.

Thanks for pointing out that the projection is recognized - I haven't used the EPSG string format before (`"ESRI:____"`). Now I know!

**Comment by rsbivand** [comment]
See https://neocarto.github.io/bertin/examples/quarto.html, https://observablehq.com/@neocartocnrs/hello-bertin-js, https://github.com/d3/d3-geo-projection#interrupted-projections - maybe something there? https://observablehq.com/@d3/berghaus-star ...

**Comment by coconn41** [comment]
Yes, this seems like a good solution. The d3js solution was also given as a solution in my post here: https://github.com/OSGeo/PROJ/issues/3394

**Comment by rCarto** [comment]
> See https://neocarto.github.io/bertin/examples/quarto.html, https://observablehq.com/@neocartocnrs/hello-bertin-js, https://github.com/d3/d3-geo-projection#interrupted-projections - maybe something there? https://observablehq.com/@d3/berghaus-star ...

And if you feel adventurous, there is an R wrapper for the berlin js lib here: https://github.com/riatelab/bertin 
Vignette: https://riatelab.github.io/bertin/articles/bertin.html
Work in progress..
