### ISSUE TITLE
Repeated warnings when making sf with empty points

### ISSUE THREAD

**Issue by bart1** [r-spatial/sf#2015]
I just noticed this case where I get 4 times a rather cryptic warning about only providing NA values, as `na.fail=F` I think no warning is needed. I will upload a pull request removing the warnings without changing behaviour

``` r
data.frame(x=NA, y=NA) |> sf::st_as_sf(coords=c("x","y"),na.fail=F)
#> Warning in min(cc[[1]], na.rm = TRUE): no non-missing arguments to min;
#> returning Inf
#> Warning in min(cc[[2]], na.rm = TRUE): no non-missing arguments to min;
#> returning Inf
#> Warning in max(cc[[1]], na.rm = TRUE): no non-missing arguments to max;
#> returning -Inf
#> Warning in max(cc[[2]], na.rm = TRUE): no non-missing arguments to max;
#> returning -Inf
#> Simple feature collection with 1 feature and 0 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: Inf ymin: Inf xmax: -Inf ymax: -Inf
#> CRS:           NA
#>      geometry
#> 1 POINT EMPTY
```

<sup>Created on 2022-10-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by edzer** [comment]
I think for consistency this should result in an error, not return a valid `sf` object.

**Comment by bart1** [comment]
Hmm interesting, for my use case (tracking data) that would be rather inconvenient. In some cases all locations are empty (either the gps effort did not result in a fix or mostly other sensor data without a location has been collected), it would be inconvenient to always have to treat those data differently. Note the user already has agreed to `EMPTY` locations by setting `na.fail=F`.

Also, according to that logic, subsetting to only `EMPTY` locations should then result in an invalid `sf` object i guess. Currently that is not the case. Interesting enough the `bbox` results in `NA` rather then `Inf` when subsetting:
``` r
data.frame(x=c(NA,1), y=c(NA,1)) |> sf::st_as_sf(coords=c("x","y"),na.fail=F) ->a
a[1,]
#> Simple feature collection with 1 feature and 0 fields (with 1 geometry empty)
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
#> CRS:           NA
#>      geometry
#> 1 POINT EMPTY
a[2,]
#> Simple feature collection with 1 feature and 0 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 1 ymin: 1 xmax: 1 ymax: 1
#> CRS:           NA
#>      geometry
#> 1 POINT (1 1)
```

<sup>Created on 2022-10-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by edzer** [comment]
I think those ideas come from the DE9-IM: the intersection of two non-intersecting geometries is the empty geometry.

**Comment by bart1** [comment]
Hmm, I do agree in the case of all `NA` coordinates, and `NA` bounding box would be better then a `Inf` bounding box. The pull request can be updated accordingly. I do not think `st_as_sf` should fail on only `NA` coordinates as I think there are use cases where missing locations can occur and it is not certain if in some cases only missing location are pressent.

**Comment by kadyb** [comment]
For comparison, I checked `{terra}` and `{geopandas}` and they return error in this case. There is no argument such as `na.fail` in these functions.

```r
library("terra")
data.frame(x=NA, y=NA) |> vect(geom=c("x", "y"))
#> Error: [vect] coordinates must be numeric
```

```python
import pandas as pd
import geopandas
geopandas.points_from_xy(x=[pd.NA], y=[pd.NA])
#> TypeError: float() argument must be a string or a number, not 'NAType'
## but empty geometry works
geopandas.points_from_xy(x=[None], y=[None])
```

**Comment by edzer** [comment]
>  I checked `{terra}`

but that gave a type error, with typed `NA` we see:
```r
library(terra)
# terra 1.6.29
data.frame(x=NA_real_, y=NA_real_) |> vect(geom=c("x", "y"))
#  class       : SpatVector 
#  geometry    : points 
#  dimensions  : 1, 0  (geometries, attributes)
#  extent      : NA, NA, NA, NA  (xmin, xmax, ymin, ymax)
#  coord. ref. :  
```
and
```
> data.frame(x=NA_real_, y=NA_real_) |> vect(geom=c("x", "y")) |> st_as_sf()
Simple feature collection with 1 feature and 0 fields (with 1 geometry empty)
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
CRS:           NA
     geometry
1 POINT EMPTY
```
(which I believe is inconsistent with the non-existing-ness of the `POINT EMPTY`).

**Comment by kadyb** [comment]
So `NaN` (R) and `numpy.nan` (Python) will also work because they are numbers (de facto).
