### ISSUE TITLE
Postgres, can't set geography column

### ISSUE THREAD

**Issue by latot** [r-spatial/sf#2018]
Hi all, maybe this is a GDAL issue, but I was trying a workaround.

The problem, when we write a table in postgres and the CRS is 4326, in "theory" the geometry type of the column should be "geography", "geometry" is used for planar, but after check the column type in the database I notice is "geometry".

So, I try to use ```layer_options``` to write the column as ```geography```, but sadly, after check the database is still ```geometry```!

```
    layer_options = c()
    if (sf::st_crs(network)$epsg == 4326){
        layer_options = c(layer_options, "GEOM_TYPE=geography")
    }else{
        layer_options = c(layer_options, "GEOM_TYPE=geometry")
    }

    sf::st_write(
        some_file_4326,
        db,
        layer = "network",
        quiet = FALSE,
        layer_options = layer_options
    )
```

I have tested like set the geometry column name too, but sadly no luck...

Gentoo 64
R 4.2.1
DBI 1.1.3
SF 1.0-8
Postgres/Postgis from docker latest

Thx!

**Comment by edzer** [comment]
Apart from a missing reprex, when experimenting I see a table written with geometry column named `the_geog`, indicating that this is of geography type?

The general check for geographic coordinates is `st_is_longlat()`.

**Comment by latot** [comment]
Hi, oks, the reprex is a little big, but it can works, and yes, the data is long/lat:

```
library(wrapr)

#Setup

cores <- 5

##Set up postgres!

postgres_port <- httpuv::randomPort()

postgres_docker_id <- local({
    
    print("Starting Postgress")
    ret <- processx::run(
        "docker",
        c(
            "run",
            "--rm",
            "-d",
            "-p", paste0(postgres_port, ":5432"),
            "-e", "POSTGRES_USER=user",
            "-e", "POSTGRES_PASSWORD=password",
            "-e", "POSTGRES_DB=db",
            "postgis/postgis",
            "-c", paste0("max_worker_processes=", parallel::detectCores()),
            "-c", paste0("max_parallel_workers=", cores),
            "-c", paste0("max_parallel_workers_per_gather=", cores),
            "-c", paste0("max_parallel_maintenance_workers=", cores)
        ),
        stdout = "|",
        stderr = "|"
    )

    if (ret$status != 0){
        stop("Postgres failed to start!")
    }
    
    docker_id <- ret %.>%
        .$stdout %.>%
        stringr::str_sub(., 1, length(.) - 3)
    return(docker_id)

})

#Here some discuss
#https://github.com/postgis/docker-postgis/issues/316
print("Waiting for Postgress to be ready")
while (TRUE){
    Sys.sleep(1)
    if (
        processx::run(
            "docker",
            c(
                "exec",
                postgres_docker_id,
                "pg_isready",
                "-h", "localhost"
            ),
            error_on_status = FALSE
        )$status == 0
    ) break
}
print("Postgress is ready to use")

db = DBI::dbConnect(
    RPostgres::Postgres(),
    user="user",
    password="password",
    host="localhost",
    port=postgres_port,
    dbname="db"
)


nc <- st_read(system.file("shape/nc.shp", package="sf")) %.>%
    sf::st_transform(., 4326)

sf::st_write(nc, db, layer = "nc", layer_options = c("GEOM_TYPE=geography"))
```

**Comment by edzer** [comment]
Ah, I see you're mixing two interfaces: `db` is of `DBI` type so uses R's DBI interface; `layer_options` is an option to the GDAL interface, not to the DBI interface. So instead of using `db` you need to use a driver that starts with `PG:`, sth like `"PG:host=localhost dbname=db user=user passwd=passwd"` see [here](https://gdal.org/drivers/vector/pg.html) for details.

**Comment by latot** [comment]
mm, personallly is little confusing, we expect to just works a connection with it, but as you explain DBI is different, so does not support GDAL, in that case, is there a way to made a connection through GDAL? because using GDAL format as described in the docs, should made a new connection every time.

https://r-spatial.github.io/sf/articles/sf2.html

**Comment by edzer** [comment]
Good point: different sections on GDAL and DBI. See also [here](https://r-spatial.org/book/01-hello.html#spatial-data-science-software): GDAL and DBI different arrows. Don't think that options for one work with the other.

**Comment by latot** [comment]
Oks, tested, with GDAL works great!, there is a few point

- Keep the geometry column name, actually takes the GDAL default
- Instead have a "Linestring" or any particular type of geometry, maybe is better use the geometry type (? this just helps to works in a simpler way.

Thx!
