### ISSUE TITLE
Errors while Installing terra R package 

### ISSUE THREAD

**Issue by avanti2112** [r-spatial/sf#2021]
**Describe the bug**
Installing terra on RHEL OS giving an error below:

R CMD INSTALL  ./terra_1.6-17.tar.gz

**Error: package or namespace load failed for ‘terra’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/00LOCK-terra/00new/terra/libs/terra.so':
  /usr/local/lib64/R/library/00LOCK-terra/00new/terra/libs/terra.so: undefined symbol: GEOSFrechetDistance_r**
Error: loading failed
Execution halted
ERROR: loading failed

**To Reproduce**
R CMD INSTALL /home/AS/pfe8-su/files/terra_1.6-17.tar.gz
* installing to library ‘/usr/local/lib64/R/library’
* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc -std=gnu11
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.4.2
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc -std=gnu11
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu11 accepts -g... yes
checking for gcc -std=gnu11 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu11 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /export/apps/gdal/2.4.2/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 2.4.2
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 6.1.1
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
checking for geos-config... /usr/local/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.8.3
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/local/lib -lgeos_c... yes
configure: Package CPP flags:  -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include
configure: Package LIBS: -L/export/apps/proj/6.1.1/lib -lproj     -L/export/apps/gdal/2.4.2/lib -lgdal -L/usr/local/lib -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppFunctions.cpp -o RcppFunctions.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppModule.cpp -o RcppModule.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c arith.cpp -o arith.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c crs.cpp -o crs.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c distRaster.cpp -o distRaster.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c distance.cpp -o distance.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c extract.cpp -o extract.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c file_utils.cpp -o file_utils.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c focal.cpp -o focal.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gcp.cpp -o gcp.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdal_algs.cpp -o gdal_algs.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdal_multidimensional.cpp -o gdal_multidimensional.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c gdalio.cpp -o gdalio.o
gcc -std=gnu11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c geodesic.c -o geodesic.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c geos_methods.cpp -o geos_methods.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c geosphere.cpp -o geosphere.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c graticule.cpp -o graticule.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c math_utils.cpp -o math_utils.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c mediancut.cpp -o mediancut.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c memory.cpp -o memory.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c ncdf.cpp -o ncdf.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c ram.cpp -o ram.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c raster_methods.cpp -o raster_methods.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c raster_stats.cpp -o raster_stats.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c rasterize.cpp -o rasterize.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c read.cpp -o read.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c read_gdal.cpp -o read_gdal.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c read_ogr.cpp -o read_ogr.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c sample.cpp -o sample.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatBase.cpp -o spatBase.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatDataframe.cpp -o spatDataframe.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatFactor.cpp -o spatFactor.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatRaster.cpp -o spatRaster.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatSources.cpp -o spatSources.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatTime.cpp -o spatTime.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c spatVector.cpp -o spatVector.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c string_utils.cpp -o string_utils.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c vecmath.cpp -o vecmath.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c vector_methods.cpp -o vector_methods.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c write.cpp -o write.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c write_gdal.cpp -o write_gdal.o
g++ -std=gnu++11 -I"/usr/local/lib64/R/include" -DNDEBUG -I/export/apps/proj/6.1.1/include   -DHAVE_PROJ_H -I/export/apps/gdal/2.4.2/include -I/usr/local/include -I'/usr/local/lib64/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c write_ogr.cpp -o write_ogr.o
g++ -std=gnu++11 -shared -L/usr/local/lib64/R/lib -L/usr/local/lib64 -o terra.so RcppExports.o RcppFunctions.o RcppModule.o arith.o crs.o distRaster.o distance.o extract.o file_utils.o focal.o gcp.o gdal_algs.o gdal_multidimensional.o gdalio.o geodesic.o geos_methods.o geosphere.o graticule.o math_utils.o mediancut.o memory.o ncdf.o ram.o raster_methods.o raster_stats.o rasterize.o read.o read_gdal.o read_ogr.o sample.o spatBase.o spatDataframe.o spatFactor.o spatRaster.o spatSources.o spatTime.o spatVector.o string_utils.o vecmath.o vector_methods.o write.o write_gdal.o write_ogr.o -L/export/apps/proj/6.1.1/lib -lproj -L/export/apps/gdal/2.4.2/lib -lgdal -L/usr/local/lib -lgeos_c -L/usr/local/lib64/R/lib -lR
installing to /usr/local/lib64/R/library/00LOCK-terra/00new/terra/libs
** R
** inst
** byte-compile and prepare package for lazy loading
in method for ‘sds’ with signature ‘x="stars"’: no definition for class “stars”
in method for ‘sds’ with signature ‘x="stars_proxy"’: no definition for class “stars_proxy”
in method for ‘svc’ with signature ‘x="sf"’: no definition for class “sf”
in method for ‘coerce’ with signature ‘"stars","SpatRasterDataset"’: no definition for class “stars”
in method for ‘coerce’ with signature ‘"ggmap","SpatRaster"’: no definition for class “ggmap”
in method for ‘coerce’ with signature ‘"sf","SpatRaster"’: no definition for class “sf”
in method for ‘coerce’ with signature ‘"sf","SpatVector"’: no definition for class “sf”
in method for ‘coerce’ with signature ‘"sfc","SpatVector"’: no definition for class “sfc”
in method for ‘coerce’ with signature ‘"sfg","SpatVector"’: no definition for class “sfg”
in method for ‘coerce’ with signature ‘"XY","SpatVector"’: no definition for class “XY”
in method for ‘coerce’ with signature ‘"im","SpatRaster"’: no definition for class “im”
in method for ‘coerce’ with signature ‘"SpatVector","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"Spatial","SpatVector"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"SpatialGrid","SpatRaster"’: no definition for class “SpatialGrid”
in method for ‘coerce’ with signature ‘"SpatialPixels","SpatRaster"’: no definition for class “SpatialPixels”
in method for ‘crs’ with signature ‘"sf"’: no definition for class “sf”
Creating a generic function for ‘ncol’ from package ‘base’ in package ‘terra’
in method for ‘ext’ with signature ‘x="sf"’: no definition for class “sf”
in method for ‘ext’ with signature ‘x="Extent"’: no definition for class “Extent”
in method for ‘ext’ with signature ‘x="Raster"’: no definition for class “Raster”
in method for ‘ext’ with signature ‘x="Spatial"’: no definition for class “Spatial”
in method for ‘extract’ with signature ‘x="SpatRaster",y="sf"’: no definition for class “sf”
in method for ‘mask’ with signature ‘x="SpatRaster",mask="sf"’: no definition for class “sf”
in method for ‘lines’ with signature ‘x="leaflet"’: no definition for class “leaflet”
in method for ‘points’ with signature ‘x="leaflet"’: no definition for class “leaflet”
in method for ‘rast’ with signature ‘x="stars"’: no definition for class “stars”
in method for ‘rast’ with signature ‘x="stars_proxy"’: no definition for class “stars_proxy”
in method for ‘rasterize’ with signature ‘x="sf",y="SpatRaster"’: no definition for class “sf”
in method for ‘show’ with signature ‘"Rcpp_SpatDataFrame"’: no definition for class “Rcpp_SpatDataFrame”
in method for ‘show’ with signature ‘"Rcpp_SpatCategories"’: no definition for class “Rcpp_SpatCategories”
in method for ‘geomtype’ with signature ‘x="Spatial"’: no definition for class “Spatial”
in method for ‘vect’ with signature ‘x="Spatial"’: no definition for class “Spatial”
in method for ‘vect’ with signature ‘x="sf"’: no definition for class “sf”
in method for ‘vect’ with signature ‘x="sfc"’: no definition for class “sfc”
in method for ‘vect’ with signature ‘x="XY"’: no definition for class “XY”
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘terra’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib64/R/library/00LOCK-terra/00new/terra/libs/terra.so':
  /usr/local/lib64/R/library/00LOCK-terra/00new/terra/libs/terra.so: undefined symbol: GEOSFrechetDistance_r
Error: loading failed
Execution halted
ERROR: loading failed

**If reporting a change from previous versions**

Please read https://cran.r-project.org/web/packages/sf/news/news.html first.

**Additional context**

<details>
Paste the output of your `sessionInfo()` and `sf::sf_extSoftVersion()`

> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS:   /usr/lib64/libblas.so.3.4.2
LAPACK: /usr/lib64/liblapack.so.3.4.2

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.2.1

Output of  sf::sf_extSoftVersion()

> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H
       "3.4.2"        "2.4.2"        "6.1.1"        "false"         "true"
          PROJ
       "6.1.1"

</details>

**Comment by edzer** [comment]
Maybe report this on terra's repo?

**Comment by rsbivand** [comment]
You may look in https://libgeos.org/. Looks like multiple installed versions of GEOS, build 3.8.3 with the lost function, and first found on load an earlier version without it. https://github.com/r-spatial/sf/#multiple-gdal-geos-andor-proj-versions-on-your-system may help.
