### ISSUE TITLE
Combining polygons that are within a specified distance of each other into a new polygon

### ISSUE THREAD

**Issue by fgoerlich** [r-spatial/sf#2022]
In the past I have used the tool [Aggregate Polygons](https://pro.arcgis.com/en/pro-app/latest/tool-reference/cartography/aggregate-polygons.htm) in ArcGIS that allows to combine polygons creating an envelope around them given a threshold distance.

![image](https://user-images.githubusercontent.com/6486324/198903942-4b446530-01dc-4482-8bdc-518090297a39.png)

Is there a simple way to achieve this using sf?
While I can find the polygons within a given distance with `st_is_within_distance` I haven´t found a way to create an envelope.

Thanks

**Comment by rsbivand** [comment]
Please provide a minimal reproducible example, best with a data set from sf or spData.

**Comment by fgoerlich** [comment]
The simplest example is the following.
```
library(tidyverse)
library(sf)

# install CatastRo from CRAN to get the data
bu <- CatastRo::catr_wfs_get_buildings_bbox(
  c(-5.567429, 42.598935, -5.565509, 42.600396),
  srs = 4326
) %>% st_transform(crs = "EPSG:25830")

# Map
ggplot(bu) +
  geom_sf() +
  ggtitle("Leon Cathedral, Spain")
```

You will get these buildings:
![image](https://user-images.githubusercontent.com/6486324/199004362-94324236-6adf-4588-a33c-662c92b22f62.png)

My main problem is to get an envelope polygon that includes all the buildings, similar to the red polygon in the (right) figure above from the ArcGIS tool.

Thanks,

**Comment by edzer** [comment]
@fgoerlich you may not see this, but your example needs data from an access restricted WFS; I get
```r
Download failed

url 
 https://ovc.catastro.meh.es/INSPIRE/wfsBU.aspx?service=wfs&version=2.0.0&request=getfeature&typenames=BU.BUILDING&bbox=-619763.361307704,5251123.54708625,-619549.627885381,5251344.49199393&SRSNAME=EPSG::3857 not reachable.

Please try with another options. If you think this is a bug please consider opening an issue
Error in catr_hlp_dwnload(api_entry, filename, cache_dir = tempdir(),  : 
Execution halted
In addition: Warning messages:
1: In download.file(url, filepath, quiet = isFALSE(verbose), mode = "wb") :
  URL 'https://ovc.catastro.meh.es/INSPIRE/wfsBU.aspx?service=wfs&version=2.0.0&request=getfeature&typenames=BU.BUILDING&bbox=-619763.361307704,5251123.54708625,-619549.627885381,5251344.49199393&SRSNAME=EPSG::3857': status was 'SSL peer certificate or SSH remote key was not OK'
2: In download.file(url, filepath, quiet = isFALSE(verbose), mode = "wb") :
  URL 'https://ovc.catastro.meh.es/INSPIRE/wfsBU.aspx?service=wfs&version=2.0.0&request=getfeature&typenames=BU.BUILDING&bbox=-619763.361307704,5251123.54708625,-619549.627885381,5251344.49199393&SRSNAME=EPSG::3857': status was 'SSL peer certificate or SSH remote key was not OK'
```
which makes it not reproducible for others.

**Comment by fgoerlich** [comment]
Sorry!, I thought it was easier to get the data from a library.
This should work now:
```
library(tidyverse)
library(sf)

bu <- read_sf("https://www.uv.es/goerlich/Ivie/bu.gpkg")

# Map
ggplot(bu) +
  geom_sf() +
  ggtitle("Leon Cathedral, Spain")
```

**Comment by rsbivand** [comment]
```
library(sf)
bu <- st_read("https://www.uv.es/goerlich/Ivie/bu.gpkg")
library(spdep)
nbq_10_snap <- poly2nb(bu, snap=10)
(comp_10 <- n.comp.nb(nbq_10_snap))
bu_10 <- aggregate(bu, list(comp_10$comp.id), head, n=1)
bu_10$ID <- factor(1:3)
plot(bu_10["ID"])
```
![image](https://user-images.githubusercontent.com/10198404/199094137-c3e1dda7-85be-43b1-9a5d-fb7f40e76aec.png)

The hard question is how to construct the three extruded polygons, in this case with a snap distance of 10m.
```
library(concaveman)
xx <- st_as_sf(st_cast(st_geometry(bu_10)[1], "POINT"))
a <- concaveman(xx, concavity=2.5)
plot(st_geometry(bu_10)[1])
plot(a, add=TRUE, border="red")
```
gets quite close, but would need to add nodes to longer lines, perhaps.
![image](https://user-images.githubusercontent.com/10198404/199098559-53397052-77c7-4170-80f3-726c26e6cd42.png)

**Comment by fgoerlich** [comment]
Thanks for the help!
Effectively if I increase the nodes, `bu_10 <- st_segmentize(bu_10, 0.1)`, before the `concaveman` calculations I get a much closer desired result:
![image](https://user-images.githubusercontent.com/6486324/200197370-9aafe544-fb47-4522-a686-c5016af0a5ed.png)

But the nodes have to be increased by a huge number.
The ArcGIS tool seems to provide an slightly different result.

If desired, it remains to keep the holes of the original polygons:
```
holes <- st_difference(nngeo::st_remove_holes(st_union(bu_10)), st_union(bu_10))
a <- st_difference(a, holes)
plot(st_geometry(bu_10)[1])
plot(a, add=TRUE, border="red")
```
![image](https://user-images.githubusercontent.com/6486324/200197815-c8c88484-8260-4d49-a4cc-9d6d06d62be3.png)
