### ISSUE TITLE
GDAL 3.6.0RC1 breaks tests

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#2027]
[testthat.Rout.zip](https://github.com/r-spatial/sf/files/9932505/testthat.Rout.zip)

The two tests are affected by `gdb` becoming writeable in 3.6.0 https://gdal.org/drivers/vector/openfilegdb.html#vector-openfilegdb (test_read), fix add `if (sf_extSoftVersion()[["GDAL"]] < "3.6.0")` before `expect_error()`, and (worse) for writing that `gdb` now has:
```
>     for (ext in setdiff(names(sf:::extension_map[sf:::extension_map %in% drvs]), excluded_drivers)) {
+ cat(ext, "\n")
+ st_write(meuse, paste0(tf, ".", ext), quiet = TRUE)
+ }
csv 
fgb 
gdb 
Unknown field name `dist.m': updating a layer with improper field name(s)?
Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Write error
In addition: Warning message:
In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Message 6: Normalized/laundered field name: 'dist.m' to 'dist_m'
```
Without GDB the loop passes.

**Comment by rsbivand** [comment]
```
tf <- tempfile()
nc <- st_read(system.file("gpkg/nc.gpkg", package="sf"))
ext <- "gdb"
st_write(nc, paste0(tf, ".", ext), quiet = TRUE, append=FALSE) # OK
names(nc)[12] <- "BIR.79"
st_write(nc, paste0(tf, ".", ext), quiet = TRUE, append=FALSE) # Unknown field name `BIR.79': updating a layer with improper field name(s)?
names(nc)[12] <- "BIR_79"
st_write(nc, paste0(tf, ".", ext), quiet = TRUE, append=FALSE) # OK
```
Geometry name seems to be `SHAPE`. Details in https://support.esri.com/en/technical-article/000005588 from https://github.com/OSGeo/gdal/blob/3f4edbe8eb32423ce11417aa150d4f79b7eb2e8d/ogr/ogrsf_frmts/filegdb/FGdbUtils.cpp#L460-L493.

**Comment by edzer** [comment]
Maybe exclude writing gdb from the tests altogether?

**Comment by rsbivand** [comment]
Yes, and maybe document somewhere for users that the driver restricts field names?
