### ISSUE TITLE
R-devel Debian POSIXlt issue

### ISSUE THREAD

**Issue by dblodgett-usgs** [r-spatial/sf#2028]
**Describe the bug**
I've had a failure crop up in R-Devel Debian builds.

e.g. https://builder.r-hub.io/status/ncdfgeom_1.1.4.tar.gz-3783611a948849c68cefc54dc8466b37#L5870

**To Reproduce**

on: `rhub/fedora-clang-devel`

```
sf::read_sf(system.file('extdata','example_huc_eta.json', package = 'ncdfgeom'))
#> Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet, : 
#> Evaluation error: a valid "POSIXlt" object has names.
#> Calls: -> st_read -> st_read.character -> CPL_read_ogr
```

**Comment by dblodgett-usgs** [comment]
🙏

**Comment by rsbivand** [comment]
Confirmed fixed in main.

**Comment by edzer** [comment]
sf 1.0-9 is now on CRAN.
