### ISSUE TITLE
Feature request: option to exclude geometry in st_read

### ISSUE THREAD

**Issue by DavidMatthews83** [r-spatial/sf#2031]
Possible enhancement to st_read /read_sf to exclude geometry. 
Maybe using the existing geometry_column option eg. st_read(.....,geometry_column = NULL)

**Comment by kadyb** [comment]
There is such functionality in `{terra}` that you can only load attributes as dataframe without geometry.

```r
f = system.file("ex/lux.shp", package = "terra")
v = vect(f) # SpatVector
v = vect(f, what = "attributes") # data.frame
```

Implementing this seems reasonable, because we can limit the memory and speed it up.

```r
x = data.frame(x = runif(1e6), y = runif(1e6), a = "a", b = "b", c = "c")
x = vect(x, geom = c("x", "y"))
tmp = tempfile(fileext = ".gpkg")
writeVector(x, tmp)
system.time(vect(tmp)) #> 3.25
system.time(vect(tmp, what = "attributes")) #> 1.41
```

**Comment by edzer** [comment]
If you're willing to list the attribute names you can:
```r
library(sf)
# Linking to GEOS 3.10.2, GDAL 3.4.3, PROJ 8.2.1; sf_use_s2() is TRUE
system.file("gpkg/nc.gpkg", package="sf") |>
  st_read(query = "select SID74, BIR74 from 'nc.gpkg'", quiet = TRUE) |>
  head()
#   SID74 BIR74
# 1     1  1091
# 2     0   487
# 3     5  3188
# 4     1   508
# 5     9  1421
# 6     7  1452
```
maybe there's a way to sort out how to do this for all non-geometry attributes.

**Comment by kadyb** [comment]
But first we need to use `ogrinfo` to find out the column names to select, and then use `st_read()`?

**Comment by Nowosad** [comment]
Or just get the first row:

``` r
library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.3, PROJ 8.2.1; sf_use_s2() is TRUE

# step 1 (get colnames)
system.file("gpkg/nc.gpkg", package="sf") |>
  st_read(query = "select * from 'nc.gpkg' WHERE FID = 1", quiet = TRUE) |>
  colnames()
#>  [1] "AREA"      "PERIMETER" "CNTY_"     "CNTY_ID"   "NAME"      "FIPS"     
#>  [7] "FIPSNO"    "CRESS_ID"  "BIR74"     "SID74"     "NWBIR74"   "BIR79"    
#> [13] "SID79"     "NWBIR79"   "geom"

# step 2 (get data)
system.file("gpkg/nc.gpkg", package="sf") |>
  st_read(query = "select SID74, BIR74 from 'nc.gpkg'", quiet = TRUE) |>
  head()
#>   SID74 BIR74
#> 1     1  1091
#> 2     0   487
#> 3     5  3188
#> 4     1   508
#> 5     9  1421
#> 6     7  1452
```

<sup>Created on 2022-11-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ateucher** [comment]
This is a little less manual: 

``` r
library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.2, PROJ 8.2.1; sf_use_s2() is TRUE

# step 1 (get colnames)
f <- system.file("gpkg/nc.gpkg", package="sf")

layer <- sf::st_layers(f)$name

row <- st_read(f, 
               query = paste("select * from ", sQuote(layer), "LIMIT 1"), 
               quiet = TRUE)

non_geom_cols <- names(st_drop_geometry(row))

# step 2 (get data)
query <- paste("select", 
               paste0(non_geom_cols, collapse = ", "), 
               "from", sQuote(layer))

st_read(f, query = query, quiet = TRUE) |>
  head()
#>    AREA PERIMETER CNTY_ CNTY_ID        NAME  FIPS FIPSNO CRESS_ID BIR74 SID74
#> 1 0.114     1.442  1825    1825        Ashe 37009  37009        5  1091     1
#> 2 0.061     1.231  1827    1827   Alleghany 37005  37005        3   487     0
#> 3 0.143     1.630  1828    1828       Surry 37171  37171       86  3188     5
#> 4 0.070     2.968  1831    1831   Currituck 37053  37053       27   508     1
#> 5 0.153     2.206  1832    1832 Northampton 37131  37131       66  1421     9
#> 6 0.097     1.670  1833    1833    Hertford 37091  37091       46  1452     7
#>   NWBIR74 BIR79 SID79 NWBIR79
#> 1      10  1364     0      19
#> 2      10   542     3      12
#> 3     208  3616     6     260
#> 4     123   830     2     145
#> 5    1066  1606     3    1197
#> 6     954  1838     5    1237
```

<sup>Created on 2022-11-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by defuneste** [comment]
Hi everyone! 

This started on thread in mastodon: https://fosstodon.org/web/@nibsalot/109282636089750407

One of my (bad) solution involved gdal_utils() see https://gist.github.com/defuneste/b6f121fea7a7b91fa6b110cdeaf0710f

For .shp isn't it possible to just read the `.dbf` ?

`plz_no_geom <- foreign::read.dbf(my_shp.dbf)` 

No idea how `.gdb` works. 

I feel the question is more about "Does {sf} need a function/argument that only import non geometry fields (for a lot of vector formats)?". I have no idea on that but we have a lot of vector formats.

**Comment by jkaucic** [comment]
Hello! 

ateucher's approach doesn't work for me. Seems it is not recognizing the function sQote?
Do you know what the issue is here?

`library(sf)
Linking to GEOS 3.11.2, GDAL 3.6.2, PROJ 9.2.0; sf_use_s2() is TRUE
# step 1 (get colnames)
f <- system.file("gpkg/nc.gpkg", package="sf")
layer <- sf::st_layers(f)$name
row <- st_read(f, 
                query = paste("select * from ", sQuote(layer), "LIMIT 1"), 
                quiet = TRUE)
# Error: Query execution failed, cannot open layer.
# In addition: Warning message:
# In CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
#  GDAL Error 1: In ExecuteSQL(): sqlite3_prepare_v2(select * from  ‘nc.gpkg’ LIMIT 1):
#  no such table: ‘nc.gpkg’`

**Comment by kadyb** [comment]
In `{vapour}` there is a similar feature to loading only attributes (fields) or geometry.

```r
library("vapour")
nc = system.file("shape/nc.shp", package = "sf")

geom = vapour_read_geometry_text(nc, textformat = "wkt")
att = as.data.frame(vapour_read_fields(nc))
crs = vapour_layer_info(nc)$projection$Wkt
```

**Comment by ottothecow** [comment]
I did a little benchmarking of @kadyb's suggestion on layer in an esri file geodatabase with only 15 observations, but each having a very complex polygon (intersection of a polygon and an NLCD raster converted to polygon).  I compared it to just reading the layer in with read_sf and immediately dropping the geometry.

It doesn't seem like the solution from `terra` is really an improvement, at least not with a GDB.  

```
library(microbenchmark)
library(terra)
library(sf)
library(dplyr)
microbenchmark(
  vect_version = vect(gdb_path, 'layername', what="attributes"),
  read_sf_version = read_sf(gdb_path, layer='layername') %>% st_drop_geometry() ,
  times=3
)
```

Using `terra` and only reading attributes was actually a bit slower:

```
Unit: seconds
            expr      min       lq     mean   median       uq      max neval
    vect_version 24.28122 24.47419 25.29598 24.66717 25.80336 26.93955     3
 read_sf_version 21.20094 21.43427 21.73099 21.66761 21.99602 22.32443     3
```

Maybe this is just an artifact of esri's GDB format, but it would be nice if you could just pull the data and do it much more quickly (like reading just the .dbf from a shapefile).  I find myself doing this quite often where I want the tabular data but don't really care about the geometry.  Usually it is not an issue to just drop the geometry, but SF can be quite slow reading complex geometry or large numbers of features.
