### ISSUE TITLE
Axis label not shown when using plot(sf_object)

### ISSUE THREAD

**Issue by wschwanghart** [r-spatial/sf#2034]
**Describe the bug**
Dear Edzer,
axis labels are not shown when using the command plot(sf_object). However, they are shown once you plot only the geometry (plot(st_geometry(sf_object))).

**To Reproduce**
demo(nc, ask = FALSE, echo = FALSE)
plot(nc["AREA"],axes = TRUE, xlab = 'x', ylab = 'y')
plot(st_geometry(nc),axes = TRUE, xlab = 'x', ylab = 'y')

Thanks for your great work!
Best regards, Wolfgang

**Comment by edzer** [comment]
Yes; if you want that, you have to go from
```r
plot(st_geometry(nc), xlab = "x", ylab = "y", col = 1:100)
```
and manage plotting of the key yourself. I recommend in general for maps more complex than currently provided by `plot.sf` to go either the `ggplot2::geom_sf()` way or use `tmap`. If you insist this is a bug I'd happy to document it.

**Comment by wschwanghart** [comment]
Thanks @edzer for the quick response. No need to classify this as a bug. It's just that some students in my course encountered this. For creating maps and figures, I'd use ggplot2 or tmap anyway, as you recommended.
Best regards!
