### ISSUE TITLE
Installing error from source on R 4.2.2 Windows 10

### ISSUE THREAD

**Issue by coreysparks** [r-spatial/sf#2035]
I'm trying to install sf from source in R 4.2.2 on Windows 10

install.packages("sf")

and keep getting an error 

C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lblosc
C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lkea
C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lsz

The entire output of the install command is here:
installing the source package ‘sf’

trying URL 'https://cran.rstudio.com/src/contrib/sf_1.0-9.tar.gz'
Content type 'application/x-gzip' length 3480774 bytes (3.3 MB)
downloaded 3.3 MB

* installing *source* package 'sf' ...
** package 'sf' successfully unpacked and MD5 sums checked
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs
rm -f sf.dll RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o mdim.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfc-sfg.o signed_area.o stars.o wkb.o zm_range.o
cp -r "C:/rtools42/x86_64-w64-mingw32.static.posix/share/gdal" ../inst/
cp -r "C:/rtools42/x86_64-w64-mingw32.static.posix/share/proj" ../inst/
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c bbox.cpp -o bbox.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c gdal.cpp -o gdal.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c gdal_geom.cpp -o gdal_geom.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c gdal_read.cpp -o gdal_read.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c gdal_utils.cpp -o gdal_utils.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c gdal_write.cpp -o gdal_write.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c geos.cpp -o geos.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c hex.cpp -o hex.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c mdim.cpp -o mdim.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c ops.cpp -o ops.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c polygonize.cpp -o polygonize.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c proj.cpp -o proj.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c proj_info.cpp -o proj_info.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c raster2sf.cpp -o raster2sf.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c sfc-sfg.cpp -o sfc-sfg.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c signed_area.cpp -o signed_area.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c stars.cpp -o stars.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c wkb.cpp -o wkb.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -DHAVE_PROJ_H -I'C:/Program Files/R/R-4.2.2/library/Rcpp/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c zm_range.cpp -o zm_range.o
g++ -shared -s -static-libgcc -o sf.dll tmp.def RcppExports.o bbox.o gdal.o gdal_geom.o gdal_read.o gdal_utils.o gdal_write.o geos.o hex.o mdim.o ops.o polygonize.o proj.o proj_info.o raster2sf.o sfc-sfg.o signed_area.o stars.o wkb.o zm_range.o -lgdal -lblosc -lkea -lhdf5_cpp -lhdf5 -lpoppler -llcms2 -lfreetype -lharfbuzz -lfreetype -llz4 -lpcre2-8 -lxml2 -lopenjp2 -lnetcdf -lmysqlclient -lspatialite -lgeos_c -lgeos -lminizip -lgeos -ljson-c -lgta -lfreexl -lexpat -lssl -lpsapi -lgif -lmfhdf -lhdf5_hl -lcrypto -lportablexdr -ldf -lhdf5 -lsz -lpng16 -lpng -lpoppler -llcms2 -lfreetype -lharfbuzz -lfreetype -llz4 -lpcre2-8 -lpcre -lcurl -lrtmp -lssl -lssh2 -lidn2 -lunistring -liconv -lgcrypt -lcrypto -lgpg-error -lws2_32 -ltiff -llzma -ljpeg -lz -lcfitsio -lzstd -lwebpdecoder -lwebp -lsbml-static -lgeotiff -lproj -lsqlite3 -lbz2 -lcrypt32 -lwldap32 -lsecur32 -LC:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64 -LC:/rtools42/x86_64-w64-mingw32.static.posix/lib -LC:/PROGRA~1/R/R-42~1.2/bin/x64 -lR
C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lblosc
C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lkea
C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: cannot find -lsz
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'sf'
* removing 'C:/Program Files/R/R-4.2.2/library/sf'
* restoring previous 'C:/Program Files/R/R-4.2.2/library/sf'
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status

<details>
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] lattice_0.20-45  R6_2.5.1         grid_4.2.2       lifecycle_1.0.3  DBI_1.1.3       
 [6] survey_4.1-1     scales_1.2.1     rlang_1.0.6      carData_3.0-5    cli_3.4.1       
[11] rstudioapi_0.14  car_3.1-1        Matrix_1.5-1     splines_4.2.2    tools_4.2.2     
[16] munsell_0.5.0    xfun_0.34        abind_1.4-5      survival_3.4-0   compiler_4.2.2  
[21] colorspace_2.0-3 mitools_2.4      knitr_1.40      

sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
       "3.9.1"        "3.4.3"        "7.2.1"         "true"         "true"        "7.2.1" 
</details>

**Comment by rsbivand** [comment]
You need a newer Rtools, yours does not have the new libraries added to support newer drivers in GDAL. You could locally edit out the missing libraries from src/Makevars.ucrt (sf 1.0-9).

**Comment by rsbivand** [comment]
See the Rtools log here https://cran.r-project.org/bin/windows/Rtools/rtools42/news.html, you need https://cran.r-project.org/bin/windows/Rtools/rtools42/files/rtools42-5355-5357.exe.

**Comment by coreysparks** [comment]
Great, that sorted it out, thank you
