### ISSUE TITLE
st_read() produces  "geom"  column reading from geopackage but "geometry" column from shapefile

### ISSUE THREAD

**Issue by nevilamos** [r-spatial/sf#2045]
The  name of the geometry field changes depending on whether  data is read from shapefile or gpkg  This is a problem when used in a way that accepts either as an iput and the geometry column later needs to be referred to ( by name).

nc_sql = st_geometry(st_read(system.file("shape/nc.shp", package="sf")))
names(nc_sql)
st_write(nc_sql,dsn ="test.gpkg")
test<-st_read("test.gpkg")
names(test)

**Comment by rCarto** [comment]
See https://github.com/r-spatial/sf/issues/1847.

**Comment by nevilamos** [comment]
thanks for the link
