### ISSUE TITLE
Feature Request: st_make_grid() support geographic CRS for grids specified in other units [m]

### ISSUE THREAD

**Issue by SebKrantz** [r-spatial/sf#2051]
It would be great to be able to create accurate fixed-area grids over large spatial geometries (continents). The current requirement to cast geographic to a projected CRS to be able to specify a grid size in meters limits the usefulness of the function for large scale spatial analysis. I have also opened an [question on Stackoverflow](https://stackoverflow.com/questions/74655449/creating-an-equal-area-spatial-grid-over-a-large-area-r-or-python) where I am curious about other software solutions. There I also calculate an error of 2.8% induced by using a projected CRS to create a 12km grid across the African continent. This is too large for accurate analysis at this scale.

**Comment by edzer** [comment]
You may want to look into the dggridr package, now archived from CRAN but still available when you can install from source: https://cran.r-project.org/web/packages/dggridR/index.html ; since you're cross posting feel free to pass this on to SO.

**Comment by edzer** [comment]
As an alternative, I created a rectilinear grid [here](https://edzer.github.io/rstudio_conf/2019/#18) with approximately equal size (gridcell height depending on latitude), and could dig up the code for that if that is of interest.

**Comment by SebKrantz** [comment]
Thanks, the dggridR package appears to be a good solution, although I cannot get exactly the 12km2 area I wanted but hexagons of 95km2 (resolution 12).

```
library(dggridR)
dgg_10km <- dgconstruct(area = 144, metric = TRUE, resround = "nearest") # creates gid with 
africa_10km_hex <- dgrectgrid(dgg_10km, minlon = -26, minlat = -36, maxlon = 55, maxlat = 38, frame = FALSE)
africa_10km_hex_sf <- st_as_sf(africa_10km_hex)
```
I can close the request if you like, but would of course be nice to have at least some kind of rectilinear approximation built into `st_make_grid()` allowing operation with geographic CRS.

**Comment by edzer** [comment]
I think you can do this with `st_as_stars()` method for `bbox` objects (package stars), then `st_as_sf()` or `st_as_sfc()` to convert to sf.
