### ISSUE TITLE
 SingleSide ignored when using st_buffer  

### ISSUE THREAD

**Issue by Brandkmayer** [r-spatial/sf#2055]
I saw that the singleSide feature was added [here](https://github.com/r-spatial/sf/issues/1001). When using the feature with lat/long the singleSide appears to not work. 

This was noted on stackexchange [here](https://gis.stackexchange.com/questions/445187/sfst-buffer-singleside-not-working-as-expected) where Dbaston answered that "the singleSide argument is ignored when the s2 library is used to do the buffering." He recommended using sf_use_s2(FALSE) but included "Note that GEOS will interpret dist to be in degrees rather than meters."

Is there a way to remedy?

**Comment by edzer** [comment]
> Is there a way to remedy?

Not an easy one - afaict the s2geometry library does not have this feature.
