### ISSUE TITLE
Shift longitude from 0,360 to -180,180?

### ISSUE THREAD

**Issue by fabeit** [r-spatial/sf#2058]
I know the function st_shift_longitude, but I actually want to do the opposite of what this function does. Is there a specular function?
Related to this question
https://stackoverflow.com/questions/71929397/how-to-change-map-projection-from-pacific-to-atlantic-centered

I have found st_wrap_dateline but can't find any specific documentation. So when I use wrap_deadline and after I use exact_extract I get "error in CPP_stats(x, x_ext, x_res, weights, wkb, default_value, default_weight,  : 
  Error getting geometry extent." So wrap_deadline is messing something up in the original shapefile.

**Comment by dbaston** [comment]
The only reason I can think of for receiving this error is that one of the geometries is empty.

You can shift your geometries with `lwgeom::st_wrap_x`.

**Comment by fabeit** [comment]
@dbaston thank you for the suggestion. Before using wrap_deadline I have no issues with exact_extract with the same sf. I will try with st_wrap_x and see what happens.

**Comment by fabeit** [comment]
@dbaston I am trying to figure out how to use that function, the help file is a bit cryptic, could you please help? I just want to have -180,180 instead of 0,360

**Comment by dbaston** [comment]
```
library(rnaturalearth)
library(sf)
library(lwgeom)

x <- st_as_sf(ne_countries())
plot(st_geometry(x))
```
![image](https://user-images.githubusercontent.com/6318931/207918358-6caa18ca-f1d7-40e9-bd6a-256f058d7580.png)
```
# Shift from -180 - 180 to 0 - 360
# cutline at x = 0
# move things to the left of the cutline by 360
x360 <- st_wrap_x(x, 0, 360)
plot(st_geometry(x360))
```
![image](https://user-images.githubusercontent.com/6318931/207918396-924bf2f2-48f3-467f-a47c-e5df7b6ca34f.png)

```
# Shift from 0 - 360 to -180 - 180
# cutline at x = 180
# move things to the left of the cutline by 360
# then move everything left by 360
z <- st_wrap_x(x360, 180, 360)
st_geometry(z) <- st_geometry(z) - c(360, 0)
plot(st_geometry(z))
```

![image](https://user-images.githubusercontent.com/6318931/207918490-074a5a73-f7ce-4b5f-89a7-2b332142729a.png)
