### ISSUE TITLE
st_distance does not recycle y when by_element = TRUE in 1.0.9

### ISSUE THREAD

**Issue by majr-red** [r-spatial/sf#2062]
From [the `st_distance` documentation](https://r-spatial.github.io/sf/reference/geos_measures.html):

>If by_element is FALSE
>st_distance returns a dense numeric matrix of dimension length(x) by length(y); <i>otherwise it returns a numeric vector of length x or y, the shorter one being recycled.</i>

(my italics) This was the behaviour in 1.0.8, but in 1.0.9 if `by_element = TRUE` then supplying unequal length x and y arguments produces an error. This appears to be because v1.0.9 includes:

```R	
if (by_element)
		stopifnot(!missing_y, length(x) == length(y))
```
Is this now the desired behaviour (and so the documentation needs updating), or a bug?

``` r
# remotes::install_version("sf", version = "1.0.9",
#                          dependencies = "Depends",
#                          upgrade = "never"
# )

library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 7.2.1; sf_use_s2() is TRUE
packageVersion("sf")
#> [1] '1.0.9'

pt_a <- st_point( c(0, 1) )
pt_b <- st_point( c(1, 0) )

x <- st_sf(geom = st_sfc(pt_a, pt_b),
           placename = c("a", "b"))

y <- st_sf(geom = st_sfc( st_point( c(2, 3) )),
           placename = c("c"))

st_distance(x, y, by_element=TRUE)
#> Error in st_distance(x, y, by_element = TRUE): length(x) == length(y) is not TRUE

sessionInfo()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows Server x64 (build 14393)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United Kingdom.1252 
#> [2] LC_CTYPE=English_United Kingdom.1252   
#> [3] LC_MONETARY=English_United Kingdom.1252
#> [4] LC_NUMERIC=C                           
#> [5] LC_TIME=English_United Kingdom.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] sf_1.0-9
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.9         pillar_1.8.1       compiler_4.1.2     highr_0.9         
#>  [5] class_7.3-19       R.methodsS3_1.8.2  R.utils_2.12.0     tools_4.1.2       
#>  [9] digest_0.6.29      evaluate_0.18      lifecycle_1.0.3    tibble_3.1.8      
#> [13] R.cache_0.16.0     pkgconfig_2.0.3    rlang_1.0.6        reprex_2.0.2      
#> [17] cli_3.4.1          DBI_1.1.3          rstudioapi_0.14    yaml_2.3.6        
#> [21] xfun_0.34          fastmap_1.1.0      e1071_1.7-11       dplyr_1.0.10      
#> [25] withr_2.5.0        styler_1.7.0       stringr_1.4.1      knitr_1.40        
#> [29] generics_0.1.3     fs_1.5.2           vctrs_0.5.0        tidyselect_1.2.0  
#> [33] grid_4.1.2         classInt_0.4-8     glue_1.6.2         R6_2.5.1          
#> [37] fansi_1.0.3        rmarkdown_2.18     purrr_0.3.4        magrittr_2.0.3    
#> [41] units_0.8-0        htmltools_0.5.3    assertthat_0.2.1   KernSmooth_2.23-20
#> [45] utf8_1.2.2         stringi_1.7.8      proxy_0.4-27       R.oo_1.25.0

sf::sf_extSoftVersion()
#>           GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
#>       "3.10.2"        "3.4.1"        "7.2.1"         "true"         "true" 
#>           PROJ 
#>        "7.2.1"
```

<sup>Created on 2022-12-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by edzer** [comment]
What would be the advantage over just using `by_element = FALSE`?

**Comment by majr-red** [comment]
You're right, of course - the case where one needs to calculate distances between a vector of locations and a single point is covered by `by_element = FALSE`.  Sorry, that was a bad example.

But what I really want to know, so that I can fix my own code, is whether the intention is that this function should no longer recycle the shorter vector when `x` and `y` are of unequal length.

**Comment by edzer** [comment]
I think the current documentation of `by_element=TRUE`, " if TRUE, return a vector with distance between the first elements of x and y, the second, etc", _implies_ that `x` and `y` need to have equal length.

**Comment by majr-red** [comment]
Perhaps, but the value section specifically states:

> If by_element is FALSE
> st_distance returns a dense numeric matrix of dimension length(x) by length(y); otherwise it returns a numeric vector of length x or y, the shorter one being recycled.

And previous versions _did_ accept vectors of unequal lengths.
