### ISSUE TITLE
plot.sf() does not draw legend even if parameters "break" and "pal" are set

### ISSUE THREAD

**Issue by bfakos** [r-spatial/sf#2065]
plot.sf() does not draw legend when the dataset contains only one unique value. It is OK if parameters "break" and "pal" are not set. But if the user set "breaks" and "pal" (and "key.pos"), it means that s/he surely want to see the legend.
I usually plot sf objects by iteraing through the columns, and use the same parameterization (width/height/res) of the device and the same parameterization (breaks, pal, key.pos) of plot(). In this case, I obviously assume that I will get images with the same arrangement, and it is unexpected that the legend is missing from some of the images. 
So I think that L220 of plot.R should be changed from
length(col) > 1) { # plot key?
to
((!is.null(pal) && is.numeric(breaks)) || length(col) > 1)) { # plot key?

**Comment by edzer** [comment]
Thanks, good suggestion!
