### ISSUE TITLE
/services/tools/gcc/7.2.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by B-1991-ing** [r-spatial/sf#2066]
Dear sf support team,

I am installing the package --- "sf", but not succeeded yet.

**Installation**
install.packages("sf", configure.args = "--with-proj-include=/usr/include --with-proj-lib=/usr/lib --with-proj-api=no")

**Error occurred when installing the packages --- s2 and sf.**
<img width="757" alt="Screenshot 2022-12-17 at 19 42 25" src="https://user-images.githubusercontent.com/54441633/208256775-13895f61-6c84-425f-acaa-b8f4fcd4f181.png">

<img width="756" alt="Screenshot 2022-12-17 at 19 43 04" src="https://user-images.githubusercontent.com/54441633/208256796-8cc8a814-7ebb-4d99-8696-b2729662336e.png">

RStudio Server version (which can't be changed due to it is the HPC setting)
rstudio1.3.1073-R.4.0.0-install

Could you give some suggestion?

Best,

Bing

**Comment by edzer** [comment]
looks like a problem with compiler versions (possibly a mix?) on your system.

**Comment by B-1991-ing** [comment]
Yeah. 

Under the directory --- /services/tools/gcc/7.2.0/lib64/libstdc++.so.6, there are **multiple versions of libstdc++**.
<img width="1103" alt="Screenshot 2022-12-18 at 20 41 16" src="https://user-images.githubusercontent.com/54441633/208316088-605445e8-d3f2-449f-b144-46b27f5831df.png">
