### ISSUE TITLE
[feature request] preserve area and other units in `st_interpolate_aw`

### ISSUE THREAD

**Issue by DSLituiev** [r-spatial/sf#2068]
currently `st_interpolate_aw` calls `unclass` to remove units. 
Keeping units may be desirable to be able to have a sensible output for both intensive and extensive inputs

Lines where `unclass` is called:

https://github.com/r-spatial/sf/blob/main/R/aggregate.R#L140
https://github.com/r-spatial/sf/blob/main/R/aggregate.R#L144

**Comment by edzer** [comment]
What should be done if the variable that is interpolated has no units?

**Comment by edzer** [comment]
Units on areas cancel out, so removing them in the computations has the same effect as leaving them in. Output variables have identical units to inputs, regardless of extensive/intensive.

**Comment by DSLituiev** [comment]
So I may not be getting the point of extensive mode, which thus may require a better documentation and examples. Would it be OK to reopen the issue please till this is resolved?

Let's say I have population per region, which is an extensive property. Now, when I plot it in extensive mode, the number that is returned in each (grid) polygon is interpolated population (number of people) within that polygon. Where it gets nuanced, that is pragmatics requiring another step further than pure theory, is that for such a visualization it would be theoretically OK to provide a scale bar with dimensionality of "number of people". 

However on pragmatic level, presenting "number of people" per arbitrary grid unit is not as useful. Thus I would assume that the "extensive" mode would handle area normalization `extensive -> intensive`. Please correct me if you see any other application where `extensive -> extensive` mapping makes pragmatic sense while interpolating on a grid. If there is such, it would be good to include into documentation

**Comment by edzer** [comment]
Extensive variables are essentially redistributed, not interpolated. You have # persons per area, then you go to other areas (e.g. grid cells), and get the # of persons per new area. That doesn't make the variable intensive. Computing population density by dividing # over the area creates an intensive variable.

**Comment by DSLituiev** [comment]
Yes, I understand that this is the behaviour of the system. My question is 

(1)  are there practical examples where such behaviour would be desirable / would make sense? Can such examples be added to documentation
(2) if no such practical cases exist, would it be best for the extensive mode take extensive variable and return an intensive one instead?

**Comment by edzer** [comment]
I think there is a wide agreement that choropleth maps should show population density rather than population counts.  You can compute those by dividing the count over the area, you do not need to do any area-weighted interpolation for that. Given population density, you can do area-weighted interpolation treating it as an intensive variable.

**Comment by DSLituiev** [comment]
ok. So sounds like there is not much use for mapping of `extensive (native geometry) --> extensive (grid)`. More often so, it is `extensive (native geometry) --> intensive (grid)`. I would suggest to make that point in documentation and maybe make a default functionality of `extensive=T` to map extensive input to intensive output
