### ISSUE TITLE
Arch Linux installation dependencies change

### ISSUE THREAD

**Issue by steveb-123** [r-spatial/sf#2072]
This is a documentation rather than code issue for now.

I am not exact sure the reason but currently, on Arch Linux, two further packages are required for proper function: `podofo` and `arrow`. Both are available from the normal community repo, not AUR. It seems like they are used by `gdal` but are not currenly pulled in as depencies.

Without these extra packages, these errors are raised for me on installation of `sf` from cran:

```
Warning in CPL_gdal_init() :
  GDAL Error 1: libarrow_dataset.so.1000: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libarrow_dataset.so.1000: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libarrow.so.1000: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libarrow.so.1000: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libpodofo.so.0.9.8: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libpodofo.so.0.9.8: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libarrow_dataset.so.1000: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libarrow_dataset.so.1000: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libarrow.so.1000: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libarrow.so.1000: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libpodofo.so.0.9.8: cannot open shared object file: No such file or directory
Warning in CPL_gdal_init() :
  GDAL Error 1: libpodofo.so.0.9.8: cannot open shared object file: No such file or directory
```

Updating the Arch installation instructions line in README from:

`pacman -S gdal proj geos`

to 

`pacman -S gdal proj geos arrow podofo`

should correct things for now.

Apologies I cannot submit the change myself right now from this machine.

**Comment by jannes-m** [comment]
More or less a week ago I also needed to install arrow to make the mentioned warning messages disappear. I didn't install podofo but maybe it had been already installed on my computer. I can't check this right now since I left my laptop at home while being away with my family 😊
