### ISSUE TITLE
`replace()` failing with simple feature objects

### ISSUE THREAD

**Issue by dimfalk** [r-spatial/sf#2073]
I'm not 100 % sure if this is a bug or maybe expected behaviour I do not understand (yet), but recently I tried replacing all NA placeholder values present in an attribute table with actual NA values and failed. However, since this seems to be working on tibbles without a geometry column without issues, I somehow expected this to work on sf objects, too... But maybe this is where I'm wrong.

Example:

``` r
library(sf)
#> Linking to GEOS 3.9.3, GDAL 3.5.2, PROJ 8.2.1; sf_use_s2() is TRUE

nc_sf <- system.file("shape/nc.shp", package="sf") |> sf::read_sf()

nc_sf["foo"] <- -99.9
nc_sf <- nc_sf[c("NAME", "foo")]

# this fails
replace(nc_sf, nc_sf == -99.9, NA)
#> Error:
#> ! Subscript `list` is a matrix, it must be of type logical.

#> Backtrace:
#>     ▆
#>  1. └─base::replace(nc_sf, nc_sf == -99.9, NA)
#>  2.   ├─base::`[<-`(`*tmp*`, list, value = `<lgl>`)
#>  3.   └─tibble:::`[<-.tbl_df`(`*tmp*`, list, value = `<lgl>`)
#>  4.     └─tibble:::tbl_subassign_matrix(x, j, value, j_arg, substitute(value))
#>  5.       └─tibble:::matrix_to_cells(j, x, j_arg)
#>  6.         └─rlang::cnd_signal(error_subset_matrix_must_be_logical(j_arg))

nc_tbl <- sf::st_drop_geometry(nc_sf)

# this works
replace(nc_tbl, nc_tbl == -99.9, NA)
#> # A tibble: 100 × 2
#>    NAME          foo
#>    <chr>       <dbl>
#>  1 Ashe           NA
#>  2 Alleghany      NA
#>  3 Surry          NA
#>  4 Currituck      NA
#>  5 Northampton    NA
#>  6 Hertford       NA
#>  7 Camden         NA
#>  8 Gates          NA
#>  9 Warren         NA
#> 10 Stokes         NA
#> # … with 90 more rows
```

<sup>Created on 2022-12-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thank you very much in advance!

**Comment by edzer** [comment]
If you look at what `replace` does:
```r
> replace
function (x, list, values) 
{
    x[list] <- values
    x
}
```
you're actually trying to do
```
nc_tbl[nc_tbl == -99.9] = NA
```
so you're looking for equality of _all_ of the values in `nc_tbl` to -99.9, including the geometries. Doing this for geometries however does not make sense, and what you get back is no longer a matrix of mode `logical` but a matrix of mode `list`, and that matrix doesn't work in `[<-.data.frame` (or `.tbl`), which is what you're calling next. So you can't expect this to work for tables with list columns, such as `sf` objects. You'll have to work through the atomic vectors in another way.

**Comment by edzer** [comment]
If you look at what `replace` does:
```r
> replace
function (x, list, values) 
{
    x[list] <- values
    x
}
```
you're actually trying to do
```
nc_tbl[nc_tbl == -99.9] = NA
```
so you're looking for equality of _all_ of the values in `nc_tbl` to -99.9, including the geometries. Doing this for geometries however does not make sense, and what you get back is no longer a matrix of mode `logical` but a matrix of mode `list`, and that matrix doesn't work in `[<-.data.frame` (or `.tbl`), which is what you're calling next. So you can't expect this to work for tables with list columns, such as `sf` objects. You'll have to work through the atomic vectors in another way.

**Comment by dimfalk** [comment]
Thanks for hinting at the acutal code of `replace()` and your clarification - was not aware of these differences, to be honest, but yeah, applying replacements on geometries does not make any sense. I hoped they would be excluded from this operation somehow and that the function would only apply on actual attributes appended...

Think I'll go for a workaround including `st_geometry()`, `st_drop_geometry()` and `st_set_geometry()` then.
