### ISSUE TITLE
Feature request: option to exclude fields in st_read

### ISSUE THREAD

**Issue by bfakos** [r-spatial/sf#2074]
I regularly read spatial data files (e.g. shapefiles) just because I need the geometry. For this, I call st_geometry(st_read()). This is unnecessarily time-consuming and memory-demanding for large files containing several fields, and it would be nice if a read_sfc() function exists similarly to read_sf(), or an extra logical argument is added to st_read().
E.g.
- st_read(fields = TRUE) would be the default parameterization/behaviour, and
- st_read(fields = FALSE) would read only the goematry and return an sfc object.

**Comment by edzer** [comment]
Have you looked into the `query` argument of `st_read()`?

**Comment by edzer** [comment]
This
```r
library(sf)
system.file("gpkg/nc.gpkg", package = "sf") |>
  read_sf(query = "select FID,geom from 'nc.gpkg'") |>
  st_as_sfc()
```
doesn't read any fields; it assumes you know the name of the geometry column and layer; for a shapefile this works:
```r
system.file("shape/nc.shp", package = "sf") |>  
  read_sf(query = "select FID from nc") |>             
  st_as_sfc()
```

**Comment by bfakos** [comment]
Thanks, Edzer, for the workaround. I guess that several users of sf do not know the name of the geometry column and/or are not familiar with the SQL syntax (which might be dependent on the file format). For those less advanced users it would be a nice feature if the st_read() could do the trick.

**Comment by rsbivand** [comment]
This is not about less-advanced users. It is about reading the dpcumentation, which should always be the first step. https://r-spatial.github.io/sf/reference/st_read.html describes the `query=` argument, and the examples include its use. More arguments mean more unit testing/code coverage, possibly factorial in the argument count.

**Comment by bfakos** [comment]
Thanks, Roger, I see your point. However, neither of the parameter description, the Details section or the Examples mention this specific (but important) case. I suggest including a sentence about "SELECT FID FROM" in the Details and/or Examples.
