### ISSUE TITLE
Cannot install sf package with proj6 - proj_normalize_for_visualization

### ISSUE THREAD

**Issue by whositwhatnow** [r-spatial/sf#2083]
CentOS7, R 4.2.1, proj 6.0.0/geos/3.11 gdal/3.5.1 installing sf via cran

I am getting error:

proj.cpp: In function ‘Rcpp::NumericMatrix CPL_proj_direct(Rcpp::CharacterVector, Rcpp::NumericMatrix, bool, bool, bool)’:
proj.cpp:281:28: error: ‘proj_normalize_for_visualization’ was not declared in this scope
  281 |                 PJ *NewP = proj_normalize_for_visualization(PJ_DEFAULT_CTX, P);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [proj.o] Error 1
ERROR: compilation failed for package ‘sf’

**Comment by rsbivand** [comment]
It is not in PROJ 6.0.0 but is in PROJ 6.1.0. I suggest installing a much newer PROJ if need be from source.

**Comment by edzer** [comment]
Did you try the same as before? https://github.com/rspatial/terra/issues/971

**Comment by whositwhatnow** [comment]
> Did you try the same as before? [rspatial/terra#971](https://github.com/rspatial/terra/issues/971)

I did, and thats how I got to that error above

**Comment by whositwhatnow** [comment]
> 

I'll try it with what you recommended and update

**Comment by whositwhatnow** [comment]
> 

I'll try your recommendation and post update

**Comment by whositwhatnow** [comment]
Solution for me:

- install via source Proj6.1.1
- recompile gdal linking proj 6.1.1 lib
- PKG_CONFIG_PATH=/cm/shared/apps/proj6/6.1.1/lib/pkgconfig/ R
- Then install.packages("sf", configure.args = c("--with-proj-lib=/cm/shared/apps/proj6/6.0.0/lib/"))

Thank you @rsbivand
