### ISSUE TITLE
pivot_longer.sf is not exported

### ISSUE THREAD

**Issue by courtiol** [r-spatial/sf#2085]
I noticed that `pivot_longer.sf()` is not exported while `pivot_wider.sf()` is:

https://github.com/r-spatial/sf/blob/49521ce04502fa2325267cf19bc1419fefb3d6da/R/tidyverse.R#L361-L376

https://github.com/r-spatial/sf/blob/49521ce04502fa2325267cf19bc1419fefb3d6da/R/tidyverse.R#L410-L423

I have read old posts about some `pivot_longer.sf()` issues related to ever changing tidyverse, so perhaps this is done on purpose, but in case it is not, I would be glad if you could add the missing `#' @export` between line 361 and 362 in tidyverse.R.

Thanks,
Alex

**Comment by edzer** [comment]
```r
> library(sf)
Linking to GEOS 3.11.1, GDAL 3.6.2, PROJ 9.1.1; sf_use_s2() is TRUE
> library(tidyr)
> methods(pivot_longer)
[1] pivot_longer.data.frame* pivot_longer.sf*        
see '?methods' for accessing help and source code
```
This happens on line 638: we don't export the function, we export the method when `tidyr` is or gets attached. Otherwise you'd have to call it as `pivot_longer.sf(...)` instead of `pivot_longer(...)`.

**Comment by courtiol** [comment]
OK, I understand. Perhaps the two pivot functions should be deal with similarly in any case since what confused me is having access to one and not the other (without loading tidyr).
