### ISSUE TITLE
Document cast multipolygon -> linestring uses exterior ring only

### ISSUE THREAD

**Issue by JosiahParry** [r-spatial/sf#2102]
Request: Document that casting MULTIPOLYGON to LINESTRING casts _only the exterrior ring_. 

Summary: Casting a MULTIPOLYGON to a LINESTRING extracts only the exterior ring and converts that to a LINESTRING. This unique aspect is not documented except from this warning. I have never noticed this warning until searching source code. I think this is because sfg objects are printed with `message()` and the `warning()` emits the same color in a blob of text in the console (see image below). In my programming fervor I see blue and thing success but perhaps that is a miscommunication due to the printing method of sfg objects.

Below the first screenshot I've included a second where I modified the `print.sfg` method to use `cat()` rather than `message()`. Note how much easier it is to see the warning....oh dear i've gone cross-eyed.

https://github.com/r-spatial/sf/blob/b798413d4cd681cd173f9bdc110f2a014555ee09/R/cast_sfg.R#L96

<img width="805" alt="image" src="https://user-images.githubusercontent.com/13534508/220360574-69fa4b61-6de3-4016-a186-af9a15465215.png">

<img width="803" alt="image" src="https://user-images.githubusercontent.com/13534508/220361145-7ff26587-ab2f-4ca3-a5c5-f808ffd4fc1a.png">

**Comment by edzer** [comment]
`message()` can be suppressed by the user, `cat()` afaict not (without using `sink()`).

**Comment by JosiahParry** [comment]
Not to entirely deviate from the purpose of the issue (documentation) but I can't help myself–I enjoy the pedantry.

I don't think printed objects are intended to be suppressed. Here's a reprex that looks at all the base types I can think of and encapsulates the print method of each in a `suppressMessages()` call.

``` r
suppressMessages({
  
  print(numeric(1))
  print(integer(1))
  print(character(1))
  print(logical(1))
  print(raw(1))
  print(head(iris))
  print(as.list(head(iris)))
  
  pnt <- sf::st_point(c(45, 45))
  print(pnt)
})
#> [1] 0
#> [1] 0
#> [1] ""
#> [1] FALSE
#> [1] 00
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2  setosa
#> 2          4.9         3.0          1.4         0.2  setosa
#> 3          4.7         3.2          1.3         0.2  setosa
#> 4          4.6         3.1          1.5         0.2  setosa
#> 5          5.0         3.6          1.4         0.2  setosa
#> 6          5.4         3.9          1.7         0.4  setosa
#> $Sepal.Length
#> [1] 5.1 4.9 4.7 4.6 5.0 5.4
#> 
#> $Sepal.Width
#> [1] 3.5 3.0 3.2 3.1 3.6 3.9
#> 
#> $Petal.Length
#> [1] 1.4 1.4 1.3 1.5 1.4 1.7
#> 
#> $Petal.Width
#> [1] 0.2 0.2 0.2 0.2 0.2 0.4
#> 
#> $Species
#> [1] setosa setosa setosa setosa setosa setosa
#> Levels: setosa versicolor virginica
```

<sup>Created on 2023-02-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
