### ISSUE TITLE
st_cast 'LINESTRING' to 'MULTIPOLYGON'

### ISSUE THREAD

**Issue by sv-pnnl** [r-spatial/sf#2103]
I have been using fishnet to intersect with polygon. But that has resulted in 'LINESTRINGS' also. This is making it impossible to cast the intersection to 'MULTIPOLYGON'. See code and error below:

Code:
st_intersection(polys, fishnet) %>% 
  st_cast("MULTIPOLYGON")

Error in ClosePol(unclass(x)) : polygons require at least 4 points
In addition: Warning messages:
1: attribute variables are assumed to be spatially constant throughout all geometries 
2: In st_cast.GEOMETRYCOLLECTION(X[[i]], ...) :
  only first part of geometrycollection is retained
3: In st_cast.GEOMETRYCOLLECTION(X[[i]], ...) :
  only first part of geometrycollection is retained

Any suggestion in this regard?

**Comment by edzer** [comment]
`st_collection_extract()`

**Comment by sv-pnnl** [comment]
Thanks. Is there a way to remove (or transform) the linestring and point from the st_intersection?

**Comment by sv-pnnl** [comment]
Awesome. Thanks.
