### ISSUE TITLE
Big `sf` objects

### ISSUE THREAD

**Issue by fgoerlich** [r-spatial/sf#2107]
Hi,
Is it possible to use [`dtplyr`](https://dtplyr.tidyverse.org/), that uses [`data.table`](https://rdatatable.gitlab.io/data.table/) under the hood, or [`multidplyr`](https://multidplyr.tidyverse.org/index.html), that uses parallel computation on `tibbles`, to perform operations on `sf`?
Thanks a lot.

**Comment by rsbivand** [comment]
Which operations? Those that would apply to any columnar table should be supported, but ones that depend on the specific quality of spatial data, that the position of each row's geometry is related to the position of other observations (topological predicates and operations) are more problematic. Both GEOS and s2geometry use fast spatial indexing (for the planar and spherical cases respectively).

**Comment by kadyb** [comment]
Here are two great tutorials:
1. [data.table + geos](https://grantmcdermott.com/fast-geospatial-datatable-geos/)
2. [collapse](https://sebkrantz.github.io/collapse/articles/collapse_and_sf.html) as alternative to data.table

But note that the main speedup is related to data frame processing, not the spatial aspect. Faster alternative to `{sf}` for planar geometry is direct binding to [geos](https://github.com/paleolimbot/geos/), but unfortunately, it isn't parallelized either.
