### ISSUE TITLE
Why st_segmentize function produces a layer which is identicall to the input layer

### ISSUE THREAD

**Issue by momeni133** [r-spatial/sf#2111]
Hello,
I am using st_segmentize function to split a line layer into multiple lines with a specific length.
Data can be downloaded from here: https://www.fhwa.dot.gov/policyinformation/hpms/shapefiles/california2017.zip
the code that I use is: 
data <- st_read("path to the data")
data <- st_transform(data, 3857) # reprojecting the data
data <- st_zm(data) # removing the z dimention

split <- st_segmentize(data,50)

**Comment by edzer** [comment]
`st_segmentize` doesn't split a line, but adds nodes on straight line pieces between existing nodes. This is helpful if a line is straight in one CRS, and appears straight after projection where it should in fact look curved.

**Comment by momeni133** [comment]
Thank you very much for your quick response. Is there any functions that I
can split a sf line into multiple shorter lines with defined max length?

**Comment by edzer** [comment]
@Robinlovelace didn't you have something for this?

**Comment by jannes-m** [comment]
You could use GRASS's v.split function for that, see https://grass.osgeo.org/grass82/manuals/v.split.html. Should be accessible via **qgisprocess**, see https://github.com/paleolimbot/qgisprocess

**Comment by LDalby** [comment]
I also had to split lines into segments  a while ago and I also ended with a qgisprocess solution as suggested by @jannes-m.
I looked something like this:
```r
split_transects <- function(transect_lines, length) {
  result <- qgisprocess::qgis_run_algorithm(
    "native:splitlinesbylength",
    INPUT = transect_lines,
    LENGTH = length,
    OUTPUT = tempfile(fileext = ".fgb"),
    .quiet = TRUE
  )
  segments <- sf::read_sf(qgisprocess::qgis_output(result, "OUTPUT"))
  return(segments)
}
```
Perhaps this could be useful for you @momeni133.

**Comment by momeni133** [comment]
Hi everyone,
Thanks for your suggestions! It is very helpful. Actually, I
tried qgis_splitlinesbylength before, but I was looking for an alternative
approach which runs faster. Yesterday, I found the "wbt_split_vector_lines"
function from the whitebox package which is weirdly fast! It solved the
problem for now, but it would be nice if we see such a function native in
sf as well.

**Comment by Robinlovelace** [comment]
> @Robinlovelace didn't you have something for this?

Yes I had something for this and it's in `{stplanr}`. The `qgisprocess` calling to GRASS is the fastest by a long way that I have tried.

**Comment by Robinlovelace** [comment]
See details here: https://github.com/paleolimbot/qgisprocess/issues/26

**Comment by edzer** [comment]
Here's a pure R function, with example; no idea about its performance:
```r
library(rmapzen)
library(sf)
# Linking to GEOS 3.11.1, GDAL 3.6.2, PROJ 9.1.1; sf_use_s2() is TRUE
roads <- as_sf(ca_tiles$roads)
# Registered S3 method overwritten by 'geojsonsf':
#   method        from   
#   print.geojson geojson
nrow(roads)
# [1] 80
roads |>
  st_geometry() |> 
  st_cast("MULTILINESTRING") |> 
  st_cast("LINESTRING") -> ls
sapply(ls, nrow) # nr of nodes per LINESTRING
#   [1]  8  2  7  3  5  2  4  4  5  3  7  3  3 15  5  2  4  2  4  5  2  2  6  2  4
#  [26]  3  2  3  2  4  3  4  7  5  5  2  3  2  4  3  4  2  3  2  5  5  4  4  2  2
#  [51]  3  4  5  2  4  4  3  4  2  3  2  2  2  3  5  3  4  4 12  5  4  3  3 20  2
#  [76]  2  8  4  6  2  3  4  4  2  3  2  2  7  4  2  7 32 12  4  7  2  4  9  4 12
# [101]  3  2  6  9  4  2  3  2  2 11  3  3  2 23  3  4  2  3  3  5  3  5  2  5  2
# [126]  7  5  4  2  5  4  2  2  2 10  4  6  4  6  4  2  9  4  8  4  2  6  9  4  2
# [151]  9  2  9  7  5  4  8  6  5  2  2  3  3  9  8  8 16 11 27  3 29  4 74  7 11
# [176]  8  4 12  6  2 10  5  2  2  2 25  7  2  4  2  2  3  3 20  2 25  6  5 25  6
# [201] 12  6 18  4  7  2  7 58  2  4  3  9 15  3  6 25  9  7  4 39  2  8  4 10  2
# [226]  4  5  3  2  8  4  3 22 53 25 24 15  2  8  2 22 12  5  4 10 18 30  2 39 21
# [251]  9 22 15 11 14 10 34  6 21  2  2  3  5  4  6  3  3  4  9  6  9  6  3 16 11
# [276]  2 11  5 40  8 26 11  4 13  3 12  2  3  4  5  3  4 14 20  6  3  2  3  3 20
# [301]  2  2 14 18 35 22  9 26  4  8 43  3  2  4  3  7  3  4  5  2  5  5  5  3 20
# [326] 23  3  5  3  2  2  6  7  9  4  2  4  2  2 33  3  3 13  2  3 14 18
st_to_segments = function(x) {
	to_seg = function(l) {
		l = unclass(l)
		nr = nrow(l)
		segs = cbind(l[1:(nr-1),,drop=FALSE], l[2:nr,,drop=FALSE])
		lstr = function(r) structure(matrix(r, 2, 2, byrow = TRUE), 
					 	class = c("XY", "LINESTRING", "sfg"))
		apply(segs, 1, lstr, simplify = FALSE)
	}
	stopifnot(inherits(x, "sfc_LINESTRING"))
	do.call(st_sfc, unlist(sapply(x, to_seg), recursive = FALSE))
}
ret = st_to_segments(ls)
# check: 
sum(sapply(ls, nrow) - 1) == length(ret) 
# [1] TRUE
plot(ret, lwd = 3)
plot(st_geometry(roads), add = TRUE, col = 'red')
```
![x](https://user-images.githubusercontent.com/520851/223670250-5d4294f4-d2f4-4ae0-8f86-ab95915a2926.png)
