### ISSUE TITLE
st_write() function outputs Chinese characters, resulting in garbled code

### ISSUE THREAD

**Issue by Kedvesem0623** [r-spatial/sf#2113]
Hello everyone, I am a new programmer. I want to use sf package to output vector point data with Chinese characters. The output is successful (using the st_write() function), and no error is reported. But when I use st_ When the read() function reread the output vector point data, I found that the Chinese attribute of the vector point changed to????.
I read the output vector in ArcGIS and R language, and changed the different encoding methods in the CPG file (including ASCII, UTF-8, UTF-16, GBK, GB2312, GB18030), all of which can not make the???? Convert to Chinese characters. What measures should I take? Sincerely ask for your help and look forward to your reply, thank you!!!

**Comment by rsbivand** [comment]
Please provide a reproducible example, in UTF-8 only. Recent Windows 10, 11, and all other OS use UTF-8. Also state your R version, and the version of sf. If Windows pre-UCRT and R 4.1, do not expect any fixes, since later Windows and R 4.2 support UTF-8. Also, `ESRI Shapefile` is a format that should be dropped as soon as possible as it does not reliably support any encodings other than the native one on your platform (you mention a CPG file, hence I infer a shapefile format); GPKG is certainly to be preferred as it uses UTF-8 by default.

**Comment by kadyb** [comment]
@Kedvesem0623, does the example below work for you?

```r
library("sf")

geom = st_sfc(st_point(c(0, 0)))
df = data.frame(text = "早上好", geom)
df = st_as_sf(df, crs = st_crs(4326))
tmp = tempfile(fileext = ".shp")
write_sf(df, tmp, layer_options = "ENCODING=UTF-8")

x = read_sf(tmp)
x$text
#> [1] "早上好"
```

**Comment by Kedvesem0623** [comment]
Thank you for your reply!
My winodws system is win10; R language version is 4.2.1; The sf package version is 1.0-9. The vector format I use is shapefile.

      st_write(sf,paste0("Result\\", targetVal, ".shp"),driver = "ESRI Shapefile")

The original format is as follows:
species	class	x	y
苹果	economic	39500428.04	4491173.145
凤梨	economic	39503507.84	4495422.338
草莓	economic	39501123	4492566.399
樱桃	economic	39499156.91	4492020.769
香梨	economic	39506590.66	4486837.934

But in fact, it is:
species	class	x	y
???	economic	39500428.04	4491173.145
???	economic	39503507.84	4495422.338
???	economic	39501123	4492566.399
???	economic	39499156.91	4492020.769
???	economic	39506590.66	4486837.934

**Comment by Kedvesem0623** [comment]
> @Kedvesem0623, does the example below work for you?
> 
> ```r
> library("sf")
> 
> geom = st_sfc(st_point(c(0, 0)))
> df = data.frame(text = "早上好", geom)
> df = st_as_sf(df, crs = st_crs(4326))
> tmp = tempfile(fileext = ".shp")
> write_sf(df, tmp, layer_options = "ENCODING=UTF-8")
> 
> x = read_sf(tmp)
> x$text
> #> [1] "早上好"
> ```

Sincerely thank you for your reply. This code looks very helpful. I'm trying~

**Comment by rsbivand** [comment]
What is in the CPG file? For me on Linux from @kadyb 's example, it contains `UTF-8`:
```
file.show(sub("shp", "cpg", tmp))
```
from the example. Please run the example, not your own case.

**Comment by Kedvesem0623** [comment]
> @Kedvesem0623, does the example below work for you?
> 
> ```r
> library("sf")
> 
> geom = st_sfc(st_point(c(0, 0)))
> df = data.frame(text = "早上好", geom)
> df = st_as_sf(df, crs = st_crs(4326))
> tmp = tempfile(fileext = ".shp")
> write_sf(df, tmp, layer_options = "ENCODING=UTF-8")
> 
> x = read_sf(tmp)
> x$text
> #> [1] "早上好"
> ```

Good! I succeeded~ After adding the code of the specified encoding method, the normal vector table is output. Thank you so much~OUO
【write_sf(df, tmp, layer_options = "ENCODING=UTF-8")】

**Comment by Kedvesem0623** [comment]
> What is in the CPG file? For me on Linux from @kadyb 's example, it contains `UTF-8`:
> 
> ```
> file.show(sub("shp", "cpg", tmp))
> ```
> 
> from the example. Please run the example, not your own case.

Thank you for your help. The problem has been solved. The original vector file does not have a CPG file. I added one manually. Because I heard that this can solve the problem of reading garbled code.
