### ISSUE TITLE
errors and dropped polygons with near-side perspective projection

### ISSUE THREAD

**Issue by belscrog** [r-spatial/sf#2114]
<pre>
Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 7.2.1
</pre>

I get a variety of errors for different center longitudes when plotting in the near-side perspective projection. Usually the error is "Invalid number of points in LinearRing" or "point array must contain 0 or >1 elements." Sometimes, however, the projected polygons have empty geometries. In the example below, note that the US and Canada don't plot, with no error. (Note: I had to type the code below, not paste, so forgive any typos.) 

In a similar vein, polygons that are larger than the bounds of a projected map extent are returned empty, rather than being cut by the bounds.

<pre>
library(sf)
library(rnaturalearth)
test <- function(lon0) {
  proj <- paste("+proj=nsper +h=35786000 +lon_0=",lon0,sep="")
  st_graticule(lon=seq(-180,180,5),lat=seq(-90,90,5)) %>% st_transform(proj) %>% st_geometry() %>% plot(col="gray90",lwd=0.5)
  ne_countries(returnclass="sf") %>% st_transform(proj) %>% st_geometry() %>% plot(col="gray50",border="white",lwd=0.5,add=TRUE)
}
par(mfrow=c(3,3),mar=c(0,0,0,0))
sapply(seq(-10,-90,-10),function(l){try(test(l))})

</pre>

**Comment by edzer** [comment]
Yes, that is well known. What you could do is first compute the `st_intersection` of the dataset with the area that is visible. An example is found [here](https://r-spatial.github.io/sf/articles/sf7.html).

**Comment by belscrog** [comment]
Ah, thanks.
