### ISSUE TITLE
Installation on EC2 Ubuntu 22.0 

### ISSUE THREAD

**Issue by gilbertocamara** [r-spatial/sf#2116]
Hi @edzer 

I am trying to install "sf" on a clean EC2 AWS machine. I have installed the dependencies as recommended (see below):

```
~$ sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
~$ sudo apt-get update
~$ sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev libsqlite0-dev
```

 I am getting the same error reported by @tim-salabim (issue #2092), as follows: 
```
* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.6.2
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... ./configure: line 3668: 66825 Segmentation fault      (core dumped) ./gdal_proj
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
ERROR: configuration failed for package ‘sf’
```

I have checked that the latest versions of the support libraries are available 
```
libsqlite0-dev is already the newest version (2.8.17-15fakesync1build1).
libudunits2-dev is already the newest version (2.2.28-3).
libgdal-dev is already the newest version (3.6.2+dfsg-1~jammy0).
libgeos-dev is already the newest version (3.11.1-1~jammy0).
libproj-dev is already the newest version (9.1.1-1~jammy0)
```

Checked there is only one version of `gdal` and `proj`
```
~$ which -a gdal-config
/usr/bin/gdal-config
/bin/gdal-config
~$ which -a proj
/usr/bin/proj
/bin/proj
```

The proj executable is available for running
```
~$ proj
Rel. 8.2.1, January 1st, 2022
usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]
```
I am sorry to disturb you, by I am at a loss to understand what is required to fix the error. 

Thanks in advance for your help,
Gilberto

**Comment by rsbivand** [comment]
The proj executable is showing a different version number from the package. Did something else pull it in?

**Comment by gilbertocamara** [comment]
Thanks @rsbivand for the point. I used the standard installation scripts as recommended in the sf GitHub. Should I uninstall projeto and start again?

**Comment by edzer** [comment]
This
```
libproj-dev is already the newest version (9.1.1-1~jammy0)
```
and this
```
~$ proj
Rel. 8.2.1,
```
contradict (on is 8.2.1, the other 9.1.1). Is it possible that the machine was not clean?

**Comment by gilbertocamara** [comment]
Hi @edzer @rsbivand 
I installed the latest version of `proj`
```
~$ sudo rm /bin/proj
~$ sudo apt-get install proj-bin
(...)
~$ proj
Rel. 9.1.1, December 1st, 2022
```
However, I keep getting the same error. Help appreciated.

**Comment by rsbivand** [comment]
I would install the development package for units first, then try to install that. Then the development packages for proj, geos and gdal. I would certainly check which drivers are supported by the gdal package before trying the sf installation. I don't know for example if that build has the drivers you need. I'd try to start from an instance with almost nothing installed.

**Comment by gilbertocamara** [comment]
Hi @rsbivand, many thanks for your tips and patience. I cleaned all libraries and binaries associated to GDAL, GEOS and PROJ, then re-installed them one by one. Now I was able to install "sf". 
Thanks for yours and @edzer's time.

**Comment by jaredlander** [comment]
I'm often plagued by this problem where the Linux libraries have been updated, forcing a heroic scramble by the `{sf}` devs to update their package. Then I sit there wondering why things don't work, questioning if it's `libgdal-dev` or `libudunits2-dev` or some other Linux library.

To help mitigate this I'm using Docker to freeze things. But when I `apt install` in Docker it just takes the latest versions of the Linux libraries.

Is there a way to know what versions of each Linux library that a specific version of `{sf}` wants so that I can install just those versions?

**Comment by edzer** [comment]
> Is there a way to know what versions of each Linux library that a specific version of {sf} wants so that I can install just those versions?

Hi Jared - `udunits2` is pretty stable, but `GDAL` and `PROJ` are pretty dynamic. A new `sf` versions is sometimes required when `GDAL` or `GEOS` change, but they try to be backward compatible with older versions using conditional compiles; occasionally this goes wrong, as I don't check every possible combination systematically.

**Comment by jaredlander** [comment]
We're having a really hard time with 1.0-11 on a machine that already had all the Linux libraries installed. A clean install is fine, but not over an existing install. Similar problems with `{terra}` (I know that's a different issue). I feel like I run into issues with Linux libraries and `{sf}` often enough that I get very frustrated.

I'm doing a clean install on a VM now and am going to keep track of library versions (of at least the usual suspects). I'll report them back here, if for nothing else than a note for future people having trouble installing at the moment.
