### ISSUE TITLE
Error building sf (1.0-10) while deploying to shinyapps.io

### ISSUE THREAD

**Issue by mbjohnsonmn** [r-spatial/sf#2123]
**Describe the bug**
We haved two apps that have been running and functioning as expected for many months, both locally and on shinyapps.io. They still both work locally, but neither can be republished, ending with the following:

> Error: Unhandled Exception: Child Task 1282211471 failed: Error building image: Error building sf (1.0-11). Build exited with non-zero status: 1
> Execution halted

**To Reproduce**
I can't reproduce, except to provide the attached error log file.
[sf_on_shinyapps_failure_to_build.txt](https://github.com/r-spatial/sf/files/10983940/sf_on_shinyapps_failure_to_build.txt)

**If reporting a change from previous versions**

Please read https://cran.r-project.org/web/packages/sf/news/news.html first.

**Additional context**

<details>
Paste the output of your `sessionInfo()` and `sf::sf_extSoftVersion()`
Output of my `sessionInfo()` 
<html>
<body>

R version 4.2.2 (2022-10-31 ucrt) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 22621)  Matrix products: default  locale: [1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    [3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                           [5] LC_TIME=English_United States.utf8      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] janitor_2.2.0             gtExtras_0.4.5            sortable_0.4.6             [4] shinyjqui_0.4.1           googlesheets4_1.0.1       googledrive_2.0.0.9000     [7] htmlTable_2.4.1           gt_0.8.0                  glue_1.6.2                [10] openxlsx_4.2.5.2          plotly_4.10.1             markdown_1.5              [13] htmltools_0.5.4           DT_0.27                   rgeos_0.6-2               [16] rgdal_1.6-5               sp_1.6-0                  leaflet.extras_1.0.0      [19] leaflet_2.1.2             reactablefmtr_2.0.0       reactable_0.4.4           [22] arrow_11.0.0.3            shinyCopy2clipboard_0.1.0 shinythemes_1.2.0         [25] shinydashboard_0.7.2      shinyjs_2.1.0             lubridate_1.9.2           [28] forcats_1.0.0             stringr_1.5.0             dplyr_1.1.0               [31] purrr_1.0.1               readr_2.1.4               tidyr_1.3.0               [34] tibble_3.2.0              ggplot2_3.4.1             tidyverse_2.0.0           [37] shiny_1.7.4               devtools_2.4.5            usethis_2.1.6              loaded via a namespace (and not attached):   [1] backports_1.4.1            lazyeval_0.2.2             jqr_1.2.3                    [4] crosstalk_1.2.0            digest_0.6.31              rsconnect_0.8.29             [7] leaflet.providers_1.9.0    fansi_1.0.4                magrittr_2.0.3              [10] checkmate_2.1.0            memoise_2.0.1              geojsonsf_2.0.3             [13] paletteer_1.5.0            tzdb_0.3.0                 remotes_2.4.2               [16] askpass_1.1                timechange_0.2.0           prettyunits_1.1.1           [19] colorspace_2.1-0           xfun_0.37                  leafem_0.2.0                [22] callr_3.7.3                crayon_1.5.2               jsonlite_1.8.4              [25] gtable_0.3.1               gargle_1.3.0               webshot_0.5.4               [28] V8_4.2.2                   pkgbuild_1.4.0             scales_1.2.1                [31] DBI_1.1.3                  miniUI_0.1.1.1             Rcpp_1.0.10                 [34] viridisLite_0.4.1          xtable_1.8-4               units_0.8-1                 [37] learnr_0.11.2              bit_4.0.5                  proxy_0.4-27                [40] stats4_4.2.2               profvis_0.3.7              htmlwidgets_1.6.1           [43] httr_1.4.5                 RColorBrewer_1.1-3         ellipsis_0.3.2              [46] farver_2.1.1               urlchecker_1.0.1           pkgconfig_2.0.3             [49] sass_0.4.5                 crul_1.3                   utf8_1.2.3                  [52] tidyselect_1.2.0           rlang_1.1.0                later_1.3.0                 [55] reactR_0.4.4               munsell_0.5.0              cellranger_1.1.0            [58] tools_4.2.2                cachem_1.0.7               cli_3.6.0                   [61] generics_0.1.3             evaluate_0.20              fastmap_1.1.1               [64] yaml_2.3.7                 rematch2_2.1.2             processx_3.8.0              [67] knitr_1.42                 bit64_4.0.5                fs_1.6.1                    [70] shinycssloaders_1.0.0.9001 zip_2.2.2                  satellite_1.0.4             [73] mime_0.12                  compiler_4.2.2             rstudioapi_0.14             [76] curl_5.0.0                 png_0.1-8                  e1071_1.7-13                [79] bslib_0.4.2                stringi_1.7.12             ps_1.7.2                    [82] lattice_0.20-45            commonmark_1.8.1           classInt_0.4-9              [85] vctrs_0.5.2                pillar_1.8.1               lifecycle_1.0.3             [88] jquerylib_0.1.4            geojsonio_0.11.0           data.table_1.14.8           [91] raster_3.6-20              mapview_2.11.0             httpuv_1.6.9                [94] R6_2.5.1                   promises_1.2.0.1           KernSmooth_2.23-20          [97] sessioninfo_1.2.2          codetools_0.2-18           assertthat_0.2.1           [100] pkgload_1.3.2              fontawesome_0.5.0          openssl_2.0.6              [103] rprojroot_2.0.3            httpcode_0.3.0             withr_2.5.0                [106] geojson_0.3.4              hms_1.1.2                  terra_1.7-18               [109] grid_4.2.2                 class_7.3-20               snakecase_0.11.0           [112] sf_1.0-10                  base64enc_0.1-3
--
 
> | >
>

          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
       "3.9.3"        "3.5.2"        "8.2.1"         "true"         "true"        "8.2.1" 
 
> | >
>

</body>
</html>
</details>

**Comment by mbjohnsonmn** [comment]
Fyi, I've updated to 1.0-11 today.

**Comment by edzer** [comment]
I built a docker image (starting from ubuntu:22.04) that has GDAL 3.0.4, PROJ 6.3.1 and GEOS 3.8.0, as in your example, and there I can reproduce the problem of #2121 but not the one you find pointing to `OGRSpatialReference::GetAxis`. Could you pls try whether your problem has been resolved by https://github.com/r-spatial/sf/commit/1d0302a8b1c6344510e466ece947e640e4759ea7 ? If not, could you point me to a Dockerfile creating your image?

**Comment by jacpete** [comment]
I was able to get it to install correctly to shinyapps.io with the sf version https://github.com/r-spatial/sf/commit/1d0302a8b1c6344510e466ece947e640e4759ea7. 

shinyapps.io uses ubuntu 20.04 so I think it was the same issue. When I was testing this with version 1.0-11, I was ending a different error point than  `OGRSpatialReference::GetAxis`, but this fix seems to have resolved the issue overall.

Thank you for the quick fix!

**Comment by mbjohnsonmn** [comment]
Apologies for the delayed response, Edzer. Your updates have solved the issue. Thanks for you work on this!
