### ISSUE TITLE
Difficulty deploying Shiny App - error related to sf

### ISSUE THREAD

**Issue by dfosterhill** [r-spatial/sf#2126]
Hello. I am new to R and Rstudio. I have modified a friend's code to create an app. The app works great, and the code is attached.

Ok, so the app runs great. But, when I go to 'publish' the app to my shinyapps account (note: I have had previous success with this, especially with a very related app), I get the following (very long) error log, which is attached. Note, it seems like the full log is not shown in the Deploy window of R Studio...maybe it is too long?

Anyway, when I click on publish and watch the progress, it is getting stuck on the 'build sf package' part of things.

I have spent a long time looking at solutions for this online...they variously deal with checking to see if Rcpp is correct, if gdal is correct, and so on. I have tried installing these things in various ways with no luck, and now I am more confused than ever.

If anyone has any ideas on what to try next, I'd be obliged.

thank you,
Dave.

****
[myerrors.txt](https://github.com/r-spatial/sf/files/11005257/myerrors.txt)
[mycode.txt](https://github.com/r-spatial/sf/files/11005258/mycode.txt)

**Comment by edzer** [comment]
Please see the last few closes issues.

**Comment by dfosterhill** [comment]
Thank you Edzer, I did...Those are many of the things that I have tried, with no success. I will continue to do so.

**Comment by edzer** [comment]
`remotes::install_github("r-spatial/sf")`

**Comment by dfosterhill** [comment]
That gives me the following error. I apologize for being such a novice. It is complicated and each thing I try seems to fix one issue, but lead to another. I appreciate your willingness to share suggestions.


> remotes::install_github("r-spatial/sf")
Downloading GitHub repo r-spatial/sf@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                       
2: CRAN packages only        
3: None                      
4: wk (0.7.1 -> 0.7.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
wk (0.7.1 -> 0.7.2) [CRAN]
Installing 1 packages: wk
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/wk_0.7.2.tgz'
Content type 'application/x-gzip' length 1889666 bytes (1.8 MB)
==================================================
downloaded 1.8 MB


The downloaded binary packages are in
	/var/folders/wj/2qclqzd909xgtz1nd1hmjc3r0000gp/T//Rtmp5CfPL5/downloaded_packages
Running `R CMD build`...
* checking for file ‘/private/var/folders/wj/2qclqzd909xgtz1nd1hmjc3r0000gp/T/Rtmp5CfPL5/remotescf4c549b803/r-spatial-sf-4a904d4/DESCRIPTION’ ... OK
* preparing ‘sf’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘sf_1.0-12.tar.gz’
* installing *source* package ‘sf’ ...
** using staged installation
configure: CC: clang -arch arm64
configure: CXX: clang++ -arch arm64 -std=gnu++14
checking for gdal-config... /opt/homebrew/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.6.3
checking GDAL version >= 2.0.1... yes
checking for gcc... clang -arch arm64
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang -arch arm64 accepts -g... yes
checking for clang -arch arm64 option to enable C11 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /opt/homebrew/Cellar/gdal/3.6.3/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.6.3
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 9.2.0
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
configure: error: libproj or sqlite3 not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/sf’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/sf’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/wj/2qclqzd909xgtz1nd1hmjc3r0000gp/T//Rtmp5CfPL5/filecf4c695dce14/sf_1.0-12.tar.gz’ had non-zero exit status

**Comment by dfosterhill** [comment]
This is where it gets stuck whenever I try to publish the app:

Preparing to deploy application...DONE
Uploading bundle for application: 8589348...DONE
Deploying bundle: 6973181 for application: 8589348 ...
Waiting for task: 1282926214
  building: Parsing manifest
  building: Building image: 8271120
  building: Installing system dependencies
  building: Fetching packages
  building: Building package: sf

**Comment by edzer** [comment]
It is possible that the process building the app tries to install from source in which case you'd need to follow the [instructions for this](https://github.com/r-spatial/sf#ubuntu) to be successful. Alternatively, you'd need to instruct the app builder to not install from source but take the (latest) binary version.

**Comment by dfosterhill** [comment]
Hello.

Your solution below worked perfectly.

I want to thank you very sincerely. I am very appreciative.

Dave.


On Mar 18, 2023, at 12:23 AM, Edzer Pebesma ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


It is possible that the process building the app tries to install from source in which case you'd need to follow the instructions for this<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fr-spatial%2Fsf%23ubuntu&data=05%7C01%7CDavid.Hill%40oregonstate.edu%7C8bd2e72dc86f4630608708db2781aac6%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C638147210089230865%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2zUnbtb4itxBauO9FQrZV1kMbsjA7QLNJeiyJsjhSHg%3D&reserved=0> to be successful. Alternatively, you'd need to instruct the app builder to not install from source but take the (latest) binary version.
