### ISSUE TITLE
Can't write GDBs using OpenFileGDB driver

### ISSUE THREAD

**Issue by phildias** [r-spatial/sf#2134]
Around mid 2022, the `GDAL` library was updated and the `OpenFileGDB` was enhanced to include the capacity to write GDBs (see [here](https://github.com/OSGeo/gdal/pull/5910)).

I think some other changes need to be made to `sf` to allow its users to access those capabilities. Right now, when I try to wright a GDB using `sf`, i get an error:

```r
library(tidyverse)
library(sf)

my_df = data.frame(col1=c(1,2,3),
                   lon=c(0,1,2),
                   lat=c(0,1,2)) %>%
  st_as_sf(coords = c("lon", "lat"), 
           crs = 4326, 
           agr = "constant")

my_df %>% 
  st_write(dsn='c:/temp/my_test.gdb', 
           layer="x1", 
           driver="OpenFileGDB",
           append=FALSE)
```

The `st_write` command above yields the following error message:

```
Creating dataset c:/temp/my_test.gdb failed.
Error: Creation failed.
In addition: Warning message:
In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 6: GDALDriver::Create() ... no create method implemented for this format.
```

Is there any way I can bypass this? Thanks!

**Comment by rsbivand** [comment]
Please look at `sf::sf_extSoftVersion()`. Is the version of GDAL later than the announcement you refer to? It is most likely that your package was built against an earlier GDAL.

**Comment by phildias** [comment]
Yep, you're right. `sf::sf_extSoftVersion()` shows me that the version of `GDAL` that R "sees" is 3.5.2, and it seems that the new `OpenFileGDB` capabilities were made available in version 3.6.0 (see [here ](https://github.com/OSGeo/gdal/milestone/36?closed=1)). 

The installation of OSGeo and GDAL were done automatically when I just ran `install.packaged("sf")`. Is there a way to update the version of GDAL that R is "seeing"?

**Comment by rsbivand** [comment]
Which platform/operating system, and how did you install `sf`?

**Comment by phildias** [comment]
I'm currently working on a PC with Windows 10. I installed `sf` by typing `install.packaged("sf")` in the R console in RStudio.

**Comment by phildias** [comment]
The version of `sf` is 1.0.12` and the version of R I'm using is 4.2.3.

**Comment by rsbivand** [comment]
On Windows, the user library is usually versioned, so that 4.2 and 4.3 can co-exist. So in 4.3, `remove.package()` will not see the 4.2 package.

**Comment by rsbivand** [comment]
For me, Windows 10, R 4.3-devel (mid-March):
```
> library(sf)
Linking to GEOS 3.11.1, GDAL 3.6.2, PROJ 9.1.1; sf_use_s2() is TRUE
> st_drivers()["OpenFileGDB",]
                   name    long_name write  copy is_raster is_vector  vsi
OpenFileGDB OpenFileGDB ESRI FileGDB  TRUE FALSE     FALSE      TRUE TRUE
```
reporting write TRUE.
```
> st_write(st_read(system.file("gpkg/nc.gpkg", package="sf")), tf)
Reading layer `nc.gpkg' from data source 
  `C:\Users\RB\AppData\Local\R\win-library\4.3\sf\gpkg\nc.gpkg' 
  using driver `GPKG'
Simple feature collection with 100 features and 14 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
Geodetic CRS:  NAD27
Writing layer `file16dc28de7042' to data source 
  `C:\Users\RB\AppData\Local\Temp\RtmpAHDeNO\file16dc28de7042.gdb' using driver `OpenFileGDB'
Writing 100 features with 14 fields and geometry type Multi Polygon.
> st_read(tf)
Reading layer `file16dc28de7042' from data source 
  `C:\Users\RB\AppData\Local\Temp\RtmpAHDeNO\file16dc28de7042.gdb' using driver `OpenFileGDB'
Simple feature collection with 100 features and 14 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
Geodetic CRS:  NAD27
```

**Comment by edzer** [comment]
Thanks!

**Comment by phildias** [comment]
Awesome, thanks for all the info! =)

**Comment by JosiahParry** [comment]
Hi all, I want to set a minimum version of {sf} to be based on when the `OpenFileGDB` driver was available. Is my reading here it requires a minimum version of R to be `R >= v4.3.0` and `sf >= v1.0-13`—this is guessed based on the first release following the closing of this issue from https://cran.r-project.org/src/contrib/Archive/sf/

**Comment by rsbivand** [comment]
I think it is only controlled by the GDAL version. From https://gdal.org/en/latest/drivers/vector/openfilegdb.html, GDAL 3.6 is needed for writing fgdb. For CRAN binaries, Windows is now at 3.9.3 I think, but macOS is on 3.5. A small example file to test, say in a github actions run, might make sense.

**Comment by JosiahParry** [comment]
@rsbivand I think there is an sf version requirement due to this line here: 
https://github.com/r-spatial/sf/blob/7dd4173f69db6ae6291d529ff333330c6ef18f75/R/read.R#L777

IIUC, sf checks the extension and maps it to the driver

**Comment by rsbivand** [comment]
For writing both vectors and rasters, using the driver argument controls. For reading, the detection of the needed driver should be done by GDAL. The extension map is very likely superfluous, never needed in `rgdal`.
