### ISSUE TITLE
st_intersection error: GEOS exception

### ISSUE THREAD

**Issue by arthurgailes** [r-spatial/sf#2143]
Related to https://github.com/r-spatial/sf/issues/2089 and https://github.com/r-spatial/sf/issues/1668 

Reprex. I used tigris for the example, but this happens in any practical n_ary intersection I attempt.

```
library(sf)
#> Warning: package 'sf' was built under R version 4.2.2
#> Linking to GEOS 3.9.3, GDAL 3.5.2, PROJ 8.2.1; sf_use_s2() is TRUE
library(tigris)
#> Warning: package 'tigris' was built under R version 4.2.2
#> To enable caching of data, set `options(tigris_use_cache = TRUE)`
#> in your R script or .Rprofile.
tracts <- tigris::tracts(county = "037", state = "06", progress_bar = FALSE)
#> Retrieving data for the year 2021
mean_area <- mean(st_area(tracts))
rad <- sqrt(mean_area / pi)

# happens in s2 and 3857
tract_buff_s2 <- st_buffer(st_centroid(tracts), rad)
#> Warning in st_centroid.sf(tracts): st_centroid assumes attributes are constant
#> over geometries of x

int_s2 <- st_intersection(tract_buff_s2)
#> although coordinates are longitude/latitude, st_intersection assumes that they
#> are planar
#> Error in eval(expr, envir, enclos): GEOS exception

tract_buff_3857 <- st_buffer(st_centroid(st_transform(tracts, 3857)), rad)
#> Warning in st_centroid.sf(st_transform(tracts, 3857)): st_centroid assumes
#> attributes are constant over geometries of x

int_3857 <- st_intersection(tract_buff_3857)
#> Error in eval(expr, envir, enclos): GEOS exception
```

Thank you.

**Comment by edzer** [comment]
This now uses the GEOS overlayNG routines (if GEOS >= 3.9.0), and this now works:
```r
tract_buff_3857 |> st_set_precision(.01) |> st_intersection() -> x
plot(st_geometry(x)[900:1000]))
```
gives
![x](https://user-images.githubusercontent.com/520851/230672012-b712871a-c661-4675-b5c3-4fdf7791d1b4.png)

which, as you can see, rounds coordinates to a 100 m grid. Larger values for precision (finer grids) give the `GEOS exception`. This is probably because many of the centroids are very close together: it's unclear to me whether you really want n-ary intersections of those on some fine grid.

**Comment by arthurgailes** [comment]
I see, thank you. My real-world dataset is analyzing buffers of points that might be a few meters apart (e.g. units in the same building), so fine control is needed. Does that mean this function is unable to process such differences? Is there a precision threshold at which it breaks?

**Comment by edzer** [comment]
It depends on how large the buffers are. I used trial and error to get at 0.01.
