### ISSUE TITLE
Is there an sf equivalent to sp::point.in.polygon()?

### ISSUE THREAD

**Issue by dankelley** [r-spatial/sf#2145]
I have some code (in the `oce` package) that uses `sp::point.in.polygon()` to create a logical vector of the indices of (x,y) points that are within a polygon with vertices (px,py).

My impression (from e.g. https://r-spatial.org/r/2023/04/10/evolution3.html#conserving-sp-workflows) is that folks are being advised to move from `sp` to `sf`, so I am working to convert my code.  At the moment I have as below, using `sapply` on individual (x,y) points.  I worry that this might be very slow, though.  Is there another way to construct a logical vector telling whether each of N points is  inside a polygon?  I'm a bit worried that the code I have will be quite slow with a lot of points.

I apologize for asking what is likely a very rudimentary question.

Dan.

```R
# This code is patterned on the start of the Examples section of
# https://r-spatial.github.io/sf/reference/geos_binary_pred.html

library(sf)
x <- c(0.5, 1.5, 2.5)
y <- c(0.5, 1.5, 2.5)
polx <- c(0, 2, 2, 0, 0)
poly <- c(0, 0, 2, 2, 0)
pol <- sf::st_polygon(list(outer=cbind(polx, poly)))

# Is the next slow? If so, is there a way I can pass vectors x,y into a function
# to get the same result?
inside <- sapply(seq_len(length(x)),
    function(i) {
        st_intersects(st_point(c(x[i], y[i])), pol, sparse=FALSE)
    })
print(inside)

# Illustrate, with red symbols for points that are inside the polygon.
plot(x, y)
text(x, y, seq_along(x), pos=4)
plot(pol, col=rgb(1,0,0,0.1), add=TRUE)
points(x[inside], y[inside], pch=20, col=2)
mtext(paste("inside: ", paste(inside, collapse=" ")))
```

**Comment by rsbivand** [comment]
Dan,

`sp::point.in.polygon()` is not affected by the retirement of `rgeos`. Code using `sp` classes is unaffected, but `sp::spTransform()`  and `sp::CRS()` will use `sf` instead of `rgdal`. `sp::over()` may be affected for some object signatures that now use `rgeos`.

The choices beyond that would be that binary predicates on geographical coordinates should use `s2` rather than planar GEOS; `sp`'s point.in.polygon is planar.

I'll set up a comparison a little later.

**Comment by dankelley** [comment]
Roger, you're very generous!

**Comment by edzer** [comment]
(the same discussion is currently taking place in the ropensci slack, spatial channel)

**Comment by rsbivand** [comment]
I don't go there, ever.

**Comment by dankelley** [comment]
Roger, as always you are very helpful and insightful.  I really appreciate this, since I don't like to make a CRAN submission that is going to be problematic.

I'll close the issue, on the assumption that this is the convention in this repository.

Thanks again, to both Roger and Edzer.
