### ISSUE TITLE
Change Link GEOS Version in Windows

### ISSUE THREAD

**Issue by Nh-code** [r-spatial/sf#2150]
I have installed GEOS version 11 on the system, and then added the bin directory to the Path, but after reinstalling sf, it is still linked to GEOS 3.9. How should this problem be solved?

![image](https://user-images.githubusercontent.com/79830573/234252415-138cd3bf-7f16-45cd-b936-bda0647fd715.png)

**Comment by edzer** [comment]
You installed the binary sf package, which includes the GEOS package as part of the sf.dll file (statically linked). You'd have to install rtools, then replace the GEOS version inside rtools with the GEOS version you want, then recompile sf as a source package.

**Comment by Nh-code** [comment]
Thank you for your quick reply.I have Rtools42 installed on my system，but I am not familiar with Rtools. Regarding the operation of changing the GEOS version in Rtools you mentioned, can you prompt me which file I should operate? Please.
![image](https://user-images.githubusercontent.com/79830573/234260107-532824f4-76f4-416a-8012-b9cd87c6ff4a.png)

**Comment by edzer** [comment]
No, I can't.

**Comment by Nh-code** [comment]
So is there a simpler way to use the st_concave_hull function in sf without GEOS>3.11?
