### ISSUE TITLE
Writing raster from R to gdb

### ISSUE THREAD

**Issue by FelipeCarrillo** [r-spatial/sf#2155]
Hi;
I recently updated sf to the development version 1.0-13. Read this: https://r-spatial.github.io/sf/articles/sf2.html and it looks like st_write is able to convert shp or raster files to geodatabase (gdb) files, is that correct? 

I am trying to write a raster file to gdb so I can create a field called 'gridcode' that ArcGIS creates when a raster is converted to gdb file.

**Comment by edzer** [comment]
Package `sf` was never meant to read or write raster data. I see
```r
> st_drivers("vector", "*GDB")
                   name    long_name write  copy is_raster is_vector  vsi
OpenFileGDB OpenFileGDB ESRI FileGDB  TRUE FALSE     FALSE      TRUE TRUE
```
but no raster drivers of that name. The [gdal driver page](https://gdal.org/drivers/raster/openfilegdb.html) suggests reading rasters may appear in GDAL 3.7.0, which has not been released yet.
