### ISSUE TITLE
Converting shp to gdb

### ISSUE THREAD

**Issue by FelipeCarrillo** [r-spatial/sf#2156]
This is a vector file, shouldn't this work? Please forgive me if I am not doing correctly.

```
library(sf)
fname <- system.file("shape/nc.shp", package="sf")
fname
nc <- st_read(fname)
nc
st_write(nc, "nc1.shp")
st_write(nc, "nc2",driver="OpenFileGDB")
 st_write(nc, dsn = "nc1", layer = "nc.shp",driver='OpenFileGDB')
st_drivers()
is_vector(nc)

Creating dataset nc1 failed.
Error: Creation failed.
In addition: Warning message:
In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 6: GDALDriver::Create() ... no create method implemented for this format.
```

**Comment by edzer** [comment]
When using a dsn name that ends in `.gdb`, I get:
```r
> st_write(nc, "nc2.gdb", driver="OpenFileGDB")
Writing layer `nc2' to data source `nc2.gdb' using driver `OpenFileGDB'
Writing 100 features with 14 fields and geometry type Multi Polygon.
```

**Comment by rsbivand** [comment]
https://gdal.org/drivers/vector/openfilegdb.html#vector-openfilegdb says 

> Write and update capabilities are supported since GDAL >= 3.6

so the GDAL version matters.

**Comment by FelipeCarrillo** [comment]
I see, thanks for the clarification. I didn't see the part about GDAL 3.6. Is this package available already and can be downloaded from CRAN?

**Comment by rsbivand** [comment]
You did not provide the output of sessionInfo(), nor sf::sf_extSoftVersion(). Please do so. If Linux, the verdion of GDAL depends on how you installed it, on Windows and macOS using CRAN binary packages, on the version of GDAL used in the build train. GDAL is.not provided by CRAN. See also https://rsbivand.github.io/foss4g_2022/modernizing_220822.html#FOSS_foundations_and_barn-raising

**Comment by rsbivand** [comment]
Windows R 4.3 binary packages use GDAL 3.6.2, macOS M1 R 4.3 binary packages use GDAL 3.5.3. On Linux, Fedora 38 has GDAL 3.6.3, Debian unstable 3.6.2, etc.; package installation from source on Linux will use the version installed on the system, or for Rtoools43 or macOS, the same binary used in building the CRAN package binaries.

**Comment by FelipeCarrillo** [comment]
My relevant session_info and sf_extSoftVersion below:
```
sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
      "3.10.2"        "3.4.1"        "7.2.1"         "true"         "true"        "7.2.1" 

sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  datasets  grDevices utils     methods   base     
```
An additional question if you don't mind, is GDAL able to convert rasters to gdb files or just vector to gdb? I have some rasters that I need to convert to gdb and/or shapefiles.

**Comment by edzer** [comment]
> An additional question if you don't mind, is GDAL able to convert rasters to gdb files or just vector to gdb? 

You've asked that in #2155

**Comment by FelipeCarrillo** [comment]
That's correct and I forgot the answer. I will wait for GDAL 3.7.

**Comment by rsbivand** [comment]
And that GDAL driver page also only mentions reading raster `.gdb` files from 3.7, not writing.
