### ISSUE TITLE
Trouble building under macOS - build ignores Makeconf?

### ISSUE THREAD

**Issue by jonathon-love** [r-spatial/sf#2159]
hi,

i'm just trying to build `sf` under macOS, and i'm receiving the following error:

```
checking for gdal.h... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
Undefined symbols for architecture x86_64:
  "_BIO_free", referenced from:
      _CPL_RSA_SHA256_Sign in libgdal.a(cpl_sha256.o)
  "_BIO_new_mem_buf", referenced from:
      _CPL_RSA_SHA256_Sign in libgdal.a(cpl_sha256.o)
  "_DFKNTsize", referenced from:
      _GDdeffield in libgdal.a(GDapi.o)
      _GDdetach in libgdal.a(GDapi.o)
      _GDregioninfo in libgdal.a(GDapi.o)

...

  "_ZSTD_maxCLevel", referenced from:
      _ZSTDVSetField in libtiff.a(tif_zstd.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure: Install failure: compilation and/or linkage problems.
ERROR: configuration failed for package ‘sf’
```

i've installed all these dependencies using the macos recipe section (and i successfully build many other packages against the recipes libs). i tried adding the following in my Makeconf

```
LDFLAGS = -v -L/usr/local/lib
```

(i hoped that adding the `-v` might output the link command, so i could see what was going on)

i can confirm that all the appropriate libs (libgdal.a, etc.) are installed to /usr/local/lib

it looks to me like `sf` is ignoring the `LDFLAGS`? i also tried setting the environmental variable of LDFLAGS to `-v -L/usr/local/lib`

my setup is as close to CRAN as possible, although i assume you build successfully on CRAN, so there may be a wrinkle on my part.

here's the whole build: https://github.com/jonathon-love/r-package-snapshot/actions/runs/4858450863/jobs/8659894961

any tips?

**Comment by jonathon-love** [comment]
hi,

we're doing the reproducible science thing, and so we need to be able to reliably reproduce a working package from an old source archive. the issue with CRAN is that they don't retain any of the old macOS binaries. we have been using the MRAN snapshots, but microsoft is retiring this. there's the rstudio package manager, but it only host windows and linux binaries.

not my preference, but you gotta do what you gotta do.

with thanks

**Comment by rsbivand** [comment]
Do you also have frozen OS components? Build train? Did you not consider storing the actual package binaaries as well as their upstream static libraries? If you were using Linux, OS are fairly static up to EOL (but Fedora moves faster), and it is also possible to re-build upstream libraries from source.

You mention having libgdal.a from recipes, but which version? The libraries that GDAL is built against also change over time, so you'd need the recipes version that was contemporary with `sf` when it was released.` _ZSTD_maxCLevel` is from libzstd, `_BIO_new_mem_buf` from an SSL library (openssl or similar), etc. Which version of `sf` are  you trying to freeze - looks like current sf_1.0-12.tar.gz? R appears to be 4.1.3, is that right? Current R is 4.3.0, and recipes do track that. Maybe look at https://github.com/R-macos/recipes/commits/master/recipes/gdal to try to see which libraries were added/modified when - but current `sf` will probably expect current recipes? And which GDAL version (PROJ 8.2.1, GEOS 3.10.2 versions) were then in play. In the Windows static case, the `sf` version you are using may not include all the libraries GDAL was built with in `Makevars.ucrt`; when something is missing, the error messages would be like those you report (some changes in Rtools42/3 are hotpatched on CRAN). The macOS static build system is different, however.

The log shows GDAL: 3.4.2 and current recipes has 3.5.3 (M1 anyway) - so which recipes version are  you running against? 

Can you replicate the problem locally with R 4.1.3, darwin 17 x86_64 and its recipes and current `sf`? If so, you should add print statements in `configure.ac`, run `autoconf`, and rebuild the source package without vignettes, and try again.  The failure is in `configure`:

```
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
Undefined symbols for architecture x86_64:
```

**Comment by jonathon-love** [comment]
> Do you also have frozen OS components? Build train?

yeah, so between github actions and the R-recipes, we can hopefully achieve that.

> Did you not consider storing the actual package binaaries as well as their upstream static libraries?

yeah, the problem is that we don't know in advance what packages people are going to want (and downloading the whole of CRAN isn't an option) ... if i can't build `sf` it probably means i'm not going to be able to build other things.

> If you were using Linux, OS are fairly static up to EOL (but Fedora moves faster), and it is also possible to re-build upstream libraries from source.

yeah, on linux this is all a dream. we're cross platform though :/

> You mention having libgdal.a from recipes, but which version? The libraries that GDAL is built against also change over time, so you'd need the recipes version that was contemporary with sf when it was released. _ZSTD_maxCLevel is from libzstd, _BIO_new_mem_buf from an SSL library (openssl or similar), etc. Which version of sf are you trying to freeze - looks like current sf_1.0-12.tar.gz? R appears to be 4.1.3, is that right? Current R is 4.3.0, and recipes do track that. Maybe look at https://github.com/R-macos/recipes/commits/master/recipes/gdal to try to see which libraries were added/modified when - but current sf will probably expect current recipes? And which GDAL version (PROJ 8.2.1, GEOS 3.10.2 versions) were then in play. In the Windows static case, the sf version you are using may not include all the libraries GDAL was built with in Makevars.ucrt; when something is missing, the error messages would be like those you report (some changes in Rtools42/3 are hotpatched on CRAN). The macOS static build system is different, however.

so this is really helpful ... and something i've been puzzled about. normally a 'undefined symbols error' takes place at the end of the build process, and usually means a mismatch between your `.h` files, and your `.so` files. the above error takes place very early, which suggests the source package is expecting is expecting a particular version? this package is partially compiled? and partially compiled against a particular version of gdal?

my experience is that you can compile a package against any version of a library, provided the `.h` files provide all the required functions/symbols.

> The log shows GDAL: 3.4.2 and current recipes has 3.5.3 (M1 anyway) - so which recipes version are you running against?

so i'm wanting to handle the R 4.1.3 case, and so my expectation is that this corresponds to the R-old-rel macos CRAN releases. my, likely erroneous, assumption is that R-old-rel is built using the version of macOS contemporaneous with the release of the 4.1 series, which i think was macOS 11. so i'm using macOS 11, and using the recipes that were contemporaneous with that. i install them with `install.libs('all', os='darwin17')` ... but it sounds like R-old-rel must be using a newer version of macOS, and newer libs. (i've been avoiding the newer versions because i want to maintain compatibility with macos 11)

exactly what CRAN does is a little opaque to me.

but i really appreciate your help here. this is really high quality help.

with thanks
