### ISSUE TITLE
Add ogrinfo to gdal_utils()

### ISSUE THREAD

**Issue by agila5** [r-spatial/sf#2160]
Dear all, I just read the [NEWS](https://github.com/OSGeo/gdal/blob/v3.7.0RC1/NEWS.md) file for the GDAL 3.7.0 release candidate and I notice the following: 

* ogrinfo: make it accessible through a new GDALVectorInfo() C API call, and a -json switch

AFAICT, that bullet message implies that starting from GDAL 3.7.0 we could add  `ogrinfo` to the GDAL utilities in `gdal_utils()`. I'm not super familiar with the C/C++ API but, if you want and if you agree, I can try implementing it as soon as possible.

**Comment by rsbivand** [comment]
You'll need 3.7.0 installed yourself to try out the patch when on >= 3.7, and to try out avoidance on platforms < 3.7. Good luck!
