### ISSUE TITLE
Same issue as https://github.com/r-spatial/sf/issues/844

### ISSUE THREAD

**Issue by hjager** [r-spatial/sf#2169]
It is now 2023 and I'm having a similar problem to #844 from 2020 (https://github.com/r-spatial/sf/issues/844) about lwgeom when running a shiny app after updating to R-4.3.0, Rstudio 2023.03.0 Build 386, and all packages including Rtools. See the error below. The shiny app's code is heavily dependent on sf. So far, i have tried uninstalling and reinstalling lwgeom. Can it be resolved on a windows system without having to build libraries in a tailored way as suggested in response to #844?

Loading required package: lwgeom
Linking to liblwgeom 3.0.0beta1 r16016, GEOS 3.9.1, PROJ 7.2.1
Error: package or namespace load failed for ‘lwgeom’:
 .onAttach failed in attachNamespace() for 'lwgeom', details:
  call: fun(libname, pkgname)
  error: (converted from warning) GEOS versions differ: lwgeom has 3.9.1 sf has 3.11.1

**Comment by rsbivand** [comment]
Sorry, absolutely nothing to do with #844 at all. Those were on Linux with dynamic loading, you are on Windows using static builds. - wait until I move to Windows ...

**Comment by rsbivand** [comment]
There has been activity on the `lwgeom` repo recently, so a new version may be about to be submitted to CRAN, and thus triggering a rebuild.

**Comment by edzer** [comment]
New version on CRAN; windows binaries will appear in a few days.

**Comment by hjager** [comment]
Thank you!
