### ISSUE TITLE
Error with st_is_valid

### ISSUE THREAD

**Issue by Pablocr7** [r-spatial/sf#2171]
Hi, I'm processing the sentinel 2 tiles with the R code, I'm using the sen2r function and I have a error while I'm trying the run process because  the error is this: #### Starting sen2r execution. ####
Error in UseMethod("st_is_valid") : 
  no applicable method for 'st_is_valid' applied to an object of class "logical",

I'm using the next code:
library(sen2r)

s2 <- "C:/online"
s2 <- list.files(s2, recursive = TRUE, full.names = TRUE)

sf::sf_use_s2(FALSE)  # Desactivar geometría esférica

sen2r(
  param_list = NULL,
  gui = FALSE,
  preprocess = TRUE,
  s2_levels = "l2a",
  sel_sensor = c("s2a", "s2b"),
  online = FALSE,
  server = "scihub",
  order_lta = FALSE,
  apihub = NA,
  downloader = "builtin",
  overwrite_safe = FALSE,
  rm_safe = "no",
  step_atmcorr = "l2a",
  sen2cor_use_dem = TRUE,
  sen2cor_gipp = NA,
  max_cloud_safe = 100,
  timewindow = NA,
  extent = NA,
  extent_name = "sen2r",
  s2tiles_selected = NA,
  s2orbits_selected = NA,
  list_prods = c("TOA","BOA"),
  list_rgb = NA,
  list_indices = c("NDVI"),
  index_source = "BOA",
  rgb_ranges = NA,
  mask_type = NA,
  max_mask = 100,
  mask_smooth = 0,
  mask_buffer = 0,
  clip_on_extent = FALSE,
  extent_as_mask = FALSE,
  reference_path = NA,
  res = NA,
  res_s2 = "10m",
  unit = "Meter",
  proj = NA,
  resampling = "near",
  resampling_scl = "near",
  outformat = "GTiff",
  rgb_outformat = "GTiff",
  index_datatype = "Float32",
  compression = "DEFLATE",
  rgb_compression = NA,
  overwrite = FALSE,
  path_l1c = "C:/online",
  path_l2a= "C:/online",
  path_tiles="C:/online",
  path_merged= "C:/online",
  path_out = "C:/*/sentinel/online",
  path_rgb = NA,
  path_indices = "C:/*/sentinel/online",
  path_subdirs = TRUE,
  thumbnails = TRUE,
  parallel = TRUE,
  processing_order = "by_groups",
  use_python = NA,
  tmpdir = NA,
  rmtmp = TRUE,
  log = NA
),
I need help with this error.

**Comment by rsbivand** [comment]
Please raise the issue at https://github.com/ranghetti/sen2r/issues, not here

**Comment by Pablocr7** [comment]
But it is an error with the sf library, if you put that error that I get, it sends me to the sf library, also that sen2r repository is not in operation because a bot tells me that it is no longer in assistance that github repository, I need help and I've been more than a week with that error.

**Comment by rsbivand** [comment]
So far, all ee know is that one or more geometries your are reading or handling are not valid. They are not made invalid by sf, so maybe your input data is invalid, or some choice you make leads to invalidity. Do look carefully at the output of `traceback()` run straight after you see the error message. Then try an equivalent example from the sen2r package itself, not your own data. Try to create a minimal example with publically available data that recreates your problem. Perhaps subscribe to the R-sig-geo mailing list and ask there? Or use a forum where other users of sen2r maybe found, perhaps stackoverflow. This is not the right place.

**Comment by Pablocr7** [comment]
ok, Thank you
