### ISSUE TITLE
[QUESTION] Is it possible to read in GeoJSON foreign members using sf_read?

### ISSUE THREAD

**Issue by Sparrow0hawk** [r-spatial/sf#2175]
## System information

R version
```R
> R.version.string
[1] "R version 4.1.3 (2022-03-10)"
```
sf version:
```R
> library(sf)
Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 7.2.1; sf_use_s2() is TRUE

> pkg = as.data.frame(installed.packages())
> pkg[pkg$Package == "sf","Version"]
[1] "1.0-12"
```

Operating System:

Windows 10 64-bit Build 19044

## Query

Suppose I had a GeoJSON:

```json
 {
  "type": "FeatureCollection",
  "features": [
    {
      "id": "d3b0f49fe255f0ea8c6ab567f876b139",
      "type": "Feature",
      "properties": {
        "name": "super thing"
      },
      "geometry": {
        "coordinates": [
          [
            [
              -1.671207540065211,
              53.784474184169426
            ],
            [
              -1.793723174508159,
              53.73814158611606
            ],
            [
              -1.742159355297673,
              53.6978638999239
            ],
            [
              -1.6283064424818008,
              53.72374369201003
            ],
            [
              -1.6171686575327726,
              53.75911951581881
            ],
            [
              -1.671207540065211,
              53.784474184169426
            ]
          ]
        ],
        "type": "Polygon"
      }
    }
  ],
  "bar": "exciting stuff",
  "foo": "extra stuff 2"
}
```

Is it possible to use `read_sf` to read in this file and capture the foreign members within the GeoJSON (fields `bar` and `foo`) as columns in the associated sf dataframe?

## What i've tried

- `read_sf` without any extra options.

- `read_sf` with `options = "NATIVE_DATA=YES" as per [GDAL GeoJSON driver docs](https://gdal.org/drivers/vector/geojson.html#open-options)

Both of these just seem to skip the foreign members and only populate the data.frame from what is within `features` which is the expected default behaviour. But if I wanted to add columns for `bar` and `foo` I'm unsure of how to do this/if its possible

**Comment by edzer** [comment]
You can try `ogr2ogr` (or `gdal_utils("vectortranslate", ...)`) to see if what you have in mind corresponds to what the GDAL driver does, e.g. by roundtripping your GeoJSON -> GPKG -> GeoJSON.
