### ISSUE TITLE
Install in conda R

### ISSUE THREAD

**Issue by WJackKing** [r-spatial/sf#2177]
**Describe the bug**

In conda environment, install in R instead of installing r-sf using conda, there is an error:

```text
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available for running:... dyld[11597]: Library not loaded: @rpath/libgdal.33.dylib
  Referenced from: <8BA3DCE2-C830-32CE-8326-1089FA52A144> /private/var/folders/k9/smz46jnx12vbrvk5_cbrfpmh0000gn/T/RtmpszLAZc/R.INSTALL2c0e51f79815/sf/gdal_proj
  Reason: tried: '/usr/local/lib/libgdal.33.dylib' (no such file), '/usr/lib/libgdal.33.dylib' (no such file, not in dyld cache)
./configure: line 3665: 11597 Abort trap: 6           ./gdal_proj
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
ERROR: configuration failed for package ‘sf’
```

**To Reproduce**

```bash
conda activate R
```
```R
install.packages("sf")
```

**Additional context**

This may something helpful.

Report this error in configure(line: 3664):
```bash
{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking GDAL: checking whether PROJ is available for linking:" >&5
printf %s "checking GDAL: checking whether PROJ is available for linking:... " >&6; }
${CXX} ${CPPFLAGS} -o gdal_proj gdal_proj.cpp ${LIBS} 2> errors.txt
if test `echo $?` -ne 0 ; then
gdal_has_proj=no
{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
printf "%s\n" "no" >&6; }
else
gdal_has_proj=yes
{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
printf "%s\n" "yes" >&6; }
fi

if test "${gdal_has_proj}" = no; then
   cat errors.txt
   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: Install failure: compilation and/or linkage problems." >&5
printf "%s\n" "$as_me: Install failure: compilation and/or linkage problems." >&6;}
   as_fn_error $? "cannot link projection code" "$LINENO" 5
fi

{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking GDAL: checking whether PROJ is available for running:" >&5
printf %s "checking GDAL: checking whether PROJ is available for running:... " >&6; }
./gdal_proj
```

The reason is when compile something in conda environment, rpath should be changed by manual.

Reference: https://docs.conda.io/projects/conda-build/en/latest/resources/use-shared-libraries.html

In macOS, it should be:
```bash
install_name_tool gdal_proj -add_rpath ${CONDA_PREFIX}/lib
```

I install successfully after execute: `ln -sf ${CONDA_PREFIX}/lib/libgdal.33.dylib /usr/local/lib`, but I don't think this is perfect solution.

<details>

```text
R version 4.3.0 (2023-04-21)
Platform: aarch64-apple-darwin20.0.0 (64-bit)
Running under: macOS Ventura 13.4

Matrix products: default
BLAS:   ~Softwares/micromamba/envs/main/lib/R/lib/libRblas.dylib 
LAPACK: ~/Softwares/micromamba/envs/main/lib/R/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/zh_CN.UTF-8

time zone: Asia/Shanghai
tzcode source: system (macOS)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.0 tools_4.3.0
```

</details>

**Comment by edzer** [comment]
What makes you think this is an issue with `sf`, and not with conda or conda-R?

**Comment by WJackKing** [comment]
> What makes you think this is an issue with `sf`, and not with conda or conda-R?

@edzer Sorry, I'm not so sure, if I do something wrong, please let me known how to fix.

There is some reason:

When I install `gert` in same environment, it depend on libgit2, so it will fail too, but after install libgit2, it will complie correct. So I think , mayby there need some patch in how to complie.

In conda, I don't think it is a good idea that add a dynamic library directory to system path, the solution is modify rpath or ORIGIN in executable file. So, we can use program installing in conda environment without change system environment.

Anywhere, if there is nothing to do, I'll close this issue.

**Comment by edzer** [comment]
The error following 
```
checking GDAL: checking whether PROJ is available for running:
```
indicates a problem in your (conda) environment, not in `sf`.

**Comment by WJackKing** [comment]
> The error following
> 
> ```
> checking GDAL: checking whether PROJ is available for running:
> ```
> 
> indicates a problem in your (conda) environment, not in `sf`.

The process of installing halt in there, because there is a test code run error

```cpp
// The block of code is in configure file, and it will test if gdal link correct.
// configure will compile it, and test the out(gdal_proj) whether have correct result or not
#include <gdal.h>
#include <ogr_srs_api.h>
#include <ogr_spatialref.h>
int main(int argc, char *argv[]) {
	OGRSpatialReference *dest = new OGRSpatialReference;
	OGRSpatialReference *src = new OGRSpatialReference;
    src->importFromEPSG(4326);
    dest->importFromEPSG(3857);
	OGRCoordinateTransformation *ct = OGRCreateCoordinateTransformation(src, dest);
	return(ct == NULL); // signals PROJ is not available through gdal
}
```

I write a makefile to test different complie command
```makefile
# This command similar to configure file, it will report an error
a.out: gdal_proj.cpp
    clang++ `gdal-config --libs` `gdal-config --cflags` gdal_proj.cpp -o a.out

# This command will work correct
b.out: gdal_proj.cpp
    clang++ -Wl,rpath ${CONDA_PREFIX}/lib `gdal-config --libs` `gdal-config --cflags` gdal_proj.cpp -o b.out
```

The error information is:
```text
dyld[15569]: Library not loaded: @rpath/libgdal.33.dylib
  Referenced from: <F39EDAD7-44D2-3C0C-AF84-323D62943A19> ~/Downloads/test/a.out
  Reason: tried: '/usr/local/lib/libgdal.33.dylib' (no such file), '/usr/lib/libgdal.33.dylib' (no such file, not in dyld cache)
zsh: abort      ./a.out
```

Actually, there is some solution:
1. link libgdal.33.dylib in system library path. (This will broke system programs)
2. modify $DYLD_LIBRARY_PATH in ${CONDA_PREFIX}/etc/conda/activated.d directory. (This will broke conda programs)
3. modiry rpath, let gdal_proj known how to find libgdal.

**Comment by WJackKing** [comment]
I know I can't install correct is because I'm using conda, but I don't know how to just modify conda environment and not broke other environment. The only perfect solution what I know is modifying compile command.
I can just modify configure file to install, but there may other file need to link gdal dynamic library, so I comment this issue.
There also have some solution, like install r-sf from conda-forge, or use brew. But I hope can install packages only from (CRAN and bioconductor) or conda-forge, and I hope have a pure environment. Moreover, unfortunately, in m1 macOS, there is some packages not included by conda-forge.
If there is no need to adapt conda, it's allright.

**Comment by WJackKing** [comment]
This solution will work perfect:

1. link needed dynamic library to system library
    ```bash
    # example
    ln -sf ${CONDA_PREFIX}/lib/libgdal.33.dylib /usr/lib
    ````
2. install package
    ```r
    install.packages("sf")
    ```
3. unlink soft link
    ```bash
    unlink /usr/lib/libgdal.33.dylib
    ```

Notes:

1. Link file in system library directory need administor privilege.
2. The dylib name will show in error messages.
3. After unlink, `sf` will still work. Because when start R, environment variable DYLD_FALLBACK_LIBRARY_PATH will be set. `/usr/lib/libgdal.33.dylib` will be used only when configure gdal.
