### ISSUE TITLE
User-unfriendly error from st_sfc(<sf object>)

### ISSUE THREAD

**Issue by MichaelChirico** [r-spatial/sf#2180]
I am still an `sf` noob and was trying to get the `sfc` object out of an `sf` object using the first function I found that looked helpful: `st_sfc()`:

```r
system.file("shape", "nc.shp", package="sf") |>
 st_read() |>
  st_sfc()
```

But this gives (cryptic if I'm not a heavy R user already) error:

```
Error in vapply(lst, class, rep(NA_character_, 3)) : 
  values must be length 3,
 but FUN(X[[1]]) result is length 2
```

It looks like `st_sfc()` is not doing enough input validation; it winds up assuming the input inherits from `sfc_GEOMETRY` when in actuality it's `c("sf", "data.frame")`:

https://github.com/r-spatial/sf/blob/e91f5e386d16011b7d2d3599d2ce0d6ff7e0d6fc/R/sfc.R#L127

It would be more user-friendly to error earlier for this case.

Also FWIW as an aside, it's odd to me to run `vapply()` to return an `n` by `3` matrix and then only use `n` by `1` of the results, tossing away 66% of the computation. This might be better:

```r
attr(lst, "classes") = vapply(lst, \(x) class(x)[2L], character(1L))
```

**Comment by edzer** [comment]
But why don't you pipe into `st_as_sfc()` - that is meant as a converter, `st_sfc()` is meant as a constructor.

**Comment by MichaelChirico** [comment]
To be clear, I'm definitely committing an error here -- I don't think there's any bug in `st_sfc()`.

Just that the failure mode is puzzling/not very helpful for a "new" user like me.
