### ISSUE TITLE
Amazon Linux 2023 - Unable to install sf - error installing dependency package units - needs udunits2 

### ISSUE THREAD

**Issue by franc703** [r-spatial/sf#2192]
I am working on an Amazon Linux 2023 ec2 instance. I have tried to install sf package, but it shows me an error that units cannot be installed. When I try to install units, it tells me I need udunits2. I do not know how to get udunits2 for amazon Linux 2023.

**Comment by rsbivand** [comment]
This is not a supported platform. The previous package was from EPEL, udunits-devel. It is not in https://docs.aws.amazon.com/linux/al2023/release-notes/all-packages-AL2023-2023.0.20230614.html, but does this version support EPEL?

**Comment by edzer** [comment]
> `I do not know how to get udunits2 for amazon Linux 2023.

Install from source?`
