### ISSUE TITLE
Legacy 'sp' notice on 'sf' startup

### ISSUE THREAD

**Issue by francisbarton** [r-spatial/sf#2193]
My package uses some `sf` functions. I don't call `sp` functions directly anywhere and only `sf` is in my Imports list in the DESCRIPTION file.
I also have `tmap` in my Suggests list.

When I load my package, I get the 

> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023....

startup message at the console. I don't think this message applies to my package as I am already using pure sf and not relying directly on sp. How can I turn this message off please?

**Comment by rsbivand** [comment]
Please name your package. Then track back through its strong dependencies, to find the subset of packages with strong dependencies on `sp`, may be `tmap`, others too.

**Comment by francisbarton** [comment]
Thanks Roger. My package is not on CRAN so no need to worry about it as a revdep for `sp`.

I am sure it is the `tmap` package that is generating the message. When I do `library(tmap)` I get the same message. Presumably because it Imports `stars`.

If I remove tmap from my Suggests list, then reload my package, I don't get the message.
I didn't think packages in the Suggests list were loaded when a package is loaded, but that is an issue for another place, not here.
