### ISSUE TITLE
`key.pos` error for `plot.sf()` with multiple factor-valued columns

### ISSUE THREAD

**Issue by henryrscharf** [r-spatial/sf#2196]
**Describe the bug**
An error occurs when trying to plot a key (e.g., `key.pos = 1`) for multiple character/factor valued columns.

**To Reproduce**
```
sf_obj <- st_as_sf(x = data.frame(a = factor(1:3, levels = 1:4), 
                                                         b = factor(2:4, levels = 1:4), 
                                                         x = c(1, 1, 2), y = c(1, 2, 2)), 
                                coords = c("x", "y"))
plot(sf_obj, pch = 15, cex = 5, key.pos = 1)
```

**Additional context**
I think I identified the problem in the `plot.sf()` function. I submitted a pull request.

<details>
Error in classInt::classIntervals(v0, min(nbreaks, n.unq), breaks, warnSmallN = FALSE) : 
  var is categorical
</details>

Thanks,
Henry

**Comment by edzer** [comment]
PR merged.
