### ISSUE TITLE
Thank you and a couple of (small) feature requests

### ISSUE THREAD

**Issue by MikkoVihtakari** [r-spatial/sf#2197]
After translating [ggOceanMaps to sf and stars](https://github.com/MikkoVihtakari/ggOceanMaps/tree/sf-version), I can only admire the level of programming in these packages. These packages are true masterpieces. They improve the old geospatial packages for R on every level, are intuitive to use, fast and efficient. Thank you so much for everyone involved in making and maintaining these packages!

While doing the translation I was missing (only) two small things. When referring to packages in my packages, I like to do something like: 

> This function uses `\link[ggplot2:ggplot2-package]{ggplot2}` to ...

in my `roxygen2` code. This is a convenient way of acknowledging a package and makes a link to the documentation of that package which, I believe, can help the user to browse through the documentation. Both `sf` and `stars` packages lack the package-wide Rd file. The sf package has `sf::sf`, which I used, and which is good enough I suppose, but I could not find anything for stars. Could that be added?

Another one: I do something like the following a lot in my package:

```r
limits <- c(11,16,67.3,68.6)
limits <- setNames(limits, c("xmin","ymin","xmax","ymax"))
sf::st_bbox(sf::st_transform(sf::st_as_sfc(sf::st_bbox(limits, crs = 4326)), crs = 3995))
```

It does not work without the `sf::st_bbox(sf::st_as_sfc())` step, which I find counterintuitive since there are already so many methods that work for `bbox`. Could it be possible to add a method for `bbox` to `st_transform` which does the `sf::st_bbox(sf::st_as_sfc())` step?

**Comment by edzer** [comment]
Thanks for your comments, @MikkoVihtakari and yes these files can and should be added; feel free to PR.

> which I find counterintuitive

The thinking behind this, I believe, is that you can transform these four corners, but that that does not give you the bounding box of the transformed geometry. If you transform a square (the polygon) you just do that. The bounding box is thought of as metadata of a geometry; to get the bounding box of transformed geometries you'll have to transform the geometry and then compute the bounding box of that. In many cases (the thinking behind `st_graticule()`) you can compute the polygon, segmentize that, transform that, and compute the bounding box from it, but I don't think it a good idea to pack that underneath a transformation of a `bbox`.

**Comment by MikkoVihtakari** [comment]
True enough, I used `smoothr::densify` in the transformation. Perhaps best to keep it as it is then. 

I think I won't time to add the package-wide Rd files before my holiday but can do it this autumn if they have not been added already.
