### ISSUE TITLE
Minor adjustments to as.ppp.sf

### ISSUE THREAD

**Issue by agila5** [r-spatial/sf#2201]
Dear all, I was wondering if it would be possible to add `W` and `check` arguments to `as.ppp.sf` method 

https://github.com/r-spatial/sf/blob/e6e5696c7b9e7777299fc45d10c8354621f81803/R/spatstat.R#L141-L143

so that the new parameters can be passed directly to `as.ppp.sfc`: 

https://github.com/r-spatial/sf/blob/e6e5696c7b9e7777299fc45d10c8354621f81803/R/spatstat.R#L122-L125

I know I can easily adjust the Window of the ppp after creating it, but I don't see any reason why those arguments are allowed only when the input is a `sfc` instead of `sf`. Happy to create a PR if that's just a typo.

**Comment by edzer** [comment]
Good idea; please check whether this one does it.

**Comment by agila5** [comment]
Works perfectly, thanks!
