### ISSUE TITLE
[Cross-Post] Polygon/multipolygon columns: incorrect write, correct read

### ISSUE THREAD

**Issue by pachadotdev** [r-spatial/sf#2206]
https://github.com/r-dbi/RPostgres/issues/439

**Comment by edzer** [comment]
@etiennebr

**Comment by pachadotdev** [comment]
> This only concerns the `dbWriteTable()` method for sf(c) objects, so I think this is better handled here than in RPostgres.
> 
> The issue is that dbWriteTable(append = TRUE) does not generate the appropriate field types in Postgres, if the table does not yet exist.
> 
> A more minimal example:
> 
> ```r
> library(RPostgres)
> library(sf)
> #> Linking to GEOS 3.11.2, GDAL 3.6.2, PROJ 9.2.0; sf_use_s2() is TRUE
> 
> # let's use the standard st_read example to make things simpler
> nc <- st_read(system.file("shape/nc.shp", package="sf"))
> #> Reading layer `nc' from data source 
> #>   `C:\Users\Daniel.AK-HAMBURG\AppData\Local\R\win-library\4.3\sf\shape\nc.shp' 
> #>   using driver `ESRI Shapefile'
> #> Simple feature collection with 100 features and 14 fields
> #> Geometry type: MULTIPOLYGON
> #> Dimension:     XY
> #> Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
> #> Geodetic CRS:  NAD27
> 
> # con-fig defined in https://www.postgresql.org/docs/current/libpq-pgservice.html
> # password via https://www.postgresql.org/docs/current/libpq-pgpass.html
> con <- dbConnect(Postgres(), service = "test")
> 
> # append = TRUE does not define table structure (and doesn't warn)
> dbWriteTable(con, "nc_append", nc, append = TRUE)
> dbGetQuery(con, r"(SELECT pg_typeof("geometry") FROM nc_append LIMIT 1)")
> #>   pg_typeof
> #> 1      text
> ```
> 
> no problems with dataframes and `append = FALSE`
> clean-up
> Session info
> Now is that a problem or should the user be smart enough to use `append = TRUE` when initializing a table?
> 
> IMHO there should either be a warning , if the table does not exist.
> 
> Or `dbWriteTable.sf` should generate the correct field types (this is what [vanilla `RPostgres::dbWriteTable()` does](https://github.com/r-dbi/RPostgres/blob/58a052b20f046c95723c332a0bb06fdb9ed362c4/R/dbWriteTable_PqConnection_character_data.frame.R#L60-L71)), e.g. change
> 
> https://github.com/r-spatial/sf/blob/732525f7ce1027473bfd4700192ec969e9af768e/R/db.R#L474-L476
> 
> to
> 
> ```
> # DBI stops if append && !is.null(field.types)
> if (append) {
>   found <- dbExistsTable(conn, name)
>   if (found) {
>     append <- FALSE
>   } else {
>     field.types <- NULL
>   }
> }
> ```
> 
> (This all needs to happen because `RPostgres::dbWriteTable()` will `stop()` if `append && !is.null(field.types)` - but maybe it should only do this if a table exists? 🤔).

thanks a lot! it looks I made a discovery here

**Comment by etiennebr** [comment]
Thanks a lot @pachadotdev for the report and @dpprdan for the fix. I'll write a few tests and try to push a fix rapidly.
