### ISSUE TITLE
poly2nb provide 0 neighbor in US county shapefile

### ISSUE THREAD

**Issue by Vickyxubba** [r-spatial/sf#2208]
Hello everyone,

I am trying to define number of neighbor for 3108 US counties using poly2nb, however, I always have three counties have "0" neighbors... I have try to change the value of snap in poly2nb function, but without luck. Could anyone help me with this issue? 
Thanks in advance!

bCRS<-CRS("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs")

ustry<-readShapePoly("USA_Counties/USA_Counties.shp", proj4string=bCRS)

us.3108=ustry[ustry$STATE_FIPS != '02' & ustry$STATE_FIPS != '15', ]

us.poly<-poly2nb(us.3108, snap=1000, queen=FALSE)----have tried different values of snap, but no luck :/
us.nb<-nb2WB(us.poly)

us.nb$num ------the num has three counties with "0" neighbors...

**Comment by rsbivand** [comment]
Not this repository. Please repeat with a fully reproducible example at https://github.com/r-spatial/spdep/issues/, with the actual data or a link to where you downloaded them. 

Note that the function you are using to read the shape file has been long deprecated and `maptools` will be retired very shortly, as it tells you when it loads.

**Comment by rsbivand** [comment]
@Vickyxubba Please close this issue now, resolution on https://github.com/r-spatial/spdep/issues/131.
