### ISSUE TITLE
Style de mat2listw(W) dans CARBayesST

### ISSUE THREAD

**Issue by gadouaka** [r-spatial/sf#2209]
Bonsoir apres avoir exécuté mes commandes suivantes:

coordo |> dnearneigh(0, 6.5) -> nb
nb <- as.matrix(nb)
list.nb2 <- mat2listw(nb, style = "B")
try(nb |> nb2listw(style="B") -> list.nb1)
summary(list.nb1)
W1 <- nb2mat(nb, style = "B")
list.nb1 <- nb2listw(neighbours = W1, style = "B")
model2 <- CARBayesST::ST.CARanova(formula = formula, family = "binomial", data = DISTRICT, trials = DISTRICT$ANNEE, W = W1, burnin = 20000, n.sample = 120000, thin = 10)
LES MESSAGE D ERREURS SUIVANTS S AFFICHES: 
Warning message: In mat2listw(W) :
  style is M (missing); style should be set to a valid value
S vous pouvez m'aider a resoudre ce probleme afin d executer mon modele CARBayesST

**Comment by rsbivand** [comment]
Not this repository, use https://cran.r-project.org/package=spdep, or ask on R-sig-geo, in both cases with a mininal reproducible example. Really, https://github.com/duncanplee/CARBayesST/issues is most appropriate. Please close this issue.
