### ISSUE TITLE
failed to load on MacOS (x86 and M2)

### ISSUE THREAD

**Issue by akrenner** [r-spatial/sf#2217]
**Describe the bug**
Building sf from source, compilation finishes, then during testing I get: 
`Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/me/proj/renv/staging/1/00LOCK-sf/00new/sf/libs/sf.so':
  dlopen(/Users/me/proj/renv/staging/1/00LOCK-sf/00new/sf/libs/sf.so, 0x0006): Symbol not found: __ZN3Aws6Client19ClientConfigurationC1Ev
  Referenced from: <FA8C3295-2793-3C69-A419-16C41753696B> /opt/homebrew/Cellar/apache-arrow/12.0.1_4/lib/libarrow.1200.1.0.dylib
  Expected in:     <BDB1F1E3-0BE9-3D7D-A57E-9D9F8CAD197A> /opt/homebrew/Cellar/aws-sdk-cpp/1.11.145/lib/libaws-cpp-sdk-core.dylib
Error: loading failed
Execution halted
ERROR: loading failed`
I get the same result on a mac-mini and an older MacBook Pro when trying to load an already installed copy of sf. General set-up is the same on both machines: supporting libraries (gdal, proj) installed with brew. I tried reinstalling gdal, apache-arrow, aws-sdk-cpp, and R to no effect (using brew as well as installing from source). 

**To Reproduce**
On a current MacOS platform (latest MacOS, brew freshly updated). 
'% brew install gdal proj pkg-config'
'> install.packages ("sf")'

<details>
'> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin22.4.0 (64-bit)
Running under: macOS Ventura 13.5.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /opt/homebrew/Cellar/r/4.3.1/lib/R/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Anchorage
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.1  tools_4.3.1     curl_5.0.2      remotes_2.4.2.1 renv_1.0.2 '

My apologies, I do not know whether this issue is with sf, apache-arrow, aws-skd-cpp, or elsewhere.

**Comment by rsbivand** [comment]
Use of homebrew is not supported here. Arrow is fast-moving and hard to support; on Linux GDAL can be built to support arrow and parquet drivers.

**Comment by akrenner** [comment]
The issue has been resolved in latest version of dependent library. All is well again. Thank you!
