### ISSUE TITLE
st_transform silently drops coordinates

### ISSUE THREAD

**Issue by jflowernet** [r-spatial/sf#2219]
When transforming a polygon from Mollweide to lon-lat, `st_transform` silently drops points that cross the antimeridian. This result in the polygon going from a rectangle to a triangle in the following example, which puzzled me till someone kindly [explained what was happening](https://stackoverflow.com/questions/76966457/why-does-re-projecting-a-rectangle-polygon-result-in-a-triangle-using-sf-in-r) on Stackoverflow. 

I wasn't sure if this is intended behaviour? It would be helpful if there was a message rather than happening silently

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1; sf_use_s2() is TRUE

#define bounding box I'm interested in - this is for Australia's EEZ and is in Mollweide projection
polygon_bbox_moll <- st_bbox(c(xmin =9797297, xmax = 15540552, ymin = -5576498, ymax = -1096691), crs = st_crs("ESRI:54009")) |>
  st_as_sfc() 

#plot - Mollweide
plot(polygon_bbox_moll, graticule = T, axes=T, las=1)
```

![](https://i.imgur.com/qNF26im.png)

``` r

#project bounding box to lon lat coordinates
polygon_bbox_lonlat <- polygon_bbox_moll|>
  st_transform(4326) 

#plot - lonlat
plot(polygon_bbox_lonlat, graticule=T, axes=T, las=1)
```

![](https://i.imgur.com/gWRJyH7.png)

``` r

#lon lat polygon has one less coordinate
st_coordinates(polygon_bbox_moll)
#>             X        Y L1 L2
#> [1,]  9797297 -5576498  1  1
#> [2,] 15540552 -5576498  1  1
#> [3,] 15540552 -1096691  1  1
#> [4,]  9797297 -1096691  1  1
#> [5,]  9797297 -5576498  1  1

st_coordinates(polygon_bbox_lonlat)
#>              X          Y L1 L2
#> [1,] 124.37141 -47.193643  1  1
#> [2,] 156.21908  -8.883331  1  1
#> [3,]  98.48587  -8.883331  1  1
#> [4,] 124.37141 -47.193643  1  1
```

<sup>Created on 2023-08-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kadyb** [comment]
`{terra}` emits a warning message from GDAL, but it looks like the final geometry is incorrect.

```r
library("terra")
v = vect(polygon_bbox_moll)
v = project(v, "EPSG:4326")
#> Warning message:
#> Point outside of projection domain (GDAL error 1)
plot(v)
#> Error in x@ptr$linesNA() : negative length vectors are not allowed
```

**Comment by jflowernet** [comment]
Interesting, thanks for the comparison. I feel like the warning could be a bit more informative, e.g. points cross the antimeridian, but I guess there are other use cases the warning will apply to.

**Comment by edzer** [comment]
@jflowernet would you consider that point across the antimeridian in the Mollweide projection to be a point on the Earth? And if so, where is it?

We could go by (un)projecting point by point, but then we would get back NA's, and these are not allowed in geometries:
```r
> st_coordinates(polygon_bbox_moll)[,1:2] |>                                                                                                                           
+   sf_project(from = st_crs("ESRI:54009"), to = st_crs(4326))                                                                                                         
          [,1]       [,2]                                                                                                                                              
[1,] 124.37141 -47.193643                                                                                                                                              
[2,]        NA         NA                                                                                                                                              
[3,] 156.21908  -8.883331                                                                                                                                              
[4,]  98.48587  -8.883331                                                                                                                                              
[5,] 124.37141 -47.193643                                                                                                                                              
Warning message:                                                                                                                                                       
In CPL_proj_direct(from_to, as.matrix(pts), keep, warn, authority_compliant) :                                                                                         
  one or more projected point(s) not finite         
```

**Comment by jflowernet** [comment]
@edzer Haha, good question! I think I see your point (no pun intended): the point is literally off the Earth.

While I appreciate that it is not `sf`'s job to ensure that people are using points within the realm of the Earth, I was wondering if it is worth including a warning to at least alert the user that points have been dropped/ NA geometry returned when this happens with `st_transform`? Or maybe this is a very niche case?

Another example of the NA geometry being silently returned below, which is somewhat closer to how I discovered the issue (I was actually projecting a polygon to Mollweide, taking the bounding box of that new polygon, cropping some data, and returning to lon-lat)

``` r
polygon_equator_lonlat <- st_bbox(c(xmin =-180, xmax = 180, ymin = -10, ymax = 10), crs = 4326) |>
  st_as_sfc() 

polygon_equator_lonlat %>% 
  st_transform("ESRI:54009")
#> Geometry set for 1 feature 
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -17870470 ymin: -1234041 xmax: 17870470 ymax: 1234041
#> Projected CRS: World_Mollweide
#> POLYGON ((-17870468 -1234041, 17870468 -1234041...

polygon_equator_lonlat %>% 
  st_transform("ESRI:54009") %>% 
  st_transform(4326)
#> Geometry set for 1 feature  (with 1 geometry empty)
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
#> Geodetic CRS:  WGS 84
#> POLYGON EMPTY
```

**Comment by edzer** [comment]
Well, you can see above what terra does: emit the error message and return an invalid geometry. You can now:

* filter on empty geometries returned by `st_transform` and examine them what was the problem
* use `sf_project` and check for `NA` values to find the exact problem points

I know it's cumbersome, but as you say it is not `sf`'s task to solve problems created by others.

**Comment by jflowernet** [comment]
Fair enough!

Many thanks for the discussion, and for the amazing package that is `sf`.
