### ISSUE TITLE
Write GPKG returns uninformative error message: Error: Impossible: field count reached

### ISSUE THREAD

**Issue by dominiqueweber** [r-spatial/sf#2225]
The error message occurred when trying to write features that have a field with the same name but one is capitalised and the other is not. This can easily happen when intersecting or merging multiple features and the error message was quite confusing to me.

Reproducible example
```
library(sf)
p <- st_as_sf(data.frame(SHAPE=1, shape=2, geom="POINT (2700348 1246597)"), wkt="geom", crs=2056)
write_sf(p, file.path(tempdir(), "p.gpkg"))
```
Error message:
`Error: Impossible: field count reached`

**Comment by rsbivand** [comment]
Do you expect the field count to be case-sensitove wrt. names?

**Comment by edzer** [comment]
I found [this](https://gis.stackexchange.com/questions/169090/how-to-open-and-save-qgis-datasource-with-to-lower-case-fields) answer, note that GPKG is SQLite.
