### ISSUE TITLE
st_make_grid behavior using squares

### ISSUE THREAD

**Issue by kbondo1** [r-spatial/sf#2232]
I was trying to use st_make_grid to create a grid of square polygons over the boundary of the state, but the grid is covering the bounding box of the shapefile rather than the geometries of the state boundary. It covers the geometries when using hexagons but not squares. 

The square grid I am trying to create is in the example code below. I am unable to reproduce this example as when I run this code on my computer, the grid covers the entire bounding box of the shapefile as well. 

(https://stackoverflow.com/questions/53789313/creating-an-equal-distance-spatial-grid-in-r)

Is this a bug in the package, or are there any modifications I can make to the code to get this to work using the sf package?

I tried to use st_intersects, but then the polygons were inside the shapefile and were not equal in size (as shown in figure in link below), which is not what I wanted for my purposes.

(https://stackoverflow.com/questions/73522671/st-make-grid-not-using-correct-map-units)

**Comment by kbondo1** [comment]
Below is a reproducible example. 

When I run it again, it seems as though there are no differences between making grids with st_make_grid, squares = TRUE or FALSE, but when using st_make_grid I am unable to create a grid in the shape of a shapefile as I was able to do using combinations of the sf, sp, and raster packages. The closest I could come to recreating this grid with st_make_grid was in the example of grid 1 below, but the cells are not in the shapes of squares and appear to be circles. I found an example with reproducible code, shown at bottom of page, where st_make_grid was used to produce the grid over the boundaries of the shapfile, but when I tried, the grid using their code, the grid also was not in the shape of the shapefile and was rectangular, so I am unsure if their code was incorrect or if something has changed with the st_make_grid code since that example was produced.

#This is code for the grid over a shapefile using sf and raster and sp packages. I am trying to recreate this grid without using raster and sp packages.

library(raster)
library(sp)
library(sf)

nad83.2011.pa.north = "+proj=lcc +lat_1=41.95 +lat_2=40.88333333333333 +lat_0=40.16666666666666 +lon_0=-77.75 +x_0=600000 +y_0=0 +ellps=GRS80 +units=m +no_defs"

# Download the shapefile 
states <- tigris::states(resolution = "5m",
                         class = "sf",
                         progress_bar = FALSE)

PA=states[states$STUSPS=="PA",]


# Transform coordinate system 
PA <- st_transform(PA, nad83.2011.pa.north)
template=as_Spatial(st_buffer(st_transform(PA, crs(nad83.2011.pa.north)), dist = 10000)) 

resolution = 5000 

grid.template <- raster(extent(template), 
                        resolution = c(resolution,resolution),
                        crs =  crs(template))


gridPolygon <- rasterToPolygons(grid.template)

template=gridPolygon[template,]

plot(template)

![template](https://github.com/r-spatial/sf/assets/76447796/67326d5a-aed7-4e4b-a05b-799c8944a3a8)

#Grids using st_make grid

# Some grid results

# This one looks like what I am trying to create, but has circles and not squares.
grid1 <- template %>%
  st_make_grid(cellsize = c(resolution,resolution), what = "centers") %>%  st_intersection(template)

plot(grid1)

# Changing squares to true does not change the grid.
grid2 <- template %>%
  st_make_grid(cellsize = c(resolution,resolution), square = TRUE, what = "centers") %>%  st_intersection(template)

plot(grid2)

#This one places cells inside of shapefile and they are not all the same size along edges.
grid3 <- template %>%
  st_make_grid(cellsize = c(resolution,resolution), square = TRUE) %>%  st_intersection(template)

plot(grid3)

# This one is the same as grid 3 but with hexagons.
grid4 <- template %>%
  st_make_grid(cellsize = c(resolution,resolution), square = FALSE) %>%  st_intersection(template)

plot(grid4)

# This one makes a rectangular grid, but not in the shape of the shapefile. 
grid5 <- template %>%
  st_make_grid(cellsize = c(resolution,resolution), square = FALSE) 
plot(grid5)

# This one also makes a rectangular grid, but not in the shape of the shapefile. 
grid6 <- template %>%
  st_make_grid(cellsize = c(resolution,resolution), square = TRUE) 
plot(grid6)


![grid1](https://github.com/r-spatial/sf/assets/76447796/8c273685-ede3-4364-9608-93570bf1c291)

![grid3](https://github.com/r-spatial/sf/assets/76447796/7367fc33-3232-468f-8e16-916bca0f4abc)

![grid6](https://github.com/r-spatial/sf/assets/76447796/adebf88b-16f7-489b-8d06-d21fcd64e695)

#This example online said it should produce a grid with squares over the shapefile, but could not get it to work as they #described and was shown in link.
#https://stackoverflow.com/questions/53789313/creating-an-equal-distance-spatial-grid-in-r

library(dplyr)
library(RCzechia) # a package of Czech administrative areas
library(sf)

mesto <- kraje() %>% # All Czech NUTS3 ...
  filter(NAZ_CZNUTS3 == 'Hlavní město Praha') %>% # ... city of Prague
  st_transform(5514) # a metric CRS 

grid_spacing <- 1000  # size of squares, in units of the CRS (i.e. meters for 5514)

polygony <- st_make_grid(mesto, square = T, cellsize = c(grid_spacing, grid_spacing)) %>% # the grid, covering bounding box
  st_sf() # not really required, but makes the grid nicer to work with later

plot(polygony, col = 'white')
plot(st_geometry(mesto), add = T)

![polygony_mesto](https://github.com/r-spatial/sf/assets/76447796/6062a947-612e-4681-9660-cb28b2037f9c)

**Comment by edzer** [comment]
The reprex doesn't work: `template` is an `sp` object, and that doesn't go into `st_make_grid`. 

Whenever you specify `what = "centers"` `st_make_grid()` returns points, when plotted points may look like circles, but it is not as if you get circle geometries returned. I started cleaning up your reprex, if you can make it work I'll look into it further.

**Comment by kbondo1** [comment]
Sorry, I forgot to include the code in the reprex to recreate the template for the sf/terra packages. The reprex below should work. Thanks for clarifying about (what = "centers") was doing. That makes sense about them being points and not circles.  In the reprex below, I included code for the grid where I was trying to make it into the shape of the template, but where I was only getting a rectangular grid.


library(terra)
library(sf)

nad83.2011.pa.north="+proj=lcc +lat_1=41.95 +lat_2=40.88333333333333 +lat_0=40.16666666666666 +lon_0=-77.75 +x_0=600000 +y_0=0 +ellps=GRS80 +units=m +no_defs"

# Download the shapefile of PA
states <- tigris::states(resolution = "5m",
                         class = "sf",
                         progress_bar = FALSE)

PA=states[states$STUSPS=="PA",]

# Transform coordinate system to state plane
PA <- st_transform(PA, nad83.2011.pa.north)

template = sf::st_buffer(PA, 10000) 

#plot(st_geometry(template))

resolution = 5000

grid.template <- rast(template, 
                        resolution = c(resolution,resolution),
                        crs =  crs(template))

gridPolygon <- as.polygons(grid.template)

grid6 <- template %>%
  st_make_grid(cellsize = c(resolution,resolution), square = TRUE) 
plot(grid6)

**Comment by edzer** [comment]
Is 
```r
plot(st_as_sf(grid6)[template,])
```
what you are looking for?

**Comment by kadyb** [comment]
@kbondo1, maybe you want to use `st_intersects()` instead of `st_intersection()`? `st_intersects()` returns the indices and then you can choose these geometries without cropping.

**Comment by kbondo1** [comment]
@edzer, thank you so much! That was exactly what I was looking for!

@kadyb, thank you as well! That is an interesting solution and will try that too.

**Comment by kadyb** [comment]
I mean something like this, but what @edzer suggested is easier:

```r
library("sf")

nc = read_sf(system.file("shape/nc.shp", package = "sf"))
nc = st_geometry(nc)
grid = st_make_grid(nc)

idx = st_intersects(nc, grid)
idx = unique(unlist(idx))
plot(grid[idx])

# direct way
plot(grid[nc])
```

**Comment by kbondo1** [comment]
@kadyb, Thank you so much for your solution! That worked for me as well.
