### ISSUE TITLE
Should `wk_wkt` be detected by `st_as_sf()`?

### ISSUE THREAD

**Issue by kadyb** [r-spatial/sf#2237]
```r
library("sf")
library("wk")

nc = read_sf(system.file("shape/nc.shp", package = "sf"))
wkt = as_wkt(st_as_text(nc$geometry))
df = data.frame(ID = seq_along(wkt), geometry = wkt)
df = st_as_sf(df, crs = st_crs(nc))
#> Error in st_sf(x, ..., agr = agr, sf_column_name = sf_column_name) : 
#>   no simple features geometry column present
```

I wonder if this should work or not? I ask because `geos_geometry` from `{geos}` is automatically detected in the above case.

**Comment by edzer** [comment]
What speaks against using `geometry = st_as_sfc(wkt)`  (apart from loss of the CRS, which in  general happens with WKT)?

**Comment by kadyb** [comment]
It's ok too! This also works: `st_as_sf(df, crs = st_crs(nc), wkt = "geometry")`.

I'm just asking whether the result for `{geos}` and `{wkt}` should be identical.

**Comment by edzer** [comment]
Could you provide the `geos` example?

**Comment by kadyb** [comment]
```r
library("sf")
library("geos")

nc = read_sf(system.file("shape/nc.shp", package = "sf"))
wkt = geos_read_wkt(st_as_text(nc$geometry))
df = data.frame(ID = seq_along(wkt), geometry = wkt)
df = st_as_sf(df, crs = st_crs(nc))
```

**Comment by edzer** [comment]
In that case `geos` did the work to convert to an `sfc` column!

**Comment by kadyb** [comment]
Aa, so for `wk_wkt` it must also be done in `{wkt}`?
