### ISSUE TITLE
`summarise()` does not maintain point order

### ISSUE THREAD

**Issue by guslipkin** [r-spatial/sf#2243]
**Describe the bug**
An empty `summarise()` call can be used to combine points and then `st_cast("POLYGON")` can be used to cast as  a polygon. However, an empty `summarise()` call does not maintain point order and so the cast operation results in an incorrect and often invalid polygon. Using `summarise(geometry = st_combine(geometry))` results in the correct point order.

**To Reproduce**
```
coord_list <- list(
  c("lat" = -105.48676, "long" = 31.67854),
  c("lat" = -107.30489, "long" = 33.01507),
  c("lat" = -100.68105, "long" = 31.55757),
  c("lat" = -106.49827, "long" = 28.08346),
  c("lat" = -108.56362, "long" = 29.72790),
  c("lat" = -105.48676, "long" = 31.67854)
) 

# this produces an incorrect and invalid polygon
coord_list |>
  dplyr::bind_rows() |>
  sf::st_as_sf(coords = c("lat", "long")) |>
  dplyr::summarise() |>
  sf::st_cast("POLYGON") |>
  sf::st_as_sfc()

# this produces the expected result
coord_list |>
  dplyr::bind_rows() |>
  sf::st_as_sf(coords = c("lat", "long")) |>
  dplyr::summarise(geometry = sf::st_combine(geometry)) |>
  sf::st_cast("POLYGON") |>
  sf::st_as_sfc()
```

<details>
R version 4.3.0 (2023-04-21)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS 14.0

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
      "3.11.0"        "3.5.3"        "9.1.0"         "true"         "true"        "9.1.0"
</details>

**Comment by edzer** [comment]
Thanks, this is caused by a call to `union` in the GEOS upstream library, which does not have order preservation guarantees.
