### ISSUE TITLE
In rmarkdown (for md output at least) st_read is unaffected by warning = F, error = F, message = F and still outputs load message.

### ISSUE THREAD

**Issue by DanOlner** [r-spatial/sf#2246]
**Describe the bug**
In rmarkdown (for md output at least) st_read is unaffected by warning = F, error = F, message = F and still outputs load message.

**To Reproduce**
See [README.md in this repo](https://github.com/DanOlner/regionalGVAbyindustry) and associated Rmd script. Everything else remains hidden, st_read I can't suppress.

**If reporting a change from previous versions**

Please read https://cran.r-project.org/web/packages/sf/news/news.html first.

**Additional context**
Version: 1.0-14

<details>
Paste the output of your `sessionInfo()` and `sf::sf_extSoftVersion()`
</details>

**Comment by rsbivand** [comment]
Of course, those knitr chunk options control `stderr`, `st_read` uses `stdout`. Use `quiet=TRUE` https://r-spatial.github.io/sf/reference/st_read.html.

**Comment by DanOlner** [comment]
Thank you Roger, much appreciated. While not a bug, how would you feel about this as a feature request? Would be good for sf messages to act the same way as others in the way they react with markdown flags...? Happy to just drop it also, mind!

**Comment by rsbivand** [comment]
`stderr` and `stdout` are different output streams, output to `stdout` with `quiet=FALSE`, the default, is expected. `results='hide'` is what is suggested here: https://bookdown.org/yihui/rmarkdown-cookbook/hide-one.html, but with `echo=TRUE` will look odd, as the code shown will emit to `stdout` but the output will be suppressed. Best use the provided argument to the method.
