### ISSUE TITLE
Correct way of adding GDAL --config to read files from private AWS or Google Cloud Bucket

### ISSUE THREAD

**Issue by bjyberg** [r-spatial/sf#2251]
Sorry if this has been documented somewhere already, but I haven't been able to figure this out. I have a private google storage bucket that I would like to read data from. If it was a public bucket I would use: `sf::read_sf('/vsigs/bucket-name/dataset.gpkg)`. However, as this is a private bucket, somehow I need to set the configuration options for vsigs (i.e., GS_SECRET_ACCESS_KEY,
GS_ACCESS_KEY_ID, or GOOGLE_APPLICATION_CREDENTIALS). In GDAL this would be done using `--config GOOGLE_APPLICATION_CREDENTIALS "path/to/credential.json"`. However I can't find a way of passing this flag anywhere in the read_sf/st_read function or in the dsn itself. Thanks for the help!

**Comment by edzer** [comment]
My guess is that you set these environment variables in your shell session from which you start R, or inside R with `Sys.setenv()`

**Comment by bjyberg** [comment]
That works, thank you!
