### ISSUE TITLE
does sf actually work using duckdb as a storage engine?

### ISSUE THREAD

**Issue by lvalnegri** [r-spatial/sf#2265]
Hello, I'm looking into _duckdb_ as a spatial storage engine to see if I should substitute _flatgeobuf_ or _parquet_ with partial queries in R. I can easily use `POINT` in both read/write, but when using `POLYGON` I can write but not read back correctly.

Running this:
```
library(duckdb)
cn <- dbConnect(duckdb::duckdb())
dbExecute(cn, "LOAD 'spatial';")
st_write(yb[1:1000,], cn, 'SZN21')
```
is OK (`yb` is an `sf` object I'm using, but it's the same outcome with any polygon), and I can test something happened:
```
dbGetQuery(cn, "SHOW TABLES;")
```
that returns:
```
   name
1 SZN21
```
or
```
dbGetQuery(cn, 'DESCRIBE SZN21;')
```
that rightly returns:
```
  column_name column_type null  key default extra
1         SZN     VARCHAR  YES <NA>    <NA>    NA
2         LCT     VARCHAR  YES <NA>    <NA>    NA
3         CMN     INTEGER  YES <NA>    <NA>    NA
4      ordine     INTEGER  YES <NA>    <NA>    NA
5    geometry    GEOMETRY  YES <NA>    <NA>    NA
```
but then trying to read:
```
st_read(cn, 'SZN21', geometry_column = 'geometry')
```
I get this error:
```
Error in CPL_read_wkb(x, EWKB, spatialite) : 
  reading wkb type 48 is not supported
```

If I keep the `geometry_column` out, I get back the correct table, as a data.frame though.

Am I doing something wrong here, or `sf` does not support *duckdb* yet? It's very hard to actually find some info about it, beside using *duckdb* with its own spatial language.

Thanks

**Comment by kadyb** [comment]
I have never used `duckdb`, but maybe try setting `EWKB = FALSE` in `st_read()`.

**Comment by edzer** [comment]
@cboettig has been working on this, see also his duckdbfs package on [cran](https://cran.uni-muenster.de/web/packages/duckdbfs/index.html) (main site being down a.t.m.)

**Comment by lvalnegri** [comment]
> I have never used `duckdb`, but maybe try setting `EWKB = FALSE` in `st_read()`.

thanks for the ip, but it does work as well, but changes error:
```
wkbType: 825242416
Error in CPL_read_wkb(x, EWKB, spatialite) : 
  unsupported wkbType dim in switch
```

**Comment by lvalnegri** [comment]
> @cboettig has been working on this, see also his duckdbfs package on [cran](https://cran.uni-muenster.de/web/packages/duckdbfs/index.html) (main site being down a.t.m.)

thanks, I've seen this [mail exchange](https://stat.ethz.ch/pipermail/r-sig-geo/2023-August/029328.html), I'll read it next week, I need to put this aside for a while.

I've also tackled it from a different angle, but still wrong with a different error:
```
dbSendQuery(cn, "DROP TABLE if EXISTS test;")
dbWriteTable(cn, 'test', 
    data.table( yb[1:10,] |> st_drop_geometry(), G = yb[1:10,] |> st_geometry() |> st_as_binary() ),
    row.names = FALSE
)
dbExecute(cn, "CREATE OR REPLACE TABLE test AS SELECT *, ST_GeomFromWKB(G) as geometry, FROM test;")
dbGetQuery(cn, "DESCRIBE test;")
  column_name column_type null  key default extra
1         SZN     VARCHAR  YES <NA>    <NA>    NA
2         LCT     VARCHAR  YES <NA>    <NA>    NA
3         CMN     INTEGER  YES <NA>    <NA>    NA
4      ordine     INTEGER  YES <NA>    <NA>    NA
5           G        BLOB  YES <NA>    <NA>    NA
6    geometry    GEOMETRY  YES <NA>    <NA>    NA
st_read(cn, query = "SELECT * FROM \"test\";", geometry_column = "geometry")
Error in CPL_read_wkb(x, EWKB, spatialite) : 
  reading wkb type 0 is not supported
```

**Comment by cboettig** [comment]
At the moment, duckdb's native geometry type is not technically the same as wkb; you simply need to use `ST_AsWKB()` first.  

`duckdbfs` seeks to make this a bit easier for the average R user with the function `to_sf()`, e.g.

```r
ex <- 
"https://raw.githubusercontent.com/cboettig/duckdbfs/main/inst/extdata/spatial-test.csv" |>
  open_dataset(format = "csv") |>
  mutate(geometry = ST_Point(longitude, latitude)) |>
  to_sf()
```

**Comment by cboettig** [comment]
At the moment, duckdb's native geometry type is not technically the same as wkb; you simply need to use `ST_AsWKB()` first.  

`duckdbfs` seeks to make this a bit easier for the average R user with the function `to_sf()`, e.g.

```r
ex <- 
"https://raw.githubusercontent.com/cboettig/duckdbfs/main/inst/extdata/spatial-test.csv" |>
  open_dataset(format = "csv") |>
  mutate(geometry = ST_Point(longitude, latitude)) |>
  to_sf()
```

**Comment by lvalnegri** [comment]
Thanks Carl, but I can't get to replicate for my use case. I already have sf objects, I'm not interested in inputs from other sources, I don't see any use in both open_dataset and to_sf. Moreover, it's polygons, not points. As far as I can infer from my example, duckdb has a valid geometry field after the ST_GeomFromWKB, but I can't read it back, the idea is then to use a WKT filter in the st_read.

**Comment by lvalnegri** [comment]
ah, so I should essentially use duckdb as a "postgres substitute" and convert the result afterwards?

**Comment by edzer** [comment]
The `query` argument should contain the sql query with the wkt filtering, and the conversion to WKB (`ST_AsWKB`) of the geometry column in the result.

**Comment by e-kotov** [comment]
@edzer thank you for this tip!

@lvalnegri so essentially your query should be something like this:

```{r}
st_read(cn, query='SELECT ST_AsWKB(geometry) as geometry, * FROM SZN21', geometry_column = 'geometry')
```

**Comment by lvalnegri** [comment]
thanks to everyone! in the end I've got it through, and my 2¢ is that `duckdb` has not been up to its expectations, at least vs `flatgeobuf`, possibly got something wrong? not only fgb is quicker in wkt filtering, that's what I was questioning, it's also a third of the duckdb space!

Anyway, this is my workflow, using the 397,237 Italian small areas for 2011 census, and benchmarking the filtering of the 7,841 polygon intersecting the boundaries of Milan (well, bounding box here). If you think anything is wrong or can be done better, please let me know.

```
# install.packages('duckdb')
library(duckdb)
library(sf)

create_table <- \(x){
    dbWriteTable(x, 'test', 
        data.table( yb |> st_drop_geometry(), G = yb |> st_geometry() |> st_as_binary() ),
        overwrite = TRUE,
        row.names = FALSE
    )
    dbExecute(x, "CREATE OR REPLACE TABLE test AS SELECT *, ST_GeomFromWKB(G) as geometry, FROM test;")
    dbSendQuery(x, "ALTER TABLE test DROP COLUMN G;")
    dbGetQuery(x, "DESCRIBE test;")
}

# reading in the small areas polygons (SZN)
yb <- masteRconfini::SZN
st_write(yb, file.path(masteRfun::pub_path, 'temp', 'duckdb_test', 'yb.fgb'))

cnm <- dbConnect(duckdb::duckdb())
dbExecute(cns, "INSTALL 'spatial';")
dbExecute(cns, "LOAD 'spatial';")
create_table(cnm)

cns <- dbConnect(duckdb::duckdb(file.path(masteRfun::pub_path, 'temp', 'duckdb_test')))
dbExecute(cns, "INSTALL 'spatial';")
dbExecute(cns, "LOAD 'spatial';")
create_table(cns)

# ISTAT code for Milan (`CMN` are the municipalities, to get the bbox of the city)
xc <- 15146 
xbx <- masteRconfini::CMN |> subset(CMN == xc) |> st_bbox() |> st_as_sfc() |> st_as_text()
sqlq <- paste0("
            SELECT SZN, ST_AsWKB(geometry) as geometry 
            FROM test 
            WHERE ST_Intersects(geometry, ST_Envelope(ST_GeomFromText('", xbx, "')))
")
microbenchmark::microbenchmark(
    'DM' = st_read(cnm, query = sqlq, geometry_column = 'geometry', quiet = TRUE) |> st_set_crs(4326),
    'DS' = st_read(cns, query = sqlq, geometry_column = 'geometry', quiet = TRUE) |> st_set_crs(4326),
    'F' = st_read(
            file.path(masteRfun::pub_path, 'temp', 'duckdb_test', 'yb.fgb'), 
            query = paste0('SELECT SZN FROM \"yb\"'), 
            wkt_filter = xbx, 
            quiet = TRUE),
    times = 50
)
# Unit: milliseconds
#  expr       min       lq      mean    median        uq      max neval cld
#    DM 163.50542 203.4338 227.71882 229.29828 243.84201 300.5284    50  a 
#    DS 178.91915 207.6527 226.23508 226.74132 241.57942 273.1707    50  a 
#     F  77.72655  85.2343  92.45958  90.08768  97.13228 139.4609    50   b

dbDisconnect(cnm, shutdown = TRUE)
dbDisconnect(cns, shutdown = TRUE)
```
![image](https://github.com/r-spatial/sf/assets/1196949/78ea1f3c-8b28-4d26-8c92-4f42d7b97196)
