### ISSUE TITLE
Problems when using the st_intersects function within an r package

### ISSUE THREAD

**Issue by Molina-Valero** [r-spatial/sf#2267]
Hello,

I am having problems with the st_intersects function when it is used within an R package.

To put you in context, I am developing my own R package. I have created a function in which I need to intersect points ("sf" "data.table" "data.frame") by polygon ("sfc_POLYGON" "sfc"  ) to make a clip and continue processing the remaining points (points within polygons). For that purpose I run the follosing code:

```{r setup, include=FALSE}
points2 <- sf::st_intersects(polygon, points)
points2 <- data.table::setDT(as.data.frame(points2 ))
colnames(points2 ) <- c("tree", "code")
points$code <- as.numeric(row.names(points))
points <- merge(points, points2, by = "code", all = FALSE)
```

Everything works fine when I run the code or even when I run a function in which it is included (figure 1). However, I have problems when I am installing the package that includes this function, because although it works, the coordinates obtained are strange (figure 2). Thus, it affects the performance of the rest of the function.

![image](https://github.com/r-spatial/sf/assets/52129566/6f313535-a130-4a13-ad3b-5f0a19cda1fb)

![image](https://github.com/r-spatial/sf/assets/52129566/25911ba3-bdd0-4727-84a0-57bb0954215d)

I can give you more details if neccesary.

I would really appreciate any information about that, because I tried to solve it my myself but I do not know what else to do.

Best regards,
Juan

**Comment by rsbivand** [comment]
Never include pictures of code. Always provide a simple, reproducible example, avoiding othe packages, that is make it work without `data.table` first.

**Comment by Molina-Valero** [comment]
Thank you very much! I solved it just avoiding data.table objects.

Best regards!
