### ISSUE TITLE
Linking GDAL 3.7.2 and PROJ 9.3.0 lead to GDAL not recognizing the PROJCRS

### ISSUE THREAD

**Issue by geo-jd** [r-spatial/sf#2271]
I noticed yesterday (21.11.2023) that installing sf & stars (working with raster data) GDAL could not recognize the CRS.

```
Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE
packageVersion: ‘1.0.14’
```

Same Version of sf (`1.0.14`) installed 3 months ago works without any issues:

`Linking to GEOS 3.11.2, GDAL 3.6.3, PROJ 9.2.0 `

### Error Messages: 

**File format: "jp2":**

```
Warning messages:
1: In CPL_get_metadata(file, NA_character_, options) :
  GDAL Error 1: PROJ: proj_create: no database context specified
2: In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
  GDAL Error 1: PROJ: proj_create: no database context specified
```

**File format: "tif" (geotif):**

```
Warning messages:
1: In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
  GDAL Message 1: PROJ: proj_create_from_database: C:\Program Files\GDAL\projlib\proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation.
2: In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
  GDAL Message 1: The definition of projected CRS EPSG:32635 got from GeoTIFF keys is not the same as the one from the EPSG registry, which may cause issues during reprojection operations. Set GTIFF_SRS_SOURCE configuration option to EPSG to use official parameters (overriding the ones from GeoTIFF keys), or to GEOKEYS to use custom values from GeoTIFF keys and drop the EPSG code.

```
Using "GEOKEYS" allows me to retain the CRS but transformation was not possible.

My workaround for now was just copy-pasting the older sf library into my new environment - which works but is not a great solution by any means.

PS:
I'm working in R 4.3.1 on a Windows Machine.

**Comment by edzer** [comment]
This is a `stars` issue. Please provide a dataset that causes these problems, along with the command(s) you used.

**Comment by geo-jd** [comment]
I am working with sentinel 2 data. As you can see it did not make any (functional) difference if i used a tfi or a jp2 raster file.

[T34TFR_20230903T092559_AOT_60m.zip](https://github.com/r-spatial/sf/files/13440142/T34TFR_20230903T092559_AOT_60m.zip)

**Comment by edzer** [comment]
```r
> library(stars)
Loading required package: abind
Loading required package: sf
Linking to GEOS 3.11.2, GDAL 3.8.0, PROJ 9.3.0; sf_use_s2() is TRUE
> read_stars("/tmp/T34TFR_20230903T092559_AOT_60m.jp2")
stars object with 2 dimensions and 1 attribute
attribute(s), summary of first 1e+05 cells:
                                Min. 1st Qu. Median     Mean 3rd Qu. Max.
T34TFR_20230903T092559_AOT_...   109     117    119 118.1433     120  125
dimension(s):
  from   to  offset delta                refsys x/y
x    1 1830   6e+05    60 WGS 84 / UTM zone 34N [x]
y    1 1830 5100000   -60 WGS 84 / UTM zone 34N [y]
> 
```

**Comment by edzer** [comment]
It seems your proj installation is confused; is the `PROJ_LIB` environment variable set to some directory by other software?

**Comment by geo-jd** [comment]
Yes, you seem to to be correct. 

The PROJ_LIB argument seems to point to an older "standalone" GDAL/proj.db. 
Still, it stands out to me that this problem was _partly_ solved by copy-pasting a sf library from another machine into my new project. That did not impact the PATH variables. I still have issues when calling the different QGIS GDAL.exe's for some commands, as i need to first set the R environment to the sf-internal proj.db.
Is there a way to force sf to use its internal ressources (except "manually" setting them inside the script)?

PS:
Is there a reason you tested with GDAL 3.8 instead of GDAL 3.7.2?

**Comment by edzer** [comment]
> Is there a reason you tested with GDAL 3.8 instead of GDAL 3.7.2?

No

**Comment by edzer** [comment]
I suspect the upstream software (PROJ) is designed such that setting `PROJ_DIR` overrules everything; `sf` tries avoiding to set it (it uses a C API function for this) to the sf package directory, but setting `PROJ_DIR` overrules this. I don't think that that is configurable.

**Comment by geo-jd** [comment]
Ok thanks for checking! 

Just to summarize, this means I am stuck with setting the PROJ_LIB in the R environment (and do the equivalent for any Python code)?

**Comment by edzer** [comment]
I think that starting your R script with `Sys.setenv(PROJ_LIB="")` should be enough.

**Comment by rsbivand** [comment]
Or `Sys.unsetenv("PROJ_LIB")` on platforms that support it.
