### ISSUE TITLE
[Question]: How does `sgbp` work?

### ISSUE THREAD

**Issue by DUOLabs333** [r-spatial/sf#2272]
I'm trying to find the polygons in a sfc set B that intersects with another sfc set A. I first use  `st_intersects` to filter out non-intersecting polygons. This gives me a sparse matrix. I know that A does not intersect with any of the polygons in B. I try to access `intersects[[1]]`, expecting to get an empty list --- however, I get `integer(0)`. Why?

**Comment by edzer** [comment]
Because it is a length zero integer vector, indicating there are no intersecting geometries.

**Comment by DUOLabs333** [comment]
That is what I assumed, but when I try to access `intersects[[1]]` of an A that does have an intersection, I only get one number (presumably the first), not the list of numbers.

**Comment by DUOLabs333** [comment]
Never mind --- the issue I was facing was due to something else completely.
