### ISSUE TITLE
Improve CRS consistency when saving/loading data

### ISSUE THREAD

**Issue by latot** [r-spatial/sf#2274]
Hi, actually when we create manually a sf object, we save it and load it again, they end with different strings for CRS.... well is the same CRS but as objects are differents.

```R
a <- sf::st_sf(sf::st_sfc(crs = 4326))
sf::st_write(a, "test.gpkg")
b <- sf::st_read("test.gpkg")
#I'll only show the section that differs between them
sf::st_crs(a)
Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
sf::st_crs(b)
Coordinate Reference System:
  User input: WGS 84 
  wkt:
```

Oks, in theory they have the same CRS, but if we ask R if both CRS are the same the answer is no, I confirm this using testthat.

Is not ideal to compare only the CRS numbers, not all WKT2 has a number, and is a lot more complex to handle, be able to compare this CRSs would be pretty nice.

I think would be great to have the same output on both of them, ideally with the official GDAL one, if that strings comes from SF, a way to both be the same.

4326 is just an example, the idea is that the crs (R object) from the sf object that we save, be the same one to the one we load.

Thx!

<details>
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Gentoo Linux

Matrix products: default
BLAS:   /usr/lib64/libblas.so.3.11.0 
LAPACK: /usr/lib64/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=es_CL.utf8       LC_NUMERIC=C             
 [3] LC_TIME=es_CL.utf8        LC_COLLATE=es_CL.utf8    
 [5] LC_MONETARY=es_CL.utf8    LC_MESSAGES=es_CL.utf8   
 [7] LC_PAPER=es_CL.utf8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=es_CL.utf8 LC_IDENTIFICATION=C      

time zone: Chile/Continental
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] wrapr_2.1.0

loaded via a namespace (and not attached):
 [1] crayon_1.5.2       vctrs_0.6.4        sfnetworks_0.6.3   cli_3.6.1         
 [5] rlang_1.1.2        DBI_1.1.3          KernSmooth_2.23-22 purrr_1.0.2       
 [9] generics_0.1.3     sf_1.0-14          glue_1.6.2         colorspace_2.1-0  
[13] lwgeom_0.2-13      e1071_1.7-13       scales_1.2.1       fansi_1.0.5       
[17] grid_4.3.2         sfheaders_0.4.3    munsell_0.5.0      classInt_0.4-10   
[21] tibble_3.2.1       lifecycle_1.0.4    compiler_4.3.2     dplyr_1.1.4       
[25] igraph_1.5.1       Rcpp_1.0.11        pkgconfig_2.0.3    tidyr_1.3.0       
[29] R6_2.5.1           class_7.3-22       tidyselect_1.2.0   utf8_1.2.4        
[33] pillar_1.9.0       magrittr_2.0.3     tidygraph_1.2.3    gtable_0.3.4      
[37] tools_4.3.2        proxy_0.4-27       ggplot2_3.4.4      units_0.8-4
</details>

**Comment by edzer** [comment]
Please use `==` for this purpose:
```r
> st_crs(a) == st_crs(b)
[1] TRUE
```

**Comment by latot** [comment]
Hi, to run tests we compare full sf objects, from ```testthat``` perspective are not the same:

```R
Expected `check_sf(table_name, table)` to run without any errors.
i Actually got a <expectation_failure> with text:
  `values` (`actual`) not equal to `ret` (`expected`).
  
  `attr(actual$geom, 'crs')$input`:   "EPSG:4326"
  `attr(expected$geom, 'crs')$input`: "WGS 84"
```

The second one, is what we have from loading the same data.

**Comment by edzer** [comment]
You should test something like `expect(isTRUE(st_crs(a) == st_crs(b)))` because that checks whether the two CRS have the same meaning. Testing identity of representions is meaningless.

**Comment by latot** [comment]
that would be, if we "only" want to compare CRS, which is not the origin point, the hard part is that same sf object has two ways to represent the same, when that happens be able to create tests for R is more troublesome.

The point if have consistency here is be able to run ```expect_equal``` from ```testthat```.

Thx!

**Comment by rsbivand** [comment]
Exactly, use the appropriate underlying method, not the too "tidy" `testthat` which wants string equality of a representation of the object. In addition, as PROJ and EPSG progress, the string values will and should change, but PROJ will identify equivalent crs. This is taken into account by the boolean operations on `"crs"` objects, but not by naive `expect_equal` of a string rendering of the WKT2_2019. The user input is largely irrelevat and only reports the initial user input, which will change in part arbitratily.

**Comment by latot** [comment]
mm, which would be the right way?

until now there is...

- CRSs with different representation
- CRS with different names and same system

Only there we could be there several ways to compare them, including how to compare geometry columns if we want them to be specific or not.....

So maybe, what rn would be good is a function to compare sf objects. or already exists one for that?

**Comment by rsbivand** [comment]
Why do you need to do so? GDAL and PROJ are dynamic, `sf` also changes, so you need to specify your needs. If you need immutable objects, you must freeze all those, and probably the R version and string encoding too. Most of the round-tripping tests are done in the package anyway, and in GDAL driver unit tests and PROJ tests, so why try to bind upstream software?

**Comment by latot** [comment]
well, the point is not to be inmutable, I think there would be two points here, one is that the data saved to the data we have should be consistent, keep the system and geometries and data. The second one would be, we need a way to compare data, even if GDAL and PROJ changes, we should be able to know if two set of data are equals.

If you ask me what I need, would be both, I verify results of models on saved data, so I need to know they are equal, at the same time there must be able to reproduce that to construct a test.

What would be the best way to write tests for SF in this cases?

**Comment by rsbivand** [comment]
No, the question is why, given that you are using upstream software that already tests round-tripping, you want to duplicate those tests rather than reading their NEWS files to pick up desirable changes in representation?

**Comment by latot** [comment]
Hi, without trying to go offtopic, when we have data, we save it and read it again, I think is reasonable to expect get exactly the same data, which is not this case.

The representation changes, but why? if in first place there is only one way to do it, why not choose that one?

From here, appears some questions about what we want to compare, but I think is reasonable want to have back the data we saved.

**Comment by edzer** [comment]
> but I think is reasonable want to have back the data we saved.

Instead of demanding us to explain this to you, please take some time and try to understand the software ecosystem that `sf` interfaces, as well as its history.

**Comment by latot** [comment]
hi, I have been doing it, sorry if is too annoying, the world is too big, but I'll continue learning, thx :)

**Comment by rsbivand** [comment]
The obvious solution is `saveRDS` `readRDS` to address your unwillingness to follow the flow of objects through external software, keeping the object as-is. If you write and read using GDAL drivers, some object components may change because the object is on write and read subject to driver choice and external software version.
