### ISSUE TITLE
st_sf found row names when they does not exists

### ISSUE THREAD

**Issue by latot** [r-spatial/sf#2282]
Hi again!

Here a reprex:

```R
ret <- sf::st_sf(
  "to" = 1:2,
  "geom" = sf::st_sfc(sf::st_linestring())
)
Warning message:
In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded
```

The weird part with this, is that no data in the columns has names, so it should not trigger this warning.

Thx!

**Comment by edzer** [comment]
You're relying on `sf` to recycle `geom`, hence the warning later on. If you provide a `geom` with proper length the warning goes away.
