### ISSUE TITLE
sf no longer supports some multisurface geometries

### ISSUE THREAD

**Issue by user3386170** [r-spatial/sf#2289]
**Describe the bug**
I am working with an (admittedly wacky) spatial file. Most of the features are multi-polygons however some of them are multi-surface. I had been loading the file into R using sf and then converting the multi-surface into multi-polygon. I was able to load the file using sf when I last worked on the project in May this year (didn't write down the sf version previously) but now it fails with sf 1.0-14. I can load the features (which is better than terra for this file) and get the bounding box but many other simple manipulations fail such as casting to multipolygon, cropping or plotting.

 
**To Reproduce**
```

ex.wkt<-"MULTISURFACE (CURVEPOLYGON (COMPOUNDCURVE (LINESTRING (2367228 7598131, 2367255 7598125, 2367249 7598098, 2367249 7598098, 2367249 7598098, 2367245 7598070, 2367240 7598052, 2367240 7598051, 
2367240 7598051, 2367238 7598037, 2367229 7598024, 2367219 7598013, 2367193 7598001, 2367193 7598001, 2367193 7598001, 2367173 7597988, 2367172 7597988, 2367172 7597988, 2367159 7597973,
2367158 7597973, 2367158 7597973, 2367141 7597946), CIRCULARSTRING (2367141 7597946, 2367140 7597945, 2367140 7597944),
LINESTRING (2367140 7597944, 2367136 7597928, 2367132 7597932, 2367119 7597949, 2367140 7597985, 2367227 7598131, 2367228 7598131))))"


ex.wkt2<-"MULTISURFACE (CURVEPOLYGON (COMPOUNDCURVE (LINESTRING (2367363 7598100, 2367341 7598073, 2367323 7598045, 2367308 7598018, 2367281 7597986, 2367237 7597919, 2367233 7597914, 2367225 7597911, 
2367208 7597917, 2367201 7597909, 2367195 7597904, 2367196 7597907, 2367195 7597911, 2367188 7597915, 2367178 7597915, 2367161 7597918, 2367156 7597912, 2367155 7597911, 2367150 7597914, 2367145 7597919,
2367146 7597925, 2367150 7597941, 2367166 7597967, 2367179 7597980, 2367198 7597993, 2367224 7598004),
CIRCULARSTRING (2367224 7598004, 2367225 7598005, 2367225 7598006),
LINESTRING (2367225 7598006, 2367236 7598017, 2367236 7598017, 2367237 7598018, 2367247 7598033),
CIRCULARSTRING (2367247 7598033, 2367247 7598034, 2367247 7598035),
LINESTRING (2367247 7598035, 2367249 7598049, 2367255 7598068, 2367255 7598069, 2367255 7598069, 2367259 7598096, 2367265 7598122, 2367363 7598100))))"

d<-data.frame(a=c(1,2), geometry=rbind(ex.wkt, ex.wkt2))
d.sf<-st_as_sf(d, wkt="geometry")
st_crs(d.sf)<-2953

d.sf.mp<-st_cast(d.sf, "MULTIPOLYGON")
#Error in scan(text = lst[[length(lst)]], quiet = TRUE) : 
#  scan() expected 'a real', got 'ParseException:'
#Error in (function (msg)  : ParseException: Unknown WKB type 12

plot(d.sf)
#Error in xy.coords(x, y, xlabel, ylabel, log) : 
#  'x' is a list, but does not have components 'x' and 'y'

```

<details>
Paste the output of your `sessionInfo()` and `sf::sf_extSoftVersion()`

 sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8    LC_MONETARY=English_Canada.utf8
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.utf8    

time zone: America/Toronto
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mapview_2.11.2    sf_1.0-14         terra_1.7-55      Hmisc_5.1-1       stringi_1.8.2    
 [6] rcompanion_2.4.34 emmeans_1.8.9     ARTool_0.11.1     vegan_2.6-4       lattice_0.21-9   
[11] permute_0.9-7     dplyr_1.1.4       data.table_1.14.8 readxl_1.4.3     

sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
      "3.11.2"        "3.7.2"        "9.3.0"         "true"         "true"        "9.3.0" 
</details>

**Comment by edzer** [comment]
Did you check #2257 and #2231?

**Comment by user3386170** [comment]
Sorry, I had not seen those issues. This is indeed identical to those. Your reaction "geometry from hell" is quite apt. I don't know how anyone would have constructed such an odd feature -- which is unfortunately about 10% of the government dataset that I am using so I can't just ignore them. I'll try to tweak the `gsub` solution to see if I can make it work. I am still puzzled about why it worked before and it doesn't now. I'll also try to download the previous version in `sf` could handle the odd geometries (which I will immediately cast to something more reasonable!).

**Comment by edzer** [comment]
> I don't know how anyone would have constructed such an odd feature

Could you reveal which software is behind this?

**Comment by user3386170** [comment]
Likely ESRI/ArcGIS : https://www2.gnb.ca/content/gnb/en/departments/erd/open-data/forestry.html#9 ; 
To be fair though, the current download provides nice normal MULTIPOLYGONs (almost, the order of the vertices is still wacky). It may have been some of the manipulation steps on our end, which were probably done in ArcGIS/ESRI before I was involved in the project.

**Comment by user3386170** [comment]
I reworked the solution from https://github.com/r-spatial/sf/issues/2257 and came up with this which works in most cases but not all:
surf2poli <- \(y){
    d.txt <- y |> 
      st_geometry() |> 
      st_as_text() |> 
      gsub(pattern="[[:alpha:]]", replacement='\\1')|> #remove all letters
      gsub(pattern="[(]", replacement='\\1')|> #remove all open parentheses
      gsub(pattern="[)]", replacement='\\1') #remove all closed parentheses
    #print(d.txt)
    paste0('MULTIPOLYGON (((', d.txt, ')))') |> 
      as.data.frame() |> 
      setNames('geometry') |> 
      st_as_sf(wkt = "geometry", crs = 2953) |> #set crs to original file projection
      st_as_sfc()
  }

**Comment by mikoontz-vp** [comment]
For posterity, I did some additional reworking of this function to get it to work for all of my use cases...

```
surf2poly = function(obj) {
  
  out_geom_txt = obj |> 
    sf::st_geometry() |> 
    sf::st_as_text() |> 
    gsub(pattern = "MULTISURFACE (", replacement = '', fixed = TRUE) |> 
    gsub(pattern = "COMPOUNDCURVE (", replacement = '', fixed = TRUE) |> 
    gsub(pattern = "CURVEPOLYGON (", replacement = '', fixed = TRUE)
  
  out = obj |> 
    sf::st_set_geometry(
      value = sf::st_as_sfc(
        out_geom_txt, 
        crs = sf::st_crs(obj)
      )
    )
  
  idx = which(sf::st_geometry_type(out) == "LINESTRING")
  
  out_greenlight = out[-idx, ]
  out_redlight = out |> 
    dplyr::slice(idx) |> 
    sf::st_cast(to = "POLYGON") |> 
    sf::st_cast(to = "MULTIPOLYGON")
  
  out = rbind(out_greenlight, out_redlight) |> 
    sf::st_cast("MULTIPOLYGON") |> 
    sf::st_make_valid()
  
  return(out)
  
}
```

**Comment by user3386170** [comment]
`Fixed=TRUE `-- how simple! I spent several hours trying to figure out how to add in the "(" to the code. I finally set on removing all alphabetic characters and then removing the parentheses separately.
 My file also had "CIRCULARSTRING" as a geometry here it is to add to your code. Plus perhaps also the LINESTRING?
```
 gsub(pattern="CIRCULARSTRING (", replacement='', fixed=T)|>
 gsub(pattern="LINESTRING (", replacement='', fixed=T)|> 

```
In the end, I managed to fix my geometries by applying multiple steps:
1. Convert to POLYGON in QGIS -- within QGIS, the wkt shows up as MULTIPOLYGON but once in R it reverts back to MULTISURFACE
2. Split into SINGLEPARTS in QGIS
3. Fix geometries (because of course there are errors with self-intersection that appear)
4. Run `gdalUtilities::ogr2ogr`
```

gdalUtilities::ogr2ogr(src_datasource_name='source.gpkg', layer='south', dst_datasource_name='output.gpkg',
preserve_fid=F, skipfailures=T, explodecollections = T, nlt = 'CONVERT_TO_LINEAR')
```

**Comment by mikoontz-vp** [comment]
Hah! If I can avoid real regex and just shortcut to `fixed = TRUE` then I'm definitely going that route. 

In my case the `LINESTRING` was the deeply embedded geometry type that I wanted to keep. Directly swapping in `MULTIPOLYGON` didn't actually work and I had to first find the `LINESTRING` then do a couple of `sf::st_cast()` calls to get the geometry to be a `MULTIPOLYGON`. Adding a check for `CIRCULARSTRING` is a good idea too, along with any other problematic/unsupported WKB types.

**Comment by gregor-fausto** [comment]
@mikoontz-vp Would you be able to describe what the function in https://github.com/r-spatial/sf/issues/2289#issuecomment-1854502398 is doing? I'm encountering `MULTISURFACE` features and this helps create valid geometries. But I'd like to make sure I understand why.

**Comment by mikoontz-vp** [comment]
Hi @gregor-fausto -- the function grabs the text representation of the geometry, removes the pieces that declare a particular component of that geometry to be a "MULTISURFACE", "COMPOUNDCURVE", and "CURVEPOLYGON" but leaves behind all of the x/y positions of the nodes and any other geometry designations (e.g., "MULTIPOLYGON", "LINESTRING", "POLYGON"). We remove those pieces by looking for that text within the text representation of the geometry, then using the `gsub()` function to replace that text with nothing (i.e., `""`).

Next, it sets the geometry of the input object to be this newly modified text representation of the geometry.

Next, it gets the row number for all of the geometries of type "LINESTRING".

The function calls every row that isn't of geometry type "LINESTRING" good to go (creating the `out_greenlight` object with all of those rows).

For the rows that are of geometry type "LINESTRING", we cast them to a "POLYGON" then to a "MULTIPOLYGON", calling it `out_redlight`.

We `rbind()` the `out_greenlight` and `out_redlight` objects, then we cast everything to MULTIPOLYGON and make those geometries valid using `sf::st_make_valid()`.

I'm sure there are likely to be some accuracy losses if the geometries were really supposed to be "MULTISURFACE" but I can live with that. As @user3386170 noted, it might also be worth removing the "CIRCULARSTRING" geometry type in addition to "MULTISURFACE", "COMPOUNDCURVE", and "CURVEPOLYGON".

**Comment by ratnanil** [comment]
I was going through a vicious cycle of trying to import "geometries from ESRI's hell" with no success with any of the functions  provided above (or in the linked issues). I was quite surprised to find that the following `ogr2ogr` command works like a charm:

```bash
ogr2ogr -f GPKG Output.gpkg -nln Output_layer -nlt CONVERT_TO_LINEAR -nlt PROMOTE_TO_MULTI Input.gdb Input_layer
```
