### ISSUE TITLE
installation failed with error

### ISSUE THREAD

**Issue by HCharlie** [r-spatial/sf#2290]
**Describe the bug**
I am trying to install sf via `install.packages("sf")`, but encountered an error like this.
```
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: GDALAllRegister not found in libgdal.
ERROR: configuration failed for package ‘sf’
* removing ‘/usr/local/lib/R/site-library/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpi9MhDL/downloaded_packages’
```

**To Reproduce**
ubuntu 20.04
R version 4.2.3
install gdal via apt
```
sudo apt update
sudo apt-get install gdal-bin
sudo apt-get install libgdal-dev
```
run `install.packages("sf")` to get the error

**Comment by rsbivand** [comment]
Are proj and geos also installed, devel versions? Do you have multiple versions of any of these installed? See https://github.com/r-spatial/sf/#ubuntu.

**Comment by HCharlie** [comment]
thanks for the fast reply, I thought the error message was only related to the gdal part, 
geos is installed with conda and its version is 3.12 
proj4 isinstalled with conda and its version is 6.1.1
I will give it a try to check if there are multiples of them are installed

**Comment by rsbivand** [comment]
Please note that there is no support offered for conda installs of anything. Please follow the package install instructions, after removing any conda installs. Builds of external software should be those suggested or source installs.

**Comment by edzer** [comment]
Please reply here in case you resolved the conda issue, but until then ask your question to the conda developers.
