### ISSUE TITLE
Create df with sfc changes column name

### ISSUE THREAD

**Issue by latot** [r-spatial/sf#2297]
Hi, I was playing and found this, if we create a dataframe with sfc objects, it ends changing the column name:

```R
data.frame(a = sf::st_sfc())
[1] geometry
<0 rows> (or 0-length row.names)
```

For multiple columns:
```R
data.frame(a = sf::st_sfc(), b = sf::st_sfc())
[1] geometry   geometry.1
<0 rows> (or 0-length row.names)
```

No idea if this is R or something in SF who causes this.

Thx!

**Comment by edzer** [comment]
Weird! `st_sf` and `tibble::tibble()` do not do that. `data.frame` is not a generic, so where does this happen?

**Comment by edzer** [comment]
I believe this is a limitation of `data.frame`; by providing an `as.data.frame` method for `sfc` objects the construct works, but the argument name (`a`) is lost:
```r
> data.frame(a = list(3:4))
  X3.4
1    3
2    4
> data.frame(a = setNames(list(3:4), "b"))
  b
1 3
2 4
```

**Comment by latot** [comment]
ufff, this is too ugly, ```data.frame``` is most common way to construct dataframes, also with ```setNames``` the ```sfc``` lost the name:

```R
data.frame(
    id = c(4, 5, 6),
    setNames(sf::st_sfc(
      sf::st_linestring(c(sf::st_point(c(1, 10)), sf::st_point(c(2, 10)))),
      sf::st_linestring(c(sf::st_point(c(3, 10)), sf::st_point(c(4, 10)))),
      sf::st_linestring(c(sf::st_point(c(5, 10)), sf::st_point(c(6, 10))))
    ), "geom")
)
  id                geometry
1  4 LINESTRING (1 10, 2 10)
2  5 LINESTRING (3 10, 4 10)
3  6 LINESTRING (5 10, 6 10)
```

I'm still curious about this, because use ```geometry``` as a name means it must be recover that name from some place.

To me seems more like a bug than a limitation, if is not support should throw an error, not return weird things.

Thx checking it!

**Comment by edzer** [comment]
I guess that is one of the reasons the `tibble` was invented. `data.frame()` is a function, not a method, we cannot change it. We can hack `sf` such that your example with `setNames` works, but setting names on `sfc` elements is against the rest of the framework and API of `sf` (in addition to being very ugly). Use `st_sf` or `st_as_sf` to control your geometry column name, then convert to `data.frame` if you need that.

**Comment by latot** [comment]
I'm actually doing that, the reason why I use ```data.frame``` is because ```purrr::map_dfr``` does not works well with ```sf``` objects, so need to be converted to ```dataframe```, and after run it convert back to ```sf```.

No idea if ```purrr::map_dfr``` should works with ```sf``` objects, if is a bug or possible feature that can be added.

**Comment by rsbivand** [comment]
Doesn't `?purrr::map_dfr` say: *[Superseded]*  from 1.0.0 ?

**Comment by latot** [comment]
Yeah, in the it says it, I have not read it in some months, because I already know how they works, didn't notice it.

I think would be good have a warning on them.

I'll replace them! Thx!
