### ISSUE TITLE
sf new version broke my code

### ISSUE THREAD

**Issue by andrestyle16** [r-spatial/sf#2298]
This code worked well with sf and then I updated sf to the last version and now it's broken:

**Code:**

p <- read_xlsx(here("output/excel/tabla_maestra.xlsx")) %>% 
  st_as_sf(crs = 4326,
           coords = c("lon", "lat")) %>% 
  st_transform(crs = 32719)

**Error:**

Error in st_transform.sfc(st_geometry(x), crs, ...) : 
  cannot transform sfc object with missing crs

When I applied this line :   st_as_sf(crs = 4326,
           coords = c("lon", "lat"))

The CRS is empty

**Comment by andrestyle16** [comment]
Thanks for the answer. Here's the Excel file: 
[points.xlsx](https://github.com/r-spatial/sf/files/13716952/points.xlsx)

**Comment by andrestyle16** [comment]
I doesn't work for me, when I load sf I have this message:

Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE

And when I run the code I have this warning:

Warning message:
In CPL_crs_from_input(x) :
  GDAL Error 1: PROJ: proj_create_from_database: C:\Program Files\PostgreSQL\14\share\contrib\postgis-3.3\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. It comes from another PROJ installation.

**Comment by edzer** [comment]
Is the environment variable `PROJ_LIB` set? Have you tried reinstalling `sf`?

**Comment by andrestyle16** [comment]
Yes, but I didn't work. I had to install the previous version of sf (1.0-14) and now it works. Thanks Edzer!

**Comment by rsbivand** [comment]
@andrestyle16 This is not helpful. We need the complete output of `sessionInfo`, because you have either loaded some other package in your R session after loading `sf` setting `PROJ_LIB` to the PostGIS one, or some other process on your platform outside R has reset it after `sf` was loaded. `proj.db` is also bundled with `sf` with its version matching that of the PROJ external library used to build `sf`. 

Probably PostGIS was present but the version mismatch was not detected before, or its version agrees with that shipped with `sf` 1.0-14. You should always use the latest release of packages, and actually assist in debugging the problem. 

The fact that there is now no error does not mean that there was no error before, only that any error was not detected. Generally, the error is having an environment variable pointing at the wrong version of `proj.db`.

**Comment by kadyb** [comment]
Similar issue was just reported in [terra](https://github.com/r-spatial/sf/issues/2298).

**Comment by rsbivand** [comment]
In `terra` here: https://github.com/rspatial/terra/blob/e07ff997604a4781bf6eea918f99648bd03af386/src/RcppFunctions.cpp#L373-L376

**Comment by edzer** [comment]
> Yes, but I didn't work.

@andrestyle16 did you check whether the environment variable `PROJ_LIB` is set to the postgis install?

**Comment by andrestyle16** [comment]
This is what I have:

`Sys.getenv("PROJ_LIB")`

"C:\\Program Files\\PostgreSQL\\14\\share\\contrib\\postgis-3.3\\proj"

**Comment by rsbivand** [comment]
Please list the order in which packages are loaded in your session starting from an empty session and no .Rprofile etc. Can you start R as `R --vanilla` in a terminal console, and load packages in sequence, checking `PROJ_LIB` as you go?

**Comment by andrestyle16** [comment]
```
library(readxl)
Sys.getenv("PROJ_LIB")
```

[1] "C:\\Program Files\\PostgreSQL\\14\\share\\contrib\\postgis-3.3\\proj"

`library(sf)`

Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE

`Sys.getenv("PROJ_LIB")`

[1] "C:\\Program Files\\PostgreSQL\\14\\share\\contrib\\postgis-3.3\\proj"

`library(tidyverse)`

── Attaching core tidyverse packages ────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ──────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package to force all conflicts to become errors

`Sys.getenv("PROJ_LIB")`

[1] "C:\\Program Files\\PostgreSQL\\14\\share\\contrib\\postgis-3.3\\proj"

```
p <- read_xlsx("points.xlsx") %>%
   st_as_sf(crs = 4326,
                coords = c("lon", "lat"))
```

Warning message:
In CPL_crs_from_input(x) :
  GDAL Error 1: PROJ: proj_create_from_database: C:\Program Files\PostgreSQL\14\share\contrib\postgis-3.3\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. It comes from another PROJ installation.

`Sys.getenv("PROJ_LIB")`

[1] "C:\\Program Files\\PostgreSQL\\14\\share\\contrib\\postgis-3.3\\proj"

**Comment by edzer** [comment]
Thanks; could you please give the output generated by each of the following commands?
```r
library(sf)
system.file("proj/nad.lst", package = "sf")
(prj = system.file("proj", package = "sf")[1])
sf:::CPL_set_data_dir(prj)
get(".sf.PROJ_LIB", envir = sf:::.sf_cache)
```

**Comment by andrestyle16** [comment]
`library(sf)`

Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE

`system.file("proj/nad.lst", package = "sf")`

[1] "C:/Users/ase-1/AppData/Local/R/win-library/4.3/sf/proj/nad.lst"

`(prj = system.file("proj", package = "sf")[1])`

[1] "C:/Users/ase-1/AppData/Local/R/win-library/4.3/sf/proj"

`sf:::CPL_set_data_dir(prj)`

[1] TRUE

`get(".sf.PROJ_LIB", envir = sf:::.sf_cache)`

Error in get(".sf.PROJ_LIB", envir = sf:::.sf_cache) : 
  objeto '.sf.PROJ_LIB' no encontrado

**Comment by edzer** [comment]
Could you check whether after running
```r
prj = system.file("proj", package = "sf")[1]
Sys.setenv("PROJ_LIB" = prj)
```
your example above runs without error?

**Comment by andrestyle16** [comment]
```
prj = system.file("proj", package = "sf")[1]

Sys.setenv("PROJ_LIB" = prj)

get(".sf.PROJ_LIB", envir = sf:::.sf_cache)

```
Error in get(".sf.PROJ_LIB", envir = sf:::.sf_cache) : 
  objeto '.sf.PROJ_LIB' no encontrado

**Comment by edzer** [comment]
I meant running your example
```r
library(readxl)
library(sf)
p <- read_xlsx("points.xlsx") %>%
st_as_sf(crs = 4326,
coords = c("lon", "lat")) %>%
st_transform(crs = 32719)
```

**Comment by andrestyle16** [comment]
Now it works:

```
prj = system.file("proj", package = "sf")[1]

Sys.setenv("PROJ_LIB" = prj)

library(readxl)

library(sf)

p <- read_xlsx("points.xlsx") %>%
  st_as_sf(crs = 4326,
           coords = c("lon", "lat")) %>%
  st_transform(crs = 32719)
```

Simple feature collection with 20 features and 1 field
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 254160.8 ymin: 4899791 xmax: 309504.1 ymax: 5100888
Projected CRS: WGS 84 / UTM zone 19S
# A tibble: 20 × 2
      id           geometry
 * <dbl>        <POINT [m]>
 1   121 (299878.5 4997217)
 2   156 (279212.9 4984702)
 3    33 (267863.7 5100888)
 4   166 (272623.7 4913549)
 5    95 (265858.2 4965667)
 6    82 (254160.8 4923782)
 7   122 (309504.1 4991130)
 8   170 (276031.8 4974039)
 9    28 (276939.3 4903508)
10   152   (265517 4940782)
11    70 (277782.1 4993970)
12   103   (269972 4899791)
13   119 (296063.4 4995179)
14   169 (275284.8 4919427)
15    67 (275693.5 5008928)
16   154 (277975.3 4946070)
17     9 (265297.8 4940787)
18   149 (277058.1 4986397)
19     6 (300895.2 4970490)
20   172 (288292.9 4989838)

**Comment by edzer** [comment]
https://proj.org/en/9.3/usage/environmentvars.html
https://github.com/OSGeo/PROJ/issues/1493
https://proj.org/en/9.3/development/reference/functions.html#c.proj_context_set_search_paths

* apparently, we should look for `PROJ_DATA` rather than `PROJ_LIB`
* apparently, `PROJ_LIB` is still obeyed
* apparently, `proj_context_set_search_paths()` does not override `PROJ_LIB` setting
* maybe we should unset `PROJ_LIB` regardless of setting `proj_context_set_search_paths()`?
* What if a user wants to set her own `PROJ_LIB` or `PROJ_DATA` with R/sf?

**Comment by rsbivand** [comment]
In the case of @andrestyle16 `PROJ_LIB` is being set prior to `sf` being loaded, most likely outside R, by PostGIS. So the higher level applications are interfering with each other, PostGIS as installed interfering with `terra` and `sf` by setting `PROJ_LIB`, and `sf` with PostGIS if `PROJ_LIB` is unset and not restored on exit. I recall Even suggesting that the only secure way to handle things was to use a dedicated context, which other applications couldn't enter, but that wasn't tested and would have to be the same PROJ context that GDAL uses. Maybe unset `PROJ_LIB` and `PROJ_DATA` if they are set when `sf` is loaded, within the scope of the R process? This would need checking across platforms. Then `CPL_set_data_dir(prj)` should work for the R session, and the environment variables should still be available in other processes (?).

**Comment by edzer** [comment]
@andrestyle16 does your example succeed after running
```r
Sys.setenv(PROJ_LIB = "")
```
?

**Comment by edzer** [comment]
Does this feel like a bug in PROJ?

**Comment by rsbivand** [comment]
Or a PostGIS bug, or a packager bug for PostGIS on Windows?

**Comment by andrestyle16** [comment]
@edzer When I run this it works: 

```
Sys.setenv(PROJ_LIB = "")

library(readxl)

library(sf)

p <- read_xlsx("points.xlsx") %>%
  st_as_sf(crs = 4326,
           coords = c("lon", "lat")) %>%
  st_transform(crs = 32719)
```

But if I run the first line after loading the libraries, it doesn't work

**Comment by edzer** [comment]
> Or a PostGIS bug ...

`proj_context_set_search_paths()` is supposed to override `PROJ_LIB` or `PROJ_DATA`, but it doesn't.

**Comment by edzer** [comment]
Should work now.

**Comment by edzer** [comment]
@andrestyle16 please confirm this now works, e.g. using
```r
install.packages('sf', repos = c('https://r-spatial.r-universe.dev'))
```

**Comment by andrestyle16** [comment]
Yes, it works
