### ISSUE TITLE
build failed both from cran and git

### ISSUE THREAD

**Issue by kemin711** [r-spatial/sf#2301]
**Describe the bug**
C++ compilation error

**To Reproduce**

install.packages("sf")
lsb_release -a
---------------------------
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

**If reporting a change from previous versions**

Please read https://cran.r-project.org/web/packages/sf/news/news.html first.

**Additional context**
error: ‘GEOSLineMergeDirected_r’ was not declared in this scope

<details>
geos.cpp: In function ‘void __countErrorHandler(const char*, void*)’:
geos.cpp:107:45: warning: unused parameter ‘fmt’ [-Wunused-parameter]
  107 | static void __countErrorHandler(const char *fmt, void *userdata) {
      |                                 ~~~~~~~~~~~~^~~
geos.cpp: In function ‘void __emptyNoticeHandler(const char*, void*)’:
geos.cpp:112:46: warning: unused parameter ‘fmt’ [-Wunused-parameter]
  112 | static void __emptyNoticeHandler(const char *fmt, void *userdata) { }
      |                                  ~~~~~~~~~~~~^~~
geos.cpp:112:57: warning: unused parameter ‘userdata’ [-Wunused-parameter]
  112 | static void __emptyNoticeHandler(const char *fmt, void *userdata) { }
      |                                                   ~~~~~~^~~~~~~~
geos.cpp: In function ‘Rcpp::List sfc_from_geometry(GEOSContextHandle_t, std::vector<std::unique_ptr<GEOSGeom_t, std::function<void(GEOSGeom_t*)> > >&, int, bool)’:
geos.cpp:225:108: warning: unused parameter ‘free’ [-Wunused-parameter]
  225 | Rcpp::List sfc_from_geometry(GEOSContextHandle_t hGEOSCtxt, std::vector<GeomPtr> & geom, int dim = 2, bool free = true) {
      |                                                                                                       ~~~~~^~~~~~~~~~~
geos.cpp: In function ‘Rcpp::List CPL_geos_op(std::string, Rcpp::List, Rcpp::NumericVector, Rcpp::IntegerVector, Rcpp::NumericVector, Rcpp::LogicalVector, int, Rcpp::IntegerVector, Rcpp::IntegerVector, Rcpp::NumericVector, Rcpp::LogicalVector)’:
geos.cpp:841:30: error: ‘GEOSLineMergeDirected_r’ was not declared in this scope; did you mean ‘GEOSLineMerge_r’?
  841 |    out[i] = geos_ptr(chkNULL(GEOSLineMergeDirected_r(hGEOSCtxt, g[i].get())), hGEOSCtxt);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~
      |                              GEOSLineMerge_r
make: *** [geos.o] Error 1
ERROR: compilation failed for package ‘sf’

</details>

**Comment by edzer** [comment]
Great, could you provide which version of GEOS this was (output of configure)?

**Comment by kemin711** [comment]
Just edited previous post with dependency.

**Comment by kemin711** [comment]
ERROR: loading failed
* removing ‘/global/software/sl-7.x86_64/modules/langs/r/4.3.2/lib64/R/library/sf’

The downloaded source packages are in
	‘/test/Rtmps8dwx8/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("sf") :
  installation of package ‘sf’ had non-zero exit status

---------------------

I think I made some progress.  compiler is good. Only loading issues now.  I am experimenting in my own home directory. Maybe installing the latest version of geo helped.

**Comment by kemin711** [comment]
Resolved the problem.  It was due to a simple linking issues. After installing the latest version of geos, for some reason, the lib was used, but actually geos used lib64. So this resulted in the failure for the linker to link to the geos so file. Either make a symlink ln -s lib64 lib in the geos lib dir or change update the LD_LIBRARY_PATH.  Now my linking problem got resolved.  Hope this round of exercise can help other people encountering similar error.
