### ISSUE TITLE
Cannot install sf package.

### ISSUE THREAD

**Issue by PowderL** [r-spatial/sf#2303]
**Describe the bug**
I try to install `sf` using install.packages("sf") and I got the following error:
```
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/ltao/R/x86_64-pc-linux-gnu-library/4.3/00LOCK-sf/00new/sf/libs/sf.so':
  libproj.so.19: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/ltao/R/x86_64-pc-linux-gnu-library/4.3/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpHsYoOT/downloaded_packages’
```
I follow the step to install `libproj`, `libgdal`, and `libgeos` use this command:
`sudo apt-get -y update && sudo apt-get install -y  libudunits2-dev libgdal-dev libgeos-dev libproj-dev`
and I tried to check if I have installed `libproj.so.19` successfully. I used `ldconfig -p | grep libproj` and I got:
```
libproj.so.22 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libproj.so.22
libproj.so.13 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libproj.so.13
libproj.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libproj.so
```
The newest version of `libproj `seems to be `libproj.so.22 ` instead of `libproj.so.19 `. I have used various methods to remove this issue, but they didn't work.
So, what should I do to exclude this issue? 
<details>
System: Ubuntu 20.04LST
R version: 4.3.2
</details>

**Comment by edzer** [comment]
This usually points to a situation where you have multiple versions of the same library installed at different places, see [here](https://github.com/r-spatial/sf?tab=readme-ov-file#multiple-gdal-geos-andor-proj-versions-on-your-system), where one is found at compile time but not at run time.

**Comment by PowderL** [comment]
Thanks for your reply. You are right. I work on a public HPC, and other users also have installed `libproj `for their use. But I have no right to uninstall the package installed by other users. So I tried to change my environment variables including `PATH `and `LD_LIBRARY_PATH` only to include my own packages. But it didn't work at all. How can I install the `sf` .

**Comment by edzer** [comment]
What you could try is from within R, retrieve `Sys.getenv("LD_LIBRARY_PATH")`, and then set it to the path you need with `Sys.setenv(LD_LIBRARY_PATH="/my/path")`, possibly keeping the path that R has set.

**Comment by PowderL** [comment]
Thanks. I installed `sf` successfully.

**Comment by edzer** [comment]
For future reference, could you share how you set `LD_LIBRARY_PATH` with `Sys.setenv()`?

**Comment by PowderL** [comment]
Of course!  I have tried to use Sys.setenv(LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu") to change the environment variable `LD_LIBRARY_PATH`, but I still failed to install `sf`.    I am not sure what's the reason for that.    I guess when installing R package the `LD_LIBRARY_PATH ` was ignored at first, while the `/usr/local/lib` was set a higher priority.    Whether `/usr/local/lib` was included in `LD_LIBRARY_PATH ` or not, the R would search for libraries in `/usr/local/lib` at first.  After manually removing the files related to `libproj` in `/usr/local`, I successfully installed `sf`.

**Comment by edzer** [comment]
Ah, so the solution was removing a duplicate library, not setting `LD_LIBRARY_PATH`. Indeed, setting `LD_LIBRARY_PATH` does not _remove_ paths set in `/etc/ld.so.conf` (or files referred to in that file), which typically include(s) `/usr/local/lib`.
