### ISSUE TITLE
Add gdalfootprint utility gdal_utils

### ISSUE THREAD

**Issue by goergen95** [r-spatial/sf#2304]
Hello,

Since recent `GDAL 3.8.0` there is a new [footprint](https://gdal.org/programs/gdal_footprint.html) utility I would really like to see supported by `sf::gdal_utils()`. 

I have a branch up and running with this [here](https://github.com/goergen95/sf/tree/gdalfootprint). It is basically just an adaptation of the `CPL_gdaltranslate` function but seems to work fine. 
I could open a PR if interested.

Best,
Darius.

**Comment by edzer** [comment]
Interested!
