### ISSUE TITLE
Using st_contains on two datasets to see if points in data1 lie inside data2

### ISSUE THREAD

**Issue by smk5g5** [r-spatial/sf#2306]
Hi,

I have 2 datasets. One is cell-level information i.e. cell types with x and y coordinates ( a single cell data transformed to spatial coordinates) that looks like this.

```
Simple feature collection with 6 features and 3 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 17137.98 ymin: 21040.92 xmax: 17158.71 ymax: 21060.83
CRS:           NA
                               coord_x  coord_y Celltypes_Aug3
Tumor_B185_AATCGGTTCCGAACGC.1 17144.23 21040.92 Tumor.Module_3
Tumor_B185_ACTGCTCAGTCACGCC.1 17152.49 21060.83 Tumor.Module_3
Tumor_B185_GCGCAACTCTCCCTGA.1 17137.98 21049.07 Tumor.Module_3
Tumor_B185_GTGTGCGAGTCCGTAT.1 17158.71 21050.25 Tumor.Module_3
Tumor_B185_GTTAAGCTCAGGCGAA.1 17142.84 21057.95 Tumor.Module_3
Tumor_B185_TGTGGTAGTCGGCACT.1 17148.71 21049.86 Tumor.Module_3
                                               geometry
Tumor_B185_AATCGGTTCCGAACGC.1 POINT (17144.23 21040.92)
Tumor_B185_ACTGCTCAGTCACGCC.1 POINT (17152.49 21060.83)
Tumor_B185_GCGCAACTCTCCCTGA.1 POINT (17137.98 21049.07)
Tumor_B185_GTGTGCGAGTCCGTAT.1 POINT (17158.71 21050.25)
Tumor_B185_GTTAAGCTCAGGCGAA.1 POINT (17142.84 21057.95)
Tumor_B185_TGTGGTAGTCGGCACT.1 POINT (17148.71 21049.86)
```

And another data which is spot level data (i.e. tissue spatial data) that looks as below.

```
Simple feature collection with 6 features and 5 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 14823 ymin: 6850 xmax: 19897 ymax: 24826
CRS:           NA
                   tissue row col imagerow imagecol            geometry
AAACAAGTATCTCCCA-1      1  50 102    17148    21052 POINT (17148 21052)
AAACACCAATAACTGC-1      1  59  19    19897     6850  POINT (19897 6850)
AAACCCGAACGAAATC-1      1  45 115    15647    23272 POINT (15647 23272)
AAACCGGAAATGTTAA-1      1  54 124    18322    24826 POINT (18322 24826)
AAACCGGGTAGGTACC-1      1  42  28    14823     8367  POINT (14823 8367)
AAACCGTTCGTCCAGG-1      1  52  42    17792    10779 POINT (17792 10779)
```
So data1 is cell level information i.e. 2d coordinates of the cells and data 2 is 2 d coordinates of the tissue regions.
I need to map which cells are in which spot regions. So far I have not had luck with sf. I tried the following.

Firstly I tried to just run

`mylst = st_contains(data2_sf,data1_sf)`

It gives me an empty list

Then I did this for each of the data (I used st_boundary with defaults)

```
data1_sf_polygon = st_boundary(data1_sf)
data2_sf_polygon = st_boundary(data2_sf)
mylst = st_contains(spot_polygon,celltrek_polygon)
```
Both approaches give me an empty list, which can not be true.

I was wondering what I might be doing wrong and what would be a correct way to do this.

More information on the data2 data is here 

https://www.10xgenomics.com/support/software/space-ranger

**Comment by rsbivand** [comment]
Both data sets are POINT geometries, where only co-incident points contain each other:

```
pt0 <- st_point(c(0,0))
pt1 = st_point(c(0,1))
pt2 = st_point(c(1,1))
sfc = st_sfc(pt0, pt1, pt2)
st_contains(sfc, sfc)
st_contains(sfc, sfc + c(0.25, 0.25))
```

`st_boundary` is inappropriate, but perhaps `st_convex_hull` or others:

```
st_contains(st_convex_hull(sfc), sfc)
```
Perhaps consider using `geos` rather than `sf` as you probably do not need anything other than access to the underlying GEOS library.

**Comment by smk5g5** [comment]
How do you suggest we should use geos to get points that lie inside other points?
Is there an example/code that you can point me to? Thank you!
