### ISSUE TITLE
Using bounding box for world data set with st_sample() overloads memory

### ISSUE THREAD

**Issue by tibbles-and-tribbles** [r-spatial/sf#2308]
When using `st_sample()` to generate 10 random points within the bounding box of `world` from `spData`, I'm getting the following error: `Error: vector memory exhausted (limit reached?)`

```
library(sf)
library(spData)

bb <- st_bbox(world)
box_sfc <- st_as_sfc(bb)

random_points_sfc <- st_sample(x = box_sfc, size = 10)
```

Output:
```
Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is
TRUE

Error: vector memory exhausted (limit reached?)
```

Note: passing `world` directly to `st_sample()` (i.e., skipping the bounding box step) works as expected.

**Comment by edzer** [comment]
Yes, that needs fixing. In the meantime, sampling from a global area can be done with
```r
library(stars) # for the default global st_bbox() method
st_bbox() |> st_sample(10)
```

**Comment by edzer** [comment]
You can now get this by
```r
random_points_sfc <- st_sample(x = box_sfc, size = 10, oriented = TRUE)
```
or by
```r
random_points_sfc <- st_sample(bb, size = 10)
```
That is somewhat annoying, but there are regrettably too many geometries out there for which we cannot simply assume that the orientation is correct (sf-complient, outer ring counter-clockwise).

**Comment by edzer** [comment]
This gives us
```r
library(sf)
# Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE
library(spData)

bb <- st_bbox(world)
box_sfc <- st_as_sfc(bb)

random_points_sfc <- st_sample(x = box_sfc, size = 10)
# Error: sampling box is 3.6e+07 times larger than sampling region;
# use force=TRUE if you really want this, or try setting oriented=TRUE
# (after reading the documentation)
# Execution halted
```
