### ISSUE TITLE
Totally lost when it cames to wkb

### ISSUE THREAD

**Issue by alexfabregat** [r-spatial/sf#2317]
Hi there.
Apologize in advance if this obvious.
I retrieved some data via duckdb. The geometry column looks like this
"b'\\x00\\x00\\x00\\x00\\x03\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x05?\\xf0\\x96\\x12%\\x9cq\\xbb@D\\x87\\xaf1\\xb1R\\xf4?\\xf0\\x96\\x83\\x9aS\\xd3\\xbd@D\\x87\\xa8t\\xfe\\xaf\\x9e?\\xf0\\x97yH\\xc19\\xf2@D\\x87\\xaa\\xc1\\tJ,?\\xf0\\x97\\x07\\xd4\\t\\xd7\\xf0@D\\x87\\xb1}\\xbb\\xed\\x81?\\xf0\\x96\\x12%\\x9cq\\xbb@D\\x87\\xaf1\\xb1R\\xf4'"
instead of the usual POLYGON followed by lon lat pairs.
I understand that this is raw content but I have no idea how to convert this into "regular" sf geometry.
Thanks.

**Comment by edzer** [comment]
Maybe read this? https://github.com/r-spatial/sf/issues/2265#issuecomment-1813520032

**Comment by alexfabregat** [comment]
So, I am getting the data using python and its library duckdb as follows:

import duckdb
db = duckdb.connect()
db.execute("INSTALL spatial")
db.execute("INSTALL httpfs")
db.execute("""
LOAD spatial;
LOAD httpfs;
SET s3_region='us-west-2';
""")

cursor = db.execute("""
select *
from read_parquet('/mnt/data/crap/type=building/*')
where
    bbox.minx > 1.036011
    AND bbox.maxx < 1.311012
    AND bbox.miny > 41.046682
    AND bbox.maxy < 41.183769
""")
rows = cursor.fetchall()
columns = [desc[0] for desc in cursor.description]
dicts = [dict(zip(columns, row)) for row in rows]

This should return a collection of polygons or multipolygons representing buildings.

The first element of this query looks like this:

{'id': '08b3946990959fff0200f5b6840bd2e9',
 'geometry': b"\x00\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\r?\xf0\x97\x840{\xc8\xce@D\x87\xa7\xa0\xc3Y\x87?\xf0\x96\xd2\xc54R\x17@D\x87\xa6\x08<\xe5d?\xf0\x97\x9a\xa1\x00\x96(@D\x87\x99\xb1\xedMv?\xf0\x97\xbe\xce\x06\x88\xb0@D\x87\x9a\x14\xe9\x9c\x10?\xf0\x98\xaa\xf1\xb0\xb1\xe4@D\x87\x9b\xdf\xc4\xf7\x15?\xf0\x98\xee(g'W@D\x87\x98\xfei'\x0b?\xf0\x995@S\xad&@D\x87\x99o\xa8.\x88?\xf0\x99^\x90\xaf\x0fM@D\x87\x96\xfe\xb4\xa6e?\xf0\x99\x8c\x99\x00\x16\xa6@D\x87\x96\xc9\x04\xc10?\xf0\x9aD\x194\x84l@D\x87\x98\xb2\x13\r#?\xf0\x99h6J>\xe8@D\x87\xa4\xac\x1cS\x1d?\xf0\x97\xeaR\x18\xd1\x88@D\x87\xa1Q\xf4\xbfZ?\xf0\x97\x840{\xc8\xce@D\x87\xa7\xa0\xc3Y\x87"}

which is what I obviously get in R after reading the csv from the list of dictionaries "dicts".

Any further help, either on the python side or R side, will be highly appreciated.

**Comment by edzer** [comment]
Note that you are raising an issue at an R package, but are using Python. The hint above I gave you was to use `ST_as_WKB()` on the geometry column, rather than `select *`, which you didn't. If you had done that, the output as Python binary would also not be of any help here, as we're looking at R. Maybe look for help elsewhere?
