### ISSUE TITLE
Request: more informative error message for "CRS" (vs "crs") argument typo

### ISSUE THREAD

**Issue by kaijagahm** [r-spatial/sf#2318]
This may be out of scope, but I figured I'd raise it. It took me 30 minutes to figure out that I had typed "CRS" instead of "crs" as an argument to `st_as_sf` today. 

Here's a reprex:
```
dat <- structure(list(location_lat = c(30.8162841796875, 30.8615703582764
), location_long = c(34.8229331970215, 34.8145484924316), tag_id = c(334771264, 
                                                                     334771264)), row.names = c(NA, -2L), class = c("tbl_df", "tbl", 
                                                                                                                    "data.frame"))
sf::st_as_sf(dat, coords = c("location_long", "location_lat"), CRS = "WGS84")
#> Error in st_sf(x, ..., agr = agr, sf_column_name = sf_column_name): no simple features geometry column present
```

The current error message is confusing and doesn't relate to what I had actually done wrong. Especially given the existence of the `CRS()` function, I suspect others might encounter this error, and it could be helpful to have an informative error message like "did you mean 'crs' instead of 'CRS'?" like some tidyverse packages throw.

Thanks for such an awesome package!

**Comment by edzer** [comment]
I can see that that is frustrating; the help of `st_as_sf()` points out that `...` is passed on to `st_sf()`, so that would be the place to look for arguments with names not in `?st_as_sf()`, which you should have seen when reading the docs of the function you used. I don't see an easy way to improve this without large refactoring.
