### ISSUE TITLE
Error in UseMethod("st_write") :    no applicable method for 'st_write' applied to an object of class "list"

### ISSUE THREAD

**Issue by KathanEcol1** [r-spatial/sf#2332]
st_write(spdf,dsn = "C:/Users/HP/Desktop/sr", layer = 'test', driver="ESRI Shapefile" )

Error in UseMethod("st_write") : 
  no applicable method for 'st_write' applied to an object of class "list"

**Comment by rsbivand** [comment]
What is `class(spdf)`?

**Comment by KathanEcol1** [comment]
List

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Nowosad** [comment]
@KathanEcol1 -- the first object in `st_write()` must be an `sf` object, not a list.

**Comment by KathanEcol1** [comment]
How to export shapefile from a list

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Nowosad** [comment]
Where does your list come from? How did you create it? 

(Here, you are trying to use the sf package, which creates, operates, and saves `sf` objects -- see, for example, https://r-spatial.github.io/sf/articles/sf2.html)

**Comment by KathanEcol1** [comment]
spdf <- fxi.contour(mod.0, i = 1:23, plt = FALSE, p = c(0.5,0.95),nx = 256, SPDF = TRUE, fitmode = TRUE)


Mod.0 is the top model from SECR analysis.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Nowosad** [comment]
Based on this function documentation, you need to use the `output = 'sf'` argument in the ` fxi.contour` function, before using `st_write()`.
