### ISSUE TITLE
sf::read_sf does not fetch INT column when it is primary key

### ISSUE THREAD

**Issue by fluegelrad** [r-spatial/sf#2336]
**Describe the bug**
See [StackOverflow thread](https://stackoverflow.com/q/77971063/15097106)

**Additional context**
_R.version_                        
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          3.1                              
year           2023                             
month          06                               
day            16                               
svn rev        84548                            
language       R                                
version.string R version 4.3.1 (2023-06-16 ucrt)
nickname       Beagle Scouts

_PSQL version_
PostgreSQL 13.13 (Ubuntu 13.13-1.pgdg20.04+1) 
on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit

**Comment by edzer** [comment]
I don't think that `sf` does anything specific in this regard; could you check with `ogr2ogr` whether the key field is read correctly, and written e.g. to a gpkg or csv?
