### ISSUE TITLE
st_wrap_dateline() not working as expected

### ISSUE THREAD

**Issue by thomasmestl** [r-spatial/sf#2340]
Hi
I know this topic was addressed before (https://github.com/r-spatial/sf/issues/1999) but it still does not work for me: 
Here a reproducable example:
```r
sf::sf_use_s2(FALSE)

txt <- "LINESTRING (154.2524 50.02265, 165.079 55.68001, -169.608 65.70425, -178.6191 69.20004, -180 69.51547, 179.2096 69.771, 174.7181 70.25778)"
line <- data.frame('i'=1,'wkt'=txt) %>% sf::st_as_sf(wkt='wkt') %>% sf::st_set_crs(4326) %>% sf::st_wrap_dateline(options = c("WRAPDATELINE=YES", "DATELINEOFFSET=180"))

plot(line)
```
![line](https://github.com/r-spatial/sf/assets/82365064/281a175a-2d1f-437a-a496-6ae5d23e35c0)

sf version: 1.0-15

Any suggestions????

wbr 
Thomas

**Comment by edzer** [comment]
With
```r
> library(sf)
Linking to GEOS 3.12.1, GDAL 3.8.3, PROJ 9.3.1; sf_use_s2() is TRUE
```
I get
![x](https://github.com/r-spatial/sf/assets/520851/4cbdd9a0-6ffa-4dd8-afd7-0c830673b205)

which seems the right thing.
