### ISSUE TITLE
Help with getting st_centroid() to work on invalid geometries that st_make_valid() does not fix.

### ISSUE THREAD

**Issue by Emilyaoc** [r-spatial/sf#2351]
I am trying to calculate centre of mass centroids for a large number (5749) of species distribution maps. The shapefiles are in standard spherical geometry units of latitude / longitude (WGS84 CRS). I used  st_read(dsn = x, check_ring_dir = TRUE) to read-in the files. When trying to calculate the centroids with st_centroid() I encounter errors relating to invalid geometries (loops not being valid due to e.g. duplicate vertices etc). I tried to fix the geometries using st_make_valid(), but 6 of the 5749 maps continue to have invalid geometries. The only way I can get st_centroid() to work for all the maps is to turn off s2 using sf_use_s2(FALSE). However, I now get the error that "st_centroid does not give correct centroids for longitude/latitude data". I think by turning off S2 I switch from spherical to planar, right? Does this now make the centroids incorrect? And if so, it would be great to have some guidance on how to get around this if possible? I previously used rgeos::gCentroid on a subset of this data with no obvious (to me!) problems and I see that the results from st_centroid (for the species maps it works for) produce similar, but not identical results. So I think I am a little confused about how turning off S2 affects the results and if this is a problem?
Thank you for any help!

**Comment by edzer** [comment]
> Does this now make the centroids incorrect?

Technically yes, but practically it may not matter. A polygon with a pole as its center like `POLYGON((0 80, 120 80, 240 80, 0 80))` will not return `POINT(0 90)` as its centroid; polygons covering the antimeridian will also go wrong. If your polygons are small and not too close to these problem areas, things may go pretty OK. The warning is there because the software does not decide for you what is "pretty OK" and what is not.

**Comment by Emilyaoc** [comment]
Ok, thank you. So, if I use st_centroid() on the polygons where I have been able to make the geometry valid (using st_make_valid()) and S2 is on, as is the default I think for sf when it reads in maps with latitude / longitude, will the centroids then be calculated using spherical geometry? So presumably more accurate globally? Should those results then be identical to the ones previously obtained from rgeos::gCentroid?

**Comment by edzer** [comment]
Have you considered comparing them?

**Comment by Emilyaoc** [comment]
They are also a little different to the results I obtained previously using rgeos::gCentroid. But not drastically so. Quite similarly different to when I checked to those calculated with s2 off on the unmodified polygons. I guess everything looks more or less similar..... but not identical. Do sf::st_centroid & rgeos::gCentroid calculate the same thing? 
Thank you for your help

**Comment by edzer** [comment]
> Do sf::st_centroid & rgeos::gCentroid calculate the same thing?

for geographic (unprojected) coordinates only if `sf_use_s2(FALSE)` has been set before.

**Comment by Emilyaoc** [comment]
Ok. Thank you for helping me understand.
