### ISSUE TITLE
documentation for asymptotic complexity of algorithms?

### ISSUE THREAD

**Issue by tdhock** [r-spatial/sf#2352]
Hi! I am trying to find the asymptotic complexity, big O notation for time and memory usage, for algorithms used in operations such as sf::st_simplify.
I read https://r-spatial.github.io/sf/articles/sf1.html and ?sf::st_simplify and ?s2::s2_simplify, but saw no mention of asymptotic complexity.
In particular I have a multipolygon, and I call st_simplify on it, and I would like to know if the algorithm used is linear in the number of polygons (in the input or output?), or linear in the total number of vertices in all the polygons (in the input or output?), or ...?
Similar to #1261 which discusses speed differences between R and python within ... are those differences constant or larger factors? (in big O notation)
Could some one please point me to the documentation or research paper where this information can be found?

**Comment by tdhock** [comment]
A concrete example would be: 
```r
m.triangle <- rbind(
  c(0,0),
  c(0,0.5),
  c(0,1),
  c(1,1),
  c(0,0)
)
m.rect <- rbind(
  c(0,0.4),
  c(0,2),
  c(-1,2),
  c(-1,0.4),
  c(0,0.4)
)
(two.polys <- sf::st_multipolygon(list(list(m.triangle), list(m.rect))))
(two.polys.joined <- sf::st_simplify(two.polys))
```
on my system I got the output
```r
> (two.polys <- sf::st_multipolygon(list(list(m.triangle), list(m.rect))))
MULTIPOLYGON (((0 0, 0 0.5, 0 1, 1 1, 0 0)), ((0 0.4, 0 2, -1 2, -1 0.4, 0 0.4)))
> (two.polys.joined <- sf::st_simplify(two.polys))
POLYGON ((0 0, 0 0.4, -1 0.4, -1 2, 0 2, 0 1, 1 1, 0 0))
```
above we had two polygons, but say we have P polygons each with N vertices, what is the big O amount of time/memory for this simplify operation?

**Comment by kadyb** [comment]
The `sf::st_simplify()` with GEOS engine uses Ramer–Douglas–Peucker algorithm so maybe [this](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm#Complexity) will be helpful.

BTW: If you plan to do some benchmarks, I recommend including [geos](https://github.com/paleolimbot/geos/) (fast interface to GEOS) and [rsgeo](https://github.com/JosiahParry/rsgeo) (interface to GeoRust).

**Comment by tdhock** [comment]
hi @edzer that is useful to know that the code in this repo is just an interface to the GEOS code, but I do not understand the significance of the geos_c.h.in file that you linked. Is there a way to determine the computational complexity by using the function names defined in that file?

hi @kadyb that is useful to know that st_simplify with GEOS engine uses Ramer–Douglas–Peucker algorithm. How did you know that? where is that documented? Please could a link be added to the sf documentation, to where this information can be found?
I would like to lookup similar information for the other functions I use: lwgeom::st_split, sf::st_intersects, etc.
I don't understand what you mean about benchmarks, can you please clarify?

**Comment by kadyb** [comment]
> How did you know that? where is that documented? Please could a link be added to the sf documentation, to where this information can be found? I would like to lookup similar information for the other functions I use: lwgeom::st_split, sf::st_intersects, etc.

This can be found in the [GEOS documentation](https://libgeos.org/doxygen/). I don't think there is such information in the `sf` documentation. Probably the best option is if you ask in the [GEOS repository](https://github.com/libgeos/geos).

> I don't understand what you mean about benchmarks, can you please clarify?

I know you asked about the theoretical complexity of the algorithms, but the spatial packages (`sf`*, `terra`, `geos`, `geopandas`) use the same backend, i.e. GEOS for calculations on the plane, but in practice they all offer different performance due to the data structures used. I did some benchmarks here:

- https://github.com/kadyb/vector-benchmark
- https://github.com/kadyb/OGH2022 (workshop)

_*`sf` also uses [S2 engine](http://s2geometry.io/)_

**Comment by tdhock** [comment]
thanks that is helpful!

**Comment by edzer** [comment]
> Is there a way to determine the computational complexity by using the function names defined in that file?

That's the point `sf` calls; you'd have look at which functions are called from there, and sort out their complexity.
