### ISSUE TITLE
st_write() issues a warning

### ISSUE THREAD

**Issue by maxbre** [r-spatial/sf#2368]
I'm chiming in as a follow-up of a closed issue:
https://github.com/r-spatial/sf/issues/1792

Here it is my reprex:

```
####### OK, this is fine!
st_sf(field_name=12345678, geom = st_sfc(st_point(0:1))) |>
  st_write("x.shp")

####### NOK, it issues a warning, because a too large number with respect to field width!
st_sf(field_name=123456789, geom = st_sfc(st_point(0:1))) |>
  st_write("x.shp", delete_layer = TRUE)

######## but by reading back the shapefile it seems perfectly fine, no truncation!
x <- st_read('x.shp')
```

Now, I'm wondering: what is the purpose of that warning? 
Is it "just a nice, gracefully warning", especially useful for those potential users of the shapefile dealing with other systems than R? 
Or is there something else that I should carefully consider when reading back that specific shapefile in R? 
In other terms, should I consider a different (safer) form of export as to be later used in R? And which one do you recommend, if any? May be a plain csv file with coords?
 
 thanks

**Comment by edzer** [comment]
The warning I see:
```r
Warning message:
In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Message 1: Value 123456789 of field field_name of feature 0 not successfully written. Possibly due to too larger number with respect to field width
```
is emitted by the GDAL library, and thus concerns software that is not controlled here.

**Comment by maxbre** [comment]
Yes, thank you for your quick reply;
I was just wondering if the warning can have some side-effects on the correct writing of the field: apparently not, as far as I understand!

**Comment by edzer** [comment]
The general recommendation is to not use shapefiles: the format is not an open standard, it has many limitations and modern formats are available. A good alternative is GeoPackage.
