### ISSUE TITLE
st_area is always 0

### ISSUE THREAD

**Issue by williamsdrake** [r-spatial/sf#2381]
I am working with coordinates to generate a polygon without any geographical system. I'm trying to calculate the area, but every time I do, the area is 0. The polygon itself is not self-intersecting and it is closed. I'm sure I'm missing something very simple but I just have no idea what. 

Here is the code:
```
library(dplyr)
library(sf)
data <- list(
  x = c(1738.675, 1737.612, 1736.125, 1734.425, 1732.938, 1732.938, 1733.362, 1735.913, 1737.612, 1739.950, 
        1741.650, 1742.713, 1743.775, 1746.112, 1747.388, 1749.725, 1750.788, 1751.000, 1750.788, 1749.300,
        1747.812, 1745.263, 1742.713, 1740.588, 1738.675),
  y = c(910.5625, 911.2000, 911.6250, 912.6875, 916.0875, 917.1500, 918.0000, 920.3375, 923.1000, 925.6500,
        925.8626, 926.5000, 926.2875, 924.5875, 924.1625, 922.2500, 920.7625, 919.0625, 918.4251, 915.0250,
        913.3250, 912.0501, 910.9876, 910.5625, 910.5625),
  label = rep("a", 25)
)

df <- data.frame(data)

sf_df <- st_as_sf(df, coords = c("x", "y")) %>%
  group_by(label)

polygons <- sf_df %>%
  summarise(geometry = st_union(geometry)) %>%
  st_as_sf()

polygons$area <- st_area(polygons)
```
The result of the area calculation is 0. 

I've also plotted the data and this is the output:
`
plot(polygons[,1])
`
![image](https://github.com/r-spatial/sf/assets/61563969/151e170f-9bd4-48ea-82f4-464364401271)

I have also used these same coordinates in python to generate a polygon and the area calculates correctly. However, my entire workflow is in R so I'd like to use an R solution for this. 

Any help would be much appreciated. Thank you!

**Comment by rsbivand** [comment]
```
sf_df <- st_as_sf(df, coords = c("x", "y"))
st_geometry_type(sf_df)
st_dimension(sf_df)
sf_df |> st_union() |> st_geometry_type()
sf_df |> st_union() |> st_dimension()
sf_df |> st_union() |> st_cast("POLYGON") |> st_geometry_type()
sf_df |> st_union() |> st_cast("POLYGON") |> st_dimension()
sf_df |> st_union() |> st_cast("POLYGON") |> plot(axes=TRUE)
```
Although casting to polygon creates an object with the correct dimensionality and type, it isn't correct, because cast zig-zags across the area. While linestrings can be built into polygon(s) with `st_polygonize`, there is no GEOS function for building linestrings from points. Perhaps reconfiguring the input as a matrix and using `st_polygon` is both more direct and less error-prone:
```
crds <- cbind(data$x, data$y)
crds |> list() |> st_polygon()  |> st_sfc() -> SFG
SFG |> plot(axes=TRUE)
SFG |> st_dimension()
SFG |> st_geometry_type()
SFG |> st_area()
```

**Comment by edzer** [comment]
IIRC, the problem is with `st_union` which creates a `MULTIPOINT` _and_ arranges the points so they have increasing _x_ coordinate. This is not wrong, but often unexpected.

**Comment by williamsdrake** [comment]
Thank you all for the comments and explanation. @rsbivand method using st_polygon what I will use going forward.
