### ISSUE TITLE
Argument mismatch in the docs for `st_zm()`

### ISSUE THREAD

**Issue by dimfalk** [r-spatial/sf#2383]
Having a look at `?st_zm`, this is the information given in the docs:

> **Usage:** 
> st_zm(x, ..., drop = TRUE, what = "ZM")

> **Details:** 
> Only combinations drop=TRUE, what = "ZM", and drop=FALSE, what="Z" are supported so far. In case **add=TRUE**, x should have XY geometry, and zero values are added for Z.

There is no `add = TRUE` option here as far as I can judge, so I guess this part of the docs probably was not updated when `drop` was introduced and it should be `drop = FALSE`?

---

And while we're at it, just another little thing I noticed at `?st_make_grid`:

> **Arguments**: 
> crs    
> object of class crs; coordinate reference system of the target ~~of the target~~ grid in case argument x is missing, if x is not missing, its crs is inherited.

**Comment by edzer** [comment]
Thanks!
