### ISSUE TITLE
Consider adding a `@Manual` BibTeX entry to the CITATION file

### ISSUE THREAD

**Issue by arnaudgallou** [r-spatial/sf#2404]
I'd like to cite the sf package in the paper I'm working on but the package doesn't provide a BibTeX entry for the actual package. I can only choose between a citation for a book or article. I'd recommend to add a `@Manual` BibTeX entry because that's often the most appropriate/easiest citation to use when referencing a package in a publication.

**Comment by rsbivand** [comment]
`toBibtex(citation("sf"))`?

**Comment by arnaudgallou** [comment]
`toBibtex(citation("sf"))` only returns a BibTeX entries for a book and article because there's no explicit `@Manual` entry available and having a CITATION file stops `citation()` from generating a citation from the package metadata.

``` r
toBibtex(citation("sf"))
#> @Book{,
#>   author = {Edzer Pebesma and Roger Bivand},
#>   title = {{Spatial Data Science: With applications in R}},
#>   year = {2023},
#>   publisher = {{Chapman and Hall/CRC}},
#>   url = {https://r-spatial.org/book/},
#>   doi = {10.1201/9780429459016},
#> }
#> 
#> @Article{,
#>   author = {Edzer Pebesma},
#>   title = {{Simple Features for R: Standardized Support for Spatial Vector Data}},
#>   year = {2018},
#>   journal = {{The R Journal}},
#>   doi = {10.32614/RJ-2018-009},
#>   url = {https://doi.org/10.32614/RJ-2018-009},
#>   pages = {439--446},
#>   volume = {10},
#>   number = {1},
#> }
```

<sup>Created on 2024-06-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by arnaudgallou** [comment]
This is how the rmarkdown developers handle multiple citations that also includes a `Manual` entry (with automatic updates): https://github.com/rstudio/rmarkdown/blob/main/inst/CITATION

**Comment by rsbivand** [comment]
Ignore rstudio. `?citation`

`toBibtex(citation("sf", auto=TRUE))`?

**Comment by arnaudgallou** [comment]
Thanks, `toBibtex(citation("sf", auto=TRUE))` returns the appropriate citation.
