### ISSUE TITLE
Unable to locate package libsqlite0-dev for sf install on Ubuntu

### ISSUE THREAD

**Issue by mmothersole** [r-spatial/sf#2423]
I need to install 'ggseg' in RStudio but it requires the 'sf' package installation. Because I run Ubuntu 24.04, I cannot install sf in RStudio and when I try to run the preliminary packages for the sf install in terminal, I get the error message "Unable to locate package libsqlite0-dev". I've tried to install libsqlite3-dev and I get the error message "Package 'libsqlite3-dev' has no installation candidate".

I'm at a dead end on what to do. Any help would be greatly appreciated.

![Screenshot from 2024-08-14 16-01-25](https://github.com/user-attachments/assets/623f2ba1-ceab-4cd1-8122-ec48bfd9f54c)
![Screenshot from 2024-08-14 17-11-06](https://github.com/user-attachments/assets/4ad757dc-3d0a-4409-b9e8-d14a9ce6d1bb)

**Comment by edzer** [comment]
Try `sudo apt-get install libsqlite0-dev`

**Comment by mmothersole** [comment]
![Screenshot from 2024-08-24 14-35-23](https://github.com/user-attachments/assets/2aaed515-595b-4c1f-882d-234ad82c895d)

**Comment by mmothersole** [comment]
@edzer How do I reopen the issue? There is no reopen issue button.

**Comment by edzer** [comment]
It's not an issue with package `sf`, but with your operating system setup.

**Comment by PaulMelloy** [comment]
Hello i ran into this issue as well.
Perhaps an issue with the documentation on the `sf` [website installation instructions for ubunto](https://r-spatial.github.io/sf/#ubuntu). 
debian (what ubuntu is based on) is not supporting `libsqlite0-dev` by the look of it. Try version 3 i.e.
```
sudo apt-get install libsqlite3-dev
```

This allowed me to install `sf` on my Linux Mint distro

**Comment by mmothersole** [comment]
On Ubuntu 24.04, I'm getting this:
![Screenshot from 2024-10-27 15-15-10](https://github.com/user-attachments/assets/4b114253-5c00-4541-9764-cdeda084dca3)

**Comment by edzer** [comment]
See the ubuntu section in README:
```r
sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev libsqlite0-dev
```
