### ISSUE TITLE
Unable to locate package libsqlite0-dev for sf install on Ubuntu

### ISSUE THREAD

**Issue by mmothersole** [r-spatial/sf#2427]
I need to install 'ggseg' in RStudio but it requires the 'sf' package installation. Because I run Ubuntu 24.04, I cannot install sf in RStudio and when I try to run the preliminary packages for the sf install in terminal, I get the error message "Unable to locate package libsqlite0-dev". I've tried to install libsqlite3-dev and I get the error message "Package 'libsqlite3-dev' has no installation candidate".

I'm at a dead end on what to do. Any help would be greatly appreciated. Also since there is no reopen button, please don't close the issue unless you're 100% sure you know the solution to the issue.

![Screenshot from 2024-08-14 16-01-25](https://github.com/user-attachments/assets/4ae34cff-951a-4701-a777-3b4900d8c5c3)
![Screenshot from 2024-08-24 14-35-23](https://github.com/user-attachments/assets/b2a92423-eb54-4586-b8f4-6ac0693b48c8)
![Screenshot from 2024-08-14 17-11-06](https://github.com/user-attachments/assets/d7e18d49-187f-4948-8e03-55e75a2ddfc0)

**Comment by edzer** [comment]
I'm really sorry, but questions of this kind are beyond the support we can offer here.
