### ISSUE TITLE
[feature] function to get `sf_column` attribute

### ISSUE THREAD

**Issue by JosiahParry** [r-spatial/sf#2435]
As a package developer I often want to grab the geometry column from an sf object. However, it is not safe to assume that the column is called `geometry`. For this reason I grab the `sf_column` attribute. This is done via `attr(x, "sf_column")`. It would be great if there were a helper function to get this. For example: 

``` r
sf_column <- function(x) {
  if (!inherits(x, "sf")) {
    stop("Expected an `sf` object")
  }
  attr(x, "sf_column")
}

x <- sf::st_sf(
  x = 1, foo = sf::st_sfc(sf::st_point(c(0, 0)))
)

sf_column(x)
#> [1] "foo"

sf_column(1L)
#> Error in sf_column(1L): Expected an `sf` object

sf_column(list())
#> Error in sf_column(list()): Expected an `sf` object
```

**Comment by edzer** [comment]
> As a package developer I often want to grab the geometry column from an sf object.

For that, `sf` provides the generic `st_geometry()`.

**Comment by JosiahParry** [comment]
Perhaps I should edit the text, I often want to get the geometry column _name_. `st_geometry()` is indeed useful for accessing the underlying sfc. But often i need to know which column is the geometry column by name or position and the `sf_column` attribute helps with that

**Comment by edzer** [comment]
> There are a good handful of folks

I count three, and pretty different ones.
