### ISSUE TITLE
accept WKT "POLYGON FULL", for full polygon (entire Earth), if coordinates are geodetic

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#2441]
The [full polygon](https://r-spatial.org/book/04-Spherical.html#ring-direction-and-full-polygon) is not part of the simple feature standard, but is needed when coordinates are geodetic. The "hidden" implementation used by `s2geometry` is `POLYGON((0 -90,0 -90))`
```r
st_as_sfc("POLYGON((0 -90,0 -90))", crs = 4326) |> st_area()
# 5.100661e+14 [m^2]
```
but that is rather ugly from the user side. A more reasonable approach would be
```r
library(sf)
# Linking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.4.0; sf_use_s2() is TRUE
x = st_as_sfc(c("POINT(0 1)", "POLYGON FULL"), crs = 'OGC:CRS84')
x
# Geometry set for 2 features 
# Geometry type: GEOMETRY
# Dimension:     XY
# Bounding box:  xmin: 0 ymin: -90 xmax: 0 ymax: 1
# Geodetic CRS:  WGS 84 (CRS84)
# POINT (0 1)
# POLYGON FULL
st_area(x)
# Units: [m^2]
# [1] 0.000000e+00 5.100661e+14
```
I suppose it should only be accepted when it is clear that the CRS is unprojected / coordinates are geodetic.

**Comment by edzer** [comment]
T.b.d. :

* [ ] `st_make_valid()`

**Comment by edzer** [comment]
As discussed with @evetion

**Comment by evetion** [comment]
Will there be a WKB equivalent? And if not, how does one store this WKT in files etc?

**Comment by edzer** [comment]
Good questions, this is less obvious! The "cheap" option is to use the WKB of `POLYGON((0 -90,0 -90))`, which is, in hex
```r
> st_as_sfc("POLYGON((0 -90,0 -90))", crs = 'OGC:CRS84') |> st_as_binary(hex = TRUE)
[1] "01030000000100000002000000000000000000000000000000008056c0000000000000000000000000008056c0"
```
I'm afraid other options would require modification of the big upstream libraries.

**Comment by edzer** [comment]
> I suppose it should only be accepted when it is clear that the CRS is unprojected / coordinates are geodetic.

Probably more useful would be that `POLYGON FULL` passes also when _no_ CRS is specified - for those working by default in geodetic coordinates.

**Comment by edzer** [comment]
Here's a test run (in sf/tests/full.R):
```r
suppressPackageStartupMessages(library(sf))

# create full polygon:
(f = st_as_sfc("POLYGON FULL"))
# Geometry set for 1 feature 
# Geometry type: POLYGON
# Dimension:     XY
# Bounding box:  xmin: -180 ymin: -90 xmax: 180 ymax: 90
# CRS:           NA
# POLYGON FULL
g = st_sfc(st_polygon(list(matrix(c(0,-90,0,-90), 2, byrow = TRUE))))
identical(f, g)
# [1] TRUE
old = sf_use_s2(FALSE)
# Spherical geometry (s2) switched off
try(st_as_sfc("POLYGON FULL")) # errors
# OGR: Corrupt data
# Error : OGR error
sf_use_s2(old)
# Spherical geometry (s2) switched on
(f = st_as_sfc(c("POLYGON FULL", "POLYGON((0 0,1 0,1 1,0 1,0 0))")))
# Geometry set for 2 features 
# Geometry type: POLYGON
# Dimension:     XY
# Bounding box:  xmin: -180 ymin: -90 xmax: 180 ymax: 90
# CRS:           NA
# POLYGON FULL
# POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))
st_is_full(f)
# [1]  TRUE FALSE
st_bbox(f[1])
# xmin ymin xmax ymax 
# -180  -90  180   90 
st_bbox(f[2])
# xmin ymin xmax ymax 
#    0    0    1    1 
st_is_valid(f) # full polygon NA: right, we don't know the CRS
# [1]   NA TRUE
st_crs(f) = 'OGC:CRS84' # geodetic:
st_is_valid(f)
# [1] TRUE TRUE
st_crs(f) = NA
try(st_make_valid(f))
# Error in (function (msg)  : 
#   IllegalArgumentException: Invalid number of points in LinearRing found 2 - must be 0 or >= 3
st_crs(f) = 'OGC:CRS84' # geodetic:
st_make_valid(f)
# Geometry set for 2 features 
# Geometry type: POLYGON
# Dimension:     XY
# Bounding box:  xmin: -180 ymin: -90 xmax: 180 ymax: 90
# Geodetic CRS:  WGS 84 (CRS84)
# POLYGON FULL
# POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))
# mixed geometries:
(f = st_as_sfc(c("POLYGON FULL", "POLYGON((0 0,1 0,1 1,0 1,0 0))", "POINT(0 1)"), crs = 'OGC:CRS84'))
# Geometry set for 3 features 
# Geometry type: GEOMETRY
# Dimension:     XY
# Bounding box:  xmin: -180 ymin: -90 xmax: 180 ymax: 90
# Geodetic CRS:  WGS 84 (CRS84)
# POLYGON FULL
# POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))
# POINT (0 1)
st_bbox(f[1])
# xmin ymin xmax ymax 
# -180  -90  180   90 
st_bbox(f[3])
# xmin ymin xmax ymax 
#    0    1    0    1 
st_is_valid(f)
# [1] TRUE TRUE TRUE
st_make_valid(f)
# Geometry set for 3 features 
# Geometry type: GEOMETRY
# Dimension:     XY
# Bounding box:  xmin: -180 ymin: -90 xmax: 180 ymax: 90
# Geodetic CRS:  WGS 84 (CRS84)
# POLYGON FULL
# POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))
# POINT (0 1)
st_make_valid(f[2:3])
# Geometry set for 2 features 
# Geometry type: GEOMETRY
# Dimension:     XY
# Bounding box:  xmin: 0 ymin: 0 xmax: 1 ymax: 1
# Geodetic CRS:  WGS 84 (CRS84)
# POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))
# POINT (0 1)
```

**Comment by edzer** [comment]
Do we need a `MULTIPOLYGON FULL`?

**Comment by evetion** [comment]
> Do we need a `MULTIPOLYGON FULL`?

That doesn't make sense conceptually, as there would be multiple overlapping full polygons? Or is it a multi with a single polygon?

General observation, we clearly have reached the limits of SF, and instead of trying to patch/hack it, it might be simpler to introduce Sphere (or similar?) as a geometry?

**Comment by edzer** [comment]
> Or is it a multi with a single polygon?

yes. 

The problem is that SFA already has _all_ types empty (7 empty geometry types) that all point to the same concept ("no points for which...")

**Comment by edzer** [comment]
> Do we need a `MULTIPOLYGON FULL`?

See also [this](https://erouault.blogspot.com/2024/09/those-concepts-in-geospatial-field-that.html) discussion, from @rouault

**Comment by edzer** [comment]
This is now in branch `polygon_full2`. 

The only revdep regression I see is in `mapme.biodiversity`; @goergen95 could you please run a check using this branch? I think what is going on is that global polygons are created at a moment that `sf_use_s2()` is `TRUE`, resulting in `POLYGON FULL`, then you're using this e.g. in `.get_intersection()` and call `st_intersects()` after (temporary) setting `sf_use_s2(FALSE)` - which then errors when the `POLYGON FULL` is considered invalid in GEOS. The solution would be to create the global polygon also under `sf_use_s2(FALSE)`, so that no `POLYGON FULL` occurs (to get your old behaviour), alternatively you could do everything under `sf_use_s2(TRUE)`. No mix.

**Comment by goergen95** [comment]
Hi @edzer,
thanks for the heads-up! Maybe I am missing something with my understanding of s2, but we rely on the second example returning `TRUE` in `mapme.biodiversity`:

``` r
library(sf)
#> Linking to GEOS 3.13.0, GDAL 3.9.2, PROJ 9.5.0; sf_use_s2() is TRUE

sf_use_s2()
#> [1] TRUE
x <- st_as_sfc(st_bbox(read_sf(system.file("shape/nc.shp", package="sf"))))

bbox <- c(xmin = -180.0, ymin = -90.0, xmax = 180.0, ymax = 90.0)
(tile <- st_as_sf(st_as_sfc(st_bbox(bbox, crs = st_crs(x)))))
#> Simple feature collection with 1 feature and 0 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -180 ymin: -90 xmax: 180 ymax: 90
#> Geodetic CRS:  NAD27
#>              x
#> 1 POLYGON FULL
st_intersects(x, tile, sparse = FALSE)
#>      [,1]
#> [1,] TRUE

bbox <- c(xmin = -180.0, ymin = -60.0, xmax = 180.0, ymax = 90.0)
(tile <- st_as_sf(st_as_sfc(st_bbox(bbox, crs = st_crs(x)))))
#> Simple feature collection with 1 feature and 0 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -180 ymin: -60 xmax: 180 ymax: 90
#> Geodetic CRS:  NAD27
#>                                x
#> 1 POLYGON ((-180 -60, 180 -60...
st_intersects(x, tile, sparse = FALSE)
#>       [,1]
#> [1,] FALSE
```

<sup>Created on 2024-10-09 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


 
We deal there a lot with global/quasi-global data sources (vector and raster) that we need to intersect. I am happy if we can omit switching off s2 for this (up and running [here](https://github.com/mapme-initiative/mapme.biodiversity/tree/polygonFull)) but this seems to fail for *nearly* global tiles.

**Comment by edzer** [comment]
Thanks; conversion to `s2` reverts ring direction if the area is larger than half the globe, assuming it is wrong. After
```r
options(s2_oriented=TRUE)
```
your example runs. The problem is that this affects all other conversions, e.g. `x` may have wrongly oriented rings. I feel that we'll have to be able to do this at the `st_as_sfc()` level and add an `oriented=TRUE` option, which is then glued to the `sfc` such that `st_intersects` gets it.

**Comment by edzer** [comment]
This commit now understand that `st_as_sfc.bbox()` always returns an oriented polygon.

**Comment by edzer** [comment]
merged into `main`.

**Comment by edzer** [comment]
@goergen95 note that 
```r
> st_area(tile)
5.100661e+14 [m^2]
> st_area(st_as_sfc("POLYGON FULL", crs = 'OGC:CRS84'))
5.100661e+14 [m^2]
```
in other words, this way you do not define a polygon that doesn't go further south than -60: this would require segmenting the parallel; s2 uses great circles not parallels. It is worth considering doing that in `sf``.
