### ISSUE TITLE
Why as.ppp.sf attach only the first column as mark? 

### ISSUE THREAD

**Issue by agila5** [r-spatial/sf#2450]
Dear all, I was wondering why the following code

https://github.com/r-spatial/sf/blob/6f247a5c902e58e7392dc88f94ab021b9095cc96/R/spatstat.R#L141-L154

forces the conversion sf -> ppp to keep only the first column of mark. What are the downside of keeping all the columns (if any) of `X`? AFAICT, the argument `value` in `spatstat.geom::setmarks` accepts a vector but also a data.frame object. For example: 

``` r
library(sf)
library(spatstat)

X <- st_read(system.file("csv/pt.csv", package="sf"))
pp <- spatstat.geom::as.ppp(st_geometry(X)) 
st_geometry(X) = NULL
spatstat.geom::setmarks(pp, X) 
#> Marked planar point pattern: 3 points
#> Mark variables: Id, Int64, Int32, WKT 
#> window: rectangle = [0, 44] x [0, 55] units
```

<sup>Created on 2024-10-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**EDIT**: Maybe this wasn't always the case, but I cannot find any proper reference in the NEWS file of spatstat

**Comment by edzer** [comment]
Yes, good point, I vaguely recollect that marks were univariate, but may have overlooked this. PR welcome!
