### ISSUE TITLE
Adding metadata to a .shp.xml file when writing to shapefile

### ISSUE THREAD

**Issue by Chandra-Goetsch** [r-spatial/sf#2454]
I have browsed through the open and closed issues here and run multiple Google searches, but can't seem to find an answer for this question. For a project I am working on, we would like to be able to add metadata tags to a shapefile in R as a .shp.xml file that could then be recognized by ArcGIS. I can't seem to find any information on creating a .shp.xml file in conjunction with creating a shapefile, either with the sf package or another R package. I'm hoping someone here might have some information on this issue.

Thanks in advance.

**Comment by rsbivand** [comment]
ESRI Shapefiles are deprecated by ESRI too - support for them in OGR/GDAL is maintenance only. They are fairly hopeless with geometries, hopeless with the DBF limitation on field names, hopeless on representing numerical fields as strings in the DBF, hopeless in not using modern WKT CRS representation, and hopeless on character string encodings. I cannoot see any reference to the sidecar auxiliary file in https://gdal.org/en/latest/drivers/vector/shapefile.html#esri-shapefile-dbf, so most likely there is no way other than reading the sidecar with an XML library such as `xml2` and re-writing it after adding what you want. Really any vector data project begun in the last ten years should have used GeoPackage, and older projects should convert soon.

For any advice, you'd need to provide a sample collection of all the files making up your shapefile, documentation on the specification of the sidecar file (not in http://shapelib.maptools.org/dl/shapefile.pdf), and an example of what you want to add and why.
