### ISSUE TITLE
1.0-18 compile error

### ISSUE THREAD

**Issue by yuanjiayj** [r-spatial/sf#2459]
error info. list below:

sf :
 Version 1.0-14 installed in /home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4 
 Version 1.0-18 available at https://mirrors.tuna.tsinghua.edu.cn/CRAN
Update? (Yes/no/cancel) 
试开URL’https://mirrors.tuna.tsinghua.edu.cn/CRAN/src/contrib/sf_1.0-18.tar.gz'
Content type 'application/octet-stream' length 3804756 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘sf’ ...
** 成功将‘sf’程序包解包并MD5和检查
** using staged installation
configure: CC: gcc
configure: CXX: g++ -std=gnu++17
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.4.0
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available for running:... yes
configure: GDAL: 2.4.0
configure: pkg-config proj exists, will use it
checking for proj_api.h... yes
configure: PROJ: 5.2.0
checking for pj_init_plus in -lproj... yes
checking PROJ: epsg found and readable... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.7.1
checking GEOS version >= 3.4.0... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/lib/mips64el-linux-gnuabi64 -lgeos_c... yes
configure: Package CPP flags:   -I/usr/include/gdal -I/usr/include
configure: Package LIBS: -lproj   -L/usr/lib -lgdal -L/usr/lib/mips64el-linux-gnuabi64 -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
** libs
using C++ compiler: ‘g++ (Uos 8.3.0.13-deepin1) 8.3.0’
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c bbox.cpp -o bbox.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c gdal.cpp -o gdal.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c gdal_geom.cpp -o gdal_geom.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c gdal_read.cpp -o gdal_read.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c gdal_read_stream.cpp -o gdal_read_stream.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c gdal_utils.cpp -o gdal_utils.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c gdal_write.cpp -o gdal_write.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c geos.cpp -o geos.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c hex.cpp -o hex.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c mdim.cpp -o mdim.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c ops.cpp -o ops.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c polygonize.cpp -o polygonize.o
g++ -std=gnu++17 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/gdal -I/usr/include -I'/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/Rcpp/include' -I/usr/local/include    -fpic  -g -O2   -c proj.cpp -o proj.o
proj.cpp: In function ‘Rcpp::LogicalVector CPL_set_data_dir(Rcpp::CharacterVector, bool)’:
proj.cpp:247:3: error: ‘proj_context_set_search_paths’ was not declared in this scope
   proj_context_set_search_paths(PJ_DEFAULT_CTX, 1, &cp);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
proj.cpp:247:3: note: suggested alternative: ‘proj_context_destroy’
   proj_context_set_search_paths(PJ_DEFAULT_CTX, 1, &cp);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   proj_context_destroy
proj.cpp: In function ‘Rcpp::LogicalVector CPL_use_proj4_init_rules(Rcpp::IntegerVector)’:
proj.cpp:261:2: error: ‘proj_context_use_proj4_init_rules’ was not declared in this scope
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, v[0]);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
proj.cpp:261:2: note: suggested alternative: ‘CPL_use_proj4_init_rules’
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, v[0]);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CPL_use_proj4_init_rules
proj.cpp: In function ‘Rcpp::List CPL_proj_is_valid(std::__cxx11::string)’:
proj.cpp:277:2: error: ‘proj_context_use_proj4_init_rules’ was not declared in this scope
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
proj.cpp:277:2: note: suggested alternative: ‘CPL_use_proj4_init_rules’
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, 1);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CPL_use_proj4_init_rules
proj.cpp: In function ‘Rcpp::NumericMatrix CPL_proj_direct(Rcpp::CharacterVector, Rcpp::NumericMatrix, bool, bool, bool)’:
proj.cpp:314:2: error: ‘proj_context_use_proj4_init_rules’ was not declared in this scope
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, 1); // FIXME: needed?
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
proj.cpp:314:2: note: suggested alternative: ‘CPL_use_proj4_init_rules’
  proj_context_use_proj4_init_rules(PJ_DEFAULT_CTX, 1); // FIXME: needed?
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CPL_use_proj4_init_rules
proj.cpp:324:14: error: ‘proj_normalize_for_visualization’ was not declared in this scope
   PJ *NewP = proj_normalize_for_visualization(PJ_DEFAULT_CTX, P);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [/usr/local/lib/R/etc/Makeconf:204：proj.o] 错误 1
ERROR: compilation failed for package ‘sf’
* removing ‘/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/sf’
* restoring previous ‘/home/yuanjiayj/R/mips64el-unknown-linux-gnuabi64-library/4.4/sf’

下载的程序包在
        ‘/home/yuanjiayj/tmp/RtmpFebqNf/downloaded_packages’里
警告信息:
In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  安装程序包‘sf’时退出狀態的值不是0

**Comment by yuanjiayj** [comment]
so far ,I only can install 1.0-14 in my computer.

**Comment by edzer** [comment]
Looks like a broken proj install: any chance of updating it (it is now at version 9.3.1...), maybe along with gdal and geos?
