### ISSUE TITLE
Setting lims alters the shape of geom_sf

### ISSUE THREAD

**Issue by liuyadong** [r-spatial/sf#2461]
**Describe the bug**

Hi, I'm making maps of Russia using `geom_sf`, but the  height/width ratio seems off. Is there a way to maintain the shape as it appears in a global context?

**To Reproduce**

``` r
library(sf)
#> Linking to GEOS 3.13.0, GDAL 3.9.2, PROJ 9.5.0; sf_use_s2() is TRUE
library(rnaturalearth)
library(ggplot2)
russia <- ne_countries(country = "russia", returnclass = "sf")
russia |>
  st_bbox(russia)
#>       xmin       ymin       xmax       ymax 
#> -180.00000   41.15142  180.00000   81.25040

ggplot() +
  geom_sf(data = russia) +
  coord_sf(crs = 4326, expand = F)
```

![](https://i.imgur.com/8LuOTjP.png)

``` r

ggplot() +
  geom_sf(data = russia) +
  coord_sf(crs = 4326, expand = F) +
  ylim(-90, 90)
```

![](https://i.imgur.com/2oDeJJV.png)

<sup>Created on 2024-10-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by liuyadong** [comment]
Thanks @edzer Russia is just one example, but more generally, it seems that QGIS can preserve the shape as it appears in a global context. I’m curious if `geom_sf` offers a similar option without changing the projection.

**Comment by edzer** [comment]
What exactly do you mean by global context? Could you share the QGIS image?

**Comment by liuyadong** [comment]
Here is the map of USA alone.
<img width="1493" alt="image" src="https://github.com/user-attachments/assets/edef2c50-26e7-4a61-9456-45d92bac6de7">

**Comment by edzer** [comment]
I think that if you add for instance `+coord_sf(crs = st_crs("+proj=eqc"))` to the two `ggplot()` commands, you get png files that match when overlayed.

**Comment by liuyadong** [comment]
@edzer Yes exactly. Could you briefly explain why?
I'm closing this issue.
