### ISSUE TITLE
st_is_empty() does not correctly identify empty geometries with sf>=1.0-18

### ISSUE THREAD

**Issue by goergen95** [r-spatial/sf#2463]
When reading a GeoJSON string like the one below `st_is_empty()` returned `TRUE` with `sf <= 1.0-17`.
The example JSON is not entirely constructed, since the output of `gdalinfo` in some cases might return such a string which we are relying on correctly identifying as empty in [`mapme.biodiversity`](https://github.com/mapme-initiative/mapme.biodiversity/blob/169fe289bd75ba313f72542d6072fa7562ec4c53/R/spatial-utils.R#L311-L334). I am not at all sure what is causing this, so I'd appreciate any help on this.

``` r
library(sf)
#> Linking to GEOS 3.13.0, GDAL 3.9.2, PROJ 9.5.0; sf_use_s2() is TRUE
packageVersion("sf")
#> [1] '1.0.18'
json <- '{"type":"Polygon","coordinates":[[]]}'
(x <- read_sf(json, quiet = TRUE))
#> Simple feature collection with 1 feature and 0 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 1
#>        geometry
#>   <POLYGON [°]>
#> 1       (EMPTY)
st_is_empty(x)
#> [1] FALSE
```

<sup>Created on 2024-10-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by goergen95** [comment]
Removing those extra `[]` we correctly identify the geometry as empty with `sf=1.0-18`.
Now I am just trying to figure out what changed between releases? [`sfc_is_empty`](https://github.com/r-spatial/sf/blame/4b5fab5d5095f8568917ed214ec652e3b067c69e/src/sfc-sfg.cpp#L94) seems to be untouched since apprx. two years.

``` r
library(sf)
#> Linking to GEOS 3.13.0, GDAL 3.9.2, PROJ 9.5.0; sf_use_s2() is TRUE
packageVersion("sf")
#> [1] '1.0.18'
json <- '{"type":"Polygon","coordinates":[]}'
(x <- read_sf(json, quiet = TRUE))
#> Simple feature collection with 1 feature and 0 fields (with 1 geometry empty)
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 1
#>        geometry
#>   <POLYGON [°]>
#> 1         EMPTY
st_is_empty(x)
#> [1] TRUE
```

<sup>Created on 2024-10-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by edzer** [comment]
Also note the difference in WKT: `(EMPTY)` vs `EMPTY` (the former being no WKT). The change was here: https://github.com/r-spatial/sf/commit/436c2938eefac117013b446af97cb7e09488af50 in `geom-predicates.R`: we stop using the GEOS function but use the built-in, which is more strict.

**Comment by edzer** [comment]
However, 
```r
'{"type":"MultiPolygon","coordinates":[[[]]]}' |> read_sf() |> st_is_empty()
## [1] FALSE
```

**Comment by goergen95** [comment]
Cool, thank you! Any plans on when `1.0-19` will land on CRAN?

**Comment by edzer** [comment]
CRAN likes updates to occur less than bimonthly; I don't consider this a bug fix but rather a "grey zone" fix, so would like to wait a while.

**Comment by edzer** [comment]
On CRAN now (earlier, because of the GDAL fix).
