### ISSUE TITLE
`sf` passes CMD check fine, but 4 packages using `sf` fail on GDAL 3.10.0 rc1

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#2466]
- [x] https://github.com/ropensci/osmextract/issues/298
- [ ] https://github.com/Defra-Data-Science-Centre-of-Excellence/sgapi/issues/1
More serious are segfaults, possibly from `st_area`:
- [x] https://github.com/aestears/plantTracker/issues/11
- [x] https://github.com/holans/ST-COS/issues/2

I have one platform with 1.0-18 and 3.9.3, another with 1.0-18 and 3.10.0rc1.

@edzer

**Comment by rsbivand** [comment]
`osmextract`, `sgapi`, `plantTracker` and `stcos` errors unchanged with GDAL 3.10.0rc2, `sf` passes all its own checks with GDAL 3.10.0rc2.

**Comment by rouault** [comment]
I've seen suspicous code in CPL_area() that could explain the crash in it. Cf https://lists.osgeo.org/pipermail/gdal-dev/2024-October/059747.html for diagnostic and suggestions

**Comment by rsbivand** [comment]
I'll try to check later, had to go out, thanks!

**Comment by rsbivand** [comment]
Segfaults in `stcos` and `plantTracker` resolved for GDAL 3.10.0rc2 with https://lists.osgeo.org/pipermail/gdal-dev/2024-October/059747.html. PR to follow Friday afternoon unless @edzer gets there first.

**Comment by edzer** [comment]
Submitted to CRAN...

**Comment by edzer** [comment]
On CRAN.
