### ISSUE TITLE
[QUESTION] st_concave_hull requires GEOS >= 3.11 in r package

### ISSUE THREAD

**Issue by sagesteppe** [r-spatial/sf#2471]
I assume cross posting to stackoverflow is still frowned upon, but I [opened this](https://stackoverflow.com/questions/79163336/error-pushing-package-with-sf-geos-dependency-to-github-pages-via-pkgdown-r) over there hoping to hear from some more pkgdown type users. Unfortunately it seems SO traffic is way way down, and no one is coming out of the word work. I am assuming this is an 'issue' you are familiar with dealing with, and might have easy suggestions for a fix? 

I'm having some issues trying to push a package up onto github pages, it seems the website will not go live if it comes up with some errors. Notably this one. The interesting thing is that the man page for the function in question renders totally fine, it's just this vignette that raises the error. It's totally fine on my machine and through rcmdcheck::rcmdcheck. 

```{r}
Writing `articles/index.html`
Reading vignettes/PACKAGE_VIGNETTE.Rmd
Error in `.f()`:
! Failed to render
  'vignettes/PACKAGE_VIGNETTE.Rmd'.
✖ Quitting from lines 373-380 [Grid Based Samples]
  (VIGNETTE.Rmd)
Caused by error:
! st_concave_hull requires GEOS >= 3.11
Backtrace:
```

I have tried 3 solutions: 
1) Copied the system requirements from the sf package Description (which I did not expect to work, but...) into my packages Description. I also updated the requirements to GEOS >= 3.11 stated above. 
2) Updating the R version in depends to 4.4.2
3) swapping over to geos_concave_hull. 

It seems option 3 will work, but I'll have to refactor the code around it a bit. Obviously I'd prefer to try and keep the process as it is, these hulls are in a pretty elaborate workflow which takes me a lot of time to troubleshoot.

**Comment by edzer** [comment]
This is a question that has more to to with GH actions and understanding the versions of software available there than with this package. The GA pkdgown runner of sf itself uses ubuntu-latest as image, which seems to come with geos 3.12.1.  You didn't reveal which package you are working on, or what you tried.

**Comment by sagesteppe** [comment]
Hey Edzer, 

Apologies for not providing more details. 

The only other semi-informed effort I have made is including `geos` in the imports, but rcmdcheck gave me a note about removing it since it seemed to be ignored. 

```{r}
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Chicago
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.1    tools_4.4.1       rstudioapi_0.17.1
```

Based on what you have said, perhaps the solution is as easy as upgrading to the latest stable Ubuntu on my end? Embarrassing if so... 

The package is [safeHavens](https://github.com/sagesteppe/safeHavens), it's quite simple.

**Comment by edzer** [comment]
Since your package does not contain any compiled code (C, C++ etc) it also does need non `SystemRequirements` - packages like `sf` and `terra` need to do that.

You are right about the geos on ubuntu 22.04:
```bash
root@c4917177dde5:/# geos-config --version
3.10.2
```
The [README](https://github.com/r-spatial/sf?tab=readme-ov-file#ubuntu) of this package has instructions how to get a more recent geos version without having to upgrade to 24.04.

**Comment by sagesteppe** [comment]
Thanks Edzer, 

My machine now has an updated geos, to 3.12.1 from 3.11.2. The package is able to pass all tests for both Windows and Mac OS. However the issues persists on Ubuntu (all versions (dev, stable, stable-1 (which is now expected) - except local). 

This is happening during: Run r-lib/actions/check-r-package@v2

``
------------ R CMD build -------------
* checking for file ‘.../DESCRIPTION’ ... OK
* preparing ‘safeHavens’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Error: --- re-building ‘safeHavens.Rmd’ using rmarkdown
Quitting from lines 389-398 [Grid Based Samples] (safeHavens.Rmd)
Error: Error: processing vignette 'safeHavens.Rmd' failed with diagnostics:
st_concave_hull requires GEOS >= 3.11
--- failed re-building ‘safeHavens.Rmd’
SUMMARY: processing the following file failed:
  ‘safeHavens.Rmd’
Error: Error: Vignette re-building failed.
``

Any more ideas of what I can try? Do I ignore tests for this OS? It is very clearly happily working on Ubuntu...

**Comment by edzer** [comment]
what does `sf::sf_extSoftVersion()` give?

**Comment by sagesteppe** [comment]
```
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H           PROJ 
      "3.12.1"        "3.8.4"        "9.3.1"         "true"         "true"        "9.3.1" 
```

**Comment by edzer** [comment]
I get
```r
set.seed(1)
matrix(runif(20),,2) |> 
  as.data.frame() |> 
  st_as_sf(coords = c("V1", "V2")) |> 
  st_combine() |> 
  st_concave_hull(ratio = .2) |> 
  plot()
```
![x](https://github.com/user-attachments/assets/b2dc58ce-f049-42a6-8a52-7c7325be3e34)

What do you get?

**Comment by sagesteppe** [comment]
Looks the same to me

![Concave_hull](https://github.com/user-attachments/assets/fb0f39df-bff9-43a7-9c7e-dec212acdc49)

**Comment by edzer** [comment]
Well, then it worked.

**Comment by sagesteppe** [comment]
Yes, it has always been fine locally. Not sure what is wrong with github actions. 

I am looking at your github/workflows/R-CMD-Check.yaml - do you think I can modify mine to specify that machines on linux need to run the code you linked anove in the README? 

```
      - name: Install macOS system dependencies
        if: runner.os == 'macos'
        run: brew install gdal proj
```

**Comment by sagesteppe** [comment]
Sorry for the confusion Edzer. @kadyb thanks we were typing at the same time, I wager the code you provided will work. I'll add it in and test.

**Comment by kadyb** [comment]
@sagesteppe, do you need a pull request (PR) to repository with patch?

**Comment by sagesteppe** [comment]
@edzer @kadyb hey no PR required, thanks for your help! The builds are success on all the ubuntu tests now, dev is still running, but that seems normal. [Website is live](https://sagesteppe.github.io/safeHavens/), and you are both thanked!
