### ISSUE TITLE
Unexpected increase in SF size after spatial operations.

### ISSUE THREAD

**Issue by Bevann** [r-spatial/sf#2474]
I am running into some unexpected behavior when I am sub setting a line feature where the resulting output is much larger than the inputs (approx 34x as large), even if the sub-setting does not modify the input data (as is the case in the small reproducible example in the attached .txt file). I have tried various fixes like re-casting to LINESTRING from MULTILINESTRING, changing projections, s2 geometry turned on vs not, consistent naming of the geometry list-col and can not figure out the reason for this behaviour.  The outputs are correct, but the massive increase in size slow workflow on the entire data set.  It seems as though the output has further nesting of list cols in the geometry columns, but trying to take a deeper look at that structure ends up freezing Rstudio.  Hoping someone has some insight into why this is happening and how I can prevent it in my scripts.

[SF_Line_Crop_Example.txt](https://github.com/user-attachments/files/17669715/SF_Line_Crop_Example.txt)

**Comment by kadyb** [comment]
It looks like the nodes are duplicated for some reason.

```r
nodes = st_coordinates(LINES_CLIP)[, 1:2]
idx = duplicated(nodes) | duplicated(nodes, fromLast = TRUE)
nodes[idx, ] # n = 8084
```

**Comment by kadyb** [comment]
In `terra` I observed the same difference between the number of nodes after crop. Maybe it is GEOS issue?

```r
library("terra")
BOUND = vect(BOUND)
LINES = vect(LINES)

LINES_CLIP = crop(LINES, BOUND)
nrow(crds(LINES_CLIP))
#> [1] 9611
```

**Comment by edzer** [comment]
Indeed, it seems that where the input is a MULTILINESTRING with a single LINESTRING in it, GEOS returns a MULTILINESTRING with a large number of LINESTRINGS, one for each pair of nodes, thus doubling the number of nodes.  Although you'd hope so, it seems that `st_line_merge()` doesn't do a good job in recreating the single LINESTRING.
