### ISSUE TITLE
OPENSSL version issue

### ISSUE THREAD

**Issue by ExpertS04p** [r-spatial/sf#2475]
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/data/lmx/.conda/envs/Rlmx/lib/R/library/sf/libs/sf.so':
  /lib/x86_64-linux-gnu/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /data/lmx/.conda/envs/Rlmx/lib/R/library/sf/libs/../../../.././libcurl.so.4)

**Comment by edzer** [comment]
Seems more of a conda problem then an `sf` problem?

**Comment by edzer** [comment]
See also #2479
