### ISSUE TITLE
R-devel (2024-11-08 r87310) - Segmentation fault: 11

### ISSUE THREAD

**Issue by RLumSK** [r-spatial/sf#2476]
**Describe the bug**
During install with the latest R-devel, the compilation on macOS (see session info below) fails with 

```
** byte-compile and prepare package for lazy loading
sh: line 1: 91823 Segmentation fault: 11  R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/yz/3s5p1pss4352wtlzt9_bzbp00000gp/T//RtmpEnZERW/file1627a41ad47e8'

 *** caught segfault ***
address 0x15970, cause 'invalid permissions'
```
I have not encountered any compilation issue with other R packages so far, so for the moment
I am somewhat confident that it is not related to my system settings. More, it happened quite recently (last two months), unfortunately I cannot pin-point the exact date/change (likely related to R-devel).

**To Reproduce**

Try install `install.packages("sf")` on a similar system using R-devel.
I've tried different versions of `sf` down to 1.0-14 with the same result. 

**Additional context**

Used homebrew libraries during compilation time: 

- proj/9.5.0
- libtiff/4.7.0
- xz/5.6.3/
- jpeg-turbo/3.0.4
- gdal/3.10.0_1
- geos/3.13.0

My session information: 

```r
R Under development (unstable) (2024-11-08 r87310)
Platform: aarch64-apple-darwin20
Running under: macOS Sequoia 15.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.5.0 tools_4.5.0   
```

**Comment by edzer** [comment]
Have you tried installing the binary package from CRAN?

**Comment by RLumSK** [comment]
@edzer Thanks for the swift response and sorry for not being more specific. Actually, I had done this because my first observation was that `'sf'` stopped working aka crashed RStudio when called via `library(sf)` (but in R-devel; means R `'sf'` was already in the library before). I have now loaded the binary from CRAN for R-release and then ran R-devel. The full terminal output:

```
> library(sf)

 *** caught segfault ***
address 0x15970, cause 'invalid permissions'

Traceback:
 1: ud_init(path)
 2: load_units_xml()
 3: fun(libname, pkgname)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(fun(libname, pkgname), error = identity)
 8: runHook(".onLoad", env, package.lib, package)
 9: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
10: asNamespace(ns)
11: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
12: loadNamespace(package, lib.loc)
13: doTryCatch(return(expr), name, parentenv, handler)
14: tryCatchOne(expr, names, parentenv, handlers[[1L]])
15: tryCatchList(expr, classes, parentenv, handlers)
16: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return && !quietly)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
17: library(sf)
```

Supplement:

- I have to admit this does not really surprise me. Usually I try to avoid precompiled packages from R-release when using R-devel. Also it looks similar, it could be something else.
- To get further to the bottom of it: I additionally tried the current R-release (4.4.2) and loaded the latest `'sf'` precompiled and built from source. In both cases no problem, no error. 

Summary:

|R VERSION    | 'sf' TYPE | OBSERVATION
|----- |------| ------------|
4.4.2   | binary | OK
4.4.2   | source | OK
devel (r87310)  | binary for R-release | segfault 
devel (r87310)  | source | segfault

**Comment by edzer** [comment]
Reinstall `units`?

**Comment by RLumSK** [comment]
Wow! Spot on, I removed and reinstalled `'units'` rebuilt `'units'` and `'sf'` for R-devel. I will close the issue. Thanks a lot! 
But may I ask how did you figure this out? Just from the `2: load_units_xml()` in the traceback?

**Comment by edzer** [comment]
Yes.
