### ISSUE TITLE
Multithreading geometric operations and predicates

### ISSUE THREAD

**Issue by lambdamoses** [r-spatial/sf#2478]
Is it possible to use multithreading for say `st_intersects` and `st_intersection`? Say x has a large number of geometries and y has a smaller number; presumably we can split x and find the intersections with y in parallel. When only a small number of x intersect y, it's pretty fast, but it takes a while when a large number of x intersect y. While I can do this with `mclapply`, it would be nice if multithreading is supported at the C++ level which would be much more efficient and can be turned on and off with an option.

**Comment by rsbivand** [comment]
@lambdamoses had these operations not been based on fast and efficient spatial indexing both in GEOS and s2, this might have made sense, but indexing is much better. Also, most of GDAL and GEOS are not thread-safe.

**Comment by lambdamoses** [comment]
Never mind, when x has many geometries but y has few, `st_intersects(y, x)` is much faster than `st_intersects(x, y)`. I just did `st_intersects(y, x)` instead.
