### ISSUE TITLE
A install issue: checking GDAL: linking with --libs only... no

### ISSUE THREAD

**Issue by wuxiangning** [r-spatial/sf#2479]
Hello!
Hello, recently when I was using VSCode to remotely connect to a LINUX server, I encountered an error while installing the sf package. 
install.packages("sf", configure.args = "--with-gdal config=/home/wuxn/Miniconda3/bin/gdal-config --with-geos-config=/home/wuxn/Miniconda3/bin/geos-config --with-proj include=/home/wuxn/Miniconda3/include/ --with-proj-lib=/home/wuxn/Miniconda3/lib/")
The error message shows:
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
This prevents me from successfully installing the sf package. However, I was able to install the sf package without any issues locally. Could you please advise on how I can resolve this problem?
Thanks!
![8e9fafdd7225e2ac5a365692769bb5a](https://github.com/user-attachments/assets/b3632a7b-5825-48d9-973c-820c9971b622)
![f5b79d3c1c6f6905db2daf90ec7e297](https://github.com/user-attachments/assets/4df94a8b-133e-450c-86bd-147b80f297c5)
![454306b826c4ce1ddeec3ce6ff5222f](https://github.com/user-attachments/assets/0c47e875-c0c7-4368-8149-6de340b58abb)

**Comment by edzer** [comment]
Conda provides binary installs of `sf`, they call it `r-sf`. Please install that, or if you really need to compile from source using conda, then contact the maintainers of conda's `r-sf`  in case you run into trouble. The instructions found here, e.g. in the README, do not use conda.

**Comment by wuxiangning** [comment]
![image](https://github.com/user-attachments/assets/233929f4-e241-4a4d-a887-b705d5021e4e)
Hello!
I used conda to install the sf package, and the installation was successful. However, I couldn't load the sf package using library(sf). The error message indicated an issue with sqlite3_strlike, and I’m not sure how to resolve it. My server does have the sqlite and libsqlite packages installed.Why?

**Comment by edzer** [comment]
That is a conda problem, not an a problem of the `sf` package.
