### ISSUE TITLE
Request for additional information on `sf::st_area()` and other functions

### ISSUE THREAD

**Issue by AlviDab** [r-spatial/sf#2481]
I’d like to suggest adding some additional information to the documentation for `sf::st_area()` and potentially other functions with similar behaviour. Regarding `sf::st_area()`, I noticed that disabling the `s2` engine by setting `sf::sf_use_s2(FALSE)` produces different results. From what I understand (based on resources like [this post](https://stackoverflow.com/questions/75329126/area-computation-comparison-terra-vs-sf)), this switches the computation to `lwgeom::st_geod_area()`, which relies on an ellipsoidal model of the Earth. This method appears to provide greater accuracy compared to the spherical model used by the `s2` engine (please correct me if I’m wrong).

I think that including explanations about how enabling or disabling the `s2` engine affects calculations in `sf::st_area()` would be useful for the users. Including this information could be also valuable for other functions like `sf::st_intersection()` to clarify their behaviour.

Additionally, I believe it would be beneficial to offer guidance in the documentation on the use of geographic coordinate systems over projected coordinate systems for more accurate area calculations. This could help reduce potential confusion for users. 

Thank you for considering these suggestions!

**Comment by kadyb** [comment]
This is mentioned in the `st_area()` docs:

> st_area returns the area of a geometry, in the coordinate reference system used; in case `x` is in degrees longitude/latitude, [st_geod_area](https://r-spatial.github.io/lwgeom/reference/geod.html) is used for area calculation.

There is also a dedicated vignette on this issue here: https://r-spatial.github.io/sf/articles/sf7.html However, now it seems to me that it is not quite accurate in the `Switching between S2 and GEOS` section, because the data has a geographical coordinates, so de facto GEOS is not used, but `st_geod_area()` and `st_geod_distance()`, right?

The S2/GEOS issue is also described in the [Geocomputation with R](https://r.geocompx.org/reproj-geo-data.html?q=spheric#geom-proj), but Figure 7.1 also doesn't seem to be precise in the context of your question about `st_area()`.

**Comment by rsbivand** [comment]
In addition, any algoritm will only give an answer for the boundary coordinates, so a measurement taken in the field with more boundary points may also differ.

**Comment by kadyb** [comment]
Here is adapted reprex from the vignette:

```r
library("sf")
nc = read_sf(system.file("shape/nc.shp", package = "sf"))

# s2
sf_use_s2(TRUE)
area_s2 = st_area(nc)
units(area_s2) = "km^2"
summary(area_s2)
#>  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#> 430.8   914.2  1217.7  1270.3  1550.4  2450.8

# lwgeom
sf_use_s2(FALSE)
area_lwgeom = st_area(nc)
units(area_lwgeom) = "km^2"
summary(area_lwgeom)
#>  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#> 430.7   914.2  1217.7  1270.3  1550.5  2450.2 

# GEOS
sf_use_s2(FALSE)
nc_3857 = st_transform(nc, "EPSG:3857")
area_geos = st_area(nc_3857)
units(area_geos) = "km^2"
summary(area_geos)
#>  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#> 632.1  1382.8  1829.4  1923.5  2359.6  3640.6
```

**Comment by edzer** [comment]
Thanks - hope this improved the docs.
