### ISSUE TITLE
st_join does not properly join features with st_within predicate

### ISSUE THREAD

**Issue by fgoerlich** [r-spatial/sf#2486]
Hi,
I have this polygon and 24 grid cells

![Rplot1](https://github.com/user-attachments/assets/1e17c43f-ccf4-4fb8-8f72-9d03b078a127)

There are 8 intersecting cells and 1 cell inside the polygon.
Performing an `st_join` with `st_intersects` predicate, and `left = FALSE`, works as expected, and returns 8 cells
```
AAI  <- read_sf("st_join.gpkg", layer = "AAI")
Grid <- read_sf("st_join.gpkg", layer = "Grid")

join_int <- st_join(Grid, AAI, left = FALSE)
```
![Rplot2](https://github.com/user-attachments/assets/f67f8a92-4dd9-4606-8804-9add2df7dfa9)

Performing an `st_join` with `st_within` predicate, and `left = FALSE`, I expect only 1 cell, but it returns the same 8 cells as before.

```
join_within <- st_join(Grid, AAI, .predicate = st_within, left = FALSE)
```

![Rplot3](https://github.com/user-attachments/assets/c8d0ddc6-83e7-4d8f-a5ac-24f6ad55567e)

`st_filter` works as expected, for the `st_intersects` predicate, as well as for the  `st_within` predicate:

```
whithin <- st_filter(Grid, AAI, .predicate = st_within)
```
![Rplot4](https://github.com/user-attachments/assets/3c174ec4-65b4-481c-97ca-4831d81ed6a7)

Is this a bug or intended behaviour?
Find attached the data file and an script.
[st_join.zip](https://github.com/user-attachments/files/18041825/st_join.zip)

Thanks a lot.

**Comment by edzer** [comment]
Try
```r
st_join(Grid, AAI, join = st_within, left = FALSE) 
```

**Comment by fgoerlich** [comment]
It works!
I have checked the documentation. 
I thought `.predicate`was the general term.
It was my fault, sorry!
