### ISSUE TITLE
error occuring whn running gdalUtilities::gdalinfo with sf 1.0-19 and ENVI driver

### ISSUE THREAD

**Issue by jbferet** [r-spatial/sf#2491]
An error occurs when calling `gdalUtilities::gdalinfo` for ENVI file format. 
An [issue](https://github.com/r-spatial/stars/issues/724) was open for package stars, but it seems that the problem comes from sf.
here is an example, using a sentinel-2 subset to be downloaded from my repository, used as illustration for the package [biodivMapR](https://jbferet.github.io/biodivMapR/index.html). 

```
library(magrittr)
# url for the S2 raster subset
url <- 'https://gitlab.com/jbferet/myshareddata/-/raw/master/biodivMapR_S2_Sample/RASTER/S2A_T33NUD_20180104_Subset'
destfile <- file.path(tempdir(),'S2A_T33NUD_20180104_Subset')
download.file(url = url, destfile = destfile, method = 'auto', quiet = FALSE, mode = "wb")
# url for the subset header
urlhdr <-  'https://gitlab.com/jbferet/myshareddata/-/raw/master/biodivMapR_S2_Sample/RASTER/S2A_T33NUD_20180104_Subset.hdr'
destfile_HDR <- paste0(destfile,'.hdr')
download.file(url = urlhdr, destfile = destfile_HDR, method = 'auto', quiet = FALSE, mode = "w")

gdalUtilities::gdalinfo(datasetname = destfile, json = TRUE, quiet = T) %>%
  jsonlite::fromJSON()
```

The error does not occur when using sf 1.0-18

**Comment by kadyb** [comment]
The problem is probably with this dataset or GDAL, because the same occurs in `gdalinfo` and `terra::describe`:

```
gdalinfo "S2A_T33NUD_20180104_Subset.hdr"
ERROR 1: The selected file is an ENVI header file, but to open ENVI datasets, the data file should be selected instead of the .hdr file.  Please try again selecting the data file corresponding to the header file: S2A_T33NUD_20180104_Subset.hdr
```

I tested this on Windows 10 and GDAL 3.9.3.

**Comment by jbferet** [comment]
> The problem is probably with this dataset or GDAL, because the same occurs in `gdalinfo` and `terra::describe`:
> 
> ```
> gdalinfo "S2A_T33NUD_20180104_Subset.hdr"
> ERROR 1: The selected file is an ENVI header file, but to open ENVI datasets, the data file should be selected instead of the .hdr file.  Please try again selecting the data file corresponding to the header file: S2A_T33NUD_20180104_Subset.hdr
> ```
> 
> I tested this on Windows 10 and GDAL 3.9.3.

thank you for your answer @kadyb . The problem occured with other datasets. 
You may want to test `gdalinfo "S2A_T33NUD_20180104_Subset"` instead of `gdalinfo "S2A_T33NUD_20180104_Subset.hdr"` as suggested by the error message.

**Comment by kadyb** [comment]
So you mean that `gdalUtilities::gdalinfo()` in this case does not return JSON and this warning appears?

```
Warning message:
In CPL_gdalinfo(if (missing(source)) character(0) else source, options,  :
  GDAL Error 1: Zero positional arguments expected
```

**Comment by jbferet** [comment]
Sorry I should have been more accurate on the description of the error. 
Here is the error I get with sf 1.0-19 when running the code provided in my initial message, in addition to the warning message you mentioned

```
Error : lexical error: invalid char in json text.
                                       Driver: ENVI/ENVI .hdr Labelled
                     (right here) ------^
```

**Comment by jbferet** [comment]
thank you @kadyb !
ok then the problem comes from gdalUtilities. 
thank you for your help, and sorry for misidentifying the source of the error. 
I am closing the issue.

**Comment by edzer** [comment]
@jbferet please raise an issue there.
