### ISSUE TITLE
undefined symbol: _ZN11GDALDataset14GetRasterYSizeEv

### ISSUE THREAD

**Issue by mSparks43** [r-spatial/sf#2493]
**Describe the bug**
SF fails to install

**To Reproduce**
install.packages("sf")

**If reporting a change from previous versions**
Not sure when this broke, sometime in the last year

**Additional context**
GDAL: 3.8.5
PROJ: 9.4.1
GEOS: 3.12.2

<details>
R version 4.4.2 (2024-10-31)
Platform: x86_64-redhat-linux-gnu
Running under: Fedora Linux 41 (KDE Plasma)

Matrix products: default
BLAS/LAPACK: FlexiBLAS OPENBLAS-OPENMP;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.2   tools_4.4.2      Rcpp_1.0.13-1    stringi_1.8.4    zip_2.3.1        openxlsx_4.2.7.1

Error in loadNamespace(x) : there is no package called ‘sf’

**Comment by rsbivand** [comment]
How was GDAL installed? Are multiple versions installed?

**Comment by mSparks43** [comment]
> How was GDAL installed? Are multiple versions installed?

sudo dnf reinstall gdal-devel gdal

**Comment by mSparks43** [comment]
additionally I see

** byte-compile and prepare package for lazy loading
in method for ‘dbWriteTable’ with signature ‘"PostgreSQLConnection","character","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘dbDataType’ with signature ‘"PostgreSQLConnection","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘coerce’ with signature ‘"Spatial","sf"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"Spatial","sfc"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sf","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sfc","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"XY","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"crs","CRS"’: no definition for class “CRS”
in method for ‘coerce’ with signature ‘"sgbp","sparseMatrix"’: no definition for class “sparseMatrix”

**Comment by rsbivand** [comment]
Is 3.8.5 also installed? If so, you need to disambiguate, as 3.9.3 may be used for building but linkage fails when 3.8.5 is found. See https://r-spatial.github.io/sf/#multiple-gdal-geos-andor-proj-versions-on-your-system.

**Comment by mSparks43** [comment]
> Is 3.8.5 also installed? If so, you need to disambiguate, as 3.9.3 may be used for building but linkage fails when 3.8.5 is found. See https://r-spatial.github.io/sf/#multiple-gdal-geos-andor-proj-versions-on-your-system.

Dont think so, I got that from configure

checking GDAL: /usr/local/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available for running:... yes
configure: GDAL: 3.8.5
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 9.4.1
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
checking for geos-config... /usr/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.12.2
checking GEOS version >= 3.4.0... yes

**Comment by rsbivand** [comment]
So the first found gdal-config is from 3.8.5.  Try `gdal-config --version` and.`which gdal-config`.

**Comment by mSparks43** [comment]
msparks@localhost:/usr/lib64$ gdal-config --version
3.8.5
msparks@localhost:/usr/lib64$ which gdal-config
/usr/local/bin/gdal-config

**Comment by mSparks43** [comment]
gdal-config distribution/bug

msparks@localhost:/usr/lib64$ sudo dnf install gdal-config
Updating and loading repositories:
Repositories loaded.
Package "gdal-devel-3.9.3-1.fc41.x86_64" is already installed.

rm /usr/local/bin/gdal-config


sudo dnf reinstall gdal-config
Updating and loading repositories:
Repositories loaded.
Package                                                                          Arch              Version                                                                          Repository                                         Size
Reinstalling:
 gdal-devel                                                                      x86_64            3.9.3-1.fc41                                                                     updates                                         1.3 MiB
   replacing gdal-devel                                                          x86_64            3.9.3-1.fc41                                                                     updates                                         1.3 MiB

Transaction Summary:
 Reinstalling:       1 package
 Replacing:          1 package

Total size of inbound packages is 228 KiB. Need to download 228 KiB.
After this operation, 0 B extra will be used (install 1 MiB, remove 1 MiB).
Is this ok [y/N]: y
[1/1] gdal-devel-0:3.9.3-1.fc41.x86_64    

install.packages("sf")

** testing if installed package keeps a record of temporary installation path
* DONE (sf)

Thank you

**Comment by rsbivand** [comment]
And which GDAL does `dnf` claim to have installed? As you listed above?

**Comment by mSparks43** [comment]
> And which GDAL does `dnf` claim to have installed? As you listed above?

It claimed 3.9.3
removing it then reinstalling it now gives
gdal-config --version
3.9.3

and install packages works.

**Comment by mSparks43** [comment]
So this looks like a dnf5 bug - fixed
