### ISSUE TITLE
Graticules in `geom_sf`

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/sf#396]
Graticules works well in the first example - `world1` but there are some problems with the second one - `world2`:

``` r
library(tidyverse)                                                              
library(sf)                                                                     
library(maps)                                                                   
                                                                                
world1 <- st_as_sf(map('world', plot = FALSE, fill = TRUE)) %>%                 
st_transform(., "+proj=laea +y_0=0 +lon_0=155 +lat_0=-90 +ellps=WGS84 +no_defs")
                                                                                
ggplot() + geom_sf(data = world1)                                               
```

![](http://i.imgur.com/J9pnySD.png)

``` r
                                                                                
                                                                                
world2 <- st_as_sf(map('world', plot = FALSE, fill = TRUE)) %>%                 
st_transform(., "+proj=laea +y_0=0 +lon_0=-77 +lat_0=39 +ellps=WGS84 +no_defs") 
                                                                                
ggplot() + geom_sf(data = world2)                                               
```

![](http://i.imgur.com/QFtwkTu.png)

@edzer should I leave it here or post it as the `ggplot2` issue?

**Comment by edzer** [comment]
Here, it's a problem with `st_graticule`:
```r
st_graticule() %>% 
  st_transform("+proj=laea +y_0=0 +lon_0=-77 +lat_0=39 +ellps=WGS84 +no_defs") %>% 
  st_geometry %>% 
  plot
```

**Comment by edzer** [comment]
Increasing `ndiscr` in the call to `st_graticule` helps:
```r
st_graticule(ndiscr=1000) %>% st_transform("+proj=laea +y_0=0 +lon_0=-77 +lat_0=39 +ellps=WGS84 +no_defs") %>% st_geometry %>% plot
```
![x](https://user-images.githubusercontent.com/520851/27516917-3dd15a2c-59c3-11e7-8447-b8b3ac4e748d.png)

but how can we pass this such that it happens inside `geom_sf`? Maybe `geom_sf` should accept a `graticule` argument? Yes, this needs work on the `ggplot2` side.

**Comment by edzer** [comment]
With the to `sf` and PR to ggplot2 referenced above, with
```r
ggplot() + geom_sf(data = world2)+ coord_sf(ndiscr=1000)
```
I now get
![x](https://user-images.githubusercontent.com/520851/27517185-76ae2456-59c8-11e7-86e6-8e0ab7fe0494.png)

**Comment by Nowosad** [comment]
Thanks @edzer, great work as always! 
I have one related question. Why this argument (`ndiscr`) is added to `coord_sf()`? I would, naively, thought that `coord_sf()` is used to set a CRS and not to change any graphical outputs (such as graticules).

**Comment by edzer** [comment]
Other parameters passed to `st_graticule` (`crs`, `datum`) are also passed on to `coord_sf`, but I don't master the gg logic yet. @hadley, do you think `ndiscr` should be a parameter to `coord_sf`, as in this PR, or rather to `geom_sf`?

**Comment by hadley** [comment]
There is one set of graticules and they are equivalent to the grid lines in Cartesian coordinations. I think it's pretty clear that the arguments that control them should belong to `coord_sf()`

**Comment by tsamsonov** [comment]
@edzer To continue a discussion on passing the parameters of `st_graticule()` to `coord_sf()`: is there any way to control the _lat_ and _lon_ values for automatically generated graticule in ggplot? Sometimes I am not satisified with the default positions of meridians and parallels, like in this plot, where I want the longitude step to be 10 degrees, not 20:

<img width="643" alt="ggplot_sf" src="https://user-images.githubusercontent.com/11613495/33803559-4f1073d0-dda4-11e7-9b06-577b6ca4f5a5.png">

**Comment by edzer** [comment]
did you try this?
```r
ggplot() + ... + scale_y_continuous(breaks = c(40,50,60))
```

**Comment by tsamsonov** [comment]
Thanks, it works! Much easier than I expected.

**Comment by edzer** [comment]
Same thing here!

**Comment by Nowosad** [comment]
There is another small thing with graticules. 
The only difference between figures is that the first one has  `+lat_0=40` and the second one - `+lat_0=39`. 
However, only the first one has that unusual line of latitude:

``` r
library(sf)
#> Linking to GEOS 3.5.0, GDAL 2.1.2, proj.4 4.9.2

st_graticule(ndiscr = 1000) %>% st_transform("+proj=laea +x_0=0 +y_0=0 +lon_0=-74 +lat_0=40 +ellps=WGS84 +no_defs") %>% st_geometry %>% plot
```

![](https://i.imgur.com/izzIRjv.png)

``` r

st_graticule(ndiscr = 1000) %>% st_transform("+proj=laea +x_0=0 +y_0=0 +lon_0=-74 +lat_0=39 +ellps=WGS84 +no_defs") %>% st_geometry %>% plot
```

![](https://i.imgur.com/KSe6gp1.png)

Created on 2018-01-19 by the [reprex
package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by edzer** [comment]
It goes away if you do e.g.
```r
st_graticule(ndiscr = 10000) %>% st_transform("+proj=laea +x_0=0 +y_0=0 +lon_0=-74 +lat_0=40.1 +ellps=WGS84 +no_defs") %>% st_geometry %>% plot
```
that is, change `lat_0` away from 40 and increase `ndiscr`. (The less you move `lat_0`, the more you need to increase `ndiscr`). 

I suspect this is not an issue with sf, but rather with approximating graticules with linestrings for particular projections with regular discretization of angles instead of focusing on where we need many points. It's very unlikely that I will work on solving this in the near future, but if someone would bring up a PR doing this I'd be happy to review.

I recall that @hadley pointed me once to a website demonstrating javascript code that did dynamic noding of graticules, but forgot where it was.
