### ISSUE TITLE
suppress specific warning message

### ISSUE THREAD

**Issue by lbusett** [r-spatial/sf#406]
Hi. Maybe this is a silly question, but is there any way to prevent `sf` from issuing the warning:
 
> "attribute variables are assumed to be spatially constant throughout all geometries", 

which I get, for example, while doing set operations on `sf` objects ? 

Thanks in advance,

Lorenzo

**Comment by edzer** [comment]
This warning comes from the fact that you are not only operating on geometries, but also on geometry attributes, and are making implicit assumptions.

You can either avoiding making this assumption and do the set operation on the object geometries, e.g. by
```r
st_intersection(st_geometry(x), st_geometry(y))
```
or make the assumption (that the attribute is constant throughout the geometry) explicit by doing
```r
st_agr(x) = "constant"
st_agr(y) = "constant"
```
before carrying out the operation (e.g. `st_intersection`) on `x` and `y`.

**Comment by lbusett** [comment]
Thanks for the answer.  

Are there any performance/speed penalties in performing set operations on the "full" sf objects instead than on geometries ? 

May I also ask, in case I'm working with geometries only, what would be the best way to "join back" the attributes table (or part of it) ? I'm asking this because it may happen that some of the attributes are indeed constant on the geometry, and can therefore be safely "kept/added back" after, e.g., an intersection or a cropping, while others are not.

**Comment by edzer** [comment]
Q1: yes, but probably negligible.
Q2: you could select those, e.g. by
```r
nc %>% select(which(st_agr(.) == "constant"))
```
or
```r
nc[, st_agr(nc) == "constant"]
```

**Comment by lbusett** [comment]
Sorry,  probably explained myself poorly.  Let's try with an example:

suppose I have an `sf` object (`in_vect_zones`), and I want to crop it on a given extent., specified by a different object (`ext_sf` in this case) If I perform an intersect on the `sf` object itself, I get something like, for example:
```
sf::st_intersection(in_vect_zones, ext_sf)
Simple feature collection with 12 features and 5 fields
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 12897990 ymin: 1685995 xmax: 12971590 ymax: 1780601
epsg (SRID):    NA
proj4string:    +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs
   id       lc_type category sup_catego mdxtnq                       geometry
1   1      forest_1   Forest Vegetation      1 POLYGON((12918415.6569245 1...
2   2      forest_2   Forest Vegetation      2 POLYGON((12903612.6960621 1...
3   3       urban_1    Other      Other      3 POLYGON((12921916.8543128 1...
```

, while if I work with geometries I get: 

```
sf::st_intersection(st_geometry(in_vect_zones), st_geometry(ext_sf))

Geometry set for 12 features 
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 12897990 ymin: 1685995 xmax: 12971590 ymax: 1780601
epsg (SRID):    NA
proj4string:    +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs
First 5 geometries:
POLYGON((12918415.6569245 1755102.58225851, 129...
POLYGON((12903612.6960621 1712373.42874566, 129...
POLYGON((12921916.8543128 1723264.60434457, 129...
POLYGON((12928524.0779807 1719705.83549906, 129...
POLYGON((12932855.0325191 1728374.45923407, 129...
```
, and I am therefore "losing" all the attributes. 

My question is therefore: after an operation like the one above done on geometries, how would I "add back" the attributes of interest from the original attributes table to the resulting geometry set ? 

(hope it is now more clear, and sorry if I'm missing something obvious)

**Comment by edzer** [comment]
`sf:::st_intersection.sf` points you to `sf:::geos_op2_df`. From there you can see that `st_intersection` on two `sfc` objects adds an attribute called `idx` to the returned geometry list-column with indexes, for each geometry, to the entries in x and y from which this geometry was formed.

**Comment by lbusett** [comment]
got it, thanks ! I didn't notice that part of the documentation, sorry. 

By the way: wouldn't it be (possibly) useful to preserve that attribute on the geometry also when the set operation is done directly on the `sfc` objects ? (just a thought)

**Comment by edzer** [comment]
It's not there: it's a property of attributes that are associated with geometry (sf), not of geometry (sfc).

**Comment by lbusett** [comment]
ok.  As mentioned, it was just a thought. I don't have a clear use case in mind for that right now. 

Thanks for your explanations. I'll close the issue.
