### ISSUE TITLE
How to convert m^2 to hectares and acres

### ISSUE THREAD

**Issue by Robinlovelace** [r-spatial/sf#413]
I've been trying to work this out for a while now, to now avail. I can see hectares and acres are supported in udunits2 but cannot seem to convert to them - have I missed something?

Reproducible attempts (I've tried others too but these are the most straightforward):

``` r
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.1.3, proj.4 4.9.2, lwgeom 2.3.2 r15302
nc <- st_read(system.file("shape/nc.shp", package = "sf"))
#> Reading layer `nc' from data source `/home/robin/R/x86_64-pc-linux-gnu-library/3.4/sf/shape/nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> epsg (SRID):    4267
#> proj4string:    +proj=longlat +datum=NAD27 +no_defs
a = st_area(nc[1, ])
a
#> 1137388604 m^2
units::set_units(x = a, value = km^2)
#> 1137.389 km^2
units::set_units(x = a, value = acre)
#> Error in stopifnot(is.character(value)): object 'acre' not found
units::set_units(x = a, value = hectare)
#> Error in stopifnot(is.character(value)): object 'hectare' not found
```

**Comment by Robinlovelace** [comment]
P.s. this relates to #291 and I'm happy to document the results if that would be useful as part of #324

**Comment by jannes-m** [comment]
units::set_units(x = a, value = ha)
This works for hectare. However, I didn't find out what the abbreviation of acre is

    # arce or something alike don't exist...
    ud_units$acre

**Comment by edzer** [comment]
These are really questions that belong [here](https://github.com/edzer/units).
```r
> units::set_units(a, units::make_unit("acre"))
281053.7 acre
```
in future versions of `units`, most likely this will also work:
```r
> units::set_units(a, "acre")
281053.7 acre
```
and maybe one day even
```r
 units::set_units(a, acre)
```
should be possible.

**Comment by Robinlovelace** [comment]
Thanks for showing how that works - I've added an issue in **units**.

**Comment by matt439miller** [comment]
Trying to use this--did the proposed 2017 fix happen?

**Comment by Robinlovelace** [comment]
Yes @matt439miller, as documented here: https://r-spatial.github.io/sf/articles/sf1.html#units

**Comment by matt439miller** [comment]
Excellent, thank you very much.
