### ISSUE TITLE
update pkgdown

### ISSUE THREAD

**Issue by mpadge** [r-spatial/sf#417]
Because all links to `github.com/edzer/sfr` are now defunct and no longer work

**Comment by edzer** [comment]
pkgdown::build_site() doesn't work, at the moment, that's the real problem.

**Comment by mpadge** [comment]
Yeah, I know that feeling. I usually have to build the individual components and manually stitch them together - a combination of `build_home()`, `build_articles()`, and `build_reference()` usually gets most of the way.

**Comment by edzer** [comment]
Thanks; I still get
```r
> pkgdown::build_reference()
Building function reference ---------------------------------------------------
Loading sf
Error: Could not find tools necessary to compile a package
```
so that has not been updated, but that is a pkgdown issue, not an sf issue. @hadley

**Comment by mpadge** [comment]
yeah, apparently it works smoothly on windows but i never get a simple `build_site()` to work on linux. workaround#2: ask someone with a windows machine to run it for you

**Comment by edzer** [comment]
It used to work up to two months ago or so.
