### ISSUE TITLE
performance of 'st_bbox' and 'st_as_sf'

### ISSUE THREAD

**Issue by nplatonov** [r-spatial/sf#418]
Loss of performance is found for 'st_bbox' (_Extract_ function) for sf>='0.5-0', however bbox is an attribute of geometry and it can be extracted in a flash.

Gain of performance is found for 'st_as_sf' (from 'data.frame' object) for sf>='0.4-0', however coercion 'data.frame' -> 'SpatialPointsDataFrame' if more time-effective than 'data.frame' -> 'sf'.

Thank you!

[bbox_timing.zip](https://github.com/r-spatial/sf/files/1145643/bbox_timing.zip)

**Comment by edzer** [comment]
Agreed, it doesn't make sense to have `st_bbox` recompute the bbox when it's already there.

**Comment by edzer** [comment]
Would be great if you could try to redo the benchmark with https://github.com/r-spatial/sf/commit/69b20e27b02a0e2022875ad953648eb5c4fd06e8, it tries to reduce recomputations.

**Comment by nplatonov** [comment]
Now, performance for 'st_box' is OK. Sub-issue for 'st_as_sf' can be closed at this time. Thank you.


[bbox_timing-2.zip](https://github.com/r-spatial/sf/files/1164423/bbox_timing-2.zip)

**Comment by edzer** [comment]
Thanks a lot!
