### ISSUE TITLE
Bring back st_is_within_distance?

### ISSUE THREAD

**Issue by karldw** [r-spatial/sf#419]
The `st_is_within_distance` function was removed in commit 587cbc7dfc46aaec0f7a8e2cf865524967e56b53 because of changes in the GEOS C API.  Would it be possible to bring it back?
From some naïve Googling, it seems like GEOS still [includes a function](https://geos.osgeo.org/doxygen/classgeos_1_1operation_1_1distance_1_1DistanceOp.html#a99de46033e82abe54143501af7aa1266) to answer the question "is *x* within some distance of *y*?"

If you'd rather not reimplement `st_is_within_distance`, I can do a quick PR to remove the reference to it from [vignette 1](https://github.com/r-spatial/sf/blob/master/vignettes/sf1.Rmd).

**Comment by edzer** [comment]
The GEOS C API did not change, but sf changed from using the C++ API to using the C API from GEOS, which [does not offer this](https://geos.osgeo.org/doxygen/geos__c_8h_source.html). Using the C++ API caused a lot of portability troubles on WIndows and Mac osx. 

Yes, PR welcome!

**Comment by edzer** [comment]
I decided to bring `st_is_within_distance` back to sf, but for sparse matrices only. If you can hold dense matrices, you could already do
```r
st_distance(x, y) <= dist
```
to obtain the dense logical matrix; in case the dense matrix is too large to hold in memory, `st_is_within_distance` now returns you the sparse representation.
