### ISSUE TITLE
graticule not working with ggplot of world2 wrapping around longitude [0,360]

### ISSUE THREAD

**Issue by bbest** [r-spatial/sf#421]
Hi @edzer,

Thank you for the wonderful sf package! The new @hadley tidyverse paradigm applied to spatial analysis is a lifesaver, especially with huge speed improvements from [spatial indexes](http://r-spatial.org/r/2017/06/22/spatial-index.html). I noticed one little issue with ggplot2 not quite working  as anticipated with the Pacific-centric world2 (longitude of [0,360] vs [-180,180]):

```r
library(ggplot2)
library(maps)
devtools::install_github('r-spatial/sf')
library(sf) 

wrld2 = st_as_sf(map('world2', plot=F, fill=T))
ggplot() +
  geom_sf(data=wrld2, fill='lightgray') +
  coord_sf(xlim=c(140,295), ylim=c(5,60))
````

![image](https://user-images.githubusercontent.com/2837257/28239014-d8a3ee50-6915-11e7-9b9c-cfea8bb2e7eb.png)

There's a problem with the graticules disappearing. Solution forthcoming...

**Comment by bbest** [comment]
Just sent pull request https://github.com/r-spatial/sf/pull/422 with the fix...

```r
library(ggplot2)
library(maps)
devtools::install_github('bbest/sf')
library(sf)

wrld2 = st_as_sf(map('world2', plot=F, fill=T))
ggplot() +
  geom_sf(data=wrld2, fill='lightgray') +
  coord_sf(xlim=c(140,295), ylim=c(5,60))
```

![image](https://user-images.githubusercontent.com/2837257/28239044-423f962e-6917-11e7-9100-2cb284aa6662.png)

**Comment by edzer** [comment]
Great work, thanks!
