### ISSUE TITLE
Provide unnest method?

### ISSUE THREAD

**Issue by karldw** [r-spatial/sf#426]
It'd be nice to use `tidyr::unnest` for list columns in `sf` objects, but `unnest` can only handle one list column per dataframe.  The `geometry` column is already a list column, so `unnest` breaks when I try to `unnest` another list column.
(Maybe I should just raise this in the `tidyr` repo; if it supported unnesting data that contained multiple list columns, it wouldn't be an issue.)
```r
library(tidyr)
library(dplyr)
library(sf)

# Make nc with an additional list column:
nc <- st_read(system.file("shape/nc.shp", package = "sf")) %>% 
    mutate(list_col = lapply(AREA, rep_len, length.out = 2))

nc %>% st_set_geometry(NULL) %>% unnest(list_col)  # works for geometry-less version
nc %>% unnest(list_col)                            # fails

```

**Comment by edzer** [comment]
Yes, I'm afraid this is a limitation of `unnest`.
