### ISSUE TITLE
compatibility with data.table library

### ISSUE THREAD

**Issue by rafapereirabr** [r-spatial/sf#428]
I wonder if it would be possible to make `sf` compatible with the `data.table` library. The library data.table is one of the most efficient ways to manipulate data.frames just as sf is for spatial objects, so it sounds like good idea to bring together the power of both libraries.

I've created an issue in the data.table github page [#2273](https://github.com/Rdatatable/data.table/issues/2273), but I thought it would be a good idea to open this issue here as well since the compatibility between the two libraries might request a bit of collaboration from both sides.

**Comment by edzer** [comment]
Maybe look at https://github.com/r-spatial/discuss/issues/15 and https://github.com/SymbolixAU/spatialdatatable. Closing here, in lack of any activity. Please reopen when something/someone moves.

**Comment by edzer** [comment]
See also https://github.com/r-spatial/mapview/issues/116 and the twitter discussion mentioned there

**Comment by nilescbn** [comment]
@edzer I'm wondering if this post by Matt Dowle amounts to the type of movement you were looking for in your Oct 19, 2017 posting?: 

https://github.com/Rdatatable/data.table/issues/2273#issuecomment-459826182

By asking the question, you can tell I'm not following the details of the issues here. I'm just a user who would really like to use sf and data.table together (an appreciative user to all you who create and maintain these fantastic packages). Thank you!
