### ISSUE TITLE
User friendliness of st_join() + aggregate/summarise

### ISSUE THREAD

**Issue by Robinlovelace** [r-spatial/sf#429]
I was using `st_join()` happily in my research but it now seems not to work... The error message says to use `aggregate()` instead. It's been a while since I used aggregate so I may be making a silly mistake, but I could not get it to work, e.g. as illustrated below:

``` r
library(raster)
#> Loading required package: sp
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
r = raster(ncol = 3, nrow = 3)
pol = st_as_sf(r)  # another issue?
#> Error in UseMethod("st_as_sf"): no applicable method for 'st_as_sf' applied to an object of class "c('RasterLayer', 'Raster', 'BasicRaster')"
pol_sp = as(r, "SpatialPolygonsDataFrame")
pol = st_as_sf(pol_sp)
plot(pol)
set.seed(5)
p = st_sample(x = pol, size = 20)
#> although coordinates are longitude/latitude, it is assumed that they are planar
p = st_sf(value = runif(20), p)
points(p)  # another issue?
#> Error in data.matrix(x): (list) object cannot be coerced to type 'double'
plot(p, add = TRUE)
```

![](http://i.imgur.com/bbbnYg4.png)

``` r
st_join(pol, p)
#> although coordinates are longitude/latitude, it is assumed that they are planar
#> Simple feature collection with 21 features and 2 fields
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: -180 ymin: -90 xmax: 180 ymax: 90
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#> First 20 features:
#>     layer      value                       geometry
#> 1      NA 0.81607607 POLYGON((-180 90, -60 90, -...
#> 1.1    NA 0.63280343 POLYGON((-180 90, -60 90, -...
#> 2      NA         NA POLYGON((-60 90, 60 90, 60 ...
#> 3      NA 0.06850976 POLYGON((60 90, 180 90, 180...
#> 4      NA 0.38457694 POLYGON((-180 30, -60 30, -...
#> 4.1    NA 0.92199057 POLYGON((-180 30, -60 30, -...
#> 4.2    NA 0.38116266 POLYGON((-180 30, -60 30, -...
#> 5      NA 0.76014253 POLYGON((-60 30, 60 30, 60 ...
#> 5.1    NA 0.25556407 POLYGON((-60 30, 60 30, 60 ...
#> 5.2    NA 0.19688638 POLYGON((-60 30, 60 30, 60 ...
#> 6      NA 0.23519875 POLYGON((60 30, 180 30, 180...
#> 6.1    NA 0.54979473 POLYGON((60 30, 180 30, 180...
#> 6.2    NA 0.25748370 POLYGON((60 30, 180 30, 180...
#> 6.3    NA 0.13640090 POLYGON((60 30, 180 30, 180...
#> 7      NA 0.53347593 POLYGON((-180 -30, -60 -30,...
#> 7.1    NA 0.92894271 POLYGON((-180 -30, -60 -30,...
#> 7.2    NA 0.93303384 POLYGON((-180 -30, -60 -30,...
#> 8      NA 0.56627268 POLYGON((-60 -30, 60 -30, 6...
#> 8.1    NA 0.97587761 POLYGON((-60 -30, 60 -30, 6...
#> 9      NA 0.82687025 POLYGON((60 -30, 180 -30, 1...
st_join(pol, p, FUN = mean)
#> Warning: 'st_join' is deprecated.
#> Use 'aggregate' instead.
#> See help("Deprecated")
#> Error in st_join(pol, p, FUN = mean): for aggregation/summarising after st_join, see examples in ?st_join
aggregate(x = p["value"], by = pol, FUN = mean)
#> Error in sort.list(y): 'x' must be atomic for 'sort.list'
#> Have you called 'sort' on a list?
```

**Comment by Robinlovelace** [comment]
Another example, from `?aggregate.Spatial`:

``` r
library(sp)
data("meuse")
coordinates(meuse) = ~x + y
ab = gUnaryUnion(as(meuse.grid, "SpatialPolygons"), meuse.grid$part.a)
#> Error in gUnaryUnion(as(meuse.grid, "SpatialPolygons"), meuse.grid$part.a): could not find function "gUnaryUnion"
plot(ab)
#> Error in plot(ab): object 'ab' not found
plot(meuse, add = T)
#> Error in plot.xy(xy.coords(x, y), type = type, ...): plot.new has not been called yet
aggregate(meuse[c("zinc", "copper")], ab, mean)
#> Error in is(by, "Spatial"): object 'ab' not found

# in sf
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
ab_sf = st_as_sf(ab)
#> Error in st_as_sf(ab): object 'ab' not found
m_sf = st_as_sf(meuse)
aggregate(m_sf[c("zinc", "copper")], ab_sf, mean)
#> Error in split.default(st_geometry(x), by): object 'ab_sf' not found
```

**Comment by Robinlovelace** [comment]
P.s. I suspect this is linked to another issue: https://github.com/tidyverse/dplyr/issues/2978

**Comment by Robinlovelace** [comment]
Ah OK I think I've figured out the first issue. I think it would be good to save some kind of aggregation index as a column in the output of `st_join()`, to avoid the bodged use of `strtrim()` below - any suggestions how to make this neater?

```r
st_join(pol, p) %>%
  mutate(id = strtrim(row.names(.), 1)) %>% 
  group_by(id) %>% 
  summarise(value = mean(value))
```

**Comment by Robinlovelace** [comment]
While it's fresh in my head: I'm using `st_join()` on some moderately large datasets with lots of vertices. I suspect that `st_join()` is copying the `geometry` column of `x` `nrow(y)` times which makes the operation very slow. Not sure that's happening, could put together a reproducible example. Sorry this issue is not clear btw - perhaps it should be called 'usability / documentation issues with st_join()' or something like that.

**Comment by edzer** [comment]
It might be less confusing if you would not do the thinking in the github issue, but only write the outcome of it. You made a false assumption that `sf::aggregate` and `sp::aggregate` both accept spatial objects for `by`.

**Comment by Robinlovelace** [comment]
Probably. The changes in this issue reflect my growing understanding of the issue, hence the change of name. I could close this issue and create a new one with only the outcome. Will mull more before posting next time.

In the meantime I still think there is room for improvement in `st_join()` and certainly its documentation which I'm happy to help with.

**Comment by Robinlovelace** [comment]
Regarding `aggregate()` methods I'm looking at `?sf:::aggregate.sf` now and see that `by` does not take spatial objects. That wasn't my assumption. I was testing different ways that someone with some knowledge of **sp** may try while trying to aggregate the attributes of one spatial object (e.g. `p` in the example above) by another (e.g. `pol`).

**Comment by Robinlovelace** [comment]
I've given this some more thought and have a more succinct version of the question: can the following example be written more concisely?

```r
library(raster)
library(sf)
r = raster(ncol = 3, nrow = 3)
pol_sp = as(r, "SpatialPolygonsDataFrame")
pol = st_as_sf(pol_sp)
set.seed(5)
p = st_sample(x = pol, size = 20)
p = st_sf(value = runif(20), p)
p_joined = st_join(pol, p)
p_joined$group = strtrim(row.names(p_joined), 1)
dplyr::summarise(dplyr::group_by(p_joined, group), mean(value))
#> Simple feature collection with 9 features and 2 fields
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: -180 ymin: -90 xmax: 180 ymax: 90
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#> # A tibble: 9 x 3
#>   group `mean(value)`          geometry
#>   <chr>         <dbl>  <simple_feature>
#> 1     1    0.72443975 <POLYGON((-18...>
#> 2     2            NA <POLYGON((-60...>
#> 3     3    0.06850976 <POLYGON((60 ...>
#> ...
#> 9     9    0.81023979 <POLYGON((60 ...>
```

**Comment by edzer** [comment]
I would have assigned
```r
pol$group = 1:9
```
before the call to `st_join`, to avoid messing with `strrim` and `row.names`. I don't know whether that was what you had in mind.

**Comment by Robinlovelace** [comment]
I had in mind a generic method that would capture the grouping of `x` in a column to reduce the number of steps needed to arrive at the solution. I think it would be beneficial to users, especially novices, to have a function that did this internally, as previous versions `st_join()` did.

**Comment by Robinlovelace** [comment]
For the benefit of clarity, I'll make this issue just about usability. Can always open another one on performance, which I've not demonstrated yet.

**Comment by edzer** [comment]
Try:
```r
m_sf %>% group_by(grp = unlist(st_intersects(m_sf, ab_sf))) %>% summarize(m = mean(zinc))
aggregate(m_sf[c("zinc", "copper")], list(unlist(st_intersects(m_sf, ab_sf))), mean)
```
This give you `MULTIPOINT` geometries, which I believe is a good thing (TM). Having to copy them over to the polygon will make the user realize what she/he is doing. Also, this will fail if the polygons overlap, and points are covered by more than one polygon. This is also a problem of the user, not of the software.

**Comment by Robinlovelace** [comment]
Nice. Should I document this somewhere? Very useful to have reproducible examples like that.

**Comment by Robinlovelace** [comment]
But also think there is scope for doing all that in one function call, unless there are unforseen costs of doing that that outweigh the user friendliness benefits for novice users.

**Comment by edzer** [comment]
I gave two reasons why I don't think that this should be in `sf`'s scope.

**Comment by Robinlovelace** [comment]
Ah OK. And re documentation?

**Comment by edzer** [comment]
Vignette 4. Manipulating simple features.

**Comment by Robinlovelace** [comment]
Cheers. I think people wanting to do this will also look at `?aggregate.sf()` and the depreciated `?st_join()`. Can put in a link to `vignette("sf4")` in the former and maybe an example or too so it's well documented and user friendly.

**Comment by Robinlovelace** [comment]
Just checked sf4 and it does not seem to exist yet. So re-opening as reminder to people (myself included) that this needs to be documented.

**Comment by Robinlovelace** [comment]
Good stuff - all present and correct for now. Hope to find time to work on `sf4` btw so let me know if you're planning to push a draft of it soon.

**Comment by Robinlovelace** [comment]
Another use case that I cannot figure out: how would one do this if each object in `x` intersects with multiple objects in `y`?

Here's an example, building on the `meuse` one above:

```r
m_sf = st_buffer(m_sf, dist = 100)
m_sf %>% group_by(grp = unlist(st_intersects(m_sf, ab_sf))) %>% summarize(m = mean(zinc))
## Error in mutate_impl(.data, dots) : 
##   Column `grp` must be length 155 (the number of rows) or one, not 165
```

This happens in my use case where we're trying to find the 'busyness' of different routes through a complex route network.

**Comment by Robinlovelace** [comment]
This seems to be a solution:

```r
sel_intersects = st_intersects(m_sf, ab_sf)
sapply(sel_intersects, function(x) mean(m_sf[x,]$zinc))
```

Potential material for the vignette in any case.

**Comment by edzer** [comment]
As I said [above](https://github.com/r-spatial/sf/issues/429#issuecomment-316363199): "Also, this will fail if the polygons overlap, and points are covered by more than one polygon. This is also a problem of the user, not of the software."

This is not something that `group_by` or `aggregate` can, or should do, but we might come up with a new verb that'd make this simpler. Can you give a small reprex?

**Comment by Robinlovelace** [comment]
Sure. I think there's merit in creating bigger ones to test performance but here's a starter:

**Comment by Robinlovelace** [comment]
``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
library(sp)
library(rgeos)
#> rgeos version: 0.3-23, (SVN revision 546)
#>  GEOS runtime version: 3.5.0-CAPI-1.9.0 r4084 
#>  Linking to sp version: 1.2-4 
#>  Polygon checking: TRUE
data("meuse")
coordinates(meuse) = ~x + y
data("meuse.grid")
coordinates(meuse.grid) <- ~x + y
gridded(meuse.grid) <- TRUE
ab = gUnaryUnion(as(meuse.grid, "SpatialPolygons"), meuse.grid$part.a)
# in sf
ab_sf = st_as_sf(ab)
m_sf = st_as_sf(meuse)
m_sf = st_buffer(m_sf, dist = 100)
sel_intersects = st_intersects(m_sf, ab_sf)
```

**Comment by Robinlovelace** [comment]
And here's the solution using the depreciated version of `st_join()`:

```r
source("https://raw.githubusercontent.com/r-spatial/sf/752c12eae34efe734d70ebbc420b99d90cbcc5ef/R/join.R")
st_join(ab_sf, m_sf["zinc"], FUN = mean)
```

```
Simple feature collection with 2 features and 3 fields
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 178440 ymin: 329600 xmax: 181560 ymax: 333760
epsg (SRID):    NA
proj4string:    NA
  mean_zinc Group.1     zinc                       geometry
1  433.9048       1 433.9048 POLYGON((180720 330120, 180...
2  498.3462       2 498.3462 POLYGON((180920 331880, 180...
```

**Comment by edzer** [comment]
As in `sp`, the syntax is again
```r
st_aggregate(m_sf["zinc"], ab_sf, mean)
```
