### ISSUE TITLE
Drivetime Polygons [Feature Request]

### ISSUE THREAD

**Issue by ben519** [r-spatial/sf#439]
For me it'd be very useful to have the ability to have the ability to generate drive-time polygons using `sf`.  For example, "show me all locations reachable within M minutes of (X,Y)".  Not sure how you would do it, but I know it [exists for ArcGIS](http://server.arcgis.com/en/server/latest/publish-services/linux/gp-service-example-drivetime-polygons.htm).  I'm curious to see if other people want this, or if I'm one of very few people for which this would be useful.

**Comment by edzer** [comment]
I can see this would be nice, but am not so sure it belongs in a simple features package. @Robinlovelace is this sth that is of interest to https://github.com/Robinlovelace/stplanr/ ?

**Comment by Robinlovelace** [comment]
Yes very much so and we could already produce such polygons by sending multiple requests to internal routing via the `SpatialLinesNetwork` class or one of the routing APIs support by stplanr. We haven't implemented any methods/APIs for generating such 'isochrone' polygons yet though.

I tend to agree that this feature does not belong in **sf**. A couple of links that may be of use/interest:

- Link to function that does this via OSRM: https://www.rdocumentation.org/packages/osrm/versions/3.0.0/topics/osrmIsochrone
- Demo of producing accessibility indicator with R: https://github.com/ITSLeeds/SSPA/blob/master/accessability.Rmd
- Demo of the isochrone API in Graphhopper (Mapzen also has one): https://graphhopper.com/api/1/docs/isochrone/

**Comment by Robinlovelace** [comment]
P.s. here is an implementation in R - showing a related concept of 'travel watershed' or 'network catchment' which is analogous to your 'drivetime' (or walktime / cycletime) polygon:

``` r
library(stplanr)
#> Loading required package: sp
data_dir <- system.file("extdata", package = "stplanr")
unzip(file.path(data_dir, "smallsa1.zip"))
unzip(file.path(data_dir, "testcycleway.zip"))
sa1income <- rgdal::readOGR(".", "smallsa1")
#> OGR data source with driver: ESRI Shapefile 
#> Source: ".", layer: "smallsa1"
#> with 638 features
#> It has 19 fields
#> Integer64 fields read as strings:  OBJECTID_1
testcycleway <- rgdal::readOGR(".", "testcycleway")
#> OGR data source with driver: ESRI Shapefile 
#> Source: ".", layer: "testcycleway"
#> with 2 features
#> It has 2 fields
#> Integer64 fields read as strings:  id
# Remove unzipped files
file.remove(list.files(pattern = "^(smallsa1|testcycleway).*"))
#> [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
catch800m <- calc_catchment(polygonlayer = sa1income, targetlayer = testcycleway, 
  calccols = c("Total"), distance = 800, projection = "austalbers", dissolve = TRUE)
plot(sa1income, col = "light grey")
plot(catch800m, col = rgb(1, 0, 0, 0.5), add = TRUE)
plot(testcycleway, col = "green", add = TRUE)
```

![](http://i.imgur.com/A7qS2ER.png)

``` r
unzip(file.path(data_dir, "sydroads.zip"))
sydroads <- rgdal::readOGR(".", "roads")
#> OGR data source with driver: ESRI Shapefile 
#> Source: ".", layer: "roads"
#> with 4451 features
#> It has 7 fields
#> Integer64 fields read as strings:  osm_id
file.remove(list.files(pattern = "^(roads).*"))
#> [1] TRUE TRUE TRUE TRUE TRUE
sydnetwork <- SpatialLinesNetwork(sydroads)
netcatch800m <- calc_network_catchment(sln = sydnetwork, polygonlayer = sa1income, 
  targetlayer = testcycleway, calccols = c("Total"), maximpedance = 800, distance = 100, 
  projection = "austalbers")
#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices

#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices

#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices

#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices

#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices

#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices

#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices

#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices

#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices

#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices

#> Warning in .Call("R_igraph_get_shortest_paths", graph,
#> as.igraph.vs(graph, : At structural_properties.c:4517 :Couldn't reach some
#> vertices
plot(sa1income, col = "light grey")
plot(catch800m, col = rgb(1, 0, 0, 0.5), add = TRUE)
plot(netcatch800m, col = rgb(0, 0, 1, 0.5), add = TRUE)
plot(testcycleway, col = "green", add = TRUE)
```

![](http://i.imgur.com/UkLLY7W.png)

**Comment by Robinlovelace** [comment]
Source: https://cran.r-project.org/web/packages/stplanr/vignettes/stplanr-paper.html

**Comment by Robinlovelace** [comment]
On a related note, we're on a mission to transition **stplanr** to support **sf** via generic methods. Anyone interested or wanting to help, check out the sfr branch: https://github.com/ropensci/stplanr/tree/sfr

**Comment by ben519** [comment]
Thanks guys.  Having thought about this more, I totally agree it doesn't belong in `sf`.  Closing this out.
