### ISSUE TITLE
Issue when using facet_grid

### ISSUE THREAD

**Issue by fzenoni** [r-spatial/sf#440]
When trying to use `facet_grid` for a specific dataset, I obtain the following error:
```
Error in CPL_gdal_dimension(st_geometry(x), NA_if_empty) : 
  impossible classs in get_dim_sfc()
```
The only reference I could find with Google points me to https://github.com/r-spatial/sf/blob/master/src/wkb.cpp#L754
To reproduce it I will go through some of the same steps as  https://github.com/r-spatial/sf/issues/435
```
library(osmdata)
library(sf)
library(magrittr)
library(ggplot2)
library(dplyr)
 
region_of_interest <- 'Lisbon'
admn_lvl <- '7' 
bbox_roi <- opq(bbox = region_of_interest)
admn_roi <- bbox_roi %>%
     add_osm_feature(key = 'admin_level', value = admn_lvl) %>%
     osmdata_sf(quiet = FALSE)
city <- admn_roi$osm_multipolygons
city <- st_make_valid(city)
city <- city["name"]

## Now I add a group column to enable faceting
city <- mutate(city, group = "foo")
city[2, "group"] <- "bar"
ggplot() + geom_sf(data = city) + facet_grid(~group)
```
The last line should provide the error indicated above.
You can try for another city (e.g. Porto) and the error will not occur. Maybe it has something to do with the presence of a `GEOMETRYCOLLECTION` in the Lisbon dataframe.

**Comment by edzer** [comment]
Indeed,
```r
ggplot() + geom_sf(data = st_cast(city, "MULTIPOLYGON")) + facet_grid(~group)
```
works, with a warning: you need to clean up possible problems cased by invalid geometries yourself.

**Comment by fzenoni** [comment]
Thank you.
It might be more of a `ggplot2` issue, but I experience another problem with `facet_grid` (and `facet_wrap`). Using again the Lisbon dataset, I would like to add a point in each facet:
```
## Defining a simple data.frame
p <- data.frame(x = 9, y = 38.7)
p <- st_as_sf(p, coords = c("x", "y"))
st_crs(p) <- 4326
ggplot() + geom_sf(data = st_cast(city, "MULTIPOLYGON")) + facet_grid(~group) + geom_sf(data = p)
```
gives the error:
```
Error in `[.default`(data, order(data$PANEL), , drop = FALSE) : 
  incorrect number of dimensions
```

**Comment by edzer** [comment]
it works if `p` actually has an attribute:
```r
p$x = 3
```

**Comment by fzenoni** [comment]
Thanks for the fix. The inconsistency of this error makes it dangerous though.

**Comment by edzer** [comment]
Now works for `p` without attribute.
