### ISSUE TITLE
st_write exports GeoJSON with ANSI encoding on Windows

### ISSUE THREAD

**Issue by dpprdan** [r-spatial/sf#444]
`st_write` (sometimes) exports GeoJSON with ANSI encoding on Windows. According to the [spec](https://tools.ietf.org/html/rfc7159#section-8.1) the default should be UTF-8.

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
# Don't know a better way to show the file encoding within R
guess_encoding <- readr::guess_encoding

write_guess <- function(){
    dsn <- "nc.geojson"
    write_sf(nc, dsn = dsn, delete_dsn = TRUE)
    guess_encoding(dsn)
}

nc <- read_sf(system.file("shape/nc.shp", package="sf"),
              options = "ENCODING=UTF-8")
write_guess()
#> # A tibble: 1 x 2
#>   encoding confidence
#>      <chr>      <dbl>
#> 1    ASCII          1
```

This shows up as ANSI in Notepad++

``` r
nc$x <- "Münster"
write_guess()
#> # A tibble: 2 x 2
#>     encoding confidence
#>        <chr>      <dbl>
#> 1 ISO-8859-1       0.32
#> 2 ISO-8859-9       0.23
```

Still showing up as ANSI. Better if we encode it as UTF-8?

``` r
nc$x <- enc2utf8(nc$x)
write_guess()
#> # A tibble: 3 x 2
#>     encoding confidence
#>        <chr>      <dbl>
#> 1      UTF-8       1.00
#> 2 ISO-8859-1       0.32
#> 3 ISO-8859-9       0.23
```

Yes! What about factor vars?

``` r
nc$y <- as.factor("Malmö")
write_guess()
#> # A tibble: 2 x 2
#>     encoding confidence
#>        <chr>      <dbl>
#> 1 ISO-8859-1       0.32
#> 2 ISO-8859-9       0.23
```

Back to ⬛️1

``` r
nc$y <- as.character(nc$y)
nc$y <- enc2utf8(nc$y)
write_guess()
#> # A tibble: 3 x 2
#>     encoding confidence
#>        <chr>      <dbl>
#> 1      UTF-8       1.00
#> 2 ISO-8859-1       0.32
#> 3 ISO-8859-9       0.23
```

Better. But what if we add "special" characters like en-dash and a Euro Sign?

``` r
nc$z <- "100,– €"
nc[[1,"z"]]
#> [1] "100,<U+0096> <U+0080>"
nc$z <- enc2utf8(nc$z)
write_guess()
#> # A tibble: 3 x 2
#>       encoding confidence
#>          <chr>      <dbl>
#> 1        UTF-8       1.00
#> 2 windows-1252       0.31
#> 3 windows-1254       0.23
nc[[1,"z"]]
#> [1] "100,<U+0096> <U+0080>"
```

File encoding is right, char encoding wrong. I'm not 100% sure, though, that the latter is due to sf. 

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.1 (2017-06-30)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2017-07-28
#> Packages -----------------------------------------------------------------
#>  package   * version date       source                       
#>  backports   1.1.0   2017-05-22 CRAN (R 3.4.0)               
#>  base      * 3.4.1   2017-06-30 local                        
#>  compiler    3.4.1   2017-06-30 local                        
#>  datasets  * 3.4.1   2017-06-30 local                        
#>  DBI         0.7     2017-06-18 CRAN (R 3.4.1)               
#>  devtools    1.13.2  2017-06-02 CRAN (R 3.4.0)               
#>  digest      0.6.12  2017-01-27 CRAN (R 3.3.2)               
#>  evaluate    0.10    2016-10-11 CRAN (R 3.3.1)               
#>  graphics  * 3.4.1   2017-06-30 local                        
#>  grDevices * 3.4.1   2017-06-30 local                        
#>  grid        3.4.1   2017-06-30 local                        
#>  hms         0.3     2016-11-22 CRAN (R 3.3.2)               
#>  htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)               
#>  knitr       1.16    2017-05-18 CRAN (R 3.4.0)               
#>  magrittr    1.5     2014-11-22 CRAN (R 3.2.2)               
#>  memoise     1.1.0   2017-04-21 CRAN (R 3.4.0)               
#>  methods   * 3.4.1   2017-06-30 local                        
#>  R6          2.2.2   2017-06-17 CRAN (R 3.4.1)               
#>  Rcpp        0.12.12 2017-07-15 CRAN (R 3.4.1)               
#>  readr       1.1.1   2017-05-16 CRAN (R 3.4.0)               
#>  rlang       0.1.1   2017-05-18 CRAN (R 3.4.0)               
#>  rmarkdown   1.6     2017-06-15 CRAN (R 3.4.1)               
#>  rprojroot   1.2     2017-01-16 CRAN (R 3.3.2)               
#>  sf        * 0.5-3   2017-07-28 Github (r-spatial/sf@728d261)
#>  stats     * 3.4.1   2017-06-30 local                        
#>  stringi     1.1.5   2017-04-07 CRAN (R 3.4.0)               
#>  stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)               
#>  tibble      1.3.3   2017-05-28 CRAN (R 3.4.0)               
#>  tools       3.4.1   2017-06-30 local                        
#>  udunits2    0.13    2016-11-17 CRAN (R 3.3.2)               
#>  units       0.4-5   2017-06-15 CRAN (R 3.4.1)               
#>  utils     * 3.4.1   2017-06-30 local                        
#>  withr       1.0.2   2016-06-20 CRAN (R 3.3.1)               
#>  yaml        2.1.14  2016-11-12 CRAN (R 3.3.2)
```

</details>

**Comment by dpprdan** [comment]
The Euro sign/en-dash problem is not due to sf but a problem in base R on Windows with CP1252 locale. So changing the encoding character and factor columns to UTF-8 should suffice to fix this, I suppose.

**Comment by edzer** [comment]
Thanks!

**Comment by dpprdan** [comment]
Sorry, this might be a misunderstanding, but IMHO the following remains a problem.

``` r
library("sf")
#> Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
library("readr")

x_sf <- st_sf(x="Münster", st_sfc(st_point(1:2)))
write_sf(x_sf, dsn = "x.geojson", delete_dsn = TRUE)
guess_encoding("x.geojson")
#> # A tibble: 1 x 2
#>     encoding confidence
#>        <chr>      <dbl>
#> 1 ISO-8859-1       0.39
```

I.e. x.geojson is not encoded as UTF-8. I would suggest having `st_write` change the encoding of all character and factor variables to "UTF-8" before writing to geojson.

**Comment by edzer** [comment]
Please check this commit, I believe I don't have access to non-UTF-8 machines.

**Comment by dpprdan** [comment]
Sorry, this does not change anything yet, i.e. the output from my [little example](https://github.com/r-spatial/sf/issues/444#issuecomment-326038428) is the same. 

If I see correctly, you only changed the `set_utf8` function. And this is only used in `st_read()`, correct? But the problem here is with `st_read()`. 

Also, you are using `Encoding(x) = "UTF-8"` in `set_utf8()`, which AFAIK only declares the encoding of a character string but does not convert it to UTF-8. The former (declaring) is excellent for `st_read()` (see #5) while the latter (conversion) is necessary for `st_write()` IMO. 

So I would suggest using `set_utf8()` only for imports and adding `if (is.character(x)); x = enc2utf8(x)` to `st_write()` somewhere after `factorsAsCharacter`. Plus possibly `names(obj)` = enc2utf8(names(obj))`

**Comment by dpprdan** [comment]
Could this also be an issue for `st_write_db`? So maybe add `if (is.character(x)); x = enc2utf8(x)` at the end of `clean_columns`?

**Comment by edzer** [comment]
I don't know whether all databases require UTF-8 strings.

**Comment by dpprdan** [comment]
Sorry if this was premature, but I took a look at your changes in a7904f1c5a6e3dd21a77beb62c39040bc2ae18f7. 
The good news: GeoJSON is now exported with UTF-8 encoding:

``` r
library("sf")
#> Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
library("readr")

x_sf <- st_sf(x="Münster", st_sfc(st_point(1:2)))
temp <- tempfile(fileext = ".geojson")
write_sf(x_sf, temp, delete_dsn = TRUE)
guess_encoding(temp) 
#> # A tibble: 3 x 2
#>     encoding confidence
#>        <chr>      <dbl>
#> 1      UTF-8       0.80
#> 2 ISO-8859-1       0.46
#> 3 ISO-8859-2       0.28
```

The bad news: `x = enc2utf8(x)` in `set_utf8` breaks the encoding on imports (i.e. `st_read()`). On import, strings need to be declared as UTF-8 but not converted to UTF-8 (assuming that GDAL always passes UTF-8 encoded strings to R, which seems to be the case). So that line should be reverted to `Encoding(x) = "UTF-8"`. Same goes for `levels(x) = enc2utf8(levels(x))` though I wonder whether the conditional `else if (is.factor(x))` (from 8b7b1275327a49586cfd65ce17aaa480e9ed2126) is even necessary, since `set_utf8` is called in `st_read()` before any strings are converted to factors, correct?

**Comment by edzer** [comment]
Sorry for the regression and thanks for testing. Hopefully this commit resolves this.

**Comment by dpprdan** [comment]
Looking good. Just to be on the super-safe side, I would leave the `names = to_utf8(n)` in `structure(lapply(x, to_utf8), names = to_utf8(n))` (now it's just `names = n`). 
Closed?!

**Comment by edzer** [comment]
That should be redundant after line 3:
```
	Encoding(n) = "UTF-8"
```

**Comment by dpprdan** [comment]
Haha, yes, I missed that. 
Thanks a lot (for this and `sf` in general).
