### ISSUE TITLE
support `+units=mi` and all other proj.4 distance units

### ISSUE THREAD

**Issue by waynefoltaERI** [r-spatial/sf#446]
When using `st_distance`, I get an error:

```
Error in crs_parameters(st_crs(x)) : 
  unknown unit: please file an issue at http://github.com/r-spatial/sf/
```

The proj4 string on the object is:

```
$proj4string
[1] "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.3 +lon_0=-95.8 +x_0=0 +y_0=0 +ellps=WGS84 +units=mi +no_defs"
```

This is with the latest CRAN relase. (Running on MacOS High Sierra Beta, if that matters.) Also:

```
> sf_extSoftVersion ()
   GEOS    GDAL  proj.4  lwgeom 
"3.6.1" "2.1.3" "4.9.3"      NA 
```

**Comment by edzer** [comment]
Thanks -- this is on my todo list; for now you'd have to st_transform to a crs that has `+units=m` before computing distances.

**Comment by edzer** [comment]
Looking [here](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/sf-00check.html) this doesn't seem to work for all platforms, yet.

**Comment by edzer** [comment]
Interestingly, on [cran](https://cran.r-project.org/web/checks/check_results_sf.html) the problem appears only on fedora so far: browse all the way down to the output diffs of the `units.R` test. Since I don't have fedora (and `rhub::check_on_fedora()` doesn't install sf properly), could someone with fedora (e.g. @rsbivand but no hurries) pls check the following, after CRAN installs of `sf` and `units`?
```r
sf::st_crs("+proj=aea +units=dm")$units
##  "dm"
units::make_unit("dm")
## 1 dm
```

**Comment by noerw** [comment]
A possibly related issue I discovered: The following code ran on my Fedora 26 machine, but throws on my Ubuntu 16.04 machine:
```r
point = st_point(c(0, 0))
point = st_sfc(point, crs = 3857)
st_buffer(point, set_units(12, km)) # ubuntu: 'Error: inherits(u, "units") is not TRUE'
                                    # fedora: works as expected
```
System specs:
- fedora 26, `R-3.4.1-1.fc26`, `geos-3.6.1-2.fc26`, `gdal 2.1.3-1.fc26`, `proj-4.9.3-2.fc26`, no `lwgeom`, `sf_0.5.3`
- Ubuntu 16.04, `R 3.4.1`, `GEOS 3.5.1`, `GDAL 2.1.3`, `proj.4 4.9.2`, `lwgeom 2.3.3 r15473`, `sf_0.5.3`

@edzer I can run the test above, once I get access to my fedora machine by the end of this week.

**Comment by rsbivand** [comment]
@edzer 

```
> sf::st_crs("+proj=aea +units=dm")$units
[1] "dm"
> units::make_unit("dm")
1 dm
```

On Fedora 26 (GEOS 3.6.1, GDAL 2.2.1, proj.4 4.9.3, lwgeom 2.3.2 r15302, sf 0.5-3)

```
> point = st_point(c(0, 0))
> point = st_sfc(point, crs = 3857)
> st_buffer(point, set_units(12, km))
Geometry set for 1 feature 
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: -12000 ymin: -12000 xmax: 12000 ymax: 12000
epsg (SRID):    3857
proj4string:    +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs
POLYGON((12000 0, 11983.5544170549 -628.0314749...
```

**Comment by edzer** [comment]
@rsbivand this is probably due to fedora/CRAN being still on gdal 2.0.2; sf checks the proj4string is valid using a proj.4 function, gdal doesn't recognize it and ... sets it to m. I've built in a harder check in sf, causing an error in this case.

**Comment by edzer** [comment]
@noerw could you please try once more on the ubuntu box after reinstalling package `units`?

**Comment by noerw** [comment]
I updated from units 0.4-4 to 0.4-5 on my Ubuntu machine and the error is gone

**Comment by edzer** [comment]
Thanks!
