### ISSUE TITLE
feature request: an .Rprofile setting to make plot operate only on geometry

### ISSUE THREAD

**Issue by jsta** [r-spatial/sf#457]
I frequently lock-up my R session by forgetting to limit plotting to the object geometry.

**Comment by oharac** [comment]
+1 on this...

Piggybacking for another feature request:

default method for View() of sf objects, can the geometry column be dropped (or perhaps truncated to just the geometry type, without the nested lists of vertices)?  In R Studio, when working with large polygons, clicking on the object name in the Environment window ends up hanging the session while it figures out how to display a column that cannot reasonably be examined in such a view.

Other than that, I am in total love with sf, thanks!

**Comment by edzer** [comment]
I think this is something you need to get used to.

**Comment by jsta** [comment]
Some day I will look into over-riding the default with https://github.com/goldingn/default

**Comment by edzer** [comment]
Way to go!
