### ISSUE TITLE
intersecting an sfc with 0 features causes R session crash

### ISSUE THREAD

**Issue by jsta** [r-spatial/sf#458]
The following code runs as expected:

```r
library(sf)
pts <- st_sfc(st_point(c(.5,.5)), st_point(c(1.5, 1.5)), st_point(c(2.5, 2.5)))
pol <- st_polygon(list(rbind(c(0,0), c(2,0), c(2,2), c(0,2), c(0,0))))
pol_df <- data.frame(id = 1) 
st_geometry(pol_df) <- st_sfc(pol)

(lst = st_intersects(pts, pol_df))
```

However, if a subsetting operation returns an object with zero features it causes the R session to crash if you try to use it in a subsequent `st_intersects` operation:

```r 
(pol_df <- pol_df[pol_df$id == 2,])
```

> Simple feature collection with 0 features and 1 field
bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
epsg (SRID):    NA
proj4string:    NA
[1] id       geometry
<0 rows> (or 0-length row.names)

```r
(lst = st_intersects(pts, pol_df))
```

Should there be some error handling to prevent this?

**Comment by edzer** [comment]
I don't think it should even give an error, but rather
```r
> (lst = st_intersects(pts, pol_df[pol_df$id == 2,]))
[[1]]
integer(0)

[[2]]
integer(0)

[[3]]
integer(0)
```
