### ISSUE TITLE
st_cast duplicating feature data incorrectly

### ISSUE THREAD

**Issue by davidorme** [r-spatial/sf#462]
Hello,

I've found that `st_cast` from POLYGON to MULTILINESTRING can break the connection between the data frame and the geometries. A toy example of three multipolygons with 3, 5 and 2 polygons respectively (unless the random number gods split any of them when the holes get put in).

```r
set.seed(123)
mpts <- st_sfc(st_multipoint(x = matrix(c(0,2,4,0,0,0), 3,2)),
		    st_multipoint(x = matrix(c(0,1,2,3,4,2,2,2,2,2), 5,2)),
		    st_multipoint(x = matrix(c(0,4,4,4), 2,2)))
mpol <- st_buffer(mpts, 0.3)
n <- 1000
holes <- st_multipoint(x = matrix(runif(n, -0.3, 4.3), n/2, 2))
holes <- st_buffer(holes, 0.05)
ranges <- st_difference(mpol, holes)
sf <- st_sf(data.frame(species=c('A','B','C')), ranges)

plot(sf)
```
![image](https://user-images.githubusercontent.com/9569132/29177541-cf9e0fda-7de6-11e7-8f7e-151234ef84e6.png)

If I convert that to POLYGON, then I get the ten expected polygons, labelled correctly by species.
```r
> (sf_pol <- st_cast(sf, 'POLYGON'))
Simple feature collection with 10 features and 1 field
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: -0.3 ymin: -0.3 xmax: 4.3 ymax: 4.3
epsg (SRID):    NA
proj4string:    NA
   species                       geometry
1        A POLYGON((4.3 0, 4.299588860...
2        A POLYGON((2.3 0, 2.299588860...
3        A POLYGON((0.3 0, 0.299588860...
4        B POLYGON((4.3 2, 4.299588860...
5        B POLYGON((3.3 2, 3.299588860...
6        B POLYGON((2.3 2, 2.299745480...
7        B POLYGON((1.3 2, 1.299588860...
8        B POLYGON((0.3 2, 0.299588860...
9        C POLYGON((4.3 4, 4.299588860...
10       C POLYGON((0.3 4, 0.299588860...
```
But if I cast that to MULTILINESTRING, then the labelling goes wrong: everything now belongs to species A:

```r
> (sf_mln <- st_cast(sf_pol, 'MULTILINESTRING'))
Simple feature collection with 10 features and 1 field
geometry type:  MULTILINESTRING
dimension:      XY
bbox:           xmin: -0.3 ymin: -0.3 xmax: 4.3 ymax: 4.3
epsg (SRID):    NA
proj4string:    NA
   species                       geometry
1        A MULTILINESTRING((4.3 0, 4.2...
2        A MULTILINESTRING((2.3 0, 2.2...
3        A MULTILINESTRING((0.3 0, 0.2...
4        A MULTILINESTRING((4.3 2, 4.2...
5        A MULTILINESTRING((3.3 2, 3.2...
6        A MULTILINESTRING((2.3 2, 2.2...
7        A MULTILINESTRING((1.3 2, 1.2...
8        A MULTILINESTRING((0.3 2, 0.2...
9        A MULTILINESTRING((4.3 4, 4.2...
10       A MULTILINESTRING((0.3 4, 0.2...
```
### Cause?

I think this is because the geometry ids aren't getting reset when the polygons conversion happens. The original feature counts are:
```r
> lengths(st_geometry(sf))
[1] 3 5 2
```
.. and those persist in the `ids` attributes of the POLYGON version. There are 10 features, but there are only three ids:

```r
> attr(st_geometry(sf_pol), 'ids')
[1] 3 5 2
```
When the cast to MULTILINESTRING happens, the rows of `sf_pol` are repeated using those ids: the first three rows are repeated 3,5 and 2 times, although each now represents a single polygon of species A. Because the sum of those inherited `ids` is equal to the feature count of the cast geometries, the lengths of the geom and dataframe will always match, so the error doesn't fire and the data is replicated incorrectly.

**Comment by davidorme** [comment]
The holes aren't necessary to trigger the error, I realise!

**Comment by edzer** [comment]
Well spottet! Pls check whether this commit solves the issue.

**Comment by davidorme** [comment]
Yes, this now fixes this bug. Those  examples now run as expected using:

```r
> library(sf)
Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
```
The `sf` version is:
```
GithubRepo:           sf
GithubUsername:       r-spatial
GithubRef:            master
GithubSHA1:           f34759bbc7801bc459db04594b7b8f4ece1f8651
```
However, I still get the errors reported in #461
