### ISSUE TITLE
sf and sp crs not identical.

### ISSUE THREAD

**Issue by MirzaCengic** [r-spatial/sf#467]
I'm not sure if this an issue suited to be posted here, but it might be useful.
Issue is that the proj4string is not identical when a file is loaded as a simple feature to when it's loaded as an sp object. However when converted to sp, it seems to work. Is it an issue or my misunderstanding of proj4string slot in st_crs()? Same issue happens if the file is loaded with rgdal::readOGR() instead of raster::shapefile().

```
## REPREX ----
# Get libraries
library(sf)
library(raster)
# Get file path
file_path <- system.file("shape/nc.shp", package="sf")
# As sf
nc_sf <- st_read(file_path)
st_crs(nc_sf)$proj4string
# As sp
nc_sp <- shapefile(file_path)
proj4string(nc_sp)
# Check if identical
identical(proj4string(nc_sp), st_crs(nc_sf)$proj4string)
# FALSE
nc_sf_sp <- as(nc_sf, "Spatial")
identical(proj4string(nc_sp), proj4string(nc_sf_sp))
# TRUE
```

**Comment by rsbivand** [comment]
In rgdal, sp CRS are fed through PROJ.4 to see whether the given values can be used. In doing this, expansions are applied (note that raster::shapefile() is a simplified wrapper for rgdal::readOGR() - preferably use the underlying function):

```
> st_crs(nc_sf)$proj4string
[1] "+proj=longlat +datum=NAD27 +no_defs"
> rgdal::checkCRSArgs(st_crs(nc_sf)$proj4string)[[2]]
[1] "+proj=longlat +datum=NAD27 +no_defs +ellps=clrk66 +nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat"
> proj4string(nc_sp)
[1] "+proj=longlat +datum=NAD27 +no_defs +ellps=clrk66 +nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat"
```

So they are identical after expansion - sf assumes that CRS definitions read by sf::st_read() can be digested by PROJ.4, sp does not assume this and always checks when an S4 CRS object is created (if rgdal is available).
