### ISSUE TITLE
Preserve extra geoJson properties in the Geometry 

### ISSUE THREAD

**Issue by SymbolixAU** [r-spatial/sf#472]
From [gdal.org](http://www.gdal.org/drv_geojson.html)

> Starting with GDAL 2.1, extra JSon members at the FeatureCollection, Feature or geometry levels that are not normally reflected in the OGR abstraction, [...], are by default preserved when executing ogr2ogr with GeoJSON both at the source and destination

Taking the example geoJSON from that page

```
geojson_txt <- '{
"type": "FeatureCollection",
"extra_fc_member": "foo",
"features" : 
  [
    {
      "type": "Feature",
      "extra_feat_member": "bar",
      "geometry": {
        "type": "Point",
        "extra_geom_member": "baz",
        "coordinates": [ 2, 49 ]
      },
      "properties": {
        "a_property": "foo",
        }
    }
  ]
}'
```

The `properties` objects that's outside the `geometry` is preserved when using `read_sf`, but the `extra_geom_member` value is dropped.

```
sf <- read_sf(geojson_txt)
sf
# Simple feature collection with 1 feature and 1 field
# geometry type:  POINT
# dimension:      XY
# bbox:           xmin: 2 ymin: 49 xmax: 2 ymax: 49
# epsg (SRID):    4326
# proj4string:    +proj=longlat +datum=WGS84 +no_defs
# # A tibble: 1 x 2
# a_property         geometry
# <chr> <simple_feature>
# 	1        foo   <POINT (2 49)>

sf::st_geometry(sf)
# Geometry set for 1 feature 
# geometry type:  POINT
# dimension:      XY
# bbox:           xmin: 2 ymin: 49 xmax: 2 ymax: 49
# epsg (SRID):    4326
# proj4string:    +proj=longlat +datum=WGS84 +no_defs
# POINT (2 49)
```

Is it possible to preserve extra JSON members that are nested inside the `geometry` too?

**Comment by edzer** [comment]
No, this is not possible. It is, afaict, also not part of the simple feature standard. It would require `sf` to treat GeoJSON differently from all other GDAL formats - currently all are treated equally.

**Comment by SymbolixAU** [comment]
Fair enough - happy for this to be closed

Keep up the good work on `sf` - really useful package!
