### ISSUE TITLE
Heads up - rushed GEOS 3.7.0 release ahead

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#475]
See this [thread](https://lists.osgeo.org/pipermail/geos-devel/2017-August/007995.html) - and likely further in the September folder.

**Comment by edzer** [comment]
but pretty cool it will have Frechet distance computing!

**Comment by edzer** [comment]
Working on a flexible reproducible build/test container [here](https://github.com/r-spatial/sf/tree/master/inst/docker/gdal22).

**Comment by dbaston** [comment]
No, for real this time!
https://lists.osgeo.org/pipermail/geos-devel/2018-May/008210.html
