### ISSUE TITLE
filtering with dplyr strips geometry if "sf" is not loaded

### ISSUE THREAD

**Issue by lbusett** [r-spatial/sf#477]
Hi. Don't know if this is  something unavoidable, a bug or I am missing something obvious:  

Within a script, doing something like this: 
```
aggr_data_filt <- aggr_data %>%
  dplyr::filter(avg > 0) 
```
returns a `sfc` only if I previously load `sf` using `library(sf)`. Otherwise, a tibble is returned. 

This is  troublesome while writing functions for packages because, unless I import the whole `sf` form import, I have to resort to something like: 

```
aggr_data_filt <- aggr_data %>%
  dplyr::filter(avg > 0) %>%
  sf::st_as_sf()
```
Is there any workaround for this ? Is there a way to import, for example, only the `filter.sf` method in a function ?

**Comment by edzer** [comment]
Yes, you can use `@importFrom sf filter.sf` but your package may also have to export this again; look [here](https://github.com/r-spatial/sf/blob/master/R/init.R#L14-L16) for an example how `sf` (and e.g. dplyr) do this trick with the `%>%` operator.

I think this is unavoidable and a consequence of using S3 instead of S4.

**Comment by lbusett** [comment]
Thanks for the reply.  I'll try this way, then.  I didn't think a "normal" importFrom would work since in interactive use this 

`aggr_data_filt <- aggr_data %>%
  sf::filter.sf(avg > 0)`

results in :

  ` Error in NextMethod() : 'NextMethod' called from an anonymous function`

**Comment by edzer** [comment]
This suggest you didn't load or import (filter from)`dplyr`, right? How would then your R session recognize `filter` as a generic?

**Comment by lbusett** [comment]
actually, in interactive use (I mean , from R console) this happens even with the "full" dplyr package loaded: 

```
library(dplyr)  
aggr_data_filt <- aggr_data %>%
      sf::filter.sf(avg > 0)
```
`Error in NextMethod() : 'NextMethod' called from an anonymous function`

The only way I found to have filter.sf to work thus in RStudio editor is to have `sf` loaded and use:

```
aggr_data_filt <- aggr_data %>%
    dplyr::filter(avg > 0)
```
What am I missing ?

**Comment by edzer** [comment]
So, the answer is that you'll have to load `sf` in your session when want to use `sf`'s `dplyr` methods.

To solve your issue, I guess `sf` would need to import and reexport all the corresponding `tidyverse` generics for which it provides methods, similar to what `dplyr` does with `tibble`.

**Comment by lbusett** [comment]
No problem with that now that I know it. Not knowing about the importFrom/export trick, I thought that I'd had also to load all `sf` namespace in my package just to access the filter method. 

Thanks for your time.

**Comment by edzer** [comment]
> I thought that I'd had also to load all sf namespace in my package just to access the filter method.

Indeed, with `importFrom` you can import what you need.
