### ISSUE TITLE
Converting sf to sp in rmarkdown

### ISSUE THREAD

**Issue by jsta** [r-spatial/sf#478]
I have two documents.

* An Rmd file with the following:

```r 
library(sf)
x = st_sfc(st_point(c(5,5)), st_point(c(6,9)), crs = 4326)
as(x, "Spatial")
```

* A _build_ script with the following:

```r 
knitr::knit("test.Rmd", "test.md")
```

I am able to render the rmarkdown if I run knitr interactively. However, I if run the build script with `Rscript` I get an error: 

`## Error in as(x, "Spatial"): could not find function "as"`. 

It does not seem to matter whether I set the `envir` argument to `new.env()` or `globalenv()`.

**Comment by edzer** [comment]
It is well known that `Rscript` does not load `methods`, where `R` does. Start your script with an explicit `library(methods)` if you want it to work like it does in R.

**Comment by jsta** [comment]
Gah, thanks!
