### ISSUE TITLE
st_jitter

### ISSUE THREAD

**Issue by tim-salabim** [r-spatial/sf#483]
@edzer would you consider a PR that implements `st_jitter` to jitter point coordinates which can be quite useful for points with very similar/identical coordinates (e.g. as a result of geocoding)? 
I have the code part basically ready but before writing tests and documentation I wanted to check whether such a PR would even be considered given that 
a) it only really makes sense for point data
b) you mentioned in the past that you'd like to decrease the number of `st_` functions rather than add new ones.

**Comment by edzer** [comment]
Good that you ask.  The following script
```r
library(sf)
demo(nc, ask = FALSE, echo = FALSE) 
pts = st_centroid(st_geometry(nc))
st_jitter = function(x, sd) {      
    (x + lapply(x, function(z) rnorm(n = 2, mean = 0, sd = sd))) %>%
        st_set_crs(st_crs(x))
}   
plot(pts)
plot(st_jitter(pts, .05), add = TRUE, col = 'red')
```
jitters not only points:
![j1](https://user-images.githubusercontent.com/520851/30500854-75230f06-9a60-11e7-9dfc-18b781b59466.png)
but also polygons:
```r
g = st_geometry(nc)
plot(g)
plot(st_jitter(g, .05), add = TRUE, col = '#ff8888')
```
![j2](https://user-images.githubusercontent.com/520851/30500857-7b1429c2-9a60-11e7-97d0-0d474b3f7ddb.png)
It uses the `+` operator, which loops over two lists, think of
```r
> st_sfc(st_point(c(1,1)),st_point(c(2,2))) + list(rnorm(2), rnorm(2))
Geometry set for 2 features 
geometry type:  POINT
dimension:      XY
bbox:           xmin: 2.206303 ymin: 0.3734777 xmax: 2.48458 ymax: 1.26339
epsg (SRID):    NA
proj4string:    NA
POINT (2.48457984338526 0.373477742865503)
POINT (2.20630280679368 1.26338967368383)
```
Do a twitter poll on whether `st_jitter` should be added to `sf`?

**Comment by tim-salabim** [comment]
That's quite clever! My attempt so far is wrapping `base::jitter` to any of `XYZM`
```
st_jitter.sfg = function(x, factor = 1, amount = NULL, what = "XYZM") {

  if (!inherits(x, "POINT"))
    stop("st_jitter is only implemented for point data", call. = FALSE)

  if (any(is.na(st_coordinates(x)))) return(x)

  what = match.arg(what, c("XYZM", "XYZ", "XYM", "XY", "X", "Y"))
  if (nchar(what) >= length(st_coordinates(x))) {
    st_point(jitter(st_coordinates(x), factor = factor, amount = amount))
  } else {
    coords = st_coordinates(x)
    coords[, strsplit(what, "")[[1]]] = jitter(coords[, strsplit(what, "")[[1]]])
    st_point(coords)
  }
}
```

**Comment by edzer** [comment]
`base::jitter` assumes univariate data. In your solution, AFAICT `POINT(0 90)` will get much more jitter than `POINT(0 1)`, since the `amount` is derived from the data range. `base::jitter` however does use `runif`, where my proposal used `rnorm` - another thing you might want to control. In case of longlat data, if you want circular jitter you'd have to do an [equirectangular](https://en.wikipedia.org/wiki/Equirectangular_projection) - latitude dependent - correction.

There's more to it than I initially though - I think there is a place for an `st_jitter`.

**Comment by tim-salabim** [comment]
The [twitter poll](https://twitter.com/TimSalabim3/status/908812243403452416) also seems to suggest that there are people who'd like to see this implemented.

You're right, `base::jitter` doesn't seem appropriate here. Regarding equirectangular correction of longlat data, woulnd't the error resulting from non-correction be very small compared to the jittering? Of course it all depends on the distance value supplied by the user, but can we think of any cases with jittering in the order of kilometers?

**Comment by edzer** [comment]
Depends on your latitude.

**Comment by tim-salabim** [comment]
Thanks! closing here
![jitter](https://user-images.githubusercontent.com/2826432/30511638-f15820b6-9add-11e7-97cc-47417c127dac.png)

**Comment by NateMietk** [comment]
Sorry to reopen.  Question on why you have to use `st_geometry` prior to using `st_jitter`.  In the above example I would love to instead do:

`g = st_jitter(nc, .05)`

...but I receive the following error message:

`Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 2, 1`

The reason being is that I want to retain the attribute information after the jitter, not just the polygon boundary.  As of now the output of the original command `g = st_jitter(st_geometry(nc), .05)` is now:

`Geometry set for 100 features` 
`geometry type:  MULTIPOLYGON`
`dimension:      XY`
`bbox:           xmin: -84.35604 ymin: 33.84318 xmax: -75.43918 ymax: 36.59716`
`epsg (SRID):    4267`
`proj4string:    +proj=longlat +datum=NAD27 +no_defs`
`First 5 geometries:`
`MULTIPOLYGON (((-81.48912 36.20807, -81.55721 3...`
`MULTIPOLYGON (((-81.21965 36.34481, -81.22045 3...`
`MULTIPOLYGON (((-80.4428 36.20816, -80.46284 36...`
`MULTIPOLYGON (((-76.02778 36.3459, -76.03615 36...`
`MULTIPOLYGON (((-77.2386 36.20227, -77.25555 36...`

I have now lost all of the attribute information. How can I get that back?
Thanks in advance.
