### ISSUE TITLE
feature request: update bbox/extent for sf object

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/sf#484]
This is a feature request that is between packages `sp`, `sf` and `raster`. 

Currently, running `sp::bbox()` or `raster::extent()` on a `sf` object seems to fail:

    library(sf)
    example(st_sf, echo=FALSE) # give object s
    library(sp)    
    bbox(s)

> Error in bbox(s) : object not a >= 2-column array

    library(raster)
    extent(s)

> unable to find an inherited method for function ‘extent’ for signature ‘"sf"’

 I am not sure where the change should be made between sp/sf/raster, but maybe `sf` could extend the `bbox` method for `sf` objects? Which would allow in turn to re-use the `setMethod('extent', signature(x='Spatial')` for sf objects? Or should raster just use the `st_bbox()` function?

Thanks!

**Comment by edzer** [comment]
It's quite tricky to do this all ways without creating strong(er) dependencies; I've now added `st_bbox` methods for `Spatial` and `Raster` objects, hope that helps.

**Comment by MatthieuStigler** [comment]
oh great, thanks for the added feature! I see your point about strong dependency, like adding packages in the suggests list. This mean you would be reluctant do to the converse, and have also sp::bbox work for sf?

**Comment by edzer** [comment]
Yes.

**Comment by edzer** [comment]
Another question is: if we start with `st_bbox` and `bbox`, but where would we end?
