### ISSUE TITLE
How to enable st_make_valid in sf on Windows (get sf to link to liblwgeom)

### ISSUE THREAD

**Issue by Zedseayou** [r-spatial/sf#487]
Hi all,

Apologies in advance for some probably fairly naive questions. I am working on Windows and trying to get started using `st_make_valid`. The info [here](https://github.com/r-spatial/sf) and on this [page](http://r-spatial.org/r/2017/03/19/invalid.html) indicate that `st_make_valid` needs `sf` to be installed from source, with `liblwgeom` present, for a link to happen when I call `library(sf)`.

I have not been able to figure out what is meant by having `liblwgeom` "present". I installed PostgreSQL 9.6.5 and PostGIS 2.3.3 from the instructions on this [link](http://postgis.net/windows_downloads/). I had thought that after doing this `liblwgeom` would be present, but `sf` still did not detect it. 

This info [here](https://stat.ethz.ch/pipermail/r-sig-geo/2017-March/025549.html) from March seems to suggest that a dev version of `liblwgeom` is needed, but not what that entails? Alternatively, what is meant by `sf` "detecting" `liblwgeom`? Do I need to point it somewhere in particular? This previous [issue](https://github.com/r-spatial/sf/issues/360) was the only thing I could find on getting `sf` installed with `liblwgeom` on Windows, but it did not seem to be the same issue. Is there some other major misunderstanding that I have given a lack of experience with PostGIS in the first place?

Any help would be greatly appreciated, including if this question should be directed elsewhere.

Thanks in advance.

EDIT 2 Oct:  Saw some more queries [here](https://stackoverflow.com/questions/46257928/make-st-make-valid-in-sf-package-work) and [here](http://r-sig-geo.2731867.n2.nabble.com/Compile-sf-in-windows-with-liblwgeom-td7591495.html#a7591496) on this. Attempting to get st_buffer trick to work in the meantime!

**Comment by edzer** [comment]
Compiling R packages on windows from source is not trivial if there are external dependencies, and it looks like nobody has so far sorted this out and shared it in such a way that you can carry it out like a recipe. `liblwgeom` is, like `gdal`, a "library of libraries", and hence may need some special care, compared to stand-alone libraries like proj or geos.

**Comment by tim-salabim** [comment]
I haven't had any luck so far. But for most cases the trick w `st_buffer(x, 0)` seems to work just fine.

**Comment by edzer** [comment]
Closing here, as we've split of `lwgeom` to its own R package.

**Comment by edzer** [comment]
https://twitter.com/edzerpebesma/status/928367268605591555 see appveyor button in README of the lwgeom pkg.
