### ISSUE TITLE
Conversion from sf to Spatial*DataFrame

### ISSUE THREAD

**Issue by andybega** [r-spatial/sf#494]
Is the lack of support in `as_Spatial` for any of the `sp::Spatial*DataFrame` classes intentional for some reason, or is it something that could be added? (I'm not that knowledgeable about the problems this might entail.)

I was trying to convert an `sf` object to its `sp` equivalent in order to use `maptools::snapPointsToLines`, and saw that `as_Spatial` currently only works with converting geometries to `sp::Spatial*` classes, without the data frame/attributes part. I ended up using something like this, where `from` is the `sf` object:

```
stopifnot(class(from)[1]=="sf")
stopifnot(class(st_geometry(from))[1]=="sfc_POINT")
sp::SpatialPointsDataFrame(
  do.call(rbind, st_geometry(from)),
  data = as.data.frame(from)[, setdiff(colnames(from), attr(from, "sf_column"))], 
  proj4string = CRS(attr(st_geometry(from), "crs")$proj4string)
)
```

or maybe this makes more sense:

```
sp::SpatialPointsDataFrame(
  as_Spatial(st_geometry(from)), 
  data = as.data.frame(from)[, setdiff(colnames(from), attr(from, "sf_column"))]
)
```

**Comment by rsbivand** [comment]
why not:

```
as(from, "Spatial")
```

Using whatever_whatever as meaningful is an unfortunate dialect. 

Reprex:
```
library(sf)
pts <- st_sf(a=3, st_sfc(st_point(1:2)))
sp_pts <- as(pts, "Spatial")
sp_pts
class(sp_pts)
```

**Comment by andybega** [comment]
Thank you! Do you know what the rationale is then for including `as_Spatial` in `sf`?

**Comment by edzer** [comment]
The `as(...)` form doesn't let you specify IDs for `SpatialLines` or `SpatialPolygons`; I've updated the docs to make it more clear `as_Spatial` only works for simple feature _geometries_.
