### ISSUE TITLE
create lat lon numeric columns from st_point feature /

### ISSUE THREAD

**Issue by lucasmation** [r-spatial/sf#498]
in a data.frame with a` st_point` column, how can one create additional numeric columns `lat `and `lon`?

```
demo(nc, ask = FALSE, echo = FALSE)
nc <- st_centroid(nc)

nc$lat <- .... 
nc$lon <- .... 
```

EDIT: obs: I belive in Postgis it would be something like `st_x`  and `st_y`

**Comment by edzer** [comment]
`data.frame`s can't have an `st_point` column; otherwise they work as `data.frame`s. This is not an `sf` related issue; pls read into how R works.

**Comment by lucasmation** [comment]
I understand how R works... 

Are you referring to the fact that I used the word `data.frame` instead of `sf`?  Anyway, I edited the original post with `sf` (edit2). 

Flowing [sf vignette1](https://r-spatial.github.io/sf/articles/sf1.html) I thought you could use either word interchangeably: 

```
"As attributes are typically stored in data.frame objects (or the very similar tbl_df), we will also store feature geometries in a data.frame column.

sf, the table (data.frame) with feature attributes and feature geometries, which contains"
```
in any case, how to add numeric coluns `lat` and `lon` to a `sf` object?

**Comment by karldw** [comment]
Hey @lucasmation, here's a function I wrote a while back that will probably accomplish what you want.  

```r
library(sf)
library(dplyr)

geometry_to_lonlat <- function(x) {
  if (any(sf::st_geometry_type(x) != "POINT")) {
    stop("Selecting non-points isn't implemented.")
  }
  coord_df <- sf::st_transform(x, sf::st_crs("+proj=longlat +datum=WGS84")) %>%
    sf::st_coordinates() %>%
    dplyr::as_tibble() %>%
    dplyr::select(X, Y) %>%
    dplyr::rename(lon = X, lat = Y)
  out <- sf::st_set_geometry(x, NULL) %>%
    dplyr::bind_cols(coord_df)
  return(out)
}
```



In general, I've found it easier to get answers on stackoverflow than github.  There's a whole [#sf tag](https://stackoverflow.com/questions/tagged/sf)!

**Comment by lucasmation** [comment]
@karldw tks. This works!
(for a general function, I don't think the reprojection should be included. 
This seems more natural:
`x %>% st_transform(x, sf::st_crs("+proj=longlat +datum=WGS84")) %>% geometry_to_lonlat`
)

tks

**Comment by edzer** [comment]
Sorry for my blunt earlier reply; I clearly misunderstood your question.

**Comment by lucasmation** [comment]
@edzer , no worries. I think adding functions `st_x` and `st_y` to `sf` wuold be nice

**Comment by Nowosad** [comment]
@lucasmation also take a look at https://github.com/r-spatial/sf/issues/284

**Comment by edzer** [comment]
```r
> nc = st_centroid(nc)
> st_x = function(x) st_coordinates(x)[,1]
> st_x(nc)[1:3]
        1         2         3 
-81.49823 -81.12513 -80.68573 
```
IMO, functions that trivial clobber the namespace.
