### ISSUE TITLE
read a .kml file with the KML driver: does not load the data columns?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/sf#499]
Hi

I am reading a *kml* file with `st_read`, and have the issue that it only reads the *geometry* field, as well as two empty fields *Name* and *Description*, but not the rest. Interestingly, this only happens on one machine that uses the driver *KML* (st_read gives 2 fields), but not on another machine that uses *LIBKML* (st_read gives 24 fields). 

Should I actually put specify options when using KML instead of LIBKML? Or try to have the LIBKML driver on the machine, hoping that would temporarily solve the issue?

Thanks!

    library(sf)

    nc = st_read(system.file("shape/nc.shp", package="sf"), quiet=TRUE) 
    st_write(nc, "test.kml")
    st_read("test.kml")

Output on machine that has only driver *KML*:

> Reading layer `test' from data source `/home/stigler/GIS/test.kml' using driver `KML'
> Simple feature collection with 100 features and 2 fields

Output on the other machine using driver *LIBKML*

> Reading layer `test' from data source `/home/matifou/test.kml' using driver `LIBKML'
> Simple feature collection with 100 features and 24 fields

**Comment by edzer** [comment]
My gdal installation has both,
```r
> st_drivers()[19:20,]
         name                        long_name write  copy is_raster is_vector
LIBKML LIBKML Keyhole Markup Language (LIBKML)  TRUE FALSE     FALSE      TRUE
KML       KML    Keyhole Markup Language (KML)  TRUE FALSE     FALSE      TRUE
```
and apparently libkml is the better one and automatically chosen. `st_read` doesn't let you choose a driver, so I can't try the other.

My guess is that your machine with only driver _KML_ runs windows or OSX, and comes with a gdal installation that doesn't have libkml. You'd need to recompile gdal on that machine, linked to libkml.

**Comment by MatthieuStigler** [comment]
Thanks for checking this! So I guess the problem is likely at the gdal level, or even at the KML library level? 

The machine with only KML is actually a Linux red hat 7.4 server , I'll have to speak to the admin to see what he can do. 

Thanks!

**Comment by edzer** [comment]
Yes, you can solve it by installing a better equipped gdal.

**Comment by senickel** [comment]
I tried to install LibKML on windows which did not work. My work around was to access the ExtendedData in the KML seperately and attach it to the simple feature.

``readKML<-function(file,...) {

  sp_obj<-st_read(file,...)
  xml1<-read_xml(file)

    # extract name and type of variables
  variable_names<-xml_find_first(xml1,".//d1:Schema[@name]") %>% 
    xml2::xml_contents() %>%
    xml2::xml_attrs() %>% 
    do.call(rbind,.)
  
  # return sp_obj if no ExtendedData is present
  if (is.null(variable_names)) return(sp_obj)
  
  data<-lapply(seq(nrow(variable_names)),function(x) {
    x1<-xml_find_all(xml1,paste0(".//d1:SimpleData[@name=\"",variable_names[x,1],"\"]")) %>% 
      xml_contents()  
    if (variable_names[x,2]=="string") return(xml_text(x1))
    xml_double(x1)
  }) %>% 
    do.call(cbind,.) %>% 
    as.data.frame()
  
  colnames(data)<-variable_names[,1]
  
    sp_obj[,variable_names[,1]]<-data
  sp_obj
}

**Comment by senickel** [comment]
I hope it is fine if still add into this discussion. I had a similar problem and tried to install LibKML on Windows 10 which did not work. My work around was to access the ExtendedData in the KML separately and attach it to the simple feature. I posted a similar answer for rgdal here: https://stackoverflow.com/questions/45989198/how-to-load-all-fields-extendeddata-not-just-name-and-description-from-kml/51657844#51657844


```
readKML<-function(file,...) {
  sp_obj<-st_read(file,...)
  xml1<-read_xml(file)

    # extract name and type of variables
  variable_names<-xml_find_first(xml1,".//d1:Schema[@name]") %>% 
    xml2::xml_contents() %>%
    xml2::xml_attrs() %>% 
    do.call(rbind,.)
  
  # return sp_obj if no ExtendedData is present
  if (is.null(variable_names)) return(sp_obj)
  
  data<-lapply(seq(nrow(variable_names)),function(x) {
    x1<-xml_find_all(xml1,paste0(".//d1:SimpleData[@name=\"",variable_names[x,1],"\"]")) %>% 
      xml_contents()  
    if (variable_names[x,2]=="string") return(xml_text(x1))
    xml_double(x1)
  }) %>% 
    do.call(cbind,.) %>% 
    as.data.frame()
  
  colnames(data)<-variable_names[,1]
  
    sp_obj[,variable_names[,1]]<-data
  sp_obj
}
```
