### ISSUE TITLE
Linux system GDAL is 1.11.4, is there a work around? 

### ISSUE THREAD

**Issue by aakbarie** [r-spatial/sf#500]
Hi, I work in an environment where I can't update our servers GDAL version to 2.0+, is there a way to get around this problem? Thanks

**Comment by rsbivand** [comment]
You will have to stay with the sp/rgdal implementations; rgdal builds conditioning on GDAL major version and does work with 1.11.*. Alternatively, compile GDAL 2.* and its dependencies on your system - the problem is most likely that you are thinking of binary package installs.

**Comment by aakbarie** [comment]
thank you
