### ISSUE TITLE
st_buffer not fully unit aware

### ISSUE THREAD

**Issue by botanize** [r-spatial/sf#504]
I'm having a problem with projections in units that aren't native to udunits. For example, the projection 2237 is in 'us-ft'. `sf` seems to handle this fine internally for things like `st_area`. But when I try to add a 50 ft buffer to a point in a projection in 'us-ft' I get this error:
`Error: cannot convert ft into (us-ft)`. 

```r
library(sf)
a <- st_as_sf(data.frame(lon = -80, lat = 26.7), coords = c('lon', 'lat'), crs = 4326)
a_ft <- st_transform(a, 2237)
a_m <- st_transform(a, 2778)
# This works
st_buffer(a_ft, 50)
# This fails
st_buffer(a_ft, units::set_units(50, 'ft'))
# This works
st_buffer(a_m, units::set_units(50, 'ft'))
```

So far the only way around this is to check if the projection is in 'us-ft' and if so, provide the buffer without units, if not, provide the buffer in 'ft'.
```r
st_buffer(a_ft, ifelse(st_crs(a_ft)$units == 'us-ft', 50, units::set_units(50, 'ft')))
```

**Comment by edzer** [comment]
Thanks, good catch!
