### ISSUE TITLE
Integer64List field type in GML throws "unrecognized field type" error

### ISSUE THREAD

**Issue by petrbouchal** [r-spatial/sf#508]
The issue described in #416 also relates to the Integer64List field type, which is not handled in d37c9bf52b7d19ba778bb719fb0fa5771c74024e and so currently `read_sf()` throws an "unrecognized field type" error when such a field is in the layer.

```
library(sf)
download.file("http://vdp.cuzk.cz/vymenny_format/soucasna/20170930_OB_530964_UKSH.xml.gz",
"GML_with_Int64List.tar.gz")
st_read("GML_with_Int64List.tar.gz", layer = "Parcely")
```
returns
```
Reading layer `Parcely' from data source `/Users/petr/github/experiments/GML_with_Int64List.tar.gz' using driver `GML'
Error in CPL_read_ogr(dsn, layer, as.character(options), quiet, type,  : 
  Unrecognized field type
```
I'm having trouble compiling `sf` on my machine so cannot make a pull request on this, but I suspect it is a matter of adding the OFTInteger64List to gdal_read.cpp.

Unfortunately in `rgdal` the issue is the same because `ogrInfo` does not classify the Integer64List type as a list (it only sees 5 list fields when there are 8) - which then causes `readOGR` to handle it as a non-list type, and fail.

```
rgdal::readOGR("GML_with_Int64List.tar.gz", layer = "Parcely")
```
returns 
```
OGR data source with driver: GML 
Source: "GML_with_Int64List.tar.gz", layer: "Parcely"
with 644 features
It has 22 fields, of which 5 list fields
Integer64 fields read as strings:  Id VymeraParcely IdTransakce RizeniId BonitovanyDilIdTranskace BonitovaneDilRizeniId ZpusobOchranyRizeniId 
Error in rgdal::readOGR("GML_with_Int64List.tar.gz", layer = "Parcely") : 
  unsupported field type: Integer64List

> rgdal::ogrInfo("GML_with_Int64List.tar.gz", layer = "Parcely")
Source: "GML_with_Int64List.tar.gz", layer: "Parcely"
Driver: GML; number of rows: 644 
Feature type: wkbPoint with 2 dimensions
Extent: (-688456.3 -1082942) - (-686849 -1080660)
CRS: +proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs  
Number of fields: 22 
Number of list fields: 5 
                                 name type length      typeName maxListCount
1                              gml_id    4      0        String            0
2                                  Id   12      0     Integer64            0
3                           Nespravny    4      5        String            0
4                        KmenoveCislo    0      0       Integer            0
5                    PododdeleniCisla    0      0       Integer            0
6                       VymeraParcely   12      0     Integer64            0
7               ZpusobyVyuzitiPozemku    0      0       Integer            0
8                    DruhCislovaniKod    0      0       Integer            0
9                      DruhPozemkuKod    0      0       Integer            0
10                KatastralniUzemiKod    0      0       Integer            0
11                            PlatiOd    4     19        String            0
12                            PlatiDo    4     19        String            0
13                        IdTransakce   12      0     Integer64            0
14                           RizeniId   12      0     Integer64            0
15                BonitovanyDilVymera    1      0   IntegerList            4
16 BonitovanyDilBonitovanaJednotkaKod    1      0   IntegerList            4
17           BonitovanyDilIdTranskace   13      0 Integer64List            0
18              BonitovaneDilRizeniId   13      0 Integer64List            0
19                   ZpusobOchranyKod    1      0   IntegerList            1
20         ZpusobOchranyTypOchranyKod    1      0   IntegerList            1
21           ZpusobOchranyIdTransakce    1      0   IntegerList            1
22              ZpusobOchranyRizeniId   13      0 Integer64List            0
> 

```

**Comment by rsbivand** [comment]
Please provide the file with the Int64List - readOGR can be fixed. In any case this is undoubtedly a data provider error, as the contents should be represented in a string list - they are almost without doubt ID codes, not long integer numbers. In string representation, leading zero will not be lost. Once we resolve this in rgdal, the resolution in sf will be trivial.

**Comment by rsbivand** [comment]
At revision 683 fixed in rgdal on R-forge; the problem was that the ogrInfo C code didn't count Integer64List sub-fields, shown in your output:

```
21           ZpusobOchranyIdTransakce    1      0   IntegerList            1
22              ZpusobOchranyRizeniId   13      0 Integer64List            0
```

where the count of the final list field was 0 and after revision is now:

```
21           ZpusobOchranyIdTransakce    1      0   IntegerList            1
22              ZpusobOchranyRizeniId   13      0 Integer64List            1
```

I remain convinced that this is an upstream issue as far as such data sets are concerned; GML is all text anyway, so a string or int64 representation takes the same space, but in R:

```
 ZpusobOchranyRizeniId1
                       :241       
 22219527010:400       
 49284652010:  3
```

is highly inefficient, as R stores all strings in a hash table and so stores "22219527010" once, and uses  int32 (I believe, maybe shorter internally?) pointers. Integer64 is really very rarely needed in data (unless the data are very very large).

**Comment by rsbivand** [comment]
rgdal 1.2-13 submitted to CRAN.

**Comment by petrbouchal** [comment]
Excellent, many thanks. I'll test once the build completes. Yes, the rgdal bug you describe is what my quick debug inspection suggested.

I agree this is a misspecification by the provider and should be a string type. I will try to take this up with the provider, but at the moment this is how the schemas for an entire national geodata system operates (this is the official data dump of the Czech geodesy office, which runs probably hundreds of exports of these every day).

**Comment by petrbouchal** [comment]
This now works in rgdal. Thanks again for the quick response.

**Comment by rsbivand** [comment]
Thanks for the feedback - now sf has a working model from rgdal 1.2-13.

**Comment by edzer** [comment]
Thanks for the example. The other list types didn't handle Null values very well.
