### ISSUE TITLE
imported objects may differ if GDAL build with or without GEOS

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#510]
In preparing a vignette for #234, I realised that while the initial import of NY tract boundaries in mid-2007 (bna2mif, then OGR MIF driver) led to invalid geometries (so different poly2nb(sp_object) and st_queen(sf_object) output), re-import with the OGR BNA driver in GDAL built with GEOS did not read invalid geometries. I'm trying to expose whether the linked GDAL was built with GEOS based on [Even Rouault's reply](https://lists.osgeo.org/pipermail/gdal-dev/2011-March/028036.html), and have this in rgdal/src/gdal-bindings.cpp:

```
SEXP
RGDAL_GDALwithGEOS(void) {
    SEXP ans;

    PROTECT(ans=NEW_LOGICAL(1));

    CPLPushErrorHandler(CPLQuietErrorHandler);
    saved_err_no = 0;

    int withGEOS;
    OGRGeometry *poGeometry1, *poGeometry2;
    char* pszWKT;
    pszWKT = (char*) "POINT (10 20)";
    OGRGeometryFactory::createFromWkt( &pszWKT, NULL, &poGeometry1 );
    pszWKT = (char*) "POINT (30 20)";
    OGRGeometryFactory::createFromWkt( &pszWKT, NULL, &poGeometry2 );
    withGEOS = 1;
    if (poGeometry1->Union(poGeometry2) == NULL) withGEOS = 0;
    OGRGeometryFactory::destroyGeometry(poGeometry1);
    OGRGeometryFactory::destroyGeometry(poGeometry2);

    CPLPopErrorHandler();
    saved_err_no = 0;

    LOGICAL_POINTER(ans)[0] = withGEOS;
    UNPROTECT(1);

    return(ans);
}
```

Does this look sensible? Would it be helpful in sf (eg in sf_extSoftVersion())? From:

```
$ grep GEOS ogr/ogrsf_frmts/*/drv_*.html
ogr/ogrsf_frmts/bna/drv_bna.html:polygon edges are described clockwise or counter-clockwise). GDAL must be built with GEOS enabled to make geometry test work. Polygons are exposed as multipolygons in the OGR Simple Feature model.<p>
ogr/ogrsf_frmts/gml/drv_gml.html:<p><b>NOTE</b> : Using the newest interpretation requires GDAL/OGR to be built against the GEOS library.</p>
```

maybe only the legacy Atlas BNA and the GML drivers are affected.

**Comment by edzer** [comment]
Interesting! According to [this](http://www.gdal.org/classOGRGeometry.html#a939bb2b738337a3af1fc715187822171), `poGeometry1->Union()` will fail if GEOS is not linked to gdal, so you'd have to catch the associated error in a check.

Is GDAL linked without GEOS only a feature of CRAN binary MacOS builds?

**Comment by edzer** [comment]
```r
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4         lwgeom GDAL_with_GEOS 
       "3.5.1"        "2.2.1"        "4.9.2" "2.3.3 r15473"         "true" 
```
