### ISSUE TITLE
st_transform (and coord_sf) don't respect proj4 +over

### ISSUE THREAD

**Issue by econandrew** [r-spatial/sf#511]
Quoting [proj4](http://proj4.org/parameters.html#lon-wrap-over-longitude-wrapping):

> By default PROJ.4 wraps output longitudes in the range -180 to 180. The +over switch can be used to disable the default wrapping which is done at a low level - in pj_inv(). 

e.g. compare the following in rgdal, which correctly applies +over
```r
# The +over paramater should stop projected coordinates from wrapping
rgdal::project(t(as.matrix(c(190, 0))), "+proj=robin")
rgdal::project(t(as.matrix(c(190, 0))), "+proj=robin +over")
```

This is very useful, for example, in ensuring that Russia appears as a contiguous block where otherwise it would wrap around 180 degrees. In fact `maps::map("world")` seems to be built that way.

`st_transform` doesn't appear to support this flag. One consequence is that ggplot2 will happily plot untransformed data outside the "usual" range for a projection, UNLESS you add a coord_sf() at which point it will fail.

```
library(sf)
library(ggplot2)

# PROBLEM
world <- maps::map("world", plot = FALSE, fill = TRUE)
sf.world <- st_as_sf(world)
sf.world.robin <- st_transform(sf.world, crs = "+proj=robin +over")

ggplot(sf.world) + geom_sf() # Correct with Siberia extended beyond 180 deg E
ggplot(sf.world.robin) + geom_sf() # Inverted polys
ggplot(sf.world) + geom_sf() + coord_sf(crs="+proj=robin +over") # Inverted polys

# WORKAROUND via sp
sp.world <- as(sf.world, "Spatial")
sp.world.robin <- sp::spTransform(sp.world, sp::CRS("+proj=robin +over"))
sf.world.robin2 <- st_as_sf(sp.world.robin)
ggplot(sf.world.robin2) + geom_sf()
```

**Comment by edzer** [comment]
I refer to #509, and close here because both issues refer to the fact that `sf` uses the GDAL interface to PROJ.4, rather than doing projections directly through the PROJ.4 API, as `rgdal` does.

**Comment by edzer** [comment]
This is now found in (moved to) `lwgeom::st_transform_proj`; see https://github.com/r-spatial/lwgeom
