### ISSUE TITLE
build error involving GEOSVoronoiDiagram_r

### ISSUE THREAD

**Issue by RoyalTS** [r-spatial/sf#513]
I'm not an expert on building packages so I apologize in advance for what may be a very incomplete bug report. I'm hoping you'll help me make it more complete.

I'm trying to install `sf` on a Ubuntu machine but get the following error towards the end:

    ** testing if installed package can be loaded
    Error: package or namespace load failed for 'sf' in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object '/afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/sf/libs/sf.so':
      /afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/sf/libs/sf.so: undefined symbol: GEOSVoronoiDiagram_r
    Error: loading failed
    Execution halted

**Comment by jsta** [comment]
What is the output of `sf::sf_extSoftVersion()`? Do you have `GEOS` installed? 

Mine is:

>          GEOS           GDAL         proj.4         lwgeom 
>       "3.5.1"        "2.2.1"        "4.9.2" "2.3.3 r15473"

**Comment by RoyalTS** [comment]
Compiled geos from source, which seems to have worked:

    tobiass@yen5:~$ geos-config --version
    3.6.2

**Comment by edzer** [comment]
Please give the output of
```
ldd /afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/sf/libs/sf.so
```
The offending function is only compiled in when GEOS >= 3.5.0 is found by configure; when an older version of GEOS is present and is being linked to, this kind of errors occur.

**Comment by RoyalTS** [comment]
~$ ldd /afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/sf/libs/sf.so
    ldd: /afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/sf/libs/sf.so: No such file or directory

**Comment by RoyalTS** [comment]
I suspect your hunch is right though in that there are multiple versions of geos kicking around on the system. Is there any way to make sure only one of them is being used?

**Comment by edzer** [comment]
Maybe setting environment variable `LD_LIBRARY_PATH` to the directory with the right one helps? Do use `ldd` and `lddtree`: dependencies might be more complicated, e.g. gdal might link to an older geos, in which case your only hope would be to install gdal from source. (I did this recently, then reverted everything back as gdal would link to another library that would link by itself to an older proj version, then that messed up everything in sf...)

Two alternatives: 1. add ubuntugis-unstable to your package repository, it serves up to date spatial libraries; 2. work in a docker image.
