### ISSUE TITLE
Build Error in sf_0.5-4

### ISSUE THREAD

**Issue by kobybr** [r-spatial/sf#515]
Any ideas on this?  

Thank you

g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I/usr/local/include -I/usr/include -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c gdal_read.cpp -o gdal_read.o
gdal_read.cpp: In function ‘Rcpp::List allocate_out_list(OGRFeatureDefn*, int, bool)’:
gdal_read.cpp:67: error: call of overloaded ‘to_string(int&)’ is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
gdal_read.cpp: In function ‘Rcpp::List CPL_read_ogr(Rcpp::CharacterVector, Rcpp::CharacterVector, Rcpp::CharacterVector, bool, Rcpp::NumericVector, bool, bool)’:
gdal_read.cpp:434: warning: name lookup of ‘i’ changed
gdal_read.cpp:249: warning:   matches this ‘i’ under ISO standard rules
gdal_read.cpp:419: warning:   matches this ‘i’ under old rules

**Comment by jsta** [comment]
What is your GDAL version?

**Comment by kobybr** [comment]
GDAL version: 2.0.0

This issue seems to be related to gcc.   I upgraded from 4.4.7 to 4.9 and it appears to have compiled it ok.

Thanks for the response!
