### ISSUE TITLE
No print method for crs class

### ISSUE THREAD

**Issue by barryrowlingson** [r-spatial/sf#517]
Currently `crs` objects print using the default print method:

```
> cc = st_crs(27700)
> cc
$epsg
[1] 27700

$proj4string
[1] "+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.1502,0.247,0.8421,-20.4894 +units=m +no_defs"

attr(,"class")
[1] "crs"
```

which is a bit ugly.

crs objects in sf seem to be lists that have epsg and proj4string components - either of which can be missing. Here's an initial print method:

```
 print.crs <-
function(x,...){
  cat("Coordinate Reference System\n")
  if(is.na(x$epsg)){
     cat("  No EPSG code\n")
  } else {
     cat("  EPSG:",x$epsg,"\n")
  }
  if(is.na(x$proj4string)){
   cat("  No proj4string")
  } else {
    cat("  proj4string :",x$proj4string,"\n")
  }
}
```
looks like:
```
> st_crs(27700)
Coordinate Reference System
  EPSG: 27700 
  proj4string : +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs 
> st_crs("+proj=tmerc")
Coordinate Reference System
  No EPSG code
  proj4string : +proj=tmerc +lat_0=0 +lon_0=0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs 
```

**Comment by edzer** [comment]
Good idea! I'm not so excited about
```
st_crs(NA)
Coordinate Reference System
  No EPSG code
  No proj4string> 
```

1. I'd suggest to have a `:` after `Coordinate Reference System`
2. no space before `:`
2. I suggest to have
```
st_crs(NA)
Coordinate Reference System: NA
```

**Comment by barryrowlingson** [comment]
And maybe present the proj4string in quotes so it can be easily pasted into other scenarios without having to bother typing the quotes? Can a valid proj4string ever contain quotes itself?

May update if I get a chance - encountered the output this morning while writing a workshop and thought I'd put this issue in as as placeholder, wasn't expecting action!
