### ISSUE TITLE
st_read does not read projection when some geometries are null?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/sf#522]
Hi

I have the impression that when a shapefile contains some null geometries (and hence when message *replacing null geometries with empty geometries* appears), `st_read` does not read the projection?

It seems that when setting `nc$geometry[1] <- NULL` I can recreate this (real-life example available if necessary). Try:

    library(sf)
    dir.create("temp_sf")
    nc = st_read(system.file("shape/nc.shp", package="sf"))

    nc$geometry[1] <- NULL

    st_write(nc, "temp_sf/nc2.shp")
    st_read("temp_sf/nc2.shp")

    unlink("temp_sf", recursive = TRUE)

Do you confirm? Is there a quick workaround for now, like a function to read just the .prj file and add it?

Thanks!

**Comment by edzer** [comment]
I can't confirm:
```r
> st_read("temp_sf/nc2.shp")
Reading layer `nc2' from data source `/tmp/temp_sf/nc2.shp' using driver `ESRI Shapefile'
replacing null geometries with empty geometries
Simple feature collection with 100 features and 14 fields (with 1 geometry empty)
geometry type:  GEOMETRY
dimension:      XY
bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.57286
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs
```
This is with
```
> sf_extSoftVersion()
   GEOS    GDAL  proj.4  lwgeom 
"3.5.1" "2.1.2" "4.9.3"      NA 
```

**Comment by MatthieuStigler** [comment]
Mmh, that is troubling... I can see that on my two machines. Here I guess we are concerned with the version of gdal in particular?

Ubuntu 16.04:

    > sf_extSoftVersion()
       GEOS    GDAL  proj.4  lwgeom 
    "3.5.0" "2.1.3" "4.9.2"      NA 

Red hat 7.4:

    > sf_extSoftVersion()
       GEOS    GDAL  proj.4  lwgeom 
    "3.4.2" "2.2.1" "4.9.3"      NA 

Typical output:

    st_read("temp_sf/nc2.shp")
    Reading layer `nc2' from data source 
    `/media/matifou/WDlinNew/Datasets/CLU/new_dropbox/specific/temp_sf/nc2.shp' using driver `ESRI 
    Shapefile'
    replacing null geometries with empty geometries
    Simple feature collection with 100 features and 14 fields (with 1 geometry empty)
    geometry type:  GEOMETRY
    dimension:      XY
    bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.57286
    epsg (SRID):    NA
    proj4string:    NA

**Comment by MatthieuStigler** [comment]
Interestingly, issue seems to happen only if the first geometry is null. Setting the second only to null, projection is read correctly.

**Comment by edzer** [comment]
`sessionInfo()`?

**Comment by MatthieuStigler** [comment]
Oh, I had sf 0-5-3 actually! With 0-5-4 does not happen anymore! 

Sorry that I didn't check this.
