### ISSUE TITLE
st_cast() does not check input geometries

### ISSUE THREAD

**Issue by etiennebr** [r-spatial/sf#529]
``` r
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.1.3, proj.4 4.9.2, lwgeom 2.3.3 r15473
st_as_sfc("LINESTRING(0 0,1 1)") %>% 
  st_cast("POLYGON") %>% 
  st_as_text()
#> [1] "POLYGON ((0 0, 1 1, 0 0))"
```
As a reference in postgis:
``` sql
SELECT ST_MakePolygon('LINESTRING(0 0, 1 1)'::geometry);
ERROR:  XX000: lwpoly_from_lwlines: shell must have at least 4 points
LOCATION:  pg_error, lwgeom_pg.c:164                                
```
This also makes me believe that lwgeom might offer efficient casting that we could reuse...

**Comment by etiennebr** [comment]
In fact, there are no checks at all.
``` r
st_as_sfc("POINT(0 0)") %>% 
	st_cast("LINESTRING") %>% 
	st_cast("POLYGON") %>% 
	st_as_text()
```
Not sure it's such a big deal though, but it might be good to add some check.

**Comment by edzer** [comment]
There's still a lot of invalid stuff possible with `st_cast`, but polygons need to have at least 4 points now.

**Comment by etiennebr** [comment]
Indeed, lots of things going on in `st_cast`, but I'm always pleasantly surprised how it nearly always comes with good results.
