### ISSUE TITLE
st_length broken for mixed polygon / multipolygon (sfc_geometry)

### ISSUE THREAD

**Issue by rundel** [r-spatial/sf#542]
Currently st_length gives an error when used with a geometry column of type sfc_geometry, e.g.

```r
outer = matrix(c(0,0,10,0,10,10,0,10,0,0),ncol=2, byrow=TRUE)
hole1 = matrix(c(1,1,1,2,2,2,2,1,1,1),ncol=2, byrow=TRUE)
hole2 = matrix(c(5,5,5,6,6,6,6,5,5,5),ncol=2, byrow=TRUE)

poly = st_polygon(list(outer, hole1, hole2))
mpoly = st_multipolygon(list(
  list(outer, hole1, hole2),
  list(outer + 12, hole1 + 12)
))

class(st_sfc(poly, mpoly))
## [1] "sfc_GEOMETRY" "sfc"  
st_length(st_sfc(poly, mpoly))
## Error: inherits(x, "sfc_LINESTRING") || inherits(x, "sfc_MULTILINESTRING") is not TRUE
```

Currently [st_length](https://github.com/r-spatial/sf/blob/master/R/geom.R#L78) only checks for point/multipoint and polygon/multipolygon, anything else triggers the `stopifnot`. sfc_GEOMETRY can't just be added to the polygon check condition since it might be hiding badness like points or more esoteric types. 

A better solution seems like iterating through the individual geometries and the doing the checks and calculations at that level?

**Comment by rundel** [comment]
Also the current error leaves a lot to be desired, something more informative about being unable to convert the current type to multilinestring or something along those lines.

**Comment by edzer** [comment]
The current documentation is indeed misleading about automatically converting everything into linestrings. You don't want to convert a polygon into a line before computing length, do you?

**Comment by rundel** [comment]
`st_cast` seems like a completely different issue and my thinking is to not rely on it at the sfc level if possible. With a bit fiddling the following is what I came up with for a revised `st_length`:

```r
geom_length = function(x, dist_fun, longlat, p) {
	stopifnot(inherits(x, "sfg"))
	
	if (inherits(x, "POINT") || inherits(x, "MULTIPOINT"))
		return(0.0)
	
	x = st_cast(x, "MULTILINESTRING")
	
	if (isTRUE(longlat)) {
		stopifnot(!is.na(p))
		if (missing(dist_fun) && !requireNamespace("geosphere", quietly = TRUE))
			stop("package geosphere required, please install it first")
		sf:::ll_length(x, dist_fun, p)
	} else {
		ret = sf:::CPL_length(st_sfc(x)) # units of coordinates
		ret[is.nan(ret)] = NA
		ret
	}
}

st_length = function(x, dist_fun = geosphere::distGeo) {
	x = st_geometry(x)

	longlat = st_is_longlat(x)
	p = NA
	if (!is.na(st_crs(x)))
		p = sf:::crs_parameters(st_crs(x))
	
	ret = vapply(x, geom_length, 0.0, dist_fun = dist_fun, p = p, longlat = longlat)
	
	if (isTRUE(longlat)) {
		units(ret) = units(p$SemiMajor)
	} else {
		if (! is.na(st_crs(x)))
			units(ret) = p$ud_unit
	}
	
	ret
}
```

**Comment by edzer** [comment]
LGTM!
