### ISSUE TITLE
st_intersection(): Error: Columns must have unique names

### ISSUE THREAD

**Issue by behrman** [r-spatial/sf#544]
The following shape files are from Natural Earth
http://www.naturalearthdata.com/

    germany <-
      read_sf(ne_50m_admin_0_countries.shp) %>%
      filter(NAME == "Germany")

    german_rivers <-
      read_sf(ne_50m_rivers_lake_centerlines.shp) %>%
      st_intersection(germany)

This results in the following error:

Error: Columns `scalerank`, `featurecla` must have unique names

I can't understand from this error message what the problem is.

Thanks,

Bill

**Comment by edzer** [comment]
This happens in the tidyverse, because you use `read_sf` rather than `st_read`. Two `tbl_df`s are merged, and the error indicates a name clash. If you would remove the offending columns before `st_intersection`, it works:
```r
geman_rivers = st_intersection(rivers, select(germany, -featurecla, -scalerank))
```
If you use `st_read`, and work with `data.frame`s, the columns would be renamed.

**Comment by behrman** [comment]
Thank you for the explanation. Students would have certainly asked me about the error, but without knowing how st_intersection() is implemented, I had no idea what the problem was.

The code used to work. I suspect that read_sf() may have changed in the meantime. Thanks for pointing out the difference between read_sf() and st_read(). I’ll make sure to point out the difference to our students.

Many thanks,

Bill

**Comment by edzer** [comment]
In early versions, both `st_read` and `read_sf` returned a `c("sf", "data.frame")` object; that was changed into a `c("sf", "tbl_df" etc` to make the tidyverse folks happy.
