### ISSUE TITLE
Suggested syntax for spatial subsetting?

### ISSUE THREAD

**Issue by mfherman** [r-spatial/sf#548]
I'm, not sure if this is the best place for this question, but I'll give it a go. I'm new to the `sf` package and just wondering what is the suggested syntax for selecting features by location?

Working with the `nz` and `nz_height` datasets in `spData`, let's say I want to select the the point features from `nz_height` that are within 1000m of the Canterbury Region. I could do something like this:
```r
library(dplyr)
library(purrr)
library(sf)
library(spData)

canterbury <- nz %>% filter(REGC2017_NAME == "Canterbury Region")
nz_height %>% filter(st_is_within_distance(nz_height, canterbury, dist = 1000) %>% 
                       map_lgl(~ length(.x) == 1))
```
This gives me the result I'm looking for, but doesn't seem particularly suited to the `%>%` workflow because of the recursive syntax, especially if I want to chain together multiple spatial subsets.

Is there are better way to do this?

**Comment by Nowosad** [comment]
I'm not sure, if it's better, but you can do it this way as well:

```
canterbury = nz %>%
  filter(REGC2017_NAME == "Canterbury Region")
nz_height_buf = st_buffer(nz_height, dist = 1000)
nz_height %>% filter(st_intersects(nz_height_buf, canterbury, sparse = FALSE))
```

**Comment by edzer** [comment]
`st_is_within_distance` can also be used with `sparse = FALSE`, that saves a `buffer`. But it will fail if `canterbury` has more than one feature.

**Comment by Nowosad** [comment]
``` r
# devtools::install_github("edzer/sfr")                                                
library(dplyr)                                                                         
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(purrr)                                                                         
library(sf)                                                                            
#> Linking to GEOS 3.5.0, GDAL 2.1.2, proj.4 4.9.2
library(spData)                                                                        
                                                                                       
canterbury = nz %>% filter(REGC2017_NAME == "Canterbury Region")                       
nz_height %>% filter(st_is_within_distance(., canterbury, dist = 1000, sparse = FALSE))
#> Error in filter_impl(.data, quo): Evaluation error: for a dense matrix, use st_distance(x,y) <= dist.
```

**Comment by edzer** [comment]
I can't find `nz` or `nz_height` in `spData`, is there a workaround for that or is it an issue?

**Comment by Nowosad** [comment]
Is not on CRAN yet - `devtools::install_github("nowosad/spData")`

**Comment by edzer** [comment]
Well, the error message from sf tried to suggest to you to use
```r
nz_height %>% filter(st_distance(., canterbury) < units::set_units(1000, m))
```
but maybe it should just carry out the suggestion rather than suggesting it.

**Comment by edzer** [comment]
@mfherman I would suggest syntax like
```r
nz_height %>% filter(lengths(st_is_within_distance(nz_height, canterbury, dist = 1000) > 0)
```
which will also work if `canterbury` has more than one feature. If that makes sense.

**Comment by mfherman** [comment]
Ahh, yes that's simpler than mapping over the list output of `st_is_within_distance()`. And it should work with any of the binary predicates instead of using the dense matrix output.

Thanks, @edzer and @Nowosad!

P.S. Thanks for all your work on this and related packages. As a relatively new R user, I'm finding `sf` objects much more intuitive to work with than `sp` object!
