### ISSUE TITLE
Make `st_read` and `st_write` generic?

### ISSUE THREAD

**Issue by etiennebr** [r-spatial/sf#551]
What do you think about deprecating `st_read_db()` and `st_write_db()`, make `st_read()` and `st_write()` generic and handle connection objects in a different way than paths? If my memory is right, this is how `dplyr`and `dbplyr` work. It would also make two less functions in `sf`.

I was also thinking we could create a special connection (`sf`) to connect to example files. Rather than the famous `st_read(system.file("shape/nc.shp", package="sf")`, we could `st_read("SF:nc.shp")` or something like that. I was inspired by the handy `readr_example()`.

**Comment by edzer** [comment]
Excellent suggestions, both of them!

**Comment by edzer** [comment]
`st_write` and `st_read` are now generic; would you, @etiennebr mind at looking into writing DBI methods and deprecating the *_db versions?

**Comment by edzer** [comment]
I think btw that the `readr_examples(file)` (in our case e.g.: `sf_examples(nc)`) is less intrusive than creating a new prefix.

**Comment by edzer** [comment]
Or maybe: `st_read("sf::nc.gpkg")` to stress this resolved is inside `sf`?

**Comment by etiennebr** [comment]
Excellent! This is exactly what I had in mind. S3 generic will probably be sufficient for all our needs. I'll make the `st_read.PostgreSQLConnection()` and `st_write.PostgreSQLConnection()`. Maybe also a `st_write.PqConnection()` (RPostgres) (but `st_read` requires some hack, but could work).

**Comment by etiennebr** [comment]
I think you're right. It's less intrusive to use `sf_examples(nc)` (or `st_example(nc)`?). Also maybe more intuitive? But it would add yet another function, I don't know. Your call.

**Comment by edzer** [comment]
Let's do our own driver: `sf::nc.gpkg`.

as of the st_read.DB methods: would we need one for each DB? Or write `st_read.DBIConnection` (in which case it would probably have to be an S4 generic?) -- might not be trivial to sort.
