### ISSUE TITLE
Change `sf` vignette filenames to match with title

### ISSUE THREAD

**Issue by coatless** [r-spatial/sf#555]
Could the `sf` vignette filenames be changed from: 

`sf1`, `sf2`,  ... ,`sf6`

to:

`1-simple-features-for-r`, `2-reading-writing-and-converting-simple-features`, ... , `6-miscellaneous`

https://cran.r-project.org/web/packages/sf/vignettes/

**Comment by edzer** [comment]
We see them here:
https://cran.r-project.org/web/packages/sf/
right? Why would you browse the directory you mention?

**Comment by coatless** [comment]
To emphasize the content that exists to students. 

Due to the positioning of vignettes being located further down on the page surround by noise, I've found it easier to directly link to the vignette directory.

**Comment by edzer** [comment]
Sorry, I don't see the need for this.
