### ISSUE TITLE
Question about support for odbc drivers

### ISSUE THREAD

**Issue by lbusett** [r-spatial/sf#557]
Hi, 

   Working on Ubuntu 17.04, and PostgreSQL Version: 9.5.10,  I am encountering an issue in writing sf objects to PostgreSQL tables when connecting to the db using the odbc driver.

All works well if (as per documentation) I connect to the db using something like: 

```
con <- DBI::dbConnect(PostgreSQL(),
                      host = "xx.xxx.xx.xx", dbname = "xxxxx", user = "xxxxx",
                      password = "xxxxx", port = 5432)
> con
<PostgreSQLConnection>
st_write_db(con, obj = my_vect,  table  = c("public","table_name"), drop = TRUE)
```

If however I connect using the odbc driver: 

```
con <- DBI::dbConnect(odbc::odbc(), Driver = "PostgreSQL Driver", 
    Server = "xxx", Database = "xxx", UID = "xxxxx", 
    PWD = "xxxxx", Port = 5432)
> con
<OdbcConnection> lbusetto@10.0.1.230
  Database: satfarming
  PostgreSQL Version: 9.5.10
```

and then try to write an object to the data base I get the error : 
```
 st_write_db(con, obj = my_vect,  table  = c("public","table_name"), drop = TRUE)
```

>  Error: length(name) == 1 is not TRUE 

I therefore wanted to ask if this is a problem on my side, or if `st_write_db` does not support connections created with the "odbc" driver.  

Asking this because the  handy new  "Conncections" panel in RStudio does not seem to support connections made with `DBI::dbConnect(PostgreSQL(),....` (i.e., I cannot save the connection, and can not see the DB structure if I connect like this). 

PS: I hope the the description of the issue is clear enough, since I am unfortunately not very fluent in the use and terminology of DBs.

**Comment by edzer** [comment]
Could you please give the output of `traceback()` after you get this error?

**Comment by lbusett** [comment]
sure, here it is: 

> 8: stop(msg, call. = FALSE, domain = NA)
7: stopifnot(length(name) == 1)
6: dbExistsTable(conn, name)
5: dbExistsTable(conn, name)
4: .local(conn, name, value, ...)
3: dbWriteTable(conn, table, clean_columns(df, factorsAsCharacter = TRUE), 
       ...)
2: dbWriteTable(conn, table, clean_columns(df, factorsAsCharacter = TRUE), 
       ...)
1: st_write_db(con, obj = in_vect, table_name = "parcelle", drop = TRUE)

**Comment by edzer** [comment]
Did you try passing arg `table = "table_name"`, leaving out the schema name?

**Comment by lbusett** [comment]
Hi, 

  yes, I already tried that with no luck. 

Digging a bit more, the problem may arise in db.R, line 165: 

```
schema_table <- function(table, public = "public") {
	if (!is.character(table))
		stop("table must be a character vector", call. = FALSE)

	if (length(table) == 1L)
		table = c(public, table)
	else if (length(table) > 2)
		stop("table cannot be longer than 2 (schema, table)", call. = FALSE)

	if (any(is.na(table)))
		stop("table and schema cannot be NA", call. = FALSE)

	return(table)
}
```

here, the table name is always built as a 2-element array (schema, table), which is then passed to:

`dbWriteTable(conn, table, clean_columns(df, factorsAsCharacter = TRUE), ...)`

This works well with the `RPostgreSQL` driver, but apparently the odbc driver expects a one-element character instead. 

I just confirmed the behaviour also on windows. Doing this fails:  

```
library(DBI)
library(sf)
con <- dbConnect(odbc::odbc(), Driver="PostgreSQL ODBC Driver(ANSI)", 
                 server = "localhost", database = "postgres", uid = "postgres", 
                 pwd = "****", port = 5432)
aaa = st_sf(a=3, st_sfc(st_point(1:2))) 
st_write_db(con, aaa, "test")

> Error: length(name) == 1 is not TRUE
```
, while this works (though I can not find a way to specify the schema in this case, and `sf` objects are not supported): 

```
st_geometry(aaa) <- NULL
dbWriteTable(con, "test", aaa)
```

As a counter test, this also fails: 

```
dbWriteTable(con, c("public", "test"), aaa)
> Error: length(name) == 1 is not TRUE
```

**Comment by edzer** [comment]
Just as a check: your odbc connection works well when not using `st_write_db`, but regular DBI read/write table commands?

**Comment by lbusett** [comment]
Yes, `dbWriteTable(con, "test", aaa)`  correctly creates a new "test" table in the db (checked on pgAdmin). 

I know this seems weird, but I now observed the same behaviour on both linux and windows, on two different machines. 

If it may help to reproduce the issue: On Windows 10, I installed postgres 9.5.10  using the installer from EntrerprseDB, and then installed both the odbc driver and the postGIS extension using the StackBuilder.

**Comment by edzer** [comment]
@etiennebr the problem above goes away when in  [this line](https://github.com/r-spatial/sf/blob/master/R/db.R#L142) we replace `table` with `table[2]`, which looks good to me if I read the docs of `dbWriteTable`. However, it breaks a couple of your tests. Could you pls take a look?

**Comment by etiennebr** [comment]
Indeed, `st_write_db` is tailored for RPostgreSQL+Postgis. The thing is that DBI does not yet provide an uniform API for database namespaces in general (see discussion in [r-dbi](https://github.com/r-dbi/DBI/issues/24)). So each driver seems to implement it in a different way (like RPostgreSQL and ODBC). My hope was that DBI would offer a unified interface, but I think it's not ready yet. 

Changing line 142 would remove schema support for RPostgreSQL connections. Since we're already changing `st_write_db` to a generic function, I could add support for odbc connections, but it doesn't seem fun to setup odbc on Ubuntu. I'll see what I can do!

**Comment by edzer** [comment]
I added a quick fix.

Agreed re: setting up odbc. I managed with the following file, which didn't require other .ini files:
```
library(DBI)
con <- dbConnect(odbc::odbc(),
#  driver = "PostgreSQL Driver",
  driver = "/usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so",
  database = "test_odbc",
  uid = "edzer",
  pwd = "****",
  host = "localhost",
  port = 5432)
#data <- dbWriteTable(con, "iris", iris)

library(sf)
demo(nc, ask = FALSE, echo = FALSE)

data <- st_write_db(con, nc, "nc", drop = TRUE)
```
It required setting up a database that has actually a password.

**Comment by lbusett** [comment]
Hi, 
 
  works perfectly, thanks.  Only problem now is that it does not seem possible to specify a non-default schema using odbc, but this is apparently a known DBI issue (https://github.com/r-dbi/DBI/issues/181).

**Comment by etiennebr** [comment]
@lbusett, indeed, that's the problem. But `sf` could handle it in a better way for sure. `odbc`probably uses something like `DBI::dbQuoteString()`, but `RPostgreSQL` uses another.
