### ISSUE TITLE
Possible bug in st_area 

### ISSUE THREAD

**Issue by mtennekes** [r-spatial/sf#560]
Hi Edzer,

Since I've updated both `sf` and `units` to the latest github versions, I got an error when applying `st_area`:

    data("NLD_prov")
    N <- as(NLD_prov, "sf")

    st_area(N)

gives:

Error in make_unit(udunits_from_proj[x$units]) : 
  cannot create unit from [cannot create unit from udunits_from_projcannot create unit from x$units

    devtools::session_info(c("sf", "udunits2", "units"))

	Session info ---------------------------------------------------------------------------------------------
	 setting  value                       
	 version  R version 3.4.1 (2017-06-30)
	 system   x86_64, linux-gnu           
	 ui       RStudio (1.0.143)           
	 language en_US                       
	 collate  en_US.UTF-8                 
	 tz       Europe/Amsterdam            
	 date     2017-11-17                  

	Packages -------------------------------------------------------------------------------------------------
	 package  * version date       source                             
	 class      7.3-14  2015-08-30 CRAN (R 3.4.0)                     
	 classInt   0.1-24  2017-04-16 CRAN (R 3.4.0)                     
	 DBI        0.7     2017-06-18 cran (@0.7)                        
	 e1071      1.6-8   2017-02-02 CRAN (R 3.3.2)                     
	 magrittr   1.5     2014-11-22 CRAN (R 3.3.2)                     
	 MASS       7.3-47  2017-04-21 CRAN (R 3.4.0)                     
	 Rcpp       0.12.13 2017-09-28 cran (@0.12.13)                    
	 sf       * 0.5-6   2017-11-17 Github (r-spatial/sf@13d5abd)      
	 udunits2   0.13    2016-11-17 CRAN (R 3.3.2)                     
	 units    * 0.5-0   2017-11-17 Github (r-quantities/units@164465e)

Best,
Martijn

**Comment by edzer** [comment]
I messed up units on github; please use the CRAN version.

**Comment by mtennekes** [comment]
This afternoon, I had a strange error when applying `set_units`, so therefore I tried the github version. Now it works! Thx
