### ISSUE TITLE
Plotting empty geometries gives an (unhelpful) error

### ISSUE THREAD

**Issue by rundel** [r-spatial/sf#561]
```r
st_as_sfc("POINT EMPTY") %>% plot()

#  Error in (function (xlim, ylim, log = "", asp = NA, ...)  : 
#   need finite 'xlim' values
```

Seems like either an empty plot or a more explicit error message should be provided.

**Comment by edzer** [comment]
not sure - I see
```r
> plot(NA)
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
```

**Comment by rundel** [comment]
Is the idea that an empty geometry is the sf equivalent of an NA? I see that the errors are somewhat equivalent but I still find the sf error to be more confusing (due to the anonymous function being applied). It seems straight forward enough to include a check that provides a slightly more helpful error message.

Also another minor point that I just noticed, but empty points seem to be inconsistent with the other empty simple features:
```
> st_as_sfc("POINT EMPTY") %>% str()
sfc_POINT of length 1; first list element: Classes 'XY', 'POINT', 'sfg'  num [1:2] NaN NaN
> st_as_sfc("MULTIPOINT EMPTY") %>% str()
sfc_MULTIPOINT of length 1; first list element:  XY[0 , 1:2] MULTIPOINT EMPTY
> st_as_sfc("LINESTRING EMPTY") %>% str()
sfc_LINESTRING of length 1; first list element:  XY[0 , 1:2] LINESTRING EMPTY
> st_as_sfc("POLYGON EMPTY") %>% str()
sfc_POLYGON of length 1; first list element:  list()
 - attr(*, "class")= chr [1:3] "XY" "POLYGON" "sfg"
```

**Comment by edzer** [comment]
This is an inconsistency of the SFA standard, I didn't come up with that.

**Comment by edzer** [comment]
And yes, you can think of an empty geometry as a missing geometry.
