### ISSUE TITLE
st_equals can say geometries are equal when identical() suggests points are not the same

### ISSUE THREAD

**Issue by Zedseayou** [r-spatial/sf#562]
[reprex.zip](https://github.com/r-spatial/sf/files/1484006/reprex.zip)

Working from the attached example kml file:
``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
polys <- st_read("reprex.kml")
st_equals(polys)
#> Sparse geometry binary predicate list of length 2, where the predicate was `equals'
#> 1: 1, 2
#> 2: 1, 2
identical(polys[1,], polys[2, ])
#> [1] FALSE
duplicated(st_geometry(polys))
#> [1] FALSE FALSE
```
The example file contains two polygons that are basically the same, plotting them shows that they cannot easily be distinguished with the naked eye. (I attached as a file instead of constructing from text because there are many points). `st_equals`  indicates that the two geometries are equal to each other, but we can see that `identical` and `duplicated` recognise that the points in the geometry are not exactly the same, and we can also see this if we look at the points ourselves.

I am assuming that this is something to do with rounding or the setting of precision at some point in `sf`, but I am not sure where in the process it happens and whether or not it is expected behaviour (maybe something to do with `st_precision`?). I am also not sure whether `st_equals` is the best practice for identifying duplicate geometries, or whether checking the geometry-lists themselves with `duplicated` is better. As far as I can tell, `st_equals` is catching more geometries that are close but not exactly the same than `duplicated` or `identical`.

**Comment by edzer** [comment]
```r
> library(sf)
> m = rbind(c(0,0), c(1,0), c(1,1), c(0,0))
> x = st_sfc(st_polygon(list(m)), st_polygon(list(m[c(2,3,4,2),])))
> st_equals(x, x)
Sparse geometry binary predicate list of length 2, where the predicate was `equals'
 1: 1, 2
 2: 1, 2
> st_equals_exact(x, x, par = 0)
Sparse geometry binary predicate list of length 2, where the predicate was `equals_exact'
 1: 1
 2: 2
```
`st_equals` checks whether two polygons describe the same area, `st_equals_exact` (and `identical`) whether their data structures are (nearly) identical.

**Comment by Zedseayou** [comment]
I guess what I wanted to get at was what the tolerance on `st_equals` was for determining "same area"? Is there some built-in default for `par` in `st_equals`? From reading the description I expected that `st_equals` would simply catch alternate orderings of points in a geometry as your example shows, while `st_equals_exact` would require the same ordering. However, in my example, it seems to identify two polygons as equal that are not simple reorderings of the same points, but rather points that are very close in value.

**Comment by edzer** [comment]
`st_equals` does not take a tolerance parameter, so assume it is (practically) zero. I think `st_equals` may even give `TRUE` when one geometry contains more vertices, e.g. on straight line pieces, not only alternative orderings of the same set of vertices. 

Your use of `identical` does not make sense as it identifies differences in the attributes, too; you want to compare the geometry column only.
