### ISSUE TITLE
Error in as_Spatial with large files

### ISSUE THREAD

**Issue by RS-eco** [r-spatial/sf#563]
I encounter the following error:
Error in as_Spatial(geom, IDs = row.names(from)) : conversion from feature type sfc_GEOMETRY to sp is not supported
when trying to convert a large sf object to a spatial object.
I have a large Geodatabase with more than 10000 features, which I want to rasterize preferably using the sf package to read in the shapefile. When I subset my data to 1800 features I am able to convert the file back to a spatial object, but when I use more features (2000) it does not work.
Is this an issue with the sf package or due to limitations in memory, etc?

**Comment by edzer** [comment]
You don't get any error messages indicating memory problems. Type `sfc_GEOMETRY` indicates that you have a mixed bag of e.g. points and lines; sp doesn't have a corresponding data structure. Maybe select first on type, then rasterize?

**Comment by RS-eco** [comment]
My geodatabase should actually only consist of polygons. But anyway, using st_read(..., type=3) solved the issue. Thanks for your help!
