### ISSUE TITLE
Link to images describing binary predicates

### ISSUE THREAD

**Issue by richardbeare** [r-spatial/sf#565]
Hi,
I thought I came across an issue describing all the details of how lines might touch polygons and therefore not intersect etc, as well as a link to a really useful page with pictures showing the combinations and corresponding predicates. Of course, I can't track it down now that I need it.

If this rings a bell, it would be really useful link to have in the pages for st_intersection and friends.

Thanks

**Comment by Robinlovelace** [comment]
PostGIS documents these things really well, e.g.: https://postgis.net/docs/ST_Overlaps.html

@Nowosad and I generated some images illustrating different joins for an in-progress-book (see [here](http://robinlovelace.net/geocompr/spatial-data-operations.html#topological-relations) if interested - any feedback welcolme) - I was thinking that it would be great if the **pkgdown** build of the documentation would create such images with examples, e.g. as demonstrated by the plot of `cycle_hire_osm` auto-produced for the **spData** pkg: file:///home/robin/repos/spData/docs/reference/cycle_hire_osm.html

Up for contributing to that mission if it's deemed worthy.

**Comment by richardbeare** [comment]
Thanks,
Perhaps that was what I thought I remembered. An equivalent would certainly be a useful vignette.

**Comment by Robinlovelace** [comment]
I assume that means 'deemed worthy'. Would you be happy with plots for each predicate @edzer? Links to the question of multiple help pages being more helpful.
