### ISSUE TITLE
CRAN warnings

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#566]
seen [here](https://cran.r-project.org/web/checks/check_results_sf.html); see DM's reply: https://stat.ethz.ch/pipermail/r-package-devel/2017q4/002076.html

**Comment by etiennebr** [comment]
I don't navigate the CRAN check often, is the commit hash of the submission somewhere in these files? Are previous submissions results available (do we know between which commit it broke)?

**Comment by edzer** [comment]
I try to sync [releases](https://github.com/r-spatial/sf/releases) with CRAN versions. I suspect this started with adding vignette 6, the first with html widgets in it.

**Comment by tim-salabim** [comment]
It's vignette 5 and very likely caused by the mapview call. This problem can be found with more packages using htmlwidgets in their vignettes. See e.g. https://cran.r-project.org/web/checks/check_results_highcharter.html

**Comment by edzer** [comment]
Seems to be a CRAN/pandoc version issue rather than an sf issue.
