### ISSUE TITLE
mutate() error on grouped sf data.frame

### ISSUE THREAD

**Issue by urbandw** [r-spatial/sf#567]
This seems related to #302 and also perhaps also to tidyverse/dplyr#2264. I am getting a grouped mutate error in an `sf data.frame`, using `sf 0.5-4` and `dplyr 0.7.4`. 

`nc <- st_read(system.file("shape/nc.shp", package="sf"))`
`nc <- nc %>% mutate(group_var = c(rep(1, 50), rep(2, 50))`

`nc %>% group_by(group_var) %>% mutate(area_gt = AREA > .1)`  gives the error
`Error in .subset2(x, i, exact = exact) : attempt to select less than one element in get1index`

whereas 

`nc %>% as_tibble() %>% group_by(group_var) %>% mutate(area_gt = AREA > .1)`
gives the expected output. 

I can recast as follows:

`nc %>% as_tibble() %>% group_by(group_var) %>% mutate(area_gt = AREA > .1) %>% st_sf()`,

but this seems like it shouldn't be necessary, and for large dataframes can take a non-trivial amount of time.

**Comment by edzer** [comment]
Thanks; should work now.

**Comment by urbandw** [comment]
Thanks! For both the quick fix and the great package.
