### ISSUE TITLE
Compilation on Mageia 6 problems

### ISSUE THREAD

**Issue by paulb20** [r-spatial/sf#569]
Hi. Trying again to install sf, after earlier problems with udunits2. This time it breaks at proj - though all the relevant dependencies are installed - there's a proj rpm plus the top three on here https://madb.mageia.org/package/list/application/0/arch/x86_64/t_search/lib64proj. All installed.

Curiously, the older packages install fine at this point - so rgdal maptools, sp and friends. 
The error message indicates that it can't find libproj.so.0 while the mageia packages seem to include /usr/lib64/libproj.so (in lib64proj-devel rpm ) and /usr/lib64/libproj.so.9 and /usr/lib64/libproj.so.9.1.0 in lib64proj9 rpm.
Maybe a guide to compilation on obscure linuxes?

**Comment by edzer** [comment]
If you want help here, at least give the output of `sessionInfo()` as well as the full output you see when installing `rgdal` and `sf` from source.

**Comment by paulb20** [comment]
Hi 
sf output:
* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
configure: CC: gcc
configure: CXX: g++
checking for gdal-config... /bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.0.2
checking GDAL version >= 2.0.0... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ.4 is available for linking:... yes
checking GDAL: checking whether PROJ.4 is available fur running:... ERROR 6: Unable to load PROJ.4 library (libproj.so.0), creation of
OGRCoordinateTransformation failed.
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ.4 not available?
ERROR: configuration failed for package ‘sf’
* removing ‘/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sf’
rgdal
* installing *source* package ‘rgdal’ ...
** package ‘rgdal’ successfully unpacked and MD5 sums checked
configure: CC: gcc
configure: CXX: g++
configure: rgdal: 1.2-16
checking for /usr/bin/svnversion... yes
configure: svn revision: 701
checking for gdal-config... /bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.0.2
checking GDAL version >= 1.6.3... yes
checking gdal: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... yes
configure: -g -O2  -I/usr/include/gdal
checking proj_api.h presence and usability... yes
checking PROJ.4 version: ... > 4.8.0
checking PROJ.4: epsg found and readable... yes
checking PROJ.4: conus found and readable... yes
configure: Package CPP flags:  -I/usr/include/gdal
configure: Package LIBS:  -L/usr/lib64 -lgdal -lproj
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2 -c OGR_write.cpp -o OGR_write.o
g++ -std=gnu++11 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2 -c gdal-bindings.cpp -o gdal-bindings.o
gcc -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2  -c init.c -o init.o
gcc -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2  -c inverser.c -o inverser.o
gcc -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2  -c local_stubs.c -o local_stubs.o
g++ -std=gnu++11 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2 -c ogr_geom.cpp -o ogr_geom.o
gcc -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2  -c ogr_polygons.c -o ogr_polygons.o
g++ -std=gnu++11 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2 -c ogr_proj.cpp -o ogr_proj.o
g++ -std=gnu++11 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2 -c ogrdrivers.cpp -o ogrdrivers.o
g++ -std=gnu++11 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2 -c ogrsource.cpp -o ogrsource.o
g++ -std=gnu++11 -I/usr/local/lib64/R/include -DNDEBUG -I/usr/include/gdal -I"/home/paul/R/x86_64-pc-linux-gnu-library/3.4/sp/include" -I/usr/local/include   -fpic  -g -O2 -c projectit.cpp -o projectit.o
g++ -std=gnu++11 -shared -L/usr/local/lib64/R/lib -L/usr/local/lib64 -o rgdal.so OGR_write.o gdal-bindings.o init.o inverser.o local_stubs.o ogr_geom.o ogr_polygons.o ogr_proj.o ogrdrivers.o ogrsource.o projectit.o -L/usr/lib64 -lgdal -lproj -L/usr/local/lib64/R/lib -lR
installing to /home/paul/R/x86_64-pc-linux-gnu-library/3.4/rgdal/libs
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (rgdal)
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Mageia 6

Matrix products: default
BLAS: /usr/local/lib64/R/lib/libRblas.so
LAPACK: /usr/local/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2    tcltk_3.4.2   

Paul Bivand (brother of rsbivand)

**Comment by edzer** [comment]
Roger's brother - well that increases your credit limit pretty much to unlimited! 

The output log above suggest to me that your gdal installation was not built against proj.4; this can be done but is quite unusual, and it breaks sf: sf uses the proj.4 functionality through the gdal interface (unlike rgdal). Maybe install gdal from source?

**Comment by paulb20** [comment]
Ok. Know Roger replies to people they should do this on R-sig-geo. Helpful to have some text to send to the Mageia package maintainer. These things tend to come in as dependencies for QGIS though Mageia policies are to separate packages as far as possible to avoid complex dependency trees so it could be a policy issue.

**Comment by rsbivand** [comment]
Good to hear from you!

I'm travelling, but will try to see whether one can see from within GDAL what its build-status with regard to proj might be. The packager might simply bbuild GDAL with static proj, but that wouldn't benefit from bug-fixes in proj itself. It's curious that GDAL appears to work in the rgdal setting, but there is no need there (I think) to use the SRS API directly, only through the drivers (not sure about that).

**Comment by rsbivand** [comment]
The traces are buried in ogr/ogrct.cpp, in which GDAL effectively copies across the definitions it needs from proj_api.h and projects.h from proj4, unless:
#ifdef PROJ_STATIC
#include "proj_api.h"
#endif
```

It then does risky stuff to create its own pointers to proj functions (either static or dynamic linking), varying by proj version, but does not seem to provide a handle to extract the proj version running inside GDAL, so I've asked about that [here](https://lists.osgeo.org/pipermail/gdal-dev/2017-November/047789.html).
```

**Comment by paulb20** [comment]
Compiled gdal 2.2.23. However still have system gdal loaded (as it's a dependency of my preferred openstreetmap editor Merkaartor - which I use a lot more than the R spatial packages and compiling that requires a qt4 buildsystem on a qt5 kde plasma machine). 

So everything still finds system (in /usr) rather than compiled (in /usr/local). 

I guess this needs some configure.vars incantation in install.packages. 

Mageia's dependency listing (from rpm specfiles) for gdal (etc) doesn't include proj, nor vice versa.

**Comment by rsbivand** [comment]
Still compiling 2.2.3 ... yes, configure.args="--with-gdal-config=/usr/local/bin/gdal-config" or something like that may work; the sf configure.args= (inside R) or --configure-args= (R CMD INSTALL) are: --with-gdal-config, --with-proj-include, --with-proj-lib, --with-proj-share, --with-geos-config, and ignoring lwgeom which is now a separate package.

**Comment by edzer** [comment]
Has this problem been settled & can we close here?

**Comment by paulb20** [comment]
Still running into problems with the configure.args incantation. 

For sf though, a guide to compilation and dependencies for the spatial stack would be useful. Part of the point of open source is enabling/encouraging people to move from user to developer, and compiling the source is essential here. Even if I'm happier pottering around the foothills.

Sf seems to introduce a dependency hell for me that didn't exist in the sp stack (though I wouldn't have tested edge cases). 

I would normally install dependencies by doing (fedora style) dnf builddep source.rpm and use the Qgis source.rpm as the way in that would bring in as much of the stack as useful. Presume a debian equivalent of the apt-get build-dep type exists. Mageia (and others) recommend using checkinstall to generate rpms and then use local dnf or urpmi to install. This isn't install.packages() friendly though.

**Comment by edzer** [comment]
The [docker files](https://github.com/r-spatial/sf/tree/master/inst/docker), mentioned in the repo's README, are meant to give you some ideas how to install things from source.

**Comment by rsbivand** [comment]
Removing the lwgeom dependency in the development version does simplify things. Now, sf depends on proj, geos, and gdal; gdal depends on proj and its other dependencies, and may also depend on geos. With sp, rgdal depended on proj and gdal; gdal depended on proj and its other dependencies, and might also depend on geos. rgeos only depended on geos.

I don't see the package issues, as proj, geos and gdal are built from source; the other dependencies that gdal has are partly met by source installs, but most by packages, and I seldom install things like QGIS - using the dnf mechanisms messed up almost everything. GRASS from source. I never build source rpms.

**Comment by paulb20** [comment]
So, from source: proj first from proj4.org, then geos via OSGEO, then gdal via OSGEO. Any other gdal capabilities can come in via the package management system as I've got now, as less critical.

Docker sounds a long way round, especially using Ubuntu. And I'm allergic to gnome - tried once and didn't like at all, so avoid gnome based distros. 

I do the dnf builddep thing to build R as the distro R is a 'stable' version so out of date. I suspect that Red Hat/Fedora have similar policies on minimising dependencies in rpms to Mageia (as Mageia/Mandrake was an offshoot a long time ago) which would cause the problems you saw.
