### ISSUE TITLE
[bug] st_write_db fails if the table name has uppercase letters

### ISSUE THREAD

**Issue by lbusett** [r-spatial/sf#571]
Attempting to write to a postgres DB fails in case the table name has capital letters in it. 

**reprex**

```r
  library(RPostgreSQL)
  library(sp)
  data(meuse)
  sf = st_as_sf(meuse, coords = c("x", "y"), crs = 28992)

   con <- DBI::dbConnect(PostgreSQL(),
                      host = "xx.xx.xx.xx", dbname = "xxxx", user = "lbusetto",
                      password = "xxxx", port = 5432)
  st_write_db(con, sf, "Meuse_tbl", drop = TRUE)
```

>  Error in postgresqlExecStatement(conn, statement, ...) : 
>   RS-DBI driver: (could not Retrieve the result : ERROR:  relation "public.meuse_tbl" does not exist
> LINE 1: UPDATE public.Meuse_tbl set wkb_geometry = ST_GeomFromEWKB(c...
>                ^
> ) 

This seems related to the fact that in postgres queries the table names are automatically casted to lowercase unless they are explicitly surrounded in double quotes (https://stackoverflow.com/a/20880247/6871135).

I tracked the issue down to  `db.R`, lines 148 - 158. While `dbWriteTable` at line 138 properly "quotes" the table name (thus creating a "Meuse_tbl" table in the DB), this query: 

```r
# convert text column `sfc_name' into geometry column `geom_name':
query = if (binary)
	DEBUG(paste0("UPDATE ", paste(table, collapse = "."),
		" set ", geom_name," = ST_GeomFromEWKB(cast(", sfc_name, " as geometry));
		ALTER TABLE ", paste(table, collapse = "."),
		" DROP COLUMN IF EXISTS ", sfc_name))
  else
	DEBUG(paste0("UPDATE ", paste(table, collapse = "."),
		" set ", geom_name," = ST_GeomFromEWKT(", sfc_name, ");
		ALTER TABLE ", paste(table, collapse = "."),
		" DROP COLUMN IF EXISTS ", sfc_name))
invisible(dbExecute(conn, query))
```

does not quote the table name "properly", therefore probably trying to send a query to a non-existing "public.meuse_tbl" table.

 Changing the query to this appears to solve the issue: 

```r
# convert text column `sfc_name' into geometry column `geom_name':
query = if (binary)
	DEBUG(paste0("UPDATE ", paste0(table[1], ".\"", table[2], "\""),
		" set ", geom_name," = ST_GeomFromEWKB(cast(", sfc_name, " as geometry));
		ALTER TABLE ", paste0(table[1], ".\"", table[2], "\""),
		" DROP COLUMN IF EXISTS ", sfc_name))
  else
	DEBUG(paste0("UPDATE ", paste0(table[1], ".\"", table[2], "\""),
		" set ", geom_name," = ST_GeomFromEWKT(", sfc_name, ");
		ALTER TABLE ", paste0(table[1], ".\"", table[2], "\""),
		" DROP COLUMN IF EXISTS ", sfc_name))
```

I could do a PR, but maybe it would be good if @etiennebr could have a look to see if there's a better way and if this could influence other functionality.

**Comment by etiennebr** [comment]
Thanks @lbusett I'm indeed trying to rely more on `dbWriteTable()` for most of the logic in the hope to make it easier to add support for multiple drivers. I think I should be able to push a working version this week. Thanks for the reproducible example; I'll add it to the tests.

**Comment by etiennebr** [comment]
Hi @lbusett, you probably moved on, but the latest `sf` version [should now work](https://github.com/r-spatial/sf/blob/master/tests/testthat/test_postgis_RPostgres.R#L123). If you could update the issue or close it, that would be perfect.
