### ISSUE TITLE
Vectorize st_intersection

### ISSUE THREAD

**Issue by yixinsun1216** [r-spatial/sf#575]
Currently `st_intersection(x, y)` intersects all geometries in x with all geometries in y. Would it be possible to have an option that can be vectorized to compute intersections between pairs of x and y? 

Background for this is that I have a very large `sf` object and want to check for overlapping polygons. I am first using `st_intersect` to figure out which polygons have intersections, and want to take the output from that to make pairs of sf objects that I use as the parameters for `st_intersection`. Right now, I am combining `st_intersection` with `map` from `purrr`, but this has proven to be very computationally demanding.

Any insight would be greatly appreciated!

**Comment by tim-salabim** [comment]
Can you provide a reproducible example? I have no idea what you mean by 'very large' but I routinely use `st_intersection` on layers of all feature types with 200k+ rows and 30+ columns. I have found computing time to be generally acceptable (<10-15 minutes usually).

**Comment by edzer** [comment]
... and do give your `sessionInfo()`!

**Comment by yixinsun1216** [comment]
Sorry here's the sessionInfo

```
sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2    texreg_1.36.23
```

I can't share the proprietary dataset, but it is has ~500,000 multipolygons/polygons that I want to intersect with itself. Below is an example of how I am currently doing pairwise intersection using 4 simple polygons 

```
library(dplyr)
library(sf)
library(purrr)

# creating the polygons
df1 <- 
  list(matrix(c(2,4,4,1,2, 2,3,5,4,2), ncol = 2), 
       matrix(c(5,4,2,5, 2,3,2,2), ncol = 2)) %>%
  map(function(x) st_polygon(list(x))) %>%
  st_sfc

df2 <- 
  list(matrix(c(5, 3, 2, 5, 2, 3, 2, 2), ncol = 2),
       matrix(c(2, 3, 3, 2, 2, 3, 3, 5, 4, 3), ncol = 2)) %>%
  map(function(x) st_polygon(list(x))) %>%
  st_sfc

```

```
# Output
> st_intersection(df1, df2)
Geometry set for 3 features 
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 2 ymin: 2 xmax: 5 ymax: 4.666667
epsg (SRID):    NA
proj4string:    NA
POLYGON ((3.5 2.75, 2 2, 3 3, 3.5 2.75))
POLYGON ((2 2, 3.5 2.75, 5 2, 2 2))
POLYGON ((2.5 4.5, 3 4.66666666666667, 3 3, 2 3...

# What I would like to do for pairwise intersection
> map2(df1, df2, st_intersection)
[[1]]
POLYGON ((3.5 2.75, 2 2, 3 3, 3.5 2.75))

[[2]]
GEOMETRYCOLLECTION EMPTY
```

**Comment by edzer** [comment]
I meant the sessionInfo() after loading sf.

**Comment by yixinsun1216** [comment]
I edited the last post to reflect the sessionInfo

**Comment by edzer** [comment]
Is it right that the `st_intersection` takes about 20 times as long as `st_intersects`?

**Comment by yixinsun1216** [comment]
When I run it on the whole dataset, st_intersect takes about 10 min while st_intersection takes more than a day

**Comment by edzer** [comment]
How much RAM does the machine have?

**Comment by yixinsun1216** [comment]
16 gb. At this point I'm ok letting it just run on my computer overnight - but wanted to take a shot in the dark at seeing if it can be vectorized using `st_intersection`!

**Comment by edzer** [comment]
I think your own solution `map` is the way to go, now.

**Comment by tim-salabim** [comment]
Here's an approach that uses `data.table`. I have no idea whether this is actually any faster than your solution using `map2`, but I would appreciate and be very interested in getting feedback how it performs in your case. We are still learning how to data.table with sf so any experiences with real-world cases are valuable.

```r
library(dplyr)
library(sf)
library(mapview)
library(data.table)

nc = read_sf(system.file("gpkg/nc.gpkg", package="sf"))

sfc1 = st_geometry(nc)
sfc2 = st_jitter(st_geometry(nc), amount = 0.05)

mapview(list(sfc1, sfc2))

dt = data.table(ID = seq_along(sfc1),
                geom1 = sfc1,
                geom2 = sfc2)

dt[, int := list(st_intersection(geom1, geom2)), by = "ID"]

mapview(sfc1[56]) + 
  mapview(sfc2[56], col.regions = "green") + 
  mapview(dt$int[56], col.regions = "red")
```

**Comment by pat-s** [comment]
Hi @edzer @tim-salabim,

continuing the [Twitter](https://twitter.com/pjs_228/status/967094903221125120) discussion here.

# Runtime
`sf `: 1.61 days (points, poly) and 1.63 days (poly, points) on a 2.1 GHz Debian 9 system. 
`ArcGIS` : < 1 min
`QGIS`: Quit QGIS2 due to being unresponsive after 2h, QGIS3 unchecked yet

# Reprex

```r
library(sf)

files <- download.file("http://www.geoinf.uni-jena.de/~bi28yuv/st_intersection_reprex/files.zip", "files.zip")
unzip("files.zip")

points <- st_read("points.shp")
polygons <- st_read("poly.shp")

time <- Sys.time()
out <- st_intersection(points, polygons)
time <- Sys.time() - time
print(time)
```

**Comment by edzer** [comment]
Seems like you're trying to rasterize polygons, for which `st_intersection` might not be the most efficient approach. Maybe try [fasterize](https://github.com/ecohealthalliance/fasterize)?

**Comment by pat-s** [comment]
Yes and no. 
First, I want to have a point feature to use it for spatial prediction with information from all predictors.That's why I am doing the `st_intersection`; I essentially just want to extract the polygon information to the points. And for that, `st_intersection` should be the right tool?

This point feature is gridded because later I'll transform it into a raster with 200x200m so that I have a spatial prediction map.

**Comment by tim-salabim** [comment]
`st_join(points, polygons[1:10, ])` takes about 45 seconds compared to about 6 minutes for `st_intersection(points, polygons[1:10, ])`. Obviously this ratio may increase or decrease for the whole set. But I think it's worth a try.

**Comment by edzer** [comment]
The `MULTIPOLYGON`s are soil types or something like that, and largely overlap. Since the spatial index works from bounding boxes, polygons with mostly overlapping bounding boxes are not efficiently indexed (Tim's example of waterways). Casting object `polygons` to `POLYGON` and using that as first argument seems to speed up things quite dramatically:
```r
> p <- polygons %>% st_cast("POLYGON")
Warning message:
In st_cast.sf(., "POLYGON") :
  repeating attributes for all sub-geometries for which they may not be constant
> system.time(out <- st_intersection(p, points[sample(nrow(points),500),]))
   user  system elapsed 
  3.094   0.000   3.094 
Warning message:
attribute variables are assumed to be spatially constant throughout all geometries 
> system.time(out <- st_intersection(polygons, points[sample(nrow(points),500),]))
   user  system elapsed 
 64.804   0.003  64.808 
Warning message:
attribute variables are assumed to be spatially constant throughout all geometries 
```

**Comment by tim-salabim** [comment]
And the combination of both runs in less than a minute for the whole set, just like ArcGIS:

```r
library(sf) 

# files <- download.file("http://www.geoinf.uni-jena.de/~bi28yuv/st_intersection_reprex/files.zip", "files.zip")
# unzip("files.zip")

points <- st_read("points.shp")
polygons <- st_read("poly.shp") %>% st_cast("POLYGON")

system.time({
  tst = st_join(points, polygons)
})

   user  system elapsed 
 32.698   0.012  32.708

head(tst)
Simple feature collection with 6 features and 2 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: 532900 ymin: 4702500 xmax: 533500 ymax: 4702700
epsg (SRID):    32630
proj4string:    +proj=utm +zone=30 +datum=WGS84 +units=m +no_defs
  OBJECTID COD_LITOLO               geometry
1        1         01 POINT (533100 4702500)
2        2         08 POINT (533300 4702500)
3        3         01 POINT (533500 4702500)
4        4         01 POINT (532900 4702700)
5        5         01 POINT (533100 4702700)
6        6         08 POINT (533300 4702700)
```
I think we know what ArcGIS is doing in case of point-polygon intersection - use binary predicates to get intersection ids and join attributes based on these ids.

**Comment by pat-s** [comment]
Awesome!

So lesson learned: Convert `MULTIPOLYGON` to `POLYGON` and use `st_join` in favor of `st_intersection` if both features overlap (?). 

If the runtime difference is that crucial and the outcome is equivalent, maybe a note in the help file for `st_intersection` would be helpful for users?

**Comment by tim-salabim** [comment]
I usually use `st_join` when dealing with point-polygon intersections where geometries don't change. For poly-poly or poly-line etc. it depends on the intended outcome (i.e. if the intersected geometries are needed - `st_intersection`- or if we merely want to know which intersections exist - `st_intersects`). The latter is much faster and is used by default in `st_join`.

**Comment by pat-s** [comment]
Good to know. Could be worth a blog post. Guess I'm not the first and last facing such a problem. 
Especially because point-poly intersections are quite common and other users from apps like ArcGIS are used to the "intersection" keyword and therefore are naturally directed to `st_intersection` instead of `st_join`.

The `st_cast("POLYGON")` is nice to additionally speed it up but there should be more awareness of when to use which function (st_join/st_intersection). 
This could be reached by a blog post + a note in the help file (or even a warning if a point-poly operation is detected).
I'm sure Edzer will find a good solution :smile:

**Comment by rsbivand** [comment]
How to return the output of `st_bbox(st_geometry(polygons)[[1]])` as an `sfg` object, so that `lapply()` could create a picture of the overlapping envelopes - to make plainer why using precise small envelopes matters for point-in polygon? A side point, is `Rcpp::checkUserInterrupt()` feasible in `geos.cpp`? I don't think we did it in **rgeos** to avoid housekeeping costs.

**Comment by tim-salabim** [comment]
@rsbivand you can get a `sfc` with `st_as_sfc(st_bbox(polygons[1, ]))`.
`Rcpp::checkUserInterrupt()` would be great (I cannot count the times I had to kill the process).

**Comment by edzer** [comment]
Check [geos.cpp](https://github.com/r-spatial/sf/blob/master/src/geos.cpp): `R_CheckUserInterrupt()` is in practically every (outer) loop.

**Comment by rsbivand** [comment]
@edzer forgot about CAPI. @tim-salabim no progress - need an sf or sfc containing all the bbox-derived POLYGON objects. I get to:

```
library(sf)
mp <- st_read("poly.shp")
o <- lapply(1:nrow(mp), function(i) st_as_sfc(st_bbox(mp[i,])))
```
but cannot create a single sfc out of n single entity sfc's. Then I want to show how much overlaps for the input gerrymandered case and demonstrate why spatial indexing obviously breaks down when most of the points could be in most of the polygons when indexed by envelope/bbox. The was an idea of a blog or similar, so I thought it would be easy.

**Comment by edzer** [comment]
Then:
```r
x = do.call(c, o)
i = st_intersection(st_sf(x))
plot(i["n.overlaps"])
```
![ov](https://user-images.githubusercontent.com/520851/36785426-05b39f50-1c83-11e8-9563-48e990c78031.png)

**Comment by edzer** [comment]
This simplification allows you to do
```r
o <- lapply(st_geometry(mp), function(x) st_as_sfc(st_bbox(x)))
```

**Comment by rsbivand** [comment]
Thanks, my mistake was `"rbind"` not `"c"` in `do.call()`. In sp/rgeos, the median bbox overlaps for multipolygons was 47, for polygons was 3. I haven't got to the area proportions being searched multiple times, but the figure as it is shows the root of the problem when doing point in polygon with envelopes overlapping each other.

**Comment by edzer** [comment]
Right. For `POLYGON`s:
```r
p <- st_cast(mp, "POLYGON")
op <- lapply(1:nrow(p), function(i) st_as_sfc(st_bbox(p[i,])))
xp = do.call(c, op)
i = st_intersection(st_sf(xp))
plot(i["n.overlaps"], border = NA)
```
![pol](https://user-images.githubusercontent.com/520851/36787066-0e901170-1c89-11e8-854f-21fa51a53f8a.png)

**Comment by tim-salabim** [comment]
Thanks @rsbivand and @edzer for this very graphic insight into this problem. I think an rspatial blog post about this would be great, as it seems to be a rather common application for users.

**Comment by rsbivand** [comment]
Right, my image of the same matches. With the same class intervals as the multipolygon case it is:

![image](https://user-images.githubusercontent.com/10198404/36787680-3218d1fc-1c8b-11e8-9f46-03f387ad6aad.png)
