### ISSUE TITLE
Simplified polygons plotting

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/sf#581]
I've tried to plot two simplified objects using different values of the `dTolerance` parametr. 
It works well for a large value, but gives strange result in case of a smaller value:

``` r
library(spData)
library(sf)
#> Linking to GEOS 3.5.0, GDAL 2.1.2, proj.4 4.9.2

us_states2 = st_transform(us_states, 2163)
plot(st_simplify(us_states2, dTolerance = 30000)$geometry)
```

![](https://i.imgur.com/fkrRPvI.png)

``` r
plot(st_simplify(us_states2, dTolerance = 20000)$geometry)
```

![](https://i.imgur.com/jDqQ8Rv.png)

Created on 2017-12-03 by the [reprex
package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by edzer** [comment]
Either `st_cast` the thing to `MULTIPOLYGON`, or add `col=0` as argument to `plot`.

Having default `col=1` for `GEOMETRY` sfc's makes some sense, since these can equally well be lines or points.
