### ISSUE TITLE
st_intersect() now "forgets" CRS?

### ISSUE THREAD

**Issue by zross** [r-spatial/sf#582]
In version 0.5-4 when I did an intersection the CRS for the result was adopted from the inputs. Now it seems that this is no longer the case unless I'm missing something. Is this for a reason or is it a bug?

```r
b0 = st_polygon(list(rbind(c(-1,-1), c(1,-1), c(1,1), c(-1,1), c(-1,-1))))
b1 = b0 + 2
b2 = b0 + c(-0.2, 2)
x = st_sfc(b0, b1, b2)
a0 = b0 * 0.8
a1 = a0 * 0.5 + c(2, 0.7)
a2 = a0 + 1
a3 = b0 * 0.5 + c(2, -0.5)
y = st_sfc(a0,a1,a2,a3)

st_crs(x) <- 32618
st_crs(y) <- 32618

int <-st_intersects(x,y)
st_crs(int) # result is NA
```

**Comment by zross** [comment]
Sorry, I got this wrong, the oddity for me was just that `st_intersects()` used to produce a list and now it's a `sgbp`.

**Comment by edzer** [comment]
... which is still a list ;-) `st_intersection` returns geometries, with a crs.

**Comment by zross** [comment]
Yep, thanks. I got confused when I saw the new (useful) printout! Looks good.

**Comment by edzer** [comment]
Thanks; motivation was to align things such that they become compatible with neighbourhood lists in spdep, see [here](https://cran.r-project.org/web/packages/spdep/vignettes/nb_sf.html).
