### ISSUE TITLE
geometry in multiple columns

### ISSUE THREAD

**Issue by monsieurxu** [r-spatial/sf#589]
I tried many things to st_as_sf the csv file to set geometry as either Points or Multipoint without success
with this file [test.txt](https://github.com/r-spatial/sf/files/1544065/test.txt)

What i want is a sf object with Id, numpoint, geom with numpoint=1..5 and geom as point or a sf object  with Id, geom with geom as multipoint

I did try many things and i'm lost
Could anyone help me ? 
thanksfully

**Comment by edzer** [comment]
I don't think it is reasonable to expect from `st_as_sf` that it can understand data in this form. Although it is of course possible to write an R script that converts such data into `MULTIPOINT` geometry `sf` objects, I think it is a better idea to ask the person who created this file for a better solution, e.g. encode the points as well-known text `MULTIPOINT` column, or come up with a single point per record and an extra column with an ID that groups the multipoint geoms. This would then drop the requirement for the NA padding.

**Comment by monsieurxu** [comment]
ok as i can't get another encoding format from the creator of the file, i'm gonna write a script

**Comment by edzer** [comment]
```r
> library(sf)
Linking to GEOS 3.5.1, GDAL 2.1.2, proj.4 4.9.3
> x  = read.csv("test.txt")
> fn = function(x) st_multipoint(matrix(na.omit(x), ncol=2, byrow = TRUE))
> geom = apply(x[-(1:2)], 1, fn)
> st_sf(x[1:2], geom = st_sfc(geom))
Simple feature collection with 10 features and 2 fields
geometry type:  MULTIPOINT
dimension:      XY
bbox:           xmin: 1924805 ymin: 598897.4 xmax: 2181158 ymax: 813509.1
epsg (SRID):    NA
proj4string:    NA
    X  Id                           geom
1   1 442 MULTIPOINT (2179729.3434439...
2   2 468 MULTIPOINT (1991521.0798444...
3   3 490 MULTIPOINT (1928234.5331340...
4   4 517 MULTIPOINT (2056523.5626655...
5   5 523 MULTIPOINT (1990523.2938469...
6   6 525 MULTIPOINT (2051450.9766957...
7   7 544 MULTIPOINT (2081374.8643257...
8   8 605 MULTIPOINT (2174545.0331422...
9   9 607 MULTIPOINT (2146748.7402435...
10 10 615 MULTIPOINT (2156617.8005235...
```

**Comment by monsieurxu** [comment]
thank you, except the inversion between X and Y, it works

**Comment by edzer** [comment]
Yeah, should be fixed now.

**Comment by monsieurxu** [comment]
sorry but nope, 
`is.numeric(x) && is.matrix(x) n'est pas TRUE `

i think there is some nesting trouble

**Comment by edzer** [comment]
... the usual `drop=FALSE` omission - now corrected.

**Comment by monsieurxu** [comment]
could you detail this to me, please?

**Comment by edzer** [comment]
In ` ?'['`, read the drop argument. 
```r
matrix(1:2, ncol = 2)[,2:1]
```
doesn't return a matrix.
