### ISSUE TITLE
Unclear Documentation - st_distance()

### ISSUE THREAD

**Issue by owenRiddy** [r-spatial/sf#595]
The st_distance() function documentation left me confused and I had to look through the source code to understand how it worked. Might the following changes please be incorporated into to the documentation strings (geom.R)?

#' @param dist_fun function to be used for great circle distances of geographical coordinates; for unprojected (long/lat) data this should be a distance function from package geosphere, or compatible to that (defaulting to \link[geosphere]{distGeo}). Ignored if \code{x} is not long/lat data (as \code{st_is_longlat}) and metric lengths are computed instead.

#' @return If \code{by_element} is \code{FALSE} st_distance returns a dense numeric matrix of dimension length(x) by length(y); otherwise returns a numeric vector of length \code{x} or \code{y}, the shorter one being recycled.

**Comment by edzer** [comment]
Thanks - helpful!
