### ISSUE TITLE
st_cast issue

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#596]
```r
library(sf)
demo(nc, echo = FALSE, ask = FALSE)
st_cast(nc, "MULTILINESTRING")
```
warns and gives 108 features, where
```r
st_cast(nc, "LINESTRING")
```
does not warn, and returns 100 features. Doesn't sound right.

**Comment by rsbivand** [comment]
Look at:

```
out <- st_cast(nc, "MULTILINESTRING")
plot(st_geometry(out[out$CRESS_ID == 27,]))
out1 <- st_cast(nc, "LINESTRING")
plot(st_geometry(out1[out1$CRESS_ID == 27,]))
```

where MULTILINESTRING is fine, but LINESTRING messes up the MULTIPOLYGON objects:

```
> sapply(st_geometry(nc), class)[nc$CRESS_ID == 27]
[1] "XY"           "MULTIPOLYGON" "sfg"         
```

**Comment by edzer** [comment]
This commit changes default behaviour; `MULTIPOLYGON` -> `MULTILINESTRING` used to do the same as `MULTIPOLYGON` -> `POLYGON`, i.e. increase the number of features. It no longer does. I believe this is the better (because simpler) way of doing things.
