### ISSUE TITLE
n-ary geometry functions

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#600]
`sf` now has unary functions like `st_area`, `st_length` and `st_dimension`, and binary geometrical predicate functions like `st_intersects` and binary functions generating geometries like `st_intersection`. We also have the n-ary (operating on more than 2) geometry functions like `st_union` (and some methods that use `st_union`: `aggregate` and `summarise`), and `c` (combine `sfg`s).

In PR #598 (excellent read!), @jeffreyhanson argues for a method `st_erase_overlaps`, that removes all overlaps from a set of (multi)polygons, sequentially. My questions are whether this is a good name, how many might follow, and whether we can approach this more cleanly.

Now, for instance, we see
```r
p = st_polygon(list(rbind(c(0,0), c(0,1), c(1,1), c(1,0), c(0,0))))
x = st_sfc(p, p + .5)
> st_difference(x)
Error in st_crs(y) : argument "y" is missing, with no default
> st_difference(x, x)
Geometry set for 2 features 
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 1.5 ymax: 1.5
epsg (SRID):    NA
proj4string:    NA
POLYGON ((0.5 1, 0.5 1.5, 1.5 1.5, 1.5 0.5, 1 0...
POLYGON ((0 0, 0 1, 0.5 1, 0.5 0.5, 1 0.5, 1 0,...
> st_intersection(x, x)
Geometry set for 4 features 
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 1.5 ymax: 1.5
epsg (SRID):    NA
proj4string:    NA
POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))
POLYGON ((0.5 0.5, 0.5 1, 1 1, 1 0.5, 0.5 0.5))
POLYGON ((0.5 1, 1 1, 1 0.5, 0.5 0.5, 0.5 1))
POLYGON ((0.5 0.5, 0.5 1.5, 1.5 1.5, 1.5 0.5, 0...
```
essentially, `st_intersection(x)` and `st_difference(x)` do nothing but error.

Does it make sense e.g. to have `st_difference(x)` return Jeff's `st_erase_overlap` (i.e. x1, x2-x1, x3-x2-x1, ...)`? And have `st_intersection(x)` return for four geometries int(x4, int(x3, int(x2, x1))) (with int = st_intersection)?

**Comment by jeffreyhanson** [comment]
Hi, now I understand what you meant by a more general approach. Yeah, I think this approach is much better.

**Comment by edzer** [comment]
Well, thanks to your excellent PR - it really helped pushing this!

**Comment by lbusett** [comment]
HI, 

   as the original poster of [this](https://stackoverflow.com/questions/44631044/efficient-extraction-of-all-sub-polygons-generated-by-self-intersecting-features),  I'd say that this perfectly solves that issue. Thanks! This will particularly useful to summarize potentially overlapping "spatial events" (e.g., fires, floodings, etcetera)! 

On a side topic: I am currently working my way on another issue that could also benefit from n-ary operations (removing small islands contained within larger polygons and automatically "filling" the hole, based on a categorical attribute (i.e., a class) -  Something akin to a raster "sieve" operation). Would you prefer that I describe the use case here or in a new issue?

**Comment by edzer** [comment]
Ah, that was you! Yes, please open a new issue for follow-up problems.

**Comment by edzer** [comment]
http://r-spatial.org/r/2017/12/21/geoms.html

**Comment by edzer** [comment]
My original draft for the blog post did this:
```r
> library(sf)
Linking to GEOS 3.5.1, GDAL 2.1.2, proj.4 4.9.3
> pts = st_sfc(st_point(c(0,0)), st_point(c(1,0)), st_point(c(0.5, 0.5 * tan(pi/3))))
> b = st_buffer(pts, 0.75)
> plot(b)
> plot(pts, add = TRUE)
```
![rplot001](https://user-images.githubusercontent.com/520851/34276674-b5817cde-e6a2-11e7-9248-e00aa7e32fb7.png)
```r
> (i = st_intersection(st_sf(b)))
Simple feature collection with 7 features and 2 fields
geometry type:  GEOMETRY
dimension:      XY
bbox:           xmin: -0.75 ymin: -0.75 xmax: 1.75 ymax: 1.616025
epsg (SRID):    NA
proj4string:    NA
                        geometry n.overlaps origins
1 POLYGON ((0.5 -0.5589369215...          1       1
2 POLYGON ((0.75 0, 0.7489721...          2    1, 2
3 MULTIPOLYGON (((1.75 0, 1.7...          1       2
4 POLYGON ((0.265946426795201...          3 1, 2, 3
5 POLYGON ((-0.23405357320479...          2    1, 3
6 POLYGON ((0.734053573204799...          2    2, 3
7 MULTIPOLYGON (((1.25 0.8660...          1       3
> st_overlaps(i)
Sparse geometry binary predicate list of length 7, where the predicate was `overlaps'
 1: 2, 7
 2: 1, 3, 5, 6, 7
 3: 2, 5, 7
 4: (empty)
 5: 2, 3, 6, 7
 6: 2, 5
 7: 1, 2, 3, 5
> plot(st_geometry(i[7,]))
```
giving the `MULTIPOLYGON` of number 7:
![rplot002](https://user-images.githubusercontent.com/520851/34276682-bb1fcc4a-e6a2-11e7-8514-cd2dde2ee090.png)

Note that the overlaps are not empty. Setting precision made the problem smaller, but not go away. Not sure whether this is a programming error, or a candidate for post-processing to remove tiny slivers.

**Comment by edzer** [comment]
... and the same holds for difference:
```r
> st_overlaps(st_difference(b))
Sparse geometry binary predicate list of length 3, where the predicate was `overlaps'
 1: 2, 3
 2: 1
 3: 1
```

**Comment by lbusett** [comment]
Yes, I noticed that too. Seems/May  be related to the fact that here we are intersecting circular buffer. In fact, increasing the `quadsegments argument when calling `st_buffer` solves/reduces the problem

**Comment by edzer** [comment]
That didn't solve it for me: with `nQuadSegs` set to 100, 1000 or 10000 I still see a `MULTIPOLYGON` and all the overlaps.

**Comment by lbusett** [comment]
Hi, 

   this is what I am currently seeing if I change the nQuadSegs argument on your "test" script: 

``` r
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.1.2, proj.4 4.9.3
pts = st_sfc(st_point(c(0,0)), st_point(c(1,0)), st_point(c(0.5, 0.5 * tan(pi/3))))
b = st_buffer(pts, 0.75, nQuadSegs = 30 )
print(st_intersection(b), n = 30)
#> Geometry set for 7 features 
#> geometry type:  GEOMETRY
#> dimension:      XY
#> bbox:           xmin: -0.75 ymin: -0.75 xmax: 1.75 ymax: 1.616025
#> epsg (SRID):    NA
#> proj4string:    NA
#> POLYGON ((0.5 -0.558936921583981, 0.47199029328...
#> POLYGON ((0.75 0, 0.74897215106593 -0.039251967...
#> MULTIPOLYGON (((1.75 0, 1.74897215106593 -0.039...
#> POLYGON ((0.265946426795201 0.153544241100228, ...
#> POLYGON ((-0.234053573204799 0.71248116268421, ...
#> POLYGON ((0.734053573204799 0.153544241100228, ...
#> MULTIPOLYGON (((1.25 0.866025403784438, 1.24897...

b = st_buffer(pts, 0.75, nQuadSegs = 500)
print(st_intersection(b), n = 15)
#> Geometry set for 7 features 
#> geometry type:  GEOMETRY
#> dimension:      XY
#> bbox:           xmin: -0.75 ymin: -0.75 xmax: 1.75 ymax: 1.616025
#> epsg (SRID):    NA
#> proj4string:    NA
#> POLYGON ((0.5 -0.559015993734486, 0.49950890057...
#> POLYGON ((0.75 0, 0.749996298901394 -0.00235619...
#> POLYGON ((1.75 0, 1.74999629890139 -0.002356190...
#> POLYGON ((0.265877959699105 0.1535041132819, 0....
#> POLYGON ((-0.234122040300895 0.712521290502539,...
#> POLYGON ((0.733935678244066 0.154396956577589, ...
#> MULTIPOLYGON (((1.25 0.866025403784438, 1.24999...

b = st_buffer(pts, 0.75, nQuadSegs = 1500)
print(st_intersection(b), n = 15)
#> Geometry set for 7 features 
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: -0.75 ymin: -0.75 xmax: 1.75 ymax: 1.616025
#> epsg (SRID):    NA
#> proj4string:    NA
#> POLYGON ((0.500094487387846 -0.55893246791029, ...
#> POLYGON ((0.75 0, 0.749999588766521 -0.00078539...
#> POLYGON ((1.75 0, 1.74999958876652 -0.000785398...
#> POLYGON ((-0.23412285361885 0.712521161749912, ...
#> POLYGON ((0.73412285361885 0.153504242034526, 0...
#> POLYGON ((0.265903040095817 0.1536282964152, 0....
#> POLYGON ((1.25 0.866025403784438, 1.24999958876...
```

I was interpreting this as apparently reducing the issue by increasing nQuadSegs, since at the end I get no more "MULTIPOLYGON" geometries. However, I noticed now that if I do: 

``` r
b = st_buffer(pts, 0.75, nQuadSegs = 1500)
st_overlaps(st_intersection(b))
```

the overlaps are apparently still there: 

```
Sparse geometry binary predicate list of length 7, where the predicate was `overlaps'
 1: 2, 3, 7
 2: 1, 3, 4, 5
 3: 1, 2, 7
 4: 2
 5: 2
 6: (empty)
 7: 1, 3
```

**Comment by edzer** [comment]
Setting precision does matter:
```r
library(sf)
# Linking to GEOS 3.5.1, GDAL 2.1.2, proj.4 4.9.3
pts = st_sfc(st_point(c(0,0)), st_point(c(1,0)), st_point(c(0.5, 0.5 * tan(pi/3))))
b = st_buffer(pts, 0.75, 100)
b %>% st_set_precision(1000) %>% st_intersection %>% st_overlaps
# Sparse geometry binary predicate list of length 7, where the predicate was `overlaps'
#  1: 2, 3, 7
#  2: 1, 3, 4, 6
#  3: 1, 2, 4, 7
#  4: 2, 3, 6, 7
#  5: (empty)
#  6: 2, 4
#  7: 1, 3, 4
b %>% st_set_precision(100)  %>% st_intersection %>% st_overlaps
# Sparse geometry binary predicate list of length 7, where the predicate was `overlaps'
#  1: (empty)
#  2: (empty)
#  3: (empty)
#  4: (empty)
#  5: (empty)
#  6: (empty)
#  7: (empty)
b %>% st_set_precision(1000) %>% st_difference %>% st_overlaps
# Sparse geometry binary predicate list of length 3, where the predicate was `overlaps'
#  1: 2, 3
#  2: 1, 3
#  3: 1, 2
b %>% st_set_precision(100)  %>% st_difference %>% st_overlaps
# Sparse geometry binary predicate list of length 3, where the predicate was `overlaps'
#  1: (empty)
#  2: (empty)
#  3: (empty)
```
but the plot doesn't look very nice:
![x](https://user-images.githubusercontent.com/520851/34295209-62ee5306-e70c-11e7-8c17-8fc6ea972549.png)

**Comment by lbusett** [comment]
to add some additional trouble/confusion, the bahaviour changes also  as a function of the magnitude of the points' coordinates and buffer radius.

With the original points, changing the precision gives you this: 

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
pts = st_sfc(st_point(c(0,0)), st_point(c(1,0)), st_point(c(0.5, 0.5 * tan(pi/3))))
b = st_buffer(pts, 0.75)
plot(b %>% st_set_precision(1) %>% st_intersection)
```

![](https://i.imgur.com/htKgCsD.png)

``` r
plot(b %>% st_set_precision(10) %>% st_intersection)
#> Error in CPL_nary_intersection(x): Evaluation error: TopologyException: Input geom 0 is invalid: Self-intersection at or near point -0.80000000000000004 -0 at -0.80000000000000004 -0.
plot(b %>% st_set_precision(100) %>% st_intersection)
```

![](https://i.imgur.com/7Mj9OXy.png)

``` r
plot(b %>% st_set_precision(1000) %>% st_intersection)
```

![](https://i.imgur.com/Q7Qcxje.png)

However, multiplying coordinates and radius by 100 gives you this instead:

``` r
pts = st_sfc(st_point(c(0,0)), st_point(c(1,0)), st_point(c(0.5, 0.5 * tan(pi/3)))) * 100.00
b = st_buffer(pts, 0.75*100.0)
plot(b %>% st_set_precision(1) %>% st_intersection)
```

![](https://i.imgur.com/TqKBMP0.png)

``` r
plot(b %>% st_set_precision(10) %>% st_intersection)
```

![](https://i.imgur.com/qx8xfxD.png)

``` r
plot(b %>% st_set_precision(100) %>% st_intersection)
```

![](https://i.imgur.com/2d4J5BX.png)

,  though re-casting to POLYGON gives back a working plot:

``` r

plot(b %>% st_set_precision(100) %>% st_intersection %>% st_cast("POLYGON"))
#> Warning in st_cast.MULTIPOLYGON(X[[i]], ...): polygon from first part only

#> Warning in st_cast.MULTIPOLYGON(X[[i]], ...): polygon from first part only
```

![](https://i.imgur.com/pDGBG4o.png)

weird... maybe a feasible solution could be to just clean-up the results after the intersection by removing the small slivers based on area, and re-casting to POLYGON...

**Comment by edzer** [comment]
If you look up what `precision` does (see also `?st_as_binary`), it is all obvious. 

As an alternative to
```r
plot(b %>% st_set_precision(100) %>% st_intersection %>% st_cast("POLYGON"))
```
you could also do a
```
b %>% st_set_precision(100) %>% st_intersection %>% st_cast("POLYGON") %>% plot
```

**Comment by lbusett** [comment]
Thanks for the info. 

   while the behaviour made sense to me for the first case (not-multiplied coordinates), I was caught off-guard by the fact that in the second one increasing precision seemed to lead to worse results. This until I read in the help of `st_set_precision` that "geometrical operations in GEOS or liblwgeom may work better at reduced precision.". Just out of curiosity, do you happen to have  a reference at hand useful to understand the reason for that? 

Anyway, thanks for this additional functionality to an already great package!

Lorenzo

**Comment by edzer** [comment]
Mmm. Maybe @rsbivand or @rundel have one?
