### ISSUE TITLE
Store time-series data as SF object: recommended?

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/sf#604]
Is it recommended to store time-series data as SF objects? If so, how can one do it? Replicating geometries with a column keeping track of time does not seem very efficient. 

For example, one might want to have a series of points or polygons, each associated with a time series of temperature at that given location.

If this is not supported, any suggestion on what is the best way to do this would be appreciated.

**Comment by lbusett** [comment]
I think you may consider using a list column to store the time series data. This would allow to associate the time series to the location, without replicating geometries. Something like: 

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
x            <- st_sf(a = 1:2, b = 2:3, geom=st_sfc(st_point(1:2),st_point(3:4)))
ts_data      <- list()
ts_data[[1]] <- data.frame( time = c(1,2,3,4,5), data = (10:14))
ts_data[[2]] <- data.frame( time = c(1,2,3,4,5), data = (15:19))
x$ts_data    <- ts_data

> str(x)
Classes ‘sf’ and 'data.frame':	2 obs. of  4 variables:
 $ a      : int  1 2
 $ b      : int  2 3
 $ geom   :sfc_POINT of length 2; first list element: Classes 'XY', 'POINT', 'sfg'  int [1:2] 1 2
 $ ts_data:List of 2
  ..$ :'data.frame':	5 obs. of  2 variables:
  .. ..$ time: num  1 2 3 4 5
  .. ..$ data: int  10 11 12 13 14
  ..$ :'data.frame':	5 obs. of  2 variables:
  .. ..$ time: num  1 2 3 4 5
  .. ..$ data: int  15 16 17 18 19
 - attr(*, "sf_column")= chr "geom"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA
  ..- attr(*, "names")= chr  "a" "b" "ts_data"

```
``` r
x$ts_data
#> [[1]]
#>   time data
#> 1    1   10
#> 2    2   11
#> 3    3   12
#> 4    4   13
#> 5    5   14
#> 
#> [[2]]
#>   time data
#> 1    1   15
#> 2    2   16
#> 3    3   17
#> 4    4   18
#> 5    5   19
```
This is  quite flexible, since the length and "times" of the time series data can vary across locations.

HTH.

**Comment by edzer** [comment]
You may want to look into the r-spatial/stars project. Regular time series for features is one of its use cases.

On 27 December 2017 21:30:01 CET, Adriano Fantini <notifications@github.com> wrote:
>Is it recommended to store time-series data as SF objects? If so, how
>can one do it? Replicating geometries with a column keeping track of
>time does not seem very efficient. 
>
>For example, one might want to have a series of points or polygons,
>each associated with a time series of temperature at that given
>location.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/r-spatial/sf/issues/604

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adrfantini** [comment]
@lbusett I could use that, thanks

@edzer  I was mistakenly under the impression that `stars` was only for raster data. Do you have any resource or hints on how to create a stars object containing multiple time-series for a set of points?

**Comment by edzer** [comment]
There is another example with features at the end of the first stars blog at r-spatial.org.

On 28 December 2017 21:01:23 CET, Adriano Fantini <notifications@github.com> wrote:
>@lbusett I could use that, thanks
>
>@edzer  I was mistakenly under the impression that `stars` was only for
>raster data. Do you have any resource or hints on how to create a stars
>object containing multiple time-series for a set of points?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/r-spatial/sf/issues/604#issuecomment-354349676

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ghiggi** [comment]
@adrfantini. If you are interested, I developed some S3 classes (and functions) that store zoo timeseries as list columns in sf objects and a set of functions to convert from sf dataframe times series in list columns (dfTSlist class) to what I call dfWIDE, dfLONG  and zoomatrix objects, as well as some apply, roll, functions to directly apply functions to timeseries stored in list-column in sf objects.  I can send you the code ...

**Comment by adrfantini** [comment]
@ghiggi Sorry for the late reply, I would for sure love it. I ended up using edzer's suggestion, but would absolutely love to take a look at some other approaches.
