### ISSUE TITLE
no st_area function in sf package?

### ISSUE THREAD

**Issue by maikeh7** [r-spatial/sf#606]
Hi, I just downloaded the sf package for R (I'm using Rstudio v.1.1.383, latest version of R, on a PC). I installed the package and was able to import a shapefile. However, there does not seem to be an st_area or an st_distance function. I even tried :  
??st_area

which returned: _no results found_. I do have the package loaded, and I've looked at the documentation online, and there should be an st_area function. Any suggestions on how to get the function? thanks.
Maike

**Comment by Nowosad** [comment]
Hi @maikeh7 ,
have you tried the development version?

``` r
library(devtools)
install_github("r-spatial/sf")
library(sf)
#> Linking to GEOS 3.5.0, GDAL 2.1.2, proj.4 4.9.2
nc = st_read(system.file("shape/nc.shp", package="sf"))
#> Reading layer `nc' from data source `/home/jn/R/x86_64-redhat-linux-gnu-library/3.4/sf/shape/nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> epsg (SRID):    4267
#> proj4string:    +proj=longlat +datum=NAD27 +no_defs
st_area(nc)
#> Units: m^2
#>   [1] 1137388604  611077263 1423489919  694546292 1520740530  967727952
#>   [7]  615942210  903650119 1179347051 1232769242 1136287383 1524655447
#>  [13] 1427072339 1085967384  718190417 1894045426  524418608 1986966652
#>  [19]  812293946  626337436  439717946  640703090  863300187 1276536764
#>  [25] 1084141138 1697937846 1109973986 1800646340 1036414044  770546970
#>  [31] 1423171283  585232978 1311628320 1225109692  800263351 1186420419
#>  [37] 2194592880 1179139746 1550312884  690606074  665152821 1457875905
#>  [43] 1340538971 1005743617  988324117 1163892506 2019778925 1810512144
#>  [49]  944425951 1350102629 1685154840 1068192109 1691487743 2082117118
#>  [55] 1447094476  943881740 2045540782 1420919020  707671880  653368537
#>  [61] 1471077596 1436135571 1550981080 1186028306  788535203 1265443511
#>  [67] 1829439189 1447873644  918216585 1312723474 1043728456  961860121
#>  [73]  781910957 1046066043  986730350  917752685  601326678 1321916259
#>  [79] 2437929994  833538942 1210326313 1738550168 1228689798 1648412173
#>  [85] 1400582685  995107225 1678077407 2071844302 1228274216  519198288
#>  [91] 1784932020  808600209 1978619669 2439553215 1264050755 2288682896
#>  [97] 2181174167 2450241815  430695499 2165843695
```

Created on 2018-01-04 by the [reprex
package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by maikeh7** [comment]
Hmmm well I just tried that and got this error:


ERROR: dependency 'pillar' is not available for package 'sf'
* removing 'C:/Users/Maike/Documents/R/win-library/3.3/sf'

I also tried installing roxygen2 and then installing sf the 'normal' way, and I was not asked about compiling binary packages, as before...but there was still no st_area function. And unfortunately your recommendation doesn't seem to work. Is there anything else I can try? Thank you so much!

**Comment by maikeh7** [comment]
Also...the plot function doesn't seem to work correctly either. For a multi-polygon sf dataframe with 15 fields called 'parks', I obtained this plot when I called 
plot(parks)
![plot](https://user-images.githubusercontent.com/13711148/34591936-0fcd2acc-f17e-11e7-8977-6d198bce0f99.png)
![image](https://user-images.githubusercontent.com/13711148/34591962-33b87cfc-f17e-11e7-87da-434fa4581ef7.png)

All of this seems to work correctly on my little tiny macbook...but I'd rather not use it because it is really small and not suitable for doing research.

**Comment by edzer** [comment]
If dependency pillar is not available, you need to install it. This issue sounds like installation/version problems, could you please restart R, load `sf`, and then tell us the output of 
```
sessionInfo()
```
?

**Comment by maikeh7** [comment]
Hi again, I looked again at my version of R, and it was 3.3.2! I have no idea how that happened (I thought I had the most recent version, but I have 3 computers, so maybe I just spaced to update the one I was working on). I installed the latest version of r and then tried installing 'sf' again, and everything worked perfectly. Sorry for the confusion! I am glad everything works! Thank you again for your prompt response!


Maike Holthuijzen
Ph.D Graduate Student
University of Vermont
cell: 208-830-0270

Nothing in life is to be feared, it is only to be understood - Marie Curie

________________________________

**Comment by edzer** [comment]
Ok, thanks!
