### ISSUE TITLE
conflict between units when using Hmisc package

### ISSUE THREAD

**Issue by coquito77** [r-spatial/sf#607]
the Hmisc package has a units function but it conflicts with the sf package
```r
library(Hmisc)

fail.time <- c(10,20)
units(fail.time) <- "Day"

library(sf)
units(fail.time) <- "Day"

 Error: inherits(value, "units") || inherits(value, "symbolic_units") is not TRUE
```
specifying package and function returns a different error message
```r
Hmisc::units(fail.time) <- "Day"

Error: 'units<-' is not an exported object from 'namespace:Hmisc'
```

**Comment by edzer** [comment]
See also https://stackoverflow.com/questions/48117627/r-units-error-when-using-hmisc-and-sf-packages

**Comment by edzer** [comment]
There's some more info on SO about this; two packages having different `units<-` methods doing different things. For follow-up, please open an issue under https://github.com/r-quantities/units
