### ISSUE TITLE
st_read() error message

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [r-spatial/sf#608]
st_read will throw an error message apparently inconsistent with file.exists() check of st_read.default. why?
```r
file.exists("line.shp")
#[1] FALSE
st_read("line")
#Cannot open data source line
#Error in CPL_read_ogr(dsn, layer, as.character(options), quiet, type,  : 
#  Open failed.
#Called from: CPL_read_ogr(dsn, layer, as.character(options), quiet, type, 
#  promote_to_multi, int64_as_string)
```

```r
# sessionInfo()
# R version 3.4.2 (2017-09-28)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows >= 8 x64 (build 9200)
# 
# Matrix products: default
# 
# locale:
#   [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
# [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
#   [1] rgdal_1.2-13         sp_1.2-5             sf_0.5-5             RevoUtils_10.0.6     RevoUtilsMath_10.0.1
```

**Comment by edzer** [comment]
Shapefiles require more than one file. Please provide a reprex.

**Comment by edzer** [comment]
So, the file doesn't exist, and `st_read` gives you an error that it can't open it. I think that's pretty O.K.

**Comment by PauloEduardoCardoso** [comment]
My bad indeed. I thought it could throw something more specifically related to wrong dsn.

**Comment by rach-codes** [comment]
library(rgdal)
library(sf)
subzonebound <- sf::st_read("/Users/rachelng/Desktop/RAWR/Assignment One", "MP14_SUBZONE_NO_SEA_PL.shp")

got an error: 
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Opening layer failed.

**Comment by LDalby** [comment]
Hi @rach-codes 

Have you tried to pass the full path to the shp file as the first argument to `st_read`?
Like:
```r
subzonebound <- sf::st_read("/Users/rachelng/Desktop/RAWR/Assignment One/MP14_SUBZONE_NO_SEA_PL.shp")
``` 
The layer argument is used if you want to load a specific layer from a multilayer file like a geopackage or similar.

In general it is much easier for others to debug your code if you provide a reproducible example. You can e.g. use the {reprex} 📦 for this. 

Hope this helps
Lars
