### ISSUE TITLE
controlling graticule appearance (color, linewidth, linetype...) with ggplot

### ISSUE THREAD

**Issue by GillesSanMartin** [r-spatial/sf#610]
The control of the graticule appearance with ggplot is quite counter-intuitive and something seems to be wrong.
If this is the intended behavior (see below), maybe a few examples in the help pages or the vignettes may help future users (also about how to remove this graticule with coord_sf(datum = NA) ).

For the examples below I used the latest ggplot version from github reinstalled today (2.2.1.9000) and sf 0.5-4 (with R version 3.4.3 - Ubuntu 16.04.3 LTS)

I expected to be able to control for example the color of the graticule with panel.grid but the commands seem to be ignored
```
library(ggplot)
library(sf)
nc = st_read(system.file("gpkg/nc.gpkg", package = "sf")) 

ggplot() + 
    geom_sf(data = nc) + 
    theme(panel.grid = element_line(color = "red", linetype = 2))
```
![rplot001](https://user-images.githubusercontent.com/4679586/34680588-d1278334-f499-11e7-8bec-f8ed84b375d8.png)

It works with `panel.grid.major` (I would expect that panel.grid.major will inherit from panel.grid)

```
ggplot() + 
    geom_sf(data = nc) + 
    theme(panel.grid.major = element_line(color = "red", linetype = 2))
```
![rplot001](https://user-images.githubusercontent.com/4679586/34680627-e7fc0e4a-f499-11e7-8392-3c4eeefa2758.png)

If you want to change only -say- the x grid color with panel.grid.major.x both x and y are changed : 

```
ggplot() + 
    geom_sf(data = nc) + 
    theme(panel.grid.major.x = element_line(color = "red", linetype = 2))
```
![rplot001](https://user-images.githubusercontent.com/4679586/34680669-044fc8b6-f49a-11e7-9adf-52e5e126a975.png)

If you want to change both x and y in different ways nothing happens : 

```
ggplot() + 
    geom_sf(data = nc) + 
    theme(panel.grid.major.x = element_line(color = "red", linetype = 2),
          panel.grid.major.y = element_line(color = "blue", linetype = 3))
```

![rplot001](https://user-images.githubusercontent.com/4679586/34680738-268b7880-f49a-11e7-87c2-8e2ecb1e935a.png)

By the way, a few weeks ago the default color of the graticule was also much lighter and less conspicuous (better to my taste)

**Comment by edzer** [comment]
There were quite a few changes in ggplot2::geom_sf and friends on Nov 1, see [here](https://github.com/tidyverse/ggplot2/commits/master/R/sf.R). The things you address here are, afaict, ggplot2 internal and not sf internal: @hadley

**Comment by GillesSanMartin** [comment]
OK sorry. ggplot and sf are so intricate now but I should have guessed... I have just posted a similar issue with clarifications (here)[https://github.com/tidyverse/ggplot2/issues/2389]

**Comment by edzer** [comment]
Thanks -- I've subscribed to it.
