### ISSUE TITLE
Problems installing sf in a MacOS High Sierra 10.13.2

### ISSUE THREAD

**Issue by lelysbravo** [r-spatial/sf#612]
I followed these instructions:
https://stat.ethz.ch/pipermail/r-sig-mac/2017-June/012429.html

and got the following:

* installing to library ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library’
* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
configure: CC: clang
configure: CXX: clang++
configure: gdal-config set to /Library/Frameworks/GDAL.framework/Versions/2.1/unix/bin/gdal-config
checking gdal-config exists... yes
checking gdal-config executable... yes
checking gdal-config usability... yes
configure: GDAL: 2.1.3
checking GDAL version >= 2.0.0... yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /Library/Frameworks/GDAL.framework/Versions/2.1/Resources/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ.4 is available for linking:... yes
checking GDAL: checking whether PROJ.4 is available fur running:... yes
./configure: line 3608: pkg-config: command not found
checking proj_api.h usability... no
checking proj_api.h presence... no
checking for proj_api.h... no
configure: error: proj_api.h not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sf’

**Comment by lelysbravo** [comment]
I used kent37 suggestion:
R CMD INSTALL sf_0.5-1.tar.gz --configure-args='-with-gdal-config=/Library/Frameworks/GDAL.framework/Versions/2.1/unix/bin/gdal-config -with-geos-config=/Library/Frameworks/GEOS.framework/Versions/3/unix/bin/geos-config --with-proj-include=/Library/Frameworks/PROJ.framework/unix/include --with-proj-lib=/Library/Frameworks/PROJ.framework/unix/lib'

and it worked!

Thank you!

**Comment by pbpearman** [comment]
Similar problem with install failure of SF, having installed GDAL framework 2.4 from [Kyngchaos page](https://www.kyngchaos.com/software/frameworks/).  Installation from RStudio and direct from GitHub both produced:
`checking for proj_api.h... no
configure: error: proj_api.h not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/sf’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/sf’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/bz/h_ys6bjn3h9b201nks55l9bc0000gn/T//Rtmpkpy7Mj/file75b37948bf50/sf_0.7-5.tar.gz’ had non-zero exit status`

I recycled the above solution for the current GDAL/GEOS/PROJ versions:
`R CMD INSTALL sf_0.7-4.tar.gz --configure-args='-with-gdal-config=/Library/Frameworks/GDAL.framework/Versions/2.4/unix/bin/gdal-config -with-geos-config=/Library/Frameworks/GEOS.framework/Versions/3B/unix/bin/geos-config --with-proj-include=/Library/Frameworks/PROJ.framework/unix/include --with-proj-lib=/Library/Frameworks/PROJ.framework/unix/lib'` 

Worked!
