### ISSUE TITLE
Units for st_distance with long/lat are not meters when by_element = TRUE

### ISSUE THREAD

**Issue by TheTS** [r-spatial/sf#614]
I am trying to return the distance between long/lat coords using st\_distance. It works fine only if `by_element = FALSE`. When `by_element = TRUE` it returns a vector but the units are not in meters.

I was previously using `geosphere::distGeo()`, but thought I'd switch over to `st_distance` with sf 0.6.

``` r
library(sf)
```

    ## Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3

``` r
p1 <- st_sfc(st_point(c(174.6997, -36.79947)), 
            st_point(c(174.701, -36.79988)), 
            st_point(c(174.6983, -36.7993)), 
            crs = 4326)

p2 <- st_sfc(st_point(c(174.701, -36.79988)), 
            st_point(c(174.7009, -36.79981)), 
            st_point(c(174.6986, -36.79927)), 
            crs = 4326)

st_distance(p1, p2)
```

    ## Units: m
    ##          [,1]      [,2]      [,3]
    ## [1,] 124.6209 113.54594 100.64719
    ## [2,]   0.0000  11.83175 224.63022
    ## [3,] 249.4092 238.83904  26.97972

This is correct. I assume `by_element = TRUE` should return c(124.6209, 11.83173, 26.97972), but:

``` r
st_distance(p1, p2, by_element = TRUE)
```

    ## [1] 0.0013631214 0.0001220656 0.0003014963

Is this expected behaviour?

**Comment by edzer** [comment]
Thanks - should be fixed now!
