### ISSUE TITLE
View()-ing sf objects

### ISSUE THREAD

**Issue by ateucher** [r-spatial/sf#618]
It's often handy to `View()` an sf object to look at the data (either by running `View(x)` or clicking on the object in the RStudio environment pane. However with objects with big/complex sfc columns it is really slow to load.

I wrote this function to strip the geometry from the object before loading it in the viewer. It works, but it's pretty hacky - especially because [RStudio already intercepts `View()`](https://github.com/rstudio/rstudio/blob/a39872678484b9b555eb34a3b920645eef39d05e/src/cpp/session/modules/SessionDataViewer.R#L549), and I'm hijacking that.

I'm posting to here for opinions - is this something that would belong in `sf`, or should I open an issue in rstudio suggesting this would be helpful behaviour? Or do people like being able to look at the geometry column in the viewer?

```r
#' A replacement for utils::View that strips the geometry column for viewing sf objects
#'
#' View()-ing an sf object can be very slow if the geometry column is very large. This function
#' shows just the data (non-geometry) columns.
#'
#' This will invoke the rstudio viewer window if RStudio is being used, otherwise the native viewer.
#'
#' @inheritParams utils::View
#' @export
View <- function(x, title) {
  is_rstudio <- requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()

  # Match original behaviour of setting title both in RStudio and in RGui
  if (missing(title)) {
    title <- paste(deparse(substitute(x))[1])
    if (!is_rstudio) title <- paste("Data:", title)
  }

  if (inherits(x, "sf")) x <- sf::st_set_geometry(x, NULL)

  if (is_rstudio) {
    .rs.viewHook(x = x, title = title)
  } else {
    utils::View(x, title = title)
  }

  invisible(NULL)
}

# In a package I think it also requires setting .rs.viewHook as a global variable since it's not exported from any packages:
utils::globalVariables(".rs.viewHook")
```

**Comment by Robinlovelace** [comment]
I reckon that would be useful. I've never big slowdowns Viewing sf objects. Could also be appropriate as a PR to `SessionDataViewer.R` if it's RStudio-specific perhaps?

**Comment by ateucher** [comment]
Yep! Thus I wondered if this override of `utils::View()` would be helpful in **sf**, for those that don't use RStudio.

But I also think you're right that it's worth seeking if RStudio would add this behaviour to the IDE...

**Comment by ateucher** [comment]
Just FYI someone else posted a similar [issue at the RStudio repo](https://github.com/rstudio/rstudio/issues/2039) so I linked back to this one...

**Comment by edzer** [comment]
`View` is not a generic, so overriding would result in dplyr-style warnings at startup; I consider that a no-go. 

What `sf` provides is a `format` method, that should be used by downstream viewers. It may be that its implementation has room for (further) optimization.

**Comment by ateucher** [comment]
Yep, no problem. I knew it was a stretch. It’s hacky and possibly antisocial :)
