### ISSUE TITLE
sf crashes R after installation with -with-geos-config

### ISSUE THREAD

**Issue by crstn** [r-spatial/sf#619]
On Mac OS High Sierra, I had sf 0.5.5 installed from CRAN and everything worked fine, until I wanted to use `st_voronoi`. Apparently my sf was linked to an older GEOS, so I followed the instructions in [this issue](https://github.com/r-spatial/sf/issues/314) and reinstalled sf with a link to an up-to-date GEOS version:

    R CMD INSTALL sf_0.6-0.tar.gz --configure-args='-with-gdal-config=/Library/Frameworks/GDAL.framework/Versions/2.1/unix/bin/gdal-config -with-geos-config=/usr/local/Cellar/geos/3.6.2/bin/geos-config

The install works fine, but now I have several functions that simply crash R – plotting, st_join, etc. Any ideas what might be going wrong?

**Comment by edzer** [comment]
Only that `-with-` should be `--with-`. I only have some experience building sf the way CRAN does (statically linked), using Simon Urbanek's [statically built libs](http://r.research.att.com/libs/).

**Comment by rsbivand** [comment]
Just a thought - might the GDAL framework have been built linking to GEOS itself, and that GEOS might be a different version to the Cellar GEOS?

**Comment by crstn** [comment]
I haven't been able to figure out what exactly caused the problem, but I solved it by installing GDAL and GEOS via Hombrew from the OSGEO tap, and then link to these two versions of the framework when installing `sf`:

    brew tap osgeo/osgeo4mac
    brew install geos
    brew install gdal2
    R CMD INSTALL sf_0.6-0.tar.gz --configure-args='--with-gdal-config=/usr/local/Cellar/gdal2/2.2.3/bin/gdal-config --with-geos-config=/usr/local/Cellar/geos/3.6.2/bin/geos-config'

**Comment by edzer** [comment]
Great - thanks for the feedback!
