### ISSUE TITLE
Weird ploting behaviour with plot(data, add=T)

### ISSUE THREAD

**Issue by BastienFR** [r-spatial/sf#626]
I've found a weird behaviour in the ploting function of `sf`.  See below:

```
### prepare session:
library(sf)

pts <- structure(list(LastYear=c("2007", "2010", "2018", "2018", "2012","2018",
"2018", "2018", "2018"),geometry=structure(list(structure(c(7149748.82537181,
1361867.46859397),class=c("XY","POINT","sfg")),structure(c(7110053.20819291,
1476849.5122007),class=c("XY","POINT","sfg")),structure(c(7149661.23093466,
1441617.58138714),class=c("XY","POINT","sfg")),structure(c(7164429.21379109,
1440106.90668633),class=c("XY","POINT","sfg")),structure(c(7164932.15539668,
1441350.65279849),class=c("XY","POINT","sfg")),structure(c(7244614.92141993,
1440331.28310236),class=c("XY","POINT","sfg")),structure(c(7244614.92141993,
1440331.28310236),class=c("XY","POINT","sfg")),structure(c(7245590.00798515,
1439406.7266096),class=c("XY","POINT","sfg")),structure(c(7245590.00798515,
1439406.7266096),class=c("XY","POINT","sfg"))),class=c("sfc_POINT",
"sfc"),precision=0,bbox=structure(c(7110053.20819291,1361867.46859397,
7245590.00798515,1476849.5122007),.Names=c("xmin","ymin",
"xmax","ymax"),class="bbox"),crs=structure(list(epsg=NA_integer_,
proj4string="+proj=lcc +lat_1=49 +lat_2=77 +lat_0=63.390675 +lon_0=-91.86666666666666 +x_0=6200000 +y_0=3000000 +datum=NAD83 +units=m +no_defs"),.Names=c("epsg",
"proj4string"),class="crs"),n_empty=0L)),.Names=c("LastYear",
"geometry"),row.names=c(NA,-9L),class=c("sf","data.frame"
),sf_column="geometry",agr=structure(NA_integer_,class="factor",.Label=c("constant",
"aggregate","identity"),.Names="LastYear"))

pol <- structure(list(id=1,geometry=structure(list(structure(list(
structure(c(7092111.90809248,7289862.03314609,7350510.84982176,
7319232.76453211,7146420.78627857,7126697.59232553,7084173.97898201,
7092111.90809248,1543401.08143375,1587647.67844029,1474585.43263297,
1407741.26932059,1291863.83104915,1307114.51528524,1526274.30718303,
1543401.08143375),.Dim=c(8L,2L))),class=c("XY","POLYGON",
"sfg"))),n_empty=0L,crs=structure(list(epsg=NA_integer_,
proj4string="+proj=lcc +lat_1=49 +lat_2=77 +lat_0=63.390675 +lon_0=-91.86666666666666 +x_0=6200000 +y_0=3000000 +datum=NAD83 +units=m +no_defs"),.Names=c("epsg",
"proj4string"),class="crs"),class=c("sfc_POLYGON","sfc"
),precision=0,bbox=structure(c(7084173.97898201,1291863.83104915,
7350510.84982176,1587647.67844029),.Names=c("xmin","ymin",
"xmax","ymax"),class="bbox"))),.Names=c("id","geometry"
),row.names=c(NA,-1L),class=c("sf","data.frame"),sf_column="geometry",agr=structure(NA_integer_,.Names="id",.Label=c("constant",
"aggregate","identity"),class="factor"))

```

ploting a polygon
```
dev.off()
plot(pol, col="white")
```

gives: 
![1](https://user-images.githubusercontent.com/10979480/35338521-28fa08bc-00ec-11e8-887c-78476735bd6b.jpeg)

Then, adding points to a polygon:
```
plot(pts, add=T)
```
gives this:
![2](https://user-images.githubusercontent.com/10979480/35338534-2f7e8802-00ec-11e8-8b34-925499175086.jpeg)

The polygon disappeared even if I use  `add = T` and there is not points showing.

Then, calling this code:

```
dev.off()
plot(pol, col="white")
plot(pts, col=1, add=T)
```

works and gives:
![3](https://user-images.githubusercontent.com/10979480/35338644-75a63cb2-00ec-11e8-9370-b0c22aab1b32.jpeg)

Note that I use `dev.off()` because without it, another weird behaviour appears:

```
dev.off()
plot(pol, col="white")
plot(pts, add=T)
plot(pol, col="white")
plot(pts, col=1, add=T)
```

gives:
![4](https://user-images.githubusercontent.com/10979480/35338708-a20d5588-00ec-11e8-8e76-4e389f159494.jpeg)

and, calling it again:
 ```
plot(pol, col="white")
```
gives:
![5](https://user-images.githubusercontent.com/10979480/35338768-c726d38a-00ec-11e8-9ea9-7ce6e8b0192b.jpeg)

and again:
```
plot(pol, col="white")
```
gives:
![6](https://user-images.githubusercontent.com/10979480/35338787-d10a54bc-00ec-11e8-949e-59d5ddd35f25.jpeg)

Is it a bug or something I don't understand.  There may also be 2 issues in this same case...

My `sessionInfo()`

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.6-1

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  magrittr_1.5    class_7.3-14    tools_3.4.3    
 [5] DBI_0.7         units_0.5-1     Rcpp_0.12.15    udunits2_0.13  
 [9] grid_3.4.3      e1071_1.6-8     classInt_0.1-24
```

**Comment by jsta** [comment]
I can reproduce this. One thing I notice is that something seems to be off about the projection of your objects:

`pol2 <- st_transform(pol, 4326)`

> OGR: Corrupt data
Error in CPL_crs_equivalent(e1$proj4string, e2$proj4string) : OGR error

yet

`st_is_valid(pol)`

> TRUE

**Comment by edzer** [comment]
The objects pol and pts are corrupt: there are no spaces before the `+` signs in the proj4strings; they do illustrate the points made, though.

**Comment by BastienFR** [comment]
About the projection, it seems to be an artifact of sharing shapes from `dput`.  I've tried `pol2 <- st_transform(pol, 4326)` both with my shape produce with `dput` and given here and my original shape and the problem occurs only with the `dput` one.  However, this has no impact on the plotting problem as in both case, I have it.

**Comment by edzer** [comment]
When I use `dput` on an `sf` object, it doesn't remove the spaces in the `proj4string`.

**Comment by BastienFR** [comment]
You're right, I remembre using a search and replace to remove the white space after pasting my code in rstudio to make it smaller, my bad...

**Comment by edzer** [comment]
Pls try again; I hope this solves the main issues, and results will be more intuitive this way.

**Comment by BastienFR** [comment]
Thanks, 
Your update did fix the problem, but now the use of `add=T` remove the legend totally.  try:

```
plot(pol, col="white")
plot(pts, add=T) # no legend
plot(pts, add=F) # legend but different extent and polygon. 
```

I understand it may be hard to get the legend in that case (I suspect you are using the `layout` function) as when you plot the polygon, you do not know a point shape with a legend is coming.  However, plotting the points before the polygon would not work as it will create the wrong extent and the polygon would hide the points anyway.  Hopefully there is a way to implement this.  Right now however, there is a work around that require only two lines of code:

```
ext <- st_bbox(pol)
plot(pts, xlim=ext[c(1,3)], ylim=ext[c(2,4)])
plot(pol, col="white", add=T)
plot(pts, add=T) 
```

That works but I'm afraid with shape with lots of point features, it will double the display and loading time.


Thanks

**Comment by edzer** [comment]
Yes, this is what I had in mind how it should work; the documentation will need some more work to point this out and to inform users that this is the way. Avoid the double plotting of the points with
```r
plot(pol, col=NA, add=T)
```

**Comment by BastienFR** [comment]
Great, thanks.
Avoiding the double plotting will be possible only if we plot empty polygons.  If we want colors in the polygon we won't have the choice but to plot the points twice.

**Comment by edzer** [comment]
That is indeed how it is, now.
