### ISSUE TITLE
lwgeom in sf_extSoftVersion()

### ISSUE THREAD

**Issue by rnuske** [r-spatial/sf#627]
The vector returned by `sf_extSoftVersion()` still lists `lwgeom`.

Looking at that vector and `?sf_extSoftVersion` I somehow expected that `sf` could/should depend on lwgeom. Maybe not as a required dependency but as an optional. But the DESCRIPTION does not mention lwgeom and the value for lwgeom in the vector is always `NA` (reveals the source code in `init.R`).

Wouldn't it be more consistent to remove `lwgeom` from the return value of  `sf_extSoftVersion()`?
If this is not possible, it might be helpful to discuss it on the help page of sf_extSoftVersion().

**Comment by edzer** [comment]
Thanks, yes, that should be removed.
