### ISSUE TITLE
osx binaries on CRAN for sf and rgdal lack proj datum files.

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#629]
Based on a test causing an error in lwgeom on CRAN flavor r-release-osx seen [here](https://cran.rstudio.com/web/checks/check_results_lwgeom.html) (0.1-4, accepted, removes the test) I found out that the sf binary for osx doesn't have the datum files of http://download.osgeo.org/proj/proj-datumgrid-1.6.zip . It appears the same is true for rgdal osx (no surprise, as the configure script was reused). Windows binaries do have them (see details below). Is this intentional, and if not how shall we resolve this for sf and rgdal? @rsbivand 

<details>

```sh
$ tar ztvf rgdal_1.2-16.tgz  | grep proj
drwxrwxr-x root/admin        0 2017-11-22 06:22 rgdal/proj/
-rw-rw-r-- root/admin     1175 2017-11-22 06:22 rgdal/proj/CH
-rw-rw-r-- root/admin   854691 2017-11-22 06:22 rgdal/proj/epsg
-rw-rw-r-- root/admin   453436 2017-11-22 06:22 rgdal/proj/esri
-rw-rw-r-- root/admin    76652 2017-11-22 06:22 rgdal/proj/esri.extra
-rw-rw-r-- root/admin      694 2017-11-22 06:22 rgdal/proj/GL27
-rw-rw-r-- root/admin    83441 2017-11-22 06:22 rgdal/proj/IGNF
-rw-rw-r-- root/admin     6385 2017-11-22 06:22 rgdal/proj/nad.lst
-rw-rw-r-- root/admin    19501 2017-11-22 06:22 rgdal/proj/nad27
-rw-rw-r-- root/admin    16559 2017-11-22 06:22 rgdal/proj/nad83
-rw-rw-r-- root/admin     3916 2017-11-22 06:22 rgdal/proj/other.extra
-rw-rw-r-- root/admin      261 2017-11-22 06:22 rgdal/proj/proj_def.dat
-rw-rw-r-- root/admin     7043 2017-11-22 06:22 rgdal/proj/world
-rw-rw-r-- root/admin   272735 2017-11-22 06:22 rgdal/gdal/projop_wparm.csv
$ unzip -l rgdal_1.2-16.zip | grep proj
   278765  2018-01-27 04:25   rgdal/gdal/projop_wparm.csv
        0  2018-01-27 04:25   rgdal/proj/
  1053928  2018-01-27 04:25   rgdal/proj/alaska
     1175  2018-01-27 04:25   rgdal/proj/CH
   264424  2018-01-27 04:25   rgdal/proj/conus
   854691  2018-01-27 04:25   rgdal/proj/epsg
   453436  2018-01-27 04:25   rgdal/proj/esri
    76652  2018-01-27 04:25   rgdal/proj/esri.extra
     8872  2018-01-27 04:25   rgdal/proj/FL
      694  2018-01-27 04:25   rgdal/proj/GL27
   452008  2018-01-27 04:25   rgdal/proj/hawaii
    83441  2018-01-27 04:25   rgdal/proj/IGNF
     3560  2018-01-27 04:25   rgdal/proj/MD
     6385  2018-01-27 04:25   rgdal/proj/nad.lst
    19501  2018-01-27 04:25   rgdal/proj/nad27
    16559  2018-01-27 04:25   rgdal/proj/nad83
   277424  2018-01-27 04:25   rgdal/proj/ntf_r93.gsb
  1113184  2018-01-27 04:25   rgdal/proj/ntv1_can.dat
      232  2018-01-27 04:25   rgdal/proj/null
   318464  2018-01-27 04:25   rgdal/proj/nzgd2kgrid0005.gsb
     3916  2018-01-27 04:25   rgdal/proj/other.extra
      261  2018-01-27 04:25   rgdal/proj/proj_def.dat
    26728  2018-01-27 04:25   rgdal/proj/prvi
      618  2018-01-27 04:25   rgdal/proj/README.DATUMGRID
    59208  2018-01-27 04:25   rgdal/proj/stgeorge
    26728  2018-01-27 04:25   rgdal/proj/stlrnc
     7048  2018-01-27 04:25   rgdal/proj/stpaul
     4424  2018-01-27 04:25   rgdal/proj/TN
     6760  2018-01-27 04:25   rgdal/proj/WI
    11112  2018-01-27 04:25   rgdal/proj/WO
     7043  2018-01-27 04:25   rgdal/proj/world
```

</details>

**Comment by rsbivand** [comment]
Not intentional, indeed, the test using `conus` on failure suggests installing the file:

```
if test "$WARN" = "warn" ; then
    echo "Note: proj/conus not found"
    echo "No support available in PROJ4 for NAD grid datum transformations"
    echo "If required, consider re-installing from source with the contents"
    echo "of proj-datumgrid-1.<latest>.zip from http://download.osgeo.org/proj/ in nad/."
fi
```
In fact, for recent proj, the grids are no longer built from source *.lla files, so can simply be unpacked by the user. Only direct resolution for OSX CRAN binaries is through Simon.

**Comment by edzer** [comment]
We can also do that for the user, so that we're not affected every time Simon sets up a new build environment. E.g. package udunits2 ships the udunits database, and pkg lwgeom ships liblwgeom, and they only fall back to using the shipped version when it is not present on the system.

**Comment by rsbivand** [comment]
The zipped 1.6 datumgrid file is 2.8MB, but beyond that, they are looking at [vdatum](http://download.osgeo.org/proj/vdatum/), which raises the volumes a lot (drat?). Initially, rgdal shipped with latest proj4 and gdal share folders, but simply setting them to be used. This was removed on the insistence of US govt labs, who needed control ov the versions uses across applications.

**Comment by edzer** [comment]
I see. I think I'll add a startup message then in case not found, indicating which files need to be copied where. Does rgdal (or gdal, or proj) have a simple checking mechanism it has found datum files?

**Comment by rsbivand** [comment]
The same one sf has in `configure.ac` around line 426? Both sf and rgdal only warn, I think.

**Comment by edzer** [comment]
Yes, at compile time; I was thinking to warn at package load time. The thing is more tricky than I thought, since it may be hard to tell at load time whether the datum files should be installed in `system.file("proj", package = "sf")` or in some system file.

**Comment by rsbivand** [comment]
The runtime check is:

```
library(rgdal)
projNAD()
```

(lifted from configure.ac) but isn't used, I think.
