### ISSUE TITLE
str() not working on output from st_distance

### ISSUE THREAD

**Issue by BastienFR** [r-spatial/sf#631]
It's not a big bug, and I don't know if it's a problem with `sf`, but I get an error when calling `str` on the result from the `st_distance` function:

```
fname = system.file("shape/nc.shp", package = "sf")
nc = read_sf(fname)

test <- st_distance(nc, by_element = F)
str(test)
Error in Ops.units(ao, 1e-10) : 
  both operands of the expression should be "units" objects
```

I work a lot with `str` so it's kind of annoying.  There an easy way around: 

```
dim(test)
[1] 100 100
class(test)
[1] "units"
```

However, I think it's still important to report it as `str` is an important basic function.

Thanks

**Comment by edzer** [comment]
Thanks; I filed the issue [here](https://github.com/r-quantities/units/issues/100). For now, you need to do
```r
str(unclass(test))
```
