### ISSUE TITLE
lwgeom required

### ISSUE THREAD

**Issue by Hamed51** [r-spatial/sf#635]
@edzer @jeroen 
 Hello, 
i could not work with tmap. this is an error : "package lwgeom required, please install it first"
i followed instruction for updating sf, from https://github.com/r-spatial/sf/issues/349 and i didbrew install postgis. everything installed but still have issue with both sf and sp class on tmap. 
i download sf from source .library("sf", lib.loc="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
Linking to GEOS 3.6.2, GDAL 2.2.3, proj.4 4.9.3.
but it is not link  to lmgeom or llwgeom. R not detected lwgeom. i tried to download the lwgeom package from cran by brew but encounter to issue. 

please advise .

**Comment by edzer** [comment]
If you want to go the brew path you need to install lwgeom from source. Please report the exact commands you followed to do this, and the output you got, in case it didn't work out.

**Comment by Hamed51** [comment]
Hi,  this is my commands for installation : brew install postgis.  After you advising to install from source, i tried agin by :brew install liblwgeom and this is the outpout:Hameds-MBP:~ hamed$ brew install liblwgeomWarning: liblwgeom 2.1.5_3 is already installedHameds-MBP:~ hamed$  thanks 

    On Thursday, February 1, 2018 9:07 AM, Edzer Pebesma <notifications@github.com> wrote:
 

 If you want to go the brew path you need to install lwgeom from source. Please report the exact commands you followed to do this, and the output you got, in case it didn't work out.—

**Comment by edzer** [comment]
You have now installed the system libraries for liblwgeom, but not yet the R package using it. Try, in R:
```r
install.packages("lwgeom")
```
and if that doesn't work
```r
install.packages("lwgeom", type = "source")
```

**Comment by Hamed51** [comment]
the second  address "install.packages("lwgeom", type = "source")", work for me and i could install.
Thank you very much and appreciate  your help.
 

    On Thursday, February 1, 2018 1:11 PM, Edzer Pebesma <notifications@github.com> wrote:
 

 You have now installed the system libraries for liblwgeom, but not yet the R package using it. Try, in R:install.packages("lwgeom")and if that doesn't workinstall.packages("lwgeom", type = "source")—
