### ISSUE TITLE
Example in vignette 1 errors: lwgeom required

### ISSUE THREAD

**Issue by Henrik-P** [r-spatial/sf#637]
Thanks for an excellent package!

I'm working through [Vignette 1](https://cran.r-project.org/web/packages/sf/vignettes/sf1.html). In the **Units** section, `a <- st_area(nc[1,])` generates an error:

> Error in st_area(nc[1, ]) : 
  package lwgeom required, please install it first

I see that it is listed as "Suggests" on the CRAN page.

**Comment by edzer** [comment]
Yes, intentionally. Why is that an issue?

**Comment by Henrik-P** [comment]
OK! I was just slightly surprised that the error was undocumented in the vignette itself _given_ the very nice, thorough and consistent presentation of code and output throughout the vignettes.

There's of course absolutely no problem with a 'Suggests' package and this 'issue' is for sure opinion-based ;) No big deal. Again, thanks for your great work!

**Comment by edzer** [comment]
I agree that it makes sense to make the dependency stronger; I will do this when lwgeom compiles for r-oldrel-osx (Mavericks); right now, that platform seems to be malfunctioning so there is little else I can do than wait.
