### ISSUE TITLE
[Documentation] Visualization of geometric binary predicates?

### ISSUE THREAD

**Issue by Henrik-P** [r-spatial/sf#638]
In `?geos_binary_pred` and in Vignette 1 and 3 there are examples of the output from various binary predicates. I believe a useful addition would be a graphic representation of these spatial relations. Either with explicit code and output, similar to [Operations returning a geometry in Vignette 3](https://cran.r-project.org/web/packages/sf/vignettes/sf3.html#operations-returning-a-geometry), or a link to a nice site describing it graphically.

Indeed, in the help text, you link to [the Wiki page of DE-9IM](https://en.wikipedia.org/wiki/DE-9IM). However, the graphical examples there are not comprehensive. For example, I fail to find an equivalent of `sf_contains_properly`.

Thanks a lot for your great work!

**Comment by edzer** [comment]
I don't think that you can visualize that predicate properly; it is described in the help file, thought. Thanks for the suggestion, we will work on visualisations when we find time.
