### ISSUE TITLE
st_union() %>% st_sf() drops 'geometry' column name?

### ISSUE THREAD

**Issue by jdeines** [r-spatial/sf#640]
Hi all,

I'm trying to dissolve/combine several features into one. The st_union() %>% st_sf() method seems most appropriate for my purpose, but the result won't plot in ggplot:

```r
nc <- st_read(system.file("shape/nc.shp", package="sf")) 
nc_union <- nc %>% st_union() %>% st_sf()  
ggplot(nc_union) + geom_sf()
```

Error in FUN(X[[i]], ...) : object 'geometry' not found

Looking into nc_union, it has the geometry column but no name (".")

This fixes it, for ggplot at least:

```r
names(nc_union) <- 'geometry'  
st_geometry(nc_union) <- 'geometry'  
ggplot(nc_union) + geom_sf()
```

I updated the development versions of both sf and ggplot packages on 2/15 when I first found the issue. Is this a bug or am I doing something suboptimally?

This is my first time posting an issue here, feedback welcome.

**Comment by edzer** [comment]
Thanks for posting!

For reasons known to those who understand ggplot internals (not me),
```r
ggplot(nc_union) + geom_sf()
```
only works if the geometry column is named `geometry`, which is often not the case; if you try
```r
nc = st_read(system.file("gpkg/nc.gpkg", package="sf"))
```
you get the same error. Try instead
```r
ggplot() + geom_sf(data = nc_union)
```

**Comment by jdeines** [comment]
Great, thanks! I wasn't sure if it would cause other problems down the pipeline within `sf`.

**Comment by edzer** [comment]
It's not something we can solve on the `sf` side, and apparently neither on the ggplot2 side, but the issue here might help future users running into the same problem.
