### ISSUE TITLE
binary operations fail on tibble sf objects when they have common column names

### ISSUE THREAD

**Issue by ateucher** [r-spatial/sf#644]
When using a binary operation such as `st_interesction` on `sf` objects that are `tibbles` fails if the two objects have column names in common:

``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, proj.4 4.9.3

pol1 <- st_sfc(st_polygon(list(cbind(c(0,3,3,0,0),c(0,0,3,3,0)))))
pol2 <- pol1 + 1
sf1 <- st_sf(id = 1, pol1)
sf2 <- st_sf(id = 2, pol2)

st_intersection(sf1, sf2) 
#> Warning: attribute variables are assumed to be spatially constant
#> throughout all geometries
#> Simple feature collection with 1 feature and 2 fields
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 1 xmax: 3 ymax: 3
#> epsg (SRID):    NA
#> proj4string:    NA
#>   id id.1                           pol1
#> 1  1    2 POLYGON ((1 3, 3 3, 3 1, 1 ...

# Convert to tibbles
sf1 <- st_as_sf(tibble::as_tibble(sf1))
sf2 <- st_as_sf(tibble::as_tibble(sf2))

st_intersection(sf1, sf2)
#> Warning: attribute variables are assumed to be spatially constant
#> throughout all geometries
#> Error: Column `id` must have a unique name
```

This is happening in `geos_op2_df()` here: https://github.com/r-spatial/sf/blob/2de29bf9c810be314c226d2519d6f60459ba8b2e/R/geom.R#L748, where `dplyr::tbl_df()` throws an error when the `data.frame` has duplicated column names. (Incidentally `dplyr::tbl_df()` should probably be replaced by `tibble::as_tibble()` as the former is deprecated).

I think it could be fixed by replacing `df = cbind(df, y[idx[,2], , drop = FALSE])` with `df = data.frame(df, y[idx[,2], , drop = FALSE])` since `cbind.data.frame()` is just a wrapper for `data.frame(..., check.names = FALSE)`. Using `data.frame()` instead of `cbind()` would fix the column names before it's passed into `dplyr::tbl_df()`.

If you think that's a good route to go I can submit a PR with a new test and a fix.

**Comment by edzer** [comment]
Yes, please go ahead -- thanks!
