### ISSUE TITLE
Fill missing when alpha != 1

### ISSUE THREAD

**Issue by kstierhoff** [r-spatial/sf#646]
Hi,
I'm experiencing a weird behavior where the fill of a geom_sf goes missing when a portion of the geom is outside the limits of the plot. I hope that I can demonstrate that here. If this is more of a ggplot2 issue, let me know and I'll post there instead.

The code below produces a figure that has all levels colored appropriately:

```
# Read shapefile
tanner_poly  <- read_sf("tanner_polygons_wgs84.shp") # Data attached as .zip (hopefully)
# Create plot
ggplot() + geom_sf(mapping = aes(fill = stratum), data = tanner_poly) +
    scale_fill_manual(name = 'Depth\nStratum',
                      values = c("30-40 m" = "red","40-50 m" = "yellow","50-60 m" = "green")) +
    coord_sf() +
    theme_bw()
```
![image](https://user-images.githubusercontent.com/2256746/36497893-87171762-16f1-11e8-9316-b88fd310645c.png)

If you zoom the plot and leave alpha = 1, all fills are present (omitted here for space).

However, when the plot limits are set to exclude a portion of the green polygon, and the alpha is set to anything other than 1, the fill for that level goes missing.

```
# Create plot with reduced limits and alpha != 1
ggplot() + geom_sf(mapping = aes(fill = stratum), data = tanner_poly, alpha = 0.9) +
    scale_fill_manual(name = 'Depth\nStratum',
                      values = c("30-40 m" = "red","40-50 m" = "yellow","50-60 m" = "green")) +
    scale_x_continuous(limits = c(-119.165, -119.095),expand = c(0,0)) +
    scale_y_continuous(limits = c(32.681, 32.719),expand = c(0,0)) +
    coord_sf() +
    theme_bw()
```

![image](https://user-images.githubusercontent.com/2256746/36497993-d6e19f74-16f1-11e8-87d6-b3deb8519f5b.png)

Can you explain this behavior, or is this a bug? I tried to attach the shapefile as a .zip, not sure if that will work...

[tanner.zip](https://github.com/r-spatial/sf/files/1745254/tanner.zip)

Thanks!
Kevin

**Comment by edzer** [comment]
Interesting - for me it works fine! What is your output of sessionInfo()?
![x](https://user-images.githubusercontent.com/520851/36498759-9b5eee9a-173f-11e8-90a8-2bcd38fc8760.png)

**Comment by kstierhoff** [comment]
Hi Edzer, thanks for the quick reply. Here is my sessionInfo().

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2       surveyR_0.2        here_0.1           kableExtra_0.7.0   maptools_0.9-2     sf_0.6-0           forcats_0.2.0      stringr_1.2.0     
 [9] dplyr_0.7.4        purrr_0.2.4        readr_1.1.1        tidyr_0.7.2        tibble_1.4.2       tidyverse_1.2.1    knitr_1.18         flextable_0.4.2   
[17] raster_2.6-7       sp_1.2-7           png_0.1-7          RODBC_1.3-15       cowplot_0.9.2      ggplot2_2.2.1.9000 testthat_2.0.0     usethis_1.2.0     
[25] devtools_1.13.4   

loaded via a namespace (and not attached):
 [1] httr_1.3.1        viridisLite_0.2.0 jsonlite_1.5      R.utils_2.6.0     modelr_0.1.1      assertthat_0.2.0  cellranger_1.1.0  yaml_2.1.16      
 [9] gdtools_0.1.6     pillar_1.1.0      backports_1.1.2   lattice_0.20-35   glue_1.2.0        uuid_0.1-2        digest_0.6.14     rvest_0.3.2      
[17] colorspace_1.3-2  htmltools_0.3.6   R.oo_1.21.0       plyr_1.8.4        psych_1.7.8       pkgconfig_2.0.1   broom_0.4.3       haven_1.1.1      
[25] scales_0.5.0.9000 officer_0.2.1     withr_2.1.1.9000  lazyeval_0.2.1    cli_1.0.0         mnormt_1.5-5      magrittr_1.5      crayon_1.3.4     
[33] readxl_1.0.0      memoise_1.1.0     evaluate_0.10.1   R.methodsS3_1.7.1 nlme_3.1-131      xml2_1.2.0        foreign_0.8-69    class_7.3-14     
[41] tools_3.4.3       hms_0.4.1         munsell_0.4.3     zip_1.0.0         compiler_3.4.3    e1071_1.6-8       rlang_0.1.6       classInt_0.1-24  
[49] units_0.5-1       grid_3.4.3        rstudioapi_0.7    base64enc_0.1-3   rmarkdown_1.8     gtable_0.2.0      DBI_0.7           reshape2_1.4.3   
[57] R6_2.2.2          lubridate_1.7.1   udunits2_0.13     bindr_0.1         rprojroot_1.3-2   stringi_1.1.6     parallel_3.4.3    Rcpp_0.12.15

**Comment by edzer** [comment]
Have you tried with only loading `sf` and `ggplot2`? Have you tried installing the latest ggplot2 from github?

**Comment by kstierhoff** [comment]
I get the same missing fill with only ggplot2 and sf loaded (code below). I think I was already using the dev version of ggplot ( 2.2.1.9000).

```
library(ggplot2)
library(sf)

tanner_poly  <- read_sf("tanner_polygons_wgs84.shp")

ggplot() + geom_sf(mapping = aes(fill = stratum), data = tanner_poly, alpha = 0.9) +
  scale_fill_manual(name = 'Depth\nStratum',
                    values = c("30-40 m" = "red","40-50 m" = "yellow","50-60 m" = "green")) +
  scale_x_continuous(limits = c(-119.165, -119.095),expand = c(0,0)) +
  scale_y_continuous(limits = c(32.681, 32.719),expand = c(0,0)) +
  coord_sf() +
  theme_bw()
```

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.6-0           ggplot2_2.2.1.9000 testthat_2.0.0     usethis_1.2.0      devtools_1.13.4   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15      bindr_0.1         magrittr_1.5      units_0.5-1       munsell_0.4.3     colorspace_1.3-2  R6_2.2.2          rlang_0.1.6      
 [9] dplyr_0.7.4       udunits2_0.13     plyr_1.8.4        tools_3.4.3       grid_3.4.3        gtable_0.2.0      e1071_1.6-8       DBI_0.7          
[17] withr_2.1.1.9000  class_7.3-14      assertthat_0.2.0  yaml_2.1.16       lazyeval_0.2.1    rprojroot_1.3-2   digest_0.6.14     tibble_1.4.2     
[25] bindrcpp_0.2      glue_1.2.0        memoise_1.1.0     compiler_3.4.3    pillar_1.1.0      scales_0.5.0.9000 backports_1.1.2   classInt_0.1-24  
[33] pkgconfig_2.0.1

**Comment by edzer** [comment]
`geom_sf` had a large update in November, did you install after that?

**Comment by edzer** [comment]
1devtools::session_info()`

**Comment by kstierhoff** [comment]
Hi, I did a clean install of R v 3.4.2 and installed ggplot2 and sf from github. Still getting the same behavior. Not sure whether I've introduced yet another variable into the equation by using an older version of R, but I'm happy to try any troubleshooting suggestions you may have, even if that includes removing v 3.4.3 and starting over. Below is the session_info() from this latest test.

`library(ggplot2)
library(sf)

tanner_poly  <- read_sf("tanner_polygons_wgs84.shp")

ggplot() + geom_sf(mapping = aes(fill = stratum), data = tanner_poly, alpha = 0.5) +
  scale_fill_manual(name = 'Depth\nStratum',
                    values = c("30-40 m" = "red","40-50 m" = "yellow","50-60 m" = "green")) +
  scale_x_continuous(limits = c(-119.165, -119.095),expand = c(0,0)) +
  scale_y_continuous(limits = c(32.681, 32.719),expand = c(0,0)) +
  coord_sf() +
  theme_bw()

devtools::session_info()`

Session info --------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, mingw32             
 ui       RStudio (1.1.408)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2018-02-21                  

Packages ------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                            
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.3)                    
 backports    1.1.2      2017-12-13 CRAN (R 3.4.3)                    
 base       * 3.4.2      2017-09-28 local                             
 bindr        0.1        2016-11-13 CRAN (R 3.4.3)                    
 bindrcpp     0.2        2017-06-17 CRAN (R 3.4.3)                    
 class        7.3-14     2015-08-30 CRAN (R 3.4.2)                    
 classInt     0.1-24     2017-04-16 CRAN (R 3.4.3)                    
 colorspace   1.3-2      2016-12-14 CRAN (R 3.4.3)                    
 compiler     3.4.2      2017-09-28 local                             
 datasets   * 3.4.2      2017-09-28 local                             
 DBI          0.7        2017-06-18 CRAN (R 3.4.3)                    
 devtools   * 1.13.5     2018-02-18 CRAN (R 3.4.3)                    
 digest       0.6.15     2018-01-28 CRAN (R 3.4.3)                    
 dplyr        0.7.4      2017-09-28 CRAN (R 3.4.3)                    
 e1071        1.6-8      2017-02-02 CRAN (R 3.4.3)                    
 ggplot2    * 2.2.1.9000 2018-02-21 Github (tidyverse/ggplot2@39e4a3b)
 glue         1.2.0      2017-10-29 CRAN (R 3.4.3)                    
 graphics   * 3.4.2      2017-09-28 local                             
 grDevices  * 3.4.2      2017-09-28 local                             
 grid         3.4.2      2017-09-28 local                             
 gtable       0.2.0      2016-02-26 CRAN (R 3.4.3)                    
 lazyeval     0.2.1      2017-10-29 CRAN (R 3.4.3)                    
 magrittr     1.5        2014-11-22 CRAN (R 3.4.3)                    
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.3)                    
 methods    * 3.4.2      2017-09-28 local                             
 munsell      0.4.3      2016-02-13 CRAN (R 3.4.3)                    
 pillar       1.1.0      2018-01-14 CRAN (R 3.4.3)                    
 pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.3)                    
 plyr         1.8.4      2016-06-08 CRAN (R 3.4.3)                    
 R6           2.2.2      2017-06-17 CRAN (R 3.4.3)                    
 Rcpp         0.12.15    2018-01-20 CRAN (R 3.4.3)                    
 rlang        0.2.0.9000 2018-02-21 Github (tidyverse/rlang@75e7fd9)  
 rprojroot    1.3-2      2018-01-03 CRAN (R 3.4.3)                    
 scales       0.5.0.9000 2018-02-21 Github (hadley/scales@d767915)    
 sf         * 0.6-1      2018-02-21 Github (r-spatial/sf@466bee6)     
 stats      * 3.4.2      2017-09-28 local                             
 testthat   * 2.0.0      2017-12-13 CRAN (R 3.4.3)                    
 tibble       1.4.2      2018-01-22 CRAN (R 3.4.3)                    
 tools        3.4.2      2017-09-28 local                             
 udunits2     0.13       2016-11-17 CRAN (R 3.4.1)                    
 units        0.5-1      2018-01-08 CRAN (R 3.4.3)                    
 usethis    * 1.2.0      2018-01-19 CRAN (R 3.4.3)                    
 utils      * 3.4.2      2017-09-28 local                             
 withr        2.1.1.9000 2018-02-21 Github (jimhester/withr@5d05571)  
 yaml         2.1.16     2017-12-12 CRAN (R 3.4.3)

**Comment by yutannihilation** [comment]
I'm not sure if you're using RStudio, but this might be related; an issue about alpha that occurs only on Windows:

https://github.com/rstudio/rstudio/issues/2196#issuecomment-365720350

If so, you can try Zoom button or ggsave().

**Comment by kstierhoff** [comment]
Hi,
Thanks for that recommendation. Yes, I am using Rstudio and principally on Windows. I have a Mac that I could test on but don't think I'll pursue this much further. I updated the latest Rstudio preview, updated to all latest github versions of ggplot2 and sf, and ran on R version 3.4.3 and 3.4.2, all with the same result, and also tested these variations on a different Windows laptop. 

It would be interesting to have someone else test on a Windows machine to learn whether something wonky is happening with my machine. Or to know whether Edzer is using a Mac. 

I'll let Edzer decide whether to close this issue or explore it further.

Cheers,
Kevin

**Comment by yutannihilation** [comment]
Thanks Kevin for the detail. I could reproduce this issue on my Windows. Sorry, this issue seems irelavant to the issue I pointed since Zoom or ggsave() won't help this time...

**Comment by kstierhoff** [comment]
Thank you for testing, which will keep me from nuking my installation at work tomorrow! I was also able to confirm that it worked on my Mac, session info below.

Session info -------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2018-02-21                  

Packages -----------------------------------------------------------------------------------------------------------
 package    * version    date       source                            
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)                    
 base       * 3.4.3      2017-12-07 local                             
 bindr        0.1        2016-11-13 CRAN (R 3.4.0)                    
 bindrcpp     0.2        2017-06-17 CRAN (R 3.4.0)                    
 class        7.3-14     2015-08-30 CRAN (R 3.4.3)                    
 classInt     0.1-24     2017-04-16 CRAN (R 3.4.0)                    
 colorspace   1.3-2      2016-12-14 CRAN (R 3.4.0)                    
 compiler     3.4.3      2017-12-07 local                             
 curl         3.1        2017-12-12 CRAN (R 3.4.3)                    
 datasets   * 3.4.3      2017-12-07 local                             
 DBI          0.7        2017-06-18 CRAN (R 3.4.0)                    
 devtools   * 1.13.5     2018-02-18 CRAN (R 3.4.3)                    
 digest       0.6.15     2018-01-28 CRAN (R 3.4.3)                    
 dplyr        0.7.4      2017-09-28 CRAN (R 3.4.2)                    
 e1071        1.6-8      2017-02-02 CRAN (R 3.4.0)                    
 ggplot2    * 2.2.1.9000 2018-02-10 Github (tidyverse/ggplot2@2b5b88d)
 git2r        0.21.0     2018-01-04 CRAN (R 3.4.3)                    
 glue         1.2.0      2017-10-29 CRAN (R 3.4.2)                    
 graphics   * 3.4.3      2017-12-07 local                             
 grDevices  * 3.4.3      2017-12-07 local                             
 grid         3.4.3      2017-12-07 local                             
 gtable       0.2.0      2016-02-26 CRAN (R 3.4.0)                    
 httr         1.3.1      2017-08-20 CRAN (R 3.4.1)                    
 knitr        1.19       2018-01-29 CRAN (R 3.4.3)                    
 lazyeval     0.2.1      2017-10-29 CRAN (R 3.4.2)                    
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                    
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                    
 methods    * 3.4.3      2017-12-07 local                             
 munsell      0.4.3      2016-02-13 CRAN (R 3.4.0)                    
 pillar       1.1.0      2018-01-14 CRAN (R 3.4.3)                    
 pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.0)                    
 plyr         1.8.4      2016-06-08 CRAN (R 3.4.0)                    
 R6           2.2.2      2017-06-17 CRAN (R 3.4.0)                    
 Rcpp         0.12.15    2018-01-20 CRAN (R 3.4.3)                    
 rlang        0.1.6.9003 2018-02-10 Github (tidyverse/rlang@616fd4d)  
 scales       0.5.0.9000 2018-02-10 Github (hadley/scales@d767915)    
 sf         * 0.6-0      2018-01-06 CRAN (R 3.4.3)                    
 stats      * 3.4.3      2017-12-07 local                             
 tibble       1.4.2      2018-01-22 CRAN (R 3.4.3)                    
 tools        3.4.3      2017-12-07 local                             
 udunits2     0.13       2016-11-17 CRAN (R 3.4.0)                    
 units        0.5-1      2018-01-08 CRAN (R 3.4.3)                    
 utils      * 3.4.3      2017-12-07 local                             
 withr        2.1.1.9000 2018-02-10 Github (jimhester/withr@df18523)  
 yaml         2.1.16     2017-12-12 CRAN (R 3.4.3)

**Comment by mdsumner** [comment]
related? https://github.com/r-spatial/sf/issues/254

**Comment by kstierhoff** [comment]
Yes, I could see it being related. On my Mac, before installing the dev version of ggplot2, I got an error describing something about not finding the edge of the polygon. Unfortunately, I wasn't able to capture the message before R hung-up and I had to restart. :( And then I upgraded ggplot2 and everything worked.
