### ISSUE TITLE
Incorrect Perimeter for polygons

### ISSUE THREAD

**Issue by mem48** [r-spatial/sf#655]
I'm trying the calculate the perimeter of polygons using st_length.
This used to work but now seems to be buggy.

**Reproducible example**
```
library(sf)
#Make some random squares
# calculate the perimeter using sf and basic maths
# compare the ratio which should be 1 in all cases

for(n in 1:10){
  # make some random dimensions
  i = runif(1,0,10000000)
  j = runif(1,0,10000000)
  
  # make a square
  pol <- rbind(c(i,i), c(j,i), c(j,j), c(i,j), c(i,i))
  pol <- st_polygon(list(pol))
  
  # calcualte the perimeter in two ways
  perimeter.expected = 4 * sqrt((i-j)**2)
  perimeter.calc = st_length(pol)
  
  # return the ratio
  message(paste0("ratio of values is ",perimeter.calc/perimeter.expected))
}
```

I get ratios ranging from 20 to 0.003 
My sessionInfo()

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.6-0

loaded via a namespace (and not attached):
 [1] compiler_3.4.0  magrittr_1.5    class_7.3-14    DBI_0.7         tools_3.4.0     pillar_1.0.1    units_0.5-1     Rcpp_0.12.14   
 [9] udunits2_0.13   grid_3.4.0      e1071_1.6-8     classInt_0.1-24 rlang_0.1.6  
```

**Comment by edzer** [comment]
This has changed not too long ago; the docs say: "st_length returns the length of a ‘LINESTRING’ or      ‘MULTILINESTRING’ geometry, using the coordinate reference system. ‘POINT’, ‘MULTIPOINT’, ‘POLYGON’ or ‘MULTIPOLYGON’ geometries return zero." You many want to convert (`st_cast`) to `LINESTRING` first.

**Comment by mem48** [comment]
I've tried using st_cast which seems to be working, but then why is `perimeter.calc = st_length(pol)` returning non zero values?

**Comment by edzer** [comment]
I see
```
ratio of values is 0
ratio of values is 0
ratio of values is 0
ratio of values is 0
ratio of values is 0
ratio of values is 0
ratio of values is 0
ratio of values is 0
ratio of values is 0
ratio of values is 0
```

**Comment by mem48** [comment]
I see

`ratio of values is 0.331421435129165
ratio of values is 0.706819566082088
ratio of values is 0.324671583079589
ratio of values is 1.73090797071962
ratio of values is 0.310676260391194
ratio of values is 1.02934273341355
ratio of values is 0.0528733732530279
ratio of values is 0.400395463389348
ratio of values is 0.635960587199511
ratio of values is 0.972927960040458`

**Comment by mem48** [comment]
Could it be a Windows problem?

**Comment by edzer** [comment]
No, with R from CRAN I get
```
ratio of values is 0.317115512031533
ratio of values is 1.4136565245003
ratio of values is 8.55522467981434
ratio of values is 0.520596629201177
ratio of values is 0.32340095007338
ratio of values is 0.274043771994821
ratio of values is 0.375584925759271
ratio of values is 0.0794028716229541
ratio of values is 0.407710605567615
ratio of values is 0.81474273342047
```
the zeroes are from sf from github.

**Comment by mem48** [comment]
Perhaps it is worth revisiting #268 as it is now a multistep process to get something as simple as the perimeter of a polygon

**Comment by edzer** [comment]
Thanks, did so.

**Comment by edzer** [comment]
https://github.com/r-spatial/lwgeom/commit/9f9f305014cde8aefe6e3d321d152067770885ad adds `st_perimeter` and `st_perimeter_2d` to package `lwgeom`.
