### ISSUE TITLE
st_is_valid does not suppress warning

### ISSUE THREAD

**Issue by calebbraun** [r-spatial/sf#656]
Running the following raises a self-intersection warning:
```
> b0 = st_polygon(list(rbind(c(-1,-1), c(1,-1), c(1,1), c(-1,1), c(-1,-1))))
> b1 = st_polygon(list(rbind(c(-1,-1), c(1,-1), c(1,1), c(0,-1), c(-1,-1))))
> st_is_valid(st_sfc(b0,b1), NA_on_exception = TRUE)
[1]  TRUE FALSE
Warning message:
In evalq((function (..., call. = TRUE, immediate. = FALSE, noBreaks. = FALSE,  :
  Self-intersection at or near point -1 -1
```
My understanding is that if `NA_on_exception` is `TRUE` (the default), then this warning would be suppressed. The documentation says:

> NA_on_exception	
logical; if TRUE, for polygons that would otherwise raise a GEOS error (exception, e.g. for a POLYGON having more than zero but less than 4 points, or a LINESTRING having one point) return an NA rather than raising an error, and suppress warning messages (e.g. about self-intersection); 

Version info:
```
> packageVersion('sf')
[1] ‘0.6.0’
> sf_extSoftVersion()
          GEOS           GDAL         proj.4         lwgeom GDAL_with_GEOS 
       "3.6.1"        "2.2.0"        "4.9.3"             NA         "true" 
```

**Comment by edzer** [comment]
Thanks! This should fix it; for now, you can always put `suppressWarnings()` around the statement.
