### ISSUE TITLE
st_write for CSV files does not output geometry column

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/sf#658]
Just as in title: st_write does not output a geometry column if using the CSV backend.
It's pretty unlikely to be useful and workarounds are easy, anyway I'll leave this here.

**Comment by edzer** [comment]
```r
st_write(nc, "nc.csv", dataset_options = "GEOMETRY=AS_WKT")
```
learned this [here](http://www.gdal.org/drv_csv.html).

**Comment by adrfantini** [comment]
Oh, ok. `AS_WKT` is OK, but `AS_XY` doesn't seem to do anything for `POINT` coordinates.

**Comment by edzer** [comment]
```r
st_write(sf, "x.csv", layer_options = "GEOMETRY=AS_XY")
```
It's actually in the documentation of the driver; my example before must have been a lucky coincidence.
