### ISSUE TITLE
st_cast to MULTILINESTRING loses XY class

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/sf#660]
I see

```R
library(sf)
pts <- matrix(1:10, ncol = 2)
pts <- rbind(pts, head(pts, 1))
(x <- st_cast(st_sfc(st_multipolygon(list(list(pts)))), "MULTILINESTRING"))
#Geometry set for 1 feature 
#geometry type:  MULTILINESTRING
#dimension:      list
#bbox:           Error in signif(attr(x, "bbox"), options("digits")$digits) : 
#  non-numeric argument to mathematical function	  
```

sf passes all tests since this manifests at print time, because

```R
class(x[[1]])
##[1] "list"            "MULTILINESTRING" "sfg"   
```

I can see the issue is here where the object is unlisted, hence removing class, but it's assumed in the subsequent call to reclass() here: 

https://github.com/r-spatial/sf/blob/master/R/cast_sfc.R#L165

I don't see what the natural way to fix this is, apologies.

**Comment by edzer** [comment]
Thanks, well spotted!
