### ISSUE TITLE
odd behaviour of st_distance

### ISSUE THREAD

**Issue by GreenStat** [r-spatial/sf#663]
Hi

related to this issue https://github.com/r-spatial/sf/issues/437 I encountered odd behaviour of st_distance.
I am not sure if it is a lack of documentation or  a bug

I guessing there are two issues here:
 different behaviour of 'by_element=TRUE' when using sf-object or geometry direct (sfc-object)
 different behaviour  of 'by_element=TRUE' when crs of object is in long/lat 

this is the reprex:

```{r}
library(sf)

pts.sf <- data.frame(
  'x'=c(1:3),
  'y'=c(1:3)
) %>% st_as_sf(coords=c('x','y'), crs=4326)

pts1.sf <- pts.sf %>% st_transform(3857)

## now calculate distances 

st_distance(pts.sf,pts.sf)
#Error in as_units.default("m") : 
# unit unitless not found: define with make_unit?

st_distance(pts.sf,pts.sf, by_element=TRUE)
Error in as_units.default("m") : 
 unit unitless not found: define with make_unit?

st_distance(st_geometry(pts.sf),st_geometry(pts.sf))
Error in as_units.default("m") : 
 unit unitless not found: define with make_unit?

st_distance(st_geometry(pts.sf),st_geometry(pts.sf), by_element=TRUE)
1 2 3 
0 0 0 

## and the same with the 'projected' object 


st_distance(pts1.sf,pts1.sf)
Units: m
         [,1]     [,2]     [,3]
[1,]      0.0 157457.5 314963.1
[2,] 157457.5      0.0 157505.5
[3,] 314963.1 157505.5      0.0

st_distance(pts1.sf,pts1.sf, by_element=TRUE)
     geometry
 [1,]      0.0
 [2,] 157457.5
 [3,] 314963.1
 [4,] 157457.5
 [5,]      0.0
 [6,] 157505.5
 [7,] 314963.1
 [8,] 157505.5
 [9,]      0.0

st_distance(st_geometry(pts1.sf),st_geometry(pts1.sf))
Units: m
         [,1]     [,2]     [,3]
[1,]      0.0 157457.5 314963.1
[2,] 157457.5      0.0 157505.5
[3,] 314963.1 157505.5      0.0

st_distance(st_geometry(pts1.sf),st_geometry(pts1.sf), by_element=TRUE)
[1] 0 0 0
```

incidentely, I am trying to make a sf version of diff, which returns the distance **between** points
of one geometry.

this is what I came up with
``` 
st_distance(st_geometry(pts1.sf),st_geometry(pts1.sf[-1,]), by_element=TRUE)
[1] 157457.5 157505.5 157505.5
Warning message:
In mapply(st_distance, x, y, by_element = FALSE) :
  longer argument not a multiple of length of shorter
```

does anyone has any idea why the result has a length of 3? 
 based on the warning I expected 2!

Peter

**Comment by GreenStat** [comment]
forgot to mention sf version
```
> library(sf)
Linking to GEOS 3.6.1, GDAL 2.2.0, proj.4 4.9.3
```

**Comment by edzer** [comment]
Your last question is the easier one: the recycling rule
```r
> 1:2 + 1:3
[1] 2 4 4
Warning message:
In 1:2 + 1:3 :
  longer object length is not a multiple of shorter object length
```

**Comment by edzer** [comment]
I see
```r
> library(sf)
Linking to GEOS 3.5.1, GDAL 2.2.1, proj.4 4.9.3
> 
> pts.sf <- data.frame(
+   'x'=c(1:3),
+   'y'=c(1:3)
+ ) %>% st_as_sf(coords=c('x','y'), crs=4326)
> 
> pts1.sf <- pts.sf %>% st_transform(3857)
> st_distance(pts.sf,pts.sf)
Units: m
         [,1]     [,2]     [,3]
[1,]      0.0 156876.1 313705.4
[2,] 156876.1      0.0 156829.3
[3,] 313705.4 156829.3      0.0
> st_distance(pts.sf,pts.sf, by_element=TRUE)
Units: m
1 2 3 
0 0 0 
> st_distance(st_geometry(pts.sf),st_geometry(pts.sf))
Units: m
         [,1]     [,2]     [,3]
[1,]      0.0 156876.1 313705.4
[2,] 156876.1      0.0 156829.3
[3,] 313705.4 156829.3      0.0
> st_distance(st_geometry(pts.sf),st_geometry(pts.sf), by_element=TRUE)
Units: m
1 2 3 
0 0 0 
> st_distance(pts1.sf,pts1.sf)
Units: m
         [,1]     [,2]     [,3]
[1,]      0.0 157457.5 314963.1
[2,] 157457.5      0.0 157505.5
[3,] 314963.1 157505.5      0.0
> st_distance(pts1.sf,pts1.sf, by_element=TRUE)
Units: m
[1] 0 0 0
> st_distance(st_geometry(pts1.sf),st_geometry(pts1.sf))
Units: m
         [,1]     [,2]     [,3]
[1,]      0.0 157457.5 314963.1
[2,] 157457.5      0.0 157505.5
[3,] 314963.1 157505.5      0.0
> st_distance(st_geometry(pts1.sf),st_geometry(pts1.sf), by_element=TRUE)
Units: m
[1] 0 0 0
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.10

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.6-1

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  magrittr_1.5    class_7.3-14    DBI_0.7        
 [5] tools_3.4.3     units_0.5-1     Rcpp_0.12.15    udunits2_0.13  
 [9] grid_3.4.3      e1071_1.6-8     lwgeom_0.1-5    classInt_0.1-24
```
which looks pretty normal to me. You didn't specify your sf version, and maybe you want to reinstall package units (strange errors, haven't seen them before).

**Comment by GreenStat** [comment]
I try to stick to CRAN versions (sf_0.6.0) after upgrading to  0.6-1  the errors disappeared.
problem solved!

**Comment by edzer** [comment]
Cool!

**Comment by tomkom** [comment]
I would like to re-open this issue, experiencing the same problem.
I encountered it first on my dataset, but was able to exactly replicate as @GreenStat above. The issue for me is with the units. 
`sf` and all my packages are installed from CRAN. I do not think this has anything to do with the `byelement=TRUE`, though, but rather with units.


`> library(sf)
Linking to GEOS 3.6.2, GDAL 2.2.4, proj.4 5.0.1
> library(lwgeom) # for spheroidical
Linking to liblwgeom 2.4.4 r16526, GEOS 3.6.2, proj.4 5.0.1
> locations_sf = st_as_sf(locations, coords = c("lon", "lat"), crs = 4283, agr = "constant")
> dist_mat <-st_distance(locations_sf,locations_sf)
Error in as_units.default("m") : 
  unit unitless not found: define with make_unit?
> pts.sf <- data.frame(
+   'x'=c(1:3),
+   'y'=c(1:3)
+ ) %>% st_as_sf(coords=c('x','y'), crs=4326)
> pts1.sf <- pts.sf %>% st_transform(3857)
> st_distance(pts.sf,pts.sf)
Error in as_units.default("m") : 
  unit unitless not found: define with make_unit?
> st_distance(pts.sf,pts.sf, by_element=TRUE)
Error in as_units.default("m") : 
  unit unitless not found: define with make_unit?
> st_distance(st_geometry(pts.sf),st_geometry(pts.sf))
Error in as_units.default("m") : 
  unit unitless not found: define with make_unit?
> st_distance(st_geometry(pts.sf),st_geometry(pts.sf), by_element=TRUE)
Error in as_units.default("m") : 
  unit unitless not found: define with make_unit?
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin17.3.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lwgeom_0.1-4 sf_0.6-1    

loaded via a namespace (and not attached):
 [1] compiler_3.4.4  magrittr_1.5    class_7.3-14    DBI_0.7         tools_3.4.4     units_0.4-6     Rcpp_0.12.16    udunits2_0.13   grid_3.4.4      e1071_1.6-8     classInt_0.1-24`

**Comment by tomkom** [comment]
The same behaviour can be repklicated with the default example from sf docs:
`> b0 = st_polygon(list(rbind(c(-1,-1), c(1,-1), c(1,1), c(-1,1), c(-1,-1))))
> b1 = b0 + 2
> b2 = b0 + c(-0.2, 2)
> x = st_sfc(b0, b1, b2)
> st_area(x)
[1] 4 4 4
> #> [1] 4 4 4
> line = st_sfc(st_linestring(rbind(c(30,30), c(40,40))), crs = 4326)
> st_length(line)
Error in as_units.default("m") : 
  unit unitless not found: define with make_unit?`

**Comment by edzer** [comment]
You don't have the current CRAN version of units installed.
