### ISSUE TITLE
Trouble Installing Version 0.6.0

### ISSUE THREAD

**Issue by justinwinikoff** [r-spatial/sf#668]
Hello, I am trying to link with `lwgeom` so that I can use `st_is_valid`. I already have a functioning version of 0.5-5 on my computer but need apparently version 0.6.0 for lwgeom to work. Trying to install this is giving me issues. I am getting the following output (partially suppressed to just show where the error begins) when I write `install.packages("lwgeom", type="source")`:

```

checking GDAL: checking whether PROJ.4 is available fur running:... 
dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.12.dylib
  Referenced from: /usr/local/opt/gdal2/lib/libgdal.20.dylib
  Reason: image not found
./configure: line 3584: 98531 Abort trap: 6           ./gdal_proj
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ.4 not available?
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sf’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sf’
...
Error: package ‘sf’ 0.5-5 was found, but >= 0.6.0 is required by ‘lwgeom’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/lwgeom’


```

Any thoughts on how to fix this? Thanks

**Comment by edzer** [comment]
Looks like you have a broken gdal setup. Did you try install the binary sf 0.6-0 first? Or are you on Mavericks?

**Comment by justinwinikoff** [comment]
I'm on Sierra. I've tried `install.packages("sf")` and am offered the following prompt: 

```
 There is a binary version available but the source version is later:
   binary source needs_compilation
sf  0.5-5  0.6-0              TRUE

Do you want to install from sources the package which needs compilation?
y/n:
```
When I write `y`, I get the same error as described above

**Comment by edzer** [comment]
AFAICT, Sierra succeeded El Capitan, so there should be binary install available, for both sf and lwgeom; see https://cran.r-project.org/web/packages/sf/index.html

**Comment by justinwinikoff** [comment]
Excuse my ignorance here, but how do you perform a binary install? I was googling around and found that you could write `R CMD Install` in the terminal but this did not work for me. I got the error "bash: R: command not found." Should I be performing this install in R itself?

**Comment by edzer** [comment]
Which CRAN mirror do you use?

**Comment by justinwinikoff** [comment]
I did not specify one, but I use R-Studio if that helps.

**Comment by edzer** [comment]
What is the output of `sessionInfo()` on your computer?

**Comment by justinwinikoff** [comment]
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2
```

**Comment by edzer** [comment]
Then you want to install a newer version of R first.

**Comment by justinwinikoff** [comment]
wow, this seemed to do the trick. It's always something obvious like that... Thanks for your help
