### ISSUE TITLE
Can 'droplevels' be implemented after filtering a spatial feature?

### ISSUE THREAD

**Issue by NateMietk** [r-spatial/sf#670]
In this example I want to clip the spatial feature just to the lower 48 US states as follows.
First download some US states data:
`library(sf)`
`library(assertthat)`

`us_shp <- "data/cb_2016_us_state_20m/cb_2016_us_state_20m.shp"`
`if (!file.exists(us_shp)) {`
`  loc <- "https://www2.census.gov/geo/tiger/GENZ2016/shp/cb_2016_us_state_20m.zip"`
`  dest <- paste0("data/cb_2016_us_state_20m", ".zip")`
`  download.file(loc, dest)`
`  unzip(dest, exdir = "data/cb_2016_us_state_20m")`
`  unlink(dest)`
`  assert_that(file.exists(us_shp))`
`}`

Now I would like to make it so just the lower 48 states are spatially represented.

`usa <- st_read("data/cb_2016_us_state_20m/cb_2016_us_state_20m.shp", quiet= TRUE) %>%
  filter(!(STUSPS %in% c("AK", "HI", "PR")))`

If I now run `levels(usa$STUSPS)` it returns:

`52 Levels: AK AL AR AZ CA CO CT DC DE FL GA HI IA ID IL IN KS KY LA MA MD ME MI MN MO MS MT ... WY`.  

What it should read is:
`49 Levels: AL AR AZ CA CO CT DC DE FL GA IA ID IL IN KS KY LA MA MD ME MI MN MO MS MT NC ND ... WY`

But, if I used `droplevels()` to truly remove these levels by running 

`usa <- st_read("data/cb_2016_us_state_20m/cb_2016_us_state_20m.shp", quiet= TRUE) %>%`
  `filter(!(STUSPS %in% c("AK", "HI", "PR"))) %>% droplevels()` 

it returns: 
`Error in UseMethod("droplevels") : `
  `no applicable method for 'droplevels' applied to an object of class "c('sfc_MULTIPOLYGON', 'sfc')"`

**Comment by edzer** [comment]
Well, you could use `droplevels` just on the factor variable, and not on the whole object. Alternatively, if you provide a method for geometry columns first, e.g. as
```r
droplevels.sfc = function(x, except, exclude, ...) x
```
it will work for the whole object (although with a warning).

**Comment by NateMietk** [comment]
appreciate the feedback - worked like a charm.
