### ISSUE TITLE
distinct() example in ?dplyr

### ISSUE THREAD

**Issue by krlmlr** [r-spatial/sf#672]
The dev version of dplyr will soon have a message that `distinct()` does not support list columns. This will show in the example of `?dplyr` in *sf*. Maybe we want to exclude the `geometry` column when you pass on to `NextMethod()` in `distinct.sf()` ?

**Comment by edzer** [comment]
Thanks, @krlmlr ! Done, earlier Today, in https://github.com/r-spatial/sf/commit/380eb07bb58a82a545d01de524cdb62fc6eee829

Do you know btw a cleaner way of adding a temporary column?

**Comment by krlmlr** [comment]
Does `st_equals()` always fill the diagonal in the resulting (sparse) matrix? It seems so, but the documentation isn't explicit about it.

Why not just reuse the name of the existing column, and save the geometry column elsewhere?

**Comment by edzer** [comment]
Brilliant suggestion, thanks! I tried to improve the docs; yes, `st_pred(x)` is taken as `st_pred(x,x)` which is then square. And elements are sorted (this is undocumented).

**Comment by krlmlr** [comment]
Thanks. This change seems to rely on sortedness, feels like a good idea to document it and test it.
