### ISSUE TITLE
st_wrap_dateline aborts R session

### ISSUE THREAD

**Issue by juanmayorgahenao** [r-spatial/sf#674]
I'm having problems using the dev version of sf and the st_wrap_dateline function. 

Here is a classic reprex: 

```r
library(maps)
wrld <- st_as_sf(maps::map("world", fill=TRUE, plot=FALSE))
wrld_wrap <- st_wrap_dateline(wrld, options = c("WRAPDATELINE=YES"), quiet = TRUE)
wrld_moll <- st_transform(wrld_wrap, "+proj=moll")
plot(st_geometry(wrld_moll), col="transparent")
```

This breaks my session and spits out: GDAL Error 1: IllegalArgumentException: Points of LinearRing do not form a closed linestringGDAL Error 1: IllegalArgumentException: Points of LinearRing do not form a closed linestring

This is my session_info():

`R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.18    knitr_1.20   `

Any ideas what might be going on?

**Comment by edzer** [comment]
Have you seen #280?

**Comment by juanmayorgahenao** [comment]
@edzer I have. I'm afraid my issue goes beyond 'st_wrap_dateline'. Plotting any line that crosses the dateline (without wrapping the dateline) crashes my session. 

`m <-  matrix(c(168.5688,	-16.59488,	-75.69947,	-40.73869	),nrow = 2, byrow = TRUE)

line_string <- st_linestring(m)  %>% 
  st_sfc(crs = 4326) %>%
  st_sf(geometry = .)

line_string %>% 
  ggplot()+
  geom_sf()
`

**Comment by edzer** [comment]
No crash here. Which version of `sf`, and what is the output of `sf_extSoftwareVersion()`?

**Comment by juanmayorgahenao** [comment]
I'm using the dev version of sf and: 
` GEOS           GDAL         proj.4 GDAL_with_GEOS 
       "3.6.2"        "2.2.3"        "5.0.0"         "true" `

**Comment by juanmayorgahenao** [comment]
I have reinstalled GEOS, GDAL, and proj.4 using homebrew and R session no longer breaks. 

However, the function `st_wrap_dateline` still does not work. This is what I'm trying to accomplish: 

`m <- matrix(c(168.5688,	-16.59488,	-75.69947,	-40.73869	),
            nrow = 2, byrow = TRUE)

line_string <- st_linestring(m) %>%
st_sfc(crs = 4326) %>%
st_sf(geometry = .) %>% 
st_segmentize(units::set_units(100, km)) %>% 
st_wrap_dateline(options = c("WRAPDATELINE=YES",  "DATELINEOFFSET=60"), quiet = TRUE) 

line_string %>%
ggplot()+
geom_sf()`

Is there anything I'm doing wrong? 

Thank you for the help @edzer

**Comment by edzer** [comment]
The problem is that `st_segmentize` doesn't care about the dateline. That is something we can address at some stage. For now a fix would be:
```r
m <- matrix(c(168.5688,	-16.59488,	-75.69947,	-40.73869	),
            nrow = 2, byrow = TRUE)
line_string <- st_linestring(m) %>%
st_sfc(crs = 4326) %>%
st_segmentize(units::set_units(100, km))
# rescale longitude to [-180,180]:
line_string2 <- (line_string + c(180,90)) %% c(360) - c(180,90)
line_string2 %>% st_sfc(crs = 4326) %>%
st_wrap_dateline(options = c("WRAPDATELINE=YES",  "DATELINEOFFSET=60"), quiet = TRUE) %>%
plot(axes=TRUE)
```

**Comment by juanmayorgahenao** [comment]
Thank you @edzer

**Comment by edzer** [comment]
My pleasure!
