### ISSUE TITLE
overload +, -, * and / for union, difference, intersection and symmetric difference on sfg/sfc's

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#675]
I implemented this; comments are welcome, also about whether this is a good idea at all.

See [here](https://r-spatial.github.io/sf/reference/ops.html) for examples.

![x](https://user-images.githubusercontent.com/520851/37458686-1093690e-2846-11e8-86e9-8b027cfefb7e.png)

**Comment by tim-salabim** [comment]
This is a great idea! Very intuitive IMO. I'll test whether this can be wrapped directly in `mapview(a + b)`.

**Comment by tim-salabim** [comment]
I did a few preliminary experiments regarding these:

```r
library(mapview)
# Warning messages:
# 1: replacing previous import ‘sf::gdal_subdatasets’ by ‘stars::gdal_subdatasets’ when loading ‘mapview’ 
# 2: replacing previous import ‘sf::gdal_crs’ by ‘stars::gdal_crs’ when loading ‘mapview’ 
# 3: replacing previous import ‘sf::gdal_metadata’ by ‘stars::gdal_metadata’ when loading ‘mapview’ 
# 4: replacing previous import ‘sf::gdal_utils’ by ‘stars::gdal_utils’ when loading ‘mapview’ 
library(sf)

## create some simple polygons
franconia1 = st_union(franconia)

mapview(franconia1)

set.seed(43)
franconia2 = st_jitter(franconia1, amount = 0.5)
mapview(franconia2) + mapview(franconia1, col.regions = "red")

set.seed(42)
franconia3 = st_jitter(franconia2, amount = 0.25)
mapview(list(franconia1, franconia3)) 

## now test various scenarios
# works as expected
f12 = franconia1 + franconia2
mapview(f12) + franconia1 + franconia2
mapview(f12) + (franconia2 - franconia3)
mapview(franconia2 - franconia1) + franconia1 + franconia3

# these do respect crs
franconia1 + franconia2
franconia1 - franconia2

## whereas these don't
franconia1 / franconia2
franconia1 * franconia2
mapview(franconia2 / franconia3) + franconia #hence native coordinates & no bg map
```
Most notable unexpected behaviour is that `*` and `/` don't seem to respect the crs of the geometries.
Other than that I haven't found anything unexpected so far (though not a very comprehensive test). 

All in all, I think this makes for quite an elegant API, similar to what others are doing - e.g. [patchwork](https://github.com/thomasp85/patchwork). This is definitely very useful!

What I do see though are some warnings when loading mapview which I haven't seen before (see commented out at the beginning of the example). I am using the dev version of `mapview` which imports `stars` as well as `sf` so I guess that's the culprit.

**Comment by edzer** [comment]
You may want to reinstall stars; I moved all GDAL dependencies to sf, stars is R only now.

**Comment by tim-salabim** [comment]
Yes, reinstalling stars resolves the warnings, thanks!

**Comment by tim-salabim** [comment]
crs now also works for * and / thanks!

**Comment by edzer** [comment]
See #696 ; proposal: arithmetic and logical set operations seem both useful; for that reason I will change the symbols that do set ops into `&` for intersection, `|` for union, `/` for diff (the [real diff op](https://en.wikipedia.org/wiki/Set_(mathematics)#Complements) should be `\` but that is not available as R operator), and `%/%` for symmetric diff:
![x](https://user-images.githubusercontent.com/520851/38568231-7545d4ac-3ce8-11e8-99b3-0cdcae2a9c7a.png)

For arith we then have `+`, `-` and `*` (also for matrix mult), and `/` for division in case the second argument is _not_ a geometry.
