### ISSUE TITLE
Creating lines from points through group+summarise+cast doesn't work when the input has zero features

### ISSUE THREAD

**Issue by mz8i** [r-spatial/sf#676]
I have been using the suggestion from [Issue 321](https://github.com/r-spatial/sf/issues/321) to create single lines from a dataframe of points with a grouping Id field. Sample code (Src = 1 indicates start of line, Src = 2 - end of line. Id is the grouping variable):

```r
library(sf)
library(tidyverse)

data.frame(Id = c(1, 2, 1,2), Lon = 1:4, Lat = 1:4, Src = c(1,1,2,2)) %>%
  top_n(0, row_number()) %>% 
  # normally the df comes from a potentially empty file, the top_n()is just to demonstrate such a situation
  arrange(Id, Src) %>%
  st_as_sf(coords=c('Lon', 'Lat'), remove=FALSE) %>%
  group_by(Id) %>%
  summarise(a=1) %>%
  st_cast("LINESTRING") %>%
  select(-a)

```

Now, if the file is non-empty, everything works as expected. But if the data frame turns out to have no elements, the call to summarise fails:
```
Error in do.call(st_sfc, geom) : second argument must be a list
In addition: Warning messages:
1: In min(x[[coords[1]]], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
2: In min(x[[coords[2]]], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
3: In max(x[[coords[1]]], na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
4: In max(x[[coords[2]]], na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
```

Is there any way to make such code robust to an empty input without writing ifs for checking if the input is empty? I would really prefer to keep the code as simple as possible, and to always return a consistent sf object with the same columns.

**Comment by edzer** [comment]
That should now work (warnings are still there).
