### ISSUE TITLE
Issue with gdal

### ISSUE THREAD

**Issue by msolano00** [r-spatial/sf#677]
Hi folks, 

There seems to be an issue for Linux users. SF will not install unless you have GDAL 2+, this doesn't seem like much of an issue but unless you are running Ubuntu you won't find the latest GDAL on the package management system for most other distros (they included older versions). 

Most people aren't system admins and won't have access to compile the whole library from scratch.

**Comment by rsbivand** [comment]
GDAL 2.0.0 was released in June 2015, almost three years ago. It changed the API, but also brought very many bug fixes. Nobody should be using the 1.* series for anything other than replicating results computed with those versions. On [Ubuntu stable](https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa), there seems to be 2.1.3 via PPA, and 2.2.2 on later.

**Comment by msolano00** [comment]
@rsbivand hi Roger, 

Yes, it seems to be only on Ubuntu, which is roughly 20% of the Linux distributions. I understand that this is not an issue from SF code itself, but it does affect end users. Is it possible to use an older version of SF (we require SF for another package)?

**Comment by jsta** [comment]
The README has instructions for Fedora and Arch so I would guess they have it as well.

**Comment by msolano00** [comment]
@jsta this is confusing since the GDAL repo only lists Ubuntu. The company I work for is currently running RHEL unfortunately.

**Comment by msolano00** [comment]
@rsbivand thanks, Roger, I will try with ELGIS.
