### ISSUE TITLE
Validity after aggregation with `do_union = FALSE`

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/sf#681]
Lately, I've tried to aggregate some spatial data without unioning them. This process often ends with non-valid polygons (see the last example below), however aggregation with union works fine. Original data are also valid. Is is possible to improve it on the **sf** part or using `lwgeom::st_make_valid()` is the only feasible solution?

The sample data is attached - [map.zip](https://github.com/r-spatial/sf/files/1830949/map.zip).

``` r
library(sf)                                                 
library(lwgeom)                                             
#> Linking to liblwgeom 2.3.2 r15302, GEOS 3.6.1, proj.4 4.9.3
map = st_read("/vsizip/map.zip")                            
                                                            
# check if map is valid                                    
all(st_is_valid(map))                                       
#> [1] TRUE
                                                            
# aggregate and union them                                  
map_aggr_union = aggregate(map, by = list(group = map$NAME),
FUN = function(x) x[1], do_union = TRUE)                    
                                                            
# check if map_aggr_union is valid                          
all(st_is_valid(map_aggr_union))                            
#> [1] TRUE
                                                            
# aggregate them                                            
map_aggr = aggregate(map, by = list(group = map$NAME),      
FUN = function(x) x[1], do_union = FALSE)                   
                                                            
# check if map_aggr is valid                                
all(st_is_valid(map_aggr))                                  
#> [1] FALSE
```

**Comment by edzer** [comment]
If you want to get valid polygons after aggregating without union'ing, make sure your polygons are suitable for that in the first place. It's not a problem of sf, but of your data.

**Comment by Nowosad** [comment]
I agree that input data can be a problem. However, is there a way to know that? As you can see above - `st_is_valid(map)` gives TRUE.

**Comment by edzer** [comment]
`st_is_valid` operates on individual geometries. When you aggregate, you create a new geometry by throwing things together:
```r
> library(sf)
Linking to GEOS 3.5.1, GDAL 2.2.1, proj.4 4.9.3
> st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,0))))
POLYGON ((0 0, 1 0, 1 1, 0 0))
> p = st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,0))))
> st_is_valid(st_sfc(p, p+.1))
[1] TRUE TRUE
> st_is_valid(do.call(c, st_sfc(p, p+.1)))
[1] FALSE
```
Regarding your data: a clue might be that in
```r
> st_relate(map)[,1]
 [1] "2FFF1FFF2" "FF2FF1212" "FF2FF1212" "FF2FF1212" "FF2F11212" "FF2FF1212"
 [7] "FF2FF1212" "FF2FF1212" "FF2FF1212" "FF2FF1212" "FF2FF1212"
```
element 5 differs from the other non-diagonal terms.

**Comment by Nowosad** [comment]
The above dataset was just an example. There is a lot of data like that.
My main goal in opening this issue was to find out is there a generic way to know if dataset could be problematic for some operations. 
Thanks for the `st_relate()` hint.

**Comment by edzer** [comment]
SFA, page 26 clause c of what constitutes a valid polygon: "No two Rings in the boundary cross and the Rings in the boundary of a Polygon may intersect at a Point but only as a tangent"

So:
```r
> library(sf)
Linking to GEOS 3.5.1, GDAL 2.2.1, proj.4 4.9.3
> p1 = st_polygon(list(rbind(c(0,0), c(1,0), c(1,1), c(0,0))))
> p2 = st_polygon(list(rbind(c(0,0), c(0,1), c(1,1), c(0,0))))
> st_is_valid(do.call(c, st_sfc(p1, p2)))
[1] FALSE
```
I.e., any combination of polygons sharing a border is invalid. So you could check for pairs of geometries for which the boundaries intersection is maximally 1-dimensional. A few words on this in the functions that allow for `do_union=FALSE` might be helpful.
