### ISSUE TITLE
st_difference for two objects, linestring and polygon gives intersection of linestring with itself as well

### ISSUE THREAD

**Issue by alazarovski** [r-spatial/sf#682]
I was trying to split a linestring with a polygon and get two linestrings. Unfortunately if I use sf::st_difference the end result are two linestrings calculated by the intersection of the linestring with the polygon and more linestrings that are result of the crossing of the linestring with itself. A simplified example is below:

```{r}
# sample sf dataframe
df <- data.frame(fid = 1, lon = c(-140, -150, -170, 170, 130), lat = c(0, 70, 50, 40, 30)) %>% 
  st_as_sf(coords = c("lon", "lat"), dim = "XY") %>% st_set_crs(4326)

# polygon
pol <- data.frame(fid = "pol", lon = c(-145,-135,-135,-145,-145), lat = c(-5,-5,5,5,-5)) %>% 
  st_as_sf(coords = c("lon", "lat"),dim = "XY") %>% st_set_crs(4326) 
pol <- pol %>% summarise(geometry = st_union(geometry), do_union = F) %>% st_cast("MULTILINESTRING")

# convert point to linestring
ldf <- df %>% group_by(fid) %>% summarise(geometry = st_union(geometry), do_union = F) %>% st_cast("LINESTRING")

# splitting linestring with polygon
mldf <- st_difference(ldf, st_buffer(st_intersection(ldf, pol), dist = 1e-12))

# converting multilinestring to multiple linestrings
ls <- st_cast(mldf, "LINESTRING")

# just for visualization 
mapview(ls)
```
After this I expected to have 2 linestrings, but instead I get 4. I was hoping to get the difference between  object 1 and object 2, instead it calculates difference of object 1 with object 1 as well.

**Comment by edzer** [comment]
Just for the record: you are aware that pkg `lwgeom` has an `st_split`, right?

**Comment by alazarovski** [comment]
st_split gives me a GEOMETRY COLLECTION that I cannot convert back to MULTILINESTRING with the sf::st_cast(). I get this error:
```{r}
Error in st_cast.sfc(st_geometry(x), to, group_or_split = do_split) : 
  use smaller steps for st_cast; first cast to MULTILINESTRING or POLYGON?
```

**Comment by edzer** [comment]
Did you try `st_collection_extract`?

**Comment by alazarovski** [comment]
st_collection_extract worked but in the end we still have intersection of the line with itself as end result.

**Comment by edzer** [comment]
Issue solved?

**Comment by alazarovski** [comment]
Considering there is no way to get the intersection of the line with the polygon without getting the intersection of the line with itself which in fact was my request, I can close the issue as unsolved if you think that is the way to go?

**Comment by edzer** [comment]
I don't get it really. Is your problem that the line should have crossed the dateline, rather than go around the world?

**Comment by alazarovski** [comment]
I apologize for the poor explanation. The desired output from using st_difference for the two objects (linestring and polygon) would be splitting the linestring into 2 parts, so in the end there would be 2 linestrings of which the first one is inside the polygon and the other is outside. Instead the linestring is split as a result from crossing with itself. The dateline is the reason why the linestring crosses itself but st_difference should give the difference between the polygon and the linestring which should be two linestrings right ? Can st_difference do this or should I maybe look for another package to get two linestrings as output from the following example. Any answer is appreciated. Thank you

**Comment by edzer** [comment]
I guess the problem is
```r
> st_is_simple(ldf)
[1] FALSE
```
i.e., `ldf` is not a simple feature, because it self-intersects, and the `st_difference` etc assume data are planar, where your data are on a sphere. You did see the warnings, right?

**Comment by alazarovski** [comment]
Thank you for explaining it simply. I guess this cannot be done in R with another package maybe ?

**Comment by edzer** [comment]
`st_wrap_dateline` might do the job, see #280, and you may want to `st_segmentize` before you plot on a plate caree or web Mercator.

**Comment by cyrilmory** [comment]
Hi. 
I started using st_split and didn't know what to do with its output. I'm guessing there might be others like me. I learnt the existence of st_collection_extract (which does exactly what I need) from reading this issue's conversation. Would it be relevant to add a sentence in the documentation of st_split, pointing the reader to st_collection_extract ?
