### ISSUE TITLE
st_within gives error: Error in CPL_geos_binop

### ISSUE THREAD

**Issue by alazarovski** [r-spatial/sf#688]
I stumbled upon this error when I was trying to check if one sf object is within another like below:
```{r}
st_within(object1$geometry, object2$geometry)
```
Result:
```{r}
Error in CPL_geos_binop(st_geometry(x), st_geometry(y), op, par, pattern,  : 
  attr classes has wrong size: please file an issue
``` 
Although I was somehow able to create a workaround by inserting the length of the vectors like this:
```{r}
st_within(object1$geometry[1:length(object1$geometry)], object2$geometry[1:length(1:object2$geometry))
``` 

This works for me for now, but still curious about the error.

**Comment by edzer** [comment]
Please provide a reproducible example, if must by direct mail.
