### ISSUE TITLE
`sf::as_Spatial` should support attributes and convert to `SpatialPolygonsDataFrame` etc

### ISSUE THREAD

**Issue by jlegewie** [r-spatial/sf#690]
Hi,

`sf::as_Spatial` coerce simple feature geometries to the corresponding Spatial* objects but does not support attributes. It would be great if `sf::as_Spatial` could direct convert to `SpatialPolygonsDataFrame`, `SpatialLinesDataFrame` etc.

```
nc < st_read(system.file("shape/nc.shp", package="sf"))
# Works
as_Spatial(st_geometry(nc[1,]))
# Error
as_Spatial(nc[1,])
```

**Comment by edzer** [comment]
Why don't you use
```r
as(nc[1,], "Spatial")
```
?

**Comment by edzer** [comment]
It's documentation sais: "Methods to coerce simple feature geometries to corresponding ‘Spatial*’ objects." Geometries, not features. If you can give me a reasons why there need to be two ways of doing this, I'm all ears. But I will add a line to the function's documentation!

**Comment by superrichard2018** [comment]
sf:::as_Spatial() how can I convert some points which are sf to sp?

**Comment by edzer** [comment]
```r
as(points, "Spatial")
```

**Comment by MichaelChaoLi-cpu** [comment]
Sir, after I run as(points, "Spatial"), other information is lost. There is no @data in the new sp object. What should I do, if I want to keep other columns in  @data.

**Comment by edzer** [comment]
what is the class of `points`?

**Comment by MichaelChaoLi-cpu** [comment]
sf class. e.g. I have three columns, saying A, B, and geometry. A  and B are numeric. After I use as function, A and B would be lost, rather than in the @data

**Comment by edzer** [comment]
need a simple reprex.

**Comment by MichaelChaoLi-cpu** [comment]
How to figure it out, sir? Could you please give me an example, sir?

**Comment by rCarto** [comment]
Hello @MichaelChaoLi-cpu , 
Here is a short post on reproducible examples (reprex) and how to create them: https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-create-one/5219

**Comment by MichaelChaoLi-cpu** [comment]
Sir, I. write a reprex, as follows:

library(sp)
library(sf)

X <- 1:20
Y <- 1:20
coord <- as.data.frame(cbind(X,Y))
coordinates(coord) <- ~X+Y
coord <- st_as_sf(coord)

A <- 1:20 #other attribute
coord <- cbind(A, coord)

B <- 1:40
A <- append(1:20, 1:20)
B <- as.data.frame(cbind(A,B))
coord_new <- dplyr::left_join(B, coord, by = "A")

coord_sp <- as(coord_new, "Spatial")
coord_sp <- as_Spatial(coord_new)

they don't work. Thank you, sir.

**Comment by edzer** [comment]
use
```r
coord_new <- dplyr::left_join(B, coord, by = "A") |> st_as_sf()
```
otherwise, `coord_new` is a `data.frame`, S3 method dispatch only works on the first argument so `sf::left_join` is never being called.
