### ISSUE TITLE
Rotation of sf objects does not work anymore

### ISSUE THREAD

**Issue by danceb** [r-spatial/sf#696]
I have followed the example to rotate features in the Vignette at [https://cran.r-project.org/web/packages/sf/vignettes/sf3.html](https://cran.r-project.org/web/packages/sf/vignettes/sf3.html).

```r
rot = function(a) matrix(c(cos(a), sin(a), -sin(a), cos(a)), 2, 2) 

nc = st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
ncg = st_geometry(nc)
plot(ncg, border = 'grey')
cntrd = st_centroid(ncg)
## Warning in st_centroid.sfc(ncg): st_centroid does not give correct
## centroids for longitude/latitude data
ncg2 = (ncg - cntrd) * rot(pi/2) * .75 + cntrd
plot(ncg2, add = TRUE)
plot(cntrd, col = 'red', add = TRUE, cex = .5)
```

Unfortunately this does not work anymore, as you can see in the markdown example in the vignette as well. In the end I did not get the rotated features only the centroids of them.

The rotation works with sf 0.6-0, so I've reinstalled this version.

Hope, you can find the issue and fix it.

**Comment by edzer** [comment]
Thanks --  this is because of #675 -- you can't use a single operator for two things. I'll try to think of a way out.

**Comment by danceb** [comment]
Thanks for the attempt to find a solution. Maybe writing a new inbuilt function `st_rotate`or something would be great.

**Comment by Nowosad** [comment]
@edzer - the new revision of the operators still do not give the same result as in the past. For example, a code from vignette 3:

``` r
library(sf)                                                          
#> Linking to GEOS 3.6.1, GDAL 2.1.4, proj.4 4.9.3
rot = function(a) matrix(c(cos(a), sin(a), -sin(a), cos(a)), 2, 2)   
nc = st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
ncg = st_geometry(nc)                                                
plot(ncg, border = 'grey')                                           
cntrd = st_centroid(ncg)                                             
#> Warning in st_centroid.sfc(ncg): st_centroid does not give correct
#> centroids for longitude/latitude data
ncg2 = (ncg - cntrd) * rot(pi/2) * .75 + cntrd                       
plot(ncg2, add = TRUE)                                               
plot(cntrd, col = 'red', add = TRUE, cex = .5)                       
```

![](https://i.imgur.com/tegSi4F.png)

**Comment by edzer** [comment]
I see this:
![x](https://user-images.githubusercontent.com/520851/38737599-03994736-3f30-11e8-945a-f172661c14ae.png)
which LGTM.

**Comment by edzer** [comment]
(now updated)
