### ISSUE TITLE
Create an sf interface for hive

### ISSUE THREAD

**Issue by etiennebr** [r-spatial/sf#699]
Following @harryprince's [comment](https://github.com/r-spatial/sf/issues/368#issuecomment-379991101) I would like to discuss how to create an `sf` interface for hive that would rely on `sparklyr`, just like the database interfaces can leverage `dbplyr`. 

/cc @mdsumner

**Comment by mdsumner** [comment]
No experience with hive myself but happy to follow leads, I did a dummy example with SQLite that I can't share so I can put together a generic example, but essentially st_as,_sf or st_sfc can detect and convert binary or text geom columns, after simple, standard queries . The crux is other metadata, and other non-simple, multi table schemas

**Comment by mdsumner** [comment]
Hi there, hope this is of interest. I kind of considered this fairly straightforward, but a lot has improved in many places and I learnt quite a bit doing it. I expect that applying this to another DB won't be massively difficult, and I'm happy to explore. 

```R
library(sf)
f <- system.file("gpkg", "nc.gpkg", package = "sf")

library(dplyr)
## so choose your particular provider (SQL Server, RPostgres, ...)
## with odbc should also allow Manifold and many others not officially in 
## the dbplyr fold
(db <- src_sqlite(f))

## the relevant table name is nc.gpkg, but obviously not predictable across
## providers
d <- tbl(db, "nc.gpkg")

## d is lazy, using it triggers SQL generation and partial (head, TOP 6, etc.) read
d

## to get a subset, work on your query
tbl(db, sql('SELECT PERIMETER, NAME FROM "nc.gpkg" WHERE BIR74 > 1e4'))

## but we don't have to write SQL (geom won't be the name always, or in all providers)

nc_q <- tbl(db, "nc.gpkg")
nc_q %>% dplyr::filter(BIR74 > 1e4) %>% dplyr::select(PERIMETER, NAME, geom)

## so, now we can bake it in our in memory format
d <- nc_q %>% dplyr::filter(BIR74 > 1e4) %>% dplyr::select(PERIMETER, NAME, geom) %>% 
  dplyr::collect() %>% 
  sf::st_as_sf()


## the crs is something else, and these two give enough for GeoPackage
## for us to reconstruct
db %>% tbl("gpkg_spatial_ref_sys")
db %>% tbl("gpkg_geometry_columns")

```

**Comment by mdsumner** [comment]
Oh, and on the general topic something that is not exposed from the GDAL bindings for sf is `ExecuteSQL`, and this is not [super tricky to use](https://github.com/hypertidy/vapour/blob/master/src/vapour.cpp#L129) but there are various gotchas

* some drivers the special FID is 0 based, some 1 based, and some arbitrary (OSM)
* managing native DB queries vs. the OGR-wrappers is another wrinkle
* field types as ever will be problematic, and SQL that modifies/transforms geoms could complicate things

http://www.gdal.org/ogr_sql.html

I sort of expected that sf exposing ExecuteSQL was an obvious thing, but I haven't explored what needs to change in sf (or be added) and how much. Certainly from my perspective reading many rows * many columns is a problem, so separability is important - and sf now allows a straight df to be returned, so it's an opportunity.

**Comment by etiennebr** [comment]
@mdsumner checkout #558. Even spatial functions are mapped, so you could do `mutate(area = st_area(geometry))`. You won't even need the `sf::st_as_sf()` part. In fact, that's the intention. If you can provide feedback, it would be awesome. 

However we are side-tracking this discussion given that we should focus on spark, but indeed the idea is to leverage `dplyr`+`dbplyr` (which `sparklyr` would mostly do for us.)

**Comment by harryprince** [comment]
I am using ESRI hive-udf in production, this maybe help:
https://github.com/Esri/spatial-framework-for-hadoop/wiki/UDF-Documentation

**Comment by jnh5y** [comment]
@harryprince As a clarification, LocationTech is working group of the Eclipse Foundation; it isn't a separate company.;)

I work for CCRi (which is a member company) and we work on GeoMesa.  If you are interested in an alternative to ESRi's hive-udf work, you can use GeoMesa's JTS+Spark module (http://www.geomesa.org/documentation/user/spark/spark_jts.html).  

Are you trying to get Spark integration?  Or do you really want to work at the Hive level?

**Comment by harryprince** [comment]
@jnh5y 
working with Hive is good, however, some advanced GIS operator is hard to play with Hive, like R-tree , KNN, and Voronoi. These operators need build index in-memory cache, in that, Spark might be a preferred solution. For R users, sparklyr and sf provided greatest data manipulation interface for data scientist, so don't need to learn more grammar is the best option.

**Comment by edzer** [comment]
Another cloud platform of interest: BigQuery: https://cloud.google.com/bigquery/docs/gis-intro

**Comment by harryprince** [comment]
latest process: run sf command via geospark, which will outperformance than PostGIS and ESRI Hadoop on throughout and speed.

![Uploading Screen Shot 2019-01-22 at 6.00.36 PM.png…]()

https://www.researchgate.net/publication/319603682_GeoSpark_SQL_An_Effective_Framework_Enabling_Spatial_Queries_on_Spark

**Comment by edzer** [comment]
I agree this is interesting; closing now because it is not really an open, or active, issue.
