### ISSUE TITLE
Unexpected result with 'st_sample' of LINESTRING and MULTILINESTRING in Geographical CRS

### ISSUE THREAD

**Issue by michaeldorman** [r-spatial/sf#701]
Seems like sampling a **line** layer given in **geographical CRS** with `st_sample` returns points concentrated in one location per feature, rather than randomly distributed. 

A **reproducible example** is given below -

```
library(sf)
nc = st_read(system.file("shape/nc.shp", package="sf"))
nc = st_cast(nc, "MULTILINESTRING")
```

## Sampling in Geographical CRS - something wrong

```
s = st_sample(nc, 1000)
plot(st_geometry(nc))
plot(st_geometry(s), add = TRUE, col = "red")
```

![unnamed-chunk-1-1](https://user-images.githubusercontent.com/9386655/38679438-6eec96e2-3e6c-11e8-9f6d-7070adc4aed4.png)

## Sampling in Projected CRS - works fine

```
nc = st_transform(nc, 26917)
s = st_sample(nc, 1000)
plot(st_geometry(nc))
plot(st_geometry(s), add = TRUE, col = "red")
```

![unnamed-chunk-1-2](https://user-images.githubusercontent.com/9386655/38679439-6f19f9ac-3e6c-11e8-8575-e3a5e425fabf.png)

**Comment by edzer** [comment]
Should work now - thanks!

**Comment by michaeldorman** [comment]
It is working now - thank you very much!
