### ISSUE TITLE
show()ing large sf objects can be slow

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/sf#703]
Just  a heads up, I do not know if this can be improved: printing to the R terminal large `sf` objects seems to be very slow. Take [this file](https://drive.google.com/open?id=16BQdMiUjqw4QuSWgKhen3CArsyEZMthm) as an example.

Showing the third multipolygon takes several seconds:
```
(a <- st_read("italy_istat2016_macro.gpkg"))  ##slow
a[c(1,2,4),] ##fast
a[3,] ##slow
```

**Comment by edzer** [comment]
Thanks for bringing this up! Yes, this was fast at first, then wrong, now complete objects are again converted to WKT before truncating. Tricky challenge - any help appreciated!

**Comment by tim-salabim** [comment]
maybe only show the class, e.g. MULTIPOLYGON, POLYGON, GEOMETRYCOLLECTION etc. which I think is the important bit of info when printing an object. I am not sure how helpful the first couple of digits of the first coordinate really is.

**Comment by adrfantini** [comment]
I personally never found myself having to read that information either.

**Comment by edzer** [comment]
Well, it's what tibble does: peak into the values. I tend to look at it more often than e.g. at the bounding box.

**Comment by edzer** [comment]
Due to lack of activity, I'm closing this one.
