### ISSUE TITLE
sf seems to reset mfrow 

### ISSUE THREAD

**Issue by Robinlovelace** [r-spatial/sf#704]
When plotting `sf` interactively I noticed sometimes normal plots would become small and be placed in the top left corner. This issue can be resolved with:

```r
par(mfrow = c(1, 1))
```

But I imagine that is not the intended behaviour.

A reproducible example demonstrates this behaviour: 

```r
library(sf)
library(spData)
plot(nz$geom)
par()$mfrow
plot(nz)
par()$mfrow
plot(nz$geom)
plot(1:9)
```

sf version: 

```
sf           * 0.6-2      2018-04-13 Github (r-spatial/sf@89eabc4)  
```

**Comment by edzer** [comment]
Should work now; thanks!!

**Comment by Robinlovelace** [comment]
Fast work. The behaviour I was expected is illustrated below using the following command:

```r
reprex::reprex({devtools::install_github("r-spatial/sf")
library(sf)
library(spData)
plot(nz$geom)
par()$mfrow
plot(nz)
par()$mfrow
plot(nz$geom)
plot(1:9)})
```

which results in this output:

``` r
devtools::install_github("r-spatial/sf")
#> Using GitHub PAT from envvar GITHUB_PAT
#> Skipping install of 'sf' from a github remote, the SHA1 (2d2ab1c1) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.2, proj.4 4.9.2
library(spData)
plot(nz$geom)
```

![](https://i.imgur.com/6YOj8dj.png)

``` r
par()$mfrow
#> [1] 1 1
plot(nz)
```

![](https://i.imgur.com/ubVGDA5.png)

``` r
par()$mfrow
#> [1] 1 1
plot(nz$geom)
```

![](https://i.imgur.com/7fy0678.png)

``` r
plot(1:9)
```

![](https://i.imgur.com/bAbrebd.png)
