### ISSUE TITLE
dplyr verbs with sf loaded but not attached

### ISSUE THREAD

**Issue by krlmlr** [r-spatial/sf#710]
don't use the *sf* implementation:

``` r
library(tidyverse)

shape <- sf::st_sf(tibble(key = 1:2, GEOM = sf::st_sfc(sf::st_point(1:2))))
shape
#> Simple feature collection with 2 features and 1 field
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 2 xmax: 1 ymax: 2
#> epsg (SRID):    NA
#> proj4string:    NA
#> # A tibble: 2 x 2
#>     key GEOM           
#>   <int> <S3: sfc_POINT>
#> 1     1 1:2            
#> 2     2 1:2
filter(shape, key < 2)
#> # A tibble: 1 x 2
#>     key GEOM           
#>   <int> <S3: sfc_POINT>
#> 1     1 1:2

library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.1, proj.4 4.9.3
filter(shape, key < 2)
#> Simple feature collection with 1 feature and 1 field
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 1 ymin: 2 xmax: 1 ymax: 2
#> epsg (SRID):    NA
#> proj4string:    NA
#> # A tibble: 1 x 2
#>     key    GEOM
#>   <int> <POINT>
#> 1     1   (1 2)
```

> Created on 2018-04-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Doesn't work for data frames either.

I think registering S3 methods really makes a difference. The *hms* package contains an implementation of manual registration for weak dependencies, it might be a good fit for the upcoming *sloop* package so that it becomes a little less of a hack.

**Comment by krlmlr** [comment]
Also, calling `filter.sf()` directly gives `NextMethod()` not specified...

**Comment by edzer** [comment]
Thanks, good idea -- it's pretty likely that the current sf setup will be illegal in 3.5.0.

**Comment by edzer** [comment]
This also adds @krlmlr to the contributors, if you are OK with this.

**Comment by krlmlr** [comment]
Thanks, I appreciate it!
