### ISSUE TITLE
st_jitter produces Error in FUN(left, right) : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by tim-salabim** [r-spatial/sf#712]
With the latest github version I see

```r
library(mapview)
library(sf)

brew = st_jitter(breweries)

Error in FUN(left, right) : non-numeric argument to binary operator
```

I think it originates from the `+` operator in [this line](https://github.com/r-spatial/sf/blob/master/R/jitter.R#L29).

<details><summary>Session info</summary>

devtools::session_info()
Session info --------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.419)           
 language en_US                       
 collate  en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2018-04-19                  

Packages ------------------------------------------------------------------------------------------
 package     * version    date       source                          
 abind         1.4-5      2016-07-21 CRAN (R 3.4.0)                  
 base        * 3.4.3      2017-12-01 local                           
 base64enc     0.1-3      2015-07-28 cran (@0.1-3)                   
 class         7.3-14     2015-08-30 CRAN (R 3.4.0)                  
 classInt      0.1-24     2017-04-16 CRAN (R 3.4.0)                  
 codetools     0.2-15     2016-10-05 CRAN (R 3.3.1)                  
 colorspace    1.3-2      2016-12-14 cran (@1.3-2)                   
 compiler      3.4.3      2017-12-01 local                           
 crosstalk     1.0.0      2016-12-21 cran (@1.0.0)                   
 curl          2.8.1      2017-07-21 CRAN (R 3.4.1)                  
 datasets    * 3.4.3      2017-12-01 local                           
 DBI           0.8        2018-03-02 cran (@0.8)                     
 devtools      1.13.3     2017-08-02 CRAN (R 3.4.1)                  
 digest        0.6.15     2018-01-28 cran (@0.6.15)                  
 e1071         1.6-8      2017-02-02 CRAN (R 3.4.0)                  
 foreach       1.4.3      2015-10-13 cran (@1.4.3)                   
 gdalUtils     2.0.1.7    2015-10-10 cran (@2.0.1.7)                 
 git2r         0.19.0     2017-07-19 CRAN (R 3.4.1)                  
 graphics    * 3.4.3      2017-12-01 local                           
 grDevices   * 3.4.3      2017-12-01 local                           
 grid          3.4.3      2017-12-01 local                           
 htmltools     0.3.6      2017-04-28 cran (@0.3.6)                   
 htmlwidgets   1.0        2018-01-20 cran (@1.0)                     
 httpuv        1.3.5      2017-07-04 CRAN (R 3.4.1)                  
 httr          1.3.1      2017-08-20 CRAN (R 3.4.1)                  
 iterators     1.0.8      2015-10-13 cran (@1.0.8)                   
 knitr         1.17       2017-08-10 CRAN (R 3.4.1)                  
 lattice       0.20-35    2017-03-25 CRAN (R 3.3.3)                  
 leaflet       1.1.0      2017-02-21 CRAN (R 3.4.3)                  
 magrittr      1.5        2014-11-22 CRAN (R 3.4.0)                  
 mapview     * 2.3.13     2018-04-19 local                           
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)                  
 methods     * 3.4.3      2017-12-01 local                           
 mime          0.5        2016-07-07 CRAN (R 3.4.0)                  
 munsell       0.4.3      2016-02-13 cran (@0.4.3)                   
 plyr          1.8.4      2016-06-08 cran (@1.8.4)                   
 png           0.1-7      2013-12-03 cran (@0.1-7)                   
 R.methodsS3   1.7.1      2016-02-16 cran (@1.7.1)                   
 R.oo          1.21.0     2016-11-01 cran (@1.21.0)                  
 R.utils       2.5.0      2016-11-07 cran (@2.5.0)                   
 R6            2.2.2      2017-06-17 cran (@2.2.2)                   
 raster        2.6-7      2017-11-13 cran (@2.6-7)                   
 Rcpp          0.12.16    2018-03-13 cran (@0.12.16)                 
 rgdal         1.2-8      2017-07-01 CRAN (R 3.4.1)                  
 RPostgreSQL   0.6-2      2017-06-24 cran (@0.6-2)                   
 satellite     1.0.0      2017-08-03 CRAN (R 3.4.1)                  
 scales        0.5.0.9000 2018-02-28 Github (hadley/scales@d767915)  
 sf          * 0.6-2      2018-04-19 Github (r-spatial/sf@55c074b)   
 shiny         1.0.4      2017-08-14 CRAN (R 3.4.1)                  
 sp            1.2-7      2018-01-19 cran (@1.2-7)                   
 stars         0.1-1      2018-04-17 Github (r-spatial/stars@785e3d3)
 stats       * 3.4.3      2017-12-01 local                           
 stats4        3.4.3      2017-12-01 local                           
 tools         3.4.3      2017-12-01 local                           
 udunits2      0.13       2016-11-17 CRAN (R 3.4.0)                  
 units         0.5-1      2018-01-08 cran (@0.5-1)                   
 utils       * 3.4.3      2017-12-01 local                           
 viridisLite   0.3.0      2018-02-01 CRAN (R 3.4.3)                  
 webshot       0.4.1      2017-05-31 cran (@0.4.1)                   
 withr         2.1.2      2018-04-01 Github (jimhester/withr@79d7b0d)
 xtable        1.8-2      2016-02-05 cran (@1.8-2)                   
 yaml          2.1.17     2018-02-27 cran (@2.1.17)  
</details>

**Comment by edzer** [comment]
Thanks, should work (again) now!
