### ISSUE TITLE
How to convert sparse result of a predicate to a graph?

### ISSUE THREAD

**Issue by krlmlr** [r-spatial/sf#715]
I haven't found a good way to convert the return of `st_intersects()` to a graph for computing connected components. Ultimately, I created an edgelist manually and passed it to `igraph::graph_from_edgelist()`. Have I missed anything obvious?

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.1, proj.4 4.9.3

rel <- 
  tibble(
    key = 1:3,
    geom = map2(1:3, c(2:3, 5), c) %>% map(st_point) %>% st_sfc()
  ) %>% 
  st_as_sf() %>% 
  st_buffer(0.8) %>%
  st_intersects()

rel
#> Sparse geometry binary predicate list of length 3, where the predicate was `intersects'
#>  1: 1, 2
#>  2: 1, 2
#>  3: 3

matrix(
  c(
    rep(seq_along(rel), map_int(rel, length)),
    unlist(rel)
  ),
  ncol = 2
) %>% 
  igraph::graph_from_edgelist() %>% 
  igraph::components()
#> $membership
#> [1] 1 1 2
#> 
#> $csize
#> [1] 2 1
#> 
#> $no
#> [1] 2
```

Created on 2018-04-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by edzer** [comment]
A candidate for an `as.igraph.sgbp` method?

**Comment by edzer** [comment]
```r
as.igraph.sgbp = function(x, ...) {
  m = cbind(
    rep(seq_along(x), lengths(x)),
    unlist(x)
  )
  igraph::graph_from_edgelist(m)
}
```

**Comment by rsbivand** [comment]
This adds a remarkable heavy **igraph** import. **igraph** is also typically unstable - I've had to comment out uses in an **spdep** vignette because the use of ARPACK could hard crash, or soft fail without warning (getting the extreme eigenvalues of a spatial weights matrix/graph). It isn't a high-frequency use functionality. Should I wrote a blog snippet? Much better not to make `sf` even more dependent on edgy packages.

```
as.nb.sgbp <- function(x, ...) {
  attrs <- attributes(x)
  x <- lapply(x, function(i) { if(length(i) == 0L) 0L else i } )
  attributes(x) <- attrs
  class(x) <- "nb"
  x
}
```

has been in the **spdep** `nb_sf` vignette since it was written, and getting from `"nb"` to **igraph** is in the **spdep** vignette `nb_igraph` vignette:

```
library(spdep)
...
nb_B <- nb2listw(x, style="B") # style= at choice, non-"B" will weight the edges, may also be asymmetric
B <- as(nb_B, "symmetricMatrix")
library(igraph)
g1 <- graph.adjacency(B, mode="undirected")
```

**Comment by edzer** [comment]
I gave that a thought too. Right now igraph is in `Suggests:`, did you consider that (you wrote "import")?

**Comment by krlmlr** [comment]
An `sgbp_to_edgelist()` function (or perhaps `as.matrix.sgbp()` or `as.data.frame.sgbp()`) would be almost as helpful, without pulling in the dependency (which still is installed on Travis and run as part of the tests).

Would just the process of loading *igraph* cause instabilities elsewhere? I'm not familiar with ARPACK, generally I found working with *igraph* to be a pleasant experience.

**Comment by rsbivand** [comment]
As a guess, an `as.data.frame.sgbp()` method to the first two columns of the old S-plus SpatialStats `spatial.neighbor` format: `c("row.id", "col.id")` (class `spatial.neighbor` inheriting from `data.frame`) would be enough. This is like [`listw2sn`](https://github.com/r-spatial/spdep/blob/master/R/listw2sn.R) in **spdep**.  Once the `sgbp` is a `data.frame`, anyone needing to use it in igraph can go through for example `igraph::graph_from_data_frame()`.

Yes, **igraph** is pleasant to use for the parts under active maintenance or development - ARPACK is a can of worms, and probably should have been dropped - I think the Matlab version is customised and protected from awkward errors. I don't know how often **igraph** actually needs extreme eigenvalues and their vectors, or whether it uses alternatives (i.e. is the ARPACK code exercised in igraph? I see that `page_rank()` uses it for negative eigenvalues; my commented out code is in the **spdep** vignette).

**Comment by rsbivand** [comment]
```
m = data.frame(row.id=rep(seq_along(x), lengths(x)), col.id=unlist(x))
```

is a compromise, and return the `data.frame`. **igraph** doesn't need the `weights` column.
