### ISSUE TITLE
Provide an option to vectorize st_bbox()

### ISSUE THREAD

**Issue by ben519** [r-spatial/sf#717]
It seems `st_bbox(x)` returns the bounding box of the entire `x` object (which makes sense). In my case, I would like to get the bounding box of *each* feature in `x`.  For example, I can do

```
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"))
bboxes <- list()
for(i in seq_len(nrow(nc))) bboxes <- c(bboxes, list(st_bbox(nc[i, ])))
```
But this is obviously slow for large feature sets.  Is there a better way and if not, would it be difficult to vectorize `st_bbox()` at the c++ level?  Thanks!

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2
```

**Comment by Nowosad** [comment]
Small tip - maybe it would be helpful in your case. You should not grow an object if you know its future size. The code below should be substantially faster for large datasets: 

```R
bboxes2 <- vector("list", nrow(nc))
for(i in seq_len(nrow(nc))) bboxes2[[i]] <- st_bbox(nc[i, ])
```

**Comment by ben519** [comment]
@Nowosad This is great, thanks!  I still think it'd be nice to have a native, vectorized version of `st_bbox()` in the sf package, but your solution works great until that day comes (if it does).

**Comment by edzer** [comment]
@Nowosad I appreciate it if you help solving issues here.

@ben519 feel free to write a PR for this in case it is worth the speed up.

**Comment by edzer** [comment]
The non-for-loop version of this is
```r
lapply(st_geometry(nc), st_bbox)
```
