### ISSUE TITLE
st_intersection output

### ISSUE THREAD

**Issue by alazarovski** [r-spatial/sf#724]
I'm new to this package and I`m just trying to use it in order to do some simple analysis but somehow I got stuck. I was wondering is there a way, if there is a linestring crossing a polygon, to calculate the parts of that linestring inside the polygon using the st_intersection. The trick is if the linestring is entering and exiting the polygon multiple times to get those parts separately in the LINESTRING format instead of getting one MULTILINESTRING with the multiple LINESTRINGs packed inside. Maybe the simple example below can show what I mean:

    library(sf)
    library(dplyr)
    
    # sample polygon
    poly <- data.frame(lon = c(0, 1, 1, 2, 2, 3, 3, 0, 0),
                       lat = c(0, 0, 1, 1, 0, 0, 2, 2, 0),
                       var = 1) %>% 
      st_as_sf(coords = c("lon", "lat"), dim = "XY") %>% group_by(var) %>% 
      summarise(geometry = st_union(geometry), do_union = F) %>% st_cast("POLYGON")

    # sample line
    line <- data.frame(lon = c(-0.5, 4), lat = c(0.5, 0.5), var = 1) %>% 
      st_as_sf(coords = c("lon", "lat"), dim = "XY") %>% group_by(var) %>%
      summarise(geometry = st_union(geometry), do_union = F) %>% st_cast("LINESTRING")

    # calculating intersection of line with polygon
    inters <- st_intersection(line,poly)

The result here is one multilinestring and I was wondering if there is a way the output of the function to be multiple linestrings instead. I know this can be done with:

    inters %>% st_cast("LINESTRING")

but this will transform all other multilinestrings in the main dataset I'm working with and I'm trying to avoid it.  

Another thing that can be used might be some kind of additional output (flag) from the function that can be used to mark these multilinestrings so they can be separated from the rest of the data

**Comment by edzer** [comment]
```r
l <- lengths(st_geometry(inters))
```
tells you how many `LINESTRING`s you have in each `MULTILINESTRING`, and
```r
rep(seq_along(st_geometry(inters)), l)
```
might generate the field that points you to the origin of each `LINESTRING` obtained from `st_cast`.

**Comment by alazarovski** [comment]
I really appreciate your help. I changed the example to show what really is the main cause of my problem. In the beginning I have a multilinestring crossing a polygon. After the `st_intersection` I need to get two multilinestrings in two rows like in the image below. It is crucial to get the multilinestrings separated because there is a gap. Is there maybe a built in possibility in the package or manually somehow. 

```{r}
# sample polygon
poly <- data.frame(lon = c(-3.5, 1, 1, 2, 2, 3, 3, -3.5, -3.5),
                   lat = c(0, 0, 1, 1, 0, 0, 2, 2, 0),
                   var = 1) %>% 
  st_as_sf(coords = c("lon", "lat"), dim = "XY") %>% group_by(var) %>% 
  summarise(geometry = st_union(geometry), do_union = F) %>% st_cast("POLYGON")

# sample line
line <- data.frame(lon = c(-4, -3, -2, -2, -3, 4), lat = c(0.5, 0.5, 1, 0.5, 1.5, 0.5), var = 1) %>% 
  st_as_sf(coords = c("lon", "lat"), dim = "XY") %>% group_by(var) %>%
  summarise(geometry = st_union(geometry), do_union = F) %>% st_cast("MULTILINESTRING")

# calculating intersection of line with polygon
inters <- st_intersection(line,poly)
``` 

![sample](https://user-images.githubusercontent.com/31340634/39304233-57fcdb8e-4959-11e8-8c53-1a5b546a4399.PNG)

**Comment by alazarovski** [comment]
Yes, it is an self-intersecting line which is why it is formated as `MULTILINESTRING`. What I'm trying to achieve is to get the `LINESTRING`s on the left-hand side marked differently than the `LINESTRING` on the right-hand side. Basically to make the function differentiate the two parts that are the output from the intersection. This would solve my problem completely, but I simply do not have an idea how to do it. I was hoping that an already built in argument to the function might solve this. I know that it can be used to identify and remove overlapping parts of polygons in an `sf dataframe` just by writing:

    inter <- st_intersection(poly) %>% filter(n.overlaps < 2)   

This is why I hoped that there might be a hidden feature to do this with my dataset of multilinestring and polygon. 

If it is not possible to get the output from the third part of the image in the previous comment I will close this issue. 

Thank you again

**Comment by edzer** [comment]
Maybe use
```r
> inters %>% st_cast("LINESTRING") %>% st_intersects
Sparse geometry binary predicate list of length 4, where the predicate was `intersects'
 1: 1, 2, 3
 2: 1, 2, 3
 3: 1, 2, 3
 4: 4
```
?

**Comment by alazarovski** [comment]
yes, but in some cases there can be intersections on both sides like below:
![sample2](https://user-images.githubusercontent.com/31340634/39313687-e2685f1e-4972-11e8-9d81-7b4c07b63014.PNG)

whether it intersects is unfortunately not good enough indicator to predict whether the `LINESTRING` belongs to the right or left-hand side.

**Comment by alazarovski** [comment]
I'll figure how to use this to group the `LINESTRING`s according to whom they intersect with. Thank you once again
