### ISSUE TITLE
Title parameters ignored when plotting sf object

### ISSUE THREAD

**Issue by smwoodman** [r-spatial/sf#727]
Not sure if this is intentional, but parameters such as cex.main and col.main are not used when plotting a sf object, but they are used when plotting a sfc object.

Here is an example of plotting a sfc object and a sf object and the different title behavior:

```
library(sf)
nc <- 
  st_read(
    system.file("shape/nc.shp", package = "sf"),
    stringsAsFactors = FALSE,
    quiet = TRUE
  )

# Plot sfc object, title is larger and red
plot(st_geometry(nc), main = "title", cex.main = 1, col.main = "red")

# Plot sf object, title does not change size and is black
plot(nc[1], main = "title", cex.main = 2, col.main = "red")
```

**Comment by edzer** [comment]
(messy commit: only the plot.R change addresses this). This should now work, except that the space reserved for larger titles isn't increased; up to cex.main=2 seems to work now.

**Comment by smwoodman** [comment]
Those arguments now work for me, thank you for the quick response! Understood about the space for larger titles, is that something that will be addressed in later commits or should I use par() to reserve more space for larger titles?

**Comment by edzer** [comment]
I'm afraid at the moment `sf::plot` takes over control of `par(mar=...)`.

**Comment by smwoodman** [comment]
Got it, thanks again

**Comment by smwoodman** [comment]
Hi @edzer , your comment about `sf::plot` taking control of `par()` made me wonder - is it possible to plot separate sf objects in the same window, i.e. using `par(mfrow)` or `layout`? And if that is not currently supported, would I need to use `ggplot2` or would you have a different recommendation? 

Apologies if this is not the right place to ask this; let me know if I should open a new issue.

**Comment by edzer** [comment]
This for instance works:
```r
> par(mfrow=c(2,2))
> plot(nc[1], reset = FALSE, key.pos = NULL)
> plot(nc[2], reset = FALSE, key.pos = NULL)
> plot(nc[3], reset = FALSE, key.pos = NULL)
> plot(nc[4], reset = FALSE, key.pos = NULL)
```
You can't have sub-plots with individual keys, as that needs to take over the `mfrow` (or `layout`) for the key placement.

**Comment by smwoodman** [comment]
Ah, got it. Thank you!!
