### ISSUE TITLE
travis false positives despite postgres errors

### ISSUE THREAD

**Issue by edzer** [r-spatial/sf#729]
Although travis checks currently look green (@pat-s) we do see errors for postgres-related tests on r-release and r-devel. @etiennebr could you take a look at the errors?

**Comment by etiennebr** [comment]
Debugging Travis is hard :(. Do you happen to know if there is a way to step into a Travis instance to see what fails  exactly (I have no errors locally)? It is surprising that the build passes despite these errors. @pat-s, do I understand correctly that you think the patch might solve this?

**Comment by pat-s** [comment]
The patch fixes the false positive green build most likely, see https://github.com/ropenscilabs/tic/issues/44.

The errors itself need to be fixed as normal errors. But I haven't taken a look from the PC yet. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pat-s** [comment]
There seem to be issues with R >= 3.5.0 and Travis in general right now: https://stat.ethz.ch/pipermail/r-sig-debian/2018-April/002829.html

Maybe building the cache again helps (Travis - Settings - Caches). However, this could also break r-oldrelease then as the packages from R 3.4 and 3.5 are not compatible with each other.
But you could then just comment r-oldrelease. 
In any case, these are just guesses. I'll try in my fork first.

**Comment by pat-s** [comment]
Rebuilding the cache did not help. I even get the errors on r-oldrelease now (https://travis-ci.org/pat-s/sf/jobs/373383128) which is btw running on R 3.3.3

I also cannot reproduce the errors locally. 

Wondering where the two GDAL and Proj4 versions are coming from here:

```
─  checking tests ...  Running ‘aggregate.R’
   4c4
   < Linking to GEOS 3.5.0, GDAL 2.2.2, proj.4 4.8.0
   ---
   > Linking to GEOS 3.5.1, GDAL 2.2.1, proj.4 4.9.3
```

Did you already check which commit broke the build?

**Comment by edzer** [comment]
@etiennebr  part of the challenge is testthat, which hides pretty much all output. You can create a small R script that should show you some output, and put that in the `tests` directory, and a .Rout file with the output you see; travis will then echo the output diffs.

**Comment by edzer** [comment]
Thanks for checking - indeed, things seem to have resolved themselves (once more)!
