### ISSUE TITLE
Strange plotting since v0.6-2

### ISSUE THREAD

**Issue by felberr** [r-spatial/sf#733]
I used `layout()` to split my plot device into two columns with different widths. Then I plotted a matrix (representing a raster) with `image()` followed by adding other sp-objects using `plot(..., add=TRUE)`. This worked really smooth until I updated the sf package form v0.6-0 to v0.6-2. 

```r
layout(matrix(1:2, ncol=2), widths=c(6,1))
par(mar=c(3,3,3, 1))

plot(NA, xlim=range(LON), ylim=range(LAT)-c(0.05, 0), xlab="", ylab="")
image(LON, LAT, n1, add=TRUE, col=clrs, breaks=brks)
plot(r_lonlat[,'LINST'], col='#3fc5ea',lwd=1, add=TRUE)                  # add rivers
plot(l_lonlat[,'OBJVAL'], col='#3fc5ea', border='#329dbb', add=TRUE)     # add lakes
plot(b_lonlat[,'ICC'], add=TRUE, col=NA, lwd=1, lty=1)                   # add borders 

par(mar=c(6,3,6,0.5))
image.scale(n1, col=clrs, breaks=brks, horiz=FALSE, xlab=""); box()
```

This is what I get with the new sf version (v0.6-2)
![wrong_plot](https://user-images.githubusercontent.com/16633190/39531524-a1386544-4e2b-11e8-80c4-6510189a02a9.png)

This is what I expect and what was ok with v0.6-1:
![right_plot](https://user-images.githubusercontent.com/16633190/39531441-70c964e4-4e2b-11e8-9c6d-9aded9079311.png)

**Comment by Robinlovelace** [comment]
I think you may just need to add `reset = FALSE` in the first plot argument. I stumbled on a similar issue and that fixed it for me, as documented here: https://github.com/r-spatial/sf/issues/707

**Comment by felberr** [comment]
@Robinlovelace Thanks a lot for the hint. I tried that already, but something went wrong while updating the package. Thus `reset = FALSE` didn't had an effect.

Hmmm, that means that I have to change many lines in my old code... Anyway, a better way of updating the sf package would be to set `reset = FALSE` as default in order to keep old code running without any troubles.

**Comment by edzer** [comment]
It is hard to make everyone happy. But by the time we agree that your code has become old, you will probably have agreed to `reset = TRUE` being the better choice between two evils. #704 is a larger problem than this one (and #707), as it affects all novice users.

**Comment by felberr** [comment]
A similar problem as above, when plotting multiple maps in a device using `layout` to arrange subplots.

I have two `sf`-objects `r` and `b` and like to plot these into a figure with multiple sub-plots. As I learned above `reset = FALSE` is needed for correct plotting of multiple `sf`-objects. Here I set `mar = c(3, 5, 3, 3)` which should be applied to each subplot. But it doesn't. The second plot has different margins.

The [code](#correct) further down shows a solution (i.e. set `mar = c(3, 5, 3, 3)` again for the second plot). Is there a better way to do that? Imagine a figure with more than two plots. I don't like to repeat before each `par(mar = c(3, 5, 3, 3)` before each subplot. 

__Code with wrong margins__
```r
# start plot
layout(matrix(1:2, ncol = 2))
par(mar=c(3, 5, 3, 3))

# first map
plot(NA, ylim = c(45.6, 47.9)), xlim = c(5.9, 10.5))
plot(r['LINST'], add = TRUE, reset =FALSE)
plot(b['ICC'], add = TRUE, col = NA, reset = FALSE)

# second map
plot(NA, ylim = c(45.6, 47.9), xlim = c(5.9, 10.5))
plot(r['LINST'], add = TRUE, reset = FALSE)
plot(b['ICC'], col = NA,  add = TRUE, reset = FALSE)
```
![image](https://user-images.githubusercontent.com/16633190/42124997-430b279c-7c6e-11e8-8d85-af274ebfb39f.png)

__<a name="correct"></a>Code with correct margins__
```r
# start plot
layout(matrix(1:2, ncol = 2))
par(mar = c(3, 5, 3, 3))

# first map
plot(NA, ylim = c(45.6, 47.9), xlim = c(5.9, 10.5))
plot(r['LINST'], add = TRUE, reset =FALSE)
plot(b['ICC'], add = TRUE, col = NA, reset = FALSE)

# second map
par(mar = c(3, 5, 3, 3))   # repeat margins
plot(NA, ylim = c(45.6, 47.9), xlim = c(5.9, 10.5))
plot(r['LINST'], add = TRUE, reset = FALSE)
plot(b['ICC'], col = NA, add = TRUE, reset = FALSE)
```
![image](https://user-images.githubusercontent.com/16633190/42125004-557f047a-7c6e-11e8-8827-1e967a6b655e.png)

**Comment by edzer** [comment]
Have you tried plotting an `sfc` object (say, `st_geometry(r)`) in the plot statement without `add=TRUE` (i.e., the ones with `NA` in your case), rather than an `sf` object?

**Comment by felberr** [comment]
No I haven't. Thanks for the tip, it solved my problem. 

`plot(NA, ...)`  was just a placeholder to plot matrix values with `image( )`. I changed that to have a `raster`-object (i.e. `r_ft`). Now I can even omit `reset = FALSE`. The final code is:

```r
layout(matrix(1:2, ncol=2))
par(mar=c(3, 5, 3, 3))

### first plot
plot(r_ft, ylim = c(45.63, 47.9), xlim = c(5.95, 10.5), axes = TRUE, legend = FALSE)
plot(st_geometry(r), add = TRUE)
plot(st_geometry(b), add = TRUE)

### second plot
plot(r_ft, ylim = c(45.63, 47.9), xlim = c(5.95, 10.5), axes = TRUE, legend = FALSE)
plot(st_geometry(r), add = TRUE)
plot(st_geometry(b), add = TRUE)
```

and I can use the nicely formatted axis labels using 
```r
plot(st_geometry(r), type = "n", ylim = c(45.63, 47.9), xlim = c(5.95, 10.5), axes = TRUE)
plot(r_ft, add = TRUE, legend = FALSE)
plot(st_geometry(r), add = TRUE)
plot(st_geometry(b), add = TRUE)
```

Thanks a lot for your help.

**Comment by edzer** [comment]
Good to know - thanks for the feed back!
