### ISSUE TITLE
Table to sf object

### ISSUE THREAD

**Issue by fabiolexcastro** [r-spatial/sf#734]
Hello everyone! 

I would like to know how can I convert a tibble into a sf object (points). I have looking in the help of the library, and until now I haven't found something useful. 

Thanks a lot,
Fabio Castro

**Comment by Nowosad** [comment]
Is this helpful - https://github.com/r-spatial/sf/issues/385?

**Comment by edzer** [comment]
Solved?

**Comment by fabiolexcastro** [comment]
Yes, it was solved. Thank you so much @Nowosad
