### ISSUE TITLE
Is there an `st_is_empty` or an equivalent? 

### ISSUE THREAD

**Issue by Demetrio92** [r-spatial/sf#738]
I have a dataset 
```R
> data_table$geometry_column  
Geometry set for 133643 features  (with 335 geometries empty)
geometry type:  POINT
dimension:      XY
bbox:           xmin: ... ymin: ... xmax: ... ymax: ...
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
First 5 geometries:
...
```
which is a result of multiple cleaning/merging steps. Now, somewhere there is a an empty geometry. How could I found which one? 
I could do 
```R
st_as_text(data_table$geometry_column) == "POINT EMPTY"
```
but it's slow and ugly. Also, if I want to do the same for a geometry with lines, I'd need `LINE EMPTY`. 
Is there a better way to do this? Like `st_is_empty` or similar?

**Comment by mdsumner** [comment]
There is `st_is_empty`, since a release early in the year (0-6-0 I believe).

**Comment by Demetrio92** [comment]
@mdsumner oh! No clue, how I missed it! Thanks!
