### ISSUE TITLE
Filter sf object without loading library leads to incorrect bbox

### ISSUE THREAD

**Issue by gregmacfarlane** [r-spatial/sf#740]
I'm trying to write a function where a `sf` object gets filtered, and then I need 
the `bbox` of the filtered object. I don't want to load the `sf` library to keep
the namespace cleaner. But this leads to a couple of issues. First, the
`dplyr::filter(sf)` function returns a `data_frame` instead of an `sf` object,
meaning I need to transform it back. But for some reason, the new `wake` object
has the same bounding box as the orginal `nc` object.

```r
library(magrittr)

# all north carolina counties
nc <- sf::st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
# only wake county
wake <- dplyr::filter(nc, NAME == "Wake") %>% sf::st_as_sf()
  
sf::st_bbox(wake) == sf::st_bbox(nc)
## xmin ymin xmax ymax 
## TRUE TRUE TRUE TRUE
```

If I load `sf`, then the bounding box is correct.

```r
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
# only wake county
wake <- dplyr::filter(nc, NAME == "Wake") 
  
st_bbox(wake) == st_bbox(nc)

##  xmin  ymin  xmax  ymax 
## FALSE FALSE FALSE FALSE
```

Two questions:

  - How can I use `dplyr::filter` properly for sf objects without loading the sf library?
  - How does the bare `data_frame` retain the larger group's bounding box?

**Comment by gregmacfarlane** [comment]
I should also note that I am using a recent version of `sf`:

```txt
sf           0.6-1      2018-03-22 cran (@0.6-1) 
```

I just spun up a VM running with sf 0.6-0, and the issue does not appear there.

**Comment by Nowosad** [comment]
Hey @gregmacfarlane - I think that it is impossible. That is a limitation of the S3 class.

**Comment by gregmacfarlane** [comment]
I think that's fair that the methods are different, but why should the bbox of a newly-created sf object have the value of the sf object it was filtered from?

**Comment by yutannihilation** [comment]
IIUC, this issue has already been fixed by this commit: https://github.com/r-spatial/sf/commit/4cd279a55b6e37356e8e232396b2322a1eb7da84.

Actually, on my local environment it works fine with sf 0.6-2:

``` r
library(magrittr)

# all north carolina counties
nc <- sf::st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
# only wake county
wake <- dplyr::filter(nc, NAME == "Wake") %>% sf::st_as_sf()

sf::st_bbox(wake) == sf::st_bbox(nc)
#>  xmin  ymin  xmax  ymax 
#> FALSE FALSE FALSE FALSE
```

Created on 2018-05-12 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by gregmacfarlane** [comment]
This is a duplicate of #710
