### ISSUE TITLE
Some commands cannot be interrupted by CTRL+C

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/sf#743]
Some of `sf`'s commands are not interrupted by `CTRL+C`. Example: I have mistyped an `st_crop` operation on a large dataset and I have been waiting for hours, since I do not want to kill the R session.

Maybe a more frequent use of `checkUserInterrupt()` (or similar) in the C/C++ source code would be useful.
See [here](https://github.com/tidyverse/dplyr/issues/123) for when this has been discussed for the `tidyverse`.

**Comment by dbaston** [comment]
@edzer The `GEOSSTRtree_insert_r` operation should be pretty fast. (You could check for an interrupt after inserting an item, though). But let me know if you think interrupt checks are needed somewhere in GEOS and I can look into it.

**Comment by edzer** [comment]
Thanks, @dbaston ! Things should be (more) fine, now.
