### ISSUE TITLE
reading arcSDE / PostgreSQL st_geometry data with sf: Error in CPL_read_wkb(x, EWKB, spatialite) 

### ISSUE THREAD

**Issue by ratnanil** [r-spatial/sf#745]
I have a postGIS database with a schema, and I'd like to use sf::st_read_db() to import the data into R. I get an error message with the request to file an issue, so this is what I am doing. It might be a bit of a challenge to create a reproducible example, but maybe you guys can already gather information from the error message? 
```
library(RPostgreSQL) 

library(sf)

conn = dbConnect(
  PostgreSQL(),
  host = "ipadress", 
  dbname = "dbname",
  user = "user",
  password = "password"
  ) 

st_read_db(conn = conn,table = c("schema", "table"),geom_column = "shape",EWKB = T)
#> Warning in postgresqlQuickSQL(conn, statement, ...): Could not create
#> execute: SELECT * from "geometry_columns"
#> type is 85
#> Error in CPL_read_wkb(x, EWKB, spatialite): reading this sf type is not supported, please file an issue


st_read_db(conn = conn,table = c("schema", "table"),geom_column = "shape",EWKB = F)
#> Warning in postgresqlQuickSQL(conn, statement, ...): Could not create
#> execute: SELECT * from "geometry_columns"
#> wkbType: 268440917
#> Error in CPL_read_wkb(x, EWKB, spatialite): unsupported wkbType dim in switch
```

I don't understand where the query `SELECT * from "geometry_columns"` comes from... any ideas what I could test?

**Comment by edzer** [comment]
Maybe fire up psql and do
```
postgis=# select * from geometry_columns ;
 f_table_catalog | f_table_schema | f_table_name | f_geometry_column | coord_dimension | srid | type 
-----------------+----------------+--------------+-------------------+-----------------+------+------
(0 rows)
```
and give the output you see. The second error is expected (although it could look nicer), as `EWKB=TRUE` for postgis.

**Comment by ratnanil** [comment]
I might have to mention that the postGIS Database was (regrettably) created with arcSDE. It seems I do not have a table / view named `geometry_columns` (neither in public or elsewhere), the closest thing I _do_ have is `sde_geometry_columns` and `st_geometry_columns`. Their respective outputs are:

```
SELECT * FROM sde_geometry_columns;
"f_table_catalog";"f_table_owner";"f_table_schema";"f_table_name";"f_geometry_column";"storage_type";"geometry_type";"properties";"coord_dimension";"max_ppr";"srid"
"histogwn";"ugeb1";"ugeb1";"ta25_109_1876";"shape";2;11;0;2;0;21781
"histogwn";"ugeb1";"ugeb1";"ta25_108_1929";"shape";2;11;0;2;0;21781
"histogwn";"ugeb1";"ugeb1";"ta25_108_1899";"shape";2;11;0;2;0;21781
```

```
SELECT * FROM st_geometry_columns;
"database_name";"owner_name";"schema_name";"table_name";"column_name";"geometry_type";"properties";"srid";"coord_dimension"
"histogwn";"ugeb1";"ugeb1";"ta25_109_1876";"shape";11;0;21781;2
"histogwn";"ugeb1";"ugeb1";"ta25_108_1929";"shape";11;0;21781;2
"histogwn";"ugeb1";"ugeb1";"ta25_108_1899";"shape";11;0;21781;2
```

**Comment by edzer** [comment]
I don't think we can consider it a PostGIS table, then? Is there a plan B to read such things?

**Comment by ratnanil** [comment]
I'm not much of a database guy, so I was under the impression that arcSDE creates PostGIS databases (which quite frankly would have been clever). 
> Is there a plan B to read such things?

Yes, I can just export the whole shabang into a more reader friendly format. Linking into the postgreSQL database with `sf` would just have been phenomenally elegant, since the data in the db is continually getting updated. It seems thought hat I must first understand this arcSDE-PostgreSQL database (especially the `st_geometry` / `sde_geometry` columns) before I can venture on this path. 

Or do you have an idea what these datatypes (`st_geometry` / `sde_geometry`) are and how they could be read by `sf`?

**Comment by edzer** [comment]
You can read the table using `RPostgreSQL::dbReadTable`, convert the wkb column using `sf:::hex_to_bin` and `st_as_sfc` with `EWKB=TRUE`; this worked for me:
```r
library(sf)
library(RPostgreSQL)
conn <- dbConnect(PostgreSQL(), dbname = "postgis")
library(sp)
example(meuse, ask = FALSE, echo = FALSE)
st_write(st_as_sf(meuse), "PG:dbname=postgis", "meuse", layer_options = "OVERWRITE=true")
tbl = RPostgreSQL::dbReadTable(conn, "meuse")
st_as_sfc(lapply(tbl$wkb_geometry, sf:::hex_to_raw), EWKB = TRUE)
```
but you loose the CRS when reading this way, as, for you, it is in the `st_geometry_columns` table. @etiennebr any other ideas?

**Comment by ratnanil** [comment]
Interesting! This looks like a promising approach. Running `lapply(tbl$shape, sf:::hex_to_raw)` column works, but including this in `st_as_sfc()` does not. I've submitted details below. 

You mentioned `sf:::hex_to_bin` in the text but used `sf:::hex_to_raw` in the code. Was that a typo? 
```
library(RPostgreSQL)
library(sf)
conn = dbConnect(
  PostgreSQL(),
  host = "host", 
  dbname = db
  user = "user"
  password = "password"
  ) 


tbl = RPostgreSQL::dbReadTable(conn, c("schema", "table"))
#> Warning in postgresqlExecStatement(conn, statement, ...): RS-DBI driver
#> warning: (unrecognized PostgreSQL field type st_geometry (id:3525248) in
#> column 1)

lapply(tbl$shape, sf:::hex_to_raw)
#> [[1]]
#>   [1] 72 00 00 00 0f 00 00 00 08 00 10 00 15 55 00 00 9a 01 0f 00 01 00 00
#>  [24] 00 b8 de 8a ec b9 11 bb 9f aa b2 b1 13 93 95 04 b9 cb 06 8d f7 06 bc
#>  [47] fb 0a 90 80 01 bc ca 01 da 31 a5 21 fd 86 09 a6 93 06 d4 81 06 b4 8a
#>  [70] 04 d0 d8 01 bd 92 01 dc ca 02 a4 e0 01 eb b2 07 d5 8d 11 f2 d6 01 ee
#>  [93] f0 03 f9 31 d9 73 9a 06 d4 05 a4 ca 0f f4 f5 0c bf b9 01 93 a6 02
#> 
#> [[2]]
#>     [1] a4 eb 01 00 eb 5d 00 00 08 01 18 00 15 55 00 00 8c ae 0f 00 01 00
#>    [23] 00 00 a7 de f3 8d b9 11 a1 b3 aa 85 b1 13 e2 e0 01 a6 15 fa e1 01
#>    [45] b6 20 fa e2 01 b6 28 e2 e3 01 a0 2e c6 c8 03 9c 67 f6 ac 04 ba 87
#>    [67] 01 c2 fe 05 be ba 01 e6 d4 05 98 aa 01 dc 97 01 aa 20 d6 93 01 92
```
.. and so forth _but_:

```
st_as_sfc(lapply(tbl$shape, sf:::hex_to_raw), EWKB = TRUE)
#>    type is 85
#>    Error in CPL_read_wkb(x, EWKB, spatialite) : 
  reading this sf type is not supported, please file an issue
```

**Comment by edzer** [comment]
Well, maybe it is not WKB, then, what arcSDE writes!

**Comment by ratnanil** [comment]
Ok so [this](https://stackoverflow.com/questions/38588713/plotting-a-polygon-in-r-from-shapefile-data-retrived-from-mysql) in combination with [this ](https://stackoverflow.com/a/49013533/4139249) works. Excuse my not-so-elegant coding..

```
library(RPostgreSQL)
library(sf)
library(rgeos)
library(purrr)

dat <- dbGetQuery(conn, "SELECT field, ST_AsText(shape) as geom FROM schema.table;")
dat2 <- map(dat$geom,~st_set_crs(st_as_sfc(rgeos::readWKT(.x)),21781))
dat3 <- st_as_sf(reduce(dat2, rbind))
dat4 <- cbind(dat3,dat$field)
```
Thank you for all the help, and thank you for making the world a better place with `sf`!

**Comment by etiennebr** [comment]
Thanks @ratnanil. I see you have solved your problem, but this is an interesting use case. We only support `postgis`, and I suspect that the extension is not created (your geometry is an `st_geometry`). If you have the rights on the database, could you `create extension postgis` (I think ArcSDE and postgis can coexist peacefully). Could you try the latest `sf` version (`install_github("r-spatial/sf")`) and report back.
``` r
dbGetQuery(con, "SELECT pg_typeof(shape) FROM schema.table LIMIT 1")
#>   pg_typeof
#> 1  geometry  # you probably have st_geometry from what I can see

dbGetQuery(con, "SELECT PostGIS_full_version();")    
#>   postgis_full_version
#> 1 POSTGIS="2.4.3 r16312" PGSQL="100" GEOS="3.5.1-CAPI-1.9.1 r4246" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.2, released 2016/10/24" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" TOPOLOGY RASTER

dbExecute(con, "create extension postgis")
```

If you can enable postgis, then you could try something like
```
st_read(con, "SELECT st_astext(shape)::geometry FROM schema.table;"
```
You also should be able to do in any case everything fails
``` r
dat <- dbGetQuery(conn, "SELECT field, ST_AsText(shape) as geom FROM schema.table;")
st_as_sf(dat, wkt = "geom", crs = 21781)
```
Without the need for `rgeos` and `purrr`

**Comment by ratnanil** [comment]
> If you can enable postgis, then you could try something like

Unfortunately, I cannot do this at this moment. Maybe at somepoint in the future, I would report back then.

However, the following lines you suggested work like a charm!
```
dat <- dbGetQuery(conn, "SELECT field, ST_AsText(shape) as geom FROM schema.table;")
st_as_sf(dat, wkt = "geom", crs = 21781)
```

**Comment by etiennebr** [comment]
After a quick read, it seems that the `st_geometry` format is not documented, so it would be impossible for `sf` to read. However, maybe this could work with the latest `sf` version:
``` r
st_read(con, query = "SELECT field, st_asbinary(shape) as geom FROM schema.table")
```
(You might have to `%>% st_transform(21781)` it).

**Comment by ratnanil** [comment]
Ok, so I installed the latest version of `sf` from github. While the SQL command _does_ work in psql, the R code your provided does not work in R.

So this works in psql:
`SELECT field, ST_AsText(shape) as geom FROM schema.table;`


but this doesn't work in R:
```
st_read(conn, query = "SELECT field, ST_AsText(shape) as geom FROM schema.table;")
#> Error in postgresqlExecStatement(conn, statement, ...) : 
#>   RS-DBI driver: (could not Retrieve the result : FEHLER:  Relation „geometry_columns“ existiert nicht
#> LINE 1: SELECT * from "geometry_columns"
#>                      ^
#> )

#> Error in names(out) <- make.names(names(out), unique = TRUE) : 
#>  attempt to set an attribute on NULL
#> In addition: Warning message:
#> In postgresqlQuickSQL(conn, statement, ...) :
#>  Could not create execute: SELECT * from "geometry_columns"
#> Error in CPL_hex_to_raw(vapply(x, skip0x, USE.NAMES = FALSE, "")) : 
 #> char2int: false character in hex string
```

Just for the record: as far as I am concerned, [this solution](https://github.com/r-spatial/sf/issues/745#issuecomment-389778839) is already pretty awesome. I am of course willing to test anything you want to try out!

**Comment by etiennebr** [comment]
Thanks @ratnanil. I agree, it's not easy to improve without an interface to SDE. However, don't hesitate to open an issue if some changes impact your ability to interact with an `st_geometry`.

**Comment by ratnanil** [comment]
@etiennebr: Coming back to this question: I was able to install postgis on the database and have successfully cast the st_geometry field to PostGIS `geometry`. Reading it into R with st_read() was successful as well and much more stable. The `ST_AsText()`approach failed with pseudo ZM geometries ([see this post](https://lists.osgeo.org/pipermail/postgis-users/2012-May/034082.html))

Here's the working code:

```
st_read(con, query = "SELECT t.*, st_asbinary(shape)::geometry as geometry FROM schema.table t") %>%
  select(-shape) %>%
  st_set_crs(2056)
```

**Comment by etiennebr** [comment]
Thanks for following up @ratnanil!
