### ISSUE TITLE
st_area dependency on projection

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/sf#746]
I'm not sure if this is the expected behaviour, maybe I am misunderstanding something. In any case, reporting just to be sure.

`st_area` seems to report very different values for the same polygons on different projections:
```R
library(sf)
nc = st_read(system.file("gpkg/nc.gpkg", package="sf"), quiet = TRUE)
st_area(nc) - st_area(st_transform(nc, 4326))
st_area(nc) - st_area(st_transform(nc, 3857))
```
The difference can be very significant (650km² on average for 3857).

**Comment by mdsumner** [comment]
This is the nature of projections, if you want ellipsoidal area calc use st_area on 4326, otherwise an area preserving projection (as in the laea family). st_area is strictly planar if not applied to longlat so it's user-beware

**Comment by adrfantini** [comment]
Yep, the difference seemed too huge, but looking at the distortion values of 3857 at high latitudes it checks out. My bad.
