### ISSUE TITLE
st_transform only works on one geometry column?

### ISSUE THREAD

**Issue by JimShady** [r-spatial/sf#750]
Hi,

I'm moving between a few CRS's, and have more than one geometry column. When I use st_transform I (unreasonably?) expect all geometry columns to be converted, but only one is. Any solution or work around please? Can I explicitly tell st_transform which columns to use or something? I'm quite new to sf, so I'm probably just missing something .  Example below...

```
p1          <- st_point(c(7,52))
p2          <- st_point(c(-30,20))

sfc         <- st_sfc(p1, p2, crs = 4326)

sfc         <- st_sf(sfc)

sfc         <- st_transform(sfc, 27700)

sfc$buffer  <- st_buffer(sfc, dist = 10) 

sfc         <- st_transform(sfc, 4326)

sfc
```

Thanks

James

**Comment by Nowosad** [comment]
Let me know if I understand your problem...
If you just need to transform one column - just specify it:

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.4, proj.4 4.9.3
p1          <- st_point(c(7,52))
p2          <- st_point(c(-30,20))
sfc         <- st_sfc(p1, p2, crs = 4326)
sfc         <- st_sf(sfc)
sfc         <- st_transform(sfc, 27700)
sfc$buffer  <- st_buffer(sfc$sfc, dist = 10) 

sfc$sfc         <- st_transform(sfc$sfc, 4326)
sfc
#> Simple feature collection with 2 features and 0 fields
#> Active geometry column: sfc
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: -29.99866 ymin: 20.0002 xmax: 7 ymax: 52
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#>                         sfc                         buffer
#> 1              POINT (7 52) POLYGON ((1017358 271844.9,...
#> 2 POINT (-29.99866 20.0002) POLYGON ((-2621716 -3048451...
```

Created on 2018-05-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by JimShady** [comment]
Thanks @Nowosad . That's useful, I didn't know I could explicitly tell st_transform which column to use.

How would I transform both columns, and keep them 'together' in the same resulting sf ?

**Comment by edzer** [comment]
Note the line
```
#> Active geometry column: sfc
```
all `sf` commands only act on the active geometry column, so
```r
sf = sfc # to avoid confusion?
sf         <- st_transform(sf, 4326)
```
acts only on column `sfc`. If you have multiple, you need to go through them one by one, as in
```r
sfc$buffer         <- st_transform(sfc$buffer, 4326)
```
It would be fairly trivial to write a wrapper function for that.

**Comment by JimShady** [comment]
Gotcha. Thanks @edzer and @Nowosad . I get it now. I see it's actually fairly easy.
