### ISSUE TITLE
problem using gdal_utils

### ISSUE THREAD

**Issue by tim-salabim** [r-spatial/sf#753]
@edzer I am trying to use `gdal_utils` to translate a geotiff to a png file. I know that you recommend not using `gdal_utils` directly, but if I can get it to wirk, I can drop the `gdalUtils` dependency in mapview which would be neat.

```r
library(sf)
library(stars)
library(gdalUtils)

rst = system.file("tif/L7_ETMs.tif", package="stars")
dst = tempfile(fileext = ".png")
dst2 = tempfile(fileext = ".png")

# works as expected
gdalUtils::gdal_translate(src_dataset = rst,
                          dst_dataset = dst,
                          of = "PNG",
                          b = 1,
                          verbose = TRUE)

# no errors or warnings
tmp = sf::gdal_utils(util = "translate", 
                     source = rst, 
                     destination = dst2,
                     options = c(of = "PNG", b = 1))
tmp # reports success

## works
png::readPNG(dst) 
## doesn't work
png::readPNG(dst2)
Error in png::readPNG(dst2) : file is not in PNG format
```
If I try to specify the options differently (I've tried all sorts of things):
```r
tmp = sf::gdal_utils(util = "translate", 
                     source = rst, 
                     destination = dst2,
                     options = c("-of PNG", "-b 1"))
Warning message:
In CPL_gdaltranslate(source, destination, options) :
  GDAL Error 6: Unknown option name '-of PNG'
```
Using gdal from the command line works as expected.

Also, using `util = "info"` works as expected:
```r
sf::gdal_utils(util = "info", source = rst)
```
Any advice on how to gte this working?

**Comment by mdsumner** [comment]
Hey there, this seems to work

```R
tmp = sf::gdal_utils(util = "translate", 
					 source = rst, 
					 destination = dst2 ,
					 options = c("-of",  "PNG", "-b", "1"))
```

I went back to this for a clue

https://github.com/r-spatial/stars/issues/5#issuecomment-304730035

so I guess the engine pastes those options together with space separation. (? I couldn't find any GDAL examples, all the python interfaces use "format = PNG" which is confusing). 

But, couldn't you read it direct, do your own scaling, avoid GDAL -  I guess I probably miss the actual required workflow here?

**Comment by tim-salabim** [comment]
Thanks Mike,
this seems to work indeed! Not very intuitive, but it works.
As for the workflow, this is for the case when the raster is actually not in memory but ondisk. Given that we need to provide `plainview` with a png file on the disk, it would be a waste to read and then write again. We do convert and write if the raster is in fact in memory.

**Comment by edzer** [comment]
```r
tmp = sf::gdal_utils(util = "translate", 
					 source = rst, 
					 destination = dst2 ,
					 options = c("-of" = "PNG", "-b" = "1"))
```
also seems to work.

What would be a more intuitive interface?

**Comment by tim-salabim** [comment]
I would vote for either

`options = c(of = "PNG", b = "1")` or `options = "-of PNG -b 1"` or ideally both possibilities. A check for names of the vector should be sufficient to check which version was provided.
