### ISSUE TITLE
casting multipart polygons to single polygons

### ISSUE THREAD

**Issue by jannes-m** [r-spatial/sf#763]
Hey Edzer,
first of all, thanks for the magificent **sf** package! I am using **sf** package version 0.6.3.

My issue is most likely related to #323, i.e. I would like to convert multipart polygons into single polygons. Running following code

```r
library("sf")
library("dplyr")
data("incongruent", package = "spData")
st_cast(incongruent, "POLYGON")
```
results in the warning message `1: In st_cast.MULTIPOLYGON(X[[i]], ...) : polygon from first part only`

However, if I apply `st_cast()` to each row individually,  it works as expected, i.e. the multipart polygons are in fact splitted into single polygons:

```r
lapply(1:nrow(incongruent), function(i) {
  st_cast(incongruent[i, ], "POLYGON")
  }) %>%
  do.call(rbind, .)
```
Hence, I have a work-around, but I was wondering if this behavior is intended?

**Comment by edzer** [comment]
I agree it's somewhat unexpected, and in any case inconsistent with
```
st_sf(a = 1, geom = st_sfc(st_multipoint(matrix(1:4, 2)))) %>% st_cast("POINT")
```
Will look into it.

**Comment by edzer** [comment]
It is not clear why `incongruent` is of type `GEOMETRY` (@Nowosad ?), but after homogenizing its type, casting to `POLYGON` works:
```r
st_cast(incongruent, "MULTIPOLYGON") %>% st_cast("POLYGON")
```
gives
```
Simple feature collection with 11 features and 2 fields
Attribute-geometry relationship: 0 constant, 1 aggregate, 0 identity, 1 NA's
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 417686.8 ymin: 443703 xmax: 422963 ymax: 446978
epsg (SRID):    27700
proj4string:    +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs
First 10 features:
         level    value                       geometry
1  Incongruent 4.037919 POLYGON ((420799.6 446093.8...
2  Incongruent 5.014419 POLYGON ((418664 446450, 41...
3  Incongruent 4.933000 POLYGON ((419964 446288, 41...
4  Incongruent 5.120139 POLYGON ((420368 444193, 42...
5  Incongruent 6.548912 POLYGON ((420419.8 445320.4...
6  Incongruent 6.548912 POLYGON ((419712.6 445271.9...
7  Incongruent 3.749791 POLYGON ((421779 445196, 42...
8  Incongruent 5.432837 POLYGON ((419577 446450.4, ...
9  Incongruent 5.432837 POLYGON ((419171.8 446538.5...
10 Incongruent 4.618049 POLYGON ((417687.6 444802, ...
Warning message:
In st_cast.sf(., "POLYGON") :
  repeating attributes for all sub-geometries for which they may not be constant
```

**Comment by Robinlovelace** [comment]
It's actually my fault: I created that dataset. Thanks for clarifying that Edzer. I plan to update the dataset accordingly. sf versions may help explain it, not sure - the code to reproduce the dataset is here in case of use/interest: https://github.com/Nowosad/spData/blob/master/R/congruent.R#L25

**Comment by jannes-m** [comment]
Perfect, thank you very much for pointing this out, @edzer!

**Comment by Demetrio92** [comment]
I keep having this issue after using `st_make_valid` 
```R
result = (
    big_polygons_with_lots_of_other_properties 
    %>% st_sf() 
    %>% st_transform(planar_epsg)
    %>% st_intersection(smaller_polygons_for_split %>% st_transform(planar_epsg))
    %>% st_transform(epsg_lat_lon)
    %>% st_make_valid()
    %>% st_cast('MULTIPOLYGON')  # I need this for whatever reason
    %>% st_cast('POLYGON', warn=F)  # this is fine, it repeats the attributes as expected
)
```

Interestingly, in this case `st_cast('MULTIPOLYGON')` does not raise a single warning that some geometries will be lost. 
This would be normal if the intersection in planar coordinates created some super small polygons that got converted into lines or something. But literally all of the resulting objects are valid polygons. Not sure why do I need an extra cast to `MULTIPOLYGON`. 
A minor issue, but took me a while to understand when I first saw it.

**Comment by edzer** [comment]
Can you break down your question to a minimal reproducible example?

**Comment by MGousseff** [comment]
I have similar issues. I don't know why it happens, so I could not set a minimal reproducible example, but I uploaded a not too big file on a repository, in case it would help identify why this happens :+1: 
```R
tmp <- tempdir(check = TRUE)
zf <- file.path(tmp, "example.fgb)
if(file.exists(zf)){file.remove(zf)}
if(!file.exists(zf)){
download.file(
  "https://raw.githubusercontent.com/MGousseff/lczexplore/multipleComparison/inst/extdata/example.fgb",
destfile = zf)
}

test<-read_sf(zf)
test %>% group_by(LCZ_PRIMARY) %>% summarise %>% ungroup %>% st_cast("POLYGON")
test %>% group_by(LCZ_PRIMARY) %>% summarise %>% ungroup %>% st_cast("MULTIPOLYGON") %>% st_cast("POLYGON")
```

Hope this helps a little. Seems that casting to multipolygon before casting to polygon makes the lapply trick unnecessary.

**Comment by edzer** [comment]
```r
test %>% group_by(LCZ_PRIMARY) %>% summarise %>% ungroup
```
gives you a mix of `POLYGON` and `MULTIPOLYGON`, hence the need to first cast to `MULTIPOLYGON`.

**Comment by MGousseff** [comment]
Thank you very much. I guess when the summarise returns only one geometryfor a given valuye of the grouping variable, this is what happens. But it also means you can't cast a polygon to a polygon, like it should rather do nothing or throw a warning rather than an error ? Anyway, thank you for your time, sf is so helpful on a daily basis.
