### ISSUE TITLE
st_cast changes sfc name

### ISSUE THREAD

**Issue by sebdalgarno** [r-spatial/sf#766]
In cases where there are multiple sfc columns, st_cast renames the sfc column to the first sfc column, regardless of whether it is the 'active' one.

For example:
```
nc <- st_read(system.file("shape/nc.shp", package="sf"))
nc$NewSfc <- nc$geometry
nc %<>% st_set_geometry('NewSfc')
nc %<>% st_cast("POLYGON") %>% select(AREA)
> names(nc)
[1] "AREA"     "geometry"
```

Should the name of the sfc column not still be 'NewSfc'?

**Comment by edzer** [comment]
Thanks! This should fix it; pls verify.

**Comment by sebdalgarno** [comment]
Fixed! thanks
