### ISSUE TITLE
st_difference incorrect behaviour with multiple overlapping polygons

### ISSUE THREAD

**Issue by mem48** [r-spatial/sf#770]
`st_difference` seems to be ignoring multiple overlaps and only considering the first polygon.

A simple example

```
# Make some overlapping circles
A <- st_point(c(1,0))
B <- st_sfc(list(st_point(c(5,0)), st_point(c(-3,0))))
A <- st_buffer(A, 3)
B <- st_buffer(B, 3)

# find the difference 
D <- st_difference(A,B)

# plot
plot(B, lwd = 10, border = "blue")
plot(A, lwd = 10, add = T, border = "black")
plot(D, lwd = 4, add = T, border = "red")
```
Produces this:

![rplot](https://user-images.githubusercontent.com/15819577/41201099-89436c4e-6ca9-11e8-90d7-e9091de074c2.png)

But I would expect it to cut out the blue circle on both sides.

**Comment by edzer** [comment]
You're mixing `sfg` and `sfc` objects, and don't take into account what happens with the latter when used in `st_difference`. Maybe try
```r
D <- st_difference(A,st_combine(B))
```
![x](https://user-images.githubusercontent.com/520851/41201266-dcf4d642-6cb4-11e8-9f95-ee38b838076a.png)

**Comment by mem48** [comment]
> You're mixing sfg and sfc objects
valid point, how about this example

```
# Make some overlapping circles as data frame
A <- st_sfc(st_point(c(1,0)))
A <- st_as_sf(data.frame(id = 1, geometry = A))
B <- st_sfc(list(st_point(c(5,0)), st_point(c(-3,0))))
B <- st_as_sf(data.frame(id = 1:2, geometry = B))
A <- st_buffer(A, 3)
B <- st_buffer(B, 3)

# check the geommetries
class(A$geometry) == class(B$geometry)

# find the difference
D <- st_difference(A,B)

# plot
plot(B$geometry, lwd = 10, border = "blue")
plot(A$geometry, lwd = 10, add = T, border = "black")
plot(D$geometry, lwd = 4, add = T, border = "red")
```

This produces an even stranger result

![rplot01](https://user-images.githubusercontent.com/15819577/41202968-f7aa2da2-6cc8-11e8-9a6d-76b19fec161a.png)

**Comment by edzer** [comment]
Since `A` and `B` have different length, `A` is automatically recycled to length 2 in `st_difference(A,B)`. Try
```r
> plot(D$geometry[1], lwd = 10, border = "blue", col = 'red')
> plot(D$geometry[2], lwd = 10, border = "blue", col = 'red')
```
and you might understand what is going on. If you explain what you are trying to achieve, I might be able to help.
