### ISSUE TITLE
`c.sfc()`: geometry empty mismatch?

### ISSUE THREAD

**Issue by uribo** [r-spatial/sf#773]
I think that seems that geometry empty of `c.sfc ()` is not correct. There are 2 sfg objects of empty, but geometry empty is 1.

``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.3.0, proj.4 5.1.0
c(st_sfc(st_point(c(NA_real_, NA_real_))),
  st_sfc(st_point(c(NA_real_, NA_real_))),
  st_sfc(st_point(c(134, 43))))
#> Geometry set for 3 features  (with 1 geometry empty)
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 134 ymin: 43 xmax: 134 ymax: 43
#> epsg (SRID):    NA
#> proj4string:    NA
#> POINT EMPTY
#> POINT EMPTY
#> POINT (134 43)
```

Created on 2018-06-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

In this case, to make geometry empty 2, need to add the following line to [`c.sfc()`](https://github.com/r-spatial/sf/blob/4f8bcd25b74dbf266102c512b244207e7cd78452/R/sfc.R#L140-L157).

```r
attr(ret, "n_empty") =
	sum(unlist(lapply(lapply(lst, attributes), `[[`, "n_empty"), recursive = FALSE))
```

If this point of view is correct, I will submit a PR for this :)

**Comment by edzer** [comment]
Thanks - please do!
