### ISSUE TITLE
R 3.4.3 - cannot install sf packet ?

### ISSUE THREAD

**Issue by shredman01** [r-spatial/sf#775]
tried to install "sf" packet on a Debian Jessie R version 3.4.3 without success. Install all R packages as root with this command;

su - -c "R -e \"install.packages('sf', repos='http://cran.rstudio.com/')\""

get the following error messages;

checking for udunits2/udunits2.h... no
checking for ut_read_xml in -ludunits2... no
configure: error: in `/tmp/Rtmp8aOs2K/R.INSTALL6fa840e79c1f/units':
configure: error:
--------------------------------------------------------------------------------
  libudunits2.so not found!

  If the udunits2 library is installed in a non-standard location, use:

    --configure-args='--with-udunits2-lib=/usr/local/lib'

  for example, if the library was not found, and/or

    --configure-args='--with-udunits2-include=/usr/include/udunits2'

  if the header was not found, replacing paths with appropriate values for your
  installation. You can alternatively use the UDUNITS2_INCLUDE and UDUNITS2_LIBS
  environment variables.

  If udunits2 is not installed, please install it.
  It is required for this package.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package âunitsâ
* removing â/usr/local/lib/R/site-library/unitsâ
ERROR: dependency âunitsâ is not available for package âsfâ
* removing â/usr/local/lib/R/site-library/sfâ

Die heruntergeladenen Quellpakete sind in
        â/tmp/RtmpxzEVPX/downloaded_packagesâ
Warnmeldungen:
1: In install.packages("sf", repos = "http://cran.rstudio.com/") :
  Installation des Pakets âunitsâ hatte Exit-Status ungleich 0
2: In install.packages("sf", repos = "http://cran.rstudio.com/") :
  Installation des Pakets âsfâ hatte Exit-Status ungleich 0

installing libudunits2 or udunits2 packages also failed. What can I do ? Other R packages are installed without any problems.

Regards,
Frank

**Comment by shredman01** [comment]
after installing libudunits2-dev and R package udunits2, the folling error messages appears when I try to install sf package:

su - -c "R -e \"install.packages('sf', repos='http://cran.rstudio.com/')\""
........
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++  -I/usr/share/R/include -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:0:
../inst/include/units.h:7:53: error: wrong number of template arguments (4, should be 3)
 typedef XPtr<ut_unit,PreserveStorage,finalizeUT,true> XPtrUT;
                                                     ^
In file included from /usr/local/lib/R/site-library/Rcpp/include/Rcpp.h:46:0,
                 from ../inst/include/units.h:2,
                 from RcppExports.cpp:4:
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/XPtr.h:48:7: error: provided for âtemplate<class T, template<class> class StoragePolicy, void (* Finalizer)(T*)> class Rcpp::XPtrâ
 class XPtr :
       ^
In file included from RcppExports.cpp:4:0:
../inst/include/units.h:7:61: error: invalid type in declaration before â;â token
 typedef XPtr<ut_unit,PreserveStorage,finalizeUT,true> XPtrUT;
                                                             ^
/usr/lib/R/etc/Makeconf:168: recipe for target 'RcppExports.o' failed
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package âunitsâ
* removing â/usr/local/lib/R/site-library/unitsâ
ERROR: dependency âunitsâ is not available for package âsfâ
* removing â/usr/local/lib/R/site-library/sfâ

Die heruntergeladenen Quellpakete sind in
        â/tmp/RtmpQ3QQyb/downloaded_packagesâ
Warnmeldungen:
1: In install.packages("sf", repos = "http://cran.rstudio.com/") :
  Installation des Pakets âunitsâ hatte Exit-Status ungleich 0
2: In install.packages("sf", repos = "http://cran.rstudio.com/") :
  Installation des Pakets âsfâ hatte Exit-Status ungleich 0

**Comment by edzer** [comment]
Your problem is with installing the units package, not sf (so far); units is a dependency of sf. Please raise the issue here: http://github.com/r-quantities/units/
