### ISSUE TITLE
gUnaryUnion with sf

### ISSUE THREAD

**Issue by RS-eco** [r-spatial/sf#776]
I am trying to dissolve a shapefile to a larger group using the sf package, but so far seem to struggle.
Here is a reproducible example of what I want to do, using the rgeos package:

#install.packages("rworldmap")
data(countriesLow, package="rworldmap")

library(rgeos)
continent <- gUnaryUnion(countriesLow, id=countriesLow$continent)
plot(continent)

I am trying to do the same with st_union from the sf package, but sofar struggle to achieve the same result:

library(sf)
countriesLow <- st_as_sf(countriesLow)

library(dplyr)
continent <- countriesLow %>% select(continent) %>% st_union(by_feature=T)
plot(continent)

Any suggestions for how to solve this would be hugely appreciated.

**Comment by tim-salabim** [comment]
This seems more like a question for StackOverflow... FWIW, you need to `group_by(continent)` and then `summarise()`
```r
data(countriesLow, package="rworldmap")

countriesLow <- st_as_sf(countriesLow)

continent <- countriesLow %>% 
  group_by(continent) %>% 
  summarise()

plot(continent)
```

**Comment by RS-eco** [comment]
Thanks!

**Comment by rsbivand** [comment]
This isn't an SO question, it's to do with **sf** being tidier than is good for it, and way slower than **sp**/**rgeos** - correct me if I'm wrong. The wiki says use `sf::aggregate.sf()`, so I'll try below - I use `aggregate()` in teaching. Tim's example omits **dplyr** (needed for `group_by` anyway). This is anyway a lot slower than `rgeos::gUnaryUnion()`:

```
system.time(gUU <- gUnaryUnion(countriesLow, as.character(countriesLow$continent)))
#   user  system elapsed 
#  1.882   0.000   1.886 
system.time(tidy <- summarise(group_by(countriesLow_sf, continent)))
#   user  system elapsed 
#  8.942   0.000   8.956 
```
It also returns a tibble, which should always be avoided, as it pretends to be a data.frame but can created unadvertised havoc in modelling. If someone wants a tibble, they should coerce explicitly - the input and output objects should be the same class (as in `aggregate()`).

This seems to work but returns only a data frame, and possibly discards four of the six output features although fastest:

```
system.time(continent1 <- aggregate(st_geometry(countriesLow_sf), list(countriesLow_sf$continent), head, 1))
#    user  system elapsed 
#  0.014   0.000   0.014 
```

This is also time-consuming, but fortunately does not coerce to tibble, and would be my preference despite taking a lot longer:

```
system.time(continent2 <- aggregate(countriesLow_sf[,"geometry"], list(countriesLow_sf$continent), head, 1))
#   user  system elapsed 
#  8.896   0.000   8.909 
```

This feature-only unary union is also slow and does not identify the features (`gUnaryUnion` inserts IDs in ID slots, accessed by `row.names()`):

```
system.time(continent3 <-st_as_sfc( tapply(st_geometry(countriesLow_sf), list(countriesLow_sf$continent), st_union)))
#   user  system elapsed 
#  8.874   0.000   8.887
```

**Comment by rsbivand** [comment]
OK, thanks:

```
system.time(continent1 <- st_union(select(countriesLow_sf, continent), by_feature=TRUE))
#   user  system elapsed 
#  0.661   0.000   0.667
```

**Comment by edzer** [comment]
Another worry is resolving internal boundaries; sp:
![sp](https://user-images.githubusercontent.com/520851/41710051-fb9baf06-7544-11e8-890c-ac63f6087e94.png)
sf:
![sf](https://user-images.githubusercontent.com/520851/41710060-011507f2-7545-11e8-8cf7-2938b8ec18e3.png)
Does rgeos set precision to a non-zero value, before unioning?

**Comment by edzer** [comment]
This fixes propagation of precision through `sf:::aggregate.sf`
```r
a <- aggregate(st_set_precision(countriesLow, 1e6), list(countriesLow$continent), function(f) f[1])
```
Timing is now also similar:
```r
> system.time(a <- aggregate(st_set_precision(countriesLow, 1e6), list(countriesLow$continent), function(f) f[1]))
   user  system elapsed 
  1.959   0.000   1.959 
> data(countriesLow, package="rworldmap")
> system.time(continent <- gUnaryUnion(countriesLow, id=countriesLow$continent))
   user  system elapsed 
  1.986   0.000   1.986 
```
The dplyr pipeline with `st_set_precision(1e8)` inserted did not have this problem, and has identical timing.
```r
> countriesLow = st_as_sf(countriesLow)
> system.time(continent <- countriesLow %>% st_set_precision(1e8) %>% select(continent) %>% group_by(continent) %>% summarize())
   user  system elapsed 
   1.94    0.00    1.94 
```
Interestingly, it gives a seventh continent:
```r
> continent
Simple feature collection with 7 features and 1 field
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -180 ymin: -89.9989 xmax: 180 ymax: 83.5996
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
precision:      1e+08 
# A tibble: 7 x 2
  continent                                                            geometry
  <fct>                                                      <MULTIPOLYGON [°]>
1 Africa        (((37.85695 -46.94427, 37.81395 -46.96287, 37.61179 -46.94644,…
2 Antarctica    (((-147.5883 -76.64984, -147.5788 -76.66276, -147.7297 -76.653…
3 Australia     (((158.8788 -54.70974, 158.8452 -54.74927, 158.8359 -54.704, 1…
4 Eurasia       (((-26.26413 -58.43514, -26.25984 -58.4923, -26.41533 -58.4398…
5 North America (((-155.5813 19.01202, -155.6256 18.96391, -155.6808 18.96768,…
6 South America (((-67.5752 -55.88966, -67.61142 -55.89173, -67.69953 -55.8731…
7 NA            (((73.70747 -53.13707, 73.58799 -53.18461, 73.46511 -53.1842, …
```

**Comment by tiernanmartin** [comment]
@edzer did you just discover the Tidyverse continent? 😉

**Comment by Nowosad** [comment]
It seems it is a `factor` vs `character` issue:

``` r
library(sf)
library(dplyr)

data(countriesLow, package = "rworldmap")
countriesLow = st_as_sf(countriesLow) %>% 
    select(continent)
#> Loading required package: sp

system.time({
    a = aggregate(st_set_precision(countriesLow, 1e8),
                  list(countriesLow$continent),
                  function(f) f[1])
    })
#>    user  system elapsed 
#>   1.290   0.004   1.305

system.time({
    b = countriesLow %>%
        st_set_precision(1e8) %>%
        group_by(continent) %>% 
        summarize()
})
#>    user  system elapsed 
#>   1.172   0.001   1.183

system.time({
    c = aggregate(st_set_precision(countriesLow, 1e8),
                  list(as.character(countriesLow$continent)),
                  function(f) f[1])
})
#>    user  system elapsed 
#>   1.216   0.002   1.227

dim(a)
#> [1] 6 3
dim(b)
#> [1] 7 2
dim(c)
#> [1] 6 3
```

Created on 2018-06-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by edzer** [comment]
... and having nothing to do with `sf`:
```r
> aggregate(a~f, data.frame(a = 1:3, f = factor(c("a", "b", NA))), mean)
  f a
1 a 1
2 b 2
> library(dplyr)
> data.frame(a = 1:3, f = factor(c("a", "b", NA)))  %>% group_by(f) %>% summarise(mean(a))
# A tibble: 3 x 2
  f     `mean(a)`
  <fct>     <dbl>
1 a             1
2 b             2
3 NA            3
```

**Comment by rafapereirabr** [comment]
Is there a simple way to  aggregate `sf` polygons by group without having to use `dplyr::group_by` and `dplyr::summarize` ?

**Comment by edzer** [comment]
Did you try `st_union`?

**Comment by rafapereirabr** [comment]
All the approaches to this operation I've seen so far either use use `dplyr::group_by` and `dplyr::summarize` or a combination of `sf::st_union` with `dplyr:select`.  I would like to find a pure `sf` and base solution to this.  This is what I've tried but it does not work properly. Not sure what I'm doing wrong here. 

```
# data
data(countriesLow, package="rworldmap")
countriesLow <- st_as_sf(countriesLow)

temp_sf <- countriesLow[,c("continent","geometry")]
result <- st_union(temp_sf, by_feature=TRUE)
```

**Comment by rsbivand** [comment]
You need `sf::aggregate()`, but you'll see the same issues as with `gUnaryUnion()` with self-intersection with this dataset.

**Comment by rafapereirabr** [comment]
I've tried using `sf::aggregate()`, but then I get the error message:

> Error: 'aggregate' is not an exported object from 'namespace:sf'

**Comment by rsbivand** [comment]
```
> temp_sf <- countriesLow[,c("continent","geometry")]
> result <- aggregate(temp_sf, list(temp_sf$continent), head, n=1)
Error in CPL_geos_union(st_geometry(x), by_feature) : 
  Evaluation error: TopologyException: Input geom 1 is invalid: Ring Self-intersection at or near point 103.09120649619024 18.13824717861678 at 103.09120649619024 18.13824717861678.
> result <- aggregate(st_buffer(temp_sf, dist=0), list(temp_sf$continent), head, n=1)
dist is assumed to be in decimal degrees (arc_degrees).
Warning message:
In st_buffer.sfc(st_geometry(x), dist, nQuadSegs, endCapStyle = endCapStyle,  :
  st_buffer does not correctly buffer longitude/latitude data
> plot(st_geometry(result))
```
with lots of stray geometry debris.

**Comment by rafapereirabr** [comment]
Thank you, Roger. This works really well.
