### ISSUE TITLE
plot.st with add does not check if legend added?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/sf#783]
Hi

It seems like the `plot(., add=TRUE)` method has an issue if the previous plot is using a legend (hence changing slightly the plotting area?). It does not seem indeed to adjust for that new plotting area?

This implies that `plot(., add=TRUE)` will:

 * plot in the correct area if previous plot was just showing the geometry
 * NOT plot in the correct area if previous plot was just showing a variable, and hence adds a legend?

See:
```

library(sf)

example(plot.sf, ask=FALSE, echo=FALSE, verbose=FALSE)

plot(st_geometry(po)+0.1)
plot(po["a"], add=TRUE)


plot(po["a"], add=FALSE)
plot(st_geometry(po), add=TRUE)
```

**Comment by edzer** [comment]
The plots that create a legend need a `reset = FALSE` if you want to add to them later:
```r
plot(po["a"], add=FALSE, reset = FALSE)
plot(st_geometry(po), add=TRUE)
```

**Comment by MatthieuStigler** [comment]
Oh great! And sorry, didn't see that parameter. 

Thanks!
