### ISSUE TITLE
`st_make_grid` creates empty feature when `square = FALSE`

### ISSUE THREAD

**Issue by jmlondon** [r-spatial/sf#784]
I'm trying to create a hex grid over a distribution of points using `sf::st_make_grid()` in version 0.6.4. The `square = TRUE` option appears to work as expected. However, `square = FALSE` results in an empty feature. 
``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.3.0, proj.4 5.1.0

box <- st_as_sfc(paste("POLYGON ((-2355556 365779.9, 2049944 365779.9,", 
                       "2049944 2043367, -2355556 2043367, -2355556 365779.9))")) %>% 
  st_set_crs(3338)

pts <- st_sample(box, size = 500)

grid_square <- st_make_grid(pts,square = TRUE)

grid_square
#> Geometry set for 100 features 
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: -2349737 ymin: 367099.9 xmax: 2042312 ymax: 2037807
#> epsg (SRID):    3338
#> proj4string:    +proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
#> First 5 geometries:
#> POLYGON ((-2349737 367099.9, -1910532 367099.9,...
#> POLYGON ((-1910532 367099.9, -1471327 367099.9,...
#> POLYGON ((-1471327 367099.9, -1032123 367099.9,...
#> POLYGON ((-1032123 367099.9, -592917.6 367099.9...
#> POLYGON ((-592917.6 367099.9, -153712.6 367099....

grid_hex <- st_make_grid(pts, square = FALSE)

grid_hex
#> Geometry set for 0 features 
#> bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
#> epsg (SRID):    3338
#> proj4string:    +proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
```

Created on 2018-07-02 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).
reprex pasted below. 

R version: 3.5.0;
 sf version: 0.6-4 (installed from github); 
macOS 10.13.4

**Comment by edzer** [comment]
Thanks! Right now
```r
grid_hex <- st_make_grid(st_as_sfc(st_bbox(pts)), square = FALSE)
```
works. Do you think that should be automatic? Is a grid, defined over a set of points, well defined?

**Comment by jmlondon** [comment]
This may just be a simple documentation fix. I focused on `x` as an _"object of class sf or sfc"_ and missed the bit in the description where it states _"Make a square or hexagonal grid over the bounding box of an sf or sfc object"_ .

As for whether the `st_bbox(pts)` step should be automatic, that would be consistent with what `spsample` does.  I think with updated documentation, it's appropriate to expect the user to provide an appropriate input if they don't want the default of `st_bbox(pts)`.

And for completeness, I now see a better approach for my example might be

``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.3.0, proj.4 5.1.0

box <- st_as_sfc(paste("POLYGON ((-2355556 365779.9, 2049944 365779.9,", 
                       "2049944 2043367, -2355556 2043367, -2355556 365779.9))")) %>% 
  st_set_crs(3338)

pts <- st_sample(box, size = 500)

grid_poly <- pts %>% st_combine() %>% 
  st_convex_hull() %>% st_make_grid(square = FALSE)
```

Created on 2018-07-02 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by edzer** [comment]
Thanks! You'll need this fix to have the entire convex hull covered.
