### ISSUE TITLE
st_write sends wrong CRS to PostGIS

### ISSUE THREAD

**Issue by tobwen** [r-spatial/sf#786]
Hi there, I'm on latest R on Windows, 64 bit using sf v0.6.3.

```
> nrw_v_3035 <- st_read("gridfiles_3035.gpkg", "nrw_1000m_3035", crs = 3035)
> st_write(nrw_v_3035, "PG:host=localhost user=postgres dbname=test", "nrw_v_3035", layer_options = c("OVERWRITE=TRUE", "SCHEMA=test"))
```

When checking the CRS in R, anything is right.
```
> st_crs(nrw_v_3035)
Coordinate Reference System:
  EPSG: 3035 
  proj4string: "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
```

But when checking the CRS in PostGIS, the CRS is wrong:
```
> SELECT ST_SRID(wkb_geometry) FROM test.nrw_v_3035;
Result: 900915
```

This isn't a valid CRS at all. st_write doesn't allow setting SRID for table when using the PG writer in LCO. Is there a teak for this?

**Comment by edzer** [comment]
This is well-known; your CRS will be correct, it is just not registered with the SRID you'd hope it would. Try:
```
select proj4text from spatial_ref_sys where srid = 900915;
```
and compare, to see of the CRS is right. All this is done in GDAL, IIRC there is nothing we can do in `sf` to prevent it.

**Comment by tobwen** [comment]
Okay, thanks for the hint. QGIS has similar problems with selecting the right SRID.

Perhaps you could add a nice work-around for this by running `SELECT UpdateGeometrySRID ...` after uploading the data to PostGIS?

**Comment by etiennebr** [comment]
If you `select *` the srid, you will probably see that the authority is `sf`. This is to preserve the exact ‘proj4string‘ when the  local doesn't match the remote description (normally there was a message when it created the new srid). If you want to keep the same srid, you have to override one of them using `get_` or `set_` `potgis_crs`. 

This is all somewhat new, so it might not be very well documented. As @edzer said, it shouldn't change the results of your analysis.

**Comment by tobwen** [comment]
@edzer 
Unfortunately, QGIS has its own SRID recognition, which often results in chaos. Even EPSG:25832 (Germany's reference system of national surveying) is misinterpreted if it comes from a shapefile. Since a fix seems to be too complicated, it is easier to write a note in the manual. The problem is pointed out on every training course. But I don't want to bash a freeware GIS in here :)

@etiennebr 
This doesn't seem to be part of *sf v0.6.3* (current CPAN precompiled version for Windows). Do you know when it has been added? I bet, it's pretty hard to compile *sf* using *RTools* only?

**Comment by edzer** [comment]
The functions @etiennebr mentions are not exported (and hence undocumented); you can call them by `sf:::set_postgis_crs()`. Note that they are not part of the sf API.

OK to close this issue here?

**Comment by phurvitz** [comment]
A workaround after `st_write()` is to alter the column. Example with multipolygon data in a column called `geom` stored in UTM 10 N (EPSG 26910):

`dbGetQuery(conn = myconn, statement = "alter table myschema.mytable alter column geom type geometry(multipolygon, 26910) using st_setsrid(geom, 26910);")`
