### ISSUE TITLE
Q: speedup st_make_valid() with st_is_valid?

### ISSUE THREAD

**Issue by tobwen** [r-spatial/sf#789]
That's more a question than a bug report...

1. Does this speedup *st_make_valid* or is *st_is_valid* ran either way?
`mutate(geom = ifelse(st_is_valid(geom), geom, st_make_valid(geom)))`

2. Sometimes *geom* has a different name, like *wkb_geometry*. I tried it to use `attr(x, "sf_column")`, but it didn't seem to work in mutate (it doesn't like the equal sign).

**Comment by edzer** [comment]
For Q. 2, could you pls provide a reprex?

**Comment by tobwen** [comment]
I think, I need to cast it to the right type. Right now, I've got a mixture of *wkb_geometry*, *geom*, *geometry*, which is pretty annoying.

Reprex for Q2:
```
zip_geom <- attr(zipcodes, "sf_column")
zipcodes %>% mutate(zip_geom = ifelse(st_is_valid(zip_geom), geom, st_make_valid(zip_geom)))
```

A workaround might be `zipcodes <- rename(zipcodes, geom = attr(zipcodes, "sf_column"))` to create a common name.

**Comment by edzer** [comment]
Sorry, that is not a reprex. Reproducible example means something I can cut and paste in an R session on my machine to illustrate your problem.

**Comment by tobwen** [comment]
@edzer 
I've updated the example, but *zip_geom* is of class *character*. I'm just not advanced enough to choose the right type...

**Comment by edzer** [comment]
Well, maybe it is time to invest a bit more time into understanding `sf` before asking questions as issues.

**Comment by tobwen** [comment]
Hmm, I don't want to go into your statement because I believe that the community should help each other and not get rid of each other.

But in case you haven't noticed: In the labels of your repository's issues there are the entries *help wanted* and *questions*. As a user I cannot select them, but their existence suggests that questions are allowed here. 

On other repositories, the moderators assign those labels to mark them as "not a bug, the user of my tool needs help, I don't have time for this". It would therefore make sense to remove the labels and point out that questions are explicitly forbidden. You may link to *stackexchange*, *reddit* or *gitter* for PostGIS-users like me.

**Comment by edzer** [comment]
If you read the issues here, you will notice that people here are willing to answer good questions. What makes a good question? E.g.,
* https://www.r-project.org/posting-guide.html
* https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by tobwen** [comment]
Okay, I'll try next time. What about my first question? You could answer it easily :)

**Comment by edzer** [comment]
`st_make_valid` does not call `st_is_valid` first in the R or C++ code of package `sf`; I don't know whether it does so in the underlying C code of `liblwgeom` (which I didn't write).
