### ISSUE TITLE
st_snap returning the start/end point of the linestring

### ISSUE THREAD

**Issue by rafapereirabr** [r-spatial/sf#792]
Hi all,

I noticed that `st_snap` is returning the start/end point of the closest linestring. Is the the expected behavior of the function? I was expecting that `st_snap` would work similarly to `maptools::snapPointsToLines` and snap a point to the closest point on a line segment.

There is a [reproducible example here](https://stackoverflow.com/questions/51292952/snap-a-point-to-the-closest-point-on-a-line-segment-using-sf).

**Comment by edzer** [comment]
No, it is a straight copy of PostGIS' [st_snap](https://postgis.net/docs/ST_Snap.html).

**Comment by rafapereirabr** [comment]
Thank you for the clarification,  @edzer . Are there any plans to create an 'sf' function similar to 'maptools::snapPointsToLines' ?

**Comment by edzer** [comment]
@tim-salabim gave you a good suggestion on SO; with `st_length` you seem to have what you're looking for. Please choose whether to pursue this issue here, or on SO.

**Comment by rafapereirabr** [comment]
Hi @edzer . Yes, @tim-salabim provided a good workaround to the problem and I'm grateful for that. :) Nevertheless, that's still just a workaround, hence my previous question whether there are any plans to develop a  built-in function in `sf` that works similarly to `maptools::snapPointsToLines`. I think this could be a valuable function for future versions of `sf` but I understand if you don't think that's worth pursuing here.

**Comment by edzer** [comment]
See `st_nearest_points`.

**Comment by jpierkunke** [comment]
Thank you for all your work on these great spatial packages and useful resources/tutorials for using them!  I would like to echo previous users that it would still be nice to add this function to sf.  It doesn't seem to me that st_nearest_points directly solves the issue; the solution provided [here](https://stackoverflow.com/questions/51292952/snap-a-point-to-the-closest-point-on-a-line-segment-using-sf) still requires writing a function involving a number of other steps.  Is there a more direct solution using st_nearest_points (or some newer addition to sf) that I have missed?  Thank you again.
