### ISSUE TITLE
Install issue on RHEL6

### ISSUE THREAD

**Issue by tk80332** [r-spatial/sf#796]
Hello,

I'm trying to install sf on my server but get this error:

```
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG -I/usr/local/include -I/usr/include -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c proj.cpp -o proj.o
proj.cpp: In function ‘bool CPL_have_datum_files(SEXP)’:
proj.cpp:45:5: error: ‘projCtx’ was not declared in this scope
     projCtx ctx;
     ^
proj.cpp:45:13: error: expected ‘;’ before ‘ctx’
     projCtx ctx;
             ^
proj.cpp:46:5: error: ‘ctx’ was not declared in this scope
     ctx = pj_get_default_ctx();
     ^
proj.cpp:46:30: error: ‘pj_get_default_ctx’ was not declared in this scope
     ctx = pj_get_default_ctx();
                              ^
proj.cpp:47:40: error: ‘pj_open_lib’ was not declared in this scope
     fp = pj_open_lib(ctx, "conus", "rb");
                                        ^
make: *** [proj.o] Error 1
ERROR: compilation failed for package ‘sf’
* removing ‘/tech/home/tk80332e/R/x86_64-redhat-linux-gnu-library/3.4/sf’

The downloaded source packages are in
        ‘/tech/appl/user/tk80332e/tmp/RtmpXtvq4V/downloaded_packages’
Warning message:
In install.packages("sf") :
  installation of package ‘sf’ had non-zero exit status
```

my specs are as follows:

R 3.4.1
RHEL6.9
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)

Can someone point me in the right direction?  Am I missing anything?

**Comment by rsbivand** [comment]
Attach full log (even just from running ./configure after unpacking the source tarball). Does **rgdal** suffer the same fate? Do you know which version(s) of PROJ4 are installed (this looks like PROJ <=4.8.0)?

**Comment by tk80332** [comment]
Thanks for responding @rsbivand.  Trying to install rgdal did point to a PROJ issue, do you have any links or documentation to share on how to update that?  

```
checking PROJ version >= 4.8.0... no
```


Thanks in advance!

**Comment by rsbivand** [comment]
What is your version of PROJ? For rgdal, PROJ >= 4.8.0 is OK, but anything less than 4.9.3 is not recommended. sf declares the same version (4.8.0) as a minimum, but requires GDAL >= 2.0.1; rgdal requires GDAL >= 1.11.4. You will need to obtain PROJ and GDAL matching sf requirements, which probably means installing from source, as RHEL 6 is ancient, and poorly provided with GIS library binaries.

**Comment by tk80332** [comment]
Thanks for the info, I'll update RPROJ and give it another shot.  We may just wait until our server is upgraded to RHEL7.
