### ISSUE TITLE
compilation with libproj.so.13 fails

### ISSUE THREAD

**Issue by robby81** [r-spatial/sf#805]
The following occurs on compilation of the R package under openSUSE Tumbleweed with libproj13 (

Do 12 Jul 2018 14:00:00 CEST | mpluskal@suse.com | - Update to version 5.1.0 and datumgrid 1.7  * See provided NEWS for list of all changes)

installed:

checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ.4 is available for linking:... yes
checking GDAL: checking whether PROJ.4 is available fur running:... ERROR 6: Unable to load PROJ.4 library (libproj.so.12), creation of OGRCoordinateTransformation failed.
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ.4 not available?
ERROR: configuration failed for package ‘sf’

**Comment by edzer** [comment]
My guess: you have either more than one PROJ version installed on your system, or your GDAL installation was compiled without linking to PROJ, or both. Note the GDAL error mentioning libproj.so.12.

**Comment by robby81** [comment]
You were rigth, the fix is underway for openSUSE.
