### ISSUE TITLE
voronoi: Retain point order?

### ISSUE THREAD

**Issue by flying-sheep** [r-spatial/sf#806]
Hi! I’m trying to write a function that returns coordinates for voronoi cells around points in a ggplot-compatible way, i.e.:

x | y | group
---|---|---
1.0|0.1|1
1.1|1.0|1
0.0|0.0|1
1.2|1.1|2
…|…|…

…with “group” being the index in the original data. Is there a way to create voronoi cells that retain the point order?

Currently, I resort to this (inefficient and backwards) workaround, in which i create individual points, find the voronoi cell they belong to, and reorder the polygons accordingly

```r
library(dplyr)
library(sf)

to_tile <- function(data) {
	points <- data %>% select('x', 'y') %>% as.matrix() %>% st_multipoint()
	hull <- st_convex_hull(points)
	# st_voronoi returns a GEOMETRYCOLLECTION containing only polygons,
	# because a MULTIPOLYGON cannot have shared corner points.
	polys <- st_collection_extract(st_voronoi(points), 'POLYGON')
	ord <- points %>% st_sfc() %>% st_cast('POINT') %>% st_intersects(polys) %>% unlist()
	st_intersection(polys[ord], hull) %>%
		lapply(function(poly) poly %>% as.matrix() %>% as.data.frame() %>% setNames(c('x', 'y'))) %>%
		bind_rows(.id = 'group')
}
```

**Comment by edzer** [comment]
I believe this is GDAL, so out of our (sf's) hands.

**Comment by flying-sheep** [comment]
Uh, so where do I report this then?

**Comment by edzer** [comment]
st_voronoi uses the GEOS function `GEOSVoronoiDiagram_r`.
