### ISSUE TITLE
feature class layers read with `st_read` lose their OBJECTIDS

### ISSUE THREAD

**Issue by mkoohafkan** [r-spatial/sf#812]
Sometimes I have feature layers that have discontinuities in the OBJECTID or FID field, e.g. as a result of editing a layer and merging/deleting features. The OBJECTID is not preserved by `st_read`, so the indices of features in the resulting `sf` object do not match the original OBJECTID indices. It would be great to introduce a `preserve_FID` or similar option for `st_read`.

**Comment by edzer** [comment]
They are now read by default, and written if present; list names are used to store them. I haven't tested this thoroughly, please do so before use. In case of massive `POINT` sets, the current solution may have a considerable memory overhead, if data are read with `read_st`.
