### ISSUE TITLE
Strange results when plotting sf 

### ISSUE THREAD

**Issue by PMassicotte** [r-spatial/sf#817]
Hi. Not sure if it is a ggplot2 or sf issue, but I am finding that I have strange representation when I am trying to plot shapefile with sf. In the following, I was expecting that the land (Svlabard) would be filled in gray. However, I am getting different results depending on the resolution of the downloaded shapefile. 

``` r

library(tidyverse)
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, proj.4 4.9.3
library(rnaturalearth)

theme_set(theme_bw())

ocean <- ne_download(scale = 50, type = 'land', category = 'physical', returnclass = "sf") %>% 
  st_transform(3411)
#> OGR data source with driver: ESRI Shapefile 
#> Source: "/tmp/RtmpRsT4uB", layer: "ne_50m_land"
#> with 1420 features
#> It has 3 fields
#> Integer64 fields read as strings:  scalerank

ggplot() +
  geom_sf(data = ocean) +
  coord_sf(xlim = c(600701.3, 1567375.5), c(-859544.4, -282590.1)) 
```

![](https://i.imgur.com/IQONxzd.png)

``` r

ocean <- ne_download(scale = 10, type = 'land', category = 'physical', returnclass = "sf") %>% 
  st_transform(3411)
#> OGR data source with driver: ESRI Shapefile 
#> Source: "/tmp/RtmpRsT4uB", layer: "ne_10m_land"
#> with 10 features
#> It has 3 fields

ggplot() +
  geom_sf(data = ocean) +
  coord_sf(xlim = c(600701.3, 1567375.5), c(-859544.4, -282590.1))
```

![](https://i.imgur.com/OflgyE7.png)

Created on 2018-08-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by edzer** [comment]
For the first one, I get, when printed to png:
![x](https://user-images.githubusercontent.com/520851/44312568-d2e25580-a3fa-11e8-8c41-77cdfcdfdc5c.png)
(the on-screen plot doesn't show the diagonal line). What is your `sessionInfo()` output?

**Comment by adrfantini** [comment]
I get the same as you, @edzer , for the first one, and the same as @PMassicotte for the second.

> > sessionInfo()
> R version 3.5.1 (2018-07-02)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Arch Linux
> 
> Matrix products: default
> BLAS: /usr/lib/libopenblasp-r0.3.2.so
> LAPACK: /usr/lib/liblapack.so.3.8.0
> 
> locale:
>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=C               LC_MONETARY=it_IT.UTF-8   
>  [6] LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] forcats_0.3.0       stringr_1.3.1       purrr_0.2.5         readr_1.1.1         tidyr_0.8.1         tibble_1.4.2        tidyverse_1.2.1    
>  [8] rworldxtra_1.01     mapview_2.5.0       dplyr_0.7.6         sf_0.6-4            rnaturalearth_0.2.0 maps_3.3.0          rgdal_1.3-4        
> [15] sp_1.3-1            ggplot2_3.0.0.9000  pacman_0.4.6        colorout_1.2-0     
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.3.1               jsonlite_1.5             viridisLite_0.3.0        modelr_0.1.2             rnaturalearthhires_0.2.0
>  [6] shiny_1.1.0              assertthat_0.2.0         stats4_3.5.1             cellranger_1.1.0         yaml_2.2.0              
> [11] pillar_1.3.0             backports_1.1.2          lattice_0.20-35          glue_1.3.0               digest_0.6.15           
> [16] promises_1.0.1           rvest_0.3.2              colorspace_1.3-2         htmltools_0.3.6          httpuv_1.4.5            
> [21] plyr_1.8.4               pkgconfig_2.0.2          devtools_1.13.6          broom_0.5.0              raster_2.6-7            
> [26] haven_1.1.2              xtable_1.8-2             scales_1.0.0.9000        webshot_0.5.0            satellite_1.0.1         
> [31] later_0.7.3.9000         git2r_0.23.0             withr_2.1.2              lazyeval_0.2.1           cli_1.0.0               
> [36] readxl_1.1.0             magrittr_1.5             crayon_1.3.4             mime_0.5                 memoise_1.1.0           
> [41] maptools_0.9-3           nlme_3.1-137             xml2_1.2.0               foreign_0.8-71           class_7.3-14            
> [46] tools_3.5.1              hms_0.4.2                munsell_0.5.0            bindrcpp_0.2.2           compiler_3.5.1          
> [51] e1071_1.7-0              rlang_0.2.2              classInt_0.2-3           units_0.6-0              grid_3.5.1              
> [56] rstudioapi_0.7           htmlwidgets_1.2          crosstalk_1.0.0          base64enc_0.1-3          labeling_0.3            
> [61] gtable_0.2.0             DBI_1.0.0                curl_3.2                 R6_2.2.2                 lubridate_1.7.4         
> [66] knitr_1.20               rgeos_0.3-28             bindr_0.1.1              stringi_1.2.4            Rcpp_0.12.18            
> [71] png_0.1-7                leaflet_2.0.1            spData_0.2.9.3           tidyselect_0.2.4         rnaturalearthdata_0.2.0

**Comment by PMassicotte** [comment]
I will try to explore this tomorrow and will post my sessioninfo. I will try to open the pdf file using another pdf reader, just in case.

**Comment by PMassicotte** [comment]
Now on Windows (original question was on linux Mint 19) I am getting another interesting situation when reading the file with Foxit Reader.

```r
library(tidyverse)
library(sf)
library(rnaturalearth)

theme_set(theme_bw())

ocean <- ne_download(scale = 10, type = 'land', category = 'physical', returnclass = "sf") %>% 
  st_transform(3411)

ggplot() +
  geom_sf(data = ocean) +
  coord_sf(xlim = c(600701.3, 1567375.5), c(-859544.4, -282590.1))

ggsave("c:/test.pdf")
```

![image](https://user-images.githubusercontent.com/4519221/44315413-d32a2300-a3f1-11e8-875c-844cda7b369b.png)

```r
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rnaturalearth_0.1.0 sf_0.6-3            forcats_0.3.0       stringr_1.3.1      
 [5] dplyr_0.7.6         purrr_0.2.5         readr_1.1.1         tidyr_0.8.1        
 [9] tibble_1.4.2        ggplot2_3.0.0       tidyverse_1.2.1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18     cellranger_1.1.0 pillar_1.3.0     compiler_3.5.1   plyr_1.8.4      
 [6] bindr_0.1.1      class_7.3-14     tools_3.5.1      jsonlite_1.5     lubridate_1.7.4 
[11] nlme_3.1-137     gtable_0.2.0     lattice_0.20-35  pkgconfig_2.0.2  rlang_0.2.2     
[16] DBI_1.0.0        cli_1.0.0        rstudioapi_0.7   rgdal_1.3-4      yaml_2.2.0      
[21] haven_1.1.2      bindrcpp_0.2.2   e1071_1.7-0      spData_0.2.9.3   withr_2.1.2     
[26] xml2_1.2.0       httr_1.3.1       hms_0.4.2        classInt_0.2-3   grid_3.5.1      
[31] tidyselect_0.2.4 glue_1.3.0       R6_2.2.2         readxl_1.1.0     sp_1.3-1        
[36] modelr_0.1.2     magrittr_1.5     units_0.6-0      backports_1.1.2  scales_1.0.0    
[41] rvest_0.3.2      assertthat_0.2.0 colorspace_1.3-2 stringi_1.2.4    lazyeval_0.2.1  
[46] munsell_0.5.0    broom_0.5.0      crayon_1.3.4    
> 
```

**Comment by adrfantini** [comment]
That's the same thing I see when viewing the file with Okular. Maybe they are not able to render polygons with so many vertices. I'm sure that if you try with muPDF, it'll work.

**Comment by PMassicotte** [comment]
I will try that. Note that this thing happens also in the RStudio viewer.

**Comment by PMassicotte** [comment]
I still have the same problem with muPDF when I zoom in.

![image](https://user-images.githubusercontent.com/4519221/44340348-8fb3d100-a452-11e8-8fb3-fe8a9e3ac2df.png)

**Comment by edzer** [comment]
In rstudio (on ubuntu), I see [this](http://rpubs.com/edzer/413488) for the first plot, which LGTM.

**Comment by PMassicotte** [comment]
@edzer For me it is kind of random. 

This is what I get with 

```r
library(tidyverse)
library(sf)
library(rnaturalearth)

theme_set(theme_bw())

ocean <- ne_download(scale = 110, type = 'land', category = 'physical', returnclass = "sf") %>% 
  st_transform(3411)

ggplot() +
  geom_sf(data = ocean) +
  coord_sf(xlim = c(600701.3, 1567375.5), c(-859544.4, -282590.1))
```

![image](https://user-images.githubusercontent.com/4519221/44344296-57b28b00-a45e-11e8-89e3-df869a7128a0.png)

**Comment by lbusett** [comment]
I wonder if (some of) the issues can be related to some reprojection "problem" towards 3411. See below what happens when reprojecting to a different CRS:

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, proj.4 4.9.3
library(rnaturalearth)

theme_set(theme_bw())

ocean <- ne_download(scale = 110, type = 'land', category = 'physical', returnclass = "sf")
#> OGR data source with driver: ESRI Shapefile 
#> Source: "/tmp/RtmpD4miAi", layer: "ne_110m_land"
#> with 127 features
#> It has 3 fields

# Crop on "valid extent" of 3411 projection 
# ocean <- sf::st_crop(ocean, xmin  = -180, xmax = 180 ,ymin = 60, ymax = 90)

# Reproject to 3411 and plot
ocean_3411 <- st_transform(ocean, 3411)

plot(ocean_3411[,1])
```

![](https://i.imgur.com/vW30c1k.png)

``` r
ggplot() +  geom_sf(data = ocean_3411)
```

![](https://i.imgur.com/Ml4l2np.png)

``` r

# the same, reprojecting to a different epsg

ocean_3857 <- st_transform(ocean, 3857)

plot(ocean_3857[,1])
```

![](https://i.imgur.com/s5x1xYG.png)

``` r
ggplot() + geom_sf(data = ocean_3857)
```

![](https://i.imgur.com/VUqhU6h.png)
