### ISSUE TITLE
Fails to install on Ubuntu 16.04 LTS ; R 3.5.0

### ISSUE THREAD

**Issue by apoorvalal** [r-spatial/sf#818]
SF works well on my install of R 3.4.4 , but fails to install on (Microsoft-) R 3.5 on the same machine. 

It throws the following error:

```
checking for ut_read_xml in -ludunits2... no
-----Error: libudunits2.a not found-----
     If the udunits2 library is installed in a non-standard location,
     use --configure-args='--with-udunits2-lib=/usr/local/lib' for example,
     or --configure-args='--with-udunits2-include=/usr/include/udunits2'
     replacing paths with appropriate values for your installation.
     You can alternatively use the UDUNITS2_INCLUDE and UDUNITS2_LIB
     environment variables.
     If udunits2 is not installed, please install it.
     It is required for this package.
ERROR: configuration failed for package ‘udunits2’
```
Any cues as to how to specify the appropriate udunits2 library? I didn't have to specify it when running `install.packages('sf')` on 3.4.

**Comment by edzer** [comment]
This seems to be an issue with package units, rather than sf; please report ask help for it there (after looking for solutions!): https://github.com/r-quantities/units/ .
