### ISSUE TITLE
Does st_voronoi work incorrectly on sfc?

### ISSUE THREAD

**Issue by dah33** [r-spatial/sf#824]
Taking the example from #474, but keeping the points, ``d``, as an sfc:

```
library(sf)

set.seed(100)
df <- data.frame(ID = 1:10, X = sample(1:10, 10), Y = sample(1:10, 10))
d <- st_geometry(st_as_sf(df,coords = c("X", "Y")))
#d <- st_union(d)
hull <- st_convex_hull(st_union(d))
plot(hull)
plot(d, add = TRUE)

# No envelope
v <- st_voronoi(d)
plot(v, col = "grey")
plot(hull, add = TRUE, col = rgb(0, 1, 0, 0.5))
plot(d, add = TRUE)
```
![image](https://user-images.githubusercontent.com/17231347/44412639-53bb6180-a561-11e8-821e-17bbe342bf3c.png)

The expected result is a Voronoi tesselation in grey, but it's missing.

```
> v
Geometry set for 10 features  (with 10 geometries empty)
geometry type:  GEOMETRYCOLLECTION
dimension:      XY
bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
epsg (SRID):    NA
proj4string:    NA
First 5 geometries:
GEOMETRYCOLLECTION EMPTY
GEOMETRYCOLLECTION EMPTY
GEOMETRYCOLLECTION EMPTY
GEOMETRYCOLLECTION EMPTY
GEOMETRYCOLLECTION EMPTY
> class(d)
[1] "sfc_POINT" "sfc" 
```
So, possibly an issue with ``st_voronoi.sfc``, unless I am misunderstanding?

```
> packageDescription('sf')
Package: sf
Version: 0.6-3
...
> library(rgeos)
rgeos version: 0.3-28, (SVN revision 572)
 GEOS runtime version: 3.6.1-CAPI-1.10.1 r0 
 Linking to sp version: 1.3-1 
 Polygon checking: TRUE  
```

My work-around for a ``sf`` object doesn't work:

```
result <- sf
st_geometry(result) <- st_collection_extract(st_voronoi(st_union(st_geometry(sf))))
```

It doesn't work as the order of geometries is not preserved.

**Comment by edzer** [comment]
Voronoi is computed on a per-feature basis; try
```r
v = st_voronoi(do.call(c, d))
plot(v, col = NA)
```
![x](https://user-images.githubusercontent.com/520851/44424485-85e0b980-a589-11e8-9660-9c5e1a33f41c.png)

**Comment by dah33** [comment]
OK, so that ``do.call`` does something similar to the ``st_union`` in the above work-around. I then still have to recover the order of the individual geometries to put them back in the ``sf``. To give you some context, here's a function I've written, including some code to recover the ordering:

```
st_buffer_without_overlap <- function(centroids, dist) {

     # Voronoi tesselation
     voronoi <- 
          centroids %>% 
          st_geometry() %>%
          st_union() %>%
          st_voronoi() %>%
          st_collection_extract()
     
     # Put them back in their original order
     voronoi <-
          voronoi[unlist(st_intersects(centroids,voronoi))]

     # Keep the attributes
     result <- centroids
     
     # Intersect voronoi zones with buffer zones
     st_geometry(result) <-
          mapply(function(x,y) st_intersection(x,y),
                 st_buffer(st_geometry(centroids),dist), 
                 voronoi,
                 SIMPLIFY=FALSE) %>%
          st_sfc(crs=st_crs(centroids))

     result
}

df <- data.frame(ID = 1:10, X = sample(1:10, 10), Y = sample(1:10, 10))
st_geometry(df) <- st_geometry(st_as_sf(df,coords = c("X", "Y")))
df$X<-NULL
df$Y<-NULL

plot(st_buffer_without_overlap(df,2))
```
![image](https://user-images.githubusercontent.com/17231347/44426449-9479a180-a586-11e8-8802-9153bd60533b.png)

For contrast, here's the vanilla ``st_buffer``:
```plot(st_buffer(df,2))```
![image](https://user-images.githubusercontent.com/17231347/44426437-8deb2a00-a586-11e8-82e2-fe2b416e87a4.png)

**Comment by edzer** [comment]
Looks cool! Note that doing a `st_union` on a set of `POINT` geometries may, iirc, change their order; calling `c` on them would not.

**Comment by SjoerdBraaksma** [comment]
So I've figured out yesterday that st_voronoi only works on a geometry collection. I am trying to understand the function on a deeper level. There are 2 things I don't understand (yet), and i hope someone can help me out!

1: Why does it have to be an sfc object, as opposed to a multipoint? 
2: Why does st_voronoi run on a per-feature basis? Does it compute the area of each point-polygon as opposed to every other point, then moving on to the next one?

**Comment by edzer** [comment]
1: this is not the case, try e.g.
```r
library(sf)
mp = st_multipoint(matrix(rnorm(20),,2))
plot(st_voronoi(mp), col = NA)
plot(st_voronoi(st_sfc(mp)), col = NA)
plot(st_voronoi(st_sf(st_sfc(mp))), col = NA)
```
2: because GEOS does it that way
3: try
```r
v = st_voronoi(mp)
st_collection_extract(v)
```
