### ISSUE TITLE
printing sf of multiple geometries causes error

### ISSUE THREAD

**Issue by SymbolixAU** [r-spatial/sf#826]
I'm exploring the `Z` and `M` dimensions and came across something I can't explain.

I'm creating an `sf` object of a mixture of `sfc`s, and the objects get created but sometimes they error when printing

### Setting up data

```r
library(sf)

## POINT
pz <- sf::st_point(c(1,2,3))
pzm <- sf::st_point(1:4)

## MULTIPOINT
mpz <- sf::st_multipoint(x = matrix(1:6, ncol = 3))
mpzm <- sf::st_multipoint(x = matrix(1:8, ncol = 4))

## LINESTRING
lz <- sf::st_linestring(x = matrix(1:6, ncol = 3))
lzm <- sf::st_linestring(x = matrix(1:8, ncol = 4))

## MULTILINESTRING
mlz <- sf::st_multilinestring(x = list(lz,lz))
mlzm <- sf::st_multilinestring(x = list(lzm, lzm))

## POLYGON
pl <- c(0,0,1,1,0,1,1,1,1,0,1,1,0,0,1)
plz <- sf::st_polygon(x = list(matrix(pl, ncol = 3, byrow = T)))
pl <- c(0,0,1,2,1,0,1,2,1,1,1,2,0,1,1,2,0,0,1,2)
plzm <- sf::st_polygon(x = list(matrix(pl, ncol = 4, byrow = T)))

## MULTIPOLYGON
mplz <- sf::st_multipolygon(x = list(plz, plz))
mplzm <- sf::st_multipolygon(x = list(plzm, plzm))

### sf objects for all the geometries
sfpz <- sf::st_sf(geometry = sf::st_sfc(pz))
sfpzm <- sf::st_sf(geometry = sf::st_sfc(pzm))

sfmpz <- sf::st_sf(geometry = sf::st_sfc(mpz))
sfmpzm <- sf::st_sf(geometry = sf::st_sfc(mpzm))

sflz <- sf::st_sf(geometry = sf::st_sfc(lz))
sflzm <- sf::st_sf(geometry = sf::st_sfc(lzm))

sfmlz <- sf::st_sf(geometry = sf::st_sfc(mlz))
sfmlzm <- sf::st_sf(geometry = sf::st_sfc(mlzm))

sfplz <- sf::st_sf(geometry = sf::st_sfc(plz))
sfplzm <- sf::st_sf(geometry = sf::st_sfc(plzm))

sfmplz <- sf::st_sf(geometry = sf::st_sfc(mplz))
sfmplzm <- sf::st_sf(geometry = sf::st_sfc(mplzm))

```

### Error

`rbind`ing all the objects causes an error when printing to console

```r
sf <- rbind(sfpz, sfpzm, sfmpz, sfmpzm, sflz, sflzm, sfmlz, sfmlzm, sfplz, sfplzm, sfmplz, sfmplzm)
sf

# Simple feature collection with 12 features and 0 fields
# geometry type:  GEOMETRY
# dimension:      XYZ
# bbox:           xmin: 0 ymin: 0 xmax: 2 ymax: 4
# epsg (SRID):    NA
# proj4string:    NA
# First 10 features:
# Error in st_sfc(NextMethod(), crs = st_crs(old), precision = st_precision(old)) : 
#  found multiple dimensions: XYZ XYZM
```

However, removing the MULTIPOLYGONs works

```r
sf <- rbind(sfpz, sfpzm, sfmpz, sfmpzm, sflz, sflzm, sfmlz, sfmlzm, sfplz, sfplzm)
sf

# Simple feature collection with 10 features and 0 fields
# geometry type:  GEOMETRY
# dimension:      XYZ
# bbox:           xmin: 0 ymin: 0 xmax: 2 ymax: 4
# epsg (SRID):    NA
# proj4string:    NA
# geometry
# 1                 POINT Z (1 2 3)
# 2              POINT ZM (1 2 3 4)
# 3     MULTIPOINT Z (1 3 5, 2 4 6)
# 4  MULTIPOINT ZM (1 3 5 7, 2 4...
# 5     LINESTRING Z (1 3 5, 2 4 6)
# 6  LINESTRING ZM (1 3 5 7, 2 4...
# 7  MULTILINESTRING Z ((1 3 5, ...
# 8  MULTILINESTRING ZM ((1 3 5 ...
# 9  POLYGON Z ((0 0 1, 1 0 1, 1...
# 10 POLYGON ZM ((0 0 1 2, 1 0 1...
```

Or removing one POINT and one POLYGON works

```r
sf <- rbind(sfpzm, sfmpz, sfmpzm, sflz, sflzm, sfmlz, sfmlzm, sfplz, sfplzm, sfmplz)
sf

# Simple feature collection with 10 features and 0 fields
# geometry type:  GEOMETRY
# dimension:      XYZM
# bbox:           xmin: 0 ymin: 0 xmax: 2 ymax: 4
# epsg (SRID):    NA
# proj4string:    NA
#                          geometry
# 1              POINT ZM (1 2 3 4)
# 2     MULTIPOINT Z (1 3 5, 2 4 6)
# 3  MULTIPOINT ZM (1 3 5 7, 2 4...
# 4     LINESTRING Z (1 3 5, 2 4 6)
# 5  LINESTRING ZM (1 3 5 7, 2 4...
# 6  MULTILINESTRING Z ((1 3 5, ...
# 7  MULTILINESTRING ZM ((1 3 5 ...
# 8  POLYGON Z ((0 0 1, 1 0 1, 1...
# 9  POLYGON ZM ((0 0 1 2, 1 0 1...
# 10 MULTIPOLYGON Z (((0 0 1, 1 ...

**Comment by edzer** [comment]
Thanks! In your last case, `print(sf, n = 3)` will also raise the error, which is caught in the `[` method called when more features are present than are going to be printed.

Your issue is that the error (or: some helpful error) should happen in all cases, right?

**Comment by SymbolixAU** [comment]
My specific issues are:

1 - What causes the error in the first place?
2 - Yes I think a more descriptive messaged would be helpful

**Comment by edzer** [comment]
1: 
```r
> traceback()
8: stop(paste("found multiple dimensions:", paste(u, collapse = " ")))
7: st_sfc(NextMethod(), crs = st_crs(old), precision = st_precision(old))
6: `[.sfc`(geom, i)
5: geom[i]
4: `[.sf`(x, 1:n, , drop = FALSE)
3: x[1:n, , drop = FALSE]
2: print.sf(sf, n = 3)
1: print(sf, n = 3)
```
It's really a design decision whether this should err; I'm not sure if it should. Do you see a need / a use case where having `sfc` columns with mixes of `XY`, `XYZ`, `XYZM` and / or `XYM`s would be of advantage?

**Comment by SymbolixAU** [comment]
The use-case I'm working towards is automatically plotting the elevations (Z) in [`mapdeck`](http://github.com/symbolixau/mapdeck).

So if someone has multiple data sets, some with Z attributes and some without, I'd like to be able to `rbind` them altogether and plot using a single `add_scatterplot()` call (for example). 

So thinking it through, I also don't think it should error.

**Comment by edzer** [comment]
Should the features without Z be converted to have Z and Z values filled with 0, or should the problem simply be deferred to the downstream (e.g. plot) functions?

In any case, we need to come up with the summary line
```
# dimension:      XYZM
```
which is no longer that simple for a mixed set. Maybe it should say what the mix is composed of.

**Comment by SymbolixAU** [comment]
I'm working under the assumption the 'problem' will be deferred downstream. I don't think it would be correct for `sf` to assume a 0 elevation if it wasn't provided.

**Comment by edzer** [comment]
I will look into it. There may be reasons elsewhere in sf that led me to require this, which I don't remember right now.

**Comment by mdsumner** [comment]
I don't think mixing should be allowed, it seems perverse. Any combination should upgrade to the superset imo. I haven't found any related discussion, but my sense is that structure should be consistent.

**Comment by Robinlovelace** [comment]
One question about Z dimensions: should `NA` values allowed/encouraged?

I can think of many datasets where the Z value is known for some observations but not others, a possible use case for mixing. But to me it also seems more sensible not to mix and just use `NA` when they are not known rather than omitting the dimension altogether.

Currently NA values are allowed in any dimension I believe, unlike **sp**, which formids `NA`s in geometries:

```
mpz <- sf::st_multipoint(x = matrix(
  c(
    1:3,
    4:6,
    NA, NA, NA
    ), ncol = 3))

mpz <- sf::st_multipoint(x = matrix(
  c(
    1:3,
    NA, NA, NA,
    4:6
  ), ncol = 3)) 
```

**Comment by SymbolixAU** [comment]
In my mind this comes down to whether each row is independent to all the other rows, AND whether it's valid GeoJSON, which does accept different dimensions per geometry (or, I couldn't see anywhere it state it wasn't allowed).

Taking this example from [geojson RFC 7946](https://tools.ietf.org/html/rfc7946), I've added a Z attribute to the `Point` and tested it at http://geojsonlint.com/
```
{
  "type": "FeatureCollection",
  "features": [{
    "type": "Feature",
    "geometry": {
      "type": "Point",
      "coordinates": [102.0, 0.5, 100]
    },
    "properties": {
      "prop0": "value0"
    }
  }, {
    "type": "Feature",
    "geometry": {
      "type": "LineString",
      "coordinates": [
        [102.0, 0.0],
        [103.0, 1.0],
        [104.0, 0.0],
        [105.0, 1.0]
        ]
    },
    "properties": {
      "prop0": "value0",
      "prop1": 0.0
    }
  }, {
    "type": "Feature",
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [100.0, 0.0],
          [101.0, 0.0],
          [101.0, 1.0],
          [100.0, 1.0],
          [100.0, 0.0]
          ]
        ]
    },
    "properties": {
      "prop0": "value0",
      "prop1": {
        "this": "that"
      }
    }
  }]
  }
```

**Comment by mdsumner** [comment]
I agree, the point @Robinlovelace made above made me change my mind. I want data coming in to maintain its form, if you expand out NAs because some are XY and some are XYZ you lose the intention of the source. I think it's better to not support some things than to force a change, or error on disparate inputs. Z and M values are much better stored and used in other ways, as practically any system using them does -  so preserving as-is is more important than supporting everything.

**Comment by etiennebr** [comment]
I was curious to see how it happened in postgis. It reacts somewhat similarly.
``` sql
with a as (
  select * from sfmplzm
  union
  select * from sfpz
  )
select st_astext(st_collect(geometry)) from a;
ERROR:  XX000: lwcollection_construct: mixed dimension geometries: 3/2
LOCATION:  pg_error, lwgeom_pg.c:162
Time: 1.286 ms 
```

However it can `st_union` without complaining, but will drop the extra dimension (`m`).
```sql
with a as (
select * from sfmplzm
union
select * from sfpz
)
select st_astext(st_union(geometry)) from a;
                                     st_astext                                      
------------------------------------------------------------------------------------
 GEOMETRYCOLLECTION Z (POINT Z (1 2 3),POLYGON Z ((1 0 1,0 0 1,0 1 1,1 1 1,1 0 1)))
```

**Comment by etiennebr** [comment]
Just to follow up, postgis does not complain if the geometries aren't interacting. Each row is independent, apparently:
```sql
with a as (
  select * from sfmplzm
  union
  select * from sfplzm
  union
  select * from sfpz                            
  )
select st_astext(geometry) from a;
                                                 st_astext                                                 
-----------------------------------------------------------------------------------------------------------
 POLYGON ZM ((0 0 1 2,1 0 1 2,1 1 1 2,0 1 1 2,0 0 1 2))
 MULTIPOLYGON ZM (((0 0 1 2,1 0 1 2,1 1 1 2,0 1 1 2,0 0 1 2)),((0 0 1 2,1 0 1 2,1 1 1 2,0 1 1 2,0 0 1 2)))
 POINT Z (1 2 3)
```

**Comment by edzer** [comment]
@Robinlovelace you can construct geometries with `NA` values in them, but it won't get you far, since
```r
> st_is_valid(mpz)
[1] FALSE
```

**Comment by edzer** [comment]
OK, we'll stick to the model where we don't mix stuff like XY and XYZ in `sfc` columns.
