### ISSUE TITLE
NA handling in `st_interpolate_aw`

### ISSUE THREAD

**Issue by jsta** [r-spatial/sf#830]
If some of the attributes of the "from" polygons in `st_interpolate_aw` are `NA` it seems there is no way to avoid them being propagated to the `st_interpolate_aw` output. Does it make sense to add an `na.rm = TRUE` argument?

```
nc = st_read(system.file("shape/nc.shp", package="sf"))
g = st_make_grid(nc, n = c(20,10))
a2 = st_interpolate_aw(nc["BIR74"], g, extensive = TRUE)

nc[sample(seq_len(nrow(nc)), 5), "BIR74"] <- NA
a3 = st_interpolate_aw(nc["BIR74"], g, extensive = TRUE)

plot(a2["BIR74"])
plot(nc["BIR74"])
plot(a3["BIR74"])
```

**Comment by edzer** [comment]
Would (should) that be equivalent to removing the corresponding feature altogether?

**Comment by jsta** [comment]
Hmm, yes it has the same effect. Maybe this issue will be a signpost for future users.

**Comment by mountainMath** [comment]
I would agree that `na.rm=TRUE` would be useful. Take the situation where several attributes are to be aggregated, only some of which are NA in some instances. Right now I pipe the first argument through `replace(., is.na(.), 0)` every time I call `st_interpolate_aw`, but I feel like a `na.rm=TRUE` options would be cleaner and more transparent.

**Comment by leahbevis** [comment]
Hi @mountainMath -- could you tell me how you "pipe the first argument through..." to address this situation? Can you provide sample code? I think am having exactly the same problem: I am aggregating values from numerous smaller polygons that overlap larger polygons, using st_interpolate_aw. Frequently the data that I'm aggregating is missing for 1 of the multiple small polygons, and in those cases I'd like to take the mean of the non-missing values and return that mean to the larger polygon. You have a solution for this? I'm sure what you said above is enough for a seasoned R / dplyr user but I don't use dplyr / piping much.

**Comment by leahbevis** [comment]
Hey @mountainMath, sorry a follow-up. I realized that -- while I still don't know how to execute the syntax -- your solution is to replace NA with 0, which I guess works when you are taking a sum (extensive = TRUE) but not when you are taking a mean (extensive = FALSE). I don't suppose you or anyone else has a solution for ignoring NA values when taking a mean? I.e., the mean over only the non-NA overlapping polygon values?

**Comment by edzer** [comment]
Could you pls check & report back whether with this fix, passing `na.rm=TRUE` works?

**Comment by edzer** [comment]
Pls try the dev version, using 

`install.packages('sf', repos = c('https://r-spatial.r-universe.dev', 'https://cloud.r-project.org'))`

**Comment by leahbevis** [comment]
Ok, I did that, just now, and restarted R and Rstudio for good measure, and the a1 and a2 outputs are still identical.

**Comment by leahbevis** [comment]
Ok, I did that just now, used that code above and restarted R and Rstudio for good measure, and that a1 and a2 objects are still identical. I did get this warning when I installed the package: Warning in install.packages : installation of package ‘sf’ had non-zero exit status. Does this mean the install didn't go through properly?

**Comment by leahbevis** [comment]
Here's an example of the problem with not having na.rm=TRUE pass through. In [this pic here](https://leahbevis.files.wordpress.com/2024/04/screenshot-2024-04-02-at-3.00.57e280afpm.png) you can see the data (gray borders) that I am interpolating up to the black borders. In [this pic here](https://leahbevis.files.wordpress.com/2024/04/screenshot-2024-04-02-at-3.14.24e280afpm.png) you can see the interpolation. Part of the problem may be that the 1970 (large black border) shapefile is less high quality, and the borders aren't matching up properly with the 2020 (gray border) shapefile. Nothing to be done about that, as far as I know. So even though there is little missing data to begin with, the interpolated object ends up with a LOT of missing data.

**Comment by edzer** [comment]
With this change, I get this for `a2`:
![x](https://github.com/r-spatial/sf/assets/520851/718bac65-b4cf-4b81-aa06-fb9e3f824ed6)

**Comment by leahbevis** [comment]
Ugh. I have now updated R, and that sample code works. So, great, in a way. However, due to your phase out of RGDAL, I now can no longe read in shapefiles with readOGR, and I'm not entirely sure how long it's going to take to transition the code that I need for a major presentation on Friday. I was doing a whole set of manipulation of a shapefile using sp, and I imagine it would take me ~10 hours to recreate this code in sf, hours I absolutely do not have. So I can't even GET to to the point of analysis now, as I won't even be able to load and process my data. 

Is there any way to re-load the old version of R, 4.2.3? For a mac? Maybe from here?

I know this is NOT your problem, and I really do appreciate the original help. But coincidentally this is just the worst possible timing for this to happen. If you can advise me on un-doing this update I would be so so so incredibly grateful.

**Comment by leahbevis** [comment]
From here, sorry https://cran.r-project.org/bin/windows/base/old/4.2.3/ ?

**Comment by rsbivand** [comment]
https://r-spatial.github.io/evolution/ gives all you need, typically `st_read` followed by coercion from sf to Spatial. Do not try to go backwards, it is most unlikely to work.

**Comment by leahbevis** [comment]
Thanks so much. I will attempt to re-write in sf. What an absolute nightmare. This is precisely why luddites like me never want to update R! Doing it right before a major presentation was a big mistake, I don't know what I was thinking.

**Comment by edzer** [comment]
> But t.b.h., I'm still not sure this is the right thing to do.

My previous solution was indeed wrong when `extensive = FALSE`; should now be fixed.

**Comment by leahbevis** [comment]
Wonderful, thank you!
