### ISSUE TITLE
plot and geom_sf

### ISSUE THREAD

**Issue by bertagrau** [r-spatial/sf#836]
I am a begginer and I am just starting to use sf package and I need to plot three layers: two polygons and one points. 

All of them are class "sf" "data.frame" and all with the same coordination system: 4326. 
When I try: 
`plot(district[0], fill = NULL, reset = FALSE)`
`plot(old[0], add = TRUE, col = "yellow")`
`plot(water["latrinebin"], add = TRUE)`

Only the first and second one are plotted together, while the third one doesn't come out.

![image](https://user-images.githubusercontent.com/42384135/45211571-f6c6e780-b292-11e8-945d-57b8308577b9.png)

 However, I can plot the third one alone with the same code: 
`plot(water["latrinebin"])`

![image](https://user-images.githubusercontent.com/42384135/45211603-080ff400-b293-11e8-938f-65b31bb2cf48.png)

I also tried to use ggplot2 with geom_sf: 
`qqplot() + 
   geom_sf(data = old)`
And I am getting this error 
_Error in sort(x) : argument "x" is missing, with no default_

Thanks for the help!

**Comment by tim-salabim** [comment]
Have you tried setting `reset = FALSE` in the second plot call also?

**Comment by bertagrau** [comment]
Thanks tim, for being so quick, it doesn't workk neither

**Comment by bertagrau** [comment]
@tim-salabim could that be the difference onf `+datum` and `+ellps` the reason? 

`> st_crs(water)`
Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +ellps=WGS84 +no_defs"
`> st_crs(old)`
Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +datum=WGS84 +no_defs"
`> st_crs(district)`
Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +datum=WGS84 +no_defs"

**Comment by tim-salabim** [comment]
very likely yes!
This works:
```r
library(sf)
library(mapview)

plot(st_geometry(franconia), fill = NULL, reset = FALSE)
plot(st_geometry(st_transform(trails, 4326)), add = TRUE, col = "yellow")
plot(breweries["founded"], add = TRUE)
```
Here, I transform trails to fit wtih the crs of the other two layers.

**Comment by bertagrau** [comment]
Thanks so much for the help. 
Finally @tim-salabim  realized that  I had to specify `+south` in CRS: 
`crs(w) <- CRS("+proj=utm +zone=36 +south")` 
My points were `+north` by default, so were somewhere in northern Europe instead of Africa. 

He find it out using: 
`options(viewer = NULL)`
`mapview(district) + old + water`
