### ISSUE TITLE
sf method for tidyr::extract

### ISSUE THREAD

**Issue by see24** [r-spatial/sf#837]
When I use `tidyr::extract` on an `sf` object it creates a second column called `geometry`

```
library(sf)
library(tidyr)
nc <- st_read(system.file("shape/nc.shp", package="sf"))
res <- extract(nc, FIPSNO, c("D1", "D2", "D3"), 
        regex = "([[:alnum:]])([[:alnum:]])([[:alnum:]])")
colnames(res)
```
I imagine this could be fixed by adding a method for `extract` with `sf` objects, which I don't see in the "Tidyverse methods for sf objects" documentation.

**Comment by edzer** [comment]
Thanks! Until someone has done that I guess you can do
```r
res <- extract(as.data.frame(nc), FIPSNO, c("D1", "D2", "D3"), 
  regex = "([[:alnum:]])([[:alnum:]])([[:alnum:]])") %>% st_as_sf
```

**Comment by mdsumner** [comment]
Minor comment for anyone exploring this: watch out for the `raster::extract` methods for sf.

**Comment by edzer** [comment]
Looks like that only needs an `sf` object as its _second_ argument:
```r
> showMethods(extract)
Function: extract (package raster)
x="Raster", y="data.frame"
x="Raster", y="Extent"
x="Raster", y="matrix"
x="Raster", y="sf"
x="Raster", y="SpatialLines"
x="Raster", y="SpatialPoints"
x="Raster", y="SpatialPolygons"
x="Raster", y="vector"
x="SpatialPolygons", y="data.frame"
x="SpatialPolygons", y="matrix"
x="SpatialPolygons", y="SpatialPoints"
```

**Comment by mdsumner** [comment]
Yes good point! I vaguely considered this after the fact.  Presumably methods will be added though, as they are there for Spatial. (Dev raster has an internal c++ representation for geometry now, though I'm not sure of plans for it).
