### ISSUE TITLE
Error in Reading Data into R Notebook

### ISSUE THREAD

**Issue by cubiloju** [r-spatial/sf#838]
When I try the following line of code in an R script file on my computer, it works fine:

```{r}
mvc <- st_read('ga_mvc.gpkg')
```
However, when I try to do the same in my notebook, I get the following error message:
```{r}
Cannot open data source ga_mvc.gpkg
 
Error in CPL_read_ogr(dsn, layer, as.character(options), quiet, type, : Open failed.
4. stop(structure(list(message = "Open failed.\n", call = CPL_read_ogr(dsn, 
layer, as.character(options), quiet, type, promote_to_multi, int64_as_string), 
cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available 
on this system"), class = "Rcpp_stack_trace")), class = c("Rcpp::exception", ...

3. CPL_read_ogr(dsn, layer, as.character(options), quiet, type, promote_to_multi, int64_as_string)

2. st_read.default("ga_mvc.gpkg")

1. st_read("ga_mvc.gpkg")
```

Any clues on how to fix this would be useful. I actually can get the code to run on my laptop, but my desktop simply refuses to acknowledge that the data file exists. I've checked the working directory and spelling and I've tried reinstalling calling the sf package as well.

**Comment by Nowosad** [comment]
Is the notebook in the same folder as your file?

**Comment by cubiloju** [comment]
That was the problem. I checked everything except that it seems. Thank you!
