### ISSUE TITLE
[st_ll_sample] Problem with size in `st_sample` for MULTILINESTRING

### ISSUE THREAD

**Issue by statnmap** [r-spatial/sf#843]
When specifying a unique `size` in `st_sample` the function will sample `size` number of points over all the features of the sf multilines object. If `size` is lower than the number of features, this results in an error like `grp[[i]] is out of bounds`.  
I would suggest to add a stop message at the beginning of function `st_ll_sample` with the following message:

```
  if (size < length(x)) {
    stop("Number of points asked is lower than number of features. ",
            "You probably want to repeat size by the length of x.")
  }
```

But I am not sure this is the best way.  
What do you think ?  
How can the definition of `size` be consistent between `st_poly_sample` and `st_ll_sample` ?

**Comment by edzer** [comment]
But we do have
```r
> st_sample(ls, rep(2, 4), type = "regular")
Geometry set for 4 features 
geometry type:  MULTIPOINT
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 2 ymax: 2.000008
epsg (SRID):    NA
proj4string:    NA
MULTIPOINT (0 0.9437566, 0 1.943757)
MULTIPOINT (0.03455627 0, 0.08455627 0)
MULTIPOINT (0.03537949 1, 0.08537949 1)
MULTIPOINT (2 2.000003, 2 2.000008)
```
Maybe that was not clear from the documenation?

**Comment by statnmap** [comment]
Yes and documentation says `either total size, or a numeric vector with sample sizes for each ...`. That should be clear enough.

**Comment by edzer** [comment]
.. means we can close here?

**Comment by statnmap** [comment]
Yes
