### ISSUE TITLE
convertion to XYZM fails

### ISSUE THREAD

**Issue by espinielli** [r-spatial/sf#858]
I would like to encode a (flight) trajectory as a XYZM LINESTRING, X=lon, Y=lat, Z=altitude, M=timestamp
The following example works:

```
library(sf)
library(dplyr)
library(lubridate)

tribble(
  ~lon, ~lat, ~alt, ~t,
     0,    0,    0,  0,
     1,    0,    1,  1,
     1,    1,    1,  2,
     0,    1,    0,  3
) %>%
  sf::st_as_sf(coords = c("lon","lat", "alt", "t"), dim = "XYZM")
```

but when time, t, is a `datetime` (like in my real life dataset) 

```
library(sf)
library(dplyr)
library(lubridate)
tribble(
  ~lon, ~lat, ~alt, ~t,
     0,    0,    0,  0,
     1,    0,    1,  1,
     1,    1,    1,  2,
     0,    1,    0,  3
) %>%
  mutate(t = as_datetime(t)) %>% 
  sf::st_as_sf(coords = c("lon","lat", "alt", "t"), dim = "XYZM")
```

I receive a strange error:

> Error in points_cpp(pts, gdim) : 
>  Not compatible with requested type: [type=character; target=double].

 I cannot find any helps how to deal with it, hence this issue in order to suggest, maybe, to spit a more helpful error message or even better to help me understand how to deal with XYZM dims for the case at hand ;-)

**Comment by edzer** [comment]
This is because when the tribble is converted into a matrix, in the presence of `POSIXt` columns R converts it into character:
```r
> as.matrix(x)
     lon lat alt t                    
[1,] "0" "0" "0" "1970-01-01 00:00:00"
[2,] "1" "0" "1" "1970-01-01 00:00:01"
[3,] "1" "1" "1" "1970-01-01 00:00:02"
[4,] "0" "1" "0" "1970-01-01 00:00:03"
```
This is also the case when `x` is a `data.frame`, nothing to do with `tibbles`.

**Comment by edzer** [comment]
This converts to `numeric` first, so you'll lose your time information but not the underlying numeric information, meaning that you can get your time back.

When encoding trajectories this way, be aware that self-intersections are to be expected: GEOS logic only considers X and Y.

**Comment by espinielli** [comment]
OK, thanks!
Eventually any suggestions as how to better model trajectories as defined above (3D + timestamps)?

**Comment by edzer** [comment]
Haven't had time to get to this recently; my last attempts were reported here: https://www.r-spatial.org/r/2017/08/28/nest.html

**Comment by edzer** [comment]
Well, that would make an interesting use case for the [stars](https://github.com/r-spatial/stars) project!

**Comment by espinielli** [comment]
yes, already watching that ;-) ...maybe I could collaborate and provide specific use cases...please let me know if/when of interest.
