### ISSUE TITLE
read_sf - loop/lapply stops and terminates R at 5th object in list

### ISSUE THREAD

**Issue by jedgroev** [r-spatial/sf#861]
I am trying to import multiple shapefiles from my desktop using sf. 
I tried with a loop and with lapply. In both cases it is working until the fourth 
object in the list, and crashes with the fifth. 
I've seen in another issue that there was a similar problem when pooling data 
with a database connection (PostgreSQL), but I do not have any idea how to fix it.   

``` {r }
data_l <- as.list(list.files(pattern='.shp'))
shps <- lapply(data_l, function(x) read_sf(x)) 
```

This is the error I get:
```
*** caught segfault ***
address 0x10, cause 'memory not mapped'

Traceback:
 1: .Call("_sf_CPL_read_ogr", PACKAGE = "sf", datasource, layer,     options, quiet, toTypeUser, promote_to_multi, int64_as_string)
 2: CPL_read_ogr(dsn, layer, as.character(options), quiet, type,     promote_to_multi, int64_as_string)
 3: st_read.default(..., quiet = quiet, stringsAsFactors = stringsAsFactors)
 4: st_read(..., quiet = quiet, stringsAsFactors = stringsAsFactors)
 5: as.data.frame(st_read(..., quiet = quiet, stringsAsFactors = stringsAsFactors))
 6: tibble::as_tibble(as.data.frame(st_read(..., quiet = quiet, stringsAsFactors = stringsAsFactors)))
 7: read_sf(x)
 8: FUN(X[[i]], ...)
 9: lapply(data_l, function(x) read_sf(x))

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 3
```

R version: 
```
version
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.4                         
year           2018                        
month          03                          
day            15                          
svn rev        74408                       
language       R                           
version.string R version 3.4.4 (2018-03-15)
nickname       Someone to Lean On   
```

**Comment by edzer** [comment]
Please provide the dataset with which this can be reproduced; if needed, off-line (email, or link in email).

**Comment by jsta** [comment]
Are you sure this is a looping issue? Are you able to read the fifth shapefile without a loop or lapply (`read_sf("fifth.shp")`)?

**Comment by jedgroev** [comment]
Sorry, I was just preparing a dataset to replicate the issue and noticed
that indeed it is not a looping issue.
It is one specific shapefile that gave the issue. But I don't see anything
suspicious.

Best,
Johannes

**Comment by edzer** [comment]
Try opening it with the command line tool gdalinfo (outside R).

**Comment by jedgroev** [comment]
Yes, but the shx and dbf file are included. All my shapefiles have the same
four components: shp, shx, prj, dbf.

**Comment by jedgroev** [comment]
gdalinfo doesn't work - should be for raster. But ogrinfo works.

ogrinfo HR_DAY_KERNEL90_POPSHP_SA3.shp
INFO: Open of `HR_DAY_KERNEL90_POPSHP_SA3.shp'
      using driver `ESRI Shapefile' successful.
1: HR_DAY_KERNEL90_POPSHP_SA3 (Polygon)

**Comment by edzer** [comment]
Please take action (see my first comment) or close this.
