### ISSUE TITLE
update to readme: missing dependency on libgdal-dev

### ISSUE THREAD

**Issue by jas1** [r-spatial/sf#862]
Hi, first of all , thanks for the awsome work on the package, 

I'm installing on ubuntu linux according to the readme , and when the script is executed

> sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
> sudo apt-get update
> sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 

in the last line have the issue:

> libgdal-dev : Depends: libmysqlclient-dev

it will be nice adding that library on the script: ( libmysqlclient-dev )

> sudo apt-get install libmysqlclient-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev 

after doing that i can proceed with R package and have a code snipet working ok.

that will save time on debugging :)  

thanks for the awsome package ! keep the good work :D !

**Comment by edzer** [comment]
On an ubuntu system, installing `libgdal-dev` should draw in all its dependencies, automatically.

**Comment by jas1** [comment]
thanks for the quick response, I just posted the error i got after running the script , may be some linux version issue. 

just in case if others have the same issue, my version is:

> Linux mint: 17.3 , rosa ( mate desktop )
> which is based on
> Ubuntu 14.04 , trusty

if can't replicate, just close.
