### ISSUE TITLE
GEOMETRYCOLLECTION errors on read with geometries of different dimensions

### ISSUE THREAD

**Issue by SymbolixAU** [r-spatial/sf#863]
Consider this GeoJSON (validated at http://geojsonlint.com/)

```r
js <- '{
  "type":"GeometryCollection",
  "geometries":[
  {
    "type":"Polygon",
    "coordinates":[[[0,0,5],[1,0,5],[1,1,5],[0,1,5],[0,0,5]]]
  },{
    "type":"Point",
    "coordinates":[0,1]
  }
  ]
}'
```

The POLYGON has a XYZ dimension
The POINT has XY dimension

`sf` can read this GeoJSON without issue

```r
sf <- sf::st_read( js )
sf
# Simple feature collection with 1 feature and 0 fields
# geometry type:  GEOMETRYCOLLECTION
# dimension:      XYZ
# bbox:           xmin: 0 ymin: 0 xmax: 1 ymax: 1
# epsg (SRID):    4326
# proj4string:    +proj=longlat +datum=WGS84 +no_defs
#                         geometry
# 1 GEOMETRYCOLLECTION Z (POLYG...
```

And it attributes the `Z` attribute to the POINT and GEOMETRYCOLLECTION

```r
sf$geometry[[1]]
# GEOMETRYCOLLECTION Z (POLYGON Z ((0 0 5, 0 1 5, 1 1 5, 1 0 5, 0 0 5)), POINT Z (0 1 0))
```

However, the equivalent `sf` structure to create this results in an error

```r
sf <- sf::st_sf( geometry = sf::st_sfc( sf::st_geometrycollection( x = list(
	sf::st_polygon( x = list( matrix(c(0,0,5,0,1,5,1,1,5,1,0,5,0,0,5), ncol = 3, byrow = T ) ) )
	, sf::st_point( x = c(0,1))
))))
# Error in sf::st_geometrycollection(x = list(sf::st_polygon(x = list(matrix(c(0,  : 
#   multiple dimensions found: XYZ, XY
```
---

## Questions

1. Can the `sf` code be made to read the geometries of different dimensions inside the GEOMETRYCOLLECTION without error?

2. Is it correct to append the Z attribute to the POINT, and to the GEOMETRYCOLLECTION?

**Comment by edzer** [comment]
1. Of course it _can be made_ like that, but I find the error the much more sane behavior than simply assigning a 0 to a missing dimension like GDAL, which is behind `st_read`, does. If you want to construct such an object, why not just pass the 0 to the Z, which at least suggests you know what you're doing? 

2. Yes; see [here](https://en.wikipedia.org/wiki/Well-known_text#Well-known_binary): there are four GEOMETRYCOLLECTION types: XY, XYZ, XYM and XYZM. There is no type for a mix of those.

**Comment by edzer** [comment]
By lack of activity / interest, closing here.
