### ISSUE TITLE
The parameter to st_buffer should be the radius

### ISSUE THREAD

**Issue by alesaccoia** [r-spatial/sf#865]
By looking at the polygons created by st_buffer I've noticed that, while expecting the __dist__ parameter to express a radius, it does actually relate to the diameter.
Trying to track this down, I've ended up at the following declaration in libgeos that seems to take a "width" parameter suggesting an overall width
https://github.com/libgeos/geos/blob/5bf8baeea27e734711ed51215665c26127d7b995/capi/geos_ts_c.cpp#L1949

**Comment by edzer** [comment]
Are you sure? If I do
```r
plot(st_buffer(st_point(0:1), dist = 1), axes = TRUE)
```
I see a circle with radius 2.

**Comment by alesaccoia** [comment]
you're right. I should have checked with a simple graph.. thanks :)
