### ISSUE TITLE
Legend issue when using multiple kinds of geometry

### ISSUE THREAD

**Issue by Peder2911** [r-spatial/sf#871]
Hey!

I am trying to make a map overlaid with scaled dots.
The dots are made by subsetting the dataset containing the statistics and applying st_centroid to the geometry. Then, i attempt to plot both datasets:

```
deathpoints <- geovote3%>%
  select(perthousand,geometry)%>%
  mutate(geometry = st_centroid(geometry))

ggplot(geovote3)+
  geom_sf(aes(fill = duque_pst))+
  geom_sf(data = deathpoints,aes(size = perthousand),color = 'lightgray')+
  scale_size_continuous(range = c(1,20))
```

This produces a map looking like this:
![geostats_co](https://user-images.githubusercontent.com/31591780/47220968-86dc6e80-d3b3-11e8-8ca0-f4ebf07dda78.png)

I need the legend to reflect the size of the points, not border thickness.

**Comment by Nowosad** [comment]
Related to: https://github.com/tidyverse/ggplot2/issues/2037

**Comment by jsta** [comment]
Have you tried using `guide_legend(override.aes = ...)` like at https://stackoverflow.com/a/51388610/3362993?

**Comment by adrfantini** [comment]
Can you please provide a Minimal Reproducible Example?

**Comment by edzer** [comment]
I don't think this is going to be solved by sf; please open the (or find the open) issue in ggplot2.
