### ISSUE TITLE
Can't build latest on Mac OSX

### ISSUE THREAD

**Issue by rmendels** [r-spatial/sf#874]
As there isn't a binary yet for mac OSX for the latest version  (0.70) i tried building from the source.  In the past I have had no problem,  now I get (first the command and then the output where problems begin - I renamed the downloaded .tgz file):

```r
 R CMD INSTALL sf.tar.gz --configure-args='-with-gdal-config=/Library/Frameworks/GDAL.framework/Versions/2.2/unix/bin/gdal-config -with-geos-config=/Library/Frameworks/GEOS.framework/Versions/3/unix/bin/geos-config'
.
.
.
** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
in method for ‘dbWriteTable’ with signature ‘"PostgreSQLConnection","character","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘dbDataType’ with signature ‘"PostgreSQLConnection","sf"’: no definition for class “PostgreSQLConnection”
in method for ‘coerce’ with signature ‘"Spatial","sf"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"Spatial","sfc"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sf","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sfc","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"XY","Spatial"’: no definition for class “Spatial”
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/rmendels/Library/R/3.5/library/sf/libs/sf.so':
  dlopen(/Users/rmendels/Library/R/3.5/library/sf/libs/sf.so, 6): Symbol not found: __ZN10OGRFeature16GetFieldAsDoubleEi
  Referenced from: /Users/rmendels/Library/R/3.5/library/sf/libs/sf.so
  Expected in: flat namespace
 in /Users/rmendels/Library/R/3.5/library/sf/libs/sf.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/rmendels/Library/R/3.5/library/sf’
* restoring previous ‘/Users/rmendels/Library/R/3.5/library/sf’
```

**Comment by edzer** [comment]
There is a binary on CRAN now.

**Comment by johnypark** [comment]
Hi @edzer,

I need to update my current 0.5 sf to newer 0.76 version, because nt_normalize doesn't get exported  I see there is OSX binaries for 0.7-6 in 
https://cran.r-project.org/web/packages/sf/index.html
which I hope to install, however when I try to install in Rstudio it does not locate 0.7-6 for binary. 

```
install.packages("sf")
Installing package into '/Users/JYP/Library/R/3.3/library'
(as 'lib' is unspecified)

  There is a binary version available but the source
  version is later:
   binary source needs_compilation
sf  0.5-5  0.7-6              TRUE

Do you want to install from sources the package which needs compilation?
y/n: 
```

I have also attempted to download the binary and install from package archive file, but it says
```
> install.packages("~/Desktop/sf_0.7-6.tgz", repos = NULL, type = .Platform$pkgType)
Installing package into '/User/Library/R/3.3/library'
(as 'lib' is unspecified)
tar: Failed to set default locale
Error in install.packages : file '~/Desktop/sf_0.7-6.tgz' is not a macOS binary package
```
Do you have any idea why binary is not showing up / my Rstudio does not recognize the downloaded binary as macOS binary package? 

My os is Mac OS 10.10.5 Yosemite. 

Thank you very much,
John.

**Comment by rmendels** [comment]
@jonypark - would check your setup to see what repositories it is looking at.  When I look at the CRAN page for sf I see:


Windows binaries: | r-devel: sf_0.7-6.zip, r-release: sf_0.7-6.zip, r-oldrel: sf_0.7-6.zip
-- | --
OS X binaries: | r-release: sf_0.7-6.tgz, r-oldrel: sf_0.7-6.tgz
Old sources:

So you should be seeing a much later binary.  If need be download the binary from CRAN and do a local install.

**Comment by johnypark** [comment]
I see the same. What I see:
Windows binaries:	r-devel: sf_0.7-6.zip, r-release: sf_0.7-6.zip, r-oldrel: sf_0.7-6.zip
OS X binaries:	r-release: sf_0.7-6.tgz, r-oldrel: sf_0.7-6.tgz

However, the problem for me is that the local install does not work, with the following error message. 
```
> install.packages("~/Desktop/sf_0.7-6.tgz", repos = NULL, type = .Platform$pkgType)
Installing package into '/User/Library/R/3.3/library'
(as 'lib' is unspecified)
tar: Failed to set default locale
Error in install.packages : file '~/Desktop/sf_0.7-6.tgz' is not a macOS binary package
```

**Comment by johnypark** [comment]
@rmendels What type of setup do you recommend checking? I don't aware of any particular setup when accessing CRAN via web. Please elaborate.

**Comment by rsbivand** [comment]
What is your version of R? If 3.3.*, note that this is very old (with sf_0.5.5). First upgrade R to 3.6.* (current), then install the CRAN binary. The internals of OSX binary packages seem to have changed between R 3.3 (mavericks) and R 3.4 (el capitan), and 3.5 is oldrelease. You are installing in `/Users/JYP/Library/R/3.3/library` etc., suggesting that you are still using R 3.3. IIRC, Apple introduced signatures or certificates for installation of binaries about then, so an unsigned package should not install. Most likely Yosemite is not supported for R > 3.3; if that is the case and you are not at MacOS >= 10.11, you are stuck, and would have to install the full antiquated source build train, the out-of-date sf external dependencies, and sf from source. If you can upgrade your OS, then R, everything works.

**Comment by johnypark** [comment]
Thanks for the detailed explanation, @rsbivand. I see now what was the problem (older version of R) 
My R version is indeed 3.3, and the reason is exactly what you said; It is running on Yosemite. Upgrading to latest OS would be desirable, but would not be practical right now. I will go ahead and look for ways to build the package from source.
