### ISSUE TITLE
st_nearest_feature function missing

### ISSUE THREAD

**Issue by HughSt** [r-spatial/sf#876]
Hi - I'm sure the error is on my side, but for some reason I cannot find the st_nearest_feature function which exists in the manual. I have installed sf version 0.6-3. It makes no difference if I install from CRAN or from the tgz file. 

Related, I have access to several functions which do not appear in the user manual such as st_centroid, st_node..

**Comment by edzer** [comment]
This feature requires GEOS version 3.6.1 or newer - which version has GEOS on your system?

**Comment by edzer** [comment]
What does the output of
```r
example(st_nearest_feature)
```
give you?

**Comment by rdornas** [comment]
I think I am maybe experiencing the exact same problem. The configuration on my side is equal to that from @HughSt, although I may inform that I use MacOS Mojave .

The result of ```example(st_nearest_feature)``` is the following warning message:

> Warning message:
> In example(st_nearest_feature) : no help found for ‘st_nearest_feature’

**Comment by edzer** [comment]
Could you (both) please check again with sf 0-7-1 from CRAN?

**Comment by rdornas** [comment]
I tried to update from CRAN some days ago without success (some problem with Xcode) but now it worked and ```st_nearest_features``` is working like a charm.

Thank you @edzer!

**Comment by HughSt** [comment]
Sorry for the slow reply - likewise, can access the function now. Thanks!

**Comment by edzer** [comment]
OK thanks!
