### ISSUE TITLE
par(mfrow) do not work with sf::plot

### ISSUE THREAD

**Issue by BastienFR** [r-spatial/sf#877]
I've posted on [stackoverflow ](https://stackoverflow.com/questions/52975447/reorganize-sf-multi-plot-and-add-a-legend) first and didn't get an answer and the more than I work on it, the more I think it might be a bug.

I'm trying to organize better my multi-plot using the `par(mfrow)` methods as stated in the help file:

> For more control over individual maps, set parameter mfrow with par prior to plotting, and plot single maps one by one.

But it is not working:

```
library(sf) 
library(dplyr)

nc <- st_read(system.file("gpkg/nc.gpkg", package="sf"), quiet = TRUE) %>% 
  select(AREA, PERIMETER) %>% 
  mutate(AREA = as.factor(AREA<median(AREA)))

par(mfrow=c(1,2))
plot(nc[,1])
plot(nc[,2])
par(mfrow=c(1,1))
```

Gives me two independent plots instead of two plots on the same window.

Needless to say, this:

```
par(mfrow=c(1,2))
plot(1:10)
plot(2:22)
par(mfrow=c(1,1))
```
works so it's seem it's `sf:plot` the problem.

Am I doing something wrong or it's a bug?

**Comment by edzer** [comment]
It's a bug in the documentation. `mfrow` will only work if you plot geometries, as in `plot(st_geometry(nc))`.

**Comment by BastienFR** [comment]
Ok, thanks for the info.  It works that way, however it's unfortunate as we lose that way all the nice automatic features of  `sf::plot` (mostly the automatic color scheme for the field of interest and the associated legend).

**Comment by edzer** [comment]
This, however does work (plots without legends):
```r
> par(mfrow=c(1,2))
> plot(nc[,2], key.pos = NULL, reset = FALSE)
> plot(nc[,2], key.pos = NULL, reset = FALSE)
```
