### ISSUE TITLE
ggplotting sf points: 'color' shown with grey fill in legend if plotting factors

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/sf#881]
Reporting what I believe to be a bug. I'm unsure whether this is on `ggplot2` or `sf`. An example will explain this best.
```R
library(ggplot2)
library(sf)
nc = st_read(system.file("shape/nc.shp", package="sf")) %>% st_centroid()
ggplot(nc, aes(color = factor(SID79))) + geom_sf()
```
![screenshot_20181102_154424](https://user-images.githubusercontent.com/12826141/47921973-31758680-deb6-11e8-8f57-76c1f70cc942.png)

The colors in the legend should be associated with a point, not with a box with grey filled in. This only happens when plotting factor points, with a discrete colorbar.

**Comment by edzer** [comment]
You would expect something like this
```
ggplot(data.frame(x=1:10, y = 10:1,name =letters[1:10]), aes(x=x,y=y,color=name)) + geom_point()
```
right? A `ggplot2` issue, not `sf`.

**Comment by adrfantini** [comment]
@edzer Exactly. Well, I'll open the issue there then.

**Comment by yutannihilation** [comment]
FYI, this is a known issue. You can manually specify the type of legend via `show.legend`. See [`?geom_sf`](https://ggplot2.tidyverse.org/reference/ggsf.html#examples):

>    ``` r
>    # Unfortunately if you plot other types of feature you'll need to use
>    # show.legend to tell ggplot2 what type of legend to use
>    nc_3857$mid <- sf::st_centroid(nc_3857$geometry)
>    ggplot(nc_3857) +
>      geom_sf(colour = "white") +
>      geom_sf(aes(geometry = mid, size = AREA), show.legend = "point")
>    ````

**Comment by yutannihilation** [comment]
@adrfantini https://github.com/tidyverse/ggplot2/issues/2037 is the issue and the usage of `show.legend` was introduced for this. That's why I said "a known issue" :)

**Comment by edzer** [comment]
Nearly a feature, by now! :-)
