### ISSUE TITLE
Have st_write() return obj invisibly?

### ISSUE THREAD

**Issue by mpjashby** [r-spatial/sf#889]
It may be useful to have `st_write()` return the value of the first argument obj invisibly, so that it can be used within magrittr pipelines and be consistent with, for example, the [`readr::write_*()`](https://readr.tidyverse.org/reference/write_delim.html#value) family. This would allow code such as:

```
some_sf_data %>%
  st_write("sf_data.gpkg") %>%
  rmapshaper::ms_simplify(keep = 0.1) %>% 
  st_write("sf_data_simplified.gpkg") %>%
  dplyr::glimpse()
```

Other use cases would include needing to export the same data in multiple formats, or exporting spatial data, removing the geometry column with `st_set_geometry(NULL)` and then saving the remaining non-spatial data.

**Comment by edzer** [comment]
Is there some other tidyverse function that _writes_, and does this too?

**Comment by mpjashby** [comment]
Sorry, I meant to say [`readr::write_*()`](https://readr.tidyverse.org/reference/write_delim.html#value) rather than `readr::read_delim()` and have corrected it now above. 

Several other Tidyverse functions do this, including the [`haven::write_*()`](https://haven.tidyverse.org/reference/read_spss.html#value) family and (in a slightly different context) [`dbplyr::copy_to()`](https://dbplyr.tidyverse.org/reference/copy_to.src_sql.html#value).

The [Tidyverse style guide (section 3.3)](https://style.tidyverse.org/functions.html) says:

> If your function is called primarily for its side-effects (like printing, plotting, or saving to disk), it should return the first argument invisibly. This makes it possible to use the function as part of a pipe.

A similar point is made in [The tidy tools manifesto](https://tidyverse.tidyverse.org/articles/manifesto.html). Apologies for not linking to these other resources when I opened the issue!

**Comment by edzer** [comment]
Good idea - thanks!
