### ISSUE TITLE
feature request: `rbind` for sfc too?

### ISSUE THREAD

**Issue by MatthieuStigler** [r-spatial/sf#890]
Hi

Would it be possible to allow `rbind.sf` to also work on *sfc* objects, not just *sf*? It seems reasonable a user would try:

    rbind(st_geometry(dat),
          st_geometry(dat2))

But this currently gives a weird output (see bwloe).

Thanks!!

``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
packageVersion("sf")
#> [1] '0.7.2'

crs = st_crs(3857)
dat = st_sf(a=c(1,2,3), geometry = st_sfc(list(st_point(0:1), st_point(c(2,3)), st_point(c(3,4)))), crs = crs)


dat2 = st_sf(b=c(1,2,3), geometry = st_sfc(list(st_point(0:1), st_point(c(2,3)), st_point(c(3,4)))), crs = crs)

rbind(select(dat, geometry),
      select(dat2, geometry))
#> Error in select(dat, geometry): could not find function "select"

rbind(st_geometry(dat),
      st_geometry(dat2))
#>      [,1]      [,2]      [,3]     
#> [1,] Integer,2 Numeric,2 Numeric,2
#> [2,] Integer,2 Numeric,2 Numeric,2
```

<sup>Created on 2018-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment]
The first error is caused by `select`: you have to load `dplyr` for it to work.

The second fails because there is no `rbind` method for `sfc` objects. Note that `select` returns a data.frame with a single column selected, where `st_geometry` returns the geometry column, not encapsulated in a data.frame (think of `dplyr::pull(dat, geometry)`.

To combine `sfc` list columns, use `c` rather than `rbind`.

**Comment by MatthieuStigler** [comment]
oops sorry about the first, forgot to add `dplyr` in the reprex. 

And ok, I see the point, from a user perspective, `st_geometry(sf)` and `select(sf, geometry)` seem to be pretty similar, but the former is not a data.frame, while the latter is, and hence it is consistent that there is a `rbind` method only for the latter. 

Wondering though if it would make sense to sacrifice a bit on consistency, and still have a rbind.sfc that promotes to sf, i.e. do `st_sf(c.sfc(...))`, possibly with a warning?

Thanks!!

**Comment by edzer** [comment]
I think that would give the wrong message.
