### ISSUE TITLE
Why is there zero or negative areas with st_area?

### ISSUE THREAD

**Issue by maikol-solis** [r-spatial/sf#897]
Hi, 

I'm working with polygons without any geographical system (I don't need them), i.e, I need only build geometrical polygons in the plane and estimate their areas. 

I build three examples with one, two and three triangles respectively. Each example was constructed on the negative `x` axis (If the polygons are in the in the positive axis for `x` and `y` all works as expected). 

I obtained zero or negative areas. 

```{R}
  t1 <- rbind(c(-1, 0), c(0, 0), c(0, 1), c(-1, 0))
  p <- st_polygon(list(t1))
  st_area(p)

  # Right
  # Output = 0.5 

  t1 <- rbind(c(-1, 0), c(0, 0), c(0, 1), c(-1, 0))
  t2 <- rbind(c(-2, 0), c(-1, 0), c(-1, 1), c(-2, 0))
  p <- st_polygon(list(t1, t2))
  st_area(p)

  # Wrong! Expected 1
  # Output = 0

  t1 <- rbind(c(-1, 0), c(0, 0), c(0, 1), c(-1, 0))
  t2 <- rbind(c(-2, 0), c(-1, 0), c(-1, 1), c(-2, 0))
  t3 <- rbind(c(-3, 0), c(-2, 0), c(-2, 1), c(-3, 0))
  p <- st_polygon(list(t1, t2, t3))
  st_area(p)

  # Wrong! Expected 1.5
  # Output = -0.5
```

I have no idea what is going on here.

Thanks for the help!

```
sf version: 0.7-1 from CRAN
```

**Comment by edzer** [comment]
Because
```r
> st_is_valid(p)
[1] FALSE
```
secondary rings passed on to `st_polygon` are taken as holes, which in your case they aren't; hole area is subtracted from the area of the exterior ring.

**Comment by maikol-solis** [comment]
Thank you very much @edzer for the explanation. It make sense. 

How could tell to `sf` that the secondary rings aren't holes? 
How could do I get the expected answers?

**Comment by edzer** [comment]
They are. Always. You want to use `st_multipolygon`, which allows for more than one exterior ring.
