### ISSUE TITLE
Affine transformation using `mutate()`

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/sf#903]
Continuing a discussion from twitter (https://twitter.com/edzerpebesma/status/1066051809347870720):

The main idea is to allow each feature to be scaled independently:

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.3.2, PROJ 4.9.3
library(dplyr)
library(spData)

nz1 = nz %>% 
        mutate(scale = seq(0.2, 1, length.out = nrow(nz)))

# works
nz2 = nz1 %>% 
        mutate(geom = geom * 0.5)

# does not work
nz3 = nz1 %>% 
        mutate(geom = geom * scale)
#> Error in mutate_impl(.data, dots): Evaluation error: non-conformable arguments.

# does not work
nz4 = nz1 %>% 
        rowwise() %>% 
        mutate(geom = geom * scale)
#> Error in mutate_impl(.data, dots): Column `geom` must be length 1 (the group size), not 3
```

<sup>Created on 2018-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment]
With this, your first "does not work" should now work, I assume that was what you were looking for. Note the newly created ambiguity of
```r
library(sf)
# Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
sfc = st_sfc(st_point(0:1), st_point(2:3))
sfc + c(2,3) # add single 2D point to EACH geometry
# Geometry set for 2 features 
# geometry type:  POINT
# dimension:      XY
# bbox:           xmin: 2 ymin: 4 xmax: 4 ymax: 6
# epsg (SRID):    NA
# proj4string:    NA
# POINT (2 4)
# POINT (4 6)
sfc * c(2,3) # first geometry multiplied by 2, second by 3
# Geometry set for 2 features 
# geometry type:  POINT
# dimension:      XY
# bbox:           xmin: 0 ymin: 2 xmax: 6 ymax: 9
# epsg (SRID):    NA
# proj4string:    NA
# POINT (0 2)
# POINT (6 9)
```
Cc: @mdsumner

**Comment by mdsumner** [comment]
Ugh- yeah that's a bit of a screwdriver in the works, I don't see a good solution

**Comment by edzer** [comment]
I documented it.

**Comment by mdsumner** [comment]
Oh great, thanks for doing this @edzer !

**Comment by Nowosad** [comment]
I've tested it on a few cases and it worked as expected. It is a great improvement.
There is one issue I've found though - **geom_sf()** has some problems with transformed data. Base graphics and **tmap** works fine:

@edzer  should I open a new issue on **ggplot2** or keep it here?

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.3.2, PROJ 4.9.3
library(dplyr)
library(spData)

new_nz = nz %>% 
        mutate(scale = seq(0.2, 1, length.out = nrow(nz))) %>% 
        mutate(geom = geom * scale)


# plotting ----------------------------------------------------------------
library(tmap)
library(ggplot2)
# base plot ---------------------------------------------------------------
plot(new_nz["Median_income"])
```

![](https://i.imgur.com/blsZYwB.png)

``` r

# tmap plot ---------------------------------------------------------------
tm_shape(new_nz) + tm_polygons("Median_income")
#> Warning: Current projection of shape new_nz unknown and cannot be
#> determined.
#> Warning: unknown projection
#> Legend labels were too wide. The labels have been resized to 0.26, 0.26, 0.26, 0.26, 0.26, 0.26. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
```

![](https://i.imgur.com/aLDNe8v.png)

``` r

# ggplot ------------------------------------------------------------------
ggplot() + geom_sf(data = new_nz, aes(fill = Median_income))
```

![](https://i.imgur.com/RYIAJjY.png)

<sup>Created on 2018-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment]
Let's try to sort out what happens first.

IIRC, by transforming it `sf` strips the CRS (i.e., sets it to NA) since you did some transformation outside the CRS framework (WKT / PROJ). `geom_sf` may make some hard assumption about the CRS it is in, as it will forcably assume your data have world coordinates. Maybe you need to put it back to the starting CRS first?

**Comment by edzer** [comment]
Forget my previous message: it looks like `geom_sf` relies on behaviour that worked previous to https://github.com/r-spatial/sf/commit/f20a5836e89698c92c12588ed02a5d58173ddd08 but no longer works. We'll need to revert the fix.

**Comment by edzer** [comment]
Which I just did: https://github.com/r-spatial/sf/commit/9fe41f2574a98e7cb29ecb572a51c0836182c86f . Sorry for the bad news.

**Comment by edzer** [comment]
No, everywhere -- I think it is in `ggplot2:::sf_rescale01` (which I suggested...)

**Comment by Nowosad** [comment]
Just for a reference - https://github.com/tidyverse/ggplot2/blob/828e948dcfc5c5a2bd532e78b160bb3abb25de74/R/sf.R#L748

**Comment by Nowosad** [comment]
Looks good now:

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.3.2, PROJ 4.9.3
library(dplyr)
library(spData)

new_nz = nz %>% 
        mutate(scale = seq(0.2, 1, length.out = nrow(nz))) %>% 
        mutate(geom = geom * scale)


# plotting ----------------------------------------------------------------
library(tmap)
library(ggplot2)
# base plot ---------------------------------------------------------------
plot(new_nz["Median_income"])
```

![](https://i.imgur.com/UrcrMpO.png)

``` r

# tmap plot ---------------------------------------------------------------
tm_shape(new_nz) + tm_polygons("Median_income")
#> Warning: Current projection of shape new_nz unknown and cannot be
#> determined.
#> Warning: unknown projection
#> Legend labels were too wide. The labels have been resized to 0.26, 0.26, 0.26, 0.26, 0.26, 0.26. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
```

![](https://i.imgur.com/opRFhX9.png)

``` r

# ggplot ------------------------------------------------------------------
ggplot() + geom_sf(data = new_nz, aes(fill = Median_income))
```

![](https://i.imgur.com/p9uMSNi.png)

<sup>Created on 2018-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Nowosad** [comment]
@edzer It looks good for me. Should I close the issue or there is still something related that needs to be tested?
