### ISSUE TITLE
How to remove POINT geometries inside GEOMETRYCOLLECTIONs

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/sf#904]
I have a dataset which is largely made up of LINESTRINGS and MULTILINESTRINGS. Unfortunately, it may happen that, when obtaining this dataset, a GEOMETRYCOLLECTION consisting of one or more POINTs plus additional LINESTRINGs can be created.

One example is [this](https://drive.google.com/open?id=1en6yhj-qM0Hk816xNlT16PlU35gSidcz) dataset:

```R
library(sf)
a = st_read('rivers.gpkg')
a %>% st_geometry_type() %>% summary
```
```
          GEOMETRY              POINT         LINESTRING            POLYGON         MULTIPOINT    MULTILINESTRING 
                 0                  0              12331                  0                  0                  4 
      MULTIPOLYGON GEOMETRYCOLLECTION     CIRCULARSTRING      COMPOUNDCURVE       CURVEPOLYGON         MULTICURVE 
                 0                  1                  0                  0                  0                  0 
      MULTISURFACE              CURVE            SURFACE  POLYHEDRALSURFACE                TIN           TRIANGLE 
                 0                  0                  0                  0                  0                  0
```
The felon is feature number 10623:
`a[10623,] %>% st_geometry()` returns:
```
Geometry set for 1 feature 
geometry type:  GEOMETRYCOLLECTION
dimension:      XY
bbox:           xmin: 17.75175 ymin: 40.29519 xmax: 17.7518 ymax: 40.29525
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
GEOMETRYCOLLECTION (POINT (17.7518 40.29525), L...
```

I want to remove all POINTs in the dataset. I cannot `st_cast` , because I get an error:
`a %>% st_cast('MULTILINESTRING')`
```
Error in st_cast.POINT(x[[1]], to, ...) : 
  cannot create MULTILINESTRING from POINT
```

How can I remove all POINTs from the dataset, recursing into collections?

**Comment by tim-salabim** [comment]
You can either use `st_collection_extract(a, "LINESTRING")` if you're after only the (multi)lines. Or use `st_dimension(a)` and use that for indexing the POINT geometries.

**Comment by adrfantini** [comment]
How could I miss this? Thanks!
