### ISSUE TITLE
Feature request: st_equals tolerance parameter?

### ISSUE THREAD

**Issue by kendonB** [r-spatial/sf#906]
All in the title. 

I am trying to verify if two polygons are the same - the ones I have inspected appear to differ by machine precision.

I have tried using `st_simplify` before `st_equals` to no avail. The only workaround I see is to round all the underlying points before running st_equals.

Perhaps an `st_round` would also be useful.

**Comment by kendonB** [comment]
So rounding the underlying points also fails for one example as I get `Evaluation error: TopologyException: side location conflict`. I will post something reproducible.

**Comment by jeffreyhanson** [comment]
Just as a heads up in case you didn't know, and apologies if this doesn't actually help at all, but you might be interested in the `lwgeom::st_snap_to_grid` function (see https://www.rdocumentation.org/packages/lwgeom/versions/0.1-4/topics/st_snap_to_grid) which can be used to align (or round) coordinates to a specific precision (e.g. single decimal place).

**Comment by jeffreyhanson** [comment]
Also, perhaps the `st_precision` might be helpful? This allows you to tag an object with a desired level of precision when performing geospatial computations (see here for more info: https://www.rdocumentation.org/packages/sf/versions/0.7-1/topics/st_precision). Here's an example that works for me using `st_precision` and `st_equals`.

```
# load package
library(sf) # version 0.7.1

# create two polygons that differ only slightly
outer <- matrix(c(0,0,10,0,10,10,0,10,0,0), ncol=2, byrow=TRUE)
hole1 <- matrix(c(1,1,1,2,2,2,2,1,1,1), ncol=2, byrow=TRUE)
hole2 <- matrix(c(5,5,5,6,6,6,6,5,5,5), ncol=2, byrow=TRUE)
pl1 <- st_polygon(list(outer, hole1, hole2))
pl2 <- pl1 + 1e-10
pl1 <- st_sfc(pl1)
pl2 <- st_sfc(pl2)

# test if equal without setting precision
st_equals(pl1, pl2, sparse = FALSE) # FALSE

# test if equal after setting precision to nearest millimetre
st_precision(pl1) <- 1000
st_precision(pl2) <- 1000
st_equals(pl1, pl2, sparse = FALSE) # TRUE
```

**Comment by kendonB** [comment]
`st_precision` worked. Super easy. Thanks heaps for the help. I think the `st_precision` call prior to `st_equals` is sufficiently simple to not warrant the originally requested feature. Thus closing.
