### ISSUE TITLE
bad maths in aggregate example in vignette 

### ISSUE THREAD

**Issue by barryrowlingson** [r-spatial/sf#908]
vignette 4 does this:

```
nc <- nc %>% mutate(frac74 = SID74 / BIR74)
(a <- aggregate(nc[,"frac74"], list(Ashe_nb = lengths(st_intersects(nc, Ashe)) > 0), mean))
```

which (I think) is computing the mean of fractions within the groups. If you really want `frac74` within groups you'd sum `SID74` and `BIR74` within groups and divide the totals.

**Comment by edzer** [comment]
Good catch - thanks!!
