### ISSUE TITLE
st_read fails with geometry_column argument

### ISSUE THREAD

**Issue by dmkaplan2000** [r-spatial/sf#920]
I just tried something along these lines:

st_read(psqlcon,query="SELECT fid, geom1, geom2 FROM mygeomtable",geometry_column="geom2")

and it fails stating:

Error: Unused arguments:  geometry_column = geom2
Check arguments for `st_sf()` for details.

Using sf_column_name instead of geometry_column allows the function to work, but does not appear to do what one expects and is undocumented.

**Comment by dmkaplan2000** [comment]
I think I understand the problem. When loading a layer over a DBI connection, all geometry columns are converted to sf format, so there is no particular need to specify the geometry_column argument. If this is the case, then st_read should probably fail with a better error message if geometry_column is given for a DBI connection, and the documentation for st_read should either be modified to make clear which arguments are valid for which methods or split into multiple pages, one per method.

**Comment by edzer** [comment]
Totally agree, this is a half baked feature; see also #909. Since the simple feature standard nowhere mentions feature IDs IIRC, I'd be perfectly happy to entirely get rid of them - one headache less.
