### ISSUE TITLE
spData dependency?

### ISSUE THREAD

**Issue by bhogan-mitre** [r-spatial/sf#922]
Should `spData` be called out as a dependency?  I just had an attempted install fail because it was unavailable.  Do you know why the namespace thinks it needs `spData`?

```
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘spData’
ERROR: lazy loading failed for package ‘sf’
* removing ‘[***]/sf’
The downloaded source packages are in
	‘/tmp/RtmpC5QvDf/downloaded_packages’
```

**Comment by edzer** [comment]
Looks like an indirect dependency, caused by `classInt`. If you (re)install classInt, it should pull `spData` in.

**Comment by bhogan-mitre** [comment]
Got it, thank you!

**Comment by rsbivand** [comment]
In **classInt**, I'm moving **spData ** from Depends: to Suggests:. However, when the example code is in an if/else block, the output does not appear in the correct order in relation to the code. This completely mangles the pkgdown output introduced last week. How should I tell pkgdown to interleave the example output inside the if/else block? @edzer and https://github.com/r-spatial/classInt/issues/3

**Comment by rsbivand** [comment]
**classInt** 0.3-1 on CRAN.
