### ISSUE TITLE
st_update_bbox function

### ISSUE THREAD

**Issue by kendonB** [r-spatial/sf#924]
Many manipulation functions can cause the `bbox` attribute to become out of date. Would be great to have a user-visible function to update the bbox.

**Comment by edzer** [comment]
That should not happen. Which functions are you referring to?

**Comment by kendonB** [comment]
`filter.sf` and `slice.sf` at least. But your comment on #923 makes me think something weird is going on somewhere. I will investigate in the NZ morning if you send you're able to send your session_info.

**Comment by kendonB** [comment]
Looks like this is redundant as of the dev `dplyr` (manipulation functions no longer cause the bbox attribute to become out of date). See https://github.com/r-spatial/sf/issues/923

The only question is whether `sf` also wants to address this to be compatible with CRAN dplyr.

**Comment by edzer** [comment]
Any idea when dplyr dev will be released?

**Comment by kendonB** [comment]
@romainfrancois?

**Comment by romainfrancois** [comment]
Early January is the plan. Actual release will depend on the results of rev dep checks.

**Comment by edzer** [comment]
Since sf just hit CRAN, we'll wait for that. Happy holidays!
