### ISSUE TITLE
speed up plot for  sfc_POINT

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/sf#933]
There's a couple of places to speed up point plotting, I PR'd it but that's messed up with formatting stuff and it's trivial so I thought I'd just put it here: 

1. Unlist into a matrix and transpose rather than `rbind`. 
2. Use `rowMeans` to do NA check rather than `apply,, is.finite`

I suppose there's still a danger that all points are empty, so the is.null test fails and then the `points(mat[ne, ]` is empty - but an `allNA` can catch that and still be fast afaics. 

Modifications: 

```R
#mat = do.call(rbind, x)
## unwrap into a matrix of known dim[2] and transpose
mat = t(matrix(unlist(x, use.names = FALSE), ncol = length(x)))
if (!is.null(mat)) {
	#ne = apply(mat, 1, function(x) all(is.finite(x))) # ne: not empty
	ne = !is.na(rowMeans(mat))  ## faster than apply
	
```

applied to these lines: 

https://github.com/r-spatial/sf/blob/e85b9f8a0e76a3eb85c068ab40f0231422697440/R/plot.R#L294-L296

**Comment by edzer** [comment]
Thanks @mdsumner !
