### ISSUE TITLE
add crs argument for st_as_sfc.bbox

### ISSUE THREAD

**Issue by kendonB** [r-spatial/sf#934]
I can provide a PR if no one else gets to this. If not today, then in the next couple of weeks

**Comment by edzer** [comment]
`bbox` objects carry a crs when obtained from an object that has one, and `st_as_sfc` passes this on:
```r
> st_as_sfc(st_bbox(nc))
Geometry set for 1 feature 
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs
POLYGON ((-84.32385 33.88199, -75.45698 33.8819...
```
Why add it to the `st_as_sfc` method?

**Comment by kendonB** [comment]
I'm seeing it not get passed on. Will investigate

**Comment by kendonB** [comment]
I was collecting bboxes from `sfg` objects. I think my application is fringe enough to not worry about in `st_as_sfc.bbox`.
