### ISSUE TITLE
Confusion with spatial operators

### ISSUE THREAD

**Issue by JimShady** [r-spatial/sf#941]
```
library(sf)
library(tidyverse)

# load large grid
large_grid <- st_read('https://www.dropbox.com/s/ovqpau5aqbjgf0i/large_grid_test.geojson?dl=1') %>%
 st_set_crs(27700)

# load small grid
small_grid <- st_read('https://www.dropbox.com/s/r5yviyxazd9bayo/small_grid_test.geojson?dl=1') %>% 
  st_set_crs(27700)

# look at grids
ggplot() +
geom_sf(data = small_grid, fill=NA, aes(colour = as.factor(small_grid_id))) +
geom_sf(data = large_grid, fill=NA, colour= 'red')
```

![image](https://user-images.githubusercontent.com/2901470/50772556-24925c00-1286-11e9-878b-b0b5136bf31a.png)

Polygon 4210 shares a boundary with both the large polygons, but is inside only the left polygon. I want to join it to only that larger polygon.

```
joined <- st_join(small_grid, large_grid, join = st_intersects)

joined

Simple feature collection with 4 features and 2 fields
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 523900 ymin: 175200 xmax: 524069.4 ymax: 175496.4
epsg (SRID):    27700
proj4string:    +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs
    small_grid_id unique_geom_id                       geometry
1            4210            125 POLYGON ((523900 175200, 52...
1.1          4210            164 POLYGON ((523900 175200, 52...
2               5            125 POLYGON ((523931.6 175496.4...
2.1             5            164 POLYGON ((523931.6 175496.4...
```
Then for polygon 5, I want this polygon to be joined to both the larger polygons, but I want it to be split into two features. One feature the intersection with the left polygon, one feature the intersection with the right polygon.

**Comment by JimShady** [comment]
PS: Apologies for multiple edits to the post above. I've been clarifying my text.

**Comment by edzer** [comment]
Running your example, I get the image below.
![x](https://user-images.githubusercontent.com/520851/50772783-375d5e80-128f-11e9-9455-f24a975a9b1f.png)

**Comment by JimShady** [comment]
Sorry @edzer . I just updated the geojson it's pulling it from. Try it now.

**Comment by edzer** [comment]
It can be deceptive how something looks:
```r
> st_area(st_geometry(small_grid)[1] / st_geometry(large_grid)[1]) # / : geometry diff
0.6009414 [m^2]
> st_area(st_geometry(small_grid)[1] / st_geometry(large_grid)[2])
9999.399 [m^2]
```
which implies the feature geometry indicated by 4210 overlaps with both red polygons.

**Comment by JimShady** [comment]
Ah damn. Thanks. Something like this had occurred to me, but I couldn't figure out how to check it exactly.

In this case, is there an operator in sf that will join the two smaller polygons to the two larger polygons, and also split them into two separate polygons?

The result will be four different polygons.

**Comment by JimShady** [comment]
Ok. I think I have managed to accomplish what I need. Thanks for your help. I post my code below incase someone wants to point out an error, or a better way of doing it. Thanks!

```r
library(sf)
library(tidyverse)

# load large grid
large_grid <- st_read('https://www.dropbox.com/s/ovqpau5aqbjgf0i/large_grid_test.geojson?dl=1') %>%
  st_set_crs(27700)

# load small grid
small_grid <- st_read('https://www.dropbox.com/s/r5yviyxazd9bayo/small_grid_test.geojson?dl=1') %>% 
  st_set_crs(27700)

# look at grids
ggplot() +
  geom_sf(data = small_grid, fill=NA, aes(colour = as.factor(small_grid_id))) +
  geom_sf(data = large_grid, fill=NA, colour= 'red')

# Join the smaller to larger
joined <- st_join(small_grid, large_grid, join = st_intersects)

# Clip/split the smaller grids by the larger grids
for (i in 1:nrow(joined)) {
  st_geometry(joined[i,]) <-  st_geometry(joined[i,]) / st_geometry(large_grid[large_grid$unique_geom_id == joined[i,]$unique_geom_id,])
}

# Check it has worked out ok by calculating the areas, and plotting.
joined$area <- as.factor(as.numeric(st_area(joined)))

ggplot() + 
  geom_sf(data=joined, aes(colour = area))
```

![image](https://user-images.githubusercontent.com/2901470/50775268-991cc900-128d-11e9-8ad8-6d6b9805558b.png)
