### ISSUE TITLE
unable to install R package 'tmap' for 3.4.3 issue with 'sf' & 'gdal' for CentoS 7

### ISSUE THREAD

**Issue by phanirg** [r-spatial/sf#949]
installing to /opt/microsoft/rclient/3.4.3/runtime/R/site-library/sf/libs
** R
** data
** demo
** inst
** preparing package for lazy loading
in method for ‘dbWriteTable’ with signature ‘"PostgreSQLConnection","character","sf"’: no definition for
in method for ‘dbDataType’ with signature ‘"PostgreSQLConnection","sf"’: no definition for class “Postgr
in method for ‘coerce’ with signature ‘"Spatial","sf"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"Spatial","sfc"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sf","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"sfc","Spatial"’: no definition for class “Spatial”
in method for ‘coerce’ with signature ‘"XY","Spatial"’: no definition for class “Spatial”
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘sf’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/microsoft/rclient/3.4.3/runtime/R/site-library/sf/libs/sf.so':
  /opt/microsoft/rclient/3.4.3/runtime/R/site-library/sf/libs/sf.so: undefined symbol: _ZN10OGRFeature20
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/opt/microsoft/rclient/3.4.3/runtime/R/site-library/sf’
ERROR: dependency ‘sf’ is not available for package ‘lwgeom’
* removing ‘/opt/microsoft/rclient/3.4.3/runtime/R/site-library/lwgeom’

The downloaded source packages are in
    
Warning messages:
1: In install.packages("lwgeom", configure.args = "--with-gdal-config=/usr/local/bin/gdal-config --with-ith-proj-include=/usr/local/include --with-proj-lib=/usr/local/lib --with-proj-share=/usr/local/share/pr
  installation of package ‘sf’ had non-zero exit status
2: In install.packages("lwgeom", configure.args = "--with-gdal-config=/usr/local/bin/gdal-config --with-ith-proj-include=/usr/local/include --with-proj-lib=/usr/local/lib --with-proj-share=/usr/local/share/pr
  installation of package ‘lwgeom’ had non-zero exit status

**Comment by rsbivand** [comment]
Which versions of GDAL, GEOS, and PROJ are installed? How were they installed? See older closed issues such as https://github.com/r-spatial/sf/issues/815, and follow the advice in the [README](https://github.com/r-spatial/sf) section on Multiple GDAL, GEOS and/or PROJ versions on your system and https://github.com/r-spatial/sf/issues/844 for the issue leading up to it.

**Comment by phanirg** [comment]
geos-3.6.2, proj-4.9.3, gdal-2.2.4.
Followed those issues, but still getting the same error.
For  RHEL7, there is no proper info. on this

**Comment by rsbivand** [comment]
For source installs, the burden is on you. You have not confirmed that you checked and that these versions are the only ones on your system. With duplicate GDAL, your symptoms are that you compiled sf against the one pointed to by gdal-config, but linked at run time against another.

**Comment by pat-s** [comment]
You may try [this solution](https://github.com/r-spatial/sf/issues/844#issuecomment-464183581) and see if it works for you.
