### ISSUE TITLE
How to use st_write when updating table

### ISSUE THREAD

**Issue by tblazina** [r-spatial/sf#950]
I am trying to update some columns in a database table however when I use `st_write()`, the table already exists and is linked to other via foreign keys to other tables so using `overwrite=True` fails. In effect i'm only updating a subset of columns in the table and when I use the `pgInsert` function from the `rpostgis`, I can pass the parameter `partial.match=TRUE` and it will simply update the matching columns in the dataframe I am trying to write. I haven't been able to find it but something like this possible? 

Otherwise I will simply use `as_Spatial(my.dataframe)` when I pass the dataframe into the `pgInsert` function, but I was wondering if this is possible with sf.  Thanks!

**Comment by edzer** [comment]
I don't think you can currently do this with `st_write`. @etiennebr ?

**Comment by etiennebr** [comment]
This is interesting, I didn't know about partial match in `rpostgis`. It think it would make for a great pull request! 

The only options we provide are `overwrite` or and `append`. You are probably aware of this, but I'll include a work around for the sake of completeness. It is possible to use `append=TRUE` and append a time stamp to track the latest geometry version in the relations (could create a view as well).

**Comment by tblazina** [comment]
Alright thanks a lot for the quick feedback! That would be a viable workaround but I think for now I'll just stick with using `rpostgis`. 

With regards to the PR, I'm actually in my first week of really using R and am coming from Python. I'll have a look at the `sf` and `rpostgis` code and see if I understand everything well enough to make a decent PR.
