### ISSUE TITLE
Writing to a GML causes loss of CRS info

### ISSUE THREAD

**Issue by GreatEmerald** [r-spatial/sf#958]
Any attempt to write a GML file results in the CRS getting lost. Basic example:

```r
library(sf)

nc = st_read(system.file("shape/nc.shp", package="sf"))
st_write(nc, "nc.gml")
ncg = st_read("nc.gml")
st_crs(ncg)
```

It looks like the GDAL GML driver expects the CRS to be specified in an additional field or so.

**Comment by edzer** [comment]
Thanks - I'm afraid there's little `sf` can do to change this. Have you tried all the options mentioned in relation to CRS in the gdal GML driver documentation?

**Comment by GreatEmerald** [comment]
Right, this also doesn't work when I use ogr2ogr, so that's definitely an issue in the library. I reported it there. And none of the creation options have anything to do with this issue, seemingly, because they are all just for modifying how the field should look like... But the field isn't there to begin with.

**Comment by edzer** [comment]
It's there in the gml file created: every feature has `<gml:MultiPolygon srsName="EPSG:4326">`.

**Comment by GreatEmerald** [comment]
Huh, so then it's a GDAL version issue as well, because on 2.1.3 it says just `<gml:MultiPolygon>`. But even so, the CRS is not supposed to be 4326, it's 4267. And the GML driver doesn't read it in.

**Comment by GreatEmerald** [comment]
Ah, maybe you tested with a different file then, because when I test with GDAL 2.3.2, it does indeed write the correct CRS, and I can read it with `options="FORCE_SRS_DETECTION=YES"`. It's quite unfortunate that it's not the default though, because you'd expect things you write into a file to be readable without loss of information by default...

**Comment by edzer** [comment]
It was correctly 4326, I'd changed it manually to see if that was the issue, and forgot about that. I can confirm setting the options detects the CRS.

**Comment by rsbivand** [comment]
Just for completeness, in **rgdal** and GDAL 2.4.0, using `setCPLConfigOption("FORCE_SRS_DETECTION", "YES")` has no effect. `rgdal::readOGR()` does not pass driver-specific options through.

The GML file contains `<gml:MultiPolygon srsName="EPSG:4267">` which is correct:

```
> proj4string(nc)
[1] "+proj=longlat +datum=NAD27 +no_defs +ellps=clrk66 +nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat"
```
(**sf** also assigns 4267, which is correct, and is also written to GML by `st_write()`: `<gml:MultiPolygon srsName="EPSG:4267">`).
