### ISSUE TITLE
writing sf object into spatial-sqlite with pool goes wrong

### ISSUE THREAD

**Issue by harryprince** [r-spatial/sf#959]
I am trying to use spatial-sqlite to store lots of .csv data into a single sqlite3 file with a spatial index to accelerate query speed.

the procedure like this,

```
library(dplyr)
library(pool)
library(sf)
```

```
sc <- pool::dbPool(RSQLite::SQLite(), dbname = "~/spatial.sqlite")

filePath = system.file("geojson/china.json",package = "leafletCN")

fence_df <- sf::st_read(filePath) %>% select(geometry)
sc %>% pool::dbWriteTable(name = "fence_tbl",value = fence_df)

```

running on .sqlite3, it return nothing.

```
sqlite> SELECT load_extension('mod_spatialite');
sqlite> select st_asText(geometry), st_asText(st_geomfromwkb(geometry)) from fence_tbl limit 1;
```

fence_tbl geometry column seems encode in wkb?

```
sqlite> select geometry from fence_tbl limit 1;
0103000020e61000000100000005000000f5dbd781734a5d4011018750a58e4340f5dbd781734a5d4018265305a38e43401ff46c567d4a5d40f44f70b1a28e43401ff46c567d4a5d40ed2aa4fca48e4340f5dbd781734a5d4011018750a58e4340
```

need help to read/write sf object correctly.

**Comment by edzer** [comment]
If you need help, provide at least a reproducible example that illustrates your problem.

**Comment by harryprince** [comment]
I assign .geojson by leafletCN package. now, it is a reproducible example.

**Comment by harryprince** [comment]
`mod_spatialite` is a spatial-sqlite module, in that,  which should be surely installed. if your os is ubuntu, it like this: `sudo apt-get install libsqlite3-mod-spatialite`

**Comment by edzer** [comment]
That is what I did, then in `sqlite3`, `SELECT load_extension('mod_spatialite');` did not work.
