### ISSUE TITLE
Clarify how to set a new bounding box in documentation of st_bbox

### ISSUE THREAD

**Issue by angela-li** [r-spatial/sf#960]
It would be useful to include a description of how to set a new bounding box in the documentation for st_bbox - how would you normally do this? Could we link to the function to do so in the documentation?

**Comment by edzer** [comment]
I don't think you can.

**Comment by tim-salabim** [comment]
This?
https://twitter.com/TimSalabim3/status/1063099774977667072?s=20

**Comment by angela-li** [comment]
Ah, ok that works! Seems like something I remember doing, but maybe that was in sp before. Is it something that makes sense to added to sf? Something like `st_bbox<-`?

**Comment by edzer** [comment]
`sp` had a `bbox<-`. `sf` keeps track of bounding boxes, so they should be OK. Why would you want to set it to another value?

**Comment by angela-li** [comment]
I think to make sure no features get cropped, which is what happens in base plotting when you're plotting something with a smaller bounding box before you plot something with a larger bounding box. 

Of course, you can just plot them in the other order to solve that issue, or use a different plotting package 😃 But it struck me that maybe you'd want the option of setting a new bounding box for the data with the smaller geographical extent...

**Comment by edzer** [comment]
If plotting is the issue, I would like to try to solve it there. Maybe we can add a bbox argument to plot that takes a bbox object and uses it to set xlim and ylim?

**Comment by rsbivand** [comment]
Wrt. BBOX, see also the discussion at the foot of: https://lists.osgeo.org/pipermail/gdal-dev/2019-January/049651.html.

**Comment by edzer** [comment]
I think that discussion refers to the BBOX that come with CRS, to point out where they are valid/useful. `sf` has no access to that, but it would be cool to have it, and do something with it.

**Comment by PatBall1** [comment]
> `sp` had a `bbox<-`. `sf` keeps track of bounding boxes, so they should be OK. Why would you want to set it to another value?

Is this true? For example, if you replace the coordinates of a sf polygon object, the 'bbox' field is not recalculated. e.g.:
`sf_poly[[1]][[1]][[1]] <- new_coords`
I'm having some trouble with this.

**Comment by edzer** [comment]
If you are comfortable doing that, you should also be comfortable using @tim-salabim 's suggestion to update the bounding box accordingly.

**Comment by PatBall1** [comment]
You're right, thanks. I should have been more thorough reading back.

**Comment by fabeit** [comment]
If I have a raster or shapefile and another shapefile with the same coordinate system but different bbox what is the best way to make the bbox match? For example I have found that xmin and xmax can be 0, 360 or -180,180.

I wouldn't want to use st_transform. Just st_bbox(sf)[1]='-180'? Isn't there a function that takes care of this automatically?

**Comment by yikeshu0611** [comment]
attr(sf_poly[[attr(sf_poly, "sf_column")]],'bbox') <- c(xmin=xmin,ymin=ymin,xmax=xmax,ymax=ymax)

**Comment by edzer** [comment]
> attr(sf_poly[[attr(sf_poly, "sf_column")]],'bbox') <- c(xmin=xmin,ymin=ymin,xmax=xmax,ymax=ymax)

After this some things might work while others won't, since they'd assume the bounding box has a class, a CRS, or even meaningful values:

```r
> st_bbox(c(xmin=1,ymin=1,xmax=2,ymax=2)) |> class()
[1] "bbox"
> st_bbox(c(xmin=1,ymin=1,xmax=2,ymax=2)) |> str()
 'bbox' Named num [1:4] 1 1 2 2
 - attr(*, "names")= chr [1:4] "xmin" "ymin" "xmax" "ymax"
 - attr(*, "crs")=List of 2
  ..$ input: chr NA
  ..$ wkt  : chr NA
  ..- attr(*, "class")= chr "crs"
```

**Comment by yikeshu0611** [comment]
> > attr(sf_poly[[attr(sf_poly, "sf_column")]],'bbox') <- c(xmin=xmin,ymin=ymin,xmax=xmax,ymax=ymax)
> 
> After this some things might work while others won't, since they'd assume the bounding box has a class, a CRS, or even meaningful values:
> 
> ```r
> > st_bbox(c(xmin=1,ymin=1,xmax=2,ymax=2)) |> class()
> [1] "bbox"
> > st_bbox(c(xmin=1,ymin=1,xmax=2,ymax=2)) |> str()
>  'bbox' Named num [1:4] 1 1 2 2
>  - attr(*, "names")= chr [1:4] "xmin" "ymin" "xmax" "ymax"
>  - attr(*, "crs")=List of 2
>   ..$ input: chr NA
>   ..$ wkt  : chr NA
>   ..- attr(*, "class")= chr "crs"
> ```

bb <- st_bbox(c(xmin=1,ymin=1,xmax=2,ymax=2))
bb[1] <- 0

this?

**Comment by BJ-Cochrane** [comment]
> This? https://twitter.com/TimSalabim3/status/1063099774977667072?s=20

Sorry, this tweet has since been deleted. What is the current solution to expanding a bounding box?

Thanks

Ben
