### ISSUE TITLE
Aspect ratio bug in st_viewport

### ISSUE THREAD

**Issue by davidorme** [r-spatial/sf#965]
Hi,

I've been using `st_viewport` to set up an inset map and there is problem with the code. Specifically,  `grid::convertUnit` has an argument `axisFrom` that sets whether the units are converted as if on the `x` or `y` axis. This isn't set in `st_viewport` so if the viewport is using something relative like `npc` then using `convertUnit` without setting `axisFrom` causes a mis-scaling:

```r
> library(grid)
> 
> # graphics window with unequal height and width
> quartz(height=6, width=4)
> pushViewport(viewport())
> vp = current.viewport()
> (wi = convertUnit(vp$width, 'inches'))
[1] 4inches
> # Correct - defaults to axisFrom = 'x'
> (vi = convertUnit(vp$height, 'inches'))
[1] 4inches
> # Nope - the npc size is the same (unit(1, 'npc')) but the size of the y-axis is different
```

The fix is easy. Either set `axisFrom` or use the explicit axis specific versions :
```r
> (vi = convertHeight(vp$height, 'inches', valueOnly=TRUE))
[1] 6
> (wi = convertWidth(vp$width, 'inches', valueOnly=TRUE))
[1] 4
```

Cheers,
David

**Comment by edzer** [comment]
Thanks! 

Also pinging @thk686 - this code came originally from [here](https://github.com/thk686/rgdal2/blob/master/R/graphics.R#L267-L268).

**Comment by davidorme** [comment]
As a side note, the `valueOnly=TRUE` makes the `unclass(sz[2]) / unclass(sz[1])` in `current.viewport.aspect` redundant.

**Comment by edzer** [comment]
Thanks!
