### ISSUE TITLE
Using reticulate to interface sf and shapely

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#968]
I can use WKT to move a shapely geometry column to sf:

```
library(sf)
nc_file <- system.file("shape/nc.shp", package="sf")
library(reticulate)
use_python(python='/usr/bin/python3')
py_config()
pkgr <- import("pkg_resources")
gpd <- import("geopandas")
pkgr$get_distribution("geopandas")$version
nc_gpd <- gpd$read_file(nc_file)
shapely <- import("shapely")
pkgr$get_distribution("shapely")$version
oo <- st_as_sf(data.frame(geom=unlist(lapply(nc_gpd$geometry, shapely$wkt$dumps))), wkt=1)
st_is_valid(oo)
table(sapply(oo$geom, function(x) class(x)[2]))
plot(oo, col="transparent")
```

Has anyone looked at WKB? Or the round trip for either? Here I'm going with Python 3. Motivation: among other things GIS/R interfaces, where several GIS use Python and GRASS is actively migrating to Python 3. Passing vector WKT/WKB would make temporary files less important.

**Comment by etiennebr** [comment]
That's indeed interesting! I haven't worked with reticulate that much, but I believe it is similar to what we do for databases.
https://github.com/r-spatial/sf/blob/c824c88c86a6786c517dc817b7e025151cdcadcf/R/db.R#L153

**Comment by rsbivand** [comment]
Thanks! So far I feel that **reticulate** is treating the geopandas object as a pandas object and so attributes needed by `shapely.wkb`  are not being communicated:

```
> ooo <- shapely$wkb$dumps(nc_gpd)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'DataFrame' object has no attribute '_geom'

Detailed traceback: 
  File "/usr/local/lib64/python3.7/site-packages/shapely/wkb.py", line 32, in dumps
    return writer.write(ob)
  File "/usr/local/lib64/python3.7/site-packages/shapely/geos.py", line 485, in write
    if geom is None or geom._geom is None:
  File "/usr/local/lib64/python3.7/site-packages/pandas/core/generic.py", line 5057, in __getattr__
    return object.__getattribute__(self, name)
> class(nc_gpd)
[1] "data.frame"
> class(nc_gpd$geometry)
[1] "list"
```

**Comment by rsbivand** [comment]
The problem for now with `geom <- st_as_sfc(sf:::as_wkb(ooo), EWKB=FALSE/TRUE)` is in getting `sf:::as_wkb(ooo)` to be `"raw"`. I've linked this to an aligned **reticulate** issue.

**Comment by rsbivand** [comment]
Progress on parallel thread on **reticulate** issue https://github.com/rstudio/reticulate/issues/338

**Comment by edzer** [comment]
Closing here, or is there some activity?

**Comment by rsbivand** [comment]
OK, some on the reticulate thread
