### ISSUE TITLE
Doc - self-interecting LineStrings should be valid

### ISSUE THREAD

**Issue by dr-jts** [r-spatial/sf#983]
It looks like the doc says self-intersecting LineStrings are invalid [1].  In fact they are valid according to the OGC SFS, so perhaps the docs or the code is wrong?

https://github.com/r-spatial/sf/blob/40345f27fe488f0aa728165cf222a09a4b7ba744/vignettes/sf1.Rmd#L767

**Comment by edzer** [comment]
Thanks for noting!
