### ISSUE TITLE
invalid geometry creates 'scary' error message

### ISSUE THREAD

**Issue by GreenStat** [r-spatial/sf#987]
Hi,

I stumbled on this non- informative error message (again):

```r
# note ls1 is 'invalid'
ls1 <- st_linestring(rbind(c(0,0)))
ls2 <- st_linestring(rbind(c(0,0),c(1,1)))
ls3 <- st_linestring(rbind(c(0,0),c(1,1),c(2,1)))

# create geometry
(sfc <- st_sfc(ls1,ls2,ls3))

# create sfg
x = st_sf(id=1:length(sfc), geometry=sfc)

 x %>% st_difference()
#Error in CPL_nary_difference(x) : 
#  Evaluation error: IllegalArgumentException: point array must contain 0 or >1 elements.

This is why
x %>% st_is_valid()
#[1]   NA TRUE TRUE
```
Pretty scary and non-informative, this error is generated for all geometry operations.

The solution is simple, filter out the invalid geometries and continue, but is it possible to generate more informative message for these cases ?

Greetings Peter

**Comment by edzer** [comment]
It is trivial to have `st_linestring()` give a warning or error, but I guess that was not your use case. Otherwise this is hard: the message is emitted by the GEOS library, out of `sf`'s reach.

**Comment by GreenStat** [comment]
Ah I see, no easy solution unfortunately. 
Thanks for now.
