### ISSUE TITLE
Consider moving st_makevalid from lwgeom to sf

### ISSUE THREAD

**Issue by dbaston** [r-spatial/sf#989]
The code backing the PostGIS `ST_MakeValid` function was [recently](https://github.com/libgeos/geos/commit/e04ba73ca7f2a033a1867251c5d5fff46491cfc7) moved into GEOS. It could now be put in the `sf` package instead of `lwgeom`, if desired.

**Comment by edzer** [comment]
Is that already in a released GEOS version, or is it clear in which version it will be released?

**Comment by dbaston** [comment]
It would be available in the next version, which would be 3.8. No schedule around that release, as far as I know.

**Comment by jeannesorin** [comment]
Is there any progress on this ? 
Any advice to handle cases where st_makevalid takes too long?

**Comment by dbaston** [comment]
@jeannesorin can you share some more information (data/code) about your case where `st_makevalid` takes too long?

**Comment by dbaston** [comment]
3.8 will probably be out within a week or two.

**Comment by edzer** [comment]
I'd welcome a PR! I'm busy refactoring package lwgeom, taking liblwgeom from PG 3.0beta1, anticipating more debris of recent and upcoming PROJ installations.

**Comment by dbaston** [comment]
Not sure what that looks like, though. Do you pull it out of `lwgeom`, or somehow conditionally load it in `lwgeom` based on whether it's provided by `sf`? Is the complexity is worth it?

**Comment by edzer** [comment]
R package lwgeom contains an almost complete copy of the liblwgeom stuff in postgis; I'm essentially redoing this. Sounds as ugly as it is.

**Comment by edzer** [comment]
lwgeom submitted to CRAN.
