### ISSUE TITLE
Is there a way to parameterise the <Style></Style> for kml in st_write?

### ISSUE THREAD

**Issue by aazaff** [r-spatial/sf#991]
The `st_write( )` documentation notes that there are driver specific layer_creation options. Is there a way to use this to attach a style to each `<Placemark>` tag in an output KML?

For example, let's say that I have the following output from `sf::st_write("my.kml")`

````KML
<Placemark>
	<name>First Feature</name>
	<description>First Description</description>
	<Style><LineStyle><color>ff0000ff</color></LineStyle><PolyStyle><fill>0</fill></PolyStyle></Style>
	<ExtendedData>
            <SimpleData name="8bitcolor">ffd100ab</SimpleData>
        </ExtendedData>
      <MultiGeometry><Polygon><outerBoundaryIs><LinearRing>
          <coordinates>0,0 1,1 2,2 3,3 0,0</coordinates>
      </LinearRing></outerBoundaryIs></Polygon></MultiGeometry>
</Placemark>
````

What I am looking to do is find a way to pass the `"8bitcolor"` attribute to the `<Style></Style>`. The style file would then look like...

````KML
<Style><LineStyle><color>ff0000ff</color></LineStyle><PolyStyle>ffd100ab<color></color><fill>1</fill></PolyStyle></Style>
````

Is this possible by passing some parameters to `st_write()`?

**Comment by edzer** [comment]
Only if it's described in the GDAL [driver specs](https://www.gdal.org/drv_kml.html) and configurable through these options; `st_write` does nothing KML-specific.

**Comment by aazaff** [comment]
This can supposedly be done if the latest `libkml` driver subversion is installed.

`ogr2ogr` will automatically check for a field named [OGR_STYLE](https://www.gdal.org/ogr_feature_style.html) and include styling as appropriate. Presumably this will also happen by default whenever `sf` invokes `ogr2ogr` without the need for passing any parameters to `st_write()`.

I will test assumption and then close this issue if there is nothing that actually needs to be changed in `sf`.

**Comment by aazaff** [comment]
This does work as expected when `ogr2ogr` is invoked by `sf::st_write()` if the libkml driver is installed.

**Comment by Nova-Scotia** [comment]
Can anyone in this thread give an example of how you would use this functionality to style a polygon fill and line color, with transparency?

**Comment by aazaff** [comment]
@Nova-Scotia, the ogr_style supports [8-digit hex format](https://css-tricks.com/8-digit-hex-codes/), which allows you to add a transparency term to a normal 6-digit color code. 

````
# Putting the following value in a cell under the OGR_STYLE field of your attribute table will
# make that particular feature be a blue polygon with 50% transparency
# and have a red outline 1 pixel thick.
BRUSH(fc:#0000FF80); PEN(c:#FF0000,w:1px)
````

See the link I put earlier in the thread for the full documentation on the OGR_STYLE syntax.

**Comment by Nova-Scotia** [comment]
I tried the following and it did not work - the output was still a transparent polygon with red lines:

```
library(sf)
library(dplyr)


# dataset included with sf package
county_polygons <- st_read(system.file("shape/nc.shp", package="sf")) %>% 
  st_transform(4326) %>% 
  mutate(OGR_STYLE = "BRUSH(fc:#0000FF80); PEN(c:#FF0000,w:1px)") %>% 
  select(Description = NAME,
         OGR_STYLE) 

st_write(county_polygons, "test1.kml", driver = "kml")
```

**Comment by aazaff** [comment]
Make sure that you have libkml driver installed and specifically declare it with `driver = "libkml"` in `sf::st_write`

**Comment by Nova-Scotia** [comment]
Looks like I don't have that driver (I tried `sf::st_drivers()`) and for someone without a lot of programming know-how, the directions (for Windows) to install are a bit cryptic @ https://github.com/google/libkml/wiki/Building-and-installing-libkml. If you know of another resource to help get this installed, I'd be interested!

**Comment by aazaff** [comment]
Yeah, libkml is essential to making it work. You're not wrong to suspect that it is hard to install. I've only ever gotten it to work on one of my machines at work.

If you're a Windows user (I'm Mac/Linux), you might putz around [OSGEO](https://www.osgeo.org/) and see if they have a driver bundle that includes it. Sorry I can't be more help.

**Comment by shadowjohn** [comment]
> The `st_write( )` documentation notes that there are driver specific layer_creation options. Is there a way to use this to attach a style to each `<Placemark>` tag in an output KML?
> 
> For example, let's say that I have the following output from `sf::st_write("my.kml")`
> 
> ```
> <Placemark>
> 	<name>First Feature</name>
> 	<description>First Description</description>
> 	<Style><LineStyle><color>ff0000ff</color></LineStyle><PolyStyle><fill>0</fill></PolyStyle></Style>
> 	<ExtendedData>
>             <SimpleData name="8bitcolor">ffd100ab</SimpleData>
>         </ExtendedData>
>       <MultiGeometry><Polygon><outerBoundaryIs><LinearRing>
>           <coordinates>0,0 1,1 2,2 3,3 0,0</coordinates>
>       </LinearRing></outerBoundaryIs></Polygon></MultiGeometry>
> </Placemark>
> ```
> 
> What I am looking to do is find a way to pass the `"8bitcolor"` attribute to the `<Style></Style>`. The style file would then look like...
> 
> ```
> <Style><LineStyle><color>ff0000ff</color></LineStyle><PolyStyle>ffd100ab<color></color><fill>1</fill></PolyStyle></Style>
> ```
> 
> Is this possible by passing some parameters to `st_write()`?

ffd100ab wrong place, Should be...
<Style><LineStyle><color>ff0000ff</color></LineStyle><PolyStyle><color>ffd100ab</color><fill>1</fill></PolyStyle></Style>

**Comment by edzer** [comment]
You'd have to consult the kml driver documentation: https://gdal.org/drivers/vector/kml.html

**Comment by aazaff** [comment]
You would have to check the `libkml` driver documentation (https://github.com/libkml/libkml), not the normal `kml` driver linked above. Be warned, `libkml` has to be installed separately from `sf` whereas the normal `kml` driver is bundled with `sf`. Also, note that `libkml` is abandonware.

Realistically speaking, the best way to do complex KML styling in R would be to build it by hand. You might find `plotKML` package useful for this https://github.com/Envirometrix/plotKML.
