### ISSUE TITLE
rtools40 GEOS/GDAL?

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/sf#997]
https://github.com/r-windows/rtools-packages does not seem at present to offer GDAL or GEOS. Do we know any more about this before alerting the repo maintainer? I guess that we need to advance this before the next release of R in april (?).

**Comment by jeroen** [comment]
The current rwinlib solution will keep working with the new toolchain. There is nothing you have to do.

If/when cran decides to start using rtools40, I will start porting more packages to the new rtools40 build system and we can eventually flip over rgdal/sf to the new system. But for now there is nothing we need to do, the packages will work on R 3.6 regardless of whether CRAN uses the current or new toolchain.

**Comment by edzer** [comment]
Make sense - thanks!

**Comment by jeroen** [comment]
There is one small tweak I'd like to make to make the future migration easier, I'll send a PR for that.

**Comment by edzer** [comment]
Do the r-devel-windows-ix86+x86_64-gcc8	builds [here](https://cran.r-project.org/web/checks/check_results_sf.html) indicate success with the new toolchain?

**Comment by rsbivand** [comment]
Looks like `Linking to GEOS 3.7.1, GDAL 2.4.2, PROJ 5.2.0`, I think, that is safe for now.

**Comment by jeroen** [comment]
Indeed, these are still built with the current binaries from rwinlib (but with gcc-8). 

Once R 4.0 is released, we can phase out rwinlib and maintain gdal as a pacman package.

**Comment by edzer** [comment]
OK, thanks!
