### ISSUE TITLE
Wrong result for st_within with two single objects

### ISSUE THREAD

**Issue by barryrowlingson** [r-spatial/sf#999]
Am getting a wrong result when relating two single geometries with "within" or "contains". First create some points:
```
pt = data.frame(x=1:2, y=1:2,a=letters[1:2])
pt = st_as_sf(pt, coords=c("x","y"))
```
then create small buffer polygons that only cover each of the points:
```
bf =st_buffer(pt, dist=0.3)
```

are the points within the polygons?

```
st_within(pt,bf, sparse=FALSE)
##      [,1]  [,2]
## [1,]  TRUE FALSE
## [2,] FALSE  TRUE
```

yes. point 1 is in buffer 1 and point 2 is in buffer 2. Good, that's what I expected.

But try with just point 1 and buffer 1:

```
st_within(pt[1,],bf[1,], sparse=FALSE)
##      [,1]
## [1,] FALSE
```
which seems wrong.

If either element is length two it seems to be correct:

```
> st_within(pt[1,],bf, sparse=FALSE)
     [,1]  [,2]
[1,] TRUE FALSE
> st_within(pt,bf[1,], sparse=FALSE)
      [,1]
[1,]  TRUE
[2,] FALSE
> 
```

The problem also manifests with `sparse=TRUE` (empty elements result).

Have also tried `drop=FALSE`:

```
> st_within(pt[1,,drop=FALSE],bf[1,,drop=FALSE], sparse=FALSE)
      [,1]
[1,] FALSE
```

version details:

```
> packageVersion("sf")
[1] ‘0.7.3’
> library(sf)
Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3
```

**Comment by edzer** [comment]
Thanks, that is a regression introduced in https://github.com/r-spatial/sf/commit/b8046c5f9cd7d5b219b107dcc4f3beb584ec130e (see also #855). The quick fix for now would be to set `prepared = FALSE`.
